### ISSUE TITLE
wrong version in dosbox-x-macosx-x64-20190202110559

### ISSUE THREAD

**Issue by suschizu** [joncampbell123/dosbox-x#1011]
the bundle version and short-version string in the info.plist (mac osx) are 0.48.2 instead of 0.82.15.
<img width="225" alt="screenshot 2019-02-10 at 18 00 11" src="https://user-images.githubusercontent.com/16004333/52536661-eb09b080-2d5d-11e9-96c0-1e67f73be6a1.png">
<img width="712" alt="screenshot 2019-02-10 at 18 00 50" src="https://user-images.githubusercontent.com/16004333/52536662-ed6c0a80-2d5d-11e9-9467-2ffa2aba0177.png">

**Comment by joncampbell123** [comment]
The latest commit generates the plist with automake to ensure that field contains the correct version number.

**Comment by suschizu** [comment]
awesome - great thanks 👍
