### ISSUE TITLE
--disable-x11 fail to compile in sdlmain_linux.cpp (Xrandr.h)

### ISSUE THREAD

**Issue by CarolinaJones** [joncampbell123/dosbox-x#1013]
Hello, Jon ..

While compiling with --disable-x11, I was unable to compile sdlmain_linux.cpp. I noted that it's referencing X11 extensions at line 415:-

/* Retrieve screen size/dimensions/DPI using XRandR */
static bool Linux_TryXRandrGetDPI(ScreenSizeInfo &info,Display *display,Window window) {
    bool result = false;

I can of course resolve by putting in:-
#include <X11/extensions/Xrandr.h>

..but I know that's not the elegant fix! :)

Kind regards & thanks
Caroline

**Comment by joncampbell123** [comment]
Should be fixed in the latest commit.

**Comment by CarolinaJones** [comment]
That worked!
All good, thanks.
