### ISSUE TITLE
X11 dependency not checked when configuring

### ISSUE THREAD

**Issue by micro500** [joncampbell123/dosbox-x#1014]
**Describe the bug**
On a clean install of Ubuntu 18.04 I installed enough dependencies for ./configure to pass, but during compilation I got an error that X11 libraries were not found. I think there should be a check for X11 when configuring.

**To Reproduce**
1. Clean install of Ubuntu 18.04
2. `sudo apt-get install git automake build-essential libsdl2-dev libavformat-* libswscale-* libavcodec-*`
3. Clone the dosbox-x repo
4. `./autogen`
5. `./configure --enable-sdl2`
6. Configure will pass
7. `make`
8. Build will fail

**Expected behavior**
I would expect the configure step to fail and tell me that X11 dependencies are not installed.

**Environment:**
 - Clean install of Ubuntu 18.04

**Additional context:**
Running `sudo apt-get install xorg-dev` was enough to fix the issue and finish the build.

**Comment by joncampbell123** [comment]
If you give --disable-x11 does it compile?

**Comment by micro500** [comment]
Yes, `--disable-x11` allowed me to compile successfully.

The error without that flag was:
```
sdlmain_linux.cpp:14:10: fatal error: X11/extensions/XKBrules.h: No such file or directory
 #include <X11/extensions/XKBrules.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Thanks to @clementgallet I found that `libxkbfile-dev` was the only missing package I needed.

**Comment by joncampbell123** [comment]
Try the latest commit, it should fix the issue.

**Comment by micro500** [comment]
No change on 192ca5126ec31a059578cdb53c37c9eccd20130d

**Comment by joncampbell123** [comment]
Please run ./autogen.sh and then the build script again.

Part of the change involves configure.ac.

**Comment by micro500** [comment]
I did that test on a fresh install, so I followed all the steps again.

**Comment by joncampbell123** [comment]
is C_X11 set in the config.h file after configure is run?

**Comment by micro500** [comment]
Yes:
`#define C_X11 1`

**Comment by joncampbell123** [comment]
So then it saw the X11 headers. Can you confirm that from config.log?

**Comment by joncampbell123** [comment]
The only way C_X11 will be set without the headers is if for any reason on your system the configure script was not regenerated from configure.ac.

In configure.ac there should be at line 880:

    if test x$have_x11_h = xyes ; then
        AH_TEMPLATE(C_X11,[define to 1 to enable X11 support])
        AC_DEFINE(C_X11,1)
    fi

**Comment by micro500** [comment]
All X11 related stuff in config.log:
```
...
configure:8434: checking for main in -lX11
configure:8453: gcc -o conftest -g -std=gnu11  -O2 -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include/SDL  -Wno-extended-offsetof   -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wconversion-null   -pedantic   -Wextra   -Wall   -I/usr/include/SDL2 -D_REENTRANT -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include/SDL  -L/home/test/dosbox-x/vs2015/sdlnet/linux-host/lib conftest.c -lX11  -lasound -lm -ldl -lpthread -lSDL2 >&5
cc1: warning: command line option '-Wconversion-null' is valid for C++/ObjC++ but not for C
cc1: warning: unrecognized command line option '-Wno-address-of-packed-member'
cc1: warning: unrecognized command line option '-Wno-int-to-void-pointer-cast'
cc1: warning: unrecognized command line option '-Wno-extended-offsetof'
configure:8453: $? = 0
configure:8462: result: yes
...
configure:8512: checking X11/XKBlib.h usability
configure:8512: gcc -c -g -std=gnu11  -O2 -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include/SDL  -Wno-extended-offsetof   -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wconversion-null   -pedantic   -Wextra   -Wall   -I/usr/include/SDL2 -D_REENTRANT -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include/SDL conftest.c >&5
cc1: warning: command line option '-Wconversion-null' is valid for C++/ObjC++ but not for C
cc1: warning: unrecognized command line option '-Wno-address-of-packed-member'
cc1: warning: unrecognized command line option '-Wno-int-to-void-pointer-cast'
cc1: warning: unrecognized command line option '-Wno-extended-offsetof'
configure:8512: $? = 0
configure:8512: result: yes
configure:8512: checking X11/XKBlib.h presence
configure:8512: gcc -E  -Wno-extended-offsetof   -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wconversion-null   -pedantic   -Wextra   -Wall   -I/usr/include/SDL2 -D_REENTRANT -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include/SDL conftest.c
cc1: warning: command line option '-Wconversion-null' is valid for C++/ObjC++ but not for C
cc1: warning: unrecognized command line option '-Wno-address-of-packed-member'
cc1: warning: unrecognized command line option '-Wno-int-to-void-pointer-cast'
cc1: warning: unrecognized command line option '-Wno-extended-offsetof'
configure:8512: $? = 0
configure:8512: result: yes
configure:8512: checking for X11/XKBlib.h
configure:8512: result: yes
...
ac_cv_header_X11_XKBlib_h=yes
...
ac_cv_lib_X11_main=yes
...
LIBS='-lasound -lm -ldl -lpthread -lSDL2 -lz -lX11 -lxkbfile -lXrandr'
...
#define C_X11_XKB 1
#define C_X11_XRANDR 1
#define C_X11 1
```

I do have that code in configure.ac. And this test was done after I did a fresh install of Ubuntu into a new VM (not the same as the initial report), so I definitely did the `./autogen` with your changes to the configure system.

**Comment by joncampbell123** [comment]
I see. So the X11 headers are installed on your system then.

Are the X11 XKB headers installed? DOSBox-X uses XKB to work out the keyboard scancode maps on the system.

**Comment by micro500** [comment]
How would I check that?

**Comment by joncampbell123** [comment]
Apparently X11 and X11 XKB is there, but the compiler error suggests that there is no XKBrules.h on your system.

At least on my system the X11 headers can be found in /usr/include/X11 and the extensions in /usr/include/X11/extensions

**Comment by micro500** [comment]
For files with XKB in the name, looks like I have:
/usr/include/X11/XKBlib.h
/usr/include/X11/extensions/XKBgeom.h
/usr/include/X11/extensions/XKB.h
/usr/include/X11/extensions/XKBproto.h
/usr/include/X11/extensions/XKBsrv.h
/usr/include/X11/extensions/XKBstr.h

**Comment by joncampbell123** [comment]
Can you "grep" to see which one defines (with typedef) the _XkbRF_Rule struct?

DOSBox-X needs those typedefs in order to query the keyboard layout.

**Comment by micro500** [comment]
None on this install (missing XKBrules.h). I checked on a different install and found that struct definition in XKBrules.h

**Comment by joncampbell123** [comment]
DOSBox-X requires XKBrules.h and XKBlib.h. The latest commit fixes the code so that if either header is not there at command line, the keyboard layout detection code that uses it is compiled out instead of erring out at compile time.

**Comment by micro500** [comment]
I pulled your changes and re-ran autogen and configure. I now see this in the configure output:
```
checking X11/extensions/XKBrules.h usability... no
checking X11/extensions/XKBrules.h presence... no
checking for X11/extensions/XKBrules.h... no
```

However the build now fails in a different spot:
```
sdlmain_linux.cpp: In function ‘unsigned int Linux_GetKeyboardLayout()’:
sdlmain_linux.cpp:226:13: error: ‘XkbRF_VarDefsRec’ was not declared in this scope
             XkbRF_VarDefsRec vd = {0};
             ^~~~~~~~~~~~~~~~
sdlmain_linux.cpp:226:13: note: suggested alternative: ‘XkbChangesRec’
             XkbRF_VarDefsRec vd = {0};
             ^~~~~~~~~~~~~~~~
             XkbChangesRec
sdlmain_linux.cpp:237:64: error: ‘vd’ was not declared in this scope
             XkbRF_GetNamesProp(wminfo.info.x11.display, NULL, &vd);
                                                                ^~
sdlmain_linux.cpp:237:13: error: ‘XkbRF_GetNamesProp’ was not declared in this scope
             XkbRF_GetNamesProp(wminfo.info.x11.display, NULL, &vd);
             ^~~~~~~~~~~~~~~~~~
sdlmain_linux.cpp:237:13: note: suggested alternative: ‘XkbGetNames’
             XkbRF_GetNamesProp(wminfo.info.x11.display, NULL, &vd);
             ^~~~~~~~~~~~~~~~~~
             XkbGetNames
```

**Comment by joncampbell123** [comment]
Whoops.

The latest commit applies the same to the SDL2 case.

**Comment by micro500** [comment]
Another failure right at the end of building:
```
g++  -g -std=gnu++11  -O2 -msse  -Wall   -Wextra   -pedantic   -Wconversion-null   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast   -Wno-extended-offsetof  -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/test/dosbox-x/vs2015/sdlnet/linux-host/include/SDL   -L/home/test/dosbox-x/vs2015/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a output/liboutput.a aviwriter/libaviwriter.a  xBRZ/libxbrz.a mt32/libmt32.a -lasound -lm -ldl -lpthread -lSDL2 -lz -lX11 -lxkbfile -lXrandr
/usr/bin/ld: cannot find -lxkbfile
```

**Comment by joncampbell123** [comment]
Wait....

    /usr/bin/ld: cannot find -lxkbfile

    /usr/include/X11/XKBlib.h

    #define C_X11_XKB 1
    #define C_X11_XRANDR 1
    #define C_X11 1

So XKB is there but not XKBfile?

**Comment by micro500** [comment]
I guess not.

1f0b6d78dc4d3a1606c3aa34f70f6f6cc8b6ea1e now successfully builds for me.

**Comment by joncampbell123** [comment]
Now that DOSBox-X checks the X11 dependencies, I think it should be OK to close this issue.
