### ISSUE TITLE
Windows 3.1 hangs suddenly. Nothing happens other then the cursor changing to an hourglass after a few seconds.

### ISSUE THREAD

**Issue by IoIxDButStronger** [joncampbell123/dosbox-x#1017]
I recently got my Raspberry Pi after about two weeks of it sitting at another building where I was working on a case for it on and off. I got it back home this afternoon - keep in mind, I haven't booted or changed it in a week - and Windows 3.1 suddenly doesn't launch, even after I updated to the latest commit. Nothing happens.

DOSBox-X logs: https://pastebin.com/raw/N5q6RBDq

dosbox.conf (only thing that was changed was the 'cycles" setting, which i set to max to try and fix the problem. Nothing changed.): https://pastebin.com/KNi1R7yU

Version is 0.82.16, OS is WfW 3.11

**Comment by joncampbell123** [comment]
What does Windows 3.1 do instead?

**Comment by TheDedede** [comment]
As I said before: nothing. Instead of booting up after the Windows logo, it's just a black screen with the hourglass cursor sitting there infinitely?

**Comment by joncampbell123** [comment]
Are you using the normal core with prefetch enabled?

I don't exactly know why but I found on my end that if you use core=normal and cputype=486_prefetch Windows 3.1 behaves just about the way you describe.

**Comment by IoIxDButStronger** [comment]
Both core and cputype are set to "auto"

**Comment by joncampbell123** [comment]
Try core=normal and cputype=pentium

**Comment by IoIxDButStronger** [comment]
Same reseults and log as last time. i also set "cycles" to auto and nothing changed.

**Comment by IoIxDButStronger** [comment]
Problem was related to the OS itself, something must've gotten corrupted? Reinstall helped.
