### ISSUE TITLE
PC-98 Tokyo Twilight Busters: Blinking command cursor not being hidden

### ISSUE THREAD

**Issue by rougelite** [joncampbell123/dosbox-x#1020]
When the game starts, the blinking command line cursor square remains in the lower left of the screen.
As far as I can tell, this behavior is unique to Tokyo Twilight Busters and does not happen on other games by the same company or any other PC98 games I tested. 

The related issues tab suggests that Tokyo Twilight Busters was used to test .nhd mounting and didn't encounter any issues so it may only be an issue with this particular installation of the game, however when running the game on Neko Project II the cursor is not visible.

![guest os_000](https://user-images.githubusercontent.com/44570288/53376832-4c687c80-3925-11e9-9740-5020542ef594.png)

**Comment by joncampbell123** [comment]
This isn't new, there seems to be a consistent issue where the game fails to turn off the cursor on the text layer.

I'm not sure what BIOS interrupt or DOS call the games attempt to use to turn off the cursor, or if hiding the cursor is part of some other BIOS call that does it as part of it's function.

**Comment by joncampbell123** [comment]
For example, once when developing a DOSLIB test program on real PC-98 hardware I found a few BIOS calls that will hide the cursor automatically for some reason. One of them (if I recall correctly) was the BIOS call to select between 20-line or 25-line text mode.

**Comment by joncampbell123** [comment]
Please try the latest commit.
