### ISSUE TITLE
PC-98: Photo Genic hangs playing any PCM sound since 0.82.15

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#1022]
**Describe the bug**
Sunsoft's Photo Genic is a game which had working INT 33h mouse support before 8255 mouse support was added. 
Since 0.82.15, The game hangs trying to play any sound effect with DOSBox-X default setting. I didn't touch the game since 0.82.4 and only found this problem checking older archived files.

**To Reproduce**
1. Run pg.bat to start the game
2. Start a new game using this option.
![image](https://user-images.githubusercontent.com/37106774/53733323-a46e2880-3ebb-11e9-9a2c-5e84cc6270ad.png)

**Expected behavior**
The game plays a PCM chime (probably using the SSG channel) and the opening sequence will be shown.

**Environment (please complete the following information):**
 - DOSBox-X 0.82.15
 - Used configuration, e.g. ```dosbox.conf```
```
[dosbox]
machine=pc98
pc-98 start gdc at 5mhz=false

```

**Comment by joncampbell123** [comment]
It may have worked back when the default FM board IRQ was IRQ 3 or 5, before the default became IRQ 12.

**Comment by joncampbell123** [comment]
Hold on... it hangs in this loop.

I'll need to look up what I/O port 75h is supposed to return on read.

    1A45:00003BD9 EB00                jmp  short 00003BDB ($+0)   (down)
    1A45:00003BDB E475                in   al,75
    1A45:00003BDD 3C10                cmp  al,10
    1A45:00003BDF 73F8                jnc  00003BD9 ($-8)         (up)

**Comment by joncampbell123** [comment]
It writes 94h to port 77h and then DFh to port 75h.

That means timer 2, set to read/write only the LSB of the timer, set to mode 2 (periodic pulse).

It only hangs because the counter value isn't counting down as it should.

**Comment by joncampbell123** [comment]
PIT Timer 2 is not gated on in PC-98 mode because on a real PC-9821 laptop I didn't see the timer cycling at all.

According to the "undocumented 9801/9821 collection" there's an undocumented bit 6 at port 434h that is connected to the clock gate input of PIT Timer 2 which might explain that.

I'll enable that clock gate in DOSBox-X by default until 434h bit 6 is implemented.

**Comment by joncampbell123** [comment]
Try the latest commit. RS-232C PIT Timer 2 clock gate on by default to support the game with reminders to myself later to examine where the BIOS switches on/off the PIT 2 gate and how this probably relates to a time REMSRV.EXE (from DOSLIB) was unable to get RS-232C communications working.

![guest os_000](https://user-images.githubusercontent.com/6245486/55491572-914d9600-55ea-11e9-9588-40d62589d23b.png)

**Comment by joncampbell123** [comment]
A game that uses the RS-232C baud rate clock (PIT 2) for delay loops isn't entirely unusual by the way.

I know of a few demoscene executables for the IBM PC/AT that use the PC speaker (PIT 2) for delay loops. The PC speaker output is gated off from the speaker while doing this, of course.

**Comment by joncampbell123** [comment]
Update: 434h does not work as documented on a PC9821Lt2. 8254.EXE from DOSLIB shows PIT 2 is not cycling. Perhaps the enable bit is elsewhere.
