### ISSUE TITLE
Enhancements for CGA Emulation

### ISSUE THREAD

**Issue by frank-deng** [joncampbell123/dosbox-x#1024]
* Is it appropriate to make even scanlines dimmer for CGA modes like cga, cga_rgb, cga_mono, so as to resemble the behaviour of the old CGA/EGA monochrome or color monitors?
* Color switching for cga_mono seems to have missing under SDL1.
* For cga_mono or some other monochrome displays like mda, hercules, is it possible to specify the color in the configuration file (green/amber/white) apart from switching it using keyboard?
* Is it appropriate to add grayscale effect for other displays like EGA, VGA, or even newer cards like svga_s3? Maybe VGA-supported monochrome/grayscale monitors could be used for budget-saving purpose in some cases.

**Comment by joncampbell123** [comment]
There's already a scaler that renders to every other scanline, if you'd like that.

However a scaler that acts similar but with a dimmer second line would be more appropriate, I agree.

I'm not sure if there's a dosbox.conf option for it, but there is monochrome display color selection tied to a mapper shortcut.

You want a 'machine=vga_mono?' I don't really see the point for S3 emulation to do it. I don't think monochrome VGA matter beyond the original IBM PS/2 line and it's VGA implementation.

This would affect VGA rendering and the INT 10h emulation (concerning the BIOS call to read back DCC monitor/card combination).

**Comment by joncampbell123** [comment]
If I recall, the monochrome VGA monitor uses only one of the R, G, or B pins and relies on the BIOS to do the weighted RGB -> grayscale conversion.

I'm guessing its the G (green) pin, can anyone with a mono VGA monitor confirm?

**Comment by joncampbell123** [comment]
I do know from actual hardware experience the Tseng ET3000 is a bit overzealous about monitor detection to the point that it will mistake most LCD monitors as a monochrome VGA monitor.

**Comment by frank-deng** [comment]
I've tried scan2x and tv2x scalars, and they only work for 320x200 graphics mode. CGA's 640x200 graphics mode and text mode not work.

**Comment by joncampbell123** [comment]
What happens if you force the scaler?

**Comment by frank-deng** [comment]
I've searched the code of `src/hardware/vga_draw.cpp`, and I haven't found how CGA text mode and 640x200 graphics mode rendered yet.
What should I do to render even lines dimmer or skip rendering even scan lines?

**Comment by frank-deng** [comment]
I have made the following changes on `src/gui/render_templates.h` (marked in red circle) to achieve the scanline effect, so as to resemble what an early 1990's monochrome CGA monitor may behave like.
![dosbox-x-scaler-changes](https://user-images.githubusercontent.com/8265668/55330054-aa5b2780-54c2-11e9-9fb0-249d3e0b4df3.png)

However, since it modifies the normal scaler for 640x200 resolution, other scenarios with 640x200 resolution without scanline effect will display abnormally, e.g. displaying CGA 640x200 mode using VGA hardware.
I'll try to add a new scaler called `cga_scanline` which is dedicated for producing scanline effect for CGA text mode and 640x200 mode when machine type is set to `cga_mono`, `cga_rgb`, `cga`, as well as some other RGBI-based CGA modes.

**Comment by frank-deng** [comment]
Maybe it's more appropriate to apply the scanline effect to 640x200 mode when scan2x or tv2x scaler is selected.

**Comment by joncampbell123** [comment]
@frank-deng Works for me, unless the appearance of your 1x2 upscaling is different from 2x2 upscaling

**Comment by frank-deng** [comment]
The original tv2x filter is configured with the odd lines dimmer now.
May I change the tv2x filter into the one with odd lines brighter and even lines dimmer?

**Comment by frank-deng** [comment]
I also add a configuration called `monochrome_pal` under `[render]` section, which is used for specifing color for monochrome displays when `machine=cga_mono` or `machine=hercules`
Possible values for `monochrome_pal` are: green, amber, gray, white

**Comment by joncampbell123** [comment]
Ready for me to merge your pull request?

**Comment by frank-deng** [comment]
OK, you can merge my modifications now, I have tested them at my side last night (Beijing time).

**Comment by joncampbell123** [comment]
Will there be further refinements? Should I close this issue?

**Comment by frank-deng** [comment]
I'll try the CGA-related enhancements again some days later.
Maybe it's time to close this issue now, I consider opening a new issue for monochrome VGA monitor.

**Comment by frank-deng** [comment]
I'll try to add scalers called for greyscale display called `greyscale`, `greyscale2x`, `greyscale3x`, `greyscale4x`, `greyscale5x`, is it appropriate to do so?
