### ISSUE TITLE
Alone in the Dark + Jack in the Dark CD version not loading

### ISSUE THREAD

**Issue by sendnonsensehere** [joncampbell123/dosbox-x#1030]
Hey great job on Dosbox-X, especially when you fixed the audio snapping bug when sound effects finished in games like Wizardry 6 and 7!

All of my games work on DB-X except for Alone in the Dark's CD version. Jack in the Dark works perfectly, but Alone in the Dark fails to load at all. I had a similar problem with the original Dosbox and lowering cycles fixed it there (and the current latest version of Dosbox also loads the game correctly), but all I get is a blank screen on DB-X. I've tried messing with the cycles, core and output, and had no luck so far.

I'm using Windows 7 64-bit and have tried every version of DB-X that works on my computer if that helps (Mingw, SDL, 32-bit, etc...) Any ideas?

Thanks a lot for your work!

**Comment by joncampbell123** [comment]
The audio snapping problem (in my tests, the 1991 Terminator game) seems to be caused by the format of the audio. If you look at the *.RS files in a hex editor, all byte values beyond the header range from 0x00 to 0x3F and center around 0x20. So the game is playing 6-bit audio as 8-bit audio.

I have the gog.com version "Alone in the Dark". I'll see if the same problem happens here.

**Comment by joncampbell123** [comment]
The gog.com version seems to work fine.

You're playing it straight from the physical CD, correct?

**Comment by sendnonsensehere** [comment]
Yes sir, that's right. I tried imgmount and regular mount of the CD but it didn't seem to work. I'll try to re-rip the disc and see if it works. Any ideas of conf settIngs I can try?

**Comment by joncampbell123** [comment]
I think DOSBox-X and DOSBox SVN are both able to handle BIN + CUE, if that helps.

The GOG.COM release looks like a raw CD sector rip (2352 bytes/sector GAME.GOG) in one file and a table of contents (GAME.INST) to match the original disc.

**Comment by sendnonsensehere** [comment]
I tried re-ripping the CD as both an IMG and ISO, and tried running directly from the CD, then tried a directory with CD contents mounted as a CD. All no go. :/

**Comment by sendnonsensehere** [comment]
Oh also Bin/Cue. I used IMGBurn and CloneCD, and it didn't work.

**Comment by sendnonsensehere** [comment]
My mistake, I tried to load the game without the .conf file that came with the Windows versions and it loaded just fine. There's something in the settings that doesn't work with AITD but default settings are just fine. Thanks for taking a look and helping out.
