### ISSUE TITLE
Having sector errors

### ISSUE THREAD

**Issue by GhoulUnlimited** [joncampbell123/dosbox-x#1033]
Hi, everyone. I'm having this weird issue where everytime I get around 2 GB of data on a 4GB hd image the sectors and the data in them cannot be read anymore, 

![guest os_006](https://user-images.githubusercontent.com/30055705/54730112-a5a28500-4b4c-11e9-8d41-95f73a162bd0.png)

![guest os_004](https://user-images.githubusercontent.com/30055705/54730114-aaffcf80-4b4c-11e9-8dab-b2f728e9001b.png)

![guest os_005](https://user-images.githubusercontent.com/30055705/54730116-b05d1a00-4b4c-11e9-8e1a-3772804222b5.png)

I would also like to know what's the maximum size for an hd image supported by Dosbox-X

**Comment by joncampbell123** [comment]
What platform is this?

The code is supposed to be able to handle 64-bit file offsets to support disk images 2GB or larger.

**Comment by GhoulUnlimited** [comment]
I'm running Windows 10 64 bit and emulating Windows 98. Here's my autoexec: 

imgmount 2 w98.img -t hdd -fs none -size 512,63,255,522
imgmount 3 games.img -t hdd -fs none -size 512,63,255,522

boot -l c

**Comment by yksoft1** [comment]
> What platform is this?
> 
> The code is supposed to be able to handle 64-bit file offsets to support disk images 2GB or larger.

Did it use off_t data type, stat(), fstat() and fseek() functions from CRT? some older MinGW system include files didn't properly declare 64-bit integer (as __int64 as in msvcrt.dll) versions of those.

**Comment by joncampbell123** [comment]
@GhoulUnlimited Are you using the VS2017 (Windows) build or the MinGW build?

**Comment by joncampbell123** [comment]
Reading up on other forums, MinGW may need _FILE_OFFSET_BITS=64 to support a 64-bit off_t in 32-bit builds.

**Comment by joncampbell123** [comment]
Apparently when the image size (in KB) is given, and multiplied by 1024, the multiply is 32-bit by 32-bit and integer overflow happens. Try pulling the latest commit and compiling from source, if you can.

**Comment by joncampbell123** [comment]
Hold on, IDE emulation is still having problems in Windows 95.

**Comment by yksoft1** [comment]
> Reading up on other forums, MinGW may need _FILE_OFFSET_BITS=64 to support a 64-bit off_t in 32-bit builds.

I found that MinGW.org and mingw-w64 have their own fseeko64 and ftello64 implemented. Perhaps we should not redefine those in dos_inc.h under such platforms.

**Comment by joncampbell123** [comment]
The IDE vm86 hack has been fixed. You should have no issues now with large >= 2GB hard drives, unless of course they exceed INT 13h C/H/S geometry limits.
