### ISSUE TITLE
Implement PCJr-specific method of clearing the video RAM

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1064]
A feature in mainline DOSBox that was mentioned in https://github.com/joncampbell123/dosbox-x/pull/1060 as something that could be recreated in DOSBox-X fairly straightforwardly. I'm just making this issue so it doesn't get forgotten.

Relevant code in mainline:
https://sourceforge.net/p/dosbox/code-0/3860/

**Comment by joncampbell123** [comment]
Done
