### ISSUE TITLE
Questions about built-in "COPY.EXE"

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#1078]
1. Who put it in the built-in binary blobs in the first place? DOSBox Daum's author or joncampbell123?
2. Why we have to use that instead of DOSBox's own DOS_Shell::CMD_COPY? Isn't COPY built into COMMAND.COM in all MS-DOS versions? 
3. It has problems with PC-98 Shift-JIS filenames. We cannot fix that without big work (find its source, probably in assembly, and fix it).

**Comment by joncampbell123** [comment]
1. Daum, I think
2. If the built-in COPY command works better, I'm all for it
3. I'm aware of that. If the internal copy can do it better, I'm all for it.

I think COPY.EXE and XCOPY.EXE came from FreeDOS, not sure.

Try removing the COPY.EXE blob.

**Comment by joncampbell123** [comment]
The latest commit removes the COPY.EXE binary so the COPY shell command can work. Try it now.

**Comment by yksoft1** [comment]
You forgot to remove the code to redirect COPY to Z:\COPY.EXE in DOS_Shell::CMD_COPY from shell_cmds.cpp.

**Comment by yksoft1** [comment]
Copying files from Touhou 1-5 HDIs to DOSBox mounted host directory worked, with Japanese filenames all correct even if Windows host codepage is not 932 (936 in my situation).

**Comment by joncampbell123** [comment]
@yksoft1 I removed the COPY.EXE search in CMD_COPY.

It might be trivial to modify the internal COPY command to read the DOS time/date timestamp and apply it to the target file during copy. Want to try?

**Comment by joncampbell123** [comment]
@yksoft1 The latest commit modifies COPY to copy the file date/time as well as the file.

**Comment by yksoft1** [comment]
Already did that in my own fork.
![image](https://user-images.githubusercontent.com/37106774/57416315-5c101580-7232-11e9-9c26-c3c6fb35f8dd.png)

I think the issue can be closed at least for now.
