### ISSUE TITLE
Windows 7/8/10 new LED control code has infinite loop issues with Num/Scroll/Caps lock

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#108]
Thanks to Microsoft's insistence on keyboard event injection (SendInput) and no other API to control LEDs, and the new code in the BIOS emulation to set LEDs, we now have an infinite loop problem with Num Lock when capture is enabled. The SDL window proc cannot distinguish between the user pressing Num Lock vs the stupid key injection events we have to do to make the LEDs change state. Pressing Num Lock at this time while capture is enabled in Windows means Num Lock immediately begins flashing rapidly and the DOS VM sees continuous Num Lock events.

It would be so much easier if Microsoft had simply kept the Win9x way of handling things with SetKeyboardState() to change the LEDs, or at least provided some consistent API to immediately change LED states, instead of dicking with event injection.

**Comment by joncampbell123** [comment]
I don't have time right now to work on this, but the low level keyboard hook and SDL window proc need to work together on this issue:

1. The low level keyboard proc needs to recognize Num/Scroll/Caps lock WM_KEYDOWN/WM_KEYUP and map them to some other message (WM_USER+0x100 perhaps).
2. The SDL proc needs to recognize WM_USER+0x100 and WM_USER+0x101 as keyboard events for thee specific keys that were entered by the user, and act on them
3. The SDL proc's normal WM_KEYDOWN/WM_KEYUP handling then needs to ignore Num/Scroll/Caps lock, and rely on the WM_USER messages, so that when the injected events to change LEDs come by they are properly ignored.
4. This hack needs to be written so that the WM_USER hack mentioned above ONLY happens while capture AND the extended hook are active. It needs to act normally in all other cases.

So the new way things would work is that Num/Scroll/Caps would be caught by the low level keyboard hook, posted to the window proc as WM_USER instead, while all other keys would be sent as WM_KEYDOWN/etc. The SDL proc would know that the capture is enabled and the hook is active, and would only process Num/Scroll/Caps from the WM_USER+0x100 handler, and ignore same events from WM_KEYDOWN. When the BIOS keyboard handler processes Num/Scroll/Caps it would flip the bits in the BIOS area and then tell keyboard emulation to set LEDs. The only way to change LED state in Windows is get the toggle key state and then SendInput inject events to trick Windows into toggling the LEDs. This of course then appears to SDL's window proc as WM_KEYDOWN and so on, which is why it needs to be hacked to know capture & extended hook are active and therefore to ignore them because they are faked for Windows stupid design and not actual user input.

**Comment by sikthehedgehog** [comment]
I'm going to guess they did that because a lot of programs had a tendency to go out of sync.

Would it be possible to use some dummy scancode surrounding the fake Num Lock presses, and then have DOSBox use them as a flag telling it when to ignore the fake presses? That would require the least amount of hacking I believe, although you'd need to find a suitable scancode.

**Comment by joncampbell123** [comment]
Fixed. Alternate message system added. WM_KEYDOWN NUM lock is triggered by injected event, so keyboard hook directs the real events for Num/Scroll/Caps as WM_USER+0x100.
