### ISSUE TITLE
Installs US keyboard on windows

### ISSUE THREAD

**Issue by Unixware** [joncampbell123/dosbox-x#109]
Its very strange, I tried the program under win10 and win8.1, it installs an US keyboard layout on the system! (my main and only keyboard is UK)

**Comment by joncampbell123** [comment]
?? I don't believe I'm making any system calls to change keyboard layout. Are you sure something else didn't auto-install keyboard layout?

**Comment by joncampbell123** [comment]
All the code does with the keyboard is disable the IME for itself and install a low level hook (if you use CTRL+SHIFT+F10 to capture). It reads the keyboard layout from the system, but there is no code that I know of to change or install a keyboard layout.

**Comment by Unixware** [comment]
I m pretty sure after running dosbox-x a new keyboard,US layout was installed.

**Comment by joncampbell123** [comment]
What the hell? You're right. But it seems to happen in a way that shows Windows is more confused than certain what keyboard layouts are involved.

I honestly don't know what part of DOSBox-X would trigger that. That's really weird.

![uk keyboard duped and us layout installed but settings does not show that wtf](https://cloud.githubusercontent.com/assets/6245486/9566597/354eacd4-4ec0-11e5-8b5e-8938aca7a5d2.jpg)
![uk keyboard duped and us layout installed wtf](https://cloud.githubusercontent.com/assets/6245486/9566599/3a52a5a0-4ec0-11e5-8e51-4f41f5291046.jpg)

**Comment by joncampbell123** [comment]
The extra keyboard layouts disappear when you reboot Windows, though.

**Comment by joncampbell123** [comment]
First finding: it happens somewhere during SDL_Init().

**Comment by Unixware** [comment]
I just asked a friend about this, he told me there is a bug involved with SDL but the SDL devs ain't fix it as they moved to SDLv2 , is it possible to compile the dosbox-x with the SDLv2?

**Comment by joncampbell123** [comment]
I would love to port DOSBox-X to SDL2. There's a lot of code that's intricately tied to SDL 1.x that makes that a fair amount of work, and some parts like the CD-ROM drive support will not port to SDL 2.x. Anyone want to take that on?

**Comment by DominusExult** [comment]
A good start would be this patch:
http://www.vogons.org/viewtopic.php?f=32&t=34770
;)

**Comment by joncampbell123** [comment]
It turns out SDL 1.x tried to maintain a consistent keymap by loading the US keyboard layout for itself at startup.

I removed that code and add code in DOSBox-X and SDL 1.x to recognize the keyboard layout (and respond to changes).

**Comment by Unixware** [comment]
Bit late reply, but since long time ago I found a way to "fix" the US keyboard SDL bug 
just a .reg file that removes the US keyboard from registry (in fact removes the layout file so US keyboard can't be loaded): 


`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Keyboard Layouts\00000409]
"Layout Display Name"=hex(2):00,00
"Layout File"=""
"Layout Text"="US"`
