### ISSUE TITLE
MSD (Microsoft Diagnostics) keyboard input doesn't work when machine=pcjr

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#11]
Possibly related to NMI-based keyboard emulation, not sure.
Program does not respond to any keyboard input when machine=pcjr, though if mouse emulation is enabled, it will respond to the mouse.

I will close this bug as "wontfix" if there is evidence MSD.EXE has the same problem on real PCjr hardware.

**Comment by Allofich** [comment]
Testing with `umb=false` (to avoid the hang mentioned in the other issue) and trying from before and after the recent PCjr keyboard changes, looks those changes fixed this issue.
