### ISSUE TITLE
Supercars International

### ISSUE THREAD

**Issue by altiereslima** [joncampbell123/dosbox-x#1106]
Supercars International game starts without sound.

**Comment by joncampbell123** [comment]
If you have the ability to compile DOSBox-X from source, see if compiling from older commits resolves the sound issue.

If you do not, see if using an older release binary helps.

**Comment by joncampbell123** [comment]
A lot of commits have been made from another user who is backporting DOSBox SVN changes to DOSBox-X (where possible) and there is always the concern that those may break something.

**Comment by joncampbell123** [comment]
Hey, just found the game.

It doesn't seem to play any audio if loaded too low in memory (if too much conventional memory is available).

I got audio to work using LOADFIX:

LOADFIX -24
SUPACARS.EXE

**Comment by altiereslima** [comment]
DOSBox-X BETA 2018-05-18 17:00 Works fine

**Comment by joncampbell123** [comment]
As posted above, I got it to work in the latest commit using LOADFIX. Sound does not work if the game is loaded below a certain memory address.

**Comment by joncampbell123** [comment]
DOSBox SVN and DOSBox-X tend to offer DOS games a lot more conventional memory than actual DOS systems. Some games have bugs and problems if too much conventional memory is available that way.
