### ISSUE TITLE
WARCRAFT II: TIDES OF DARKNESS

### ISSUE THREAD

**Issue by altiereslima** [joncampbell123/dosbox-x#1107]
WARCRAFT II: TIDES OF DARKNESS, don't start.
![image](https://user-images.githubusercontent.com/18044879/57895526-747bc380-7822-11e9-84ee-3c975cd9174a.png)

**Comment by Allofich** [comment]
In the file "dosbox.conf", change "vesa modelist cap:" from 0 to another value.

There's a note in the file that says:

```
Warcraft II by Blizzard ................ Set to a value between 8 and 16. This game
has a fixed buffer that it reads the modelist into. DOSBox-X's normal modelist
is too long and the game will overrun the buffer and crash without this setting.
```

@joncampbell123, maybe the default setting should be something more compatible/realistic like a typical value for a computer using `svga_s3`?

**Comment by Askmewho** [comment]
@joncampbell123 whats the usage form? 
vesa modelist cap = 10    ?
vesa modelist cap:10    ?

ive tried the gui config an it keeps producing the fault...

**Comment by joncampbell123** [comment]
in dosbox.conf it is "vesa modelist cap=10"
