### ISSUE TITLE
More DIR switches

### ISSUE THREAD

**Issue by sagamusix** [joncampbell123/dosbox-x#113]
Many years ago I wrote some BASIC games which used the DOS DIR command for reading directories. Some switches for this command were never implemented in DOSBox, so all it does is returning "illegal switch" instead of a file listing. I have written a patch for DOSBox which supports all documented DIR switches, but so far it has not made it into the main branch. Feel free to incorporate it into your branch: http://www.vogons.org/viewtopic.php?f=41&t=18081#p343341

**Comment by joncampbell123** [comment]
Done
