### ISSUE TITLE
Zip file support

### ISSUE THREAD

**Issue by jose1711** [joncampbell123/dosbox-x#1132]
An old patch enabling mounting a zip file as a drive exists at https://sourceforge.net/p/dosbox/patches/100/. Currently the patch fails to apply but at the time it emerged (2005) it seemed to work fine. It would be nice to have this integrated into the current codebase.

**Comment by jose1711** [comment]
More up-to-date (2015) exists in http://ykhwong.x-y.net/ (http://ykhwong.x-y.net/downloads/dosbox/patch/source.7z) and it brings support for both .zip and .7z files

```
src/shell/shell.cpp
..
if((strstr(name,".ZIP") != 0) || (strstr(name,".7Z") != 0)) {
  //TODO:Add more extensions?
  LOG_MSG("Mouting %s as PHYSFS write directory", buffer);
  autoexec[12].Install(std::string("MOUNT C \"") + buffer + std::string(":") + name
```

**Comment by Wengier** [comment]
The current DOSBox-X version (0.83.9) already supports this in read-only mode. It has been updated in #2206 to add write support as well by using overlay mounts instead of the older method.

**Comment by Wengier** [comment]
This is already fully supported in DOSBox-X version 0.83.10.

**Comment by jose1711** [comment]
Thank you!
