### ISSUE TITLE
Budokan audio issue

### ISSUE THREAD

**Issue by Hexaae** [joncampbell123/dosbox-x#1133]
Digitized voices and audio in loop issue in Budokan game when you start a fight/training.

Win 10 Pro 1903

**Comment by joncampbell123** [comment]
The only version I can find uses the PC speaker for (awful sounding) PC speaker music and digitized speech.

https://abandonwaregames.net/game/budokan-the-martial-spirit

**Comment by joncampbell123** [comment]
The only MS-DOS version I am aware of is the 1989 version that plays digitized speech through the PC speaker. Is there a version that plays from Sound Blaster with this problem?

**Comment by joncampbell123** [comment]
Ah, if you hit escape you can configure it to play from Adlib instead of PC speaker.

**Comment by joncampbell123** [comment]
It supports CMS, Adlib, and MPU-401 so I'm not really sure why it defaults to PC speaker speech and music every single time.

**Comment by joncampbell123** [comment]
I see no attempt whatsoever to probe CMS/SB/Adlib/MPU-401 ports at startup.

**Comment by Hexaae** [comment]
That's because of the lame crack. Run just "fix.com" and then "Budo.exe MT32" to launch it with audio card from the start… ;)

**Comment by joncampbell123** [comment]
That works, thanks!

**Comment by tjareth** [comment]
> That's because of the lame crack. Run just "fix.com" and then "Budo.exe MT32" to launch it with audio card from the start… ;)

I may be missing some context I need, but where do I find "fix.com"?  Is it something I need to download separately?
