### ISSUE TITLE
Printer support?

### ISSUE THREAD

**Issue by sikthehedgehog** [joncampbell123/dosbox-x#114]
Pretty much what it says, vanilla DOSBox never supported printers because games didn't need it but I could see this being useful, even if all it does is print to a PNG file instead of actually sending it to a printer. (also there's the occasional game that supports printing something)

Obvious use case: converting an ESC/P stream (by sending the file to PRN) so we can see what's in it.

**Comment by joncampbell123** [comment]
I could make that easy. Would you be OK with the unix/CUPS model of running another program under DOSBox-X and connecting the virtual parallel port to the program's STDIN? Then the program can focus on reading printer codes from STDIN and render to wherever (including PNG) the output. It would be easier to write than integrating it into DOSBox-X itself.

**Comment by sikthehedgehog** [comment]
How easy would be that to use? Or do you mean it's just a separate program that would come together with DOSBox-X?

**Comment by ghoul8765** [comment]
www.vogons.org/viewtopic.php?f=31&t=25007

**Comment by joncampbell123** [comment]
I mean it would be a separate EXE compiled from the same source tree. DOSBox-X would run the program and direct parallel port output to the program. All the program has to do is read printer data from STDIN and render it to memory/screen/PNG/whatever. Not having to worry about DOSBox-X state would allow you to focus on developing the code to emulate a printer.

The program would basically look like:

    #include <stdio.h>
    
    int main() {
        char c;
        
        /* main loop. will not terminate until stdin is closed.
           stdin would normally be the read end of an anonymous pipe
           given by DOSBox-X, which would only signal EOF if DOSBox-X
           closes it i.e. at termination. You *could* also pipe to stdin a file
           if you want to test the code without DOSBox-X! */
        while (!ferror(stdin) && !feof(stdin)) {
            c = fgetc(stdin);
            /* do something with byte 'c', usually render it, emulate linefeed/pagefeed,
               parse escapes, divide pages, etc. */
        }
        
        /* this is where the code would display the rendered output
           to screen, save to PNG, etc. */
        
        /* done */
        return 0;
    }

**Comment by joncampbell123** [comment]
I would also develop a STDIN/STDOUT protocol to send data and control lines, recv line status (including "out of paper" signal), DOSBox-X cycle/timing info, etc. for the program to better integrate with emulation, but that comes much later. That's less important than getting printer emulation off the ground.

**Comment by joncampbell123** [comment]
Printer emulation code was ported into DOSBox-X within the last few months from the Daum SVN branch.

I still envision an interface though to allow DOSBox-X to spawn a subprocess that uses STDIN/STDOUT to send/receive parallel port status and emulate a printer.

**Comment by KormaX-of-DOS** [comment]
Is it voluntary that the DOS versions lack the printer emulation settings?
