### ISSUE TITLE
emulation hiccups on mouse move after hiding menu bar on OpenGL surface on SDL builds on Windows

### ISSUE THREAD

**Issue by FyiurAmron** [joncampbell123/dosbox-x#1147]
**Describe the bug**
After hiding menu bar (either directly, or by e.g. entering fullscreen mode), the emulation (both gfx, sound, and all visible events) starts to stutter in reaction to *every* single mouse move. With slow mouse cursor movement this is already troublesome, but with a fast mouse move, the emu actually hangs for a couple of seconds. It seems as if some CPU-expensive operation happens on every mouse pointer update?

**To Reproduce**
1. Use any SDL build that uses the "custom" menu bar instead of system-based one on Windows 7 (e.g. Windows/Windows/SDL2, Windows/MinGW/SDL2, Windows/MinGW/SDL_Draw),
2. Switch to any OpenGL surface,
3. Hide menu bar (either from the menu itself or using the keyboard),
4. (optional) Launch a mouse-using application/game,
5. Move the mouse fast and observe the stutter.

**Expected behavior**
The emu shouldn't stutter etc.

**Environment (please complete the following information):**
 - Windows 7 64 bit
 - all DOSBox-X I tested, at least from 0.82.12 to 0.82.19
 - stock configuration, with OpenGL surface enabled

**Additional information**
I don't know if this issue is limited to Windows platform only, I haven't tested other platforms yet - but it seems to happen in SDL(2?)+new menu bar+OpenGL configurations only.

**Comment by joncampbell123** [comment]
Please confirm if this is limited only to OpenGL or happens with surface output too.

**Comment by FyiurAmron** [comment]
@joncampbell123 it doesn't happen for surface (and, FWIW, didn't happen for me with ddraw, which seems to fallback to surface in the menu?), but it did happen for overlay (which seemed to fallback to surface in the menu?)

**Comment by joncampbell123** [comment]
I just confirmed it's a general issue with SDL/SDL2 builds when OpenGL and the custom menus are involved in general. I am able to reproduce the issue on Linux.

**Comment by joncampbell123** [comment]
The latest commit fixes the issue. Can you compile from source?

**Comment by FyiurAmron** [comment]
@joncampbell123 would pulling https://github.com/joncampbell123/dosbox-x/pull/1151 be OK for you? I hope that refactoring this code a bit would allow to make it easier to avoid similar problems in the future.

**Comment by joncampbell123** [comment]
@FyiurAmron Works for me, done.

**Comment by FyiurAmron** [comment]
> The latest commit fixes the issue. Can you compile from source?

I've checked it vs mingw-sdl2, and it works 100% good, no hiccups, no slowdown.
