### ISSUE TITLE
GUI for imgmount?

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [joncampbell123/dosbox-x#1153]
I think it is nice if there is GUI for imgmount.
When swapping disks, renaming an image file and reloading it are a bit messy.

**Comment by PakkunKinoppi** [comment]
This would be a great thing !

**Comment by tokumeiwokiboushimasu** [comment]
Or, just asking the new disk image's file name when swapping disks is also nice.

**Comment by joncampbell123** [comment]
Agreed.

**Comment by Max833** [comment]
A GUI for imgmount would be really handy indeed.

**Comment by tokumeiwokiboushimasu** [comment]
Now we can mount disk images from menu! Thanks!!
