### ISSUE TITLE
macOS screenshot colours are always wrong

### ISSUE THREAD

**Issue by meunierd** [joncampbell123/dosbox-x#1156]
**Describe the bug**
![guest os_000](https://user-images.githubusercontent.com/37849/60366345-43fa7e00-99b9-11e9-87ed-f91a2fe388f6.png)

Colours are always as though there's a filter applied over the buffer. If I use the OS' native screen capture it's fine.

**To Reproduce**
1. Take a screenshot on macOS

**Comment by joncampbell123** [comment]
Does this happen with SDL2 builds?

Mac OS X and SDL1 combined have a strange RGBA byte order that's completely backwards from what most of the code is prepared to handle, even despite the changes I've made.

**Comment by meunierd** [comment]
I'm just grabbing the public build from homebrew, not sure what it was built against and I haven't been able to get this building from source locally.

**Comment by meunierd** [comment]
Finally got SDL2 building, I can confirm that this fixes the issue!
