### ISSUE TITLE
PC-98 Peret em Heru locks

### ISSUE THREAD

**Issue by meunierd** [joncampbell123/dosbox-x#1162]
**Describe the bug**
Game locks consistently in the first few minutes.

**To Reproduce**
1. Start playing
2. Tap through dialogue (`<space>`), it'll usually freeze before you gain control of your character but if not it's within the first couple minutes
3. When it finally chokes this is what I see in the console:

```
...
LOG: A1 port attempt to write FONT ROM char 0x56
LOG: A1 port attempt to write FONT ROM char 0x56
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: PC-98 INT 18 AH=42h CH=0xC0
LOG: PC-98 INT 18 AH=42h CH=0xC0
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
LOG: 8251 warning: RX overrun
```

**Environment (please complete the following information):**
 - Operating system: macOS
 - f687c100f78360bbaa45dc4daf4c93ff25a95942
 - `dosbox.conf`
```
# This is the configuration file for DOSBox 0.82.16. (Please use the latest version of DOSBox)
# Lines starting with a # are comment lines and are ignored by DOSBox.
# They are used to (briefly) document the effect of each option.
# To write out ALL options, use command 'config -all' with -wc or -writeconf options.

[sdl]
#          output: What video system to use for output.
#                  Possible values: surface, overlay, opengl, openglnb, openglhq, ddraw, direct3d.
#        autolock: Mouse will automatically lock, if you click on the screen. (Press CTRL-F10 to unlock)
#     sensitivity: Mouse sensitivity.
# mouse_emulation: When is mouse emulated ?
#                  integration: when not locked
#                  locked:      when locked
#                  always:      every time
#                  never:       at no time
#                  If disabled, the mouse position in DOSBox-X is exactly where the host OS reports it.
#                  When using a high DPI mouse, the emulation of mouse movement can noticeably reduce the
#                  sensitiveness of your device, i.e. the mouse is slower but more precise.
#                  Possible values: integration, locked, always, never.
output=overlay
autolock=true
sensitivity=50
mouse_emulation=never

[dosbox]
#   title: Additional text to place in the title bar of the window
# machine: The type of machine DOSBox tries to emulate.
#          Possible values: hercules, cga, cga_mono, cga_rgb, cga_composite, cga_composite2, tandy, pcjr, ega, vgaonly, svga_s3, svga_et3000, svga_et4000, svga_paradise, vesa_nolfb, vesa_oldvbe, amstrad, pc98, pc9801, pc9821, fm_towns, mcga, mda.
title=Peret em Heru - For the Prisoners
machine=pc98
cascade interrupt ignore in service=true  # does it with and without this option

[cpu]
cycles=max

[render]
# scaler: Scaler used to enlarge/enhance low resolution modes. If 'forced' is appended,
#         then the scaler will be used even if the result might not be desired.
#         Possible values: none, normal2x, normal3x, normal4x, normal5x, advmame2x, advmame3x, advinterp2x, advinterp3x, hq2x, hq3x, 2xsai, super2xsai, supereagle, tv2x, tv3x, rgb2x, rgb3x, scan2x, scan3x, hardware_none, hardware2x, hardware3x, hardware4x, hardware5x, xbrz, xbrz_bilinear.
scaler=normal2x forced

[dos]
# xms: Enable XMS support.
# ems: Enable EMS support. The default (=true) provides the best
#      compatibility but certain applications may run better with
#      other choices, or require EMS support to be disabled (=false)
#      to work at all.
#      Possible values: true, emsboard, emm386, false.
# umb: Enable UMB support.
xms=false
ems=false
umb=false

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
imgmount 2 "Peret em Heru - For the Prisoners.hdi" -t hdd -fs none
BOOT -l c
```

**Additional context**
This is happening both with and without the fan translation. I can email you an HDI if you're having trouble tracking it down.

**Comment by joncampbell123** [comment]
I'm having trouble tracking it down, the collection I have to test is only whatever was on the Internet Archive at the time I started PC-98 emulation.

**Comment by meunierd** [comment]
[Peret.zip](https://github.com/joncampbell123/dosbox-x/files/3360205/Peret.zip)

Feel free to delete this comment once you've got it

**Comment by joncampbell123** [comment]
Thank you. I see it run normally then suddenly jump into an undefined (FF) region of memory.

**Comment by joncampbell123** [comment]
I found I can avoid the crash IF you set the cycle count to a value around 100000.

I can also avoid the crash if I imgmount the HDI image to drive a: and run the game directly instead of booting the HDI image, but there is no sound for some reason.

**Comment by joncampbell123** [comment]
It's still playable with a high cycle count if you use dynamic core.

It seems to run without crashing at 70000 cycles.

**Comment by joncampbell123** [comment]
Since the game is said to have come out in 1998 it's entirely possible it was only tested on 1998-era Pentium hardware. Does this game crash the same way on anything lower end, like a 486?

**Comment by joncampbell123** [comment]
A log of the CPU execution shows that when it crashes, it gets very involved with the FM interrupt, then eventually IRETs to a random junk address.

**Comment by joncampbell123** [comment]
If I start the opening sequence or game and then immediately use the debugger to mask IRQ 12 (FM interrupt) to prevent it from working, the game does not crash.

**Comment by joncampbell123** [comment]
The game seems to require cputype=pentium and a minimum cycle count of 65000 to run with FM music enabled without crashing.

**Comment by meunierd** [comment]
For me with `cputype=pentium` and `cycles=100000` it crashes later but still consistently crashes.

**Comment by yksoft1** [comment]
This game is built with the Dante98: RPG Maker II.
RPG Maker II was released in 1996, requires 386+ CPUs to run so it shouldn't need 100000+ cycles at all.

**Comment by joncampbell123** [comment]
Since the issue seems to center around the FM music I am looking into the MUSIC.COM program right now.

Apparently the interface is through INT 48h

When you run the game by IMGMOUNTing the HDI file to A: and running it without booting, FM music does not work, but the game does not crash.

Apparently the reason FM music doesn't work in that way is that MUSIC.COM assumes it is installed if the segment value of INT 48h is anything other than 0060h. DOSBox-X vectors unknown INTs to handlers in the BIOS (segment F000h) so it doesn't load.

**Comment by joncampbell123** [comment]
If I patch that check out of MUSIC.COM so that it loads anyway in that case, then the FM music works and the game eventually crashes.

**Comment by joncampbell123** [comment]
The fault seems to be within the FM music driver. Something causes it to corrupt memory and crash the game. It seems to be CPU speed dependent.

**Comment by joncampbell123** [comment]
MUSIC.COM's IRQ 12 ISR appears to switch stacks before processing the interrupt, and switch back before return. The crash appears to be a corner case where it does NOT switch the stack back after processing and IRETs back to the program.

**Comment by joncampbell123** [comment]
Actually it's a re-entrancy problem. The game is using vsync interrupt IRQ2 to call the driver per vsync. Most of the IRQ 12 FM interrupt handling is done without interrupts enabled, however there is one point in that ISR where interrupts are briefly enabled for one CPU cycle, like this:

    STI
    CLI

The game crashes if the vsync interrupt is handled during that brief window.

The reason it crashes is because of the stack switching performed by MUSIC.COM's FM interrupt handler. It's not re-entrant. That stack switching also happens through the callback called by the vsync interrupt. The saved stack address is overwritten and the wrong one restored.

**Comment by joncampbell123** [comment]
You can fix the crashing by masking IRQ 2 from the debugger:

PIC MASKIRQ 2

This does mean though that if the game relies on counting vsync it will fail at some point.

**Comment by joncampbell123** [comment]
I can test this later, but does anyone know if a 386/486/Pentium will service interrupts if the instruction pipeline contains STI and CLI right after each other?

**Comment by joncampbell123** [comment]
According to a 486 laptop (486DX/50MHz), the CPU will not service interrupts at the "STI" given the sequence.

    STI
    CLI

Apparently the window for handling interrupts is too short for the CPU to service any pending interrupts.

Which explains how this reentrancy bug could go unnoticed on real hardware.

**Comment by joncampbell123** [comment]
By the way, I can easily imagine this game having problems if run in virtual 8086 mode under EMM386.EXE since STI/CLI in virtual 8086 mode trigger a General Protection Fault and the time it takes for EMM386.EXE to emulate STI/CLI for the VM is enough time for the CPU to process an interrupt, given this problem.

**Comment by joncampbell123** [comment]
The latest commit fixes normal core not to immediately process STI so that STI + CLI does not cause interrupt processing.

Peret has been running for 5 minutes now without crashing and playing FM music.

**Comment by joncampbell123** [comment]
Also, the tutorial mode has an interesting easter egg. See it? :)

![guest os_000](https://user-images.githubusercontent.com/6245486/60762950-e8666b00-a01e-11e9-8120-642412a7c040.png)

**Comment by sikthehedgehog** [comment]
Maybe it's possible x86 always waits one more instruction after STI before acknowledging interrupts? I know there's a similar hack with MOV SS, <...> so you can change the stack safely (which can't be done in a single instruction, as you need to change both SS and SP), this doesn't seem directly related but I wouldn't be surprised and wouldn't be the only CPU to have a similar quirk.

I admit I don't know why anybody would do STI immediately followed by CLI, however.

**Comment by sikthehedgehog** [comment]
OK seems I'm right

https://www.felixcloutier.com/x86/sti
> If IF = 0, maskable hardware interrupts remain inhibited on the instruction boundary following an execution of STI. (The delayed effect of this instruction is provided to allow interrupts to be enabled just before returning from a procedure or subroutine. For instance, if an STI instruction is followed by an RET instruction, the RET instruction is allowed to execute before external interrupts are recognized. No interrupts can be recognized if an execution of CLI immediately follow such an execution of STI.) The inhibition ends after delivery of another event (e.g., exception) or the execution of the next instruction.

http://faydoc.tripod.com/cpu/sti.htm
> Set interrupt flag; external, maskable interrupts enabled at the end of the next instruction

**Comment by joncampbell123** [comment]
@sikthehedgehog In the PC-98 MS-DOS world you'll find plenty of code doing weird things. Some things that make the early IBM PC demoscene look tame by comparison.

Here's some off the top of my head:

- Using the bus mouse interrupt as a periodic interrupt for timing (somewhat common)
- Reading memory locations directly in DOS kernel memory to determine console state (very common)
- Using PIT timer 2, tied to the RS-232 port, as a countdown timer for a delay loop (a game that was brought up some time ago, don't remember)
- Programming PIT timer 0, tied to IRQ 0 (timer interrupt), to run in square wave mode, then reading the output of the square wave through the 8259 interrupt controller IRR register for a delay loop (Steel Gun Nyan). Even funnier, the original PIT code in DOSBox SVN mentions that possibility but says "eh... nobody does that, not going to bother emulating it".

**Comment by meunierd** [comment]
I can confirm the latest master works for me! Thanks for looking into this

**Comment by meunierd** [comment]
This seems similar to behaviour mentioned in the readme for Night Slave which only worked on older versions of dosbox-x, I'll see if this works (warning it's got h content)

**Comment by joncampbell123** [comment]
It also seemed to fix lockups for one particular demoscene prod "saga by dust" that until now required the cs_equ_ds IRQ hack in order not to lock up in certain parts.

**Comment by joncampbell123** [comment]
I'm glad you mentioned Night Slave, the CPU_Cycles = 4 hack seems to trigger the right conditions that Night Slave causes DOSBox-X to hang (normal core never exits the loop), so a new commit was added that emulates the STI+CLI condition by peeking ahead to the next opcode instead.

- Night Slave (PC-98): works
- Peret em Heru (PC-98): works
- Saga by Dust (IBM PC): works

**Comment by meunierd** [comment]
On latest master I get this for Night Slave:

```
...
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: A1 port attempt to write FONT ROM char 0x57
LOG: PC-98 INT 18 AH=42h CH=0x80
```

**Comment by joncampbell123** [comment]
Night slave works on my end, it just takes awhile to get through the starfield effect and into the game. Starting a game should work, just as it does on my end.

Saga by Dust, if it hangs, tends to hang on the second part (with the scroller and 3D sphere objects) because some race condition eventually causes the Sound Blaster driver to try to operate the sound card with DS set to VGA memory (A000h), which of course is not valid.

**Comment by meunierd** [comment]
Maybe it's just the fan translation of Night Slave that's broken? You can
find a pre patched hdi of it on the Retronomicon Games Patreon

**Comment by joncampbell123** [comment]
@meunierd I'm saying Night Slave does work, no problems. It's not a fan translation, obviously.

![guest os_000](https://user-images.githubusercontent.com/6245486/60772318-7850f700-a0a9-11e9-8761-9d9666307d74.png)

**Comment by meunierd** [comment]
Are you using the HD or FD release from Neo Kobe? Would you mind sharing
your conf? I still keep locking for some reason

**Comment by joncampbell123** [comment]
I am running the game from an HDI image (hard disk).

[dosbox.conf.txt](https://github.com/joncampbell123/dosbox-x/files/3369910/dosbox.conf.txt)

**Comment by meunierd** [comment]
That works thanks! Definitely something to do with my config

**Comment by joncampbell123** [comment]
It may be the option to ignore cascade interrupt in service.

I'm not entirely sure how to approach it yet but PC-98 seems to use the 8259 slightly differently than IBM PC that allows the slave PIC to fire interrupts even if the ISR does not ack the cascade interrupt. On the IBM PC failure to acknowledge the cascade interrupt would prevent IRQ 8-15 from working.
