### ISSUE TITLE
SDL 1.x causes DOSBox-X crash/hang redirecting stderr/stdout when DOSBox-X is run from Program Files

### ISSUE THREAD

**Issue by CriusMacOldenly** [joncampbell123/dosbox-x#117]
---
## Microsoft Visual C++ Debug Library

Debug Assertion Failed!

Program: C:\Program Files (x86)\DOSBox-0.74\DOSBox.exe
File: f:\dd\vctools\crt_bld\self_64_amd64\crt\src\isatty.c
Line: 45

Expression: (fh >= 0 && (unsigned)fh < (unsigned)_nhandle)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
## Abort   Retry   Ignore   

Happened on startup trying to run X-com Apocalypse.

**Comment by joncampbell123** [comment]
Can you get a stack trace of the debug assertion? It doesn't help much if I'm only given that it happens in isatty()

**Comment by joncampbell123** [comment]
Is this still an problem?

I will close this issue as fixed if it no longer happens.

**Comment by CriusMacOldenly** [comment]
I'm sorry, I didn't notice a reply.


Fault bucket 120377879621, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: DOSBox.exe
P2: 0.74.0.0
P3: 55d2e2f4
P4: DOSBox.exe
P5: 0.74.0.0
P6: 55d2e2f4
P7: 80000003
P8: 0000000000305b94
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4400.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER44FC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4507.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4518.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_DOSBox.exe_79112b25cd7cdd517311c99f31a058191a50a966_25671950_3aa54d74

Analysis symbol: 
Rechecking for solution: 0
Report Id: dcb9a9fb-66dd-4f2a-a1c9-830cbe8219ed
Report Status: 268435456
Hashed bucket: 005b67e4a6002cd892843091e26e8a80

[Report.txt](https://github.com/joncampbell123/dosbox-x/files/1583917/Report.txt)

**Comment by joncampbell123** [comment]
I mean: If you run the latest build, is it still a problem?

**Comment by CriusMacOldenly** [comment]
I have just downloaded the latest build, but Avast worries the file might have a virus, and prevents me from running it, even though I picked that I trust the file. It says the file must be interrogated first to see that it's safe. It estimates 150 minutes before I can test the latest build -- sorry.

**Comment by CriusMacOldenly** [comment]
I have just downloaded the latest build, but Avast worries the file might have a virus, and prevents me from running it, even though I picked that I trust the file. It says the file must be interrogated first to see that it's safe. It's been a few hours now, and nothing seems to have happened, so I'll have to try running it later.

**Comment by joncampbell123** [comment]
It probably detected the new WinPCAP support and it's busy waterboarding it in a torture chamber somewhere within your PC :)

**Comment by CriusMacOldenly** [comment]
It's been over 150 minutes, and Avast won't let me run the file still. I think I'll have to wait until Avast staff look at the file, and determine it's safe for me to run.

**Comment by CriusMacOldenly** [comment]
As far as I can tell, Avast tested the file here, and couldn't determine it was safe (possibly since I have the VM disabled). Avast uploaded the file to their own servers, and it'll probably be looked at by them. Avast is (correctly) completely preventing me from running the program.

**Comment by CriusMacOldenly** [comment]
Dosbox no longer crashes.
Dosbox also does not give any sort of error if you try to run it without admin access -- it simply doesn't do anything.

**Comment by joncampbell123** [comment]
How do I recreate your system configuration? I'm curious what locked-down settings you'd have to have on your system to trigger this.

**Comment by CriusMacOldenly** [comment]
I'm surprised you knew the program I ran froze dosbox-x instead of crashing. Since you mentioned this, I decided to try a few of my dos games, and none of them ran. Every game either stated: "Packed File is corrupt", or dosbox-x froze. I tried 5 different programs, and even the installers didn't work.
As I continued testing, I tested your old dosbox-x, and it started perfectly fine, without requiring admin access.
All the programs failed in the same manner however, and the program asserted in in the same fashion. Since none of the programs ran anyways, the changes had no effect.

Since I remembered these programs previously working, I went to install the newest dosbox (original) from the web page, and it ran perfectly fine, and ran all the games and programs perfectly fine too.
There are larger problems, but I'm happy to help in any way I can.

**Comment by CriusMacOldenly** [comment]
Just in case you are referring to my windows configuration, and not my dosbox configurations, I am running local account, administrator, windows 10 professional, and I don't know what specifically you want to know about my windows 10 system.

**Comment by joncampbell123** [comment]
That's all I need, honestly.

When I reboot into Windows 10 from Linux to use VS2017 I am using a similar configuration, except Windows 10 home.

So perhaps this is a problem with permissions in Pro.

I don't have Windows 10 pro, but I do have an old Windows 7 Ultimate VM I could test this under to see if I can recreate this.

**Comment by joncampbell123** [comment]
Holy crap, don't ever create a secondary account in Windows 10 home it will throw away *all* your desktop settings and reset them >:(

**Comment by joncampbell123** [comment]
Anyway, I just ran it from a "standard user" account and it seems to work fine.

**Comment by joncampbell123** [comment]
Does the same issue happen if you run the SDL2 build of DOSBox-X?

SDL2 builds do not have CD-ROM drive support. That might be related.

**Comment by joncampbell123** [comment]
Good news: It just occurred to me to try copying DOSBox-X.exe to Program Files and running it there, which recreates this issue.

**Comment by joncampbell123** [comment]
SDL 2.x builds however don't seem to have this issue.

**Comment by joncampbell123** [comment]
Okay... so when run in that way, stderr is in an invalid state with no file handle, and that's where things blow up.

**Comment by joncampbell123** [comment]
Whoever wrote SDL 1.x decided that the SDL main function should use freopen() on stderr to write to stderr.txt. stdout too.

The best fix I can make for this is to remove that code and let stdout/stderr go to whatever device/file Windows assigned it at startup instead.

**Comment by joncampbell123** [comment]
Yes! Removing that code from SDL main allows DOSBox-X to run from the Program Files directory without problems.

**Comment by joncampbell123** [comment]
It's fixed. I'll post a binary now.

**Comment by joncampbell123** [comment]
https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-0.82.1-pf-fix
