### ISSUE TITLE
Most characters in EGA graphics mode rendered 1px lower than normal

### ISSUE THREAD

**Issue by lwchkg** [joncampbell123/dosbox-x#1196]
**Describe the bug**
Most characters in EGA graphics mode rendered 1px lower than normal. This causes broken rendering in some games because they try to enlarge only a part of the character box.

Note: when I say open a program in QBasic, I refer to the program in [programs.zip](https://github.com/joncampbell123/dosbox-x/files/3477528/programs.zip). 

**To Reproduce**
1. Start QBasic in DosBox.
2. Open "NOBOMB.BAS".
3. Run the program (press F5).
4. Check the output on the screen. You should be able to see that the enlarged text is broken.
(Note: you need to press SPACE to go past the intro screen, but the bug should be reproduced before that.)

**Expected behavior**
See the screenshot below (left: PCjs, right: DosBox-X). AFAIK, the rendering of PCjs is correct.
![firefox_2019-08-07_22-31-22](https://user-images.githubusercontent.com/4113719/62633585-f7667300-b966-11e9-98dc-703b6317022d.png)

To produce the screenshot run ASCTABLE.BAS in QBasic.

**Screenshots**
![qbasic_001](https://user-images.githubusercontent.com/4113719/62633620-04836200-b967-11e9-845a-f1e1894c7bbd.png)

**Additional context**
I believe that this problem is inherited from DosBox.

**Comment by joncampbell123** [comment]
It may be the accidental use of the 8x16 VGA font in EGA mode, will check.

**Comment by joncampbell123** [comment]
I'm getting correct results when machine=ega

![qbasic_000](https://user-images.githubusercontent.com/6245486/62674648-30e3b200-b958-11e9-9c1e-ac33246606f2.png)

**Comment by joncampbell123** [comment]
Notice what NOBOMB.BAS is doing to make the "Let's play!" text.

It's printing "Let's play!" on the screen (using the BIOS through QBASIC I think) and then using POINT() to read the pixels and redraw them larger on the screen.

    2000 LOCATE 1, 1: PRINT "Let's play!"
    2010 FOR VERT = 0 TO 12
    2020 FOR HORI = 0 TO 85
    2030 IF POINT(HORI, VERT) THEN LINE (HORI * 6 + 45, VERT * 6 + 20)-(HORI * 6 + 49, VERT * 6 + 24), 10, BF: LINE (HORI * 6 + 50, VERT * 6 + 25)-(HORI * 6 + 54, VERT * 6 + 29), 8, BF
    2040 NEXT HORI, VERT

https://www.qbasic.net/en/reference/qb11/Function/POINT.htm

**Comment by joncampbell123** [comment]
However "SCREEN 9" means EGA 640x350 mode, which should probably cause the BIOS to print with the 8x14 font bitmap instead of 8x16, so perhaps DOSBox-X is at fault here. In fact it's probably likely.

Note that 14 x 25 = 350, to keep the DOS prompt the same number of console rows.

I will double check this on the trusty old 486 laptop, hold on a sec.

**Comment by joncampbell123** [comment]
Confirmed.

Notice char 177 (▒) is 14 pixels high.
![ega8x14laptop](https://user-images.githubusercontent.com/6245486/62675154-a18bce00-b95a-11e9-9dd1-534dc96e28cd.jpg)

**Comment by joncampbell123** [comment]
Display is also correct with machine=vgaonly.
![qbasic_001](https://user-images.githubusercontent.com/6245486/62675289-47d7d380-b95b-11e9-8ce1-4c4c5aabd90f.png)

**Comment by joncampbell123** [comment]
I am testing with QBASIC v1.1 as found on qbasic.net.

Perhaps you are using a version of QBASIC that is getting the font incorrectly?

**Comment by lwchkg** [comment]
I just tried to reproduce without using D-Fend: failed to reproduce. So somehow it has to do with D-Fend, or the way how I start DosBox-X.

Investigation shows that it has to do with the following config: [DOSBOXTEMP.zip](https://github.com/joncampbell123/dosbox-x/files/3479946/DOSBOXTEMP.zip) I have no idea yet what is the exact switch that causes problems.

**Comment by lwchkg** [comment]
Finally got the result: the culprit is the following setting:
```
[dos]
keyboardlayout=US
```

**Comment by joncampbell123** [comment]
I see... I'll try to figure out which one.

![qbasic_000](https://user-images.githubusercontent.com/6245486/62677206-62617b00-b962-11e9-9340-cf4d50077811.png)

**Comment by joncampbell123** [comment]
Commenting out the keyboardLayout=US line seems to fix it.

**Comment by joncampbell123** [comment]
However running KEYB after boot does not cause the same issue.

**Comment by joncampbell123** [comment]
I think the problem is with the built-in EGA.CPX file.

If I modify the 14-line case of the CPI loader to add +2 to the font data offset, the font renders correctly. (?)

**Comment by lwchkg** [comment]
Why +2? Without a good explanation this is almost certainly more problems
than what it solves.

BTW, now I am even more puzzled. Why does not giving the keyboard layout
not giving problems? Isn't code page 437 already the default?

**Comment by joncampbell123** [comment]
If you don't specify a keyboard layout then it doesn't load any CPX/CPI files, and the problem does not occur.

DOSBox-X has 3 built-in EGA.CPX files, one for several sets of code pages.

**Comment by joncampbell123** [comment]
I'm beginning to think the problem is the built-in CPX/CPI file. The 14-line font seems to be too low in the character cell, as if it's the 16-line VGA font shifted up and truncated. Adding +2 breaks other parts of the console.

DOSBox-X and DOSBox SVN boot up in the US (code page 437) locale anyway.

**Comment by joncampbell123** [comment]
That probably wouldn't be an issue if NOBOMB.BAS rendered all 14 rows of the text instead of the top 12.

**Comment by joncampbell123** [comment]
Notice the character cell relative to the cursor. Top: VGA  Bottom: EGA

![command_000](https://user-images.githubusercontent.com/6245486/62681261-2502ea80-b96e-11e9-8243-c9c7dd11f95f.png)
![command_002](https://user-images.githubusercontent.com/6245486/62681268-27fddb00-b96e-11e9-817e-eb9029fec157.png)

**Comment by lwchkg** [comment]
So somehow we need to look at the fonts to see what's going on.

The bad news, is that the file is compressed by UPX. That does increase our
effort to decode them.

**Comment by joncampbell123** [comment]
@lwchkg I think DOSBox-X inherited the built-in CPI files from DOSBox SVN. It might be best to ask them where those came from. It might have in turn come from something else, probably FreeDOS.

**Comment by lwchkg** [comment]
The file appears to be added by this commit: https://sourceforge.net/p/dosbox/code-0/2715. So you might want to have a look.

**Comment by lwchkg** [comment]
BTW, your suspicion is correct. The copyright notices do point at Henrique Peron, and a web search reveals that to be ftp://salsa.net/pub/freedos/files/distributions/1.2/repos/pkg-html/cpidos.html.

The sad part is... why only 3 of the files are embedded, and which 3 are they. Again, I HATE THE USE OF UPX HERE, just to save 3 kb of data but to make the code smell. It's already past 2010...

**Comment by lwchkg** [comment]
Oh I was wrong. Those CPX are already compressed by UPX in FreeDOS. Readme: http://www.fdos.org/kernel/cpi/cpidos.htm

**Comment by lwchkg** [comment]
Just found the info. The files are ega.cpx, ega3.cpx and ega5.cpx from CPIDOS12.ZIP (the second oldest version). Now I'll try to decompress the files and compare that with the CPIDOS11.ZIP.

**Comment by lwchkg** [comment]
FYI: here's the decompressed fonts [CPIDOS.zip](https://github.com/joncampbell123/dosbox-x/files/3490108/CPIDOS.zip). (Basically decompressed by upx -d *.cpx)

**Comment by lwchkg** [comment]
I've decoded the information of ega.cpx. The characters in the font are indeed placed 1px lower than normal.

Here's the version used in DosBox.
![ega_v12](https://user-images.githubusercontent.com/4113719/62918200-85ac8000-bdd1-11e9-85ee-2963274cdd8d.png)

And here's version 3.0.
![ega_v30](https://user-images.githubusercontent.com/4113719/62918244-abd22000-bdd1-11e9-83a4-18a01471ed5b.png)

**Comment by lwchkg** [comment]
If you like to try decoding the files yourself, see https://github.com/lwchkg/cpifont_decode.

**Comment by lwchkg** [comment]
I have just inspected the CPI from MS-DOS, and they render the 8x14 characters at the same lower space. So it looks like that the 1px displacement is working as intended.

So we can close the issue now. BTW, this may be worthy of writing a FAQ, especially to D-Fend users.

![MSDOS_EGA](https://user-images.githubusercontent.com/4113719/62934853-2f9f0300-bdf8-11e9-8d16-9633483bc2fd.png)

**Comment by joncampbell123** [comment]
Thank you for confirming this.

Some games developers, especially independent ones, don't necessarily test their games against every use case and can easily miss problems like this.
