### ISSUE TITLE
Sound issues with "Titus the Fox: To Marrakech and Back"

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1200]
**Describe the bug**
1. The game fails to detect the SoundBlaster and only plays with PC speaker sound.
As described here: https://www.vogons.org/viewtopic.php?t=42616&p=408812, in mainline DOSBox the issue is with the cycles. As the person there says, at max cycles it uses PC speaker sound, while at a set 3000 cycles it uses OPL sound (confirmed on my computer as well), but in DOSBox-X the game uses PC speaker in both cases.

2. With PC speaker sound, the initial splash screen plays a continuous high-pitched tone. In mainline, the splash screen is silent.

Discovered while testing this SVN commit:
https://sourceforge.net/p/dosbox/code-0/3960/

The above commit when applied to DOSBox-X changes the PC speaker sound at the splash screen to instead be a continuous stuttering sound, but doesn't make it silent like mainline.

**To Reproduce**
1. Get "Titus the Fox: To Marrakech and Back"
2. Run `RUNME.BAT` to start the game.

**Expected behavior**
If SoundBlaster is available it should run with OPL music. If using PC speaker sound, the splash screen should probably be silent like in mainline.

**Environment (please complete the following information):**
 - Windows 10 64-bit
 - Using ec7a61f
 - Nothing unusual in dosbox.conf (also reproduced with completely default .conf)

**Comment by joncampbell123** [comment]
Will test.

The fact that it tests the card in a cycle-dependent manner, and supports PC speaker, suggests that it was made before Sound Blaster 16 was common.

Can you try sblaster=sbpro2, sblaster=sb2, etc. on your end?

**Comment by Allofich** [comment]
> Can you try sblaster=sbpro2, sblaster=sb2, etc. on your end?

Sure, will try now.

**Comment by Allofich** [comment]
Tried all the possible settings for `sbtype` including `none` and the pc speaker was used in all cases.

**Comment by joncampbell123** [comment]
Found the Adlib polling code:

    03B4:00001616 BA8803              mov  dx,0388
    03B4:00001619 B90020              mov  cx,2000
    03B4:0000161C EC                  in   al,dx
    03B4:0000161D 2460                and  al,60
    03B4:0000161F 752C                jne  0000164D ($+2c)        (no jmp)
    03B4:00001621 E2F9                loop 0000161C ($-7)

**Comment by joncampbell123** [comment]
So apparently the OPL emulation answers 00h at first, then E0h for the first loop (within 100 reads), which the game doesn't like.

If I force it past the first loop, it writes outp(0x388,0x04), outp(0x389,0x23), then loops for 0x9FFF cycles waiting for (inp(0x388) & 0x60) == 0x40.

    03B4:00001623 B80423              mov  ax,2304
    03B4:00001626 E87EFF              call 000015A7 ($-82)
    03B4:00001629 B9FF9F              mov  cx,9FFF
    03B4:0000162C EC                  in   al,dx
    03B4:0000162D 2460                and  al,60
    03B4:0000162F 3C40                cmp  al,40
    03B4:00001631 7404                je   00001637 ($+4)         (no jmp)
    03B4:00001633 E2F7                loop 0000162C ($-9)
    03B4:00001635 EB16                jmp  short 0000164D ($+16)  (down)

Remember 164Dh is the "give up" branch.

**Comment by joncampbell123** [comment]
The final test appears to be:

outp(0x388,04); outp(0x389,0x43);

Then wait for (inp(0x388) & 0x60) == 0x20.

    03B4:00001637 B80443              mov  ax,4304
    03B4:0000163A E86AFF              call 000015A7 ($-96)
    03B4:0000163D B9FF9F              mov  cx,9FFF
    03B4:00001640 EC                  in   al,dx
    03B4:00001641 2460                and  al,60
    03B4:00001643 3C20                cmp  al,20
    03B4:00001645 7404                je   0000164B ($+4)         (down)
    03B4:00001647 E2F7                loop 00001640 ($-9)
    03B4:00001649 EB02                jmp  short 0000164D ($+2)   (down)
    03B4:0000164B F8                  clc
    03B4:0000164C C3                  ret

164Bh is the "success" branch, returning with CF=0.

**Comment by joncampbell123** [comment]
If I use the debugger to force all three to pass, FM music plays.

**Comment by joncampbell123** [comment]
According to the OPL3 datasheet, register 04h holds RST, MT1, and MT2.

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Sound%20and%20Music/Adlib/FM/Yamaha%20YMF262%20FM%20Operator%20Type%20L3%20%28OPL3%29%20%281994%2d11%29%2epdf

So the first test is that MT1 and MT2 are not set and do not suddenly become set.

That ALSO means that if somehow the card were left in a state where MT1 and MT2 were set, the game would fail to detect Adlib.

**Comment by joncampbell123** [comment]
The reason the OPL emulation in DOSBox-X is failing the test is that a hack made for Wolfenstein 3D is enabled by default.

This hack makes the OPL2/3 timer bits "expire" (and bits set) if it sees 50 consecutive I/O reads from the OPL status port.

Disable the hack by adding:

[sblaster]
adlib force timer overflow on detect=false

On my end FM music now works even if cycles=10000

**Comment by joncampbell123** [comment]
Ironically it seems the I/O delay handling in DOSBox-X is good enough now the hack is no longer needed, Wolf3D works without the option.

**Comment by Allofich** [comment]
Confirmed. And amazing how quickly you managed to work that out!

**Comment by joncampbell123** [comment]
The obvious problem of writing such CPU cycle dependent code is that it still fails if the cycle count is above 15000 or so, which is probably why it doesn't work on anything past about a 486/33MHz.

By the way, it wouldn't hurt if the game developers thought to scroll the screen if you're some distance from the center of the screen so things don't just "pop out" suddenly and kill you.

**Comment by joncampbell123** [comment]
It doesn't appear to be checking for Sound Blaster, just Adlib. I don't see any writes to 220h-22Fh.

**Comment by Allofich** [comment]
Any ideas about the PC speaker high-pitched tone issue? Should I make a separate report for it?

**Comment by joncampbell123** [comment]
It used to be the PC speaker noise was caused by a failure to emulate mode 0 (or something like that) but that was fixed some time ago.

There's nothing out of the ordinary in programming the PC speaker here, however there's some odd behavior with port 61h.

LOG: write p61 b0
LOG: write p61 30
LOG: write p61 b0
LOG: write p61 30
; Here the game programs PIT timer 2 connected to the PC speaker
LOG: write p61 33

LOG: write p61 a3
LOG: write p61 23
LOG: write p61 b3
LOG: write p61 33

I'm not sure why it's playing with bits 5-7 of port 61h.
The only possible explanation might be that the game had to worry about whether or not it was on a VGA-based 286 with an XT type keyboard controller. Setting bit 7 clears the keyboard buffer on XT keyboards so another scan code can arrive. Bit 6 enables the keyboard.

**Comment by joncampbell123** [comment]
It's possible that by accident the test sets bit 0-1 and therefore enables both gates needed for the PC speaker to sound.

**Comment by joncampbell123** [comment]
Oh yes, that is definitely the kind of port 61h handling that a programmer would do if concerned about XT keyboards.

    03B4:00000D5A E460                in   al,60
    03B4:00000D5C 8AD8                mov  bl,al
    03B4:00000D5E E461                in   al,61
    03B4:00000D60 8AE0                mov  ah,al
    03B4:00000D62 0C80                or   al,80
    03B4:00000D64 E661                out  61,al
    03B4:00000D66 8AC4                mov  al,ah
    03B4:00000D68 E661                out  61,al
    03B4:00000D6A 881EC004            mov  [04C0],bl              ds:[04C0]=901C
    03B4:00000D6E 80FB01              cmp  bl,01
    03B4:00000D71 7506                jne  00000D79 ($+6)         (down)
    03B4:00000D73 2E803EB36B00        cmp  byte cs:[6BB3],00      cs:[6BB3]=0000
    03B4:00000D79 757E                jne  00000DF9 ($+7e)        (down)
    03B4:00000D7B B80300              mov  ax,0003
    03B4:00000D7E CD10                int  10

There's some code further down to compare the readback of 61h against various values and toggle bits.

**Comment by joncampbell123** [comment]
However according to this site, setting bit 7 resets a latch related to IRQ0?

https://www.tek-tips.com/viewthread.cfm?qid=258828

**Comment by joncampbell123** [comment]
The aformentioned code, including the part that sets bit 0-1 is in the IRQ1 keyboard handler! Which tells me... XT keyboard handling.

**Comment by joncampbell123** [comment]
The PC speaker beep seems intentional.

    03B4:000011B4 E85904              call 00001610 ($+459)
    03B4:000011B7 7219                jc   000011D2 ($+19)        (down)

    03B4:000011D2 B0B6                mov  al,B6
    03B4:000011D4 E643                out  43,al
    03B4:000011D6 E461                in   al,61
    03B4:000011D8 0C03                or   al,03
    03B4:000011DA E661                out  61,al

Writes port 43h to program PIT timer 2, set mode 3 (square wave), then switches on both PC speaker gates.

**Comment by joncampbell123** [comment]
Hold on though, write state == 3 is an internal DOSBox state that doesn't exist on real hardware. It can only be achieved from write state == 0 and writing the first byte.

The timer init sets the timer chip to write state == 3. Let me check...

**Comment by Allofich** [comment]
Might be that the only way to know for sure is to test on real hardware? I don't have real hardware to test with.

Anyway, no rush. I'm not dying to play this game with PC speaker sound or anything :). It's just a fun mystery to solve. Thank you for your attention to the issue and posting your findings. I enjoy reading them and probably others do as well.

**Comment by joncampbell123** [comment]
Hold on though... it's possible that programming the PIT timer, then outp(0x43,0xB6) without programming the counter might not produce any sound.

I'll go test this right now on the old 486 laptop, hold on.

**Comment by Allofich** [comment]
> I'll go test this right now on the old 486 laptop, hold on.

Oh, great! Looking forward to hearing what you find.

**Comment by joncampbell123** [comment]
Good news, that's exactly what happens.

On the laptop:

Enable beeper, beep is audible immediately:
    o 61,3

Write 43h in the same way the game does, WITHOUT writing a counter. Beeper is silent after this:
    o 43,b6

**Comment by joncampbell123** [comment]
However DOSBox-X it seems already emulates the behavior mentioned in the previous post.

**Comment by joncampbell123** [comment]
Yeah, it looks like it's intentional.

 413079733 ERROR PIT:port 43 B6
 413079748 ERROR PIT:port 40 write:0 state:3
 413079750 ERROR PIT:port 40 write:40 state:0

**Comment by joncampbell123** [comment]
The game does

    out 43h,b6h

Then does

    out 61h,03h

On real hardware, if you write a control word without writing a counter value, you will not get a beep. It doesn't matter if you write port 61h before or after putting the timer in that state, you will not get a beep.

DOSBox-X correctly emulates the case where you write port 61h before 43h, but does not correctly emulate the case of writing port 43h then port 61h (which is what the game does).

**Comment by joncampbell123** [comment]
Try the latest commit.

**Comment by joncampbell123** [comment]
It seems like once the game has initialized Adlib, it doesn't seem to matter anymore what the cycle count is, it detects it fine.

It could be that the game doesn't bother to reset the two timers on the OPL chip, so the timer tests always pass on faster hardware ONCE they have been triggered to start.

**Comment by Allofich** [comment]
Latest commit works for me, too.

I consider these issues solved and I'll close this in a while. One minor thing I did notice, is that I can hear a soft "pop" as the PC speaker turns on while the splash screen is starting to show. Is this expected?

**Comment by joncampbell123** [comment]
I could double check by running the game on the 486, but I expect that. According to what I understand, the 8254 in mode 3 with the clock gate off will set the output HIGH. Writing a control word without a counter is just about the same as turning off the clock gate (as far as I know). So if the output is HIGH (not oscillating) and you set the bits in port 61h to un-gate the output, then you should hear a slight "pop" from the speaker.

**Comment by joncampbell123** [comment]
I just confirmed on the 486 laptop:

outp(0x61,0x00);
outp(0x43,0xB6);

Then an I/O write to un-gate the speaker makes an audible "pop" from the speaker, though no tone.

outp(0x61,0x03);

Another pop if the speaker is turned off.

outp(0x61,0x00);

DOSBox-X behavior matches real hardware.

**Comment by Allofich** [comment]
Thanks for taking the extra step to check that. Looks like things shaped up nicely.
