### ISSUE TITLE
Gravis Ultrasound does not work with "The Elder Scrolls II: Daggerfall"

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1206]
**Describe the bug**
`Gravis Ultrasound` (and `Gravis Ultrasound Max`) are available as options in the sound setup program for sound effects and MIDI music, but they don't work correctly.

When Gravis Ultrasound is selected for sound effects, and "Test Digital" is selected in the setup program, the test sound plays, but sounds very jittery.

When Gravis Ultrasound is selected for music and "Test MIDI" is selected, it fails with `ERROR: MIDI driver could not initialize.`

The exact same symptoms happen with DOSBox SVN, and with both the full and demo versions of Daggerfall (the newer demo, there is also an older demo that I'm not talking about here).

**To Reproduce**
1. Install "The Elder Scrolls II: Daggerfall" or the demo version.
2. Run `SETUP.EXE.` 
3. Select `Gravis Ultrasound` for your "Digital Device" and your "MIDI Device".
4. Use `Test Digital` or `Test MIDI` and observe the problems mentioned above.

**Expected behavior**
Should presumably work and sound normal.

**Environment (please complete the following information):**
 - Windows 10 64-bit
 - Commit abbe05b (also, same behavior before and after changes in the PR https://github.com/joncampbell123/dosbox-x/commit/6977dcfb89c9885dd7464e531c30de23abf4dc98)
 - Used configuration:
sbtype                           = none
gus                                = true
gusbase                         = 220
gusirq                            = 7
gusdma                         = 1 (also tried 11, which the program seems to default to)

**Additional context**
Tried some of the available hack settings in dosbox.conf that say they can help with games/demos, but didn't have any luck.
Nothing in the console/log.

**Comment by joncampbell123** [comment]
Did you try:

pic unmask irq=true
startup initialized=true

**Comment by joncampbell123** [comment]
Actually, considering how most games use the Gravis for music, did you try installing the Gravis Ultrasound drivers into C:\ULTRASND first?

**Comment by joncampbell123** [comment]
Copying C:\ULTRASND does not help. Running ULTRAMID doesn't help.
The game seems to have reliability issues with Gravis Ultrasound digital audio.
I'm told the game came out late enough that GUS use was becoming less common.

**Comment by joncampbell123** [comment]
Also, the same artifacts you hear in the "test audio" function of the sound card program ALSO happen under DOSBox SVN.

**Comment by Allofich** [comment]
> Did you try:
pic unmask irq=true
startup initialized=true

Just tried these now, but no difference.

> Also, the same artifacts you hear in the "test audio" function of the sound card program ALSO happen under DOSBox SVN.

Yes, I also get the same sound artifacts and MIDI error with DOSBox SVN.

**Comment by joncampbell123** [comment]
I've noticed that the game won't talk to ULTRAMID or play music with the GUS even if I copy the ULTRASND directory from another DOSBox-X test set.

Also, Gravis Ultrasound audio support seems to randomly crash the game. It's evident by the memory corruption that shows up on the screen.

**Comment by joncampbell123** [comment]
However the GUS related issues do not happen in DOSBox SVN.

**Comment by joncampbell123** [comment]
GUS related crashes can be avoided by disabling the hard disk I/O delay.

**Comment by joncampbell123** [comment]
Actually, running LOADFIX before the game fixes GUS crashing as well.
That makes it the first 32-bit protected mode game where LOADFIX has any effect :)

**Comment by fdegni** [comment]
I am following it, thanks as really interested about the way to get GRAVIS at work.

**Comment by Allofich** [comment]
Just to report something that didn't work, in case it's helpful:
There is a file in the Daggerfall directory called `HMIDRV.386` that contains the text
```
HMI DMA Driver For Gravis Ultrasound
Copyright 1992, Human Machine Interfaces
```

The game "Descent" also has a `HMIDRV.386` file that differs a little bit, and Descent works fine with Gravis Ultrasound in DOSBox-X. I tried switching the `HMIDRV.386` files, but no luck. Descent worked fine with both versions of the file, and Daggerfall had the same problems with both versions of the file.

**Comment by Allofich** [comment]
On searching, looks like this may just be an issue with the game, or perhaps more specifically, with Human Machine Interfaces (HMI) sound setup.

https://www.vogons.org/viewtopic.php?t=21350
Two people here claim what sounds like the same thing happens with Daggerfall on real GUS boards.

https://www.vogons.org/viewtopic.php?t=24541
Here someone describes the same issue in "The Terminator: Future Shock"/"Skynet" (same or similar game engine), and also how to work around the issue for Daggerfall. I can confirm it works for the music (sound is still messed up).

https://www.vogons.org/viewtopic.php?f=33&t=58102
Someone describing what sounds like maybe the same issue with another game using "HMI".

Anyway, the two people claiming to have what sounds like the same problem on real GUS boards is pretty convincing to me, so I'm okay with closing this.

**Comment by joncampbell123** [comment]
If the errant behavior matches real hardware, then I'm OK with closing the issue and leaving it at that.

The closed issue will at least serve as documentation on what is going on.
