### ISSUE TITLE
INT 10h AH=12h BL=10h does not satisfy Thexder MCGA check

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1207]
Thexder chooses a binary to run, EGA (MAINEG), or MCGA (MAINPS).

When machine=mcga, it is still choosing MAINEG.

While DOSBox-X passes the PS/2 machine type IDs checks (0xFA), the response to INT 10h AH=12h BL=10h is not satisfactory.

Code in question within game:

    0302:00000377 32C0                xor  al,al
    0302:00000379 B310                mov  bl,10
    0302:0000037B B7FF                mov  bh,FF
    0302:0000037D B10F                mov  cl,0F
    0302:0000037F B412                mov  ah,12
    0302:00000381 CD10                int  10
    0302:00000383 80F90C              cmp  cl,0C
    0302:00000386 730D                jnc  00000395 ($+d)         (down)
    0302:00000388 80FB03              cmp  bl,03
    0302:0000038B 7708                ja   00000395 ($+8)         (no jmp)
    0302:0000038D 0AFF                or   bh,bh
    0302:0000038F 7504                jne  00000395 ($+4)         (no jmp)
    0302:00000391 8D16CD02            lea  dx,[02CD]              ds:[02CD]=616D
    0302:00000395 E82C00              call 000003C4 ($+2c)

DS:DX at 395h is an ASCIIZ string indicating which file to run.

DS:2C6 = "mainjr"
DS:2CD = "maineg"
DS:2D4 = "mainps"

**Comment by joncampbell123** [comment]
Ralph Brown Interrupt List ref:

http://www.ctyme.com/intr/rb-0162.htm

**Comment by joncampbell123** [comment]
Note that after a compare, CF=1 if the first operand was less than the second. It's like a SUB (subtract) but without putting the result in the destination register.

**Comment by sikthehedgehog** [comment]
If I recall correctly, Thexder prioritizes EGA over MCGA, so the only way it'll ever use mode 13h is on an actual MCGA (it'll use 640×200 on VGA instead). This is because it's a port from a system that used 640×200 so the game attempts to use the most "accurate" mode available.

In other words, you actually need to emulate a system without the EGA modes to get it to use mode 13h.

**Comment by sikthehedgehog** [comment]
Quick remark: no idea if it's actually using 640×200 or 640×400 with pixel doubling. But point stands, it only picks MCGA if it can't find EGA modes (the MCGA support is there only for the sake of PS/2).

**Comment by joncampbell123** [comment]
The EGA modes are not supposed to exist when machine=mcga and they don't, however the response to this BIOS call makes Thexder think they do. That's the bug.

**Comment by joncampbell123** [comment]
A commit has been pushed that makes this call fail to respond in MCGA mode, which is enough to satisfy Thexder.
