### ISSUE TITLE
Policenauts — PC-9821 AVSDRV.SYS audio

### ISSUE THREAD

**Issue by giulioz** [joncampbell123/dosbox-x#1210]
I'm investigating about running Policenauts (PC-9821) on Dosbox-x, in PC-98 mode.
There seems to be some driver issues, the game refuse to launch.

![error](http://i.imgur.com/2n6W4gR.png)

That translates to: the PCM driver AVGSDRV.SYS isn't installed.
This is referring to AVSDRV.SYS driver file, for the Qvision PCM audio card. The file is present on the game floppy, but of course it gives these errors on the log:
```
LOG:  614255129 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1684
LOG: PC-98 INT 1Ah unknown call AX=AF0B BX=12B8 CX=000D DX=0000 SI=0000 DI=0000 DS=0963 ES=0963
```

Running the game itself logs this:
```
LOG: PC-98 INT 18 AH=42h CH=0xE0
LOG: PC-98 port 68h unknown command 0x02
LOG: PC-98 INT stub unknown call AX=1100 BX=0A66 CX=0018 DX=0F94 SI=2EF8 DI=0F94 DS=0000 ES=052F
LOG: PC-98 INT stub unknown call AX=0000 BX=0510 CX=0A66 DX=7002 SI=24CC DI=0FB0 DS=7202 ES=018E
```

For the record, this is the CONFIG.SYS file on the game boot floppy:
```
LASTDRIVE=Z
FILES=20
BUFFERS=10
SHELL=A:\COMMAND.COM a: /P /e:1024
DEVICE=A:\HIMEM.SYS
DEVICE=A:\EMM386.EXE
DEVICE=A:\NECCD.SYS /D:CD_101
DEVICE=A:\AVSDRV.SYS
DOS=HIGH
```

**Comment by giulioz** [comment]
Some links for more info:
[http://fullmotionvideo.free.fr/phpBB3/viewtopic.php?f=1&t=965](http://fullmotionvideo.free.fr/phpBB3/viewtopic.php?f=1&t=965)

[https://www.youtube.com/watch?v=pOYh92usnhk](https://www.youtube.com/watch?v=pOYh92usnhk)

NekoProject seems to be able to emulate the game.

**Comment by joncampbell123** [comment]
DOSBox-X has a DEVICE command that can load MS-DOS device drivers in a minimal fashion.

**Comment by giulioz** [comment]
Already tried, loading the driver with `device` doesn't solve the problem, even with different driver versions.
The driver complaints that it's a block device and must be loaded with CONFIG.SYS, and logs this on console:
```
LOG:   40850613 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1684
LOG: PC-98 INT 1Ah unknown call AX=AF0B BX=12B8 CX=000D DX=0000 SI=0000 DI=0000 DS=0963 ES=0963
```

**Comment by yksoft1** [comment]
There are multiple versions of AVSDRV.sys existed, in MS-DOS 5.0A/5.0A-H, MS-DOS 6.2, Driver disk of PC-9801-86 and etc. 
I think DOSBox-X emulates a Speak Board (YM2608 PCM, PC-9801-73 compatible, no PC-9801-86 PCM) and won't work with programs that requires 86PCM.

**Comment by giulioz** [comment]
Any chance to have 86PCM board compatibility?
I might try to port NekoProject code...

**Comment by cracyc** [comment]
I think that it works with the -118 and a matching verison of avsdrv.sys but the mouth animations only work with the -86 and a specific avsdrv.

**Comment by joncampbell123** [comment]
@giulioz 86PCM board compatibility would be welcome, let me know if you have any questions on how to mod the DOSBox-X source code to accomplish it. Which games use it?

**Comment by joncampbell123** [comment]
@giulioz When I ported over the FM board emulation as it is now I made sure to add a header that adds just enough Neko Project II programming environment so that porting additional code isn't too difficult. What the wrapper has yet to support at this time is anything related to DMA that might be required for -118 board emulation.
