### ISSUE TITLE
The Legend of Heroes III (PC-98) master disk detection failure [TASK: Examine real PC-98 hardware, mem 60:6C, with and without floppy drive]

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1226]
Some disassembly:

    ; loop while waiting for input
    163C:00000311 E80EFE              call 00000122 ($-1f2)
    163C:00000314 750C                jne  00000322 ($+c)         (down)
    163C:00000316 803E441B00          cmp  byte [1B44],00         ds:[1B44]=000F
    163C:0000031B 75F4                jne  00000311 ($-c)         (up)
    ; called when menu redraws focus rectangle
    163C:0000031D E84F58              call 00005B6F ($+584f)
    ; keypress handling
    163C:00000322 8AE0                mov  ah,al
    163C:00000324 226405              and  ah,[si+05]             ds:[17DF]=0063
    163C:00000327 740C                je   00000335 ($+c)         (down)
    163C:00000329 3AC4                cmp  al,ah
    163C:0000032B 7429                je   00000356 ($+29)        (down)
    163C:0000032D 837C0800            cmp  word [si+08],0000      ds:[17E2]=0000
    163C:00000331 7423                je   00000356 ($+23)        (down)
    163C:00000333 EB06                jmp  short 0000033B ($+6)   (down)
    163C:00000335 837C0800            cmp  word [si+08],0000      ds:[17E2]=0000
    163C:00000339 74DB                je   00000316 ($-25)        (up)
    163C:0000033B FF5408              call near word [si+08]      ds:[17E2]=0000
    163C:0000033E 7206                jc   00000346 ($+6)         (no jmp)
    163C:00000340 22C0                and  al,al
    163C:00000342 7515                jne  00000359 ($+15)        (no jmp)
    163C:00000344 EBD0                jmp  short 00000316 ($-30)  (up)
    163C:00000346 C606421B14          mov  byte [1B42],14         ds:[1B42]=0014
    163C:0000034B E84701              call 00000495 ($+147)
    163C:0000034E E81E58              call 00005B6F ($+581e)
    163C:00000351 E8D858              call 00005C2C ($+58d8)
    163C:00000354 EB9D                jmp  short 000002F3 ($-63)  (up)
    163C:00000356 224405              and  al,[si+05]             ds:[17DF]=0063
    163C:00000359 8AE0                mov  ah,al
    163C:0000035B 8A440B              mov  al,[si+0B]             ds:[17E5]=2500
    163C:0000035E F6C420              test ah,20
    163C:00000361 7403                je   00000366 ($+3)         (down)
    163C:00000363 E9C600              jmp  0000042C ($+c6)        (down)
    ...
    ; enter key handler
    163C:0000042C 88440B              mov  [si+0B],al             ds:[17E5]=2500
    163C:0000042F C606427905          mov  byte [7942],05         ds:[7942]=00F3
    163C:00000434 E88501              call 000005BC ($+185)
    163C:00000437 E83557              call 00005B6F ($+5735)
    163C:0000043A 8A440B              mov  al,[si+0B]             ds:[17E5]=2500
    163C:0000043D E87C01              call 000005BC ($+17c)
    163C:00000440 BA0103              mov  dx,0301
    163C:00000443 B403                mov  ah,03
    163C:00000445 CD42                int  42
    163C:00000447 33C0                xor  ax,ax
    163C:00000449 8A440B              mov  al,[si+0B]             ds:[17E5]=2500
    163C:0000044C 02440A              add  al,[si+0A]             ds:[17E4]=0000
    163C:0000044F EB1C                jmp  short 0000046D ($+1c)  (down)
    ...
    163C:0000046D C9                  leave
    163C:0000046E 5F                  pop  di
    163C:0000046F C3                  ret
    ...
    163C:0000524A 6A02                push 0002
    163C:0000524C 6A30                push 0030
    163C:0000524E 68B42C              push 2CB4
    163C:00005251 6A00                push 0000
    163C:00005253 E85410              call 000062AA ($+1054)	; erase dialog from screen
    163C:00005256 E81609              call 00005B6F ($+916)		; delay (?)
    163C:00005259 E86709              call 00005BC3 ($+967)		; erase dialog from screen (?)
    163C:0000525C C3                  ret
    ...
    163C:000051E6 B4FF                mov  ah,FF
    163C:000051E8 B00F                mov  al,0F
    163C:000051EA E87000              call 0000525D ($+70)		; mystery master disk check
    163C:000051ED 7308                jnc  000051F7 ($+8)         (down)
    163C:000051EF BE261C              mov  si,1C26
    163C:000051F2 E82500              call 0000521A ($+25)
    163C:000051F5 EBEF                jmp  short 000051E6 ($-11)  (up)
    163C:000051F7 C3                  ret
    ...
    ; mystery master disk check (AH=?? AL=??)
    163C:0000525D BEC47D              mov  si,7DC4
    163C:00005260 8CDA                mov  dx,ds
    163C:00005262 C1E204              shl  dx,04
    163C:00005265 03D6                add  dx,si
    163C:00005267 81C2FF02            add  dx,02FF
    163C:0000526B 7303                jnc  00005270 ($+3)         (down)
    163C:0000526D BEC480              mov  si,80C4
    163C:00005270 89363207            mov  [0732],si              ds:[0732]=7DC4
    163C:00005274 8944FE              mov  [si-02],ax             ds:[1C24]=C85E
    163C:00005277 32FF                xor  bh,bh
    163C:00005279 8ADC                mov  bl,ah			; BX = AH (zero extend)
    163C:0000527B 32E4                xor  ah,ah
    163C:0000527D 8BF8                mov  di,ax			;   \_/
    163C:0000527F 03FF                add  di,di			; DI = AL (zero extend) * 2u
    163C:00005281 8BBD6810            mov  di,[di+1068]           	; DI = WORD PTR DS:[(AL*2u)+1068h]
    163C:00005285 0BFF                or   di,di			; IF DI == 0 (NULL) JMP 52B5h (which is STC+RET)
    163C:00005287 742C                je   000052B5 ($+2c)        	;       ^
    163C:00005289 80FBFF              cmp  bl,FF			; IF BL != 0xFF (BL = AH on entry, see 5279h) JMP 52B7h
    163C:0000528C 7529                jne  000052B7 ($+29)        	;	^
    163C:0000528E BBA87D              mov  bx,7DA8			; BX = buffer at 7DA8h
    163C:00005291 8B0EA67D            mov  cx,[7DA6]              	; CX = length from WORD PTR DS:[7DA6h]
    163C:00005295 E31E                jcxz 000052B5 ($+1e)        	; IF CX == 0 JMP 52B5h (which is STC+RET)

    163C:00005297 8A07                mov  al,[bx]                	; AL = BYTE PTR DS:[BX]
    163C:00005299 8AE0                mov  ah,al			; ...
    163C:0000529B 80E4F0              and  ah,F0			; AH = AL & 0xF0
    163C:0000529E 80FC90              cmp  ah,90			; IF AH != 0x90 JMP 52B2h (continue)
    163C:000052A1 750F                jne  000052B2 ($+f)         	;       ^
    163C:000052A3 A808                test al,08			; IF AL & 8 != 0 JMP 52B2h (continue)
    163C:000052A5 750B                jne  000052B2 ($+b)         	;	^
    163C:000052A7 57                  push di
    163C:000052A8 53                  push bx
    163C:000052A9 51                  push cx
    163C:000052AA E81200              call 000052BF ($+12)
    163C:000052AD 59                  pop  cx
    163C:000052AE 5B                  pop  bx
    163C:000052AF 5F                  pop  di
    163C:000052B0 730C                jnc  000052BE ($+c)         	; IF CF=0 (CALL 52BFh returned with CF=0) JMP 52BEh
    163C:000052B2 43                  inc  bx			; ...
    163C:000052B3 E2E2                loop 00005297 ($-1e)		; BX++, IF --CX != 0 JMP 5297h

    163C:000052B5 F9                  stc
    163C:000052B6 C3                  ret				; RET (CF=1)

    163C:000052B7 8A87A87D            mov  al,[bx+7DA8]           	; AL = BYTE PTR DS:[BX+7DA8h]  (BX = AH, see 5279h)
    163C:000052BB E80100              call 000052BF ($+1)		; store AL, copy some values from structs *DS:DI to *DS:SI, CLC+RET
    163C:000052BE C3                  ret				; RET (CF=0)

    163C:000052BF 8844FF              mov  [si-01],al             ds:[1C25]=BEC8
    163C:000052C2 8B4504              mov  ax,[di+04]             ds:[10EC]=5AF4
    163C:000052C5 89840003            mov  [si+0300],ax           ds:[1F26]=1F4E
    163C:000052C9 8B450A              mov  ax,[di+0A]             ds:[10F2]=F83C
    163C:000052CC 89840203            mov  [si+0302],ax           ds:[1F28]=2512
    163C:000052D0 F8                  clc
    163C:000052D1 C3                  ret

**Comment by joncampbell123** [comment]
The 920:A5A table is copied from 163C:267A.

    163C:0000009A E8B518              call 00001952 ($+18b5)

    163C:00001952 B0FF                mov  al,FF
    163C:00001954 BB7C26              mov  bx,267C
    163C:00001957 E890E7              call 000000EA ($-1870)
    163C:0000195A 7321                jnc  0000197D ($+21)        (down)
    163C:0000195C BE6B20              mov  si,206B
    163C:0000195F FEC8                dec  al
    163C:00001961 7403                je   00001966 ($+3)         (no jmp)
    163C:00001963 BE5620              mov  si,2056
    163C:00001966 B200                mov  dl,00
    163C:00001968 B80709              mov  ax,0907
    163C:0000196B CD40                int  40
    163C:0000196D 68066E              push 6E06
    163C:00001970 56                  push si
    163C:00001971 E82EF1              call 00000AA2 ($-ed2)
    163C:00001974 E899F9              call 00001310 ($-667)
    163C:00001977 E824EE              call 0000079E ($-11dc)
    163C:0000197A E933F4              jmp  00000DB0 ($-bcd)       (up)
    163C:0000197D 32C0                xor  al,al
    163C:0000197F 86C4                xchg ah,al
    163C:00001981 A37A26              mov  [267A],ax              ds:[267A]=0000
    163C:00001984 BA4E20              mov  dx,204E
    163C:00001987 B8003D              mov  ax,3D00
    163C:0000198A CD21                int  21
    163C:0000198C 7305                jnc  00001993 ($+5)         (down)
    163C:0000198E BE8A20              mov  si,208A
    163C:00001991 EBD3                jmp  short 00001966 ($-2d)  (up)
    163C:00001993 8BD8                mov  bx,ax
    163C:00001995 B43E                mov  ah,3E
    163C:00001997 CD21                int  21
    163C:00001999 B419                mov  ah,19
    163C:0000199B CD21                int  21
    163C:0000199D A29626              mov  [2696],al              ds:[2696]=0100
    163C:000019A0 33DB                xor  bx,bx
    163C:000019A2 8AD8                mov  bl,al
    163C:000019A4 81C37C26            add  bx,267C
    163C:000019A8 8A07                mov  al,[bx]                [illegal]
    163C:000019AA A29826              mov  [2698],al              ds:[2698]=9190
    163C:000019AD 24F0                and  al,F0
    163C:000019AF 3C90                cmp  al,90
    163C:000019B1 7405                je   000019B8 ($+5)         (no jmp)
    163C:000019B3 C606BA2601          mov  byte [26BA],01         ds:[26BA]=0000
    163C:000019B8 B415                mov  ah,15
    163C:000019BA CD40                int  40

    163C:000019BC 06                  push es
    163C:000019BD 8EC2                mov  es,dx
    163C:000019BF 8BFE                mov  di,si
    163C:000019C1 B90E00              mov  cx,000E
    163C:000019C4 BE7A26              mov  si,267A
    163C:000019C7 F3A5                repe movsw            ; DS:SI = 163C:267A ES:DI = 0920:0A5A
    163C:000019C9 07                  pop  es
    163C:000019CA C3                  ret

**Comment by joncampbell123** [comment]
It may be related to the BIOS data area 0x400-0x5FF since it is consistent in DOSBox-X regardless whether you boot into a guest OS or run it directly. Reportedly this works 100% fine in Neko Project II.

**Comment by joncampbell123** [comment]
Does not appear to be related to the BIOS data area.

**Comment by joncampbell123** [comment]
This might be relevant, though booting the HDI in DOSBox-X does not get any different results.

    163C:000004D1 B86000              mov  ax,0060
    163C:000004D4 8EC0                mov  es,ax
    163C:000004D6 8CC8                mov  ax,cs
    163C:000004D8 8ED8                mov  ds,ax
    163C:000004DA 836614BF            and  word [bp+14],FFBF      ss:[2980]=7206
    163C:000004DE BEF404              mov  si,04F4
    163C:000004E1 BF0400              mov  di,0004
    163C:000004E4 B90400              mov  cx,0004
    163C:000004E7 F2A7                repne cmpsw
    163C:000004E9 7504                jne  000004EF ($+4)         (down)

    ; REPNE CMPSW
    ; DS:SI 163C:04F4
    ; ES:DI 0060:0004
    
    163C:000004F4 81 99 91 90 96 EC 81 99 E8 97 01 E8 B9 01 E8 0B  ................

**Comment by joncampbell123** [comment]
Version check:

    163C:00000182 B430                mov  ah,30
    163C:00000184 CD21                int  21
    163C:00000186 3C02                cmp  al,02
    163C:00000188 740C                je   00000196 ($+c)         (no jmp)
    163C:0000018A 3C03                cmp  al,03
    163C:0000018C 7408                je   00000196 ($+8)         (no jmp)
    163C:0000018E 3C04                cmp  al,04
    163C:00000190 7404                je   00000196 ($+4)         (no jmp)
    163C:00000192 3C05                cmp  al,05
    163C:00000194 7503                jne  00000199 ($+3)         (down)
    163C:00000196 A25E04              mov  [045E],al              ds:[045E]=0000
    163C:00000199 C3                  ret

**Comment by joncampbell123** [comment]
Irrelevant check for high resolution displays:

    163C:0000019D 33C0                xor  ax,ax
    163C:0000019F 8ED8                mov  ds,ax
    163C:000001A1 F606010508          test byte [0501],08         ds:[0501]=E801
    163C:000001A6 7430                je   000001D8 ($+30)        (down)
    163C:000001A8 33C0                xor  ax,ax
    163C:000001AA B112                mov  cl,12
    163C:000001AC CDDC                int  DC

**Comment by joncampbell123** [comment]
Here's something that pokes directly into DOS kernel memory.

    163C:00000281 33C9                xor  cx,cx
    163C:00000283 B86000              mov  ax,0060
    163C:00000286 8EC0                mov  es,ax
    163C:00000288 BB6C00              mov  bx,006C
    163C:0000028B 803E6A0400          cmp  byte [046A],00         ds:[046A]=FF00
    163C:00000290 740A                je   0000029C ($+a)         (down)
    163C:00000292 06                  push es
    163C:00000293 C41E6004            les  bx,[0460]              ds:[0460]=0026
    163C:00000297 268B5FFC            mov  bx,es:[bx-04]          es:[0068]=0000
    163C:0000029B 07                  pop  es
    163C:0000029C 803E6A0401          cmp  byte [046A],01         ds:[046A]=FF00
    163C:000002A1 7418                je   000002BB ($+18)        (down)
    163C:000002A3 53                  push bx
    163C:000002A4 8AD9                mov  bl,cl
    163C:000002A6 FEC3                inc  bl
    163C:000002A8 B80944              mov  ax,4409
    163C:000002AB CD21                int  21
    163C:000002AD 5B                  pop  bx
    163C:000002AE 720B                jc   000002BB ($+b)         (no jmp)
    163C:000002B0 F7C20010            test dx,1000
    163C:000002B4 7405                je   000002BB ($+5)         (down)
    163C:000002B6 B004                mov  al,04
    163C:000002B8 E9BF00              jmp  0000037A ($+bf)        (down)
    163C:000002BB 80F910              cmp  cl,10
    163C:000002BE 7C03                jl   000002C3 ($+3)         (no jmp)
    163C:000002C0 E98500              jmp  00000348 ($+85)        (down)
    163C:000002C3 268A07              mov  al,es:[bx]             es:[006C]=0000
    163C:000002C6 3C34                cmp  al,34
    163C:000002C8 741D                je   000002E7 ($+1d)        (down)
    163C:000002CA 3C70                cmp  al,70
    163C:000002CC 727A                jc   00000348 ($+7a)        (no jmp)
    163C:000002CE 3C80                cmp  al,80
    163C:000002D0 7244                jc   00000316 ($+44)        (no jmp)
    163C:000002D2 3C88                cmp  al,88
    163C:000002D4 726A                jc   00000340 ($+6a)        (no jmp)
    163C:000002D6 3C90                cmp  al,90
    163C:000002D8 720D                jc   000002E7 ($+d)         (no jmp)
    163C:000002DA 3CA0                cmp  al,A0
    163C:000002DC 720E                jc   000002EC ($+e)         (no jmp)
    163C:000002DE 3CB0                cmp  al,B0
    163C:000002E0 7262                jc   00000344 ($+62)        (no jmp)
    163C:000002E2 32C0                xor  al,al
    163C:000002E4 E99300              jmp  0000037A ($+93)        (down)
    163C:000002E7 B003                mov  al,03
    163C:000002E9 E98E00              jmp  0000037A ($+8e)        (down)
    163C:000002EC 803C00              cmp  byte [si],00           ds:[046C]=0000
    163C:000002EF 75F6                jne  000002E7 ($-a)         (no jmp)
    163C:000002F1 8BD1                mov  dx,cx
    163C:000002F3 8AC8                mov  cl,al
    163C:000002F5 80E103              and  cl,03
    163C:000002F8 B401                mov  ah,01
    163C:000002FA E302                jcxz 000002FE ($+2)         (down)
    163C:000002FC D2E4                shl  ah,cl
    163C:000002FE 06                  push es
    163C:000002FF 33C9                xor  cx,cx
    163C:00000301 8EC1                mov  es,cx
    163C:00000303 8BCA                mov  cx,dx
    163C:00000305 2622265C05          and  ah,es:[055C]           es:[055C]=0000
    163C:0000030A 2622268804          and  ah,es:[0488]           es:[0488]=0000
    163C:0000030F 07                  pop  es
    163C:00000310 7451                je   00000363 ($+51)        (down)
    163C:00000312 0C08                or   al,08
    163C:00000314 EB64                jmp  short 0000037A ($+64)  (down)
    163C:00000316 803C00              cmp  byte [si],00           ds:[046C]=0000
    163C:00000319 75CC                jne  000002E7 ($-34)        (no jmp)
    163C:0000031B 8BD1                mov  dx,cx
    163C:0000031D 8AC8                mov  cl,al
    163C:0000031F 80E103              and  cl,03
    163C:00000322 B410                mov  ah,10
    163C:00000324 E302                jcxz 00000328 ($+2)         (down)
    163C:00000326 D2E4                shl  ah,cl
    163C:00000328 06                  push es
    163C:00000329 33C9                xor  cx,cx
    163C:0000032B 8EC1                mov  es,cx
    163C:0000032D 8BCA                mov  cx,dx
    163C:0000032F 2622265D05          and  ah,es:[055D]           es:[055D]=0000
    163C:00000334 2622268804          and  ah,es:[0488]           es:[0488]=0000
    163C:00000339 07                  pop  es
    163C:0000033A 7427                je   00000363 ($+27)        (down)
    163C:0000033C 0C08                or   al,08
    163C:0000033E EB3A                jmp  short 0000037A ($+3a)  (down)
    163C:00000340 B001                mov  al,01
    163C:00000342 EB36                jmp  short 0000037A ($+36)  (down)
    163C:00000344 B002                mov  al,02
    163C:00000346 EB32                jmp  short 0000037A ($+32)  (down)
    163C:00000348 C60400              mov  byte [si],00           ds:[046C]=0000
    163C:0000034B 803E5E0403          cmp  byte [045E],03         ds:[045E]=0005
    163C:00000350 722A                jc   0000037C ($+2a)        (no jmp)
    163C:00000352 8AC1                mov  al,cl
    163C:00000354 E83300              call 0000038A ($+33)
    163C:00000357 3C40                cmp  al,40
    163C:00000359 7421                je   0000037C ($+21)        (down)
    163C:0000035B 3C50                cmp  al,50
    163C:0000035D 751D                jne  0000037C ($+1d)        (no jmp)
    163C:0000035F B005                mov  al,05
    163C:00000361 EB17                jmp  short 0000037A ($+17)  (down)
    163C:00000363 E84800              call 000003AE ($+48)
    163C:00000366 7212                jc   0000037A ($+12)        (no jmp)
    163C:00000368 B404                mov  ah,04
    163C:0000036A CD1B                int  1B
    163C:0000036C 720C                jc   0000037A ($+c)         (no jmp)
    163C:0000036E 80FC60              cmp  ah,60
    163C:00000371 7407                je   0000037A ($+7)         (down)
    163C:00000373 E86300              call 000003D9 ($+63)
    163C:00000376 7202                jc   0000037A ($+2)         (no jmp)
    163C:00000378 B006                mov  al,06
    163C:0000037A 8804                mov  [si],al                ds:[046C]=0000
    163C:0000037C 46                  inc  si
    163C:0000037D 43                  inc  bx
    163C:0000037E FEC1                inc  cl
    163C:00000380 3A0E6804            cmp  cl,[0468]              ds:[0468]=1A1A
    163C:00000384 7303                jnc  00000389 ($+3)         (down)
    163C:00000386 E913FF              jmp  0000029C ($-ed)        (up)
    163C:00000389 C3                  ret
    163C:0000038A 56                  push si
    163C:0000038B 06                  push es
    163C:0000038C B451                mov  ah,51
    163C:0000038E 2E803E5E0404        cmp  byte cs:[045E],04      cs:[045E]=0005
    163C:00000394 7202                jc   00000398 ($+2)         (no jmp)
    163C:00000396 B458                mov  ah,58
    163C:00000398 F6E4                mul  ah
    163C:0000039A 2EC4366004          les  si,cs:[0460]           cs:[0460]=0026
    163C:0000039F 8D7416              lea  si,[si+16]             ds:[0482]=0000
    163C:000003A2 26C434              les  si,es:[si]             es:[046C]=0000
    163C:000003A5 03F0                add  si,ax
    163C:000003A7 268A4444            mov  al,es:[si+44]          es:[04B0]=0000
    163C:000003AB 07                  pop  es
    163C:000003AC 5E                  pop  si
    163C:000003AD C3                  ret

**Comment by joncampbell123** [comment]
Another workaround that can be applied through the debugger prior to starting the game:

SM 60 6C 90 90 0 0

Though it's *supposed* to be F0/F1 etc. according to http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20NEC%20PC%2d98/Collections/Undocumented%209801%2c%209821%20Volume%202%20%28webtech.co.jp%29/memdos%2etxt

**Comment by joncampbell123** [comment]
Booting the HDI image, 60:6C is A0 00 00 00. So the documentation is WRONG, it's the same numbers used through INT 1Bh. Letting MS-DOS boot but then using the debugger to enter "SM 60 6C 90 0 0 0" prior to the game starting has the same effect.

**Comment by joncampbell123** [comment]
It likes:

90 00 00 00
90 A0 00 00

It does not like:

90 91 A0 00
90 91 00 00

**Comment by joncampbell123** [comment]
Um... mounting the master FDI and the HDI results in:

80 A0 00 00

80h is still a hard disk. Wrong.

**Comment by joncampbell123** [comment]
Latest commit changes it to 80 A0 90, which is better.

**Comment by joncampbell123** [comment]
@yksoft1 HDI image is booting now without the prompt, it seems.

Here's how:

    imgmount 0 "master.fdi" -t floppy -fs none
    imgmount 2 "ed3.hdi" -t hdd -fs none
    boot -l c

Where master.fdi is from the FDI set (disk 01 master disk) and ed3.hdi is the HDI image.

**Comment by joncampbell123** [comment]
Actually, the game is happy as long as SOMETHING appears in the floppy drive as a 1.2MB floppy that MS-DOS lists as code 90h at 60:6C.

    dd if=/dev/zero of=nothing.img bs=1024 count=$((77*8*2))

    imgmount 0 "nothing.img" -t floppy -fs none
    imgmount 2 "ed3.hdi" -t hdd -fs none
    boot -l c

**Comment by yksoft1** [comment]
> Actually, the game is happy as long as SOMETHING appears in the floppy drive as a 1.2MB floppy that MS-DOS lists as code 90h at 60:6C.
> 
> ```
> dd if=/dev/zero of=nothing.img bs=1024 count=$((77*8*2))
> 
> imgmount 0 "nothing.img" -t floppy -fs none
> imgmount 2 "ed3.hdi" -t hdd -fs none
> boot -l c
> ```

But it worked in Neko Project II even if nothing is in any floppy drives at all.

**Comment by joncampbell123** [comment]
@yksoft1 Try bringing up Neko Project II and booting MS-DOS with no floppy drives, then use a debugger to see what MS-DOS stores at 60:6C-6F.

**Comment by yksoft1** [comment]
> @yksoft1 Try bringing up Neko Project II and booting MS-DOS with no floppy drives, then use a debugger to see what MS-DOS stores at 60:6C-6F.

There seems to be no way to disable floppy drive emulation in Neko Project II at all.

**Comment by joncampbell123** [comment]
There is at least one floppy drive at all times then?

**Comment by yksoft1** [comment]
> There is at least one floppy drive at all times then?

I think so. Isn't it easier to just disconnect the FDD cable on a real PC-98 and observe the content of 60:6C-6F?

**Comment by joncampbell123** [comment]
@yksoft1 Yes. I'll do that this weekend when I have time to set up to do the test.

**Comment by joncampbell123** [comment]
Here's the contents of 60:6C on a Pentium PC-9821 with two floppy drives, and one IDE CF card with two partitions:

0x80 0x80 0x90 0x91

**Comment by joncampbell123** [comment]
When the floppy cable is disconnected, it becomes:

0x80 0x80 0x00 0x00

**Comment by joncampbell123** [comment]
Therefore, this is a game that will not run without a floppy drive, the way it apparently works.

**Comment by joncampbell123** [comment]
I'm impressed that unlike IBM PC hardware, it can auto-sense the drives instead of requiring you to specify them in the BIOS.

**Comment by joncampbell123** [comment]
Also notice the bytes seem to match drive letters. A: and B: are separate partitions on the CF card, C: and D: are the floppy drives.

**Comment by yksoft1** [comment]
So it's why those Falcom games won't run under FreeDOS(98). 
FreeDOS(98), as DOSBox-X before the dummy table was added, didn't implement 60:6C tables as NEC or Epson's DOS did.
