### ISSUE TITLE
Microsoft FORMAT.COM crashes after Y/N prompt

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1227]
**Describe the bug**
When running FORMAT.COM in the native DOSBox-X environment with a mounted disk image, FORMAT.COM will crash and jump into random data instead of formatting the disk image.

**Comment by Wengier** [comment]
I have fixed the crash in pull request #1491. Although it still won't actually format the disk (because the required low-level function is not yet implemented), it is now able to properly exit to DOS with an error message.

**Comment by Wengier** [comment]
@joncampbell123 This one can be closed too since FORMAT.COM already works properly now.
