### ISSUE TITLE
Failure to process CTRL+C / CTRL+BREAK during INT 21h AH=3Fh (READ) from CON

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1230]
**Describe the bug**
Programs using INT 21h AH=3Fh to read from the console device cannot be terminated by CTRL+C

**To Reproduce**
1. Copy SORT.EXE from MS-DOS 6.22
2. Run SORT.EXE
3. Observe it echoes back what you type
4. Try to exit using CTRL+C, observe only CP437 hearts instead

**Expected behavior**
Program terminates on CTRL+C / CTRL+BREAK

**Comment by Wengier** [comment]
@joncampbell123 This bug is now fixed in the patch I posted in Issue #1448: "DEL and COPY command fixups"
