### ISSUE TITLE
Text truncated

### ISSUE THREAD

**Issue by Sesatre** [joncampbell123/dosbox-x#1231]
Hello,

The text in "Configuration GUI" > "Help" is truncated since some versions ("Getting Started", for example).

Thank you for your work !

**Comment by joncampbell123** [comment]
It must have happened when I fixed that text wrapping bug that happened when you dragged the window partially off screen.

**Comment by joncampbell123** [comment]
To explain: Prior to a fix of mine, the text wrapping worked, but it was based on the corner of the screen as well as the window. So you could make strange text wrapping effects dragging the window offscreen.

**Comment by joncampbell123** [comment]
Fixed
