### ISSUE TITLE
sblaster autodetection in "Titus the Fox" not working

### ISSUE THREAD

**Issue by Condor-2-4-2** [joncampbell123/dosbox-x#1236]
Hello,

the game "Titus the Fox" normally detects the soundblaster if the variabel "sb" is set.
In vanilla DOSBox 0.74-3 this works fine with the followings config settings:

> [sdl]
fullscreen=true
fulldouble=true
fullresolution=1024x768
output=opengl

> [dosbox]
machine=svga_s3
memsize=2

> [render]
aspect=true

> [cpu]
core=normal
cputype=auto
cycles=4000

> [sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

> [autoexec]
mount c "."
c:
cd fox
ffc sb
exit

With the same settings in DOSBox-X 0.82.21 x64 the game starts only with pcspeaker sound. I also tried different settings for cpu and sblaster, but the soundblaster was not detected. 

Is there a possibility to run the game with soundblaster?

Thank you in advance,

Condor-2-4-2

**Comment by Allofich** [comment]
Coincidentally, I just recently posted this same issue.
https://github.com/joncampbell123/dosbox-x/issues/1200

@joncampbell123 looked into it and said:

> The reason the OPL emulation in DOSBox-X is failing the test is that a hack made for Wolfenstein >3D is enabled by default.
>
>This hack makes the OPL2/3 timer bits "expire" (and bits set) if it sees 50 consecutive I/O reads from >the OPL status port.
>
>Disable the hack by adding:
>
>[sblaster]
>adlib force timer overflow on detect=false
>
>On my end FM music now works even if cycles=10000

I think this option is now disabled by default, but if you used dosbox.reference.conf from a previous version as a base for your .conf file, you may still have it on, since it was on by default before.

**Comment by Condor-2-4-2** [comment]
Hello Allofich,

thank you for the fast reply! 

With disabling the hack the soundblaster playback now works in the game.
