### ISSUE TITLE
Game Error War Eagles: Packed file is currupt

### ISSUE THREAD

**Issue by dosxga** [joncampbell123/dosbox-x#1237]
**Describe the bug**
When the dos game War Eagles is run from DOSBox X : we.exe gives the error packed file is currupt  may be related to: https://github.com/joncampbell123/dosbox-x/issues/7

**To Reproduce**
1.  Mount a folder from a usb drive with we.exe in it.
2. cd to we.exe
3. run we.exe
Does not occur in dosbox 74.3 and may be related to: https://github.com/joncampbell123/dosbox-x/issues/7
**Expected : game loads
**Screenshots**
**Environment (please complete the following information):**
 - Operating system Windows 10 64bit
 - DOSBox-X release version or commit SHA1 this issue occurred on
Version .82.21 

**Additional context**
![wareagles](https://user-images.githubusercontent.com/54957125/64370621-71306180-cfe4-11e9-97f4-cc3958380166.png)

**Comment by joncampbell123** [comment]
Try LOADFIX then run the game.

Microsoft EXEPACK compressed executables have this problem that fail to decompress if loaded too low in memory.

**Comment by joncampbell123** [comment]
See also: https://jeffpar.github.io/kbarchive/kb/072/Q72360/

**Comment by joncampbell123** [comment]
That error message is typical of EXEPACK'd executables, so unless there's another reason it prints that message, I'm going to go ahead and close the issue.
