### ISSUE TITLE
Puyo Puyo 2 doesn't work in PC-98 mode (INT 18h AH=30h attempt to set 15KHz mode does not signal failure as it should)

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#1238]
Compile's DOS version of Puyo Puyo 2 is a game designed for both PC-9821 and IBM PC (SVGA). 
It works under DOSBox-X IBM PC mode, but hangs in PC-98 mode.

The game can be found at https://archive.org/details/msdos_Puyo_Puyo_2_1995 .

run PP2.COM to start the game.

**Comment by joncampbell123** [comment]
LOG: DOS CON: Copyright 1994 by COMPILE Corp.  /  Programmed by K.Yoneyama
    LOG: DOS CON: 						  Takeshi.K
    LOG: DOS CON: PC-9821(256Color) Puyo2 Graphic Driver Ver 1.01
    LOG: PC-98 INT 18 AH=30h AL=00h BH=00h
    LOG: PC-98 INT 18h AH=30h attempt to set 15KHz hsync which is not yet supported

**Comment by joncampbell123** [comment]
1CED:0000CC1A B80030              mov  ax,3000
    1CED:0000CC1D B700                mov  bh,00
    1CED:0000CC1F CD18                int  18
    1CED:0000CC21 0AC7                or   al,bh
    1CED:0000CC23 750B                jne  0000CC30 ($+b)         (no jmp)

INT 18h AX=3000h BH=00h.
if (AL | BH) == 0 (assumes BH is unmodified?) exit to DOS

**Comment by joncampbell123** [comment]
If I catch the INT 18h call there, then SR AL FF to force AL=FFh before the test, then allow the code to continue, the game runs fine.

I'll need to examine NP2 and real hardware to see what this attempt does. Also based on the code, an error code is expected in AL, not AH?

![demo_000](https://user-images.githubusercontent.com/6245486/64447788-0426d580-d091-11e9-90cd-0528fb7dd394.png)

**Comment by joncampbell123** [comment]
Sound Blaster 16 support seems to require the installed Creative drivers, which is unusual. Typically DOS games have their own support and do NOT require Creative drivers.

**Comment by joncampbell123** [comment]
The latest commit updates INT 18h AH=30h to indicate failure properly for the 15KHz modesetting attempt, and updates register return values according to NP2 source code to set AL/AH/BH. The game should work now.
