### ISSUE TITLE
S3 emulation is broken, again

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#124]
Windows 3.1: S3 emulation works but entering a DOS VM causes a crash
Windows 95: S3 emulation causes hard crash in Windows 95 when Windows 95 uses it's S3 driver.

**Comment by joncampbell123** [comment]
Warcraft II: S3 emulation causes the DOS4/GW extender to crash if less than 48MB of RAM.

**Comment by joncampbell123** [comment]
In fact, setting vmemsize=1 to emulate an S3 with 1MB of video RAM seems to fix a lot of crashiness so far.

**Comment by joncampbell123** [comment]
Right. I figured out that the Windows 3.1 S3 driver moves the linear address window down to 0xA0000 briefly when entering a DOS VM, then puts it back. In DOSBox and DOSBox-X, the LFB page mapping takes priority over system memory. Additionally, the window is always mapped at full size. Therefore, that mapping overrides whatever system memory Windows is executing from, and the whole DOS VM crashes. Adding code to properly emulate the S3 linear address window and disable the LFB for the DOS VM prevents crashing in Windows 3.1.

**Comment by joncampbell123** [comment]
Confirmed: The most recent commit allows Windows 95 to use the S3 emulation without crashing now.

**Comment by joncampbell123** [comment]
Confirmed: Windows 95 OSR2 and S3 emulation is working now.

**Comment by joncampbell123** [comment]
Confirmed: Windows 98 (first edition) working with S3 emulation.

**Comment by joncampbell123** [comment]
Confirmed: Windows 98 SE and Windows ME

**Comment by joncampbell123** [comment]
Coming back to Warcraft II, patching INT 10 to lie to the game and report 1MB regardless of size also prevents the game from crashing.

**Comment by joncampbell123** [comment]
Apparently you can run Warcraft II with machine=vesa_oldvbe and vmemsize=4, it won't crash. Simply disabling linear framebuffer modes (machine=vesa_nolfb) didn't resolve crashing. Is this a problem with VBE 2.0 extensions?

**Comment by joncampbell123** [comment]
A-ha! Warcraft II crashes with more than 1MB of S3 video RAM because it uses a fixed size buffer to hold the VESA mode list. If the modelist is too long, then it overruns the buffer and crashes. Capping the VRAM at 1MB prevents the modelist from getting too long and that's why it runs that way.

**Comment by ghoul8765** [comment]
Brilliant work on those two fixes. I suspect that these corrections to the video emulation fixed other issues as well. Your work is without peer!

**Comment by joncampbell123** [comment]
Final comment: Running the game with the supplied DOS4/GW means that no matter what VESA BIOS fixes you use it eventually crashes anyway. Bleh. Just use DOS32A and avoid the suck that is DOS4/GW.

**Comment by ghoul8765** [comment]
Confirmed. However, I just realized that when the GUS is inactive, then none of these issues occur! It's only where GUS is active that the dos32a is required, at least from limited testing. There is a Vogons post that suggests a similar issue on real hardware, although they may have used different audio hardware than GUS.

It seems that you fixed a buffer overrun in the war2 code and there are additional bugs in the dos extender and/or Miles audio drivers. :)
