### ISSUE TITLE
Scroll bar in "Help" menu.

### ISSUE THREAD

**Issue by Sesatre** [joncampbell123/dosbox-x#1242]
Hello, In the "Configuration GUI" it is not possible to read all the text of "Help" because of the resolution of the screen. Would it be possible to have a scroll bar down?

Thanks again.

**Comment by joncampbell123** [comment]
I've considered adding that and it might be possible to hack the crappy GUI toolkit to support it.

**Comment by joncampbell123** [comment]
If you have the ability to compile from source, do it from the latest commit, because I just modified the message boxes to make the text scrollable if too big to fit in the window.

There's no scrollbar yet, but if you click and drag over the text you can scroll the text.

**Comment by joncampbell123** [comment]
I just updated the code again. If the text cannot fit in the window, it makes room for a scrollbar and draws a scrollbar. You can grab the "thumb" of the scrollbar and drag it to scroll through all the text.

![scrollbar1](https://user-images.githubusercontent.com/6245486/64560661-c4185a80-d2fd-11e9-9784-22b1aa31af35.jpg)

**Comment by joncampbell123** [comment]
Scrolling is implemented for help, and also for the settings themselves.
