### ISSUE TITLE
Apply options "On The Fly" via commands & New Menu for "Devices"

### ISSUE THREAD

**Issue by inukaze** [joncampbell123/dosbox-x#1243]
Hi there, i want to know why on DOSBox-X i can't use the follow commands in the "Command Line Interface" i use the follows from my own batch scripts files

Duke Nukem 3D / Atomic Edition : 
```
core dynamic
cputype pentium_slow
cycles 131072
cycleup   = 512
cycledown = 512
```

Sega Outrun :
```
core normal
cputype pentium_slow
cycles 2048
cycleup   = 256
cycledown = 256
loadfix
outega
```

Broken Sword : 
```
core=simple
cputype=auto
cycles=max
cycleup=1024
cycledown=1024
```

Exhumed / PowerSlave :
```
core dynamic
cputype 486_slow
cycles 65536
cycleup   = 1024
cycledown = 1024
```

Oddworld - Abe's Oddysy :
```
core=dynamic
cputype=pentium_slow
cycles=65535
cycleup=1024
cycledown=1024
dos4gw abedos
```

The Elder Scroll II : Daggerfall
```
core dynamic
cputype pentium_slow
cycles 8192
cycleup   = 1024
cycledown = 1024

REM Mount Folder like CD
mount d ..\..\discos\dfcd -t cdrom -label Daggerfall

REM Mount C with 600 MB Free : 
mount C ..\..\Games\tes2 -freesize 614400
```

Rayman :
```
core=dynamic > nul
cycles=auto 5120 85% limit 16384 > nul
cycleup=512 > nul 
cycledown=512 > nul 
cputype=pentium_slow > nul
```

![dosbox_commands](https://user-images.githubusercontent.com/1647332/64517889-30c03480-d2bf-11e9-93f8-ada81d445f5b.png)

Ok here my mockup, is just a Mockup

Floppy - Options : 
![InuFeatureRequest001](https://user-images.githubusercontent.com/1647332/64517987-56e5d480-d2bf-11e9-842b-c07ed8a56b27.png)

Hard Drive Disk - Options : 
![InuFeatureRequest002](https://user-images.githubusercontent.com/1647332/64517996-5cdbb580-d2bf-11e9-9ed8-522faee275dc.png)

I think when the user select "Set & Use Folder" can specify too if want to use "-freesize" option for games like "The Elder Scroll II : Daggerfall" (because i mount with -freesize 614400 for avoid problems)

Dunno, DOSBox is compatible with "qcow2" image format ? If not i really want to add support for this file type, because i prefer just size the files really installed and not whole size when i had a few mb occupied and the img file is 2GB instead the MB i am really using.

CD-ROM - Options : 
![InuFeatureRequest003](https://user-images.githubusercontent.com/1647332/64518014-636a2d00-d2bf-11e9-8730-ffd10f8f6f2b.png)

The Reason of this is because when i for example install Windows 95 RTM and start, some strange things happend, in the autoexec section of the config file i put
1 - Floppy Image
2 - Hard Disk Image (and i boot from this)
3 - ISO Image

But the strange is sometimes Floppy and/or CDROM Inside Windows 95, just simple don't work, i had create a 2GB HDD Image. sometimes appears on the System sometimes not, i had installed a "Virtual CD" drive for solve this.

![dosbox_w95_cdrom_001](https://user-images.githubusercontent.com/1647332/64518563-674a7f00-d2c0-11e9-893b-35edfa53f6e7.png)

But i consume a lot Space Free, just putting 1 ISO, like Diablo 1, because the DOSBox after start Windows 9X don't allow me to Eject or Insert/Change the ISO from the Menu Options [I think the source code of PCEm can help you in this point]

![dosbox_w95_cdrom_002](https://user-images.githubusercontent.com/1647332/64518676-9660f080-d2c0-11e9-849a-bc4aa66a7862.png)

Test in Video [5 Mins] -> [Here](https://dai.ly/x7kjawg)

Well after i restart DOSBox-X Three times from inside itself window Pressing F12+R. i got "CDROM" of DOSBox 
![dosbox_w95_cdrom_003](https://user-images.githubusercontent.com/1647332/64523619-b3022600-d2ca-11e9-9ac5-a96cb5e814bd.png)

Really i don't understand why sometimes yes sometimes not this device inside the WIN95 RTM.

Another particular thing i notice, its in msdos mode i can't start quake for msdos
but inside from windows 95 yes. but its too slow, i supose is because i need to set core in "Simple" or Windows 95 nevers start if not there, because the "Auto" its not working for start the Guest OS.

and a last thing without Hard Disk Drive Image, just in DOSBox Mode, turrican 2 its very hard to get it working because when i start T2.EXE the Text on the Menus are invisible.

and after the first try, i just can select 
1) 
2) Joystick

and after of that start some kind of video test very glitchy. 

i try with the mode explained -> [Here](https://github.com/joncampbell123/dosbox-x/issues/22)
C:\TURRICAN.CFG 

and all steps but is the same ever.

**Comment by joncampbell123** [comment]
The shell by default will not accept names of configuration settings as commands, because it becomes impossible to run programs of the same name.

SVN behavior as you expect can be enabled with "shell configuration as commands=true", but the recommended way to change settings is with "CONFIG -SET option=value".

**Comment by inukaze** [comment]
> The shell by default will not accept names of configuration settings as commands, because it becomes impossible to run programs of the same name.
> 
> SVN behavior as you expect can be enabled with "shell configuration as commands=true", but the recommended way to change settings is with "CONFIG -SET option=value".

Thanks for that answer, and another dunno, in the next release you finally implement 3DFX support to the SDL2 version ? 

I ask because yesterday i install DirectX 8.0a in WIndows 95, i and use SDL2 DOSBox-X 0.82.21 and when i try to run "dxdiag" the dosbox-x closed and the latest message was "3DFX is not yet implemented on SDL2 Version" but with the SDL1 version (with DOSBox-X 0.82.19, because again i can compile becuase indicate must be compile using the sdl1 from the package) but in this version 3DFX works, i had test "Direct3D" the first is slow, but the second works acceptably .

**Comment by inukaze** [comment]
Thanks for the answers :)
