### ISSUE TITLE
Windows 95: PS/2 mouse aux emulation doesn't work when UIDE.SYS is used and attached to the same IDE port as the system drive

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#125]

**Comment by joncampbell123** [comment]
How to recreate: Install Windows 95. Make sure the MS-DOS device driver is loaded for the CD-ROM drive. Make sure dosbox.conf uses imgmount to attach the CD-ROM to the primary slave, and the hard drive to the primary master. Notice that in that specific case the cursor won't respond to mouse input.

**Comment by joncampbell123** [comment]
Perhaps it's that the OAK IDE driver I'm using now works better with Windows than UIDE.SYS.

**Comment by ghoul8765** [comment]
I've used the OAK IDE driver only. I believe the mscdex emulation was originally designed around its characteristics. If it was of interest and given UIDE.SYS is open source, then a debug build of this driver could be compiled for easier testing. Also, it is possible that this driver displays the same issue on real hardware.

**Comment by jwt27** [comment]
I tried this a while ago on hardware, win9x wouldn't boot at all with UIDE.SYS loaded.
