### ISSUE TITLE
realms of arkania 1 - sound problem

### ISSUE THREAD

**Issue by Condor-2-4-2** [joncampbell123/dosbox-x#1259]
Hello,

I want to play "Realms of Arkania 1" (GoG-Version) on Dosbox-X, but there is no sound. With  Dosbox 0.74, which original came with the GoG-Version, the game starts with sound without any problems. The soundblaster settings are the same for both config files.

Here is my actual config file for the game used with Dosbox-X 0.82.21 x64:
[dosbox-x_realms1.txt](https://github.com/joncampbell123/dosbox-x/files/3643680/dosbox-x_realms1.txt)

I also tried to get the ingame music to work without success. GoG delivered the game with separate music files in ogg format which are stored in a game subfolder called "MUSIC". Than there is an image file named "game.gog" and a cuesheet named "game.cue" in the main game folder which has to be mounted as drive "D". And I converted the ogg files into wave format and changed the cue sheet to wave. 

Here is my cue sheet:
[game.txt](https://github.com/joncampbell123/dosbox-x/files/3643734/game.txt)

But as I started Dosbox-X with the config file and mounted the cue sheet from further above, I got an MSCDEX failure message "invalid file... . In Dosbox 0.74 there is no problem to load the external music files with the cue sheet.

Is there a solution for both problems?

Thank you in advance!

Condor-2-4-2

**Comment by joncampbell123** [comment]
Is this the game?

https://archive.org/details/msdos_Realms_of_Arkania_-_Blade_of_Destiny_1992

**Comment by Condor-2-4-2** [comment]
Hello,

yes, this is the game. I have the german version. I also executed the soundsetup before starting the game. There are only two options selectable, "card" and "adlib gold" which I both tried. I also tested the preselected port "388" and later port "220", which is the default port for the soundblaster card in the default config. But I had no success to get the sound to work.

In Dosbox 0.74 the sound works with port "388" selected in the setup, thus the soundblaster port in the config file is "220".

For the GoG-Version there is only an image file "game.gog" with a size of ca. 8 mb without the music data in it. The music date exists only as separate ogg files (14 tracks) in the subfoler "music". The cuesheet file has exactly the same content like the one I posted before, with the only exception that I changed the ogg formats to wav. And this is working for Dosbox 0.74 without problems.
So is there a way to load the music files with the game.gog-image like in Dosbox 0.74?

**Comment by Condor-2-4-2** [comment]
Now I have mounted only the "game.gog" image on "d" (without cuesheet) and started the game with  "SCHICKM.EXE" (the executable for the german version). I got an error message "sound hardware not found" directly. After that the game works but without sound.

I have logged the start sequence. Here is my log file:
[log.txt](https://github.com/joncampbell123/dosbox-x/files/3648328/log.txt)

**Comment by Condor-2-4-2** [comment]
I noticed that I have overseen the button to turn the page in the soundset program. On the first page after setup start there will be shown only "adlib gold" and "card". When I press the arrow button on the right, a further options page appears which also show the soundblaster card. Now the sound effects are working! What a stupid mistake of mine!

The last problem is now to load the separate music files in the subfolder.

**Comment by joncampbell123** [comment]
It is a very unusual card selection menu, yes. :)

https://twitter.com/greatcodeholio/status/1176256643153022976
