### ISSUE TITLE
where is my Dosbox.conf?

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#126]
I can't seem to find the Dosbox.conf file my Dosbox-X is using

I'm running Lubuntu 15.04

I understand Dosbox.conf is meant to be located in

/home/username/.Dosbox

but for some reason my Dosbox-X wasn't using the conf files in that folder

I've even deleted that folder - It does not get recreated when I start dosbox-X

I ran this in Dosbox-X

CONFIG.COM -wcd -all
Writing config file dosbox-0.801.conf

but I have no idea where it's writing the .conf file to - its not in
/home/username/.Dosbox

any idea whats happening? 
or where to find the .conf file?

**Comment by joncampbell123** [comment]
My branch doesn't auto-create dosbox.conf and it does not use the one in your home directory.

Try this to create dosbox.conf in your current directory:

CONFIG.COM -wcd -all dosbox.conf

When you run dosbox-x from that directory it should automatically read that file.

**Comment by toddfraser88** [comment]
that worked, i have a .conf file now

thanks!
