### ISSUE TITLE
XP Support

### ISSUE THREAD

**Issue by anonyme-x22** [joncampbell123/dosbox-x#1262]
Hi,

Please dont be like the GAFAM.
Unless specific reasons dosbox can run under XP.
Can you set the flags in your compilation environment for xp.

Thanks in advance,
Have a good day,
Rgds,

**Comment by joncampbell123** [comment]
@anonyme-x22 Please explain the last post, I'm not sure what you mean.

**Comment by joncampbell123** [comment]
VS2017 is warning that Windows XP targets are deprecated and will no longer be supported. The VS2017 compiled binaries will continue to require at least Vista.

Windows XP support is and always will be available from the binaries compiled with MinGW.

**Comment by anonyme-x22** [comment]
Hi,

Thanks for your answer.
Does VS2017 is a requirement, can't you just use the VS2015 ?

Have a good day,
Rgds,

**Comment by anonyme-x22** [comment]
Hi,

Effectively the MinGW build works. Thanks a lot.

Rgds,

**Comment by joncampbell123** [comment]
I either use the latest community version of Visual Studio or MinGW, so there's no interest in downgrading to support the older version.

MinGW is unlikely to suddenly pull support for Windows XP anytime soon as far as I know.

All development on my end is primarily done in Linux.

**Comment by anonyme-x22** [comment]
Hi,

Thanks for your answer.
Regarding the latest. Newer is not always better.
There is no point about having the latest of something just to be like the other in my opinion.
Your argument to switch to visual studio 2017 aren't justified to my eyes, but you're free and you do what you want. Thanks that MinGW still support xp.

PS: Linux, i understand because, if i wanted to be updated, When i turn on windows 10 on my computer, i'm loosing my mind ;), when i switch on linux i'm free! (if linux hasn't changed...)

Have a good day,
Rgds,

**Comment by yksoft1** [comment]
> Hi,
> 
> Thanks for your answer.
> Does VS2017 is a requirement, can't you just use the VS2015 ?
> 
> Have a good day,
> Rgds,

In fact VS2017 CRT and linker does support XP, but it requires /SUBSYSTEM:Windows,"5.01".
In the contrary VS2015 CRT before Service Pack 2 had errors under XP.

**Comment by nemo838** [comment]
lastest .net framework version for XP is 4.0
default .net framework of VS 2017 is higher than 4.0
that is the problem

change target .net framework on VS project property before compile
maybe this can solve problem.
