### ISSUE TITLE
HDI images using FreeDOS98 crash in DOSBox-X, especially if components written for Neko Project II are involved

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1268]
Some HDI images here use FreeDOS98:

https://ia800100.us.archive.org/view_archive.php?archive=/22/items/NeoKobe-NecPc-98012017-11-17/Anjin.zip

**Comment by joncampbell123** [comment]
It turns out the boot sector code attempts INT 1Bh with AH=03h and AL=boot drive.

DOSBox-X does not implement function 3h, and sets carry.

Boot sector calls INT 18h to wait for keyboard input (with nothing on screen), and when the user hits a key, jumps to the BIOS entry point FFFF:0000.

**Comment by joncampbell123** [comment]
Adding INT 1Bh AH=3h emulation (at least the disconnect case and CF=0) allows FreeDOS(98) to boot. Fixed.

**Comment by joncampbell123** [comment]
Here's a screenshot of the other HDI image that crashes, that mentions drivers designed for Neko Project II (or 286).

![vlcsnap-2019-10-10-11h55m39s637 gif](https://user-images.githubusercontent.com/6245486/66598177-4db58500-eb55-11e9-960f-5f2eae4f7f9d.png)

**Comment by yksoft1** [comment]
Replaced EMM386.EXE with the one from MS-DOS 6.2 and Zai Metajo.hdi booted without crashing.

**Comment by yksoft1** [comment]
About Zai Metajo, there are lots of "rotate mode not supported" in the log whenever the PSG-PCM voice is played.
