### ISSUE TITLE
Begin testing/developing Windows builds of DOSBox-X on ReactOS

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1269]
It's time to make sure Windows builds can run on alternatives, Microsoft continues to change Windows 10 in ways that piss people off.

Lower priority: Testing with WINE.

https://news.ycombinator.com/item?id=21103683

**Comment by joncampbell123** [comment]
ReactOS won't run DOSBox-X, even the MinGW builds.

**Comment by joncampbell123** [comment]
You can however install VirtualBox guest additions in ReactOS and they'll sort of work.

Getting the shared folders thing to work though requires installing the Samba and Samba-tng packages and restarting ReactOS.

**Comment by softtest02** [comment]
Does DOSBOX-X still run on Win2k3 or Windows XP?

ReactOS attempts to be binary compatible with Win2k3. So the recommendation for application devs is simply to develop and compile for Win2k3. In fact, their own devs do this with ReactOS components, like their shell for example.

Then, if any bugs show up in ReactOS when running a binary that works fine in Win2k3, it's considered a ReactOS bug, and it's recommended then to report it to ReactOS's bug tracker.

**Comment by joncampbell123** [comment]
Last time I checked, MinGW builds run on XP.

ReactOS's error message isn't too useful, so it could mean anything from a version number it doesn't recognize to DLL import symbols that the host doesn't provide.

**Comment by yksoft1** [comment]
FYI:
https://twitter.com/yksoft1/status/1180466973697687555
