### ISSUE TITLE
Low frame rate when running Blood

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#127]
I've noticed I'm getting a low framerate running blood on Dosbox-X

on Dosbox 0.74 it works fine

any settings i could modify to help fix this?

or is the problem in sourcecode?

**Comment by joncampbell123** [comment]
Low framerate is usually a sign you're not using the dynamic core. Blood is CPU intensive enough to need the dynamic core to run at an acceptable frame rate.

**Comment by toddfraser88** [comment]
OK, tried that

framerate still low

**Comment by joncampbell123** [comment]
Games like Blood and Quake need a cycles count at least 50000 to run like they used to on old Pentium hardware. Is your cycle count that high?

Also, 64-bit builds do not have the dynamic core. The dynamic core source code is specific to 32-bit builds.

**Comment by toddfraser88** [comment]
cycles go to max when i run blood

I compiled from source - on Lubuntu 15.04 64-bit

I assume in a 64-bit environment it compiles as 64-bit?

**Comment by joncampbell123** [comment]
Correct. I do not currently test 64-bit -> 32-bit Linux cross-compile scenarios.

**Comment by toddfraser88** [comment]
is there a way to make it compile as 32-bit?

**Comment by joncampbell123** [comment]
If your Linux distribution offers a 32-bit toolchain for 64-bit and corresponding 32-bit libraries, that might be possible.

**Comment by toddfraser88** [comment]
looking at it, it would probably be easier to download a 32-bit Lubuntu, live boot it, and compile dosbox there

it doesn't seem to want to have sdl 64-bit and 32-bit installed at the same time

**Comment by toddfraser88** [comment]
OK

SO after a bit of effort, I've got a 32-bit Dosbox-X running.

Blood is working fine in the 32-bit version - no framerate issues at all.

**Comment by toddfraser88** [comment]
I'm still curious to know what is happening in the 64-bit version that makes it run slow.

Did you notice any slowdowns yourself when running 64-bit versions of Dosbox-X?

**Comment by DominusExult** [comment]
Dosbox has a mode called dynamic core which allows much more speed but is only available for 32bit. The 64bit version is not as fast and optimized due to whatever ;)
(Yes, my explanation sucks)

**Comment by DominusExult** [comment]
I wonder, though, whether Dosbox-x is in sync with Dosbox SVN fixes/enhancement to 64bit dynamic core.

**Comment by joncampbell123** [comment]
Every so often I'll bring in some changes from the main project, but not often. Their changes to CPU emulation are probably incompatible with DOSBox-X.

**Comment by toddfraser88** [comment]
I compiled Dosbox SVN r3955 from EmuCR as 64-bit

I observed no low framerate in blood in that build

**Comment by aybe** [comment]
There was some regression back then, causing a slowdown, but testing with current version as of today, the game is smooth.
