### ISSUE TITLE
Change value for "vga 3da undefined bits"?

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1273]
This value, configurable in dosbox.conf, is 0 by default, the same as DOSBox SVN was. A recent commit to SVN changes the value, which is not configurable in SVN, to 4.

https://sourceforge.net/p/dosbox/code-0/4266/

I can confirm it fixes slow animations in the game The Blues Brothers.

I tried the "JOOP #2" demo mentioned in the DOSBox-X comments. It works fine I guess, there's a little jumpiness but I don't know if that's normal or not.

Should this value be 4 by default? If 4 is correct, does it no longer need to be configurable?

**Comment by joncampbell123** [comment]
It should be configurable still, but it's OK to change the default value to 4.

JOOP will hang if it's zero because for some bizarre reason there's a loop that shifts left and terminates when bit 7 is nonzero.

**Comment by joncampbell123** [comment]
It should remain configurable because part of the philosophy of DOSBox-X is to give you many options to twiddle with to break existing games (to learn their faults) or to break any new development you're doing. That includes errant code that assumes things about undefined bits in port 3DAh.

**Comment by Allofich** [comment]
OK, I'll leave it to you to change the default, which seems like the right thing to do unless we find software requiring a different value. You can close this issue then whenever you would like.

**Comment by joncampbell123** [comment]
The demo in question:

http://files.scene.org/get/mirrors/hornet/demos/1992/joopinc2.zip

**Comment by joncampbell123** [comment]
The errant loop that will hang if 3DAh returns 00h at any time:

               in    al,dx     ; <- DX = 3DAh
           l1: shr   al,1      ; AL >>= 1, CF = bit that was shifted out
               jnc   l1        ; loop until we shift out nonzero bit
