### ISSUE TITLE
Unable to type input to start game

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1274]
I found this recent bug report for DOSBox SVN:
https://sourceforge.net/p/dosbox/bugs/514/

The game (game is in Chinese, called 爆笑三国志, "Bàoxiào sānguózhì") is attached to the bug report. Unzip to a folder, open the folder and run `SANGO.EXE` to start it.

After pressing a key to get past the title screen, another screen will appear. In DOSBox SVN you can type here, then advance through the menus to start the game, but in DOSBox-X you can't type anything and you can't, as far as I can tell, advance into the game. No errors in the log.

![sango_000](https://user-images.githubusercontent.com/19624336/66208775-e29d2600-e6f0-11e9-8660-49790655e803.png)

In SVN, you can input text into the rectangle in the center of the screen, and advance to the next screens.

By the way, I checked out the gameplay in SVN and found out that what the bug report means. The player and computer players take turns moving a number of tiles across the game board. It is supposed to be a random number, but both the player and computer roll a 5 every time and always move 5 tiles. Since I can't start the game in DOSBox-X I don't know if it happens in DOSBox-X.

**Comment by Allofich** [comment]
Here's a video of the game (it's in fast-forward for some reason).
https://www.youtube.com/watch?v=1O_NUH03lDE
It's working correctly here, the game starts and the movements are not always 5.

**Comment by joncampbell123** [comment]
I see a loop polling port 61h, not to check if keyboard input is there but to wait on bit 4 as a delay loop of some kind.

    033B:0000D890 50                  push ax
    033B:0000D891 51                  push cx
    033B:0000D892 B9D007              mov  cx,07D0
    033B:0000D895 E461                in   al,61
    033B:0000D897 2410                and  al,10
    033B:0000D899 3AC4                cmp  al,ah
    033B:0000D89B 74F8                je   0000D895 ($-8)         (up)
    033B:0000D89D 8AE0                mov  ah,al
    033B:0000D89F E2F4                loop 0000D895 ($-c)
    033B:0000D8A1 59                  pop  cx
    033B:0000D8A2 58                  pop  ax
    033B:0000D8A3 C3                  ret

**Comment by joncampbell123** [comment]
There is code to count using the timer counter in the BIOS data area.

    033B:0000D916 B84000              mov  ax,0040
    033B:0000D919 8EC0                mov  es,ax
    033B:0000D91B 26A16C00            mov  ax,es:[006C]           es:[006C]=36BE
    033B:0000D91F 8BD8                mov  bx,ax
    033B:0000D921 2639066C00          cmp  es:[006C],ax           es:[006C]=36BE
    033B:0000D926 74F9                je   0000D921 ($-7)         (no jmp)

**Comment by joncampbell123** [comment]
Here is another condition it's looping for, which never happens apparently:

Prior code:
    033B:000098FF E88E3F              call 0000D890 ($+3f8e)
    033B:00009902 E80040              call 0000D905 ($+4000)
At:
    033B:00009905 83E27F              and  dx,007F
    033B:00009908 83FA78              cmp  dx,0078
    033B:0000990B 73F2                jnc  000098FF ($-e)         (no jmp)

**Comment by joncampbell123** [comment]
DX is always 0xFFFF because it's expecting the PC speaker (PIT 2) to cycle.

    033B:0000D905 B086                mov  al,86
    033B:0000D907 E643                out  43,al
    033B:0000D909 B0B6                mov  al,B6
    033B:0000D90B E643                out  43,al
    033B:0000D90D E442                in   al,42
    033B:0000D90F 8AE0                mov  ah,al
    033B:0000D911 E442                in   al,42
    033B:0000D913 8BD0                mov  dx,ax

**Comment by joncampbell123** [comment]
Here's an immediate fix for the game:

1. Start DOSBox-X, and run DEBUG.EXE

2. Type the following to enable the PC speaker clock gate but NOT the output gate: "O 61,2"

3. Then run SANGO.EXE

4. Keyboard input should work

**Comment by joncampbell123** [comment]
The thing about DOSBox-X is that it's supposed to represent what *real hardware* does, so if it's normal for real hardware to start with bits [1:0] of port 61h off, then the game SHOULD fail this way, *but* DOSBox-X should offer a dosbox.conf setting or command to tweak port 61h on startup for games like this as well so you can run it.

**Comment by joncampbell123** [comment]
The game does "run in fast forward" if you use a high cycle count like 30000. It animates more normally if you emulate a 486 and use a cycle count of about 10000 or so.

**Comment by joncampbell123** [comment]
I'll add a dosbox.conf option to indicate the BIOS should leave port 61h with bit 1 set at startup for games like this.

**Comment by Allofich** [comment]
Thanks, I was able to start the game with your quickfix. And in-game, the SVN problem of it always rolling a five does _not_ happen. (According to the bug reporter at the SVN site, someone says DOSBox 0.73 didn't have this issue either)

**Comment by joncampbell123** [comment]
dosbox.conf option added.

**Comment by 280696516** [comment]
I am the bug reporter of https://sourceforge.net/p/dosbox/bugs/514/,  
The "always rolling  five" problem is also fixed.
thanks.
