### ISSUE TITLE
brightness and contrast issue in game "Terra Nova" because of 8-bit DAC emulation

### ISSUE THREAD

**Issue by Condor-2-4-2** [joncampbell123/dosbox-x#1276]
Hello,

in the game "Terra Nov - Strike Force Centauri" I noticed a strange behaviour with brightness and contrast. I'm running the game on the actual DOSBox-X version 0.82.22 x64 under Windows 10.

After starting the game the ingame menue appears with the normal brightness and contrast level as shown in the picture bellow.

![Menue_bright](https://user-images.githubusercontent.com/49206911/66273262-a396de00-e872-11e9-84f7-cc0363ddcb31.jpg)

If I select a new game suddenly the screen gets dark and the contrast is low. This behaviour stays for the complete game and in all menues. Bellow pictures of dark screens.

![Menue_dark](https://user-images.githubusercontent.com/49206911/66273342-50715b00-e873-11e9-8ee5-ac051322a678.jpg)
![ingame_screen_dark](https://user-images.githubusercontent.com/49206911/66273344-549d7880-e873-11e9-9e4b-c229852e8185.jpg)

I knew that I had no problems in an earlier version of DOSBox-X. So I went back till version 0.82.17 - and here it works! No decrease in brightness and contrast. Bellow an picture of the game running on this older DOSBox version.

![ingame_screen_bright](https://user-images.githubusercontent.com/49206911/66273397-cc6ba300-e873-11e9-9b57-e2e161a5594c.jpg)

From version 0.82.18 until version 0.82.22 the brightness and contrast issue is present. Is there a way to configure DOSBox-X so that there is no decrease in brightness and contrast in the game?

Thank you in advance,

Condor-2-4-2

**Comment by joncampbell123** [comment]
It's possible adding 8-bit DAC width support might have caused it:

  - Added INT 10h VESA BIOS function AH=08h "SET DAC WIDTH"
    so that, when enabled, DOS applications can switch the
    DAC from 6-bit to 8-bit.

Try adding to the [dosbox] section:

enable 8-bit dac=false

**Comment by Condor-2-4-2** [comment]
Thank you for the fast reply :-) After adding the line "enable 8-bit dac=false"  the brightness and contrast levels are shown correct!

**Comment by joncampbell123** [comment]
Hold on, if that's the problem, then it means there's something with the game, the DAC, and 8-bit vs 6-bit palette mode.

It might be a problem reading back the palette, I don't think I added any code to emulate that in 8-bit mode.

**Comment by Condor-2-4-2** [comment]
Oh, excuse me, I thought that 8-bit DAC = false is the final solution.

**Comment by joncampbell123** [comment]
@Condor-2-4-2 No, no, it means that 8-bit DAC emulation has some bugs that need to be looked at.

**Comment by joncampbell123** [comment]
"Amulets and Armor" appears to have a similar issue.

**Comment by joncampbell123** [comment]
Update on "Amulets and Armor", the game appears to use signed char for palette DAC values, and it expects the value to get chopped to 6 bits when reading it back from the DAC. If not chopped, signed char overflow bugs happen and the palette has an "overbright" effect.

**Comment by joncampbell123** [comment]
I found a shareware copy of this game. I see it calling the VESA BIOS to set DAC width to 8. If the game is still sending DAC values as if 6-bit wide, and making a dark screen, that's the game's problem, although I will continue to look into who is at fault here.

**Comment by joncampbell123** [comment]
The game really wants to set 8-bit DAC mode. There are three places where it does so. Before setting the initial mode, after setting an initial mode, and then again after setting the VESA SVGA mode.

Either the game was written when 8-bit DAC was uncommon, or there's some additional unknown quirk about writing port 3C8h/3C9h in this mode that isn't being emulated.

Perhaps most SVGA cards always treat writes to port 3C9h as 6-bit and 8-bit DAC access is elsewhere, an undocumented quirk that the game assumes.

**Comment by joncampbell123** [comment]
If I can find an old SVGA card (real hardware) that DOSLIB's VESA test program shows can support 8-bit DAC, I'll poke at it to see what port 3C9h behavior is.

**Comment by joncampbell123** [comment]
If I comment out the code to set the "8-bit DAC supported" bit in the VESA BIOS info block, the game does not call set 8-bit DAC.

**Comment by joncampbell123** [comment]
Actually it seems the problem is much simpler than that.

Once you single-step through all the protected mode DOS extender stuff, the game is checking to make sure the VESA call succeeded (AL==0x4F) and assuming 6-bit DAC otherwise.

So it is DOSBox-X's fault for not setting AL=4Fh on return.
