### ISSUE TITLE
How do I "sleep" in my program's idle loop?

### ISSUE THREAD

**Issue by myrkraverk** [joncampbell123/dosbox-x#1277]
I'm trying to keep the CPU utilization (emulation speed) low in my program's idle loop, but I have not been able to do that.

I know this can be done because the bundled FreeDOS Edit program keeps the CPU emulation speed at 3000 cyc/ms, but when I run my program it always goes to 100%.

I've tried adding `int 28` to my idle loop, but that doesn't seem to help.  The DPMI function `int 2f/1680` seems to be unsupported by either DOSBox-X or CauseWay;  nor is the `int 15/5305` power management function supported.

Is there an API that I can use to tell DOSBox-X to "take it easy, this is just an idle loop?"

**Comment by joncampbell123** [comment]
I suppose an option could be added, but in reality I don't think actual MS-DOS does much of anything in INT 28h. Idle calls on real hardware don't really mean much (as far as I know) except in multitasking systems like Windows or OS/2.

If you want, you could arrange for an interrupt after an interval and use HLT to halt CPU execution until the interrupt happens (which would also work on real hardware).

**Comment by joncampbell123** [comment]
If from C/C++ and you have inline __asm capability, a __asm hlt should do fine.

The CPU will halt execution until an interrupt happens.

That *also* means if you HLT with interrupts disabled, then you've hung your program and the user needs to hit RESET.

**Comment by Allofich** [comment]
Does int 2f 1680 do anything in MS-DOS? There is a TODO comment in `dos_misc.cpp` that makes it sound like it does

```
	case 0x1680:	/*  RELEASE CURRENT VIRTUAL MACHINE TIME-SLICE */
		//TODO Maybe do some idling but could screw up other systems :)
		return true; //So no warning in the debugger anymore
```

but int 2f 168x calls seem to be Windows-related functions, and when I used `DEBUG.EXE` to trace a simple

```
mov ax, 1680
int 2f
```

in real MS-DOS 6.22, it compared `ax` against various values but never 1680, and it returned with all registers unmodified.

**Comment by myrkraverk** [comment]
`int 2f/1680` is a DPMI function, so a DPMI host (Windows 3.1, NT and OS/2 VDM) should support it.  Apparently MS DOS itself might not support it.  Right now I don't know if DOSBox-X is a DPMI host or not.

About the HLT instruction, I have yet to try it.  I'll see if I can figure out how to use one in my compiler (OpenWatcom).  At the very least it should help when people run my code on real dos in a virtual machine.

**Comment by myrkraverk** [comment]
I have the HLT insturction a try, but since I'm writing a protected mode application, it throws an error.

For now I've given up on HLT, and I just keep `cycles = fixed 3000` in my config file.

Thank you for the replies.
