### ISSUE TITLE
"Packed file is corrupt" message on The Adventures of Captain Comic after booting Windows 3.1/3.11

### ISSUE THREAD

**Issue by HomerBender77** [joncampbell123/dosbox-x#1278]
After I boot Windows 3.11 and I want to play the Adventures of Captain Comic game, the game fails to begin and shows a "packed file is corrupt" message. This persists even after exiting Windows.

**Comment by joncampbell123** [comment]
Run loadfix before the game executable.

**Comment by HomerBender77** [comment]
Thanks. It helps.
