### ISSUE TITLE
Joystick support is broken

### ISSUE THREAD

**Issue by Gui55** [joncampbell123/dosbox-x#128]
DOSBox-X, when set to joysticktype=auto, 4axis, etc. the joystick emulation acts as if disabled. Verified this in the mapper editor too.

**Comment by joncampbell123** [comment]
I verified there is nothing in the code calling the JOYSTICK enable function. The SDL mapper shows both joysticks as DISABLED and I don't know how to enable it. I ordered a USB joystick for further testing when it arrives.

**Comment by joncampbell123** [comment]
Got it. The code to read joystick type needs to come before mapper initialization, not after.

The USB joystick arrived today, just tested that the emulation works with DOOM and Wolfenstein 3D if I turned off timed intervals.
