### ISSUE TITLE
Conf file doesn't work

### ISSUE THREAD

**Issue by HomerBender77** [joncampbell123/dosbox-x#1280]
Even after copying the dosbox.reference file and renaming it DOSBox.conf and also typing a few lines under the MOUNT section, it still doesn't work.

**Comment by joncampbell123** [comment]
Rename it to dosbox.conf

**Comment by HomerBender77** [comment]
I did. It still doesn't work.

**Comment by joncampbell123** [comment]
In the same directory as dosbox.exe?

**Comment by HomerBender77** [comment]
Yes.

**Comment by Allofich** [comment]
It works for me. You need to give more information, like the contents of your dosbox.conf file, your OS, what "doesn't work" means (I assume it just starts to the Z: prompt without any messages about mounting?) or nobody can help you.
Also this is a duplicate of https://github.com/joncampbell123/dosbox-x/issues/1178.

**Comment by HomerBender77** [comment]
My OS is Windows 10. I just tried to put mount c DOS, then cd C:\windows and then win under the AUTOEXEC section. 

> what "doesn't work" means (I assume it just starts to the Z: prompt without any messages about mounting?)

Yes, this is what it means.

**Comment by Allofich** [comment]
Could you attach your dosbox.conf file? (put it in a .zip file and drag and drop the .zip file into the window here where you type to post a comment)

**Comment by HomerBender77** [comment]
[dosbox.conf.zip](https://github.com/joncampbell123/dosbox-x/files/3707727/dosbox.conf.zip)

**Comment by Allofich** [comment]
Your file is called "dosbox.conf.conf". I'm guessing you don't see file extensions in File Explorer.

[conf.zip](https://github.com/joncampbell123/dosbox-x/files/3707770/conf.zip)

Here's the same file back, just with the extra ".conf" removed.

Also, do you have a folder called "DOS" within the same folder as dosbox-x.exe? That's what it will try to mount.
