### ISSUE TITLE
DeluxePaint II "could not reserve Tandy graphics memory" if machine=tandy

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1282]

**Comment by joncampbell123** [comment]
You can overcome this error if you run LOADFIX before running DeluxePaint

**Comment by joncampbell123** [comment]
According to this reference, the Tandy (pre-VGA) is said to use system memory for video RAM in the same way that the PCjr did. Yet neither DOSBox-X nor DOSBox SVN reserve 32KB below 128KB when machine=tandy, but they DO when machine=pcjr.

**Comment by Allofich** [comment]
With the recent PCjr memory emulation improvements, is this issue still relevant?

**Comment by joncampbell123** [comment]
It looks like recent commits allow DeluxePaint II to run with Tandy emulation.

**Comment by Allofich** [comment]
Just to confirm:
Didn't Wengier make it so DOSBox-X automatically runs LOADFIX now if needed? Might that be why it worked now? You wrote in a comment above that LOADFIX allowed getting around the error. Was the issue here that DeluxePaint II was supposed to be able to run without using LOADFIX?

**Comment by joncampbell123** [comment]
Prior to the fix, DeluxePaint II would start up, present it's menu, and then complain that it could not reserve Tandy graphics memory.

**Comment by Wengier** [comment]
It is great that the Tandy graphics memory issue is fixed too.
