### ISSUE TITLE
Blood 3DFX version: Fatal error: unable to load DLL.

### ISSUE THREAD

**Issue by inukaze** [joncampbell123/dosbox-x#1285]
**Describe the bug**
1. When i try to run 3DFX.EXE -setupfile 3dfx.cfg (Oficial Patch) for Blood, i receive "Fatal error: unable to load DLL." but the file "glide2x.ovl" is in the gamedir

**To Reproduce**
1. Download [Blood Shareware](https://www.dosgamesarchive.com/file/blood/blood/) or use your backup cd image

2. If you use the Backup Image, download the official patch from [RTCM Files](http://dukertcm.com/knowledge-base/downloads-rtcm/blood-patchs/#insw)

3. First create directory structure i use command in terminal
mkdir -p "~/MSDOS/DEMOS/3DFX/BLOOD"
copy the "glide2x.ovl" (i use a extract version of GTA for MSDOS, i this works fine with Tomb Raider, and works fine with Voodoo Rush Patch for Tomb Raider) to the new blood directory

Open dosbox-x 
mount c
install the game
i put in "C:\DEMOS\3DFX\BLOOD" and 
try run "3DFX" [Extracted from the Patch File]

4. On the DOSBox-X Window i see the output : 

```
DOS/4GW Protected Mode Run-time Version 1.97
Copyright (c) Rational Systems, Inc. 1990-1994
Using Setup file: BLOOD.CFG

If you get a "Fatal Error," you need to download the Glide drivers from
http://www.3dfx.com

Fatal error: unable to load DLL.
```

![DOSBox-x-0 82 22-SDL1-BloodShareware-3DFX-001](https://user-images.githubusercontent.com/1647332/66687533-e1b84700-ec50-11e9-93d6-38f5ae393851.png)

On the Terminal output i see : 

```
LOG:  315928525 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:  315928580 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1687
LOG:  315928603 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:  315939717 ERROR BIOS:INT15:Unknown call ax=BF01

```

**Expected behavior**
Run the game with 3DFX Support, because the first time works, but after not work anymore i don't understand why. i just exit because is too much brighter and lot of floor texture show in blank instead the textures.

**Environment (please complete the following information):**
 - GNU/Linux
 - DOSBox-X 0.82.22 SDL1
 - Used configuration, e.g. ```dosbox-0.82.22.conf```

**Additional Information : 
[Carmaggedon : Splat Pack](https://www.dosgamesarchive.com/download/carmageddon-splat-pack/) use "CARM3DFX.EXE" to play if you get a black screen try with this enviroment variable : 
`set SST_TMUMEM_SIZE=2`

But if don't work you see on the terminal output

```
LOG: 4245700514 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1500
LOG: 4245981169 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1684
LOG: 4245981409 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1684
LOG: 4246058560 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1684
```

[GunMeta](https://www.dosgamesarchive.com/download/gunmetal/) you can set video mode directly from Game, but notice in where its the resolution 320x240x256 Colors Mode X [Second Position], because if you set 640x480 3dfx Glide [43 Position if you change during Gameplay, you can select if press 8 times up from second position], the screen goes black, and you need choise again a working lower resolution, and set again 640x480 3dfx glide to had enable correctly. 

But if you do this, the game not show any texture, just a background, and part of the GUI in black. and well this don't work fine with this title

[Jet Fighter III](https://www.dosgamesarchive.com/download/jetfighter-iii/) first run SETUP.EXE and set 3DFX Voodoo Rush, If you Press ESC during gameplay open the menu, but the text is not visible, if you want to close de game press ALT+X and after press Y then press enter. well the result on this demo, always is the same, don't matter which 3D Card you had setup. If someone really want to play this don't setup any 3D Card just use VGA.

**Additional context**
I don't know what 3DFX.EXE for Blood is searching for. but in the RTCM says : 

```
* Attention *
3DFX.EXE was released in it's alpha stage. It does not support voxels (it will use sprites instead), it evokes visual glitches (skybox's won't be seamless and status bar is scaled wrong), and suffers from memory leaks. Voodoo RUSH and Voodoo 2 are not supported!

* Important * Windows 95/98 Users.
If you receive an error message that says, "fatal error: unable to load Glide DLL", right-click on the 3DFX.exe file and then choose properties. Click on the MEMORY tab at the top. At the bottom of the screen is a value called “MS-DOS Protected Mode”. In that field, type in "65535" and then click "OK". Now, just double-click on the 3DFX.exe file to start the game and play! 
```

Well another things like this playable demos with 3DFX Support works fine :
[Archimedean Dynasty](https://www.dosgamesarchive.com/download/archimedean-dynasty/) use "AD3DFX.EXE" to play

[Grand Theft Auto](https://www.dosgamesarchive.com/download/grand-theft-auto/) (I use the glide2x.ovl from this demo) use DEMOFX.EXE to play

[Tomb Raider](https://www.dosgamesarchive.com/file/tomb-raider/tomb3dem/) use "TOMB.EXE" to play after setup with "SETUP.EXE"

[Tomb Raider: Unfinished Business](https://www.dosgamesarchive.com/file/tomb-raider-unfinished-business/trub3dfx/) This unzip files, and require a Backup Image or Original Disc into the Drive to Play with this.

[XCar : Experimental Racing](https://www.dosgamesarchive.com/file/xcar-experimental-racing/xdemofx/) you must use the follow command : `set SST_TMUMEM_SIZE=2`

Because if you don't use this command you get the error : 
```
gd error (glide): grTexDownloadMipMap: mipmap  cannot span 2 Mbyte boundarygrTex
DownloadMipMap: mipmap  cannot span 2 Mbyte boundary
```

After you ran that command you can play fine with XCARFX.EXE

[Shadow Warrior V1.2](https://www.dosgamesarchive.com/file/shadow-warrior/3dsw12/) + [Patch](https://www.dosgamesarchive.com/file/shadow-warrior/swsw3d11/) you should set using "SET3DFX.EXE" and run with "SW3DFX.EXE" the first time take a while (on my pc near 3 mins) to show the message "Converting Texture" (with Dynamic Core in 32768 Cycles in Pentium MMX)

Dunnos. 
1 - I just need a "Glide2x.ovl" driver for msdos games ?

2 - How i determine which GPU is emulating DOSBox-x ?

3 - Don't exist Voodoo Drivers for Windows 3.X ?

4 - DOSBox-X just emulate Voodoo Rush or can emulate anothers type of Voodoo ? i want all information i can gather from msdos mode to determine which gpu and specs are in use.

**Comment by aybe** [comment]
> **Expected behavior**
> Run the game with 3DFX Support, because the first time works, but after not work anymore i don't understand why. i just exit because is too much brighter and lot of floor texture show in blank instead the textures.
> 

So it worked at least once, but then refuses to work ?

**Comment by inukaze** [comment]
> So it worked at least once, but then refuses to work ?

Exactly just work the first time, after of that i can't run blood with 3dfx anymore.

**Comment by aybe** [comment]
After a little more than 1 hour spent trying to run Blood and failing I abandon ...

And this didn't help much: https://www.google.com/search?q=blood+3dfx+dosbox

GTA demo works just fine, however, so DOSBox-X is not to blame because 3DFX emulation works with stock settings.

Not exactly what you expect but if you really want to play Blood then BloodGDX is an excellent port:
https://blood-wiki.org/index.php?title=List_of_Source_Ports_and_Recreations#Released
(site is down currently but should be back soon, hopefully)

Port is really good, input is much better than in DOS, you can play in HD and game can be finished (I did).

**Comment by aybe** [comment]
@joncampbell123 

During this intense exercise I have found quite a bunch of bugs, going to fill a few issues :)

**Comment by NebularNerd** [comment]
Fifa International Soccer appears to work with a couple of setting changes, see #2481

**Comment by NebularNerd** [comment]
Got it working 🙂

You will need:
- A proper copy of Blood on CD (or image) I'm using v1.0 and install as normal
- Grab the correct patch from [RTCM Files](http://dukertcm.com/knowledge-base/downloads-rtcm/blood-patchs/#insw), for me it was [r0020.exe](http://dukertcm.com/knowledge-base/downloads-rtcm/blood-patchs/r0020.exe) (Registered v1.0 -> v1.20 3DFX patch) run the patch in DosBox and let it do it's thing (don't worry about missing files)
- Grab [Blood in 3dfx](http://dukertcm.com/knowledge-base/downloads-rtcm/blood-patchs/arjan3dfx.zip) from the above link, copy to the folder where Blood is installed, rename it something 8.3 friendly like `3dfx-run.bat`
- Grab [GLIDE2X.zip](https://github.com/joncampbell123/dosbox-x/files/9792953/GLIDE2X.zip) (I extracted it from the GTA Demo linked above) and place the `GLIDE2X.OVL` file in the Blood directory.
- Run DosBox-x with `memsize=63` and `output=opengl`
- Remember to mount your CD (or image) for CD Audio
- Run the 3dfx-run.bat and enjoy...


https://user-images.githubusercontent.com/8470449/196005609-a5eeae23-62b3-4dab-952c-b2e939be3571.mp4


https://user-images.githubusercontent.com/8470449/196005614-c01d1901-2af7-444f-9170-18ea3fb07991.mp4

**Comment by grapeli** [comment]
It also works with dosbox-x's built-in 3DFx emulation (with very fast `opengl` or very slow `software`).

[dosbox-x.blood.3dfx.webm](https://user-images.githubusercontent.com/452325/196011422-b221af6b-7a5d-49bd-8ac4-aac949b5edbb.webm)

I do not know if there is a need to verify these reports. In my eye a large number should have closed a long time ago. Now it's a terrible mess.

**Comment by NebularNerd** [comment]
I should have mentioned I was using the inbuilt glide emulation (which does work quite well) The main issue was that you needed to jump through a few hoops to get it running.

I had already been testing Blood to help out on #3752 so as I was already halfway done I thought I would give this another go. I was also using these old posts as a source of software for testing again PHYSFS, kill two birds with one stone kind of thing. If I find I get one of these old posts working then I'll share it as someone somewhere may find it helpful.

What DosBox-x could possibly do with is a dedicated page or database with known good settings, but like the [DosBox compatibility list](https://www.dosbox.com/comp_list.php?letter=a) it's a huge amount of work to maintain and would soon end up as just another forum. 

@joncampbell123 This can now be closed, Blood 3DFX works fine once setup correctly.
