### ISSUE TITLE
Possible bug in SDL-drawn menus

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1286]
There's an odd bit of code in both `MenuShadeRect()` and `MenuDrawRect()` in `sdlmain.cpp`:

```
        if (x < 0) {
            w += x;
            x = 0;
        }
        if (y < 0) {
            y += h;
            y = 0;
        }
```

`y += h` is probably supposed to be `h += y`.

**Comment by joncampbell123** [comment]
Good catch... it might have caused some serious issues if the shade function were ever called with a negative y coordinate.
