### ISSUE TITLE
3Dfx Voodoo card emulation broken

### ISSUE THREAD

**Issue by Gui55** [joncampbell123/dosbox-x#129]
Noticed this when using WinME inside DOSBox-X. Also noticed PCI bus (along with S3 Trio. 32/64 PCI) still show up as working in device manger. ISA PNP Bus is gone, but shows up as working too in device manager if installed manually, but still the Voodoo card isn't found.

**Comment by joncampbell123** [comment]
I made some recent commits that fix PCI enumeration and 3dfx problems. I just did an install of Windows ME and the Voodoo card is showing up fine.

When you confirm the same on your end, I would like to go ahead and close this?

**Comment by Gui55** [comment]
Yep, I can confirm it's now fixed. Thank-you very much!

**Comment by Jarvik7** [comment]
Do the PCI enumeration fixes fix UMBPCI failing to find the PCI bus and refusing to start, or are they just voodoo related?

(http://www.uwe-sieber.de/umbpci_e.html)
