### ISSUE TITLE
Space Pigs Megademo: copperbar adjustment does not respond to keyboard

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#13]
During the configuration phase of the demo a screen is shown instructing the user to move the cyan bar down between the arrows. Keyboard input does not work.

http://www.pouet.net/prod.php?which=3972

**Comment by Allofich** [comment]
Tested using latest code, commit b3f8ffc, and also tried with Mar 15, 2015 release which would be current at time of this report. The behavior on the bar screen was the same, so the issue remains.

But, the bug description here seems inaccurate. The program *does* respond to keyboard input, as the flickering of the text, which is also supposed to change in response to pressing the keys, does indeed change. Only the cyan bar does not move.

For the configuration questions I selected 3 "VGA card (standard)", 1 for the sound (don't know what is the correct choice there) and 1 "Hey, my machine is fast enough!".

Note you have to run LOADFIX before running the demo or it will fail to load. Even after running LOADFIX a couple errors are logged.

  22129568       EXEC:Execute megademo.EXE 0
  22129568       FILES:file open command 0 file megademo.EXE
  22129568 ERROR EXEC:stack underflow/wrap at EXEC SS:SP=021b:0000
  23823620       EXEC:Execute MEGADEMO.001                      0
  23823620       FILES:file open command 0 file MEGADEMO.001                     
  23823620 ERROR EXEC:stack underflow/wrap at EXEC SS:SP=015b:0000

Also tried DOSBox 0.74. It does not display any flickering (which the text suggests it should) or the cyan bar at all.

**Comment by joncampbell123** [comment]
TODO: It would be better to run this on real hardware to assess what it should look like and how it should respond.
