### ISSUE TITLE
Add MT-32 support in Linux

### ISSUE THREAD

**Issue by ParticleMon** [joncampbell123/dosbox-x#1301]
dosbox-patched has working MT-32 emulation with Munt in Ubuntu.
How about merging it?

https://launchpad.net/~i30817/+archive/ubuntu/dosbox-patched

**Comment by joncampbell123** [comment]
DOSBox-X already has MT-32 emulation, at least when I compile here on Linux. It just has to be enabled.

**Comment by joncampbell123** [comment]
To be fair it is fairly old though, brought in from DOSBox Daum, and appears to have been modified to use SSE instructions.

**Comment by joncampbell123** [comment]
DOSBox-X already has working MT-32 emulation, though it's an older version.

Feel free to submit a patch that updates the MT-32 emulation, if wanted.
