### ISSUE TITLE
Trying to make 8gb hard drive image

### ISSUE THREAD

**Issue by WindowsNinetyTen** [joncampbell123/dosbox-x#1303]
When I try to create an 8gb hard drive image using imagemake, I get a message saying "not enough space available for the image file. Need 4119494144 bytes."

**Comment by joncampbell123** [comment]
"Imagemake" is not a built-in command in DOSBox-X. What are you using to create the image file?

**Comment by HomerBender77** [comment]
Whoops, I meant "imgmake". When I go into that and try to make an 8gb hd image with "imgake (name)_8gig", I get the message stated above.

**Comment by aybe** [comment]
When you mount a drive with say like `mount c .`, you can see there's around 256Mb of free space, trying to create such image will then fail ... obviously!

You could do `mount c . -freesize NNNN` but it appears to fail above `1024` so for the time being the maximum free space that will be reported will be 1Gb but surprisingly, 2Gb images can be created!

@joncampbell123 probably some bug laying around

**Comment by joncampbell123** [comment]
@aybe Another barrier is that the MS-DOS API is limited to file sizes 2GB or less. There is a newer API that appeared when Microsoft added FAT32 support that allows file sizes up to just under 4GB, which are not yet emulated by DOSBox-X (or DOSBox SVN). So it's not really a bug, just an API limitation with INT 21h. It's better to use an external tool to create >= 2GB images.

I'm also aware of a bug I found by accident in MS-DOS 6.22 and FAT12 drives (such as a floppy disk) where you can apparently seek to very large offsets well beyond the limits of the disk that wrap around to a valid offset, and cause large (invalid) file sizes to appear in the directory entry. It isn't apparently until you run SCANDISK which rightfully complains about it and fixes it.

**Comment by aybe** [comment]
That's right, 2Gb file limit ... forgot about it already !

**Comment by Wengier** [comment]
IMGMAKE already supports FAT32 disk images in recent DOSBox-X versions, so this is no longer an issue.
