### ISSUE TITLE
type dosbox in terminal to run dosbox?

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#131]
you know how if you compile dosbox from source, or run apt-get install dosbox you can then run dosbox by simply typing dosbox in the terminal?

Well I can't do that since I compiled my 32-bit dosbox on a separate system and then moved it across to my 64-bit system.

If I type dosbox in terminal I get
The program 'dosbox' is currently not installed. You can install it by typing:
sudo apt-get install dosbox

unless I'm in the folder where I put dosbox

I was if I could make it so that I just have to type in dosbox in the terminal and have it start dosbox like it's supposed to?

**Comment by DominusExult** [comment]
make a file alias to the dosbox binary somewhere in your path.

Or in the file that sets up your terminal (on OS X it is ~/.profile) add the following line and restart terminal:
alias dosbox="path/dosbox"

if you at some point decide to install dosbox via apt-get you will need to get rid of either alias.

**Comment by joncampbell123** [comment]
Did you compile your 32-bit DOSBox statically or against dynamic libraries? You would need to carry over the .so shared library files with it. Transferring the binaries over would be easiest if you compiled it into one static binary with no external dependencies.

**Comment by toddfraser88** [comment]
I'm not sure, I think dynamically as it kept asking for different .so files, so i copied them across until it worked

how do I compile statically so I don't need those dependencies?

editing ~/.bashrc with an alias pointing to it worked for me - thanks
