### ISSUE TITLE
Sound Blaster MIDI DSP commands 0x30-0x31 and 0x34-0x37 not implented, MIDPLAY.EXE does not work

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#132]
whenever I try to play MIDI files through MIDI players like megamid or midplay - I get this output in the dosbox console

LOG:   45243075 ERROR SBLASTER:DSP:Unhandled (undocumented) command 49
LOG:   45247464 ERROR SBLASTER:DSP:Unhandled (undocumented) command 6C
LOG:   45250254 ERROR SBLASTER:DSP:Unimplemented input command 99
LOG:   45252072 ERROR SBLASTER:DSP:Unhandled (undocumented) command 33
LOG:   45253430 ERROR SBLASTER:DSP:Unhandled (undocumented) command 5C
LOG:   61304050 ERROR SBLASTER:DSP:Unhandled (undocumented) command 89
LOG:   62256636 ERROR SBLASTER:DSP:Unhandled (undocumented) command 89
LOG:   63207089 ERROR SBLASTER:DSP:Faked ADC for 35073 bytes
LOG:   63209547 ERROR SBLASTER:DSP:Unhandled (undocumented) command 33
LOG:   63211266 ERROR SBLASTER:DSP:Unhandled (undocumented) command  0
LOG:   64155794 ERROR SBLASTER:DSP:Unhandled (undocumented) command 89
LOG:   64159153 ERROR SBLASTER:DSP:Unhandled (undocumented) command 49
LOG:   64161773 ERROR SBLASTER:DSP:Unhandled (undocumented) command  0
LOG:   67944050 ERROR SBLASTER:DSP:Unhandled (undocumented) command 83
LOG:   67946984 ERROR SBLASTER:DSP:Unhandled (undocumented) command 4F
LOG:   67948673 ERROR SBLASTER:DSP:Unhandled (undocumented) command  0
LOG:   82132967 ERROR SBLASTER:DSP:Unhandled (undocumented) command 81
LOG:   82136043 ERROR SBLASTER:DSP:Unimplemented MIDI I/O command 30
LOG:   82137368 ERROR SBLASTER:DSP:Unhandled (undocumented) command  0
LOG:   88755483 ERROR SBLASTER:DSP:Unhandled (undocumented) command 81
LOG:   88759881 ERROR SBLASTER:DSP:Unimplemented MIDI UART command 37
LOG:   88762807 ERROR SBLASTER:DSP:Unhandled (undocumented) command  0
LOG:   90653056 ERROR SBLASTER:DSP:Unhandled (undocumented) command 81
LOG:   90655694 ERROR SBLASTER:DSP:Unhandled (undocumented) command 3C
LOG:   90660086 ERROR SBLASTER:DSP:Unhandled (undocumented) command  0
LOG:   96344027 ERROR SBLASTER:DSP:Faked ADC for 37485 bytes
LOG:   96355486 ERROR SBLASTER:DSP:Faked ADC for 37753 bytes
LOG:   96359198 ERROR SBLASTER:DSP:Unhandled (undocumented) command 4B
LOG:   96364221 ERROR SBLASTER:DSP:Unhandled (undocumented) command 6C
LOG:   96368754 ERROR SBLASTER:DSP:Unimplemented input command 99
LOG:   96378086 ERROR SBLASTER:DSP:Unimplemented input command 99

is this expected behavior?

**Comment by joncampbell123** [comment]
I don't think Sound Blaster emulation is designed to emulate the MIDI commands, or it's not emulated well, since Roland MPU-401 emulation is available anyway. Where can I get those programs to test against? If I can't obtain those programs, then I will attempt to test the same case using Windows 3.1 SB16 drivers.

**Comment by toddfraser88** [comment]
I got them here

http://www.hitsquad.com/smm/dos/

**Comment by joncampbell123** [comment]
MEGAMID seems content with using the MPU-401 to play MIDI. MIDPLAY however is using the Sound Blaster MIDI DSP commands as your debug log indicates, which neither DOSBox nor DOSBox-X yet emulates.

I noticed at the start of MIDI playback this message:

DSP:Unimplemented MIDI I/O command 31

Here's a list of all known DSP commands including the MIDI commands not yet implemented by DOSBox(-X):

http://the.earth.li/~tfm/oldpage/sb_dsp.html

**Comment by toddfraser88** [comment]
I can't get MEGAMID to play any sound at all

how did you get it working?

**Comment by joncampbell123** [comment]
I have MPU-401 emulation enabled, in "intelligent" mode. It seems to work for me with sbtype=sb1 through sbtype=sb16 just fine. I have MIDI emulation set up to use "synth" mode using Fluidsynth and a soundfont. It seems to work fine whether you tell it to use Sound Blaster MIDI (DSP command 38h) or MPU-401.

**Comment by joncampbell123** [comment]
Check the latest commit. DSP commands 34h-37h are implemented now. These commands switch the DSP into a passive conduit for MIDI data (UART) until you reset the DSP. MIDPLAY now works in DOSBox-X.

**Comment by toddfraser88** [comment]
I'll try the latest commit in a bit

I've just been running with the default MIDI settings, no fluidsynth, I was expecting FM Synth emulation to work at least but I don't hear anything

**Comment by toddfraser88** [comment]
OK, I tried the latest commit

I must be doing something wrong somewhere, I'm still not getting any sound.

**Comment by toddfraser88** [comment]
I tested MEGAMID in dosbox on my windows installation and it's working on windows.

So I can only assume something is broken on my linux installation

**Comment by toddfraser88** [comment]
also, thanks for implementing these commands

**Comment by joncampbell123** [comment]
MEGAMID works anyway. Try MIDPLAY. Thats the one using the DSP MIDI UART mode that was just added.

**Comment by toddfraser88** [comment]
it's working on windows

on linux - no sound - but am no longer getting missing commands showing up in console
