### ISSUE TITLE
'Reset guest system': host key gets stuck after reboot

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1320]
**Describe the bug**

F11 is stuck after pressing F11+R.

**To Reproduce**
1. start dosbox
2. press F11+R
3. dosbox reboots
4. type 'dir', you'll only be able to type 'di'
5. reboots again
6. press F11, now it's unstuck
7. type 'dir', does not reboot

**Expected behavior**

F11 shall not be stuck after F11+R.

**Environment:**
Microsoft Windows [Version 10.0.18362.388]
0.82.23
dosbox-x-windows-20191031-191254-windows.zip

**Comment by joncampbell123** [comment]
Easy to miss here, SDL1 on Linux likes to reset keyboard state (all keys are treated as up even if I'm holding a key) every time it recreates or resizes the window.

**Comment by aybe** [comment]
So I've tried calling `MAPPER_ReleaseAllKeys` in `ResetSystem` but it failed -> wrong approach obviously.

Now for the theory I guess one should send `SDL_KEYUP` to SDL but on how exactly and in a clean manner is another story.
