### ISSUE TITLE
CONFIG.COM and MIXER.COM both disappear from Z:\ after 'Reset guest system'

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1321]
**To Reproduce**
1. start dosbox
2. dir Z: -> 45 files
3. F11+R
2. dir Z: -> 43 files

**Environment:**
 Microsoft Windows [Version 10.0.18362.388]
0.82.23
dosbox-x-windows-20191031-191254-windows.zip

**Comment by aybe** [comment]
So `PROGRAMS_Init` is only called in `SDL_main` but never runs after `ResetSystem`.

@joncampbell123 
Not sure whether and what should be called after resetting the system...

**Comment by joncampbell123** [comment]
Fixed.
