### ISSUE TITLE
28.COM fails ... sometimes

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1324]
**To Reproduce**
1. start dosbox
2. type the following:
```
50
dir
28
```
3. nothing will work but `cls` to restore prompt

**Screenshots**
Just looks like it has hanged but in fact it hasn't:
![dosbox-x_2019-11-07_00-05-02](https://user-images.githubusercontent.com/1537591/68345705-45b81900-00f2-11ea-8b6b-bcfd68f70821.png)

**Environment (please complete the following information):**
Microsoft Windows [Version 10.0.18362.388]
0.82.23
dosbox-x-windows-20191031-191254-windows.zip

**Comment by joncampbell123** [comment]
I think what should happen is the BIOS should range check the Y coordinate of the cursor against number of rows and set it to bottom row.

I don't think it should necessarily clear the screen below it.

Of course what exactly happens should be determined by 25.COM, 28.COM, and 50.COM running on real hardware.

**Comment by aybe** [comment]
The problem is nothing works but `cls` or a program that changes video mode in 'some way' like `intro`.

So I thought the easiest might be to simply clear the screen like `25.com` does.

**Comment by aybe** [comment]
same as https://github.com/joncampbell123/dosbox-x/issues/1325#issuecomment-552124019

**Comment by joncampbell123** [comment]
28.com and 50.com call the BIOS to change text height but do not move the cursor position up to stay on screen.

If you go to 50-line mode then 28-line mode and the cursor is below line 28 it will remain below line 28 and invisible.

**Comment by joncampbell123** [comment]
25.COM uses INT AX=0003h, which causes a modeset and clear. http://www.ctyme.com/intr/rb-0069.htm

28.COM uses INT AX=1111h, which sets the 8x14 font and a modeset but not clearing cursor or screen. http://www.ctyme.com/intr/rb-0145.htm

50.COM uses INT AX=1112h, which sets the 8x14 font and a modeset but not clearing cursor or screen. http://www.ctyme.com/intr/rb-0147.htm
