### ISSUE TITLE
50.COM should clear screen buffer after prompt

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1325]
**To Reproduce**
1. start dosbox
2. type the following:
```
50
dir
28
cls
50
```
3. there is garbage after the prompt

**Screenshots**
![dosbox-x_2019-11-07_00-14-24](https://user-images.githubusercontent.com/1537591/68346121-9aa85f00-00f3-11ea-98aa-2f522bc5fe4e.png)

**Environment (please complete the following information):**
Microsoft Windows [Version 10.0.18362.388]
0.82.23
dosbox-x-windows-20191031-191254-windows.zip

**Comment by aybe** [comment]
#1324

@joncampbell123 

How can I clear the screen using ASM ?

**Comment by joncampbell123** [comment]
In IBM PC mode, load ES with 0xB000 (mono) or 0xB800 (color) set DI to 0, AX to 0, CX to 16384 (to fill 32768 bytes), and REP STOSW.

**Comment by joncampbell123** [comment]
The standard detection between mono (MDA) and color (CGA) is to read bits [5:4] from AX after calling INT 11h.

http://www.ctyme.com/intr/rb-0575.htm

**Comment by aybe** [comment]
I was thinking it'd be easier but as I never did any ASM I am not likely to magically pull it out by tonight... :(

**Comment by aybe** [comment]
@joncampbell123 
Tried a few things, all failed, I am curious to see what ASM you'd come up with.
