### ISSUE TITLE
Building solution now also requires Windows SDK 10.0.17134.0?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1326]
**Describe the bug**

Not only Windows 8.1 SDK is required but also 10.0.17134.0 is.

Shouldn't it require one or the other, but not both ? Someone please clarify.

**Comment by joncampbell123** [comment]
It should be building all with the same SDK.

If it is possible to build with SDK 10.0.17134.0 but retain the ability for the binary to run on Windows 7 through 10, then all should use the 10.0.17134.0 SDK.

**Comment by aybe** [comment]
Okay, I'll see what I can do.

**Comment by aybe** [comment]
If you do this:

https://github.com/joncampbell123/dosbox-x/commit/2469ecb87db44eabdc503a8de89cb2f0084a9537#diff-ac3b1ae90cb3797dfc4f060f3be32a1d

Then you don't need to upgrade platform toolset anymore (and edit all projects), but then you get:

_error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found._

This one is not available in the installer, maybe this one project (freetype) should be upgraded to 2017 like others?

**Comment by aybe** [comment]
#1331

**Comment by aybe** [comment]
Version 10 can target Windows 7:
https://docs.microsoft.com/en-us/cpp/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application?view=vs-2019

In an ideal world, this solution should use this version and see all its projects upgraded accordingly.

#1339

**Comment by aybe** [comment]
closing, refer to #1339 instead
