### ISSUE TITLE
compile dosbox statically?

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#133]
It was mentioned earlier in another thread that it is possible to compile dosbox statically so that you do not need to copy dosbox's dependencies across along with dosbox

just wondering how do I compile dosbox statically so I don't need to copy those dependencies across?

**Comment by joncampbell123** [comment]
I've never actually tried it yet, but theoretically you'll need to compile DOSBox-X with -static in the CFLAGS, CXXFLAGS, and LDFLAGS. I think you'll need -static-libgcc in there as well. Next, you'll need to compile it's dependencies as static libraries. That means SDL, and SDL's dependencies including ALSA and the X libraries. When you recompile DOSBox-X against those statically linked dependencies, then the binary should be statically linked. Use objdump or nm to be sure.

**Comment by Allofich** [comment]
There's a duplicate issue at https://github.com/joncampbell123/dosbox-x/issues/228. I'm copying over the suggestion above into that issue, so I suggest closing this one.
