### ISSUE TITLE
M.A.X. - Mechanized Assault & Exploration: slow map scrolling

### ISSUE THREAD

**Issue by DwarfFighterCleric** [joncampbell123/dosbox-x#1338]
Is it possible to determine why this game gets so slow when you scroll the map at 40000 fixed cycles?
What exactly is happening there? Is the bottleneck the I/O disk read speed? Or is it about the SVGA render? Or both?
I'm uploading the full game (file named MAX_RU, 25 MB download, play using MAXRUN.EXE) for you guys to see what I'm talking about for yourselves. A quick way to reproduce this is starting a New Campaign and going to the 8th Mission. Right at the start, your base is full of units and the map scrolling lags a lot. It wasn't like that in my 486 back in the day, so why is Dosbox so comparatively slow in this area?

**Comment by aybe** [comment]
After testing, game isn't much slower with `40000` cycles than when using `max` cycles for CPU, it's perfectly playable.

**Comment by joncampbell123** [comment]
If you capture video of the emulation, does the captured video show any slowdown?

Also, dynamic core might help with slowdowns.

**Comment by DwarfFighterCleric** [comment]
What you guys would guess is the way this game achieves the map scrolling? I mean, does the game have to redraw the entire screen (units, buildings) at every scrolling "step"? My guess is that the game needs to read from disk at every frame, thus slowing everything down. And I also notice scrolling with the keyboard is a tad faster than with mouse, there's a subtle difference there, like two different pieces of code were used for each. I wonder what kind of DOS sorcery the original devs used to get this working. It's not critical or anything, it's just matter of curiosity and hopefully bring improvement in future dosbox releases.

**Comment by aybe** [comment]
These questions are better off asked at https://www.vogons.org/index.php.
