### ISSUE TITLE
Status for the Visual Studio solution

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1339]
## Summary

Consolidating solution to use only VS2019 projects and Windows 10 SDK:
- ~~dosbox-x~~ done
- using DirectX from SDK requires non-trivial changes, there are subtle differences
- SDL projects don't build
- ARM builds seems to have drifted a lot, they don't build

(anything else not in this list hasn't been tested)

**Comment by aybe** [comment]
#1335

**Comment by aybe** [comment]
done for dosbox-x:
https://github.com/joncampbell123/dosbox-x/commit/8d08f4e724be76db752eac956462587619a446f0

**Comment by aybe** [comment]
TODO update after #1351

**Comment by joncampbell123** [comment]
I can confirm that DOSBox-X can build from the project file IF you install VS2019 and toolset v142.
