### ISSUE TITLE
mixer /listmidi - shows no devices

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#135]
mixer /listmidi - shows no devices

I noticed this on my linux installation of dosbox - 

I imagine this is why the MIDI players I was testing did not work.

would it be possible to code dosbox so that if, for whatever reason, no devices show up in /listmidi that it sets the internal soundblaster MIDI emulation as device 0 so that you at least get FM Synth?

**Comment by joncampbell123** [comment]
Hm, mixer /listmidi shows nothing here either, but Fluidsynth is working perfectly.

Are you asking that DOSBox-X carry some sort of built-in MIDI -> OPL3 playback support? MIDI through FM synth is usually done at the OS level (i.e. Windows 3.1/95).

**Comment by toddfraser88** [comment]
but on real soundblaster hardware doesn't FM synth come through the MIDI port when you play MIDI files in DOS?

**Comment by joncampbell123** [comment]
No. The MIDI UART is completely separate from the OPL3 on the card. But Windows 3.1 through 98 have drivers that can render MIDI through the OPL3 chip. DOS games generally have either two versions for OPL3 and MIDI or they do their own MIDI to FM playback. Some SB clones and GUS have TSR programs that can use hardware NMI or virtual 8086 mode to trap IO writes to MPU-401 MIDI ports and emulate it in software. The sound card itself does not render MIDI except to send it out the MIDI port.

**Comment by toddfraser88** [comment]
So the only solution in this case would be to boot into windows?

**Comment by joncampbell123** [comment]
Assuming your Linux DOSBox-X compile has enabled Fluidsynth support, I recommend you download their soundfont file and then set up your dosbox.conf to use it.

http://en.osdn.jp/projects/sfnet_androidframe/downloads/soundfonts/FluidR3_GM.sf2/

Put the .sf2 file in the same directory as your dosbox.conf, then,

Set your dosbox.conf up like this:

    [midi]
    mpu401=intelligent
    mididevice=synth
    midiconfig=FluidR3_GM.sf2

**Comment by toddfraser88** [comment]
OK, I've done that, but fluidsynth doesn't seem to want to work

how do i check if fluidsynth is enabled on my dosbox build?

**Comment by joncampbell123** [comment]
In Linux builds, look at config.h. You should see:

    /* Define to 1 to enable fluidsynth MIDI synthesis */
    #define C_FLUIDSYNTH 1

**Comment by ghoul8765** [comment]
http://www.vogons.org/viewtopic.php?f=31&t=46343

A dosbox author replied that listmidi doesn't work on linux.

**Comment by toddfraser88** [comment]
I've followed your instructions, but Fluidsynth just doesn't want to work for me

I don't even know why

**Comment by joncampbell123** [comment]
Run the compiled binary with the --debug switch. Somewhere in the debugging output there should be a message from the MIDI emulation on whether or not Fluidsynth was initialized and whether it was able to open the soundfount.

**Comment by toddfraser88** [comment]
LOG:          0 DEBUG MISC:Initializing MIDI emulation
LOG:          0 DEBUG MISC:MIDI:Can't find device:synth, finding default handler.
LOG:          0 WARN  MISC:ALSA:Invalid alsa port FluidR3_G
LOG: SDLNet_ResolveHost: 
LOG: TiMidity: can't open control connection (host=FluidR3_GM.sf2, port=7777)
LOG:          0 WARN  MISC:MT32: Control ROM file not found
LOG:          0 DEBUG MISC:MIDI:Opened device:none

**Comment by joncampbell123** [comment]
This is from Linux, right?

So if it can't find "synth" then FluidSynth is apparently not being compiled into the build.

Perhaps you need to "apt get" or "yum install" the fluidsynth package and development headers for your distribution.

If Fluidsynth is already there, one way to test it, is to bring up VLC player and see if VLC player has any configuration options for using FluidSynth. If it does, there should be a configuration page where you enter the path of a SoundFont. If it works, you should be able to open and play a MIDI file in VLC player with it.

**Comment by toddfraser88** [comment]
yep, fluidsynth working in VLC

**Comment by joncampbell123** [comment]
going back to DOSBox-X, does config.h mention FLUIDSYNTH? Like this:

    /* Define to 1 to enable fluidsynth MIDI synthesis */
    #define C_FLUIDSYNTH 1

If that line is an #undef instead of a #define, then look at config.log to see if any error messages can indicate why autoconf did not pick up on FluidSynth.

One possible reason off the top of my head: are the development headers installed for FluidSynth? Most distros I know tend to install the libraries but omit the headers unless you install them. In some Linux distributions I've worked with there is for example a 'libcap' and 'libcap-devel' package that contains the library and headers respectively.

**Comment by toddfraser88** [comment]
I had to compile fluidsynth from source for config to detect it as present, buy yeah thats what is in my config.h

**Comment by DominusExult** [comment]
Just to make sure, but you were using a special 32bit build before - that one will not work with the 64bit default your system will built.

**Comment by joncampbell123** [comment]
We're using standard 32-bit and 64-bit build processes, no cross compiling. FluidSynth and DOSBox-X can be compiled for either 32-bit and 64-bit.

**Comment by toddfraser88** [comment]
yeah, I compiled a 64-bit build, fluidsynth worked there.

The way I've setup dosbox-x 32 bit is like this

/dosbox-X-32bit/binary/usr/local/bin

my compile binary is in /bin

I've also got all the 32-bit dependencies for it in /libs/i686 inside the bin folder

I also use this which I got off of a gog.com script

	export LD_LIBRARY_PATH="${CURRENT_DIR}/libs/i686"

  echo "Starting DOSBox"
   "${CURRENT_DIR}/dosbox_i686" "$@"


echo "Done."

maybe my fluidsynth in the i686 folder is missing something?

**Comment by joncampbell123** [comment]
Will do.
