### ISSUE TITLE
MOUNT C . syntax does not work in XP

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1350]
![VirtualBoxVM_2019-11-14_05-56-04](https://user-images.githubusercontent.com/1537591/68827905-ec2c8d00-06a3-11ea-8673-d423255472d5.png)

Works in Win10:

![dosbox-x_2019-11-14_06-00-21](https://user-images.githubusercontent.com/1537591/68827942-11b99680-06a4-11ea-9584-58331bbb4a11.png)

**Comment by aybe** [comment]
I have no idea on how to debug that ... remote VS2019 tools needs at least Win7.

**Comment by joncampbell123** [comment]
I see Microsoft has still not yet fixed the bug with stat() and Windows XP.

For whatever reason, stat() does not work on Windows XP if compiled with VS2015 or later even if you target Windows XP.

This is why I didn't bother to target XP with the VS2015 project file.

If you want XP support, install MinGW and compile with the build-mingw scripts.

**Comment by yksoft1** [comment]
Seems the VS2019 CRT officially dropped XP support once and for all.
VS2015 SP2 and VS2017 had a CRT with stat() working in XP.

**Comment by aybe** [comment]
Now I remember there was such bug ...

**Comment by joncampbell123** [comment]
@aybe I think it's better if VS2017 builds just ignore Windows XP and require Windows 7 or higher. Microsoft doesn't seem to care much about Windows XP anymore. Windows XP users can run the MinGW-built binaries instead.
