### ISSUE TITLE
Switch development to VS2019 instead of VS2017.

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1358]
As stated before, MinGW is explicitly supported as a means to compile binaries compatible with Windows XP.
Microsoft has marked the Windows XP compatible toolset as deprecated. It's foolish to waste time supporting something they will drop soon.

**Comment by Allofich** [comment]
The VS 2017 solution is fully switched over to VS 2019 now, isn't it?

Also, the VS 2013 solution looks like it was last touched 2 years ago and maybe should be removed.
