### ISSUE TITLE
32bit dosbox-x - need help to get fluidsynth to work

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#136]
I'm trying to get my build of dosbox-x 32-bit to work with fluidsynth

I compiled it on a 32-bit system with fluidsynth present

I've got my dosbox-x in a directory structure like this

/dosbox-x-32-bit/usr/local/bin
dosbox and fluidsynth executable in there

/dosbox-x-32-bit/usr/local/bin/include
contains fluidsynth include files - not sure if fluidsynth needs these to work

/dosbox-x-32-bit/usr/local/bin/libs/i686
contains all the *.so files needed for dosbox to work 
I also put fluidsynth.so files in there - not sure if that does anything

I use this script that I got from gog.com to point 32bit dosbox-x to it's dependencies

declare -r CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

 change dir to script

	export LD_LIBRARY_PATH="${CURRENT_DIR}/libs/i686"

 I added these additional export lines - not sure if they help with fluidsynth

	export LDFLAGS="${CURRENT_DIR}/libs/i686"
	export C_INCLUDE_PATH="${CURRENT_DIR}/include"
	export CPLUS_INCLUDE_PATH="${CURRENT_DIR}/include"
	export CPPFLAGS="${CURRENT_DIR}/include"

  echo "Starting DOSBox"
   "${CURRENT_DIR}/dosbox_i686" "$@"

echo "Done."

**Comment by DominusExult** [comment]
First step is to know whether it works on the system you built on. 
Then Fluidsynth itself has a couple of dependencies which need to be present and in the correct arch.

**Comment by toddfraser88** [comment]
OK, I tried again, starting from scratch on a 32-bit lubuntu live boot DVD

I got this in debug log

LOG:          0 ERROR ALL:Unable to open file "FluidR3_GM.sf2"
LOG:          0 ERROR ALL:Couldn't load soundfont file
LOG:          0 ERROR ALL:Failed to load SoundFont "FluidR3_GM.sf2"
LOG:          0 WARN  ALL:Failed to pin the sample data to RAM; swapping is possible.
LOG:          0 DEBUG MISC:MIDI:Opened device:synth

seems it doesn't want to load the soundfont for some reason

but at least it opened the synth device on 32-bit

soundfont located in these folders

/home/lubuntu/.dosbox/capture
/home/lubuntu/.dosbox

dosbox.conf

mpu401=intelligent
mididevice=synth
midiconfig=FluidR3_GM.sf2



any help?

**Comment by DominusExult** [comment]
Full path to the soundfont in the conf might help

**Comment by toddfraser88** [comment]
path is

midiconfig=/home/toddbrowser/.dosbox/capture/FluidR3_GM.sf2

fluidsynth is working on my 32-bit testing system now, but still broken on my 64-bit

what are the fluidsynth files I need to migrate over from 32-bit?

on my 64-bit system I've got

dosbox-x-32bit/19Jan2016/binary/usr/local/bin/libs/i686/libfluidsynth
dosbox-x-32bit/19Jan2016/binary/usr/local/bin/libs/i686/libfluidsynth.la
dosbox-x-32bit/19Jan2016/binary/usr/local/bin/libs/i686/libfluidsynth.so
dosbox-x-32bit/19Jan2016/binary/usr/local/bin/libs/i686/libfluidsynth.so.1
dosbox-x-32bit/19Jan2016/binary/usr/local/bin/libs/i686/libfluidsynth.so.1.5.2
dosbox-x-32bit/19Jan2016/binary/usr/local/bin/libs/i686/pkgconfig/fluidsynth.pc

dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/types.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/settings.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/synth.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/event.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/seq.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/seqbind.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/shell.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/sfont.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/ramsfont.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/audio.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/midi.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/log.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/misc.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/version.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/voice.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/mod.h
dosbox-x-32bit/17Jan2016/binary/usr/local/bin/include/fluidsynth/gen.h


am i missing anything?

**Comment by DominusExult** [comment]
All dependencies of fluidsynth are missing

**Comment by toddfraser88** [comment]
OK, where are the dependencies located?

**Comment by DominusExult** [comment]
fluidsynth needs a lot of stuff (reason why I don't bundle it with OS X snapshots I do of other software).
You might be better off finding out how to have an extra 32bit toolchain on your 64bit linux when it comes to stuff like fluidsynth.
You can see at https://trac.macports.org/browser/trunk/dports/multimedia/fluidsynth/Portfile which libs fluidsynth depends on when you built it with everything... (Macports is a package manager for OS X, but as a reference it works well enough now).

**Comment by toddfraser88** [comment]
I've never used toolchain on lubuntu before, is it that hard to setup?

if it is difficult, I'll probably just grab all the dependencies individually and copy them across the slow way.

**Comment by DominusExult** [comment]
Sorry, I have no detailed instructions for linux. I've only done it a couple of times from scratch for OS X.
You'd need to google it...

**Comment by toddfraser88** [comment]
I managed to get fluidsynth to work!

**Comment by DominusExult** [comment]
Yeah!!! ;)

**Comment by joncampbell123** [comment]
Shall I close this issue?

**Comment by toddfraser88** [comment]
yeah
