### ISSUE TITLE
Blue Force (Tsunami DOS game) only black screen

### ISSUE THREAD

**Issue by clst** [joncampbell123/dosbox-x#1362]
**Describe the bug**
Vanilla Dosbox works fine. DosBox-X shows a black screen with machine=svga_s3 with the game's sound playing. No error messages on stdout.

When I try machine=mcga (probably not supported) I get a few artifacts that resemble the scrambled screens.

**Environment (please complete the following information):**
 - Operating system: Arch Linux
 - DOSBox-X 0.82.23, compiled from aur package
 - Used configuration: blank dosbox.conf, all defaults

**Comment by joncampbell123** [comment]
Please try the game on real hardware.
As far as I can tell it's writing the VGA attribute controller in a way that leaves the screen blank.

The design of the attribute controller requires disabling screen output to write the palette (I/O write 0x3C0 with bit 5 clear). Port 0x3C0 index with bit 5 set re-enables the screen.

The game appears not to be modifying the palette, but instead AC registers at indexes 0x10 and 0x14. However bit 5 is clear, which means disabling the screen, and the game does not write another index with bit 5 to re-enable the screen.

**Comment by joncampbell123** [comment]
The only way this could possibly work is if somehow bit 5 doesn't mean anything when the index in bits [4:0] are 0x10 or higher (i.e. doesn't blank the screen if clear).

I've already uncovered what Paradise SVGA and PS/2 VGA does for indexes 0x18-0x1F (they mirror 0x10-0x17), perhaps this is another undocumented quirk the game relies on.

**Comment by joncampbell123** [comment]
If you have any MS-DOS VGA hardware around (perhaps a Pentium with SVGA), could you bring up DEBUG.EXE and see what happens when you enter:

- This should blank the screen until "o 3c5,25" (type it blind)
    o 3c0,5
    o 3c0,5
    o 3c0,5
    o 3c0,5
    o 3c0,25

- Now try (assuming the DOS prompt is visible again). It should retain the DOS prompt:
    o 3c0,10
    o 3c0,0
    o 3c0,30
    o 3c0,0

Does the screen go blank at "3c0,10" or does it stay visible?

See also: http://www.osdever.net/FreeVGA/vga/attrreg.htm

**Comment by joncampbell123** [comment]
I can make the game display properly if I add code to ignore bit 5 for indexes 0x10-0x1F.
![blue_000](https://user-images.githubusercontent.com/6245486/70402964-13982080-19ea-11ea-958f-f6ee55d69090.png)

**Comment by joncampbell123** [comment]
I'll check later when I can on real hardware what the behavior of the attribute controller is here.

**Comment by joncampbell123** [comment]
Except.. DOSBox SVN doesn't have a problem here.

**Comment by joncampbell123** [comment]
It happens to work with DOSBox SVN because SVN's attribute controller emulation sets the "disabled" bit but does not actually blank the screen if you write an index with bit 5 clear. Their emulation is broken in that regard.

On *real* hardware, the screen goes blank when you write the index in port 3C0h with bit 5 clear and stays blank until an index is written with bit 5 set.

**Comment by joncampbell123** [comment]
The screen should be blank by now in SVN here:
![dosboxsvnshouldbeblank](https://user-images.githubusercontent.com/6245486/70404187-1a289700-19ee-11ea-9fca-a751eedc1ffa.png)

**Comment by joncampbell123** [comment]
Confirmed on a Paradise SVGA-based laptop: o 3c0,0 (when accepting index) should immediately blank the screen and o 3c0,20 should unblank it.

**Comment by joncampbell123** [comment]
And yet... the game displays correctly. Hm....
![IMG_20191208_214211160 jpg](https://user-images.githubusercontent.com/6245486/70410476-0a1bb200-1a04-11ea-8993-912ed4d5e5ae.jpg)

**Comment by joncampbell123** [comment]
Uh... why is it calling a BIOS INT 10h function concerning DAC state?

http://www.ctyme.com/intr/rb-0128.htm

**Comment by joncampbell123** [comment]
Ah!

It's not Blue Force writing the AC controller in that manner, it's DOSBox-X function INT10_GetDACPage(), which is writing registers 0x10 and 0x14 without regard for bit 5.

So I can fix this after all.

**Comment by joncampbell123** [comment]
By the way, DOSBox SVN has the same bug in it's copy of INT10_GetDACPage()

**Comment by clst** [comment]
Wow, amazing detective work.

I do remember that there was a note somewhere in the game's box (or another TsAGE engine game) that said that Paradise VGA cards had a bug and needed a firmware update (new ROM chip) from Paradise...
   
So it's more like their engine is weird and it only somehow broke on Paradise VGA cards.  
Game works fine on my Compaq DP-4000 with on-board Cirrus Logic VGA.

**Comment by clst** [comment]
Found it. On page 19 in the Protostar Manual Q&A (Problem & Solution) but it was STB and a different issue:

> P: The screen is divided into numerous small images.
S: Some models of STB VGA Cards have a bug in the BIOS.
If you are using an STB VGA Card  (Powergraph for
example),  then you may request a BIOS upgrade from
STB by calling (214)  234-8750 (9:00AM 5:00PM CST).
The BIOS upgrade that you need is identified as Revision
1.92, and is dated 2-19-93. You must state that this BIOS
upgrade fixes problems with a  TSUNAMI product when
you call STB.
