### ISSUE TITLE
need for speed video problem 

### ISSUE THREAD

**Issue by 280696516** [joncampbell123/dosbox-x#1363]
The Need for Speed Special Edition, 
single player,select a car,select video ,
 can't see video. sound is ok.

dosbox.conf is:
[autoexec]
mount C .
imgmount d ./nfsse.iso -t cdrom
c:
cd nfsse
nfs

![nfs_019](https://user-images.githubusercontent.com/54297406/70423310-338e1980-1aa8-11ea-9228-7252da432686.png)

**Comment by joncampbell123** [comment]
https://archive.org/details/msdos_Need_for_Speed_The_-_Special_Edition_1996

**Comment by joncampbell123** [comment]
Videos do not play properly in DOSBox SVN either.

**Comment by joncampbell123** [comment]
I think Need for Speed here is doing something funky with CRTC registers after setting 640x400 16bpp mode.

**Comment by viniciusferrao** [comment]
Have you run UNIVBE.EXE before launching NFS.EXE?

For me even the graphics menu are broken without UNIVBE.EXE. Ir renders the second quadrant of the image only.

**Comment by joncampbell123** [comment]
UNIVBE.EXE provided with the game has no effect. Same problem.

**Comment by viniciusferrao** [comment]
It's working here:
![image](https://user-images.githubusercontent.com/2031761/71595082-17b2ec00-2b19-11ea-9961-a95ac9e2962c.png)

UNIVBE.EXE in my case wasn't provided by the game. I have the original NFS:SE and it does not came with UNIVBE.EXE so I'm using the RELEASE 5.0:

![image](https://user-images.githubusercontent.com/2031761/71595198-6f515780-2b19-11ea-9cce-bae2157d8927.png)

PS: I'm running DOSBox with svga_et3000. svga_et4000 and up breaks.

**Comment by viniciusferrao** [comment]
http://www.os2museum.com/wp/need-for-speed-se-video-glitch/

**Comment by joncampbell123** [comment]
Really??

All along I assumed it has something to do with playing with registers, assuming video modes, or VESA BIOS data issues.

**Comment by joncampbell123** [comment]
[dosbox]
allow low resolution vesa modes                   = false
allow explicit 24bpp vesa modes                   = false
allow high definition vesa modes                  = false
allow unusual vesa modes                          = false
allow 32bpp vesa modes                            = false
allow 24bpp vesa modes                            = false
allow 16bpp vesa modes                            = false
allow 15bpp vesa modes                            = false
allow 8bpp vesa modes                             = true
allow 4bpp vesa modes                             = false
allow 4bpp packed vesa modes                      = false
allow tty vesa modes                              = false

![needforspeedduh](https://user-images.githubusercontent.com/6245486/71747669-1c331980-2e25-11ea-9b5f-d2329743240a.png)

**Comment by 280696516** [comment]
I modify nfs.exe according to 
http://www.os2museum.com/wp/need-for-speed-se-video-glitch/
now it is well even without univbe.
[NFSnew.zip](https://github.com/joncampbell123/dosbox-x/files/4021540/NFSnew.zip)

**Comment by Allofich** [comment]
With the unmodified nfs.exe, are the videos messed up correctly in DOSBox-X? According to that link, in VirtualBox (back in 2011, anyway) the videos play in 320x200 at 16bpp but with "garbled video".

**Comment by viniciusferrao** [comment]
Messed up correctly? You mean, they are broken? Yes they are.

There's no HiColor videos in the game. It was a programming fault explained on the link. The bug never trigged since in TNFS:SE days people don't have video cards supporting 320x200x16, so the bug never really showed up.

**Comment by Allofich** [comment]
The bug reporter said "can't see video", so I imagined (probably incorrectly) that DOSBox-X showed a black screen, but the article seems to show the video displaying, but with wrong colors. If DOSBox-X and VirtualBox "mess up" differently, I thought that may be worth looking into, to get accurate emulation. Otherwise I guess there may be no issue here.

**Comment by Allofich** [comment]
Well to answer my question I checked DOSBox-X and what I see is wrong-colored video that looks like the screenshot in the linked article, except in DOSBox-X it's also squished up against the top of the screen. I don't know if that difference is meaningful or not, though.

**Comment by Allofich** [comment]
> [dosbox]
allow low resolution vesa modes = false
allow explicit 24bpp vesa modes = false
allow high definition vesa modes = false
allow unusual vesa modes = false
allow 32bpp vesa modes = false
allow 24bpp vesa modes = false
allow 16bpp vesa modes = false
allow 15bpp vesa modes = false
allow 8bpp vesa modes = true
allow 4bpp vesa modes = false
allow 4bpp packed vesa modes = false
allow tty vesa modes = false

The only one of these that seems to be needed to get it showing correctly is `allow low resolution vesa modes = false`

**Comment by viniciusferrao** [comment]
@Allofich I can confirm that only setting `allow low resolution vesa modes = false` solves everything. I don't even need to change the graphics card to svga_et3000 nor use UNIVBE.EXE anymore. It solved another issue that I've had, that was broken image even on the menus.

**Comment by Maxkatsur** [comment]
I played it on DOSBOX-Pure, an RetroArch core which is easier-to-use fork of DOSBox. Any solutions for DOSBox-Pure, or they are pretty much the same?

**Comment by rderooy** [comment]
Either apply the fix from the linked os2museum.com page or talk to the author of dosbox-pure to have an option similar to dosbox-x to disable either low-res or 8bpp vesa modes.

**Comment by Max833** [comment]
Or use DOSBox Staging, it is working there out of the gate.
