### ISSUE TITLE
EGA palette modification not supported?

### ISSUE THREAD

**Issue by fabiensanglard** [joncampbell123/dosbox-x#1364]
**Describe the bug**
EGA palette modification is not supported

**To Reproduce**
1. Set DosBOX to operate as an EGA machine via its config file.
2. Start a game supporting EGA (Out of This World of Duke Nukem 2)
3. See that the graphic result is not correct. The default EGA palette seems to be used instead of the one uploaded by the game.

**Expected behavior**
The game specific palette should have been loaded.

**Screenshots**
<img width="640" alt="Screen Shot 2019-12-13 at 2 11 41 PM" src="https://user-images.githubusercontent.com/1219472/70836633-a43d7a80-1db5-11ea-963b-5f4db85a4b83.png">

**Environment (please complete the following information):**
 - Operating system NA
 - DOSBox-X release version: 0.74-3
 - Used configuration: machine=ega

**Comment by Allofich** [comment]
Can't confirm this.

We need to get some things clear, though. Are you using DOSBox-X or regular DOSBox? Your screenshot says "DOSBox 0.74" and the version you mention, 0.74-3, is a regular DOSBox version. (However, I also tried some regular DOSBox versions I have and I didn't see the palette problem there, either)

Next, maybe there is an issue with game setup or the game itself. What I tested with is the demo of "Out of This World". I extracted the .zip file, ran `INSTALL.BAT` to install the demo and selected EGA during the installation program, then ran the installed demo ( `AWDEMO.EXE` ). It looked correct both with machine = svga_s3 (default setting) and machine = ega.

**Comment by fabiensanglard** [comment]
Indeed, the bug was between the chair and the screen. Thank you for clarifying, I thought the games used to be able to detect EGA/VGA automatically.

**Comment by joncampbell123** [comment]
Duke Nukem 2 as far as I know uses the 16-color mode but assumes a VGA, and it assumes there is a VGA palette to set as well. That doesn't work on EGA, so the colors are wrong.

Some games were written by programmers who either didn't know or didn't care to detect the video card.
