### ISSUE TITLE
re-add the old Drive menu to the dosbox-x GUI?

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#1366]
can you readd the old Drive menu to the dosbox-x GUI?

I found it useful using dosbox on a tablet.
<img width="412" alt="dosboxdrivemenu" src="https://user-images.githubusercontent.com/9592379/71173444-b760b680-229d-11ea-8843-1902f5090465.png">

**Comment by Wengier** [comment]
I have added back the drive menu items (mostly for Windows) in my pull request #1514.
