### ISSUE TITLE
Alt key stays pressed after pause

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#137]
Using alt-pause keyboard combination in dosbox-x will pause the application. Pressing pause key again will unpause. However, the alt key stays pressed after unpause -- so that any keyboard input is combined with the alt key function. Pressing the alt key by itself after unpause will restore the alt key.

Is there a simple fix to clearing the alt key state after unpause?

**Comment by joncampbell123** [comment]
Not yet, for the same reason that bringing up the SDL mapper interface requires you to tap CTRL and SHIFT to regain use of the command line.

Alt+Pause on my end brings up the debugger. I have to go to the terminal window where the debugger exists and hit F5 to resume. Are you referring to Ctrl+Pause, the mode I added where you can pause and single-frame-step emulation? I can confirm that after resuming with Pause the console acts as if CTRL is still down.

**Comment by ghoul8765** [comment]
Thank you for testing it. It must be a SDL issue. :) Would it be better to bind pause (and SDL mapper) to a different key combination, perhaps just the pause key, to avoid retention of the alt/ctrl key state? Otherwise, is it possible to clear the sdl keyboard buffer after exiting these modes?

**Comment by joncampbell123** [comment]
I have another suggestion: I think it has something to do with the fact that both my CTRL+Pause hack and the SDL mapper code call SDL functions to flush keyboard input. However the BIOS data area still thinks those keys are down when emulation resumes.

If the SDL mapper were designed to keep track of which keys are in the "down" state, we could have the SDL mapper and CTRL+Pause functions emit "up" scancodes before flushing SDL keyboard input to keep things coherent.

Another idea I'd like to consider is VirtualBox's "host key" idea. You have one key on the keyboard you never send to the guest (usually right control) and holding down that key while typing another one acts like a keyboard shortcut to emulator functions.

**Comment by ghoul8765** [comment]
That's interesting. I like the first idea, to emit "up" scancodes after the pause and mapper functions; hopefully that works! I also wonder whether the "flushing SDL keyboard input" function is necessary in the code, does it have any effect on use of dosbox-x?

Another point from my recollection which is hopefully correct: the original "pause" detection routine involved a key up event which was changed to a key down event in dosbox-x (there is a commit on this issue). However, the key up detection allowed the user to alt-tab to restore the console input after pausing; while the key down detection required pressing the alt key only. Is it possible that the code was chosen to detect a key up event because it provided multiple ways to restore input, even if it is a workaround?

**Comment by joncampbell123** [comment]
The SDL flush calls were probably added by DOSBox developers to prevent the SDL mapper UI from acting on whatever else you had in the keyboard buffer. It was there when I forked the code, so I can't speak for DOSBox developers or what they were trying to do when it was added. I could try removing those flush calls to see if anything happens.

**Comment by ghoul8765** [comment]
Oh. Perhaps best to leave it (SDL flush calls) since it may fix a problem on another OS, like OSX.

**Comment by ghoul8765** [comment]
This patch seems to fix the above issue:
<pre lang=""><code>--- sdlmain-ORIG.cpp	2015-11-27 06:04:28 -0500
+++ sdlmain.cpp	2016-01-29 21:46:14 -0500
@@ -537,9 +537,6 @@ void PauseDOSBox(bool pressed) {
 	void GFX_UpdateSDLCaptureState();
 	GFX_UpdateSDLCaptureState();
 
-	KEYBOARD_ClrBuffer();
-	GFX_LosingFocus();
-
 	// redraw screen (ex. fullscreen - pause - alt+tab x2 - unpause)
 	if (sdl.draw.callback) (sdl.draw.callback)( GFX_CallBackReset );
 }</code></pre>

**Comment by joncampbell123** [comment]
It doesn't solve the problem on my end. it may release Alt but the DOS prompt still acts like CTRL is down when I exit the mapper.

**Comment by ghoul8765** [comment]
This patch may be appended to the above one. This should hopefully prevent the CTRL down issue on exiting mapper:
<pre lang=""><code>--- sdl_mapper.cpp	2016-01-30 04:18:58 -0500
+++ sdl_mapper-CHANGED.cpp	2016-01-30 04:17:55 -0500
@@ -2474,9 +2474,6 @@ void MAPPER_RunInternal() {
 #endif
 	if(mousetoggle) GFX_CaptureMouse();
 	SDL_ShowCursor(cursor);
-#ifdef __WIN32__
-	UI_Shortcut(0);
-#endif
 	DOSBox_RefreshMenu();
 	if(!menu_gui) {
 		SDL_FreeSurface(mapper.surface);
@@ -2503,11 +2500,7 @@ void MAPPER_RunInternal() {
 	}
 #endif
 #endif
-	KEYBOARD_ClrBuffer();
-	GFX_LosingFocus();
-
-	void GFX_ForceRedrawScreen(void);
-	GFX_ForceRedrawScreen();
+	GFX_ResetScreen();
 }
 
 void MAPPER_Init(void) {</code></pre>

**Comment by joncampbell123** [comment]
Mapper code was revised since this issue to better handle stuck key issues. On entry to the mapper or other UI entry points, it should send key release events for anything held down.

Please confirm this is no longer an issue.

**Comment by joncampbell123** [comment]
This is no longer an issue as far as I can tell.
