### ISSUE TITLE
Remove VS2013 solution

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1372]

**Comment by joncampbell123** [comment]
@yksoft1 I'd like to remove the unmaintained vs2013 directory and solution. Are you still using this?

If you do not respond by Jan 1st I will remove it anyway.

**Comment by yksoft1** [comment]
It's OK for me as my nmake makefiles are referencing to dependencies like SDL in /vs2015.
I personally never used anything in /vs2013 at all.
