### ISSUE TITLE
Parallel1 capture file isn't closed after writing

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1377]
Possibly this is by design, but I hope it can be changed:

If I specify

parallel1 = file file:output.prn

and then do something like DIR>LPT1, the resulting output.prn file is not closed until DOSBox-X exits, which means that I can't do something like print it or convert it to a PDF and then delete it. When I don't specify a filename, then I *can* print, delete, etc., the resulting files in the captures folder, but those files don't distinguish between lpt1, lpt2, and lpt3 output. 

So this brings me back to my earlier request in a closed issue, which is for some way to distinguish output files from the different ports, and create files that can be manipulated while DOSBox-X is still open. The ugly workaround that I offered here:

https://github.com/joncampbell123/dosbox-x/issues/1296#issuecomment-544282953

still works, but it's obviously ugly and something more competent would be helpful.

Again, this is a request for output from LPT1, etc., that would (1) use different filenames for each port and (2) can be opened and deleted while DOSBox-X is running. Thank you!

**Comment by joncampbell123** [comment]
Add a timeout: setting to parallel1.

If you add a timeout:1000, the file will be closed and flushed 1 second after the last data byte is written.

**Comment by emendelson** [comment]
And I should have understood that! Thank you!
