### ISSUE TITLE
"F8" case in PC-98 input processing not reachable

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1378]
I made a comment about this recently but it may have been overlooked:

https://github.com/joncampbell123/dosbox-x/commit/9ba65491b0e52f85bf26eb4f9859267e7344c250

The line at
https://github.com/joncampbell123/dosbox-x/blob/fc78c46ba460fd7afe7b505f6e7c0e752b54b4cb/src/shell/shell_misc.cpp#L208

is never reached due to the above commit. I don't know if or how this bug actually manifests itself when using DOSBox-X, but the code as it is now doesn't seem right.

**Comment by joncampbell123** [comment]
It's a mistake, and nothing below that uses case 0x4200 anyway. I'll remove it.
