### ISSUE TITLE
Request: add menu entry to force "rescan"

### ISSUE THREAD

**Issue by saintfrater** [joncampbell123/dosbox-x#1379]
Sometimes, I've to shell or leave my dos application to type in an "RESCAN" command to allow the VM to know that the file has been updated or added...

It would be lovely to have a command somewhere in the main menu to do an RESCAN for all disks.

many thanks for all the work done so far.

**Comment by joncampbell123** [comment]
That I could do, though today is DOSBox-X build day so it will have to wait next year (in a few days).

**Comment by joncampbell123** [comment]
However there is also MOUNT option -nocachedir you might use to get the same effect.

The option disables caching of the directory entries which should eliminate the need to run RESCAN

**Comment by saintfrater** [comment]
Hello Jon,

many thanks for your answer, I wasn't aware of this option.
Maybe the Wiki should be have mention of that...
