### ISSUE TITLE
ERROR CPU:Illegal Unhandled Interrupt Called 6

### ISSUE THREAD

**Issue by rubin55** [joncampbell123/dosbox-x#1380]
**Describe the bug**
I started Alone in the Dark 3, with a dosbox.conf I previously used succesfully on another computer in combination with DOSBox-X. The screen turns black, stays black, DOSBox-X locks up. I enabled CPU logging and got the following error (scrolled hundreds of times per second):

```
ERROR CPU:Illegal Unhandled Interrupt Called 6
```

I have played this game with DOSBox-X before: Notable things that have changed: 

 * DOSBox-X version (probably 0.82.4);
 * Processor: AMD Ryzen 2700U instead of 1700X
 * Graphics: AMD Vega 10 instead of AMD Vega Frontier Edition

I'm attaching the log and dosbox.conf used.

**To Reproduce**
1. Start dosbox-x with attached dosbox.conf
2. Mount a directory which contains Alone in the Dark 3
3. Start the game with AITD3.EXE
4. See DOSBox-X lock up, see attached log.

**Expected behavior**
I expected the game to start normally.

**Environment (please complete the following information):**
 - Operating system: Windows 10 release 1909
 - DOSBox-X release version: 0.82.24

**Additional context**
See the following dosbox.conf:
[dosbox-aloneinthedark3.conf.txt](https://github.com/joncampbell123/dosbox-x/files/4013926/dosbox-aloneinthedark3.conf.txt)

See the following dosbox.log:
[dosbox.log](https://github.com/joncampbell123/dosbox-x/files/4013927/dosbox.log)

**Comment by rubin55** [comment]
I just re-downloaded the latest 0.82.4 pre-release version from the releases page (here: https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-20180316-2157) and verified that indeed, Alone in the Dark 3 starts normally with that version. A regression of sorts?

**Comment by rubin55** [comment]
i just donwloaded a whole bunch of previous releases, testing each one with the same config file and setting both core=normal and core=dynamic. 

`0.82.20` is the last version where Alone in the Dark 3 works with both normal and dynamic core.

**Comment by joncampbell123** [comment]
Try LOADFIX before running the game.

**Comment by rubin55** [comment]
Argh.. that works (tried on just-released 0.82.25); Why is it that loadfix works in so many different cases (and why oh why do I always forget to try it first)..

**Comment by joncampbell123** [comment]
There's a surprising amount of code out there that has issues when loaded below the 64KB boundary, especially if the A20 gate is enabled.
