### ISSUE TITLE
Configuration UI: can't show all menu items

### ISSUE THREAD

**Issue by roytam1** [joncampbell123/dosbox-x#1384]
**Describe the bug**
can't show all menu items in Configuration UI.

**To Reproduce**
1. Go to 'Main'
2. Click on 'Configuration UI'
3. Scroll down to 'Settings'

**Expected behavior**
A scrollable or split menu for showing all items. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1192577/71757716-d9c81600-2ed2-11ea-81cd-02239e588a9b.png)

**Environment (please complete the following information):**
 - Operating system: Win7 x64 with Classic Theme
 - DOSBox-X release version or commit SHA1 this issue occurred on: 0.82.25 2020-01-01 10:44 mingw-win32 SDL1
 - Used configuration, e.g. ```dosbox.conf``` : default config

**Additional context**

**Comment by joncampbell123** [comment]
The GUI toolkit involved will have to be modified to support split/scrolling menus first, then it will be possible.
It's only worse if somehow all buttons are not visible on the dialog.

**Comment by joncampbell123** [comment]
Done.
