### ISSUE TITLE
0.82.25: usage of --disable-fpu make final linking fail with " undefined reference to `fpu`"

### ISSUE THREAD

**Issue by kas1e** [joncampbell123/dosbox-x#1388]
Tried to build latest dosbox-x on AmigaOS4 (so PPC Big-Endian CPU), and firstly want to disable everything, to have more or less clean build for tests:

```./configure --build=x86_64 --host=ppc-amigaos --target=ppc-amigaos --disable-opengl --disable-core-inline --disable-debug --enable-sdl2 --disable-x11 --disable-dynamic-core --disable-dynrec --disable-fpu --disable-fpu-x86 --disable-fpu-x64 --disable-unaligned-memory```

So far all compiles well, but then on linking I have:

```C
cpu/libcpu.a(mmx.o): In function `FPU_SET_TOP':
/amiga/dosbox_x/src/cpu/../../include/fpu.h:216: undefined reference to `fpu'
/amiga/dosbox_x/src/cpu/../../include/fpu.h:216: undefined reference to `fpu'
collect2: error: ld returned 1 exit status
```

**Comment by joncampbell123** [comment]
That's a good point actually: Since the Pentium MMX registers are just the FPU registers re-used for SIMD operations, --disable-fpu should also disable MMX emulation (and Pentium Pro emulation).

**Comment by kas1e** [comment]
yep... I tried also to build with enabled FPU, but with just disabled ```-disable-fpu-x86 --disable-fpu-x64 ```,  but it brings me some errors about all "long" functions such as ```floorl(), ceill(), sinl(), cosl(), sqrtl(), atan2l(), tanl(), powl(), logl(), fabsl()``` being undeclared in my C lib from SDK, so i for fun replace all "l" on "f" and while C file parses fine, when it should compiles to object it bring me assmbler errors like:

```C
/tmp/cca8PzOm.s: Assembler messages:
/tmp/cca8PzOm.s:29: Error: unrecognized opcode: `fldcw'
/tmp/cca8PzOm.s:399: Error: unrecognized opcode: `fldcw'
/tmp/cca8PzOm.s:1329: Error: unrecognized opcode: `fldcw'
/tmp/cca8PzOm.s:1390: Error: unrecognized opcode: `fldcw'
```

Not sure if it because of my "l" on "f" replacement, or something else... But probably firstly I need to implement all "l" function to be sure that is it or not are a problem. And that probably for another ticket anyway (if you, of course, doesn't mind to continue there).

Thanks for reply!

**Comment by joncampbell123** [comment]
Is "long double" the same as "double" on your platform?

**Comment by kas1e** [comment]
At least pure:

```C
#include <stdio.h>
int main()
{
    printf("long double = %d\n", sizeof(long double));
    printf("double = %d\n", sizeof(double));
}
```
show me `8` for both

**Comment by joncampbell123** [comment]
Edit include/dosbox.h, line 79, and comment out the line that reads:

# define HAS_LONG_DOUBLE        1

**Comment by joncampbell123** [comment]
Long term that code should probably assume long double is defined only if GCC and x86 or x86_64 instead of not MSVC and not ARM.

**Comment by kas1e** [comment]
yeah, with that and with swapping "l" functions on "f" ones all compiles and links now :)  Thanks!

Check the screenshot (it's just pure default binary running, without anything else in a directory):

http://kas1e.mikendezign.com/aos4/dosboxx/dosboxx_first_run.jpg

Now sure through why it all blinks and shows those green dots. Probably some endian/swapping issues can be? Or that unrelated there?

**Comment by joncampbell123** [comment]
The VGA code assumes little Endian byte order. Video memory is typecast as uint32_t and assumed by the code to carry (bit 7-0 plane 0) (bit 15-8 plane 1) and so on.

VGA text mode stores character data in VGA plane 0 and attribute data in VGA plane 1. It's presented to the CPU as if interleaved for backwards compatibility with stuff written for CGA/MDA, so in text mode a write to a memory address is actually written to (address & ~1) and VGA plane (address & 1).

Fixing the VGA code to work on Big Endian is a matter of adjusting the code to typecast as uint32_t and treating the upper 8 bits as plane 0 instead.

**Comment by joncampbell123** [comment]
All VGA emulation is written around the concept of treating video memory as an array of uint32_t and each uint32_t contains the 4 8-bit VGA planar bytes combined. This was also inherited from DOSBox SVN as well because it makes emulating the planar ROPs easier and more efficient.

**Comment by kas1e** [comment]
We have back in past some older version port of original DOSBox (it was 0.74 if I remember right) , which if I remember right have VGA working so probably I can check if there were any big-endian ifdefs so to "copy+paste" them :) Need to recheck

**Comment by joncampbell123** [comment]
It might work. DOSBox-X has modified the VGA emulation somewhat to more strictly follow the VGA planar model described for all modes to better match actual hardware, where DOSBox SVN typecast video memory differently for certain modes like text and CGA.

**Comment by kas1e** [comment]
Checked, yep, old dosbox show it ok.

Btw, what i also noticed, that when first "intro" screen appears, it looks also a bit strange/wrong:

http://kas1e.mikendezign.com/aos4/dosboxx/dosboxx_intro.jpg

This time not messy as when we in console, but also something wrong seems so (?)

> Fixing the VGA code to work on Big Endian is a matter of adjusting the code to typecast as uint32_t and treating the upper 8 bits as plane 0 instead.

Is it easy or require some good coding skills and understanding of code ?:)

**Comment by kas1e** [comment]
Found that year and a half back, someone tried to build an amigaos4 version too, and it was  0.82.10 version, but as I see he didn't have those issues in that version (at least for VGA). He did have issues for EGA, CGA, but VGA seems was ok (though maybe he fixes something with your help?)

I will try to build 0.82.10 version to see if that issue is here, if not, then I can step by step found commit which starts causing this, maybe then it will be easy to add necessary big-endian ifdefs (if you doesn't mind, of course).

**Comment by AmigaBlitter** [comment]
Still here,
kas1e. The version has been build. I already have a working version of
DosBox X, thanksto Jon Campbell.

I continue to follow the interesting DosBox X port and i will continue the
port as soon as possible.


Kind regards
Davide


Il giorno sab 18 gen 2020 alle ore 10:51 kas1e <notifications@github.com>
ha scritto:

**Comment by joncampbell123** [comment]
Fixed. --disable-fpu should also disable Pentium MMX emulation and avoid the compile failure.
