### ISSUE TITLE
Error in Dosbox-x when I try to install a game (Master of Orion 2)

### ISSUE THREAD

**Issue by kstodola** [joncampbell123/dosbox-x#1389]
I'm trying to run Dosbox-s on Linux Mint. I've been using Dosbox on Windows for some time - no problems. Now trying to use it on Linux. I can't mount a CD as my D drive as the CDs apparently show up in the media file tree using the CD label - and the CD label contains a space (MOO2 V1.0) and Dosbox can't handle this. So I've created an ISO file and have that 'imgmount' ed as my D drive (using -t iso).

Now this game needs to be "installed" to set up all the files. But if I try to execute the setup
   D:\> setup
or
   D:\> SETUP
or
   D:\> SETUP.EXE
I get:
   D:\win SETUP.EXE
   Illegal command: win

This 'imgmount'ed D drive shows the SETUP.EXE file. I've tried everything I can think of to figure out why the "win" seems to be getting prepended to my intended command, but am getting nowhere.

This may not be a dosbox-x specific issue, as I get the same with dosbox and dosemu. But I'm hoping you may have some idea of what might be causing this.

I'm running Linux Mint Cinnamon 19.3

Also - is there any way to get the "mount" command to accept a CD label that includes a space? I've tried bracketing in single quotes and double quotes with no luck. So I'm assuming I can't make this work.

Thanks,
Kevin

**Comment by joncampbell123** [comment]
Is SETUP.EXE attempting to run itself in Windows?

Perhaps SETUP.EXE has an MS-DOS stub that attempts to invoke the COMMAND shell to start Windows and run itself.

**Comment by joncampbell123** [comment]
If you look at the first 1024 bytes of SETUP.EXE in a hex editor do you see the typical "This program requires Microsoft Windows" stub or something different?

Another hint is to read a little endian 32-bit value from byte offset 0x1C, jump to that offset, and see if the letters "PE" (Win32) or "NE" (Win16) appear at that location.

**Comment by kstodola** [comment]
There is no such text in the first 2014 bytes of SETUP.EXE. I don't see anything recognizable in the first 1024 bytes. 

And the content at 0x1c is 01 00 24 01. But the SETUP.EXE file is only 0xAF80 bytes lone, so I can't see any way to offset to that value at 0x1c.

BTW, since I was getting nowhere trying to get this to work in dosbox-s, I decided to try Wine - and it installed fine via wine. So I probably don't need to pursue this issue in doxbox-x any more. But thanks for the response

**Comment by joncampbell123** [comment]
So SETUP.EXE is probably just a pure MS-DOS program that attempts to run itself in Windows, for some reason. I'm sorry DOSBox-X could not resolve the issue, but I'm glad WINE was able to help.

At some point, try creating a DOSBox-X setup where you install Windows 3.1, then ensure WIN.COM is in the PATH variable, and see if that helps SETUP.EXE run.
