### ISSUE TITLE
Scalers seems to not be working on opengl

### ISSUE THREAD

**Issue by Askmewho** [joncampbell123/dosbox-x#1391]
So, Ive compile master on arm linux and the only shader (scaler) than works its the software one.
btw, Ive tried both, sdl1 and sdl2 compilations, shaders works on normal dosbox

Also, I would love to have Xbrz multithreaded like its on snes9x (it changes everything)

could you check if thats could be taken from their source code??

**Comment by joncampbell123** [comment]
Shader support as inherited from Daum is DirectX only.

**Comment by Askmewho** [comment]
Ok, closing, consider to add the multithread ed xbrz please. Thanks

**Comment by Askmewho** [comment]
@joncampbell123 just check my testing on rpi4. We need that multithreaded xbrz :) haha https://youtu.be/7t28jDH2a1w

**Comment by Askmewho** [comment]
@joncampbell123  Ive solved my new sound issue on rk3399, it was kernel related,now runs amazing. Thanks!
