### ISSUE TITLE
bug debugger in linux

### ISSUE THREAD

**Issue by supinrus** [joncampbell123/dosbox-x#1394]
Versions of DosBOX-X from 0.82.23 to 0.82.25 have debugger bug in Linux.
After breakpoint make on cs:eip line not working key F5(continue).

**Comment by joncampbell123** [comment]
That was fixed soon after the monthly release.

The issue also reflects itself in the inability to step over interrupts if you breakpoint on interrupt.

https://github.com/joncampbell123/dosbox-x/commits/master
