### ISSUE TITLE
How to use mt32 rom files? / Relative ROM paths do not work

### ISSUE THREAD

**Issue by legionpheonix** [joncampbell123/dosbox-x#1395]
Maybe I did something wrong for the latest version of DosBox-X?
Everything works in DosBox ECE.

mpu401              = intelligent
mpubase             = 0
mididevice          = mt32
midiconfig          = 
samplerate          = 48000
mpuirq              = -1
mt32.romdir         = "..\DosBox-X\DosBox-X\MT-32"
mt32.reverse.stereo = true
mt32.verbose        = true
mt32.thread         = true
mt32.dac            = auto
mt32.reverb.mode    = auto
mt32.reverb.time    = 5
mt32.reverb.level   = 3
mt32.partials       = 32

**Comment by joncampbell123** [comment]
Run with --debug and look at the log file. It should indicate whether or not it found the ROM files.
My testing is typically done with them in the current working directory.

**Comment by legionpheonix** [comment]
> Запустите с --debug и посмотрите файл журнала. Должно указываться, были ли найдены файлы ROM.
> Мое тестирование обычно проводится с ними в текущем рабочем каталоге.
Honestly, I did not understand how to run in debug mode

@echo off
start "" DOSBox-x.exe ^
-debug ^

**Comment by legionpheonix** [comment]
> > Run with --debug and look at the log file. It should indicate whether or not it found the ROM files.
> > My testing is typically done with them in the current working directory.
> 
> Honestly, I did not understand how to run in debug mode
> 
> @echo off
> start "" DOSBox-x.exe ^
> -debug ^

Write exactly how you run and can send your .conf file?

**Comment by legionpheonix** [comment]
> Run with --debug and look at the log file. It should indicate whether or not it found the ROM files.
> My testing is typically done with them in the current working directory.

I understood how MT32 works. If you put dosbox-x.exe and rom files in the game folder, then everything works.
But then the question is the following. Can I somehow divide? I separately made the dosbox folder and in it I store the program itself and settings.
The option does not work in the conf file, if you register the following:
mt32.romdir = ".. \ DosBox-X \ DosBox-X \ MT-32"

**Comment by joncampbell123** [comment]
Are you using the right path separator?

Backslash on Windows and MS-DOS.
Forward slash everywhere else including Linux and Mac OS X.

**Comment by joncampbell123** [comment]
If you are, then perhaps there is a problem with relative paths.

**Comment by legionpheonix** [comment]
> If you are, then perhaps there is a problem with relative paths.

Yes, obviously there is such a problem.
But in DosBox ECE, it is similarly configured for me and everything works as expected.
Even if I prescribe the full path
D: \ Games \ Emulators \ DosBox-X \ DosBox-X \ MT-32
Anyway, through the console, if you type “mixer”, there is no “MT32” in the list.
But when everything is in one folder, then MT32 is visible.
You can somehow fix this so that there is no mess, but clearly sorted folders with the game and the program.

**Comment by legionpheonix** [comment]
> If you are, then perhaps there is a problem with relative paths.

Do you have any suggestions?

**Comment by legionpheonix** [comment]
Have you decided to ignore me now?

**Comment by joncampbell123** [comment]
Hello, sorry about that.

I'll see if relative paths work here on my end, and fix it if not so.

**Comment by joncampbell123** [comment]
Digging through the DOSBox-X source code... the answer is that DOSBox-X does not implement the mt32.romdir setting.

**Comment by legionpheonix** [comment]
> Digging through the DOSBox-X source code... the answer is that DOSBox-X does not implement the mt32.romdir setting.

Can you add this feature?

**Comment by joncampbell123** [comment]
Try it now, latest commit.

**Comment by legionpheonix** [comment]
> Try it now, latest commit.

Sorry, I don’t know how to compile the source code. But I will definitely check when you have time to give the .exe file.

**Comment by joncampbell123** [comment]
It should work as expected, the specific code was borrowed and hardly modified as-is from DOSBox ECE to implement it.

You'll have an EXE to test in the Release section in a few days as it is nearing the end of the month and DOSBox-X binary releases are monthly.
