### ISSUE TITLE
0.82.26 SDL2 built in macOS Catalina - tiny text / Clipboard paste is not working

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1396]
In the macOS download of the latest version, the SDL version acts normally but the SDL2 version looks very strange:

<img width="721" alt="Screen Shot 2020-01-31 at 9 41 55 PM" src="https://user-images.githubusercontent.com/5208505/73585802-d93f8280-4472-11ea-9de1-bdf14fc68eca.png">

This happens with the downloaded build, and also when I build source code in Catalina. I haven't tried it under other macOS versions yet.

**Comment by joncampbell123** [comment]
Ah, Mac OS X is screwing with the OpenGL surface scale again.

Anything I did to correct for it in Mojave and below breaks in Catalina.

**Comment by emendelson** [comment]
Well, a thousand thanks for anything you can do to fix it, and I hope you aren't regretting that you took on this project!

**Comment by joncampbell123** [comment]
The OS X version is made of enough hacks without OS X getting High DPI vs normal DPI crossed up, especially where OpenGL is concerned.

**Comment by joncampbell123** [comment]
@emendelson I'm sort of on a break right now from working on DOSBox-X to pursue a few other hobby projects. Would you like to assist as a collaborator?

**Comment by emendelson** [comment]
@joncampbell123 - I'm certainly willing, but I don't know anything about programming. All I know is how to take a few lines of someone else's code and then try changing it until something works or almost works (usually on the tenth try), and then I ask for help on stackoverflow and usually get it. I do a lot of spaghetti-code scripting (AppleScript, AutoIt) but no real programming. If you want something codesigned (or notarized in macOS), I have Windows and Apple signing certificates, but you may not want things signed under someone else's name. This is entirely up to you - I'm happy to do what I can.

**Comment by joncampbell123** [comment]
@emendelson You may be happier then hacking on your own fork of DOSBox-X.

**Comment by emendelson** [comment]
@joncampbell123 - If I knew more I would gladly do more. But while we're here, I should mention that the only hack I did (with the help of a DOSBox dev) that might conceivably be of interest is one that adds an option to use a font with the euro symbol at ASCII 128 instead of C-cedilla. It's completely awkward (someone who knows how to program could do it in six lines) but it seems to work. I've also tried to get the clipboard-paste feature working again, with no luck. All my other hacks are related to the 35-, 43-, 50- and 60-line text modes that I added for use with WordPerfect, etc.

**Comment by joncampbell123** [comment]
@emendelson This is the clipboard in Windows, correct? If you know the scan codes needed to type it in, you can write a routine to convert a string to scancodes and then send them into the keyboard buffer. Since the keyboard buffer is small, you might use a PIC event to inject them at perhaps 15 chars/sec. You'll need to inject scancodes for the shift keys if switching between capital and lowercase letters.

**Comment by joncampbell123** [comment]
@emendelson Do you intend clipboard paste to work from a mapper event?

**Comment by emendelson** [comment]
@joncampbell123 There's already a PasteClipboard routine in the DOSBox-X code in sdlmain.cpp, around line 5400 and 5600+. I lifted it from an early version of dbDOS, and you added to DOSBox-X a long time ago. It worked until a few months ago, and then stopped working for reasons that I can't figure out. I mapped it to a mapper event  (Ctrl-Alt-F4) in my code, but I've remmed that out since it stopped working. - I also changed it from CF_TEXT to OEM_TEXT with each release.

There's an issue about this here: https://github.com/joncampbell123/dosbox-x/issues/897

As it says there, something broke PasteClipboard between September 29, 2017 (my build from that date pasted from the clipboard) and November 4, 2017 (my build from that date didn't paste from the clipboard).

**Comment by emendelson** [comment]
@joncampbell123 - Also, PasteClipboard is already available in the mapper interface. It worked until late 2017, but I can't make it work in current code.
![Capture](https://user-images.githubusercontent.com/5208505/73666910-84b62600-4671-11ea-9f8b-5973590b7f25.PNG)

**Comment by dixius99** [comment]
FYI, for me at least, moving the window around a little usually fixes the small text problem.

**Comment by emendelson** [comment]
A correction about clipboard paste - it works perfectly in the SDL1 version. I was testing with the SDL2 version, where it doesn't work at all.

Is it possible to do either (1) make clipboard paste work under SDL2 or (2) remove it from the mapper interface under SDL2?

**Comment by joncampbell123** [comment]
It is. Wrap the MAPPER_AddHandler() call responsible for making the clipboard shortcut in #if !defined(C_SDL2) ... #endif

**Comment by emendelson** [comment]
Will do. Thank you.
