### ISSUE TITLE
v0.82.26 tagged wrongly in git (dosbox-x-v0.82.86)

### ISSUE THREAD

**Issue by PedroHLC** [joncampbell123/dosbox-x#1397]
It was brought to my attention that the latest version was tagged wrongly (with an 86 where should be 26) and with that, the source code archive link in GitHub releases pages got messed up.
It's not a giant problem, but it requires manual intervention for everyone who packages DOSBox-X for their distros/repos and then to revert it when a new release is on...

**Comment by joncampbell123** [comment]
Fortunately Github let me correct the issue after pushing a new (correct tag).

It's probably time to start counting from v0.83.0 to avoid the inevitable clash 60 versions later.
