### ISSUE TITLE
The game "The Even More Incredible Machine" doesn't start

### ISSUE THREAD

**Issue by lwchkg** [joncampbell123/dosbox-x#1398]
**Describe the bug**
The captioned game, The Even More Incredible Machine, doesn't start in DosBox-X. It starts normally in vanilla DosBox and Enhanced Community Build.

**To Reproduce**
1. Start the game

**Expected behavior**
The game runs.

**Actual behavior**
The emulation is frozen. No output after finishing the command prompt.

**Environment (please complete the following information):**
 - Win10 [Version 10.0.17763.973]
 - DOSBox-X 20200131-windows, x64, SDL1.
 - Used configuration: plain DosBox start without any config file.

**Comment by lwchkg** [comment]
Anyway, I'm referred to the DOS version of the game. (Don't try the one with Windows 3.1, it works perfectly.)

**Comment by joncampbell123** [comment]
Try running "LOADFIX" before starting the game.

**Comment by joncampbell123** [comment]
Using a copy from the Internet Archive, it seems to work fine.

https://archive.org/details/msdos_Even_More_Incredible_Machine_The_1993

**Comment by lwchkg** [comment]
> Try running "LOADFIX" before starting the game.

Yes it works. (Forgot to reply, sorry.)

I'm still checking the version from the Internet Archive anyway.

**Comment by lwchkg** [comment]
Just checked the Internet Archive. Er... another DOS version with a CD-ROM? Oh that must be a newer version re-released for DOS. The dates read 1994 instead of 1993 :-(

So I must be referring to an older version before. Anyway, since LOADFIX worked (implying the responsibility goes to the game itself) and the mysteries about a different version solved, the bug can be closed now. Thanks for help!
