### ISSUE TITLE
Voodoo LFB writes have frequent, incorrect memory mask

### ISSUE THREAD

**Issue by ghoul8765** [joncampbell123/dosbox-x#140]
Voodoo LFB writes in pipeline mode have a bug.

Logged via voodoo_emu.cpp:
LOG_MSG("VOODOO.LFB:write pipelined mode %X (%d,%d) = %08X & %08X\n", LFBMODE_WRITE_FORMAT(v->reg[lfbMode].u), x, y, data, mem_mask);

EXAMPLE OF BUG VIA DEBUG OUTPUT (x,y,data,mem_mask)
VOODOO.LFB:write pipelined mode 0 (318,13) = F81F3800 & 0000FFFF
VOODOO.LFB:write pipelined mode 0 (318,13) = F81F0000 & FFFF0000
VOODOO.LFB:write pipelined mode 0 (320,13) = F81FF81F & 0000FFFF
VOODOO.LFB:write pipelined mode 0 (320,13) = F81F0000 & FFFF0000
VOODOO.LFB:write pipelined mode 0 (322,13) = F81FF81F & 0000FFFF
VOODOO.LFB:write pipelined mode 0 (322,13) = 38000000 & FFFF0000
VOODOO.LFB:write pipelined mode 0 (324,13) = 38003800 & 0000FFFF
VOODOO.LFB:write pipelined mode 0 (324,13) = 38000000 & FFFF0000
VOODOO.LFB:write pipelined mode 0 (326,13) = F81F3800 & 0000FFFF

THE OUTPUT SHOULD INSTEAD LOOK SIMILAR TO THIS:
VOODOO.LFB:write pipelined mode 0 (318,11) = 3800FFE0 & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (320,11) = F81FF81F & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (322,11) = 3800F81F & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (324,11) = 3800FFE0 & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (326,11) = 3800FFE0 & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (328,11) = FFE03800 & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (330,11) = 38003800 & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (332,11) = 3800FFE0 & FFFFFFFF
VOODOO.LFB:write pipelined mode 0 (334,11) = F81FF81F & FFFFFFFF

TRACED ISSUE TO NEARBY THESE FUNCTIONS:<pre lang=""><code>void voodoo_w(UINT32 offset, UINT32 data, UINT32 mask) {
	if ((offset & (0xc00000/4)) == 0)
		register_w(offset, data);
	else if ((offset & (0x800000/4)) == 0)
		lfb_w(offset, data, mask);
	else
		texture_w(offset, data);
}
void Voodoo_PageHandler::writed(PhysPt addr,Bitu val) {
	addr = PAGING_GetPhysicalAddress(addr);
	if (!(addr&3)) {
		voodoo_w((addr>>2)&0x3FFFFF,val,0xffffffff);
	} else {
		if (!(addr&1)) {
			voodoo_w((addr>>2)&0x3FFFFF,val<<16,0xffff0000);
			voodoo_w(((addr>>2)+1)&0x3FFFFF,val,0x0000ffff);
		} else {
			Bit32u val1 = voodoo_r((addr>>2)&0x3FFFFF);
			Bit32u val2 = voodoo_r(((addr>>2)+1)&0x3FFFFF);
			if ((addr&3)==1) {
				val1 = (val1&0xffffff) | ((val&0xff)<<24);
				val2 = (val2&0xff000000) | (val>>8);
			} else if ((addr&3)==3) {
				val1 = (val1&0xff) | ((val&0xffffff)<<8);
				val2 = (val2&0xffffff00) | (val>>24);
			} else E_Exit("???");
			voodoo_w((addr>>2)&0x3FFFFF,val1,0xffffffff);
			voodoo_w(((addr>>2)+1)&0x3FFFFF,val2,0xffffffff);
		}
	}
}
USE_FULL_TLB (vga_memory.cpp has a similar working scheme)
static INLINE PhysPt PAGING_GetPhysicalAddress(PhysPt linAddr) {
	return (paging.tlb.phys_page[linAddr>>12]<<12)|(linAddr&0xfff);
}
</code></pre>

**Comment by ghoul8765** [comment]
This workarounds the above bug for the purpose of finding the cause:
<pre lang=""><code>void Voodoo_PageHandler::writed(PhysPt addr,Bitu val) {
	addr = PAGING_GetPhysicalAddress(addr);
	if (1) {
		voodoo_w((addr>>2)&0x3FFFFF,val,0xffffffff);</code></pre>

**Comment by ghoul8765** [comment]
Please ignore the changes in the above posts, this patch below fixes the Voodoo LFB writes bug and now direct3d games fully work with the emulation in software and hardware modes:<pre lang=""><code>--- voodoo_interface-ORIG.cpp	2014-01-16 01:16:54 -0500
+++ voodoo_interface.cpp	2016-01-22 22:53:06 -0500
@@ -89,7 +89,7 @@ void Voodoo_PageHandler::writed(PhysPt a
 	} else {
 		if (!(addr&1)) {
 			voodoo_w((addr>>2)&0x3FFFFF,val<<16,0xffff0000);
-			voodoo_w(((addr>>2)+1)&0x3FFFFF,val,0x0000ffff);
+			voodoo_w(((addr>>2)+1)&0x3FFFFF,val>>16,0x0000ffff);
 		} else {
 			Bit32u val1 = voodoo_r((addr>>2)&0x3FFFFF);
 			Bit32u val2 = voodoo_r(((addr>>2)+1)&0x3FFFFF);</code></pre>

**Comment by joncampbell123** [comment]
Done. Also, fixed the problem with the 3Dfx card missing from PCI enumeration.

**Comment by ghoul8765** [comment]
Thanks. :)

**Comment by joncampbell123** [comment]
Should I close this issue?

**Comment by ghoul8765** [comment]
Please do.
