### ISSUE TITLE
Win32 build can not run on XP

### ISSUE THREAD

**Issue by nemo838** [joncampbell123/dosbox-x#1408]
I guess it compiled with higher .net framework version is the problem
lastest xp support version is 4.0
I guess it compiled with higher version option. (VS2017/2019 default)
I really want to run your dosbox on windows XP. would you check it?

and one more problem: unstable when  boot to windows 95 since 0.82.17.
i want to know what update makes it unstable since 0.82.17
install/boot tested build: 0.82.16(good) // 0.82.17, 0.82.18, 0.82.25, 0.82.26 (not good)

**Comment by joncampbell123** [comment]
Binaries compiled with VS2017/VS2019 require Windows Vista at minimum.

However binaries compiled with MinGW will continue to support Windows XP. Use the MinGW binaries for Windows XP.
