### ISSUE TITLE
Windows 98 doesn't run in Normal mode

### ISSUE THREAD

**Issue by ognjenmi** [joncampbell123/dosbox-x#1409]
Hi,

I am trying to install Windows 98. 
I did following steps.
1. I created HDD image with DOS 6.22 installed there.
2. Mounted HDD image as drive C
3. Mounted local directory with Windows 98 as drive D
4. Started setup from D by running setup /is
5. I get error from that there is problem with C drive as shown on picture Windows98Setup.png
6. I run ScanDisk which reports FAT backup copy error and fixes it. You can see it in ScanDisk.png
7. I go to setup again, and then I get new error that setup was out of memory as shown in Windows98Setup2.png
8. Windows setup continues to run normally up to reboot
9. After reboot I boot Win98 from drive c (boot -l c) and setup contues and all seems it finishes normally
10. Then after rebooting from drive C after short time of loading of Windows 98 I get blank screen.
11. I try to restart DOSBox-X from menu but it gets stuck.
12. On reboot I get opton to run in Safe mode which works as expected.
13. Rebooting again Normal mode doesn't work as  described.

I can provide you with hard drive image file but its to big to upload here (around 200 MB when compressed).

I am running DOSBox-X version 0.82.25, x64 with SDL2.
[Problem.zip](https://github.com/joncampbell123/dosbox-x/files/4209232/Problem.zip)

**Comment by joncampbell123** [comment]
You will need to boot MS-DOS from the hard disk image to install from within the guest environment, and make sure to run with the normal core.

**Comment by ognjenmi** [comment]
That worked. Thanks!
