### ISSUE TITLE
Lack of DOS CHMOD (set attributes) support makes Comix zone setup install no files

### ISSUE THREAD

**Issue by ognjenmi** [joncampbell123/dosbox-x#1411]
**Describe the bug**
I am trying to install Comix Zone game within Windows 3.11 running on DOSBox-x 0.8.25 x64, SDL2, Windows 10 host OS. 

After installation is "successfully" finished there is no files in destination folder and the folder is empty. 

On log file you can see that files were open for writing and I debugged INT21 handler a bit. I saw that file is created, written and immediately deleted, all using regular DOS INT 21 calls. This is drives me to a conclusion that there is some condition met that prevents files to be installed.
This is actuality old windows installer (mssetup). 

I tried to use VS 2019 debugger and DOSBox debugger in parallel but this appeared as difficult as they are not in sync (kind of expected as DOSBox had to run its cycles). 

Any hints? Is there a way to debug this in a nicer way? Maybe there is some known mssetup problem. 

**To Reproduce**
1. Install Windows 3.11 I in DOSBox and run it 
2. Install Comix Zone
3. Installation folder will be empty

**Expected behavior**
Folder should contain installation files.

**Environment (please complete the following information):**
 - Operating system Windows 10
 - DOSBox-X release version or commit 0.82.25 SHA1

**Comment by sikthehedgehog** [comment]
I thought this game required 32-bit Windows, not 16-bit? (note that it was extremely common to have 16-bit installers for 32-bit programs)

**Comment by ognjenmi** [comment]
Yes, the game itself is 32-bit (exe has PE and not NE format) and it installs Win32s extension and it should work with Windows 3.11. The problem here is that setup program actually has problems. 
I confirmed this by looking into setup scripts.

**Comment by ognjenmi** [comment]
I have been disassembling and debugging the setup. I found out the reason!
There is mix of missing DOSBox feature and the setup bug.

There are msinsstf.dll and mscomstf.dll which are running script Comix.mst.
Setup executes line CopyFilesInCopyList and takes files one by one. Source files are compressed in old Win style (with last letter as underscore e.g. EX_). It decompresses the each properly and file shows up in destination directory. So far so good.

Then it tries to setup read-only access to a file. Afterwards it checks if file exists and it is read-only. If it is not read-only it deletes the file.

Here is the problem DOSBox can't set file attributes which generates the warning in console.

Setup is buggy and ignores the error reporting that installation has been successfull even though FCOPYFILE function returns erroneous result (=1).

There is workaround to open COMIX.INF and instead of "STF_READONLY"   = "YES" put "STF_READONLY"   = "".

Although workaround really works it would be good to have some basic set attributes support.

**Comment by joncampbell123** [comment]
It's tougher to do the other attribute bits but the R readonly attribute could be done easily enough on Linux, Mac OS X, and Windows.

Windows: Map it to the readonly attribute given by Windows.
Linux and Mac OS X: Map it to the inverse of the "W" (writeable) bit in the user-section of the st_mode bitfield.

**Comment by ognjenmi** [comment]
Are you proposing me to do it or you are just commenting :)
I might do it for windows, but for Linux/Mac I don't have test environment to try it out.

**Comment by joncampbell123** [comment]
I'm just commenting.

**Comment by ognjenmi** [comment]
I was looking into fatDrive::GetFileAttr code as I was interested in implementing SetFileAttr and I noticed that code is bit suboptimal there if you look for directory attributes. Seems like this function should be rewritten to always have one pass trough directory tree. Doing this there could be a function that returs raw sector (pointer to it), its number and directory entry offset of particular file. This could be later used for both get/set attributes. What do you think?

**Comment by Wengier** [comment]
I have already implemented the SetFileAttr function (along with the built-in ATTRIB command) on local (Windows only) and FAT drives (all systems) for DOSBox-X. More information is available in Issue #1469.

**Comment by joncampbell123** [comment]
@Wengier's patch has been applied, which should allow Comix to work.
If the drive is a local drive, it should use the full file attributes on Windows and support at least the R (readonly) bit on Linux and Mac OS X.
