### ISSUE TITLE
"dosbox-x -startui" returns error

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#1413]
I am testing the various command-line options for DOSBox-X, and found that if I start it with "dosbox-x -startui" on non-SDL2 builds, and then click the "Close" button in the bottom of the popup menu, the following error message will appear:

E_Exit

DOSBoxMenu::get_item() No such item 'overscan_0'

OK

The program will exit when I click the OK button. The error will occur even if I change some settings before clicking on the "Close" button. This error message does not appear on the SDL2 build.

Tested under Windows 10, DOSBox-X v0.82.26 and v0.82.25 (SDL1 builds).

Also, I noticed that "dosbox-x -printconf" does not work properly on Windows. Nothing will show on the screen if you run this command, and the file "C:\Users\<UserName>\AppData\Local\dosbox\dosbox-0.82.26.conf" it (silently) generated just contains the string "CONFIGFILE_INTRO", and nothing else, instead of a conf file with various options and comments.

**Comment by joncampbell123** [comment]
Confirmed.

Moving the startui/etc code and fullscreen setup down after the menu setup code fixes the issue.

**Comment by joncampbell123** [comment]
The latest commit seems to fix the issue. Testing to make sure it doesn't break Linux.

**Comment by joncampbell123** [comment]
Linux is OK. Fixed.
