### ISSUE TITLE
Option NOT to cache hard-disk directories 

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1414]
If I understand this correctly, DOSBox and DOSBox-X, by default, have always cached directories mounted as hard-disks, so that if you read the directory of a hard-disk folder, and then some program outside DOSBox-X changes the directory, DOSBox-X won't see the change.

My fork needs the ability to see directory changes made outside DOSBox-X, and I've accomplished this by changing dos_programs.cpp, line 321, to use the media type for a floppy (0xF0) instead of the media type for a hard disk (0xF8). Is there any chance that DOSBox-X could add a config option "Don't cache hard-disk directories"? I'm probably not the the only person who could use this.

And if this feature is already present, my apologies for wasting bandwidth.

EDIT: I see that this was addressed earlier here: https://github.com/joncampbell123/dosbox-x/issues/1379

So I'll rephrase my original question: Is it possible to have a config option to set the -nocachedir switch for all hard drives?

**Comment by joncampbell123** [comment]
Not at this time, but you can use -nocachedir with every mount command until that is implemented.

**Comment by joncampbell123** [comment]
There you go. Under [dosbox] add nocachedir=true

**Comment by emendelson** [comment]
That was quick! Thank you!
