### ISSUE TITLE
cputype=pentium_mmx does not support 16-bit real mode MMX instructions / confirm they work on real Pentium MMX

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1416]
**Describe the bug**
DOSBox-X throws an invalid opcode exception on any attempt to execute MMX instructions in real mode. It does NOT throw the same exception in 32-bit protected mode.

**How to test**
Run dos86l\mmx.exe, observe invalid opcode exception. Run dos386f\mmx.exe, observe no crash.

**Comment by Wengier** [comment]
Already fixed in version 0.83.3 I believe.

**Comment by joncampbell123** [comment]
That is correct. The MMX cases needed to be included for both 32-bit and 16-bit code cases.
