### ISSUE TITLE
CPU type is not considered when decoding MMX instructions

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1417]
**Describe the bug**
It appears there's no special case code for MMX instructions vs CPU type. Which means a 486 CPU type may still execute MMX instructions, which is wrong. The only thing stopping programs from trying to execute MMX instructions for anything less than pentium_mmx is the bitmask returned by CPUID that indicates whether MMX support exists.

**Comment by Wengier** [comment]
Already fixed in version 0.83.3 I believe.
