### ISSUE TITLE
DPI awareness is a drawback on Surface tablets with high resolution displays

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#1420]
**Describe the bug**
On systems attached to a high resolution display, including Surface tablets with a 2880 x 1920 display, DOSBox-X's DPI awareness disables scaling at the cost of a very small window on the display.
![Tiny DOSBox-X](https://user-images.githubusercontent.com/6245486/75505050-183bf780-598f-11ea-83bc-101a2fbdaa5b.png)

**Comment by joncampbell123** [comment]
Perhaps it's time to re-enable that auto scale select I disabled some time ago due to window scaling problems, since the code now defers window sizing until the user finishes. Then, the auto scale should take the user's display DPI into consideration, so that this isn't a problem.

**Comment by Wengier** [comment]
I noticed that the "dpi aware=auto" setting is recently added, and the current code for "dpi aware=auto" is:

```
#if defined(MACOSX)
				/* Try not to look extra tiny on Retina displays */
				dpi_aware_enable = false;
#elif defined(WIN32) && defined(_MSC_VER) && (defined(_M_ARM) || defined(_M_ARM64))
				/* Microsoft Surface tablets are really high resolution. Try not to look like a tiny window on them */
				dpi_aware_enable = false;
#else
				dpi_aware_enable = true;
#endif
```

For Windows systems, I think the "false" setting will only apply if it is running on ARM/ARM64 platforms. However, this apparently does **not** cover all Surface tablets. For example, I am using Windows 10 on Surface Pro 4 (x64 system), and with "dpi aware=auto" the window is still very small. I have to manually set it as "api aware=false" instead to avoid this problem.

**Comment by joncampbell123** [comment]
That is correct. The intent is to assume false if Windows ARM/ARM64. Later on, I intend to add code to query the primary monitor and decide from the DPI whether to default true or false.

**Comment by Wengier** [comment]
@joncampbell123 I have improved "dpi aware=auto" in my pull request #1581. You can take a look a it.

**Comment by joncampbell123** [comment]
Why not just "dpi >= 192" or "dpi >= (96*2)" ?

**Comment by Wengier** [comment]
@joncampbell123 They are all same of course. My code just check the scaling factor, which is DPI/96.
