### ISSUE TITLE
Add some logging in dos file functions

### ISSUE THREAD

**Issue by ognjenmi** [joncampbell123/dosbox-x#1421]
It would be good to add some logging in file close, file read, file write and file delete (unlink) functions in dos_files.cpp.
Maybe would be also good to log all INT 21 calls by displaying ah and al registers.
This would make detection of some problems easier.

When I was resolving the issue #1411 I changed this part of code and things were  much more clear to me. 

I attached patches that contain suggested changes.
[dosbox-x-add-log-patches.zip](https://github.com/joncampbell123/dosbox-x/files/4269718/dosbox-x-add-log-patches.zip)

Regards,
Ognjen

**Comment by joncampbell123** [comment]
I will either use your patch or add it myself, on the condition that you have to enable it from the command line or dosbox.conf to enable file I/O logging. Most people don't care to fill their log.txt files with every file I/O involved.

**Comment by ognjenmi** [comment]
I used standard logging function I saw in the code which takes care of log type and level.

**Comment by joncampbell123** [comment]
Added to latest commit.

**Comment by joncampbell123** [comment]
I will close this issue later when I add some new code around your patch. I think it would be better if it wasn't enabled by default even for --debug mode, but could be enabled at any time from the command line, or from the DOS menu in the menu bar.

**Comment by joncampbell123** [comment]
Patch added.
