### ISSUE TITLE
Failing to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by popey** [joncampbell123/dosbox-x#1429]
I maintain the [snap](https://snapcraft.io/dosbox-x) of dosbox-x (which has around 5K weekly active installs), and recently it's started to fail to build, which blocks updating it to the latest stable release.

```
HEAD is now at 16061fdd2 Prepare for release
./autogen.sh: 5: ./autogen.sh: function: not found
./autogen.sh: 6: [: -eq: unexpected operator
./autogen.sh: 9: ./autogen.sh: Syntax error: "}" unexpected
Failed to run 'override-build': Exit code was 1.
Build failed
```
I suspect that's due to `/bin/sh` pointing to `/bin/dash` on Ubuntu rather than bash. The same code in `autogen.sh` works in bash. 

The full log can be found at https://launchpadlibrarian.net/467336852/buildlog_snap_ubuntu_bionic_amd64_4d5029d8ffe84c9769102f66cf7436f9_BUILDING.txt.gz (scroll to the bottom). 

it previously worked. Looks like the code added 10 days or so "broke" it. https://github.com/joncampbell123/dosbox-x/blame/master/autogen.sh

Perhaps changing the shebang to `#!/bin/bash` is sufficient (the code passes) if you're okay with that? Otherwise I'll carry a patch in the snap to ninja that line, but obviously I'd rather not :D

**Comment by joncampbell123** [comment]
I will change it to #!/bin/bash, since that is what the script is written for.
