### ISSUE TITLE
Voodoo hardware emulation has rounding errors in pixel pipeline

### ISSUE THREAD

**Issue by ghoul8765** [joncampbell123/dosbox-x#143]
At Vogons, there is a workaround patch to avoid rounding errors in the pixel pipeline while in hardware mode. These errors do not occur in the software rasterizer. This workaround stretches the framebuffer so the rounding error artifacts are not shown. However, this stretching creates an improperly sized framebuffer which may cause other problems. I recommend no longer using that patch except for the portions which do not relate to stretching the framebuffer. I can post those code bits if needed.

Instead, I identified the source of the rounding errors and posted a patch below. This fixes the pixel pipeline in hardware mode and affects both 3dfx and d3d games. The d3d games were especially susceptible to the errors, likely from extensive use of the pixel pipeline in HUDs and text on-screen.
<pre lang=""><code>diff -rupN dosbox-NEW-ORIG//src/hardware/voodoo_opengl.cpp dosbox-NEW//src/hardware/voodoo_opengl.cpp
--- dosbox-NEW-ORIG//src/hardware/voodoo_opengl.cpp	2015-05-28 23:14:21 -0400
+++ dosbox-NEW//src/hardware/voodoo_opengl.cpp	2016-01-23 15:56:57 -0500
@@ -1301,6 +1300,8 @@ void voodoo_ogl_texture_clear(UINT32 tex
 }
 
 void voodoo_ogl_draw_pixel(int x, int y, bool has_rgb, bool has_alpha, int r, int g, int b, int a) {
+	GLfloat x2, y2;
+
 	if (m_hProgramObject != 0) {
 		glUseProgramObjectARB(0);
 		m_hProgramObject = 0;
@@ -1320,9 +1321,12 @@ void voodoo_ogl_draw_pixel(int x, int y,
 
 	VOGL_SetAlphaMode(0, 0,0,0,0);
 
+	x2 = (GLfloat) x + 0.5;
+	y2 = (GLfloat) y + 0.5;
+
 	VOGL_BeginMode(GL_POINTS);
 	glColor4ub((GLubyte)(r&0xff), (GLubyte)(g&0xff), (GLubyte)(b&0xff), (GLubyte)(a&0xff));
-	glVertex2i(x, y);
+	glVertex2f(x2, y2);
 }
 
 void voodoo_ogl_draw_z(int x, int y, int z) {
@@ -1355,6 +1359,7 @@ void voodoo_ogl_draw_z(int x, int y, int
 
 void voodoo_ogl_draw_pixel_pipeline(int x, int y, int r, int g, int b) {
 //	VOGL_ClearBeginMode();
+	GLfloat x2, y2;
 
 	// TODO redo everything //
 	if (m_hProgramObject != 0) {
@@ -1386,11 +1391,14 @@ void voodoo_ogl_draw_pixel_pipeline(int
 		VOGL_SetAlphaMode(0, 0,0,0,0);
 	}
 
+	x2 = (GLfloat) x + 0.5;
+	y2 = (GLfloat) y + 0.5;
+
 	VOGL_BeginMode(GL_POINTS);
 //	glBegin(GL_POINTS);
 //	glColor3f((float)r/255.0f, (float)g/255.0f, (float)b/255.0f);
 	glColor3ub((GLubyte)(r&0xff), (GLubyte)(g&0xff), (GLubyte)(b&0xff));
-	glVertex2f((float)x, (float)y);
+	glVertex2f(x2, y2);
 //	glEnd();
 }
 
</code></pre>

**Comment by joncampbell123** [comment]
Added.

**Comment by joncampbell123** [comment]
Let me know if I should close this issue

**Comment by ghoul8765** [comment]
Thanks, I think so.
