### ISSUE TITLE
Linux - IMGMOUNT MSCDEX: Failure: Invalid file or unable to open

### ISSUE THREAD

**Issue by 7oxicshadow** [joncampbell123/dosbox-x#1441]
I have a .cue file with an iso binary and 29 additional .ogg files for audio.

If I try to mount using "imgmount e path/to/file.cue -t cdrom" I get the error:

MSCDEX: Failure: Invalid file or unable to open

This command works fine in standard dosbox and the mount works as expected (including audio).
Digging around on the net suggests that this is a known problem if dosbox is not compiled with SDL_sound.

I cannot seem to see a reference to SDL_sound in your fork. Does dosbox-x support .ogg files?

Thanks

**Comment by joncampbell123** [comment]
CD-ROM emulation as inherited from DOSBox SVN does not include Ogg support.

**Comment by 7oxicshadow** [comment]
Hmm. I wonder what version is available in the Fedora repos then...
I know it is 0.74.3 but it must not be the SVN version.

Either way, thanks for taking the time to respond. I will close the issue.

Thanks.
