### ISSUE TITLE
SDL_Sound for compressed imgdisks

### ISSUE THREAD

**Issue by NelsonRosenberg** [joncampbell123/dosbox-x#1442]
**Describe the bug**
I'm trying to run a game that has a compressed bin/cue with an ogg track. Both this and the SVN version give me an error. I wonder if SDL_Sound is not enabled and, if so, would it be possible?

The error message is "MSCDEX: Invalid file or unable to open". The images in question do work in original version of dosbox.

**To Reproduce**
```
C:\>IMGMOUNT D dummy.cue -t iso -fs iso
Could not load image file: dummy.cue
MSCDEX: Failure: Invalid file or unable to open
````

To reproduce I have used the audio from Bazooka Sue installer here:  http://bakhtosh.bplaced.net/?page_id=25.

**Expected behavior**
Image is mounted successfully 

**Environment (please complete the following information):**
 - Operating system: Win 10
 - DOSBox-X release version: DOSBox-X 0.83.0 2020-03-01 00:33

Hope that helps. Thank you.

**Comment by joncampbell123** [comment]
DOSBox-X does not implement support for OGG/MP3 compressed audio tracks.

**Comment by NelsonRosenberg** [comment]
Thank you for the quick reply. Could that be a request for a future improvement?

**Comment by joncampbell123** [comment]
Of course. Libogg + Libvorbis and some additional code, or the relevant code could be borrowed from the fork that does support it with credit in the README.

**Comment by rderooy** [comment]
DOSBox ECE supports it, and it would be great if DOSBox-X would 'borrow' that functionality :-)

**Comment by Wengier** [comment]
I have already "borrow" this functionality to DOSBox-X from DOSBox-staging. See my pull request #1639.
