### ISSUE TITLE
Add unique DOS device to DOSBox-X so batch files can ID DOSBox-X?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1446]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a DOS device to DOSBox-X that can be tested by a batch file, so that the batch file can then take action if (and only if) DOSBox-X is the environment?

**Describe the solution you'd like**
I've added a DOSBOX# device to dos_devices.cpp by plugging in these two blocks of code, but I don't understand what I'm doing, so this is almost certainly inefficient and wrong, But it seems to work:

First, around line 65:

`class device_DOSBOX : public DOS_Device {`
` public:`
`    device_DOSBOX() { SetName("DOSBOX#"); };`
`    virtual bool Read(Bit8u* data, Bit16u* size) {`
`        (void)data; // UNUSED`
`       *size = 0; //Return success and no data read. `
`        return true;`
`    }`
`    virtual bool Write(const Bit8u* data, Bit16u* size) { `
`        (void)data; // UNUSED`
`        (void)size; // UNUSED`
`        return true;`
`    }`
`    virtual bool Seek(Bit32u* pos, Bit32u type) {`
`        (void)type;`
`        (void)pos;`
`        return true;`
`    }`
`    virtual bool Close() { return true; }`
`};`

and then, in the code that begins "void DOS_SetupDevices(void) {"

`  DOS_Device* newdev4;`
`  newdev4 = new device_DOSBOX();`
`  DOS_AddDevice(newdev4);`
  
I'm sure there's a better way, and I hope the better way might be worth adding to the source.

**Comment by Wengier** [comment]
@emendelson I think another (probably easier and better) way for batch files to check whether DOSBox-X is the environment is to test the existence of DOSBox-X specific files in the Z drive. In such case no code modifications will be needed. For example:

IF EXIST Z:\DSXMENU.EXE IF EXIST Z:\NMITEST.COM ECHO DOSBox-X is running.

**Comment by emendelson** [comment]
@Wengier - Of course that is exactly right. I should not have forgotten that!
