### ISSUE TITLE
DOSBox-X FFMPEG capture gets RGB colors backwards in 16bpp modes

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#145]
Not sure if it's a problem with FFMPEG's libswscale library.

It's most visible on the Windows 98 desktop (machine=svga_s3) when set to 16-bit RGB mode.

**Comment by ghoul8765** [comment]
Would it make a difference by setting SDL to windib or another output mode other than surface? I also recall that you made an (experimental?) change to detect the higher depth mode in dosbox-x some time ago, would that have any effect?

**Comment by joncampbell123** [comment]
windib? In Linux? :)

The higher depth mode fix was for someone's Mac OS X installation, where apparently for each 32-bit pixel the alpha channel was in bits 0-7 instead of bits 24-31 where most PC graphics cards put it.

**Comment by ghoul8765** [comment]
Sorry. :)

Also, here is the wikipedia entry: https://en.wikipedia.org/wiki/FFmpeg. I wonder whether it has the support built-in.

**Comment by joncampbell123** [comment]
Fixed it. FFMPEG's pix fmt defines RGB/BGR order for 15/16bpp mode according to bit field order, and 24/32bpp mode according to byte order. So naturally, I'd got it backwards by mistake.
