### ISSUE TITLE
DIR always displays label of current drive

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1451]
**Describe the bug**
When running the integrated DOS commands in DOSBox-x and typing DIR to show the contents of a drive other then the current drive will show the LABEL of the current drive.

e.g. this works fine;
![command_000](https://user-images.githubusercontent.com/17701098/77223468-2e3b7300-6b5d-11ea-9259-2cc0b71db7d8.png)

But here it still shows the label of the Z: drive
![command_001](https://user-images.githubusercontent.com/17701098/77223477-490de780-6b5d-11ea-875e-ac65d7270bea.png)

But once I make the A: drive my current drive, DIR will return the correct LABEL data.
![command_002](https://user-images.githubusercontent.com/17701098/77223504-79ee1c80-6b5d-11ea-94ba-59eaef95bf24.png)

I also double checked with MS-DOS 6.22 and it works properly. And I tried it with other DOSBox editions (vanilla, ECE, staging) but only staging has a more advanced dir, and then only shows the label (which works properly), not the serial.

**To Reproduce**
1. run DIR on a drive other then the current drive

**Expected behavior**
See the destination drive label and serial

**Environment (please complete the following information):**
Fedora 31
DOSBox-x 0.83.0 64bit built myself, but the same happens with your RPM.

**Edit**
I removed the references to serial also being incorrect, as I noticed that is still a TODO item.

**Comment by Wengier** [comment]
@joncampbell123 I have made a patch that fixes the label issue with the DIR command, and it also fixes the issue that DIR /P was unable to display the drive label when waiting for a key press, and the issue that users could not press Ctrl+C to break from such a pause with the DIR /P command. The diff file for the latest commit ee92c3c is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-ee92c3c-patch.diff

A pre-compiled Windows 64-bit binary is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by joncampbell123** [comment]
Patch applied, fixed.
