### ISSUE TITLE
mt32.romdir using tilde (~) in path does not work

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1452]
**Describe the bug**
Using a relative link with a tilde to the home directory in the mt32.romdir path does not work. Using . or .. however seems to work fine.

e.g.
config -set mt32.romdir=~/mt32
will show in the log 
LOG: MT32 emulation cannot work without the PCM and CONTROL ROM files.
LOG: To eliminate this error message, either change mididevice= to something else, or
LOG: place the ROM files in what will be the "current working directory" for DOSBox-X
LOG: when it starts up and initializes MIDI emulation.
LOG: The ROM files are: CM32L_CONTROL.ROM, MT32_CONTROL.ROM, CM32L_PCM.ROM, MT32_PCM.ROM
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h

But running
config -set mt32.romdir=/home/user/mt32
and it will show only
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h

**To Reproduce**
1. Try to use a relative path to the ROMs with a tilde

**Expected behavior**
For the roms to be found

**Environment (please complete the following information):**
- Fedora 31
- DOSBox-X 0.83.0 64bit built

**Comment by sikthehedgehog** [comment]
`~` is a shell thing, it's not part of the path processing so most programs don't support that.

That said, I imagine it'd be nice to make it work (even if it just relies on `getenv("HOME")` and then refuses to work if not defined), so I'd vote to turn this into a feature request instead lol

**Comment by rderooy** [comment]
Ok, understood. If you want to change it to a feature request, I'm fine with it.

**Comment by joncampbell123** [comment]
Also, dosbox.conf files that use tilde will only work on Mac OS X or Linux, not Windows

**Comment by sikthehedgehog** [comment]
I imagine this is for customized settings (though default paths should differ between OSes *anyway*).

**Comment by rderooy** [comment]
This was resolved some time ago
