### ISSUE TITLE
Multiple screenshots taken of a program all overwrite as (name)_000.png

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#1454]
**Describe the bug**
When using the "Take screenshot" command from the DOSBox-X GUI, the screenshots taken are always saved with the number 000. This means that if you take multiple screenshots of a program, only the last one will remain, because they will have all overwritten with the same filename.

**To Reproduce**
1. Start DOSBox-X to the DOSBox-X command prompt. Remove any file named `command_000.png` from the `capture` folder if you don't want to lose it.
2. Click "Capture", then "Take screenshot" in the DOSBox-X GUI.
3. You should get a screenshot called `command_000.png` in the `capture` folder.
4. Type something so the screen looks different, and click "Take screenshot" again.
5. A new screenshot will be taken (you can check that it shows the text you typed), overwriting `command_000.png`. The first screenshot is lost.

**Expected behavior**
Additional screenshots should be saved with a suffix of 001, 002, etc.

**Environment (please complete the following information):**
 - Windows 10 x64, built with Visual Studio 2019 with SDL1.
 - 3ec8c34 (latest as of now)
 - Happens with the default .conf.

**Additional context**
Does not happen with the latest release 0.83.0 on the releases page (Visual Studio x64 SDL1 binary).

**Comment by joncampbell123** [comment]
It's possible the recent LFN patch broke it.

**Comment by joncampbell123** [comment]
Fixed, latest commit.
