### ISSUE TITLE
Fix for "E_Exit: DOS: Too many devices added" when CLIP$ and 3 LPT ports enabled

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1456]
When I enabled the new CLIP$ device and three parallel ports, DOSBox-X, the program started up with an error message "E_Exit: DOS: Too many devices added"

The fix is to change dos_inc.h, line 115, so that it reads:

#define DOS_DEVICES 15

instead of 10. I think this allows for CLIP$, three LPT ports and four COM ports but I haven't tested the COM ports. I don't know if this has any bad effects elsewhere, but it seems to work here.

**Comment by Wengier** [comment]
@emendelson and @joncampbell123 I can confirm this error with such configuration, but I notice that the same error happens in the earlier DOSBox-X 0.83.0 official version too if I enable all the LPT and COM ports (e.g. "parallelX = file" for X=1..3 and "serialX = file" for x=1..4), even though there is no such device as CLIP$ in that version. In other words, this error is not specific to the recent changes or features, but it happens in earlier versions too. Increasing DOS_DEVICES as recommended by emendelson will hopefully fix such problem.

**Comment by joncampbell123** [comment]
I increased the limit to 20, just to be safe.
