### ISSUE TITLE
Renaissance "Amnesia" demo hangs if sbtype=sbpro2

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#146]
There seems to be loop that gets stuck if the DSP signals not busy (and never toggles it?)

Did the Sound Blaster Pro have a DSP busy cycle too?

**Comment by joncampbell123** [comment]
This same problem also affects some other earlier demos. The 1991 "Scrolla" demo gets stuck the same way when you hit spacebar to exit to DOS.

**Comment by joncampbell123** [comment]
The code in question appears in "Scrolla", "Amnesia" and in some form "Saga" by dust. They all have hangups if sbtype is anything other than sb16 (with a DSP busy cycle).

  0008:4B33  FB                  sti
  0008:4B34  803D0129000000      cmp  byte [00002901],00
  0008:4B3B  741E                je   00004B5B ($+1e)        (no jmp)
  0008:4B3D  FA                  cli
  0008:4B3E  EC                  in   al,dx
  0008:4B3F  0AC0                or   al,al
  0008:4B41  79F0                jns  00004B33 ($-10)        (up)
  0008:4B43  EC                  in   al,dx
  0008:4B44  0AC0                or   al,al
  0008:4B46  78FB                js   00004B43 ($-5)         (no jmp)

**Comment by ghoul8765** [comment]
If you edit the je or js instruction for a jmp, does it continue to play? Perhaps from 74xx and 78xx to EBxx?

Did the dosbox-x logging present clues? Did you test a real sbpro (versions) against the "DSP busy cycle"?

**Comment by joncampbell123** [comment]
I'll try patching the instruction.

I don't have a Sound Blaster Pro card to test with, but I do have plenty of SB16 cards that I know have the busy cycle, and one original Sound Blaster 2.0 (not Pro) that I confirmed does not have the busy cycle.

If you or anyone else has a Sound Blaster Pro lying around, plug it in, boot it up, and then test for the busy cycle by running DEBUG.EXE and typing this line repeatedly:

    i 22C

On a SB16, you'll see a lot of 7F codes and sometimes FF as well. On a DSP 2.0 you'll only see 7F (no busy cycle).

    7F: DSP not busy (bit 7=0)
    FF: DSP busy (bit 7=1)

**Comment by joncampbell123** [comment]
Fun fact BTW, I confirmed on the SB 2.0 card that

**Comment by joncampbell123** [comment]
Right. So if the demo is stuck at this code, overwriting the "jns" instruction with NOPs (90 90) allows Amnesia to run, Scrolla to exit to DOS, and Saga to start up when sbtype=sbpro2.

    0008:4B33  FB                  sti
    0008:4B34  803D0129000000      cmp  byte [00002901],00
    0008:4B3B  741E                je   00004B5B ($+1e)        (no jmp)
    0008:4B3D  FA                  cli
    0008:4B3E  EC                  in   al,dx
    0008:4B3F  0AC0                or   al,al
    0008:4B41  79F0                jns  00004B33 ($-10)        (up)
    0008:4B43  EC                  in   al,dx
    0008:4B44  0AC0                or   al,al
    0008:4B46  78FB                js   00004B43 ($-5)         (no jmp)            

Saga doesn't even have the "cmp byte[xxx] / je" in the loop, but it's basically the same kind of loop.
So the question is, why are these demos waiting for the DSP to become busy when not busy?
Did the DSP have a busy cycle all along? How would this work with SB clones that probably don't do that?

**Comment by joncampbell123** [comment]
When the card is doing nothing else, the DSP busy bit cycles by itself on SB16 cards. On the SB 2.0 card I have, I see no such cycling.

But that's when the card isn't doing anything. So what I will check next is whether or not the busy bit cycles by itself when the card is playing audio.

**Comment by joncampbell123** [comment]
A-ha. Okay, so here's how the whole busy cycle thing works out:

On the SB16 cards, the DSP busy cycle is always there.
On my SB 2.0 card, the DSP busy cycle only happens when the card is playing audio through DMA.

So that right there tells me how to fix this issue.

**Comment by ghoul8765** [comment]
Nice work. I'm surprised the issue wasn't seen in past cases.

**Comment by joncampbell123** [comment]
Results of update:

Amnesia: Now runs fine with sbtype=sbpro2
Scroll land: Hitting spacebar no longer hangs, exits to DOS properly
Saga: Runs fine with sbtype=sbpro2. Also, unlike sbtype=sb16, the demo doesn't make obnoxious static noises between demo parts.

Looks like success.
