### ISSUE TITLE
Win98 SE Install Freeze Plug&Play Bios detection

### ISSUE THREAD

**Issue by Starfoxfs** [joncampbell123/dosbox-x#1461]
**Describe the bug**
The Windows 98 SE 4.10.2222 German freezes at Installation at the Point where Plug&Play Components detection runs (Remaining 15 Minutes see attached Picture).

The Win98 Installation runs in Verbose Mode (setup /p g=3) for testing where the Problem is. 

My C.Img is created with imgmake with Megabuild 6 and a Dos6.22 Bootdisk
Imgmake c.img -t hd_2gig -nofs -bat

**Environment (please complete the following information):**
 - Windows 10 64bit Version 1909
 - DOSBox-X Version 0.83.0 64bit for Windows x64 Release SDL2

[dosbox.conf.txt](https://github.com/joncampbell123/dosbox-x/files/4401800/dosbox.conf.txt)

![error3](https://user-images.githubusercontent.com/62878094/77895762-8833eb00-7277-11ea-9094-67932a86c75a.jpg)

**Comment by rderooy** [comment]
You need to change some settings to run Win9x under DOSBox-X. Here is what I use with Win95:

[cpu]
cputype=pentium_slow
core=normal

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakev86io=true

[ide, secondary]
int13fakev86io=true
cd-rom insertion delay=4000

**Comment by Starfoxfs** [comment]
I´ve tried it with Pentium_slow, Windows Setup shows "You need at minimum a 66MHZ CPU".

Then i changed Settings to:
cputype=pentium
core=normal

With this Settings it runs.

**Comment by rderooy** [comment]
My main point was to use core=normal or core=full. I don't recall getting the 66MHz error, but I just changed my setting to the (newer) cputype=pentium_mmx and that seems to boot fine.

I suspect that those notes that you referenced are a bit dated. They are from 2014.

**Comment by joncampbell123** [comment]
It's best to run the Windows install all the way through with core=normal. core=dynamic is incompatible with Windows 95/98/ME because of the way they do preemptive multitasking, and task switching during page fault exceptions.

**Comment by Starfoxfs** [comment]
Ok thank you for the Help 👍 

Now it runs fine.
