### ISSUE TITLE
PC-DOS 2000 setup.exe causes DOSBox-X core dump

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1468]
**Describe the bug**
Trying to avoid having to run LOADDSKF to create a boot disk... I tried running the PC-DOS 2000 setup.exe directly from the CD-ROM from the DOSBox-X integrated DOS to install it to the mounted C: drive. This seems to run fine, it asks all the questions, but at the end where it needs to start the actual install process, DOSBox-X gets a segmentation fault (LOG messages attached below).

This uses the PC-DOS 2000 CD-ROM (which is NOT bootable).

**To Reproduce**
 IMGMAKE hdd.img -t hd -size 2048
 IMGMOUNT C hdd.img
 IMGMOUNT D PC-DOS_2000.iso -t iso
 D:
 SETUP

**Expected behavior**
Not a core dump :-)

**Environment (please complete the following information):**
- DOSBox-X 0.83.0 64bit
- Fedora 31

**Additional context**
LOG: IDE: index 0 slave=0
LOG: Using partition 0 on drive (type 0x06); skipping 63 sectors
LOG: FAT: BPB says 63 sectors/track 128 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT16 with 65510 clusters
LOG: Mapping BIOS DISK C/H/S 520/128/63 as IDE 4160/16/63
LOG: IDE: index 0 slave=1
LOG:  165278138 ERROR BIOS:CMOS:WRite to unhandled register 17
LOG:  165278159 ERROR BIOS:CMOS:WRite to unhandled register 17
LOG:  165278195 ERROR BIOS:Disk 0 not active
LOG:  165761366 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=AD80
LOG:  165761538 ERROR MISC:DOS:Setting country code not supported
LOG:  165761648 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B700
LOG:  165761719 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165761757 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165761795 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165761833 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165762669 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165762720 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165762755 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165763525 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165763987 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165765441 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165765476 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165766246 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165767319 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165769145 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165769180 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165769950 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165771023 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:  165771972 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:  165803827 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4680
LOG:  165803948 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4A12
LOG:  165803957 ERROR BIOS:INT1A:Undefined call B0
LOG:  165804165 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:  165804372 ERROR DOSMISC:DOS:IOCTL Call  4 unhandled
LOG:  165816749 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG: 1143839437 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG: 1143841224 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG: 1143847429 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG: 1143849662 ERROR MISC:DOS:Set File Attributes for C:\IBMBIO.COM not supported
LOG: 1143850306 ERROR MISC:DOS:Set File Attributes for C:\IBMDOS.COM not supported
Segmentation fault (core dumped)

**Comment by rderooy** [comment]
I decided to compile the latest version from github (as of today), and the segfault does not occur, and the installation succeeds. After the installation is complete, I can boot the HDD img.

so..
**To Reproduce**
IMGMAKE hdd.img -t hd -size 2048
IMGMOUNT C hdd.img
IMGMOUNT D PC-DOS_2000.iso -t iso
D:
SETUP

After installation has completed, and rebooted DOSBox-X:
IMGMOUNT C hdd.img
BOOT -L C

It does generate tons of messages in the LOG, most of them to do with not being able to set file attributes, which I don't understand as the C: drive is an image, and not a host filesystem, so setting attributes should be possible.

Also, PC-DOS 2000 loads an APM driver by default, so I get a constant stream of
LOG: APM BIOS warning: CPU IDLE called with IF=0, not HLTing
But that may be resolved by setting some DOSBox-X APM options, need to test.

**Comment by rderooy** [comment]
As to the constant stream of APM messages after installation, the only way to stop them that I found was to disable APM by setting in the [cpu] section either

apmbios = false
or
apmbios allow realmode=false

Or from CONFIG.SYS just remove the line DEVICE=C:\DOS\POWER.EXE

**Comment by rderooy** [comment]
I will close this issue, as the core problem is resolved, and open a new one for not being able to set file attributes on a mounted image from the integrated DOS.

Not sure if I should open an issue for the APM warnings.

**Comment by rderooy** [comment]
Seems I was too quick in closing this issue. It occurs with both 0.83.0 and 0.83.1-git

The first time you run SETUP it will crash DOSBox-X with a SEGFAULT, but if you then restart DOSBox-X and run SETUP a second time, it will succeed.

After the SEGFAULT the HDD image contains the following files:
IBMBIO.COM
IBMDOS.COM
And the following empty directory structure:
\DOS\SYSTEM
\DOS\DATA

**Comment by Wengier** [comment]
There is apparently a bug in the code while handling the creation of the volume label. This is now fixed in the patch file I posted in Issue #1469.

**Comment by joncampbell123** [comment]
@Wengier Please confirm the latest commit fixes the crash, and then close the issue if it did.

**Comment by rderooy** [comment]
@Wengier Thanks again! I can indeed confirm that with the latest 0.83.1-git version as of today, the crash no longer happens.

Here is the LOG from the install. Note that this is with apmbios=false

LOG: IDE: index 0 slave=0
LOG: Using partition 0 on drive (type 0x06); skipping 63 sectors
LOG: FAT: BPB says 63 sectors/track 128 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT16 with 65510 clusters
LOG: Mapping BIOS DISK C/H/S 520/128/63 as IDE 4160/16/63
LOG: IDE: index 0 slave=1
LOG:   43504164 ERROR BIOS:CMOS:WRite to unhandled register 17
LOG:   43504185 ERROR BIOS:CMOS:WRite to unhandled register 17
LOG:   43504221 ERROR BIOS:Disk 0 not active
LOG:   43987385 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=AD80
LOG:   43987557 ERROR MISC:DOS:Setting country code not supported
LOG:   43987667 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B700
LOG:   43987738 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43987776 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43987814 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43987852 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43988688 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43988739 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43988774 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43989544 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43990007 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43991461 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43991496 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43992266 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43993338 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43995164 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43995199 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43995969 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43997043 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG:   43997992 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:   44032455 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4A12
LOG:   44032464 ERROR BIOS:INT1A:Undefined call B0
LOG:   44032671 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:   44032878 ERROR DOSMISC:DOS:IOCTL Call  4 unhandled
LOG:   44045230 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:   98657607 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:   98659394 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:   98665599 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:   98683954 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:  322333414 ERROR DOSMISC:DOS:IOCTL Call  5 unhandled
LOG:  322371177 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322372137 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322401570 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322402530 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322431035 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322431995 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322461411 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322462371 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322491024 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322491984 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322521701 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322522661 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322551926 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322552886 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322582339 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322583299 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322612590 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322613550 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322642839 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322643799 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322673263 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322674223 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322703556 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322704516 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322733786 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322734746 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322764312 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322765272 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322794694 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322795654 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322824723 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322825683 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322855029 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322855989 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322885089 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322886049 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322915077 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322916037 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322945081 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322946041 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322974804 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  322975764 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323004695 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323005655 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323035027 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323035987 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323065454 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323066414 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323095535 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323096495 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323125744 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323126704 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323156241 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323157201 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323186668 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323187628 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323217099 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323218059 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323247073 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323248033 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323277215 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323278175 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323307364 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323308324 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323337799 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323338759 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323368097 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323369057 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323398354 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323399314 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323428613 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  323429573 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1203
LOG:  335638899 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B700
LOG: APM BIOS call attempted. set apmbios=1 if you want power management
LOG:  336342178 ERROR BIOS:INT15:Unknown call ax=4100

**Comment by rderooy** [comment]
Seems I was again too quick in closing the issue. While the original problem is indeed no longer happening, I cannot boot the HDD disk image afterwards. When executing the "BOOT -L C" command, it tries to boot, sits there for a few seconds while in the LOG I am seeing "Illegal Unhandled Interrupt Called 20" messages pop up and then DOSBox-X just closes. No core dump or anything.

LOG: IDE: index 0 slave=0
LOG: Using partition 0 on drive (type 0x06); skipping 63 sectors
LOG: FAT: BPB says 63 sectors/track 128 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT16 with 65510 clusters
LOG: Mapping BIOS DISK C/H/S 520/128/63 as IDE 4160/16/63
LOG: IDE: index 0 slave=1
LOG: Booting guest OS stack_seg=0x7000 load_seg=0x07c0
LOG: Removing UMB block 0xcc00-0xdfff
LOG: Alright: DOS kernel shutdown, booting a guest OS
LOG:   CS:IP=0000:7c00 SS:SP=7000:0100 AX=0000 BX=7c00 CX=0001 DX=0080
LOG:   14194749 ERROR CPU:Illegal Unhandled Interrupt Called 20
LOG:   17621556 ERROR CPU:Illegal Unhandled Interrupt Called 20
LOG:   21048365 ERROR CPU:Illegal Unhandled Interrupt Called 20
LOG:   24475173 ERROR CPU:Illegal Unhandled Interrupt Called 20
LOG:   27901997 ERROR CPU:Illegal Unhandled Interrupt Called 20
LOG:   31328759 ERROR CPU:Illegal Unhandled Interrupt Called 20
LOG:   31329209 ERROR CPU:Illegal Unhandled Interrupt Called 6

Trying to boot MS-DOS 6, it just hangs with a stream of "Illegal Unhandled Interrupt Called 6" messags. So it seems the patch broke booting from a HDD image.

**Comment by Wengier** [comment]
@rderooy I do not think I can reproduce the said problem on my computer so far. After executing the "BOOT -L C" command within DOSBox-X, I will see the following on my screen:

Z:\> BOOT -L C
Booting from drive C...

F1 . . . Dos
F5 . . . disk 2

Default: F1

If I press F1 (or just ENTER), then PC DOS 2000 will boot as normal. Also tried to boot MS-DOS 6.0 after installation, which works too. Perhaps something wrong with your HDD image?

**Comment by Wengier** [comment]
@rderooy I have tried multiple times (>10 times) to install PC DOS 2000 (from CD) or MS-DOS 6.0 (from A:) and then tried to boot from Drive C: from within DOSBox-X (latest commit). The conclusion from my test results:

* MS-DOS 6.0 is always able to boot from the HDD image after install;
* PC DOS 2000 is able to boot from the HDD image after install if it was already installed before, or if there were files IBMBIO.COM and IBMDOS.COM located in C:\ before install, otherwise it will not boot correctly (either hang or "Non-System disk or disk error" if a different DOS was previously installed).

However, I noticed that this is in fact another issue associated with DOSBox-X's PC DOS 2000 compatibility, and it is *not* caused by the earlier patch. Because without the patch, PC DOS 2000 Setup crashed after copying the files IBMBIO.COM and IBMDOS.COM to C:\, and when you re-run PC DOS 2000 Setup and finish it, PC DOS 2000 will boot fine only because the files IBMBIO.COM and IBMDOS.COM were already in C:\ before the last install. With the patch however, PC DOS 2000 Setup will no longer crash, so there is no need to run PC DOS 2000 Setup for the second time. If PC DOS 2000 was not previously installed, then before running Setup there would be no files IBMBIO.COM and IBMDOS.COM located in C:\, but if you manually copy the files IBMBIO.COM and IBMDOS.COM from the install CD to C:\ before running PC DOS 2000 Setup, then PC DOS 2000 will also boot fine after install, even in the case it was not previously installed. Apparently it is another issue to be fixed, but for now the workaround is to manually copy the files IBMBIO.COM and IBMDOS.COM from the install CD to C:\ before running PC DOS 2000 Setup, if the said files were not already located in C:\.

**Comment by rderooy** [comment]
@Wengier Sorry about the MS-DOS 6 red-herring. Your right, I could not boot the image from older DOSBox-X versions either, so somehow the image had gotten corrupted. Recreating it, it worked fine.

As you mentioned. This causes the install work first time.
IMGMAKE hdd.img -t hd -size 2048
IMGMOUNT C hdd.img
IMGMOUNT D PC-DOS_2000.iso -t iso
D:
COPY DOSFILES\IBMBIO.COM C:\
COPY DOSFILES\IBMDOS.COM C:\
SETUP

p.s.
Before install, running:
CONFIG -SET CPU APMBIOS=FALSE
Does nothing. You need to set it in the config file for it to actually work.

I will close this issue for now. Do you want me to open another issue for having to copy IBMBIO/IBMDOS before?

**Comment by Wengier** [comment]
@rderooy You can open another issue for that of course.

**Comment by RNMB15** [comment]
There are other issues with problems with the APM BIOS from DOSBOX.

https://github.com/joncampbell123/dosbox-x/issues/78
https://github.com/joncampbell123/dosbox-x/issues/56
https://github.com/joncampbell123/dosbox-x/issues/83
https://github.com/joncampbell123/dosbox-x/issues/87
