### ISSUE TITLE
Cannot set file attributes on IMGMOUNT

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1469]
**Describe the bug**
As described in https://github.com/joncampbell123/dosbox-x/issues/1468

I understand there are challenges with running ATTRIB on a host filesystem (using MOUNT), but that should not prevent it from working with IMGMOUNT.

**To Reproduce**
IMGMAKE hdd.img -t hd -size 2048
IMGMOUNT C hdd.img
IMGMOUNT D PC-DOS_2000.iso -t iso
C:
ECHO > test
D:\DOSFILES\ATTRIB.EXE test
D:\DOSFILES\ATTRIB.EXE -A test

**Expected behavior**
Attrib to work with IMGMOUNT
Also the stub attrib that dosbox provides should be replaced with one that works, at least for the IMGMOUNT case.

**Environment (please complete the following information):**
DOSBox 0.83.1-git (pulled today)

**Additional context**
LOG Messages from running attrib on test
LOG:  718872892 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  718872899 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  718872906 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  718872913 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  718872938 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  718873077 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B700
LOG:  718889848 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B707

Log Messages from running attrib -A on test
LOG:  991214875 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  991214882 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  991214889 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  991214896 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  991214921 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG:  991215060 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B700
LOG:  991226307 ERROR MISC:DOS:Set File Attributes for C:\TEST not supported
LOG:  991229687 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B707

**Comment by Wengier** [comment]
@joncampbell123 and @rderooy I have made a patch for DOSBox-X that implements the ATTRIB command and the SetFileAttr function, which work on *both* local drives (via MOUNT) and FAT drives (via IMGMOUNT), although the SetFileAttr function on local drives will currently only work in Windows builds (whereas SetFileAttr function on FAT drives should work in all builds). For example:

"ATTRIB +R TEST" will enable the read-only attribute for the file (or directory) named "TEST".
"ATTRIB -S -H *.EXE" will clear system and hidden attributes for all files with the EXE extension.
"ATTRIB" (without parameters) will show the attributes for all files and directories in the current directory.

The diff file for the latest commit df6366f is available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-df6366f-patch.diff

A pre-compiled Windows 64-bit binary is also available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by rderooy** [comment]
@Wengier thanks! I will give it a go in the next day or so.

**Comment by joncampbell123** [comment]
Patch looks good so far @Wengier, I may later adapt it to at least support the R bit on Linux as the absence of the 'w' file mode.

**Comment by joncampbell123** [comment]
Patch merged, and I added support code for Linux and Unix systems to map the Readonly attribute to the local filesystem.
