### ISSUE TITLE
SuperCalc Flashing Text.

### ISSUE THREAD

**Issue by ThePillenwerfer** [joncampbell123/dosbox-x#1473]
I first tried dosbox on Windows Vista and every program I tested worked except for SuperCalc 3 or 4.  The cell labels should be black on yellow but on dosbos-x they show as flashing black on brown.

Correct display.
![Screenshot at 2020-04-12 12-11-10](https://user-images.githubusercontent.com/42588539/79067627-aad2f480-7cb8-11ea-90a5-993d3cb137db.png)

dosbox-x video capture
https://drive.google.com/open?id=10aJJ9VLLU1DGsKlwD4L6SWuyZ4OyJDSD

When I switched to Linux Mint I managed to build it and found the same.

I now use Debian but have been unable to build dosbox-x on that.  However the latest Windows version runs under Wine and has the same outcome.

Other versions of dosbox don't exhibit this behaviour (meaning it isn't a great problem to me) but dosemu simply crashes after loading the program, which may provide a clue.  

I am reporting this as it may effect other software.

**Comment by joncampbell123** [comment]
It means somewhere along the bit to disable the blink attribute was not set, either because INT 10h screwed up or the program didn't program the VGA as it should or some VGA state error (this is VGA, right?)

**Comment by ThePillenwerfer** [comment]
Thanks for the reply.

Yes, it was set to VGA.  Adding

```
[dosbox]
machine=cga
```
to the .conf file fixed it.  

EGA still flashes and the background colour is slightly off but closer to what it should be than VGA.

Capture: [](https://drive.google.com/open?id=1RwgaWzvC9AjOn77hwPSjat9CQCa1HkqX)

**Comment by joncampbell123** [comment]
I noticed that SuperCalc3 and SuperCalc4 (the versions you mentioned) have copyright dates from 1983 to 1986, which suggests that it was written for CGA or MDA hardware and probably writes directly to port 3D8h to set mode and attribute settings.

On EGA/VGA, port 3D8h does nothing.

If you are using a version of DOSBox-X with a debugger, can you use BPINT 10 10 03 to see if it calls INT 10h AX=1003?

http://www.ctyme.com/intr/rb-0117.htm

**Comment by ThePillenwerfer** [comment]
I'll try to build a debug-enabled version of dosbox-x later and report back.

SuperCalc worked fine on VGA monitors when run in a DOS window on Windows 98se or via NTVDM on XP.

**Comment by ThePillenwerfer** [comment]
First I ran build-debug-no-avcodec (I already knew it wouldn't build with the AV codec) and got an error:—

```
joe@Sony:~/Desktop/dosbox-x-dosbox-x-v0.83.0$ ./build-debug-no-avcodec
./autogen.sh: 5: ./autogen.sh: function: not found
./autogen.sh: 6: [: -eq: unexpected operator
./autogen.sh: 9: ./autogen.sh: Syntax error: "}" unexpected
```
I therefore commented out the ./autogen line and ran:—

```
aclocal
autoheader
automake --include-deps --add-missing --copy 
autoconf
```
manually before running build-debug-no-avcodec again.

I noticed this appear in the terminal window when running loading SuperCalc:—

`LOG:  106949625 ERROR INT10:Function 3000 not supported`

I don't know how to use the debugger but clicking Main > Debugger and entering BPINT 10 10 03 produced this:—
![Screenshot at 2020-05-04 10-13-54](https://user-images.githubusercontent.com/42588539/80952234-46a3dc00-8df1-11ea-8698-9db08b06636a.png)

**Comment by joncampbell123** [comment]
INT 10h AX=3000h: Something to do with IBM 3270 terminals or emulation? http://www.ctyme.com/intr/rb-0241.htm

**Comment by joncampbell123** [comment]
So testing so far with SuperCalc3 v2.10: https://winworldpc.com/download/75c2afcb-86c3-8362-c2b1-11c3a4c2a90f

    machine=cga                       OK
    machine=pcjr                      OK
    machine=tandy                     OK
    machine=mda                       OK
    machine=hercules                  OK

**Comment by joncampbell123** [comment]
So, yes, the problem is exactly as I thought. A program that pre-dates EGA is writing port 3D8h/3D9h to change the video mode to a text mode that selects intensity instead of blinking.

![sc3ega_3d8](https://user-images.githubusercontent.com/6245486/80993151-7225c700-8def-11ea-858a-039c0e898546.png)

**Comment by joncampbell123** [comment]
![Firefox_Screenshot_2020-05-04T18-00-19 533Z](https://user-images.githubusercontent.com/6245486/80997631-75708100-8df6-11ea-93e8-7cd45049eb59.png)

**Comment by joncampbell123** [comment]
http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/CGA/IBM/IBM%20Color%20Graphics%20Monitor%20Adapter%2epdf

**Comment by joncampbell123** [comment]
If what I'm saying about SuperCalc3 is not clear, emulation is correct and the issue occurs because SuperCalc3 is unaware of EGA/VGA hardware.

**Comment by ThePillenwerfer** [comment]
Thanks for your efforts.  It shows that your goal of accurate emulation is being achieved better than in other dosboxes.

**Comment by joncampbell123** [comment]
SuperCalc4 seems to have the same issue: It still expects to disable blink via port 3D8h even when machine=ega

**Comment by joncampbell123** [comment]
I'm going to test SuperCalc5 just for completeness. Surely with a copyright date of 1991 they would have corrected that by then.

**Comment by joncampbell123** [comment]
Yup, SuperCalc5 is EGA/VGA aware.

**Comment by joncampbell123** [comment]
One more interesting thing I found.

The write to 3DAh caught my eye because normally you read from that port, but on the PCjr, 3DAh is writable.

You can read it to reset a toggle, and then write an index then value to it to set additional parameters.

   1178377 DEBUG MISC:IO write slow path port=3da data=2 iolen=1: device matches=0
   1178379 DEBUG MISC:IO write slow path port=3da data=3 iolen=1: device matches=0

   1178381 DEBUG MISC:IO write slow path port=3da data=3 iolen=1: device matches=0
   1178383 DEBUG MISC:IO write slow path port=3da data=0 iolen=1: device matches=0

So according to WHATVGA, SuperCalc 3 is setting the PCjr border color to 3 (dark cyan?) and telling the PCjr to disable blink.

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/PCjr/IBM%20PCjr%20graphics%20system%20%28WHATVGA%20v2%2e00%29%20%281995%2d09%2d29%29%2etxt

**Comment by ThePillenwerfer** [comment]
Last night I booted a Pentium 4 with built-in Intel VGA graphics which is connected to a CRT monitor under FreeDOS and that ran both SC3 and SC4 with no blinking.  Perhaps it has some sort of compatibility kludge like other dosboxes.

Until reading your posts yesterday I would have sworn that when I was at college from 1988 to 1990 we ran SuperCalc 3 on 286 machines with EGA monitors.  I am however happy to accept that my memory could well be corrupted after thirty years. 

Personally I regard the problem as fixed as changing the machine type to cga is a simple matter.

**Comment by sikthehedgehog** [comment]
It's also possible that at some point there was a patch to fix SuperCalc 3 and 4 on EGA/VGA and isn't well documented :P

Also if something ran before that disabled blink and then returned to DOS without reenabling it, that'd probably do it as well (since I don't think that DOS ever attempts to change the video mode?). Especially since honestly blink wasn't all that desirable in practice (compared to having more background colors available).

**Comment by joncampbell123** [comment]
@sikthehedgehog INT 10h reprograms all CRT registers and would likely restore the blink attribute behavior, so that sounds unlikely, but a patch update that adds EGA/VGA support sounds like something a company would do, especially if there is a time gap in years between versions 3 & 4 (late 1980s), and 5 (early 1990s).

**Comment by joncampbell123** [comment]
Another very remote possibility is that perhaps early clone EGA/VGA cards might have been designed to respond to port 3D8h and update the blink attribute state within from it (though accept no other mode bits) even though the official IBM hardware did not.

**Comment by joncampbell123** [comment]
@ThePillenwerfer I am using the copies of SuperCalc from the WinWorldPC site which might differ from the versions you used. Links are in previous posts in this issue.

**Comment by ThePillenwerfer** [comment]
Yes, my version does seem different: it's files are dated 17 June 1986 whereas the WinWorldPC version's are 11 November 1986.  Also my version of SCRIBM.DRV is 12.3kB against 12.5kB.

However, it behaves just the same, ie blinks on dosbox-x, works on stock dosbox (v0.74-3) and dosbox-DAUM, and crashes on DOSEmu.

Have you seen the SuperCalc 4 v1.00 IBM PC.txt file in the WinWorldPC archive which says:─

```
Minimum Requirements: 
256K RAM
PC/MS-DOS 2.0
Two disk drives
Hercules, CGA, EGA video
```

Obviously that could easily be wrong but the paper manual I have confirms it:—
![SC4 Man](https://user-images.githubusercontent.com/42588539/81083157-20af3200-8eec-11ea-8244-b2d2532b1fc9.png)
(I scanned it straight; it's printed crooked.)

**Comment by joncampbell123** [comment]
I can confirm that SuperCalc4 did correctly identify machine=hercules.

DOSBox SVN and other forks may have inherited a bug in INT 10h or VGA emulation that breaks the blink attribute in some cases that DOSBox-X fixed, but I'm not certain.

If the program does support EGA, then perhaps it's detecting EGA using an unknown method that fails in DOSBox-X.

**Comment by joncampbell123** [comment]
Alright... SC3 and SC4 on real hardware (Paradise SVGA in this case) does detect EGA/VGA or at least does turn off blinking.

The error is in DOSBox-X.

**Comment by joncampbell123** [comment]
SC3 doesn't seem to be making any INT 10h calls beyond cursor positioning stuff and a query for the current mode.

I did catch some interesting code though:

- There is code that checks for a video BIOS at C000:0000h (looks for AA55h)
- If found, it reads the INT 10h vector and checks to make sure that (((segment >> 4) + offset) & 0xFF00) >= 0xFE00 (actually it just compares AH >= 0xFE).

The last one makes me think... DOSBox-X still sets INT 10h to a vector somewhere around 0xF000:0xFExx, while on the PVGA-based laptop, INT 10h points somewhere in 0xC000:0xxxx (the VGA BIOS). So what this program is probably trying to do apparently, is detect EGA/VGA not by using the standard call but instead by whether there is a video BIOS and INT 10h points below the system BIOS.

**Comment by joncampbell123** [comment]
Ha!

If I break into the debugger and force AX=C000 at the point it checks the segment, the program then proceeds to check for EGA/VGA normally and it displays correctly for machine=vgaonly.
![vgasc3](https://user-images.githubusercontent.com/6245486/81088517-e32cb380-8eaf-11ea-98cf-9223aa503cba.png)

**Comment by joncampbell123** [comment]
This kind of checking and verification is what I keep older hardware around for. :)

**Comment by joncampbell123** [comment]
I should try this on my IBM PS/2 model 30, since I think that has VGA support embedded in the system BIOS that might fail the check (VGA hardware but nothing at C0000h).

**Comment by ThePillenwerfer** [comment]
I used to run SuperCalc on a PS/2 30 with no problems.  I'm not sure if it was 3 or 4 though.

**Comment by joncampbell123** [comment]
If you can compile the latest code, it should work properly now. Also, the view command appears to render graphs correctly in EGA mode.

**Comment by ThePillenwerfer** [comment]
Done and all is well.

Thank you very much for your efforts.
