### ISSUE TITLE
FOR and LFNFOR commands implemented

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#1474]
I noticed that the FOR command in DOSBox-X currently does not do anything (i.e. dummy). So I decided to implement it for DOSBox-X as in a real DOS system. The syntax for the FOR command is:

FOR %variable IN (set) DO command [command-parameters]

For example:
FOR %I IN (*.TXT) DO ECHO %I
Will list the names of all files with the .TXT extension.

It is possible to use the FOR command in a nested way. For example:
FOR %I IN (1 2 3) DO FOR %J IN (*.COM *.EXE) DO DIR /B "%J"
Will list all files with the .COM or .EXE extensions 3 times.

When used in batch files, %variable needs to be replaced with %%variable as in a real DOS system.

Furthermore, I have added the LFNFOR command to DOSBox-X which will control whether to use long filenames in the FOR command, as in a real MS-DOS 7+ system. For example:

"LFNFOR ON" will enable LFN usage in the FOR command (only if LFN support itself is enabled);
"LFNFOR OFF" will disable LFN usage in the FOR command;
"LFNFOR" (without arguments) will show its current status.

I also fixed the help messages for some commands as well as the handling of file attributes for FindNext on local drives (it already worked on other drives).

The diff file for the latest commit 868c743 is located at:
http://individual.utoronto.ca/wengier/files/dosbox-x-868c743-patch.diff

And a pre-compiled Windows 64-bit binary is available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by Wengier** [comment]
The patch now includes improvements for redirection as mentioned in Issue #1463 and peculiarities with wildcards as mentioned in Issue #1475.

**Comment by Wengier** [comment]
I now added the BREAK and VERIFY commands as in real DOS, as they seem to be missing in DOSBox-X. Also, changing DOSBox-X's internal time is now supported, either by the built-in TIME command or by the INT 21h function.

The diff file for the latest commit 868c743 is still located at:
http://individual.utoronto.ca/wengier/files/dosbox-x-868c743-patch.diff

And a pre-compiled Windows 64-bit binary is available from:
http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by Wengier** [comment]
I noticed that in DOSBox-X the the command "DIR /S" did not work as expected, and "DIR /?" mentioned its /S option as "Displays files in specified directory and all subdirectories (not supported)", so I decided to implement it as in real DOS and added it to the patch. For example, with the new version:

"DIR /S" will display files and directories recursively;
"DIR A* /S /P will display all entries starting with A in the current directory and all its subdirectories, one screen at a time;
"DIR *.EXE /B /S" will list the names of all files with the EXE extension in the current directory and all its subdirectories.

The diff file for the latest commit 868c743 is still located at:
http://individual.utoronto.ca/wengier/files/dosbox-x-868c743-patch.diff

**Comment by Wengier** [comment]
I have found the REN command in DOSBox-X did not work with wildcards (i.e. * or ?) at all - any use of wildcard(s) in this command will trigger the error "This is a simple version of the command, no wildcards allowed!". So I decided to go ahead to make it compatible with wildcards and added to the patch. For example, with the new version:

"REN A.COM B.\*" will rename the file A.COM to B.COM;
"REN \*.BAT \*.CMD" will rename all BAT files to the .CMD extension;
"REN C\*.TXT D??.BAK" will rename all TXT files starting with letter C to the .BAK extension, also change their main file names to 3 letters containing the leading letter D and the second and third letters of their original filenames.

The updated diff file for the latest commit 868c743 is still located at:
http://individual.utoronto.ca/wengier/files/dosbox-x-868c743-patch.diff

**Comment by joncampbell123** [comment]
Applying now.

Is your text editor set to edit in UTF-8? It garbled one of the lines of CHANGELOG.

![image](https://user-images.githubusercontent.com/6245486/79522243-0a5e3680-8010-11ea-8d6e-7f9d7dcfdf26.png)

**Comment by Wengier** [comment]
@joncampbell123 For all source code editing I used Notepad++,  which is set to edit in UTF-8. But for the CHANGELOG file I sometimes used other text editors such as Notepad to edit, which might have caused such issue. To avoid this problem I will remember to use Notepad++ to edit the CHANGELOG file too from now on.
