### ISSUE TITLE
Decrease IDE ATA command logging

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1477]
**Describe the bug**
I did an install of Win98SE (full retail) in DOSBox-X 0.83.1-git and had a HUGE amount of logging going on, both during the install and afterwards when booting. So much so that I wonder how much of a performance effect it has.

Endless streams of messages like these:
LOG: IDE ATA command 30 dh=0xa5 count=0x40 chs=1e/05/26

For now I commented the LOG line out (lines 3387-3388 of src/hardware/ide.cpp), and it seems to perform better.

**To Reproduce**
- Start dosbox-x
IMGMAKE hdd.img -t hd -size 2048
IMGMOUNT C hdd.img
IMGMOUNT D Win98SE.iso -t iso
D:
SETUP /is

Note: /is is to ignore scandisk, otherwise it complains about the Z: drive having an in-correctable error. Install works fine this way, no need to have a boot disk, or boot from the CD (this is with the full retail version).

After the first reboot you can use
IMGMOUNT C hdd.img
IMGMOUNT D Win98SE.iso -t iso
BOOT -L C

You will however end up with a FAT16 drive this way. You can convert the drive afterwards to FAT32, but then you can no longer access the drive content from DOSBox-X itself.

**Expected behavior**
Less logging. The amount of logging going on was so extensive that any other warnings or errors where just lost in the noise.

**Environment (please complete the following information):**
- Fedora 31
- DOSBox-X 0.83.1-git

**Additional context**
dosbox.conf:
[cpu]
cputype=pentium_mmx
core=normal
[fdc, primary]
enable=true
int13fakev86io=true
[ide, primary]
int13fakev86io=true
[ide, secondary]
int13fakev86io=true
cd-rom insertion delay=4000
[render]
scaler=none
aspect=false
[autoexec]
imgmount C hdd.img
imgmount D Win98SE.iso -t iso
boot -L C

After I converted the drive to fat32, I had to adjust [autoexec] as follows:
imgmount 2 hdd.img -fs none
imgmount D Win98SE.iso -t iso
boot -L C

p.s. with this, under System Properties -> Performance, it still complains that "Drive A is using MS-DOS compatibility mode file system."

**Comment by Wengier** [comment]
@rderooy I think you can change LOG_MSG(...) to proper logging type and level in that file, so that such log messages can be enabled or disabled easily.

**Comment by Wengier** [comment]
I have already added the fix for this issue in the patch I posted in Issue #897.

**Comment by rderooy** [comment]
@Wengier thanks once again!
