### ISSUE TITLE
GLSL shader support

### ISSUE THREAD

**Issue by almeath** [joncampbell123/dosbox-x#1478]
**Is your feature request related to a problem? Please describe.**

Shader support in DOSBox-X is currently PC-only due to the requirement to use Direct3D output and the .fx shader format.

**Describe the solution you'd like**

It would be great to have OpenGL-compatible GLSL shader support built into DOSBox-X to improve functionality for macOS and Linux users, and bring the feature into line with the current DOSBox SVN.

**Comment by Wengier** [comment]
It is already supported in the latest code. See Issue #1673.
