### ISSUE TITLE
dosbox to dosbox-x

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#1483]
As mentioned in Issue #1481 by @rderooy and myself, DOSBox-X did not report itself as DOSBox-X in several places. For example, "dosbox -version" and "dosbox -help" still showed its version as "DOSBox version 0.83.1" even though 0.83.1 is the version of DOSBox-X rather than DOSBox (there is apparently no version 0.83.1 for DOSBox). I decided to clean up such strings in the code a bit so that DOSBox-X now reports itself as "DOSBox-X" instead of "DOSBox" to the user. For example, the DOSBox-X configuration GUI will now show the title "DOSBox-X Configuration" instead of "DOSBox Configuration".

Also, I noticed that DOSBox-X still uses the config file named `dosbox.conf` by default, and it would NOT try to load the config file named `dosbox-x.conf` (even though the executable name is `dosbox-x.exe`), so I changed this too. Now after trying to load the config file from the user directory, DOSBox-X will first try to load the config file named `dosbox-x.conf`, and if this file cannot be found, it will then try to load the config file named `dosbox.conf` as before. So both `dosbox-x.conf` and `dosbox.conf` are now recognized at the config file name for DOSBox-X, first `dosbox-x.conf` and then `dosbox.conf`, as we could probably expect.

The diff file for the most recent commit a14533b is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-a14533b-patch.diff

It includes all changes I posted in Issue #897.

A pre-compiled Windows 64-bit binary is also available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by joncampbell123** [comment]
Patch applied. Thanks!

**Comment by ThePillenwerfer** [comment]
Great job.

**Comment by Wengier** [comment]
@joncampbell123 Some additional changes and cleanups:

http://individual.utoronto.ca/wengier/files/dosbox-x-c9d9073-patch.diff

**Comment by joncampbell123** [comment]
There you go.

**Comment by emendelson** [comment]
@Wengier - One more detail: in shell.cpp, line 877, the existing line needs to be two characters shorter, to avoid breaking the border in the welcome screen. Perhaps it could read "For more details, see the README file etc.,"?

**Comment by Wengier** [comment]
@emendelson I already changed that sentence to "For more information read the online guide in the DOSBox-X Wiki" as I mentioned in Issue #1307 three days ago, but that patch has not been applied to the current git yet.

**Comment by emendelson** [comment]
@Wengier - Ah, I missed that! Sorry!
