### ISSUE TITLE
Can a DOSBox-X batch file detect whether SDL1 or SDL2 is active?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1484]
Is it possible for a batch file in DOSBox-X to detect whether the current build uses SDL1 or SDL2? 

I'm asking because I have a project where it might make sense for a user to experiment with an SDL2 build, and I would like autoexec.bat to detect which version is running.

**Comment by Wengier** [comment]
@emendelson You can try this inside DOSBox-X:

``VER | FIND "SDL2" >NUL``
``IF ERRORLEVEL 1 ECHO SDL1 build detected.``
``IF NOT ERRORLEVEL 1 ECHO SDL2 build detected.``

P.S. It is recommended to set the %TEMP% environment variable before using pipes (|).

**Comment by emendelson** [comment]
@Wengier - Thank you! That's perfect. I ought to have thought of it myself but didn't. 

Also, I didn't realize that the %TEMP% variable should be set - is this because piped text can get written to a temporary file?

**Comment by Wengier** [comment]
@emendelson Yes, that is right - piping requires a temporary file to be created (and automatically deleted afterwards) as in a real DOS system. If the %TEMP% variable was not set, then DOSBox-X will try to create a temporary file in the current directory, but if the current directory is not writable then piping will fail with an error message. So it is recommended to set the %TEMP% variable to a writable directory so that piping should always succeed.

**Comment by Wengier** [comment]
@emendelson With the latest patch I posted in Issue #1307, it is possible to use a batch file to detect whether the current build uses SDL1 or SDL2 with only the built-in Z: drive and the CLIP$ device - no temporary file or external tool is needed inside DOSBox-X. For example:

``VER >CLIP$``
``ECHO ,>>CLIP$``
``FIND "SDL2" CLIP$ >NUL``
``IF ERRORLEVEL 1 ECHO SDL1 build detected.``
``IF NOT ERRORLEVEL 1 ECHO SDL2 build detected.``
``ECHO ,>>CLIP$``

The second line works around a bug with the built-in FIND.EXE that it cannot find a string if the line does not have an EOL. The last line clears the text when the operation finishes.

**Comment by Wengier** [comment]
DOSBox-X's built-in FIND command is from FreeDOS, which has the the bug I mentioned above to be worked around. On the other hand, the FIND command from MS-DOS does not have this bug, so if you use MS-DOS's FIND.EXE then the second line (to append an EOL to CLIP$) above is not necessary.
