### ISSUE TITLE
Current code won't build in VS2019

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1486]
Current code won't build in VS2019; an attempt to build SDL or SDL2 for Windows produces this:

C:\Users\Edward\Desktop\Current\dosbox-x-master\src\shell\shell_cmds.cpp(1819,22): error C2120: 'void' illegal with all types
10>C:\Users\Edward\Desktop\Current\dosbox-x-master\src\shell\shell_cmds.cpp(1856,20): error C2120: 'void' illegal with all types
10>C:\Users\Edward\Desktop\Current\dosbox-x-master\src\shell\shell_cmds.cpp(1865,18): error C2120: 'void' illegal with all types

Something seems to have gone wrong with the definition of PAUSED, but I can't guess what it is or how to fix it, other than to rem out the three error-producing lines.

**Comment by Wengier** [comment]
@emendelson I am building the code with VS2015 on Windows and GCC on Linux. Both apparently worked fine. Do not have VS2019 to test though at this time.

**Comment by emendelson** [comment]
Very strange - when I downloaded the code again, it built successfully. Apologies for wasting bandwidth!

**Comment by Allofich** [comment]
@emendelson, I'm curious what version of VS2019 you successfully built with. There has actually been a problem recently with building DOSBox-X with VS2019 16.5 and later.

https://github.com/joncampbell123/dosbox-x/issues/1453

There might be a fix coming, but the latest version is automatically offered for download is 16.5.4, and it still has the issue. I haven't tried any of the "preview" versions.

**Comment by emendelson** [comment]
@Allofich - I'm using 16.4.5. It keeps offering to upgrade to 16.5, but I read https://github.com/joncampbell123/dosbox-x/issues/1453 and knew not to do so. I think I saw somewhere (perhaps in the thread about that issue) that someone at Microsoft was predicting that the fix would come with 16.7, but I could be misremembering that. 

Perhaps the simplest thing to do right now, if it's not possible to install 16.4, is to install VS 2017?

**Comment by Allofich** [comment]
> that someone at Microsoft was predicting that the fix would come with 16.7

Yes, that was me. I'm not completely sure that they were talking about the same issue as #1453 but it sounded similar.

**Comment by Allofich** [comment]
We have a workaround for this now and latest VS2019 should build.
