### ISSUE TITLE
Option to report REAL disk space on local drives

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#1487]
I noticed that DIR (and other commands) in DOSBox-X *always* (incorrectly) reported the free disk space as 256MB on local drives, on both Windows and Linux platforms, even though the actual free disk space is completely different, such as in the case there is already no disk space left. Clearly, this behavior is not always desired. So I added a config option named "get real disk space" to overcome this problem. It is disabled by default, but if it is enabled it will report the REAL disk space on local drives.

In additional to the built-in DIR command, the DIR command from DOS command.com will now be able to display the actual disk space on local drives too. However, since DIR command in MS-DOS 6.x or earlier only supported disk space up to 2GB via the older DOS call (Int 21/ah=36h), only 2GB will be reported to these DOSes if the free disk space is greater than 2GB. However, the true disk space will be reported via the newer DOS call (Int 21/ah=73h), even if the disk is *very* large, so that DIR command from both MS-DOS 7.1+ and 4DOS 8.0 will correctly report the free disk space (e.g. in the 10GB+ range). Coded for and tested in both Windows and Linux platforms to ensure that it works in different platforms.

The diff file for the most recent commit 2782946 is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-2782946-patch.diff

It includes changes I posted in Issue #1307 along with some other code cleanups.

A pre-compiled Windows 64-bit binary is also available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by sikthehedgehog** [comment]
Anecdotally, DIV Games Studio 2 (and probably 1 too) won't install if it thinks there isn't enough hard disk space. 256MB isn't enough for a full install, forcing you to do a minimum install then manually copy over the remaining files (or just outright by-pass the installer and manually copy everything). Incidentally, the installer will report 2GB free at most (probably using the older call).

So yeah, not reporting the real size can be an issue (installers may refuse to install in their attempt to be "helpful", and a lot of software that came on CD is bound to want more than 256MB). On the other hand no idea if there's any software that breaks if free disk space is over 256MB.

**Comment by rderooy** [comment]
I feel that real space reporting should be enabled by default.

And there should be a setting to CAP the reported size to a user definable value, such that maximum size is capped, but NOT if the real available diskspace is less then capped size.

**Comment by sikthehedgehog** [comment]
Maybe 2GB would be a good default cap? (since it matches the limit for the old call and most partitions nowadays will have more than 2GB free)

**Comment by Wengier** [comment]
Thanks for the suggestions! I have updated the patch to make real space reporting enabled by default on local drives (as suggested), so that newer DOS programs can handle the large space (>2GB) will get the true disk space, whereas older DOS programs that can only support up to 2GB will only get 2GB disk space as the maximum size.

On the other hand, you can always use the built-in MOUNT command's existing -freesize option to set a fixed free space to report. But I also added a new config option named "freesizecap" to change the behavior of this option, either CAP mode (default) or FIXED mode. For example:

With freesizecap=true (CAP mode):
``MOUNT C C:\ -freesize 256``
Will report a maximum free disk space of 256MB for C: drive if there is more than 256MB free space available.

And with freesizecap=false (FIXED mode):
``MOUNT C C:\ -freesize 256``
Will always report a free disk space of 256MB for C: drive (as before).

BTW, the usage of the -freesize option is slightly different if the mount type is set to floppy drive. For example, ``MOUNT A A:\ -t floppy -freesize 100`` will report a free disk space of 100KB instead of 100MB, either as the maximum size (CAP mode) or at all times (FIXED mode) depending on the setting of the freesizecap config option.

You can either set the freesizecap config option in dosbox-x.conf, or change it at the runtime with the config -set command (e.g. ``config -set freesizecap=false``). The previous "get real disk space" option was removed.

The diff file for the latest commit 2782946 is still available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-2782946-patch.diff

And a pre-compiled Windows 64-bit binary is also available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

**Comment by Wengier** [comment]
@joncampbell123 I think that is about it for now. Since there are around 6 days until the next month, I will not be adding any new features in the next few days, but only try to help fix bug(s) that may be found or reported. I have been personally testing DOSBox-X almost daily in this month, playing around with various commands and some programs, trying to find and fix bugs that may be found, so the program as a whole should be considered pretty stable in my opinion, when compared with earlier releases. I will continue to see if there are any bugs that may be found in the remaining days of this month, but there will be no new features to be added.

**Comment by joncampbell123** [comment]
I will apply the patch provided.

Can you provide future changes as pull requests, please? It's easier for me to merge and the commit messages from your changes make it into the DOSBox-X branch git log, where you can be properly credited.

**Comment by joncampbell123** [comment]
What is the significance of SP=E224h when emulating INT 21h AH=0?

**Comment by Wengier** [comment]
@joncampbell123 Sure, I will try to use the pull requests feature in the future. Never tried before, but I I think I will make it work.

As for SP=E224h, it fixes the bug that DIR /S from MS-DOS 7.1 may crash hard within DOSBox-X. With this change it works properly in DOSBox-X now.

**Comment by joncampbell123** [comment]
Do you mind if I modify that part to work only if the emulation DOS version is 7.1 or higher?

**Comment by Wengier** [comment]
@joncampbell123 I have not tried with the command with MS-DOS 7.0 COMMAND.COM, but I think it is okay to check if it is at least DOS 7 with that call.

**Comment by joncampbell123** [comment]
Alright, the SP=E224h case will only work if the major version is 7 or higher.
