### ISSUE TITLE
Autogen error.

### ISSUE THREAD

**Issue by Achaean** [joncampbell123/dosbox-x#1488]
Latest version (0.83.0) on a Debian oldstable distro.

```
>./autogen.sh
./autogen.sh: 5: ./autogen.sh: function: not found
./autogen.sh: 6: [: -eq: unexpected operator
./autogen.sh: 9: ./autogen.sh: Syntax error: "}" unexpected
>
```

**Comment by joncampbell123** [comment]
Remove the "function finish {" subroutine from autogen.sh and try again. Also, Debian may be using dash instead of bash.

**Comment by Achaean** [comment]
> Remove the "function finish {" subroutine from autogen.sh and try again.
Correct!!!  :-)
That solved the problem!

> Also, Debian may be using dash instead of bash.
Oh...I wasn't aware of that!
Indeed, according to the wiki "Debian uses Dash as the default non-interactive shell", on recent versions.
