### ISSUE TITLE
Restart by keyboard controller causes an abort

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1489]
**Describe the bug**
I have been playing around with old Windows 3.x versions, and sometimes at the end of installation, or with driver changes they want to reboot the PC and do so apparently using the keyboard controller. However with current -git this causes an Abort and DOSBox-X closes. I did not test this with 0.83.0.

LOG: Restart by keyboard controller requested
terminate called after throwing an instance of 'int'
Aborted

**To Reproduce**
* Run DOSBox 0.83.1-git
* Have some software do a reset using the keyboard controller

**Expected behavior**
reboot instead of an abort

**Environment (please complete the following information):**
- Fedora 31
- DOSBox-X 0.83.1-git

**Comment by joncampbell123** [comment]
The most likely reason is that you are using dynamic core on Linux where C++ exceptions do not work properly. Use normal core.

**Comment by rderooy** [comment]
I can indeed confirm that with setting core=normal it works properly.

LOG: Restart by keyboard controller requested
LOG: Rebooting the system
