### ISSUE TITLE
Windows 95 and S3 emulation: minor screen corruption when entering a DOS box without going fullscreen, while using the generic "S3" driver (SVGA bank switching) in 256-color mode

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#150]
Only with Windows 95: bringing up a DOS box without going fullscreen causes some of the non-accelerated graphics rendering to misrender on screen until you enter fullscreen and exit. It doesn't happen with any other version of Windows.

![tmp2](https://cloud.githubusercontent.com/assets/6245486/12613085/1cb08aaa-c4ac-11e5-90a0-996b3db88359.gif)

**Comment by ghoul8765** [comment]
Do the different versions of the S3 driver show the same result? Particularly the version from the directx6.1 package, I believe it is dated 1998 instead of the PCI driver from 1996 or the ISA driver. And the vbemp driver, although it may be fullscreen only?

Is there also an effect from changing the "graphics acceleration" slider to a lower value?

**Comment by joncampbell123** [comment]
It's a problem only with the driver in Windows 95, with a copyright date of 1995. The Windows 95 OSR2 version (copyright date 1996) doesn't have this problem.

The problem only happens in 256-color mode. 16-bit and 32-bit graphics don't have this problem. The way the graphics get spaced out imply it's some sort of problem with SVGA mode and VGA chained vs Mode-X mapping, as if the DOS VM somehow flips the bit back into chained VGA.

I can confirm that so far I've only tested the "full" performance mode. I am testing the other modes now.

**Comment by joncampbell123** [comment]
BTW, in all versions of Windows 9x/ME the card is identified as PCI, not ISA.

**Comment by joncampbell123** [comment]
Okay, the "most accelerator functions" settings now means the mouse cursor itself becomes distorted in the same way. It looks like 4 pixels apart separated by 12 spaces, which again implies some illegitimate switch between SVGA and chained VGA.

The next step down, means that when the DOS VM comes up, EVERYTHING is misrendered in that same way. And at the "None" setting, everything is subject to this misrendering.

**Comment by joncampbell123** [comment]
I just traced down another reason for graphical glitches in Windows 95 vs OSR2.

The Windows 95 driver appears to use bank switching and 0xA0000-0xAFFFF, while Windows 95 OSR2 and later use the linear framebuffer. That would also explain why the original Windows 95 driver is subject to whether or not VGA chained mode is active.

Also, Windows 95 is referring to the card as simply "S3" while Windows 95 OSR2 refers to the card as "S3 Trio/PCI". If I ask Windows 95 to change the driver to "S3 Trio/PCI" then that eliminates the artifacts.

Prior programming experience with ISA and PCI cards tells me that some later cards (S3 Virge PCI for example) tend to switch off legacy VGA mapping logic when the VESA BIOS switches on SVGA modes, so it's possible that real hardware in SVGA modes ignore the VGA chain bit entirely. I could pop in an old S3 Trio PCI card and see if I'm right.

**Comment by joncampbell123** [comment]
I just confirmed I can get the same artifacts in Windows 95 OSR2 if I select "Change driver" and change "S3 Trio32 PCI" to "S3".

**Comment by ghoul8765** [comment]
Thank you for sharing your findings(!) and the cause of the S3 / DOS box issue. It's a great sign that your emulation is very robust and mirroring issues in real hardware. I will definitely keep in mind, too, that the (early) 9x drivers may have legacy support for hardware.

**Comment by joncampbell123** [comment]
Fixed it.

The DOSBox-X INT 10h handler was setting the "compatible chain 4" flag directly, even though farther down in the function the S3-specific code writes CRTC register 0x31 which contains the same bit anyway. Windows 95's S3 driver expects to trap and virtualize I/O to the CRTC registers and that doesn't work when DOSBox-X directly changes VGA state like that.
