### ISSUE TITLE
Reference config errors

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1500]
**Describe the bug**
A few mistakes in the reference config.

```
[fdc, primary]
#         int13fakev86io: If set, and int13fakeio is set, certain INT 13h commands will
#                           cause floppy emulation to issue fake CPU I/O traps (GPF) in
#                           virtual 8086 mode and a fake IRQ signal. you must enable this option
#                           if you want 32-bit floppy access in Windows 95 to work with DOSBox-X.
```
Note how it mentions setting "int13fakeio", but that is not an option for [fdc, primary] (only valid for [ide, *])

```
[sblaster]
#                                              dma: The DMA number of the soundblaster. Set to -1 to start DOSBox-X with the IRQ unassigned
#                                                     Possible values: 1, 5, 0, 3, 6, 7.
#                                             hdma: The High DMA number of the soundblaster. Set to -1 to start DOSBox-X with the IRQ unassigned
#                                                     Possible values: 1, 5, 0, 3, 6, 7.
```
DMA settings, but then it talks about IRQ...

**Comment by Wengier** [comment]
I agree that the reference config file has issues in the comments like this. It needs some time to do such cleanups, probably in the next a few releases.

**Comment by ThePillenwerfer** [comment]
It also says in the [parallel] section:—
```
#                for printer:
#                  printer still has it's own configuration section above.
```
when there isn't such a thing.

**Comment by rderooy** [comment]
Not a reference config issue, but...
![command_003](https://user-images.githubusercontent.com/17701098/81296840-cab8c680-9072-11ea-9513-6b3b8535b22a.png)

The ```-chs``` option works, but not ```-geometry```

**Comment by rderooy** [comment]
In the reference config.

```# fluid.reverb,roomsize: Fluidsynth reverb room size.```

and 

```fluid.reverb,roomsize = .61```

Note how it uses a comma instead of a period, while all other settings use a period as a seperator.

**Comment by Wengier** [comment]
I have already fixed most issues mentioned above for the config reference file in my pull request #1529, including the addition of the [printer] section. But note that "int13fakev86io" (instead of "int13fakeio") is accepted in [fdc, primary] section, so this one is not really an issue.

**Comment by rderooy** [comment]
@Wengier if the "int13fakev86io" is a valid option for [fdc, primary], it should probably be mentioned in the reference config.

Also the screenshot I posted of imgmake is another issue where the "-geometry" text in the help simply needs to be changed to "-chs".

**Comment by Wengier** [comment]
@rderooy Done for the "-geometry" to "-chs" change.

The option "int13fakev86io" is already mentioned there in the reference config, so there is no need to change anything.

**Comment by rderooy** [comment]
@Wengier 

Sorry, I meant to say that the text in [fdc, primary] refers to "int13fakeio" which is not a valid option for [fdc, *], but only for [ide, *]. Undoubtedly the text was just copied from the ide section.

It currently reads in the [fdc, primary] section:
```
#         int13fakev86io: If set, and int13fakeio is set, certain INT 13h commands will
#                           cause floppy emulation to issue fake CPU I/O traps (GPF) in
#                           virtual 8086 mode and a fake IRQ signal. you must enable this option
#                           if you want 32-bit floppy access in Windows 95 to work with DOSBox-X.
```

While I think this should be changed to:
```
#         int13fakev86io: If set, certain INT 13h commands will
#                           cause floppy emulation to issue fake CPU I/O traps (GPF) in
#                           virtual 8086 mode and a fake IRQ signal. you must enable this option
#                           if you want 32-bit floppy access in Windows 95 to work with DOSBox-X.
```

**Comment by Wengier** [comment]
@rderooy Done. I think I have already fixed everything mentioned so far in this thread.

**Comment by rderooy** [comment]
@joncampbell123 with commit https://github.com/joncampbell123/dosbox-x/commit/f9091eb294b3de4fb8b2a9f36613c8b8f0c51d17

You undid one of the fixes from @Wengier where IRQ was changed to DMA has now been changed back to IRQ.
