### ISSUE TITLE
"DIR" bug

### ISSUE THREAD

**Issue by sfubuki5** [joncampbell123/dosbox-x#1505]
**Describe the bug**
when using "dir" command , the program it self will crash.

**Expected behavior**
I'm not that sure how this glitch happened

**Screenshots**
![dsb-xbug](https://user-images.githubusercontent.com/62366679/80898370-257db580-8d35-11ea-969d-2f8f198d03e3.png)
(sorry my system language is in Chinese)

**Environment:**
 - Operating system: Windows 8.1 
 - Version 0.83.1
 - dosbox.conf:

[dosbox]
machine=vga
memsize=364

[cpu]
core=dynamic
cycles=max

[log]
logfile=/log/normal.txt

[autoexec]
@ echo off
mount c /dos
c:
autoexec
---------End of dosbox.conf----------

**Additional context**
This bug won't work on Z: drive

**Comment by Wengier** [comment]
I see you are using "mount c /dos" in Windows. Have you tred the following Instead:

MOUNT C C:\DOS

**Comment by sfubuki5** [comment]
> I see that you are using "mount c /dos" in Windows. Have you tried the following instead:
> 
> MOUNT C C:\DOS

Thx, but I usually run this on a usb drive. also, there's no problem running dos (including PC-98) applications from a mounted folder or a virtual hard disk.

**Comment by Wengier** [comment]
I have opened pull request #1508, which supports mounting a directory like "/dos" instead of "C:\DOS\dir" in Windows.

**Comment by sfubuki5** [comment]
> I have opened pull request #1508 (now merged), which supports mounting a directory like "/dos" instead of "C:\DOS" in Windows (DIR should work fine then).

Thank a lot!

**Comment by joncampbell123** [comment]
What's funny is that since about Windows 7, the filesystem API accepts either \ or / in paths where Windows XP and earlier only accepted the backslash.

**Comment by joncampbell123** [comment]
@Wengier Do you consider this fixed? This issue should be closed if so.

**Comment by Wengier** [comment]
@joncampbell123 Yes, this was already fully fixed early last month.

**Comment by Wengier** [comment]
@joncampbell123 In addition, the following issues can be closed too:

#534
#1227
#1230
#1307
#1366
