### ISSUE TITLE
How to use a real PC speaker?

### ISSUE THREAD

**Issue by sfubuki5** [joncampbell123/dosbox-x#1506]
Hi, I want's to know how to use a real PC speaker to instead the emulated PC speaker

**Comment by joncampbell123** [comment]
What do you mean?

Do you want to write code to use the PC speaker on real hardware?

IBM PC or PC-98?

**Comment by joncampbell123** [comment]
Assuming that is the case, this DOSLIB source code prove an excellent reference for you on how to program the PC speaker and the 8254 timer chip behind it (both IBM PC/XT/AT and PC-98):

https://github.com/joncampbell123/doslib/tree/master/hw/8254

**Comment by sfubuki5** [comment]
> What do you mean?
> 
> Do you want to write code to use the PC speaker on real hardware?
> 
> IBM PC or PC-98?

oh,thanks for that program guide, maybe I will use it some day ;)
but what l mean is that how to make the singal of PC speaker from the DOS game in the dosbox-x directly go to the speaker driver (but probably no sense, because after Windows 7, beep.sys is normally use the soundcard, except replace it with the beep.sys from older Windows like Windows XP)

**Comment by joncampbell123** [comment]
DOSBox-X (or any other DOSBox) does not have that option.

Even if support for beep.sys is added, it will probably not support anything beyond simple beeps.

Emulation is written to be as accurate as possible and should be very close to real hardware behavior (as far as I can make it).

**Comment by sfubuki5** [comment]
> DOSBox-X (or any other DOSBox) does not have that option.
> 
> Even if support for beep.sys is added, it will probably not support anything beyond simple beeps.
> 
> Emulation is written to be as accurate as possible and should be very close to real hardware behavior (as far as I can make it).

Oh, that's a pity, thanks a lot!
