### ISSUE TITLE
localDrive::GetFileAttr is not converting guest filename code page to host on Win32

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#1515]
I saw that on Win32, localDrive::GetFileAttr is directly using the guest filename to query the file's native attributes using GetFileAttributes() without doing guest to host filename code page conversion.

In src/dos/drive_local.cpp:

```
#if defined (WIN32)
	Bitu attribs = GetFileAttributes(newname);
	if (attribs == INVALID_FILE_ATTRIBUTES)
		{
		DOS_SetError((Bit16u)GetLastError());
		return false;
		}
	*attr = attribs&0x3f;
	return true;
#else
    // guest to host code page translation

```

This may make ATTRIB command fail to get attributes for files with Japanese filenames using "drive_local" filesystem under PC-98 mode.

![image](https://user-images.githubusercontent.com/37106774/81140952-b48d0680-8f9d-11ea-86b9-00b9f875beae.png)

**Comment by yksoft1** [comment]
BTW does anyone tested the new LFN features under PC-98 mode at all?

**Comment by joncampbell123** [comment]
@yksoft1 Those are brand new and not fully tested yet on my end.
@Wengier The LFN updates are your work, correct? For the WIN32 case, use the filename conversion code to convert from guest (in this case Shift-JIS) to UTF-16 (wchar_t) for the Windows API. You'll have to change GetFileAttributes to GetFileAttributesW to pass the widechar string properly. Do you need assistance on how to do that?

**Comment by joncampbell123** [comment]
@Wengier I'll get around to updating guest to host unicode conversion for get/set file attributes on Windows.

**Comment by Wengier** [comment]
@joncampbell123 I will make a pull request very soon. You can check that.

**Comment by Wengier** [comment]
@joncampbell123 I have submitted my pull request (#1518). It improved Shift-JS support in PC-98 mode (GetFileAttr, SetFileAttr, LFN DIR), as well as adding the -set command-line option to change config setting when starting DOSBox-X.

**Comment by yksoft1** [comment]
`    // TODO: offer a config.h option to opt out of Windows widechar functions
`

I think it's necessary at least for non-VS2019 builds as someone might try to run them under Windows platforms without widechar support (like Windows 9x and HX-DOS extender).

**Comment by Wengier** [comment]
@yksoft1 In any case, with the latest code the LFN features should alreadylyalready work normally in the PC-98 mode. Thanks for bring us attention about this.

**Comment by yksoft1** [comment]
Closed the issues now as I can confirm the GetFileAttr/SetFileAttr of drive_local is now wchar_t aware on Win32.
