### ISSUE TITLE
Win95 Setup Error SU99405

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1516]
**Describe the bug**
When running Windows 95 RTM (Original release or OSR0), or Win95 OSR1 setup.exe in the integrated DOS that DOSBox-X provides, at the end of the 1st phase (before the first reboot) the installation will fail with an Error SU99405, after which setup will exit back to DOS.
![krnl386_002](https://user-images.githubusercontent.com/17701098/81180777-c83f6980-8fab-11ea-9307-b047b192de6a.png)

This does not happen with Win95 OSR2 or later, which are able to successfully install this way.

In the LOG the following message stands out:
```LOG:  237108758 ERROR DOSMISC:DOS:IOCTL Call E0 unhandled```

**To Reproduce**
imgmake hdd.img -t hd_520
imgmount C hdd.img
imgmount D Win95.iso -t iso
XCOPY D:\WIN95 C:\WIN95 /I /E
C:
CD WIN95
SETUP /IS

**Expected behavior**
Installation to complete, like it does with OSR2 or later.

**Environment (please complete the following information):**
- Fedora 32
- DOSBox-X 0.82.3-git

[sdl]
autolock=true

[dosbox]
name=Windows 95
memsize=32

[cpu]
cputype=pentium_mmx
core=normal

[dos]

[ne2000]
ne2000=true
nicirq=10
realnic=1

[midi]
mididevice=fluidsynth
fluid.driver=pulseaudio
fluid.soundfont=/usr/share/soundfonts/default.sf2

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none
aspect=false

**Comment by rderooy** [comment]
I'm not sure what happened, it was working like above, but suddenly I am getting filesystem corruption (consistently) instead. As noted here https://github.com/joncampbell123/dosbox-x/issues/1517

**Comment by rderooy** [comment]
Just to confirm this error occurs, as long as your drive size is not between 256MB and 535MB, because then you run into issue #1517 before you can get far enough.

**Comment by joncampbell123** [comment]
I can confirm a 800MB disk image works fine.

**Comment by Wengier** [comment]
This issue is already fixed in the latest code (i.e. setting file attributes of WINBOOT.INI).

**Comment by rderooy** [comment]
I can confirm that I don't get this error any longer! Thanks guys!
