### ISSUE TITLE
Fluidsynth not working

### ISSUE THREAD

**Issue by maximus105** [joncampbell123/dosbox-x#1521]
Fluidsynth not working with the following options:
mididevice = synth
midiconfig = Fluidsynth.sf2
The sound of MIDI synthesis is always heard the same (not from file .sf2).
File Fluidsynth.sf2 is located in the same folder as DOSBox-X.
Аt the same settings, in the DOSBox SVN-Daum, it everything is working.

**Comment by rderooy** [comment]
Can you post your DOSBox-X LOG? I'm assuming your on Linux?

There has been a large update to the fluidsynth support in DOSBox-X just a few days ago. It should now be equivalent to that of DOSBox ECE. But it requires that you build it yourself for now.

**Comment by maximus105** [comment]
> Can you post your DOSBox-X LOG? I'm assuming your on Linux?
> 
> There has been a large update to the fluidsynth support in DOSBox-X just a few days ago. It should now be equivalent to that of DOSBox ECE. But it requires that you build it yourself for now.

No. I'm on Windows 10 x64. How to get a log file?

**Comment by Wengier** [comment]
@maximus105 Build the latest code and use "mididevice = fluidsynth" instead of "mididevice = synth", along with required FluidSynth settings. Then it should be equivalent to that of DOSBox ECE, as mentioned by @rderooy.

**Comment by Wengier** [comment]
Also, if you are using Windows, please make sure FluidSynth support is actually enabled, or it will fallback to the default MIDI device so that FluidSynth support is not actually in function.

**Comment by rderooy** [comment]
If your on Windows, start DOSBox-X from the command-line with the "-console" parameter to see the log.

**Comment by maximus105** [comment]
> If your on Windows, start DOSBox-X from the command-line with the "-console" parameter to see the log.
When DOSBox-X started with the "-console" option, the following was displayed:
LOG: MIDI: win32 selected Microsoft GS Wavetable Synth
How to switch MIDI to Fluidsynth?

**Comment by rderooy** [comment]
Assuming FluidSynth is running, this should do the trick:
```
[midi]
mididevice=fluidsynth
fluid.soundfont=c:\path\to\soundfont.sf2
```

**Comment by maximus105** [comment]
> Assuming FluidSynth is running, this should do the trick:
> 
> ```
> [midi]
> mididevice=fluidsynth
> fluid.soundfont=c:\path\to\soundfont.sf2
> ```

With these settings, the following is displayed:
LOG: "fluidsynth" is not a valid value for variable: mididevice.
But the Fluidsynth does not work.

**Comment by Wengier** [comment]
> > Assuming FluidSynth is running, this should do the trick:
> > ```
> > [midi]
> > mididevice=fluidsynth
> > fluid.soundfont=c:\path\to\soundfont.sf2
> > ```
> 
> With these settings, the following is displayed:
> LOG: "fluidsynth" is not a valid value for variable: mididevice.
> But the Fluidsynth does not work.

You are either not using the latest code, or FluidSynth support is not actually enabled in the build. As I mentioned earlier, you need to use the latest code and make sure FluidSynth support is actually enabled in the build.

**Comment by rderooy** [comment]
Sorry, I assumed you had compiled the latest code. It should work like that once there is a new binary windows release. @Wengier sometimes does additional compilations for Windows, but I have not seen any the last days.

**Comment by Allofich** [comment]
Here's a build with the latest code.
[dosbox-x-windows-9c303aa.zip](https://github.com/joncampbell123/dosbox-x/files/4600485/dosbox-x-windows-9c303aa.zip)

**Comment by maximus105** [comment]
> Here's a build with the latest code.
> [dosbox-x-windows-9c303aa.zip](https://github.com/joncampbell123/dosbox-x/files/4600485/dosbox-x-windows-9c303aa.zip)

I downloaded DOSBox-X 0.83.2
The message still appears:
LOG: "fluidsynth" is not a valid value for variable: mididevice.
Fluidsynth still doesn't work.

**Comment by rderooy** [comment]
I just tried it with the binary that @Allofich provided, and can confirm that it does not work. It seems it was build without FluidSynth support, probably because the FluidSynth headers were not installed or found during build time.

I have confirmed it works on Linux, by building it myself. But I don't have a windows build environment, so cannot test it there.

**Comment by Allofich** [comment]
Ah, sorry, I haven't used FluidSynth before and didn't notice that support for it had to be configured.

**Comment by Wengier** [comment]
So I have uploaded a DOSBox-X Windows 64-bit binary with the latest code and FluidSynth support, built with MinGW x64 (along with required DLLs):

http://individual.utoronto.ca/wengier/files/dosbox-x-mingw64.zip

Make sure the sound font file (e.g. FluidR3_GM.sf2) as specified in dosbox-x.conf exists.

Turns out it is easier to build a FluidSynth-enabled Windows binary with MinGW than Visual Studio.

@rderooy All my previously-uploaded DOSBox-X Windows binaries were built without FluidSynth support.

**Comment by maximus105** [comment]
I downloaded DOSBox-X 0.83.2
The message still appears:
LOG: "fluidsynth" is not a valid value for variable: mididevice.
Fluidsynth still doesn't work.

**Comment by joncampbell123** [comment]
Mingw x64? Windows builds do not have Fluidsynth, since Windows provides it's own MIDI synth.

**Comment by maximus105** [comment]
I downloaded dosbox-x-windows-20200531-220809-windows.zip

**Comment by rderooy** [comment]
@joncampbell123 FluidSynth support is not exclusive to Linux. It should also work on Windows as long as the necessary headers where present during build time. @Wengier was able to do a windows mingw build last month with FluidSynth support.

In any case, I just checked the latest mingw-win64 build, and indeed FluidSynth support is missing.

**Comment by rderooy** [comment]
I just checked the Linux RPM file, and it is also lacking FluidSynth support for the same reason.

dosbox-x.spec.in needs to be updated with additional "BuildRequires:"

fluidsynth-devel
and at the same time also libpcap-devel such that ne2000 support is also enabled on Linux in the provided builds.

**Comment by rderooy** [comment]
For dosbox-x.spec.in perhaps also add "fluid-soundfont-gm" to the "Requires:" list such that there is a suitable soundfont installed by default. I don't think you will need to add "fluidsynth" to the "Requires:" list, as the RPM build process will do a "ldd" on the binary after the build, and include the necessary libs automatically

**Comment by Wengier** [comment]
@maximus105 You can download the latest Windows binary with FluidSynth support (built with MinGW 64-bit) from:

http://individual.utoronto.ca/wengier/files/dosbox-x-mingw64.zip

(Same link as above, but updated to the latest code)

Once again, make sure the sound font file (e.g. FluidR3_GM.sf2) as specified in dosbox-x.conf exists.

**Comment by Wengier** [comment]
FluidSynth will be enabled for Visual Studio builds by default.

**Comment by maximus105** [comment]
Is it possible in future release builds of MinGW x86 & MinGW x64 to support fluidsynth? Or will there be fluidsynth support only in Visual Studio builds?

**Comment by Wengier** [comment]
@maximus105 There are two ways to enable FluidSynth support for MinGW builds, either by configuring them with system-installed FluidSynth library or using the built-in FluidSynth code. FluidSynth support may be enabled for the MinGW release builds in the future, but it now first becomes available for Visual Studio builds.

**Comment by Wengier** [comment]
@maximus105 I have already enabled the built-in FluidSynth library for MinGW builds (when no external FluidSynth available), similar to the Visual Studio builds. Since it will use the built-in source code, no external DLL is needed.

**Comment by maximus105** [comment]
@Wengier Thanks!

**Comment by Wengier** [comment]
@maximus105 Official MinGW builds for DOSBox-X 0.83.7 are now available both separately and from the Windows installer. Please check it out.
