### ISSUE TITLE
Linux Dependencies Required to USE dosbox-x.

### ISSUE THREAD

**Issue by ThePillenwerfer** [joncampbell123/dosbox-x#1526]
**Is your feature request related to a problem? Please describe.**
I don't know what additional Linux packages dosbox-x requires to use, as opposed to those needed to build it.

**Describe the solution you'd like**
A list of package dependencies.

**Describe alternatives you've considered**
Looked at available documentation.  I have found a list of packages required by stock dosbox but don't know if they are the same as those needed by dosbox-x.

**Additional context**
I recently built dosbox-x on one machine and have successfully run the resulting binary on a different one that has no build tools installed and has never run any version of dosbox. I’m wondering if any dependencies were already satisfied by chance or if other things are needed for certain functions and I’m yet to discover their omission.  This information would also assist in the putting together of a .deb package.

**Comment by rderooy** [comment]
It obviously depends on what was build in. e.g. if the libpcap headers were not present during build time then libpcap.so.1 would not be needed.

I don't know about building .deb files, but for creating a rpm it automatically runs ldd to include the needed dependencies.

$ ldd dosbox-x
	linux-vdso.so.1 (0x00007ffdd2784000)
	libasound.so.2 => /lib64/libasound.so.2 (0x00007f7ee3ad1000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7ee3aca000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7ee3aa8000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7ee3962000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f7ee381b000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f7ee3806000)
	libvga.so.1 => /lib64/libvga.so.1 (0x00007f7ee3774000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f7ee3745000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f7ee372b000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f7ee36f4000)
	libpcap.so.1 => /lib64/libpcap.so.1 (0x00007f7ee36a5000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f7ee3698000)
	libxkbfile.so.1 => /lib64/libxkbfile.so.1 (0x00007f7ee366c000)
	libfluidsynth.so.1 => /lib64/libfluidsynth.so.1 (0x00007f7ee35a5000)
	libavcodec.so.58 => /lib64/libavcodec.so.58 (0x00007f7ee2224000)
	libavformat.so.58 => /lib64/libavformat.so.58 (0x00007f7ee1fe2000)
	libavutil.so.56 => /lib64/libavutil.so.56 (0x00007f7ee1ed8000)
	libswscale.so.5 => /lib64/libswscale.so.5 (0x00007f7ee1e4d000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f7ee1dc3000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7ee1bd3000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7ee1bb8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7ee19ee000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7ee19e3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7ee3bf6000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f7ee19b7000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f7ee19a8000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f7ee187d000)
	libjack.so.0 => /lib64/libjack.so.0 (0x00007f7ee182b000)
	libpulse-simple.so.0 => /lib64/libpulse-simple.so.0 (0x00007f7ee1824000)
	libsndfile.so.1 => /lib64/libsndfile.so.1 (0x00007f7ee17af000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f7ee1758000)
	libreadline.so.8 => /lib64/libreadline.so.8 (0x00007f7ee1700000)
	libswresample.so.3 => /lib64/libswresample.so.3 (0x00007f7ee16e1000)
	libvpx.so.6 => /lib64/libvpx.so.6 (0x00007f7ee13e1000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f7ee13b7000)
	libdav1d.so.3 => /lib64/libdav1d.so.3 (0x00007f7ee1297000)
	libopencore-amrwb.so.0 => /lib64/libopencore-amrwb.so.0 (0x00007f7ee1281000)
	librsvg-2.so.2 => /lib64/librsvg-2.so.2 (0x00007f7ee09a9000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f7ee0950000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f7ee0828000)
	libzvbi.so.0 => /lib64/libzvbi.so.0 (0x00007f7ee0796000)
	libaom.so.0 => /lib64/libaom.so.0 (0x00007f7ee02e7000)
	libgsm.so.1 => /lib64/libgsm.so.1 (0x00007f7ee02d8000)
	libmp3lame.so.0 => /lib64/libmp3lame.so.0 (0x00007f7ee025d000)
	libopencore-amrnb.so.0 => /lib64/libopencore-amrnb.so.0 (0x00007f7ee0231000)
	libopenjp2.so.7 => /lib64/libopenjp2.so.7 (0x00007f7ee01dd000)
	libopus.so.0 => /lib64/libopus.so.0 (0x00007f7ee017c000)
	libspeex.so.1 => /lib64/libspeex.so.1 (0x00007f7ee015e000)
	libtheoraenc.so.1 => /lib64/libtheoraenc.so.1 (0x00007f7ee0125000)
	libtheoradec.so.1 => /lib64/libtheoradec.so.1 (0x00007f7ee0109000)
	libvo-amrwbenc.so.0 => /lib64/libvo-amrwbenc.so.0 (0x00007f7ee00ed000)
	libvorbis.so.0 => /lib64/libvorbis.so.0 (0x00007f7ee00bd000)
	libvorbisenc.so.2 => /lib64/libvorbisenc.so.2 (0x00007f7ee0012000)
	libx264.so.159 => /lib64/libx264.so.159 (0x00007f7edfd4f000)
	libx265.so.188 => /lib64/libx265.so.188 (0x00007f7edf8bc000)
	libxvidcore.so.4 => /lib64/libxvidcore.so.4 (0x00007f7edf7ab000)
	libva.so.2 => /lib64/libva.so.2 (0x00007f7edf780000)
	libmfx.so.1 => /lib64/libmfx.so.1 (0x00007f7edf772000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f7edf75f000)
	libbluray.so.2 => /lib64/libbluray.so.2 (0x00007f7edf70f000)
	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f7edf5ee000)
	libgnutls.so.30 => /lib64/libgnutls.so.30 (0x00007f7edf406000)
	libsrt.so.1 => /lib64/libsrt.so.1 (0x00007f7edf364000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007f7edf2f2000)
	libva-drm.so.2 => /lib64/libva-drm.so.2 (0x00007f7edf2ed000)
	libvdpau.so.1 => /lib64/libvdpau.so.1 (0x00007f7edf2e7000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f7edf2d3000)
	libOpenCL.so.1 => /lib64/libOpenCL.so.1 (0x00007f7edf2af000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f7edf27b000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f7edf1c2000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f7edf1bc000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f7edf143000)
	libpulse.so.0 => /lib64/libpulse.so.0 (0x00007f7edf0eb000)
	libpulsecommon-13.99.so => /usr/lib64/pulseaudio/libpulsecommon-13.99.so (0x00007f7edf064000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f7edf05f000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007f7edf041000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007f7edf036000)
	libXtst.so.6 => /lib64/libXtst.so.6 (0x00007f7edf02d000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f7edef74000)
	libasyncns.so.0 => /lib64/libasyncns.so.0 (0x00007f7edef6c000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f7edef65000)
	libFLAC.so.8 => /lib64/libFLAC.so.8 (0x00007f7edef08000)
	libogg.so.0 => /lib64/libogg.so.0 (0x00007f7edeefd000)
	libsoxr.so.0 => /lib64/libsoxr.so.0 (0x00007f7edee91000)
	libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007f7edee83000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f7edee58000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f7edec74000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f7edeb04000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f7edeaf2000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f7edead9000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f7edea88000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f7ede9a6000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f7ede95b000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f7ede899000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f7ede88e000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f7ede7e2000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f7ede7db000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f7ede7cb000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f7ede7bd000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f7ede799000)
	libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007f7ede667000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f7ede645000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f7ede4c0000)
	libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007f7ede4aa000)
	libnettle.so.7 => /lib64/libnettle.so.7 (0x00007f7ede46d000)
	libhogweed.so.5 => /lib64/libhogweed.so.5 (0x00007f7ede43b000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007f7ede3a2000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f7ede0b5000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f7ede05e000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f7ede055000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f7ede043000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f7ede020000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f7ede006000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f7eddfc4000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f7eddfbe000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007f7eddf5e000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f7eddf2f000)
	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007f7eddf10000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007f7eddf04000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f7eddee0000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f7eddeb1000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f7edddc5000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f7edddac000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f7eddda5000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f7eddd93000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f7eddd8c000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f7eddd37000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f7eddc9e000)
	libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007f7eddc94000)

$ rpm -q --whatprovides /lib64/libasound.so.2
alsa-lib-1.2.2-2.fc32.x86_64

**Comment by ThePillenwerfer** [comment]
Thanks for that.

I'll answer my own question in case the information is useful to anybody else.

It seems that for the build-no-avcodec recipe for dosbox-x 0.83.2 the packages needed on Debian Stretch are:—

```
libasound2, libc6, libx11-6, libxext6, libtinfo5, zlib1g, libpng16-16, libpcap0.8, libxrandr2, libfluidsynth1, libgl1-mesa-glx, libstdc++6, libgcc1
```

Obviously the names may be subtly different on Ubuntu or other Debian-bases distros.
