### ISSUE TITLE
GUS emulation: OOPS, timer emulation code mistake!

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#153]
timerIRQ = ((myGUS.IRQStatus & 0x0C/*Timer 1&2 IRQ*/)!=0) && ((myGUS.TimerControl & 0x0C/*Timer 1&2 IRQ Enable*/)!=0);

That will allow either timer's enable bit to enable both timer interrupts!
Should be:

    timerIRQ = ((myGUS.IRQStatus/*Timer 1&2 IRQ*/ & myGUS.TimerControl/*Timer 1&2 IRQ Enable*/ & 0x0C)!=0);

This new version masks Timer 1 IRQ against IRQ 1 enable, Timer 2 IRQ against IRQ 2 enable.

**Comment by ghoul8765** [comment]
The math may as well be in assembly. :)

**Comment by joncampbell123** [comment]
IRQ status bits 3-4 reflect IRQ state. The IRQs are masked for each timer by bits 3-4 in the timer control register. So (IRQ status AND Timer Control AND 0x0C) == a bitfield indicating which timers will trigger an IRQ.

C/C++ have '&' as the boolean AND operator. X = A & B means to and each bit from A by each bit from B and assign the result of each bit to X.

Examples:

    (truth table for AND). X is TRUE (1) if A and B are TRUE (1), else FALSE (0)
    A   AND   B           X
    0              0            0
    1              0            0
    0              1            0
    1              1            1

    0xAA & 0xFF = 0xAA       10101010 & 11111111 = 10101010
    0xAA & 0x0F = 0x0A        10101010 & 00001111 = 00001010
    0xAA & 0xF0 = 0xA0        10101010 & 11110000 = 10100000

This sort of binary shortcut stuff is common in assembly language, yes, but it need not be magic. It's pretty straightforward how it works.

**Comment by ghoul8765** [comment]
Thank you very much for the instruction. I'll go over it a few times so I can interpret the code more easily. I've had to use the binary math just a couple of times, but it always requires me to write out the truth table for the problem each time. :)

**Comment by ghoul8765** [comment]
I think I understand now the example. The 0x0C is compared to the other two values to check whether bits 3 and/or 4 are On. I see now how this is fairly fundamental to how a system works, where the timer is on a schedule and the IRQ is dependent on that. Hopefully this example carries over to most situations. :)

**Comment by joncampbell123** [comment]
Almost. 0x0c is a bitmask. the code ANDs the timer IRQ enable and IRQ status bits. We only care about bits 2-3 so we AND the result with 0x0c then check to see if the result is nonzero to determine whether to signal a timer IRQ.

0x0c = 00001100 to mask off all but bits 2-3.

**Comment by ghoul8765** [comment]
That makes sense now. The bitmask is so that only the tested bits are retained. I had always thought that editing of this kind of code requires a fluency and practice in binary math, but perhaps I can better follow it with some effort and a ruleset.
