### ISSUE TITLE
Sopwith loses the sound of an airplane

### ISSUE THREAD

**Issue by maximus105** [joncampbell123/dosbox-x#1530]
**Environment (please complete the following information):**
 - Windows 10 x64
 - DOSBox-X 0.83.1 x64 SDL2
 - cycles = 240

**Describe the bug**
In Sopwith, the sound of an airplane disappears at maximum airplane speed. Perhaps this is somehow related to the bug https://github.com/joncampbell123/dosbox-x/issues/1492

**To Reproduce**
1. Launch the game Sopwith.com or Sopwith.exe
2. Select a single player game (press "s", then "3")
3. Make sure the sound is turned on in the game (the "s" key turns the sound on or off)
3. Take off the plane (control keys "<", ">", "?") And increase the speed of the aircraft to the maximum (key "x").
4. Fly right to the end of the level.
4. Toward the end of the level, the sound of a flying airplane will disappear, and will appear only when you press the "s" key several times, which turns the sound on or off.
Also, the sound of the aircraft may accidentally disappear at the minimum speed of the aircraft (the "z" key reduces the speed of the aircraft)
In 86Box, DOSBox-ECE there is no such bug with sound. By the way, the Paratrooper game in 86Box also works correctly (with the sound of helicopters and airplanes).

**Comment by rderooy** [comment]
The good thing is that the source code is freely available: http://sopwith.org/

**Comment by rderooy** [comment]
Do you know which "version" of sopwith your using? Unfortunately sopwith does not display a version number, but there are various versions.

I did notice the sound vanishing with sopwith 1 towards the end, but not with sopwith 2.

**Comment by maximus105** [comment]
> Do you know which "version" of sopwith your using? Unfortunately sopwith does not display a version number, but there are various versions.

I checked Sopwith1 and Sopwith2 versions: on both versions the sound is lost. Here is the version of Sopwith2, where the sound also disappears at the maximum speed of the aircraft:
http://www.wingkong.net/sopwith2b/files/sopwith2.zip

**Comment by joncampbell123** [comment]
Given the age of the game, I assume the sound is PC speaker output?

DOSBox-X inherits the DOSBox design where PC speaker output is shut off if no changes to state are made after a certain time (10 seconds I think).

**Comment by joncampbell123** [comment]
Testing Sop1 and Sop2, the PC speaker sound disappears if the game makes no change to the sound for 10 seconds.

So if you play the game and it makes different noises, you won't lose the sound.

If you sit and leave the game to make a continuous buzz, the buzz will stop after 10 seconds.

This behavior was inherited from DOSBox SVN at the time DOSBox-X was forked. I suppose it's time to remove it and instead stop rendering PC speaker output only if left off after 10 seconds.

**Comment by joncampbell123** [comment]
src/hardware/pcspeaker.cpp line 642: The code assumes that if no change to PC speaker state occurs for 10 seconds if output enabled, or 1 second if output disabled, and the output happens to be zero at the time that decision is made, the PC speaker output stops rendering.

What should really happen is that the timeout should not happen as long as the PC speaker is still buzzing, instead of turning off because the output happened to be zero at that point.

**Comment by joncampbell123** [comment]
I just pushed a commit that prevents PC speaker output from timing out unless the PC speaker isn't making any noise. Sopwith's droning buzz can run forever now without timeout. Please try the latest code if you can compile from source.

**Comment by maximus105** [comment]
You could write detailed instructions on how to build a build using minigw, similar to this instruction?
https://pcem-emulator.co.uk/phpBB3/viewtopic.php?t=845
