### ISSUE TITLE
Main > Autolock mouse menu option does nothing

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1532]
**Describe the bug**
Toggling the menu option "Autolock mouse" does nothing, at least not until you do a "Reset guest system".

**To Reproduce**

* Start DOSBox-X and load something that uses the mouse.
* Under "Main", toggle the "Autolock mouse" option.

If it was set "off" (default), it will show a checkmark, indicating it is on. But Autolock when clicking inside the DOSBox-X window will do nothing. Now do a "Reset guest system", and load the same software again, and autolock will work.

Likewise if you had configured autolock=true in your dosbox-x config. If you disable the menu option, and click inside the DOSBox-X window, it will still lock, until you do a "Reset guest system".

**Expected behavior**
For the option to have immediate effect, not just after using the "Reset guest system" option.

**Environment (please complete the following information):**
- Fedora 32
- DOSBox-X 0.83.2-git

**Comment by Wengier** [comment]
@rderooy I think the "Autolock mouse" option does work if you check or uncheck it BEFORE running the software that uses the mouse (such as Windows 3.1). Once the software is already running, the function will no longer accept new changes until a guest system reset.

**Comment by rderooy** [comment]
@Wengier You seem to be right. If start DOSBox-X with autolock=true (integrated DOS or real DOS), toggle the option, and then start WfW3.11, the new state will take effect.

Still this seems like an option you should be able to change 'on the fly'. It's current behaviour can be confusing.

**Comment by joncampbell123** [comment]
If you're using the Mouse Integration driver with Windows 3.1/95, moving the mouse in the emulator window causes the cursor to match within the guest.

If you're running a DOS program that uses INT 33h that polls absolute mouse position (not relative motion), that will also match emulator window to guest, provided DOSBox-X  correctly guesses what mouse range it is trying to use (only a few cases like the DOS versions of Lemmings cause trouble here).
