### ISSUE TITLE
Main > Send Key > Ctrl-Alt-Del inconsistent behaviour

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1534]
**Describe the bug**
The behaviour if the menu option is inconsistent.

It **does not** work with either the integrated DOS, or when booting a real DOS. This includes when running games from DOS. I would expect a soft-reset.

It **does** work if you run WfW3.11 or Win9x inside DOSBox.

**To Reproduce**
- Start DOSBox-X to the integrated DOS prompt
- Use the menu option

**Expected behavior**
Soft reset, similar to that of a real PC.

**Environment (please complete the following information):**
- Fedora 32
- DOSBox-X 0.83.2-git

**Comment by Wengier** [comment]
I think Ctrl-Alt-Del is not yet handled by the DOSBox-X code at all. The key combination Ctrl-Alt-Del works in Win3.x or Win9x only because Windows will handle Ctrl-Alt-Del by itself.

**Comment by Wengier** [comment]
I have already fixed this in my pull request 1536. Ctrl+Alt+Del should now do a reset when in the integrated DOS, or when booting a real DOS.
