### ISSUE TITLE
CD audio is looping

### ISSUE THREAD

**Issue by ghoul8765** [joncampbell123/dosbox-x#154]
Using Half-life as a reference, the cd redbook music shouldn't loop. This is from a FAQ:

"Is there background music for Half-Life?
-Yes there is, but only at certain times. It doesn't play background music in 
loops. Certain spots can only call on the background music, and it won't loop. 
So, you will only get to hear it once, and it'll all go quiet again."

However, the music tracks continue looping instead. It can be heard at the start of a new game. Another way is to start a new game and then load another map, and the other map will continue playing the original music track.

I don't know if it is related, but the Windows 95 music player will continue playing a track even if the program is closed without pressing the "stop music" button. I assumed this happens in real hardware, too.

**Comment by ghoul8765** [comment]
I have to log further, but there is already a message which seems associated with the above issue:
if (playing)
  LOG_MSG("ATAPI: Interrupting CD audio playback due to SEEK\n");
  cdrom->StopAudio();

And there is a reference in cdrom_image.cpp to StopAudio:
player.isPlaying = false;
player.isPaused = false;

Given the music is already playing, then the seek command occurs while loading another map. I would guess that a stopaudio command would be sent on loading another map (not yet logging for it), but why is a seek command sent at this time? I tested with both the mscdex driver and the 32-bit windows driver.

Another note is that the music does stop upon loading another map, but then restarts after the map is loaded. I wouldn't think a playaudio command is sent on loading of any map, so should the SEEK (or another unlogged) command cause this? Is it still possible that real hardware shows this issue under a set of conditions, too.

**Comment by joncampbell123** [comment]
My understanding of the way Windows 95 uses the CD-ROM drive is that a SEEK or READ is meant to interrupt CD audio playback by distracting the drive. So if neither of those code snippets are stopping playback, then there is a bug in CD audio emulation that needs to be fixed.

Does the same happen with DOS games, when DOS games attempt to stop playback?

**Comment by ghoul8765** [comment]
That's a good question. I've never heard of any issues with DOS games, but haven't verified whether they use SEEK or whether their cd audio playback is continuous. I'd prefer to have a simpler example to test.

I also believe that the SEEK command is interrupting CD audio playback, but it then restarts on loading the new map. If music not playing and no SEEK command is issued, then loading the new map doesn't generate music.

**Comment by ghoul8765** [comment]
Have this so far from mimimal logging:
Track 28 attr=0x00
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idle
ATAPI CD-ROM: spinup complete
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idle
ATAPI CD-ROM: spinup complete
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idle
ATAPI CD-ROM: spinup complete

The above is with music playback enabled (via mscdex). "cd stop" at the half-life console will stop the music playback and avoid the above issue.

**Comment by ghoul8765** [comment]
And more extensive logging:
Track 28 attr=0x00
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idl
ATAPI CD-ROM: spinup complete
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idl
ATAPI CD-ROM: spinup complete
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idle
ATAPI CD-ROM: spinup complete
ATAPI CD-ROM: pause/resume
ATAPI CD-ROM: play_audio_msf
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idle
ATAPI CD-ROM: spinup complete
ATAPI CD-ROM: pause/resume
ATAPI CD-ROM: pause/resume
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idle
ATAPI CD-ROM: spinup complete
ATAPI CD-ROM: pause/resume
ATAPI CD-ROM: play_audio_msf
ATAPI CD-ROM: spinning down

**Comment by ghoul8765** [comment]
Have this on the start map:
ATAPI CD-ROM: spinning down
ATAPI CD-ROM: triggered to spin up from idle
ATAPI CD-ROM: spinup complete
pause/resume (4B)
play_audio_msf (47)
pause/resume (4B)
play_audio_msf (47)
pause/resume (4B)
play_audio_msf (47)
pause/resume (4B)
play_audio_msf (47)
pause/resume (4B)
play_audio_msf (47)

When switching to another map, then I just see one set of these commands only, although the music continues to loop. I wonder if the pause/resume is out of sync due to this repeating pattern of pause/resume and play.

**Comment by ghoul8765** [comment]
Ok, a quake cue/bin shows none of these issues, particularly in the media player. It's just half-life and its 28 music tracks. I think that in half-life it is pausing the track (stopping the playback) without effect, just like in the media player. Is this actually in mscdex code? Is there a track limit? Does this happen with music files (sdl_sound), an empty iso, and 28 tracks, too?

**Comment by ghoul8765** [comment]
In the media player and hl1, this is a repeating pattern with music stopped (read_subchannel):
SUBCH
00
12
00
00

And this repeats while music is playing in the media player or hl1:
SUBCH
00
11
00
00

**Comment by ghoul8765** [comment]
This may be informative:
pause/resume (4B)
start_lba 0 end_lba 0
play_audio_msf (47)
pause/resume (4B)
start_lba 0 end_lba 0
play_audio_msf (47)
pause/resume (4B)
start_lba 0 end_lba 0
play_audio_msf (47)
pause/resume (4B)
start_lba 0 end_lba 0
play_audio_msf (47)
pause/resume (4B)
start_lba 0 end_lba 0
play_audio_msf (47)

**Comment by ghoul8765** [comment]
ATAPI command 42 02 00 01 00 00 00 00 04 00 00 00 to_host=0
ATAPI command 42 02 40 01 00 00 00 00 10 00 00 00 to_host=0
ATAPI command 4b 00 00 00 00 00 00 00 00 00 00 00 to_host=0
pause/resume (4B)
ATAPI command 47 00 00 03 0f 09 06 1a 16 00 00 00 to_host=0
play_audio_msf (47)
ATAPI command 42 02 00 01 00 00 00 00 04 00 00 00 to_host=0

**Comment by joncampbell123** [comment]
Looking at the ATAPI commands you listed there, it looks like the game is asking it to play from start to end. The SCSI standard says it's supposed to stop at the end address, so if it's looping and it's not the game causing it, then the CD playback needs to be checked to make sure it stops. If however it's looping because the game is commanding it to, then behavior is as expected.

Command 47h PLAY AUDIO MSF.

http://jon.nerdgrounds.com/jmcs/docs/Hardware/SCSI/Multimedia/SCSI%20Multimedia%20Commands%20-%202.pdf

**Comment by ghoul8765** [comment]
Thank you for the valuable insight. The game is sending rapid commands during the start of the start map to cause the above issue. Also, if I switch to another map while the music is playing, then the music plays and then restarts with another pair of pause/resume and play_audio_msf commands; however, the commands don't seem to be sent until the track is complete (not rapidly sent), so the looping must be as expected.

The 1.0 version is checking tracks. Applied the 1.0.0.6 patch which fixed the above issue.

**Comment by ghoul8765** [comment]
Thank you for fixing the issue, somehow! I don't know why this cue/bin caused it and not other images, but it is also improves the speed alot in the above configuration.
