### ISSUE TITLE
Parellel Port Problems following Update.

### ISSUE THREAD

**Issue by ThePillenwerfer** [joncampbell123/dosbox-x#1541]
**Describe the bug**
Not only does the virtual dot-matrix printer not work but sending LPT1 output to a file now doesn't either.

**To Reproduce**
1. Download, build and install FreeType2
2. Build and install latest dosbox-x code.
3. Set `parellel1=file` in .conf file.
4. Load dosbox-x and `type dir > lpt1`
5. No file is produced.

**Expected behavior**
A file to appear in ~/capture or wherever else is specified in the .conf file.

**Screenshots**
Version built a few days ago:—
![Screenshot at 2020-05-11 14-27-13](https://user-images.githubusercontent.com/42588539/81567304-0c5bb100-9394-11ea-8c07-ae10f6a6c77d.png)

Version built today:—
![Screenshot at 2020-05-11 14-26-28](https://user-images.githubusercontent.com/42588539/81567367-209fae00-9394-11ea-9837-92d261c778f1.png)

**Environment (please complete the following information):**
 - Debian 9.12 32-bit.
 - DOSBox-X release 0.83.2 downloaded c10am BST 11 May 2020
 - Used configuration, e.g. ```dosbox-x.conf```

```
[sdl]
output=opengl
mapperfile=~/.dosbox/mapper-0.83.2.map

[dosbox]
#machine=cga

[printer]
printer     = true
dpi         = 360
width       = 85
height      = 110
printoutput = png
multipage   = false
docpath     = ~/capture
timeout     = 0

[parallel]
parallel1=file 

[dos]
keyboardlayout=uk

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.

```

**Additional context**
I have never been able to get the virtual dot-matrix printer in dosbox-x to work but have been able to send LPT1 output to a file.  When I saw from the changelog that printing support for Linux had been enabled and decided to give it another try.

First I did a `git pull` to get the updated code and then downloaded, built and installed FreeType 2.10.0.  Next I build dosbox-x with `build-no-avcodec.`  I made a directory `~/.dosbox/FONTS` containing `courier.ttf`, enabled the virtual dot-matrix printer in the .conf file, ran dosbox-x and typed `dir > lpt1`.  No png file was produced.

After some fiddling about I reverted things to how they were, ie `parellel1=file` and found that that no longer works either.  No log entries are made about capturing — see screenshots above.

**Comment by rderooy** [comment]
@ThePillenwerfer 

I just tried it here on Fedora 32, with the build I did myself, and your example works.
```
LOG: SHELL:Redirect output to lpt1
LOG: Capturing Parallel Port Stream to capture/dosbox_000.prt
LOG: Parallel 1: File closed.
```

**Comment by ThePillenwerfer** [comment]
Thanks for that as it suggested a fault at my end.  

I completely started again on a different PC which had never previously built anything so everything was new and couldn't have been accidentally cocked-up.

The build of dosbox-x done on that does indeed capture to files fine so at least nothing has been lost.

I still have had any success with virtual dot-matrix printer but that's a matter for a different issue, assuming I can't get it going.
