### ISSUE TITLE
SYS command causes (another) disk image corruption

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#1543]
The FAT driver has been updated recently to fix the filesystem corruption with the Win9x setup. But with the latest code I found another bug in the FAT driver that will cause disk corruption, this time with the SYS command from MS or PC DOS.

Previously (before today's commits) the command "SYS . C:" will report an error "Extended Error 18" or "No more files", but with the current code the command "SYS . C:" (or "SYS A: C:" etc) will succeed with the message "System transferred", but then the disk image is not bootable and more importantly, once you restart DOSBox-X the disk image is no longer readable or mountable. So the disk image has been permanently damaged from this command and is no longer usable by DOSBox-X.

Tested with the SYS command from MS-DOS 6.0 and PC DOS 2000. Same result.

The MS-DOS 6.0 disks (including SYS.COM, IO.SYS, MSDOS.SYS etc) can be found at:

https://winworldpc.com/product/ms-dos/6x

Steps to reproduce the result (using MS-DOS 6.0 DISK1.IMG):

IMGMAKE HDD.IMG -t hd_250
IMGMOUNT A: DISK1.IMG
IMGMOUNT C: HDD.IMG
VER SET 6.0
A:
SYS A: C:
Then close and restart DOSBox-X and try to mount HDD.IMG again, and if it is mounted do a "DIR C:" and see the result.

**Comment by joncampbell123** [comment]
Windows 95 SYS.COM (run from the DOSBox-X command line) seems to have no issues SYSing to a floppy disk image in drive A: though.

**Comment by Wengier** [comment]
Floppy images seem to be fine, but not hard disk images. I have tested hard disk images with 100MB, 250MB and 520MB (all created with IMGMAKE), all have such problems (either no longer mountable or no longer readable). I have now included steps to reproduce this problem in my first post.

**Comment by joncampbell123** [comment]
I think the problem is that INT 21h AX=440Dh CL=60h (Get device parameters) is returning dummy information instead of the actual geometry and FAT filesystem information.

So SYS.COM uses the bad information and corrupts the filesystem.

After SYS C: DOSBox-X mis-identifies the drive as FAT32 (!)

**Comment by Wengier** [comment]
@joncampbell123 I see. Let me try to fill the real information and see how it works.

**Comment by joncampbell123** [comment]
@Wengier Filling in the correct information might require another method to the C++ DOS drive class. Let me know if it would be easier for me to implement that.

**Comment by Wengier** [comment]
@joncampbell123 I just saw your last message. I have already finished it so that the SYS command should now work properly on FAT drives. See pull request #1544.
