### ISSUE TITLE
issues with new FAT32 support

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1554]
**Describe the bug**
Trying to xcopy a directory tree from an ISO to a FAT32 volume fails after 4 files.

I was able to reproduce this with both setting, and not setting ver=7.10.

e.g.
```
C:\>IMGMOUNT C hdd.img
Image geometry auto detection: -size 512,63,64,1023
Drive C is mounted as hdd.img
C:\>IMGMOUNT D Win98SE.iso -t iso
MSCDEX installed.
Drive D is mounted as Win98SE.iso
C:\>xcopy d:\win98 c:\windows\options\cabs /i /e
Copying D:\WIN98\OLS\AOL\AOL40AU.EXE
Copying D:\WIN98\OLS\AOL\AOL40CA.EXE
Copying D:\WIN98\OLS\AOL\AOL40UK.EXE
Copying D:\WIN98\OLS\AOL\AOL40US.EXE
Unable to create directory C:\WINDOWS
4 file(s) copied
```

The volume was originally a 2GB FAT16 volume, that was converted to FAT32 with Win98's conversion utility.

For some strange reason that I don't understand, if the xcopy destination is C:\TEST it does succeed.

Running ```D:\win98\scandisk.exe c:``` reports only the error that free space is being reported incorrectly.

**Comment by joncampbell123** [comment]
Yeah, I noticed that. It's a strange bug.

**Comment by joncampbell123** [comment]
It might be related to how FAT32 handles the root directory.

I can't recreate this issue if I make a top level directory, then a subdirectory, then XCOPY into that subdirectory.

For example

    mkdir c:\abc\def
    xcopy *.* c:\abc\def\*.* /s /e

Always works.

**Comment by joncampbell123** [comment]
GetAttr/SetAttr fixed. Try the latest commit.

**Comment by rderooy** [comment]
Seems to work now. Thanks!
