### ISSUE TITLE
Win98 setup.exe - runtime error R6001

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1555]
**Describe the bug**
With ver=7.10
Running Win98SE setup.exe from FAT32 volume shows:
```
C:\WINDOWS\OPTIONS\CABS>setup
Please wait while Setup initializes

run-time error R6001
- null pointer assignment
Setup is now going to perform a routine check on your system.

To continue, press ENTER. To quit Setup, press ESC.
```
Log shows:
```
LOG: 1122839196 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122839202 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122839209 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122839216 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122840192 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122842109 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1615
LOG: 1122875456 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122875465 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122875475 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122875485 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122876477 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1122878246 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=D201
LOG: 1122885907 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1686
LOG: 1122885960 ERROR DOSMISC:DOS:INT 2F Unhandled call AX= 600
LOG: 1122885974 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=B700
LOG: 1122890627 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=160A
LOG: 1124215992 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1124216001 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1124216011 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1124216021 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
LOG: 1124216669 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=122E
```

**Comment by rderooy** [comment]
It is necessary to run ```setup /is``` as otherwise it will refuse to continue due to the free space error.

It will give the same run-time error, but will continue a little bit, but then error out with an SU995035 error.
![krnl386_000](https://user-images.githubusercontent.com/17701098/82047373-fd863e80-96b2-11ea-81e7-4377fce90f4f.png)

These are the additional log messages:
```
LOG: 2997781482 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=160B
LOG: 3007320994 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=5600
LOG: 3007332394 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=5600
LOG: 3008173864 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
LOG: 3008174254 ERROR DOSMISC:DOS:IOCTL Call 11 unhandled
```
Pressing enter and it will show a black screen with blinking cursor, with the following additional LOG messages:
```
LOG: 3333140100 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4007
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: surface consider=720x417 final=720x417
LOG: X11 main window is 720 x 417 maximized=0
LOG: XRandR CRTC 0: pos=(1920,0) size=(1920,1080) outputs=1
LOG: Our window lies on this CRTC display (window pos=(1960,69) size=(720,417) match=(2320,277)).
LOG:   Goes to output 0: name='XWAYLAND0' size_mm=(480 x 270)
LOG: Screen report: Method 'XRandR' (1920.000 x 1080.000 pixels) at (1920.000 x 0.000) (480.000 x 270.000 mm) (18.898 x 10.630 in) (101.600 x 101.600 DPI)
LOG: DEBUG: INT 2Fh Windows 286/386 DOSX exit broadcast issued (DX=0x0001)
LOG:  [286 DOS extender]
LOG: 
LOG: 3333168023 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1606
```

**Comment by Wengier** [comment]
Win98SE setup.exe seems to check the reported DOS version and do things slightly differently according to it. So if enter "VER SET 6.0" (even without disabling LFN support) before running SETUP, then the program will not show the error.

**Comment by Wengier** [comment]
Also, I did compare the FAT32 disk images before running SCANDISK and after letting SCANDISK "fixed" the free disk space, and it seems that it did not actually change anything on the disk image. So while the free space scanning is an issue by itself, letting it "fix" the error won't cause any damage to the disk, so ```SETUP /IS``` is still not really necessary for Win98 Setup.

**Comment by Wengier** [comment]
The SCANDISK free space issue has been fixed in my pull request #1558.

**Comment by rderooy** [comment]
I tried different ways to install Win98SE onto a FAT32 volume, and each attempt has failed.

If I **do not** set ver=7.10 in the config, I get the following error.
![krnl386_001](https://user-images.githubusercontent.com/17701098/82120713-6c819700-9788-11ea-964e-b573e85f6eec.png)

![scandisk_000](https://user-images.githubusercontent.com/17701098/82120721-799e8600-9788-11ea-8b94-f7c74c14268a.png)

If I **do** set ver=7.10 in the dosbox-x config I get the errors mentioned in the 1st post.

**Comment by Wengier** [comment]
@rderooy I have tried to do dynamic DOS version switching for testing, and it seems to work for Win98 Setup. So basically you set VER=6.0 before running SETUP.EXE, and then set VER=7.1 when the graphical installation part begins, so that both issues will not occur and Win98 Setup continues. Dynamic DOS version switching is for my internal testing only and not yet available from the menu.

P.S. With DOSBox-X 0.83.1+ you can just use ```VER=7.1``` instead of ```VER=7.10``` for setting 7.1 as the reported DOS version. Same applies to the VER command, e.g.

"VER SET **7.1**" will set the reported DOS version as 7.1 (7.10).
"VER SET **7 1**" will set the reported DOS version as 7.01 as in (original) DOSBox.

**Comment by joncampbell123** [comment]
I wonder if the recent bug with FAT32 FORMAT.COM divide by zero (if FORMAT /S) and Windows 98 SETUP "NULL pointer assign" are related. Perhaps some of the newer FAT32 IOCTLs and INT 21h functions are returning 0s in fields they shouldn't.

**Comment by Wengier** [comment]
@joncampbell123 I have submitted a pull request to suppress the "run-time error R6001" and the "assertion failed!" errors.

**Comment by joncampbell123** [comment]
@Wengier Just merged it,made a few corrections to tab indentation, and added a comment to explain why the special case was added.

**Comment by joncampbell123** [comment]
It also seems to fix the "NULL pointer deference" error messages.

**Comment by Wengier** [comment]
@joncampbell123 I think "run-time error R6001\n- null pointer assignment" is the same error spanning two lines.

**Comment by joncampbell123** [comment]
It turns out FORMAT.COM divides by zero because it calls INT 21h AH=36h and computes sectors per cluster * bytes per sector, which comes out zero in this case.
