### ISSUE TITLE
DIR /S too verbose

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1556]
**Describe the bug**
In DOS, when you use DIR /S to find a file, it does not list every single directory along the way that does not contain a match.

Running ```DIR *.INI /S``` in the DOSBox-X Shell
![command_000](https://user-images.githubusercontent.com/17701098/82051144-a33cac00-96b9-11ea-8fde-37677f037ff8.png)

Compared to running it in MS-DOS 6.22:
![guest os_002](https://user-images.githubusercontent.com/17701098/82051223-c23b3e00-96b9-11ea-94a0-2888e9745245.png)

Only when MS-DOS fails to find any match, does it give a file not found message.
![guest os_003](https://user-images.githubusercontent.com/17701098/82051534-57d6cd80-96ba-11ea-943d-c7fe9e26b257.png)

**To Reproduce**
* mount a folder with lots of sub directories
* Use "DIR /S" to locate some file

The output is such that it is often impossible to find the file your looking for, unless you redirect the output, as it will scroll off your screen.

**Expected behavior**
Similar to MS-DOS, don't output every directory that does not contain a match.

**Comment by Wengier** [comment]
I have already fixed this in my pull request #1558.
