### ISSUE TITLE
The DOSBox-X Font.

### ISSUE THREAD

**Issue by ThePillenwerfer** [joncampbell123/dosbox-x#1557]
I have several computers with an identical build of DOSBox-X on.  On one of them, a laptop with an Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07) the in-built font does seem to display as nicely as on the others.  This is particularly noticeable with the Control symbol (Shift-6):—
![laptop](https://user-images.githubusercontent.com/42588539/82061491-b141fb00-96c0-11ea-96ea-1b0611b4e497.png)

One of the other PCs has a Intel Corporation 82915G/GV/910GL Integrated Graphics Controller (rev 04) which looks like this:—
![hp](https://user-images.githubusercontent.com/42588539/82061556-c6b72500-96c0-11ea-8ff3-ae73ec0aa983.png)

and the final one I’ve tried it on which has an NVIDIA Corporation G86 [GeForce 8500 GT] (rev a1) this:—
![nVidia](https://user-images.githubusercontent.com/42588539/82061589-d46caa80-96c0-11ea-9ff0-64aa1e5d01f7.png)

Full-screen or windowed, with or without `aspect=true` makes no difference.

This is so minor that I’m not expecting anybody to waste their time ‘fixing’ it but it is strange.

One item for my Future Feature Wish-List would be being able to change the built-in font at will.  This is in accordance with the Accurate Emulation aim as in the DOS era not all computers used the same font.  For instance my old Amstrad used a sans-serif font:—
![Amstrad](https://user-images.githubusercontent.com/42588539/82062228-b6ec1080-96c1-11ea-95fd-81a6b7455af3.png)

**Comment by rderooy** [comment]
This is what it looks like on my Fedora Linux 32 with 4x zoom
![Screenshot from 2020-05-15 19-48-46](https://user-images.githubusercontent.com/17701098/82080664-4951db80-96e5-11ea-91ce-56077c69a27d.png)

This is with a hybrid Intel/Nvidia setup using the opensource drivers.

**Comment by ThePillenwerfer** [comment]
Thanks for that.  After more testing I have determined that the problem is in KEYB and opened an appropriate bug report.
