### ISSUE TITLE
Gravis Ultrasound realism: RealTech "Dimension" demo odd GUS behavior raises questions about Voice Control register

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#157]
There are two things that raise questions about the Voice Control register.

The first is this snippet of code inherited from the original DOSBox GUS emulation:

    void WriteWaveCtrl(Bit8u val) {
        ...
        if ((val & 0xa0)==0xa0) myGUS.WaveIRQ|=irqmask;
        else myGUS.WaveIRQ&=~irqmask;
        ...
    }

The GUS SDK documents the voice control register but doesn't say anything about whether or not bit 7 is writeable. It is implied (at least to me) that bit 7 is a Wave IRQ pending bit and therefore something you read back, not write. So:
- Is bit 7 writeable?
- If I were to set both bit 5 and bit 7 while writing the register, would real GUS hardware trigger a wave (voice) interrupt immediately? If so, does it allow this under all conditions? Or only if a voice is not stopped?
- Can I clear a pending wave IRQ by manually clearing bit 7 instead of reading IRQ events from register 8Fh? does clearing bit 5 clear a pending wave IRQ? both?
- This code also implies that simply writing the Voice Control register normally can clear a pending wave IRQ. Is that true? Or does a pending wave IRQ stick until processed through register 8Fh or cleared by bit 5?

Now the other part: It turns out that RealTech's "Dimension" demo crashes in DOSBox-X if you use Gravis Ultrasound playback because the demo writes 0xFF to the voice control register to stop a voice. However, 0xFF also sets bits 5 and 7, which triggers DOSBox-X to fire a wave IRQ, which the demo's IRQ handler is apparently not prepared to handle and therefore an IRQ storm ensues that causes the demo to crash.

- What does real GUS hardware do if you throw something nonsensical like 0xFF into the Voice Control register?
- If you simultaneously set bits 5 and 7 while also setting both bits 0-1 to stop the voice, does the GUS fire a wave IRQ? If so, do both voice bits have to be set, or can either one prevent a wave IRQ?

**Comment by ghoul8765** [comment]
I confirmed the above and look forward to any results from testing 0xFF against the real GUS. It seems that the demo is writing 0xFF to the register twice, why not just once?

It's interesting that this demo is the only one with the issue, at least so far. I would have thought the authors stick to a common gus audio routine, especially since this demo supports many devices.

**Comment by joncampbell123** [comment]
Just tested. Apparently bit 7 is writeable. Sort of. Setting it causes the voice to trigger an IRQ but only if bit 5 (IRQ enable) is also set. But, it seems bit 7 is held to zero if bit 5 (IRQ enable) is also zero.

Writing FF makes the voice stop, but also triggers an IRQ.

This test was carried out from within the Ultrasound test program in DOSLIB, so it handles the interrupt correctly. I will load DIMENSION onto the system's hard drive (well, CF card) and see if it runs on the hardware.

**Comment by joncampbell123** [comment]
Okay. So writing FF causes a voice IRQ. However, despite that quirk, Dimension is running perfectly fine on the old Pentium+GUS setup. So perhaps the cause of the IRQ storm is DOSBox-X's method of dispatching the IRQ rather than the voice IRQ occurring.

**Comment by ghoul8765** [comment]
Thank you for the improvements. I will look over the lines of code from the latest updates and what they do, it looks very interesting.
