### ISSUE TITLE
Conf File Name (Linux).

### ISSUE THREAD

**Issue by ThePillenwerfer** [joncampbell123/dosbox-x#1574]
**Describe the bug**
I was under the impression that DOSBox-X now also looks for a conf file called `dosbox-x.conf' but earlier I found it didn't appear to work.

**To Reproduce**
1. Create a .conf file called `dosbox-x.conf` in `~/.dosbox' and move any other existing ones.
2. Launch DOSBox-X
3. `dosbox-x.conf` is ignored

**Expected behavior**
I would expect `dosbox-x.conf` to work as per the CHANGELOG entries under V 0.83.1.

**Environment (please complete the following information):**
 - Operating system Debian 9.12 32-bit
 - DOSBox-X release version 0.83.2
 - Used configuration, e.g. ```dosbox-x.conf```

**Additional context**
I was testing something earlier and had to install DOSBox-X on a different PC and it ignored the `~/.dosbox/dosbox-x.conf `file I created. Running `dosbox-x -printconf` revealed it was looking for `.~/.dosbox/dosbox-0.83.2.conf`.

**Comment by Wengier** [comment]
@ThePillenwerfer DOSBox-X will try to load the file dosbox-x.conf and then dosbox.conf in the CURRENT DIRECTORY after trying to load the dosbox-0.83.2.conf file from the user directory (~/.dosbox in the case of Linux). This is not specific to Linux, but it is how it works in Windows and other platforms too.

**Comment by ThePillenwerfer** [comment]
Thank you for the clarification.  That's potentially handy for using a temporary one.
