### ISSUE TITLE
It was a mistake for DOSBox developers to have made the Mixer routines time by the sound card

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#158]
On my Linux system, there seems to be enough of a timing difference between the sound card and SDL get ticks routine that the DOSBox mixer is "over rendering" a bit. It seems in fact that this over-rendering causes problems in some demoscene productions that are really fussy with rendering to the sound card. "Saga" for example is picky enough that if the mixer auto-adjustment code is allowed to function by not locking ticks aka speedup and not capturing audio/video, and the cycles count is above a certain level, the demo will have some rather annoying and loud popping/clicking artifacts as if DMA is going past the buffer consistently (besides the quiet pops/crackles that normally happen during the demo). These artifacts seem to go away if I start the demo while capturing video.

There's loads of "tick add" vs "needed" and auto-adjustment stuff in the mixer.cpp file that could be cleaned up a lot if DOSBox were to render to emulator time instead of trying to bend it's will to the sound card all the time. Output code from the mixer to the sound card would instead be managed by a routine that generally copies samples 1:1, but if it sees the sound card differ, could slightly "bend" the sample rate out to the sound card to match (like what VLC player does to keep audio synched).

Another alternative would be to recode DOSBox to read time from the sound card instead of from the SDL ticks function, so that the mixer and sound card match up 100% anyway (and fall back to SDL ticks if sound is turned off). Emulator time would follow the sound card, not SDL timer ticks.

**Comment by ghoul8765** [comment]
That will be a great improvement to the mixer function. I like the VLC method given that it maintains the portability of SDL; also with the assumption that using the sound card instead would be machine specific (or can SDL universally read the sound card time?).

**Comment by joncampbell123** [comment]
Coming back to this issue:

I long ago rewrote the mixer to render according to emulator time and SDL_GetTicks() so this is not an issue anymore.

The only reason I am keeping this open now is that I still haven't added the VLC-style effect of slightly speeding up or slowing down audio when audio rendering isn't quite at the same sample rate as emulation.
