### ISSUE TITLE
(Linux) AltGr not working with SDL1

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1580]
**Describe the bug**
The AltGr key (or the right ALT key, if it is not marked as AltGr) on international keyboard layouts does not work in the SDL1 build on Linux.

It **does** work with
* The Linux SDL2 build, such as the Flatpak release
* The Windows SDL1 build

**To Reproduce**
1. Start DOSBox-X
2. ```keyb be```
3. pressing AltGr-E should show the Euro symbol

The above example uses a Belgium-French keyboard layout, but AltGr will not work with any non-US layout including UK, FR, DE, IT, ES, etc.

**Expected behavior**
AltGr to function with SDL1 like it does on Windows, or with SDL2.

**Screenshots**
Linux SDL1 build with AltGr pressed - nothing is highlighted, but a key press is detected in the bottom right corner.
![Screenshot from 2020-05-21 16-59-53](https://user-images.githubusercontent.com/17701098/82572629-ec42a380-9b84-11ea-8c14-d01f91fa3884.png)

Linux SDL2 build with AltGr pressed - Both the right Alt and Mod2 are highlighted
![Screenshot from 2020-05-21 17-01-07](https://user-images.githubusercontent.com/17701098/82572644-f2d11b00-9b84-11ea-928a-75e2dc5ed173.png)

**Environment (please complete the following information):**
- Fedora 32 (Wayland)
- DOSBox-X 0.83.2-git

**Comment by rderooy** [comment]
Windows SDL1 build with AltGr pressed.
![Capture](https://user-images.githubusercontent.com/17701098/82573496-2496b180-9b86-11ea-83cd-e45378ecf6b5.JPG)

**Comment by ThePillenwerfer** [comment]
AltGr-4 gives a € with keyb uk, as it should, when built with SDL2 but simply types a 4 with SDL1 so it isn't something unique to the Belgium layout.

**Comment by rderooy** [comment]
BE was just an example, it happens with any international layout that uses AltGr.

**Comment by grapeli** [comment]
I cannot confirm this.
It works as it should in every possible variant. With SDL1 library attached as well as the one from the repository. It's also fine with SDL2.
`keyb be`
alt-e gives the euro sign
`keyb pl`
alt-a, alt-e, alt-c, alt-l Polish diacritics - respectively - **ą**, **ę**, **ć**, **ł**

In my opinion it can be closed. Unless @rderooy suggests what conditions must be met to confirm.

**Comment by rderooy** [comment]
@grapeli I just tried it here with my daily SDL1 build, and after typing ``keyb be`` the right ALT key (ALTGr) now functions as an Enter key, and AltGr-E does not produce the euro sign.

And this happens irrespective of the host keyboard layout.

In the screenshot you can see it registering as a the Numpad Enter key
![Screenshot from 2020-12-04 08-18-41](https://user-images.githubusercontent.com/17701098/101133610-57c3fe00-3609-11eb-8746-29e115d90fb9.png)

With the default US layout, it does not register as an Enter key, but it also does not highlight the right Alt key
![Screenshot from 2020-12-04 08-22-25](https://user-images.githubusercontent.com/17701098/101133962-f0f31480-3609-11eb-8775-9de2b1a5dd96.png)

With the SDL2 build with a US keyboard layout, the left and right ALT keys highlight properly (in addition to Mod2), and with switching to an international layout like BE, AltGr and E produces the euro symbol.

**Comment by rderooy** [comment]
Forgot to add, I don't have a mapper file.

**Comment by grapeli** [comment]
@rderooy 
I understand. Now I can confirm that it does not work under Xwaland and for me.
**Only this is by no means the fault of DOSBox-X.**
In case of Xwaland bugs you must report to this address.
https://bugs.freedesktop.org/
There you will find a really long list of bugs.

By the way, I suggest running wayland applications under wayland.
`SDL_VIDEODRIVER=wyaland`

**Comment by rderooy** [comment]
@grapeli unfortunately running under wayland is not practical for the time being.

First of all the SDL1 toolkit has no support for Wayland, so this is SDL2 territory only.

But also SDL2 has problems with Wayland, in particular the Wayland requirement for client side decorations, which means that on Gnome in particular you loose your title bar and borders. That is why my flatpak build does not enable Wayland.

Until SDL2 supports client-side-decorations (which looks like it could be a long time), SDL2 windowed applications will have to continue using XWayland.

**Comment by grapeli** [comment]
@rderooy
Nobody prevents you from using Xorg. I've really been using it without a regular user account (rootless) for over 12 years.

If you set up the right mapping, it will work under Xwayland for dosbox-x with SDL1.
```
setxkbmap -print
setxkbmap be
setxkbmap pl,us
```

**Comment by rderooy** [comment]
@grapeli sure I could, but I prefer running a modern and actively maintained environment. And I'm old enough to have installed slackware from disks and manually configuring the XFree86 config file for the right video adapter, monitor and input devices.

In any case, if your interested in SDL2 Wayland support, here is the SDL bug report with patch: https://bugzilla.libsdl.org/show_bug.cgi?id=5194

**Comment by grapeli** [comment]
I use Sway (occasionally) and it has window decorations. I don't care about them (I usually give up on them).

For years I have been using minimalist window managers in which the entire working space is taken up by the application. I don't care about icons, pretty wallpapers (staring at them), transparencies, dancing windows and other tinsel. My main concern is that the program that I run works properly.

**Comment by rderooy** [comment]
@grapeli Sway (and KDE) has wayland window decoration because it implements the _optional_ XDG-Decoration extension which implements Server-Side-Decorations, something that was rejected by Mutter which Gnome and Enlightenment uses.

**Comment by grapeli** [comment]
> @grapeli sure I could, but I prefer running a modern and actively maintained environment.

You are completely inconsistent. The SDL1.x library has not been developed for years, and the development team does not even accept all security patches. For example, a few of those used by Fedora.
https://src.fedoraproject.org/rpms/SDL/tree/master

**Comment by rderooy** [comment]
@grapeli I'm inconsistent? why? It is not my choice to maintain the SDL1 side of DOSBox-X. I just did some testing some time back with the SDL1 and SDL2 builds with various non-US keyboards, as we had multiple reports of problems, and found an issue with the SDL1 version and reported it. I don't use the SDL1 version for regular use any longer.

**Comment by grapeli** [comment]
@rderooy 
See how it works under Sway with dosbox-x sdl1 (Xwayland).
https://drive.google.com/file/d/1ySEWQqPP9Bef3s7l5uTJTHPhey5q_h2Y/view?usp=sharing

**Comment by rderooy** [comment]
Closing this as the original problem this was opened against has been solved a while back.
