### ISSUE TITLE
Save state issue with CD-ROM Mixed Mode audio tracks

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#1582]
**Describe the bug**
The game Rayman for DOS (1995) is on a mixed mode CD-ROM with 25 tracks: the first is the data track, the following are audio tracks for the background music.
Saving a state of the game and reloading later when the music has changed in the level, the game restart exactly in the right position but the music continues to play instead of restarting on the previous position on the track.

**To Reproduce**
1. At the beginning of the 1st level take a save state
2. Wait some time until the music change (CD track 14)
3. Restore the save state
4. The music continues instead of returning at previous position

**Expected behavior**
In this not official patched DOSBox version (https://www.vogons.org/viewtopic.php?f=41&t=53116) the game restart to play the audio track in the right position at the moment of state saving.

**Environment (please complete the following information):**
Windows 10 64 bit
DOSBox-X 0.83.1 x64 SDL2 (dosbox-x-windows-20200502-170825-windows.zip)
Default configuration

**Comment by Wengier** [comment]
The save state feature is NEVER officially included in DOSBox SVN. It is a patch developed by another programmer. DOSBox-X used an earlier version of the patch, which is NOT in a stable state. The patch had been further improved since then, but it is not trivial to port it directly to DOSBox-X because of the structure difference.

**Comment by MX9000** [comment]
Thanks Wengier,
I corrected my bug report by specifying that it is an unofficial version of DOSBox.
I know that the save state function in DOSBox-X is not yet stable but I was curious to try it!

**Comment by Wengier** [comment]
@MX9000 I have already ported the improved save state feature to DOSBox-X in the last 2 or 3 days. It should work better than the previous code.

**Comment by MX9000** [comment]
Thanks so much Wengier!
I'll wait for the next build and will definitely try it.

**Comment by MX9000** [comment]
I have just tested the new release dosbox-x-windows-20200630-163819-windows.zip and I confirm that the issue is solved.
Thanks again!
