### ISSUE TITLE
New default dosbox-x config dir not XDG compliant

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1588]
**Describe the bug**
With the latest build, the default dosbox config directory has changed from ~/.dosbox to ~/.dosbox-x

If we want to change the default directory, I think it should be done properly, and it should be XDG compliant. As such I am asking to change it to ~/.config/dosbox-x before the next release.

There is an enviroment variable that can overwrite the default location, but by default it is not set ($XDG_CONFIG_DIRS).

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by Wengier** [comment]
I have changed user directory from ~/.dosbox-x to ~/.config/dosbox-x as suggested in my pull request #1593. The environment variable will not be used to reduce complexity (DOSBox-X will load dosbox-x.conf from the current directory first after all).
