### ISSUE TITLE
segfault caused by the NE2000 code

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#160]
Operating system is Fedora 23 (x86_64). I was running Windows 95 OSR2.5.

The function `bx_ne2k_c::rx_frame()` causes dosbox-x to segfault when the network card gets initialized. I compared your code to Bochs' at the function `bx_ne2k_c::mcast_index()`, and the only difference is that Bochs declares the variable `crc` as `Bit32u` instead of an `unsigned long`. Once I made this change (from `unsigned long` to `Bit32u`), it worked.

I'm not at all familiar with network drivers and never wrote anything in this front (or anything worthwhile, for that matter. I'm just a wannabe programmer). You might know better what the code does and how or if my fix breaks something elsewhere.

The exact location of the offending code is in ne2000.cpp, line 1287, right after a call to `mcast_index`.

**Comment by joncampbell123** [comment]
I'm guessing when this code made it in from Ykhwong the ne2000 code was copied and pasted from an older release of Bochs that hadn't fixed that yet :)

That makes perfect sense: 'unsigned long' is 64-bit on x86_64 and 32-bit on x86. It's being used (shifted 26 bits right) as an index into an array. On 64-bit, bits can get into the upper 32 bits and come out as part of the index, thus, segfault.

**Comment by joncampbell123** [comment]
This was fixed a few commits back.
