### ISSUE TITLE
Bug in keyboard command F0

### ISSUE THREAD

**Issue by jwt27** [joncampbell123/dosbox-x#161]
I think I found a bug in keyboard.cpp.

When sending an `F0 0n` command (get/set scan code set), the keyboard should respond with ACK (`FA`) for both command bytes, and only return a third byte if the second command byte is `00`.
In the current implementation, the keyboard responds to `F0 00` with one ACK, then the scancode set, and another ACK. Changing the scancode set (`F0 0n`) is ACKed three times instead of the expected two.

See also the following references:  
[IBM keyboard datasheet](http://www.mcamafia.de/pdf/ibm_hitrc11.pdf)  
[VirtualBox source code](https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Devices/Input/PS2K.cpp)

**Comment by jwt27** [comment]
Did a quick test with the following program:

    void kb_recv()
    {
        const uclock_t timeout = 0.5 * UCLOCKS_PER_SEC;
    
        uclock_t start = uclock();
        while (uclock() < (start + timeout))
            if (inportb(0x64) & 1)
                cout << hex << "   <-- " << (unsigned)inportb(0x60) << endl;
    }

    void kb_send(byte b)
    {
        do { } while (inportb(0x64) & 2);
        outportb(0x60, b);
        cout << hex << (unsigned)b << " --> " << endl;
        kb_recv();
    }

    void kb_test()
    {
        cout << "KEYBOARD F0 TEST" << endl;
    
        byte pic = inportb(0x21);
        outportb(0x21, pic | 2);            // disable keyboard irq

        do { } while (inportb(0x64) & 2);
        outportb(0x64, 0x20);               // get controller configuration 
        do { } while (!(inportb(0x64) & 1));
        byte cfg = scancode::undo_translation(inportb(0x60));
    
        do { } while (inportb(0x64) & 2);
        outportb(0x64, 0x60);
        do { } while (!(inportb(0x64) & 8));
        do { } while (inportb(0x64) & 2);
        outportb(0x60, cfg & 0b10111111);   // disable translation

        kb_recv();  // make sure the keyboard buffer is empty

        cout << "sending F0 00" << endl;
        kb_send(0xF0);
        kb_send(0x00);

        cout << "sending F0 02" << endl;
        kb_send(0xF0);
        kb_send(0x02);
    }


Which shows the expected response on hardware (plain old IBM 1391401):

    sending F0 00
    f0 -->
       <-- fa
    00 -->
       <-- fa
       <-- 2
    sending F0 02
    f0 -->
       <-- fa
    2 -->
       <-- fa
       
While DOSBox-X produces the following output:

    sending F0 00
    f0 -->
       <-- fa
    00 -->
       <-- 1
       <-- fa
    sending F0 02
    f0 -->
       <-- fa
    2 -->
       <-- fa
       <-- fa

**Comment by joncampbell123** [comment]
Merged, thanks!

However before I close this issue, I remember that some hardware I tested against tended to return two ACKs instead of one, and that's why it was written that way. I will pull out some old PC AT hardware and check whether one or two ACKs are returned.

**Comment by jwt27** [comment]
I see you closed this already, but just to confirm, I tried a few different AT and PS/2 keyboards too; one BTC, a Compaq and three no-name boards. All respond to F0 exactly like the IBM keyboard does :)
