### ISSUE TITLE
serial: it's not clear what the serialfile driver is trying to do

### ISSUE THREAD

**Issue by voltagex** [joncampbell123/dosbox-x#1615]
https://github.com/joncampbell123/dosbox-x/blob/master/src/hardware/serialport/serialfile.cpp#L36 isn't really clear what it's trying to accomplish. Specifying a config of `serial1=file` results in a file called `serial` in the working directory, but setting `serial1=file:somethingelse` breaks the serial port (seemingly)

Would you accept a pull request with more comments and / or more logging and / or support for changing the filename used?

**Comment by joncampbell123** [comment]
It's supposed to accept the filename following "file:", what happens if you do?

Go ahead and make a pull request.

**Comment by voltagex** [comment]
If I have

```
[serial]
serial1=file
```
`InstallationSuccessful=true` is hit and COM1 works.

If I have 

```
[serial]
serial1=file:myfile
```
I get a runtime error out of the following Pascal program:


```
 program HelloSerial;
 var
   DataFile: Text;
 begin
   Assign(DataFile,'COM1');
   Rewrite(DataFile);
   Writeln(DataFile,'Hello World');
   Close(DataFile);
 end.
```

but in both cases, the dosbox console shows 

```
LOG:  368216469       FILES:file open command 0 file c:\ADAM\SERIAL.EXE
LOG:  368216469 DEBUG MISC:DOS_AllocateMemory(blocks=0x0046) = 0x07ca-0x080f
LOG:  368216469 DEBUG MISC:DOS_AllocateMemory(blocks=0x97ee) = 0x0811-0x9ffe
LOG:  368217251       FILES:file open command 0 file COM1
```

**Comment by voltagex** [comment]
Sorry, user error: the config should be 

```
[serial]
serial1=file file:myfile
```
