### ISSUE TITLE
Geometry detection fails on DOS ≤ 3.21 partitions

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1623]
**Describe the bug**
If a partition was created and formatted with DOS 2.0-3.21 the automatic geometry detection fails. This is because the partitioning system prior to DOS 3.3 was different. As such you always need to manually specify the geometry.

Note: this applies to:
* PC DOS 2.0-3.2
* MS-DOS 3.21
Older MS-DOS versions did not have "standardised" partitioning and formatting tools as everything up to that point was OEM specific.

e.g.
```
Z:\>imgmount c hdd.img
Could not extract drive geometry from image.
Use parameter -size bps,spc,hpc,cyl to specify the geometry
Unable to detect geometry
```
**To Reproduce**
Using PC DOS 3.2 in this example,
```
imgmake hdd.img -t hdd -size 20 -nofs
imgmount 2 hdd.img -size 512,32,2,640
boot Disk01.img
```
Run fdisk and create a primary DOS partition for the whole disk. After a reboot run:
```
imgmount 2 hdd.img -size 512,32,2,640
boot Disk01.img

select a: c:\dos 1 us
```

**Expected behavior**
Automatic geometry detection to succeed.

**Environment (please complete the following information):**
 - Fedora 32
 - DOSBox-X 0.83.2-git (today's build)

**Other**
Linux fdisk reports the partition as follows:
```
$ fdisk -l hdd.img
Disk hdd.img: 20 MiB, 20971520 bytes, 40960 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start   End Sectors Size Id Type
hdd.img4   *       32 40959   40928  20M  4 FAT16 <32M
```

**Comment by joncampbell123** [comment]
Use the "expert mode" aka "x" of fdisk to see the actual C/H/S values of the partition start/end.

**Comment by rderooy** [comment]
$ fdisk hdd.img

Welcome to fdisk (util-linux 2.35.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): x

Expert command (m for help): p
Disk hdd.img: 20 MiB, 20971520 bytes, 40960 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start   End Sectors Id Type       Start-C/H/S End-C/H/S Attrs
hdd.img4   *       32 40959   40928  4 FAT16 <32M       0/1/1  639/1/32    80

**Comment by joncampbell123** [comment]
The end C/H/S is the address of the last sector, not the C/H/S count.

So if the last sector is C/H/S 639/1/32, then the geometry is 639+1 / 1+1 / 32 = 640/2/32.

Note that sectors count from 1, cylinder and head count from 0.

**Comment by rderooy** [comment]
Yes, that is what I figured, but I don't understand the head-count. It shows a start-head count of 1 and an end-head count of 1, while there should be 2 heads.

**Comment by joncampbell123** [comment]
Sectors count from 1, so that is the first sector of the track. Head is 1 because MS-DOS likes to create partitions starting on track boundaries (fdisk even warns you about this when you create DOS partitions). MS-DOS cannot start from C/H/S 0/0/1 because that would collide with the master boot record / partition table.

**Comment by joncampbell123** [comment]
The result is that there is empty unused space between the MBR and the first partition. Some bootloaders like GRUB take advantage of that to install themselves there (where on modern drives the first partition is 63 sectors from the start of the drive).

**Comment by rderooy** [comment]
Ok. thanks. In any case, Linux fdisk is able to get the necessary geometry data from the partition, so I guess this is a feature request for having DOSBox-X also detect it for these older partitions types.

**Comment by joncampbell123** [comment]
There is auto geometry detection, but it's currently only called if you're mounting the disk image to a drive letter.

Otherwise if your geometry happens to have 16 heads and 63 sectors/track it happens to guess right.

**Comment by joncampbell123** [comment]
Looking at the code it seems silly to have one set of geometry detection if mounting a FAT filesystem and an entirely different geometry detection if mounting with -fs none. The two should be carefully brought together into one function.

**Comment by joncampbell123** [comment]
Try the latest commit. It works for me now given an MS-DOS 3.30 bootable disk image with cyl=93 heads=16 sectors/track=11

**Comment by rderooy** [comment]
@joncampbell123 

The change you made is useful, and will help in cases where a disk is partitioned with DOS ≥ 3.3 but the filesystem has yet to be created.

Unfortunately it does NOT help with DOS ≤ 3.21 as the partition layout of DOS 2.0-3.21 is simply different to that of later DOS versions. Trying to mount a PC-DOS 3.2 HDD image, formatted or not, still fails.

**Comment by rderooy** [comment]
**DOS 1.x**
Has no HDD support.

**DOS 2.0-3.21**
Uses an old partition layout, partition limited to 31 or 32MB. You could only have 1 DOS partition (other partitions for non-DOS are allowed to exist).
```
$ fdisk -l hdd.img 
Disk hdd.img: 20 MiB, 20971520 bytes, 40960 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start   End Sectors Size Id Type
hdd.img4   *       32 40959   40928  20M  4 FAT16 <32M
```

**DOS 3.3**
Uses the new partition layout, but still limited to 31 or 32? MB partitions. Multiple DOS partitions are allowed to exist (DOSBox internal DOS only accesses the first one).
```
$ fdisk -l hdd.img 
Disk hdd.img: 504 MiB, 528482304 bytes, 1032192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot  Start     End Sectors  Size Id Type
hdd.img1   *        32   65535   65504   32M  4 FAT16 <32M
hdd.img2         65536 1032191  966656  472M  5 Extended
hdd.img5         65568  131071   65504   32M  4 FAT16 <32M
hdd.img6        131104  196607   65504   32M  4 FAT16 <32M
hdd.img7        196640  262143   65504   32M  4 FAT16 <32M
hdd.img8        262176  327679   65504   32M  4 FAT16 <32M
hdd.img9        327712  393215   65504   32M  4 FAT16 <32M
hdd.img10       393248  458751   65504   32M  4 FAT16 <32M
hdd.img11       458784  524287   65504   32M  4 FAT16 <32M
hdd.img12       524320  589823   65504   32M  4 FAT16 <32M
hdd.img13       589856  655359   65504   32M  4 FAT16 <32M
hdd.img14       655392  720895   65504   32M  4 FAT16 <32M
hdd.img15       720928  786431   65504   32M  4 FAT16 <32M
hdd.img16       786464  851967   65504   32M  4 FAT16 <32M
hdd.img17       852000  917503   65504   32M  4 FAT16 <32M
hdd.img18       917536  983039   65504   32M  4 FAT16 <32M
hdd.img19       983072 1032191   49120   24M  4 FAT16 <32M
```

**DOS 4.0**
New partition layout + partitions up to 2014MB (should have been 2GB, but is buggy, limiting the actual max capacity). Also DOS 4.0 is not happy with the DOS 5.0 formatted disks created by IMGMAKE. DOS 4.0 can read the filesystem image, but doing a DOS 4.0 SYS on such an image will fail to boot. After re-formatting with DOS 4.0 format, it will boot fine.
```
$ fdisk -l hdd.img 
Disk hdd.img: 1023.77 MiB, 1073479680 bytes, 2096640 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start     End Sectors    Size Id Type
hdd.img1   *       63 2096639 2096577 1023.7M  6 FAT16
```
**DOS 5.0-7.0**
Partitions up to 2048MB actually work.

$ fdisk -l hdd.img 
Disk hdd.img: 503.52 MiB, 527966208 bytes, 1031184 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe3657373

Device     Boot Start     End Sectors   Size Id Type
hdd.img1   *       63 1031183 1031121 503.5M  6 FAT16

**Comment by joncampbell123** [comment]
Please run fdisk without the -l option, then type 'x' to get expert mode, and then print the partition table. Expert mode shows C/H/S geometry.

Disk images I have of MS-DOS 2.x and 3.x seem to autodetect correctly in DOSBox-X.

DOSBox-X does not yet read extended partitions (neither does DOSBox SVN nor any other fork).

**Comment by rderooy** [comment]
It is still the same 20MB disk image as before.
```
$ fdisk hdd.img 

Welcome to fdisk (util-linux 2.35.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): x

Expert command (m for help): p
Disk hdd.img: 20 MiB, 20971520 bytes, 40960 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start   End Sectors Id Type       Start-C/H/S End-C/H/S Attrs
hdd.img4   *       32 40959   40928  4 FAT16 <32M       0/1/1  639/1/32    80
```
![guest os_001](https://user-images.githubusercontent.com/17701098/84491801-673f3b80-aca5-11ea-9917-da5c47fc9cb7.png)

**Comment by rderooy** [comment]
Exactly the same with MS-DOS 3.21
![guest os_002](https://user-images.githubusercontent.com/17701098/84493566-3b718500-aca8-11ea-8d12-4f0a34a59c69.png)

**Comment by rderooy** [comment]
And with PC DOS 2.1
![guest os_003](https://user-images.githubusercontent.com/17701098/84494056-1a5d6400-aca9-11ea-87eb-7df8a9acabde.png)

**Comment by rderooy** [comment]
Using vbindiff here are header differences between MS-DOS 3.21 and 3.30 for a 20MB disk. In both cases, I created a blank image (imgmake -nofs) and let DOS do the partitioning and formatting.

![Screenshot from 2020-06-12 15-18-08](https://user-images.githubusercontent.com/17701098/84507288-db3b0d00-acc0-11ea-9827-22c028b98206.png)

**Comment by rderooy** [comment]
Mounting as ``imgmount 2 hdd.img -fs none``, it complains, but then mounts it as drive 2 anyway. But in the logs I see that it detected the WRONG geometry
```
LOG: Mapping BIOS DISK C/H/S 40/16/63 as IDE 40/16/63
```
And booting obviously fails.
![guest os_000](https://user-images.githubusercontent.com/17701098/84509716-64a00e80-acc4-11ea-9d80-7d7d0ce899b5.png)

**Comment by rderooy** [comment]
Did a bit more tracing through the code, and found the issue. Basically all the locations it is reading to determine the geometry are different.

In dos_programs.cpp in the DetectGeometry() method, if I put this hack in, it works with both DOS 3.21 and DOS 3.3+

       Bitu pe1_size = host_readd(&buf[0x1ca]); //DOS 3.3+ partition table
        if (pe1_size == 0) {
            pe1_size = host_readd(&buf[0x1fa]); //DOS 2.0-3.21 partition table
            ptype = buf[0x1f2];
            heads = buf[0x1f3] + 1u;
            sectors = buf[0x1f4] & 0x3fu;
            starthead = buf[0x1ef];
            startsect = (buf[0x1f0] & 0x3fu) - 1u;
            startcyl = (unsigned char)buf[0x1f1] | (unsigned int)((buf[0x1f0] & 0xc0) << 2u);
            endcyl = (unsigned char)buf[0x1f5] | (unsigned int)((buf[0x1f4] & 0xc0) << 2u);
        }
        if (pe1_size != 0) {

**Comment by joncampbell123** [comment]
Wait... DOS 3.x FDISK automatically chooses the LAST entry in the partition table?

**Comment by rderooy** [comment]
@joncampbell123 I don't know. I used vbindiff to find the DOS 3.3+ hex values, and then looked where they are located with DOS 3.21 and adjusted the locations.

I'm doing something else right now. But will try to clean it up later, do some further testing and send a pull request.
