### ISSUE TITLE
Hard coded fonts for Printer emulation

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1632]
**Is your feature request related to a problem? Please describe.**
src/hardware/parport/printer.cpp contains hard-coded font filenames and path. This is not only inflexible, it requires additional steps from the user to get printing to work.

Example, it requires "courier.ttf" in ~/.config/dosbox-x/FONTS on Linux. And the same file on Windows in a FONTS directory where the dosbox-x.exe binary is located.

Ideally, it would use the old location by default if it exists, and if not, it would use the installed system-fonts. You can see a mapping of Windows and Linux fonts to the fonts that it needs here:
https://github.com/joncampbell123/dosbox-x/wiki/Guide%3ASetting-up-printing-in-DOSBox%E2%80%90X#setting-up-fonts-for-the-emulated-printer

I had a quick look at coding this, but I'm not skilled enough in C++ to do it properly. I can hack it to load the proper system font file, depending on Windows or Linux, but then I just end up hard-coding system paths, which should also be avoided.

For Linux, it seems the recommended method is to use FontConfig to locate a suitable font by style http://cheshirekow.github.io/cpp_fontconfig_page.html
Simply using a hard-coded filename and pointing it to /usr/share/fonts will not work, as the fonts are often in deeper sub-directories. For example on my Fedora system a suitable courier font would be LiberationMono-Regular.ttf but that is located on the filesystem as /usr/share/fonts/liberation-mono/LiberationMono-Regular.ttf

For Windows, either find the FONT directory using something like SHGetKnownFolderPath() to get FOLDERID_Fonts and still use hard-coded filenames, or using something like EnumFontFamiliesExA() to find a matching style.
https://docs.microsoft.com/en-gb/windows/win32/api/wingdi/nf-wingdi-enumfontfamiliesexa?redirectedfrom=MSDN

For MacOS it seems that the right way is to use Cocoa, and more specifically NSFontManager
https://developer.apple.com/documentation/appkit/nsfontmanager

**Comment by ThePillenwerfer** [comment]
I'm the same as you as regards not knowing the C syntax, and DOSBox-X is too complicated a thing to learn on.  What I thought of was adding a line in the .conf file that simply says `printerfont=~/.fonts/courier.ttf` or `printerfont=c:\wndows\fonts\couri.ttf.`  I'm yet to work out what the others are for or how to make any use of them if I wished to.

The other thing I was wondering is if on the latest version the fonts need to be in `~/.config/dosbox-x/FONTS` are still in `.dosbox/FONTS.`

**Comment by rderooy** [comment]
I used to do software development a long, long time ago (20+ years ago). Just not with C and C++. So I am able to understand it mostly and make some minor modifications. Just this was a bit too much, since I did not want to do a dirty hack, but wanted to wire it up properly.

And I don't want to put a hack in for the courier font either, although that is the one that is typically used. The other fonts you should be able to use if you try something like an old version of WordPerfect and then you can select different printer fonts.

As to the font directory, it is now ~/.config/dosbox-x/FONTS on Linux. I have confirmed it, and the updated **draft** printing guide has been updated.

**Comment by Wengier** [comment]
The latest DOSBox-X code in my pull request will now use the installed system fonts it the fonts do not exist in the old location, as follows:

FONTS\roman.ttf:
Windows:
               ```C:\Windows\Fonts\times.ttf```
Linux:
               ```/usr/share/fonts/liberation-serif/LiberationSerif-Regular.ttf```

FONTS\sansserif.ttf:
Windows:
               ```C:\Windows\Fonts\arial.ttf```
Linux:
               ```/usr/share/fonts/liberation-sans/LiberationSans-Regular.ttf```

FONTS\courier.ttf
Windows:
               ```C:\Windows\Fonts\cour.ttf```
Linux:
               ```/usr/share/fonts/liberation-mono/LiberationMono-Regular.ttf```

FONTS\script.ttf:
Windows:
               ```C:\Windows\Fonts\freescpt.ttf```
Linux:
               ```/usr/share/fonts/freescpt.ttf```

FONTS\ocra.ttf:
Windows:
               ```C:\Windows\Fonts\Ocraext.ttf```
Linux:
               ```/usr/share/fonts/Ocraext.ttf```

Therefore, copying to the FONTS folder is no longer required in the latest code.
