### ISSUE TITLE
Connectivity issue

### ISSUE THREAD

**Issue by emanuelepulcidoria** [joncampbell123/dosbox-x#1647]
Dosbox-x is not able to read the SERIAL part of the config file correctly

**To Reproduce**
1. Create server.conf in the Dosbox-x folder (file attached)
2. Launch a Dosbox with the comand: dosbox -console -conf server.conf
[server.txt](https://github.com/joncampbell123/dosbox-x/files/4761070/server.txt)

3. In the console window I can see LOG: Invalid type for serial1 

**Expected behavior**
In the console window I should see:
LOG: Serial1: Nullmodem server waiting for connection on port 23

**Environment (please complete the following information):**
 - WIndows 10
 - DOSBox-X 0.83.2

**Additional context**

**Comment by emanuelepulcidoria** [comment]
I found the problem: it is the way I unzipped the files:
I extracted everything but because there are so many files with the same name I got question about overwriting files already existing. If you press YES TO ALL, Dosbox-x works but I get that error.
I tried to unzip everything without overwriting (NO TO ALL) and it finally worked!

**Comment by emanuelepulcidoria** [comment]
Maybe it is worth for the future split the .zip files for the different version of Windows...32, 64, etc.

**Comment by rderooy** [comment]
I don't know what program you used to unzip, but the files are in different directories on purpose.

**Comment by emanuelepulcidoria** [comment]
I used 7zip, and yes the files are in different folders but I did not notice at a first glance at the beginning. So just to make it clear:
- for windows 64 you unzip the x64 folder;
- for windows 32 you unzip the win32 folder;
is that correct?

**Comment by rderooy** [comment]
That is one way of doing it, yes. Windows 64bit should be able to run either the 32 or 64bit version.

Again, for the next version which should be out early next month, there should be a windows installer (.exe) version.

**Comment by emanuelepulcidoria** [comment]
ok thanks, you said that this is one way of doing it.
what is the right way according to you that you know the software.
I am using Dosbox-x on a Windows 64 machine but I want to run it also on a Windows XP 32 machine that I have and I want to unzip the files in the correct way.
All the connectivity now works perfectly and I have been able to connect through modem (with the new phonebook feature) a host and a client both through the 127.0.0.1 and also on my router IP address. Now this was possible also on Dosbox-staging.
What I want to test now is this connection between my 2 machines, I could not test that with Dosbox-staging because it did not support Windows XP 32 bit.

**Comment by rderooy** [comment]
With the zip files, it is really up to you. You can unpack only the version you want or you can unpack them all into different directories. Whatever you want.

Also, I don't think anyone is doing active testing with older Windows versions, so you may run into some issues.

**Comment by emanuelepulcidoria** [comment]
@rderooy I am not able to run Dosbox-x on my old Windows XP 32 bit system. I am really interested in testing this modem connection between 2 different machine across the net because there is where Dosbox-staging failed. Are you interested in doing this test between the 2 of us. I am happy to host the server.

**Comment by rderooy** [comment]
@emanuelepulcidoria I suspect your running into https://github.com/joncampbell123/dosbox-x/issues/1650

Basically grab the 32bit mingw zip file instead.

**Comment by Wengier** [comment]
@rderooy Visual Studio builds of DOSBox-X 0.83.1 did not work in Windows XP either. So always use the MinGW builds for Windows XP.

**Comment by emanuelepulcidoria** [comment]
Ok, it does run now on Windows XP 32 bit but whatever version I try: mingw, mingw-lowend, mingw-sdl2, mingw-sdldraw I again get the same error where the SERIAL part of the config file is not read correctly...

**Comment by emanuelepulcidoria** [comment]
Do you have any suggestion regarding this issue? Dosbox-x runs on Windows XP 32 bit but all the version I found in the MinGW zip file are not able to read the SERIAL part of the config file correctly and I get again the message in the console: Invalid type for serial1

**Comment by emanuelepulcidoria** [comment]
It looks to me that all these versions have been compiled without the SERIAL feature built in it.
