### ISSUE TITLE
ESS AudioDrive emulation makes Windows 95 driver unhappy

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#165]
I've developed the ESS emulation as far as I can, but I'm currently at a loss as to why Windows 95's driver is able to play one sound (the Windows startup sound), but then the driver complains the Audio Drive is not functioning correctly. I've tried implementing other registers and a few hacks to no avail.

It appears to be using an undocumented ESS DSP command 0xC3 to read something, and 0xC2 to write something, at startup or DSP reset. Not sure what it means.

The driver uses the auto-init mode of the ESS playback, but then allows the audio to stop on the last block by switching off the auto-init mode while playback is going. Then it attempts to read from the DSP, reset the DSP, read back the ack, then reset the DSP again.

I have no idea what I can do to make it work with Windows 95.

If anyone can help me on this, I'd appreciate it.

**Comment by ghoul8765** [comment]
Is there a reference driver setup for Win3.1 or Dos? Also, I wonder if the linux driver writes those undocumented commands, although probably not.

**Comment by joncampbell123** [comment]
I can't get the Windows 3.1 driver to see the card. Haven't tried Linux yet.

**Comment by ghoul8765** [comment]
I'll try to replicate your post, thanks!

**Comment by ghoul8765** [comment]
I replicated most of the code path of the 95 ESS driver in emulation. After disabling "ESS_CheckDMAEnable", then there is no audio but there is also no error and the 95 driver isn't disabled.

**Comment by ghoul8765** [comment]
I have this from the logs:
ESS DMA stop for normal dma mode
 dsp_reset port: 6, val8: 3
 DSP:Reset
 dsp_reset port: 6, val8: 0
 write_data port: 12, val8: 198
 dsp_reset port: 6, val8: 1
 DSP:Reset
 dsp_reset port: 6, val8: 0
 write_data port: 12, val8: 16
 write_data port: 12, val8: 128
 DSP Command 10

Are the writes all handled as expected?

**Comment by joncampbell123** [comment]
Currently, the code only tries to map ESS register changes to existing Sound Blaster 16 DMA transfer code. The ESS code does not use the MODE_DAC mode.

DSP command 0x10 is the command to send one sample to the DSP output (DAC mode). I think what the driver is trying to do there is make sure the audio output is centered to 0V by writing 0x80 (128) to the DAC.

**Comment by ghoul8765** [comment]
Thank you for the help. It sounds like the issue is upstream. I tried the other OS drivers, too.

I wonder if there is any relevant audio driver source code in the 95 DDK. Otherwise, it may be worthwhile to test the linux driver.

**Comment by ghoul8765** [comment]
The 95 sbpro driver works well with the ESS688 device. :)

**Comment by ghoul8765** [comment]
This code should make 95 happy:
<pre lang=""><code>--- sblaster-X.cpp	2016-02-20 01:56:50 -0500
+++ sblaster-X-2.cpp	2016-02-20 03:58:15 -0500
@@ -520,6 +520,7 @@ void SB_OnEndOfDMA(void) {
 		if (sb.ess_playback_mode) {
 			LOG(LOG_SB,LOG_NORMAL)("ESS DMA stop");
 			ESSreg(0xB8) &= ~0x01; // automatically stop DMA (right?)
+			if (sb.dma.chan) sb.dma.chan->Clear_Request();
 		}
 	} else {
 		sb.dma.left=sb.dma.total;
</code></pre>

**Comment by joncampbell123** [comment]
That fixed it! Thanks!
Now to figure out why 16-bit PCM playback isn't yet working properly.

**Comment by ghoul8765** [comment]
Thank you for the other updates!
