### ISSUE TITLE
Version 0.83.2 can't run in Windows 7 (SetThreadDpiAwarenessContext)

### ISSUE THREAD

**Issue by AK5GH** [joncampbell123/dosbox-x#1650]
**Describe the bug**
The latest version of Dosbox-X (0.83.2) can't run in Windows 7!
The error message says something like (translation):

> "Procedure entry point SetThreadDpiAwarenessContext is not found in USER32.DLL"

The use of -nodpiaware command line switch does not help.
However, prior to the last update, versions 0.83.1 and 0.83.0 were running
just fine on the same system 
(without the -nodpiaware switch and with "dpi aware" option = true) 

**To Reproduce**
1. Use Win7 Pro SP1 OS (any language)
2. Click on 'dosbox-x.exe' (no need to specify any command line options or .conf files)
3. See the system error right away (and the application won't even get started)

**Expected behavior**
Just as in _all_ previous versions (up to 0.83.1).

**Environment (please complete the following information):**
 - Operating system: Win7 Pro SP1 32-bit 
    (I did not try Win7 64-bit, but my guess it would be the same)
 - DOSBox-X release version 0.83.2
 - Used configuration: N/A

**Additional context**
If I may suggest, remove the mandatory requirement for the "SetThreadDpiAwarenessContext" function on Win32 and Win64 platforms. Call this function _only if_ Windows 10 (or at least Windows 8 -- _probably_, not tested) is detected.

**Comment by Wengier** [comment]
@AK5GH Have you tried the MinGW builds of DOSBox 0.83.2? Do they work on Windows 7?

**Comment by joncampbell123** [comment]
I see that on line 8357 there is the _MSC_VER case that calls it directly in a way that causes a dependency, vs the MinGW builds that use GetProcAddress and LoadLibrary right below it.

@Wengier Was this your work? Why not the same code for both _MSC_VER as MinGW? It would remove the SetThreadDpiAwarenessContext() dependency and allow running under Windows 7 again.

**Comment by Wengier** [comment]
@joncampbell123 Yes, I did plan to use the same code for both. That is why I asked him if the MinGW build works on Windows 7 before doing the merging.

**Comment by AK5GH** [comment]
> Have you tried the MinGW builds of DOSBox 0.83.2? Do they work on Windows 7?

@Wengier Yes, all 4 kinds of MinGW Win32 executables do _run_ in Windows 7. Didn't do any further testing, though.

**Comment by Wengier** [comment]
@AK5GH Thanks for the feedback. I will make the Visual Studio builds run in Windows 7 too just like the MinGW builds.

**Comment by joncampbell123** [comment]
@AK5GH Though I don't test it often, the MinGW builds are intended to run as downlevel as Windows XP, since VS2019 won't target XP properly (and the XP target is deprecated).

**Comment by AK5GH** [comment]
@joncampbell123 Understood. Thanks for the insights about the support for XP. One day the support for XP might prove useful. 
However, I do hope the Windows 7 compatibility of the native Win32 and Win64 versions would be restored in the upcoming release 0.83.3. Thanks for your quick attention to this issue!

**Comment by joncampbell123** [comment]
@Wengier Are you addressing the MinGW/VS2019 split regarding that function or should I merge them together?

**Comment by Wengier** [comment]
@joncampbell123 I already merged that of course, but I wanted to do more cleanups to the overlay drive support before submitting the pull request.

**Comment by Wengier** [comment]
I have ready made the pull request by now.

**Comment by AK5GH** [comment]
Fixed in version 0.83.3
