### ISSUE TITLE
Current code won't build SDL2 in VS2019

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1654]
Building for SDL2/Win32 with current code, in VS2019, produces this error:

`10>LIBCMT.lib(ftol2.obj) : error LNK2005: __ftol2_sse already defined in sdl2.lib(SDL_stdlib.obj)`

This is with code up to https://github.com/joncampbell123/dosbox-x/commit/8d88dadac16c197dfe1d059653cd6e4cb0d9e26d

EDIT: This occurs with Win32; x64 builds correctly.

**Comment by Wengier** [comment]
I have not tried VS2019 yet, but the SDL2 code certainly builds in VS2015, which I typically use.

**Comment by Wengier** [comment]
Just tried to build the latest code (SDL2 x64) in Visual Studio 2019 16.5.4, and it worked too! So I think your VS project may not be clean.

**Comment by emendelson** [comment]
x64 does build successfully. Win32 produces the error. I've edited the heading to show this.

**Comment by Wengier** [comment]
@emendelson Commenting out the following function in the file vs2015\sdl2\src\stdlib\sdl_stdlib.c will make the Win32 build compile too:

```
void
_ftol2_sse()
{
    _ftol();
}
```

**Comment by emendelson** [comment]
@Wengier Yes, that worked. Thank you!
