### ISSUE TITLE
Euro symbol?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1655]
s there any possibility that DOSBox-X could support the euro symbol in codepage 858? This was included in PC-DOS 7 and 2000, I believe, though never in MS-DOS.

Also, for many years, my DOSBox/DOSBox-X fork included an option to use the euro instead of C-cedilla as character 128 in the default font. Because of changes in the DOSBox-X code, I haven't been able to make this option work for a long time, and I wonder if anyone can suggest an easy way to restore it. I implemented it in a very clumsy way, using a complete replacement font, which I've attached here if anyone wants to use the euro symbol that I added to it.

[dosbox-x-eurofont.txt](https://github.com/joncampbell123/dosbox-x/files/4775100/dosbox-x-eurofont.txt)

**Comment by Wengier** [comment]
@emendelson I think the current DOSBox-X code already supports the Euro symbol in code page 858. Tried with the following:

keyb uk 858
chrset.exe

Where the program chrset.exe is downloaded from your website, i.e. http://www.columbia.edu/~em36/wpdos/chrset.exe

Then the euro symbol (€) will indeed be shown at position D5.

**Comment by emendelson** [comment]
@Wengier - you are absolutely right about keyb uk 858. Thank you.

The other issue involves an option to use the euro instead of C-cedilla in code page 437. I seem to be getting that working again in my fork, and when I do, I'll close this issue. Thank you again.

**Comment by emendelson** [comment]
@Wengier - you are absolutely right about keyb uk 858. Thank you.

The other issue involves an option to use the euro instead of C-cedilla in code page 437. I seem to be getting that working again in my fork, and when I do, I'll close this issue. Thank you again.

**Comment by Wengier** [comment]
@emendelson I have already added the euro config option to display the Euro symbol instead of the specified ASCII character (such as 128 for C-cedilla) in any codepage in my latest pull request.
