### ISSUE TITLE
Opening Mapper Editor from menu causes failed assertion

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1659]
**Describe the bug**
Running the latest development build, trying to open the mapper editor crashes dosbox-x SDL1 (cannot try SDL2, as it's compile fails).

Log shows:
```
dosbox-x: sdl_mapper.cpp:2924: void SetActiveEvent(CEvent*): Assertion `event' failed.
Aborted
```
**To Reproduce**
- start latest dosbox-x build
- Main -> Mapper editor (or press the F12-M hotkey)
- crash

**Expected behavior**
no crash

**Environment (please complete the following information):**
 - Fedora 32
 - DOSBox-X 0.83.3-git

**Comment by joncampbell123** [comment]
This has been fixed in the latest commit.
