### ISSUE TITLE
Dosbox-x HX build stuck in fullscreen mode

### ISSUE THREAD

**Issue by Magstriker** [joncampbell123/dosbox-x#1663]
The HX DOS Extender tailored build of DOSBox-X is stuck in fullscreen mode and neither making a config file, nor adjusting the options in the menus, nor pressing the hotkeys, nor changing the hotkeys, nor setting flags from the command prompt when launching works. All the other builds deal with fullscreen just fine. Is this a way to make DOSBox-X work better with HX? If so, sorry for the false alarm.

Downloaded zip: dosbox-x-mingw-hx-dos-20200531220949
Version: dosbox-x 0.83.2
OS: Windows 10 Pro 64x

**Comment by joncampbell123** [comment]
The HX builds happen to run on Windows but they are made for the HX DOS extender environment.

The GUI environment for HX is so primitive that it does not support window-in-window updating and does not draw window decorations. If the window is smaller than the screen, then the part not covered by the screen is never redrawn. Mouse capture and motion handling work best when the full screen is covered as well. So in it's intended environment, there's no point not filling the screen.

**Comment by Magstriker** [comment]
Oh okay. Sorry for misunderstanding.
