### ISSUE TITLE
'Phonebook file' feature on DosBox-X for Mac

### ISSUE THREAD

**Issue by Alle82** [joncampbell123/dosbox-x#1667]
**Describe the bug**
I am not able to emulate modem phone call with an IP address. 

**To Reproduce**
1. Add 'phonebookfile=phonebook-0.75.0.txt' in the conf file 
2. Compile phonebook-075.0.txt with 5551234 127.0.0.1:12345 and save it in the conf file folder location
3. Open the game (688 attack in my car)
4. Try to call the number 5551234

**Expected behavior**
Expected: The modem emulator to call IP 127.0.0.1 port 12345
What happens: modem call 5551234 port 23
**Environment (please complete the following information):**
 - macOS Catalina
 - DOSBox-X release version 0.74-3-1
 - Used configuration, DOSBox 0.74-3-1 Preferences

**Comment by rderooy** [comment]
can you try running dosbox-x from the commandline? There should be logging output which should contain something along these lines:

LOG: SERIAL: Loading phonebook from /home/robert/.config/dosbox-x/phonebook-0.83.3.txt
LOG: SERIAL: Mapped phone 5551234 to address cavebbs.homeip.net

**Comment by rderooy** [comment]
Also, are you sure your running DOSBox-X, as your version number indicates vanilla dosbox, which does NOT have phonebook support.

**Comment by Alle82** [comment]
You are right, now I am on the correct version 0.83.2.
I have now this issue:
LOG: Invalid type for serial1
serial1 is set in conf file as:
serial1       = modem listenport:12345

**Comment by Alle82** [comment]
Upgrade to version 0.83.2
