### ISSUE TITLE
Support GLSL/GLSLP Shaders

### ISSUE THREAD

**Issue by abdulahmad** [joncampbell123/dosbox-x#1673]
GLSL/GLSLP format has a lot of support due to Retroarch and there are a lot of great shaders available in that format. I'd like to ask support be added for GLSL/GLSLP in the way Retroarch does it. GLSLP allows chaining together multiple shaders which makes it especially powerful, and the Retroarch UI also allows modifying of Shader Parameters on the fly which also makes it powerful.

I've tried looking for .fx shaders that are the equivalent of the shaders I like in Retroarch, but they mostly aren't available. The handful of ones that are available in .fx are usually in a format for Reshade (which is possible to use with Dosbox but isn't seamless and has it's own issues) which isn't compatible with Dosbox-X.

**Comment by Wengier** [comment]
I have already added support for GLSL shaders in the latest code by porting the code from DOSBox SVN. Tested with the shader files "ScanLine.glsl" and "crt-lottes.glsl" (downloaded from: https://github.com/tyrells/dosbox-svn-shaders/tree/master/crt) and seem to work at least on the SDL1 builds. The config option "glshader" (in [render] section) can be used to specify a GLSL shader file when the output is set to "opengl" or "openglnb" (if compatible with the shader).

**Comment by Wengier** [comment]
The "sharp" is a built-in GLSL shader. By setting "glshader=sharp", it renders largely in the pixel-perfect mode for "output=opengl" or "output="openglnb".

**Comment by BobbyMcJefferson** [comment]
I just checked and glsp doesn't seem to be supported yet. I tried to load the [scalefx+rAA.glslp](https://github.com/scummvm/scummvm-shaders/blob/master/base/scalefx/scalefx%2BrAA.glslp) shader from ScummVM in Dosbox-X but it doesn't seem to work.

**Comment by n1tr0ms** [comment]
Still no GLSLP shader variants support and minor compability with glsl shaders from here - https://github.com/libretro/glsl-shaders
CRT-Royale doesn't work too:
https://github.com/libretro/glsl-shaders/blob/master/crt/crt-royale.glslp
https://github.com/libretro/glsl-shaders/blob/master/crt/crt-royale-ntsc-256px-composite.glslp
https://github.com/libretro/glsl-shaders/blob/master/crt/crt-royale-ntsc-320px-composite.glslp
