### ISSUE TITLE
Lutris support - executable as CLI argument not working

### ISSUE THREAD

**Issue by gombosg** [joncampbell123/dosbox-x#1675]
**Describe the bug**
Lutris runs Dosbox runners as `dosbox %s` where `%s` is the game executable. Vanilla Dosbox supports this, it just runs the game executable from that folder without any config whatsoever.

**To Reproduce**
Dosbox-X doesn't support that e.g. if I do
`./dosbox-x /gamedir/GAME.BAT`
then it says
`WARNING: Unknown option gamedir/GAME.BAT (first parsing stage)`
(EDIT: same if file name is given in quoted)

**Expected behavior**
It should start the game.

**Environment (please complete the following information):**
 - Fedora 32
 - Fresh compile from master 8cf8188
 - No config

**Additional context**
This is supposed to be working judging from the manual page in the `intro` command and looking at how vanilla Dosbox works.

**Comment by Wengier** [comment]
I have already fixed the issues in my pull request #1695.

**Comment by gombosg** [comment]
Thanks, works, closing!
