### ISSUE TITLE
Ultima VI incorrectly assigns the instrument on song 4 and 8 while using mt-32 emulation and Munt.

### ISSUE THREAD

**Issue by Razor221** [joncampbell123/dosbox-x#1677]
Ultima VI has problems while using mt-32 as midi music player. Songs 4 and 8 the instrument set as synth instead of piano and because of that those songs don't sound right at all. This happens while using the built-in mt-32 emulation and also munt. 

Everything is normal while using the official DOSBox 0.74-3 and the latest DOSBox SVN Daum so i don't think it's a problem with my installation of munt or the rom that i'm using. 
I added the screenshots of the control panel of the mt-32 in munt for song 4 and 8 with dosbox-x and official DOSBox. That's actually how i figured out what's the problem.

Screenshot of dosbox-x assigns the wrong instrument
![Screenshot_1](https://user-images.githubusercontent.com/53368916/85223425-ca2e8200-b3cb-11ea-9202-d54d2c2dbd9c.png)
Screenshot of normal behavior with official DOSBox.
![Screenshot_2](https://user-images.githubusercontent.com/53368916/85223439-e2060600-b3cb-11ea-85c1-cee3495e7b95.png)
 
I use windows 10 1909. Latest dosbox-x release but i also tried version 0.83 and same behavior happens. SDL or SDL2 doesn't make any difference result is the same.

**Comment by rderooy** [comment]
1) Is there an easy way to trigger the game to play the effected song? Can you provide either some steps, or a save file that causes it to play one of the songs?

2) DOSBox ECE also has MT-32 support integrated, does it have the same issue?

**Comment by Razor221** [comment]
1. yes there is. just press number keys to toggle between songs in the main menu.
2. I didn't try it. but i will now and will post the result.

**Comment by rderooy** [comment]
Just to be clear, your mt32.romdir is set to a valid path with the ROMs? Also which ROMs does the directory contain, the MT-32 Old, New or CM32L?

Can you also start dosbox-x with the -console switch and look for MIDI messages?

**Comment by Razor221** [comment]
I use CM32L Rom but i also tried the old mt-32 rom result is same with both built-in emulation and munt.
Just in case this is how my midi section of the config file set up for capturing the console.
![Screenshot_7](https://user-images.githubusercontent.com/53368916/85228267-32d92700-b3eb-11ea-9129-dd2a923a1a70.png)

This is the output of the console.
https://pastebin.com/vPdQrsj7

**Comment by rderooy** [comment]
I tried it with both internal Munt and external Munt on Linux (Fedora 32), and I got "ElecPiano4". So it is working fine here with this setup.

So this would appear to be either something with the Windows version, or something specific to your PC setup.

**Comment by Razor221** [comment]
I did further testing on this issue and i think i've found the problem. On ultima VI using dynamic cpu core type causes this behavior. There is no problem with normal core, full core and simple core but dynamic core causes this problem.
@rderooy Can you please test dynamic cpu core on linux?

**Comment by rderooy** [comment]
@Razor221 I had core=auto set before, but changed it to core=dynamic.

And indeed I can confirm the same effect as your seeing, I now get "Harmo Pan" on the display with 4, and "Fantasy" with 8. So this does indeed seem to be an issue with the Dynamic core. This would be something for @joncampbell123 to look into.

p.s. for the MT32/CM32L ROM's I recommend to keep them in separate directories and use the mt32.romdir to point to the one you want. If you put them both into the same directory, DOSBox-X will always use the CM32L ROMs, and there are a few early games that work best with the MT-32 Old ROM's.

**Comment by Razor221** [comment]
Thanks for the tip @rderooy. I will do that. I always used CM32L because as far i know it had more sounds than old MT-32.

**Comment by Razor221** [comment]
@joncampbell123  The issue is fixed in the latest version. I think the overhaul of dynamic core in the latest version fixed whatever causing this weird bug.
