### ISSUE TITLE
The game Thexder does not start

### ISSUE THREAD

**Issue by maximus105** [joncampbell123/dosbox-x#1681]
**Describe the bug**
The game Thexder does not start. When the game starts, a message appears: Packed file is corrupt.

**To Reproduce**
1. Download game http://dl.old-games.su/get/O3aWkBwrSSqyrpTinTlX0w==,1593010223/pc/thexder/files/Thexder.rar
2. Click on thexder.com
3. See error

**Environment (please complete the following information):**
 - Windows 10 x64 2004
 - DOSBox-X 0.83.2 x64 SDL2

At the same time, in DOSBox-Staging v0.75.0, DOSBox ECE r4353, DOSBox SVN-Daum, the game starts without errors.

**Comment by rderooy** [comment]
Run loadfix first...

**Comment by Wengier** [comment]
@maximus105 I just tried, and the following works:

LOADFIX thexder.com

**Comment by maximus105** [comment]
Thank. The game is working. The question is, why do you need to specify LOADFIX for this? Are there any other similar games requiring LOADFIX ?

**Comment by Wengier** [comment]
@maximus105 Please check out Issue #7 for more information on this.

**Comment by sikthehedgehog** [comment]
Starting to think that DOSBox-X's defaults should include LOADFIX…

**Comment by Wengier** [comment]
@joncampbell123 and @maximus105  I have implemented the algorithm to automatically re-run the program with LOADFIX if the error "Packed file is corrupted" error message is detected in my latest pull request. Tested with the game and confirmed to work.

**Comment by Wengier** [comment]
@sikthehedgehog That may not work in other cases, especially for programs that do not have such problem and also requires a lot of memory.

**Comment by joncampbell123** [comment]
@Wengier The modification sets a flag if INT 21h AH=40h write to file or device sees the string "Packed file is corrupt" which is fine. Be aware there are DOS games that fail differently not because of the EXEPACK algorithm but because their code makes similar assumptions. In any case that is why DOSBox-X was updated some time ago to dummy allocate enough memory to provide about 600K of RAM (roughly typical MS-DOS 6.22 levels), though the settings in dosbox.conf allow you to change the "minimum mcb" block and allocation for more or less RAM.

**Comment by joncampbell123** [comment]
By the way, I do happen to know from awhile back that the EXE loader in the MS-DOS 5.0 kernel and higher have special code to detect the old EXEPACK code and patch it. At some point I would like DOSBox-X to do the same (but only if dosver is 5.0 or higher of course).

**Comment by rderooy** [comment]
I agree that this is a good step forward, but it will not fix all the cases where loadfix is needed. Not all games fail with an EXEPACK error, some fail later during gameplay, or start to misbehave. Those are the once that are more difficult, and require trial and error to find that loadfix is needed.
