### ISSUE TITLE
Updated MMX patch posted

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1687]
**Describe the bug**
Kekko posted an updated MMX patch
https://www.vogons.org/viewtopic.php?f=32&t=74877&p=868569#p868569

**Comment by Wengier** [comment]
I have already updated the MMX patch to the new version in my pull request #1688.

**Comment by joncampbell123** [comment]
Done. Also incorporated a fix to enable MMX instructions in 16-bit real mode (because real hardware allows that), and to prevent MMX instructions from working if Pentium or below.
