### ISSUE TITLE
Fails to build on 64-bit mingw with gcc 5.3.0

### ISSUE THREAD

**Issue by jwt27** [joncampbell123/dosbox-x#169]
Continued from #164: I'm trying to build DOSBox-X on gcc 5.3.0 under 64-bit mingw (msys2), but it fails. 
Installed the dependencies (SDL etc) through pacman, then configured with `./configure --build=x86_64-w64-mingw32 --disable-shaders`.
Here's the full output from `make -k`: https://gist.github.com/jwt27/f43a2b90b1dbe343a671

Most are narrowing conversion errors but there are a few others. I think I can fix most of these but I'm not sure what to do in direct3d.h with the duplicate definitions.

**Comment by joncampbell123** [comment]
I'm starting to think some of the issues you're seeing are related to the code that assumes Microsoft C++ if it sees the WIN32 define. I'm also confused why mingw doesn't recognize the %zu printf format specifier? %zu means you're printing a size_t value.

**Comment by sikthehedgehog** [comment]
Is it using the old MSVCRT for that function? I would guess that one doesn't know about %zu.

**Comment by jwt27** [comment]
Is %zu a C++11 feature? I noticed configure says `checking checking for C++11 support... checking whether g++ accepts " -std=gnu++11 "... no`... which seems wrong.

**Comment by sikthehedgehog** [comment]
I _think_ %zu may be there in C99 already, it's just that the DLL in question wasn't exactly up to date with even C99 as far as I know. So the question here is whether MinGW is using that or its own implementation. (also just to make it clear: are we talking about MinGW or MinGW-w64? because the former definitely uses that old MSVCRT DLL and is horribly unmaintained overall)

**Comment by joncampbell123** [comment]
%zu is the printf format for size_t, at least in Linux.

Unfortunately mingw compiles against MSVCRT.DLL which doesn't support that.

**Comment by joncampbell123** [comment]
Are you able to compile the latest code?

I will close this issue if it is no longer a problem.

**Comment by jwt27** [comment]
I'll have to try. master branch?

**Comment by joncampbell123** [comment]
Yup.

**Comment by jwt27** [comment]
I ran `./build-mingw` and got a working executable. Now I see there's an SDL2 version... will have to check that one too.

Build log here: https://gist.github.com/jwt27/45d0698d7c0c0de4b7f352297c7abf96

**Comment by jwt27** [comment]
`./build-mingw-sdl2` fails on linking the executable. I'm probably missing some prerequisites, although I have all available SDL2 packages installed.

Build log: https://gist.github.com/jwt27/cf3ebeba3378d15d04e933c65b40224e

**Comment by joncampbell123** [comment]
The official MinGW (not MinGW64) binaries seem to have intermittent problems with compiling properly, whether or not -j is used, at least on Windows 10.

Running the build script again might allow the compile to work properly.

**Comment by joncampbell123** [comment]
One obvious sign it's going to fail in this way is if the console output intermittently jumbles the character output during compile, it seems.
