### ISSUE TITLE
[Linux][gcc 10.x]Build process is broken in core_dynrec.cpp

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#1691]
**Describe the bug**
I wanted to build dosbox-x from git using this AUR PKBGUILD and build process stop when working on core_dynrec.cpp

https://aur.archlinux.org/packages/dosbox-x-git/

**To Reproduce**
Just try to build latest git on linux.

**Expected behavior**
Build process going on? :)

**Environment (please complete the following information):**
Archlinux with gcc 10.1

Commit I used: https://github.com/joncampbell123/dosbox-x/commit/376a6c333f3dbe2d205757f6c2c337f1429d98ba

**Additional context**

Here is an error log:

```
core_dynrec.cpp: In function 'Bits CPU_Core_Dynrec_Run()':
core_dynrec.cpp:368:8: error: 'BR_OpcodeFull' was not declared in this scope; did you mean 'BR_Opcode'?
  368 |   case BR_OpcodeFull:
      |        ^~~~~~~~~~~~~
      |        BR_Opcode
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
make[4]: *** [Makefile:439: core_dynrec.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/fred/dosbox-x-git/src/dosbox-x/src/cpu'
make[3]: *** [Makefile:461: all-recursive] Error 1
make[3]: Leaving directory '/home/fred/dosbox-x-git/src/dosbox-x/src/cpu'
make[2]: *** [Makefile:530: all-recursive] Error 1
make[2]: Leaving directory '/home/fred/dosbox-x-git/src/dosbox-x/src'
make[1]: *** [Makefile:390: all-recursive] Error 1
make[1]: Leaving directory '/home/fred/dosbox-x-git/src/dosbox-x'
make: *** [Makefile:327: all] Error 2
```

**Comment by rderooy** [comment]
@joncampbell123 started a few hours ago to remove the old full core, and that seems to have broken the build for now.

If you can go back to commit bfb0dc1 it should work.

**Comment by joncampbell123** [comment]
@rderooy Fixed it. However despite some hours pouring over the code, it looks like I cannot remove full core. The recursive page fault handling requires it.

For whatever reason, Windows 3.1 and dynamic core work better with full core and crash with normal core. Though this time around calling normal core from dynamic does not cause crashes with Quake.

Full core is going to stay, I'll move on to another task.

**Comment by FredBezies** [comment]
Fix indeed. Thanks. Closing this bug report.
