### ISSUE TITLE
SDL_net on Fedora

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [joncampbell123/dosbox-x#1692]
Hi, 
building dosbox-x on Fedora fails with undefined reference to SDLNet_GetError().
This is because the configure script generates Makefile with a line

LIBS = -lasound -lm -ldl -lpthread -lSDL2 -ltinfo -lfreetype  -lSDL_net -lz -lpng -lz -lpcap -lX11 -lXrandr -lxkbfile -lfluidsynth -lGL

but, on Fedora, /usr/lib64/libSDL_net.so is for SDL1.
I can build dosbox-x if I replace  -lSDL_net  with  -lSDL2_net  in Makefile, include/Makefile,
and src/Makefile.

**Comment by joncampbell123** [comment]
Does build-debug make a working SDL1 binary?

**Comment by tokumeiwokiboushimasu** [comment]
build-debug is OK.  
build-debug-sdl2 fails.

**Comment by rderooy** [comment]
Your probably having this problem: https://github.com/joncampbell123/dosbox-x/issues/1624

**Comment by tokumeiwokiboushimasu** [comment]
Ah, yes.  Seems the same problem.  So, linking libSDL2_net.so instead of libSDL_net.so solves the problem.

**Comment by rderooy** [comment]
Since I suspect a new release is just around the corner, just want to highlight that SDL2 builds still fail on Linux.

**Comment by tokumeiwokiboushimasu** [comment]
Now new version was released.  So we consider this problem again.
I found in configure.ac

> # HACK: Don't enable SDL2 net if SDL2
> if test x$have_sdl_net_lib = xyes -a x$have_sdl_net_h = xyes ; then
>  LIBS="$LIBS -lSDL_net"
>  AC_DEFINE(C_SDL_NET,1)
>  AC_DEFINE(C_MODEM,1)
>  AC_DEFINE(C_IPX,1)
> else 
>  AC_MSG_WARN([Can't find SDL_net, internal modem and ipx disabled])
> fi

So, libSDL_net.so is linked instead of libSDL2_net.so perposely.
Why is this necessary?  I changed Makefile by hand to link libSDL2_net.so
and it seems there is no problem.

**Comment by joncampbell123** [comment]
That HACK comment is old. I enabled SDLnet if SDL2.

**Comment by tokumeiwokiboushimasu** [comment]
> I enabled SDLnet if SDL2.

But, in the case of SDL2, we have to link libSDL2_net.so instead of libSDL_net.so

**Comment by joncampbell123** [comment]
Right. So for SDL2 the code in configure.ac needs to use SDL2_net if detected, else SDL_net.

**Comment by tokumeiwokiboushimasu** [comment]
Now fixed.  Thanks.
