### ISSUE TITLE
dosbox-x - networking problems

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#170]
I'm having trouble getting networking to work in dosbox-x

my network interface won't show up

```

LOG: SDLNet_TCP_Open: Couldn't connect to remote host
LOG: TiMidity: can't open control connection (host=127.0.0.1, port=7777)
LOG: Allocated APM BIOS pm entry point at f000:e86c
LOG: 
Network Interface List 

-----------------------------------

LOG: ISA Plug & Play BIOS enabled
LOG: SDL:OPENGL:No support for texturesize of 1024, falling back to surface
```

any help?

**Comment by joncampbell123** [comment]
Is this NE2000 emulation or something else?

**Comment by toddfraser88** [comment]
I think so, it's only dosbox with the issue

**Comment by ghoul8765** [comment]
probably a winpcap issue.

**Comment by toddfraser88** [comment]
I'm on linux, so it would be libpcap?

**Comment by ghoul8765** [comment]
Yes, that's correct. It will enumerate the network cards and it's a required library for ne2000 emulation.

**Comment by toddfraser88** [comment]
I had an old version libpcap file left over, I updated it and it's all working now

**Comment by ghoul8765** [comment]
That's wonderful.

**Comment by toddfraser88** [comment]
just one more thing

```
LOG: Using Network interface:
eth0
(no description)
LOG: 
Unable to open the interface: eth0: You don't have permission to capture on that device (socket: Operation not permitted).
```

how do i give myself permission to access the interface so that I don't need to use the root user?

**Comment by ghoul8765** [comment]
Try a script something like this:
http://www.vogons.org/viewtopic.php?f=31&t=36236

**Comment by toddfraser88** [comment]
I think for convenience, I'll just put up with running dosbox as root.

**Comment by toddfraser88** [comment]
hey, sorry to bring this up again

I've run into the same problem again on the windows build of dosbox-x, both 32-bit and 64-bit

I have winpcap installed, but this time I'm not even getting the network interface list,

do i need anything else besides winpcap?

**Comment by joncampbell123** [comment]
At this time I do not compile Windows builds with winpcap support, I've never tried. If you have the free community version of Visual Studio you could try adding the winpcap headers and modifying the config.h to enable it.

**Comment by Danfun64** [comment]
Any suggestions on how to add said headers? Especially for Win10PCap?

**Comment by joncampbell123** [comment]
WinPCap has headers and libraries to link against. See if they work with VS2015.

https://www.codeproject.com/articles/30234/introduction-to-the-winpcap-networking-libraries

https://www.winpcap.org/devel.htm

**Comment by joncampbell123** [comment]
I just added WinPCAP headers and enabled NE2000 emulation now.

**Comment by brunocastello** [comment]
Do I have to update the libpcap on macOS Mojave for NE2000 to see the network interface lists?
When I run dosbox-x with debug enabled the list shows a few options without no description at all. None of them work after I change realnic=list to any of these options. I think it's a libpcap issue, but I thought that macOS Mojave comes with libpcap installed? I am missing something to break this obstacle... I am using the latest release of dosbox-x.

**Comment by joncampbell123** [comment]
Are you compiling from source or using a binary release?

**Comment by brunocastello** [comment]
Using a binary release

**Comment by brunocastello** [comment]
I’m quite sure that macOS has libpcap included. So I’m at loss scratching my head. I haven’t tried the linux binary yet on my raspberry, but I will do soon.
