### ISSUE TITLE
Can't create HDD images larger than 2GB

### ISSUE THREAD

**Issue by XJDHDR** [joncampbell123/dosbox-x#1701]
**Describe the bug**
While trying to follow the [guide for installing Win98](https://github.com/joncampbell123/dosbox-x/wiki/Guide%3AInstalling-Windows-98), I found that I could not create images bigger than 2GB in size. If I try, DOSBox-X just creates a 0 byte file and prints an error to the terminal: "Not enough space available for the image file. Need 4289725440 bytes." The number changes depending on the size of the image I requested. I played around with the numbers and found that 2051MB was the maximum size I could create. Anything starting from 2052MB caused that error.

I most definitely have more than enough free space on all of my PC's partitions. I have DOSBox-X installed on my D: drive that has 250GB free space, my Temp folder is also on my D: drive and my C: drive, where Windows is installed, has 33.7GB free.

**To Reproduce**
Type one of the following commands into the terminal:
```
imgmake <name> -t hd_4gig -nofs
imgmake <name> -nofs -t hd -size 2052
```

**Expected behavior**
DOSBox-X successfully creates an image larger than 2GB.

**Environment (please complete the following information):**
 - Windows 10 v1910 x64
 - DOSBox-X v0.83.2 x64  (tested both SDL1 and SDL 2 versions)
 - [dosbox conf.zip](https://github.com/joncampbell123/dosbox-x/files/4849118/dosbox.conf.zip)

**Comment by Wengier** [comment]
There are some recent updates to IMGMAKE command, including support for FAT32 drives (-fat 32). Can you try the latest code instead of the previous release version?

**Comment by XJDHDR** [comment]
@Wengier 
I'll have to see if I can set up a build environment.

**Comment by Wengier** [comment]
Or if you prefer, you can wait for two days and try out the next release version instead.

**Comment by Wengier** [comment]
Both features and usability have been improved in the coming version. I see you are using Windows 10 - a Windows installer version may come soon too.

**Comment by rderooy** [comment]
That error seems to indicate you don't have space on your *real* harddisk/ssd/nvme to create a 4GB file. Upgrading to the next version will not solve a diskspace problem.

**Comment by XJDHDR** [comment]
@rderooy 
As I said in the OP:
"I most definitely have more than enough free space on all of my PC's partitions. I have DOSBox-X installed on my D: drive that has 250GB free space, my Temp folder is also on my D: drive and my C: drive, where Windows is installed, has 33.7GB free."

As for filesystems, I use NTFS for all my hard disks. FAT32 wouldn't stop me from creating a 2.1GB image anyway.

@Wengier 
I think I'll wait for the next release then. Thanks! As for the installer, doesn't affect me either way. I'll happily use the standalone edition with or without it.

**Comment by rderooy** [comment]
@XJDHDR I understand what your saying, just that I don't think the next version will change the actual problem.

I suspect some kind of 2GB limit problem with the windows filesystem API's that DOSBox uses.

Which DOSBox-X download did you use? dosbox-x-windows or dosbox-x-mingw-win64? And can you try the other.

**Comment by rderooy** [comment]
I just tried the MinGW compiled version on Windows 10 and it works, but the VS compiled version fails. This is with the release versions, as I don't have a windows build environment setup on my windows PC.

**Comment by XJDHDR** [comment]
@rderooy 
Okay, you didn't say anything about APIs previously. I was using the **dosbox-x-windows** version previously. Just tried **dosbox-x-mingw-win64** and it works. I suspect that the problem is in how VS is compiling this program. Or more specifically, the SDL portion of DOSBox-X.

**Comment by Wengier** [comment]
@XJDHDR Both VS and MinGW builds are for Windows of course. I have been primarily using MinGW builds myself lately, and that is probably why I never experienced such a problem.

**Comment by Wengier** [comment]
I have already fixed this VS-specific issue in my latest pull request.
