### ISSUE TITLE
Option to prevent window resizing?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1704]
Graphic-editing applications and text-based applications tend to look bad when resized by dragging the window border, and there's no easy way to get them back to the correct size if the user has resized them by mistake.

In my fork, I've been experimenting for a long time with ways to prevent resizing, and the only reliable way that I've found seems to be a bad hack, which involves changing sdl_video.h (in vs2015\sdl\include and vs2015\sdl2\include) so that the define SDL_RESIZABLE is changed to 0x00000000. 

This is clearly a bad method, but I don't know enough to find anything better. Is there an easy way to add a config setting (maybe "disableresize") that would be better. It seems to me that there is probably a place in the code where this setting could set sdl_resizable to 0 everywhere, but I can't figure out what it might be.

I realize this is low-priority, but I hope it's worth thinking about.

**Comment by joncampbell123** [comment]
There is a menu command in DOSBox-X to reset the window size (and undo your custom resizing) for this reason.

**Comment by emendelson** [comment]
That's what I get for turning off the menu...! Apologies for time-wasting.
