### ISSUE TITLE
Copy and Paste menu item

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1709]
**Is your feature request related to a problem? Please describe.**
The current copy-and-paste support is not the most intuitive.

As such I want to suggest a Edit menu. Either directly in the top bar, or as a sub-menu in Main. With support for Mark, select-all and paste similar to that of the Windows Command Prompt.

For this you would not need to change the clip_key_modifier.

**Additional context**
![Capture](https://user-images.githubusercontent.com/17701098/86379548-3f7f3a00-bc8b-11ea-9b8e-d9c6447bccd8.JPG)

**Comment by Wengier** [comment]
@rderooy I think the Edit menu is not really required for copying and pasting in Windows Command Prompt. In case you don't know, you can enable "QuickEdit mode" in "Command Prompt Properties", and then you will be able to directly use the mouse to copy and paste without the need of the Edit menu. It will be very similar to the "clip_key_modifier=none" setting as in DOSBox-X. But an additional Edit menu can be considered of course.

**Comment by rderooy** [comment]
@Wengier I know, was just using it as an example. And I think it may be easier to discover the Edit menu than setting clip_key_modifier in the config file.

**Comment by Wengier** [comment]
I think it is probably easier to make a toggle menu item so that when enabled, then no keyboard modifier is needed for the copy and paste operation.

**Comment by Wengier** [comment]
@rderooy I have already done this in my latest pull request.
