### ISSUE TITLE
release 0.83.3 crashes on start when started on macOS 10.15.5 Catalina

### ISSUE THREAD

**Issue by vasquesbc** [joncampbell123/dosbox-x#1711]
**Describe the bug**
The Application crashes right after it has been started.

**To Reproduce**
1. Start release 0.83.3 on macOS 10.15.5 Catalina
2. See the App crashing and macOS Crash Reporter appear

**Expected behavior**
should not crash on start.

**Environment (please complete the following information):**
 - macOS 10.15.5 Catalina
 - DOSBox-X 0.83.3
 - Freshly unzipped and started

**Additional context**
It seams there is a missing Library (part of ffmpeg?)
Since i didn't find any prerequisites (did i miss something?) i suppose the library is not included in the app bundle.

Take a look at the Crash Report right on the top:

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/ffmpeg/4.1_1/lib/libswresample.3.dylib
  Referenced from: /private/var/folders/*/dosbox-x.app/Contents/MacOS/libavcodec.58.dylib
  Reason: image not found
```

[dosbox-x_0.83.3_macos_crash.txt](https://github.com/joncampbell123/dosbox-x/files/4869021/dosbox-x_0.83.3_macos_crash.txt)

**Comment by dixius99** [comment]
Same here. I tried installing `ffmpeg` via `brew` just to see what would happen (which installs a long list of dependencies), and it then provided a similar error for `libx264.dylib`.

**Comment by emendelson** [comment]
I built the SDL and SDL2 versions from source under macOS 10.5 Catalina, and both versions started up correctly. So something seems to be wrong with whatever is used to build the release versions.

**Comment by joncampbell123** [comment]
My Mac OS build system has Brew-installed FFMPEG headers and libraries. The script to make the .app is supposed to copy those shared libraries into the .app.

Maybe the Mac OS build scrips should just pass --disable-avcodec.

**Comment by emendelson** [comment]
Presumably the build-script should not assume that anything exists on the system that isn't part of a default install with the Xcode command-line tools?

**Comment by joncampbell123** [comment]
They don't assume, configure.ac checks whether the libraries are available.

If it detects FFMPEG's libavcodec libraries are present, then it will use them in the video capture code.

The .app builder script is supposed to then copy the library files into the .app directory so it works on whatever system it is downloaded to, because obviously not everybody has FFMPEG installed.

**Comment by emendelson** [comment]
Ah - I misunderstood! Thank you.

**Comment by eirnym** [comment]
if do symbolic links, it starts normally, but it'd be better if the package would be fat, e.g. contain all dependencies

**Comment by joncampbell123** [comment]
The .app build script is supposed to include all dependencies, and at one point, it worked. Not sure what broke.

**Comment by Wengier** [comment]
Fixed in latest versions.
