### ISSUE TITLE
Mount from terminal broken

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1712]
**Describe the bug**
Running "dosbox ." with vanilla DOSbox (or staging or ECE) will mount the current directory as C: and change to C:.

![Screenshot from 2020-07-03 12-29-53](https://user-images.githubusercontent.com/17701098/86460648-0a292980-bd29-11ea-85a0-466ae46cda17.png)

But do the same with dosbox-x and it is ignored.

**To Reproduce**
1. dosbox-x .

**Expected behavior**
```
MOUNT C "."
C:
```

**Environment (please complete the following information):**
 - Fedora 32
 - DOSBox-X 0.83.4-git

**Comment by Wengier** [comment]
Yes, it is something supported in DOSBox but not DOSBox-X. I have already fixed this in my latest pull request.
