### ISSUE TITLE
Font in Tomb Raider I unreadable

### ISSUE THREAD

**Issue by ableeker** [joncampbell123/dosbox-x#1713]
**Describe the bug**
I've been trying DOSBox-X to play Tomb Raider I with the CD in Windows 10. It starts, shows the movies, and then shows the start menu. However, the text in the menu is unreadable. If you ignore that, and just select the right options, it actually runs the game quite well. I'm using the unmodified conf-file. Other versions of DOSBox, like DOSBox itself, or DOSBox-ECE, show the text correctly.

**To Reproduce**
1. Run a Windows version of DOSBox-X.
2. Mount the game directory as C.
3. Mount the CD-ROM as D.
4. Goto C.
5. Run the the normal version, or the 3DFX version of Tomb Raider I.
6. The start menu opens. The text in the screens of this menu is unreadable.
7. Use the arrow keys to select the passport, and press Enter to use the option Game.
8. The passport opens, press Enter to select the open passport to use the option New Game, or Load Game.
9. If you've selected Load Game, the screen with the saved games opens.

**Expected behavior**
I should be able to read the text in the start menu.

**Screenshots**
This is the game loading screen in DOSBox-X.

![dosbox-x](https://user-images.githubusercontent.com/2095835/86479624-c9dba280-bd4c-11ea-8c3e-935ce6e91c0d.png)

This is the same screen in DOSBox-ECE.

![dosbox-ece](https://user-images.githubusercontent.com/2095835/86479661-d9f38200-bd4c-11ea-8dda-18da57438dcd.png)

**Environment (please complete the following information):**
 - Windows 10
 - DOSBox-X windows-20200630-163819
 - Default ```dosbox-x.conf```

**Comment by rderooy** [comment]
I just tried it here on Linux and it seems to work fine. Tried it with output=surface and output=openglnb, and tried it with both the regular and the 3dfx executable.

**Comment by ableeker** [comment]
I've installed the Linux version to see if that made a difference.

This what I see when I run DOSBox-X on Ubuntu 20.04.

![Screenshot from 2020-07-03 19-21-49](https://user-images.githubusercontent.com/2095835/86488949-fbf7ff00-bd62-11ea-8c26-68ca1332a1f0.png)

This is the same screen in DOSBox.

![Screenshot from 2020-07-03 19-49-44](https://user-images.githubusercontent.com/2095835/86490146-b1788180-bd66-11ea-9b9e-ddbe590db5df.png)

**Comment by rderooy** [comment]
In that case, I can only think of 2 things. Either it is something to do with how TombRaider is configured. I have it set with the default SB16, which I assume is what your also using. Besides, I consider this to be a very low likelihood of being an issue.

What is more likely to be the issue, is the version of the game. I suspect your version is different from mine. Perhaps one of us has a newer version, or patches applied that make the difference.

**Comment by ableeker** [comment]
I've just found out that the issue isn't present when I change the display options in Tomb Raider (the sun glasses). When I select the option Normal, the text is quite readable, but when I select Mipmapping, I see only blocks.

**Comment by rderooy** [comment]
I only see Low, Medium and High as options in the detail (sun glasses) sub-menu.

**Comment by ableeker** [comment]
I have the Sold Out edition as well. But this being an emulation of the Voodoo (1?) complicates matters slightly, you'll need a real driver, GLIDE2X.OVL, not a wrapper. The version of the OVL matters a too, I can play Tomb Raider with OVL 2.42, and 2.43, but later versions, 2.46, and 2.48, just give me a black screen. Even later versions, 3.01, seem to work, but there's no 3DFX splash screen, the display options are High, Middle, and Low (not Mipmapping, and Normal), and everything is visibly pixelated.

I've also noticed that the text is readable when output is opengl, openglnb, or openglhq. Anything other than that gives me unreadable text, but only if the display option is set to Mipmapping, Normal is fine in all modes.

Unfortunately opengl does't work with full screen, so until this issue has been solved I can use the opengl output with the Mipmapping option, or use direct3d with Normal.

**Comment by Wengier** [comment]
The font and full-screen issues are solved in the current DOSBox-X build which enables support for Glide wrappers. I have uploaded a zip package which includes 3dfx version of Tomb Raider and required file for DOSBox-X (dosbox-x.exe, dosbox-x.conf, glide2x.dll), so you can just type dosbox-x.exe to run Tomb Raider 3dfx:

Download: [tomb3d.zip](http://cndos.fam.cx/dosware/tomb3d.zip)

**Comment by Wengier** [comment]
I believe I have already fixed the Tomb Raider font issue in Voodoo hardware emulation mode as well in the latest code (https://github.com/joncampbell123/dosbox-x/commit/2613ac10056c56195b064327a36e3bde7b3950c8).
