### ISSUE TITLE
After SaveState, and then subsequent LoadState, the screen is damaged

### ISSUE THREAD

**Issue by maximus105** [joncampbell123/dosbox-x#1714]
**Describe the bug**
In fullscreen mode after SaveState, and then subsequent LoadState, the screen is damaged:
In svga_s3 mode, the screen will stretch horizontally (if you save and load it again, the screen will shrink horizontally)
In cga or cga_mono mode, the screen will compressed horizontally (if you save and load it again, the screen will stretch horizontally)

**Environment (please complete the following information):**
 - Windows 10 x64 2004
 - DOSBox-X 0.83.3 x64 SDL2

[sdl]
fullscreen        = true
fulldouble        = false
fullresolution    = desktop
windowresolution  = desktop
output            = openglnb
autolock          = true
autolock_feedback = none
clip_key_modifier = shift
clip_paste_speed  = 20
sensitivity       = 100
mouse_emulation   = locked
mouse_wheel_key   = 0
waitonerror       = true
priority          = higher,normal
mapperfile        = mapper-0.83.3.map
mapperfile_sdl2   = mapper-0.83.3.sdl2.map
usescancodes      = true
overscan          = 0
titlebar          = 
showmenu          = true

[render]
frameskip               = 0
alt render              = false
aspect                  = true
char9                   = true
doublescan              = false
scaler                  = advinterp2x forced
xbrz slice              = 16
xbrz fixed scale factor = 0
xbrz max scale factor   = 0
autofit                 = true
monochrome_pal          = white bright

[dosbox]
vmemsize                                          = 8
memsize                                           = 32

[vsync]
vsyncmode = on
vsyncrate = 60

**Comment by Wengier** [comment]
I think the said issue may only occur with your specific configuration, but not the default configuration of DOSBox-X, so it does not happen in general.

**Comment by maximus105** [comment]
With the same .conf file configuration, this problem did not exist in version 0.83.2

**Comment by Wengier** [comment]
@maximus105 Have you noticed the major changes in the save state feature in 0.83.3 over 0.83.2? See Issues #1576 and #1582 for more details.

**Comment by maximus105** [comment]
@Wengier In these described issues there is no such damage to the screen. In the .conf file, I only changed:
fullscreen        = true
output            = openglnb
aspect             = true
After that, screen damage appeared, which was not in version 0.83.2 with the same changes in the .conf file.

**Comment by Wengier** [comment]
@maximus105 The save and load state feature is primarily intended for windowed mode (you cannot even see the "save state" menu when you are in full-screen mode). But in any case, I think I have already fixed this in my latest pull request.
