### ISSUE TITLE
Save state in MacOS version will be supported?

### ISSUE THREAD

**Issue by aminta** [joncampbell123/dosbox-x#1718]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Wengier** [comment]
I do not have macOS myself to test (I only tested it in Windows and Linux), but what happens when you try to use DOSBox-X 0.83.3's save state feature in macOS? Any error message?

**Comment by Wengier** [comment]
In case you are using macOS 10.15.5 and the release build of DOSBox-X 0.83.3 crashes on start when running on it (Issue #1711), you can try to build the DOSBox-X source code on macOS by yourself, which may resolve the problem.

**Comment by Wengier** [comment]
It is already supported in current DOSBox-X version.
