### ISSUE TITLE
Dosbox-x 0.83.3 for MacOSX doesn't open / start on MacOSX Catalina 10.15.5

### ISSUE THREAD

**Issue by aminta** [joncampbell123/dosbox-x#1719]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Operating system
 - DOSBox-X release version or commit SHA1 this issue occurred on
 - Used configuration, e.g. ```dosbox-x.conf```

**Additional context**

**Comment by Allofich** [comment]
Might be the same issue as https://github.com/joncampbell123/dosbox-x/issues/1711.
Does the crash information look the same as what's reported there?

**Comment by Wengier** [comment]
Fixed in latest versions.
