### ISSUE TITLE
KEYB (Swedish support problem)

### ISSUE THREAD

**Issue by starinspace** [joncampbell123/dosbox-x#1721]
**Describe the bug**
I can only get "ä" to work with "KEYB sv". Not åäö and "'¨-.,´" is not on the right button. 

**To Reproduce**
Tested;
KEYB sv          (seems to be 437)
KEYB sv 850   (same problem, same buttons is wrong)
KEYB sv 437   (same problem, same buttons is wrong)
KEYB sv 153   (says "No layout in sv for code 153")

**Expected behavior**
to get åöä and ¨',.-^*;:\_ to work on the right buttons on the keyboard.

**Screenshots**
<a href='https://www.bildtagg.se/bild/7p8oj7yr4p2dlfesqqbau' target='_blank'><IMG src='https://www.bildtagg.se/file/7p8oj7yr4p2dlfesqqbau' /></a>

**Environment (please complete the following information):**
 - Windows 10 64-bit
 - DOSBox-X 0.83.3 2020-06-30 18:32

**Additional context**
If its not supported, could it be added to next release?

**Comment by rderooy** [comment]
I'm assuming your using the SDL1 version?

Try either the SDL2 version, or try setting in your dosbox-x config file:
```
[sdl]
usescancodes=true
```

**Comment by starinspace** [comment]
> I'm assuming your using the SDL1 version?
> 
> Try either the SDL2 version, or try setting in your dosbox-x config file:
> 
> ```
> [sdl]
> usescancodes=true
> ```

Oh! Well, I have just missed that. Well now it works. Thank you. :)
