### ISSUE TITLE
Can't compile with MinGW since 17816ea (the START addition)

### ISSUE THREAD

**Issue by diaphone0** [joncampbell123/dosbox-x#1734]
Hi :)
I'm using an old mingw installation (msys 1.0 + tdm-gcc 4.9.2) to compile DOSBox-X for a while,
And now it looks that the functions 'strcpy_s' and 'strcat_s' are not defined in mingw.

Trying to define strcpy_s as 'strcpy' and strcat_s as 'strcat' helps me to go around this issue.
(and the startcmd feature seems to work well, tested with "START + notepad.exe" and notepad started maximized) 
Anyway i'm not sure if that's the right thing to do, I'm kinda n00b on c and cpp...

**To Reproduce**
Sorry I can't describe that easily, i've fiddled with various dosbox and mingw include & makefiles in order to compile it with mingw 4.9.2 with some success until today...

**Environment (please complete the following information):**
 - Operating system - Windows 10, msys 1.0 and tdm-gcc 4.9.2 
 - commit - 17816ea
 - Used configuration - nothing special, just enabling [dos] / startcmd

...and sorry if my English is not perfect :)

**Comment by Wengier** [comment]
Current version of MinGW64 (which I am using along with Visual Studio) does compile the code fine, so this issue seems to be specific to older versions. But in any case, it can be solved by using strcpy and strcat instead, and I will soon submit a new pull request which includes a fix for this.

**Comment by diaphone0** [comment]
thanks!
