### ISSUE TITLE
Build error in VS2019

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1737]
With current code (aca847e) an attempt to build in VS2019 produces these errors:

10>C:\Users\Edward\Desktop\dosbox-x-master-13July\src\shell\shell_misc.cpp(1178,36): error C2065: 'P_NOWAIT': undeclared identifier
10>C:\Users\Edward\Desktop\dosbox-x-master-13July\src\shell\shell_misc.cpp(1178,28): error C3861: '_spawnl': identifier not found

My guess is this is compiler-specific, but I have no idea of what it means...

**Comment by Wengier** [comment]
@emendelson I believe this is exactly the same issue as the following, which I already fixed in my latest pull request.

https://github.com/joncampbell123/dosbox-x/commit/aca847e8d9c2950105fc6e279d886d7fc2768b7f#comments

**Comment by Wengier** [comment]
In any case, this was Visual Studio SDL1-specific, as it did not happen in other platforms such as MinGW64 SDL1 or Visual Studio SDL2 (which I mainly use for Windows builds).

**Comment by Allofich** [comment]
Visual Studio 2019 is building fine, so this should be closed.
