### ISSUE TITLE
Guide on which build to use

### ISSUE THREAD

**Issue by bthylafh** [joncampbell123/dosbox-x#1739]
**Is your feature request related to a problem? Please describe.**
There are many different Windows builds of dosbox-x to choose from and no indication why I might want to use any given one.

**Describe the solution you'd like**
It would be good to have some guidance in the wiki, or in the readme.md file.

**Describe alternatives you've considered**
I looked around the github repository and the website but didn't see anything obvious describing the strengths/weaknesses of each build, besides an old bug report detailing why this project maintains an sdl1 fork. I don't see any documentation in the downloadable zip files either.

**Additional context**
* dosbox-x-mingw-win32-20200630164800.zip
* dosbox-x-mingw-win64-20200630174234.zip
  * all the different mingw builds: -lowend, -sdl2, -sdldraw, and just plain mingw.
* dosbox-x-windows-20200630-163819-windows.zip

**Comment by Wengier** [comment]
The Visual Studio build is the default build, but it does not run on Windows XP. So if you are using Windows XP, the MinGW build should be used instead. Also, if you have certain other problems with the Visual Studio build, the MinGW builds (including the plain mingw build or lowend/sdldraw ones) may sometimes solves such problem, but if you don't experience specific problems, then in most cases you can stick with the default Visual Studio build. You can choose SDL1 or SDL2 version according to your preference.

You did not mention the DOSBox-X Windows installation package, which also includes all these builds, but it will automatically pre-select a build according to your platform, such as Visual Studio SDL1 build for Windows Vista or later, MinGW SDL1 build for Windows XP, and ARM SDL1 build for Windows ARM platform. There is also a quick documentation included in it.

Link to Windows installer: [DOSBox-X-0.83.3-setup.exe](https://github.com/Wengier/dosbox-x-wiki/raw/master/DOSBox-X-0.83.3-setup.exe)

**Comment by bthylafh** [comment]
If we're meant to use the Windows installer, then IMO that should be included in the downloadable assets, and it isn't, and I don't see anything about that in the wiki or readme.md either.

The point is that none of this stuff is listed in the documentation.

**Comment by Wengier** [comment]
I have added more information for the packages to the documentation in my latest pull request.
