### ISSUE TITLE
Win98 - cant access NAS shares

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#174]
my win98 installation in dosbox-x - it can see my NAS, I can ping NAS IP (192.168.88.23)

But if I type \192.168.88.23 into windows explorer I get -

Cannot find file or item- make sure the path and filename is correct.

It's been a while since I use win98 - do I need to do something extra to access shares?

**Comment by dashaw92** [comment]
\\192.168.88.23
^^ Notice the two backslashes

**Comment by joncampbell123** [comment]
There's the backslashes issue :) but also you need to enable NE2000 emulation, then install the NE2000 device driver in Windows. You'll need libpcap (Linux, Mac OS X) or WinPcap (Windows) for that to work.

**Comment by toddfraser88** [comment]
made a typo when i sent that post, I usually use \\192.168.88.23 correctly

NE2000 emulation networking is working - I can ping 192.168.88.23 in windows98 just fine

I made sure I used  \\192.168.88.23 when i tried this time - still same message

**Comment by ghoul8765** [comment]
Best to test with real hardware as the 9x->NAS can be problematic:
http://www.msfn.org/board/topic/120648-using-a-nas-on-win9x/
https://community.netgear.com/t5/Using-your-ReadyNAS/SOLVED-Windows-98-Cannot-Access-ReadyNAS-Shares/td-p/832256
http://www.troubleshooters.com/linux/win9x_samba.htm   <-- try this

**Comment by toddfraser88** [comment]
I thought I'd try dosbox-x on one of my windows machines, just to be sure if it's something on linux thats causing this or not

I'm using your windows build, haven't got visual studio myself

but I can't see where it is meant to list network interfaces, I don't see them listed in the command prompt,
I have set in .conf

realnic=list

but i don't see where it lists anything, am I missing something?

**Comment by toddfraser88** [comment]
any help with the windows version?

**Comment by toddfraser88** [comment]
I figured out there is no status window, that's why a I'm not seeing anything.

**Comment by joncampbell123** [comment]
Windows builds now have WinPCAP and NE2000 emulation.
