### ISSUE TITLE
Disney's Duck Tales: the Quest for Gold not starting

### ISSUE THREAD

**Issue by maximus105** [joncampbell123/dosbox-x#1741]
**Describe the bug**
Disney's Duck Tales: The Quest for Gold won't launch with default .conf settings. At the same time, in DOSBox-Staging v0.75.0, DOSBox ECE r4356, DOSBox SVN-Daum, this game starts normally, without bugs.

**To Reproduce**
1. Download the game:
http://dl.old-games.su/get/tvuxsFk8gSEUJ8kKfe05gw==,1595235615/pc/disneys_duck_tales_the_quest_for_gold/files/Disneys_Duck_Tales_The_Quest_for_Gold.rar
2. Click on 'ducktale.exe'
4. See error (the game will not start or there will be a black screen all the time).

**Environment (please complete the following information):**
 - Windows 10 x64 2004
 - DOSBox-X 0.83.3 x64 SDL1

**Comment by Wengier** [comment]
I have already fixed this in my latest pull request.

**Comment by yksoft1** [comment]
I also found that this game displays wrong graphics and crashes running in machine=tandy in 0.83.3. 
![image](https://user-images.githubusercontent.com/37106774/87894200-a024ba00-ca74-11ea-9148-2a01fe72e2d9.png)
This game worked well in DOSBox 0.74-2.

**Comment by Wengier** [comment]
Just tried again the game with machine=tandy with the latest code in my pull request (not merged yet) and confirmed to work.

**Comment by maximus105** [comment]
The new version 0.83.4 of DOSBox-X was not released on August 1. Have you changed the frequency of the new version release? (1st day of each month). And when is the new version of DOSBox-X coming out now?

**Comment by joncampbell123** [comment]
@maximus105 I have been incredibly busy in the last weeks or so and will get a release out Sunday or Monday.
