### ISSUE TITLE
Configure with C_AVCODEC but without C_SSHOT doesn't work

### ISSUE THREAD

**Issue by eirnym** [joncampbell123/dosbox-x#1746]
**Describe the bug**
When building with C_AVCODEC set, but with C_SSHOT unset (e.g. missing libpng or we don't want screenshots feature), hardware.cpp will fail on missing type `VideoCodec` included from `"../libs/zmbv/zmbv.h"` which is enabled only while screenshot feature is enabled.

**To Reproduce**
1. uninstall libpng (or reconfigure with `--disable-screenshots`)
2. reconfigure
3. make 

**Expected behavior**
`../libs/zmbv/zmbv.h` is included with either `C_AVCODEC` or `C_SSHOT` is enabled in `config.h`

**Environment (please complete the following information):**
 - Tested under macOS/MacPorts
 - DOSBox-X 0.83.3

**Comment by Jookia** [comment]
Is this still an issue? It looks fixed in 107a7e7721

**Comment by eirnym** [comment]
yep, it looks like so, thank you
