### ISSUE TITLE
Example config in Guide:Installing Windows 98

### ISSUE THREAD

**Issue by pancirno** [joncampbell123/dosbox-x#1754]
The "cycles" option should go to the [cpu] section - at least that what works for me in current Dosbox-X release

**Comment by rderooy** [comment]
Your right. I have changed it in the work-in-progress wiki here: https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3AInstalling-Windows-98

At the end of the month, when there is a new dosbox-x release, it should get updated.
