### ISSUE TITLE
She Bo (Dinosaurr Balls or Chinese Pang) shows only upper half of screen

### ISSUE THREAD

**Issue by ognjenmi** [joncampbell123/dosbox-x#176]
Hi,

When the game-play starts only upper half or upper (2/3) of screen is visible.
[PANG.zip](https://github.com/joncampbell123/dosbox-x/files/149144/PANG.zip)
![ball_000](https://cloud.githubusercontent.com/assets/8169388/13369512/19e6798a-dcf6-11e5-95af-2d815d705f7a.png)

**Comment by joncampbell123** [comment]
Can you post your dosbox.conf? I can't seem to recreate the issue, the game shows up fine here. I tried all VGA and SVGA machine settings.
![ball_000](https://cloud.githubusercontent.com/assets/6245486/13371860/e57448b4-dce4-11e5-881a-1722639b4bcd.png)

**Comment by sikthehedgehog** [comment]
It looks like for whatever reason every line is doubled in the original screenshot?

**Comment by joncampbell123** [comment]
It looks like for some reason, the pixels are not being doubled horizontally, but are being doubled vertically, but the scaling is cutting off the bottom half. Are you using aspect ratio correction or any of those options? Again, it helps if you post your dosbox.conf. By default settings it should look like the screenshot I posted.

**Comment by ognjenmi** [comment]
This is all I have in my config which is generated from DBGL.
I attached file I got with config -writeconf

[sdl]
fullresolution=0x0
output=opengl

[dosbox]
captures=..\captures\174

[render]
scaler=advmame3x

[autoexec]
mount C "C:\"
C:
cd \igre\Platform\PANG
BALL.EXE


[shebo.zip](https://github.com/joncampbell123/dosbox-x/files/149502/shebo.zip)

**Comment by ghoul8765** [comment]
Test with an unmodified dosbox configuration file.

**Comment by ognjenmi** [comment]
Sorry I foud what was the issue. By mistake I copied config file from Daum build to doxbox-x folder. Now everything works. Sorry for this false issue.
