### ISSUE TITLE
No mouse after quick-reboot on booted guest windows (98 & 3.11)

### ISSUE THREAD

**Issue by diaphone0** [joncampbell123/dosbox-x#1761]
**Describe the bug**
Tested on 0.83.4 (ef72659 built with mingw32/msys1.0),
I've tried the new quick reboot feature and I've noticed that after a quick reboot (main->reboot guest system), the mouse doesn't move.
That happens on both windows 98se and wfw3.11 guests.

**To Reproduce**
1. imgmount an image with windows guest installed
(I'm using the same img from issue #1758 that contains a hebrew edition of wfw3.11 installed)
2. boot -l c
   start win.com (in my win3.11 img it's not included in autoexec)
3. the mouse should work at this point
4. do the quick reboot from the main menu (F11+S)
   at this point the mouse doesn't move...
5. i've also tried freedos's edit with ctmouse driver, and it's not affected after quick reboot.
    it seems also that loading ctmouse before win.com brings back the mouse on wfw3.11

**Environment (please complete the following information):**
 - Operating system Windows 10 64BIT
 - DOSBox-X release version or commit SHA1 this issue occurred on
0.83.4 (ef72659),
 - Used configuration, e.g. ```dosbox-x.conf```
none

**Comment by Wengier** [comment]
Thanks for reporting the issue. I have already fixed it in my latest pull request.

**Comment by diaphone0** [comment]
Thanks! I can confirm the mouse is working now after a quick reboot (as of 2e2406e).

But sometimes dosbox-x crashes after the quick reboot, it looks kinda random...
Is there an option to keep the console output to a file? 
Trying "dosbox-x.exe --console > log.txt" doesn't work as it opens a new console window for the log.

**Comment by diaphone0** [comment]
BTW, With the quick boot feature added, I think it would also be nice to add a mapper option for sending CTRL+ALT+DEL,
Just a suggestion... :)

**Comment by Wengier** [comment]
@diaphone0 Just set “logfile=dosbox-x.log” in [log] section of dosbox-x.conf, and then you will have the logs in dosbox-x.log file.

**Comment by diaphone0** [comment]
Thanks, currently it doesn't crash anymore, if it would happen again i'll post the log file...

**Comment by Wengier** [comment]
@diaphone0 I have already added HOST+Del as the default mapper key for Ctrl+Alt+Del in my latest pull request.
