### ISSUE TITLE
Spanish keyboard problems again: can't type accented upper-case Ó

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1762]
Using current code, both SDL1 and SDL2 builds have problems with the Spanish keyboard, These were reported to me by a user of my WordPerfect system, but the user tested with the SDL1 and SDL2 builds of the current code, not my patched version. He reports that with KEYB SP 850 in [autoexec], these problems occur:

SDL1: AltGr does not work (has no effect). The -/_ key produces the wrong characters (I don't know which characters appear, but I've asked). Ó accentuated uppercase does not appear.

SDL2: AltGr does not work (has no effect). Ó accentuated uppercase does not appear.

I haven't tested this, but the report seems to be reliable.

**Comment by rderooy** [comment]
I just tried it with the SDL2 version here, and AltGr works to produce the Euro symbol when I press AltGr-e, also various other keys on the right hand side of the keyboard, and under the number keys, have additional symbols when I use AltGr.

Dead keys also work, so when I press ' and then e, I get é or with shift É. Likewise, I can produce a lower-case ó, but in this case not the upper case variation. Ó. Not sure why that is.

p.s. unless you have a good reason you should use codepage 858 as it is basically the same as 850, but includes the Euro symbol.

SDL1 and non-us keyboards requires that you set
```
[sdl]
usescancodes=true
```
This is also mentioned here https://github.com/joncampbell123/dosbox-x at the bottom of the page in "International Keyboard Layouts". When I do that here, it seems to behave the same as the SDL2 binary.

**Comment by rderooy** [comment]
@Wengier @joncampbell123 International keyboard layout issues are a common problem, particular with the SDL1 build. Perhaps usescancodes should default to auto, which would mean that if (SDL1 && !keyboard=us) usescancodes=true

What do you think?

**Comment by emendelson** [comment]
@rderooy I will ask my user to change from 850 to 858 and let me know what happens. This is very strange. He is a very reliable reporter.

@joncampbell123 @wengier My user tells me that this build (made from my patched version of the April 2020 code) works perfectly, with the accented upper-case Ó and everything else:

http://www.columbia.edu/~em36/wpdos/DOSBox-X-17April.exe

That was a long time ago. I would like to try to narrow down the differences between my version from that date and the current version. I know that the main differences would probably be in dos_keyboard_layout_data.cpp, but where else should I look?

I see that Wengier has already added a patch I got from a DOSBox dev to improve diacritics, so that can't be part of the current problem that my user reports.

**Comment by emendelson** [comment]
Update (as shown in the edited post immediately above this one). I sent my user another SDL2 build, and he reports that everything is working except for the accented upper-case Ó. What might fix this?

**Comment by rderooy** [comment]
The o-acute character is not used in languages like German or French, but with the help of wikipedia I found it is used in Spanish Portuguese, Dutch and some others. https://en.wikipedia.org/wiki/%C3%93

And indeed when I switch to "keyb nl" (same key as "keyb sp"), or "keyb po", I cannot generate the upper-case o-acute character either.

**Comment by rderooy** [comment]
p.s. usescancodes should not be needed with the SDL2 version. It is mainly there to work around SDL1 limitations.

**Comment by emendelson** [comment]
My user also reports this:

"The Spanish keyboard works fine (except the Ó character) in the last Dosbox.exe that you sent me, when the English keyboard is selected in Windows. If the Spanish keyboard is selected in Windows, the AltGr key does not work. This has always happened in Dosbox.  And it not only occurs in Dosbox, also in emulators like Ibmulator (emulator of the IBM PS / 1), which do not depend on Dosbox. English keyboard must be selected in Windows for AltGr key to work in Spanish Keyboard."

I don't know any more about this.

**Comment by rderooy** [comment]
I just gave that a quick test on my Linux system, and when I select a Belgium keyboard on the host OS and a Belgium keyb with the SDL2 dosbox-x binary, AltGr works just fine. So this may be a Windows issue.

p.s. the Belgium layout also cannot generate the upper-case o-acute character.

**Comment by rderooy** [comment]
I also just tried it with Windows 10. I switched the host OS to a Belgium keyboard, and did the same with the dosbox-x SDL2 binary, and AltGr works here. So there may be something else going on with your users system.

**Comment by Wengier** [comment]
@rderooy I have already added support for "usescancodes=auto" in my latest pull request, which enables the use of scancodes when non-US keyboards are detected on SDL1 builds. I don't have international keyboards to test myself though.

**Comment by rderooy** [comment]
@Wengier thanks, will give it a try. As to testing, you don't need an international keyboard for that. Just look up an image of a non-us keyboard online, and switch your keyboard layout and see if key presses correspond with the picture.

The only issue is around the Enter key, where most non-US keyboards have a large vertical Enter, and the US keyboards have a large horizontal Enter key. But this causes only ONE key to switch physical location, but has no effect on keycodes.

**Comment by rderooy** [comment]
Got a moment to try it on Linux with an SDL1 build. Seems to work fine with either the host keyboard set to US or to an International layout.

**Comment by rderooy** [comment]
Another interesting twist. To see if dosbox can render the upper-case o-acute character Ó I created an empty file in my filesystem with "Ó" as the filename. I then folder mounted the directory with the file in it. Turns out the file is simply missing when you run DIR.

Looking at the log, I see the following with the default US layout and codepage 437:
```
LOG: read_directory_next: Filename 'Ó' from host is non-representable on the guest filesystem through code page conversion
```
I guess this is to be expected, since I cannot find the upper-case o-acute character in codepage 437 (it does have the lower-case variation, and creating a filename with that character works fine).

But when I change to codepage 858, it shows this error:
```
LOG: FindNext: Filename './�' from guest is non-representable on the host filesystem through code page conversion
```
And codepage 858 (and 850) does have the character, so this should work.

**Comment by rderooy** [comment]
To check that the issue is limited to the integrated DOS, I booting PC DOS 2000 in DOSBox-X, and I can type the upper-case o-acute character.
![guest os_000](https://user-images.githubusercontent.com/17701098/88795654-b16e7480-d1a0-11ea-9802-53573f260c42.png)

**Comment by emendelson** [comment]
My users tells me that this build correctly displays the accented-upper-case-Ó. Could you possibly test it:

http://www.columbia.edu/~em36/wpdos/DOSBox-X-17April.exe

**Comment by rderooy** [comment]
Indeed it works with that binary. It is a modified SDL2 build

**Comment by rderooy** [comment]
With that binary, I also tried the to create a Ó file and list it.

With the default setting (codepage 437), it would not list the file, but the LOG also did not have any errors. So it seems that logging is turned down.
When I switched to codepage 858, it still would not show the file, and I got a similar error as I got on Linux.

**Comment by rderooy** [comment]
The ╙ character is codepoint 211 (unicode 2558) in codepage 437, while in codepage 850 or 858 this same code point would be the upper-case e-grave (È) (unicode 00C8).

Instead Ó should be codepoint 224 (unicode 00D3) in codepage 850 or 858. This same codepoint in codepage 437 would be the alpha symbol (α).

**Comment by emendelson** [comment]
@rderooy Amazing detective work. Is there a way to fix this in the code?

**Comment by rderooy** [comment]
Part of the filesystem issue seems to be src/dos/drive_local.cpp it handles the conversion from codepage to unicode, at least for filenames. And it turns out it only supports 3 codepages, namely 437, 866 and 932. Codepage 850/858 support really needs to be added here.

**Comment by joncampbell123** [comment]
@rderooy By design it's somewhat easy to add new code pages. Find the code page listings on the Unicode consortium site and use the scripts (on Linux) in the mappings subdirectory of the source tree to generate an include header for it.

**Comment by joncampbell123** [comment]
It's hard as hell to find this now on their site, but, here are the mappings tables we used for code pages so far:

https://unicode.org/Public/MAPPINGS/

**Comment by joncampbell123** [comment]
Code page 850: https://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP850.TXT

**Comment by rderooy** [comment]
Was just going to mention that. Their links are broken, but I found a ftp server with google that had the CP850.txt file in the meantime.

**Comment by rderooy** [comment]
There is no CP858.TXT, but here is how to make one from the CP850.TXT file
http://unicode.org/mail-arch/unicode-ml/Archives-Old/UML013/0025.html

**Comment by Wengier** [comment]
@rderooy I agree that codepage 850/858 support needs to be added, and I will add them to the code soon.

**Comment by rderooy** [comment]
@Wengier Ok :-) I was going to look into it tomorrow if it was something I was comfortable writing. But your definitely more capable at coding it than I am.

**Comment by Wengier** [comment]
@rderooy I have already added them in my latest pull request.

**Comment by rderooy** [comment]
That was really quick :-) Will give it a test tomorrow.

**Comment by emendelson** [comment]
I built Wengier's code from his fork and sent the executable to my user, who reports that he still can't type the upper-case accented Ó, as he could on my April build. He normally types the character by typing the acute accent then upper-case O, but he reports that this doesn't work in the new code. 

Does anyone have any suggestions about what to look for in comparing my April build with current code?

**Comment by Wengier** [comment]
@emendelson The new code pages I added are to help host to guest code page mapping on local drives, not for entering specific character, if the previous setting "usescancodes=true" did not work for it.

**Comment by Wengier** [comment]
@rderooy I have already added other code pages including 852, 855, 872, 869 and 872 too for other international users.

**Comment by emendelson** [comment]
@Wengier - Yes, I understand. I'm still baffled at why my April build lets me type that character. Unfortunately, I can't build the April code again because of the problem with VS 2019 that got solved afterwards. But I don't see any difference in the keyboard or SDL2-related files that might explain this.

I can confirm that with KEYB ES, in my April build, I can type acute-accent then O, and get the Ó. I can't in the new build.

**Comment by Wengier** [comment]
@emendelson Not sure about typing, but I just checked and confirmed that pasting the said character into DOSBox-X does work, at least on VS SDL1 builds.

**Comment by emendelson** [comment]
@Wengier - I'm away from my machine, but in the SDL1 build, could you try:

KEYB ES

and then type the single quotation mark (') and then shift-O, and see what happens?

**Comment by emendelson** [comment]
I got back to my machine, and built SDL1, with usescancodes=true (maybe not needed?) and tried to type the Ó; no success. I can't see anything obvious about my April 17 build that makes it work. I tried the March 2020 release, and couldn't type the character there either.

**Comment by Wengier** [comment]
@emendelson The reason for the said issue is that the codepoint 224 (0xe0) is a special one. I do have a workaround for this though - please try the latest code in my pull request.

**Comment by emendelson** [comment]
@Wengier - It works perfectly! Thank you!

**Comment by emendelson** [comment]
Time to close this...
