### ISSUE TITLE
Harmonise keyboard, codepage and country settings

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1769]
**Is your feature request related to a problem? Please describe.**
Right now things work, but are a bit messy.

1. ~~keyboard layout autodetect uses a windows-only regional setting, which may or may-not match the actual keyboard layout the user has.~~
2. codepage set by keyboard autodetect routine does not match that as set by the ```keyb``` command by default. e.g. keyboard autodetect ends up using codepage 437 for most regions, while the ```keyb``` or ```keyboardlayout=``` uses a default codepage that more accurately reflects what historically would have been used.
3. ~~country= setting always defaults to 1 (US), regardless of any region autodetect.~~
4. There is no support for any autodetect on Linux or MacOS.

~~The windows regions are a good indicator for the COUNTRY= setting, but a poor indicator of the host keyboard layout. However, right now the windows regions are only used for guessing the host keyboard layout.~~

**Describe the solution you'd like**
1. ~~windows regions should be used to automatically set the COUNTRY= setting.~~ Something similar should be implemented for Linux and MacOS (freedesktop specification?)
2. default codepage for a keyboard layout should be consistent between autodetect, keyboardlayout= and keyb command.
3. ~~keyboard autodetect on windows, should use a different mechanism to detect the current keyboard layout set. This may not be easy, I was not yet able to find a good method for doing so.~~
4. keyboard autodetect should also support Linux and MacOS. Again not easy, at least for Linux if you want to avoid desktop environment specific APIs.

**Comment by Wengier** [comment]
I have modified the country setting to make it auto-detection (if possible) by default, or fallback to 1 if auto-detection cannot be done. Moreover, with this default setting the country code 81 (Japan) will be used for PC-98 mode.

**Comment by rderooy** [comment]
Nice @Wengier 

Still needs some kind of better solution for the keyboard autodetect. As mentioned country (region) is a very poor indicator of keyboard layout. Here where I live you can buy 4 different keyboard layouts in the local shops (de, fr, be, sf), and instead I use a US keyboard :-)

**Comment by rderooy** [comment]
closing this as most things have been done.
