### ISSUE TITLE
dosbox-x - no status window in windows version

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#177]
is there a way I can enable the status window on the windows version of dosbox-x?

**Comment by toddfraser88** [comment]
whoops! never mind! figured it out.

**Comment by Danfun64** [comment]
Well that's nice....but how in the world did you do it? You can't say you figured it out and not say how!

**Comment by joncampbell123** [comment]
At the command line, pass -console to tell the Win32 build that it should show the console.

For all the command line options run dosbox-x with --help at a command line.

**Comment by thayeeboi890** [comment]
is there a way to do it on linux?

**Comment by rderooy** [comment]
Just start dosbox-x from a terminal and you will get the debug information in the terminal you launched it from.
