### ISSUE TITLE
I can't install CD-ROM in my Windows 95

### ISSUE THREAD

**Issue by ognjenmi** [joncampbell123/dosbox-x#178]
Hi,

I tried everything to install CD-ROM drive in Windows 95 installed in DOSBox-X. I installed it from hard disk image not from CD. I mounted the image file with imgmount and set up config file as advised on DOSBox-X subject on Vogons forum. But CD is not visible in windows. I tried to add it as new hardware but with no success. I even tired to add OAKCDROM.SYS in config.sys and use it with mscdex but then loading of this driver hangs.

in stderr there is lots of write errors generated during this hanging.

I attached all files I considered relevant.

Regards,
Ognjen
[cdromissue.zip](https://github.com/joncampbell123/dosbox-x/files/149517/cdromissue.zip)

**Comment by joncampbell123** [comment]
When you run imgmount before boot Windows 95, do you include the -ide option to tell it which IDE port to connect to? Is IDE emulation enabled?

**Comment by ognjenmi** [comment]
Yes here's the command line I execute
imgmount d CD\DonaldDuck.cue -t iso -ide 2m

**Comment by ognjenmi** [comment]
Should this be enough?

[ide, primary]
enable=true
pnp=true
irq=0
io=0
altio=0
int13fakeio=false
int13fakev86io=false
enable pio32=false
ignore pio32=false
cd-rom spinup time=0
cd-rom spindown timeout=0
cd-rom insertion delay=0

[ide, secondary]
enable=true
pnp=true
irq=0
io=0
altio=0
int13fakeio=false
int13fakev86io=false
enable pio32=false
ignore pio32=false
cd-rom spinup time=0
cd-rom spindown timeout=0
cd-rom insertion delay=0

**Comment by ognjenmi** [comment]
I found out that the problem actually was CD-ROM driver I used. For some reason it does not work DOSBox. I changed the driver and now I can see CD in Windows. Emulation now works, but there is no LFN support and all non 8.3 names are with ~1, ~2 suffixes. I'll put this in separate issue.
