### ISSUE TITLE
Dangerous Dave PC Speaker Sound Doesn't Work.

### ISSUE THREAD

**Issue by Razor221** [joncampbell123/dosbox-x#1781]
**Describe the bug**
PC Speaker sound doesn't work in Dangerous Dave. It's just silent. There is no sound at all

**To Reproduce**
Just start the game and no sound at all

**Expected behavior**
There should be PC Speaker sounds.

**Environment (please complete the following information):**
Windows 10 x64 version 2004
The latest released version 0.83.4

**Additional context**
I tried other games with PC Speaker and they work. I also tried DOSBox ECE and PC Speaker sounds works as intended in Dangerous Dave. The only sound option is PC Speaker with this game so there is no workaround.

**Comment by joncampbell123** [comment]
Works fine here, with sound.

![dave_000](https://user-images.githubusercontent.com/6245486/89267834-98c0ed00-d5ec-11ea-8c01-4767ea9dc0b2.png)

**Comment by joncampbell123** [comment]
Try hitting F2 for the "Control Panel" and select PC speaker sound, hit enter.
![dave_001](https://user-images.githubusercontent.com/6245486/89267968-c0b05080-d5ec-11ea-80a5-ae95a6a746cc.png)

**Comment by Razor221** [comment]
Something on my dosbox-x somehow got broken or something. I tried default settings nothing worked until I decided to re-download the latest version. Now everything works fine with my old settings.
