### ISSUE TITLE
Linux Glide wrapper libglide2x.so

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1788]
**Describe the bug**
I'm not quite sure where to get libglide2x.so for the new Glide support in DOSBox-X. It is definitely not included with any modern Linux distribution.

My guess was OpenGlide. Unfortunately this project seems to have been abandoned years ago. After downloading various ZIP files (both binary and source) from sourceforge, and finding only Windows files, I finally found I had to grab the CVS repository from sourceforge instead.

Unfortunately the compile fails because of a missing windows.h header file. And my understanding is that this is Windows specific, and so the code will not work as-is on Linux.

The same file (GlOgl.h) also includes <GL\gl.h> and <GL\glu.h> with invalid windows style path slashes. 

**To Reproduce**
```
cvs -z3 -d:pserver:anonymous@openglide.cvs.sourceforge.net:/cvsroot/openglide co -P openglide
cd openglide
./bootstrap
./configure
make
```

**Environment (please complete the following information):**
 - Fedora 32
 - DOSBox-X 0.83.5-git

**Additional context**
```
$ make
make  all-recursive
make[1]: Entering directory '/home/robert/github/openglide'
Making all in platform
make[2]: Entering directory '/home/robert/github/openglide/platform'
Making all in linux
make[3]: Entering directory '/home/robert/github/openglide/platform/linux'
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include  -g -O2 -D__unix__ -D__linux__ -I../../platform/linux  -MT library.lo -MD -MP -MF .deps/library.Tpo -c -o library.lo library.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include -g -O2 -D__unix__ -D__linux__ -I../../platform/linux -MT library.lo -MD -MP -MF .deps/library.Tpo -c library.cpp  -fPIC -DPIC -o .libs/library.o
In file included from library.cpp:15:
../../GlOgl.h:37:10: fatal error: windows.h: No such file or directory
   37 | #include <windows.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:432: library.lo] Error 1
make[3]: Leaving directory '/home/robert/github/openglide/platform/linux'
make[2]: *** [Makefile:381: all-recursive] Error 1
make[2]: Leaving directory '/home/robert/github/openglide/platform'
make[1]: *** [Makefile:695: all-recursive] Error 1
make[1]: Leaving directory '/home/robert/github/openglide'
make: *** [Makefile:509: all] Error 2
```

**Comment by rderooy** [comment]
Seems that this openglide fork at least compiles:
https://github.com/voyageur/openglide

**Comment by rderooy** [comment]
Starting dosbox-x with glide=true shows me:
```
LOG: Glide:LFB access: read-write (no aux)
LOG: Glide:Unable to load glide2x library, glide emulation disabled
```
```
$ ls -l /usr/local/lib
total 1948
-rw-r--r--. 1 root root 1294442 Aug  6 11:36 libglide2x.a
-rwxr-xr-x. 1 root root     964 Aug  6 11:36 libglide2x.la
lrwxrwxrwx. 1 root root      19 Aug  6 11:36 libglide2x.so -> libglide2x.so.0.0.0
lrwxrwxrwx. 1 root root      19 Aug  6 11:36 libglide2x.so.0 -> libglide2x.so.0.0.0
-rwxr-xr-x. 1 root root  688536 Aug  6 11:36 libglide2x.so.0.0.0
lrwxrwxrwx. 1 root root      13 Aug  6 11:36 libglide.so.2 -> libglide2x.so
```

Even specifically running dosbox-x as follows makes no change.

```
$ LD_LIBRARY_PATH=/usr/local/lib dosbox-x -conf glide.conf
```

**Comment by rderooy** [comment]
Managed to get it passed the issue. Turned out that /usr/local/lib is not in the default library path. adding it to /etc/ld.conf.d and running sudo ldconfig solved that.

I can run Tomb Raider in 3dfx mode. I copied z:\glide2x.ovl to the tomb raider directory and ran tomb3dfx.exe and I got the 3dfx splash and it works.

But how do I know its not running in the regular voodoo mode, and not the glide passthrough?

**Comment by kcgen** [comment]
Excellent trail blazing @rderooy ! 
I don't have answers, but am impressed with voodoo and glide progress -X continues to make. 🤩

**Comment by rderooy** [comment]
It seems with voodoo=auto it will not use the glide pass-through? The voodoo logo was the hint in this regard as I don't have the 3dfxSpl2.dll file. With voodoo=false the voodoo logo no longer shows on startup of TR1.

CPU usage of dosbox-x is however pretty much the same for both emulation modes, around 20-24% on my system.

- Pressing F2 in TR1 in Voodoo mode, shows a pretty abysmal 6-14FPS range.
- Unfortunately F2 does not work the same way in Glide pass-through mode (it reduces the size of the render area), but performance seems much better.

With TR1 "Unfinished Business" the F2 key behaviour is reversed compared to TR1.
- Running TR1 "Unfinished Business" in Voodoo emulation mode, F2 reduces the size of the render area
- Running TR1 "Unfinished Business" in Glide pass-through mode, F2 does show a FPS counter, and it sticks pretty close to 30 FPS.

**Comment by rderooy** [comment]
Trying to understand how to get the 3dfx splash screen to show on Linux in Glide pass-through mode, I checked the code and found that it is Windows only. This is not clear from the reference config.

**Comment by Wengier** [comment]
The "voodoo" and "glide" are separate options. So you need to set "glide=true" if you want to enable glide pass-through. As for the3dfx splash screen, it apparently requires the 3dfxSpl2.dll file, and I wonder if a Linux counterpart indeed exists?

**Comment by rderooy** [comment]
I understand I need glide=true for glide pass-through, but that seems to require also that I set voodoo=false? With the default voodoo=auto it seems that TR1 was still using the PCI voodoo emulation.

**Comment by kcgen** [comment]
Conflicting argument bools sometimes hint that they should be inverted into a single state. 

`3d_type = voodoo, glide, nvidia_tnt, s3_savage, etc..`

Games only used one card (or chipset-type, if SLI), so maybe this collapsing of options makes sense?

**Comment by Wengier** [comment]
I don't actually think that "glide=true" requires "voodoo=false". For example, with the Tomb Raider 3dfx I uploaded in the earlier package, it has the setting "voodoo=auto" and "glide=true" (in dosbox-x.conf). If on the other hand I set "glide=false" while keeping "voodoo=auto", then the game will not load, failing with the error "Fatal error: unable to load DLL.". This is an indication that "glide=true" does work independently of the "voodoo=auto" setting.

**Comment by Wengier** [comment]
The said package is still available from: [tomb3d.zip](http://cndos.fam.cx/dosware/tomb3d.zip)

**Comment by rderooy** [comment]
It seems I got confused due to the 3dfx splash showing. I assumed I would only get the 3dfx splash if it was using the original GLIDE2X.OVL (or on Windows if you have the DLL file installed).

Instead on Linux with
```
[pci]
voodoo=auto
glide=true
```
The Z: drive contains GLIDE2X.OVL and starting TR1, I get the 3dfx splash screen

With
```
[pci]
voodoo=false
glide=true
```
The Z: drive contains GLIDE2X.OVL and starting TR1, I **do not** get the 3dfx splash screen

With
```
[pci]
voodoo=auto
glide=false
```
The Z: drive **obviously does not** contains GLIDE2X.OVL and starting TR1, I get the 3dfx splash screen

**Comment by rderooy** [comment]
Strangely starting TR1 Unfinished Business, I don't get the 3dfx splash screen in any of the modes, regardless of OVL file.

**Comment by rderooy** [comment]
A possible "hack" could perhaps be that if glide=true and a program tries to open GLIDE2X.OVL that it is automatically redirected to Z:\GLIDE2X.OVL instead.

**Comment by rderooy** [comment]
I have created a draft Wiki page on how to setup the emulated 3dfx Voodoo
https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3ASetting-up-3dfx-Voodoo-in-DOSBox%E2%80%90X

It needs some updates for setting up glide2x.dll for Windows and libglide2x.dylib for macOS.

**Comment by rderooy** [comment]
Until now I had only tested with SDL1, trying to start TR1 or TR1UB with the SDL2 build results in an immediate segfault. Either with Voodoo HLE (Glide passthrough) or Voodoo LLE (hardware emulation) mode.

```
LOG: Setting execute permission on the code cache has failed
Segmentation fault
```

**Comment by Wengier** [comment]
@rderooy Since the issue with SDL2 build happens also with Voodoo hardware emulation mode, I don't think it is related to the Glide code in any way. In any case, I wonder if the said issue is Linux-specific or it also happens in Windows? If so, can you upload a package that can produce the issue? The package I uploaded earlier also used the SDL2 build, but I have never seen such an issue yet.

**Comment by rderooy** [comment]
@Wengier seems it is solved by using core=normal

**Comment by Wengier** [comment]
@rderooy Can you upload a Tomb Raider package that requires GLIDE2X.OVL to be on the current directory (instead of Z:\) so that I can try to redirect it in the code? The Tomb Raider 3dfx package I uploaded earlier is apparently fine with the file GLIDE2X.OVL located on Z:\.

**Comment by rderooy** [comment]
@Wengier It is the Tomb Raider budget release by Sold Out Software. As it is a late release, it includes all the updates and patches and the Unfinished Business expansion. You can find it here: https://archive.org/details/TombRaiderBySoldOutSoftware

In any case, I have been replacing GLIDE2X.OVL. In fact, I created a batch file to automatically handle it. I never considered that it would automatically find the file on the Z: drive. But I guess for that to work I need to delete the OVL file from the game directory?

```
IF EXIST Z:\GLIDE2X.OVL echo 3dfx Glide pass-through support enabled
echo.
echo 1) Tomb Raider (svga)
echo 2) Tomb Raider (3dfx)
echo 3) Tomb Raider - Unfinished Business (svga)
echo 4) Tomb Raider - Unfinished Business (3dfx)
echo.
CHOICE /N /C:1234 "Please press 1, 2, 3 or 4."
IF ERRORLEVEL == 4 GOTO TR1UB_3DFX
IF ERRORLEVEL == 3 GOTO TR1UB
IF ERRORLEVEL == 2 GOTO TR1_3DFX
IF ERRORLEVEL == 1 GOTO TR1
EXIT

:TR1
CD TOMBRAID
TOMB
EXIT

:TR1UB
CD TOMBRAID
TOMBUB
EXIT

:TR1_3DFX
CD TOMBRAID
IF EXIST Z:\GLIDE2X.OVL COPY Z:\GLIDE2X.OVL . /Y
IF NOT EXIST Z:\GLIDE2X.OVL COPY GLIDE2X.ORG GLIDE2X.OVL /Y
TOMB3DFX
EXIT

:TR1UB_3DFX
CD TOMBRAID
IF EXIST Z:\GLIDE2X.OVL COPY Z:\GLIDE2X.OVL . /Y
IF NOT EXIST Z:\GLIDE2X.OVL COPY GLIDE2X.ORG GLIDE2X.OVL /Y
TOMBUB3
EXIT
```

**Comment by Wengier** [comment]
@rderooy I have downloaded the "Tomb Raider by Sold Out Software.zip" file from the link you posted, and found that it only contains the CD image "Tomb Raider.cue" and "Tomb Raider.bin". Inside the CD image I can only find TOMB.EXE but not TOMBUB or TOMBUB3, nor GLIDE2X.OVL. Where did you get these files from?

P.S. If the game indeed already has the file GLIDE2X.OVL that is different from the file located in Z:, I think you can probably just rename the file in the game directory without having to copy the file from Z: to the game directory. You may want to verify this for the version you have.

**Comment by Wengier** [comment]
I have already added glide2x.dll install instructions for Windows in the Wiki page:

https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3ASetting-up-3dfx-Voodoo-in-DOSBox%E2%80%90X

**Comment by Wengier** [comment]
@rderooy I have confirmed that the 3dfx version of the Screamer Rally game can also automatically find the GLIDE2X.OVL file on the Z drive, as long as you rename the original GLIDE2X.OVL file in the game folder to something else (there is no need to copy the file GLIDE2X.OVL from Z: to the game folder).

**Comment by arromdee** [comment]
Yes, I used that openglide.

Packages I have installed include these:

/usr/local/src/dosbox-x% rpm -q -a | grep mesa
lib64mesaglu1-devel-9.0.0-8.mga7
mesa-19.3.4-1.mga7
lib64mesaegl1-19.3.4-1.mga7
lib64mesavulkan-drivers-19.3.4-1.mga7
lib64osmesa8-20.0.7-3.mga7
lib64mesagl1-19.3.4-1.mga7
libmesagl1-19.3.4-1.mga7
lib64mesakhr-devel-19.3.4-1.mga7
lib64mesaegl1-devel-19.3.4-1.mga7
lib64mesaglu1-9.0.0-8.mga7
lib64mesagl1-devel-19.3.4-1.mga7
mesa-demos-8.4.0-2.mga7

/usr/local/src/dosbox-x% rpm -q -a | grep SDL
lib64SDL_gfx16-2.0.26-1.mga7
lib64SDL-devel-1.2.15-23.1.mga7
lib64SDL_net1.2_0-1.2.8-9.mga7
lib64SDL_net-devel-1.2.8-9.mga7
lib64SDL_sound1.0_1-1.0.3-19.mga7
lib64SDL1.2_0-1.2.15-23.1.mga7

**Comment by Wengier** [comment]
@rderooy The section containing the 3dfx/glide settings is now called [voodoo]. A new config option "voodoo_maxmem" (default: true) is added to specify whether to use the 12MB max memory instead of the standard 4MB memory (similar to DOSBox ECE). The config option "voodoo" is now called "voodoo_card" to make clear it is for emulating the Voodoo card hardware (not the high-level Glide emulation). Since these settings were introduced only after version 0.83.4 and the only exception "voodoo" always defaults to auto, I believe this change is still in time.

**Comment by rderooy** [comment]
@Wengier I had seen the PR, and have noticed you updated the draft wiki to match.
