### ISSUE TITLE
-_ and /? keys do the same in keymapper without a mapper file

### ISSUE THREAD

**Issue by Laci60** [joncampbell123/dosbox-x#1792]
**Describe the bug**
I have hungarian Windows 10 with hungarian keyboard hu208 and code page 852. If I start dosbox-x without a mapper file, -_ (üÜ) and /? (-_) keys do the same: both act like -_ (üÜ) key. If there is a mapper file, this problem does not exist.

**To Reproduce**
1. Start dosbox-x without a mapper file
2. Start keymapper
3. Press -_ (üÜ) then /? (-_) key: mapper editor highlights -_ (üÜ) key in both case
4. Save unchanged keymap and restart dosbox-x
5. Press -_ (üÜ) then /? (-_) key: both key highlights the appropriate key

**Expected behavior**
Both -_ (üÜ) and /? (-_) keys should highlight the appropriate key in keymap editor even keymap file does not exist.

**Screenshots**
I could not take suitable screenshot.

**Environment (please complete the following information):**
 - Operating system: Windows 10 hungarian
 - DOSBox-X release version 0.83.4 SDL1
 - Used configuration: no .conf file (internal one used)

**Additional context**
No other context.

**Comment by Wengier** [comment]
I see you are using the SDL1 build. Have you tried the SDL2 build instead? While the new default ```usescancode=auto setting``` on SDL1 build can solve most non-US keyboard layout issues, it is known that certain issues related to non-US keyboards still remain on the SDL1 version.

**Comment by Laci60** [comment]
After reading your answer I tried SDL2 build. It have not the above mentioned issue.
I will try my DOS programs with SDL2 build. If those pass the test I will use SDL2 build instead of SDL1.
