### ISSUE TITLE
Serial nullmodem server not working

### ISSUE THREAD

**Issue by jwt27** [joncampbell123/dosbox-x#1796]
**Describe the bug**
When a serial port is configured with `nullmodem server:1`, no TCP port is opened, and no COM port is created.

**To Reproduce**
dosbox.conf:
```
[serial]
serial1 = nullmodem port:2222
serial2 = nullmodem server:1 port:3333
serial3 = dummy
serial4 = dummy
```
BDA dump shows:
```
C:\>debug
-d40:0
0040:0000  F8 03 00 00 E8 03 E8 02 ...
```
`mode` shows no COM2 port, also basic commands like `ctty` or redirection say "file not found".  
`netstat` in Windows shows no open port 3333.

**Environment:**
 - Windows 7 amd64
 - DOSBox-X 0.83.4
 - Used configuration: see above

**Comment by rderooy** [comment]
server: should be followed by the IP or hostname of the destination server. So if you have a second dosbox-x instance running on the same machine, listening on port 3333, it would be ```serial2 = nullmodem server:127.0.0.1 port:3333```

**Comment by jwt27** [comment]
Ahh, I'm stupid (or, this could be documented better).  So specifying `server` makes dosbox-x work as a *client*.  I was assuming it's a boolean value, but it does make sense since there's no other way to specify where to connect as a client.

The weird thing is that I used this config some time ago, or at least, I don't remember changing it in the meantime.  I must be misremembering.

Anyhow, thanks, it works now.
