### ISSUE TITLE
NeedForSpeed 2

### ISSUE THREAD

**Issue by DSN9990** [joncampbell123/dosbox-x#1798]
Crashes with this message:

![image](https://user-images.githubusercontent.com/69558812/90080607-706a7a00-dce1-11ea-833f-11c5ed90ce7d.png)

DOSBox-X version: 0.83.4 (Tried both SDL1 and SDL2 MinGW 64Bit/32Bit build)

How to reproduce:

Install Win95
Install the Game
Run the game

Tried first rip version, also tested cd version (with iso) and did not work also.

Some of my Config (I used this before, I already had deleted):
machine = svga_s3
memsize = 32
vmemsize = 4
cputype = pentium_mmx
cycles = max
voodoo = opengl
glide = true
sblaster = sb16vibra

I'm on Win10 X64

**Comment by DSN9990** [comment]
I noticed that no Win95 game worked in DOSBox-X. How I can fix this?
I tried MK Trilogy and it did not work.
It crashes with a "DOSBox-X has stopped working" error when I select auto config or choose manual config (and select S3 as the manufacturer) in the UNIVBE configuration.
But the DOS version worked fine, not the Win95 version. And all my dos games works fine.

**Comment by rderooy** [comment]
Did you follow the guide for installing Win95?
https://github.com/joncampbell123/dosbox-x/wiki/Guide%3AMicrosoft-Windows-in-DOSBox%E2%80%90X

**Comment by DSN9990** [comment]
Yes, and it did not work also.

**Comment by rderooy** [comment]
glide=true is not to be used with Windows 95. It is only for DOS Glide applications that use GLIDE2X.OVL.

**Comment by DSN9990** [comment]
It first gives this error:
![nfs2error1](https://user-images.githubusercontent.com/69558812/90139303-8f532580-dd4e-11ea-87b0-84d80a5e6a18.jpg)

And then this:
![nfs2error2](https://user-images.githubusercontent.com/69558812/90139447-c6c1d200-dd4e-11ea-8a5b-a2e1712f5ac7.jpg)

**Comment by rderooy** [comment]
Do you get similar problems with using the regular S3 drivers instead of UniVBE?

**Comment by DSN9990** [comment]
Yes

**Comment by DSN9990** [comment]
I got NFS2 running very little time. It crashed a few seconds later in game and the system hanged up.
I now set cycles=60000 in my config, and Dosbox-x is slower than cycles=max.

**Comment by DSN9990** [comment]
I got also various strange errors
