### ISSUE TITLE
WordPerfect 4.2 tries to open non-existent file

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1800]
**Describe the bug**
The very old (DOS 1.0-compatible) WordPerfect 4.2 tries to open a file named "2" when launched with no command-line parameters.

**To Reproduce**
Download a complete WPDOS 4.2 installation from
http://www.columbia.edu/~em36/wpdos/WP42.7z
Unpack it. In DOSBox-X, navigate to its folder and run WP.EXE.
It will report "File not found" and the bottom line of the screen will show that it thinks it is editing a file named "2".

**Expected behavior**
It won't report "File not found" when launched with no command-line parameters.

**Environment (please complete the following information):**
 Windows 10
 August 1 release code

**Additional context**
Probably two people in the universe still use this program, and unfortunately I've been asked to support them. This is minor annoyance, but it may point to something else that's worth fixing.

**Comment by Wengier** [comment]
@emendelson I have tried the package you linked in DOSBox-X, but it looks like I cannot reproduce the said problem on the two computers I tried. Running the program WP.EXE seems to work fine, without showing any errors here. I tried both the default setting and my customized setting, no issue found so far.

**Comment by Allofich** [comment]
I can't reproduce it either, using a build from 7/30.

I did notice one small oddity, though.

1) Start DOSBox-X and run WP.EXE.
2) While WP.EXE is running, close DOSBox-X. (I did this because I don't know the program's command to quit it)
3) Start DOSBox-X again and run WP.EXE again.
4) A warning screen will appear asking whether another instance of WP.EXE is running, I assume as a result of step 2. The initial "A" of "Are you.." will show for a moment then disappear when the Y/N prompt at the right of the screen appears.

So the question is if the "A" also disappears on a real MS-DOS machine.
![wp_000](https://user-images.githubusercontent.com/19624336/90311334-da2e9200-df34-11ea-9a17-0d7b051d293f.png)

**Comment by emendelson** [comment]
@Wengier @Allofich - Well, this is embarrassing. The release versions run WP42 with no problems at all - and my build runs them with no problems when I run without a .CONF file, so clearly something's wrong in the configuration that I normally use, and I'll have to track that down.

@Allofich - The "are other copies running" problem is what happens with vDos; it apparently results from WP's failure to delete its temporary files {WP}.* when it closes. I've been told by someone who knows about these things that this is the result of DOS 1.0-style file management, but I don't have the details. I can't imagine why it should happen to you with DOSBox-X.

When I figure out what's causing this in my configuration, I'll report. My fork uses an AutoIt wrapper to launch DOSBox-X and it's possible that something's going wrong there.

Meanwhile, apologies for wasting bandwidth on an incomplete and maybe pointless report.

**Comment by Wengier** [comment]
@Allofich The shortcut to quit from (any version of) DOS-based WordPerfect is F7.

Also, the display issue of the initial "A" as in "Are other..." has already been fixed in my latest pull request.

**Comment by emendelson** [comment]
Apologies for wasting bandwidth on this. It turns out that the conf file I was using in my system for plain DOS had two [autoexec] sections, and the environment seems to have got confused. Fixed; and apologies again.

**Comment by emendelson** [comment]
Apologies for wasting bandwidth on this. It turns out that the conf file I was using in my system for plain DOS had two [autoexec] sections, and the environment seems to have got confused. Fixed; and apologies again.
