### ISSUE TITLE
Pixel Perfect?

### ISSUE THREAD

**Issue by bob12111** [joncampbell123/dosbox-x#1801]
I'd like to set my output as pixel perfect, similar to how DOSBOX ECE could do.  Think we could implement a pixel perfect setting?

**Comment by Wengier** [comment]
The author of the pixel perfect patch, @ant-222 had already accepted my invitation to implement it for DOSBox-X earlier. He said he would do it when he becomes available.

**Comment by bob12111** [comment]
So, it's coming, then...?

**Comment by Wengier** [comment]
Then you can use it if you wish...

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by ant-222** [comment]
And I am no available yet :-)

**Comment by sikthehedgehog** [comment]
o_o

**Comment by ant-222** [comment]
If you feel like it, you may use adapt my code from *DOSBox EXE* or *DOSBox staging* using the scaling algorithm from my generic scaling unit [`ppscale`](https://launchpad.net/ppscale). I, however, wanted to try integer scaling [built](https://wiki.libsdl.org/SDL_RenderSetScale) into *SDL 2*, instead of doing it manually (which is slow) or relying on nearest-neighbor interpolation supported by *OpenGL*.

**Comment by dreamer** [comment]
Oh, hi @ant-222 - in case you missed it, I brought back an option of using your algorithm with OpenGL (in [dosbox-staging 0.76.0-alpha builds](https://dosbox-staging.github.io/downloads/devel/)), so now both `output=openglpp` and `output=texturepp` work exactly as they used to work in ECE :)

**Comment by ant-222** [comment]
A little of topic update for whoever is interested: my [fork](https://github.com/ant-222/dosbox-x) of *DOSBox-X* with pixel-perfect mode implemented via `openglpp`.

**Comment by Wengier** [comment]
The pixel perfect scaling is already supported in DOSBox-X version 0.83.10 via ```output=openglpp```.
