### ISSUE TITLE
GunMetal DOS installer shows not enough free space

### ISSUE THREAD

**Issue by DSN9990** [joncampbell123/dosbox-x#1805]
**Describe the bug**
The DOS installer for GunMetal (INSTALL.EXE) reports insufficient free space, even when setting "freesize 1000" (haven't tried this, but persists anyway).
No matter what installation type is selected.
INSTALL.EXE appears to only run if "DOS4GW INSTALL.EXE" is typed, otherwise it gives an error saying:

"DOS/4GW fatal error (1004): syntax is DOS4GW <executable.xxx>"

**To Reproduce**
Run INSTALL.EXE by typing DOS4GW INSTALL.EXE on the CD
Select any installation type
Now it shows "WARNING! You don't have enough space on selected drive for full installation." and exits when pressing enter

**Expected behavior**
INSTALL.EXE should report enough free space on HDD

**Screenshots**

![dos4gw_000](https://user-images.githubusercontent.com/69558812/90388329-0134b300-e05e-11ea-89c7-904d4b71a2ae.png)

**Environment (please complete the following information):**
DOSBox-X 0.83.4
dosbox-x.conf:
   
   [sdl]
output=direct3d
autolock=false
mouse_emulation=always

[dosbox]
vmemsize=2
memsize=24
vesa modelist cap=32
allow low resolution vesa modes=true
allow explicit 24bpp vesa modes=true
allow high definition vesa modes=true
allow unusual vesa modes=true
allow 32bpp vesa modes=true
allow 24bpp vesa modes=true
allow 16bpp vesa modes=true
allow 15bpp vesa modes=true
allow 8bpp vesa modes=true
allow 4bpp vesa modes=true
allow 4bpp packed vesa modes=true
allow tty vesa modes=true
ignore extended memory bit=true

[cpu]
core=dynamic
cputype=pentium
cycles=max

[pci]
voodoo=auto
glide=true

[dos]
hard drive data rate limit=0
ver=7.1

**Comment by rderooy** [comment]
Seems this is a known problem, even on retro DOS machines.
https://www.vogons.org/viewtopic.php?t=34791

The installer is simply broken.

**Comment by DSN9990** [comment]
How can I install the game manually? Which files/folders I should copy?
Can you tell me all files/folders which I should copy?

**Comment by rderooy** [comment]
I suggest you ask on the Vogons thread.

**Comment by DSN9990** [comment]
Yes, thanks.
