### ISSUE TITLE
left ctrl+left alt+arrow keys (or some other keys) resets the virtual machine

### ISSUE THREAD

**Issue by AshyRaccoon** [joncampbell123/dosbox-x#1828]
**Describe the bug**
When I press left ctrl+left alt+any arrow key, the virtual machine resets, similar to when going to the Main menu and using "Reset virtual machine".

This also happens with left ctrl+left alt+any one of the following keys: left right up down, ins home end pgdn pgup, any numpad number (whether numlock is on or off).

It does not happen when using right ctrl or right alt.

Interestingly, I cannot get it to happen when playing Commander Keen 4, Cosmo's Cosmic Adventure, Duke Nukem 1, or Doom.
It does happen at the initial DOS prompt, during Commander Keen 1, ZZT, or OMF2097.
(Tested by pressing left ctrl+left alt+right arrow.)

**Environment:**
Windows 10 (1909)
Default dosbox-x.conf in all cases

It happens in two releases I tried:
0.83.5 (dosbox-x-windows-0.83.5-setup.exe) (sdl, sdl2, mingw)
0.83.2 (dosbox-x-windows-20200531-220809-windows.zip)

Notably, the other one I tried does not have the bug:
0.83.1 (dosbox-x-windows-20200502-170825-windows.zip)

**Comment by rderooy** [comment]
Just tried it here on Linux with the latest build.

I cannot trigger it with the cursor keys, but I can with ins, home, end, pgdn, pgup.

**Comment by Wengier** [comment]
Thanks for reporting this! This bug was introduced when support for restarting the VM via Ctrl+Alt+Del was added. I have already fixed it in the latest code.
