### ISSUE TITLE
Uninstalling DOSBox-X doesn't delete all context menu items

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1835]
**Describe the bug**

After uninstalling, the context menu is still present.

**To Reproduce**
1. install
2. uninstall
3. check context menu

**Expected behavior**

There shouldn't be any leftovers after uninstalling.

Appears to be the case for `Directory` and `Directory\Background`.

**Screenshots**

Installed:

![2020-09-10_19-57-59](https://user-images.githubusercontent.com/1537591/92776931-00164d80-f3a0-11ea-895d-3a12eb219984.png)

Uninstalled:

![2020-09-10_19-58-58](https://user-images.githubusercontent.com/1537591/92777030-17edd180-f3a0-11ea-9879-c1a20ad61863.png)

If you click it you'll get this:

![explorer_2020-09-10_19-59-16](https://user-images.githubusercontent.com/1537591/92777070-20460c80-f3a0-11ea-8c13-289b60f9eb22.png)

**Environment (please complete the following information):**
 - Microsoft Windows [Version 10.0.19041.450]
 - dosbox-x-windows-0.83.5-setup.exe

**Comment by Wengier** [comment]
Welcome back @aybe! And thanks for reporting this! I can confirm that it is indeed the case for (foreground/background) directory entry, although it does not occur for file entries. I will look into the problem and fix it soon!

**Comment by Wengier** [comment]
It is already fixed in the code I believe. You can verify it on your computer too.

**Comment by aybe** [comment]
Thanks !

Okay, I'll check, closing in the meantime.

**Comment by taekout** [comment]
This still happens to me. This bug still exists.
