### ISSUE TITLE
Improve "Packed file is corrupt. Now run it with LOADFIX" message

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1839]
**Is your feature request related to a problem? Please describe.**

![explorer_2020-09-10_21-09-55](https://user-images.githubusercontent.com/1537591/92788188-07425900-f3aa-11ea-8a29-14644d77363f.png)

**Describe the solution you'd like**

This is a bit confusing warning message, I think I'd be nice that user knows this comes from DOSBox-X itself:

Here's how a better message for the user could be, with DOSBox-X being explicitly written:

```
DOSBox-X couldn't load the executable:

Reason: packed file is corrupt

Trying again with LOADFIX
```

**Comment by Wengier** [comment]
Thanks for the suggestion! It is always a good idea to improve the out of box experience for new users in DOSBox-X. The only concern I have is that the message “Packed file is corrupt” did come from the executable itself, so it will be on the first line, but the other messages can all be improved, so the overall message output to the user can be something like this:

```
Packed file is corrupt
DOSBox-X couldn't load the executable due to the above error.
Trying again with LOADFIX...
```

Let me know if you have further suggestions for improvement.

**Comment by aybe** [comment]
Okay I didn't realize that !

Beside that maybe `DOSBox-X` could be highlighted by using a different color I think it's proper.

**Comment by Wengier** [comment]
@aybe Good suggestion! How about this:

![image](https://user-images.githubusercontent.com/8216923/92795240-38a52f80-f37e-11ea-9254-61714a12b0ad.png)

**Comment by aybe** [comment]
What about setting `DOSBox-X` a distinct background color so it gets spotted easily since messages can briefly appear and disappear ?

![dosbox-x_2020-09-10_23-05-47](https://user-images.githubusercontent.com/1537591/92806323-2d6ff500-f3ba-11ea-81f3-b5cffa69a0fb.png)

**Comment by Wengier** [comment]
@aybe What is the color code you used to display ``DOSBox-X``` in color?

**Comment by aybe** [comment]
![2020-09-10_23-45-30](https://user-images.githubusercontent.com/1537591/92812534-bd646d80-f3bf-11ea-9866-85ee4fcfded3.png)

![2020-09-10_23-45-48](https://user-images.githubusercontent.com/1537591/92812555-c5241200-f3bf-11ea-831d-dbd056a32f69.png)

![dosbox-x_2020-09-10_23-46-56](https://user-images.githubusercontent.com/1537591/92812634-f0a6fc80-f3bf-11ea-8b47-def927a39faf.png)

Not sure if it's Github, ShareX, night light mode or PNG but somehow what you see isn't the exact colors i have here, some color profile is being applied in the shots!

**Comment by aybe** [comment]
Just tested it, seems like code is there but for some reason it's never hit, I guess it's not finished yet.

**Comment by Wengier** [comment]
@aybe I have tested a few color combinations, but while "DOSBox-X" alone with colors seems to look fine, when combined with other words it did not appear to look very good so far, at least for the color combinations I have tried. If you can find a color combination that looks good for the whole sentences, please let me know, thanks!

**Comment by aybe** [comment]
Let's keep it simple for the time being ?

Something like this ?

![dosbox-x_2020-09-11_19-45-49](https://user-images.githubusercontent.com/1537591/92956599-70d46d00-f467-11ea-9b76-19a178a918e6.png)

![dosbox-x_2020-09-11_19-49-30](https://user-images.githubusercontent.com/1537591/92956874-edffe200-f467-11ea-803b-b1d4af5ef366.png)

**Comment by Wengier** [comment]
@aybe It is not really a "fatal error" I think, or else DOSBox-X should probably exit immediately.

**Comment by aybe** [comment]
This is just an example,

The general idea was as follows:

- `DOSBox-X` is highlighted
- then the descriptive error message, e.g. `Fatal Error !`

**Comment by Wengier** [comment]
@aybe Sure, I can understand that. I tried some background colors, can you check which one is better?

![image](https://user-images.githubusercontent.com/8216923/92961020-94ce8900-f43c-11ea-953f-73404a640052.png)

![image](https://user-images.githubusercontent.com/8216923/92961039-9a2bd380-f43c-11ea-9aa6-f2210ad4c7f5.png)

**Comment by aybe** [comment]
Second is great 💯

**Comment by Wengier** [comment]
Done.

![image](https://user-images.githubusercontent.com/8216923/92969500-16c5ae80-f44b-11ea-991d-88e25fbe34f9.png)

**Comment by aybe** [comment]
Great, thank you!
