### ISSUE TITLE
Quit warning not always shown

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1841]
**Describe the bug**

The quit warning isn't always shown.

**Expected behavior**

Shouldn't it always be visible?

**Screenshots**

(done with `Run with ...` context menu)

![dosbox-x_2020-09-10_23-24-41](https://user-images.githubusercontent.com/1537591/92809359-d4ee2700-f3bc-11ea-986d-d0e597d23d48.png)

Not shown for QBASIC:

![dosbox-x_2020-09-10_23-25-21](https://user-images.githubusercontent.com/1537591/92809456-eafbe780-f3bc-11ea-90da-79f5a96c8b85.png)

**Environment (please complete the following information):**
 - Operating system Windows 10
 - DOSBox-X release version 0.83.5

**Comment by Wengier** [comment]
@aybe The quit warning currently works like this:

If set to auto (default), DOSBox-X will warn if there are open file handles or a guest system is currently running. Note that this is not exactly the same as one program is currently running.

If set to true, DOSBox-X will always show a quit warning.

If set to false, DOSBox-X will never show a quit warning.

So if you want the quit warning to be always shown, you can set "quit warning=true" in the config file.

**Comment by aybe** [comment]
closing, see #1843 instead
