### ISSUE TITLE
Confusing "Quick right mouse button copy/paste"

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1842]
**Is your feature request related to a problem? Please describe.**

https://github.com/joncampbell123/dosbox-x/blob/23653d031af2036b241d53bb94e548fff79a1ec7/CHANGELOG#L329

![2020-09-10_23-51-54](https://user-images.githubusercontent.com/1537591/92812988-a70ae180-f3c0-11ea-93dd-28df1cb75912.png)

This is confusing, I thought I'd be able to copy a .BAS program I typed and that wasn't yet saved but no, it overwrote it with Windows clipboard!

**Describe the solution you'd like**

This should rather be something like `Paste text in Windows clipboard with right mouse button click`, things will be clear then.

**Comment by Wengier** [comment]
@aybe This functionality is for both select, copy to and paste from the Windows clipboard, not just the paste function. If you drag the right mouse button without releasing it, then text will be selected and highlighted. Releasing the right mouse button will copy the selected text to the clipboard. If you don't drag and simply release the right mouse button, then text from the Windows clipboard will be pasted to the DOSBox-X window.

**Comment by aybe** [comment]
OK amazing !!!

Something emerges from this for me, effectively it's written in the wiki,

![dosbox-x_2020-09-11_00-10-19](https://user-images.githubusercontent.com/1537591/92814260-344f3580-f3c3-11ea-8ed3-1035ea3115d5.png)

Don't you think it'd be nice that:

- wiki also shows url like the ones below
- possibly gets blinking treatment so it drags user attention

As a consequence the repository would probably receive less already solved issues by just reading the wiki.

Maybe it's also time to overhaul the welcome screen to give a distinct feeling and signature to DOSBox-X?

After all, the ECE fork did it in some way:

![DOSBox_2020-09-11_00-15-03](https://user-images.githubusercontent.com/1537591/92814784-e0911c00-f3c3-11ea-8b92-66ef3351e300.png)

Also makes me think that the old Daum icon could be 'refreshed' somehow !

**Comment by Wengier** [comment]
I agree it is a good idea to give a distinct feeling and signature to DOSBox-X. What color is the better for DOSBox-X do you think?

**Comment by aybe** [comment]
Not sure really,

It's probably easier to give a try sketching on a good ANSI editor for some WYSIWIG 😉:

https://www.onworks.net/software/windows/app-ansi-text-editor
http://wiki.bbs.nz/ansi:editors

**Comment by aybe** [comment]
First above looks nice but does not start !

This one works and seems to be good, albeit 24-bit only:
https://www.gridsagegames.com/rexpaint/index.html

**Comment by Wengier** [comment]
How about this style:

![image](https://user-images.githubusercontent.com/8216923/92969041-2a244a00-f44a-11ea-9b1e-21b7d70db48d.png)

**Comment by rderooy** [comment]
Not a fan... I personally like the current colour scheme much better.

**Comment by aybe** [comment]
Closing, continuing the discussion on a dedicated issue #1849

**Comment by aybe** [comment]
Sorry, reopening since the actual issue hasn't been solved.

**Comment by Wengier** [comment]
@rderooy That is why I asked for a discussion. Before a consensus is made the code will not merged to the repository.

**Comment by aybe** [comment]
@Wengier 

I propose to rename the menu item to something like this:

- Enable shared clipboard with host
  - Copy on select/paste with right mouse button
  - Copy on select/paste with middle mouse button

So the actual menu item gets an extra child entry to allow selecting an alternate button.

**Comment by ThePillenwerfer** [comment]
If you're changing the welcome screen how about making the box 80 columns wide so it doesn't look like there's a scaling problem?

**Comment by Wengier** [comment]
@aybe That is not a bad suggestion! Will do!

**Comment by Wengier** [comment]
@ThePillenwerfer Why not? It is a cool idea actually.

**Comment by Wengier** [comment]
See the new design in Issue #1849.

**Comment by Wengier** [comment]
@rderooy You can check out the latest design in the other issue too.

**Comment by Wengier** [comment]
I have now added  a "Shared Windows clipboard functions" menu group (under "Main"), which allows you to enable or disable the different ways for DOSBox-X to communicate with the Windows clipboard. One of these ways is to copy/paste via the mouse button, which now supports either the middle mouse button or the right mouse button.

![image](https://user-images.githubusercontent.com/8216923/93037854-68b83100-f611-11ea-9e34-2cd0cfb6a3ae.png)

**Comment by aybe** [comment]
Amazing, thank you @Wengier 🥇
