### ISSUE TITLE
Some configuration GUI states should not be cancelable.

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1846]
**Describe the bug**

Some configuration GUI states should not be cancelable (I think).

**Expected behavior**

See below, you can circumvent the GUI easily by invoking app. menu on top.

**Screenshots**

![dosbox-x_2020-09-11_06-59-12](https://user-images.githubusercontent.com/1537591/92863530-54e7b180-f3fc-11ea-990d-9800ca4ade4d.png)

**Environment (please complete the following information):**
 - DOSBox-X release version 0.83.5

**Comment by Wengier** [comment]
Good suggestion! It is already done in the latest code.
