### ISSUE TITLE
Default config does not boot

### ISSUE THREAD

**Issue by heftig** [joncampbell123/dosbox-x#185]
The default config does not boot, causing a `not enough memory for internal tables` error.

Increasing `private area size` as the config suggests does not help.

Disabling `dynamic kernel allocation` does help.

Arch Linux x86_64

**Comment by joncampbell123** [comment]
Is this from running DOSBox-X with no configuration file whatsoever?

**Comment by heftig** [comment]
Yes, using the config file generated that way.

**Comment by joncampbell123** [comment]
Could you post the config file it generated? I can't reproduce it on my end.

**Comment by heftig** [comment]
I now wonder where the `dosbox-0.801.conf` came from, since I can't remember using any commands to write it, and dosbox doesn't seem to do so automatically, either.

Anyway, without a config it does boot, so sorry for the noise.
