### ISSUE TITLE
IMGMAKE command from Windows 98 wiki doesn't work

### ISSUE THREAD

**Issue by GHExplorer** [joncampbell123/dosbox-x#1851]
This command from the Windows 98 installation wiki, 

https://github.com/joncampbell123/dosbox-x/wiki/Guide:Installing-Windows-98

     IMGMAKE hdd.img -size 16384

returns you to the prompt, with a help message, as if you typed the wrong syntax.

**Comment by rderooy** [comment]
Thanks, that is a typo. It should be
```
IMGMAKE hdd.img -size 16384 -t hd
```

**Comment by rderooy** [comment]
I have corrected it in the draft wiki for the next DOSBox-X release
https://github.com/Wengier/dosbox-x-wiki/wiki

**Comment by GHExplorer** [comment]
Ok, thanks. I went with the 8 gig, for now.

Regards,

	-----------------------------------------From: "Robert" 
To: "joncampbell123/dosbox-x"
Cc: "GHExplorer", "Author"
Sent: Saturday September 12 2020 7:58:09AM
Subject: Re: [joncampbell123/dosbox-x] IMGMAKE command from Windows 98
wiki doesn't work (#1851)

	Thanks, that is a typo. It should be 

	IMGMAKE hdd.img -size 16384 -t hd  

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2]. 

Links:
------
[1]
https://github.com/joncampbell123/dosbox-x/issues/1851#issuecomment-691477082
[2]
