### ISSUE TITLE
Add menu options to select a CPU model, e.g. 486DX-33, Pentium 60, 75, etc 

### ISSUE THREAD

**Issue by DSN9990** [joncampbell123/dosbox-x#1854]
**Describe the solution you'd like**
If possible, please add a menu to select a CPU model (to simulate a specific speed) in DOSBox-X. I'll like this.

**Describe alternatives you've considered**
This should give DOSBox-X better options.

**Additional context**
The menu should contain separate CPU types, which should be like this:

8086 - 7/8/9/10/12/16Mhz
8088 - 4/7/8/10/12/16Mhz
80286 - 6/8/10/12/16/20/25Mhz
80386 - SX/DX 16/20/25/33/40Mhz
80486 - SX/DX 16/20/25/33/40/50/66Mhz
Pentium - 60/75/90/100/120/133/150/166/200Mhz
Pentium MMX - 166/200/233Mhz

**Comment by Wengier** [comment]
@DSN9990 In the current "CPU" menu, select "CPU type", and you will find a list of CPU options from 8086 to Pentium Pro. Please let me know if it is still missing something.

**Comment by DSN9990** [comment]
@Wengier I asked you if you can add options to select a specific CPU speed, like PCem have.

**Comment by rderooy** [comment]
Emulating a specific speed CPU is not straight forward. DOSBox, and
DOSBox-X by extension is NOT cycle accurate.

DOSBox will run one x86 instruction per-cycle, so if you set 1000 cycles,
it will run 1000 instructions per second. But actual legacy CPUs, depending
on the instruction, and the CPU model, may take several cycles to execute a
instruction.

The best you can do, is to try to approximate it. Especially programs using
x87 (floating point unit) are affected by this.

Have a look at the dosbox wiki for more information:
https://www.dosbox.com/wiki/Performance

**Comment by aybe** [comment]
FWIW in D-Fend Reloaded:

![2020-09-13_23-23-06](https://user-images.githubusercontent.com/1537591/93028988-1dede780-f618-11ea-9ce0-f92eca19fc22.png)

- normal/auto
- dynamic/45000
- auto/500
- auto/10000
- auto/3000

IMO it could be nice to have a few presets that approximates families of CPUs.

**Comment by maximus105** [comment]
I made approximate cycles values by analogy with the Norton Utilities System Information and NSSI (Navrаtil Software System Information) performance index:

**8088 XT 4.77MHz (cycles=240).** The value was chosen as accurately as possible, according to the sound of the music in the game Arkanoid on a real machine 8088 XT 4.77MHz: https://youtu.be/_7mouV05qy0
![sysinfo_XT_Mono (240)](https://user-images.githubusercontent.com/58270614/93107550-6b229580-f6ba-11ea-943c-e672eab61d8a.png)

**286-8MHz (cycles=750)**
![sysinfo_286-8 (750)](https://user-images.githubusercontent.com/58270614/93107624-855c7380-f6ba-11ea-827a-8d148e8dff0e.png)

**286-12MHz (cycles=1510)**
![sysinfo_286-12 (1510)](https://user-images.githubusercontent.com/58270614/93107936-e5ebb080-f6ba-11ea-880c-04fd8d1669c1.png)

**386DX-33MHz (cycles=6075)**
![sysinfo_386DX-33 (6075)](https://user-images.githubusercontent.com/58270614/93108037-04ea4280-f6bb-11ea-9936-0e6ea3e37c6e.png)

**486DX-33MHz (cycles=12010)**
![sysinfo_486DX-33 (12010)](https://user-images.githubusercontent.com/58270614/93108099-15022200-f6bb-11ea-870c-23668a4c8527.png)

**486DX2-66MHz (cycles=23880)**
![sysinfo_486DX2-66 (23880)](https://user-images.githubusercontent.com/58270614/93108159-28ad8880-f6bb-11ea-93f3-249249493c1e.png)

**Pentium-66MHz (cycles=35618)**
![sysinfo_Pentium-66 (35618)](https://user-images.githubusercontent.com/58270614/93108244-3e22b280-f6bb-11ea-8f24-8e5847cd4ad6.png)

**Pentium-100MHz (cycles=60000)**
![sysinfo_Pentium-100 (60000)](https://user-images.githubusercontent.com/58270614/93108288-4bd83800-f6bb-11ea-8ae7-a780ad10a087.png)
![nssi_Pentium-100 (60000)](https://user-images.githubusercontent.com/58270614/93108299-4ed32880-f6bb-11ea-9442-67a475e8e981.png)

**Comment by aybe** [comment]
@maximus105 amazing, you just need to add the core you've used and it'll be perfect !

**Comment by maximus105** [comment]
I added to the description the core and cputype.

**Comment by brunocastello** [comment]
> I added to the description the core and cputype.

Can you explain how you measured the cycles? Trial and error?

**Comment by maximus105** [comment]
@brunocastello Yes.

**Comment by Wengier** [comment]
@maximus105 Great work! I will try to add menu options based on the data you provided. Please check if there are errors in the data before it is added. If you (or anyone else) want to add more to the list it is very welcomed of course.

8088 XT 4.77MHz: cycles=240

286-8MHz: cycles=750

286-12MHz: cycles=1510

386DX-33MHz: cycles=6075

486DX-33MHz: cycles=12010

486DX2-66MHz: cycles=23880

Pentium-66MHz: cycles=35618

Pentium-100MHz: cycles=60000

**Comment by brunocastello** [comment]
Given that MMX apparently doesn't work well (at least for me), how about adding the popular Pentium 133MHz? I'm sure I had that model straight after the 486DX2 decades ago.

**Comment by DSN9990** [comment]
@Wengier Thanks.

**Comment by Wengier** [comment]
I have already added "Emulate CPU speed" menu group (under "CPU") to emulate the speed of these CPU classes in the latest code. Thanks for the data provided by @maximus105. If @maximus105 (or anyone else) wants to add more CPU classes to the list, please free feel to do so.

**Comment by brunocastello** [comment]
I thought that the emulated CPU speed largely depends of how powerful your host computer is?

**Comment by maximus105** [comment]
I performed the selection of cycles on the i9-9900K processor. I added cycles for Pentium-120 MHz, Pentium-133 MHz, Pentium MMX-166 MHz to the description. A further increase in cycles (above the value of 97240) does not lead to an increase in performance, but even to a slowdown in programs (Volkov Commander), and hangs of Norton Utilities System Information and NSSI (Navrаtil Software System Information). I also added cycles to the description for the highest possible performance, roughly corresponding to AMD-K6-2-400 (cycles = max, core = dynamic, cputpe = pentium_mmx).

**Comment by Wengier** [comment]
I have already added the emulation options for Pentium-120 MHz, 133 MHz, and 166 MHz in the latest code. The emulation speed provided should be considered accurate overall, as I have checked with NSSI on my own computer and found that the speeds largely match here too (maybe around 5% difference sometimes). Since minor adjustments may be desired in some cases, I have added a new config option "cycle emulation percentage adjust" in [cpu] section for users who wish to make relative percentage adjustments (between -25% and 25%) of the emulated CPU cycles.

**Comment by DSN9990** [comment]
Could you give me a updated build?

**Comment by Wengier** [comment]
Sure! Here it is the updated Windows binary package:

[dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

Note: FluidSynth support is fully enabled in this build. The sound font GeneralUser_GS.sf2 is bundled and enabled by default. Furthermore, the DOSMID program now appears on the Z drive to play MIDI audios.

**Comment by DSN9990** [comment]
Can you give me a link to NSSI?

**Comment by Wengier** [comment]
@DSN9990 Here: https://www.navsoft.cz/nssi060.exe

**Comment by maximus105** [comment]
I checked the DOSBox-X 0.83.6 build posted above here. With my mapper configured in cga_mono or svga_s3 mode, when starting DOSBox-X, the image gets corrupted:
[Config.zip](https://github.com/joncampbell123/dosbox-x/files/5251587/Config.zip)
![command_002](https://user-images.githubusercontent.com/58270614/93709851-79edca00-fb4a-11ea-81ef-782f539917fb.png)
![command_003](https://user-images.githubusercontent.com/58270614/93710122-d2be6200-fb4c-11ea-90c8-a6d2ff112f47.png)
In addition, the Volkov Commander file manager is launched in my .conf file, and if I do "Reset Virtual Machine" or "Reboot Gues System", an error window will appear and DOSBox-X will close:
![2020-09-20_135916](https://user-images.githubusercontent.com/58270614/93709929-2def5500-fb4b-11ea-8d07-d270cfab7b54.png)
In addition, if you do "Reset Virtual Machine", then an error window appears randomly and DOSBox-X will close:
![2020-09-20_140256](https://user-images.githubusercontent.com/58270614/93709959-77d83b00-fb4b-11ea-95b8-36c1b4daf2fd.png)
In addition, cycles values ​​over 60000 slow down overall performance. Programs start to slow down noticeably. The previous build DOSBox-X 0.83.5 did not have the above problems.

**Comment by Wengier** [comment]
@maximus105 Please check out the following Windows binary:

[dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

The banner image issue only happened with your modified key setting (not default configuration), which was fixed. Also, the issue with rebooting the system only occurred with the setting "keyb ru" as we discussed in Issue #1732. It seems that the fix mentioned that did not work when the Volkov Commander file manager is currently running, so I have modified the fix in the updated build.

However, I am not able to notice that cycles values ​​over 60000 slow down overall performance. For example, when I select Pentium 120/133/166 CPUs (all >60000 cycles) to emulate, the benchmarks do increase as expected.

**Comment by rderooy** [comment]
You may run into issues, if your host system is not able to sustain the number of cycles chosen. Remember that DOSBox is for the most part single-threaded, so CPU clock rating is more important than core count.

**Comment by maximus105** [comment]
@Wengier In the new build, the above issues are gone, apart from the performance drop over cycles > 60000. This is especially noticeable with cycles = 97240. The performance indices themselves, in the form of numbers or bars, have not changed. And the performance has decreased in the form:
1. In Volkov Commander, the cursor in the panels began to move up/down noticeably slower.
2. In Norton Utilities System Information, windows maximize noticeably more slowly.
3. In NSSI, windows unfold noticeably slower and PC Speaker stutters several times at startup.
Maybe this is due to the fact that I tested DOSBox-X 0.83.5 x64 SDL1, and the new DOSBox-X build 0.83.6 x86 SDL1?

**Comment by Wengier** [comment]
@maximus105 I think the DOSBox-X 0.83.5 build you tested was MinGW x64 SDL1 build. Why you try the Visual Studio x86 SDL1 build and see how it works (compared to DOSBox-X 0.83.6 Visual Studio x86 SDL1 build). All 0.83.5 Windows builds are included in the Windows installer.

**Comment by maximus105** [comment]
@Wengier I tested DOSBox-X 0.83.5 Visual Studio x86 SDL1 and x64 SDL1. Yes, they both slow down at cycles = 97240. It turns out that I would rather use MinGW x64 SDL1, since it does not slow down ?

**Comment by maximus105** [comment]
@Wengier Please correct the cycles value for Pentium 66 MHz to 35620. I have found a more accurate cycle value.

**Comment by Wengier** [comment]
@maximus105 Done in the latest code.

**Comment by maximus105** [comment]
@Wengier Yes, and don't forget to correct the description in the menu "(~ 35618 cycles)" to "(~ 35620 cycles)".

**Comment by Wengier** [comment]
@maximum105 The description has been updated accordingly as well.

**Comment by Wengier** [comment]
@maximus105 The description has been updated accordingly. A MinGW 64-bit SDL1 Windows binary I built is available from:

Download link: [dosbox-x-mingw64.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-mingw64.zip?raw=true)

**Comment by DSN9990** [comment]
Can you update the file dosbox-x-update.zip to MinGW 32Bit SDL1?

**Comment by Wengier** [comment]
@DSN9990 You want the Visual Studio build or the MinGW build?

**Comment by Wengier** [comment]
@DSN9990 If you want the Visual Studio build, the dosbox-x-update.zip file is already updated.

**Comment by DSN9990** [comment]
MinGW.

**Comment by Wengier** [comment]
@DSN9990 Use the dosbox-x-mingw64.zip file for the MinGW build (and dosbox-x-update.zip for the Visual Studio build). Both files will be maintained from now on and updated sometimes (regularly or on request).

**Comment by DSN9990** [comment]
@Wengier I want the MinGW 32 build

**Comment by Wengier** [comment]
@DSN9990 I don’t have 32-bit MinGW so I cannot build MinGW 32-bit build myself. Wait for the next official release if you want that.

**Comment by DSN9990** [comment]
@Wengier The VisualStudio build is 32Bit? I want that?

**Comment by Wengier** [comment]
@DSN9990 Visual Studio 2019 can build both 32-bit and 64-bit binaries easily from a single solution, which is not the case for MinGW 64-bit. I think I tried 32-bit MinGW a few months ago but it did not work for some reason, so I uninstalled it and never tried it again.

**Comment by DSN9990** [comment]
@Wengier Can you give me the 64Bit VisualStudio build?

**Comment by Wengier** [comment]
@DSN9990 I will do that tomorrow (I had already left my main computer).

**Comment by DSN9990** [comment]
@Wengier Thanks. I'll wait.

**Comment by maximus105** [comment]
In the new MinGW x64 SDL1 build, the aspect = true option does not work with fullscreen = true. And there is no direct3d in the output option. Or is it the way it should be?

**Comment by Wengier** [comment]
@DSN9990 A 64-bit Visual Studio SDL1 build is available from:

[dosbox-x-64-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-64-update.zip?raw=true)

**Comment by Wengier** [comment]
@maximus105 The MinGW build was built by me just for testing, and it does not come with things like Direct3D support. As for glshaders, at this time you can get them from:

https://github.com/tyrells/dosbox-svn-shaders

**Comment by Wengier** [comment]
@maximus105 You can now find GLSL shaders in the contrib/glshaders directory of this source tree:

https://github.com/joncampbell123/dosbox-x/tree/master/contrib/glshaders

The Windows installer will copy them to the glshaders subdirectory of the DOSBox-X install directory as well.

**Comment by DSN9990** [comment]
@Wengier Can you add options for Pentium 60, 75 and 90mhz?

**Comment by Wengier** [comment]
@DSN9990 Yes if you (or anyone else) can provide the data for them.

**Comment by rderooy** [comment]
Just a comment. Don't you think that when people select a CPU this way,
that they also expect the emulated CPU to be set to match?

The problem with that obviously is that it will require a reset of the
emulation.

**Comment by Wengier** [comment]
@rderooy Yes, I had thought of that too, but requiring a reset the emulation will be a big impact. So the menu is named "emulate CPU speed" and placed in the cycles subsection to make it clearer that it is just for emulating the speed in terms of CPU cycles, not something like "select CPU subtype" near "CPU type".

**Comment by DSN9990** [comment]
@maximus105 Can you provide data for Pentium 60Mhz (not 66Mhz), Pentium 75Mhz and Pentium 90Mhz?

**Comment by joncampbell123** [comment]
There is certainly a positive response to this feature!
![Firefox_Screenshot_2020-10-04T05-01-28 579Z](https://user-images.githubusercontent.com/6245486/95007396-307a9180-05c4-11eb-8eb8-18335c7c9f18.png)

**Comment by Wengier** [comment]
@joncampbell123 I am certainly very happy to hear that. You have definitely done great work in maintaining the project and I hope more people will like it.

**Comment by Wengier** [comment]
@maximus105 You had made very helpful efforts to provide the data for the CPUs. Please feel free to add more so that users can benefit more from this feature.

**Comment by maximus105** [comment]
I added cycles for 486DX4-100, 486DX5-133, Pentium-75, Pentium-90 to the description. Please correct my nickname in the changelog (In the word "maximum", you need to correct the last letter "m" for "s").

**Comment by Wengier** [comment]
@maximus105 Thanks for adding the cycles for these CPU types to the description. I have already added them to the latest code. Also sorry for the typo of your nickname, and I think I have already corrected it in CHANGELOG.

**Comment by Wengier** [comment]
@maximus105 I have corrected your nickname in the Releases page as well. If you have data for other CPU models, please feel free to add them as well. Thanks!

**Comment by maximus105** [comment]
I added cycles for 286-25, 386DX-25, Pentium-60 to the description. Can you add a hotkey to the menu for "Edit cycles"?

![1](https://user-images.githubusercontent.com/58270614/97080367-6202dd80-1603-11eb-958d-b26d59cb76f4.png)

**Comment by Wengier** [comment]
@maximus105 Thanks! I have already added them to the latest code (https://github.com/joncampbell123/dosbox-x/commit/807221bf6efe1e2345d15a31ec5aaeafe8bd2e3b).

Meanwhile, the "Edit cycles" function is already in the mapper editor, named "EditCycles". You can certainly add a hotkey for it yourself.

**Comment by maximus105** [comment]
@Wengier Is it possible to make the "Show details" option persist (turn on) after closing and then starting DOSBox-X ?

![1](https://user-images.githubusercontent.com/58270614/97092894-4d006b80-1650-11eb-8b40-434747b6e70f.jpg)

**Comment by Wengier** [comment]
@maximus105 The "show details" menu option is equivalent to the -showcycles and -showrt command-line options combined. So you can just run DOSBox-X with these command-line options.

**Comment by maximus105** [comment]
@Wengier Thanks!
