### ISSUE TITLE
Which is the one that's Npcap?

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#1855]
When setting up networking, I have to replace "realnic=list" with one of these:

LOG: 1. rpcap://\Device\NPF_{64838B0A-838D-4C53-80F1-8FDA9CF1856F}
(Network adapter 'Microsoft' on local host)
LOG: 2. rpcap://\Device\NPF_{5473511F-D8F5-480D-9A9C-120DCC3743BB}
(Network adapter 'Microsoft' on local host)
LOG: 3. rpcap://\Device\NPF_{7AA66DB6-31F6-4F74-B48E-BA253D3B10EE}
(Network adapter 'NdisWan Adapter' on local host)
LOG: 4. rpcap://\Device\NPF_{4C79354F-A1B1-4DE7-B018-F59BE5AB19CF}
(Network adapter 'NdisWan Adapter' on local host)
LOG: 5. rpcap://\Device\NPF_{718E69B8-0F93-4604-A1EB-3CB75F7E3C2A}
(Network adapter 'Oracle' on local host)
LOG: 6. rpcap://\Device\NPF_{FC3AF806-EE2B-4695-B4AE-88A8246CC2C4}
(Network adapter 'rpcap://\Device\NPF_{FC3AF806-EE2B-4695-B4AE-88A8246CC2C4}' on local host)
LOG: 7. rpcap://\Device\NPF_{B7222EB6-9426-4613-BFA9-C64D6419EF28}
(Network adapter 'NdisWan Adapter' on local host)
LOG: 8. rpcap://\Device\NPF_{E46495F0-4B37-400E-B63C-435E4082A370}
(Network adapter 'Microsoft' on local host)
LOG: 9. rpcap://\Device\NPF_{54E39370-3753-41FC-A213-7BF5CA0D8538}
(Network adapter 'Microsoft' on local host)
LOG: 10. rpcap://\Device\NPF_Loopback
(Network adapter 'Adapter for loopback traffic capture' on local host)
LOG: 11. rpcap://\Device\NPF_{C80D45B2-1875-486A-BE10-DF81622212AF}
(Network adapter 'TAP-NordVPN Windows Adapter V9' on local host)
LOG: 12. rpcap://\Device\NPF_{5F06FACD-F7F5-4D7D-B95D-4439C5A0D8F7}
(Network adapter 'Intel(R) Ethernet Connection I217-LM' on local host)

Which one should I choose!?

**Comment by rderooy** [comment]
My guess... the last one. number 12 looks the most promising.

**Comment by jadasse** [comment]
thanks

**Comment by jadasse** [comment]
I'm reopening it again just in case

**Comment by jadasse** [comment]
Are these the recommended settings? Or do I have to change them?

![Screenshot 2020-09-14 170754](https://user-images.githubusercontent.com/71288109/93138416-f7c65700-f6ac-11ea-902b-6df3e74eaf4f.png)

**Comment by rderooy** [comment]
If your following the wiki and are using the windows template config, then
no. You should set it to Irq 10 as indicated on the wiki.

**Comment by jadasse** [comment]
tbh https://github.com/joncampbell123/dosbox-x/wiki/Guide%3AInstalling-Windows-98 this is what I'm using so thanks ;)

**Comment by jadasse** [comment]
I don't think it's working

**Comment by jadasse** [comment]
Sorry I'm a month late

**Comment by rderooy** [comment]
Did you check https://github.com/joncampbell123/dosbox-x/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X#setup-guide-for-windows-hosts

**Comment by jadasse** [comment]
I did install npcap, and made ne2000.conf. The problem is, in the log options, I'm having trouble finding which one to use! I think imma try mTCP instead

**Comment by jadasse** [comment]
Although I chose 12, the network still won't connect. I tried reinstalling npacp, but it still won't work.

**Comment by jadasse** [comment]
LOG:  1. rpcap://\Device\NPF_{64838B0A-838D-4C53-80F1-8FDA9CF1856F}
    (Network adapter 'Microsoft' on local host)
LOG:  2. rpcap://\Device\NPF_{5473511F-D8F5-480D-9A9C-120DCC3743BB}
    (Network adapter 'Microsoft' on local host)
LOG:  3. rpcap://\Device\NPF_{7AA66DB6-31F6-4F74-B48E-BA253D3B10EE}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  4. rpcap://\Device\NPF_{4C79354F-A1B1-4DE7-B018-F59BE5AB19CF}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  5. rpcap://\Device\NPF_{718E69B8-0F93-4604-A1EB-3CB75F7E3C2A}
    (Network adapter 'Oracle' on local host)
LOG:  6. rpcap://\Device\NPF_{78567E31-39F6-4785-A276-79C496276FB9}
    (Network adapter 'rpcap://\Device\NPF_{78567E31-39F6-4785-A276-79C496276FB9}' on local host)
LOG:  7. rpcap://\Device\NPF_{B7222EB6-9426-4613-BFA9-C64D6419EF28}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  8. rpcap://\Device\NPF_{E46495F0-4B37-400E-B63C-435E4082A370}
    (Network adapter 'Microsoft' on local host)
LOG:  9. rpcap://\Device\NPF_{54E39370-3753-41FC-A213-7BF5CA0D8538}
    (Network adapter 'Microsoft' on local host)
LOG: 10. rpcap://\Device\NPF_Loopback
    (Network adapter 'Adapter for loopback traffic capture' on local host)
LOG: 11. rpcap://\Device\NPF_{C80D45B2-1875-486A-BE10-DF81622212AF}
    (Network adapter 'TAP-NordVPN Windows Adapter V9' on local host)
LOG: 12. rpcap://\Device\NPF_{5F06FACD-F7F5-4D7D-B95D-4439C5A0D8F7}
    (Network adapter 'Intel(R) Ethernet Connection I217-LM' on local host)

**Comment by rderooy** [comment]
@jadasse How is the system connected to the internet? Is it via Ethernet or Wifi? Do you have a VPN active?

The functionality that DOSBox-X needs from npcap, called "promiscuous mode" normally only works with Ethernet adapters. It will not work with most other types of connectivity. In addition, some types of firewall or vpn software *may* cause problems.

On a vanilla Windows 10 without any additional 3rd party firewall, antivirus or VPN software here, it works with Intel Ethernet.

Interface 12 appears to be a Intel Ethernet adapter, which should normally work.

**Comment by jadasse** [comment]
I wish it was by Ethernet tbh, but no, it's by WiFi. I have no VPN active.

**Comment by jadasse** [comment]
I'm going to get ethernet soon btw but I don't know when

**Comment by jadasse** [comment]
I also found the npcap loopback adapter, but I think it's supposed to be for ethernet

**Comment by rderooy** [comment]
As mentioned on the wiki, it will not work with WIFI as it almost always lacks support for the necessary **promiscuous mode** that we need.

Loopback **may** work (I did not test it), as long as your communicating between two DOSBox-X instances running on the **SAME** PC (or possibly between a DOSBox-X instance and the host PC itself, as long as your using the TCP/IP protocol on both sides). And if your trying to communicate over TCP/IP, you will need to statically define the IP addressing as there will not be a DHCP server listening on the loopback device.

If your limited to WIFI, this may be of interest: https://github.com/joncampbell123/dosbox-x/pull/1863 once it is finished and merged.

**Comment by jadasse** [comment]
The ethernet adapter is coming today btw

**Comment by jadasse** [comment]
Good news! I got myself ethernet access!

**Comment by jadasse** [comment]
Hello?

**Comment by Wengier** [comment]
@jadasse Yes, it is certainly great to hear the news. Thanks for letting us know.

**Comment by jadasse** [comment]
Unfortunately I can't do something today, I'm in Pennsylvania, I return home tomorrow

**Comment by jadasse** [comment]
I forgot to inform; I returned on Sunday

**Comment by jadasse** [comment]
I do not see the network list in the log messages since I got the ethernet access.

**Comment by rderooy** [comment]
You will only see the network list in the LOG if...
- you set realnic=list
- your using a binary with PCAP support compiled in
- (not sure) if it finds that a PCAP implementation like npcap is present

**Comment by jadasse** [comment]
LOG:  1. rpcap://\Device\NPF_{64838B0A-838D-4C53-80F1-8FDA9CF1856F}
    (Network adapter 'Microsoft' on local host)
LOG:  2. rpcap://\Device\NPF_{5473511F-D8F5-480D-9A9C-120DCC3743BB}
    (Network adapter 'Microsoft' on local host)
LOG:  3. rpcap://\Device\NPF_{7AA66DB6-31F6-4F74-B48E-BA253D3B10EE}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  4. rpcap://\Device\NPF_{4C79354F-A1B1-4DE7-B018-F59BE5AB19CF}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  5. rpcap://\Device\NPF_{718E69B8-0F93-4604-A1EB-3CB75F7E3C2A}
    (Network adapter 'Oracle' on local host)
LOG:  6. rpcap://\Device\NPF_{5F06FACD-F7F5-4D7D-B95D-4439C5A0D8F7}
    (Network adapter 'Intel(R) Ethernet Connection I217-LM' on local host)
LOG:  7. rpcap://\Device\NPF_{7FE104C9-D81D-45E3-BBF3-3D9037208BB8}
    (Network adapter 'rpcap://\Device\NPF_{7FE104C9-D81D-45E3-BBF3-3D9037208BB8}' on local host)
LOG:  8. rpcap://\Device\NPF_{B7222EB6-9426-4613-BFA9-C64D6419EF28}
    (Network adapter 'NdisWan Adapter' on local host)
LOG:  9. rpcap://\Device\NPF_{E46495F0-4B37-400E-B63C-435E4082A370}
    (Network adapter 'Microsoft' on local host)
LOG: 10. rpcap://\Device\NPF_{54E39370-3753-41FC-A213-7BF5CA0D8538}
    (Network adapter 'Microsoft' on local host)
LOG: 11. rpcap://\Device\NPF_Loopback
    (Network adapter 'Adapter for loopback traffic capture' on local host)
LOG: 12. rpcap://\Device\NPF_{C80D45B2-1875-486A-BE10-DF81622212AF}
    (Network adapter 'TAP-NordVPN Windows Adapter V9' on local host)

Which one should I use?

**Comment by rderooy** [comment]
Just like before the Ethernet adapter. However, it is now listed as entry 6, so using the device number is not reliable. Use the device name instead of the device number as mentioned on the network wiki page.

**Comment by jadasse** [comment]
thanks, I tried it with the mtcp and it worked, so now I can FINALLY close this issue, goodbye and thanks :)
