### ISSUE TITLE
Are these the recommended settings? Or do I have to change these? I’m following the Windows 98 installation guide btw

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#1856]
![image](https://user-images.githubusercontent.com/71288109/93142369-dcab1580-f6b3-11ea-8380-c546d90f35ce.png)

**Comment by joncampbell123** [comment]
Windows can mis-detect the IRQ, make sure it matches what you entered in your dosbox-x.conf.

Checking src/dosbox.cpp the default appears to be 3.

**Comment by jadasse** [comment]
Btw https://github.com/joncampbell123/dosbox-x/wiki/Guide%3AInstalling-Windows-98 this is the guide I'm using

**Comment by rderooy** [comment]
True. But windows does not like Irq 3 because it conflicts with COM2.

So you need to either change the Irq for the ne2000 or disable COM2.

The guide opts to change the Irq of the ne2000.

**Comment by jadasse** [comment]
Got it now, thanks guys

**Comment by jadasse** [comment]
I'll just use IRQ 10, like rderooy said, I'll come back to this to break the news

**Comment by jadasse** [comment]
I checked the conf, it WAS 10, thanks, guys! :D
