### ISSUE TITLE
Whenever I try to start up Windows 98, it gives me this error. what should I do?

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#1857]
![Screenshot 2020-09-15 000630](https://user-images.githubusercontent.com/71288109/93164364-56a8c200-f6e7-11ea-989a-320ac6b5432a.png)

**Comment by rderooy** [comment]
It seems that some files are missing from your hdd image, in particular command.com

After the imgmount command, but before the boot command you should be able to access the filesystem and have a look around. But unless you know your stuff, it may be easier to just re-install Win98.

**Comment by jadasse** [comment]
crap :(
