### ISSUE TITLE
When I try to enter IMGMAKE hdd.img -size 16384 it keeps giving me the information about the program instead of creating the img file. What should I do?

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#1862]
![Screenshot 2020-09-16 220103](https://user-images.githubusercontent.com/71288109/93411117-67cd0c80-f868-11ea-9ca6-46bfe75dfa2b.png)

**Comment by Wengier** [comment]
It should be:

```
IMGMAKE hdd.img -size 16384 -t hd
```

See Issue #1165 .

It was already fixed in the draft Wiki, and I have now decided to fix it in the main Wiki as well instead of doing it when the next release comes.

**Comment by jadasse** [comment]
thanks
