### ISSUE TITLE
Parenthesis keys don't type anything

### ISSUE THREAD

**Issue by Jookia** [joncampbell123/dosbox-x#1864]
**Describe the bug**
DOSBox doesn't seem to pass the parenthesis keys (shift 9 and shift 0) to DOS. The key mapper can detect when I press the combination so DOSBox is getting the key press, it just isn't sending it to DOS.

**To Reproduce**
1. Open DOSBox
2. Press shift 9
3. See no characters typed

**Expected behavior**
1. Open DOSBox
2. Press shift 9
3. See the left parenthesis "(" appear on the screen

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Operating system: Debian 10
 - DOSBox-X release version or commit SHA1 this issue occurred on: 116196c7063fa59673e71c4c68b51f0907954e96
 - Used configuration, e.g. ```dosbox-x.conf```: no configuration

**Additional context**
I also have this problem in qemu too?

**Comment by rderooy** [comment]
Hmm, it is working fine here.

- Are you using a SDL1 or SDL2 build?
- What is your host keyboard layout set to
- Are you setting any keyboard layout option in your dosbox-x config or via the keyb command?

**Comment by Jookia** [comment]
On Thu, Sep 17, 2020 at 03:13:56AM -0700, Robert wrote:
> Hmm, it is working fine here.
> 
> - Are you using a SDL1 or SDL2 build?

I used both SDL1 and SDL2

> - What is your host keyboard layout set to

US I think? How do I check?

> - Are you setting any keyboard layout option in your dosbox-x config or via the keyb command?

No.

**Comment by Jookia** [comment]
Okay, my bad on this. This was because I didn't add '-xkb -skip_keycodes 187,188' to x11vnc, see: https://www.virtualbox.org/ticket/4772
