### ISSUE TITLE
Localizing the DOSBox-X shell

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#1866]
## Describe the solution you'd like

Having a localized DOSBox-X would be nice.

I tried something and was surprised on how easy it was to get started translating simple things.

## Additional context

Example branch:

https://github.com/joncampbell123/dosbox-x/tree/translation

### `time`, still has US format and incorrect code page not showing accents:

![chrome_2020-09-18_04-46-57](https://user-images.githubusercontent.com/1537591/93549607-ff665400-f969-11ea-8ac0-e6c5b0a07c0e.png)

### `del`, same as above and should answer keys be translated or not:

![chrome_2020-09-18_04-47-18](https://user-images.githubusercontent.com/1537591/93549652-10af6080-f96a-11ea-8725-ee5e5a577195.png)

### easy translation using `gettext` and `poedit`:

![chrome_2020-09-18_04-53-37](https://user-images.githubusercontent.com/1537591/93550074-ef9b3f80-f96a-11ea-8007-90760708a129.png)

(poedit has a free limited edition available on all platforms)

Usage:
 - annotate all strings in code, I used `Tr("translate me")` for the example
 - in poedit, create a project for a translation in another language
  - set directories with code to analyze
  - set keywords to look for, e.g. `Tr`
  - analyze sources and translate the extracted strings through a friendly GUI

Finally, copy generated `.mo` files next to executable and start DOSBox-X with `LANG` environment variable set.

### Issues found so far

- everything should be translated, e.g. date and number formats, etc
- the code page should be inferred from environnement variable, e.g. `LANG=fr_FR`
- how `MSG_Add`, `ANSI` and `const char *` elements are going to be translated easily ?
  - these will have to be reworked somehow to accomodate for dynamic string lengths
- some strings will have to be rewritten differently according gettext docs
- how do an update to translation files accomodate large changes in code ?

### Summary

It is possible to get DOSBox-X shell translated with a relatively minimal impact on source.

Most of it will be easy but tedious, with some more challenging parts.

The big question is, how nice/useful a localized DOSBox-X really is ?

### References

https://www.gnu.org/software/gettext/manual/html_node/
https://poedit.net/

**Comment by Wengier** [comment]
@aybe A question: why not use the language file approach? I mean, is there any issue with the language file approach (using -lang command-line option)? You can also set date and time formats using the COUNTRY command. See this Wiki page for more details:

https://github.com/joncampbell123/dosbox-x/wiki/Guide%3ARegional-settings-in-DOSBox%E2%80%90X

**Comment by aybe** [comment]
Well, I just learned something new thanks to you !

I am going to read the wiki so that in the future I don't make any suggestions for which there's already a solution for !

**Comment by aybe** [comment]
Okay, i've tried to translate message.txt and these are the problems I've encountered:

- impossible A/B comparison which is really problematic, you have to overwrite the text
- what is one supposed to do when it comes to adjusting a previous translation ?
  - open original message.txt and compare differences in git style ?
    - problem is, they are very far from each other making it difficult to follow
    - it's hard to tell how much it is overflowing compared to original
- overflowing, should last column be honored which then implies a new line or what ?
- encoding, messages.txt is ANSI and when I reopened it I lost all accents, only UTF-8 worked
- impossible to mark a message as TODO, some are ambiguous and can't be translated, e.g. `DOSBox-X %s configuration directory`
- etc, I've stopped at this point

So as you can see, the combo gettext and poedit do handle these remarkably well, I clearly see the difference.

I guess you'll agree that it's not the best environment there is:

![devenv_2020-09-19_02-48-06](https://user-images.githubusercontent.com/1537591/93655232-92fb5b80-fa22-11ea-84d7-ed4f61c03a8e.png)

Notepad++ is a bit better since you can add few plugins but still suboptimal:

![notepad++_2020-09-19_02-50-25](https://user-images.githubusercontent.com/1537591/93655322-f1283e80-fa22-11ea-97fe-6f237ca3314a.png)

See poedit for a difference:

![Poedit_2020-09-19_02-52-38](https://user-images.githubusercontent.com/1537591/93655375-39dff780-fa23-11ea-9e6f-904e757219e8.png)

What do you think ? 😀

**Comment by aybe** [comment]
Also, slightly (un-)related but, every single source file always has tabs mixed with spaces which is really confusing and should be addressed, i.e. use `\t` when you want to signify <kbd>Tab</kbd>.

**Comment by aybe** [comment]
@Wengier 

Some rather good news, gettext and poedit are able to match a specific syntax, which means that enclosing all strings is not necessary.

Also you can preview source code etc:

![2020-09-19_05-00-34](https://user-images.githubusercontent.com/1537591/93657720-23429c00-fa35-11ea-88aa-ed2971564657.png)

Now there are errors but not as much as you'd think:

```
9/19/2020 4:56:42 AM: shell/shell.cpp:1084: warning: Empty msgid.  It is reserved by GNU gettext:
	gettext("") returns the header entry with
	meta information, not the empty string.
9/19/2020 4:56:42 AM: shell/shell.cpp:1118: warning: Empty msgid.  It is reserved by GNU gettext:
	gettext("") returns the header entry with
	meta information, not the empty string.
9/19/2020 4:56:42 AM: dos/dos_programs.cpp:6351: invalid multibyte sequence
9/19/2020 4:56:42 AM: dos/dos_programs.cpp:6358: invalid multibyte sequence
9/19/2020 4:56:42 AM: dos/dos_programs.cpp:6448: invalid multibyte sequence
9/19/2020 4:56:42 AM: dos/dos_programs.cpp:6465: invalid multibyte sequence
9/19/2020 4:56:42 AM: dos/dos_programs.cpp:6490: invalid multibyte sequence
9/19/2020 4:56:42 AM: dos/dos_programs.cpp:6501: invalid multibyte sequence
9/19/2020 4:56:42 AM: dos/dos_programs.cpp:6721: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1054: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1070: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1074: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1078: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1086: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1099: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1121: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1127: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1132: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1134: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1144: invalid multibyte sequence
9/19/2020 4:56:42 AM: shell/shell.cpp:1150: invalid multibyte sequence
```
I removed duplicates, they just occur right after these, so as you can see, less than 30 errors occurred.

IMO this is a game changer as basically you'd translate using a standard approach and could ditch messages.txt entirely.

**Comment by Wengier** [comment]
@aybe The language file format used by DOSBox-X is the same format as used by original DOSBox, although of course with a number of additional messages. So when making new translations for DOSBox-X perhaps you can use existing language files for DOSBox for messages that were already translated.

Also, since it is already a standardized format used by DOSBox and its forks for many years, I think perhaps the best solution is for poedit to support the DOSBox language file format, then it will become even easier than the gettext+poedit approach as the latter is kind of hack (instead of the official way supported by the software itself).

**Comment by aybe** [comment]
Alright, understood.

**Comment by rderooy** [comment]
There are some existing translations for DOSBox that you can use as a base.
https://www.dosbox.com/download.php?main=1

**Comment by aybe** [comment]
Thanks !
