### ISSUE TITLE
When I try to mount an iso in drive d using imgmount, it doesn't appear in Windows 98, what do I do? I used installation method two by the way, i assume it's a no no :(

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#1869]
![Screenshot 2020-09-20 153619](https://user-images.githubusercontent.com/71288109/93720509-7ca2ec00-fb57-11ea-8bc6-82171f7342d5.png)

**Comment by rderooy** [comment]
Hmm strange. Here it works just fine. What does Win98 device manager look like? In particular the IDE controllers. Also are you using Win98 or 98SE? And did you use a retail or OEM version?

You can also try to specify the CD-ROM to take a particular IDE device.

e.g.
```
imgmount cdrom.iso -ide 2m
```
Which ensures it will be on the 2nd IDE controller as master device.

Another user reported a similar problem that I could not recreate, and he got it working by disabling pnp on the second IDE controller.

**Comment by jadasse** [comment]
If I want to add more drives, would I increase the drive letter alphabetically and the "2m" to "3m" and so on?

**Comment by rderooy** [comment]
Each IDE controller can have 2 devices, called Master and Slave, so you can have a 1m, 1s, 2m, 2s
This only applies in DOSBox-X when booting a OS, if your using the integrated DOS, there is no real need to specify it. Even when booting, it should automatically place the IDE devices in a "typical" setup.

If you need more than 4 devices when booting, you need to activate more IDE controllers in your dosbox-x config file.

**Comment by jadasse** [comment]
Oh ok! Thx
