### ISSUE TITLE
I’m curious [install windows 98 through a directory]

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#1870]
Is it possible to install windows 98 through a directory in my computer instead of an img?

**Comment by Wengier** [comment]
Unfortunately, Windows 98 can not be started from the integrated DOS shell at this time (Issue #1217), so you must install it in to a disk image and boot from it.

**Comment by jadasse** [comment]
Oof

**Comment by Siddhant-Mashalkar** [comment]
> Unfortunately, Windows 98 can not be started from the integrated DOS shell at this time (Issue #1217), so you must install it in to a disk image and boot from it.

What? i was able to run Win98 using WIN.COM instead of boot -l C , it works
