### ISSUE TITLE
Latest code fails to build [on macOS] since yesterday's commits, and only code for build 0.83.5 compiles and works.

### ISSUE THREAD

**Issue by brunocastello** [joncampbell123/dosbox-x#1871]
**Describe the bug**
As oriented by @rderooy, I attempted to build a new binary so I could give input for the error I was getting. Latest code fails to build, stops throwing an error as shown below

**To Reproduce**
Issued a git clone to get the code;
entered the directory and issued a ./build-macosx
build starts, but ends at the following screen attached:

**Expected behavior**
Expected a compiled binary, and if the build were successful I'd issue a make dosbox-x.app. But no dice.

**Screenshots**
Attached
![Screen Shot 2020-09-21 at 1 04 14 AM](https://user-images.githubusercontent.com/23453202/93732135-5fe1d500-fba6-11ea-9a97-3b98efa47d50.png)

**Environment (please complete the following information):**
 - Operating system: macOS Catalina 10.15.6
 - DOSBox-X release version or commit SHA1 this issue occurred on: latest code, latest commit

**Additional context**
Nothing.

**Comment by brunocastello** [comment]
Also, as oriented too, I'll be trying to compile the code prior to previous commits to (who knows if I can) find the offending commit where I get to be unable to compile. I'm starting from the last commit for September 18h, where code was merged from master.

**Comment by brunocastello** [comment]
I finally managed to compile from the code as of this commit of September 13, 2020: https://github.com/joncampbell123/dosbox-x/commit/a10007edcafb7b3e3580cce780e7f900f412146c

And as of the commit https://github.com/joncampbell123/dosbox-x/commit/4e9b6cb22909746adbf5b40776c03f5d627880e5, for September 14, 2020 the code starts to fail to compile, giving the same error as seen on above screenshot.

I tested only the last and first commits of each day, until I was able to compile again. Obviously I wasn't able to try and compile every commit made since September 13, 2020. But apparently the error is on **shell.cpp** file, regarding the banner.

hope this helps.

**Comment by emendelson** [comment]
I can confirm that the current code won't build under Mojave either; same errors.

**Comment by Wengier** [comment]
I have modified the title of this issue to mention that this occurs only occurred in macOS (it did build fine on both Windows and Linux platforms).

I don't have macOS to test myself, but I think I already fixed the building for macOS. Please check out the latest code.

**Comment by brunocastello** [comment]
> I have modified the title of this issue to mention that this occurs only occurred in macOS (it did build fine on both Windows and Linux platforms).
> 
> I don't have macOS to test myself, but I think I already fixed the building for macOS. Please check out the latest code.

I compiled it right now and made a dosbox-x.app, now it works as before, thank you.

Just one more thing: Recent builds I have been getting this message when I do a "make dosbox-x.app" even though the app works flawlessly: 

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: error: 'dosbox-x.app/Contents/MacOS/*.dylib': No such file or directory`

Apparently the app is missing the dylib library files, not sure if this affects the dosbox-x performance on macOS or not. So far the app is working the same way previous successful build does.

**Comment by Wengier** [comment]
@rderooy You may want to check the warning @brunocastello mentioned as I think you recently moved/modified the macOS-related files and Makefile.am which copied the dylib files for macOS.

**Comment by rderooy** [comment]
@Wengier I had another look at it, and I don't see why my changes would cause this.

@brunocastello can you check if this error happens with code from before the 9th of September? That is when my changes where merged to move some of the macos specific files under contrib.

**Comment by brunocastello** [comment]
At this moment I can’t, I just woke up and discovered that we are without power since nine hours ago, and I don’t know when this blackout will end. I will let you know when I can.
