### ISSUE TITLE
[Linux][SDL2] Building process is broken in render.cpp

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#1881]
**Describe the bug**
After AVX2 was added to main code, I cannot get Dosbox-X to be build. Every single time, build process stop while processing render.cpp.

Error log start with:

```
render.cpp:172:67: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
  172 |                 __m256i v = _mm256_loadu_si256((const __m256i*)src);
      |                                                                   ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/immintrin.h:53,
                 from /usr/include/SDL2/SDL_cpuinfo.h:86,
                 from /usr/include/SDL2/SDL.h:38,
                 from ../../include/sdlmain.h:10,
                 from render.cpp:35:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/avx2intrin.h:433:1: error: inlining failed in call to 'always_inline' 'int _mm256_movemask_epi8(__m256i)': target specific option mismatch
```

**To Reproduce**
1. Grab latest git code
2. Use this configure line: ./configure --enable-core-inline --disable-debug --enable-avcodec --prefix=/usr --enable-sdl2
3. Run make and wait.

**Expected behavior**
Build process going on.

**Environment (please complete the following information):**
 - Archlinux
 - commit SHA1: b5310f1c3671bfe1b0226fd75a8703053fa4ecdb

Attaching crash log.
[dosbox-x-crash.log](https://github.com/joncampbell123/dosbox-x/files/5286470/dosbox-x-crash.log)

**Comment by Wengier** [comment]
Pull request #1882 is supposed to fix it. Please check the new code.

**Comment by FredBezies** [comment]
It is fixed. Build process is ok now.
