### ISSUE TITLE
[SDL1] [Linux] broken build in render.cpp due to AVX2 change

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1883]
**Describe the bug**
After @linkmauve 's https://github.com/joncampbell123/dosbox-x/pull/1882 the build works for SDL2, but is still broken on SDL1

```
render.cpp: In function ‘bool cacheHit_AVX2(const Bitu*, Bitu*, Bits)’:
render.cpp:149:9: error: ‘__m256i’ was not declared in this scope
  149 |         __m256i v = _mm256_loadu_si256((const __m256i*)src);
      |         ^~~~~~~
render.cpp:150:16: error: expected ‘;’ before ‘c’
  150 |         __m256i c = _mm256_loadu_si256((const __m256i*)cache);
      |                ^~
      |                ;
render.cpp:151:16: error: expected ‘;’ before ‘cmp’
  151 |         __m256i cmp = _mm256_cmpeq_epi32(v, c);
      |                ^~~~
      |                ;
In file included from ../../include/menu.h:20,
                 from ../../include/sdlmain.h:4,
                 from ../../src/output/output_tools.h:9,
                 from ../../include/sdlmain.h:200,
                 from render.cpp:35:
render.cpp:152:61: error: ‘cmp’ was not declared in this scope; did you mean ‘bcmp’?
  152 |         if (GCC_UNLIKELY((unsigned int)_mm256_movemask_epi8(cmp) != 0xFFFFFFFF))
      |                                                             ^~~
../../config.h:353:43: note: in definition of macro ‘GCC_UNLIKELY’
  353 | #define GCC_UNLIKELY(x) __builtin_expect((x),0)
      |                                           ^
render.cpp:152:40: error: ‘_mm256_movemask_epi8’ was not declared in this scope; did you mean ‘_mm_movemask_epi8’?
  152 |         if (GCC_UNLIKELY((unsigned int)_mm256_movemask_epi8(cmp) != 0xFFFFFFFF))
      |                                        ^~~~~~~~~~~~~~~~~~~~
../../config.h:353:43: note: in definition of macro ‘GCC_UNLIKELY’
  353 | #define GCC_UNLIKELY(x) __builtin_expect((x),0)
      |                                           ^
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
make[3]: *** [Makefile:434: render.o] Error 1
make[3]: *** Waiting for unfinished jobs....
sdlmain.cpp: In function ‘bool help_intro_callback(DOSBoxMenu*, DOSBoxMenu::item*)’:
sdlmain.cpp:8553:45: warning: unused parameter ‘menu’ [-Wunused-parameter]
 8553 | bool help_intro_callback(DOSBoxMenu * const menu, DOSBoxMenu::item * const menuitem) {
      |                          ~~~~~~~~~~~~~~~~~~~^~~~
sdlmain.cpp:8553:76: warning: unused parameter ‘menuitem’ [-Wunused-parameter]
 8553 | bool help_intro_callback(DOSBoxMenu * const menu, DOSBoxMenu::item * const menuitem) {
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
sdlmain.cpp: In function ‘bool help_about_callback(DOSBoxMenu*, DOSBoxMenu::item*)’:
sdlmain.cpp:8567:45: warning: unused parameter ‘menu’ [-Wunused-parameter]
 8567 | bool help_about_callback(DOSBoxMenu * const menu, DOSBoxMenu::item * const menuitem) {
      |                          ~~~~~~~~~~~~~~~~~~~^~~~
sdlmain.cpp:8567:76: warning: unused parameter ‘menuitem’ [-Wunused-parameter]
 8567 | bool help_about_callback(DOSBoxMenu * const menu, DOSBoxMenu::item * const menuitem) {
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
make[3]: Leaving directory '/home/robert/github/dosbox-x/src/gui'
make[2]: *** [Makefile:524: all-recursive] Error 1
make[2]: Leaving directory '/home/robert/github/dosbox-x/src'
make[1]: *** [Makefile:399: all-recursive] Error 1
make[1]: Leaving directory '/home/robert/github/dosbox-x'
make: *** [Makefile:332: all] Error 2
```

**Comment by kcgen** [comment]
@linkmauve,

Assuming one builds with some lower-bound of instruction support (Under GCC, this might be `-march=native`,  `-march=haswell`, -mcpu=armv8`, etc..), modern optimizing compilers will use the fatest patform-specific SIMD calls whenever possible. 

Was this a case where GCC / Clang / VisualStudio wasn't able to make those optimizations?

Were you able to capture micro-benchmarks before and after showing an improvement?

**Comment by linkmauve** [comment]
Yes, as I said in [the original commit](https://github.com/joncampbell123/dosbox-x/commit/76d607070b94989fbf331362e66bd8f54c925543), it gave a substantial speedup to this function according to `perf(1)` (from ~8.3% of the total runtime in SSE2 to ~6.2% in AVX2, and ~13.5% with just -O3 -march=native, all built using g++).

Do you have any framework for micro-benchmarks that I could use to try not to regress?  I couldn’t find any in the codebase.

I also wanted to do a NEON version, but there is something in the build system which prevents automake from generating the needed Makefiles on my Switch…

**Comment by kcgen** [comment]
Sorry for not catching that @linkmauve! 

Wow; forget the need for a micro-benchmark given  such a notable boost could be measured in the total runtime.

(I don't know of a micro-benchmark framework (other than just measuring total function contribution like you've done). 

Nice work!

**Comment by Wengier** [comment]
I have modified the render.cpp file slightly so that the code should build in Linux SDL1. If @linkmauve finds any issues in the code feel free to post them here.

**Comment by linkmauve** [comment]
I assume you meant 15f1565a8391effd27db1698803d2d6f4e41e118, and if so there is indeed an issue: there is no amd64 CPU which doesn’t support SSE, as it is the mandatory set of SIMD instructions of this architecture, so the second branch of the `#if` will never be built.

Additionally, everywhere that I could see in the codebase, `__SSE__` is actually used to mean “built for amd64” (or i686 when using `-march=native`), most notably in `dosbox.h`, it would probably be better to replace that with an actual check that we are indeed on x86, so we’d avoid missing SSE2/AVX2 optimisations on generic i686, and still avoid building them on ARM or any other architecture.

**Comment by Wengier** [comment]
@linkmauve I am sure you know the AVX2 code better, but getting the code to compile is apparently also very important. Could you please propose a fix that solves both the said issue and let the code compiles successfully? Thanks!
