### ISSUE TITLE
Wrong 1x Resolution?

### ISSUE THREAD

**Issue by raekuul** [joncampbell123/dosbox-x#1897]
**Describe the bug**
I am having difficulty getting DOSBox-X to output at a 1x size window. 

**To Reproduce**
1. Load graphical program (example: BMENACE1, with native resolution 320x200).
2. Set "Normal 2x" scaler.
3. Set "None" scaler.
**Expected Behavior:** *"None" outputs at 320x200, "Normal 2x" outputs at 640x400*
**Observed Behavior:** *Both modes output at 640x400*
4. Set "Force Scaler"
5. Set "Normal 2x scaler.
**Expected Behavior:** *"Normal 2x" scaler outputs at 640x400*
**Observed Behavior:** *"Normal 2x" scaler now outputs at 1280x800*

**Environment (please complete the following information):**
 - Operating system: Windows 10 x64
 - DOSBox-X release version or commit SHA1 this issue occurred on: 0.83.6 Mingw x64
 - Used configuration, e.g. ```dosbox-x.conf```: [dosbox-x.conf](https://www.dropbox.com/s/v0bf7s3zrqj6773/dosbox-x.conf.txt?dl=0)

**Additional context**

**Comment by raekuul** [comment]
Got my problem figured out - The issue was with _Doublescan_ being enabled. 

With that said, this might mean that Doublescan causes DOSBox-X to output unexpected values without "Force Scaler" enabled.

**Comment by joncampbell123** [comment]
Doublescan is enabled by default because VGA hardware will normally emit each scanline twice to the monitor in 200-line modes.
