### ISSUE TITLE
CD-ROM swapping under Windows 98 not working

### ISSUE THREAD

**Issue by crawlingChaos** [joncampbell123/dosbox-x#190]
I mentioned this in the disk attach/detach thread, but since that is a longer term issue, I thought it worth mentioning in its own thread:

I have Windows 98 on a hdd image attached to -ide 1m and mapped to drive C:, two CD-ROMS iso's are attached to -ide 2m and mapped to drive D:

Pressing CTRL-F4 to swap CD-ROMS in Windows 98 does not switch images.
I can see a message that DOSBox-X is trying to swap the hard drive, but since there are no other images mounted on that drive, nothing happens.

**Comment by Gui55** [comment]
CTRL-F4 is for swapping floppies only. To swap CD-ROMs use CTRL-F3. Hope this helps!

(You can also change these mappings at any time in the mapper file [CTRL-F1], because these do have their own events.)

**Comment by crawlingChaos** [comment]
Thanks, I'll try it. 

Still doesn't make sense that it prints a message regarding swapping the hdd image though.

I have used CTRL-F4 to swap CD-ROMS under vanilla DOSBox 0.74 before, so this behavior is different I guess?

**Comment by aybe** [comment]
TODO put in FAQ and close
