### ISSUE TITLE
[RFE] Add screenshots to AppStream metainfo file

### ISSUE THREAD

**Issue by AsciiWolf** [joncampbell123/dosbox-x#1901]
Currently, there are no screenshots in the AppStream [metainfo file](https://github.com/joncampbell123/dosbox-x/blob/master/contrib/linux/dosbox-x.metainfo.xml.in) for DOSBox-X. Please, consider adding some.

**Comment by rderooy** [comment]
Yeah I know. It is one of the things I planned to do.

I'm not sure yet if I will just add it upstream and let it trickle down with the next monthly release (early Nov.) or add it here locally as a temporary solution.

**Comment by rderooy** [comment]
I just added a PR for this: https://github.com/joncampbell123/dosbox-x/pull/1930

**Comment by AsciiWolf** [comment]
Thanks!
