### ISSUE TITLE
More information needed on the configuration tool. And a proposed change to the Wiki search function.

### ISSUE THREAD

**Issue by zydanielson** [joncampbell123/dosbox-x#1907]
### Problem - Part 1
**How do I hide the configuration tool?**

I don't want my client to see the configuration tool when DOSBox-X initializes. Somehow I changed something once so that the configuration tool doesn't show when DOSBox-X is run. But I don't know what I changed to make that happen and can't find anything about this in the Wiki, so I can't find out how to do this again. How do we prevent the configuration tool from popping up when loading DOSBox-X?

### Problem - Part 2
**Finding an answer to this problem in the Wiki**

**On This Wiki page :**
https://github.com/joncampbell123/dosbox-x/wiki/DOSBox%E2%80%90X%E2%80%99s-Drop%E2%80%90Down-Menus
There is a good description of the drop down menus. However, I would suggest some additional pieces of information on this page:

1. Tell on this page about how to turn the menu bar off and on with **F11-Esc**, or better yet, repeat the complete explanation of **DOSBox-X’s Special Keys**, as found on the Wiki home page here: https://github.com/joncampbell123/dosbox-x/wiki#dosbox-xs-special-keys -- or at least link to it.

1. Explain how the menu bar can be turned off or on initially in the config file.

1. Explain how to suppress the appearance of the configuration tool when DOSBox-X loads. (My main question above in this issue.) I found it accidentally when I configured the computers on my client's site. But now I can't find it again. I would like to suppress this on the DOSBox-X that is loading the machine in my office.

**Proposed Change to the Wiki Search Function**

All three of these pieces of information are related and should be easily found in one place. For that matter, it isn't really very easy to find _anything_ specific in this Wiki. Is it possible to create a search function that would find pages mentioning what the user is looking for? The only search function I've found is on the right column where it has a search box that says _"Find a Page ..."_ -- but this search function only appears to search page titles and not the text in the pages themselves.

Is it possible to improve this search function? It would have been nice to type in "configuration tool" and find all this information in one place, or at least on the various pages where this is mentioned in the text of the Wiki pages (not just the titles of the pages).

**Comment by rderooy** [comment]
Regarding the search function. The wiki is provided by github and the projects have practically no control over it. The only thing you can do is add/update/delete pages. In fact, github even blocks search engines like google from indexing the wiki. @Wengier had an idea of how we may be able to bypass the block for the dosbox-x wiki such that google and such could find the pages but that still has to be implemented.

**Comment by zydanielson** [comment]
Hello @rderooy, @Wengier:
>  @Wengier had an idea of how we may be able to bypass the block for the dosbox-x wiki such that google and such could find the pages but that still has to be implemented.

**Brainstorming a Bit**

- Is that implementation planned? It would certainly make this Wiki more useful!

- There is also open source wiki software out there. Is it feasible to obtain such software and create a more functional wiki for this project on https://dosbox-x.com/? I'd be happy to research this idea further if it sounds interesting to you folks.

Meanwhile, need any help writing for or maintaining the Wiki being used here on github for this project?

**Comment by Wengier** [comment]
About the configuration tool (Part 1), I am not exactly sure what you mean. I think DOSBox-X will not launch the configuration tool by default when it starts unless you specify the command-line option -startui (or -startgui). On the other hand, the configuration tool will not be launched at start in the default setting. Or do you mean you want to hide the "configuration tool" from the drop-down menu completely?

About the drop-down menus (part 2) - Sure, it can be mentioned in the Wiki. Indeed, anything like this can be added to the user guide. Thanks for the suggestion.

Also, thanks for the general ideas to improve the DOSBox-X Wiki system. Such improvements are certainly helpful for DOSBox-X users. I think it is possible to put the Wiki pages on https://dosbox-x.com/ itself, both for better functions and to unblock search engines as @rderooy mentioned. Please free feel to research this idea further and let us know when you think you find something useful. And of course any help to write for (or maintaining) the Wiki pages is helpful to the project and definitely appreciated.

**Comment by rderooy** [comment]
The problem with putting the wiki on dosbox-x.com is that it adds
additional maintenance overhead. A free wiki is not an issue, there are
several, chief amongst them mediawiki as used by wikipedia. But the
software needs to be maintained, and I don't know where dosbox-x.com is
hosted, but adding a wiki to it can incur additional costs for
bandwidth/storage/cpu.

**Comment by Wengier** [comment]
@rderooy I think the dosbox-x.com domain is a just a wrapper for the gh-pages branch on DOSBox-X's GitHub site. So I guess the actual hosted server will remain the same as is (on Github).

**Comment by zydanielson** [comment]
Oh goodness, this is my bad. In the Windows Start Menu there are many shortcuts. I think I meant to drag out to the desktop the first one that directly loads the DOSBox-X.exe, but instead I accidentally dragged out the second one and immediately changed the shortcut name:
![WindowsStartMenu](https://user-images.githubusercontent.com/11687580/95001464-736a4400-0587-11eb-82da-ff1e5eb01038.jpg)
When I used a shortcut to the plain .exe itself, everything loaded as expected, without showing the gui tool. Sorry about that. I guess I've been working too many long, late night hours!

**As to the Wiki**

I see through notifications that all three of us (me, @rderooy, and @Wengier) are posting at the same time. I'll wait until you guys finish before posting more about the Wiki.
::chuckle::

**Comment by Wengier** [comment]
@zydanielson You can certainly post more comments about the Wiki. No problem for that.

**Comment by Wengier** [comment]
@zydanielson Also, I have already added the following information to the [DOSBox‐X’s Drop‐Down Menus](https://github.com/joncampbell123/dosbox-x/wiki/DOSBox%E2%80%90X%E2%80%99s-Drop%E2%80%90Down-Menus) Wiki page. Thanks for the suggestion.

```
DOSBox-X will show the drop-down menus in the windowed mode by default, but you can also hide it if you prefer, using any of the following methods:

* Start DOSBox-X with the -nomenu command-line option;

* Set the option "showmenu" to "false" in [sdl] section of the DOSBox-X configuration;

* Under the "Video" menu, select "Hide/show menu bar" when the menu bar is currently visible;

* Using the key combination ([F11/F12]+Esc by default - F11+Esc on Windows and F12+Esc otherwise) to toggle the menu bar.
```

**Comment by zydanielson** [comment]
That's great, @Wengier. Thank you!

**Comment by Wengier** [comment]
@zydanielson and @rderooy After a few hours' effort, I finally got the DOSBox-X largely working from the dosbox-x.com domain:

https://dosbox-x.com/wiki/

There are still some pages needed to be cleaned up, but it seems to work. Thanks a lot for proposal, and the next step will be to implement the actual search Wiki function.

**Comment by Wengier** [comment]
Virtually all Wiki pages are working from https://dosbox-x.com/wiki/ now. But it looks that GitHub pages do not support dynamic contents like PHP, so I am not sure if search functions can be implemented natively. But I hope search engines like Google can now search for pages within it.

**Comment by rderooy** [comment]
The rendering of that looks so much better than it did on github. But now
we need to adjust a few links to point to the new location.

**Comment by zydanielson** [comment]
@Wengier The way you have set this up, putting everything on one long page actually has the advantage of using the browser's Ctrl-F to find what you need in the Wiki. This is great!

I did a Ctrl-F and typed in "configuration tool" and got 6 places on the page where it is mentioned. This works well even without an intelligent search feature. Of course, it would be GREAT to get major search engines to index the wiki.

WTG!

**Comment by Wengier** [comment]
It will be pretty good to automatically redirect the previously main Wiki (https://github.com/joncampbell123/dosbox-x/wiki) to https://dosbox-x.com/wiki/, but I am not sure how to do so even after some online search. Right now I can only add a note in it to mention that "The DOSBox-X Wiki is now also available from: https://dosbox-x.com/wiki".

**Comment by Wengier** [comment]
@zydanielson I agree that it will be very helpful to get major search engines to index the wiki. If only it supports dynamic content like PHP, then a built-in search feature can be implemented natively as well.

**Comment by zydanielson** [comment]
> "The DOSBox-X Wiki is now also available from: https://dosbox-x.com/wiki".

Perhaps adding something about Ctrl-F:

**The DOSBox-X Wiki is now also available in a single page format, easily searchable with Ctrl-F on your browser. Here: https://dosbox-x.com/wiki.**

**Comment by Wengier** [comment]
@zydanielson I think it is not really in single page format - there are still subpages as before. In order to make users easily to see the (main) subpages, I have now made the Wiki in HTML frame format. When you enter https://dosbox-x.com/wiki, you will now see "Wiki main page", "List of Wiki guide pages", "DOSBox-X project homepage", "DOSBox-X issue tracker" on the top frame, which will always be visible as long as you are in the Wiki.

**Comment by zydanielson** [comment]
Great job, @Wengier. I like it a lot!

Maybe it's not necessary, but considering how long it took _me_ to remember to do it, it might be helpful to note this somewhere:

**To locate specific information on any Wiki page, remember to use Ctrl-F (find) in your browser.**

**Comment by Wengier** [comment]
@zydanielson Thanks for the suggestion! I have already added the following text in the top frame of the DOSBox-X Wiki:

**Hint: To locate specific information on any Wiki page, you can use Ctrl+F (Command+F on a Mac) to search for text in your browser.**

Please feel free to post any other suggestions for the Wiki.
