### ISSUE TITLE
Command "BOOT" has an extra step (F1 ... DOS, F5 ... disk 2)

### ISSUE THREAD

**Issue by tinue** [joncampbell123/dosbox-x#1913]
**Issue description**

The command "BOOT" is supposed to boot a mounted hard disk image (or a floppy, but this is not relevant for this issue). According to the documentation, the command will simply boot the image.
Instead, a prompt is shown:
```
F1 . . . Dos
F5 . . . disk 2

Default: F1
```

After a while, the default kicks in and the image boots.

**To Reproduce**
1. Mount a disk image, for example:
```
MOUNT X DriveC
IMGMOUNT C X:hd512mb.img
```
2. Boot the mounted image:
```
BOOT -l C
```

**Expected behavior**
The image is booted immediately.

**Environment (please complete the following information):**
 - Windows 10 2004
 - 0.83.5 SDL2
 - Used configuration:
```
[autoexec]
KEYB SG
MOUNT X DriveC
MOUNT M SETUP

IMGMOUNT A M:DRIVERS.img -t floppy
IMGMOUNT C X:hd512mb.img
IMGMOUNT D M:Win98.iso -t iso

BOOT -l C
```

**Comment by rderooy** [comment]
This is mentioned on the wiki. It is the imgmake command that writes a MBR
that prompts you to press a key. If you want to get rid of it, once you
have booted DOS/Win9x run the command:

fdisk /mbr

**Comment by tinue** [comment]
Thank you for your explanation! I found the Wiki entry here: https://github.com/joncampbell123/dosbox-x/wiki/Guide%3ADOS-Installation-in-DOSBox%E2%80%90X#boot-menu
Closing the issue.
