### ISSUE TITLE
Custom BIOS?

### ISSUE THREAD

**Issue by sikthehedgehog** [joncampbell123/dosbox-x#193]
Is there any way to make dosbox-x run with a BIOS provided by the user instead of the built-in one? (and if not, would it be worth adding this feature?) I'm asking because somebody just dumped the Tera Drive BIOS and I wanted to see how far it'd go before it hit a barrier against the MD-side hardware :P

**Comment by joncampbell123** [comment]
I would love to add that! I already have in mind running the BIOSes of some old 486 motherboards I have in DOSBox-X, including that one that has the "graphical" user interface.

**Comment by Rondom** [comment]
You might want to look at PCem. It supports quite a few machines with their original BIOSes.
https://pcem-emulator.co.uk/

**Comment by joncampbell123** [comment]
That would provide more immediate gratification, yes.

DOSBox-X still needs some code cleanup and reorganization. I would love to have the option to run BIOSes directly, but I'm more concerned with cleaning up the code and improving BIOS and DOS startup process.

**Comment by joncampbell123** [comment]
I've long forgotten this issue, but technically this has been fullfilled with the --bios option in the BOOT command.

BOOT --bios ROMIMAGE.BIN

Enjoy.

**Comment by ndbroadbent** [comment]
Hi @joncampbell123! Sorry to comment on an old issue, but I'm struggling to find any further information about the BOOT command and how to boot with the `--bios` option. I would love to get an old Award BIOS running with the energy star logo before I boot into Windows 95/98 (for nostalgia reasons, so it feels like turning on my old PC.)

<img width="640" alt="Screen Shot 2021-08-23 at 2 53 04 PM" src="https://user-images.githubusercontent.com/139536/130784151-51543f6c-5e06-4eca-b5e5-93a47e6d9206.png">

I've also been playing with pcem, and I found that their 486 machine uses the ROM at `sis496/SIS496-1.AWA` for this Award SiS 496/497 BIOS.

I downloaded `dosbox-x` and ran it from my `~/code/pcem/roms` directory:

```
cd ~/Downloads/dosbox-x-macosx-x86_64-20210801002330/dosbox-x/dosbox-x.app/Contents/MacOS
./DosBox ~/code/pcem/roms
```

Then I ran `BOOT --bios sis496/SIS496-1.AWA`, which gave me some errors:

```
LOG: Loading BIOS image sis496/SIS496-1.AWA to 0xe0000, 0x20000 bytes
LOG:    2786400 ERROR BIOS:CMOS:WRite to unhandled register 3f
LOG:   14564174 ERROR CPU:Write fe20aa55 to rom at c0000
LOG:   14564175 ERROR CPU:Write cb002438 to rom at c0004
LOG:   14564176 ERROR CPU:Write 0 to rom at c0008
LOG:   14564177 ERROR CPU:Write 0 to rom at c000c
LOG:   14564178 ERROR CPU:Write 0 to rom at c0010
LOG:   14564179 ERROR CPU:Write 0 to rom at c0014
```

(I also figured out that I could run `./DosBox ~/code/pcem/roms -fastlaunch -c "BOOT --bios sis496/SIS496-1.AWA"` to try to load the BIOS immediately.)

I've tried a lot of different pcem BIOS roms, and I can't seem to find any that dosbox-x can run. Do you know of any roms that work? Thanks a lot for your help!

**Comment by exrecege** [comment]
> I've long forgotten this issue, but technically this has been fullfilled with the --bios option in the BOOT command.
> 
> BOOT --bios ROMIMAGE.BIN
> 
> Enjoy.

Hi!
i try to boot bios.bin 
https://ia801509.us.archive.org/11/items/T43SLIC2.17UNo1802No2010ByTTAV134/T43-SLIC2.1_7U_no_1802_no_2010_by_TTAV134.zip
but error message popup comes:
![Screenshot (2)](https://github.com/joncampbell123/dosbox-x/assets/149888902/7db9bf1b-e335-422e-ae30-285180d57010)
How can i solve this?
THX

**Comment by joncampbell123** [comment]
> > I've long forgotten this issue, but technically this has been fullfilled with the --bios option in the BOOT command.
> > BOOT --bios ROMIMAGE.BIN
> > Enjoy.
> 
> @joncampbell123, for #3664 I tried loading IBM PC BIOS (from 86Box), but it gives only blank screen. I did that with `memsizekb=640`, `machine=cga` and `cputype=8086` and PC DOS floppy image mounted.
> 
> Can you please give some tips how to use that function?
> 
> Will [GLaBIOS](https://github.com/640-KB/GLaBIOS) work and if so, which of the files to use?

It's probably running the BIOS (you should see it in the debugger) but the emulation is probably not what the BIOS expects. Perhaps that could be improved over time, of course.

What I have tested somewhat well enough so far is the option to load and run a VGA BIOS image. Specific combinations of machine=svga_s3 and S3 Trio ROM images seem to work OK.
