### ISSUE TITLE
Linux/SDL is not compatible with PS3 SixAxis gamepad

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#194]
http://sdl.5483.n7.nabble.com/patch-SDL1-2-1-3-fix-for-PS3-SixAxis-and-other-joysticks-td23888.html
"The Linux joystick driver enumerates all axes up to ABS_MISC but
accepts input for all axes up to ABS_MAX. This causes all axes after
ABS_MISC to be remapped to axis 0, because the abs_map table is
initialised to zero. In practice this makes joysticks such as the PS3
SixAxis gamepad almost unusable.

As a simple fix I suggest replacing ABS_MISC with ABS_MAX around line
705 in src/joystick/linux/SDL_sysjoystick.c so that all axes including
the accelerometer ones are available."

Here is the patch for SDL:

``` diff
diff --git a/src/joystick/linux/SDL_sysjoystick.c b/src/joystick/linux/SDL_sysjoystick.c
--- a/src/joystick/linux/SDL_sysjoystick.c
+++ b/src/joystick/linux/SDL_sysjoystick.c
@@ -702,7 +702,7 @@ static SDL_bool EV_ConfigJoystick(SDL_Joystick *joystick, int fd)
                ++joystick->nbuttons;
            }
        }
-       for ( i=0; i<ABS_MISC; ++i ) {
+       for ( i=0; i<ABS_MAX; ++i ) {
            /* Skip hats */
            if ( i == ABS_HAT0X ) {
                i = ABS_HAT3Y;
```

**Comment by joncampbell123** [comment]
Applied.
