### ISSUE TITLE
Viewing the FPU stack in the debugger

### ISSUE THREAD

**Issue by midn1** [joncampbell123/dosbox-x#1940]
**Is your feature request related to a problem? Please describe.**
It's a pain to debug programs that use the x87 stack.

**Describe the solution you'd like**
To add a view of the x87 stack on the "registers" window of the debugger.

**Describe alternatives you've considered**
`fst` the data into memory, view the raw bytes, then put them through a IEEE-754 calculator

**Additional context**
Something like this, perhaps?
![image](https://user-images.githubusercontent.com/7090833/95651266-b02ec180-0ad8-11eb-951c-ff7213413766.png)

**Comment by midn1** [comment]
I'm trying to implement this feature myself, but I can't at all figure out how to get any value from the FPU. All values from `fpu.regs_80` and `fpu.p_regs` (when reinterpreted as a long double) seem to be zero.

**Comment by midn1** [comment]
The error turned out to be a broken program I was testing :P. I've gotten it to work, maybe I'll PR.

**Comment by Wengier** [comment]
@midn1 Sure, please feel free to send PR related to the debugger etc. Thanks!
