### ISSUE TITLE
[git]Dosbox-x build process stops in dos_execute.cpp

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#1941]
**Describe the bug**
I try to build dosbox-x from git using commit https://github.com/joncampbell123/dosbox-x/commit/fafe30be6854e0cc8cf7802c6c0e3c47d14c26d8

Build process stops with this message:

```
dos_execute.cpp:306:62: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
  306 |         bool shellcom = !strcasecmp(name+fLen-8, "4DOS.COM") && (fLen == 8 || *(name+fLen-9)=='\\') || !strcasecmp(name+fLen-11, "COMMAND.COM") && (fLen == 11 || *(name+fLen-12)=='\\'); // Trap 4DOS.COM and COMMAND.COM
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dos_execute.cpp:307:41: error: 'stricmp' was not declared in this scope; did you mean 'strncmp'?
  307 |         if (!shellcom || !DOS_OpenFile(!stricmp(name+fLen-8, "4DOS.COM")?"Z:\\4DOS.COM":"Z:\\COMMAND.COM",OPEN_READ,&fhandle)) {
      |                                         ^~~~~~~
      |                                         strncmp
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
make[3]: *** [Makefile:410: dos_execute.o] Error 1
```

**To Reproduce**
1. Grab latest commit.
2. Use this configure line: ./configure --enable-core-inline --disable-debug --enable-avcodec --prefix=/usr --enable-sdl2
3. Run make
4. Wait a little

**Expected behavior**
Build process going on :)

**Environment (please complete the following information):**
 - Archlinux
 - Commit: https://github.com/joncampbell123/dosbox-x/commit/fafe30be6854e0cc8cf7802c6c0e3c47d14c26d8
 - gcc 10.2.0

**Comment by Wengier** [comment]
It looks like I missed line 307 while fixing line 306 for GCC. It is hopefully already fixed in the latest code, and please check it out.

**Comment by FredBezies** [comment]
Fixed, thanks!
