### ISSUE TITLE
Enabling avcodec causes dosbox-x crashes or triple CPU fault

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1947]
**Describe the bug**
Due to a recent change to the avcodec detection logic (https://github.com/joncampbell123/dosbox-x/commit/61d2e1e9493ad6c23521f7db744639604d7e89c1) during configure time, the avcodec libs are finally getting detected on my Linux (Fedora 33 beta) system. However, this has brought with it a new issue that was previously masked.

with avcodec enabled, I get a crash on startup of Win9x. Note that I'm not actually using the recording function.

```
LOG: Limit check 110000+4-1 = 110003 > ffff
LOG: Segment limit violation
LOG: E_Exit: Illegal descriptor type 4 for int D
E_Exit: Illegal descriptor type 4 for int D
```

If I build with ``--disable-avcodec`` the crash does not happen. This effects both SDL1 and SDL2.

I had originally reported this in https://github.com/joncampbell123/dosbox-x/issues/1904 but closed that as the original issue got lost due to subsequent unrelated posts.

The ffmpeg used comes from the rpmfusion repository, as fedora itself does not package ffmpeg.
```
$ rpm -qa|grep ffmpeg
ffmpeg-libs-4.3.1-11.fc33.x86_64
ffmpeg-4.3.1-11.fc33.x86_64
ffmpeg-devel-4.3.1-11.fc33.x86_64
```

**Comment by Wengier** [comment]
Looks like the avcodec code may be problematic at this time. Perhaps the option --disable-avcodec should be used by default for now until the problem is solved?

**Comment by rderooy** [comment]
That is what I did in my semi-automatic process, where I pull the latest updates and build both SDL1 and SDL2 binaries. As I rarely use the record functionality. But it is obviously not a real solution.

It would be good though if someone can confirm these crashes.

**Comment by Wengier** [comment]
@rderooy I notice that avcodec is probably causing issues even for MinGW builds on WIndows XP machines (see https://www.vogons.org/viewtopic.php?f=41&p=906423#p906423). So I just disabled it by default while allowing the option --enable-avcodec to enable the feature (https://github.com/joncampbell123/dosbox-x/commit/f6e5d3b1258951110c80f60b45ab60cf5044fc9e).

**Comment by Wengier** [comment]
I also added the --disable-libfluidsynth option to optionally disable libfluidsynth in that commit, so with it MinGW builds can use the built-in fluidsynth code even if external fluidsynth library is available (external libfluidsynth requires many extra DLLs in contrast to built-in fluidsynth support that has no such requirement).

**Comment by rderooy** [comment]
With the latest builds, it is now crashing even though I have ``--disable-avcodec`` specified when I do my local builds.

It seems that the option is now ignored when I run:

```
./build-debug-sdl2 --disable-avcodec
```
Because if afterwards I check with ldd, it is clearly linked:
```
$ ldd ~/bin/dosbox-x|grep libav
	libavcodec.so.58 => /lib64/libavcodec.so.58 (0x00007f5af78d9000)
	libavformat.so.58 => /lib64/libavformat.so.58 (0x00007f5af768a000)
	libavutil.so.56 => /lib64/libavutil.so.56 (0x00007f5af73e6000)
```

This is perhaps also the cause for the EMS386 and WfW issues that now occur regardless of ``core=`` and ``output=`` settings.

**Comment by rderooy** [comment]
After running ``./configure`` and if I check ``config.status``:

```
$ cat config.status |grep avcodec
ac_cs_config="'--disable-avcodec'"
  set X /bin/sh './configure'  '--disable-avcodec' $ac_configure_extra_args --no-create --no-recursion
"x-host/lib -lSDL -lX11 -lXext -lpthread -ltinfo -lfreetype  -lSDL_net -lz -lpng -lz -lpcap -lX11 -lXrandr -lxkbfile -lfluidsynth -lavcodec -lavforma"\
"t -lavutil -lswscale -lavcodec  -lGL"
```
As you can see, it still has ``-lavcodec``

**Comment by rderooy** [comment]
Not sure why my config.status still had the references to avcodec, but after doing a ``./cleantree`` and removing ``--disable-avcodec`` from my own build script, the issue of avcodec getting enabled no longer occurs.

Still the issue remains that enabling avcodec causes crashes with:
- Booting DOS and running EMS386
- Running WFW (from integrated DOS, or when booting DOS)
- Booting Win9x

These issues happen regardless of SDL1 or SDL2, ``core=`` or ``output=`` settings.

**Comment by rderooy** [comment]
With the latest change (https://github.com/joncampbell123/dosbox-x/commit/61e4e5ea73e6cf608c4ea4da77c723b17b68462e), dosbox-x is crashing again with the default build scripts on Linux. I have to add ``--disable-avcodec``

**Comment by joncampbell123** [comment]
@rderooy More importantly, I fixed --disable-avcodec to actually work properly. :)

**Comment by rderooy** [comment]
Closing this issue as it no longer crashes with 0.83.20. Not that recording actually works properly, but that is a separate issue.
