### ISSUE TITLE
Add iso and cue/bin mount option in menu

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#1951]
**Is your feature request related to a problem? Please describe.**
If I am not wrong, I don't find a way to mount a CD-ROM image via the menu Drive > Drive Letter > Mount as CD-ROM.

**Describe the solution you'd like**
Add an option to load an ISO or cue/bin image in addition to physical drives and folders options already present.

Thank you.

**Comment by rderooy** [comment]
The option is there, it may just not be obvious.

All the "Mount as...." options are for mounting folders as floppy/hd/cd-rom
The "Mount disk image" option is what you want. When you select a ISO or CUE file, it will automatically mount it as a CD-ROM.

**Comment by MX9000** [comment]
Thank you rderooy,
you're right, my fault, I should have looked better.
However, it might be a good idea to integrate the Mount disk image menu entry into the 3 already existing entries, since HD, CD-ROM and floppy can be mounted not only as folders or physical devices, but also as image files.
Have a nice day.

**Comment by rderooy** [comment]
Mounting physical devices is a windows only thing, and to my understanding basically just mounts the root folder of the drive. Any additional tracks the CD may contain, like audio tracks will, I think, not be available by mounting a CD this way.

**Comment by Wengier** [comment]
@MX9000 The mounting type for disk images is automatically in DOSBox-X, based on the drive letter and image type etc. So for example it will auto-mount ISO/CUE images as CD images.

In order to make the menu items more clearly, I have updated the menu items to read as the follows (for now):

```
Auto-mount Windows drive
Mount folder as hard drive
Mount folder as CD drive
Mount folder as floppy drive
Mount disk image
```

**Comment by rderooy** [comment]
@Wengier perhaps change "Mount disk image" to "Mount image file"? Or perhaps "Mount disk or CD image"

Disk image may seem to only apply to diskette/floppy or hdd images.

**Comment by Wengier** [comment]
@rderooy Good suggestion. How about "Mount disk or CD image file"?

**Comment by MX9000** [comment]
@Wengier and @rderooy thanks for your help: now the menu seems much clearer to me.
