### ISSUE TITLE
SDL1 under Windows not working anymore...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#1957]
When i compile the current master with VS2019, SDL1 build, then the BIOS screen is showing up and then the DosBox crashes.

**To Reproduce**
1. Compile DoxBox in VS2019 SDL(1) build
2. Start the new compiled DosBox-x.exe

**Expected behavior**
DosBox internal command.com after Bios screen

**Screenshots**
Not availiable

**Environment (please complete the following information):**
 - Operating system: Windows 10 x64 (1809)
 - DOSBox-X commit with SHA1 b8e265207481ff37b13768541a1e612f8c7d8f35
 - default dosbox-x.conf settings

**Comment by Wengier** [comment]
Are you building 32-bit or 64-bit binary? Maybe there is something wrong with the building tree with your VS2019 environment? As of recently I mainly use VS2019 to build the DOSBox-X code (primarily SDL1) in my machine too, but I could not reproduce the problem. Perhaps try a clean build and see how it works?

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Hello Wengier,

This is hapens on both 32 bit and 64 bit builds.
The problem on 64 bit build is a little bit different, it does'nt crashes, it hangs (must be killed through taskmanager).
I always used a clean build. :-(.
And i use a fresh and full installed current version of vs2019.

**Comment by Wengier** [comment]
I have uploaded both 32-bit and 64-bit Visual Studio SDL1 binaries I built based on the latest code. Can you check them out and see if they work?

32-bit: [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-update.zip)

64-bit [dosbox-x-64-update.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-64-update.zip)

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Both versions have the same problem :-(.
I tried on multiple systems.

**Comment by Wengier** [comment]
Interesting. I tried both binaries on at least two systems and both seemed to work. Perhaps other users can try them also and see if they work?

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
I try to find out which commit was the last working one

**Comment by whocares0101** [comment]
Just tried the 64 bit version and it just crashes no error dialog.
I'm using windows 10 x64 2004.
[dosbox-x.log](https://github.com/joncampbell123/dosbox-x/files/5409054/dosbox-x.log)

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
I was able to find out the first non working commit - 70e948c

**Comment by Wengier** [comment]
@whocares0101 Thanks for checking it out and let me know the result.

@B-u-R-n-I-n-G-f-I-r-E Thanks for trying to find out the first non-working commit. That change basically tried to make the shortcuts like "Left Ctrl+..." read as "Ctrl+" from the menu (see Issue #1949). The code works on my computer, but I think factors like mapper customizations can affect things too. Do you use for example customized mapper file for me to test? Thanks!

**Comment by Wengier** [comment]
@B-u-R-n-I-n-G-f-I-r-E Meanwhile, could you please check out the updated DOSBox-X binaries and see if they work on your system now? Thanks!

32-bit: [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-update.zip)

64-bit [dosbox-x-64-update.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-64-update.zip)

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Hi Wengier,

i don't use a customized mapper file.
The good news is, your last posted version is working!!! 👍

**Comment by Wengier** [comment]
@B-u-R-n-I-n-G-f-I-r-E Great to hear that!

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
No problem :-)

Keep on your great work 👍
