### ISSUE TITLE
asm code for DosBOX screenshot. Can be useful?

### ISSUE THREAD

**Issue by timofonic** [joncampbell123/dosbox-x#196]
I just found @BogdanHabic's [screenasm](https://github.com/BogdanHabic/screenasm) code for DosBOX, I wonder if it can be used in DosBOX-X too.

**Comment by joncampbell123** [comment]
The goal is that, if it works on real hardware, then it should work on DOSBox. And if it works in DOSBox, it should work on real hardware.
