### ISSUE TITLE
IPX does not work.

### ISSUE THREAD

**Issue by sduensin** [joncampbell123/dosbox-x#1962]
**Describe the bug**
Attempting to use IPX networking results in a huge number of console errors:
```
LOG:  538239568 ERROR CPU:Illegal Unhandled Interrupt Called 6
LOG:  538239586 ERROR CPU:Illegal Unhandled Interrupt Called 6
LOG:  538248154 ERROR CPU:Illegal Unhandled Interrupt Called 6
LOG:  538252345 ERROR CPU:Illegal Unhandled Interrupt Called 6
LOG:  538252363 ERROR CPU:Illegal Unhandled Interrupt Called 6
LOG:  538254577 ERROR CPU:Illegal Unhandled Interrupt Called 6
LOG:  551432911 ERROR CPU:Illegal Unhandled Interrupt Called 6
```

**To Reproduce**
Enable IPX in the config file.
Connect to another DOSBox-X instance with `ipxnet`.
Try to use IPX.

Specifically, this function never returns from the `int86()` call (Borland C++ code):
```
BYTE IPX::openSocket(short *socketNumber) {
	REGS regs;

	SHORTSWAP(*socketNumber);
	regs.w.ax = 0;
	regs.w.bx = 0x0;
	regs.w.dx = (unsigned int)*socketNumber;
	printf("Calling int 0x7a function 0x0\n");
	int86(0x7a, &regs, &regs);
	printf("Back\n");
	*socketNumber = (short)regs.w.dx;
	SHORTSWAP(*socketNumber);

	return regs.h.al;
}
```

**Expected behavior**
Working IPX?

**Screenshots**
This is the result from mainline DOSBox:
![image](https://user-images.githubusercontent.com/98645/96944394-4b904100-14a0-11eb-8b53-19da44601d9d.png)

With DOSBox-X it hangs after printing `Calling int 0x7a function 0x0`.  Technically, it doesn't really hang - it just starts consuming cycles like there's no tomorrow.

**Environment (please complete the following information):**
 - Linux Mint 19
 - DOSBox-X 0.83.6 (SDL2)

**Additional context**
I'm writing new DOS software using IPX.  Once I have a better IPX test program, I'm happy to share it.

**Comment by Wengier** [comment]
@sduensin With "ipx=true", does the command "ipxnet ping" work when you run it in DOSBox-X on your system? Also, I think you can still upload the current IPX test program so that we can check the issue more directly. Thanks!

**Comment by Wengier** [comment]
@sduensin Moreover, have you also tried your IPX test program in a real DOS system and see if it works the same?

**Comment by rderooy** [comment]
@Wengier in the screenshot, it shows ipxping working.

@sduensin the ipx code in dosbox-x to my understanding is the same as that in vanilla dosbox. As such, can you try with vanilla dosbox, or dosbox SVN to double check if your problem is unique to dosbox-x?

In any case, as you seem to already understand, dosbox implements IPX over IP, and therefore will for instance not work with legacy DOS machines running plain IPX.

**Comment by Wengier** [comment]
@rderooy I think the screenshot only showed ipxnet ping working in vanilla DOSBox, but **not** DOSBox-X. Correct me if I am wrong, but there seems to be no mention of whether ipxnet ping works in DOSBox-X in the original poster (only the result of ipxtest in DOSBox-X was mentioned).

**Comment by rderooy** [comment]
@Wengier my bad, your absolutely right!

**Comment by sduensin** [comment]
[IPXTEST.zip](https://github.com/joncampbell123/dosbox-x/files/5431191/IPXTEST.zip)

Here's a 16-bit real-mode DOS binary and the source code.  I used Borland C++ 4.52 to build it.

**Comment by Wengier** [comment]
Thanks for uploading the IPXTEST executable.

I think I can confirm the issue. Also, after trying a few earlier DOSBox-X versions it seems that the last version that this test program could work was the following DOSBox-X release:

https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-windows-v0.801.newyears.b3/dosbox-x-windows-dosbox-x-windows-v0.801.newyears.b3.zip

I think the issue is not with the IPX code itself, but because of other changes. Not yet sure at this time.

**Comment by Wengier** [comment]
@sduensin While the internal IPX option may not work for this for some reason, this issue can be easily solved by using the IPX via NE2000 networking instead, which I can confirm it will work just fine:

![image](https://user-images.githubusercontent.com/8216923/101860092-081a9080-3b3b-11eb-906c-5dd18c0d5564.png)

So just load LSL, NE2000 and IPXODI before loading IPXTEST, while setting ne2000=true and ipx=false. More details for setting up the NE2000 networking are available from:

https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X

**Comment by sduensin** [comment]
Thanks for the work-around.  I'm not blocked by this.  I just wanted to report it so it could be fixed.

**Comment by Wengier** [comment]
@sduensin Sure! Thanks for reporting it.

**Comment by cstubbs50** [comment]
I've also run into this ipx issue when trying to run Warcraft 2 for multiplayer networking.  When it first attempts to connect to the network on IPX it just hangs.  This has happened on 2 machines I own, a Windows 10 and Windows 8.

Also the work-around has an external link that no longer works for the Novell NetWare DOS/Windows Client v1.21.  It just says page not found.  https://www.novell.com/coolsolutions/tools/13555.html

Is there are an alternate location where we can download vlm121_2.exe and vlm121_6.exe?

**Comment by adufray** [comment]
Having the same issue, however IPX multiplayer does work in DOSBox vanilla (0.74-3-3). I'm testing with macOS (10.15.7), Warcraft II (1.40), and DOSBox-X (0.84.3).

**Comment by rderooy** [comment]
Confirmed with Doom II. ipxnet is able to connect between 2 instances of DOSBox-X running on the same host, but the game is always 'searching'.

**Comment by rderooy** [comment]
Novell IPX client is apparently no longer available from the Novell support site. You should be able to use this way back link: http://web.archive.org/web/19961221111819/http://support.novell.com/Ftp/Updates/nwos/vlm121/Date0.html

**Comment by BridgeHeadland** [comment]
[Novell IPX.zip](https://github.com/joncampbell123/dosbox-x/files/10889370/Novell.IPX.zip)
Here it will always be available.

**Comment by joncampbell123** [comment]
Please try the latest commit if you can compile from source code. It fixes some issues with the IRQ handler needed for IPX to work. Reopen if somehow it does not.
