### ISSUE TITLE
[archlinux][git]Dosbox-X build process is broken in sdlmain.cpp

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#1963]
**Describe the bug**
I tried to build Dosbox-X from git revision https://github.com/joncampbell123/dosbox-x/commit/5ee5e64affa4af8a09510239773daa71f18195b5 and it is broken in sdlmain.cpp:

```
/usr/bin/ld: gui/libgui.a(sdlmain.o): warning: relocation against `socknum' in read-only section `.text'
/usr/bin/ld: gui/libgui.a(sdlmain.o): in function `DOSBOX_parse_argv()':
sdlmain.cpp:(.text+0x18e61): undefined reference to `socknum'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

**To Reproduce**
1. grab last git revision
2. use these configure options: ./configure --enable-core-inline --disable-debug --enable-avcodec --prefix=/usr --enable-sdl2
3. launch build process and wait.

**Expected behavior**
Build process going on?

**Screenshots**

**Environment (please complete the following information):**
 - Archlinux
 - Commit: https://github.com/joncampbell123/dosbox-x/commit/5ee5e64affa4af8a09510239773daa71f18195b5

[dosbox.log](https://github.com/joncampbell123/dosbox-x/files/5429217/dosbox.log)
Adding build log if it helps...

**Comment by rderooy** [comment]
After the configure, did you run one of the scripts like build-debug-sdl2
or did you run make?

I'm asking as the build scripts are the most tested. In particular the
--disable-debug option is less often tested.
Unlike what you may expect, this disables the integrated debugger feature,
which you can use to debug DOS applications, and not debugging code in
dosbox-x itself.

**Comment by FredBezies** [comment]
> After the configure, did you run one of the scripts like build-debug-sdl2 or did you run make? I'm asking as the build scripts are the most tested. In particular the --disable-debug option is less often tested. Unlike what you may expect, this disables the integrated debugger feature, which you can use to debug DOS applications, and not debugging code in dosbox-x itself.

I launch directly make after configure part. And removing --disable-debug won't change a thing. Same error and same building crash.

**Comment by FredBezies** [comment]
Looks like this commit is related to this bug: https://github.com/joncampbell123/dosbox-x/commit/9b6f987d2e5a748db365a7b8239d5dd192c5b934

sdlmain.cpp was modified and I can see:

+extern int enablelfn, socknum;

Just an educated guess, of course.

**Comment by Wengier** [comment]
I think the issue only occurs when the null modem feature is disabled in the building process. Hopefully this commit (https://github.com/joncampbell123/dosbox-x/commit/a03ef8e1dddf0f50ace7070723b87c0dd5b69164) will fix it. Please check out the new code. Thanks for reporting!

**Comment by FredBezies** [comment]
> I think the issue only occurs when the null modem feature is disabled in the building process. Hopefully this commit ([a03ef8e](https://github.com/joncampbell123/dosbox-x/commit/a03ef8e1dddf0f50ace7070723b87c0dd5b69164)) will fix it. Please check out the new code. Thanks for reporting!

Well... It is still busted...

```
g++  -march=x86-64 -mtune=generic -pipe -fno-plt -std=gnu++11  -O2 -msse  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/fred/dosbox-x-git/src/dosbox-x -I/home/fred/dosbox-x-git/src/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/fred/dosbox-x-git/src/dosbox-x/vs2015/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L   -Wl,-O1,--sort-common,-z,relro,-z,now -L/home/fred/dosbox-x-git/src/dosbox-x/vs2015/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a aviwriter/libaviwriter.a  libs/xBRZ/libxbrz.a libs/mt32/libmt32.a libs/fluidsynth/libfluidsynth.a -lasound -lm -ldl -lpthread -L/usr/lib -pthread -lSDL2 -ltinfo -lfreetype  -lz -lpng -lz -lpcap -lX11 -lXrandr -lxkbfile -lfluidsynth -lGL
/usr/bin/ld: gui/libgui.a(sdlmain.o): warning: relocation against `socknum' in read-only section `.text'
/usr/bin/ld: gui/libgui.a(sdlmain.o): in function `DOSBOX_parse_argv()':
sdlmain.cpp:(.text+0x18e61): undefined reference to `socknum'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

**Comment by Wengier** [comment]
@FredBezies Interesting. In any case I have tried to fix it in a different way. Please check it out. Thanks!

**Comment by FredBezies** [comment]
> @FredBezies Interesting. In any case I have tried to fix it in a different way. Please check it out. Thanks!

Well, it is good. Build process is going to its end now. Thanks a lot for the fix!
