### ISSUE TITLE
Emulated pentium cpu stepping

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1966]
**Please describe your question.**
Setting ``cputype=pentium``, and running a CPUID tool: http://web.inter.nl.net/hcc/J.Steunebrink/chkcpu.htm

Reports a Pentium CPU with FDIV bug. Should we not emulate a CPU without FDIV bug?
![command_000](https://user-images.githubusercontent.com/17701098/97411214-4009a380-1900-11eb-8c60-e31573e71394.png)

I'm guessing it is because of the reported CPU stepping. Both B1 and C1 steppings have the bug, while the D1 stepping is fixed.

**Comment by joncampbell123** [comment]
What's wrong with emulating the FDIV bug? :)

(probably not going to happen)

**Comment by Wengier** [comment]
@joncampbell123 Is there an actual Pentium CPU without the FDIV bug? If so, perhaps there can be an advanced config option to control whether to emulate the said bug (probably false by default)?

**Comment by rderooy** [comment]
Ohh absolutely. It mainly effected the original 60 and 66MHz CPU's. And
Intel provided a free replacement CPU to those that wanted one.

**Comment by joncampbell123** [comment]
I think there were some 100MHz versions made with the bug too. At least I remember mine back in the day having something of that problem, though it didn't bother me at all. At most it might have caused the textures in Quake to warp a little more when viewing walls at extreme angles :)

**Comment by rderooy** [comment]
Yeah, there are some early 3.3V models that also had the bug.

**Comment by Wengier** [comment]
There is now an advanced config option "report fdiv bug" (in [cpu] section) which when set to true will report this bug.
