### ISSUE TITLE
add  xBRZ for SDL2 builds

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#1969]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Possibility to use xBRZ in SDL2 builds.

**Describe alternatives you've considered**
I used SDL1 but i want to jump to SDL2.

**Additional context**
None.

**Comment by Wengier** [comment]
Having taken a look at the code. I think you can just enable C_XBRZ for SDL2 in vs2015/config.h, then build the code and it should work. Not sure why it was disabled for SDL2 builds. In any case, I have already done so in the latest code (https://github.com/joncampbell123/dosbox-x/commit/bfc30fc6bf253ff5524dc6667f2aae27f8dbdf24).

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Thank You.
Now it's working. 👍
