### ISSUE TITLE
Alpha Waves (infogrames) has VGA flickering

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#197]
See here:
https://github.com/joncampbell123/dosbox-x/blob/master/NOTES/Alpha%20waves%20%28infogames%29.txt

Seems related to timing issue since vmemdelay=4000 led to no noticeable flickering under limited testing.

**Comment by joncampbell123** [comment]
Ah, forgot about that one.

I think the best way to determine whether to work on the problem is to run the game on actual 386SX hardware (with the turbo switch off *and* on) and see if the flickering happens on real hardware.

Another change I suggest is to adjust the vmemdelay option to see if making video RAM slower helps the game avoid flickering.

**Comment by joncampbell123** [comment]
Coming back to this later...

Running the game again, I notice that at cycles=10000 the time in the upper right hand corner runs way too fast.

It only runs at a normal speed if you slow it down to cycles=1230, but then that brings the framerate down.

I'm guessing that this game was written for really slow old PCs.

Also, found the source code: http://cc3d.free.fr/Alpha-Waves.zip

**Comment by joncampbell123** [comment]
The remaining task here is to run it on an old 386SX and see if the flickering is just as bad

**Comment by joncampbell123** [comment]
I can definitely confirm that on a Packard Bell 386SX at 20MHz, the game flickers as well.... and that the PC speaker music is hard on the ears.

I can stop the flickering if I toggle the turbo switch, at the cost of the frame rate.

**Comment by sikthehedgehog** [comment]
It does seem like the flickering is really that bad:
https://www.youtube.com/watch?v=bF_a6qMeWP8

From description:
> Produced using a 486 DOS system - not an emulator.

I know you said 386 but hopefully a 486 is close enough for this.

**Comment by joncampbell123** [comment]
It seems like anything faster than a 8MHz 386 causes the game to flicker.

**Comment by joncampbell123** [comment]
https://www.youtube.com/watch?v=WahsflP4mcc
