### ISSUE TITLE
DOSBox-X in PC-98 mode will not let me install Windows 3.1 unless I go into Japanese mode.

### ISSUE THREAD

**Issue by passerine-cult** [joncampbell123/dosbox-x#1971]
Found a Windows 3.1 install, specifically the one for NEC/Epson OEM.

Mounted the .img file as a virtual drive using ImDisk and when I tried to run Setup.exe it said "You cannot install Windows 3.1 on English mode. Try on Japanese mode."

How do I go into Japanese Mode?
![pc98](https://user-images.githubusercontent.com/72469891/97632851-5a22af00-19f0-11eb-8fe7-0e380fa524fc.PNG)

**Comment by joncampbell123** [comment]
Interesting, DOSBox-X with machine=pc98 should respond to country/locale INT 21h calls with code page data suggesting Japanese.

**Comment by joncampbell123** [comment]
Does it help if you add to dosbox.conf

[pc98]
pc-98 BIOS copyright string=true

Some versions of MS-DOS and Windows for PC-98 check for a copyright string in ROM in order to fail on Epson clones.

**Comment by joncampbell123** [comment]
Actually...

Does it help if you change your Windows locale to Japanese?

src/dos/dos.cpp line 1907 appears to use your Windows locale when asked extended country information on Windows.

**Comment by passerine-cult** [comment]
> Actually...
> 
> Does it help if you change your Windows locale to Japanese?
> 
> src/dos/dos.cpp line 1907 appears to use your Windows locale when asked extended country information on Windows.

I have a locale emulator, lemme try that.

**Comment by Wengier** [comment]
@joncampbell123 The dos.cpp code will use the Windows locale with the setting COUNTRY=0. But it can be customized with either the "country" setting in [config] section or the COUNTRY command. So for example the setting "country=81" (or the "COUNTRY 81" command from the shell) will hopefully use the Japanese locale.

**Comment by Wengier** [comment]
@passerine-cult I just checked myself. Typing the command "COUNTRY 81" before running PC-98 Windows 3.1 Setup should let it run. Please check it out.

**Comment by passerine-cult** [comment]
> @passerine-cult I just checked myself. Typing the command "COUNTRY 81" before running PC-98 Windows 3.1 Setup should let it run. Please check it out.

That worked! Thanks :)
