### ISSUE TITLE
Save State Failed

### ISSUE THREAD

**Issue by Capsulejay** [joncampbell123/dosbox-x#1974]
**Describe the bug**
When I try to use the save state feature in a game, I get an error message saying "Failed to save the current state".

**To Reproduce**
1. Go to Capture
2. Click on 'Save State'
3. See error

**Expected behavior**
Creates save state

**Screenshots**
Please see attached screenshot of the error message.

**Environment (please complete the following information):**
 - Windows 10
 - DOSBox-X 0.83.6

**Additional context**
The game I've been playing when running into this issue is called "Rusty". I don't have any other games to try at the moment to see if the error is specific to this game.
 ![DOSBox-X 0 83 6, 3000 cycles_ms, JO PAUSED 11_1_2020 2_18_40 AM](https://user-images.githubusercontent.com/73772458/97797390-a5081680-1bea-11eb-9ef3-eede54bb42c0.png)

**Comment by Wengier** [comment]
This error message is pretty generic. Can you open the error log (“Show console”) to see the exact cause of the error, e.g. something like “Save failed! Out of Memory”? Also, does the save work before you start the game?

**Comment by Capsulejay** [comment]
Thanks so much for the fast reply! I'm pretty new to this, so it's definitely possible that I'm doing something wrong rather it being a bug. I get the same error if I try to use the save before opening the game. Here's a screenshot of the console. 
![C__Program Files_DOSBox-X_dosbox-x exe 11_1_2020 2_49_39 AM](https://user-images.githubusercontent.com/73772458/97797688-22348b00-1bed-11eb-8b78-961e10163334.png)

**Comment by Wengier** [comment]
@Capsulejay I have never seen the log message "LOG: Save failed! - .\save\CMOS" myself before. I am wondering if you are using a configuration file with a setting that can cause the said issue. Perhaps you can try the default configuration and see if it works, or if possible you can post the configuration file you are using. Thanks.

**Comment by Capsulejay** [comment]
I only recently installed DOSbox-X and didn't change any settings from the defaults as far I recall. I've attached what I believe to be the config file. Please let me know if that isn't the right thing. Thanks again for your help.
[dosbox-x.conf.txt](https://github.com/joncampbell123/dosbox-x/files/5470364/dosbox-x.conf.txt)

**Comment by Wengier** [comment]
@Capsulejay Now I see that you running DOSBox-X from C:\Program Files\DOSBox-X\ directory. It is not recommended to install DOSBox-X here since it may not have written permission to create subdirectory or files under C:\Program Files\. Perhaps you can try to install DOSBox-X to the default location which is C:\DOSBox-X\ and how if it works better then?

**Comment by Capsulejay** [comment]
That solved the problem. Thanks so much for your help!
