### ISSUE TITLE
Fit to aspect ratio in fullscreen broken

### ISSUE THREAD

**Issue by divid3byzer0** [joncampbell123/dosbox-x#1979]
In DOSBOX-X 0.83.7 (64 bits, SDL2), whenever I choose the option "Fit to Aspect Ratio" and then go fullscreen, the image is "compressed" in width.

Went back to previous version (0.83.6) and works ok there.

**Screenshots**
![Untitled 1](https://user-images.githubusercontent.com/6065102/97999659-81f48700-1de3-11eb-825c-4b9b1ff7a6ff.jpg)

**Environment (please complete the following information):**
 - Windows 10 x64
 - DOSBox-X 0.83.7 (64 bits, SDL2)
 - Windows 95 conf file (same as in wiki).

**Comment by Wengier** [comment]
Have you tried the Windows SDL1 build and see if it works there? Or it is only specific to OpenGL output?

**Comment by divid3byzer0** [comment]
I tried with the latest Windows SDL1 build and as you suspected, it's OpenGL related, since the same thing happens there. With the Direct3D output it works as it should. I guess I'll keep using the SDL1 version for the time being.

**Comment by divid3byzer0** [comment]
> 
> 
> Have you tried the Windows SDL1 build and see if it works there? Or it is only specific to OpenGL output?

I tried with the latest Windows SDL1 build and as you suspected, it's OpenGL related, since the same thing happens there. With the Direct3D output it works as it should. I guess I'll keep using the SDL1 version for the time being.

**Comment by Wengier** [comment]
I think the issue with OpenGL was already fixed in the latest code.

**Comment by divid3byzer0** [comment]
Can confirm: latest version fixed this!
