### ISSUE TITLE
CD-Rom doesn't get reset

### ISSUE THREAD

**Issue by blindphoneman** [joncampbell123/dosbox-x#1980]
When booting into a DOS HD image, CD-Roms get duplicated.

I discovered this when I set up DOS 6.22 with CD-Rom support and ran memmaker, though this isn't related to memmaker itself.

What happens is that, the CD-Rom is recognized correctly the first time.

Upon a reboot issued by the OS, another drive appears.

First, here are my lines in the autoexec section of the config file:

imgmount c hdd.img
imgmount d pc-dos_2000.iso -t cdrom
boot -l c

Next, the output from the first boot, next reboot and next reboot.  Drive gets repeated:

First boot (normal):

Drive D is mounted as pc-dos_2000.iso
Z:\>boot -l c
Booting from drive C...

F1 . . . Dos
F5 . . . disk 2

Default: F1
Starting MS-DOS...

HIMEM is testing extended memory...done.

This driver is provided by Oak Technology, Inc..
OTI-91X ATAPI CD-ROM device driver, Rev D91XV352
(C)Copyright Oak Technology Inc. 1987-1997
  Device Name        : MSCD001
  Transfer Mode      : Programmed I/O
  Number of drives   : 1

MSCDEX Version 2.23
Copyright (C) Microsoft Corp. 1986-1993. All rights reserved.
       Drive D: = Driver MSCD001 unit 0
C:\>

Reboot (1 more drive showing)

Z:\>boot -l c
Booting from drive C...

F1 . . . Dos
F5 . . . disk 2

Default: F1
Starting MS-DOS...

HIMEM is testing extended memory...done.

This driver is provided by Oak Technology, Inc..
OTI-91X ATAPI CD-ROM device driver, Rev D91XV352
(C)Copyright Oak Technology Inc. 1987-1997
  Device Name        : MSCD001
  Transfer Mode      : Programmed I/O
  Number of drives   : 2

MSCDEX Version 2.23
Copyright (C) Microsoft Corp. 1986-1993. All rights reserved.
       Drive D: = Driver MSCD001 unit 0
       Drive E: = Driver MSCD001 unit 1
C:\>

Next Reboot (1 more drive showing)

Z:\>imgmount d pc-dos_2000.iso -t cdrom
MSCDEX installed.
Drive D is mounted as pc-dos_2000.iso
Z:\>boot -l c
Booting from drive C...

F1 . . . Dos
F5 . . . disk 2

Default: F1
Starting MS-DOS...

HIMEM is testing extended memory...done.

This driver is provided by Oak Technology, Inc..
OTI-91X ATAPI CD-ROM device driver, Rev D91XV352
(C)Copyright Oak Technology Inc. 1987-1997
  Device Name        : MSCD001
  Transfer Mode      : Programmed I/O
  Number of drives   : 3

Not enough drive letters available
C:\>

**Comment by Wengier** [comment]
@blindphoneman How did you reboot inside DOSBox-X? E.g. by clicking "Reset virtual machine" or by clicking "Reboot guest system"? If I click "Reset virtual machine" everything seems to get reset, and I did not see additional CD drives here. If I click "Reboot guest system", then the internal DOS shell will never show up and the guest DOS is restarting directly, and I did not see additional CD drivers here either.

By the way, you can just type ```imgmount d pc-dos_2000.iso``` instead of ```imgmount d pc-dos_2000.iso -t cdrom```, and ```boot c:``` instead of ```boot -l c```.

**Comment by blindphoneman** [comment]
Hi:

This occurred when a warmboot was requested, the way a lot of apps do.  The CD-Rom gets duplicated, for example, if I use the FDAPM utility from FreeDOS, though it doesn't really matter what program does the warm reboot.
So, for example, if I type FDAPM warmboot, it reboots, and it looks like I have 2 cd-roms instead of just one.  Next time, it looks like 3 drives, etc.For example.  Sending CTRL+ALT+DEL using the menus doesn't do this--just when a program inside the session requests a warmboot.

**Comment by Wengier** [comment]
@blindphoneman I think I have already fixed this issue in my latest pull request. If you use Windows, here is the latest Windows binary you can check out:

Download: [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

**Comment by blindphoneman** [comment]
Hi:

Looks like that did it.

These improvements are amazing.

Thanks much!
