### ISSUE TITLE
Two keyboard keys input same characters (SDL1 only)

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#1987]
**Describe the bug**

On my notebook (DELL Precision M6800 with italian keyboard) with SDL1 version of the last DOSBox-X release the "minus/underscore" key input the same characters as the "quote/question mark" key.
All other keys are configured correctly.
SDL2 version works 100%.

**Screenshots**

![63caff28d5325ad348ac4f95f5d07f35](https://user-images.githubusercontent.com/58113425/98447959-361a4880-2129-11eb-8ee2-d2c54fb7005e.jpg)

**Environment (please complete the following information):**
 - Windows 10 Pro 64 bit italian (version 2004)
 - DOSBox-X 0.83.7 SDL1 and 2 (nothing manually changed in .conf file)
 - KEYB command output "Codepage 437 has been loaded for layout it"

**Comment by Wengier** [comment]
While SDL1 version of the DOSBox-X should support most non-US keyboards fine as of the current version, it still does not guarantee all keys will always work 100% as intended. This appears to be a known issue. In such case I would suggest the SDL2 version instead.

**Comment by MX9000** [comment]
@Wengier , I was not using the SDL2 version because of the aspect ratio bug with OpenGL in full screen mode.
But I'm reading right now that it should be fixed for the next release.
Thanks for the info!

**Comment by Wengier** [comment]
@MX9000 Perhaps you can try the latest Windows SDL2 version I built and see how it works.

[dosbox-x-64-update.zip](https://github.com/joncampbell123/dosbox-x/files/5508670/dosbox-x-64-update.zip)

**Comment by MX9000** [comment]
@Wengier, Key and OpenGL aspect ratio issues fixed.
Thank you!
