### ISSUE TITLE
How to make save/load options persistent

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#1989]
Every time I launch the emulator I have to select "No remark when saving state" and "No warning when loading state" under "Capture > Save/load options" menu.
I can't find options in the dosbox-x.conf file to make this configuration permanent.
Thank you.

**Comment by Wengier** [comment]
You are certainly right about this - there should be options in the dosbox-x.conf file to make the save/load options persistent. I have already added config options "saveremark" (default: true) and "forceloadstate" (default: false) in [dosbox] section to control these options from the config file.

**Comment by MX9000** [comment]
@Wengier , great!
Thank you.

**Comment by maximus105** [comment]
@Wengier Could you do a MinGW x64 SDL1 build, with these fixes added for the save / load state?

**Comment by Wengier** [comment]
@maximus105 Sure, you can download the MinGW x64 SDL1 build here:

[dosbox-x-mingw64.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-mingw64.zip)

**Comment by MX9000** [comment]
Thank you all for the preview build, now the options are saved.
