### ISSUE TITLE
Option To Exclude Network Driver

### ISSUE THREAD

**Issue by paulrrogers** [joncampbell123/dosbox-x#1990]
Trying to get Privateer running and it requires `ems=false`. Sadly it still fails with "Network driver detected. Cannot start protected mode safely".

Ideally I could just exclude/disable the network driver from the DOSBox-X configuration or a switch so that protected mode could be used safely.

It appears that the only solution for now is to compile from source with SDL's networking excluded. Yet my attempts from Cygwin and WSL2 with the `build-mingw-sdl2` script all fail to detect `sdl2-config` or run into line ending problems with/in `configure`.

Regardless, thanks for all your work on DOSBox-X! Save states in particular really help make the older games more enjoyable.

**Comment by joncampbell123** [comment]
Hold on... what is the game using to detect the network driver? Is it looking for IPX?

Maybe all you need to do is disable IPX emulation, or NE2000 emulation entirely.

**Comment by Wengier** [comment]
I just checked, and it is likely because of the IPX bug in the 0.83.7 Visual Studio builds. @paulrrogers Please try the 0.83.7 MinGW builds which should work properly for this game.

**Comment by paulrrogers** [comment]
@Wengier thanks, using the built-in MinGW builds does work. And thanks for making the installer offer the option for other build types!
