### ISSUE TITLE
Make drive letter Z: configurable

### ISSUE THREAD

**Issue by piula** [joncampbell123/dosbox-x#1991]
**Is your feature request related to a problem? Please describe.**
My only frustration with DOSBox(-X) is the fixed mapping of its internal Z: drive. I'm used to using this drive letter for a RAMDisk, which conflicts with the fact that the drive letter is already in use.

**Describe the solution you'd like**
Imho, the optimal solution would be an option in the configuration file, e.g. "internal drive = z".

**Describe alternatives you've considered**
A single define in the source code would also be ok, e.g. "#define DOSBOX_DRIVE_CHAR 'I' " in a main header file. This way, one would have to only replace 1 occurrence and recompile DOSBox-X. There is an example here:

https://www.vogons.org/viewtopic.php?p=274051#274051

However, this patch has been written for DOSBox 13 years ago and there have been too many changes so it's hard for me to find the corresponding places in the current source code. In addition to that, I cannot be sure that the fixed Z: drive letter is meanwhile being used in more places.

**Comment by Wengier** [comment]
@piula Actually, DOSBox-X as of version 0.83.7 already allows you to move the internal virtual drive to any drive you want via MOUNT command. For example:
```
MOVE -Z Y
```
Will move the virtual drive to Y:.
```
MOVE -Z Z
```
Will move the virtual drive back to Z:.

It is more powerful than the patch you mentioned, as it allows you to move the drive as many times as you want. Hope this helps.

**Comment by piula** [comment]
Great 👍 Didn't know that, but it's indeed a wonderful solution. Thanks.
