### ISSUE TITLE
mode with cols=132 causes dir/w to mess up

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1996]
**Describe the bug**
Setting ``mode con cols=132 lines=60`` and running ``dir/w`` causes the output to be messed up. ``ls`` on the other hand has no issue, and neither does dir when using 4dos.

![command_000](https://user-images.githubusercontent.com/17701098/99059835-66396f80-259f-11eb-9d38-744f8773c047.png)

Also, question. Are you not supposed to be able to break a DIR output? I did a dir /s of a very large directory tree and neither CTRL-C nor CTRL-BREAK had any effect. Likewise with the ``tree``command.

**Comment by Wengier** [comment]
@rderooy Thanks for reporting the bug with DIR /W. I think I have already fixed it in my pull request.

And you are right, it will be nice to allow break from a long DIR output as well.
