### ISSUE TITLE
PS1 audio emulation has wrong clock [vogons]

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#200]
From PM:

Re: DOSBox-X branch

Sent: 2016-4-14 @ 02:51
From: Myloch
To: TheGreatCodeholio 
For Dosbox-X programmer(s): pitch for ps1 audiocard emulation is wrong, we already fixed that a long ago in Ykhwong's build. This was due to the fact Ps1 using most code taken from tandy emulator, but Ps1 audiocard hardware is slightly different. A kind friend shared card's datasheet some time ago in the ps1 audiocard main topic and we had confirmation of that. Jmk (original ps1 audiocard coder) managed to fix that, here is how to do it:

    Jmk wrote:
    Judging by what I've read in that technical document, it looks like the sound chip is fed by a 4 Mhz clock instead of a ~3.5 Mhz clock.

    So, there's a line in ps1_sound.cpp that looks like this:
    SN76496Reset( &ps1.sn, 3579545, sample_rate );

    Instead, it should look like this:
    SN76496Reset( &ps1.sn, 4000000, sample_rate );

    That should fix it! Mind you, that was with the old code (it was 0.72 I worked with) which may have been updated since, but the same principle applies.

Bug #2: Intersound MDO is not working in Asterix operation getafix for some odd reason. It works perfectly with other Coktel games like oliver & company, No Exit, Gobliins 2...

**Comment by box-tortoise** [comment]
https://bitbucket.org/pcem_emulator/pcem/commits/57b5243b9a11b7ae04056d6f3609229065a6644d

**Comment by joncampbell123** [comment]
http://www.vogons.org/viewtopic.php?f=32&t=18327&start=60

http://www.vogons.org/viewtopic.php?f=32&t=18327&start=40#p296745

**Comment by joncampbell123** [comment]
https://ps1stuff.wordpress.com/

**Comment by joncampbell123** [comment]
I have no means to test the change. Can anyone point me to some DOS games that use PS/1 audio capabilities? Or verify the change is the correct frequency?

**Comment by joncampbell123** [comment]
Test suite:

Prince of Persia (v1.0 and v1.3) - SN, DAC (IRQ).
Prince of Persia 2 - SN, DAC (IRQ).
Space Quest IV (VGA) - SN, DAC (Manually fed).
King's Quest V (EGA) - SN.
Bard's Tale III - SN.
Mario Andretti's Racing Challenge - SN.
BattleTech: The Crescent Hawks Revenge - SN.
Galleons of Glory - SN, DAC (IRQ).
Where in the World is Carmen Sandiego? Enhanced - SN, DAC (IRQ).
Joe Montana Football - SN.
F-14 Tomcat - SN, DAC (samples sound odd, needs to be looked at).
Stunt Island - DAC (Manually fed).
Bush Buck - SN.
Roger Rabbit 2 - DAC (Manually fed).
Sargon V - SN.
Red Baron - Reported OK.
Silpheed (PS/1 Version) - Reported OK.
Rocketeer - Reported OK.
