### ISSUE TITLE
Virtual Memory RAM drive for Clarion 2.1

### ISSUE THREAD

**Issue by zydanielson** [joncampbell123/dosbox-x#2004]
![image](https://user-images.githubusercontent.com/11687580/99469411-dfb6c200-28ff-11eb-9d81-b14f5bedf2d8.png)

### From the Clarion 2.1 Language Reference Manual:
> **Appendix E: Configuring Virtual Memory**
>
> ... Virtual memory is composed of conventional memory (below 640 kilobytes), extended memory (above 1 megabyte), expanded memory (EMS) , and hard disk....
>
> Extended and expanded memory must be assigned to a RAM drive to be used as virtual memory. A RAM drive is a fast pseudo disk drive that resides in expanded or extended memory. RAM drives can be set up with the VDISK or RAMDRIVE utilities supplied with the DOS operating system

### My Question
I was unable to find any utilities called VDISK or RAMDRIVE. How do I set up a RAM drive in DOSBox-X?

**Comment by rderooy** [comment]
You can create a RAM disk as follows:

```
imgmount d -t ram -size 10000
```
Size is in KB, so the above gives you 10MB. This does not effect available RAM in dosbox-x.

**Comment by zydanielson** [comment]
Thank you @rderooy.

### Three more questions.

1. This command is issued where? In the Autoexec.bat?
1. And in the command as you wrote it above, is **`d`** the drive letter of the RAM disk?
1. Is the **`imgmount`** command documented anywhere, so I can see the meaning of all the switches?

**Comment by Wengier** [comment]
@zydanielson You can issue the command either from the DOSBox-X's DOS shell, or in the [autoexec] section of dosbox-x.conf.
 Yes, D is the drive letter of the RAM disk. For help with the IMGMOUNT command, just enter ```IMGMOUNT /?``` from the DOSBox-X's DOS shell, and enter ``IMGMOUNT /EXAMPLES``` for some usage examples.

**Comment by zydanielson** [comment]
Thank you @Wengier. Now the challenge is getting Clarion 2.1 to recognize the RAM disk as virtual memory. I realize that's my arena, and not yours.

No luck with it so far. 🙃

**Comment by rderooy** [comment]
The RAM drive is mentioned on the wiki.
https://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X#_creating_a_ram_drive

**Comment by rderooy** [comment]
Just a thought...

The way DOSBox-X implements a RAM drive is rather different than it would have been on a traditional DOS system. For instance, on a retro DOS system it would use some amount of EMS or XMS memory, while in DOSBox-X it does not. Perhaps Clarion relies on, or checks for this behaviour.

The RAM drive is meant as a temporary disk really. Using it for making your application run faster, as you would have done on a retro DOS system, is unlikely to have the same speedup (if any) running under and an emulator. Modern systems have such (relatively) large caches that all your data is likely to be in the hosts cache anyway.

**Comment by Wengier** [comment]
@zydanielson The standard DOS drivers for creating RAM drives such as RAMDRIVE.SYS and XMSDSK do not work yet in DOSBox-X's built-in DOS shell, but they do work if you boot into a guest DOS system inside DOSBox-X. So if you really need this at this time you can certainly try to boot into a guest DOS system inside DOSBox-X and create RAM drives with these drivers. You can see the DOS install guide within DOSBox-X from the following Wiki page. Hope this helps.

https://dosbox-x.com/wiki/Guide%3ADOS-Installation-in-DOSBox%E2%80%90X

**Comment by zydanielson** [comment]
All good input here. Thanks to all who participated.

### Resolution
I was able to find a solution to the problem with a tedious amount of careful Clarion coding and am now able to store an image of where I was just before the call to a new program happens, and restore the image once the program returns. To the user this is invisible, so it looks like it's all happening in a single program. But the call frees up most of the 512k for whatever needs to be done in the modification of the original program. Clarion had the ability to do this with its CALL statement, but there were some documented limitations as to what would not be restored upon returning from the call. Unfortunately, the exact solution to the problem wasn't documented clearly anywhere in the Clarion manuals, nor was I able to find a solution to it anywhere on the web. However, I solved it. And now it works. ☺

@Wengier I'll remember the solution you suggested about booting into a guest DOS system inside DOSBox-X in case I ever decide to make use of extended or expanded memory through a RAM drive. However, with the solution I have created in Clarion itself, I think I will be able to do anything that needs to be done in conventional memory. I'd like to know if and when the built-in DOS shell of DOSBox-X will support **` RAMDRIVE.SYS, XMSDSK, etc.`** and I assume that will be posted somewhere when it happens. For now, though, I am content to stay with DOSBox-X as it is.

Many thanks again. I'm closing this issue and am happy with the resolution.

**Comment by Wengier** [comment]
@zydanielson Of course we want DOSBox-X’s DOS shell to support RAMDRIVE.SYS, XMSDSK, etc, but this requires DOS device driver support which is not yet implemented. But it is definitely a goal.
