### ISSUE TITLE
Program which runs in DOSBox crashes in DOSBOX-X when accessing a binary file

### ISSUE THREAD

**Issue by fwillo** [joncampbell123/dosbox-x#2006]
**Describe the bug**
Dear all,

I try to run a program for dental analysis in DOSBox in order to transfer from old machines to newer ones. This program is controling a hardware which reads sensors in order to analyse the jaw movement. Over a USB-Serial-Converter (FTDI chip) we can get it running with satisfactory results in DOSBox 0.74.3. However, display and sound aswell as response to keys were pretty glitchy, which is why I tried DOSBox-X. There, everything criticized before was working flawlessly. Unfortunately, calling some menus resulted in a crash back to the command-line.

Because the program is proprietary, I cannot provide any executable. I already could narrow it down to one *.BIN file being called. **Is there any difference in calling binary files in DOSBox-X?** I already tried to look for a hint in the debugger (I have some basic knowledge with assembler), but I fail to identify the code segments to libraries, executable what so ever.

The folder with the program content is mounted with the identical command as in the original DOSBox. I know that providing this less informations is not perfect, but maybe you can give me some hints in order to narrow it down to the root. There has to be a reason why this is not crashing in DOSBox 0.74.3.

Looking forward to your answers,
fwillo

**Expected behavior**
Not crashing to the command line

**Environment (please complete the following information):**
 - Windows 10, 64-bit
 - DOSBox-X 0.83.7 64-bit, SDL2

**Comment by fwillo** [comment]
One more note: On Linux DOSBox-X 0.83.7 64-bit, SDL2 is not crashing at this step.

**Comment by rderooy** [comment]
On a system where your having the crash, do you get any output to the log when it does?
Also, is your dosbox-x.conf file identical between Linux and Windows?

Can you dosbox-x on windows from the command prompt with the options ``-defaultconf -console`` to have it use the default config values and log to the console?

**Comment by fwillo** [comment]
Hi rderooy,

I ran `-defaultconf -console` on both systems and Linux runs where Windows crashes. I also ran inside DOSBox-X
```
mount c C:\DOSBOX # Windows
mount c /home/user/DOSBOX # Linux
C:
TMJ # The program
```
Here is the Windows log:
```
LOG: Early LOG Init complete
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 0.83.7 (Windows SDL2)
LOG: Windows keyboard layout ID is 0x0407
LOG: Host keyboard layout is now ger (German)
LOG: Mapper keyboard layout is now ger (German)
LOG: SDL2 reports desktop display mode 1920 x 1080
LOG: The default output for the video system: opengl
LOG: Configured windowposition:
LOG: SDL:Current window pixel format: SDL_PIXELFORMAT_RGB888
LOG: SDL: You are running in 24 bpp mode, this will slow down things!
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: ISA BCLK: 8333333.333Hz (25000000/3)
LOG: monopal: green,
LOG: Active save slot: 1 [Empty]
LOG: USING AVI+ZMBV
LOG: Max 3670016 sz 16384
LOG: Final 16384
LOG: MIDI:Opened device:win32
LOG: Pentium CMPXCHG8B emulation is enabled
LOG: VOODOO LFB now at d0000000
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Allocated APM BIOS pm entry point at f000:e88c
LOG: Writing code to fe88c
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Windows: IID_ITaskbarList3 is available
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: DOS keyboard layout loaded with main language code GR for layout gr
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Warning: file creation failed: C:\DOSBOX\TMJPROG\LPT1
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
```
And here the Linux log:
(comes in a moment, its running on another machine)

**Comment by rderooy** [comment]
This entry in the Windows log is probably the cause:

```
LOG: Warning: file creation failed: C:\DOSBOX\TMJPROG\LPT1
```

My guess would be that your user is not allowed to create files in that location?

**Comment by Wengier** [comment]
@fwillo and @rderooy The name LPT1 is the special device name for printing in DOS and Windows, which does not exist in Linux. Apparently the program is trying to access the printer, and DOSBox-X supports the printer passthrough feature, but @fwillo you probably have not set it up properly. Please check out the [parallel] and [printer] sections of DOSBox-X's config file for more information about printing. The issue does not happen in Linux simply because there is no such device named LPT1 there, and it is probably created as a regular file instead.

**Comment by fwillo** [comment]
@rderooy and @Wengier I feel so stupid for not taking this into consideration (although it seems a bit unlikely that a program crashes when not finding a printer). Configuring the printer as @Wengier stated lead to no crash. I should've not considering asm debugging and binary file access first and maybe work off the warnings in the log...

Thanks for your help!
