### ISSUE TITLE
PING google.com doesn't work

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#2008]
it gives me:
mTCP: Warning - trailing whitespace detected on line 23 of the config file.

Your DHCP lease expires in less than 3600 seconds! Please run dhcp.exe

However, when I type in DHCP google.com, it gives me:
unknown option: google.com

dhcp [options]

options:
 -help
 -retries <n> Retry n times before giving up
 -timeout <n> Set timeout for each attempt to n seconds
 -packetstats Show packet statistics at the end

What do I do?

**Comment by rderooy** [comment]
@jadasse All your network issues seem to be caused by the same problem. And ``dhcp google.com`` is simply wrong and will never work. DHCP is for getting a network address from a local DHCP server, and is not an alternative to PING. As mentioned in one of the other issues you created, did you follow the wiki?

**Comment by rderooy** [comment]
Below is an example where I ping google.com using mTCP.

In my dosbox-x config file I have set the following relevant options:

```
[ne2000]
ne2000=true
realnic=eno1
nicirq=10
macaddr=AC:DE:48:88:99:AC

[autoexec]
MOUNT C .
C:
SET MTCPCFG=C:\MTCP.CFG
NE2000.COM 0x60 10 0x300
DHCP
```

**WARNING** the above ``realnic=`` value is specific to MY PC. As indicated on the wiki page, you need to find which value is appropriate for yours.

In addition, the ``SET MTCPCFG=`` part needs to point to the MTCP.CFG file that is included with mTCP.

![Screenshot from 2020-11-20 22-45-57](https://user-images.githubusercontent.com/17701098/99852886-329fac00-2b82-11eb-946a-1c59160ea8c9.png)

**Comment by jadasse** [comment]
I followed what the wiki said, yes.

[ne2000]
ne2000=true
nicirq=10
realnic=6

[autoexec]
MOUNT C "C:\Users\dlada\Documents\dosbox-x-update\mtcp"
C:
SET MTCPCFG=C:\SAMPLES\SAMPLE.CFG
NE2000 0x60 10 0x300
DHCP

This is my conf btw, but I am still receiving the same thing, "Your DHCP lease expires in less than 3600 seconds! Please run dhcp.exe," but I know not to use it

**Comment by rderooy** [comment]
Can you please share the complete output of the ``ne2000`` and ``dhcp`` commands?

Running ``ne2000`` here returns:

```
C:\>NE2000.COM 0x60 10 0x300
Packet driver for NE2000, version 11.4.3
Packet driver skeleton copyright 1988-93, Crynwr Software.
This program is freely copyable; source must be available; NO WARRANTY.
See the file COPYING.DOC for details; send FAX to +1-315-268-9201 for a copy.

System: [345]86 processor, ISA bus, Two 8259s
Packet driver software interrupt is 0x60 (96)
Interrupt number 0xA (10)
I/O port 0x300 (768)
My Ethernet address is AC:DE:48:88:99:AC
```
And running ``dhcp`` returns:
```
C:\>DHCP
mTCP DHCP Client by M Brutman (mbbrutman@gmail.com) (C)opyright 2008-2020
Version: Mar  7 2020

mTCP: Warning - trailing whitespace detected on line 23 of the config file.

Timeout per request: 10 seconds, Retry attempts: 3
Sending DHCP requests, Press [ESC] to abort.

DHCP request sent, attempt 1: Offer received, Acknowledged

Good news everyone!

IPADDR 192.168.1.117
NETMASK 255.255.255.0
GATEWAY 192.168.1.1
NAMESERVER 192.168.1.1
LEASE_TIME 86400 seconds

Settings written to 'C:\MTCP.CFG'
C:\>
```

Also, it needs to be able to write to the file you have setup for ``MTCPCFG=``

**Comment by jadasse** [comment]
I got the same outputs you did. except for the results in DHCP: (i only listed what was different)
ipaddr 192.168.1.61
nameserver 65.19.96.252
lease_time 3583 seconds

**Comment by jadasse** [comment]
c:\samples\sample.cfg is what the settings are written to, btw

**Comment by jadasse** [comment]
One more thing, my ethernet address ends with AA instead of AC.

**Comment by jadasse** [comment]
Hello?

**Comment by rderooy** [comment]
after you ran the``ne2000`` and  ``dhcp`` commands, type:
```
ping 192.168.1.1
```

**Comment by jadasse** [comment]
no matter what I type in, I get the same error :(

**Comment by rderooy** [comment]
@jadasse I don't know what to suggest any more. Your not giving full output details so I'm just fishing in the dark.

If you want me to continue looking into this, please post your config file, and LOG output when starting dosbox-x with ``dosbox-x -console`` when you try to do the above ``ne2000``, ``dhcp`` and ``ping 192.168.1.1`` commands.

Also, do you have firewall software installed on your Windows software, other then what is provided by Windows itself? E.g. Symantec or something?

**Comment by jadasse** [comment]
Will do, and no I don't have a firewall other than Windows Security

**Comment by jadasse** [comment]
LOG: Early LOG Init complete
LOG: Win32 EnumDisplayDevices #0: name=\\.\DISPLAY1 string=Intel(R) HD Graphics 4600
LOG: Win32 EnumDisplayDevices #1: name=\\.\DISPLAY2 string=Intel(R) HD Graphics 4600
LOG: Win32 EnumDisplayDevices #2: name=\\.\DISPLAY3 string=Intel(R) HD Graphics 4600
LOG: Win32 EnumDisplayDevices #3: name=\\.\DISPLAY4 string=NVIDIA Quadro K2100M
LOG: Win32 EnumDisplayDevices #4: name=\\.\DISPLAY5 string=NVIDIA Quadro K2100M
LOG: Win32 EnumDisplayDevices #5: name=\\.\DISPLAY6 string=NVIDIA Quadro K2100M
LOG: Win32 EnumDisplayDevices #6: name=\\.\DISPLAY7 string=NVIDIA Quadro K2100M
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: Win32 EnumDisplayDevices #0: name=\\.\DISPLAY1 string=Intel(R) HD Graphics 4600
LOG: Win32 EnumDisplayDevices #1: name=\\.\DISPLAY2 string=Intel(R) HD Graphics 4600
LOG: Win32 EnumDisplayDevices #2: name=\\.\DISPLAY3 string=Intel(R) HD Graphics 4600
LOG: Win32 EnumDisplayDevices #3: name=\\.\DISPLAY4 string=NVIDIA Quadro K2100M
LOG: Win32 EnumDisplayDevices #4: name=\\.\DISPLAY5 string=NVIDIA Quadro K2100M
LOG: Win32 EnumDisplayDevices #5: name=\\.\DISPLAY6 string=NVIDIA Quadro K2100M
LOG: Win32 EnumDisplayDevices #6: name=\\.\DISPLAY7 string=NVIDIA Quadro K2100M
LOG: DOSBox-X version 0.83.8 (Windows SDL1)
LOG: Windows keyboard layout ID is 0x0409
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: The default output for the video system: direct3d
LOG: Configured windowposition:
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
 extracting: Program_Name
 extracting: Time_Stamp
 extracting: Save_Remark
LOG: ISA BCLK: 8333333.333Hz (25000000/3)
LOG: monopal: green,
LOG: Active save slot: 1
LOG: USING AVI+ZMBV
LOG: Max 1048576 sz 16384
LOG: Final 16384
LOG: MIDI:Opened device:win32
LOG: Pentium CMPXCHG8B emulation is enabled
LOG: VOODOO LFB now at d0000000
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Allocated APM BIOS pm entry point at f000:e88c
LOG: Writing code to fe88c
LOG: NE2000: Base=0x300 irq=10
LOG: Using Network interface:
rpcap://\Device\NPF_{5F06FACD-F7F5-4D7D-B95D-4439C5A0D8F7}
(Network adapter 'Intel(R) Ethernet Connection I217-LM' on local host)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Windows: IID_ITaskbarList3 is available
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1
LOG: BX_ERROR: ne2K: dma read underrun iolen=2 remote_bytes=1

[ne2000]
ne2000=true
nicirq=10
realnic=6

[autoexec]
MOUNT C "C:\Users\dlada\Documents\dosbox-x-update\mtcp"
C:
SET MTCPCFG=C:\SAMPLES\SAMPLE.CFG
NE2000 0x60 10 0x300
DHCP

**Comment by rderooy** [comment]
You seem to be getting a lot of dma read underrun errors. Do those occur when you try to PING, or when you run DHCP.EXE?

I'm asking as on my Linux system I get just a single one, and it is when running dhcp.

**Comment by jadasse** [comment]
It happened when autoexec ran dhcp.

**Comment by rderooy** [comment]
@jadasse I booted Win10 where I have **npcap** installed, and tried various of the dosbox-x 0.83.8 binaries (64bit SDL1 and SDL2, mingw, mingw-sdl2) and they all worked just fine running ping.

Unlike my Linux system, where I got just one underrun error, on Windows I got 3. But still nowhere near your error count.

To be honest, I don't know what to suggest at this point.

**Comment by jadasse** [comment]
Oh well, should we call it a day and close this?

**Comment by Wengier** [comment]
@jadasse Maybe there is some compatibility issue with network adapter on this computer? Perhaps you can try it on a different computer and see if you get a different result?

**Comment by jadasse** [comment]
Ok, ill try that

**Comment by Jookia** [comment]
Could you verify that packets are actually getting sent to your host adapter using Wireshark? Maybe this is a compatibility issue with your router

**Comment by jadasse** [comment]
Tbh i give up this was months ago
