### ISSUE TITLE
mTCP and towel.blinkenlights.nl

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#2009]
How do I connect to towel.blinkenlights.nl alike so in https://www.wikihow.com/Watch-Movies-Using-Telnet in mTCP? I tried telnet towel.blinkenlights.nl, but it gives me:
mTCP: Warning - trailing whitespace detected on line 23 of the config file.

Your DHCP lease expires in less than 3600 seconds! Please run dhcp.exe

**Comment by Wengier** [comment]
Can you post your config file so that we can take a look at? Thanks.

**Comment by rderooy** [comment]
@jadasse did you follow the wiki guide on setting up NE2000 networking?
https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X

**Comment by rderooy** [comment]
In any case, I just tried it and it seems to work just fine.

Using the exact same config as I posted in the other issue you created I did a
``telnet towel.blinkenlights.nl``

And it successfully connects and I get this:

![Screenshot from 2020-11-20 22-57-28](https://user-images.githubusercontent.com/17701098/99853898-21f03580-2b84-11eb-80f4-a3797d6d97d3.png)

**Comment by jadasse** [comment]
[ne2000]
ne2000=true
nicirq=10
realnic=6

[autoexec]
MOUNT C "C:\Users\dlada\Documents\dosbox-x-update\mtcp"
C:
SET MTCPCFG=C:\SAMPLES\SAMPLE.CFG
NE2000 0x60 10 0x300
DHCP

**Comment by Wengier** [comment]
@rderooy There is now a "List network interfaces" menu option under "Help" menu so that there is no longer a need to look at the log file for the network interface list. I think you can update the Wiki page accordingly as well.

**Comment by rderooy** [comment]
@Wengier nice! that will make it easier, especially for Windows users not having to run dosbox-x from a command prompt. I will update the wiki sometime this week.

**Comment by jadasse** [comment]
I'm still getting the same error (I didn't change anything, yet, I'm just posting this comment so this thread will avoid any inactivity)

**Comment by Wengier** [comment]
@jadasse If telnet shows the error "Your DHCP lease expires in less than 3600 seconds! Please run dhcp.exe", it means that your network setting is likely incorrect. For example, if I specify a wrong "realnic" setting I will get the exact same error (you can ignore "mTCP: Warning - trailing whitespace detected on line 23 of the config file" which has nothing to do with this). So please make sure the settings especially the realnic value is correct for your ethernet adapter.

**Comment by jadasse** [comment]
oh ok thx

**Comment by jadasse** [comment]
I tried all of them, and none of them seem to work :(

**Comment by Wengier** [comment]
@jadasse Do you have (wired) ethernet adapter(s), or only have WiFi? In the Wiki page mentioned above you can find the following paragraph, which may apply to your case:

```
By default DOSBox-X networking attempts to bridge to your chosen host network adapter.
This may not work, depending on the network adapter chosen as it relies on the adapter and its driver supporting true promiscuous mode.
In particular WIFI adapters are known to not work. Unfortunately there is no clear error message if you run into this problem,
and typically all you will experience is that your not able to get a DHCP address.
```

**Comment by jadasse** [comment]
I have ethernet, and wifi

**Comment by rderooy** [comment]
If the DHCP command is returning an IP address, than it should in principle work.

Try to ``ping`` your local gateway or DNS server. The 3600 seconds equates to 1 hour, so assuming your getting a valid address from ``dhcp``, it could be that your DHCP server on your network (typically provided by your home WIFI access point) is set to only hand out very short leases. But I have never seen this in practice.

As mentioned on the wiki page, make sure your point ``realnic=`` to your Ethernet adapter and not to Wifi, VPN or some other virtual adapter. Also make sure in your OS (Windows?) that your Ethernet adapter is your default network device. If possible disable the Wifi.

**Comment by jadasse** [comment]
Hello?

**Comment by rderooy** [comment]
@jadasse as long as you cannot even ping your local internet gateway (router), this will simply not work.

**Comment by jadasse** [comment]
Oh well, should we call it a day and close this?

**Comment by NoamRothschild** [comment]
Probably not relevant anymore, but I had encountered the same issue that the DHCP returned me only 3600 in lease time, and I managed to fix the issue by changing the value of
`dhcp_lease_threshold`
in the sample.cfg file of mTCP (under DHCP client options)

to be something lower, for example
`dhcp_lease_threshold 300`
This way you can still play around with the networking stuff until you only have 5 minuets and not 1 hour (which was the threshold given)
