### ISSUE TITLE
Color palette problems when switching to graphic mode from mode 7 (mode mono)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2010]
This is a long-standing DOSBox and DOSBox-X problem that I never got around to pointing out before. DOSBox-X supports the command "mode mono" which switches the display to video mode 7. But when an application like WordPerfect is running under mode 7, and that application switches to graphic mode, the color palette in graphic mode is  wrong and visual distortion occurs (see below). This problem does not occur under pure DOS or vDos

To reproduce, start DOSBox-X, enter MODE MONO at the prompt, and then start WordPerfect 5.1 or 6.x. 

In WPDOS 5.1, press Shift-F7, then 4 - View Document. You will see the graphic distortion. Press F7 to exit the View document screen, and F7 again to exit WPDOS.

In WPDOS 6.x, press Shift-F7, 7 - Print Preview, to see the graphic distortion. Press F7 to exit the preview screen, and F7 to exit WP.

This is an example of the distortion in WPDOS 5.1, using default settings in DOSBox-X:

![Capture](https://user-images.githubusercontent.com/5208505/99696281-8912ca80-2a5c-11eb-8bce-50032c8882c3.PNG)

This is what it ought to look like, illustrated from vDos:

![Correct](https://user-images.githubusercontent.com/5208505/99696397-a778c600-2a5c-11eb-9b26-4b7c586298b4.png)

Under Linux, dosemu2 also shows the correct output under mode 7 (obtained by entering "xmode -mode 7"). I don't have WPDOS 5.1 installed in my Linux setup, but here's an illustration of the correct WPDOS 6.2 output from dosemu2:

![Three](https://user-images.githubusercontent.com/5208505/99696601-dd1daf00-2a5c-11eb-9ebc-6b9ebb5a832a.png)

Under DOSBox-X, WPDOS 6.2 shows distorted output like the output shown in the first screenshot.

This bug has been present for decades, and I wouldn't know where to look to try to fix it. But now that ttf output is possible, DOSBox-X is extremely suitable to application software, and I hope this problem can be fixed.

**Comment by Wengier** [comment]
I think I have already fixed this. Check out the updated Windows binary:

http://cndos.fam.cx/dosware/dosbox-x-update.zip
