### ISSUE TITLE
Request: TTF support for 2nd VGA font bank in WordPerfect for DOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2011]
Now that Wengier has done heroic work in bringing TTF output to DOSBox-X, this additional TTF feature seems to be worth asking about.

WordPerfect for DOS includes support for a 512-character screen font that uses the optional second font bank in VGA hardware. This makes it possible to see accented characters, curly quotation marks, etc., on ordinary text screens, This feature works perfectly in DOSBox-X with bitmap fonts, because WP loads a set of bitmaps to display the second 256 characters. You can see this in action with WPDOS 5.1 by starting DOSBox-X in an 80x25 VGA screen, and pressing Shift-F1, Display, Colors/Fonts/Attributes, and choosing item 5 - 512 Characters, 8 Foreground Colors.

Then load the file CHARACTR.DOC (part of an ordinary WPDOS 5.1 installation) and scroll down to p. 11, where you will see many symbols not normally visible in VGA text.

To implement this feature for TTF output requires code that Wengier has already worked with and used in vDosPlus. This is a request to Jon to ask if you are willing to let Wengier include this code in DOSBox-X, where it will be useful to WordPerfect users who use TTF output. The feature already exists for all other outputs, and it would be good to have it working with TTF also.

**Comment by joncampbell123** [comment]
Sure, go ahead.

My only concern is that as far as I know the upper 256 of the 512-char mode do not have standard character assignments. If implemented, it would be WordPerfect-specific (maybe even specific to certain versions). I suggest adding a ttf option to control what the upper 256 are assumed to be i.e. ttf.char512=wordperfect to enable that.

**Comment by emendelson** [comment]
That's exactly right. WP has specific character assignments (slightly different in 5.1 and 6.x) and they're part of the code that Wengier works with. WP uses VGA-specific files that spell out which WP characters to use, and these can be mapped to unicode by reading the file.

**Comment by Wengier** [comment]
Thanks @joncampbell123. I have added a ttf.char512 option which when set to true will use the word processor as specified by the ttf.wp config option (you can specify something like WP, WP5, WP6 for WordPerfect) in my pull request.

@emendelson I have already implemented 512-character font for WordPerfect in my pull request. Set something like ttf.wp=wp and ttf.char512=true to use it.

**Comment by emendelson** [comment]
@Wengier - 512-character font works perfectly in WP. Thank you!

One other WP issue, and I don't know if it's related to attributes. When I start either WP 5.1 or 6.x the screen has horizontal lines across it, as shown; it seems to be WP's "strikeout" attribute. I don't know if this is worth fixing (or even if it's possible to fix it), as it doesn't affect any actual interaction with the program:

![Capture](https://user-images.githubusercontent.com/5208505/99830702-13762f80-2b2c-11eb-86a5-52637eeb6bbf.PNG)

**Comment by Wengier** [comment]
@emendelson I think it can be easily fixed by making "strikeout" attribute turned off by default while allowing you to enable it from the menu. I will submit the new code shortly.

**Comment by Wengier** [comment]
@emendelson There is now a ttf.strikeout option which defaults to false, but you can toggle it dynamically from the menu "Video" => "Text-mode". Please check it out the updated Windows binary:

* [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

**Comment by emendelson** [comment]
@Wengier - This now works perfectly. Thank you.
