### ISSUE TITLE
Current code won't build in VS2019

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2017]
Current code (https://github.com/joncampbell123/dosbox-x/commit/b54dcd0af9d1d5228342f8da8773d5afe12a493d) produces this error in VS2019:

10>C:\Users\Edward\Desktop\dosbox-x-master\src\ints\mouse.cpp(798,24): error C2678: binary '&': no operator found which takes a left-hand operand of type 'ttf_cell' (or there is no acceptable conversion)

**Comment by joncampbell123** [comment]
The TTF code was recently changed to an array of struct rather than an array of uint32_t that needs unpacking/bit shifting, in order to clean up the code. I have only so far developed and tested the code on Linux, that case is Windows only.

**Comment by emendelson** [comment]
OK - I'll wait! I hope maybe @Wengier might also be able to look into this.

**Comment by Wengier** [comment]
@emendelson Have you tried the current code? It seems to build in VS2019 fine here. I was aware that the code with commit c02499638a1c3f8fc1302af6a396c6298acaaca4 did not build in VS2019 indeed, but the new fixed code should build.

@joncampbell123 That part of code is for both Windows *and* SDL2 version of non-Windows platforms, so you can test that code with Linux SDL2 build too.

**Comment by emendelson** [comment]
@Wengier - Current code builds perfectly. Thank you!
