### ISSUE TITLE
Mapping a WASD-like layout on joystick does not allow movement on 2 axes

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#202]
Example: while mapping `W, A, S, D` keys on the left thumb stick of a joystick using the mapper works, usage within DOSBox doesn't. You can either move horizontally or vertically, a diagonal movement will only trigger either `W` or `A` and so on.

Note: such movement does work when using the keyboard.

Is this something that could be addressed in the future ?

Thank you.

**Comment by joncampbell123** [comment]
It may be the joystick code inherited from DOSBox expects the joystick input to be a range of values instead of keyboard events, and the two don't match up.

But I agree, being able to map WASD would be an excellent way to emulate a digital gamepad connected to the joystick port.

**Comment by aybe** [comment]
I think I've nailed it :D

In the following lines there is a hard-coded value of `25000` :

https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/sdl_mapper.cpp#L143
https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/sdl_mapper.cpp#L228
https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/sdl_mapper.cpp#L771

I've replaced this by something like `#define JOY_THRESHOLD (25000/4)` and it does work, I can move and strafe simultaneously.

Obviously, now when moving the thumb-stick it will raise a key event sensibly earlier ... also this is an aggressive value and should be further tweaked.

Let me know if you don't see anything wrong with this approach and I will push a commit.

**Comment by joncampbell123** [comment]
Sounds like a good approach to me. I think it might be even more useful if it were made a configuration option for fine-tuning, at least for now.

**Comment by aybe** [comment]
Yes that's what I was thinking, going to look at that ...

And further tune the threshold but it's rather weird, I tried the following for a [circular deadzone](https://msdn.microsoft.com/en-us/library/windows/desktop/ee417001(v=vs.85).aspx#dead_zone) but I need to go much lower than ~23000 for it to work:

```
magnitude = sqrt(32767*32767 + 32767*32767) = 46340
maxExtent = 32767 / magnitude = 0.707
threshold = 32767 * maxExtent = 23170
```

For the configuration I was thinking something like:

```
[joystick]
deadzone1=24000
...
deadzone8=24000
```

etc ... probably easier and less error-prone than deadzones=24000,24000,24000 ...

I'll take a look and see if I can hook to this in the least intrusive way :dart:

**Comment by joncampbell123** [comment]
I'm going to be busy with my work for awhile, and some video production. Would you @aybe like collaborator access to the repo?

**Comment by aybe** [comment]
I'm kind of busy too but yes, why not :D I'd address this issue and maybe a few others, why OpenGL fails here + shaders and I was wondering if mouse could be emulated by the mapper through a joystick.

Note: I am using Windows so regarding Linux at some point I'll see if I can get the thing to compile and test over !

**Comment by aybe** [comment]
@joncampbell123 

Just a quick ping to let you know what's up : I've got deadzone working for the mapper along config properties, works well. I've also baked circular deadzone for DOS joysticks and tune-able response (cubic interpolation etc ...); will push that soon.

**Comment by aybe** [comment]
Okay done, https://github.com/joncampbell123/dosbox-x/commits/joystick

Do not forget updated doc:
https://github.com/joncampbell123/dosbox-x/blob/joystick/README.joystick

Let me know if all is okay,

**Comment by aybe** [comment]
pretty happy with joystick content branch, it only needs to be merged now
