### ISSUE TITLE
TTF more than 25 lines, and high-res graphic modes: WordPerfect mouse won't move out of 25-line screen area.

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2020]
This is part of a long-standing DOSBox problem that I hope can be solved in DOSBox-X.

With the new TTF option, you can create a 43-line window (and other sizes) larger than the standard VGA text screen.

In WordPerfect for DOS 6.x, when you use a 43-line mode, with the mouse does not move below the 25th line. To see the problem, first enable the mouse in WPDOS 6.x under DOSBox-X. Use Shift-F1, Mouse, Type, and select "Mouse Driver (Absolute/Pen 2)."

Then, open or create a document in WPDOS that extends more than 25 lines in the window. The mouse cursor will not move below the 25th line.

Also, in WordPerfect for DOS 6.x, you can choose a VESA graphic driver with resolutions up to 1024x768. (Use Shift-F1/Display/Graphic Mode Screen Type; select VESA VBE and choose a high-resolution driver). You can then switch to the high-resolution graphic editing mode, with Ctrl-F3, Graphics (or Page).

When you try to edit a WP document in graphics mode, the WPDOS mouse pointer will not move out of a region in the upper-left corner measuring (I think) 640x400 (or maybe 480?).

Could there be a change in mouse.cpp (I think) so that the maximum x and y value for the mouse matches the actual maximum x and y of the window? Or matches the current video mode?

Also, with SDL1 only, I think, there's another longstanding DOSBox bug that occurs when switching modes in WPDOS 6.x: When you press Ctrl-F3, and then G, or P to switch to either Graphic or Page modes, the character that you type (G or P) gets repeatedly typed into the document until you hit the backspace key to stop it. But perhaps that calls for a separate issue report.

Steps to reproduce are indicated above. Thanks for any help with this.

**Comment by Wengier** [comment]
I can reproduce the mouse pointer issue (mouse pointer will not move out of a region in the upper-left corner) when I select "Mouse Driver (Absolute/Pen 2)", but the issue does not seem to occur when I select "Mouse Driver (MOUSE.COM)". Why not try this driver then? The mouse cursor seems to be able to move below the 25th line.

**Comment by emendelson** [comment]
With "Mouse Driver (MOUSE.COM)" I don't see a mouse cursor in WP 6.2 at all. Also in WP 6.1 - there's no mouse cursor with "Mouse Driver (MOUSE.COM)." That's why I used "Mouse Driver (Absolute Pen/2)". I'm very puzzled that you see a mouse cursor with the MOUSE.COM driver.

**Comment by Wengier** [comment]
@emendelson Glad to hear it now works. As for "g" or "p", I think it can be overcome by using the mouse though.

**Comment by emendelson** [comment]
@Wengier - Yes, but the WP users I work with can't be expected to remember to use the mouse (which they mostly don't use anyway) to select a menu item. Is there any chance that any keystroke in the keyboard buffer could be cleared when switching video modes? My (uninformed) guess is that this would solve the problem without any downsides.

**Comment by Wengier** [comment]
@emendelson I think I have already fixed the "g" or "p" issue in my latest PR.

**Comment by emendelson** [comment]
@Wengier Yes, the "g" or "p" issue is finally fixed with the Keyboard_clear function in the new code. Thank you!
