### ISSUE TITLE
TTF horizontal line problem with Consola font

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2021]
With TTF output, and the text font set to Consola, the bottom horizontal single and double lines appear a few pixels above where they should be. See, for example, the welcome screen:

![Capture](https://user-images.githubusercontent.com/5208505/99917596-40b70f00-2cdf-11eb-9fb6-4a5f4303b667.PNG)

Notice that the horizontal double line doesn't line up with the right-angle characters at the left and right. This doesn't occur with the line at the top of the welcome screen, and doesn't occur with the default font. The same problem occurs with single lines at the bottom of dialog boxes, for example:

![Capture](https://user-images.githubusercontent.com/5208505/99917639-8ecc1280-2cdf-11eb-9b57-5a5c62cb57da.PNG)

**Comment by Wengier** [comment]
I think this is really specific to the Consola font. With the Lucon font I get the following:

![image](https://user-images.githubusercontent.com/8216923/99921230-0194b800-2cf7-11eb-8326-2febe5978380.png)

And with the Nouveau_IBM font:

![image](https://user-images.githubusercontent.com/8216923/99921192-c7c3b180-2cf6-11eb-8659-ef32f03ccbe1.png)

Apparently different TTF fonts have different appearance.

**Comment by emendelson** [comment]
Yes, it's very strange. It doesn't occur in vDos/Plus, only with DOSBox-X. Not a serious problem...

**Comment by Wengier** [comment]
I checked it and believe the issue the Consola font is with the merged sdl_ttf.c file, which can be fixed.

**Comment by Wengier** [comment]
@emendelson I think I have already fixed this in my latest PR.

**Comment by emendelson** [comment]
@Wengier - Fixed now. Thank you!
