### ISSUE TITLE
sdl_ttf.c and SDL_video.h (for SDL1) not included in VS2015 project

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2023]
The SDL1 SDL_video.h include file is not included in the VS2015 project; the SDL2 version of the same file is included. Could both be part of the project? I sometimes experiment with the settings (for example, making the DOSBox-X window non-resizable) and it would be good to be able to access both files easily.

**Comment by emendelson** [comment]
Also, the sdl_ttf.c file is not included in the project.

**Comment by Wengier** [comment]
@emendelson The SDL1 SDL_video.h file can be found at vs2015\sdl\include, and sdl_ttf.c file can be found at src\gui. You can just add a line like ```#include "SDL_video.h``` to include the file that you need to use.

**Comment by emendelson** [comment]
@Wengier - Yes, I understand that, but I'm asking about something different, which is whether the files appear in the Solution Explorer in the sidebar of Visual Studio. The reason it helps to have those files included in the VS2015 project is so that, when the project is open in Visual Studio, a Find search will locate strings in those files. Otherwise, you can't find the strings you're looking for in those files. As far as I can see, there's no reason to have the SDL_video.h file included for SDL2 but NOT for SDL1.

**Comment by Wengier** [comment]
@emendelson Are you sure that SDL_video.h file is included in the repository's VS2015 project file for SDL2? I cannot find it in either [dosbox-x.vcxproj](https://github.com/joncampbell123/dosbox-x/blob/master/vs2015/dosbox-x.vcxproj) or [dosbox-x.vcxproj.filters](https://github.com/joncampbell123/dosbox-x/blob/master/vs2015/dosbox-x.vcxproj.filters). I don't think it is included for either SDL1 or SDL2. But if you want, you can of course add them very easily.

**Comment by emendelson** [comment]
@Wengier Actually, I was wrong - both versions of SDL_video.h are in the VS2015 solution - they are listed under External Dependencies. I was mistaken about this - I was looking in the wrong place.

Also, I was wrong to suggest that sdl_ttf.c should be included in the solution. If it is included, the project won't build because it finds duplicate definitions.

Apologies to everyone for wasting your time!
