### ISSUE TITLE
Request: Add Increase/Decrease TTF font size to Windows SDL1 system menu

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2027]
The Windows SDL1 system menu already includes "Pause" and other features that (without the menu) might not be immediately obvious to the user, especially if the main DOSBox-X menu is turned off. Is it possible to add Increase TTF font size and Decrease TTF font size to the system menu (if output = ttf)? This would be helpful to anyone who doesn't remember Win+F11/F12 or doesn't know where to find it on the menu - and most people who use word-processors and similar applications would be glad to have it, I think.

EDIT: As I guessed, it was easy to add this feature to the menu, and I hope it might be built into standard code.

**Comment by Wengier** [comment]
I have made some cleanups to the Windows SDL1 system menu. It now appears in Windows SDL2 builds too, and the items as you requested are added too. Please check it out.

**Comment by kalgon** [comment]
I don't know if this is related to that change but I have the following error when building:
```
sdlmain.cpp:5086:24: error: ‘TTF_IncreaseSize’ was not declared in this scope
 5086 |     MAPPER_AddHandler(&TTF_IncreaseSize, MK_uparrow, MMODHOST, "ttf_incsize", "Increase TTF size", &item);
      |                        ^~~~~~~~~~~~~~~~
sdlmain.cpp:5089:24: error: ‘TTF_DecreaseSize’ was not declared in this scope
 5089 |     MAPPER_AddHandler(&TTF_DecreaseSize, MK_downarrow, MMODHOST, "ttf_decsize", "Decrease TTF size", &item);
      |                        ^~~~~~~~~~~~~~~~
```

**Comment by emendelson** [comment]
@Wengier - I downloaded the code from your fork (and I think that the main code is now identical) and combined it with my changes, and all these things work perfectly. Thank you.

I hope you don't mind one more request: is it possible to make the system menu display the current keystrokes for Increase/Decrease TTF font size, etc., in the same way that the DOSBox-X menubar displays those keystrokes? That would help users learn the keystrokes without searching for them in the menubar. Thank you again for this superb work.

**Comment by Wengier** [comment]
@emendelson I have already made the system menu to display the current keystrokes for various functions in my PR. Please check it out.

**Comment by emendelson** [comment]
@Wengier This works perfectly now; thank you!
