### ISSUE TITLE
TTF output not working in macOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2033]
I've built the latest code under Mojave in macOS, but TTF output doesn't seem to work. I have output=ttf, and config -get sdl returns output=ttf, but the text font is the standard vga bitmap font.

Is this by design, or is it possible to make TTF output work on a Mac in addition to Linux?

**Comment by Wengier** [comment]
@emendelson TTF output requires the FreeType library. Please make sure that the FreeType library is installed on your Mac. You can verify it in the config.h file by checking if there if the following line exists:

```
#define C_FREETYPE 1
```

If there is no such line, selecting the TTF output will fallback to the default one. Try both SDL1 and SDL2 builds with FreeType enabled and see if they work.

**Comment by Wengier** [comment]
I made some further fixes for the TTF output on macOS. Please check out the code in my PR. Still, make sure the FreeType library is enabled on the Mac.

**Comment by emendelson** [comment]
@Wengier I downloaded the latest code, which has `#define C_FREETYPE 1` in config.h, and compiled under macOS Mojave. Clearly I don't have a FreeType library installed, because even with a dosbox-x.conf file that has `output=ttf`, the output setting displays as "default."

What I hope to do is create a DOSBox-X application that can be distributed to other users and that uses TrueType. It seems likely that vDosPlus/vDos will never work smoothly under Wine in current versions of macOS, so DOSBox-X is the only practical DOS emulator for use with DOS applications on a Mac. 

Two questions: 

1. If I installed a FreeType library on my Mac, and then compiled DOSBox-X, would the resulting executable use TTF on someone else's system? (I don't know how to install FreeType on my Mac, and I don't use Brew, etc., because I want to be confident that when I compile something, it will be usable on other people's systems.)

2. If not, is it possible to enhance DOSBox-X so that TrueType will be available for users who do not have a FreeType library installed?

**Comment by emendelson** [comment]
Follow-up. I installed the FreeType library in Mojave in /usr/local, and built DOSBox-X - and it displayed TrueType correctly. I copied the executable to a system running Catalina, but, as expected, it failed because it couldn't find libfreetype.6.dylib.

So I deleted everything in /usr/local that had "freetype" in its name, and put a copy of libfreetype.6.dylib into the same folder with the dosbox-x executable. TrueType displayed correctly. But when I copied these two files to a Catalina system, I got the same error message about not finding the dylib.

Is there some easy way to make this work correctly across different systems?

**Comment by joncampbell123** [comment]
If you look in Makefile.am, the "dosbox-x.app" build step, there's at least an attempt to locate certain dependencies and copy them into the .app bundle.

Back when I wrote it, it was needed for the .app to support the FFMPEG libraries (for MPEG-TS capture) even on systems that didn't have it.

**Comment by emendelson** [comment]
@joncampbell123 Unfortunately, it doesn't help to copy the dylb into the same folder with the executable. I tried this on a second Mojave system, and again got an error message. 

Would it be possible to build in the freetype library from the VS2015 folder?

**Comment by joncampbell123** [comment]
Probably.

My plan is to modify configure.ac so that, if an external FreeType library is not available, it will use the internal one, and a way to specify using the internal one anyway.

**Comment by emendelson** [comment]
@joncampbell123 That would be terrific. Incidentally, when I installed the FreeType library and compiled, the TTF output was really beautiful to see. The font rendering was superb.

**Comment by joncampbell123** [comment]
@emendelson I just did that in the latest commit. The internal FreeType library is compiled as static and linked into the binary on Mac OS X now, SDL1 and SDL2.

**Comment by emendelson** [comment]
@joncampbell123 - Yes! I just built on Mojave, copied the executable to a Catalina system, and it worked perfectly. Thank you! Closing this.
