### ISSUE TITLE
macOS: output=ttf and fastbioslogo=true locks up DOSBox-X on launch

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2036]
With current code on macOS (built under Mojave), this conf file causes DOSBox-X to lock up on launch:

```
[sdl]
output=ttf

[dosbox]
fastbioslogo = true
```

Either entry alone causes no problem; the lockup occurs only with both.

**Comment by emendelson** [comment]
This occurs only with SDL1. I wonder if Wengier's new PR will fix it in SDL1...

**Comment by Wengier** [comment]
@emendelson I certainly think so since it was designed to improve TTF support on macOS SDL1. Have you tried the current code already?

**Comment by emendelson** [comment]
@Wengier Yes, this works now with macOS SDL1. Thank you!
