### ISSUE TITLE
Question: macOS, where to put consola.ttf so conf file can find it?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2037]
Under macOS, with ttf output, I can specify `ttf.font=consola` in the conf file and, DOSBox-X will load the consola.ttf file in my home folder.

For my own application, which launches the dosbox-x executable (not the full app, just the unix executable) with a conf file specified on the command line, I want to include the consola.ttf file inside the application, but I can't figure out where to put it. I've tried every possible location, with no success. I can make the font load if i specify the full path, but the full path will differ depending on the the location of the application. 

Is there a default location where the executable will look for a TTF file, or could one be added to the code so that it would be easy to load this on a Mac?

**Comment by Wengier** [comment]
@emendelson How did you specify the config file on the command line?

Assume the config file is located in the /test directory with the name dosbox-x.conf, then you can launch the dosbox-x executable with the config file as follows:

```
dosbox-x -defaultdir /test
```

If the config file is with a different name (e.g. myconfig.conf) in this directory, then you can launch the dosbox-x exeutable with the config file as follows:

```
dosbox-x- -defaultdir /test -conf myconfig.conf
```

The path as specified by the "-defaultdir" option (/test in this case) will become the default working path for DOSBox-X. You can put other files needed by DOSBox-X such as consola.ttf in this directory too. Hope this helps.

**Comment by emendelson** [comment]
@Wengier - The `-defaultdir` option was exactly what I needed. I use a shell command in an AppleScript application to launch the executable, and that directory is a variable created by the AppleScript. All I needed to do was revise the shell command, and I was able to load the TTF  file. Thank you!
