### ISSUE TITLE
Allow mapper file to be found in DOSBox-X executable directory?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2040]
@Wengier recently made things easier by letting DOSBox-X find a TTF file in the same directory as the executable. Could this also apply to the mapperfile filename specified in the conf file? (I think I have to specify the path of that file if defaultdir is not the same as the folder with the executable, but I could be wrong...)

**Comment by Wengier** [comment]
@emendelson I have already fixed this in my PR, along with clipboard pasting for macOS SDL1 builds which should now work.

**Comment by emendelson** [comment]
Thank you!
