### ISSUE TITLE
macOS: WPDOS 6.2 crashes when switching from TTF to graphic mode

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2042]
Current code, built in macOS Mojave; running with a conf file containing only `[sdl] output=ttf`

Run WPDOS 6.2, use Shift-F1, Display, and set the graphic screen type to any VESA graphic mode. Then press Shift-F7, Print Preview, and DOSBox-X crashes, with this log:

```
LOG: Screen report: Method 'CoreGraphics' (1440.000 x 900.000 pixels) at (0.000 x 0.000) (285.750 x 178.594 mm) (11.250 x 7.031 in) (128.000 x 128.000 DPI)
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (1440.000 x 900.000 pixels) at (0.000 x 0.000) (285.750 x 178.594 mm) (11.250 x 7.031 in) (128.000 x 128.000 DPI)
LOG:  236899762 ERROR MOUSE:Unhandled videomode 69 on reset
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (1440.000 x 900.000 pixels) at (0.000 x 0.000) (285.750 x 178.594 mm) (11.250 x 7.031 in) (128.000 x 128.000 DPI)
LOG: Screen report: Method 'CoreGraphics' (1440.000 x 900.000 pixels) at (0.000 x 0.000) (285.750 x 178.594 mm) (11.250 x 7.031 in) (128.000 x 128.000 DPI)
Segmentation fault: 11
```

This does not occur with WPDOS 5.1, and does not occur in 6.x with standard VGA graphics. This is only in macOS, not Windows.

EDIT: This occurs with an SDL1 build; I'm now building SDL2 and will test again.

**Comment by Wengier** [comment]
@emendelson Can you try set ```ttf.outputswitch=surface``` and see if it works for you?

**Comment by emendelson** [comment]
@Wengier - Yes, that fixes it. Thank you! I should have remembered this from an earlier post. (Switching from text mode to graphic is very slow in 6.2 but faster the second time I make the same switch between modes.)

**Comment by Wengier** [comment]
@emendelson With the current code I think you can use the default ttf.outputswitch too for switching from the text mode to graphical mode, not just ttf.outputswitch=surface.
