### ISSUE TITLE
Request: single mapper file with maps for both SDL1 and SDL2

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2045]
For next month's version (and I know this is a minor issue):

The current version requires different mapper files for SDL1 and SDL2 builds. Is there any hope that a single file can be used instead, with separate sections headed [SDL1] and [SDL2] or something similar? This is the basic method used by the SheepShaver/BasiliskII Mac emulators, which have a single mapper file for all platforms, divided into sections.

I understand that the conf file already has an option for the SDL2 mapper, but maintenance might be easier if a single file could be used instead.

EDIT: Even better, since the project uses its own SDL versions, would it be possible to adjust the key numbers in the project's SDL1 code so that a single mapper file could be used for both SDL1 and SDL2?

**Comment by Wengier** [comment]
I have already added support for a unified mapper file for both SDL1 and SDL2 versions in my PR for the mapperfile config option. SDL-version-specific mapper files can still be specified with the mapperfile option, or they can be specified with the mapper_file_sdl1 or mapper_file_sdl2 config options. In the latter case, the mapper file will only apply to the specific SDL version, overriding the mapperfile config option.

You can download the latest Windows binary from:

http://cndos.fam.cx/dosware/dosbox-x-update.zip
