### ISSUE TITLE
Thank you for temporary hold fix!

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2047]
@joncampbell123 - Thank you for the fix for Ctrl-Alt in the latest code. I was wondering why I seemed to have press some keys twice to get results, and wasn't sure that I was seeing something real. Sorry for wasting bandwidth on an issue, but  I couldn't see any other easy way to get in touch.

**Comment by joncampbell123** [comment]
The "hold" modifier in DOSBox-X means that pressing the key toggles whether it's down (releasing has no effect). Like a toggle switch. It shares the same name as "hold" in DOSBox SVN that, as far as I know, wasn't really implemented to do anything.

Does CTRL+ALT work as expected in the latest code?

I will be starting the big end of month build at 6 PM tonight PST.

**Comment by emendelson** [comment]
Yes, it seems to work here perfectly. Thank you again (and I think there are still six minutes left before you start the build...).
