### ISSUE TITLE
Caps, Num and Scroll Lock

### ISSUE THREAD

**Issue by knifour** [joncampbell123/dosbox-x#205]
Is it passable that DOSBox has it own Caps Lock status?

**Comment by aybe** [comment]
Please describe clearly the behavior you are asking for.

**Comment by knifour** [comment]
When DOSBox without focus, press Caps Lock DOSBox will not change Caps Lock status, when DOSBox have focus, press Caps Lock will only chage DOSBox's caps lock status.

When DOSBox got focus or lost focus, DOSBox will change the keyboard led light on/off correspond by itself Caps Lock status(Num Lock and Scroll Lock are the same).

Sorry for my poor english.

**Comment by aybe** [comment]
So you're asking that DOSBox has independent caps lock/num lock/scroll lock from system ? If yes then [it is already the case](https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/sdlmain.cpp#L1247), just checked right now on Windows dev and it works.

There's a trick however for it to work, mouse must be captured by DOSBox and in the current release only Ctrl-F10 does work, not the mouse button. [In the latest dev version](https://github.com/joncampbell123/dosbox-x/files/249928/dosbox-x.pdf) (rename to .zip and decompress) mouse can be captured with a click but obviously you will still need Ctrl-F10 to release it.

Ideally there should be a VMware-like auto mouse capture when windowed but it hasn't happened yet :D

**Comment by knifour** [comment]
I see, thank you very much.
