### ISSUE TITLE
undefined reference to xbrz::scale

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#2052]
**Describe the bug**
The build has been broken on Linux since the new version was started. Here is the error:

```
/usr/bin/ld: output/liboutput.a(output_tools_xbrz.o): in function `xBRZ_Render(unsigned int const*, unsigned int*, unsigned short const*, int, int, int)':
/home/robert/git/github/dosbox-x/src/output/output_tools_xbrz.cpp:134: undefined reference to `xbrz::scale(unsigned long, unsigned int const*, unsigned int*, int, int, xbrz::ColorFormat, xbrz::ScalerCfg const&, int, int)'
/usr/bin/ld: /home/robert/git/github/dosbox-x/src/output/output_tools_xbrz.cpp:141: undefined reference to `xbrz::scale(unsigned long, unsigned int const*, unsigned int*, int, int, xbrz::ColorFormat, xbrz::ScalerCfg const&, int, int)'
collect2: error: ld returned 1 exit status

**Comment by Wengier** [comment]
I have not yet encountered this issue so far. Did you see the problem in both Linux SDL1 and SDL2 builds, or only one of them? Perhaps you can clean the source and try again and see if it happens?

**Comment by rderooy** [comment]
Yes, both SDL1 and SDL2 are effected by this. But since you did not see the problem, I ran cleantree and then the builds succeeded. So I guess it was some leftover junk in my tree.
