### ISSUE TITLE
DOSBox-X + HXDOS无法执行QuickJS, 但实机可以

### ISSUE THREAD

**Issue by hlizard** [joncampbell123/dosbox-x#2054]
我使用i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z编译的QuickJS可以在实机和qemu下用HXDOS启动执行, 没有报错, 但在DOSBox-X下用HXDOS启动后执行语句(hxldr32, 然后执行qjs.exe, 然后输入1+2回车)就异常终止了, 不知道问题出在哪, 下面是报错截图:
![image](https://user-images.githubusercontent.com/6994037/100960370-1412bb00-355b-11eb-8fd3-ca5685137817.png)

如果要测试这是我编译的qjs(需要使用https://github.com/mcmilk/7-Zip-zstd/来解压我的.7z): https://github.com/hlizard/QuickJS-Windows-Build/blob/2020-09-06/QuickJS-Windows-Build.7z

下面是我测试时使用的软件版本:
HXDOS-extender (2.17+)
dosbox-x-mingw-win32-20201130195816.zip
dosbox-staging-windows-x86-v0.75.2.zip
Windows 10 20H2

另外, 我发现DOSBox-X的配置文件[autoexec]节不像实机那样支持%开头的语句, 好像被当作注释跳过了:
![image](https://user-images.githubusercontent.com/6994037/100961118-b1222380-355c-11eb-90e0-6e55f63b16e9.png)

**Comment by joncampbell123** [comment]
Hello @hlizard. This project is conducted primarily in English. It's possible what you are trying to run in HX-DOS needs more memory. Try increasing the total memory available to the guest. HX-DOS and Win32 apps within do not handle out of memory conditions very well.

**Comment by Wengier** [comment]
As @joncampbell123 said, please try to write messages in English whenever possible.

I have tried your QJS.exe program in both HX DOS Extender 2.17+ and HX DOS Extender 2.18 in DOSBox-X. Enter "1+2" will cause issues in both, but the result is not exactly the same. In the case of HX DOS Extender 2.18, the result is the following: 

![image](https://user-images.githubusercontent.com/8216923/100965268-5ce55800-34f8-11eb-8d0f-5ccb4ad3be94.png)

So there is indeed some bug here. On the other hand, if I run it with HX DOS Extender 2.17, I will get the crash screen as you posted.

By the way, It is not recommended to use HX DOS Extender 2.17+ any more unless you really want AC97 support, because it is apparently no long being developed, and it is not always stable.

Also, you are right that lines starting with % in [autoexec] section are ignored, which is not correct in this case and I will fix it. But for now you can workaround it by changing ```%appd%``` to ```call %appd%```.

Hope this helps.

**Comment by hlizard** [comment]
Sorry, I will try to use English later. I use Chinese because I guess Wengier can understand.

It seems that this problem may come from quickjs windows port itself. I also have some strange extra characters when I execute it on windows, but it doesn't crash.

I'll close this temporarily until quickjs works on windows, and then test it with the latest version of HXDOS.


This English is based on software translation, if not authentic, please understand.

**Comment by hlizard** [comment]
I found the cause of the problem and temporarily fixed it, but now there is a more peculiar phenomenon. The arithmetic result under dosbox-x is wrong. For comparison, QEMU is on the right
![image](https://user-images.githubusercontent.com/6994037/100976673-d6258f00-357a-11eb-8682-052d5f84dcb3.png)


This is my monkey patch (based on quickjs 2020-11-08)
![image](https://user-images.githubusercontent.com/6994037/100977023-551ac780-357b-11eb-8963-491702b8ea26.png)

**Comment by Wengier** [comment]
@hlizard I have already fixed the issue for lines starting with % being ignored in my PR. I will check the arithmetic issue you just mentioned too.

**Comment by hlizard** [comment]
If you want binary files (extracted with 7-Zip-zstd), https://github.com/hlizard/QuickJS/blob/d32/QuickJS.7z. If you want to compile quickjs under windows, you can take a look https://github.com/hlizard/QuickJS-Windows-Build/commit/98b612b1128b195b9210b2d2df35edb557ff4c21 , I use Git bash+cygwin+[i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download).

**Comment by grapeli** [comment]
@hlizard 
Linux QuickJS running under DOSBox-X seems to be working fine.
[quickjs.linux.zip](https://github.com/joncampbell123/dosbox-x/files/5635831/quickjs.linux.zip)

Unpack this zip, go to the quickjs directory and run linux.bat. Next.
root [Enter]
qjs [Enter]

**Comment by Wengier** [comment]
@grapeli I think qjs runs fine as you said, but typing ```1+2``` in its command-line does not return the correct result yet.

**Comment by Wengier** [comment]
@hlizard and @grapeli By doing further testing I noticed that the issue with the arithmetic result only occurs with the dynamic core (x86 or rec), but **not** the normal core. If you set core=normal then you should get the correct result:

![image](https://user-images.githubusercontent.com/8216923/101086193-8052e600-357e-11eb-80d3-367db61ca8e6.png)

**Comment by grapeli** [comment]
@Wengier 
The Linux version of QuickJS running under DOSBox-X with `core=dynamic_x86` produces this result:
```
~ # qjs --bignum /usr/share/quickjs/pi_bigfloat.js 25
3.1415926535897932384626433
```
Correct.

**Comment by joncampbell123** [comment]
This is a problem with floating point, then, correct?

The problem DOSBox-X inherits from DOSBox SVN is that VS2019 builds use the "double" floating point type to emulate FPU registers. You only get the full 80-bit precision with dynamic core.

MinGW, Linux, and GCC builds use the "long double" datatype to emulate FPU registers and should provide the full FPU precision.

This is caused by Microsoft's C++ compiler, which long ago (during the Win16 -> Win32 transition to Windows 95) decided not to support "long double", and just alias it to "double".

**Comment by Wengier** [comment]
@joncampbell123 I checked that the official MinGW and Linux Flatpak builds of DOSBox-X 0.83.8 encounter the exact same problem with ```core=dynamic``` (```core=normal``` will work fine) as the Visual Studio builds. I believe @grapeli is talking about the [quickjs.linux.zip](https://github.com/joncampbell123/dosbox-x/files/5635831/quickjs.linux.zip) Linux package he made, which is different from the official DOSBox-X Linux package.

**Comment by Wengier** [comment]
@joncampbell123 To make it easier for you to test, I have made a zip package which contains all required files to run QJS here.

* [qjs.zip](https://github.com/joncampbell123/dosbox-x/files/5639814/qjs.zip)

Type ```DPMILD32 QJS``` to run it.

**Comment by grapeli** [comment]
@Wengier 
This qjs.exe binary is built with the i686 toolchain?
`LOG: FPU WARNING: FPU_FUCOMI called, needs testing`
https://en.wikipedia.org/wiki/X86_instruction_listings#Added_with_Pentium_Pro_2

I compiled the Linux version under i486.

**Comment by Wengier** [comment]
@grapeli The included qjs.exe file is the exact same binary file that @hlizard posted, extracted with 7-Zip-zstd. I repackaged the qjs.exe file along with required HX DOS Extender files in zip to make it easier to be tested. The log message you posted may be the cause of the issue (@joncampbell123 is probably familiar with the FPU code).

**Comment by Wengier** [comment]
@hlizard Does it work for you now with core=normal and HX DOS Extender 2.18?

**Comment by grapeli** [comment]
@Wengier 
It partially works with `core=dynamic`.
`DPMILD32 QJS.EXE -e "x=1+2;console.log(x);"`
like this - incorrectly.
`DPMILD32 QJS.EXE -e "x=1/3;console.log(x);"`
Bignum uses [libbf](https://bellard.org/libbf/) and not the standard libm.
`DPMILD32 QJS.EXE -e --bignum -e "'use strict';var x;x=BigFloat(1/3);console.log(x);"`

**Comment by Wengier** [comment]
@grapeli Yes, console.log(x) seems to show the correct result for x=1+2, but x=1+2 itself shows 0.00000000000000000 for the dynamic core, and console.log(x) does not show the correct result for x=1/3 for the dynamic core.

On the other hand, if I switch to the normal core, everything seems to work fine.

**Comment by hlizard** [comment]
> @hlizard Does it work for you now with core=normal and HX DOS Extender 2.18?

Yes, normal core works(HX DOS Extender 2.19pre3)!  And tsc.exe(TypeScript compiler generated by qjsc) also works on HX DOS. It's amazing!

**Comment by Wengier** [comment]
@hlizard Great to hear that it works for you!
