### ISSUE TITLE
Error message SUD409 when trying to install Windows 98

### ISSUE THREAD

**Issue by robinhood2014** [joncampbell123/dosbox-x#2059]
I'm trying to install Windows 98 in DOSBox-X. I'm just barely into the GUI part of the installation (executable is KRNL386.EXE) when I get a fatal error message with error number SUD409 relating to possible virus detection software. I am running Bitdefender on my host machine -- can that somehow interfere unintentionally with what I am trying to accomplish in this situation?

In case you need a screenshot of the error, here it is:
![krnl386_000](https://user-images.githubusercontent.com/6971466/101175469-d2d9e400-360a-11eb-9ada-4ca09a331b20.png)

**Comment by rderooy** [comment]
I have not seen this error in my testing. Are you following the win98 installation guide from the dosbox-x wiki?

**Comment by joncampbell123** [comment]
Also, make sure you do not install or run Windows 98 while using dynamic core.

**Comment by robinhood2014** [comment]
Stupid, stupid me... Following the guide to the letter, I've got it working. But I notice the sound is VERY choppy.
