### ISSUE TITLE
EF2000 crashes with general protection fault

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#206]
The game does not run at all in dosbox-x:

```
fault = 0D general protection fault
eip = F000C6AD    flg = 00003002    cs  = 002B        ss  = 0033
ds  = 0033        es  = 0033        fs  = 0000        gs  = 0000
eax = 00000000    ebx = 00000000    ecx = FFFFFFFF    edx = DFFFEC34
esi = 00017000    edi = 1015C004    ebp = 00000080    esp = DFFFEB30
stk = 00000033 00000067 00000000 DFFFEC30 0002DBE2 0E0D0D0D 0F0F0E0E
version 01.40 by Col
```

Note: game does work in regular DOSBox and Daum versions.

**Comment by joncampbell123** [comment]
Does it work if you first run LOADFIX?

**Comment by aybe** [comment]
Unfortunately, no :(

**Comment by joncampbell123** [comment]
Does the game require a 486 or higher? Try setting cputype=pentium.

One modification I made some time back was to make reading/writing CR4 cause a GPF on anything below a "new" 486 based on testing DOSLIB code against an old (1991-ish) 486.

**Comment by aybe** [comment]
Okay, actually it does run on Win64 build and without LOADFIX, so the crash is Win32-only :)

**Comment by joncampbell123** [comment]
The win32 build (as far as I know) defaults to core=dynamic. Does the game run normally with core=normal?

**Comment by aybe** [comment]
```cputype=pentium``` does nothing,

but with ```core=normal``` it works !!! though extremely slowly

**Comment by box-tortoise** [comment]
Does it work with core=dynamic on older versions of dosbox-x?

**Comment by aybe** [comment]
Found the issue,

Around [DOSBox v0.801 Windows 9x/ME friendly](https://github.com/joncampbell123/dosbox-x/releases/tag/v0.801) release the SB16 detection fails (in the past chronologically), after detection succeeds but game crashes.

So disabling sound in the game makes it work on any release I've tested, even current:

```
DOSBox-X-win32-d1f2b1c69f593f5de9979ec613fb6b08a8f35695.zip               
dosbox-x-windows-1266d4022804aac9e22a12fbd8ce7c660b38418a.zip             
dosbox-x-windows-201602190219.zip                                         
dosbox-x-windows-3586d3a779a66dea8c705e24faa0631fee469431                 
dosbox-x-windows-3586d3a779a66dea8c705e24faa0631fee469431.zip             
dosbox-x-windows-6ba2abd942920bc343f48dfb6f874971e15c20c4.zip             
DOSBox-X-windows-7159bc654b8e36b4899e7f1106d4048aa7650978.zip             
dosbox-x-windows-8c197997adf86e3d9bca7d7160800d0a49a7d580.zip             
dosbox-x-windows-dosbox-x-windows-v0.801.newyears.b3.zip                  
dosbox-x-windows-v0.801.gusandbootfixes.b4.zip                            
dosbox-x-windows-v0.801.next.b1.zip                                       
dosbox-x-windows-v0.801.zip                                               
```

**Comment by box-tortoise** [comment]
I wonder if any of these commits are relevant: https://github.com/joncampbell123/dosbox-x/commits/master/src/hardware/sblaster.cpp?page=3. May also test with non-sb16 emulated devices.

The above test suggests that the dynamic core is the cause, but it may be that the normal core bypasses the fault with its page fault handling code.

**Comment by aybe** [comment]
I really would like to help but this low-level DOS stuff is beyond me :(

Let's see if @joncampbell123 has an idea on this !

**Comment by aybe** [comment]
TODO add to FAQ and close

**Comment by joncampbell123** [comment]
Testing now, no problems so far.

The fix seems to be not to use dynamic core.

**Comment by joncampbell123** [comment]
No problems here.
