### ISSUE TITLE
Mapper ignores hostkey=ctrlalt

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2064]
In current SDL2 code, if I have `hostkey=ctrlalt` in the conf file, `config -get hostkey` shows `ctrlalt`, but the mapper says that hostkey is F11. Screens:

![Capture](https://user-images.githubusercontent.com/5208505/101217583-9da3b500-364f-11eb-9c4e-dd06af5e5024.PNG)
![Capture2](https://user-images.githubusercontent.com/5208505/101217587-a09ea580-364f-11eb-8abf-d84cdf3a06aa.PNG)

Am I missing something obvious?

**Comment by joncampbell123** [comment]
The alternate hostkey system as implemented works by bypassing normal mapper handling to directly handle those host key combinations, even though the mapper's internal data structures still say that F11 is the host key.

**Comment by Wengier** [comment]
@emendelson If you look at the "Select host key" menu group under "Main", you will find the following:

Ctrl+Alt
Ctrl+Shiift
Alt+Shift
Mapper defined: xxx (usually F11)

So if you select any of them except the last one (or setting from the config), then the mapper-defined host key will be ignored and the select host key will be used instead.

**Comment by emendelson** [comment]
Understood. But I think this has the potential to be confusing to users who thought they set the hostkey in the conf file, and see their choice confirmed with the `config` command. Perhaps it's worth some further thought?

**Comment by Wengier** [comment]
@emendelson The current comment for the hostkey config option says "Select a DOSBox-X host key, or use the mapper-defined host key (default: F11 on Windows and F12 otherwise)." Perhaps the comment can be expanded to further clarify this.

**Comment by Wengier** [comment]
With #2138, the Host key will no longer appear in the mapper when the alternative host key system is enabled.

**Comment by emendelson** [comment]
Thank you, @Wengier
