### ISSUE TITLE
Disable Alt-F4 closes app in SDL2?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2065]
In an SDL2 build, I was driving myself slightly crazy trying to apply a function to Ctrl-Alt-F4, because that key combination always closed DOSBox-X under Windows. In contrast, there is no problem assigning a function to Ctrl-Alt-F4 in SDL1.

Finally I remembered from years ago that this is controlled by the SDL hint, `SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4`. 

In the file vs2015\sdl2\src\video\windows\SDL_windowsevents.c, this hint is specified in line 357; if you change SDL_FALSE to SDL_TRUE, then Ctlr-Alt-F4 (or other combinations with Alt-F4) can be used as specified.

**Comment by Wengier** [comment]
@emendelson You are right it should be consistent between SDL1 and SDL2 builds in this case. I have already made the said change in my latest PR.

**Comment by emendelson** [comment]
@Wengier Fixed. Thank you!
