### ISSUE TITLE
SDL2, Windows, Toggle Menu key only turns menu on, not off

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2067]
In current code, testing with a Windows SDL2 build, with showmenu=false, F11, Esc shows the menu, but there seems to be no way to hide the menu. F11,Esc doesn't hide it when it's showing.

Also, with showmenu=true, F11, Esc doesn't hid the menu. 

Am I missing something obvious?

**Comment by Wengier** [comment]
There was indeed something missing for the toggle menu option in the Windows SDL2 build. I have already addressed this, and the menu option also appears in the system menu of the Windows SDL2 build too. You can download the updated Windows SDL2 binary here:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by emendelson** [comment]
@Wengier - Fixed! Thank you!
