### ISSUE TITLE
Error on line 9 of Z:\4DOS.INI

### ISSUE THREAD

**Issue by JoeC4281** [joncampbell123/dosbox-x#2075]
When I start Dosbox-x.exe with 4DOS as the command processor;
![image](https://user-images.githubusercontent.com/58880711/101486521-c6b39680-392a-11eb-9c5f-b6b13809314d.png)

This is the Z:\4DOS.INI file;
![image](https://user-images.githubusercontent.com/58880711/101486681-0ed2b900-392b-11eb-834e-b9bb21629e73.png)

This is my C:\4DOS directory;
![image](https://user-images.githubusercontent.com/58880711/101486825-3f1a5780-392b-11eb-8220-2a87ae58ae60.png)

In my .conf file, I have the following;
![image](https://user-images.githubusercontent.com/58880711/101486355-8522eb80-392a-11eb-87a9-a8ead8af33eb.png)

...and...

![image](https://user-images.githubusercontent.com/58880711/101486965-738e1380-392b-11eb-90a5-193b1fe20dc2.png)

**Environment (please complete the following information):**
 - Windows 10 [Version 10.0.18363.1198]
 - DOSBox-X 0.83.8 (SDL1, 64-bit)
 - Build Date Nov 30, 2020

Why do I get the *"Error on line 9 of Z:\4DOS.INI"*? I'm thinking it is because the *4startpath* is pointing to C:\4DOS, but C: has yet to be mounted, therefore, C:\4DOS does not exist yet.

Can this be remedied?

Joe

**Comment by JoeC4281** [comment]
My temporary fix is to copy my own 4DOS.INI file to **e:\dosbox-x\drivez**, and change 4StartPath=Z:\

Joe

**Comment by JoeC4281** [comment]
...or I could just change the 4StartPath=Z:\ in the [4dos] section of the .conf file.

Joe

**Comment by Wengier** [comment]
@JoeC4281 Yes, the reason for the error is indeed that the C: drive is not yet mounted at the time when 4DOS is started. But it can be easily solved though, by loading MOUNT command via INSTALL option in [config] section (instead of doing so in [autoexec] section), e.g. 

```
[config]
...
INSTALL=MOUNT.COM C C:\
```

And then 4DOS should be able to see the C: drive when it starts. Hope this helps.

**Comment by JoeC4281** [comment]
Thanks Wengier, that works!

Joe

**Comment by JoeC4281** [comment]
Hi @Wengier ;
On my Windows 10 [Version 10.0.19042.985] system, I just did a GIT PULL, and have compiled using VS 2019 16.9.5 the 32-bit DOSBOX-X.EXE to version 0.83.14 (SDL1, 32-bit).

DosBox-x.exe launches, and then closes.

The problem was that **mount.com** is no longer in the Z:\ folder. It is now in the z:\system folder. So, I fixed that in my .conf file;

`install     = z:\system\mount.com C e:\dosbox`

Now, DosBox-x.exe launches, and leaves me at the Z:\ prompt.

That is, my [autoexec] is no longer executed, as the drives in my [autoexec] are no longer mounted, and my 4Dos prompt is not placed at the C:\Utils folder.

```
[config]
rem         = This section is DOS's CONFIG.SYS file, not all CONFIG.SYS options supported
break       = off
numlock     = 
shell       = 4DOS.COM
dos         = high, umb
fcbs        = 100
files       = 127
country     = 1
lastdrive   = a
set path    = Z:\system;c:\utils;c:\office30;c:\4dos
set prompt  = $P$G
set temp    = c:\temp
install     = z:\system\mount.com C e:\dosbox
installhigh = 
device      = 
devicehigh  = 
SET WIN_SystemRoot=%SystemRoot%
SET WIN_COMSPEC=COMSPEC: %COMSPEC%

[autoexec]
mount u: e:\utils
mount r: r:\
C:
cd \utils

```

Please advise, and thanks.

Joe

**Comment by Wengier** [comment]
@JoeC4281 The 4DOS.COM is located at Z:\DOS\4DOS.COM. The only change you need to make is the following:

From:
`set path = Z:\system;c:\utils;c:\office30;c:\4dos`

To:

`set path = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL;c:\utils;c:\office30;c:\4dos`

With this you can keep `install = mount.com C e:\dosbox` as is (no need to specifically point to z:\system\mount.com).

Not that with the default setting of `set path = Z:\` DOSBox-X will automatically expand it to `set path = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL`, but not in the case of customized path like yours.

Hope this helps.

**Comment by JoeC4281** [comment]
Hey @Wengier ,
That fixes the [config.sys] part, but [autoexec] still is not executed, as I am still placed at the Z:\ 4dos prompt.

```
Z>path
PATH=Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL;c:\utils;c:\office30;c:\4dos

Z>ver

4DOS 8.00   MS-DOS 7.10

Z>
```
I can run the autoexec.bat manually;
```
Z>AUTOEXEC.BAT
mount u: e:\utils
Drive U is mounted as local directory e:\utils\
mount r: r:\
Drive R is mounted as local directory r:\
C:
cd \utils

```
Please advise, and thanks.

Joe

**Comment by Wengier** [comment]
@JoeC4281 Please check out the updated DOSBox-X binary, which should allow the [autoexec] section to be executed in this case：

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Hope this helps.

**Comment by JoeC4281** [comment]
Hey @Wengier ,
Thanks, that works.

Joe
