### ISSUE TITLE
Really Bizarre Filesystem Issue

### ISSUE THREAD

**Issue by sduensin** [joncampbell123/dosbox-x#2078]
**Describe the bug**
Using OpenWatcom to compile a program, the results are written in totally the wrong place:
- Everything is a subdirectory under `C:\fltkpico`
- Source code is in `src`
- Compiled object code should be written to `obj`

But...

- A zero-byte file is written to `obj`
- The actual obj output is written into the source file!

**To Reproduce**
Unpack the attached tarball.   (Rename, please, GitHub didn't like my bz2 file.)  My configuration and everything are included.  The `B.BAT` in the root begins the build.

**Expected behavior**
`fltk.lib` generated in the `lib` folder.  Confirmed this works under actual DOS (Windows 98).

**Screenshots**
No screenshot.  DOSBox-X eventually blows up.

**Environment (please complete the following information):**
DOSBox-X 0.83.8 on Linux Mint 19

**Additional context**
Never seen anything like this before.  :-)

Not really a zip:
[dosbox-x.tar.bz2.zip](https://github.com/joncampbell123/dosbox-x/files/5669357/dosbox-x.tar.bz2.zip)

**Comment by Wengier** [comment]
@sduensin I have tried your package and made minor modifications to the B.BAT batch file to let it run on my system. What I got is the following screen:

![image](https://user-images.githubusercontent.com/8216923/101718002-57df5600-3a6e-11eb-9237-5e45f6e95c0b.png)

Clearly wpp386 complains about the source file src\fl.cxx. And by looking at the file fl.cxx in your tarball, it is apparently not a C source file (similar for FL_Bitmap.cxx). Perhaps you did not include the original source file in the tarball?

Also, can you post the DOSBox-X configuration file you are using? Thanks!

**Comment by sduensin** [comment]
Ah crap!  Yep, that's the object file that overwrote the source.  Apparently I tarred the wrong thing.  New `src` attached.  And this time, it IS a zip.  :-)


[src.zip](https://github.com/joncampbell123/dosbox-x/files/5674590/src.zip)

**Comment by grapeli** [comment]
@sduensin 
Looks like a serious bug with long filenames. Certainly source files should never be overwritten with relocatable files.
From FreeDOS (doslfn) running under DOSBox-X, the compilation is done correctly and successfully, and the whole thing is really fast.

For comparison (on a really slow processor) how fast is the compilation process from the included dosbox-x.tar.bz2.zip file:
72s - dosemu2 (host filesystem)
161s - qemu-2.8 (kvm), freedos (doslfn)
192s - qemu-5.2.0-rc2 (kvm), freedos (doslfn)
414s - dosbox-x (core=dynamic_x86), freedos (doslfn)
2538s - qemu-5.2.0-rc2 (tcg), freedos (doslfn)

**Comment by Wengier** [comment]
Thanks @sduensin for reporting the issue and @grapeli for the testing and the minimal image! I could reproduce the issue, and I noticed something very strange with the input (DS:SI) to one of the functions (but other functions seem to be okay). I will study it further.

**Comment by Wengier** [comment]
@sduensin and @grapeli I think I have already solved this issue in my latest PR.

**Comment by grapeli** [comment]
I confirm. Now compilation runs correctly and successfully directly from DOS DOSBox-X. No files are overwritten anymore. You got it really fast.
```
C:\fltkpico>ver
DOSBox-X version 0.83.9 (SDL2). Reported DOS version 7.10.
```

**Comment by sduensin** [comment]
Fixed before I reported!  That's fast!  Thanks!
