### ISSUE TITLE
Rename executable to dosbox-x

### ISSUE THREAD

**Issue by sikthehedgehog** [joncampbell123/dosbox-x#208]
Just in case you're stupid enough to have done sudo make install out of impulse.

Turns out that uninstalling DOSBox and reinstalling it will not restore the original one and you're stuck with DOSBox-X, which is really problematic on 64-bit which doesn't have the dynamic core (and hence is pretty much guaranteed to be way too slow for late DOS programs which expect a powerful CPU).

By the way, is there any way to get back normal DOSBox? >_> (I can still run DOSBox-X from the directory I built it on if I need it)

**Comment by joncampbell123** [comment]
You'll need to reinstall dosbox. I'll have make install change the exe name, you're right.

**Comment by sikthehedgehog** [comment]
That's exactly what I had tried (hoping it'd just overwrite dosbox-x) but that didn't work. So dunno now :/

**Comment by joncampbell123** [comment]
Okay. Executable is now 'dosbox-x' and "make install" will install it as such.

**Comment by sikthehedgehog** [comment]
Commenting before I forget. Just uninstalled dosbox-x and now dosbox appears. Turns out they were installed on different directories (dosbox in /usr/bin, dosbox-x in /usr/local/bin). Go figure. I just wish dosbox would now get that the config file exists though... >_<
