### ISSUE TITLE
Emulator real time clock stopped when menu dialog box is open

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#2082]
**Describe the bug**
When I typed the DOS command TIME after opening a dialog box for a few minutes (e.g. "Configuration Tool" or "About DOSBox-X"), I noticed that the emulator's internal clock lagged behind the host clock, as if it stopped while the dialog box was open.
I tried again the TIME command after a few minutes, but the emulator's clock never regained the lost time.
To synchronize the emulator's clock with host PC clock I have to reset the virtual machine.
Thank you.

**To Reproduce**
1. Leave a dialog box open for some time.
2. Close the dialog box
3. Type TIME command at DOS prompt
4. Compare emulator time with host computer time

**Expected behavior**
I think that the emulator clock and the host computer clock should always be synchronized.

**Environment (please complete the following information):**
 - Windows 10 Enterprise 64-bit version 1809
 - DOSBox-X 0.83.8 SDL2 64-bit
 - dosbox-x.conf file attached: [dosbox-x.conf.zip](https://github.com/joncampbell123/dosbox-x/files/5680642/dosbox-x.conf.zip)

**Comment by Wengier** [comment]
@MX9000 Thanks for reporting this! You don't need to reset the virtual machine to synchronize the internal clock with host PC clock though. Just type ```TIME /H``` should do the job. But I agree that there can be perhaps the default option to automatically synchronize the internal clock with the host PC clock.

**Comment by Wengier** [comment]
I have now added the ability to automatically synchronize the date/time with the host system by default. It can be turned off by setting the new config option"synchronize time" to "false" in [dosbox] section, or if you manually change the date/time. Hope this helps.

**Comment by MX9000** [comment]
@Wengier Thank you!
I'll definitely try it in the next release.

**Comment by joncampbell123** [comment]
@Wengier I had to adjust the BIOS_TIMER synchronize code due to some conflicts with demoscene stuff that relies on BIOS_TIMER while setting a higher tick rate, and I had to make "synchronize time" false by default.

The fix retains BIOS_TIMER synchronization with local time, but only if the timer is at the proper 18.2Hz rate. The fix temporarily skips synchronization if anything still uses the BIOS IRQ0 handler but at a faster tick rate (like the aformentioned demoscene stuff).

**Comment by Wengier** [comment]
@MX9000 Due to the fact that time synchronization does not yet work in all situations (PC-98, higher tick rate mode, etc), the feature will be disabled by default as mentioned above, but if desired you can always enable it either from the config file or from the “DOS” menu. Hope this helps.

**Comment by MX9000** [comment]
@joncampbell123 , @Wengier Thank you very much for your efforts and Merry Christmas!

**Comment by MX9000** [comment]
Issue solved.
Thanks.
