### ISSUE TITLE
8088mph

### ISSUE THREAD

**Issue by jadasse** [joncampbell123/dosbox-x#2089]
Is there a way DOSBox-X can run 8088mph properly, in its 8088 4.77 MHz cga form?

**Comment by joncampbell123** [comment]
I would like to, but, no. It's going to require significant changes to video emulation. Especially where the demo seems to rely on driving the CRTC vertical sync controls per scanline.

**Comment by jadasse** [comment]
Oh ok

**Comment by Torinde** [comment]
[PCbox says it can](http://pcbox-emu.xyz)
> Run certain demos that don’t work on much else than real hardware (Like 8088MPH, for instance)
