### ISSUE TITLE
Cannot compile dosbox-x under Ubuntu 16.04

### ISSUE THREAD

**Issue by zaxxxxx** [joncampbell123/dosbox-x#209]
As per "INSTALL" I think I've installed every single libsdl that's required by dosbox but neither vanilla dosbox 0.74 nor this fork doesn't want to compile. I've also tried

apt-get build-dep dosbox

since dosbox is in the official repo but it didn't help either.

Here's the output of ./configure : http://pastebin.com/pFS6AZgt

And here's the output of make (showing only the last lines): http://pastebin.com/Jh2Y8Rtd

And lastly here's the output of make of the vanilla 0.74 dosbox which I'm not really interested in because it's already available in the official repo. It also dosen't build but it's output is a bit different (showing only the last lines) : http://pastebin.com/pNn2NgzS

Any help is highly welcome! I'd love to check this fork out because of it's windows 98 capabilities.

**Comment by aybe** [comment]
Adding `# define isinf(x) (std::isinf(x))` @ https://github.com/joncampbell123/dosbox-x/blob/master/src/fpu/fpu_instructions.h#L284 should fix it but ... it ends up like this :dancer: 

```
dosbox.cpp: In function ‘void notifyError(const string&)’:
dosbox.cpp:543:28: warning: format not a string literal and no format arguments [-Wformat-security]
     LOG_MSG(message.c_str());
                            ^
g++: internal compiler error: Killed (program cc1plus)
```

Someone with Linux knowledge, can you take a look ?

**Comment by joncampbell123** [comment]
GCC doesn't like it when you declare that the function is like printf(), but then use a non-constant format string. You're supposed to use a string constant with the format string of printf.
You can eliminate that warning by changing it to LOG_MSG("%s",message.c_str());

I'm guessing G++ crashed because your #define isinf(x) (std::isinf(x)) makes a recursive macro that never finishes expanding. isinf(x) -> std::isinf(x) -> std::std::isinf(x) -> std::std::std::isinf(x) -> and so on. Try making isinf(x) a static inline function that calls std::isinf().

**Comment by zaxxxxx** [comment]
Thanks guys, adding `# define isinf(x) (std::isinf(x))` worked like a charm and now it works fine.

**Comment by toddfraser88** [comment]
I'm having this issue aswell on ubuntu 16.04, 
where exactly do i change the code to fix this?

**Comment by telanus** [comment]
is there any solution to this?

**Comment by oleg-baskakov** [comment]
aybe's solution didn't work for me. I compiled all succesfully  after manual fix:
add class prefix explicitly `std::isinf(x)` at https://github.com/joncampbell123/dosbox-x/blob/master/src/fpu/fpu_instructions.h#L457

**Comment by toddfraser88** [comment]
is this correct?

`if (std::isinf(fpu.regs[st].d) && std::isinf(fpu.regs[other].d)) { `

**Comment by joncampbell123** [comment]
@toddfraser88 that should be right, yes.
