### ISSUE TITLE
LPT5+ output: file not closed?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2094]
@Wengier - For some reason, my mail message hasn't been delivered, so I'll post it here (with edits reflecting further testing):

Using yesterday's code, if I print from WPDOS 5.1  to LPT5 or LPT6 (and maybe LPT7 through 9 also, though I didn't test this), and specify the output as a file (output5.prn), the file doesn't get closed until DOSBox exits. My AutoIt wrapper can't do anything with the file, and "openpcl" etc. doesn't work either.

This problem does NOT occur with LPT1-3. Also, it doesn't occur with the new port setting LPT4, only for 5 and 6 (and presumably higher numbers). Is it possible to fix this?

Thanks again for all your splendid work!

**Comment by Wengier** [comment]
@emendelson Thanks for catching this. Please check out the updated DOSBox-X binary, which should hopefully solve this issue:

Download: [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/blob/master/dosbox-x-update.zip?raw=true)

**Comment by emendelson** [comment]
Perfect. Thank you!
