### ISSUE TITLE
BUILD: MSVC 2013 needs <algorithm>

### ISSUE THREAD

**Issue by darkstar** [joncampbell123/dosbox-x#21]
MSVC2013 needs ```include <algorithm>``` to define ```std::min``` and ```std::max```, which is missing in disney.cpp

Here's a diff to make it build
```
diff --git a/src/hardware/disney.cpp b/src/hardware/disney.cpp
index 9d2418b..81f47ca 100644
--- a/src/hardware/disney.cpp
+++ b/src/hardware/disney.cpp
@@ -18,6 +18,7 @@


 #include <string.h>
+#include <algorithm> // for std::min and std::max
 #include "dosbox.h"
 #include "inout.h"
 #include "mixer.h"
```

Also, the different uses of min/max could be unified (ide.cpp uses a custom macro MIN and MAX for example, and debug/debug_win32.c also defines its own version of min() ...)

**Comment by joncampbell123** [comment]
Thanks! For some reason GCC did not demand it.

**Comment by joncampbell123** [comment]
Pull the latest commit. Does it work?

**Comment by darkstar** [comment]
yup, works
