### ISSUE TITLE
Full-screen issue with ttf output (SDL2 under Windows)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2100]
Using current code, with a Windows SDL2 build, and a conf file with ONLY `[sdl] output=ttf`.

Start DOSBox-X.
Use the Host-f keystroke to toggle to full-screen
Use Alt-Tab to toggle to another window 
Use Alt-Tab again to toggle back to DOSBox-X running full-screen

The full-screen DOSBox-X will be completely blank, with no text showing. You can toggle back to windowed mode, and regain the text.

This does not happen with the default `output` setting.

**Comment by Wengier** [comment]
I think I have already fixed this in the code.

**Comment by emendelson** [comment]
@Wengier - Yes, fixed. Thank you!
