### ISSUE TITLE
New printer options: allow single quotes for "openwith" etc. command

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2101]
The terrific new "openwith" etc. options for parallel output accept command in quotation marks like this:

`openwith:"SomeProgram.exe /option filename"`

I'm trying to use a program that expects its command-line parameters in double quotes, and won't accept single quotes. Would it be possible to make the openwith option accept single quotes with double quotes inside, like this:

`openwith:'SomeProgram.exe "first parameter" "second parameter"'`

Alternatively, could double quotation marks be escaped in the command string like this:

`openwith:"SomeProgram.exe \"first parameter\" \"second parameter\" "`

I tried putting the command in a cmd file, but that opens a full cmd window instead of displaying only the program.

The program I'm working with is messagebox-win.exe found here: 

https://github.com/cubiclesoft/messagebox-windows

If I could find an alternative that accepts single quotes around its parameters, I would gladly use that instead.

**Comment by Wengier** [comment]
@emendelson I have added a ```squote``` option which will enable the use of single quotes. It is disabled by default because single quotes can be part of the program name or parameter, but if you prefer you can enable it so that single quotes will be used instead of double quotes. For example, the following should work:

```
file file:output.prn timeout:1000 squote openwith:'"SomeProgram.exe" "first parameter" "second parameter"'
```

**Comment by emendelson** [comment]
@Wengier - This is fixed with your new code. Thank you!
