### ISSUE TITLE
Windows builds with ttf output, mode con lines=43 locks up or distorts DOSBox-X

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2102]
Current code, Windows SDL1 build, with only this in dosbox-x.conf:

```
[sdl]
output=ttf
```
Enter:

`mode con lines=43`

and DOSBox-X locks up (not always, but three out of four tries).

In the SDL2 build, it produces video distortion, but you can type `exit` and close down normally.

EDIT: I don't remember if I requested this before, but it be very good if `config -set ttf.lins=nn` could change the window size in the same way that `mode con` can change it. Or could the mode command set any arbitrary number of lines/cols if output=ttf?

**Comment by Wengier** [comment]
@emendelson I think I have already fixed this issue in my PR.

**Comment by emendelson** [comment]
@Wengier Thank you for the fix. I will test it when I get back to my Windows machine.

About setting custom lines/cols: I can't find the place in the code that specifies which video modes are valid with the mode command. Before you added TTF support, I created a few custom video modes like 35x80, 50x80, 60x80, 66x80, etc. and created small Shell programs to switch to them. These don't work reliably with TTF output, and the mode command works with some of those resolutions. 

I would like to try modifying the mode command to work with my custom video modes. Just for information, these are the ones I add (59 is a duplicate of mode 3, which I needed for reasons that don't apply any longer)

```
{ 0x053  ,M_TEXT   ,1056,960, 132,60, 9, 16, 8 ,0xB8000 ,0x4000, 192, 960, 132,960, 0   }, // 132x60 //192->160?
{ 0x054  ,M_TEXT   ,1056,688, 132,43, 9, 16, 8 ,0xB8000 ,0x4000, 192, 800, 132,688, 0   }, // 132x43 //192->160?
{ 0x055  ,M_TEXT   ,1056,400, 132,25, 9, 16, 8 ,0xB8000 ,0x4000, 160, 449, 132,400, 0   }, // 132x25 //should that be 192?
{ 0x061  ,M_TEXT   ,1056,800, 132,50, 9, 16, 8 ,0xB8000 ,0x4000, 192, 800, 132,800, 0   }, // 132x50 //192->160?
/* added by emendelson - 43-line mode */ //experimental plength changed from 2000 to 4000
{ 0x056  ,M_TEXT   ,720, 688, 80, 43, 9, 16, 1 ,0xB8000 ,0x4000, 100, 688, 80, 688, 0   }, 
/* Added by ripsaw8080 - 50-line mode */ //experimental plength changed from 2000 to 4000 
{ 0x057  ,M_TEXT   ,720, 800, 80, 50, 9, 16, 1 ,0xB8000 ,0x4000, 100, 800, 80, 800, 0   },
/* Added by h-a-l-9000 - 66-line mode */ // nb originally read 1056 //experimental plength changed from 3000 to 4000
{ 0x058  ,M_TEXT   ,720,1056, 80, 66, 9, 16, 1 ,0xB8000 ,0x5000, 100,1056, 80,1056, 0   },
/* added by emendelson to reproduce original mode 3, for the 25-line command! */
{ 0x059  ,M_TEXT   ,720 ,400 ,80 ,25 ,9 ,16 ,8 ,0xB8000 ,0x1000 ,100 ,449 ,80 ,400 ,0	},
/* Added by emendelson - 60-line mode */ //experimental plength changed from 3000 to 5000
{ 0x060  ,M_TEXT   ,720, 960, 80, 60, 9, 16, 1 ,0xB8000 ,0x5000, 100, 960, 80, 960, 0   },

```

It would be very useful to be able to use the mode command (or batch files that run the mode command) to switch to the ones that aren't already supported, but I'll understand if this is outside the range of standard DOSBox-X.

**Comment by emendelson** [comment]
@Wengier A followup: your new code solves the problem, and my custom modes now seem to work correctly also with ttf output. Thank you!

**Comment by Wengier** [comment]
@emendelson Great to hear that it works! Since the custom video modes are more or less made up, I don't think they will be incorporated to the standard DOSBox-X code directly, but later it may be possible to specify an external data file that contains user-defined video modes. Just a possibility.

**Comment by emendelson** [comment]
@Wengier That's an interesting possibility. Meanwhile, my custom modes work very well with current code. Thank you again.
