### ISSUE TITLE
VS2019: Fails to compile ARM64 target because of physfs LZMA support

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#2110]
**Describe the bug**
VS2019 cannot compile ARM64 targets because of a compile error, missing symbol related to LZMA decoding.

**Additional context**
Error: physfs_lzmasdk.h line 1256 "CrcUpdateT1" undeclared identifier

**Comment by Wengier** [comment]
@joncampbell123 It looks like a bug of the LZMA code. I have tried to fix it so that the ARM64 target should build fine, but I don't have a Windows ARM64 system to actually run the build myself.

**Comment by joncampbell123** [comment]
This has been fixed.
