### ISSUE TITLE
[Feature Request] Adding a "mount archive as folder" option in mount menu?

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#2111]
Hello. In your commit 1db6889fd26575165b79d49de407a32041776b4f, you added support for physfs. I tested it and it works great. But I had to mount by hand my test archive.

I wonder if you can add a "mount archive as folder" option in mount menu in order to make archive mounting as folder in a more simple way?

Thanks for your answer.

**Comment by Wengier** [comment]
It is certainly a good suggestion! I have thought about it too and have already added the menu option to mount an archive file in my PR #2112.

**Comment by FredBezies** [comment]
Tested it and it works perfectly, even with a multi-level directory archive such as Planet-X3 retail one. Thanks!
