### ISSUE TITLE
Clipboard-copy problems with output=ttf in >25 line modes

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2116]
Current code, SDL1 build, Windows:

With a conf file containing only [sdl] and output=ttf, enter

mode con lines=43

Enter DIR to get a lot of text on screen; hold down the shift key and click the right-mouse button to start copying to the clipboard. The highlighted part of the screen flashes on and off.

While I am here, is there any hope that DOSBox-X can support a cmd-window-style copy-to-clipboard feature, where you turn on Mark, move the cursor to select text, and press Enter to copy it? That would be very easy to use if it could be implemented.

EDIT: What would be ideal would be a keystroke (host+something) that marks the current cursor position as the starting point for marking text; you press the keystroke, then use the arrow keys to extend the selection, and press Enter to copy to the clipboard.

**Comment by Wengier** [comment]
@emendelson The fact that the highlighted part of the screen flashes on and off in this case as you said is purely cosmetic - it does not change the actual clipboard copy function at all, so you don't need to worry about this. If you don't want to hold down the Shift key, why not check the "Quick Edit" option in the "Shared clipboard functions" menu group? I think it is certainly easier to select the text using mouse instead of the keyboard.

**Comment by emendelson** [comment]
@Wengier - Those methods certainly work. I find it's easier to get exactly the text I want when I use the keyboard, but that's subjective.

Question: Is there a way to assign Quick Edit to a keystroke?

**Comment by JoeC4281** [comment]
@emendelson In vDosPlus, I used the [SNIP437.COM](https://sourceforge.net/p/vdosplus/discussion/general/thread/361607bf/#64ea) utility to allow the use of the keyboard to select text on the screen, and save it to the clipboard.

@Wengier [helped me](https://github.com/joncampbell123/dosbox-x/issues/2097) get DosBox-X setup, so that I can copy to the clipboard via LPT1, but I have not been able to get SNIP437.COM to actually print the selected text to the clipboard (LPT1).

![image](https://user-images.githubusercontent.com/58880711/103045171-73a82900-4551-11eb-8e14-2ccae6d9f170.png)

It would be great if I had this ability again, as I prefer using the keyboard to select text on the screen, rather than the mouse.

Joe

**Comment by Wengier** [comment]
@emendelson and @JoeC4281 If you want to use the keyboard to select and copy text on the DOSBox-X screen, why not try the [DOSClip 3.2](http://ansis.lv/dosclip/index.en.php) tool? I can confirm that it works with DOSBox-X (TTF output or not). With it loaded, press Ctrl+C to start text selection and Ctrl+V to copy text, or you can use the mouse of course.

P.S. I don't have a copy of SNIP437.COM to test any more, and the download link on the page is apparently dead.

**Comment by JoeC4281** [comment]
The source code and .com for SNIPPER is available from;

https://www.pcjs.org/software/pcx86/sw/magazines/pcm/

Volume 6 Number 18 of PC Magazine

I am using Windows 10 64-bit. I tried DOSCLIP, but Ctrl-C does not allow any selection of text, nor anything else.

Joe

**Comment by Wengier** [comment]
@JoeC4281 I think @emendelson had a special version called SNIP437.COM available, but I tried the original SNIPPER tool, which does allow me to select text on the screen as well as saving to a file name as specified by the "dos clipboard device name" setting, either CLIP$ or LPT1 or another name.

As for DOSCLIP, it does work here (I am using Windows 10 64-bit too). After I press Ctrl+C, I need to hold the Shift key to select text on the screen. But maybe you want to change the default shortcut keys with its /K option and see if it works better for you.

**Comment by JoeC4281** [comment]
I've put my copy of [SNIP437.COM](https://1drv.ms/u/s!AhH9hlYaKTEokATqb99cWskj9bgO?e=Tmi7tw) on my OneDrive.

After highlighting text on the DosBox-X screen, I tried saving the file to LPT1, and that works!

![image](https://user-images.githubusercontent.com/58880711/103052288-c3ddb600-4566-11eb-99aa-66d36e855ab5.png)

However, the SNIP437.COM Print to the LPT1 port does not work.

Joe

**Comment by emendelson** [comment]
@JoeC4281 Yes, SNIP437.COM was (is) my patched version of SNIPPER.COM, made for DOSBox years and years ago. 

@Wengier - One thing I noticed with SNIPPER is that when I save to CLIP$, the most recent clip is appended to the existing text in CLIP$, instead of replacing the existing text with the new clip, which is probably not what the user wants (though it could be useful). I suppose it should be possible to modify the source code for SNIPPER to change this behavior, but I wouldn't know how to do it.

I moved the archive to a different folder, which is why the old link is dead. This should work:

https://www.dropbox.com/s/s84arfynu8jrx2r/dosboxsnipper.zip?dl=1

**Comment by Wengier** [comment]
@JoeC4281 and @emendelson I think there is an easy solution for SNIP437.COM's print feature: create a batch file named e.g. toclip.bat in the DOSBox-X directory with a content like this:

```
@clip<%1>nul
```

Then edit the "parallel1" config option to some like:

```
parallel1 = file file:output1.prn timeout:1000 openwith:toclip
```

Then SNIP437.COM's print feature should work. Hope this helps.

**Comment by emendelson** [comment]
I didn't know about the ClipText tool when I wrote something similar a few years ago:

http://www.columbia.edu/~em36/clip2txt.html

As you can see, I mostly copied code that I didn't understand, and any competent programmer can clean it up in a dozen ways. The codepage feature may be useful.

**Comment by Wengier** [comment]
@emendelson If you want to explicitly use a certain codepage, you can probably get the command-line [convertcp tool](https://sourceforge.net/projects/convertcp/) and then use the following command line in a batch file instead:

```
convertcp 437 utf-16 /i %1 | clip
```

Hope this helps.

**Comment by JoeC4281** [comment]
@Wengier With your suggestions, I can now use SNIP437.COM to save selected text to the clipboard via the "F - File" and "P - Print" options, although I am going to use the "P - Print" option, as that is what I used in vDosPlus.

Thanks!

Joe

**Comment by emendelson** [comment]
DOSCLIP (to my surprise) sends the selected text to the Windows clipboard (I don't think it did that under old DOSBox), but the .COM file is compressed in some way that I don't recognize, so I can't patch the code to clean up the opening banner or to change the hotkey modifier from Ctrl to Alt. Does anyone know a way to decompress the .COM file?

Again, it would be very good to have a similar feature in DOSBox-X itself: Press a key to start selecting at the current cursor position, move the arrow keys (with or without the shift key), and press Enter to copy the selected text to the host clipboard.

**Comment by JoeC4281** [comment]
I agree with @emendelson in regards to adding a feature to DOSBox-X that would allow the selection of text using the keyboard, and having it copied to the host clipboard.

Joe

**Comment by Wengier** [comment]
@emendelson Unlike DOSBox, DOSBox-X supports the DOS clipboard API for Windows just like vDosPlus, which is why DOSClip can send the selected text to the Windows clipboard.  I think @JoeC4281 posted the DOSClip source code previously in the other thread, although it may not be the latest version.

In any case, thank you both for the request. I have already implemented text clipboard using the keyboard in my PR. You can now use of arrow keys (left, right, up, down) to select text to be copied to the host clipboard. Set "clip_mouse_button=arrows" to enable it, or select it from "Shared clipboard functions" menu group. In QuickEdit mode, press the Home to start the actual selection, and End to end the text selection and copy the selected text to the clipboard.

Happy Christmas Eve!

**Comment by emendelson** [comment]
@Wengier  This is very impressive! Thank you! 

Two thoughts: first, is it possible to have a keystroke that will work the same way as choosing Quick Edit from the menu? Some users might not have the menu visible, and a keystroke would be much quicker.

Second, is it possible to make the selection work by holding down the arrow keys, as in DOSCLIP, instead of pressing the keys repeatedly?

This is a really excellent feature already. Thank you again.

**Comment by Wengier** [comment]
@emendelson Thanks for the suggestions! I have already added the Quick Edit mode to the mapper so that you can define your own shortcut for it. Also, the arrow key non-repeat issue only occurs in the SDL1 build, but not the SDL2 build. I have already enabled the repeat for SDL1 build too. In addition, I have fixed the highlighted part of the screen flashing on and off issue with >25 line modes as you mentioned earlier.

Please check it out.

**Comment by emendelson** [comment]
@Wengier Very busy today, but got a chance to build the new code and experiment. I mapped fastedit to Ctrl-Alt-F3, and the arrow-key option works perfectly at the DOS prompt. Inside a program like WordPerfect, I can't get it to work: the Home and End keys get read by the program, and move the cursor instead of performing the clipboard copy. Is there a way to prevent the program from seeing the Home and End keys? (I'm not sure whether the cursor movement is seen by the program or by the fastedit feature.)

I probably won't be able to respond today, but will be back tomorrow. Thank you again for all this superb work.

**Comment by JoeC4281** [comment]
Hey @Wengier I did a git pull and compiled the new code.

I have DosBox-X configured now as;
![image](https://user-images.githubusercontent.com/58880711/103141315-ba686100-46c0-11eb-86c9-017fadcb0bb6.png)
...and I am able to use the Shift-Arrow Key to locate the cursor on 4DOS.COM, dBASE IV 2.0 App, and WordPerfect 6.2

However, when I am selecting text using the cursor, while highlighting in one area of the screen, the cursor is also moving through the fields on my dBASE form at the same time.

Ditto for WordPerfect, and the 4DOS.COM command line. In the 4DOS.COM case, pressing the Shift-Up Arrow to locate the cursor, also causes the command line to scroll back through my command history.

It does, however, copy the text I select to the clipboard, which I can use from a Windows App.

So, if the cursor movement can be ignored (by the app or 4DOS.COM), then that would be better.

While not visible in this screen capture from one of my dBASE apps, note that the green rectangle indicates where I had located the cursor using Shift-Up/Down Arrow, but the cursor for the dBASE app moves along with it, in this case, from the ACCT_NUMB field down to the ACCT_NAME field, and vice-versa.

![image](https://user-images.githubusercontent.com/58880711/103141445-5c3c7d80-46c2-11eb-91a6-90ef86da9228.png)

Also, even after I exit my dBASE app, and return to the 4DOS.COM prompt, the text selection cursor still remains on the screen, at the location it was in my dBASE app.

![image](https://user-images.githubusercontent.com/58880711/103141500-04524680-46c3-11eb-9422-af0e778d0ff9.png)

Joe

**Comment by emendelson** [comment]
@Wengier Also, while we are making requests, can the keyboard shortcut be added to SDL1? It seems to be available in SDL2.

This is a major addition to DOSBox-X for use with applications, and I know that you have done a lot of work on it - but it is all VERY worthwhile. Thank you.

**Comment by Wengier** [comment]
@emendelon and @JoeC4281 I think both of you are talking about the flexibility of the keys used for the keyboard selection. If you look at the clip_key_modifier config option, you will find that this option is customizable. For example, if you set "clip_key_modifier" to "alt", then without QuickEdit you will be able to use Alt+arrows and Alt+Home/End to do the text selection. I have checked that these keys appear to work fine with WordPerfect and dBASE. Let me know if you believe they are still insufficient.

**Comment by JoeC4281** [comment]
Well, that was easy! I have changed my .conf to;

![image](https://user-images.githubusercontent.com/58880711/103174322-2072f680-482f-11eb-9bc0-30653c0a4e47.png)

...and I can move the cursor, select the text, and copy it to the clipboard, with no secondary issues.

Awesome work on your part  @Wengier. Thanks!

Joe

**Comment by emendelson** [comment]
@Wengier and @JoeC4281 - Yes, that's perfect. Thank you!

**Comment by emendelson** [comment]
@Wengier One issue with using Alt-arrows to select text. If I move the cursor up or down five rows, I can move the cursor back again two rows, and only three rows will be selected. But if I move the cursor left or right twenty characters, and then move it back again ten characters, the selection is not reduced in the same way it is reduced when I move the cursor up or down.

I hope this is clear! And maybe I'm seeing things incorrectly.

**Comment by JoeC4281** [comment]
Hey @emendelson Am I seeing something similar to what you are experiencing?

Under 4DOS Prompt, if I make a mistake, and select four rows instead of three, and I up-arrow to reduce the selection to three rows, four rows remain selected.

Ditto for columns.

However, when I do the same thing while running a dBase IV app, the rows get reduced, that is, if I make a mistake, and select four rows instead of three, and I up-arrow to reduce the selection to three rows, only three rows are selected. The columns also work correctly.

So, I only have a problem with trying to correct a text selection when at the 4DOS Prompt, but no problems with correcting a text selection in dBASE IV or WordPerfect 6.2

Joe

**Comment by emendelson** [comment]
@JoeC4281 It sounds similar. I was experimenting in WordPerfect and at the DOS prompt. Odd that we should see different issues, but it sounds like it's the same underlying issue. @Wengier will know how to fix it!

**Comment by Wengier** [comment]
@emendelson and @JoeC4281 I did find a bug in the keyboard text selection code so I have already fixed it in #2127. Can you please check if the new code fixes the problem you described?

**Comment by JoeC4281** [comment]
I went through the motions with 4Dos, dBase IV 2.0, and WordPerfect 6.2 again.

Text selection in dBase IV 2.0 and WordPerfect 6.2 WAD, just as I noted previously.

Text selection now WAD in 4Dos, which fixes the problem I noted previously.

Great work @Wengier, thanks!

Joe

**Comment by emendelson** [comment]
@JoeC4281 (WAD = Working as Designed) Yes. @Wengier - Thank you! Closing this now...

**Comment by emendelson** [comment]
@Wengier XyWrite uses Alt-Arrow keys internally, so I guess the only way to use the select-for-clipboard feature in XyWrite is to change the clip_mouse_button setting to "right". There's probably no reliable way to use the keyboard - unless you can think of one!

**Comment by Wengier** [comment]
@emendelson In the case of XyWrite 4, I think you can just use Ctrl+Alt+arrows to do the text selection- XyWrite seems to ignore them, but they will be accepted for the text selection. Or just use the mouse to do the text selection instead as you said.

**Comment by Wengier** [comment]
@emendelson Just set "clip_key_modifier=ctrlalt" in the case of XyWrite 4.

**Comment by emendelson** [comment]
@wengier - That sounds like the right solution. Because I now use Ctrl-Alt-Up/Down for increase/decrease TTF size, I'll probably change the font size setting to Ctrl-Alt-PgUp/PgDn. After I get these changes made, I'll post a link to a test installer. 

(For both Windows and the Mac, I'm trying to create a DOSBox-X-based system for running applications like XyWrite, complete with printing, etc., in addition to a new version of DOSBoxWP.)
