### ISSUE TITLE
Compile on RPi4 64bit RasPiOS(Raspbian)?

### ISSUE THREAD

**Issue by lee-yunseok** [joncampbell123/dosbox-x#2120]
No problem with `./configure` but `./build` failed. How to compile DOSBox-X on **64bit** RPi?

**Comment by joncampbell123** [comment]
What error messages did it produce?

**Comment by lee-yunseok** [comment]
@joncampbell123

```
UNAME_MACHINE = aarch64
UNAME_RELEASE = 5.10.2-v8+
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1385 SMP PREEMPT Wed Dec 23 12:00:51 GMT 2020
configure: error: cannot guess build type; you must specify one
```

**Comment by joncampbell123** [comment]
Looking at config.guess on my system, it should recognize aarch64:Linux:*:*

Try running ./autogen.sh, then ./build or ./build-debug. If you have autoconf, automake, and m4 installed it should regenerate the autoconf files with a newer version that recognizes aarch64.

By the way, the last time I checked, I could only find 32-bit Raspian. Where did you find 64-bit Raspian? I have been wanting to test and develop DOSBox-X on Raspian armv8 (aarch64) for some time, but I have only been able to find 32-bit armv7 builds.

**Comment by lee-yunseok** [comment]
Same error occurred. 64bit RasPiOS still in **beta**.

https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/

**Comment by JDraugr** [comment]
If you are still having this issue, you must update your config.guess and config.sub. That is the information I found when I was going through this issue. The updating of the files got me through the build process and I was then able to install dosbox-x.

Links to files:

[config.guess]
 `http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD`

and

[config.sub]
`http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD`

**Comment by lee-yunseok** [comment]
@JDraugr It didn't work for me. Same error occurred.
