### ISSUE TITLE
How to increase Configuration Menu ?

### ISSUE THREAD

**Issue by Roughtrade** [joncampbell123/dosbox-x#2121]
i just compiled dosbox-x from source. With ./build-debug

Is it possible to make the configuration menu bigger, or is there a place in the source code where you can change the size factor?

![Bildschirmfoto zu 2020-12-26 07-43-03](https://user-images.githubusercontent.com/18134832/103146878-bfc0bc80-474f-11eb-988c-f98c9a520ad5.png)

**Comment by Wengier** [comment]
Right now you cannot directly change the config window size from the UI, but it can be done by modifying the source code (in the sdl_gui.cpp file).

**Comment by Wengier** [comment]
This is hopefully fixed in #2242.
