### ISSUE TITLE
Colors change after video mode switching with mode con lines=43 (etc.)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2128]
Tested with current code, SDL1:

Set up the WordPerfect Shell 3.1, with WPDOS 5.1 on the menu.

Start up DOSBox-X with `output=ttf`

Enter `mode con lines=43 cols=80` (either in [autoexec] or at the prompt.

Start the Shell (which will fill 25 lines of the 43-line window).

Run WPDOS from the shell. Press F7 to exit WPDOS and return to the shell.

Colors will be corrupted as in the screen shot:

![Capture](https://user-images.githubusercontent.com/5208505/103235378-02c98e00-4910-11eb-875c-013d81f59138.PNG)

Interestingly, this problem does NOT occur if you enter `ttf.lins=43` in the conf file. However, it does occur if you enter that setting in the conf file and THEN change the video mode with the `mode con` command.

**Comment by Wengier** [comment]
@emendelson There is a "Reset window size" menu option (either from the drop-down menu or from the system menu), and you can always try this and see if it helps. You can define a shortcut for this menu option in the mapper too.

**Comment by emendelson** [comment]
@Wengier Unfortunately, when I use that menu option, the colors are distorted in a different way.

![Capture](https://user-images.githubusercontent.com/5208505/103237590-0829d700-4916-11eb-93e1-96a141a05239.PNG)

The same problem occurs if you're running WordPerfect and press Ctrl-F1 to return temporarily to the Shell. Is it possible to avoid this problem in the code? The users I'm trying to support won't want to click on a menu item every time they switch between a program and the Shell. And it seems likely that this problem will emerge in other situations.

**Comment by Wengier** [comment]
@emendelson Apparently, WP 5.1 has actually changed the palette of the color 1 in this case, which should be blue by default. You can change it back with the SETCOLOR command:

```
SETCOLOR 1 #0000a8
```

Perhaps this command can be executed automatically in this case?

**Comment by emendelson** [comment]
@Wengier - it turns out that Shell messes up the colors without even opening WPDOS. Try this.

Run Shell. Press 4 for setup. Immediately press F7 to exit setup. The colors are distorted in exactly the same way I described above.

If, after exiting setup, I run the DOS command SETCOLOR, the output tells me that color 1 is #00a8a8.  If I run `SETCOLOR 1 -` then the colors are restored.

There is no way to automate running this command every time the Shell does something. Is it possible to add an option in DOSBox-X that would force a SETCOLOR command at every mode change?

**Comment by Wengier** [comment]
@emendelson Yes, the color palette is changed by SHELL.EXE itself, not WPDOS. However, it happens in non-TTF outputs too, not just the TTF output, so it is likely a bug of WP Shell, and it has nothing to do with the TTF output. I tried it with DOSBox-X 0.83.5 with 132x43 line mode and the color is similarly changed in such case, even though DOSBox-X 0.83.5 did not support TTF output at all. Since the SETCOLOR command can only change the color scheme in TTF output, I doubt it will help for the general case.

**Comment by emendelson** [comment]
@Wengier - Yes, you're right. It has nothing to do with TTF output. What's strange is that the problem doesn't happen with `ttf.lins=43` but does happen after setting the mode with `mode con`. I can certainly live with this, since the ttf.lins setting prevents it from happening. Time to close this.
