### ISSUE TITLE
Add PgUp/PgDown to mapper keys?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2130]
To avoid conflicts with keyboard layouts in some applications, I would like to assign the PgUp and PgDown to some mapper keys, but these keys don't seem to be available. Is it possible to add them? Many thanks for any help with this.

**Comment by Wengier** [comment]
@emendelson Both PgUp and PgDn keys can already be assigned to any shortcuts in the mapper. I just tested them myself and can confirm they work for this purpose. You just need to select the function(s) in the mapper, click "Add", press PgUp or PgDn key, then click the lower (not higher) button that shows "host" (not "Host"), or "mod1", "mod2", "mod3" (not "Mod1", "Mod2", "Mod3"), click "Save" and "Exit". It should then work. Hope this helps.

**Comment by emendelson** [comment]
@Wengier - Yes, I realized that I could assign those keys in the mapper, but I want to assign them in the code, in the same way that I can assign a function to `Mk_up, MMOD1|MMOD2`. That way the assignment won't depend on a mapper file. 

What I'm hoping is that the PgUp/PgDown keys can be added to the list in mapper.h, lines 24-31. I think I see that SDL_SCANCODE_PAGEUP can be assigned to a key named Mk_pageup or something similar, and I think I can figure out how to do that in my code, but I hope it might be useful in the standard code.

**Comment by emendelson** [comment]
@Wengier - On second thought, ignore this request. I realized that I could use two function keys instead. Apologies for wasting time and bandwidth!

**Comment by Wengier** [comment]
@emendelson Actually it is not a bad request. There are a couple of key symbols missing in sdl_mapper, so I have added the missing number and alphabet keys along with PgUp/PgDn key symbols in #2131.

**Comment by emendelson** [comment]
@Wengier Excellent. Thank you!
