### ISSUE TITLE
[FR] replace contrib/fonts/UnifontFullMediumMono.ttf with unifont_jp-13.0.05.ttf

### ISSUE THREAD

**Issue by roytam1** [joncampbell123/dosbox-x#2132]
**Is your feature request related to a problem? Please describe.**
normal version of unifont (i.e. without "_jp" suffix) does not comply Japanese standard of how ideographs present because it use Chinese(PRC) standard in normal version of unifont.

**Describe the solution you'd like**
replace `contrib/fonts/UnifontFullMediumMono.ttf` with `unifont_jp-13.0.05.ttf`.
it is also better to re-render FREECG98.BMP with this font as well.

**Describe alternatives you've considered**
unifont_jp font with version >= 13.0.02 complies the Japanese ideograph standard(in terms of Japanese kanji).

**Additional context**

**Comment by Wengier** [comment]
Thanks for the suggestion, Roy! I can find the ```unifont_jp-13.0.05.ttf``` file from:

 https://unifoundry.com/pub/unifont/unifont-13.0.05/font-builds/

Do you have a FREECG98.BMP file rendered from this font? Thanks.

**Comment by roytam1** [comment]
> Do you have a FREECG98.BMP file rendered from this font? Thanks.

I don't, since I don't know which program to render it.

**Comment by Wengier** [comment]
I see. I am not really sure about the exact program to render it either. Perhaps @joncampbell123 or @stgiga knows how to do so?

**Comment by roytam1** [comment]
I opened anex86 on Win2000 JPN and use Unifont-JP to auto-generate and capture with HpyerSnap and join them together.
I also replaced some glyphs from Unifont's single to JIS' dual width, and some glyphs in extended area with public domain izmg16.
due to codepage restrictions, some glyphs are not available in generated font:

upper part(i.e. NEC extended JIS C 6220, half width):
- Control Pictures
- Block Elements
- Box Drawing (and rounded corners)
- (after half-width katakana) more Box Drawing & Block Elements glyphs
- half-width version of ♠♥♦♣●○円年月日時分秒
- forward slash

lower part:
- half-width(single width) combined katakana
- extra half-width punctuations
- both width of dotted and dashed line drawing glyphs
- combined width(thin and thick) box-drawing glyphs.
![unifont-jp-more-izmg16](https://user-images.githubusercontent.com/1192577/103325222-cc158400-4a85-11eb-8d30-239a4f7cfa89.png)

**Comment by roytam1** [comment]
and of course many missing glyphs are important:
anex98.bmp:
![Snap1](https://user-images.githubusercontent.com/1192577/103327058-f9663000-4a8d-11eb-8333-eded3196c2ed.png)

unifont-jp-more-izmg16.bmp:
![Snap2](https://user-images.githubusercontent.com/1192577/103327068-03882e80-4a8e-11eb-8027-0173d55358bd.png)

**Comment by roytam1** [comment]
... so I decided to copy missing glyphs from freecg98.bmp, and replaced 0x5C to Yen sign:
![unifont-jp-more-izmg16](https://user-images.githubusercontent.com/1192577/103329625-6b437700-4a98-11eb-83f4-4dd6e9b3dff5.png)

screenshot:
![Snap1](https://user-images.githubusercontent.com/1192577/103329644-80200a80-4a98-11eb-8135-b107f4ac0160.png)

**Comment by Wengier** [comment]
@roytam1 Can you upload the updated BMP file? Thanks.

**Comment by roytam1** [comment]
> @roytam1 Can you upload the updated BMP file? Thanks.

[unifont-jp-more-izmg16.zip](https://github.com/joncampbell123/dosbox-x/files/5753749/unifont-jp-more-izmg16.zip)

**Comment by Wengier** [comment]
Sassatoots

**Comment by Wengier** [comment]
@roytam1 Thanks! I think I will upload it to the contrib/fonts directory as well.

**Comment by RNMB15** [comment]
I have found the following about PC 98 Font and what about the PC 98 BIOS:

[PC98-BIOS-BACKUP-TOOLS.zip](https://github.com/joncampbell123/dosbox-x/files/5754113/PC98-BIOS-BACKUP-TOOLS.zip)
[98rometc.zip](https://github.com/joncampbell123/dosbox-x/files/5754115/98rometc.zip)
[font.zip](https://github.com/joncampbell123/dosbox-x/files/5754116/font.zip)
[98font.zip](https://github.com/joncampbell123/dosbox-x/files/5754114/98font.zip)

**Comment by RNMB15** [comment]
I have something that doesn't quite fit the topic: This is a tool collection for playing music from Game music in PC 98:

[drivers.zip](https://github.com/joncampbell123/dosbox-x/files/5754135/drivers.zip)

And here is a collection of tools to boot:

[PC98HDD MS-DOS v6.2.zip](https://github.com/joncampbell123/dosbox-x/files/5754171/PC98HDD.MS-DOS.v6.2.zip)
[Uploading PC98HDD MS-DOS v6.2.z01.zip…]()
[Uploading PC98HDD MS-DOS v6.2.z02.zip…]()
[Uploading PC98HDD MS-DOS v6.2.z03.zip…]()

**Comment by Wengier** [comment]
@roytam1 The new FREECG98.BMP file is already here:

https://github.com/joncampbell123/dosbox-x/blob/master/contrib/fonts/FREECG98.BMP

The original FREECG98.BMP file is here:

https://github.com/joncampbell123/dosbox-x/blob/master/contrib/fonts/FREECG98_OLD.BMP

**Comment by Wengier** [comment]
@RNMB15 Thanks for the links. For the last one, the HDD IMG files do not seem to be directly mountable in PC-98 mode though.

**Comment by RNMB15** [comment]
I tried to fine-integrate the IMG in dosbox with the following parameter, but it didn't work.

![dsfdfs](https://user-images.githubusercontent.com/56356083/103418673-fce1e000-4b8f-11eb-8e49-f4e861c7079e.png)

**Comment by rderooy** [comment]
@RNMB15 you need to specify the drive letter with the imgmount command.

e.g. to mount the image on the D: drive

```
imgmount d PC98-5~1.IMG
D:
```

**Comment by RNMB15** [comment]
That worked, but it hangs after booting:

![command_002](https://user-images.githubusercontent.com/56356083/103439749-e2ffd600-4c3f-11eb-9f4d-5822514d9652.png)
![guest os_001](https://user-images.githubusercontent.com/56356083/103439750-e3986c80-4c3f-11eb-870f-44d9da3105a1.png)

**Comment by rderooy** [comment]
@RNMB15 your mounting the image on the D: drive, and then your booting from the C: drive, which is just a folder mount, which will vanish the moment your booting a disk image?

Can you mount the image file on the C: drive instead? Something like:
```
imgmount d PC98.IMG -u
```
Also, do you need all those other flags, do you really need them? Typical IBM PC compatible disk images are auto detected normally. Not sure about PC-98.
Try mounting the image file as the C: drive instead.

**Comment by roytam1** [comment]
> @roytam1 The new FREECG98.BMP file is already here:
> 
> https://github.com/joncampbell123/dosbox-x/blob/master/contrib/fonts/FREECG98.BMP
> 
> The original FREECG98.BMP file is here:
> 
> https://github.com/joncampbell123/dosbox-x/blob/master/contrib/fonts/FREECG98_OLD.BMP

alright I think this issue can be closed. Above comments seems to be off-topic to me.

**Comment by Wengier** [comment]
@roytam1 Yes, I agree that the original issue is already done.

@RNMB15 I can mount and boot the PC98-128MB-DOS3.img file fine with the following (only -size 512,17,8,8162 is required): 

```
IMGMOUNT C PC98-128MB-DOS3.img -size 512,17,8,8162
BOOT C:
```

The PC98-542MB.img file can be mounted and booted fine too if you comment out the following line of the config.sys file:

```
DEVICE=A:\TOOLS\HSB.EXE Q VC Y-
```

Then use the commands:

```
IMGMOUNT C PC98-542MB.img -size 512,17,8,8162
BOOT C:
```

Hope this helps.

**Comment by RNMB15** [comment]
The menu of PC98-542MB.img is not displayed correctly in DOSBOX-X: In np21x64w it is displayed properly.

![guest os_000](https://user-images.githubusercontent.com/56356083/103669703-faf59380-4f78-11eb-9eda-5e784a0f40c5.png)
![dsad](https://user-images.githubusercontent.com/56356083/103670150-7fe0ad00-4f79-11eb-9841-849307b8e00a.png)

**Comment by stgiga** [comment]
I just regenerated FREECG98.BMP with Unifont-JP 13.0.06

https://cdn.discordapp.com/attachments/231947749862539264/850143585604468756/FREECG98.BMP

Any improvements made to the prior FREECG98.BMP should be redone for *this* version, because Unifont-JP has proper JP Han ideographs.
