### ISSUE TITLE
Current code won't build in macOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2139]
Testing in Mojave

`build-macosx`

produces this error message:

```
/bin/sh /Users/edward/Development/dosbox-x-master-31Dec/vs2015/sdl/build-scripts/mkinstalldirs build
make: *** No rule to make target `/Users/edward/Development/dosbox-x-master-31Dec/vs2015/sdl/src/main/macosx/*.m', needed by `build/*.lo'.  Stop.
make: *** Waiting for unfinished jobs....
mkdir -p -- build
```

**Comment by Wengier** [comment]
@emendelson The current code seems to build fine here in my macOS a High Sierra VM, and there are vs2015/sdl/src/main/macosx/*.m files. Make sure the source tree is clean and try again.

**Comment by emendelson** [comment]
@Wengier You're right. I downloaded again and it built correctly. Apologies for wasting bandwidth.

**Comment by Wengier** [comment]
Hopefully all targets should build, as I assume a new version is coming very soon.
