### ISSUE TITLE
"Abuse" game - cannot use mouse in menu

### ISSUE THREAD

**Issue by Expack3** [joncampbell123/dosbox-x#214]
EDIT: My host OS is Windows 10 Pro x64, version 1511
I attempted to play the 2.0 freeware release of Abuse using the 32-bit Windows installer preview version, only to find the main menu has massive framerate issues - the mouse moves, but only after 5 seconds, and sounds 'pop' as they attempt to play. This issue is not present on the stable .74 release of normal DOSBOX. Shutting off MIDI music doesn't change anything.

Below is the DOSBOX config I used to run Abuse (anything unlisted uses default settings):

```
# This is the configuration file for DOSBox DOSBox-X. (Please use the latest version of DOSBox)
# Lines starting with a # are comment lines and are ignored by DOSBox.
# They are used to (briefly) document the effect of each option.
# To write out ALL options, use command 'config -all' with -wc or -writeconf options.
[dosbox]
memsize=32

[cpu]
core=dynamic

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount c .\games
c:
cd abuse
abuse
exit
```

**Comment by box-tortoise** [comment]
Test this version: https://github.com/joncampbell123/dosbox-x/releases/tag/v0.801.

**Comment by Expack3** [comment]
Initially, the menu cursor seemed to work with v0.801, but when I closed and re-opened DOSBOX-X, the same problem as before occurred.

**Comment by Gui55** [comment]
Assuming you have core=dynamic and are using the 32-bit build, try setting "fpu=false" and verify that "non-recursive page fault=false". Also be sure you're not booting into any guest OS (such as MS-DOS or win95) and are just running Abuse from DOSBox-X's native prompt.

Hope this helps!

**Comment by Expack3** [comment]
Adding `fpu=false` and `non-recursive page fault=false` to my config worked using both the 32-bit Windows installer preview version and v0.801...but only when MIDI is disabled. 0.74 stable DOSBOX works just fine with MIDI enabled.

**Comment by box-tortoise** [comment]
Host OS was excluded: https://support.microsoft.com/en-us/help/13443/windows-which-operating-system.

**Comment by joncampbell123** [comment]
Where do you find the version of Abuse you're using? I just tested the DOS version with the normal core and it seems to work fine.

**Comment by Expack3** [comment]
The one I'm using is found here: http://www.classicdosgames.com/game/Abuse.html

Specifically, the 2.0 shareware (actually freeware) release.

**Comment by Expack3** [comment]
Here's one scenario I used which freezes up the Windows installer preview, but not regular DOSBOX:

As soon as the Crack Dot Com logo appears, press the spacebar. This is able to reliably bring up the issue mentioned in the OP.

**Comment by joncampbell123** [comment]
I can confirm it doesn't happen on my Linux system with core=normal. I'm trying core=dynamic now.

**Comment by joncampbell123** [comment]
It works on my end with core=dynamic. The installer and runtime version are DOS based.

**Comment by Expack3** [comment]
Can also confirm the game runs fine on Windows 10 64-bit with the normal core on the 32-bit installer preview version. Here's my revised config file which contains the settings I can confirm work:
```
[dosbox]
memsize=32

[cpu]
core=normal
cycles=auto

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount c .\games
c:
cd abuse
abuse
exit
```

**Comment by joncampbell123** [comment]
Mouse seems to work fine.
