### ISSUE TITLE
Where is the mingw builds for 0.83.9 ??

### ISSUE THREAD

**Issue by skywind3000** [joncampbell123/dosbox-x#2142]
**Please describe your question.**

Where is the mingw builds for 0.83.9 ?? 
Cannot be found in https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.83.9 

Are they obsoleted in the future ??

**Comment by emendelson** [comment]
Look at the third paragraph of text on this page:

https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.83.9

**Comment by joncampbell123** [comment]
They're building now. The build process for the MinGW binaries takes *hours* because Windows 10 has found ways to make MinGW really slow.

**Comment by Wengier** [comment]
@skywind3000 The MinGW builds are ready now, along with the Windows installer.

**Comment by skywind3000** [comment]
Thanks, 
so this should be closed.

**Comment by skywind3000** [comment]
consider setup a CI task ??
