### ISSUE TITLE
0.83.9 DOS build doesn't run

### ISSUE THREAD

**Issue by KormaX-of-DOS** [joncampbell123/dosbox-x#2145]
Hello,

I tried to update to 0.38.9 under DOS but it doesn't work with the msvcrt.dll provided in the package nor could I effectively replace the file with another version. It doesn't work out of the box and it doesn't run with any of my settings either.

The error message with the .dll you distributed:

DPMILD32: import not found: _fstat64
DPMILD32: file msvcrt.dll
DPMILD32: z:\d\msvcrt.dll: cannot resolve imports

Other versions of msvrt.dll gave even more catastrophic errors while trying to call imports from ntdll.dll or other files mostly non-existent in HX and no matter which combinations of .dll files I tried to add (works sometimes) I didn't manage DOSBox-X.EXE to run.

Here's the error message with your msvcrt.dll setting DPMILDR=128:

LOG: Early LOG Init complete
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 0.83.9 (Windows SDL1)
LOG: Windows keyboard layout ID is 0x0409
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
DPMILD32: unresolved import called dkrnl32: exception 80000003, flags=0 occured at EF:2EA7                 ax=3BC4658 bx=0 cx=3F60A38 dx=790000
          si=3BC75FC di=3F62F40 bp=3BC7ED8 sp=3BC463C
          [eip] = FF 00 00 00 00 00 00 00 00 00 00 00
          [esp] = 00A918F1 00000000 00000000 00A845D0 03BC4658 03E7BE30
dkrnl32: fatal exit!

Thank you for your work on this project.

Regards:
KormaX

**Comment by Wengier** [comment]
@KormaX-of-DOS I was certainly aware of this, which was why I did not post it in the DOSBox-X website. An updated HX-DOS build is now ready, which I have verified to work by myself. So please check it out:

[osbox-x-mingw-hx-dos-20210102130253.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.9/dosbox-x-mingw-hx-dos-20210102130253.zip)

**Comment by KormaX-of-DOS** [comment]
Thank you! It works perfectly.
