### ISSUE TITLE
dosbox-x compile issue, please help

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#216]
```

Making all in fpu
make[3]: Entering directory '/home/toddbrowser/Downloads/dosboxdownload/dosbox-x-64bit/12jul2016/dosbox-x/src/fpu'
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -std=gnu++11   -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -g -O2 -Wall -mmmx -msse -msse2 -D_FILE_OFFSET_BITS=64 -Wno-strict-aliasing  -std=gnu++11   -MT fpu.o -MD -MP -MF .deps/fpu.Tpo -c -o fpu.o fpu.cpp
In file included from fpu.cpp:45:0:
fpu_instructions.h: In function ‘void FPU_FCOM(Bitu, Bitu)’:
fpu_instructions.h:457:27: error: ‘isinf’ was not declared in this scope
   if (isinf(fpu.regs[st].d) && isinf(fpu.regs[other].d)) {
                           ^
fpu_instructions.h:457:27: note: suggested alternative:
In file included from fpu_instructions.h:324:0,
                 from fpu.cpp:45:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
Makefile:346: recipe for target 'fpu.o' failed
make[3]: *** [fpu.o] Error 1

```

I posted in another thread but wasn't sure it would be noticed, so I made this one.

I'm running ubuntu 16.04 aswell, 

any help with this?

**Comment by joncampbell123** [comment]
The "man" page for isinf says that you need to include math.h and link with -lm.

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       fpclassify(), isfinite(), isnormal():
           _XOPEN_SOURCE >= 600 || _ISOC99_SOURCE || _POSIX_C_SOURCE >= 200112L;
           or cc -std=c99
       isnan():
           _BSD_SOURCE || _SVID_SOURCE || _XOPEN_SOURCE || _ISOC99_SOURCE || _POSIX_C_SOURCE >= 200112L;
           or cc -std=c99
       isinf():
           _BSD_SOURCE || _SVID_SOURCE || _XOPEN_SOURCE >= 600 || _ISOC99_SOURCE || _POSIX_C_SOURCE >= 200112L;
           or cc -std=c99

http://linux.die.net/man/3/isinf

**Comment by joncampbell123** [comment]
What I mean in the previous post is that somewhere in the configure.ac script or global build flags DOSBox-X will have to define _POSIX_C_SOURCE or another one of those #defines to declare itself compliant with recent POSIX standards to reliably use isinf()

**Comment by toddfraser88** [comment]
I put this in the "too hard" basket and moved back to 14.04

**Comment by Danfun64** [comment]
I am affected by this issue as well, and in my opinion, not fixing an issue that affects newer versions of the Ubuntu is fairly serious. I just tried using 14.04 but found it too old.

**Comment by joncampbell123** [comment]
Try adding #include <math.h> to the top of fpu.h and make sure that something defines _POSIX_C_SOURCE >= 200112L.

see "man isinf" for how it's supposed to work.

**Comment by Danfun64** [comment]
Tried it.....

Making all in fpu
make[3]: Entering directory '/home/danfun64/Documents/dosbox-x/src/fpu'
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -std=gnu++11   -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -g -O2 -Wall -mmmx -msse -msse2 -D_FILE_OFFSET_BITS=64 -Wno-strict-aliasing  -std=gnu++11   -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -MT fpu.o -MD -MP -MF .deps/fpu.Tpo -c -o fpu.o fpu.cpp
In file included from fpu.cpp:47:0:
fpu_instructions.h: In function ‘void FPU_FCOM(Bitu, Bitu)’:
fpu_instructions.h:457:27: error: ‘isinf’ was not declared in this scope
   if (isinf(fpu.regs[st].d) && isinf(fpu.regs[other].d)) {
                           ^
fpu_instructions.h:457:27: note: suggested alternative:
In file included from fpu_instructions.h:324:0,
                 from fpu.cpp:47:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
Makefile:346: recipe for target 'fpu.o' failed
make[3]: *** [fpu.o] Error 1

**Comment by joncampbell123** [comment]
Use 'man isinf' to determine what feature macros are required for Ubuntu. I dont know why it differs from what is standard glibc behavior according to man pages on my system.

https://linux.die.net/man/3/isinf

**Comment by Danfun64** [comment]
https://linux.die.net/man/3/isinf and 'man isinf' look pretty much the same to me.
Here is the man isinf of my Ubuntu 16.04 system: https://paste.debian.net/906355/

**Comment by joncampbell123** [comment]
I'm not really sure what Ubuntu is doing differently, but see if defining the feature macros listed in the man page helps to allow linking to "isinf"

**Comment by box-tortoise** [comment]
Noted this on Ubuntu 16.04 (gcc 5.3), although unknown whether it is the cause of the above:
https://bugs.freedesktop.org/show_bug.cgi?id=95562

Results in:
‘isinf’ was not declared in this scope
     if (isinf(cpu_data[index])){

And the fix for that above bug. Prepend "std namespace" to isnan and isinf calls:
https://cgit.freedesktop.org/beignet/commit/?id=14bd8855dddcf683df8138c1062bc65b05d46f94

It's not fair that you should support all gcc versions, in any case. :)
