### ISSUE TITLE
Bulding DOXBox-X with MinGW on Windows XP

### ISSUE THREAD

**Issue by ant-222** [joncampbell123/dosbox-x#2161]
Can you please help me bulid *DOSBox-X* on *Windows XP* using *MinGW*? @Wengier has already made it compile on my system by commenting out some code and providing his own libraries. Now I should like to build it out-of-the-box. I did the following:

1. installed a shining new version of [*MinGW*](http://mingw.org/) from scratch.
2. cloned the repository:

        $ git clone -b master --single-branch git@github.com:joncampbell123/dosbox-x.git dosbox-x
3. changed to `dosbox-x/`,
4. ran ` ./build-mingw 1>out.txt 2>err.txt`.

No `dosbox-x.exe` appeared under `src\`, yet I see no error in [`err.txt`](https://pastebin.com/raw/VpFc6Sik)—only warnings, and here is [`out.txt`](https://pastebin.com/raw/LL60E4fj).

**Comment by joncampbell123** [comment]
It gave up while building SDL1?

Somehow I think out.txt got truncated.

Can you see what it says if you do NOT pipe stdout/stderr to a file?

**Comment by ant-222** [comment]
@joncampbell123 
> It gave up while building SDL1?

Yes.

> Somehow I think out.txt got truncated.

I have checked it as well as I could and found no evidence of trunation. When I try this line manually:

    gcc -g -O2 -Iinclude -I/home/Ant/dosbox-x/vs2015/sdl/include -D_GNU_SOURCE=1 -Wall -c /home/Ant/dosbox-x/vs2015/sdl/src/loadso/win32/SDL_sysloadso.c -o build/SDL_sysloadso.o

I get:

    adso.c:22:10: fatal error: SDL_config.h: No such file or directory
       22 | #include "SDL_config.h"

Futhermore, `git status` says:

    deleted:    vs2015/sdl/include/SDL_config.h

I have already told Wengier about it—the build process involves the removal of a versioned file! I think this is very bad manners, and all versioned files should be sacred to the build system.

> Can you see what it says if you do NOT pipe stdout/stderr to a file?

The same thing as long as I as my terminal buffer will scroll up...

**Comment by ant-222** [comment]
The same thing happens if I change to `~/dosbox-x/vs2015/sdl` and run:

    ./build-dosbox.sh 1>out.txt 2>err.txt

`err.txt` is the same as before. The only suspicious line in it is this:

    libtool: ignoring unknown tag RC

Can it be the reason of the failure?

**Comment by ant-222** [comment]
@joncampbell123, you were right after all: `out.txt` was truncated. When I filtered the output before writing it to a file:

    build-dosbox.sh | grep -v libtool > outf.txt

it received further messages. This is does not seem to be a problem with DOSBox-X.

**Comment by ant-222** [comment]
Problem solved. All I had to do was:

1. Disable as many features as possible in the configure script
2. Change the greedy `make -j` to `make -j1` in the build scripts for *DOSBox-X* and *SDL1*.
