### ISSUE TITLE
CD audio issue with "binary format" ISOs

### ISSUE THREAD

**Issue by DSN9990** [joncampbell123/dosbox-x#2162]
**Describe the bug**
CD audio does not loop correctly in at least two games I tested (Alien Trilogy and Powerslave, maybe others also.)

**To Reproduce**
1. Install and launch game (either Alien Trilogy or Powerslave)
2. Start a new game
3. Wait until CD track 1 (ingame) finishes playing
4. The music stops playing immediately and does not loop anymore. However if you go back to the title screen (in Alien Trilogy), the main menu track plays fine.

**Expected behavior**
CD audio should loop fine (in these two games I mentioned above) like in other games I tested (such as MechWarrior 2: 31st Century Combat, Grand Theft Auto, etc).

**Additional context**
I believe the problem is due to the ISO dump I have. It's this format:

![isodump](https://user-images.githubusercontent.com/69558812/103721515-9b18e000-4fac-11eb-8ab2-9c4b4a991bf4.PNG)

Links to the two games I tested:
[https://archive.org/details/AlienTrilogyUSA](url)
[https://archive.org/details/PowerslaveUSA](url)

**Comment by Wengier** [comment]
@DSN9990 Thanks for reporting. There is indeed some issue and I will look at.

**Comment by DSN9990** [comment]
Update: Also found that the main menu track (Alien Trilogy) doesn't loop (stops playing immediately, leaving just sound effects).

**Comment by DSN9990** [comment]
@Wengier Can you fix this now? The CD audio issue occurs only with the binary format above, so it would be good to fix this issue anyway.

**Comment by kcgen** [comment]
Hi @DSN9990,

I am the last person to touch the CD audio handling code (working up from the excellent baseline from the Dosbox Team), so will be happy to look at this. 

I unfortunately don't have either of those games in that exact binary format. Is there an archive source you can point me to, or can we coordinate further? You can reach me on the DOSBox Staging Discord channel, if that helps.

**Comment by DSN9990** [comment]
@kcgen Thanks for fixing this issue! Now it should work properly as expected. So @Wengier, can you compile the latest code for a MinGW 64bit SDL2 build?

**Comment by Wengier** [comment]
@kcgen Many thanks for the fix in PR #2475.

@DSN9990 You can try the DOSBox-X 64-bit MinGW SDL2 binary based on the latest code below:

* [dosbox-x-mingw64-sdl2.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64-sdl2.zip)
