### ISSUE TITLE
DOSBox-X Fails to Launch

### ISSUE THREAD

**Issue by aaykut** [joncampbell123/dosbox-x#2163]
**Describe the bug**
Cannot run DOSBox-X, it fails to launch with message "The application dosbox-x can't be opened"

**To Reproduce**
1. Unpacked "dosbox-x-macosx-x86_64-20201231203002.zip"
2. Attempted to run "dosbox-x" app from dosbox-x/ 
3. See error messsage

**Expected behavior**
App launches and runs as expected

**Screenshots**

![image](https://user-images.githubusercontent.com/5464592/103800607-9ab72e00-501a-11eb-8151-5aa9b24e8949.png)

**Environment (please complete the following information):**
 - MacOS 10.15.7 (19H114) Catalina
 - Downloaded latest dosbox-x-macosx-x86_64-20201231203002.zip from web site
 - Used configuration, e.g. ```dosbox-x.conf``` - NONE

**Additional context**
Error persists if I run this or the sdl2 version, either from the unpack or Applications directory.

**Comment by Wengier** [comment]
In case you downloaded earlier, could you download the file again and see if it helps?

If it still does not run from the Finder, can you please try run it from the command-line instead? Just go to the directory ```dosbox-x/dosbox-x.app/Contents/MacOS``` (SDL1) or ```dosbox-x-sdl2/dosbox-x.app/Contents/MacOS``` (SDL2) and run the DosBox binary directly. Hope this helps.

**Comment by wmwragg** [comment]
I'm having the same issue with the ARM version. I get the following dialog:

<img width="328" alt="Screenshot 2021-01-07 at 11 01 40" src="https://user-images.githubusercontent.com/327409/103885425-e8de3700-50d7-11eb-941b-5332fe5fb8e2.png">

I've tried re-downloading, and opening from the command line, but just keep getting this error.

**Comment by aaykut** [comment]
Thanks @Wengier -- I have re-downloaded "dosbox-x-macosx-x86_64-20201231203002.zip" as suggested, and it seems to work now; I have managed to run it directly from Finder.

**Comment by Wengier** [comment]
@wmwragg The ARM version is not signed, only the Intel version. If you need signed macOS package please check out the Intel version for now.

**Comment by Wengier** [comment]
@wmwragg I don't think signing is really required however. Other users have suggested commands like ```xattr -cr dosbox-x.app``` to solve the problem. The ARM package is probably preferred in such case.
