### ISSUE TITLE
Quick Launch Program doesn't work on DOSBox-X 0.83.9 MinGW

### ISSUE THREAD

**Issue by OltScript313** [joncampbell123/dosbox-x#2165]
**Describe the bug**
Quick Launch Program literally doesn't work

**To Reproduce**
1. Go to 'DOS'
2. Click on 'Quick Launch Program'

**Environment (please complete the following information):**
 - Windows XP x64 SP2
 - DOSBox-X 0.83.9 MinGW SDL1 (64-bit)

**Additional context**
Quick Launcher works with DOSBox 0.83.9 Win64 in Windows 7....

**Comment by Wengier** [comment]
Yes, I can confirm this on Windows XP. Looks like a backward compatibility issue with the tinyfd library, since it works on later versions of Windows.

**Comment by vareille** [comment]
I've just made some modification to tinyfiledialogs to be compatible with windows XP. Can you try the new version 3.8.5 ? thanks

**Comment by Wengier** [comment]
It is already fixed in #2196.

**Comment by Wengier** [comment]
The feature in both 32-bit Visual Studio (patched) and MinGW builds of DOSBox-X 0.83.10 should now work in Windows XP.
