### ISSUE TITLE
"messages.txt" Broken translation system

### ISSUE THREAD

**Issue by Dalekamistoso** [joncampbell123/dosbox-x#2173]
Hi, the problem is the following:

I am working on a spanish translations for DosBox-X and I found that some texts are not replaced with the ones in "messages.txt".

All tests are being made under Windows 10 LTC x64 version (spanish language)

I generated a clean language file using the gui, following the procedure described  in the documentation:

Main->Configuration Tool->Configuration->Save language file->(I introduced default name "messages.txt")

I am editing the file "messages.txt" using OEM-US text codification plus two more in order to check mistakes. 

But the text chains contained inside the section

":SHELL_STARTUP_BEGIN2" 

Are ignored and no matter what I write, DosBox-X ignores it and  force its internal english names breaking the texts.

I attach you a screenshot for better explanation, I use a default dosbox.conf config file with the only modification of:

language=message.txt

![DOXBOX-X BUG001](https://user-images.githubusercontent.com/67012746/104067299-30151680-5203-11eb-9aec-59dbbcf0abfb.png)

I found this behaviour in the version 0.83.9 in all x86/x64 VSBuilds (both SDL1 & SDL2 )

Also I found that mingw builds have an additional bug that adds an extra CR/LF plus the mentioned one:

![DOXBOX-X BUG002](https://user-images.githubusercontent.com/67012746/104068043-88004d00-5204-11eb-9c48-b8ad063af249.png)

Thanks in advance for your patience and for your hard work!

**Comment by Wengier** [comment]
@Dalekamistoso Thanks for reporting this! Yes, there is a bug there which I just fixed. Please check out the updated Windows binary below:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Thanks for your support!

**Comment by Dalekamistoso** [comment]
Solved by Wengier, thank you very much!
