### ISSUE TITLE
No audio for any game when using DOSBox-X snap; issue does not repro when using DOSBox 0.74-3 with same settings 

### ISSUE THREAD

**Issue by skipcress** [joncampbell123/dosbox-x#2177]
I installed the DOSBox-X snap application on Ubuntu 20.04, and can't get audio to work for any game. I also have regular DOSBox 0.74-3 installed on my machine, and using the exact same config file settings it works fine. Here's the output of "snap connections dosbox-x":

Interface | Plug | Slot | Notes
-- | -- | -- | --
**audio-playback** | **dosbox-x:audio-playback** | **:audio-playback** | -
desktop | dosbox-x:desktop | :desktop | -
desktop-legacy | dosbox-x:desktop-legacy | :desktop-legacy | -
home | dosbox-x:home | :home | -
network | dosbox-x:network | :network | -
network-bind | dosbox-x:network-bind | :network-bind | -
opengl | dosbox-x:opengl | :opengl | -
removable-media | dosbox-x:removable-media | :removable-media | manual
unity7 | dosbox-x:unity7 | :unity7 | -

My sound card is: "Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series] (rev 01)"

My config file contents are copied from my DOSBox 0.74-3 config file, which is mostly just left at the defaults, with the following exceptions:

output=overlay
aspect=true
cycles=fixed 30000
prebuffer=80

...after that I'm just mounting drives and configuring local variables for Windows 3.1.

**Comment by rderooy** [comment]
The DOSBox-X team has nothing to do with the snap package. I suggest you report the issues here: https://github.com/snapcrafters/dosbox-x

Alternatively, you may want to checkout the flatpak package. https://flathub.org/apps/details/com.dosbox_x.DOSBox-X

**Comment by skipcress** [comment]
My apologies, didn't realize that. Will do, thanks!
