### ISSUE TITLE
Access host environmental variables?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2189]
Possibly DOSBox-X already does this, but, if so, I can't find it.

One reason I use vDos for many of my DOS-based applications is that vDos gives me access to all Windows environment variables, so I can run batch files that use Windows %TEMP% and any environment variable that I've set in the host environment. I realize that this is difficult to implement for all the hosts that DOSBox-X support, but (if it isn't there already) it would be useful to have.

Apologies for wasting bandwidth if this is already a DOSBox-X feature.

**Comment by rderooy** [comment]
I'm fairly certain it is not supported.

Not sure how I feel about it, not too much of a fan. If this is added, I think it should be disabled by default, and also if you have securemode active it should be disabled.

**Comment by joncampbell123** [comment]
@emendelson Did you know on Linux systems, that would expose the DOS guest to things like your username, your shell settings and macros, and if your in an SSH session, a SSH session ID and hostname?

All those environment variables from your host would also consume conventional memory PER MS-DOS PROCESS (in the environment segment), which could cause "out of memory" errors for a game or application.

I'm fine with that if it's off by default, and there are command line options to either enable all, or selectively list which environment variables to allow into the guest DOS environment.

**Comment by jharrison03** [comment]
I don't understand why this would be a security issue.  Every program run under the parent shell has access to these variables.  There's nothing unique about DOSBox-X in this regard.  Anyway, DOSEmu allows for this through the use of a utility (SYSTEM.COM) and I find it to be useful if you're using the emulator for stuff other than games.

**Comment by joncampbell123** [comment]
It's entirely possible the user may have something in their environment block they'd rather not share. Also every environment variable added to the environment block in the MS-DOS application consumes conventional memory, and it is replicated every time a new process spawns. which can turn a setup that works into one where the DOS game does not have enough memory to run.

It's better if the DOS environment inside is isolated from the host as much as possible except for what you allow.

**Comment by emendelson** [comment]
This feature could be turned off by default, but, again, the environment is available to every other application running in your OS. Perhaps the configuration could include a list of variables that DOSBox-X would inherit from the host?

In vDos, host environment variables look like this: %%COMSPEC%% while internal vDos variables look like this: %COMSPEC%. In my WordPerfect vDos system, this makes many things extremely easy that require complex workarounds in my DOSBox-X-based system. I set a group of variables before launching vDos and then use those variables in batch files, WordPerfect macros, etc., etc.

**Comment by rderooy** [comment]
Making this optional and limiting it to only named environment variables seems sensible.

**Comment by jharrison03** [comment]
> Making this optional and limiting it to only named environment variables seems sensible.

But I don't even do this for my web browser (Firefox), which also has access to the environment.

**Comment by emendelson** [comment]
Another thought: In my vDos-based system, I use an AutoIt launcher to feed environment variables to vDos itself, so someone can drop a file on the AutoIt launcher and the launcher can feed the path to vDos. 

DOSBox-X could do this kind of thing directly if it had an option to create a environment variable with the path of a file dropped on the executable.

**Comment by JoeC4281** [comment]
Maybe something could be done along the lines of what [MS-DOS Player](http://takeda-toshiya.my.coocan.jp/msdos/index.html) does, that is,

```
Usage: MSDOS [-b] [-c[(new exec file)] [-p[P]]] [-d] [-e] [-i] [-m] [-n[L[,C]]]
             [-s[P1[,P2[,P3[,P4]]]]] [-vX.XX] [-wX.XX] [-x] (command) [options]

	-d	pretend running under straight DOS, not Windows
	-e	use a reduced environment block

```
Just a suggestion.

Joe

**Comment by jharrison03** [comment]
If someone is really that concerned, then I guess what variables can be exported could be defined in the configuration file.

Again, I bet nobody thinks twice about running a web browser, etc. that has access to the parent environment.  A compiler that has access to this is potentially a hypothetical nuclear weapon.  Maybe we should all be concerned about that, and there's certainly a very valid argument for that.  This might be philosophy and not computer science.  But using a DOS emulator as an attack vector certainly wouldn't be my first way to make entry into a system.  YMMV, of course.

**Comment by Wengier** [comment]
@emendelson With the code in #2190 DOSBox-X will now resolve paths in [config] section, so that Windows environment variables such as %COMSPEC% there will be resolved. With this you can for instance include a list of variables that DOSBox-X would inherit from the host.

For example, you could set the following in the config file:

[config]
SET WIN_COMSPEC=COMSPEC: %COMSPEC%
And then %COMSPEC% will be expanded to the actual Windows environment variable.

This will only work for [config] section, not inside DOSBox-X for reasons such as security, but it will hopefully good enough for our purpose.

**Comment by Wengier** [comment]
An updated Windows binary with this enabled is also available from:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by emendelson** [comment]
Thank you, Wengier. This is perfect.
