### ISSUE TITLE
CDRom not showing whe booted into win98?

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#219]
I'm sure I'm missing something, but the CDRom drive doesn't show up when i boot into win98

imgmount 0 "/home/awesome/WIN98VM/WIN98C/WIN98C.IMG" -t floppy -fs none
imgmount 1 "/home/awesome/WIN98VM/WIN98C/pro98m.img" -t floppy -fs none
imgmount 2 "/home/awesome/WIN98VM/win98hdd.img" -t hdd -fs none
imgmount d "/home/awesome/WIN98VM/win98cd/Windows 98SE/windows98se.iso" -t iso -fs iso

have i missed anything?

**Comment by joncampbell123** [comment]
you need to specify the -ide parameter with imgmount.

I recommend -ide 2m to put the CD-ROM drive on the secondary IDE controller as master.

**Comment by toddfraser88** [comment]
so 
imgmount d "/home/toddbrowser/WIN98VM/win98cd/Windows 98SE/windows98se.iso" -t iso -fs iso -ide 2m

is this right?

**Comment by joncampbell123** [comment]
That's right.

Also make sure your dosbox.conf enables IDE emulation, both primary and secondary controllers, and that the "v86 hack" for Windows 95/98 is on.

**Comment by toddfraser88** [comment]
that worked, thanks very much

**Comment by aybe** [comment]
TODO add to FAQ then close ?
