### ISSUE TITLE
Enhance windowposition option

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2193]
The new windowposition option is extremely useful, but it could be even more useful if it could reflect the size of the current screen. For example, it would be very useful to have something like this:

`windowposition=(screenwidth/2 -200), 50`

Or, perhaps even something like this, which adjusts for the actual size of the window:

`windowposition=(screenwidth/2 -(windowwidth/2)), 50`

I'm sure someone else can come up with better syntax, but I hope the idea is worth thinking about.

**Comment by Wengier** [comment]
@emendelson Implementing this directly from the config file will make the windowposition option very complicated, adding the ability to evaluate mathematical expressions, DOSBox-X constants, and more. However, I decided to go with a different approach, by making it possible to change the windowposition setting directly from DOSBox-X's DOS shell, and adding ability to get the screen/width width and height from the command-line, as well as adding a calculator. With these you should be able to achieve the result, using a command-line tool like [NSET](https://github.com/joncampbell123/dosbox-x/files/5825824/NSET.ZIP) to get the intermediary result to an environment variable like %result%. For example:

```
config -get screenwidth | nset result=$1
eval %result%/2-200  | nset result=$1
config -set windowposition=%result%,50
```

Hope this helps.

**Comment by emendelson** [comment]
Thank you again, @Wengier! This is a very flexible solution. Closing this now.
