### ISSUE TITLE
Monochrome/VGA Multi-Screen Emulation

### ISSUE THREAD

**Issue by oitofelix** [joncampbell123/dosbox-x#2197]
Are there plans to implement [this](https://www.vogons.org/viewtopic.php?f=32&t=26110)?  It seems there were working patches for DOSBox [here](https://www.vogons.org/viewtopic.php?p=269328#p269328).

**Comment by joncampbell123** [comment]
There are. At least my idea is to use SDL2 multi-window capabilities to do so.

**Comment by Wengier** [comment]
I have already implemented this by adapting the patch. It should work on both SDL1 and SDL2 builds, but later on SDL2 multi-window capabilities may be added for further enhancement of the feature on SDL2 build. Right now it is enabled on debug builds only since it requires the pdcurse library.

**Comment by Wengier** [comment]
This is already supported in DOSBox-X version 0.83.10. Further information may be found in Issue #1075.
