### ISSUE TITLE
Garbled mouse cursor in FS98 where switching from software renderer to direct3d via Voodoo emulation

### ISSUE THREAD

**Issue by box-tortoise** [joncampbell123/dosbox-x#221]
Is this issue similar to that of commit eb0dbf8 where the mouse cursor was fixed by first clearing and removing it?

**Comment by joncampbell123** [comment]
I guess.... but if the 3D acceleration is on the Voodoo why should it have any effect on the VGA emulation.

Remember that 3Dfx implemented their accelerated output as an entirely separate card you pass the VGA through, and when it's activated by the driver, it cuts out the VGA card and feeds it's own signal to the monitor. I have a Voodoo Banshee in a test system that works exactly that way.

**Comment by box-tortoise** [comment]
That must be true. The mouse cursor is not clearing in d3d mode, but it functions and seems to change shape as expected for certain mouse-over events. Could the issue be related to uncleared memory in some region?

**Comment by box-tortoise** [comment]
Verified that the issue only occurs with the voodoo setting to opengl, but there is no issue when voodoo=software.

**Comment by box-tortoise** [comment]
If "voodoo_ogl_draw_pixel" in voodoo_opengl.cpp is disabled, then the mouse cursor does not appear. So the issue must be along the pixel pipeline in the opengl path, probably late in the path since the software path draws the cursor correctly.

**Comment by box-tortoise** [comment]
I think the cursor drawing is to the rgb buffer. My only guess is that the game is reading the cursor from a buffer which contains a malformed cursor in the opengl path. I don't know where the cursor is read from.

Also, the garbled cursor is actually a mouse cursor in all cases, but it appears that sections of the cursor are missing and sometimes displaced along the y-axis.

**Comment by box-tortoise** [comment]
Found one possible solution to the issue.
`--- voodoo_emu-orig.cpp	2016-07-28 04:26:01 -0400
+++ voodoo_emu.cpp	2016-07-28 04:36:35 -0400
@@ -2230,10 +2230,10 @@ void lfb_w(UINT32 offset, UINT32 data, U
 					if (has_rgb || has_alpha) {
 						// if enabling dithering: output is 565 not 888 anymore
 //						APPLY_DITHER(v->reg[fbzMode].u, x, dither_lookup, sr[pix], sg[pix], sb[pix]);
-						voodoo_ogl_draw_pixel(x, scry+1, has_rgb, has_alpha, sr[pix], sg[pix], sb[pix], sa[pix]);
+						voodoo_ogl_draw_pixel(x, scry, has_rgb, has_alpha, sr[pix], sg[pix], sb[pix], sa[pix]);
 					}
 					if (has_depth) {
-						voodoo_ogl_draw_z(x, scry+1, sw[pix]);
+						voodoo_ogl_draw_z(x, scry, sw[pix]);
 					}
 				} else {
 					/* write to the RGB buffer */
@@ -2589,7 +2589,7 @@ void lfb_w(UINT32 offset, UINT32 data, U
 				if (v->ogl && v->active) {
 					if (FBZMODE_RGB_BUFFER_MASK(v->reg[fbzMode].u)) {
 //						APPLY_DITHER(FBZMODE, XX, DITHER_LOOKUP, r, g, b);
-						voodoo_ogl_draw_pixel_pipeline(x, scry+1, r, g, b);
+						voodoo_ogl_draw_pixel_pipeline(x, scry, r, g, b);
 					}
 /*					if (depth && FBZMODE_AUX_BUFFER_MASK(v->reg[fbzMode].u)) {
 						if (FBZMODE_ENABLE_ALPHA_PLANES(v->reg[fbzMode].u) == 0)
`
I haven't tested outside fs98, however. Perhaps another d3d5 or d3d6 game, such as Jedi Knight, would verify that the change is ok. The dosbox-x window should be verified as not losing a line of pixels above or below the viewport. Also, there are other uses of scry+1 in this source file, but the first change above is necessary whereas the above second change is not relevant to the above issue but follows from the first change. Another solution is the to revert only the rounding error fix for y2 in voodoo_ogl_draw_pixel, but I think the above is the more correct solution.

**Comment by box-tortoise** [comment]
I now think the above code changes are reasonable to apply. First, the fs98 mouse cursor is fixed (and presumably for other direct3d software which is sensitive to exact placement of pixels). Second, Jedi Knight in direct3d mode is drawing pixels correctly. Third, the changes are consistent with a prior commit for handling "rounding error" in the opengl-based Voodoo emulation. I can also create a commit for this soon.
