### ISSUE TITLE
Does the Apple MacOS ARM version use any x86 code or is it fully native?

### ISSUE THREAD

**Issue by sofakng** [joncampbell123/dosbox-x#2210]
I'm extremely happy to see that there is a version of this for the Apple M1 (ARM) chip.

Does the dynamic (re)compiler also use ARM instructions?  (ie. is this fully 100% native to M1/ARM or does it use any x86 calls that are going through Rosetta, etc?)

**Comment by joncampbell123** [comment]
The dynamic core as imported can recompile to ARMv7 and ARMv8, yes.

**Comment by sofakng** [comment]
Glad to hear it, thanks!

Does that mean everything under Dosbox-X is running under ARM (ie. native) then?

**Comment by joncampbell123** [comment]
Correct. I'm not aware of any published API for ARM MacOS applications to run x86 code on a whim.

**Comment by sofakng** [comment]
Thanks a bunch!
