### ISSUE TITLE
Alternate OPL3 emulation for dosbox-x?

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#222]
Patch is here:
https://www.vogons.org/viewtopic.php?f=32&t=49327

Would this be an addition that is of interest to the project?

**Comment by joncampbell123** [comment]
Go ahead, as long as it's not default, but selectable in the dosbox.conf.

**Comment by box-tortoise** [comment]
Thanks. I'll add it and then you can always revert it if it isn't worthwhile.

**Comment by box-tortoise** [comment]
Committed it as an optional patch at /dosbox-x/patch-integration/opl3_accurate.diff. I'll try to find cases which show it is a necessary addition.

**Comment by joncampbell123** [comment]
This has been integrated.
