### ISSUE TITLE
With HDPMI32 single-stepping in Protected Mode with lDebugX fails

### ISSUE THREAD

**Issue by ecm-pushbx** [joncampbell123/dosbox-x#2221]
Originally reported to DOSBox at https://sourceforge.net/p/dosbox/bugs/544/

**Describe the bug**
When trying out a DPMI example (dpmimini.com) running with a DPMI host (HDPMI32) in a DPMI debugger (lDebugX), single-stepping in Protected Mode fails to work. Instead of the expected single-step operation occurring in Protected Mode, execution falls back to Real 86 Mode in some sort of handler that appears to belong to the DPMI host.

**To Reproduce**
HDPMI32.EXE is from https://github.com/Baron-von-Riedesel/HX/releases/tag/v2.19pre5

The test files can be found in https://ulukai.org/ecm/test/20210127.zip or can be built from https://hg.ulukai.org/ecm/ldebug and https://hg.ulukai.org/ecm/dpmitest

Attached: [20210127.zip](https://github.com/joncampbell123/dosbox-x/files/5880536/20210127.zip)

Now enter the following:

```
flatpak run com.dosbox_x.DOSBox-X
keyb gr
(mount C: as directory containing test files)
C:
hdpmi32 -r
ldebugx.com dpmimini.com
g
g 16C
t
```

**Expected behavior**
Expected: Trace step instruction at 0000_016Ch and register dump of next instruction (at 0000_0172h) while still in Protected Mode.

Actual: Execution ends up so that the dump occurs at CS:IP = 0820h:02EAh in Real 86 Mode, which appears to be in some handler of HDPMI. Subsequent "G" commands to the debugger end up giving "Unexpected single-step interrupt" messages and dumping at the same CS:IP, though register values change and it appears every 5 runs one letter of the "Welcome in 32-bit protected mode" message is displayed.

**Screenshots**
https://ulukai.org/ecm/test/20210127-2.png

**Environment (please complete the following information):**
 - Debian 11 amd64
 - DOSBox-X 0.83.9 (flatpak)

**Comment by Wengier** [comment]
Below is the result I got when I ran it in a real MS-DOS system:

```
C:\LDEBUG>ldebugx.com dpmimini.com
-g
DPMI entry hooked, new entry=06BC:7BAE
Protected mode breakpoint at 015Ah.
32-bit code segment breakpoint at 016Ch.

Unexpected breakpoint interrupt
AX=0200 BX=0020 CX=0105 DX=000A SP=FFFC BP=0000 SI=0269 DI=7BAE
DS=1ED1 ES=2ED2 SS=1ED1 CS=1ED1 IP=013B NV UP EI PL ZR NA PE NC
1ED1:013B 89E5              mov     bp, sp
-g 16C
AX=0009 BX=00BF CX=40FB DX=000A SP=FFFC BP=FFFC SI=0269 DI=7BAE
DS=008F ES=009F SS=008F CS=00BF IP=016C NV UP EI PL NZ NA PO NC
00BF:0000016C 8C0590010000  mov     dword [00000190], es   DS:00000190=6F4E0000
#t
AX=0009 BX=00BF CX=40FB DX=000A SP=FFFC BP=FFFC SI=0269 DI=7BAE
DS=008F ES=009F SS=008F CS=00BF IP=0172 NV UP EI PL NZ NA PO NC
00BF:00000172 1E            push    ds
```

Is this the result you have expected?

The only actual difference seems to be the last line - ``00BF:00000172 1E            push    ds`` vs ``0827:02EA 684C1C            push    word 1C4C`` when running in DOSBox-X.

**Comment by ecm-pushbx** [comment]
The segment registers are all different too. There is another difference, not shown in your dump: After executing the "T" command it should show EIP=0000_0172h in Protected Mode. That is, the prompt should be a # hash sign, not a - dash. (You can also use the "RV" command at that point which should tell you the current mode is PM with a 32-bit CS. In DOSBox-X it says R86M.)

**Comment by Wengier** [comment]
Of course we will always try our best to make it match the actual behavior in a real DOS system. It is hopefully fixed in #2226.

**Comment by ecm-pushbx** [comment]
Is there some way to obtain a build or do I have to build it myself to test the fix?

**Comment by rderooy** [comment]
A new release should be out soon. Typically on the 1st of the month.

**Comment by ecm-pushbx** [comment]
Updated to flatpak DOSBox-X version 0.83.10 and it works as expected. Thanks!
