### ISSUE TITLE
Menu: identify Mac Cmd key as "Cmd", not "Left meta"?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2230]
My DOSBox-X-based Mac applications use the Cmd-Option key combinations to perform some functions. On the DOSBox-X menu, the "Cmd" key is identified as "Left meta" - and I don't think any real-world user will be able to guess that that means.

Could the menu display"Win" or "Cmd" or something else, depending on the host OS, instead of "Left meta"? I realize this can't be done for the impending release, but perhaps it could be done for the next one?

**Comment by Wengier** [comment]
@emendelson Yes, this issue only occurs in the SDL1 builds, not SDL2 builds. I have already fixed this in #2231 so that Window key(s) in Windows and the Command key(s) in macOS will now be displayed as the "Windows" and "Command" keys instead of the "super" and "meta" keys.

**Comment by emendelson** [comment]
Thank you, @Wengier! Closing this now.
