### ISSUE TITLE
PC 88 support

### ISSUE THREAD

**Issue by viki-t-s** [joncampbell123/dosbox-x#2237]
Dosbox-X is a great improvement upon Dosbox. It supports PC98 already. Is it possible to add support for emulating PC88? There are a few games for PC88 which currently cannot be played in Dosbox-X

**Comment by joncampbell123** [comment]
I agree that would be a nice addition. Two things need to be implemented as far as I know:
- N88 ROM BASIC
- Z80/8080 emulation, or perhaps NEC V20 emulation, since V20s have a hardware 8080 mode in addition to 8086 level instruction set support.

**Comment by joncampbell123** [comment]
I'm also aware (through @yksoft1) that there is an 8080/Z80 PC-88 emulator program for PC-98 systems you can run those old games with as well.

**Comment by RNMB15** [comment]
The amstrad CPC also has a Z80 CPU and the CRTC (for graphic display) is identical to the Motorola 6845 controller. 

https://en.wikipedia.org/wiki/Amstrad_CPC#Video

**Comment by viki-t-s** [comment]
> I'm also aware (through @yksoft1) that there is a 8080/Z80 PC-88 emulator program for PC-98 systems you can run those old games with as well.

Thanks. Found it.
