### ISSUE TITLE
Audio Problems in Mac/ARM64

### ISSUE THREAD

**Issue by Ekamekia** [joncampbell123/dosbox-x#2239]
I've come across a few audio problems in the ARM64 build of Dosbox-x 0.83.10 for MacOS that are not present in the Intel build. (Both are using the same configuration file)
First the MT32 device fails to load. 

**Intel**
LOG: MT32: Found ROM pair in ./: MT32_CONTROL.ROM and MT32_PCM.ROM
LOG: MIDI:Opened device:mt32

**ARM**
LOG: MIDI:Cannot find device:mt32. Finding default handler.
LOG: MIDI:Opened device:coreaudio

The other problem may be related I'm not sure, It's with a program called MOD4WIN, It's a MOD tracker player I've tried it in both Windows 3.1, and Windows98, apparently is features "Direct Hardware Support". In the Intel build it works fine, in the ARM build it does not output any audio at all, while the rest of the system audio works fine.

**Comment by rderooy** [comment]
Based on the output of the ARM build, it seems the ARM binary does not have MT32 support compiled in.

**Comment by Ekamekia** [comment]
Oh. >.>
