### ISSUE TITLE
Spanish keyboard: ' and - keys are the same

### ISSUE THREAD

**Issue by Zackxs3** [joncampbell123/dosbox-x#2249]
**Describe the bug**
Like it says in the title, the keys for ' and - are considered the same in Dosbox-X, even though they should be different.

**To Reproduce**
1. Use the command keyb sp
2. Open Mapper Editor
3. Click on the "-" key
4. Press the ' key
5. See that they are the same key

**Expected behavior**
Those two keys should be different, displaying their respective symbols, instead of being the same key and displaying only the ' symbol

**Environment (please complete the following information):**
 - Operating system: Windows 10 64 bit
 - DOSBox-X release version: 0.83.10 MinGW SDL1, 64-bit

**Additional context**
I have tried other DOSBox versions and they work properly. I have only had issues with this one.

**Comment by Wengier** [comment]
DOSBox-X provides both SDL1 and SDL2 builds, and the main difference is the input handling. If you tried SDL1 build earlier, can you please try the SDL2 build and see if the problem is solved. Thanks.

**Comment by rderooy** [comment]
As @Wengier mentioned, the SDL1 and SDL2 libraries provide different input handling. The SDL1 library only really has support the the US keyboard layout, which DOSBox-X tries to work around. But it is known this is not perfect, and there are some keys on non-US keyboards that don't work properly with it.

The solution is to use a SDL2 build instead.

**Comment by Zackxs3** [comment]
It did work! Thanks a lot!
