### ISSUE TITLE
Codepage doesn't always match chosen keyboard layout unless codepage is specified

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2251]
With version 0.83.10 (tested in macOS, SDL1 and SDL2 versions), if you enter this command `keyb us` DOSBox-X correctly returns

`keyboard layout us loaded for codepage 437`

If you then enter `keyb uk` DOSBox-X again correctly returns the keyboard layout and matching codepage:

`keyboard layout uk loaded for codepage 858`

But if you then enter `keyb us` DOSBox-X changes the keyboard, but not the codepage, and returns:

`keyboard layout us loaded for codepage 858`

You need to know to enter `keyb us 437` to restore the US codepage. This isn't unreasonable, but shouldn't the `keyb` command, by default, change the codepage to match the keyboard language (as it does when you enter 'keyb uk`)?

**Comment by Wengier** [comment]
@emendelson Thanks for reporting this! It is hopefully fixed in #2247.
