### ISSUE TITLE
Default dosbox.conf contains the string Message not Found!

### ISSUE THREAD

**Issue by BPaden** [joncampbell123/dosbox-x#226]
Currently it appears there's no documentation on how dosbox-x and its configuration differs from dosbox. I know from reading around that there are some additional/different configuration options. Could we get a list of those somewhere?

Ideally there would be a dosbox-x.conf manpage distributed with the software that lists all possible values and their meaning. I believe even dosbox itself has some hidden/poorly explained options.

**Comment by joncampbell123** [comment]
There's not much documentation on how it differs, but dosbox.conf does describe what the options do. Dosbox-x is deliberately verbose on what the options do and sometimes how they differ from dosbox.

**Comment by BPaden** [comment]
> dosbox.conf does describe what the options do. 

Generally yeah, but I remember they didn't explain the difference between output modes. That might have been the only issue.

> Dosbox-x is deliberately verbose on what the options do and sometimes how they differ from dosbox.

I'm not seeing a dosbox.conf distributed with dosbox-x. Also when I open the generated dosbox.conf reported by `dosbox-x -printconf`, the only contents are `Message not Found!`. The source-tree documentation seems to still be referencing dosbox v0.74 as well.

**Comment by joncampbell123** [comment]
try bringing up dosbox-x and then typing:

config -all -wc ref.conf

It will create a ref.conf listing all of the options.

**Comment by BPaden** [comment]
That does work. So I guess the issue here is that dosbox-x is not correctly writing the default dosbox.conf file.

**Comment by Allofich** [comment]
For current DOSBox-X, at least, the .conf file seems to be fine. I see no "Message not Found!" message in my existing .conf or when making a new one with config -all -wc ref.conf.

I noticed, though, that `-printconf` doesn't seem to do anything in DOSBox-X, not that it's really needed for DOSBox-X since the .conf file is right there in the same directory as the executable. Seems like we can close this issue, though.
