### ISSUE TITLE
CTRL button not working (PC98mode)

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#2265]
**Describe the bug**
CTRL button is ignored when pressed. (Although it is recognized in "mapper editor")

**To Reproduce**
1. Start dosbox-x in PC98 mode `dosbox-x -set machine=pc98`
2. Press CTRL+C
3. Dosbox does not recognize CTRL button (Plz see figure below)
![CTRL+C in PC98 mode](https://user-images.githubusercontent.com/68574602/107841442-46b01e00-6dfe-11eb-8090-66d9a7f0471c.jpg)

**Expected behavior**
As same as in normal mode, CTRL button shall be recognized.
![normal_mode](https://user-images.githubusercontent.com/68574602/107841494-a8708800-6dfe-11eb-9f3c-0edd88760278.jpg)

**Environment (please complete the following information):**
 - Operating system: Windows 10
 - DOSBox-X release version: 0.83.10 ![dosbox-x-vsbuild-win-20210131230425.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.10/dosbox-x-vsbuild-win-20210131230425.zip)
  (same as for mingw version)
 - Used configuration: no modification in .conf file (only -set machine=pc98 on start)

**Comment by joncampbell123** [comment]
I see.

Here's a simple test, hitting CTRL+C 11 times (first row) followed by 'C' 11 times (second row).

DOSBox-X isn't paying attention to the CTRL key here.

DOSBox-X:
![int18_000](https://user-images.githubusercontent.com/6245486/107841952-6bf84a00-6d74-11eb-9830-0d6145a2f8f8.png)

Real hardware (note INT 18h returns 0x2B03 for CTRL+C and 0x2B63 for 'C'):
![IMG_20210212_205510684 jpg cut](https://user-images.githubusercontent.com/6245486/107842018-d90bdf80-6d74-11eb-8bb4-42ee419aee84.jpg)

**Comment by joncampbell123** [comment]
Try the latest commit.

**Comment by maron2000** [comment]
I managed to build the latest commit.
I hit several keys with CTRL button pressed and confirmed that it realizes whether the CTRL button is pressed.
Thanks a million!
