### ISSUE TITLE
Record locking not working in DOSBox-X 0.83.10 under Linux and MacOS

### ISSUE THREAD

**Issue by dev4inno** [joncampbell123/dosbox-x#2270]
Hello,

I am using several DOS based multi-user applications developed in MS Cobol 4.5 (same as Microfocus Cobol).
However, until now I must use DOSEMU under Linux and vDOSPlus under Windows to get the record locking working.
And: there is no MacOS solution for me so far.

That's why I like DOSBox-X. If it works, I could use the same DOS Emulator everywhere :-)

Unfortunately although announced in the changelog for release 0.83.10 the record locking does not work in this version.

To demonstrate it, I have created a small test program which creates an indexed file and locks one record (if it is unlocked). The program can be started several times and every other instance should detect the locked record and send a message.

Here is the correct behavior in DOSEMU under Debian Linux:

![DOSEMU_Linux](https://user-images.githubusercontent.com/63194871/107964184-528c1380-6fa9-11eb-94ee-7283ba866690.png)

And here is the correct behavior in vDOSPlus under Windows 10:

![vDosPlus_Windows10](https://user-images.githubusercontent.com/63194871/107964272-63d52000-6fa9-11eb-8cf8-cef418acf80b.png)

But in the second DOSBox-X instance under Debian Linux the record lock is not detected:

![DOSBox-X_Linux](https://user-images.githubusercontent.com/63194871/107964327-72bbd280-6fa9-11eb-97f8-73618c2eb97f.png)

Same error in DOSBox-X under macOS:

![DOSBox-X_mac_OS](https://user-images.githubusercontent.com/63194871/107964355-79e2e080-6fa9-11eb-91d3-7312270ad013.png)

For your own tests and to replicate the error I have attached the MS Cobol 4.5 based DOS test program (lockrec.exe) via this link:

http://www.mediafire.com/file/xy088tm6j5dvwua/lockrec.exe/file

It would be perfect if you could implement the same locking function in DOSBox-X like it is available in DOSEMU and vDOSPlus. 

Kind regards from Northern Germany!

**Comment by emendelson** [comment]
@dev4inno For macOS, you can try this Wine-packaged version of vDos (not vDosPlus); it runs under Big Sur and probably a few earlier versions, but it isn't notarized. You may need to clear extended attributes before it will run, but perhaps not.

http://www.columbia.edu/~em36/vDosMac64.zip

**Comment by dev4inno** [comment]
@emendelson Thank you for this information. However I would really appreciate if DOSBox-X offers record locking. As mentioned above: in this case I can use one (the same) DOS emulator on all platforms, which makes life much easier :-)

**Comment by emendelson** [comment]
I can confirm that vDos under Wine in macOS successfully locks the record:

<img width="1175" alt="Screen Shot 2021-02-15 at 5 18 30 PM" src="https://user-images.githubusercontent.com/5208505/107998122-6425e900-6fb2-11eb-9135-9b061624ba65.png">

**Comment by Wengier** [comment]
@dev4inno Thank you so much for posting the issue and the test program! Indeed, in DOSBox-X 0.83.10 the record locking feature was mostly coded on Windows platforms (the [release notes for 0.83.10](https://dosbox-x.com/release-0.83.10.html) says "Improved file locking on Windows systems"), so while it is confirmed to work with your test program on Windows it did not work properly with your test program on Linux and macOS. But I think I have already fixed this issue in #2273 so that it should now work on all platforms. Confirmed with your test program in Windows, Linux, and macOS platforms.

In Linux:

![image](https://user-images.githubusercontent.com/8216923/108018778-aff28580-6fe6-11eb-96f0-e70071c0b25c.png)

In macOS:

![image](https://user-images.githubusercontent.com/8216923/108018546-13c87e80-6fe6-11eb-963e-47072bfa4b70.png)

Thanks again!

**Comment by dev4inno** [comment]
@Wengier Thank you very much. That's great news!
So this fix will be included in the next DOSBox-X release (0.83.11)?

With this fix a dream will come true: one DOS emulator on each platform :-)
Thank you once again for your excellent support!!!

**Comment by Wengier** [comment]
@dev4inno Yes, it will definitely be included in the next release. Thank you too.

**Comment by mhw37** [comment]
Hi! @dev4inno - any way we can get the COBOL source code for this exe so I can modify this for our particular company?

**Comment by dev4inno** [comment]
@mhw37 I used a source from my dairy farm system and reduced the logic to output the above messages. But it contains some copy members which I cannot disclose. However, if you own a MS or MF COBOL compiler, pls. have a look at the samples delivered with the compiler. Depending on the compiler version you will find demonstration programs for file locking (e.g. MS COBOL 4.5 & 5.0 contain a multiuser demo program named MUDEMO.CBL).

**Comment by dev4inno** [comment]
Now I have downloaded and installed the new version 0.83.11.
Record locking works like a charm.
Thank you again @Wengier for your excellent support!
