### ISSUE TITLE
Problem with winrun when no 8dot3 filename entry for working directory

### ISSUE THREAD

**Issue by Andrew-D0** [joncampbell123/dosbox-x#2271]
Hi,

I've found a bug with running external programs using winrun. The Windows EXE program won't start in the very specific case that the current directory is longer than 8.3 characters and this directory does not have a short filename entry for it.
Note that this is the current working directory in DOSBox-X, not the location of the Windows EXE program.

(In case you didn't know, Windows has 8dot3name creation turned on by default on system drives but turned off by default for non-system drives. Turning 8dot3name on does not create missing 8dot3 filename entries. Turning 8dot3name off does not remove existing 8dot3 filename entries.)

I used a USB stick for testing, I created two partitions, F: with 8dot3names and G: without.
This is how I set them up for 8dot3name creation in Windows:

>C:\>fsutil.exe 8dot3name set f: 0
>Successfully enabled 8dot3name generation on f:
>
>C:\>fsutil.exe 8dot3name set g: 1
>Successfully disabled 8dot3name generation on g:

>C:\>fsutil.exe 8dot3name query f:
>The volume state is: 0 (8dot3 name creation is enabled).
>The registry state is: 2 (Per volume setting - the default).
>
>Based on the above settings, 8dot3 name creation is enabled on f:
>
>C:\>fsutil.exe 8dot3name query g:
>The volume state is: 1 (8dot3 name creation is disabled).
>The registry state is: 2 (Per volume setting - the default).
>
>Based on the above settings, 8dot3 name creation is disabled on g:

I started "dosbox-x.exe -winrun", mounted drive C: to a location with a test executable and ran the following:

`MOUNT F F:\`
`MOUNT G G:\`
`F:`
`MKDIR MORETHAN8`
`CD MORETHAN8`
`C:\TEST.EXE`
`G:`
`MKDIR MORETHAN8`
`CD MORETHAN8`
`C:\TEST.EXE`

TEST.EXE can be any Windows executable.

When running a Windows program while the current drive & directory is F:\MORETHAN8 it runs ok.
If I run the same program while the current drive & directory is G:\MORETHAN8 then does not:
>This program cannot be run in DOS mode.

DOSBox-X 0.83.10
Windows 10 20H2 64-bit
I removed dosbox-x.conf before testing, it should have been using the default configuration.

**Comment by Wengier** [comment]
Thanks for reporting this! I think I have already fixed this in the code in #2273.

**Comment by Andrew-D0** [comment]
Thanks, that's great!
I could wait for the next release but I thought I should try this out myself...
I'm using MSYS2 MingW 64-bit and compiling by running 'build-mingw'. I assume that's the correct way to build DOSBox-X... I could well be doing it wrong!

If I run "git checkout dosbox-x-v0.83.10" then it compiles ok and I get a working executable.
When I try compiling the latest commit (a5551a375c3813aa8693a744bb7bfa98b5adf185) I get an error message:

>g++  -I/home/Andrew/test/dosbox-x/vs2015/libpng/linux-host/include -std=gnu++14  -O2 -msse  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/Andrew/test/dosbox-x -I/home/Andrew/test/dosbox-x/vs2015/sdlnet/linux-host/include -I/home/Andrew/test/dosbox-x/vs2015/sdlnet/linux-host/include/SDL -mno-ms-bitfields -D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=199506L -IC:/msys64/mingw64/include/ncursesw -IC:/msys64/mingw64/include  -I/home/Andrew/test/dosbox-x/vs2015/pcap  -static -static-libgcc -static-libstdc++ -L/home/Andrew/test/dosbox-x/vs2015/libpng/linux-host/lib  -L/home/Andrew/test/dosbox-x/vs2015/sdlnet/linux-host/lib -o dosbox-x.exe dosbox.o winres.o debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a libs/decoders/internal/libopusint.a aviwriter/libaviwriter.a output/direct3d/liboutputdirect3d.a libs/xBRZ/libxbrz.a libs/mt32/libmt32.a libs/fluidsynth/libfluidsynth.a -L/home/Andrew/test/dosbox-x/vs2015/sdl/linux-host/lib -lmingw32 -lSDLmain -lSDL -mwindows -lm -luser32 -lgdi32 -lwinmm -ldxguid -lwinmm -ldsound -limm32 -lole32 -loleaut32 -lversion -lsetupapi -lSDL_net -lwsock32 -lws2_32 -lwinspool -liphlpapi -lSDL_net -lz -lpng -lz -lopengl32
>C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: shell/libshell.a(shell_misc.o):shell_misc.cpp:(.text+0x5fcc): undefined reference to `__imp_PathFileExistsA'
>C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: shell/libshell.a(shell_misc.o):shell_misc.cpp:(.text+0x60c0): undefined reference to `__imp_PathFileExistsA'
>collect2.exe: error: ld returned 1 exit status
>make[3]: *** [Makefile:467: dosbox-x.exe] Error 1
>make[3]: Leaving directory '/home/Andrew/test/dosbox-x/src'
>make[2]: *** [Makefile:527: all-recursive] Error 1
>make[2]: Leaving directory '/home/Andrew/test/dosbox-x/src'
>make[1]: *** [Makefile:400: all-recursive] Error 1
>make[1]: Leaving directory '/home/Andrew/test/dosbox-x'
>make: *** [Makefile:333: all] Error 2

**Comment by Wengier** [comment]
@Andrew-D0 I see. Can you add the option ```-lshlwapi``` at the end of the g++ command and try again? Thanks for your support.

**Comment by Andrew-D0** [comment]
Yes, that did it. I added "-lshlwapi" to src/Makefile on the end of the "LIBS = ..." line and it compiled.
Then I noticed your latest commit and re-built with that, that also works.

So I've tested DOSBox-X with the fix for long filenames and it works here.
Thanks!
