### ISSUE TITLE
Problem with Int21 0x5A Create unique file

### ISSUE THREAD

**Issue by Andrew-D0** [joncampbell123/dosbox-x#2274]
We have a program which uses Int 21 AH=0x5A to create unique/temporary files. There appear to be two problems with DOSBox-X:

The filename generation isn't random. The order is the same every time DOSBox-X is started. I think this is because the random seed isn't initialised before creating the random name.
I have found that if I use a pipe on the command-line then this initialises the random seed, presumably because of:
https://github.com/joncampbell123/dosbox-x/blob/master/src/shell/shell.cpp#L361
Once doing this the filename creation is random.

The other problem is, if I open two copies of DOSBox-X and make an Int 21 call to create a unique file in the same location (same mount point) then the second copy overwrites the first file.
I can see that DOS_CreateTempFile() is what gets called to handle the Int 21 call, and this does appear to check for existing files, but the file does get overwritten.

I don't know a simple way to call Int 21 from DOS, but I hope that's enough information to reproduce the problem.

Using DOSBox-X 0.83.10 on Windows 10 20H2 64-bit.

**Comment by Wengier** [comment]
Thanks for reporting this! It is hopefully fixed in #2276.

**Comment by Andrew-D0** [comment]
Wonderful, that does work here. (I even made initRand() return before calling srand() so I could check that it doesn't overwrite existing files.)
Thanks!
