### ISSUE TITLE
[SDL1/SDL2]Revision 13451 cannot be built: there is an error in drive_local.cpp:622:22:

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#2277]
**Describe the bug**
Hello.

I'm unable to get revision 13451 to be built. It breaks in  drive_local.cpp:622:22:

**To Reproduce**
1. grab the latest git code
2. run./ autogen.sh
3. use this configure line: ./configure --enable-core-inline --disable-debug --enable-avcodec --prefix=/usr --enable-sdl2
4. type make and wait.

**Expected behavior**
Build process stops with this error:

```
In file included from /usr/include/fcntl.h:329,
                 from ../libs/physfs/physfs_platform_posix.c:23,
                 from drive_local.cpp:54:
In function 'int open(const char*, int, ...)',
    inlined from 'virtual bool localDrive::FileCreate(DOS_File**, const char*, uint16_t)' at drive_local.cpp:622:22:
/usr/include/bits/fcntl2.h:50:24: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
   50 |    __open_missing_mode ();
      |    ~~~~~~~~~~~~~~~~~~~~^~
```

**Environment (please complete the following information):**
 - Archlinux with gcc 10.2.x
 - Commit https://github.com/joncampbell123/dosbox-x/commit/c2c97cc237f252dce2ad70803fab4a37ff701fd7

**Additional context**

My last successful revision? 13445 / commit 4b112a5c24a1716f56f2f9f18a683f046104b99e

Adding full error log.
[error.log](https://github.com/joncampbell123/dosbox-x/files/5994034/error.log)

**Comment by FredBezies** [comment]
Build process is broken with both SDL1 and SDL2 versions.

**Comment by Wengier** [comment]
@FredBezies I think this is likely specific to some Linux systems. Can you try change line 622 of drive_local.cpp from:

```int fd = open(host_name, (O_RDWR | O_CREAT));```

To:

```int fd = open(host_name, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH);```

And see if it works on your system?

**Comment by FredBezies** [comment]
Yes, it works. It was a good guess. This bug is now dead. Thanks for the fix.
