### ISSUE TITLE
Clipper program - "Cannot create VM Swap file"

### ISSUE THREAD

**Issue by Bromarin** [joncampbell123/dosbox-x#2278]
Hi,

After multiple research, i can't find any solution to my problem.

**Purpose**
Launch an old clipper financial's program.

**Environment**
- Windows 10 64bit
- dosbox-x version 0.83.11 32bits SDL1
- (i try with dosbox-x 0.83.9 64bits SDL1 too)

**Issue**
The error message : "Unrecoverable error 5311 : cannot create VM swap file" :
![image](https://user-images.githubusercontent.com/77847155/108239951-abdf7880-714a-11eb-81dc-df2304a54d39.png)

**What i've tried (my current configuration file https://pastebin.com/W5yEC0SV)**
  - set "TEMP" variable with "C:\temp"
  - increase memsize to 32/64
  - set clipper parameter with valid path (with mounted path)
  > SET CLIPPER=//F:250 //SWAPPATH:"C:\swap" //TEMPPATH:"C:\temp"

I know it's a typical clipper's problem but i tested on vDosPlus and vDos and it run correctly. The debugger left no clue in his log's file.

Thank in advance for your help.

**Comment by Wengier** [comment]
@Bromarin Thanks for reporting this! Could you send me the Clipper program so that I can reproduce and fix it? You can either upload the program here or send to [my email](mailto:wengierwu@yahoo.com). Thanks.

**Comment by Bromarin** [comment]
@Wengier Thanks for your reply. I sent you an email !

**Comment by Wengier** [comment]
@Bromarin I have taken a look at it. It appears to be a path problem in the config file. According to the config file only K:\ is mounted, but the Clipper program will try to create a temporary file in the root directory of C: drive, which does not exist and thus the error. So please make sure that the C: drive is mounted to a writable location, and then it should work. Hope this helps.

**Comment by Bromarin** [comment]
@Wengier i already tried this but i tried some variations and it finally work ! 
The solution was "mount C:\ C:\temp"...

I think i must have misunderstood something but i can finally move forward with dosbox-x.

Thanks you for your help and time !
