### ISSUE TITLE
Crash in Configuration tool in Windows if you use shift-backspace

### ISSUE THREAD

**Issue by foone** [joncampbell123/dosbox-x#2279]
**Describe the bug**
You can crash DOSBox-x by using shift+backspace in a configuration tool textbox.
Shift-Backspace itself doesn't immediately crash, but as soon as you type another letter afterwards, it crashes.
This was discovered by holding shift while typing and backspacing, like "C<BACKSPACE>D", but the capitalization of the before or after characters doesn't matter, and you don't have to hold shift the whole time.

**To Reproduce**
1. Launch DOSBOX, click Main->Configuration Tool
2. Click on SDL
3. Click on the first text box, "fullresolution"
4. Hold shift and backspace over the last letter of "desktop"
5. Type any other letter, with or without shift. 
6. DOSBox-X should crash. 

**Expected behavior**
Shift-backspace should be treated like regular backspace. That's how much GUI text boxes work, like the one I'm typing this on.

**Environment (please complete the following information):**
 - Windows 10 (10.0.19042.804)
 - DOSBox-X v0.83.10 (20210131230425). I tested against the vsbuild and mingw versions, SDL1 and SDL2, all crash in the same way. I also originally discovered the crash on 0.83.5
 - I used a fresh no-modifications dosbox-x.conf file, to confirm the crash.

**Comment by joncampbell123** [comment]
Admittedly the GUI toolkit that was imported from DOSBox Daum is rather hacky C++. I cleaned it up some, and added the TAB / Shift+TAB stuff myself, but it doesn't surprise me that it has a corner case like that.

**Comment by joncampbell123** [comment]
Eugh :stuck_out_tongue_winking_eye: Geez, have some error correction. vector.erase() doesn't bounds check you know, out of bounds values can happen!

gui_tk.h which seems to be the point where it crashes.

![image](https://user-images.githubusercontent.com/6245486/108264514-7cb21280-711c-11eb-80bb-7560ade84e4e.png)

**Comment by joncampbell123** [comment]
At the time you type, clearSelection() is called and start_sel is out of bounds.

**Comment by joncampbell123** [comment]
Fixed.
