### ISSUE TITLE
Loading a save state resets the scaler 

### ISSUE THREAD

**Issue by foone** [joncampbell123/dosbox-x#2280]
**Describe the bug**
When you load a save state, it changes DOSBox-X to use the scaler that was in use when that save state was made, even if it has been changed since then. Additionally this causes a minor menu glitch, where the menus indicate you're still using the scaler you had selected before loading state, when you've actually switched to the scaler at use when the save state was made. 

**To Reproduce**
1. Launch DOSBox-X and launch any graphical game (I tested with Paratrooper)
2. Set a scaler, such as Normal2X
3. Save the state
4. Change the scaler to any other value, like None
5. Load the state
6. DOSBox-x will now be using the original (Normal2X) scaler, not the later selected scaler (None)
7. Check the scaler menu: The checkmark will be on the later scaler (None), not the actually-in-use scaler (Normal2X)

**Expected behavior**
I expected the save state load to only affect the game's state, not the state of the emulator. 

**Environment (please complete the following information):**
 - Microsoft Windows 10 [Version 10.0.19042.804]
 - v0.83.10 (20210131230425), I tested against vsstudio SDL and SDL2, with identical results.
 - Fresh, no-changes dosbox-x.conf file

**Comment by Wengier** [comment]
Thanks for reporting! It is hopefully fixed in #2283.

**Comment by yetmorecode** [comment]
I'm checking bugs for state loading issues. The fix seems reasonable to me here. Is there a reason this ticket isnt closed yet?

**Comment by foone** [comment]
Nope. Closing.
