### ISSUE TITLE
[config] > devicehigh

### ISSUE THREAD

**Issue by JayQ2K** [joncampbell123/dosbox-x#2281]
In dosbox-x.conf there is a [config] section which aims to emulate CONFIG.SYS behavior. One of the options is devicehigh. Now if I want to use this option, where the driver is located on a mountpoint instead of a 'locally connected' drive (e.g. Z:) you'll end up with an error:
The following file is corrupted or missing: <FILE>

With mountpoints being created under [autoexec], this seems to be too late for [config] since those parameters are already executed before [autoexec], meaning devices cannot be loaded if they are on an external location.

It therefore seems that mountpoints must already be created before [config] and [autoexec] are being executed.

**Comment by Wengier** [comment]
Yes, it is a known issue. But it can be easily solved, just by mounting drives using INSTALL command before DEVICE(HIGH) command in [config] section instead of in [autoexec] section, e.g.:

```
[config]
INSTALL=MOUNT.COM C: :C\
DEVICEHIGH=C:\DRIVE.SYS
```

Hope this helps.
Hope this helps.

**Comment by JayQ2K** [comment]
Checked it and have it working. Might be something to have available in a WIKI page or something.
