### ISSUE TITLE
VGA BIOS is only found in the current working directory

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#2291]
**Describe the bug**
I had a look at the new code for loading a VGA BIOS and quickly noticed an issue. It only finds the ROM if it is in the current working directory.

It should probably look in various places.

What I propose, is something similar to what dosbox-staging has done, and have one function to find additional files (MT32 ROMs, PC98 font, TTFs for screen and printer, BIOS ROMs).

https://github.com/dosbox-staging/dosbox-staging/blob/master/src/misc/cross.cpp
DetermineConfigPath()

This will not be perfect, for instance for a MIDI soundfont, you still will want to also check the system directories as the current code does.

**Comment by rderooy** [comment]
Also look for XDG in:
- https://github.com/dosbox-staging/dosbox-staging/blob/master/src/src/midi/midi_fluidsynth.cpp
- https://github.com/dosbox-staging/dosbox-staging/blob/master/src/src/midi/midi_mt32.cpp

**Comment by Wengier** [comment]
Thanks for the report. With #2294 it should now allow VGA ROMs to be found in DOSBox-X program directory and user config directory too. And the path will be resolved as with other config options that involve paths. As for XDG, I think it is already handled for the user config directory.

**Comment by rderooy** [comment]
The XDG reference was partly meant to quickly locate the relevant piece of code. But also XDG is important on Linux, especially for things like Flatpak.
