### ISSUE TITLE
Error MM_GetPtr: Out of memory!

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#2292]
**Describe the bug**

The games Dangerous Dave's Risky Rescue and Dave Goes Nutz! crash frequently with error "MM_GetPtr: Out of memory!".
In DOSBox 0.74-3 the games runs well.
I left the default memory configuration in both emulators.
I noticed that the MEM command in DOSBox 0.74-3 shows 632 Kb of free conventional memory, but in DOSBox-X there are only 608 Kb.
I tried also to disable sound support in the games to decrease RAM footprint as recommended by the readme, but still crashes occurs..

**To Reproduce**

Try to play the first level of Dave Goes Nutz!

**Environment (please complete the following information):**
 - Windows 10 Pro 20H2
 - DOSBox-X release 0.83.10 Visual Studio and MinGW versions 32 and 64 bit.

**Comment by Wengier** [comment]
I did try both games on my 32-bit Windows build of DOSBox-X but I have not experienced with the said error so far. Perhaps I have not played the games long enough yet?

**Comment by MX9000** [comment]
It seems a bug related to save states.
Try starting the first level and saving a status immediately.
Kill some monsters and then let them kill you.
Reload the previous state and get killed again: the game should crash.
I used the game "Dangerous Dave Goes Nutz v1.01 (1993)(Softdisk Publishing) [Action, Adventure]" extracted from the collection Total_DOS_Collection-RELEASE#17-[1981-1995].zpaq found at archive.org.
Thank you.
