### ISSUE TITLE
Errors when mounting certain floppy/CD images from the Drive menu

### ISSUE THREAD

**Issue by DSN9990** [joncampbell123/dosbox-x#2293]
**Describe the bug**
Serious issue when I try to mount some CD images from the Drive menu. However IMGMOUNTing the image from the DOS prompt works just fine.

**To Reproduce**
1. Go to the Drive menu
2. Click on D: and choose any ISO affected by this error
3. See error prompt "Drive D: failed to mount"

**Expected behavior**
Mounting such images from the Drive menu should work the same way as IMGMOUNT without errors.

**Screenshots**
From the Drive menu:

![mounterror](https://user-images.githubusercontent.com/69558812/108613082-4222d100-73cd-11eb-8fe8-dd4700826af8.PNG)

From the DOSBox-X prompt:

![command_000](https://user-images.githubusercontent.com/69558812/108613094-641c5380-73cd-11eb-8eec-b95df511cbaf.png)

**Environment (please complete the following information):**
 DOSBox-X 0.83.10

**Comment by Wengier** [comment]
Thanks for reporting this. I think it only happens if the full path is long. It is hopefully fixed in #2294.
