### ISSUE TITLE
Paste host clipboard into Win3.11?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2298]
Probably I'm missing something obvious, but is it possible to paste from the host clipboard into Windows 3.11-applications launched in DOSBox-X? I have a project that runs Windows 3.11 under DOSBox-X, but I can't use the clipboard-pasting function in Win311 applications - not from the DOSBox-X menu and not via a mapped keystroke. I *can* paste from the host clipboard into Windows 3.11's MS-DOS Prompt window, but not into Win311 applications like Write or Notepad.

This project dates back a long time, and it's possible that I'm missing something obvious that should be in the settings. I'll be grateful for any advice.

**Comment by joncampbell123** [comment]
I believe there is a feature for Windows systems to paste text into DOS by faking keystrokes. It might work for Windows 3.1.

**Comment by Wengier** [comment]
There is also a CLIP$ device which you can open it from Win3.x applications like Write or Notepad to get the clipboard contents. As discussed earlier the result got from this is highly accurate, instead of depending on the keyboard functions.

**Comment by emendelson** [comment]
Yes, I had forgotten about opening CLIP$ in Windows 3.11. Is there any hope that some future version of DOSBox-X could control the Win311 clipboard directly?

**Comment by Wengier** [comment]
@emendelson On Windows systems you can already control the Win3.x clipboard “directly”, by using the command “TYPE CLIP$ | WCLIP”. Just make sure both the clipboard device and clipboard API are enabled. WCLIP is available from: [wclip22.zip](https://www.horstmuc.de/int/wclip22.zip)

You are right that CLIP$ device was only available for Windows host, but with #2300 it should work on Linux and macOS also, although write access is only supported in Linux and macOS SDL2 builds.

**Comment by Wengier** [comment]
@joncampbell123 The paste clipboard feature is available for all platforms, both SDL1 and SDL2 builds in recent DOSBox-X versions. It was previously available only for Windows.

**Comment by emendelson** [comment]
@Wengier Excellent! Thank you! This will be very useful.

**Comment by Wengier** [comment]
Just want to add that ```TYPE CLIP$ | WCLIP``` is for sending the shared clipboard content to Win3.x clipboard. To send the Win3.x clipboard content to the shared clipboard use ```WCLIP RECEIVE>CLIP$``` instead. With #2300 this method should work on all platforms (although write access is not supported in Linux/macOS SDL1 builds).

**Comment by emendelson** [comment]
Some more experiments: I have clipboard pasting mapped to Ctrl-Alt-F4 in both DOSBox and DOSBox-X. In my Win31 system, this keystroke pastes text in Win31 apps when I run DOSBox SVN, but not when I run DOSBox-X (SDL1 build).

**Comment by emendelson** [comment]
Some more experiments: I have clipboard-pasting mapped to Ctrl-Alt-F4 in both DOSBox and DOSBox-X. In my Win31 system, this keystroke pastes text into Win31 apps when I run DOSBox SVN, but not when I run DOSBox-X (both SDL1 and SDL2 builds, in Windows 10).

**Comment by Wengier** [comment]
@emendelson DOSBox SVN does not have built-in text-pasting functions. Are you using some custom function to do the pasting?

**Comment by Wengier** [comment]
@emendelson Also, pasting texts containing lower ASCII characters into Win3.1 apps (e.g. Notepad) should work fine in Windows SDL1 builds of DOSBox-X. I just confirmed it myself.

**Comment by emendelson** [comment]
@Wengier - You're right: I added a custom clipboard-paste function into my build of DOSBox SVN; I got it from the old dbDOS fork of DOSBox. Apologies for the irrelevant detail. I'll experiment again with the Windows build of DOSBox-X.

**Comment by emendelson** [comment]
@Wengier - You are absolutely right. Using the current release (SDL1), The clipboard-pasting function works perfectly. I'll have to figure out why it doesn't work in my setup. I'll close this thread now, because it's based entirely on a mistake.
