### ISSUE TITLE
copy inside 4dos does not work

### ISSUE THREAD

**Issue by stu** [joncampbell123/dosbox-x#2307]
**Describe the bug**
So, this is odd. I run 4dos 8.00 (not the one provided in the system, one I unzipped). if I do copy it returns "invalid handle" for a file that exists doing a copy filea fileb. the debug log spits out

(I did a copy xx.obj xx.ob)

LOG:   46174722 DEBUG DOSMISC:DOS:INT 2F Unhandled call AX=D44E
LOG:   46175074 DEBUG DOSMISC:DOS:INT 2F Unhandled call AX=B706
LOG:   46175277       DOSMISC:DOS:65:Extended country information call 6501
LOG:   46177290       DOSMISC:Getting global code page table
LOG:   46190475 DEBUG DOSMISC:DOS:INT 2F Unhandled call AX=AE00
LOG:   46211389       FILES:Special file open command 40 file xx.ob
LOG: Large file locking start=100000000, len=1
LOG:   46211480       DOSMISC:DOS:MS-DOS 7+ long file name support call 43
LOG:   46212226       DOSMISC:DOS:MS-DOS 7+ long file name support call 47
LOG:   46215918       DOSMISC:DOS:MS-DOS 7+ long file name support call 47
LOG:   46219634       FILES:file search attributes 17 name c:\temp\xx.ob
LOG:   46219973       DOSMISC:DOS:MS-DOS 7+ long file name support call A1
LOG:   46221811       FILES:file search attributes 17 name c:\temp\xx.ob\*.*
LOG:   46224625       FILES:Special file open command 40 file xx.obj
LOG: Large file locking start=100000000, len=1
LOG:   46224716       DOSMISC:DOS:MS-DOS 7+ long file name support call 43
LOG:   46225434       DOSMISC:DOS:MS-DOS 7+ long file name support call 47
LOG:   46229239       DOSMISC:DOS:MS-DOS 7+ long file name support call 47
LOG:   46233003       FILES:file search attributes 17 name c:\temp\xx.obj
LOG:   46233354       DOSMISC:DOS:MS-DOS 7+ long file name support call A1
LOG:   46235207       FILES:file search attributes 17 name c:\temp\xx.obj\*.*
LOG:   46240604       FILES:file search attributes 0 name c:\temp\xx.obj
LOG:   46246832 DEBUG DOSMISC:DOS_FreeMemory(seg=0x07db)
LOG:   46246855 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x007f) = 0x07db-0x0859
LOG:   46246884 DEBUG DOSMISC:DOS_FreeMemory(seg=0x07db)
LOG:   46246907 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x0fff) = 0x07db-0x17d9
LOG:   46246972 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x8824) = 0x17db-0x9ffe
LOG:   46255371       FILES:Special file open command 40 file c:\temp\xx.obj
LOG: Large file locking start=100000000, len=1
LOG:   46255462       DOSMISC:DOS:MS-DOS 7+ long file name support call 43
LOG: Large file locking start=0, len=ffff
LOG:   46257705 DEBUG DOSMISC:DOS_FreeMemory(seg=0x17db)
LOG:   46257722 DEBUG DOSMISC:DOS_FreeMemory(seg=0x07db)
LOG:   46257767 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x9824) = 0x07db-0x9ffe
LOG: Large file locking start=0, len=ffff
LOG:   46260828       DOSMISC:DOS:MS-DOS 7+ long file name support call A1
LOG:   46263827 DEBUG DOSMISC:DOS:INT 2F Unhandled call AX=D44E
LOG:   46277939       DOSMISC:DOS:MS-DOS 7+ long file name support call 47
LOG:   46282172 DEBUG DOSMISC:DOS:INT 2F Unhandled call AX=D44E

now if I do exit to get out of 4dos back into the dbx shell it works

LOG:  439080369 DEBUG EXEC:Parsing command line: copy xx.obj xx.ob
LOG:  439080369       FILES:file search attributes 10 name "C:\TEMP"
LOG:  439080369       FILES:file search attributes FFF7 name "C:\TEMP\XX.OBJ"
LOG:  439080369       FILES:file search attributes FFF7 name C:\TEMP\XX.OBJ
LOG:  439080369       FILES:file search attributes 10 name "C:\TEMP"
LOG:  439080369       FILES:file search attributes FFF7 name "C:\TEMP\XX.OB"
LOG:  439080369       FILES:file search attributes FFF7 name C:\TEMP\XX.OB
LOG:  439080369       FILES:file search attributes FFF7 name C:\TEMP\XX.OB
LOG:  439080369       FILES:file search attributes 10 name "C:\TEMP"
LOG:  439080369       FILES:file search attributes FFF7 name "C:\TEMP\XX.OBJ"
LOG:  439080369       FILES:file search attributes FFF7 name C:\TEMP\XX.OBJ
LOG:  439080369       FILES:file open command 0 file C:\TEMP\XX.OBJ
LOG: Large file locking start=100000000, len=1
LOG:  439080369       FILES:file create attributes 0 file "C:\TEMP\XX.OB"

for giggles, I used the 4dos provided in dbx z:\ (which seems to be the same 8.00) and it gave me the same error.

**To Reproduce**
1. run 4dos.
2. copy an existing file to one that does not exist

**Expected behavior**
I expect a copy in 4dos to work...

**Environment (please complete the following information):**
 - Linux
 - DOSBox-X release version or commit 556c084d42516e2f81df805e06ece24f2ecaed9e

**Comment by Wengier** [comment]
Thanks for reporting this! It only occurred in non-Windows builds of recent code, and it is hopefully fixed in #2311.

**Comment by Wengier** [comment]
@stu Just a small tip: It is recommended to use the built-in 4DOS.COM file on the Z: drive instead of the original one. It is 4DOS 8.00 with minor patches to work better with DOSBox-X.
