### ISSUE TITLE
Feature request: option for specifying titlebar strings

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2309]
DOSBox-X already has an option not to "show details" in the titlebar. In many situations, the display of cycles in the Windows DOSBox-X titlebar is distracting and irrelevant. It would be good to have an option to display only "DOSBox-X" and the name of the running application, without any details at all.

In my fork, I've been changing the code so that the titlebar only shows "DOSBox-X : " (that's a space then a colon then a space), followed by the name of the running application. That gives a very clear appearance, without clutter. I think this option might be useful to others also.

**Comment by Wengier** [comment]
In #2311 there is an option "showbasic" which when set to false will not show the version number and the current running speed. Hope this solves this issue.

**Comment by emendelson** [comment]
Done. Thank you!
