### ISSUE TITLE
Mouse responsiveness dependent on vertical retrace timing

### ISSUE THREAD

**Issue by box-tortoise** [joncampbell123/dosbox-x#231]
Previous report on mouse responsiveness in Wing Commander:
http://www.vogons.org/viewtopic.php?t=30754

I noted similar issue in FS 5.1.

A change to the vertical retrace timing was suggested in that thread which seems to improve mouse responsiveness in menus of FS 5.1:
```
@@ -40,11 +40,8 @@ Bitu vga_read_p3da(Bitu port,Bitu iolen)
 	// bit   0  Horizontal or Vertical blanking
 	//       3  Vertical sync
 
-	if (timeInFrame >= vga.draw.delay.vrstart &&
-		timeInFrame <= vga.draw.delay.vrend)
-		retval |= 8;
 	if (timeInFrame >= vga.draw.delay.vdend) {
-		retval |= 1;
+		retval |= 9;
 	} else {
 		double timeInLine=fmod(timeInFrame,vga.draw.delay.htotal);
 		if (timeInLine >= vga.draw.delay.hblkstart && 
```
It was noted that this is the mouse behavior in dosbox 0.65 and does not necessarily lead to lesser accuracy in the emulation. If there are no obvious problems with this change, would it be ok to commit it to dosbox-x (at least for others to test) to improve mouse responsiveness in the above flight simulators?

**Comment by joncampbell123** [comment]
Actually, considering my experience with VGA hardware, that change would make it more accurate to hardware. Both bits are set during vertical blank/retrace. Go ahead.

**Comment by box-tortoise** [comment]
Thank you for your expertise.
