### ISSUE TITLE
Change DosBox-x icon following new guidelines macOS Big Sur

### ISSUE THREAD

**Issue by josephillips85** [joncampbell123/dosbox-x#2317]
Im working on upgrade the icons for macOS Big sur .

i upload few examples so we can decide one @joncampbell123 @Wengier 
![image](https://user-images.githubusercontent.com/28776122/109405897-c1bb1d80-7942-11eb-8a43-dcb3d13eaf5f.png)
![image](https://user-images.githubusercontent.com/28776122/109405903-cb448580-7942-11eb-90b8-36c6d1a98c9e.png)

I guess the blue looks cool .

or any another idea?

Thanks

**Comment by joncampbell123** [comment]
The darker blue background helps the lighter colored letters stand out, I think.
