### ISSUE TITLE
Windows 3.11 screen colors with Mac SDL2 build?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2318]
I believe this was answered before, but I can't find it after much searching.

When I run Window 3.11 on a Mac with current SDL1 code, the screen colors are correct, using a 64K color 1024x768 screen with S3 drivers in Windows 3.11:

When I use an SDL2 build, I get this:

![Screen Shot 2021-03-01 at 10 29 14 AM](https://user-images.githubusercontent.com/5208505/109521882-c59e8b00-7a7b-11eb-832f-74d8698df0b5.png)

I've experimented with various SDL settings but can't find any that give the correct colors. Does anyone know what they might be?

EDIT: I can get the correct colors with the S3 drivers and 256 colors; but the wrong colors with 32K and 64K colors. Is there a solution?

**Comment by Wengier** [comment]
Not exactly sure but I guess this issue may be related to Issue #1619. If this is the case, the problem only occurs in 32+bit color mode with certain version of the S3 driver, but will not occur in 256 or 16-bit. Can you try a different driver or the 16-bit color mode instead?

**Comment by emendelson** [comment]
@Wengier It does sound like a similar bug. Unfortunately, the S3 drivers seem to be the only ones for Windows 3.11 under DOSBox-X that support 32K or 64K colors *and* modes of 800x600 or higher. So, if you want to use 32K or 64K colors at large resolutions, you can't use DOSBox-X SDL2 builds under macOS.

This is not a major hardship, since SDL1 drivers work, and the 256-color drivers work correctly at all resolutions, but, since DOSBox-X tries to emulate real hardware, it would be good if someday these high-color high-resolution drivers worked correctly on a Mac. But is certainly NOT an urgent problem!

**Comment by Wengier** [comment]
Hope it is fixed by #3428.
