### ISSUE TITLE
Chocolatey package update - Dosbox-x Installer should be made non-interactive  

### ISSUE THREAD

**Issue by Xav83** [joncampbell123/dosbox-x#2331]
Hi dosbox-x devs 🙂 

I hope you are doing great in those pandemic times !

I create this issue, because I experiment a problem with the installation of `dosbox-x` with the file [dosbox-x-windows-0.83.11-setup.exe](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.11/dosbox-x-windows-0.83.11-setup.exe).

To give you more context, I am the maintainer of [dosbox-x chocolatey package](https://chocolatey.org/packages/dosbox-x), and want to update the `dosbox-x` version available on Chocolatey, but I am experimenting some issue to validate the installation for Chocolatey requirements.

Indeed, for the installation to pass Chocolatey package validation process, the installer must not be interactive, or have some options to make it non-interactive.

Sadly, when I pass all the silenting options to the installer executable ([/SP- /VERYSILENT /SUPPRESSMSGBOXES](https://jrsoftware.org/ishelp/index.php?topic=filessection)), I still have some windows prompting.

![Capture](https://user-images.githubusercontent.com/6787157/110039439-830dd480-7d41-11eb-92a4-0948d344392c.png)

After some digging, I managed to found the [code of this particular window](https://github.com/joncampbell123/dosbox-x/blob/5c6c8f22c53745931f13372ae23646895b7e376d/contrib/windows/installer/DOSBox-X-setup.iss#L265), but, since I don't know a lot about Inno-setup installer programming, I can't go any further in the debug/fix of the issue I have, and I am hoping that you could help me on that 🙂 

Thanks in advance for your answer, and your work on dosbox-x in general 😃 

*Note*: For now, the Chocolatey package is blocked to the version `0.83.4`, and can't be updated until this issue has been fixed.

**Comment by Wengier** [comment]
@Xav83 Thanks for posting the issue here! The current version of DOSBox-X is 0.83.11, with a lot of updates since version 0.83.4, I think it is likely easy to suppress this particular window for the purpose of dosbox-x chocolatey package, just by commenting out line 265 (add "//" in the front) so that it defaults to Yes. For general purpose though I think an automatic timeout for the message box may be a solution.

**Comment by Xav83** [comment]
@Wengier I don't know if it would work, but there seems to be a [function allowing to detect if the installer is in silent mode](https://jrsoftware.org/ishelp/index.php?topic=filessection).
So maybe, using this function and displaying the message box only if the installer is not in silent mode could be another solution too.

**Comment by Wengier** [comment]
@Xav83 I see. Although the description in your linked page only applies to the [Files] section, I have found another way to detect the (very) silent mode which could silence that message box in such case. You can try the updated Windows installer below:

* [dosbox-x-windows-0.83.11-setup.exe](http://cndos.fam.cx/dosware/dosbox-x-windows-0.83.11-setup.exe)

Hope this helps.

**Comment by Xav83** [comment]
Thanks a lot for you reactivity @Wengier ! 🙂

The version of dosbox-x installer you have put in your last message works well on my machine ! I was able to install dosbox-x with `/SP- /VERYSILENT /SUPPRESSMSGBOXES`  flags and the installation worked without any window popping up. 🙂👍

This means that, if you integrate the code with which you've created this installer on your main branch, when you will create the next release, then, the Chocolatey package should update itself and, this time, pass the Chocolatey tests without any problem 🙂👌

**Comment by Wengier** [comment]
@Xav83 Yes, the main code has been updated accordingly as well, so it should work the same as the updated installer linked above.

**Comment by Xav83** [comment]
When the next release of `dosbox-x` will be out, I will update this issue to validate that everything is well validated by Chocolatey validation system, and that the version is accessible via Chocolatey 😉

**Comment by Xav83** [comment]
The new release of `dosbox-x` is now accepted by Chocolatey validation process and available on [Chocolatey](https://community.chocolatey.org/packages/dosbox-x) 😃👌 

I am going to close this issue, since everything works fine now. 😉 

Thanks again @Wengier for your help ! 🙂
