### ISSUE TITLE
Bubble Bobble seems to freeze at Tandy mode

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#2343]
**To Reproduce**
Change mode from svga_s3 to tandy in settings. Open up Bubble Bobble, choose Tandy mode, configure controls, then it freezes at screen after that. Works in default (svga_s3) mode

**Expected behavior**
Game should not freeze at intro screen and should be playable

**Environment (please complete the following information):**
Windows 10 using 0.83.11
[DOS conf.zip](https://github.com/joncampbell123/dosbox-x/files/6096558/DOS.conf.zip)

**Comment by FredBezies** [comment]
I can confirm this freeze also with revision 13619 on Linux.

**Comment by ualaa1** [comment]
Please see #2380
