### ISSUE TITLE
Jordan vs. Bird: One-on-One Tandy will not boot

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#2344]
**Describe the bug**
Attempting to boot Jordan Vs Bird in Tandy mode will result in a screen saying "Cannot Allocate Display Memory"

**To Reproduce**
Change to Tandy mode and load the game.

**Expected behavior**
The game should boot up with digitalized audio.

**Screenshots**
![command_000](https://user-images.githubusercontent.com/68984176/110229997-6351ea00-7ec2-11eb-8501-b7af5895dd74.png)

**Comment by Wengier** [comment]
As with #2366, try run the command ```LOADFIX -A``` before launching "1on1". Hope this helps.

**Comment by ualaa1** [comment]
Works, thanks!

**Comment by ualaa1** [comment]
Please see #2380
