### ISSUE TITLE
DOSBox-X vs. SVN: performance issues in macOS

### ISSUE THREAD

**Issue by almeath** [joncampbell123/dosbox-x#2345]
For some months, ever since I started extensively using DOSBox-X, I have noticed a significant performance differential between DOSBox-X and DOSBox SVN.

I compile my own SVN builds in macOS Mojave, and have done the same with both SDL1 and SDL2 builds of DOSBox-X up to and including 0.83.11 of March 1st 2021.

I have conducted some benchmarking tests using DOSBench, and the results are contained in the attached table.

[Scores.docx](https://github.com/joncampbell123/dosbox-x/files/6096608/Scores.docx)

In summary, DOSBox-X performs significantly slower than SVN (by about 30-35%), despite equivalent config settings. I ensure that they are running on 'base' config settings generated by "config -writeconf dosbox.conf".

The only thing I adjust is making sure they are both on maximum cycles, with DOSBox SVN net to "dynamic" core while DOSBox-X uses "dynamic_x86".

I am at a loss to explain this differential, as no amount of settings adjustments make any significant difference to the results.

It is enough of a drop to cripple DOSBox-X in more demanding Windows 9x games, where I experience stuttering sound and some video lag, which does not occur at all in SVN.

**Comment by joncampbell123** [comment]
Yes, that's the downside of developing around accuracy rather than speed.

**Comment by almeath** [comment]
Which is totally fine with me, and I understand and support the rationale of the project. I just wanted to make sure this was expected behavior and not caused by some bug in the code. :-)
