### ISSUE TITLE
Problem with mouse during install of win 3.x and 9x

### ISSUE THREAD

**Issue by massof** [joncampbell123/dosbox-x#2353]
Hello,
as the title suggests I am trying to install the two versions of Windows but as soon as I get to the first screen I realize that the mouse does not work. It is not captured or moves or clicks. I also tried older versions of Dosbox-x. With the Dosbox (not x) everything is ok. My pc is a core i5 with windows 10 x64.
Thank you all

**Comment by joncampbell123** [comment]
Have you tried manually capturing your mouse? DOSBox-X does not have the same auto-capture functionality.

**Comment by massof** [comment]
Yes, I've tried everything.  Even to install older versions of the app but nothing.  What else can i try?  Thanks again

**Comment by rderooy** [comment]
Are you setting:
```
[sdl]
autolock=true
```

With that it works for me on Linux. When I click inside the window it captures the mouse.

**Comment by joncampbell123** [comment]
I'm noticing here that the issue happens if int33=false. Otherwise, mouse works fine here.

**Comment by joncampbell123** [comment]
It also seems it can happen if mouse or AUX incoming data happens while Windows 3.1 has the PS/2 interrupt masked. When unmasked, the interrupt is not properly acknowledged in a manner that prevents PS/2 mouse interrupts from working.

**Comment by joncampbell123** [comment]
Please try the latest commit, if you can compile from source.
