### ISSUE TITLE
how to scroll page up

### ISSUE THREAD

**Issue by Nicogr78** [joncampbell123/dosbox-x#2354]
I play some text adventures using dosbox-x but when for some reason i die (which happens a lot) dosbox-x goes straight to black screen with Z:. and i cant read previous screen and what happened and why i died. Is there a way to scroll the screen up or backwards so i can see what happened or dosbox-x doesnt reset immediately to a new screen?

**Comment by joncampbell123** [comment]
DOSBox-X is not a terminal emulator, there is no scrollback buffer.

**Comment by Nicogr78** [comment]
well is there a way when game ends not to send immediately out of it into the z: command line? so I have time to read how the game ended?

**Comment by Wengier** [comment]
DOSBox-X is a DOS emulator, so it tries to emulate the actual behaviors of the DOS games/applications. It is the game (not DOSBox-X) which decides to reset the screen and return to DOS in such case. If the DOS game does not do this by itself, then you will likely see the result in in both DOS and DOSBox-X.

**Comment by Nicogr78** [comment]
Thanks for the answer. I tried same game to normal dosbox and it was still booting me after death. It must be a problem with the image file i think because it doesnt make sense that original game didnt let you read a whole page of text when you die. Same thing also happened when i finished the game. I was booted to Z: Command and i thought i was dying but watched a walkthrough on youtube and it seems i finished the game and didnt notice. Love dosbox-x btw because i can save state and alt tab full screen :)
