### ISSUE TITLE
Turn off "quit" warning

### ISSUE THREAD

**Issue by leuat** [joncampbell123/dosbox-x#2355]
Hi there!

I'm the developer of TRSE (www.turborascal.com), a cross-platform development tool for 8/16 bit software. I've been using DOSBOX for my 8088/386/486 software development, but wanted to change to dosbox-x because of the M1 Arm support. However, I'm finding the question "are you sure you want to quit.." etc very annoying, since I'm constantly compiling + executing applications during development, and have to press "yes" every single time. I haven't been able to find any option in the command line help / settings file on how to turn this warning question off.

regards

Nicolaas

**Comment by ThePillenwerfer** [comment]
Here's what you need in the `.conf` file:—
```
[dosbox]
quit warning = false
```

**Comment by leuat** [comment]
Thanks, man!
