### ISSUE TITLE
Hard Rebooting ("config -bc") causes a crash when machine is set to "amstrad"

### ISSUE THREAD

**Issue by Banjo-Oz** [joncampbell123/dosbox-x#2361]
Not sure if it's something else I've done, but my DOSBox-X session boots and runs as expected if I have machine=amstrad in my conf file. However, if I use the "config -bc" command to reboot, DOSBox-X crashes attempting to reboot. This doesn't happen with other machines that I know of (though I tested cga, ega, vgaonly, mcga and vga_s3; all rebooted fine).

Just wanted to check if this was only my issue or one that others could confirm?

**Comment by Wengier** [comment]
Does the same issue on your system if you try to close the DOSBox-X window with the setting ```machine=amstrad```?

**Comment by Banjo-Oz** [comment]
@Wengier Yes, it does. It also crashes the same way if I choose the menu option "Reset virtual machine".

**Comment by Wengier** [comment]
@Banjo-Oz The code in #2369 should fix the crash at least for ```config -bc``` and closing the DOSBox-X window in this mode.

**Comment by Banjo-Oz** [comment]
@Wengier Thanks! I'll check it as soon as there is a Windows build available. Really appreciate the fix (and the one for the disk image popup mentioned too).

**Comment by Banjo-Oz** [comment]
@Wengier I can confirm it no longer crashes in this situation using build 83.12. Thanks!

**Comment by Wengier** [comment]
@Banjo-Oz Glad to hear it.
