### ISSUE TITLE
"INVALID MESSAGE WITH QUOTES" message box when loading multiple floppy images

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#2363]
**Describe the bug**

When loading multiple floppy images, after clicking on the No button in the message asking if you want to mount more images, another box appears that says "INVALID MESSAGE WITH QUOTES".
After clicking the OK button the floppy images are loaded anyway and everything works correctly.
The folder that contains the images has a short path without spaces (D:\DOSBox-X\FD) and the images have simple names (disk1.img, disk2.img, and so on).

**To Reproduce**

Try to load multiple floppy images from the Drive menu item.

**Screenshots**

![Multiple image loading bug](https://user-images.githubusercontent.com/58113425/111033964-cc31e880-8413-11eb-94ac-101180a6abb2.PNG)

**Environment (please complete the following information):**
 - Windows 10 Pro 64 bit version 20H2
 - DOSBox-X 0.83.11 Visual Studio build, 64 bit, SDL2

**Comment by Banjo-Oz** [comment]
I can confirm the same error (it doesn't seem to prevent the images working, from what I can tell).

I'm on Windows 7 x64, using DOSBox-X 0.83.12 (that you liked a binary WIP build in my joypad thread), SDL1.

**Comment by Wengier** [comment]
Thanks for reporting this! I believe this is due to a recent change in the included library. It should work with the code in #2369.

**Comment by MX9000** [comment]
Thank you all for the fix!
