### ISSUE TITLE
"The selected save slot is an empty slot" message box locks full screen mode

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#2365]
**Describe the bug**
When the emulator is in full screen mode, if you select accidentally an empty save state slot with key combinations F11 + dot or F11 + comma and then reload the save state with F11 + L, the emulator window minimizes instantly on the taskbar. If you click on the application button on the taskbar the emulator window maximizes with a black background and a message box warning you of the empty slot. If you click on the OK button the window minimize itself again in an endless loop. I can close the emulator only by terminating the process with the task manager.

**To Reproduce**
1. Go in full screen mode
2. Launch a game
3. Save a state in the default slot 1
4. Type the key combination to select the previous or next slot
5. Reload the save state from the empty slot

**Screenshots**

![Empty save slot bug](https://user-images.githubusercontent.com/58113425/111034766-72332200-8417-11eb-8237-dd43732d917a.png)

**Environment (please complete the following information):**

 - Windows 10 Pro 64 bit version 20H2
 - DOSBox-X 0.83.11 Visual Studio build, 64 bit, SDL2

**Comment by Wengier** [comment]
I have tried it myself, and I think for SDL1 and SDL2 builds the result will be different. In any case, I have been fixing this by automatically turning the full-screen mode off and on before and after showing such messages, and you can check out the updated Windows binary package below:

* [dosbox-x-64-update.zip](http://cndos.fam.cx/dosware/dosbox-x-64-update.zip)

**Comment by MX9000** [comment]
@Wengier, thank you for the solution!
