### ISSUE TITLE
Outrun does not boot in Tandy mode

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#2366]
**Describe the bug**
When selecting the Tandy 1000 mode (or 16-color Tandy) in Outrun when Dosbox-X machine is set to Tandy, the game changes to a black screen

**Comment by Wengier** [comment]
I was able to play the game in Tandy mode if I run the command ```loadfix -a``` before loading the game. I downloaded the game from [here](https://www.abandonwaredos.com/abandonware-game.php?abandonware=OutRun&gid=1031).

**Comment by ualaa1** [comment]
Can you try these: https://www.old-games.ru/game/download/get.php?fileid=28531&modal=1 and https://www.old-games.ru/game/download/get.php?fileid=28532&modal=1
The loadfix didn't work on these. I used your link, but Tandy sound didn't work (only PC speaker sound) and it skipped the intro (where a voice says "Sega computer presents Outrun")

**Comment by ualaa1** [comment]
Please see #2380
