### ISSUE TITLE
Windows: DOSBox-X won't start (Problem with embedded manifest and VirtualStore??)

### ISSUE THREAD

**Issue by sagamusix** [joncampbell123/dosbox-x#237]
I tried downloading the Windows installer (both 32-bit and 64-bit) for the latest preview release from May, and it just plain crashes when trying to launch DOSBox-X. Older versions used to work. I'm on Windows 7 x64.

**Comment by joncampbell123** [comment]
I didn't write the Windows installer, so I can't say whether what it installs is the latest or what the installer does to launch it.

**Comment by joncampbell123** [comment]
If you launch DOSBox-X by itself, without any options, does it run?

**Comment by sagamusix** [comment]
No. I verified this by launching it manually and als trying to delete/revert the config file.

**Comment by joncampbell123** [comment]
Well I'm not sure what's going on, but understand that I don't develop DOSBox-X for Windows anymore and Windows binaries since that point come from another branch or repository. It's possible that branch built DOSBox-X at a time where a bug or mistake caused a crash on startup.

**Comment by aybe** [comment]
I wrote this installer, it does nothing special beside installing it along shortcuts.

I'll paste here the information screen of the installer that you've probably skipped:


_Welcome to DOSBox-X, a fork of the DOSBox project !

Caveat:

Due to the way of how Windows works, access to the 'Program Files' folder requires administrative permissions. Unless you have specific reasons, we recommend that you install DOSBox-X in a different folder that does not require administrative permissions._

So if you did install it in Program Files and not launched it as an admin, it will crash abruptly as it fails writing to current directory, it's not really user-friendly but it's how DosBox reacts in such case.

Solutions:
- run it as admin if you absolutely want it in Program Files
- install it somewhere else like C:\DosBox to be able to launch without admin rights

I guess the installation notes should be updated somehow ...

**Comment by aybe** [comment]
I've updated the release page of the install with a clear note in bold:

https://github.com/joncampbell123/dosbox-x/releases/tag/windows-installer

Let us know if that fixed it for you !

**Comment by sagamusix** [comment]
Sorry for the delay, I was reinstalling Windows and DOSBox-X wasn't high on the priority list. :)
Activating administrator mode when placing the program in C:\Program Files\ does indeed fix the issue.
However, a program requiring write access to its program folder is very bad style no matter which operating system, so hopefully this deficiency will be addressed in the future.

**Comment by aybe** [comment]
Somehow, something has been lost in the solution conversion process from the original DOSBox to DOSBox-X project, resulting in this behavior.

Basically when a program is run with default permissions and tries to write to Program Files, the system redirects it to a VirtualStore folder in a transparent manner. However, currently it is not happening and that results in a crash unless run as admin.

I've checked both solutions and they use the same settings, some say using a manifest will do but this fork should be able to do as the original one. This is not a really complex issue per se, but finding what's causing this is what's going to take some time in fixing it.

**Comment by sagamusix** [comment]
I have not had this issue before but I can imagine that it's not something you will find in the solution, but rather in the application manifest. Maybe a manifest was previously not present but now is, or an option was added that declares the application does not need VirtualStore...

**Comment by sagamusix** [comment]
Actually I think this is precisely the issue: The original DOSBox project does not embed a manifest, which means Windows will treat it as a pre-Vista application that may need to use VirtualStore. DOSBox-X.exe contains a manifest however, and it contains a trustInfo section, effectively disabling VirtualStore. If you did not knowingly create this manifest, then it is most likely VS2015's default manifest, and you will have to override it with your own.

**Comment by aybe** [comment]
Let me clarify,

In original project there's no manifest declared,
In this fork there's no manifest declared,

(actually VS generates and integrates a default manifest if you don't specify one manually)

So the problem lies in finding why it's causing this even though project settings are identical.

**Comment by sagamusix** [comment]
> So the problem lies in finding why it's causing this even though project settings are identical.

It's precisely this default manifest with its "trustInfo" section that is generated by VS2015 but not by VS2008, which I think is still the default solution used for DOSBox. You can try specifying an empty manifest, or maybe at least a manifest that does something useful, like declaring compatiblity with some Windows versions. Example:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
 <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
  <application>
   <!-- Windows 10 -->
   <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
   <!-- Windows 8.1 -->
   <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
   <!-- Windows 8 -->
   <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
   <!-- Windows 7 -->
   <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
   <!-- Windows Vista -->
   <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
  </application>
 </compatibility>
</assembly>
```

**Comment by aybe** [comment]
Ok sorry I forgot to mention but I've tried to embed a manifest with trustInfo yesterday hoping it'd be a quick fix but that didn't work.

By the way, if you have the time and skills to fix it, you are welcome to commit to the project 😃

**Comment by sagamusix** [comment]
Well, so far I have mostly been guessing using my limited knowledge of manifests. My guess is that you should *omit* the trustInfo section, as far as I understand it automatically tells the system that you do not need VirtualStore (but you do / SDL does).

I can have a shot, where do I find the Windows branch that was mentioned?

**Comment by aybe** [comment]
The Windows branch I've been working on is 'joystick',

Basically it contains fixes/features for joystick stuff where details are in https://github.com/joncampbell123/dosbox-x/blob/6fc3e8ce296cebe519fd212797855e5dedeba26a/README.joystick .

From what I've seen yesterday the 'master' branch needs to be fixed for VS, many primitive types names have been changed and therefore it does not compile out of the box.

**Comment by sagamusix** [comment]
The easiest way right now to keep the same behaviour as the original DOSBox is to go to the project properties -> Manifest -> Input and Output -> Embed Manifest -> No.

Here's a patch that does that: [dosbox-x.vcxproj.patch.zip](https://github.com/joncampbell123/dosbox-x/files/620383/dosbox-x.vcxproj.patch.zip)

**Comment by aybe** [comment]
Okay, what I'll do is see how original project behaves under VS2015 and see if I can spot where the error is.

**Comment by joncampbell123** [comment]
@Aybe Is this still a problem?

**Comment by joncampbell123** [comment]
I'll assume the lack of an answer in 9 months is... no.

@aybe Feel free to reopen this issue if I'm wrong.
