### ISSUE TITLE
Commit 76b69bb6fd2da969f153d673e1492d6e3f1bd774 -  "Update MMX code" - break build process: 

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#2372]
**Describe the bug**
I simply tried to build dosbox-x based on commit 09bc8a0aec8fd1386b69ebdf1d86e23b6d854af9 but build process stops complaining about a missing mmx related file.

So this is a consequence of commit 76b69bb6fd2da969f153d673e1492d6e3f1bd774 which modifies MMX code.

Here is the error I got:

```
In file included from core_dyn_x86/decoder.h:2473,
                 from core_dyn_x86.cpp:306:
core_dyn_x86/dyn_mmx.h:19:10: fatal error: ..\core_normal\prefix_0f_mmx.h: No such file or directory
   19 | #include "..\core_normal\prefix_0f_mmx.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**To Reproduce**
See details

**Expected behavior**
Build process going on.

**Comment by joncampbell123** [comment]
I just fixed that. Here on Linux you need to change the back slashes to forward slashes. Should be in the latest commit.

**Comment by FredBezies** [comment]
Ok. Will test and report asap.

**Comment by joncampbell123** [comment]
Whoops, hold on, now I'm pushing the commit.

**Comment by FredBezies** [comment]
I was waiting for your commit. Don't worry :)

Well, another bug bites the dust. Thanks for the fix. Closing the bug report now.
