### ISSUE TITLE
DosBox-X 0.801 will not run on XP SP3

### ISSUE THREAD

**Issue by dnice0200** [joncampbell123/dosbox-x#238]
I tested using the May 9 release labeled "Windows Installer (Preview)".
I am running on a 32-bit machine, so I tested the 32-bit installer.

Installation went fine, but Windows says "dosbox.exe is not a valid 32-bit program".

However, I found both the 32-bit and 64-bit version to work fine on Windows 10 (64-bit machine).

Is there something I can do to make it run on Win XP ?

**Comment by dnice0200** [comment]
How can I get Windows binarys built for XP SP3 without doing so myself?  I do not have Windows development tools.  I do not know where else to post this issue.

**Comment by aybe** [comment]
I would like to synchronize the Windows branch with current one, as well as fixing the https://github.com/joncampbell123/dosbox-x/issues/237 bug and also restore XP support in the meantime. 

I can't really provide a timeframe though (actually, when I have some free time).

**Comment by sagamusix** [comment]
Proposed patch for restoring XP compatibility (including the patch for #237):
[xp-compatibility.zip](https://github.com/joncampbell123/dosbox-x/files/620392/xp-compatibility.zip)

**Comment by aybe** [comment]
Yes, I'll patch it ASAP, thank you :)

**Comment by joncampbell123** [comment]
DOSBox-X releases now run on Windows XP
