### ISSUE TITLE
Wing Commander Privateer crashes dosbox-x

### ISSUE THREAD

**Issue by zhro** [joncampbell123/dosbox-x#2384]
I tested this on two systems using MinGW build SDL1 (default) and Release SDL1 (Default Visual Studio).

DOSBox-X version 0.83.11, tested on Windows XP x86 (SP3) and Windows 10 x64.

I have had a range of errors including a popup for a Visual C++ runtime error (using the MinGW build), having dosbox-x crash and disappear entirely, to having it "soft reset".

This is replicated by trying to run priv.exe from Wing Commander Privateer.

It does not crash when running on regular dosbox.

**Comment by Wengier** [comment]
Can you try set "ems=false" in the config file (or from the menu "DOS" => "Expanded Memory (EMS)" => "Disable EMS emulation") and run the game again?

**Comment by zhro** [comment]
That fixes it. Why does it crash with dosbox-x and not normal dosbox?

And how does the game even run with ems=false? It requires ems.

**Comment by Wengier** [comment]
Wing Commander Privateer also runs in normal DOSBox with the setting ems=false. You can find more information in this thread:

https://www.vogons.org/viewtopic.php?p=60517

**Comment by joncampbell123** [comment]
It looks like an issue with JEMM and DOSBox-X VCPI emulation. The vm86 monitor can't quite work with the game.

If you run with vcpi=false, JEMM complains that it can't set up protected mode, because it assumes EMM386.EXE and therefore vm86 mode even though it really isn't running in vm86 mode at all.

**Comment by joncampbell123** [comment]
So that message suggests an exception during CPU_LTR() while handling VCPI function 0x0C (VCPI switch from vm86 to protected mode).

**Comment by joncampbell123** [comment]
LOG: VCPI:Could not load TR with 10
LOG: CPU_Interrupt() interrupted
LOG:   29566404       PAGING:Recursive PageFault for 113004 used=0
LOG: CPU_Exception: Exception 14 already in progress, triggering double fault instead
LOG:   29566404       PAGING:Recursive PageFault for 113004 used=1
LOG: Warning: PAGING_NewPageFault() more than one level, now using level 2
LOG: CPU_Exception: Double fault already in progress == Triple Fault. Resetting CPU.
LOG:   29566404 DEBUG MISC:Emulation threw a signal to reboot the system
LOG:   29566404 DEBUG MISC:Dispatching VM event DOS exit, reboot begin
