### ISSUE TITLE
[MMX Emulation] Impulse Tracker freezes when running it with the SB16 MMX driver

### ISSUE THREAD

**Issue by polyzium** [joncampbell123/dosbox-x#239]
As the title says.
When i change CPU type to Pentium MMX, and run IT with the SB16 driver for MMX (command line params were "it sitsb16.mmx"), Impulse Tracker just freezes at the start screen and i cant do anything.

**Comment by joncampbell123** [comment]
MMX emulation is incomplete. It was inherited from code merged from Daum's branch.

**Comment by polyzium** [comment]
Hm how about pcem/86box's mmx emulation?

**Comment by alpharisc** [comment]
Can confirm that with version 0.83.18 MMX driver now working properly, good performance too.
