### ISSUE TITLE
Dynamic core vs Touhou Project clipping and movement issues

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#2395]
**Describe the bug**
Odd bugs and glitches occur with Touhou Project 1 when run with dynamic core.

**Additional context**
https://discord.com/channels/231947749862539264/319281334054944778/824396301567262761

**Comment by joncampbell123** [comment]
![Firefox_Screenshot_2021-03-31T06-19-03 938Z](https://user-images.githubusercontent.com/6245486/113099135-561cd800-91ae-11eb-92b4-2f727a69809c.png)


https://user-images.githubusercontent.com/6245486/113099169-6634b780-91ae-11eb-8960-87739eb854f0.mp4

**Comment by yksoft1** [comment]
Isn't it FPU related?
TH1 detects hardware floating point and will use it if found.
I've saw such problem in my Emscripten build of Neko Project 21 kai, when BINARYEN_TRAP_MODE was still supported in Emscripten and I didn't set BINARYEN_TRAP_MODE='js'.

**Comment by joncampbell123** [comment]
Are you using a build that provides less than full 80-bit IEEE precision?

VS2019 builds and any non-Intel builds may have this problem.

**Comment by joncampbell123** [comment]
It seems recent fixes to dynamic core might have resolved this... at least here on Linux, and on ARMv8 based M1 Macbooks.

If this happens again (maybe with Microsoft C++?), reopen this issue.
