### ISSUE TITLE
null modem emulation should limit connections to localhost only for security reasons

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#240]
Currently, null modem emulation (as far as I know) listens for a connection on a specific port (usually telnet port 23) and can be accessed remotely over the local area network.

The expectation (at least in my mind) is that a localhost connection is expected to enable debugging only from the same machine.

Therefore, it would be a useful security enhancement to only accept connections from localhost unless otherwise specified to avoid unexpected serial I/O from another machine on the network.

**Comment by sikthehedgehog** [comment]
I know some games used null modem for multiplayer (think of it like LAN) and there were file transfer utilities using null modem to pass files across two computers. So there's definitely more use to it than just "debugging with a local machine".

That said it'd be definitely a good thing to limit it to listening only to the one specific machine you want to interact with and nothing else. Not sure how the UI for this would look like.

**Comment by joncampbell123** [comment]
It would be a nullmodem option to enable non-localhost connections, of course.

If you want non-localhost to connect, you will be able to say so.
