### ISSUE TITLE
Wolfestein 3D does not seem to detect Disney Sound Source

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#2400]
**Describe the bug**
In Wolfenstein 3D, if the game detects you have a Disney sound source, the boot-up screen of the game shows that sound source is selected, and in-game, you can change the sound effects to sound source instead of sound blaster if you want. However, in Dosbox-X, it does not seem to be able to automatically detect the sound source.
**To Reproduce**
On main menu, go to speaker, check the checkbox on Disney, then go back to game and be disappointed that the Disney option is seemingly worthless.

**Expected behavior**
I expected Disney sound source to be selectable as a sound effect.

**Screenshots**
What it should probably look like once I have the Disney checked in the settings:
![Screenshot from 2021-03-30 01-29-01](https://user-images.githubusercontent.com/68984176/112960267-1942d980-90f9-11eb-8c1f-f7c14aa43f85.png)
On Dosbox-X, the sound source isn't even highlighted unlike in the image, which it probably should be

**Comment by rderooy** [comment]
Did you enable the parallel port in your config file?

**Comment by ualaa1** [comment]
I did check the check the dongle under the checkbox for LPT, but LPT 1 still says printer. Should LPT 1 be changed to disney instead?
