### ISSUE TITLE
F11+? shortcut system gets "stuck", acts as if F11 is constantly pressed

### ISSUE THREAD

**Issue by rebb** [joncampbell123/dosbox-x#2405]
**Description**
It seems that the F11 shortcut system can sometimes get "stuck" and then acts as if the F11 key is still being pressed while it is not.
I noticed this because i made a save-state on the character generation of Realms of Arkania - Blade of Destiny, and when i tried to name the character ( the name had an L in it ), Dosbox-X kept loading the save-state instead.

**Reproduction**
I can reproduce this atm simply by loading a save-state via F11+L.
It even causes the input to not work any more in Star Control 2.

**Expected behavior**
Game input should not act as if the F11 key is still being pressed when hitting keys.

**Environment**
Windows 7
dosbox-x-v0.83.11
dosbox-x.conf, possibly from a version before 0.83.11

**Comment by Wengier** [comment]
With DOSBox-X 0.83.11 or the latest code I have not been able to reproduce this problem on my Windows 10 system yet. Does it happen only with F11+L, or it happens with any F11 combinations (like F11+F)? And does it happen anywhere (e.g. in the DOS command line), or it happens only in certain games? Have you tried the default setting and see if it works?

**Comment by rebb** [comment]
When it happens, it also causes the F key to act as F11+F.

So far i've tested this with Realms of Arkania 1 and Star Control 2.
When it happens, it also happens on the prompt.

I just tried it with the reference dosbox-x.conf and the issue did not occur.
However - when i edited this file and changed the following settings, it started happening again :

aspect : false -> true

Sometimes you have to tap the L-Key twice for it to act like F11+L if the problem occurs.
It's quite noticable in the DOS prompt, because most of the keyboard-input then stops working, only some keys get through.

**Comment by rebb** [comment]
I also noticed that the problem only seems to happen in windowed mode.
If i load the savestate in fullscreen mode, the issues is not there.

**Comment by rebb** [comment]
I'll see if the issue still exists in the new version :)

**Comment by Wengier** [comment]
@rebb Can you try the DOSBox-X Windows binary below and see if the issue occurs when you press F11+L?

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by rebb** [comment]
@Wengier : It seems the problem does not occur with this update version :)

**Comment by rebb** [comment]
Not sure if i should add this here or make a new Issue, but even though this fixes the F11 being "stuck", i noticed that it is now needed to press F11+L twice after a while to make it load the savestate.

I'm playing something atm where i'm (ab)using the savestates quite a lot, and i'm reloading the states quickly.
But each time i need to press F11+L twice to make it actually trigger the savestate load.

I've randomly poked around in the sourcecode myself, but haven't found a good way to fix this.

**Comment by rebb** [comment]
I think i'll make a new Issue for this and close this one :)
