### ISSUE TITLE
File names that are non-representative to the guest cause Windows 3.1 setup.exe memory corruption

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#2407]
**Describe the bug**
Windows 3.1 SETUP.EXE scans all drives and directories to try to determine if Windows is already installed. If a file has a name that is non-representative in the guest code page, corruption occurs and it begins scanning gibberish nonsense paths.

**To Reproduce**
1. Copy the Windows 3.1 install disk files to a directory, mounted under C: in DOSBox-X
2. Copy some files into another folder, even another drive, with unicode characters on the host that the guest code page cannot represent (i.e. Japanese characters for the default IBM PC US code page 437).
3. CD to the folder where you copied disk 1 of Windows 3.1 setup, run SETUP.EXE
4. Allow SETUP.EXE to scan for existing Windows, observe corrupted text on screen afterwards.

**Expected behavior**
Filenames DOSBox-X cannot represent to the guest should not appear at all to the guest, much less overrun any buffers in the guest application.

![setup_000](https://user-images.githubusercontent.com/6245486/113376220-0eb95780-9326-11eb-95e4-3d7c498f2868.png)
![setup_001](https://user-images.githubusercontent.com/6245486/113376222-0f51ee00-9326-11eb-9811-b69b57467906.png)

**Comment by joncampbell123** [comment]
On my system, D: is mounted from /usr/src/doslib for DOSLIB development.

Corruption happened when Windows scanned across these particular files in the DOSLIB repo:
![image](https://user-images.githubusercontent.com/6245486/113376344-5213c600-9326-11eb-80f0-b2821701c433.png)

**Comment by CyberXZT** [comment]
A similar 'access violation' crash occurs in the Microsoft Office 4.3 installer during "Setup is searching for installed components..."

```
' from host is non-representable on the guest filesystem through code page conversion                                                                             
' from host is non-representable on the guest filesystem through code page conversion                                                                             
LOG: Limit check ffce+1-1 = ffce > b4ff ES:DI                                                                                                                     
LOG: Segment limit violation                                                                                                                                      
LOG: Limit check ffce+1-1 = ffce > b4ff ES:DI                                                                                                                     
LOG: Segment limit violation
```

**Comment by Wengier** [comment]
I think this issue only happens on Linux and macOS (non-Windows platforms), so I did not encounter this earlier. In any case, I think it is already fixed in the latest code by hiding such entries from incompatible code pages on non-Windows systems.

**Comment by CyberXZT** [comment]
Awesome.

I likely won't have the time to compile and test this before the next build comes out, but I'll let you afterwards.

Thanks!

**Comment by CyberXZT** [comment]
I can confirm that the latest release fixed both the issue I mentioned and the original setup.exe issue for me.

Thanks again!

**Comment by Wengier** [comment]
Thanks for confirming it works in the latest release. I think the issue can be closed now.
