### ISSUE TITLE
DOS/4GW "can't create swap file"

### ISSUE THREAD

**Issue by silver246** [joncampbell123/dosbox-x#2410]
When trying to start any game that uses DOS/4GW I always get the following error message:
```
DOS/4GW Professional Protected Mode Run-time Version 1.97
Copyright (c) Rational Systems, Inc. 1990-1994
DOS/4GW Professional Error (2504): can't create swap file ".\NBPLRXBJ.TMP.SWP"
DOS/4GW Professional fatal error (1011): VMM initialization error [1]
```
DOSBox-X has write access to the folder so this is not a permission problem.
The problem seems to be the 8.3.3 naming of the swap file.
When trying to create a file using DOSBox-X "edit.com"and name it "NBPLRXBJ.TMP.SWP" it cannot be created. Changing the name to "NBPLRXBJ.SWP" and it works.

After using different DOS/4GW version and setting DOS4GVM environment variable to use swap file name with 8.3 naming the games starts. This problem is not present in DOSBox 0.74 which always creates swap files with 8.3 naming.

Now the question is why does DOSBox-X create swap files with 8.3.3 naming? Why does DOSBox 0.74 not do this when using the same DOS4GW.EXE?

**Environment:**
 - Operating system: Ubuntu 20.04.2 LTS
 - DOSBox-X version 0.83.12 SDL1 (SNAP)
 - Default dosbox-x.conf

**Comment by rderooy** [comment]
A few avenues...

- You may have to ``SET TEMP=`` or ``SET TMP=`` to a location you can write to
- Run ``VER``, what is the "Reported DOS version"? If it is >=7.0 try setting it lower (e.g. ``ver set 6.22``), if it is set lower, try setting it to 7.0

Most DOS programs will try to use either the TEMP or TMP variable for temporary files, and if this is set to an invalid location it may cause problems.

Unlike vanilla dosbox, dosbox-x does supports LFN (Long File Names), which where introduced with MS-DOS 7.0 (the DOS version included with Windows 95). By setting it to 6.22 you disable the LFN support (unless you specified LFN=true in your config file). But with a copyright date of 1994, support for LFN seems unlikely, since Win95 did not come out until the year after.

**Comment by rderooy** [comment]
p.s. you can simply run ``set`` to see what your current environment variables are

**Comment by silver246** [comment]
Thanks for the quick response!

Setting `tmp` or `TEMP` to different folders does not change anything.
Changing DOS version to 3.30, 5.00, 6.22 or 7.10 also has no effect.
After setting `lfn=true` in the config file I get long file names when changing directories or using `dir` but it is still not possible to save files with names longer than 8.3.

**Comment by rderooy** [comment]
Simply setting ``lfn=true`` does not enable LFN for programs that never supported it in the first place. The DIR command included with dosbox-x obviously does support it, but I'm not sure the edit program (which came from freedos) does.

With LFN enabled, try something like:
```
echo test > .\NBPLRXBJ.TMP.SWP
```

Not saying this is actually a LFN issue.

Which program is it, that your trying to run?

**Comment by silver246** [comment]
With LFN disabled I get:
`File creation error - ./NBPLRXBJ.TMP.SWP`
After enabling LFN it works and the file gets created.

Game I try to run is X-COM: Apocalypse

**Comment by rderooy** [comment]
I have X-Com: Apocalypse and just tried it here with dosbox-x.

I found that it runs the intro, but at the end of the intro it crashes back to text mode with:

```
DOS/4GW Professional Error (2504): can't create swap file ".\SGXMGBXC.TMP.SWP"
DOS/4GW Professional fatal error (1011): VMM initialization error [1]
```

The first eight characters of the name of the swap file seems to be randomly generated as I got a different name each time.

**Comment by rderooy** [comment]
A quick test shows that this is a regression. It worked at least with 0.83.8 so somewhere in between then and now things broke.

**Comment by Wengier** [comment]
Yes, I can confirm this issue. It is hopefully fixed as part of #2416.

**Comment by DSN9990** [comment]
@Wengier Great! I experienced this same DOS/4GW error in Command & Conquer some days ago. Can you compile a new MinGW x64 SDL2 build?

**Comment by Wengier** [comment]
@DSN9990 Try this MinGW 64-bit SDL1 build (with all features including slirp backend enabled):

* [dosbox-x-mingw64.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64.zip)

**Comment by Wengier** [comment]
@DSN9990 A MinGW x64 SDL2 build is now also available from here:

* [dosbox-x-mingw64-sdl2.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64-sdl2.zip)

Check it out.

**Comment by silver246** [comment]
Works with latest build, thanks!
