### ISSUE TITLE
Transparency in Direct Draw problems (apparently on S3 video)

### ISSUE THREAD

**Issue by marcelofrau** [joncampbell123/dosbox-x#2418]
**Describe the bug**
I am not sure if this is a bug, but I am having a kind of transparency problem apparently related to the S3 and Windows 95/98 environment. I have tested several different configurations and tried a lot of modes to make it work, but all the time, the sprites/textures are not transparent with a black border. I am having this problem on several games like Super Bubsy and MIB (note on the cursor on screenshot below) 

I have also tested the same image on another pc emulator (pcem in this case) and it worked, and with this I can discard any driver or bad instalation of windows, so that's why I am thinking this is a bug on dosbox-x.. Since I prefer so much to play my games on dosbox-x instead pcem I would love to help this to be solved :)

**To Reproduce**
1 - install windows 95 or 98 
2 - install super bubsy or MIB
3 - run the game and try to play
4 - you can see the black border instead transparency on the sprites/textures right in the beginning.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1341820/113522091-48949300-959e-11eb-82fc-28acc5c45253.png)

![image](https://user-images.githubusercontent.com/1341820/113522334-e76dbf00-959f-11eb-8f8d-28332f353a2a.png)

**Environment (please complete the following information):**
 - Windows 10
 - DOSBox-X 0.83.12
 - I have tried all different configurations, starting with this: 
```
[sdl]
autolock=true

[dosbox]
title=Windows 95
memsize=64

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

```

**Additional context**
Also, I have tried the SDL 2 version to see if there was anything different.

I also tried with these configurations:
```
[sdl]
output            = default
# Possible values: default, surface, overlay, ttf, opengl, openglnb, openglhq, openglpp, ddraw.
fullscreen        = false
fullscreen        = true
fulldouble        = true
fullresolution    = desktop
windowresolution  = original
windowposition    = 
display           = 0
autolock          = true
clip_mouse_button = right
clip_key_modifier = shift
clip_paste_bios   = default
clip_paste_speed  = 30
sensitivity       = 100
mouse_emulation   = locked
mouse_wheel_key   = -1
waitonerror       = true
priority          = higher,normal
mapperfile        = mapper-dosbox-x.map
usescancodes      = auto
titlebar          = 
showbasic         = true
showdetails       = false
showmenu          = true

[dosbox]
title     = Windows 98x
memsize   = 256
machine   = svga_s3
#Possible values: vgaonly, svga_s3, svga_et3000, svga_et4000, vesa_nolfb, vesa_oldvbe
vmemsize=64
#vesa modelist width limit=0
#vesa modelist height limit=0

[dos]
ver=7.1

[cpu]
cputyp     = pentium_mmx
core       = dynamic
cycles     = max
apmbios    = true
isapnpbios = true

[keyboard]
aux            = true
controllertype = auto
auxdevice      = intellimouse45

[sblaster]
sbtype=sb16vibra
irq=5

[voodoo]
#   voodoo_card: Enable support for the 3dfx Voodoo card.
#                  Possible values: false, software, opengl, auto.
# voodoo_maxmem: Specify whether to enable maximum memory size for the Voodoo card.
#                  If set (on by default), the memory size will be 12MB (4MB front buffer + 2x4MB texture units)
#                  Otherwise, the memory size will be the standard 4MB (2MB front buffer + 1x2MB texture unit)
#         glide: Enable Glide emulation (Glide API passthrough to the host).
#                  Requires a Glide wrapper - glide2x.dll (Windows), libglide2x.so (Linux), or libglide2x.dylib (macOS).
#           lfb: Enable LFB access for Glide. OpenGlide does not support locking aux buffer, please use _noaux modes.
#                  Possible values: full, full_noaux, read, read_noaux, write, write_noaux, none.
#        splash: Show 3dfx splash screen for Glide emulation (Windows; requires 3dfxSpl2.dll).
voodoo_card   = auto
voodoo_maxmem = true
glide         = true
lfb           = full
splash        = true

#[ne2000]
#ne2000=true
#nicirq=10
#nicbase=300
#realnic=08
#backend=pcap

#[ethernet, pcap]
#realnic=08

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
frameskip        = 0
aspect           = true
euro             = -1
doublescan       = true
scaler           = none
glshader         = none
pixelshader      = none
autofit          = true
monochrome_pal   = green
ttf.font         = 
ttf.outputswitch = auto
ttf.winperc      = 60
ttf.ptsize       = 0
ttf.lins         = 0
ttf.cols         = 0
ttf.wp           = 
ttf.blinkc       = true
```

If there is anything else that I can help to provide more info, please let me know.

**Comment by marcelofrau** [comment]
I think this can be related to #532 somehow..

**Comment by joncampbell123** [comment]
Yes, this is a known issue with S3 emulation, inherited from DOSBox SVN, which does not understand transparency color key blitting.

**Comment by marcelofrau** [comment]
Is there any workaround to avoid this problem somehow? 

Like using any other video mode to emulate other videocard or something.. I don't know but dosbox-x already support some of the 3dfx stuff for 3d, it could emulate a voodoo 3 for instance that also handle 2d stuff.. (just wondering.. don't know how much effort is to solve this or event o go to this approach)

**Comment by DSN9990** [comment]
@joncampbell123 It would be good to fix this issue anyway. Is it harder to fix or not?

**Comment by joncampbell123** [comment]
I have the S3 datasheets, the question is how registers are written to tell BitBlt to key one specific color or mask as requested.

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/SVGA/S3%20Graphics%2c%20Ltd

**Comment by joncampbell123** [comment]
https://jon.nerdgrounds.com/jmcs/docs/browse/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/SVGA/S3%20Graphics%2c%20Ltd/S3%20Vision864%20Graphics%20Accelerator%20%281994%2d10%29%2epdf

Register BEE8h, index 0Eh, Multifunction Control Miscellaneous Register (MULT_MISC)
- bit 7: Don't update bitmap if color compare 0=equal 1=not equal to the color value of the source bitmap
- bit 8: enable color compare

Register B2E8h, Color Compare Register (COLOR_CMP)
- Comparison color

I'll check to see if that is being used here for transparency in some Windows 95 Direct-X based games.

**Comment by joncampbell123** [comment]
If you can, compile from the latest commit, I added code to the S3 XGA emulation to support the COLOR_CMP register and color compare blitting. So far, one Windows 95 game is happy with it, showing it's UI properly instead of with red rectangles around each part.

I can't find a working copy of Super Bubsy, can you try the latest commit with it?

**Comment by marcelofrau** [comment]
Let me try it here.. I have just pulled from master and will check.. 

![image](https://user-images.githubusercontent.com/1341820/113977623-240d1500-9843-11eb-8ea0-c3ff64bf7410.png)

Apparently it worked!! :D :D  I will try some more games, but can't test right now, so in the next hours I can test and show some other results, I was seeing this behavior in at least 2 other games and will post screenshots here with them.

Thanks so much!

**Comment by marcelofrau** [comment]
As far as I have tested, it worked perfectly! 

I grabbed here some evidence running both versions, the master build and the release 0.83.12 that was with the bug.

MIB with the master build:
![image](https://user-images.githubusercontent.com/1341820/113996900-e5ce2080-9857-11eb-8841-d2554fcbd3b2.png)

MIB with the release 0.83.12 
![image](https://user-images.githubusercontent.com/1341820/113997243-3e052280-9858-11eb-9242-7102c5a89a19.png)

Again just to have the screenshots in the same response:
Super Bubsy with the master build:
![image](https://user-images.githubusercontent.com/1341820/113997648-a227e680-9858-11eb-83d0-c2d8b811ae35.png)

Super Bubsy with the release 0.83.12
![image](https://user-images.githubusercontent.com/1341820/113997600-99cfab80-9858-11eb-90a2-452516eb2bd5.png)

For International Rally Championship there is still some issues (it was also happening on the 0.83.12) when using the 16bit accelerated mode in graphics options, but this maybe can be related or maybe this other effect here is caused by another problem perhaps?
![image](https://user-images.githubusercontent.com/1341820/113999800-aa812100-985a-11eb-833b-c7b8f0135191.png)


This is using the 8bit mode on the graphics options:
![image](https://user-images.githubusercontent.com/1341820/113999204-1b740900-985a-11eb-88a0-b516f7e950fd.png)

The changes I did on the options (sorry, the game is in Portuguese, but if you want I can grab a copy in English and run the same test, it says Video Mode, 8bits or 16bits accelerated):
![image](https://user-images.githubusercontent.com/1341820/113999425-5413e280-985a-11eb-86ad-68395151d9fc.png)

So, I think the main issue is solved but not sure if the problem happening in the International Rally Championship is related, I can try to get some logs or any other info you want to see if it is part of the same problem.


This was the latest config file that I have used:
```
[sdl]
output            = default
# Possible values: default, surface, overlay, ttf, opengl, openglnb, openglhq, openglpp, ddraw.
fullscreen        = false
fullscreen        = true
fulldouble        = true
fullresolution    = desktop
windowresolution  = original
windowposition    = 
display           = 0
autolock          = true
clip_mouse_button = right
clip_key_modifier = shift
clip_paste_bios   = default
clip_paste_speed  = 30
sensitivity       = 100
mouse_emulation   = locked
mouse_wheel_key   = -1
waitonerror       = true
priority          = higher,normal
mapperfile        = mapper-dosbox-x.map
usescancodes      = auto
titlebar          = 
showbasic         = true
showdetails       = false
showmenu          = true

[dosbox]
title     = Windows 98x
memsize   = 256
machine   = svga_s3
#Possible values: vgaonly, svga_s3, svga_et3000, svga_et4000, vesa_nolfb, vesa_oldvbe
#vesa modelist width limit=0
#vesa modelist height limit=0

[dos]
ver=7.1

[cpu]
cputyp     = pentium_mmx
core       = dynamic
cycles     = max
apmbios    = true
isapnpbios = true

[keyboard]
aux            = true
controllertype = auto
auxdevice      = intellimouse45

[sblaster]
sbtype=sb16vibra
irq=5

#[voodoo]
#   voodoo_card: Enable support for the 3dfx Voodoo card.
#                  Possible values: false, software, opengl, auto.
# voodoo_maxmem: Specify whether to enable maximum memory size for the Voodoo card.
#                  If set (on by default), the memory size will be 12MB (4MB front buffer + 2x4MB texture units)
#                  Otherwise, the memory size will be the standard 4MB (2MB front buffer + 1x2MB texture unit)
#         glide: Enable Glide emulation (Glide API passthrough to the host).
#                  Requires a Glide wrapper - glide2x.dll (Windows), libglide2x.so (Linux), or libglide2x.dylib (macOS).
#           lfb: Enable LFB access for Glide. OpenGlide does not support locking aux buffer, please use _noaux modes.
#                  Possible values: full, full_noaux, read, read_noaux, write, write_noaux, none.
#        splash: Show 3dfx splash screen for Glide emulation (Windows; requires 3dfxSpl2.dll).
#voodoo_card   = auto
#voodoo_maxmem = true
#glide         = true
#lfb           = full
#splash        = true

#[ne2000]
#ne2000=true
#nicirq=10
#nicbase=300
#realnic=08
#backend=pcap

#[ethernet, pcap]
#realnic=08

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
frameskip        = 0
aspect           = true
euro             = -1
doublescan       = true
scaler           = none
glshader         = none
pixelshader      = none
autofit          = true
monochrome_pal   = green
ttf.font         = 
ttf.outputswitch = auto
ttf.winperc      = 60
ttf.ptsize       = 0
ttf.lins         = 0
ttf.cols         = 0
ttf.wp           = 
ttf.blinkc       = true
```

**Comment by marcelofrau** [comment]
No issues so far related to this, I think we can close this bug..
