### ISSUE TITLE
MSCDEX: mounted subdirectory. Limited Support. 

### ISSUE THREAD

**Issue by github-fanuser** [joncampbell123/dosbox-x#2420]
**Please describe your question.**
A clear and concise description of what your question is. Ex. How do I [...]

**Comment by github-fanuser** [comment]
In the newest version released on 4-1-2021, when I mount multiple iso's, I get the error message in the subject line. When i type imgmount with parameters, it shows no files mounted. I decided go go back to the previous version (3-1-2021) and the iso's mount with no trouble. It appears that something has changed or broke in the latest release. I have been using the -t cdrom switch, I tried -fs iso switch in the latest release, but did not work. I am running the command from a .bat file; so the command has not changed.

**Comment by Wengier** [comment]
Thanks for reporting! I think you use Windows, and can you try the updated Windows binary which likely fixes the said issue:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by github-fanuser** [comment]
This version works, I use 64 bit SDL2. SDL1 does not work with one of my games....the mouse pointer does not move past a particular point. I will stick with release 3-1-2021 until there is a fix for 64bit SDL2, I will try the 32bit SDL2 tomorrow; so I can determine if it is the 64bit or SDL2 that is the problem.

**Comment by Wengier** [comment]
@github-fanuser The updated MinGW 64-bit SDL2 build is available from:

* [dosbox-x-mingw64-sdl2.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64-sdl2.zip)
