### ISSUE TITLE
Game "Extreme tactics" BSODs on 0.83.12 with dynamic_x86 core while working flawlessly on 0.83.11

### ISSUE THREAD

**Issue by Diatonator** [joncampbell123/dosbox-x#2422]
**Describe the bug**
I'm emulating Win98 SE Russian edition in DoxBox-X and I'm running the game "Extreme tactics" the way it's indended to run - using the mounted CD emulation.
I'm using the dynamic_x86 core, with the normal core the game is lagging quite a bit, although is still playable (P1 MMX).
When I updated on 0.83.12 build, I cannot play the game due to fatal failures happening either in the game or OS.
The one which gives a concise error is the BSOD, which is the driver failure.

If I'm switching back to "normal" core, the game appears to be running OK.

Other things which may happen upon running the game:

- Game just freezes on the black screen
- Dosbox-X just quietly exits
- Guest OS rebooting itself

**To Reproduce**
Install the game in Win98
Keep the CD emulation on for the game to recognize the CD
Run the game 

**Expected behavior**
Works flawlessly on 0.83.11 - sounds, visuals, gameplay

**Screenshots**
Hope doesn't need translating aside from the fact that it's a driver failure:
![image](https://user-images.githubusercontent.com/75184268/113563824-0e180e00-9611-11eb-99aa-d8cdf18a7602.png)

**Environment (please complete the following information):**
 - Windows 10 x64
 - DOSBox-X 0.82.12, dynamic_x86 core
 - Dosbox-X config: [win98.zip](https://github.com/joncampbell123/dosbox-x/files/6257669/win98.zip)

**Additional context**
ISO of the game CD - Press "Скачать файл" to download the ISO.
https://www.old-games.ru/game/download/get.php?fileid=9750&modal=1

**Comment by Diatonator** [comment]
Also one thing to mention is if it doesn't find CD - it don't crash. It just says "Insert CD" and exits.

**Comment by Diatonator** [comment]
God a really similar BSOD on a Japanese game **Asuka 120 burning fest return**, same on the dynamic_x86 core
![image](https://user-images.githubusercontent.com/75184268/113600740-1db34900-9649-11eb-9570-c5258ca8854b.png)

**Comment by Wengier** [comment]
I have tried the game "Exterme tactics" on the latest code, the result is as follows:

1. With the config file you provided I got a black screen when trying to run the game.
2. With my own config file I was able to run the game and see the main menu of the game.

For this test I used the MinGW 64-bit SDL1 Windows binary. Both use the dynamic_x86 core, although I did not see the BSOD when using either config file. Which build do you use for running the game?

**Comment by Diatonator** [comment]
The game works on just Pentium processor (non MMX one) and with dynamic_x86 core.
And that other game too!

Regarding BSOD I didn't get one right away. I also got the black screen first, then I rebooted and tried to run again, and then I got the other things like BSOD.

The build I tried is Release SDL1 (Visual Studio).

**Comment by Wengier** [comment]
@Diatonator I think I have found the problem. Please check out the updated 32-bit Visual Studio SDL package:

[dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by Diatonator** [comment]
@Wengier It won't allow me to download this for some reason

**Comment by Diatonator** [comment]
@Wengier Didn't help - both games froze on a black screen with this build.

**Comment by Wengier** [comment]
@Diatonator I cannot seem to reproduce the problem with the updated build, no matter CPU type I selected.

**Comment by Diatonator** [comment]
@Wengier OK, what I did now: 
- I downloaded the build you put here on another host machine, used .conf file I provided in this issue
- Made a clean install of Win 98 SE RU on a normal core
- Switched back to dynamic_x86 core and installed the game "Extreme tactics"

Tried to run - the black screen and the freeze on a pentium_mmx processor. On pentium processor and on dynamic_x86 core it works.

- Could you've sent a wrong build?
- Maybe some of the options in the .conf file are messing with this, and you tried this on some another configuration?

**Comment by Wengier** [comment]
@Diatonator Can you try the following 64-bit SDL1 build and see if it helps on your system:

* [dosbox-x-64-update.zip](http://cndos.fam.cx/dosware/dosbox-x-64-update.zip)

**Comment by Diatonator** [comment]
@Wengier I tried to actually play the game now and discovered quite an important issue with the last build you sent here.
The game does run, but the sound actually gets screwed up!
I attached the 2 captures of the game run on 0.83.11 and your 0.83.13 build on pentium_mmx and dynamic_x86 core, and the first does contain the actual sounds of the game, and the second only has some weird crackles:
[ExtremeTacticsSoundComparison.zip](https://github.com/joncampbell123/dosbox-x/files/6288217/ExtremeTacticsSoundComparison.zip)
Setting the processor on just pentuim fixes that of course.

**Comment by Wengier** [comment]
@Diatonator I double-checked the CPU code changes, and it appears that there was one MMX opcode which still used the updated code instead of the 0.83.11 code, which I have now restored as well. Can you please try the new DOSBox-X build and see if there is any change?

* [dosbox-x-64-update.zip](http://cndos.fam.cx/dosware/dosbox-x-64-update.zip)

If there is no change, then I am afraid the issue may be caused by something else such as updates in the sound emulation.

**Comment by Diatonator** [comment]
@Wengier on this build the sound appears to work.

**Comment by Diatonator** [comment]
Confirming another broken game on dynamic core for pentium mmx on 0.83.12 - **Delta force**
![image](https://user-images.githubusercontent.com/75184268/114458837-69856580-9be8-11eb-9df2-fe0cd53db2eb.png)
I can run it somehow on 0.83.11 - with visual problems (will report later).

Also tried **Idinaloq** - Dosbox-X just quietly crashed.

Maybe it's not the game supportability problem, but the OS problem? The BSODs mentions sound driver - maybe something there?

**Comment by Wengier** [comment]
@Diatonator What if you run the game in the build I provided above, instead of 0.83.12 release version?

**Comment by Diatonator** [comment]
@Wengier pretty much the same as on 0.83.11
