### ISSUE TITLE
Add feature to enable/disable Save State compression/packing (+config option).

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#2423]
Hi! 
The feature of Save State compression I suggested to Tae Woong (Dosbox Daum build) long time in 2013, but he added it as default, unchangable from 2014, when we talked this over - he finally stabilized Save States in his mod. 
But he even made compressed EVERY part of the save with some packer method (Z/ZLIB) and then also packing the group into ZIP archive.
I think compression feature must be switchable. Why so:
1. For investigation. If you need to rip some resource from dump directly or compare savestates byte by byte - but they are COMPRESSED - better disable packing.
2. For speed up. If you HDD are fast enough (SDD for example) and you have enough disk space - just place unpacked memory dumps - will be much faster than waiting for packing EVERY time. 
I think this will also be recommended for AutoSave feature

Also i suggest making option "Save State in memory only". The very first experimental mod of savestate was in RAM only.
This option will make Savestates to RAM ONLY instead of disk save folder. This will be ultimate speed up for autosaves.

**Comment by Wengier** [comment]
@Corak667 Thanks for the suggestion. In the updated Windows build below I have added a config option "compresssaveparts" config option in the [dosbox] section which when set to false will not compress the individual components in saved states. You can try it out:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

As for saving state in memory only, which is possible but will likely require some restructure of the save state feature. After all, they have to be saved to the disk eventually and require new user interface for doing so.

**Comment by Corak667** [comment]
Thank you! Yes, It now works.

Currently with Z compression enabled it does much faster because it packing directly in memory (very fast), then it does packing to ZIP archive. So data size placed to temporal dir already small and then just packed to zip. 
If Z disabled and uncompressed - it dumps whole memory data to temporal dir (big, long time, depends on memsize= parameter) and packs it to ZIP. At least it's rippable and comparable. 
I just think, could it be packed to zip directly in memory or zip packing only works for local drive, that's why seems Tae Woong decides to force Z packer. Or maybe don't pack to ZIP also. Originally 2012x Daum build used only uncompressed method without ZIP packer too and it was fast.

**Comment by Corak667** [comment]
@Wengier Thank you! Yes, It works.
But currently with compression it does much faster because it packing directly in memory (very fast), then packing to ZIP archive. So data size placed to temporal dir already small and then just packed to zip. 
If uncompressed - it dumps whole memory data to temporal dir (big, long time, depends on memsize= parameter) and packs it to ZIP. At least it's rippable and comparable. 
I just think, could it be packed to zip directly in memory or zip packing only works for local drive, that's why seems Tae Woong decides to force Z packer.

**Comment by Corak667** [comment]
@Wengier Thank you! Yes, It works.

But currently with compression it does much faster because it packing directly in memory (very fast), then packing to ZIP archive. So data size placed to temporal dir already small and then just packed to zip. 
If uncompressed - it dumps whole memory data to temporal dir (big, long time, depends on memsize= parameter) and packs it to ZIP. At least it's rippable and comparable. 
I just think, could it be packed to zip directly in memory or zip packing only works for local drive, that's why seems Tae Woong decides to force Z packer.

**Comment by Corak667** [comment]
@Wengier Thank you! Yes, It works.

But currently with compression it does much faster because it packing directly in memory (very fast), then packing to ZIP archive. So data size placed to temporal dir already small and then just packed to zip. 
If uncompressed - it dumps whole memory data to temporal dir (big, long time, depends on memsize= parameter) and packs it to ZIP. At least it's rippable and comparable. 
I just think, could it be packed to zip directly in memory or zip packing only works for local drive, that's why seems Tae Woong decides to force Z packer.

**Comment by Wengier** [comment]
@Corak667 Yes, that is why it is now an option mainly for investigation purposes, but it will never be the default option.
