### ISSUE TITLE
Doxbox-x is damaged and can't be opened. Dosbox-x MacOS ARM on M1 MBP

### ISSUE THREAD

**Issue by apulaski17057** [joncampbell123/dosbox-x#2426]
**Please describe your question.**
A clear and concise description of what your question is. Ex. How do I [...]
When I download and run the MacOS ARM binary on my M1 mac, I receive a message that says: "dosbox-x" is damaged and can't be opened. You should move it to the Trash. I'm then given the option to move the file to the trash or to cancel. Not quite sure what I'm doing wrong but any help you can provide would be much appreciated.
<img width="963" alt="Screen Shot 2021-04-06 at 10 49 16 AM" src="https://user-images.githubusercontent.com/82044415/113731402-c3f16400-96c6-11eb-9936-e36de55a1acc.png">

**Comment by joncampbell123** [comment]
Use the Finder Info window to examine the application. Also, right-click or command-click on the application and select "Show Package Contents". Go into Contents, MacOS.

The DosBox executable should appear as a program that runs under the Terminal (has the Terminal icon). Double-clicking it should bring up the Terminal program, and DOSBox-X.

**Comment by joncampbell123** [comment]
Also try updating to the latest Mac OS. I have no idea why Gatekeeper claims the program is damaged instead of being upfront and honest that program is not signed.

**Comment by Skaggynuts** [comment]
I have learned that running the command: xattr -cr "dosbox-x.app"
Gets gatekeeper to stop complaining.

**Comment by apulaski17057** [comment]
Haven't had a moment to update my mac yet, I'll report back as soon as I do.

**Comment by Morac2** [comment]
running the attraction -lr "dosbox-x.app" command shows that the "com.apple.quarantine: 0083;60846a25;Safari;DC3C2D5D-C4CC-4608-A783-429F5513E250" is set on everything in the App.  My understanding is that should trigger MacOs to ask if the file is safe to run, but it's not.  Maybe because the app isn't signed?

**Comment by apulaski17057** [comment]
I've followed your instructions. I'm currently running the latest version of Mac OS, 11.4, and I'm still unable to open or run DosBox-X. Attached is a screen shot of the results of executing the executable from within the package contents. Thanks for your help with this, and my apologies for the delay in my response.
<img width="936" alt="Screen Shot 2021-05-29 at 12 14 07 PM" src="https://user-images.githubusercontent.com/82044415/120077347-0c4e5200-c078-11eb-8d3b-420a54f8ae59.png">

**Comment by Wengier** [comment]
@apulaski17057 Try go to the directory where the macOS zip package is extracted, where you should find two folders including "dosbox-x" and "dosbox-x-sdl2". Then run the following command:

`xattr -cr dosbox-x/dosbox-x.app dosbox-x-sdl2/dosbox-x.app`

Hope this helps.
