### ISSUE TITLE
SLIRP: no network in WIndows 95

### ISSUE THREAD

**Issue by legluondunet** [joncampbell123/dosbox-x#2433]
Hello,
I can not obtain internet on Windows 95.
I added 

```
[ne2000]
#  ne2000: Enable NE2000 Ethernet emulation.
# nicbase: The base address of the NE2000 board.
#  nicirq: The interrupt it uses. Note serial2 uses IRQ3 as default.
# backend: The backend (pcap or slirp) used for Ethernet emulation.
ne2000  = true
nicbase = 300
nicirq  = 3
backend = slirp

[ethernet, slirp]
#    ipv4_network: The IPv4 network the guest and host services are on.
#    ipv4_netmask: The netmask for the IPv4 network.
#       ipv4_host: The address of the guest on the IPv4 network.
# ipv4_nameserver: The address of the nameserver service provided by the host on the IPv4 network.
# ipv4_dhcp_start: The start address used for DHCP by the host services on the IPv4 network.
ipv4_network    = 10.0.2.0
ipv4_netmask    = 255.255.255.0
ipv4_host       = 10.0.2.2
ipv4_nameserver = 10.0.2.3
ipv4_dhcp_start = 10.0.2.15


[log]
logfile=win95osr2.5-dosbox-x.log
```

to the conf file.
Then in Windows 95 I launched the tool to discover new hardware, it found a network card called "NE 2000" and installed it:

![guest os_008](https://user-images.githubusercontent.com/325405/114133142-de655080-9905-11eb-9102-51e70a073692.png)

but still no internet.

in my dosbox-x log file I can read:

```
SLIRP: Slirp version: 4.1.0
SLIRP: Successfully initialized
NE2000: Base=0x300 irq=3
```

What did I miss?
I have to add tcp/ip protocol?
I have to modify default value in conf file?

Thank you for your help.

Infos:
OS: Ubuntu 20.04
Dosbox build: compiled from git 8 april 2021

_Originally posted by @legluondunet in https://github.com/joncampbell123/dosbox-x/issues/320#issuecomment-816420448_

**Comment by legluondunet** [comment]
Same conf works with Windows 98:
![Capture d’écran de 2021-04-09 08-01-39](https://user-images.githubusercontent.com/325405/114135805-1078b180-990a-11eb-9346-18d34f971c01.png)

**Comment by legluondunet** [comment]
I finally found the problem: 
Windows 95 installed NE 2000 network card with IPX/SPX protocol per default.
I deleted it and replaced it by MS TCP/IP protocol and it works now.
Sorry for the noise.

**Comment by legluondunet** [comment]
I will let some notes here  that could be useful to people that want to use Dosbox-x slirp network with WIndows 3.1/95/98.

Windows 98:
just install NE2000 card, reboot, it works.

Windows 95:
install NE2000 card, delete deleted IPX/SPX protocol and replaced it by MS TCP/IP protocol, reboot, it works.
ipconfig does not work,  use winipcfg instead

![guest os_009](https://user-images.githubusercontent.com/325405/114240762-5a07e180-9988-11eb-9328-84b1596c084f.png)

Windows 3.1 (not workgroup or 3.11):
more difficult...
On internet search for this program:"
ne2000.com", "winpkt.com" and "Trumpet Socket"
copy ne2000.com and winpkt.com to c:\
add this lines to autoexec.bak (inside dosbox-x conf)
ne2000 0x65 3 0x300
winpkt 0x65 
launch Windows 3.1
install "Trumpet Socket"
config "Trumpet Socket" like this:
ip address: 10.0.2.15
dns servers: 10.0.2.3
check "Packet driver"
vector: 65
netmask: 255.255.255.0
Gateway: 10.0.2.2
reboot and it should work.

![krnl386_000](https://user-images.githubusercontent.com/325405/114241322-3ee9a180-9989-11eb-9b9c-1ea1d294c566.png)

**Comment by Jookia** [comment]
Thanks so much for these notes, you're a hero! I don't know how to edit the wiki, but would you mind if I added these as notes there? Or maybe you could do that?

**Comment by Wengier** [comment]
@Jookia You are welcome to edit the Wiki of course, it is available from:

https://github.com/wengier/dosbox-x-wiki/wiki

The updated contents will be transferred to https://dosbox-x.com/wiki with the release of each new version.

**Comment by rderooy** [comment]
As also mentioned in the other issue, the fact that Win95 defaults to IPX/SPX was already documented on the wiki. As is DOS, Windows for Workgroups 3.11 and Win98.

**Comment by legluondunet** [comment]
Thank you @rderooy  , effectively I just did read the wiki about installing different Windows versions with Dosbox-x, it's very well documented and even updated with recent SLIRP feature.
It's a pity I didn't find this articles sooner.
