### ISSUE TITLE
Windows 98 Sound Blaster 16 Plug & Play driver won't work without ASP emulation

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#244]
Where Windows 95 and earlier are perfectly happy without ASP emulation, Windows 98 will not talk to the Sound Blaster 16 PnP emulation unless ASP/CSP emulation is enabled.

Workaround:

Under the [sblaster] section, add:

    enable asp=true

**Comment by joncampbell123** [comment]
DOSBox-X's current code is supposed to emulate how the DSP acts to ASP commands when no ASP is present, since (as far as I know) the CSP/ASP chip was dropped from the cards by the time they started making the PnP versions of Sound Blaster 16.

**Comment by thfrwn** [comment]
Sorry to revive this one here - I'm running Windows 98 inside dosbox-x and can't get the soundcard to work. It recognized only Ad Lib Gold Compatible (OPL3) (plus MPU-401), but no soundblaster. In the .conf, I left the standard settings (sb16). I tried `enable asp=true`, but that didn't change anything. When I try to update driver for ad lib and pick the SB16 PnP driver, Win98 complains that this is not a fitting driver, and it doesn't work after reboot and only got a yellow exclamation mark in the device manager then. Any hints?

**Comment by thfrwn** [comment]
Guess I found the solution - had to add the `Creative Sound Blaster 16 or AWE-32` driver instead, and it's now there in addition to `Ad-Lib Gold Compatible` device.

**Comment by joncampbell123** [comment]
You'll need to enable ASP emulation, Windows 98's SB16 driver won't work without it.

**Comment by joncampbell123** [comment]
You can get Windows 98 to auto-detect the SB16 if you also enable ISA PnP and set sbtype=sb16vibra
