### ISSUE TITLE
"Sudden splitscreen" on Win98 on svga_et4000 machine

### ISSUE THREAD

**Issue by Diatonator** [joncampbell123/dosbox-x#2440]
**Describe the bug**
While troubleshooting a certain game I tried changing machine type from svga_s3 to svga_et4000.
I rebooted in Win98, Windows defaulted video settings to 16 colors/640x480 and succesfully installed a new video adapter driver.
I rebooted again and tried changing color mode.
Rebooted again and got some sort of splitscreen which basically made a view of a whole bottom half of the screen obstructed and it's generally weird.

**To Reproduce**
- Machine svga_et4000, Win98SE guest
- Setup video drivers, reboot 
- Change color mode to 256 or 16bit colors.
- Reboot

**Expected behavior**
Erm.. not this.

**Screenshots**
![image](https://user-images.githubusercontent.com/75184268/114323952-4ac39800-9b30-11eb-8789-6362d25fef67.png)
Video capture: [SplitscreenCapture.zip](https://github.com/joncampbell123/dosbox-x/files/6292906/SplitscreenCapture.zip)

**Environment (please complete the following information):**
 - Win10 x64, SDL1 x64 build
 - DOSBox-X release version 0.83.12
 - Used configuration: [win98.zip](https://github.com/joncampbell123/dosbox-x/files/6292905/win98.zip)

**Additional context**
What even is this??
Is this some weird secret feature in Dosbox-X or some Win98 antics?

**Comment by joncampbell123** [comment]
This is a bug in DOSBox-X, inherited from SVN, in how 256KB VGA VRAM wrapping works.

The same happens if you ask DOSBox-X to use the ET4000 VGA ROM BIOS image instead of it's own built in INT 10h implementation, when asked to set 640x480 256-color mode.

**Comment by joncampbell123** [comment]
I'm still not entirely sure where the bit is on ET4000 cards that enables SVGA modes over standard VGA, still looking.

At some point a switch is flipped that disables the VGA 256KB address masking.

**Comment by joncampbell123** [comment]
Should be fixed in the latest commit, with or without et4000.bin.
