### ISSUE TITLE
Bad command or filename - "Start"

### ISSUE THREAD

**Issue by viki-t-s** [joncampbell123/dosbox-x#2441]
I am trying out vim for dos in dosbox-x. A couple of batch files were installed in z drive, when i installed vim. When I use the built-in batch file to launch vimtutor, I get this error "Bad command or file name Start". When I checked around, start is an internal MS dos command part of command.com and does not have any separate exe. I use command.com as shell in dosbox-x. Kindly advise what am I doing wrong. 

I am using the Dosbox-X version 0.83.12 SDL2 VS Build 64 bit

**Comment by rderooy** [comment]
START is not an internal DOS COMMAND.COM command. It is a windows shell command (CMD).

**Comment by grapeli** [comment]
`vimtutor -console`

**Comment by Wengier** [comment]
On the Windows platform you can enable START command in DOSBox-X by setting startcmd=true, but please try the suggestion given above for launching vimtutor.

**Comment by viki-t-s** [comment]
Thank you all for your suggestions. I tried grapeli's suggestion and it works. Thanks

**Comment by Wengier** [comment]
@viki-t-s The START command is for launching Windows applications from within DOSBox-X, so you should really use the other method for running DOS programs within DOSBox-X.

**Comment by viki-t-s** [comment]
Closing issue
