### ISSUE TITLE
Windows ME mystery regsvr32 crash on first boot after install

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#245]
Not sure which module or what is involved.
![boot_000](https://cloud.githubusercontent.com/assets/6245486/22412440/2494eab6-e663-11e6-9674-d7a5cb42e306.png)

**Comment by box-tortoise** [comment]
Didn't reproduce the error where PnP is disabled and vmemsize=1, although I unloaded the floppy disk image before rebooting.

**Comment by joncampbell123** [comment]
Yup, that's puzzled me too. But at the time I noticed it I was grateful to have fixed the lack of CMPXCHG8B that caused more serious BSODs.

**Comment by box-tortoise** [comment]
I appreciate your enhancements to support WinME. I was testing software that had an issue in Win95, so I tried ME; and noted the WDM driver model (SB16) and the stable user interface which seemed more like modern Windows than Win9x.

**Comment by joncampbell123** [comment]
I did a recent reinstall of Windows ME in DOSBox-X and this issue did not reoccur. If it consistently does not occur I'll go ahead and close this.

**Comment by joncampbell123** [comment]
As far as I know this was caused by a problem with either APM BIOS emulation or lack of the CMPXCHG8B instruction in the CPU.

I'll test-install Windows ME again in DOSBox-X. If this crash doesn't happen, I'll close the issue.
