### ISSUE TITLE
Win98 video corruption with default machine type

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#2451]
**Describe the bug**
With the latest code and default machine type (svga_s3), I get the following when selecting to shutdown windows:

![guest os_032](https://user-images.githubusercontent.com/17701098/115109483-3c351080-9f76-11eb-9e6d-5a03e985ea30.png)

This seems to be some overlay that causes this. Selecting Cancel restores things.

**Comment by Diatonator** [comment]
Yes
![image](https://user-images.githubusercontent.com/75184268/115116573-d743df80-9fa2-11eb-9b1f-6f1696026f08.png)

**Comment by joncampbell123** [comment]
The correct overlay can be restored by commenting out the "byte swap" patch added for Windows 3.1. Hm..

**Comment by joncampbell123** [comment]
Aha, the same register has a BUS WIDTH bit that indicates a 8 or 16-bit transfer. Do not byte swap unless BUS WIDTH is set. That fixes the hatch pattern while keeping BYTE SWP.

I'll check to see if this breaks the Windows 3.1 86C928 driver fixes.

**Comment by joncampbell123** [comment]
Fixed in latest commit.

**Comment by Diatonator** [comment]
Seems to be fixed
![image](https://user-images.githubusercontent.com/75184268/115119190-c5b50480-9faf-11eb-81e0-e67568599f52.png)
