### ISSUE TITLE
how to load windows 95-98 games with dosbox-x?

### ISSUE THREAD

**Issue by FrostKnight** [joncampbell123/dosbox-x#2454]
Is anything required besides dosbox-x to load windows 95-98 games?
There is a game called monopoly westwood, and I wanted to try to load it with dosbox-x, 
But I do not see the option to load windows 95/98 cd roms on dosbox-x 
Is there planned support for doing this without, wine or additional depends? Meaning windows 98 or windows 95 in cd rom form.
Ps, I don't have interest in the network features, so I also wondered if its possible to disable network usage in dosbox-x.

I am around, reply anytime.

**Comment by joncampbell123** [comment]
Before booting the Windows 95/98 disk image, imgmount the ISO image to a drive letter.

Use the -ide param to attach it to an IDE controller.

Like this:

imgmount d: cdrom.iso -t cdrom -fs none -ide 2m

**Comment by rderooy** [comment]
Please check the wiki, there is a guide on installing Windows in dosbox-x.

**Comment by FrostKnight** [comment]
@rderooy I saw that eventually, 

@joncampbell123 so your saying that it is possible to mount my windows 95 games with that command?

I followed your guide to install windows 95, I can now boot it at will, the only issue is with regard to loading my game into the windows 95 dosbox-x image.  

I need sleep where I am now, will try tomorrow though thanks in advance!

**Comment by rderooy** [comment]
There is no real swapping of CDs for booted DOS/Windows at this point. Once you booted DOS or Windows, your stuck with the CDs you specified beforehand. Your only option is to shutdown win95, change the IMGMOUNT command to point to the new ISOs and restart Windows.

You can however mount multiple CDs on different drive letters. And/or you can specify multiple CDs for a single drive letter and swap between them using the menu or keyboard shortcut.

```
imgmount d cd1.iso
imgmount e cd2.iso
imgmount f cd3.iso
imgmount g cd4.iso
```

Or:

```
imgmount d cd1.iso cd2.iso cd3.iso cd4.iso
```

Or a hybrid:
```
```
imgmount d cd1.iso
imgmount e cd2.iso
imgmount f cd3.iso
imgmount g cd4.iso cd5.iso cd6.iso cd7.iso
```
```

**Comment by FrostKnight** [comment]
I might be misunderstanding, but did you mean, I have to reinstall windows 95 altogether to be able to mount cd roms in dosbox-x?
I wanted to be able to mount my cd rom images within dosbox-x when windows 95 is installed.

**Comment by FrostKnight** [comment]
I have a slight correction to make to my earlier reply, I got it working now, but the odd thing is, only one cd rom image can be detected and run at a time.  Only D Drive will let me run my game or games as the case may be. 
You know the whole copy protection crap issue I am sure... its one of those games. I have a few like it, 
Weird right?   This can be closed though I would think, thank you for your help.   Appreciate it!
