### ISSUE TITLE
"Mapper file saved" - Can this message also display the full path of the file?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2456]
In the mapper editor, when I click "Save", the editor displays a message "mapper file saved" - but it doesn't tell the path and filename. I can use config -get sdl to find the filename, but not the full path. Since DOSBox-X clearly knows the path and name of the file that it's saving, could it also display that information when it saves the file?

I hope this won't be hard to implement, and it will spare users some frustration.

**Comment by Wengier** [comment]
Use GetFullPathName function on Windows to get the full path and filename of the mapper file, e.g.

`char path[256];if (GetFullPathName(mapper.filename.c_str(), 256, path, NULL)) LOG_MSG("Saved mapper file: %s", path, NULL);`

For non-Windows systems, please use realpath function instead.

**Comment by emendelson** [comment]
@Wengier Thank you. Presumably it should be possible to use something like this in the mapper-editor code to display the path. If no one adds this to the code, I'll try to implement it myself, but I don't think I have nearly enough skill to make it work.

**Comment by Wengier** [comment]
@emendelson If you use Windows, you can just add the line I mentioned above _as-is_ after line 4138 of src/gui/sdl_mapper.cpp. Then the full mapper file path will be displayed in the DOSBox-X log file. That line is not a general example but an actual implementation to display the full mapper file path in the log file. Please let me know if you need further help.

**Comment by Wengier** [comment]
It is already in the latest code. Closing.
