### ISSUE TITLE
Savestate: crash on Win32s session in Windows 3.11

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#2462]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Operating system
 - DOSBox-X release version or commit SHA1 this issue occurred on
 - Used configuration, e.g. ```dosbox-x.conf```

**Additional context**

**Comment by Wengier** [comment]
This can be possible since it is known that the save state feature is not yet perfect at this time, although it should work in many or most cases in general.
