### ISSUE TITLE
opening a file opened exclusively in another program - bad error 

### ISSUE THREAD

**Issue by ptakgit** [joncampbell123/dosbox-x#2469]
When you try to open a file that is exclusively open in another program, a "file does not exist" error is reported. An error should be reported correctly "File access denied".

**Comment by Wengier** [comment]
Thanks for reporting. Please try the updated 64-bit Windows binary:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by ptakgit** [comment]
Thank you for so fast and great support. The modification works fine.
