### ISSUE TITLE
when the fastbioslogo = true option is enabled, the display is not set correctly - the screen crashes 

### ISSUE THREAD

**Issue by ptakgit** [joncampbell123/dosbox-x#2471]
**Describe the bug**
when the fastbioslogo = true option is enabled in .conf file and ttf.lins = 43, ttf.cols = 132, the display is not set correctly - the screen crashes 

[dosbox-x.zip](https://github.com/joncampbell123/dosbox-x/files/6367276/dosbox-x.zip)

**To Reproduce**
1. use dosbox-x.conf
2. run dosbox-x.exe
3. see dosbox screen

**Screenshots**
![correctScreen](https://user-images.githubusercontent.com/60302325/115913048-64d67200-a470-11eb-9de9-8a3421ec5f67.png)
![IncorrectScreen](https://user-images.githubusercontent.com/60302325/115913051-66079f00-a470-11eb-9f5e-f5a3f843eaf0.png)

**Environment (please complete the following information):**
 - Windows 10, pro, 64bite
 - DOSBox-X Latest Release: 0.83.12, Release Date: April 1, 2021
 - Used attached configuration

**Comment by Wengier** [comment]
Thanks for reporting. Please try the updated 64-bit Windows binary:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by ptakgit** [comment]
Thank you for so fast and great support. Now the problem is gone.
