### ISSUE TITLE
database indexing is 3 x slower then in DOSBOX or VDOS

### ISSUE THREAD

**Issue by ptakgit** [joncampbell123/dosbox-x#2473]
Database indexing in Foxpro program is 3 times slower then in original DOSBOX or VDOS.
Demo file is attached - unzip attached ZIP into folder and run TEST.EXE. Is run foxpro command for to create index.
Please, is it possible to optimize it for to comparable speed with DOSBOX or VDOS?
[TEST.zip](https://github.com/joncampbell123/dosbox-x/files/6367604/TEST.zip)

**Comment by grapeli** [comment]
The slowdown factor in dosbox-x is `diskio_delay`. Any program that reads or writes large amounts of data will therefore run slower in dosbox-x than in dosbox-SVN. For example, data compression, decompression. Most often, the slowdown is several or a dozen percent. In this test it goes up to 2.7x.

**Comment by Wengier** [comment]
@grapeli Thanks for the information. This is indeed the reason for the said slowdown.

@ptakgit DOSBox-X tries to emulate the disk IO delay by default as part of its emulation, but if you just want the speed as in original DOSBox, then you can set the following to disable the disk IO delay:

``
[dos]
``
``
hard drive data rate limit = 0
``

Hope this helps.

**Comment by grapeli** [comment]
> 
> `[dos]`
> `hard drive data rate limit = 0`
> 
> Hope this helps.

@Wengier 
Oh yeah it helps.

Why doesn't it work that way.
`dosbox-x -set "hard drive data rate limit"=0`

**Comment by Wengier** [comment]
@grapeli Try this:

``
dosbox-x -set "dos hard drive data rate limit=0"
``

For config options with spaces you need to specify the section name in front of it.

**Comment by grapeli** [comment]
@Wengier 
Unfortunately, it doesn't change anything.

**Comment by Wengier** [comment]
@grapeli Glad to hear that.

**Comment by ptakgit** [comment]
Thank you all very much. This solution works fine. If I can recomend, It would be good to mention this possibility in the documentation. This can be crucial for data processing programs.

**Comment by Wengier** [comment]
The use of option “hard drive data rate limit=0” is now covered in the FAQ section on https://dosbox-x.com/wiki/
