### ISSUE TITLE
When I stop video recording with revision bd2664ba65b06e67df598c360e997bc1c78d646c, dosbox freezes.

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#2483]
**Describe the bug**
I recorded a video of a game in Tandy mode, and when I stopped the recording using dropdown-menu and unchecking "Capture/Record video to AVI", dosbox-x freezes.

**To Reproduce**
See above.

**Expected behavior**
Dosbox-x not freezing :)

**Environment (please complete the following information):**
 - Archlinux
 - Commit: 

bd2664ba65b06e67df598c360e997bc1c78d646c
 - Used configuration: machine=tandy in main section, and sbtype=none in soundblaster section.

**Comment by Wengier** [comment]
I have not been able to reproduce the problem so far, with the settings machine=tandy and sbtype=none. Perhaps the issue is related to other settings in your configuration file, or the specific game you are doing the recording?

**Comment by FredBezies** [comment]
Only other settings were the working dir and the use of the midi roms.  So, it could be a bug with the game too.

**Comment by grapeli** [comment]
I cannot confirm this by running Sid Meier's Civilization with `machine=tandy` and `sbtype=none`. In both the case of capture format avi+zmbv and mpeg-ts+h.264, everything records correctly and nothing freezes.

**Comment by FredBezies** [comment]
Looks like last revision of Planet-X3 is kinda buggy here. Closing the bug.
