### ISSUE TITLE
DOS program can't start 

### ISSUE THREAD

**Issue by ptakgit** [joncampbell123/dosbox-x#2484]
I tryed to run attached refox.exe with several combinations of the DOSBOX-X setting, but without success. The refox should be show a dialog after start, but only black window is visible.
Can I recognize, where the problem could be? If yes, how? Or is somewhere discribed the setting for the best backward compatibility for this situation? This program worked well also in 32 bite Windows 10 yet.
I don't know much about assembler, so I am not able to debug in DOSBOX debugger.
Thank you for help.
correct screen after start:
![refoxStartScreen](https://user-images.githubusercontent.com/60302325/116123841-cb9f9980-a6c3-11eb-9ccc-f38859b91890.png)

**Comment by Wengier** [comment]
I have tried the program in vanilla DOSBox, vDos(Plus), as well as a real MS-DOS system and MS-DOS prompt under Windows 98, and the program did not run in these environments either. It only appears to run inside NTVDM so far. Perhaps the program expects a very specific configuration which is the case for in the NTVDM environment?

**Comment by grapeli** [comment]
Try to run without the title screen.
`REFOX.EXE -T`

**Comment by ptakgit** [comment]
Great. Thank you very much. The REFOX.EXE -T works. Refox is a commercial software, so maybe this solution could be usefull for other people. Do you will add it to some "known problems" document?
I also deleted the ZIP file from my first comment.
