### ISSUE TITLE
Cycle with test if file exists in directory with 1835 files will crash the DOSBOX-X.

### ISSUE THREAD

**Issue by ptakgit** [joncampbell123/dosbox-x#2485]
Cycle with test if file exists in directory with 1835 files will crash the DOSBOX-X.

**To Reproduce**
1. unzip DIRTEST
2. run DIRTEST.EXE. Program read all file names in directory DATA and in cycle test, if file exist. Somewhere up of 1616 file the DOSBOX-X crash. Succes is reported by text "OK - press any key"

The test program is very simple (DIRTEST.PRG):

* read files in directory to the array
=adir(pole,'&odkud_dir.\&jake_soub')
if type('pole')<>'U'
  * cycle for every files
   for i=1 to alen(pole,1)
       soub=odkud_dir+'\'+pole(i,1)
       * test if file exists
       if file(soub)
       endif
       ? m.i
   endf
endif   
rele pole,i,soub
retu

[DIRTEST.zip](https://github.com/joncampbell123/dosbox-x/files/6386691/DIRTEST.zip)

**Comment by Wengier** [comment]
Thanks for reporting. I can reproduce the said issue in DOSBox-X (and vanilla DOSBox) when running the test program from a mounted local drive. The program calls the FindFirst functions numerous times, which likely causes the DOSBox/DOSBox-X drive cache code to run out of resource and crash when repeatedly executing in the following line in src/dos/drive_cache.cpp:

```
CFileInfo* info = new CFileInfo;
```

The issue won't occur if I run the test program from a mounted disk image, but will end in the message "Feature not available", which is the same if I run the program from a real DOS system.

**Comment by ptakgit** [comment]
Sorry, I have forgoten a command for debugging in source code (set step on), which is not interpreted in a runtime version of the FoxPro (compilator and interpreter) and throws this error message. But it is also means, that all files were processed and result is OK.

**Comment by ptakgit** [comment]
Also a file copy in directory with many files is wery slow. Try example - file copy FILECOPY.EXE. After unzip /FILECOPY.zip run FILECOPY.EXE. It copy 100 files from DATA directory to the OUT (OUT dir must exists before).
In VDOS it take 0.14 sec, DOSBOX 0.9 sec, DOSBOX-X 28 sec !!!
Directory casch in .conf file is disabled.

[FILECOPY.zip](https://github.com/joncampbell123/dosbox-x/files/6389116/FILECOPY.zip)
DOSBOX-X config file
[dosbox-x.zip](https://github.com/joncampbell123/dosbox-x/files/6389123/dosbox-x.zip)

**Comment by Wengier** [comment]
@ptakgit For your original question, it seems that the said issue only occurs in 32-bit DOSBox-X builds, but not 64-bit DOSBox-X builds, which have more resource available. So you can try the 64-bit MinGW build(s) below instead so that all files should be processed normally.

MinGW 64-bit SDL1 build: http://cndos.fam.cx/dosware/dosbox-x-mingw64.zip
MinGW 64-bit SDL2 build: http://cndos.fam.cx/dosware/dosbox-x-mingw64-sdl2.zip

For the file copying test, with the default setting DOSBox-X is indeed slower than DOSBox or vDos for this test, but this is simply because DOSBox-X implements many things not supported by other DOS emulators, and there may be config options that can greatly help you with this if you just want speed comparable to DOSBox or vDos, like the option "hard drive data rate limit = 0" mentioned earlier.

**Comment by ptakgit** [comment]
I confirm that MinGW 64-bit SDL1 works correctly in the "if file exists" test. Will you be able to correct the problem in the 32-bit version in the future?

Copy test: I understand that DOSBOX-X is more complicated than VDOS, but 100 times slowing down compared to VDOS seems inadequate to me. I assume that this is a bit of an extreme situation in my test, but this slowdown will also be reflected in normal use.
I have already the option "hard drive data rate limit = 0" set in .conf file.

**Comment by Wengier** [comment]
@ptakgit With the default setting and the option "hard drive data rate limit = 0" alone I get around 7-9 seconds (not 28 seconds) for your file copy test in DOSBox-X. Of course there may be other settings similar to "hard drive data rate limit = 0" you can also add to greatly improve the test further (perhaps @grapeli can help with this again).

I did have a temporary solution for the original problem in 32-bit version, but it is not good enough and I hope there will be a better solution in the future.

**Comment by ptakgit** [comment]
I understand. But, please, try a simple command directly in the DOSBOX-X (first delete the contents of the OUT folder, run the command in the folder containing my test directory DATA and OUT):
copy DATA \ *. * OUT
On my PC, this operation takes so little in VDOS and DOSBOX that I can't even measure it - say maybe 1 sec.
DOSBOX-X will do the same in 110 sec!!!
Then try to delete the contents of the OUT directory by the command "del OUT \ *. *" - it also takes a very long time. I write this because it probably doesn't matter in games, but it starts to have an effect on working with database files. I know that the author of VDOS, Mr. Schaars, redesigned the FindFirst, FindNext implementation. 

My conf file is attached
[dosbox-x.zip](https://github.com/joncampbell123/dosbox-x/files/6389651/dosbox-x.zip)

**Comment by grapeli** [comment]
@Wengier 
In the case of the FILECOPY.EXE test, the core C library (system functions, toolchain type) has a big impact on dosbox-x performance.
In my case, this translates to 8-9x slower performance compared to dosbox-SVN (much less than 28x).
-X
```
50.04%  libc-2.33.so                [.] __strcasecmp_l_sse42
 5.96%  dosbox-x                    [.] DOS_Drive_Cache::GetLongName
 3.53%  dosbox-x                    [.] VGA_TEXT_Xlat32_Draw_Line
 2.87%  dosbox-x                    [.] String_HOST_TO_SBCS<unsigned short>
 2.34%  dosbox-x                    [.] strcasecmp@plt
 2.32%  libc-2.33.so                [.] __strcasecmp_sse42
 1.32%  dosbox-x                    [.] RENDER_StartLineHandler
 1.32%  libc-2.33.so                [.] __memmove_sse2_unaligned_erms
 0.82%  libc-2.33.so                [.] __strcpy_sse2_unaligned
 0.73%  dosbox-x                    [.] CPU_Core_Dyn_X86_Run
 0.67%  libc-2.33.so                [.] __memcmp_sse4_1
 0.67%  libc-2.33.so                [.] __strcmp_sse2_unaligned
 0.66%  dosbox-x                    [.] WildFileCmp
 0.62%  libc-2.33.so                [.] malloc
 0.56%  libc-2.33.so                [.] _int_malloc
```
SVN
```
2.78%  libc-2.33.so                [.] __strcpy_sse2_unaligned
2.57%  dosbox                      [.] CPU_Core_Dyn_X86_Run
2.44%  dosbox                      [.] WildFileCmp
2.17%  dosbox                      [.] CPU_Core_Normal_Run
2.11%  libc-2.33.so                [.] __strcmp_sse2_unaligned
2.06%  dosbox                      [.] VGA_TEXT_Draw_Line

```
Dosbox-X has grown into a variety of additional implementations like LFN and other.

**Comment by Wengier** [comment]
@grapeli Thanks for the information, which is certainly helpful.

@ptakgit Please check out the updated MinGW 64-bit SDL1 build. If I run the DOSBox-X binary with the default setting (i.e. ``dosbox-x -defaultconf``, with default directory caching, no LFN), the FILECOPY.EXE test completes in about 3 seconds here with the build. The command ``del OUT \ *. *`` should be also faster in this case. Other performance impact may also be caused by core C library (system functions, toolchain type) as mentioned above.

* [dosbox-x-mingw64.zip](http://cndos.fam.cx/dosware/dosbox-x-mingw64.zip)

The redesign of the FindFirst, FindNext functions in vDos is not a bad thing, but for the purpose of this discussion it performs about the same as DOSBox anyway.

**Comment by ptakgit** [comment]
Thank you for your effort. In the extreme case, some functions (such as copying larger count of files, bulk deleting, etc.) can be implemented by the windows external library. I turn off the directory caching due to the possibility of changes (such as creating a file) from external programs. So I will hope that sometime in the future there may be a better solution within DOSBOX-X.

**Comment by grapeli** [comment]
@Wengier 
This [commit](https://github.com/joncampbell123/dosbox-x/commit/427fd343cd33ec437e20d3dbd004ca1484f118d0) improved a lot.
`FILECOPY.EXE`
0.66-0.72s -SVN
1.12-1.19s -X
`copy DATA\*.* OUT\`
0.128s -SVN (it's really fast)
8.978s -X (much better than it was)

**Comment by ptakgit** [comment]
@Wengier
That looks promising. Could you please send me a link to the exe?

**Comment by grapeli** [comment]
@ptakgit 
I suspect that this binary provided by @Wengier [above](https://github.com/joncampbell123/dosbox-x/issues/2485#issuecomment-828422069) already contains this change.
