### ISSUE TITLE
Audio tracks folder when unpacked?

### ISSUE THREAD

**Issue by starinspace** [joncampbell123/dosbox-x#2496]
When I use `IMGMOUNT d BRR\BRR.CUE -t cdrom` that contains "audiotracks", it does play them in the game. I also tried with deleting the audiotracks and put them in a folder thats in the same folder as the bin and cue-file and called it "audio" and places the files there from the disc. It does also work. However, If i extract all files from the disk I have to use `MOUNT` instead, I did try putting the audio-files in the folder the game is, does not work, is it possible to get this to work? Also is only Wav supported?

**Comment by rderooy** [comment]
The file BRR.CUE is a text file that should contain the filename and paths of the data and audio tracks.

Note that, in general, it is best to only specify the filename and not the path to any bin or audio files INSIDE the CUE file. Also, make sure that the filenames are correct. Some systems are case-sensitive, so if the filename is "track03.wave" the reference to it in the CUE file should be exactly the same.

And if you look at the feature highlights:
https://dosbox-x.com/wiki/DOSBox%E2%80%90X%E2%80%99s-Feature-Highlights

**Support for cue sheets with FLAC, MP3, WAV, OGG Vorbis and Opus CD audio tracks**

With DOSBox-X it is possible to mount .cue files (either from the menu or with IMGMOUNT command) that include FLAC, MP3, WAV, OGG Vorbis and Opus music as CD audio tracks.

**Comment by starinspace** [comment]
So...if i extract the files i only need to imgmount a cue-file that points to the wav-files?

**Comment by Wengier** [comment]
@starinspace Yes, only cue sheets are needed for mounting audio (WAV, etc) files, e.g.

```
FILE "audio.wav" WAV
  TRACK 01 AUDIO
    INDEX 01 00:00:00
...
```

**Comment by starinspace** [comment]
Oh, thank you, got it to work at last!

**Comment by starinspace** [comment]
Problem solved.
