### ISSUE TITLE
Help with new code for System Menu?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2498]
There is no reason why anyone should waste their time helping me to sort this out, but I hope someone might be generous enough to point the way.

My DOSBox-X fork adds some items to the Windows system menu; the code that I used earlier now causes errors when I plug them into the latest code. Can anyone suggest what I would need to do to prevent the errors. Here is what my formerly-working code did (using one example):

**resource.h**

`# define ID_WIN_SYSMENU_WEBSITE 0x0F0B`

**menu.cpp**
```
{
        const char* msg = "DOSBoxWP &website";
        memset(&mii, 0, sizeof(mii));
        mii.cbSize = sizeof(mii);
        mii.fMask = MIIM_ID | MIIM_STRING | MIIM_STATE;
        mii.fState = MFS_ENABLED;
        mii.wID = ID_WIN_SYSMENU_WEBSITE;
        mii.dwTypeData = (LPTSTR)(msg);
        mii.cch = (UINT)(strlen(msg) + 1);

        InsertMenuItem(sysmenu, GetMenuItemCount(sysmenu), TRUE, &mii);
    }
```

**sdlmain.cpp**
```
case  ID_WIN_SYSMENU_WEBSITE:
   ShellExecute(0, "open", "http://www.columbia.edu/~em36/wpdos/dosboxwp.html", "", NULL, SW_SHOWNORMAL);
```

I see that the current code requires a `key=` near the top of the block in menu.cpp, and that seems to refer to something on the main menu. But it's not clear to me whether system menu items need to have corresponding items on the main menu. If that's the case, then I'll just have to study the code to figure this out. (And I see that this would make the items available to non-Windows users.) Meanwhile, if anyone has any guidance, I'll be glad to have it.

**Comment by Wengier** [comment]
@emendelson The ```key=``` line is for items appears in the main menu to make the following line shorter. It is not necessary for the item you want to add. For your item you can try the following in menu.cpp:

```
    {
        memset(&mii, 0, sizeof(mii));
        mii.cbSize = sizeof(mii);
        mii.fMask = MIIM_ID | MIIM_STRING | MIIM_STATE;
        mii.fState = MFS_ENABLED;
        mii.wID = ID_WIN_SYSMENU_WEBSITE;
        mii.dwTypeData = L"DOSBoxWP &website";
        mii.cch = (UINT)(wcslen(mii.dwTypeData)+1);

        InsertMenuItemW(sysmenu, GetMenuItemCount(sysmenu), TRUE, &mii);
        if (buffer != NULL) {delete[] buffer;buffer = NULL;}
    }
```

Hope this helps.

**Comment by emendelson** [comment]
@Wengier Thank you for this! I figured some of this out while you were posting, but I didn't realize that it could be as simple as your example. That works perfectly. Thank you again!
