### ISSUE TITLE
Can't get 64-bit glide pass through working

### ISSUE THREAD

**Issue by pgalbraith** [joncampbell123/dosbox-x#2501]
I'm trying to run Myth TFL in a Win 95A machine using 3dfx glide pass through.  Everything works using nGlide and 32-bit DOSBox-X 0.83.13.  However if I try to use 64-bit DOSBox-X (also 0.83.13) with dgVoodoo 2.74.1 x64 glide DLL's (copied into the DOSBox-X exe directory), I only get a black screen (with fixed hourglass mouse pointer) on the 3dfx portions of the game.  Any thoughts about this, maybe I'm doing something wrong?

**Comment by Wengier** [comment]
The problem can either be on the DOSBox-X side or on the dgVoodoo side. Are you using the SDL1 or SDL2 build of 64-bit DOSBox-X binary? Perhaps you can try the SDL1 build if you used SDL2 build, and vice versa?

**Comment by TheMadLynx** [comment]
Have you tried 32-bit DLLs from dgVoodoo?

**Comment by pgalbraith** [comment]
Sorry for the extra-long delay, I finally got around to trying this game again with DOSBox-X 0.83.21 (SDL1, 64-bit) and dgVoodoo 2.78 64-bit glide2x.dll & 3dfxspl2.dll dropped in the dosbox-x directory, and it seems to work now.
