### ISSUE TITLE
I can't see the window.

### ISSUE THREAD

**Issue by Toadfield** [joncampbell123/dosbox-x#2507]
**Describe the bug**
If I open dosbox-x,then I just can't see the window,I can just see it in the task bar
![image](https://user-images.githubusercontent.com/68649672/117283070-bb2ab400-ae65-11eb-9765-5823a258f503.png)

**To Reproduce**
1. Open Dosbox-x

**Expected behavior**
That I can see the window

**Environment (please complete the following information):**
 - Operating system:Arch with newest kernel and kde
 - DOSBox-X release version:0.83.13-1
 - Used configuration:Standard configuration

**Additional context**
When I try it with wayland,then it works,but the gui buttons at the top don't work properly and are under the window borders and don't disappear when I don't need them.

**Comment by rderooy** [comment]
Did you compile it yourself, or are you using the flatpak?

If you compiled it yourself, did you compile the SDL1 or SDL2 version?

native wayland is only possible with the SDL2 version, **but** not recommended as you will loose the window controls. This is an issue with SDL2 and out of our hands. Hopefully a newer SDL2 version will be out soon with client-side-decoration support.
Having said that, running dosbox-x via xwayland works just fine here on my system.

**Comment by Toadfield** [comment]
I installed the aur package.
How can I start it with xwayland?
Cause I have set that every sdl app starts in wayland mode on my system.

**Comment by rderooy** [comment]
I was not aware that Arch had packaged dosbox-x. You may want to try reporting an issue then with Arch.

Normally by default dosbox-x runs in x11 (meaning xwayland, if running wayland) mode. But you can force it from the command line with

```
SDL_VIDEODRIVER=x11 dosbox-x
```

Likewise you can force native wayland with
```
SDL_VIDEODRIVER=wayland dosbox-x
```

**Comment by rderooy** [comment]
Looking at the archlinux build script
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dosbox-x

I noticed it is building the SDL1 version, so it can only do x11 video.

Instead of calling the "build" script, they should be calling the "build-debug-sdl2" script.

And "debug" in this case just means that the integrated debugger for debugging dos applications is enabled. Not debugging for dosbox-x itself.

**Comment by rderooy** [comment]
Going with the SDL2 version however, does mean sacrificing Glide support, as openglide is not compatible with SDL2. I raised an issue for this a while ago.

It does however solve some problems, notably keyboard issues with non-US layouts where some keys don't work with the SDL1 version.

**Comment by Toadfield** [comment]
Okay,I will say it to the packager that they should update it to sdl2.
But one question,when I use the sdl2 version on wayland,do I have to start it with `SDL_VIDEODRIVER=wayland` or will it automatically start with native wayland?

**Comment by Toadfield** [comment]
I think I will just use xwayland for all sdl2 programs until sdl2 selects it by default,too many sdl2 programs don't work with xwayland.
