### ISSUE TITLE
Dynamic IMGs/VHDs Support

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2515]
**Is your feature request related to a problem? Please describe.**
yes, the error "Dynamic VHDs not supported"

**Describe the solution you'd like**
add dynamic IMG/VHD support because my laptop doesnt have enough space for fixed size disks

**Describe alternatives you've considered**
(i dont know)

**Additional context**
(nothing)

**Comment by Wengier** [comment]
Thanks for your suggestion. I agree that dynamic IMGs/VHDs support is something nice to have, in addition to normal IMGs/VHDs.
