### ISSUE TITLE
was able to boot from IMG , but it couldnt boot after some time

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2518]
**Describe the bug**
Installed Windows 95 to IMG file, it was bootable but later gave me error "Error Loading Operating System"

**To Reproduce**
1. Run DOSBOX-X
2. mount img as drive C and boot
3. did this some times, but later it couldnt boot from IMG
**Expected behavior**
expected to boot from IMG, but sadly couldn't

**Screenshots**
(dont have any because deleted IMG after that)

**Environment (please complete the following information):**
 - Windows 10 Version 1909
 - DOSBox-X release version 0.83.13
 - Used configuration, the default config file
**Additional context**

**Comment by rderooy** [comment]
Possibly the filesystem in the IMG file got corrupted. You can try to mount it with z-zip as a test. Which can happen if there where unclean shutdowns.
https://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X#_using_harddisk_images_in_windows
