### ISSUE TITLE
Automountall = true - option not to list drives at startup?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2521]
With the setting `automountall=true`, the mounted drives are displayed as a list during startup. Is it possible to suppress this list so that the drives are not displayed? Possibly that option is already there, but I haven't found it. If so, apologies for wasting bandwidth.

**Comment by Wengier** [comment]
@emendelson Please check out the updated DOSBox-X build below. With the command-line option `-fastlaunch` the output made by "automountall=true" will now be suppressed as well.

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Hope this helps.

**Comment by emendelson** [comment]
@Wengier - This is excellent news. Thank you! Is it possible to add the -fastlaunch option in the conf file also, so that it doesn't require a command-line switch?

**Comment by Wengier** [comment]
@emendelson The -fastlaunch option does several things such as hiding the BIOS screen and the welcome banner, which can already be controlled by config options fastbioslogo and startbanner. If there is another config option to do exactly what -fastlaunch option does then I am afraid there will be duplicate functionalities...

**Comment by emendelson** [comment]
@Wengier - That makes perfect sense. I'll close this now, with thanks.
