### ISSUE TITLE
cannot install Windows ME

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2522]
**Describe the bug**
i read the installation guide of installing WIndows ME and it wont install
**To Reproduce**
1. Open Winme.conf with dosbox-x
2. mount Winme iso and hdd image
3. run setup

**Expected behavior**
expected for setup to continue

**Screenshots**
here is a screenshot:
![image](https://user-images.githubusercontent.com/71384075/117865265-64810800-b2b3-11eb-936b-849eeb9d9461.png)

**Environment (please complete the following information):**
 - Windows 10 Version 1909
 - DOSBox-X Version 0.83.12
 - Used configuration, e.g. ```winme.conf from Installing Windows ME guide```

**Additional context**
i even tried changing core and it still wont install

**Comment by Wengier** [comment]
Or select "CPU" => "Emulate CPU speed" => "Pentium 166MHz MMX (~97240 cycles)" from the menu. Clearly, 166MHz > 150MHz as required by the Windows ME Setup program.

**Comment by Siddhant-Mashalkar** [comment]
ok, its working now
