### ISSUE TITLE
corrupt file message

### ISSUE THREAD

**Issue by shamanlim** [joncampbell123/dosbox-x#2524]
**Please describe your question.**
A clear and concise description of what your question is. Ex. How do I [...]

I played a game Bandit Kings Of Ancient China (Chinese Version). It uses PLAY.COM to load other programs to set CGA mode, display opening animations, and run main program. But I found it back to command prompt, and something like "XXX corrupt" shown rapidly and disappeared.

If I run with MAIN.EXE, the program successfully starts but in mono mode.
So I want to ask 2 questions.
1. Is there any method to avoid "XXX corrupt" ?
2. How can I get error messages shown slowly ? （show up very fast and then become $P$G, I cannot see the whole message)

**Comment by joncampbell123** [comment]
Try LOADFIX -a before running the game.

Some games, especially older games, do not run properly if loaded too low (below the 64KB boundary) in memory. This includes executables compressed with the EXEPACK option in Microsoft linker.

**Comment by shamanlim** [comment]
Thank you. It solves my problem.
