### ISSUE TITLE
INT 21h console output does not check CTRL+C

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#2525]
**Describe the bug**
CTRL+C checking is performed on console input, but not console output. MS-DOS checks CTRL+C on both input and output.

CTRL+C should be able to terminate a program that is reading or polling the console (STDIN), and should be able to interrupt a program when it is printing to the console (STDOUT).

Test case: DOSLIB project, hw/dos/blah.c

The program prints "Blah Blah Blah" until forced to terminate with CTRL+C.

blah.c should be interruptible with CTRL+C. It is interruptible under MS-DOS 5.0, but not under the DOSBox-X DOS kernel.

**Comment by Wengier** [comment]
It is hopefully already fixed in the latest code.

**Comment by joncampbell123** [comment]
I am able to CTRL+C out of BLAH.EXE, so this is fixed now.
