### ISSUE TITLE
Full motion video playback in TekWar does not work

### ISSUE THREAD

**Issue by Candlemass** [joncampbell123/dosbox-x#2541]
**Describe the bug**
After the game initially boots you should be presented with a FMV of William Shatner. Instead the video is stuck on the first frame or two and does not play. No video or sound. The only way to move past this is to hit the escape key to the criminal objective selection screen. After selected another FMV should play and that doesn't work either. Safe to assume none of the full motion videos in the game function.

**To Reproduce**
Mount C Drive as the game directory
Image mount D Drive as disc image directory
c:
tekwar.exe

The game should then start.

**Expected behavior**
Vanilla 0.74-3 plays the videos fine albeit with some slightly annoying audio clipping but otherwise functional.

**Environment**
0.83.14 Visual Studio SDL1 build

**Comment by Candlemass** [comment]
Nevermind. This appears to be another issue with the sound card IRQ being predefined for reasons unknown in the stock config file which in several cases doesn't match with the installed game. Changing to 7 from 5 solved it.

**Comment by Wengier** [comment]
@Candlemass Glad you solved it already.
