### ISSUE TITLE
Duke Nukem (1991) sound is not right

### ISSUE THREAD

**Issue by Candlemass** [joncampbell123/dosbox-x#2544]
**Describe the bug**
Game sound is distorted.

**Expected behavior**
The same non distorted sound that vanilla 0.74-3 has.

**Video clips**
DOSBox 0.74-3:
https://streamable.com/f2zv00

DOSBox-X 0.83.14 Visual Studio SDL1 build:
https://streamable.com/p27m50

**Environment (please complete the following information):**
- Windows 7
- DOSBox-X 0.83.14 Visual Studio SDL1 build
- Used configuration:

[SDL]
fullscreen        = true
fulldouble        = true
fullresolution    = 1920x1080
windowresolution  = 800x600
windowposition    = 560,236
display           = 0
output            = ddraw
autolock          = true
clip_mouse_button = right
clip_key_modifier = shift
clip_paste_bios   = default
clip_paste_speed  = 30
sensitivity       = 100
mouse_emulation   = locked
mouse_wheel_key   = -1
waitonerror       = true
priority          = higher,normal
mapperfile        = DOSBox-X.map
usescancodes      = auto
titlebar          = 
showbasic         = false
showdetails       = false
showmenu          = false

[DOSBox]
title                 = 
fastbioslogo          = true
startbanner           = false
bannercolortheme      = default
dpi aware             = auto
quit warning          = false
show advanced options = false
hostkey               = mapper
mapper send key       = ctrlaltdel
synchronize time      = false
machine               = svga_s3
captures              = 
autosave              = 
saveslot              = 1
savefile              = 
saveremark            = true
forceloadstate        = false
memsize               = 32
nocachedir            = false
freesizecap           = cap

[Video]
vmemsize                = -1
vmemsizekb              = 0
high intensity blinking = true

[Render]
frameskip        = 0
aspect           = false
euro             = -1
doublescan       = true
scaler           = hq3x
glshader         = none
pixelshader      = none
autofit          = true
monochrome_pal   = green

[CPU]
core       = auto
fpu        = true
cputype    = auto
cycles     = max
cycleup    = max
cycledown  = max
apmbios    = true
isapnpbios = false

[Keyboard]
aux            = true
controllertype = auto
auxdevice      = intellimouse

[Mixer]
nosound    = false
swapstereo = false
rate       = 48000
blocksize  = 4096

[MIDI]
mpu401          = intelligent
mpubase         = 0
mididevice      = fluidsynth
midiconfig      = 
samplerate      = 48000
mpuirq          = -1
mt32.romdir     = 
fluid.driver    = default
fluid.soundfont = 

[SBlaster]
sbtype                       = sb16
sbbase                       = 220
irq                          = 7
dma                          = 1
hdma                         = 5
enable speaker               = false
sbmixer                      = true
oplmode                      = auto
oplemu                       = default
oplrate                      = 48000
oplport                      = 
hardwarebase                 = 220
goldplay                     = true
blaster environment variable = true

[GUS]
gus               = false
gusrate           = 48000
gusmemsize        = -1
gus master volume = 0.00
gusbase           = 240
gusirq            = 5
gusdma            = 3
gustype           = classic
ultradir          = C:\ULTRASND

[Speaker]
pcspeaker    = true
pcrate       = 48000
tandy        = auto
tandyrate    = 48000
disney       = false
ps1audio     = false
ps1audiorate = 48000

[DOS]
xms                             = true
xms handles                     = 0
shell configuration as commands = false
hma                             = true
ansi.sys                        = true
share                           = true
file access tries               = 0
network redirector              = false
minimum mcb free                = 0
dosv                            = off
ems                             = true
umb                             = true
quick reboot                    = false
ver                             = 7.1
lfn                             = true
automount                       = false
automountall                    = false
mountwarning                    = true
autofixwarning                  = true
startcmd                        = false
startwait                       = true
startquiet                      = true
int33                           = true
keyboardlayout                  = auto
dos clipboard device enable     = false
dos clipboard device name       = CLIP$
dos clipboard api               = true

[Config]
set temp    = 

[AutoExec]

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
For my the DosBox-x PC Speaker sounds like original and the DosBox74-3 sounds distorted.
Here You can compare to the PC-Speaker output of my AMD K7 PC with MS-Dos 6.2.
It is also the startsequence of DN but only audio:

[DN1_Speaker.zip](https://github.com/joncampbell123/dosbox-x/files/6525240/DN1_Speaker.zip)

Sorry for the bad quality - i recorded it with my cellphone.

**Comment by joncampbell123** [comment]
The DOSBox-X rendition is correct. It sounds that way on real hardware. The game rapidly writes counter values to the PC speaker timer in order to play it's sound effects. Every time it does, it writes the mode byte and then a counter, which has the effect of resetting the phase of the square wave and giving the sound effects that "rough" sound.

DOSBox SVN does not emulate that correctly, nor does it render changes to PC speaker output at a resolution high enough to reflect these changes, therefore the less interesting "pure tone" in DOSBox SVN.

**Comment by joncampbell123** [comment]
See also:

![Firefox_Screenshot_2021-05-21T22-16-54 536Z](https://user-images.githubusercontent.com/6245486/119203318-9dee0c00-ba47-11eb-9f57-96f40a0f01ee.png)


http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Timer/8253/8254%20programmable%20interval%20timer%20%281993%2d09%29%2epdf

**Comment by joncampbell123** [comment]
If the game were to just write the counter value without the control word aka mode byte, the 8254 would finish the cycle of the square wave before taking the new count, and it would sound like DOSBox SVN's rendition of the sound effects instead, even on real hardware.

**Comment by Candlemass** [comment]
No, vanilla DOSBox is emulating it properly. My old K6-2 machine output the same sound and it's no coincidence that every video on youtube that I watched to confirm also sounds the same way.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
@Candlemass:
No, You are wrong.
Here is a YouTube Video were a guy compares the vanilla vs. real hardware PC-Speaker sound:
https://www.youtube.com/watch?v=kBasp2kPgXI
He also says that DN1 sounds terrible in (vanilla, maybe SVN) DosBox.
I personaly think that the Videos you watched was records of vanilla DosBox gameplays because DosBox vanilla is still common.
DosBox-x Pc-Speaker emulation is very accurate. You can believe us that ;-)

**Comment by joncampbell123** [comment]
@Candlemass Can you listen closely on your K6-2? It should sound rough with harmonics, instead of a single tone.

It might not be obvious if the speaker is a tiny cone or a tiny piezoelectric speaker.

**Comment by Wengier** [comment]
@Candlemass I have also tried the game in a real Pentium system with MS-DOS and I believe the sound in DOSBox-X is correct. The sound in vanilla DOSBox is apparently off from the sound from my real DOS system.

**Comment by Candlemass** [comment]
> 
> 
> @Candlemass:
> No, You are wrong.
> Here is a YouTube Video were a guy compares the vanilla vs. real hardware PC-Speaker sound:
> https://www.youtube.com/watch?v=kBasp2kPgXI
> He also says that DN1 sounds terrible in (vanilla, maybe SVN) DosBox.
> 
> Here an another example. The guy here compares DosBox vanilla with DosBox ECE with enhanced (fixed) PC-Speaker emulation:
> https://twitter.com/jikissgamer/status/1069499727744561153
> 
> I personaly think that the Videos you watched was records of vanilla DosBox gameplays because DosBox vanilla is still common.
> DosBox-x Pc-Speaker emulation is very accurate. You can believe us that ;-)

This proved nothing. It's essentially exactly the same as the video clips I posted but in far shittier quality.

All it shows is that there's a difference not which one is accurate.

Where's the video of "real hardware" vs DOSBox vs DOSBox-X?

**Comment by joncampbell123** [comment]
@Wengier @Candlemass I have furthermore confirmed correct PC speaker behavior by writing programs to mimic how Duke Nukum programs the PC speaker, and running it on real hardware vs DOSBox-X.

Version 1: Programs PC speaker by writing control byte and counter rapidly as Duke Nukum does:

https://github.com/joncampbell123/doslib/blob/master/hw/8254/tpcrapi2.c

Version 2: Programs PC speaker by writing counter, but NOT control byte, same patterns:

https://github.com/joncampbell123/doslib/blob/master/hw/8254/tpcrapn2.c

Note that on real hardware the program only sounds like DOSBox SVN if you run TPCRAPN2.EXE (without control byte). It's writing the control byte first that resets the phase of the square wave, and therefore gives Duke Nukum's sound effects that rough sound.

For completeness, this program can compile to PC-98 if you want to confirm the 8254 and PC speaker function the same as it does on IBM PC hardware.

**Comment by sagamusix** [comment]
I can also confirm that DOSBox-X sounds exactly like I remember from real hardware.

**Comment by Wengier** [comment]
Indeed, DOSBox-X had done a lot of developments to implement accurate emulation, as can be confirmed by this one.
