### ISSUE TITLE
DOS Version running on FPGA  PC486 Core (video mode 800x600x16 with LFB not supported)

### ISSUE THREAD

**Issue by flynnsbit** [joncampbell123/dosbox-x#2550]
I am using the MiSTer FPGA 486 core and had the idea of running dosbox-x on top of it for emulating some of the older platforms (XT, PCJr, CGA games at 8Mhz etc)

Setup, latest ao486 core running at 100MHz, L1 and L2 cache on
core using ET4000 video bios
DOS 7.1 (Windows 98 version)
HIMEM, QEMM, EMM all tested.

When launching the HX version of dosbox-x I get "video mode 800x600x16 with LFB not supported"

When launching the LOADIN version the linux kernel requires a mathco so I only make it to the video mode selection and then it halts due to mathco requirement.  The core on the FPGA is more like a 486SX 66MHZ as it does not have an fpu.  

Any ideas to get passed the video error from the HX version?  I tried univbe and it didn't seem to change anything.  

One more note is dosbox-x.exe -h doesn't give anything either and shows the video mode error above.

I did find one reference here and maybe it is an issue with HX extender maybe?
https://board.flatassembler.net/topic.php?p=60581#60581

![IMG_0654](https://user-images.githubusercontent.com/32404856/119398866-cbcc8e00-bc9d-11eb-86a3-3225b135d8ec.jpg)

**Comment by Wengier** [comment]
For the HX-DOS version, there is a HXGUIHLP.INI file where you can change the video setting. You can find this in the HX-DOS package by default:

```
[display]
xres=800
yres=600
bpp=16
```

But you can certainly experiment with a different video setting and see if it works, e.g.

```
[display]
xres=640
yres=480
bpp=8
```

If it still does not, then it is likely a bug or limitation of the HX DOS Extender. You can report the issue there as it is still under active development.

As for the LOADLIN package, it is the work of @grapeli, and he may be able to help you with this.

Thanks for your support.

**Comment by grapeli** [comment]
Yes, even linux 5.2 can still run under 486SX, but I don't think that's the hardware for it.
And I can't imagine dosbox-x running under it. It really doesn't make any sense. Waste of time. I advise against.

For comparison, run this [dosbox-staging](https://github.com/dosbox-staging/dosbox-staging/files/5289092/dosbox-staging.riscv64.zip) emulator for RISCV architecture in a browser under [JSLinux](https://bellard.org/jslinux/vm.html?cpu=riscv64&url=buildroot-riscv64-xwin.cfg&graphic=1&mem=256) (let's assume about 100MIPS) and try to work in it. Now imagine that it works much slower under the 486SX (a lot, a lot).

**Comment by flynnsbit** [comment]
Fair enough. Moving on from the experiment.

**Comment by flynnsbit** [comment]
Just coming back to this and leaving a comment.  I did get the fpga core to boot using a combo of an ET6000 bios and univbe to get the LFB turned on. You can see HX load and then it goes to a black screen.  I verified that this is an issue with the way the MiSTer core has a custom video bios that operates the LFB differently and is really only setup for Windows and not DOS/UNIVBE.  So I am going to close this out and I can always revisit of the MiSTer AO486 ever has true dos video card support.
