### ISSUE TITLE
Automake message in macOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2552]
I'm not sure this is a bug. Building current code (and the same issue has appeared for many months, if I remember), this message appears at the top of the output from the build-macosx script:

`Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake line 3936.`

I don't have any idea of whether this affects anything...

**Comment by Wengier** [comment]
According to this page, it may just be a deprecation warning about automake:

https://githubmemory.com/repo/ddclient/ddclient/issues/313
