### ISSUE TITLE
Additional options for mouse scroll wheel support in QBasic/PDS/VBDOS and Microsoft EDIT

### ISSUE THREAD

**Issue by Jesae09** [joncampbell123/dosbox-x#2556]
Current scroll wheel is supported via
```
[sdl]
#   mouse_wheel_key: Convert mouse wheel movements into keyboard presses such as arrow keys.
#                      0: disabled; 1: up/down arrows; 2: left/right arrows; 3: PgUp/PgDn keys.
```
Would love to have it emulate a page scroll in QBasic/PDS/VBDOS and Microsoft EDIT by sending CTRL-up/down arrows (which does a page scroll).  Seems to be a more natural scroll.  With moving the arrow keys (option 2) the edit cursor moves up and down as expected but seems more natural to move the whole page up and down with a page scroll.  VDOS-Plus has this option (option 4):
```
(0: disabled; 1: up/down arrows; 2: left/right arrows; 3: PgUp/PgDn keys;
 4: Ctrl+up/down arrows; 5: Ctrl+left/right arrows; 6: Ctrl+PgUp/PgDn keys;
 7: Ctrl+W/Z, as supported by WordStar and MS-DOS EDIT. Default: 1,2)
```
By the way, love that you are supporting development environments!

**Comment by Wengier** [comment]
@Jesae09 Option 7 as you mentioned above is now supported too, and the latest DOSBox-X build is still available from:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Wengier** [comment]
With the release of DOSBox-X 0.83.14 these options should be officially supported. Closing.
