### ISSUE TITLE
START command under macOS - what is default directory?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2563]
It's terrifically useful to have the START command working in macOS. I can use it easily if I specify a full path or a path with "~" for the user folder. What I can't figure out is what the current directory is when I run START, so that I can use `../../path` or something similar to run an app. 

Is there an easy answer to this?

**Comment by Wengier** [comment]
@emendelson The default directory for START command is the DOSBox-X working directory. You can set this directory with the `-defaultdir` command-line option, or via the folder selection dialog if it shows up when you run DOSBox-X from the Finder. You can view the DOSBox-X working directory via the command `CONFIG -L`, which will show the following (among other things):

```
DOSBox-X's working directory:
...
```

Hope this helps.

**Comment by emendelson** [comment]
@Wengier Thank you! That's exactly what I needed to know!
