### ISSUE TITLE
DOSBox-X running without outputting to any window on OpenGL

### ISSUE THREAD

**Issue by DaVince** [joncampbell123/dosbox-x#2573]
**Describe the bug**
When I start DOSBox-X while having selected one of the OpenGL renderers, no visible window shows up. Only an entry in the taskbar appears (as shown below), but clicking on it does not make any other window appear.

It _appears_ like there is a window because the cursor gets really small on my HiDPI monitor when hovering over the area on my screen where the window is supposed to be. But it's simply not there; not even window decorations.

**To Reproduce**
1. Open DOSBox-X with fullscreen=false and output=opengl (or any of the other OpenGL output modes).

**Expected behavior**
A DOSBox-X window should appear, displaying the contents of the program.

**Screenshots**
![image](https://user-images.githubusercontent.com/105533/120692695-68fea200-c4a8-11eb-8478-8f4d7caeff6b.png)

**Environment**
- Kubuntu 21.04
- DOSBox-X commit 5dc7886e624013b5ba11f4afcc3b0f885f2a8a65 (but a version from a few months ago has the same issue)
- Config: [dosbox-x-0.83.10.conf.tar.gz](https://github.com/joncampbell123/dosbox-x/files/6593543/dosbox-x-0.83.10.conf.tar.gz)
- Proprietary NVIDIA drivers: 460.80
- Xorg 1.20.11 (12011000)
- KDE Plasma Version: 5.21.4
- Kernel Version: 5.11.0-17-generic
- Graphics Processor: GeForce GTX 1660 Ti/PCIe/SSE2

**Additional context**
* If I start with output=default and then select any of the OpenGL outputs, everything outputs just fine. It's only when I _start_ DOSBox-X with the OpenGL output selected that no window shows up (at least not visibly).
* OpenGL + fullscreen mode works fine too, until I switch to windowed mode, at which point I get the described behavior.
* DOSBox-X isn't *unresponsive*; I can still close it from the task bar and sound keeps playing.

**Comment by DaVince** [comment]
Somehow, in the KDE preview, I CAN see the game:
![Screenshot_20210603_203352](https://user-images.githubusercontent.com/105533/120694926-06f36c00-c4ab-11eb-9492-08f57c5f3216.png)

Also, regular popups show when I try to close it:
![Screenshot_20210603_203420](https://user-images.githubusercontent.com/105533/120694972-15418800-c4ab-11eb-968c-b3a48db9c7e0.png)

It's really bizarre. Everything behaves as if the window is there, except it just isn't and I can't even drag or resize the invisible area where the window is supposed to be.

**Comment by Wengier** [comment]
You appear to be using DOSBox-X 0.83.10. Can you try the latest version 0.83.14 and see if it helps in your case?

In addition, you can also try the following:

1. There is a "dpi aware" setting in [dosbox] section of the config file (dosbox-x.conf) which can be used to enable or disable the DPI aware setting, and you may want to check if changing this setting helps.

2. You did not mention if you are using SDL1 or SDL2 builds. If you used SDL1 build, then try SDL2 build and see if it works for you, and vice versa.

**Comment by DaVince** [comment]
Ah, hmmm. I just took the master branch assuming it was the latest, but I just noticed the develop branch and will recompile from that. I was using the default compiler flags (just regular ./autogen.sh && ./configure) but will explicitly select SDL2 and let you know how things look.

**Comment by DaVince** [comment]
It looks like this is a resolved issue in latest develop. Thanks for making me aware I wasn't running the latest. :smiley:
