### ISSUE TITLE
Mount command option to output directory name for one drive letter only?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2579]
I know that the mount command, without parameters, will produce a list of mounted drive letters. But for a project I'm working on, it would be convenient to be get the output for one drive letter only. For example, I would like to enter a command like this:

`mount F -d`

(either -d or some other letter not already used) and get the path of the directory mounted as (in this case) drive F:

`C:\Users\myname\Documents`

or something similar like '/Users/myname/Documents` on a Mac.

I see that I can enter a command like `mount F -o` and get output saying that drive F is already mounted with local directory C:\Users\ etc., but it would be useful to have a way to get the path without the preceding "Drive F is already mounted" string. I want to send the output to a text file that can be read by a macOS shell script, and it would make life easier if I could avoid the step of removing characters from the string. 

I hope this isn't too difficult, and that someone else might also find it useful.

**Comment by Wengier** [comment]
@emendelson I agree there should be a way to do this, and in fact the syntax can be simpler. For example, if you type the command `MOUNT F` (or `MOUNT F:`), instead of showing the usage of MOUNT command, the status of Drive F: should be shown instead (or show that the drive is not mounted if so). You can make the output shorter with the -q option, e.g. `MOUNT F -q`. Since there are different types of drives, not just directory mounts, so the string like "local directory" or "Internal Virtual Drive" will be shown in the output. Please check out the updated Windows build：

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Hope this helps.

**Comment by emendelson** [comment]
@Wengier That is very close to ideal. One request, though I don't know if it's easy:

Could the strings "local directory", "Internal Virtual Drive", etc. be padded out with spaces so that each would be the same length? That way, it would be easy for a script to strip the first 30 spaces (or whatever number it might be) and get the correct path. As it stands, any script would need to do some complex parsing of the output.

Thank you!

**Comment by rderooy** [comment]
String lengths can change depending on localization. Besides ignoring spaces and any other content you don't care about is easy with a bit of regex from a script.

**Comment by emendelson** [comment]
@rderooy - Yes, I forgot about localizations. But in extracting the path via a script, I can't remove spaces, because paths can include spaces. Perhaps the best thing would be to make the path start after a specified number of characters, no matter what the "Local directory," etc. string might be. Alternatively, perhaps the "Local directory" etc. string could come AFTER the path, with something in between that won't be used in a path name, maybe something like this:

`\Users\myname\Documents ::: local directory`

That way, a script could strip everything starting with `:::`.

**Comment by rderooy** [comment]
I think it can be done. If the final piece is "known", you can simply exclude that.

Alternatively with a bit more "creative scripting"... First you take the part from the beginning to the final path slash. For the part after that, you recursively add the next piece until you get a directory that exists. Not perfect though, as it would find "/game dir" before it would find "/game dir 2"

**Comment by emendelson** [comment]
Or there could be an additional option that outputs only the path.

**Comment by maron2000** [comment]
Hi, you can easily extract the directory name of the mounted drive by combining grep and sed.
`mount | grep "^E "| sed -e "s/^E[ ]*local directory[ ]*\(.*\) .*$/\1/"` (example to extract directory for Drive E)
However, the version I tried DOSBox-x seems that it cannot pipe 3 or more commands, I guess.

Command typed in DOSBox-x 0.83.14 Release (grep and sed works seperately, but not simultaneously)
![command_001](https://user-images.githubusercontent.com/68574602/120960340-96906780-c796-11eb-8bbe-6ffa2f881243.png)

Same command typed in Windows Command Prompt (Successfully extracted with one command)
![command_windows](https://user-images.githubusercontent.com/68574602/120960625-3b12a980-c797-11eb-97af-41759646e491.png)

Also, grep fails to find the first drive (Drive C in the screenshot below). I think a CR+LF is missing so the letter "C" isn't at the beginning of the line.
![command_002](https://user-images.githubusercontent.com/68574602/120960932-c68c3a80-c797-11eb-86b2-765b9f1e581d.png)

**Comment by emendelson** [comment]
Yes, but grep and sed aren't native commands in Windows, so that solution will only work on Linux and macOS. 

My guess is that an expert programmer could add a "path-only" option by writing three lines of code, and I hope someone might consider doing that...!

**Comment by Wengier** [comment]
@emendelson You can try the updated Windows build below. With the latest code you can add an option "-o local" for -q to show only the local directory. (the "-o local" option is for a different purpose when actually mounting a directory). For example:

`mount -q -o local c:`

Will only show the directory for local drives (and nothing for other drives). Hope this helps.

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by maron2000** [comment]
@Wengier 
Regarding the listing of mounted drives (`MOUNT` without parameters),
I think we need to put a "\n" after printing line filled with hyphen(-)s.
On the screen it looks fine, but if we redirect the output to a text file, we may see some misalignments.

Particularly, add one line in /src/dos/dos_programs.cpp 
```
        for(int p = 0;p < cols;p++) WriteOut("-");
        WriteOut("\n");   //<-- add this line
```

**Comment by Wengier** [comment]
@maron2000 Thanks for reporting this. The reason that there was no `WriteOut("\n")` before is that when the hyphens are written exactly 80 times on the screen, the cursor will automatically go to the next line, so adding the `WriteOut("\n")` command will start another new line. But I decided to solve this by writing the hyphens 79 (instead of 80) times so that this won't occur, and `WriteOut("\n")` command will generate the same result on the screen and when you redirect it to a text file. The updated Windows binary is still available from:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by Wengier** [comment]
Note that you can now also use the command `mount -q` to list the drives without showing the headers etc, and `mount -q -o local` will only list the local drives. This is an extension of the usage like `mount -q c:` as discussed earlier.

**Comment by emendelson** [comment]
@Wengier - This is extremely useful, and will save a lot of trouble. Thank you! I'll close this now.
