### ISSUE TITLE
compile dosbox-x in raspbian

### ISSUE THREAD

**Issue by isidoro-80** [joncampbell123/dosbox-x#2583]
hi i have a raspberry pi4 4 gb with retropie and pixel desktop (raspiban 32 bi). I don't want dosbox-x. I have downloaded all the required libraries but when I go to compile the dosbox program I have these errors in photo. you can help me?
![20210608_205017 1](https://user-images.githubusercontent.com/75086284/121558152-b1bcda80-ca15-11eb-91bb-072a9e2ec93e.jpg)

**Comment by rderooy** [comment]
Did you take a release build, or did you clone the git repo? If the later, can you take the latest release build as I think some changes made in the last days *may* have broken things.

Alternatively, there is a flatpak arm64 build, but even on a p4, raspbian is unfortunately still defaulting to 32bit. So you would have to manually go to a 64bit distro to use it.

**Comment by isidoro-80** [comment]
Thanks for the reply. I got the files to compile from github. now i tried to install dosbox-x on arch linux based 64bit monkajaro and i managed to install dosbox-x with flatpak and it seems to work. i would like to compile dosbox-x in rapbian 32bit

**Comment by isidoro-80** [comment]
i clone the git repo.  I haven't found any builds on the internet. sorry i don't speak english. I translate with Google. I thought I answered you. I wrote you:  I got the files to compile from github.

**Comment by Allofich** [comment]
This issue was already fixed by
https://github.com/joncampbell123/dosbox-x/commit/6da0b9914c43479af6333b65c777a26432f41a0e.

If you get the latest code the problems shown in your screenshot shouldn't happen anymore.

**Comment by Allofich** [comment]
If you are using the latest version of the code, the error should not happen anymore.

Take a look at your file `vs2015/sdl/include/SDL_syswm.h`. If it still has these lines at around line 90, 91, then you are not using the latest code. These lines caused the errors shown in your post:

```
HWND ime;				/* The Win32 input method window */
HIMC imc;				/* The Win32 input method context */<!--EndFragment-->
```

You can get the latest version of the code, or just remove these lines yourself.

**Comment by isidoro-80** [comment]
thank you very much. incredible I checked and in the online file the wrong lines are not there. I was unlucky. I downloaded a wrong version a few days ago. a few days later it was corrected. :-). Thanks for the info

**Comment by Allofich** [comment]
Happy to hear that. I think this issue can be closed now.

**Comment by isidoro-80** [comment]
I build last version dosbox-x but in build log i read many warning. Ccplus warning unrecognized command line option.... It's normal. If you want i can post log.

**Comment by Wengier** [comment]
@isidoro-80 Warnings are fine, and you can generally ignore them. But if there are errors during compilation then they probably need to be fixed.

**Comment by isidoro-80** [comment]
> @isidoro-80 Warnings are fine, and you can generally ignore them. But if there are errors during compilation then they probably need to be fixed.

hello forgive my ignorance. despite the errors the makefile is created but if I type sudo make install the process does not start. maybe to ignore the errors I have to use a different command? if the command is correct and these errors are not resolved I think it is not possible to install the program.

**Comment by rderooy** [comment]
Errors and warnings are not the same thing. It is known that there are quite some warnings during the build process. They are not fatal and afterwards you can do a "sudo make install".

If however you get an "error", that is a different matter. Then the build stops and the make install will not work.

**Comment by isidoro-80** [comment]
ok now i understand. there are warnings and errors in the file. do you plan to solve these errors?

**Comment by rderooy** [comment]
@Allofich is doing some code cleanup, which I suspect is the reason for your error.

Best thing for now would be to use a release build instead.
https://github.com/joncampbell123/dosbox-x/releases

Download one of the "Source code" packages from the URL above and build that.
