### ISSUE TITLE
A weird and silly question

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#2584]
Will a future DOSBox-X update support DOSBox-X for DOS? Not that I need to run it there, but that's how I would interpret a DOSBox-X version that handles most things.

**Comment by Allofich** [comment]
The same question was raised in another issue https://github.com/joncampbell123/dosbox-x/issues/1830, although recent discussion in that issue seems to be more about fonts than running DOSBox-X for DOS in DOSBox-X.

**Comment by Wengier** [comment]
With the latest version (0.83.14) DOSBox-X for DOS already runs in DOSBox-X, although with known issues, as mentioned in the other thread pointed out above.

**Comment by Wengier** [comment]
Moreover, there is also a LOADLIN-based DOSBox-X that also runs in DOSBox-X, and it runs relatively reliably thanks to the work of @grapeli.

**Comment by Allofich** [comment]
Do we need to keep this open? @BridgeHeadland, are you OK with using the other issue? I think we should only keep 1 issue open per topic as much as possible.

**Comment by BridgeHeadland** [comment]
> Do we need to keep this open? @BridgeHeadland, are you OK with using the other issue? I think we should only keep 1 issue open per topic as much as possible.

It is okay. I did not know about the other issue, sorry.

**Comment by Wengier** [comment]
OK, closing.
