### ISSUE TITLE
Error build 

### ISSUE THREAD

**Issue by isidoro-80** [joncampbell123/dosbox-x#2589]
I build last version dosbox-x but in raspbian on raspberry. In build log i read many warning. Ccplus warning unrecognized command line option....
And another warning midi_synth.h:48:7 error  log all was not declared in this scope
 It's normal. i post error build log.
[Nuovo.txt](https://github.com/joncampbell123/dosbox-x/files/6644652/Nuovo.txt)

**Comment by Wengier** [comment]
Perhaps this is an issue of missing the "logging.h" header file in some source file(s)? Perhaps @Allofich can check this?

**Comment by Allofich** [comment]
I'm checking it now.

**Comment by Allofich** [comment]
I test Linux builds by using Travis CI with the `build` script file in the root of the DOSBox-X source. When doing that, the error does not occur. It also doesn't occur when building with Visual Studio (testing through AppVeyor). (Note: I am getting a separate build error right now in the Linux builds, which I will submit a PR for)

According to the log file above, `midi_synth.h` was included from midi.cpp:101, which looks like

```
#if C_FLUIDSYNTH || defined(WIN32) && !defined(HX_DOS)
#include "midi_synth.h"
#endif
```

The Travis CI builds I did appear to not have been using FluidSynth. (There is a `configure: WARNING: libfluidsynth MIDI synthesis not available` in the log). I imagine to reproduce the error, it may be necessary to build on Linux with `C_FLUIDSYNTH` defined.

Unfortunately, I have little experience with building on Linux or FluidSynth, so I'm not sure how to/if this can be done through Travis CI. I wonder why the Windows build has no issue here, as you can see that it also includes `midi_synth.h` here.

@isidoro-80, you can try adding

#include "logging.h"

to the top of `src/gui/midi_mt32.h`. That should fix the error for this file, at least. But another error may appear after that if there are more problems.

**Comment by Allofich** [comment]
I got my test Linux build to compile with FluidSynth now, but it builds without any error.
@isidoro-80, please try with the latest code and let us know what happens. If you still have the error, try adding `#include "logging.h"` to the top of the src/gui/midi_mt32.h file and let us know if that fixed it. Since I can't reproduce the build error, if it does in fact still happen, I need you or someone with the same problem to help by providing such information.

**Comment by isidoro-80** [comment]
in monkajaro (arch linux 64 bit version) I compiled the latest version of dosbox-x without errors. in raspbian 32 bit I compiled the latest version with the errors I described. ieru I compiled the rebuild version as suggested by a user. the compilation was successful with only some warning. the program works. after my message has the latest version been updated? if you want I can try again with the suggestions you gave me. I will send you the log.

**Comment by Allofich** [comment]
> after my message has the latest version been updated?

After your original message in this issue, yes, there have been some changes.

> if you want I can try again with the suggestions you gave me. I will send you the log.

Yes, please try when you have some time.

**Comment by isidoro-80** [comment]
Hello yesterday comoile last versione of dosbox-x in rpi4 in retropie pixel desktop. All right the build it's ok thanks
