### ISSUE TITLE
[SDL2][GCC 11.1.0]Build process stops in sdl_gui.cpp: "error: 'MSG_Get' was not declared in this scope"

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#2592]
**Describe the bug**
Hello

I saw a building process bug. I think at once it was the same as the one in issue #2589 , but it was not because I cannot get code from Allofich to get build too.

**To Reproduce**
1. Grab last git source code, commit 7a28222 for me
2. Use these configure options: --enable-core-inline --enable-debug --enable-avcodec --prefix=/usr --enable-sdl2
3. Launch build process
4. Wait. Build will break in [log.txt](https://github.com/joncampbell123/dosbox-x/files/6647611/log.txt):25:

**Expected behavior**
Build process continuing.

**Screenshots**

**Environment (please complete the following information):**
 - Archlinux
 - commit 7a28222
 - gcc version 11.1.0 (GCC)

Adding error log.

**Comment by FredBezies** [comment]
[log.txt](https://github.com/joncampbell123/dosbox-x/files/6647619/log.txt)

Build log I forgot.

**Comment by grapeli** [comment]
https://github.com/joncampbell123/dosbox-x/pull/2590

**Comment by FredBezies** [comment]
Oops. Sorry. Closing bug.

**Comment by FredBezies** [comment]
I tried to build Dosbox-X using allofich git code. Without any luck.

**Comment by FredBezies** [comment]
Well, it looks like I made a mistake when I tried to build allofix branch.

Closing bug for good, now.

Sorry for the bugspam.
