### ISSUE TITLE
"Cycling" by Abaddon: "The end" screen triggers complains about writing ROM area 0xC0000-0xC7FFF

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#26]
64-bit Linux build.

Apparently while drawing the "The end" screen it seems to be overwriting the VGA BIOS? This is worrisome as in DOSBox-X builds the VGA BIOS is by default 12KB behind the DOSBox private area.
Even in mainline compatible mapping mode, it is seen writing all the way out to C800:0 and indeed seems to trample on DOSBox's private data area.

If the demo does this on real hardware, then I will close as "wontfix" and I recommend that people running the demo use the dosbox.conf to put DOSBox's private area in lower conventional memory instead.

**Comment by Allofich** [comment]
Just tried with the latest master branch at 5bd2212, and I can confirm this issue, or a similar one, still exists.

Starting with

`ERROR CPU:Write 0 to rom at c0000`
`ERROR CPU:Write 0 to rom at c0001`
`ERROR CPU:Write 0 to rom at c0002`
...
it continued up, one by one, to 
`ERROR CPU:Write 0 to rom at c2fff`

I didn't see it go all the way to 0xC7FFF, though, like the issue title says. Graphics also are messed up, and when running with sound (I selected "SoundBlaster" and "16Mhz") the sound cut out soon after starting (at about the 35 second mark).

Used default .conf settings.

**Comment by Allofich** [comment]
Just tried with DOSBox 0.74. It runs considerably better. There are still graphic errors but not as severe, and there didn't seem to be any problems with the sound, unless you let it run all the way to the end, after which the sound started looping in a bugged manner, but until then it was fine.

Also tried with DOSBox-SVN, and it ran the same as DOSBox 0.74.

**Comment by joncampbell123** [comment]
@Allofich The demo seems to rely on SVGA cards (like Tseng ET4000) that allowed you to map 128KB from A0000-BFFFF by setting a certain register a certain way.

On other SVGA cards, you can map A0000-BFFFF but access wraps to 64KB anyway due to how chained 256-color mode works on anything other than ET4000 cards.

Try running the demo with machine=svga_et4000.

**Comment by Allofich** [comment]
> Try running the demo with machine=svga_et4000.

Thanks, doing so seems to fix all the graphics errors.
The sound still cuts out at the same spot, and

```
ERROR CPU:Write 0 to rom at c0000
ERROR CPU:Write 0 to rom at c0001
ERROR CPU:Write 0 to rom at c0002
```
up until
```
ERROR CPU:Write 0 to rom at c2fff
```

still appears.

**Comment by joncampbell123** [comment]
The sound cuts out because DOSBox-X becomes focused on writing log output to the console for all 8192 or so writes to c0000. :)
