### ISSUE TITLE
imgmount doesnt automatically detect geometry if i use -nofs when creating img

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2600]
**Describe the bug**
When i make img with -nofs option, it isn't able to automatically detect geometry
**To Reproduce**
1. open dosbox-x
2.create img file using -nofs option
3.try mounting same image
4.see error
**Expected behavior**
expected to mount image

**Screenshots**
![image](https://user-images.githubusercontent.com/71384075/122566064-c24c0100-d064-11eb-9e78-9a3c70279c4c.png)

**Environment (please complete the following information):**
 - Windows 10 (version 1909)
 - DOSBox-X latest version
 - Used configuration:
[dosbox-x-conf.txt](https://github.com/joncampbell123/dosbox-x/files/6677198/dosbox-x-conf.txt) 

**Additional context**
no

**Comment by rderooy** [comment]
This is expected. If you use ``-nofs``, it also implies no partitions in addition to no filesystem. So your creating an empty file. You will need to specify the dimensions when mounting such a file, at least until you have created a partition.

This is documented on the wiki.
https://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X

**Comment by Siddhant-Mashalkar** [comment]
i tried specifying size but it says
Cannot Create drive from file

**Comment by Siddhant-Mashalkar** [comment]
so finally its fixed, i had to mount it as drive 2 and boot into a bootdisk to create partition

**Comment by rderooy** [comment]
Correct, if you use -nofs you need to boot dos and use fdisk to partition the disk first. This is documented on the wiki, in the installation guides for the various DOS versions.

**Comment by rderooy** [comment]
Also, you only need to use ``-nofs`` if you want to install MS-DOS prior to 3.3. From 3.3 to 4.0x you the partition layout created by imgmake is fine, you just need to do a format. From DOS 5.0 onwards, you don't even need to format the disk.

And since your using a 100MB disk, I'm assuming your using at least DOS 5.0 as older DOS versions had problems with disks of that size.
