### ISSUE TITLE
E_Exit- something is messing with the memory

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2603]
so, i installed Windows 1.0 on a MS-DOS 3.3 Hard Disk Img that i just made, i booted up and tried to run a executable
then i got this error:
![image](https://user-images.githubusercontent.com/71384075/122631003-b3596300-d0e5-11eb-9ad4-2e63c255557c.png)

**Comment by Wengier** [comment]
Can you post the image you made? It is also possible that the image is corrupted in some way...

**Comment by Siddhant-Mashalkar** [comment]
i installed Windows 2.0 instead because Windows 1 not working, btw you can try installing Windows 1, download link is here:
https://mega.nz/file/plhHWSpC#z6IpEn-htsxlNJFaNM3w7YIK1X-e87aJiDFvOOyGAW0

**Comment by rderooy** [comment]
FYI, I did not try it recently, but installing Windows 1.0x should work.
https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-1.0x

Or for Windows 2.x
https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-2.x
