### ISSUE TITLE
Linux build fails without X11 since commit 0eafde

### ISSUE THREAD

**Issue by mrfixit2001** [joncampbell123/dosbox-x#2607]
I can build the latest release without an issue but the commit 0eafde89557bfe10ee85974a1842cac39cbdcab2 has made the build fail without X11 installed now.

https://github.com/joncampbell123/dosbox-x/commit/0eafde89557bfe10ee85974a1842cac39cbdcab2#commitcomment-52450204

int_dosv.cpp:35:10: fatal error: X11/Xlib.h: No such file or directory
   35 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[6]: *** [Makefile:398: int_dosv.o] Error 1

**Comment by Wengier** [comment]
Thanks for reporting! Can you check the latest code and see if it compiles in your environment?

**Comment by mrfixit2001** [comment]
@Wengier thank you for the quick reply! I see the new commit to int_dosv, and it almost fixed it, but still fails to build, as other pieces of the code try to use some X variables.
Here are the new errors, let me know as soon as you have a new commit to test and I'll rebuild.

int_dosv.cpp:51:8: error: ‘Display’ does not name a type
   51 | static Display *font_display;
      |        ^~~~~~~
int_dosv.cpp:52:8: error: ‘Window’ does not name a type
   52 | static Window font_window;
      |        ^~~~~~
int_dosv.cpp:53:8: error: ‘Pixmap’ does not name a type
   53 | static Pixmap font_pixmap;
      |        ^~~~~~
int_dosv.cpp:54:8: error: ‘GC’ does not name a type
   54 | static GC font_gc;
      |        ^~
int_dosv.cpp:55:8: error: ‘XFontSet’ does not name a type
   55 | static XFontSet font_set16;
      |        ^~~~~~~~
int_dosv.cpp:56:8: error: ‘XFontSet’ does not name a type
   56 | static XFontSet font_set24;

**Comment by mrfixit2001** [comment]
I can confirm that updating this line:
https://github.com/joncampbell123/dosbox-x/blob/master/src/ints/int_dosv.cpp#L50

To be:
#if defined(LINUX) && C_X11

Allows for a successful compile :) So once you make that update you can close this issue.

**Comment by Wengier** [comment]
I have already made this change. Thanks and closing.
