### ISSUE TITLE
how to edit CONFIG.SYS

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2609]

**Comment by Siddhant-Mashalkar** [comment]
is there any way to edit config.sys in dosbox-x?

**Comment by Wengier** [comment]
The CONFIG.SYS file has the content of the [config] section of the config file, so you can edit its contents from there. Hope this helps.

**Comment by Siddhant-Mashalkar** [comment]
ok
