### ISSUE TITLE
Irregular SJIS code handling in PC98

### ISSUE THREAD

**Issue by tomyun** [joncampbell123/dosbox-x#2617]
Just got curious how irregular (undefined) SJIS code should be handled.

[ir.txt](https://github.com/joncampbell123/dosbox-x/files/6713674/ir.txt)

```
$ xxd ir.txt
00000000: 837e 837f 8380                           .~....
```

This text file has `837f` which is not defined (shouldn't be used because of del 7f) in SJIS code map.

However, in Anex86, it seems to be mapped to a character next to it, i.e. `8380` (ム).

![anex86](https://user-images.githubusercontent.com/906626/123372851-2ffe9e00-d539-11eb-999e-3a9108358c00.png)

In DOSBox-X, it doesn't.

<img width="752" alt="dosbox-x" src="https://user-images.githubusercontent.com/906626/123372830-25440900-d539-11eb-8e16-b56d579628a5.png">

I guess DOSBox-X is right here, but just want to double check if this is what actual hardware would behave. I'm asking this since there are some translated games somehow relying on such irregular SJIS codes for custom font mapping and they just run fine on Anex86. Then I'm afraid they would run into a problem on DOSBox-X due to this subtle difference.

**Comment by Wengier** [comment]
I also assume the DOSBox-X behavior is correct, since it does not sound right to map a undefined character to the character next to it. But you (or anyone else) please feel free to check the behavior on actual hardware so we will be sure.

**Comment by maron2000** [comment]
Hi, I think it is a bug of MS-DOS. 
The result of guest NEC MS-DOS 6.2 on DOSBox-X is shown below.
Also got the same result using NP21/w.

![shiftjis_bug](https://user-images.githubusercontent.com/68574602/123409011-ab6b5880-d5e8-11eb-895e-1e801226f212.png)
[ir.txt](https://github.com/joncampbell123/dosbox-x/files/6715439/ir.txt)

**Comment by tomyun** [comment]
Thanks for the info! Now I'm curious how many games/programs took advantage of this "undefined" behavior as most, if not all, of them were probably running on MS-DOS back in the days.

**Comment by Wengier** [comment]
Thanks @maron2000 for confirming the actual behavior on Japanese MS-DOS! I have added a config option `del` in [dosv] section (defaults to `true`) which will map the said symbol (0x7f) to the next character (0x80) for all Japanese modes (Japanese DOS/V, TTF, JEGA, PC-98) supported by DOSBox-X. Please check out the updated Windows builds:

* Windows SDL1: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

A screenshot:

![image](https://user-images.githubusercontent.com/8216923/123507341-d2e91200-d636-11eb-9165-11762afade5a.png)

**Comment by Wengier** [comment]
@tomyun DOSBox-X 0.83.15 has already been release, which has this fix included. Please check it out.

**Comment by tomyun** [comment]
Confirmed it works as described on 0.83.15. Thanks for working on this!
