### ISSUE TITLE
Might & Magic VII: For Blood and Honor - core: dynamic freezing

### ISSUE THREAD

**Issue by vinevi** [joncampbell123/dosbox-x#2621]
**Describe the bug**
[Might & Magic VII: For Blood and Honor](https://en.wikipedia.org/wiki/Might_and_Magic_VII:_For_Blood_and_Honor) freezes in outdoor areas when using software rendering. Player movement is what usually triggers the freezing. It occurs shortly after the player starts moving.

- This does not happen when rendering in hardware mode.
- This does not happen if the game is started with `no sound` flag
- Only happens in outdoor areas (the game uses 2 separate rendering engines for outdoor and indoor areas)
- Setting `core: normal` does seem to fix the issue

**To Reproduce**
1. Start a new game in software mode
2. Walk around for a bit

**Expected behavior**
No freezing during the gameplay.

**Environment:**
 - Ubuntu 20.04.2 LTS, AMD® Ryzen 3 3200u with radeon vega mobile gfx × 4
 - DOSBox-X 0.83.14 (SDL2, 64-bit)
 - DOSBox-X Configuration: 
```
[cpu]
cputype=pentium_mmx
core=dynamic
cycles=max
```
_The rest of the configuration is similar to the one from the [guide for Windows 95 installation](https://github.com/joncampbell123/dosbox-x/wiki/Guide:Installing-Windows-95)._ 

**Additional context**

- The game is using [Miles Sound System 5.0m](http://www.radgametools.com/msshist.htm) for audio playback.
- It does use MSS 3D API.
- The previous game - [Might & Magic VI: Mandate of Heaven](https://en.wikipedia.org/wiki/Might_and_Magic_VI:_The_Mandate_of_Heaven), does not have that issue. It uses 4.0b version of Miles Sound System. It does not implement 3D sound.
- After the game gets frozen the debugger shows that it is stuck in that code:

```
                   LAB_0048916a                                                                       XREF[2]:     004890cc(j), 00489189(j)  
        0048916a 8b 7f 14        MOV        EDI,dword ptr [EDI + 0x14]=>DAT_0080b76c                          = ??
        0048916d d9 c1           FLD        ST1
        0048916f d8 67 0c        FSUB       dword ptr [EDI + 0xc]
        00489172 d8 4f 04        FMUL       dword ptr [EDI + 0x4]
        00489175 d9 45 f4        FLD        dword ptr [EBP + local_10]
        00489178 d8 67 10        FSUB       dword ptr [EDI + 0x10]
        0048917b d8 4f 08        FMUL       dword ptr [EDI + 0x8]
        0048917e de c1           FADDP
        00489180 d8 07           FADD       dword ptr [EDI]
        00489182 d9 c1           FLD        ST1
        00489184 de d9           FCOMPP
        00489186 df e0           FNSTSW     AX
        00489188 9e              SAHF
        00489189 76 df           JBE        LAB_0048916a
```
Which is a part of one of the functions of the outdoor area render engine.
- The game was tested with Windows 95 and Windows 98 installations and the issue occurs with both.
- The `no sound` flag can be set via the [debug configuration file](https://tcrf.net/Might_and_Magic_VII:_For_Blood_and_Honor#mm6.ini).

**Comment by Wengier** [comment]
Thanks for reporting. It is known that the dynamic core (core=dynamic) does not work with certain games or programs, so the normal core core=normal) may be required for such programs. It is hoped for the dynamic core to work with more such programs though.

**Comment by stephenbonar** [comment]
@Wengier @vinevi I have the exact same problem, but with Might and Magic VI in Win98 SE. Setting core=normal does not fix it for me, only disabling the sound entirely using sbtype=none fixes it, as was described for other games in #2689. I have not yet tried in Windows 95. Common theme is sound seems to break many games for some reason.

**Comment by vinevi** [comment]
@stephenbonar 
It did freeze on Windows 98 on my machine as well. Windows 95 seems to be fine. I uploaded some HDD images of Might & Magic VI on Windows 95 there:
https://vinevi.github.io/might-and-magic-dosbox-x

**Comment by stephenbonar** [comment]
@vinevi Thanks! I went ahead and tried it on my own Windows 95 installation and I still have the same problem there. The game works fine as long as sound is disabled but with it enable it either hangs after the first few steps (on dynamic core) or has extremely poor performance on normal core until it eventually freezes.

**Comment by vinevi** [comment]
@stephenbonar
It might be due to an incompatible driver.  Did you install S3 driver via DirectX bundled with the game or got it elsewhere? Also what version of the game did you install? Is it patched in some way, localized?

**Comment by brunocastello** [comment]
Any game will trigger the issue, I tested FIFA 98, FIFA 99, NEED FOR SPEED II SE.

**Comment by stephenbonar** [comment]
@vinevi I followed the guidance on the Wiki in regards to the S3 driver which is "If you installed Windows 95 OSR2 or later, you already have the latest video driver installed." The version listed in Device Manager has a 8-24-1996 date (in Windows 98, it has a 4-23-1999 data. Both list Microsoft as the provider of the driver. 

As for the version of the game, the copy I have is from one of the last "collection" releases 3DO put out before going belly up (the Might and Magic Platinum Collection). The disk has a 2002 copyright, and MM6.exe lists version 1.2.

**Comment by vinevi** [comment]
@stephenbonar 
So the only difference is that in my case I install DirectX from the CD including the driver for S3. Other than that everything seems to be identical.

QEMU was freezing on Windows 98 as well on my machine.

It does look like a sound issue but what makes it strange is that hardware rendering makes it go away and it does not seem to happen in indoor environments.

**Comment by rderooy** [comment]
Does the DirectX installation install a newer S3 video driver? If so I should amend the wiki to mention that.

I know that the driver date changes depending on windows build version you install, but since there are no stand-alone S3 driver updates for 95 OSR2 or later, I figured there where none. But perhaps they are bundled with DirectX instead.

**Comment by vinevi** [comment]
Might & Magic VII got fixed by running the game with Pentium CPU type (instead of MMX or Pro). The difference is also present in the cutscenes where MMX/Pro will introduce sound artifacts.

**Comment by stephenbonar** [comment]
@vinevi Yep, that fixed it for me too on Might and Magic VI. It's now playable on Windows 98 SE on the M1 Mac. I switched to the pentium CPU type instead of pentium_mmx. Same improvements: with the audio now enabled, the audio and graphical artifacts during the cutscenes are gone and the game no longer freezes. I don't get the smoothest frame rate, but it's playable.
