### ISSUE TITLE
Issue With Dates > 6-23-2021

### ISSUE THREAD

**Issue by therube** [joncampbell123/dosbox-x#2624]
Issue With Dates > 6-23-2021

I use both MS Multiplan & Quicken DOS version 8.0.

(Today is 6-30-2021.)

In each application, it appears that 6-23-2021 is a "magic" date.
Files printed (to disk) from within Multiplan/Quicken end up dated 6-23-2021.

In Multiplan, I load a spreadsheet.
P (rint) F (ile), giving it a name, say, /tmp/OUT999.
The file is output as expected, though its date (date modified) is 6-23-2021 (rather then 6-30-2021).
(Time is not fixed, though I don't see any particular pattern to the timestamp itself.)
If I touch a spreadsheet file (outside of DOSBox-X, such that it is dated current, 6-30-2021, & I then load that file in DOSBox-X, then save it, when saved to disk, that file is dated, 6-23-2021.

In Quicken, I provide the date of a transaction.  So a transaction from yesterday is dated 6-29-2021.
(That part is fine.)
Quicken itself differentiates between current & future transactions, based on current date & transaction date.
As it is, Quicken is showing that 6-29-2021 transaction as if it were a future date (& as today is 6-30-2021, the transaction has occurred, so should display as, current.)
Similarly, when you load Quicken, the last entry display in an account is "empty" (if you will), & is where you would enter a new transaction.  That last entry, by default, displays the current date.  So Quicken, today, should be displaying 6-30-2021 in that "empty" entry. Instead, it is showing as 6-23-2021.

**Expected behavior**
New created & modified files should be dated, current.

**Environment (please complete the following information):**
 - Operating system
Win7 x64

 - DOSBox-X release version or commit SHA1 this issue occurred on
DOSBox-X 0.83.14
dosbox-x-vsbuild-win64-20210601022229-SDL2

**Additional context**
dosbox-x.conf changes:
output = ttf
working directory default = config
SET PATH=%PATH%;C:\BIN
MOUNT C C:\
C:

For Multiplan, I start it from a batch file, MP.BAT:
START  dosbox-x.exe  -c  MP.BAT  %1 %2 %3  -fastlaunch
(%1 %2 %3 are typically nul)

For Quicken, its batch file, Q.BAT:
C:
CD C:\QUICKEN
Q.EXE %1 %2 %3
CD\
(again %1... are typically nul)

**Comment by Wengier** [comment]
DOSBox-X by default maintains its own date and time, so the DOS date/time inside DOSBox-X may be different from the Windows host system. Can you check the actual date of DOS inside DOSBox-X? You can do so with DATE command. You can enable automatic date/time synchronization with the host system either via a config option ("synchronize time" in [dosbox] section) or from the drop-down menu ("DOS" => "Synchronize host date/time"). Hope this helps.

**Comment by therube** [comment]
Hmm.  06-23-2021.

> DOSBox-X by default maintains its own date and time

And what, it is set to current date at the time the instance was opened, & remains that way until manually changed (or sync'd)?

Thank you.

I'll set the 'synchronize time'.
