### ISSUE TITLE
can't get glide to work

### ISSUE THREAD

**Issue by WhiteMagicRaven** [joncampbell123/dosbox-x#2625]
can't get glide to work, i read a 3dfx emulation manual , tried several times and can't get glide2x.ovl on drive z =(

**Comment by rderooy** [comment]
glide2x.ovl should appear on the emulated Z:\ drive if you have glide enabled in your dosbox-x config file, **AND** if you have a working Glide wrapper installed on the host OS.

Please check out the wiki
https://dosbox-x.com/wiki/Guide%3ASetting-up-3dfx-Voodoo-in-DOSBox%E2%80%90X

**Comment by WhiteMagicRaven** [comment]
i readed exactly this article, and glide2x.ovl not appears i use dosbox x 32 bit and nglide

**Comment by Wengier** [comment]
> i readed exactly this article, and glide2x.ovl not appears i use dosbox x 32 bit and nglide

What DODBox-X version are you using? If you use version 0.83.14 (or later), then the glide2x.ovl file should appear in Z:\SYSTEM rather than the root directory of Z drive. Hope this helps.

**Comment by WhiteMagicRaven** [comment]
well its okay now

**Comment by Wengier** [comment]
OK, I will close this.
