### ISSUE TITLE
DOSBox-X 0.83.15 crashes on Mac due to missing dylibs

### ISSUE THREAD

**Issue by dixius99** [joncampbell123/dosbox-x#2628]
**Describe the bug**
When trying to launch DOSBox-X on macOS Big Sur (Intel), the app does not launch, and I get the macOS error report.

It appears that the current builds are missing the following dylibs:

- libslirp
- fluid-synth
- ffmpeg

Installing these manually with `brew install libslirp fluid-synth ffmpeg` (which installs several dependencies, especially for `ffmpeg`) fixes the issue.

**To Reproduce**
1. Double-click either the SDL or SDL-2 version of the app

**Expected behavior**
Expectation is that the app will load, with no need to manually install the libraries manually.

**Environment (please complete the following information):**
 - macOS 11.4
 - DOSBox-X release version 0.83.15

**Comment by joncampbell123** [comment]
That doesn't sound right... if you look in the .app bundle, there should be .dylib files alongside the DOSBoxX executable for FFMPEG, libslirp and FluidSynth.

Also, duplicate of [https://github.com/joncampbell123/dosbox-x/issues/2627] which indicates that libglib didn't make it.

**Comment by joncampbell123** [comment]
The Makefile used to force the .dylib files to refer to the executable by modifying them, but that breaks code signing, so it was removed. otool -L seemed to imply that it was supposed to search the same directory anyway, so I assumed it would work.

**Comment by dixius99** [comment]
> Also, duplicate of #2627 which indicates that libglib didn't make it.

Sorry, I didn't see that one. I can close this one and share info there.
