### ISSUE TITLE
"drive z expand path = true" not working if internal drive has been moved to other letter

### ISSUE THREAD

**Issue by piula** [joncampbell123/dosbox-x#2640]
**Describe the bug**
In version 0.83.15, the "drive z expand path" option has been added. With it being enabled, a simple "PATH=Z:\" is sufficient to reach all DOSBox-X internal tools regardless of their subdirectory (which has been introduced with 0.83.14).

The drive expansion works only if the internal drive keeps using the default letter Z:. When assigning a different letter, it fails, but imho it should work regardless of the particular drive letter.

**To Reproduce**
1. enable "drive z expand path" (should be active by default)
2. start DOSBox-X
3. PATH=Z:\
4. MOUNT -Z A:
5. PATH=A:\
6. MOUNT

**Expected behavior**
Step 4 succeeds because drive expansion works if internal DOSBox-X drive has driver letter Z:. Step 6, however, fails because drive expansion doesn't work if the drive letter of DOSBox-X' internal drive has been changed.

**Environment (please complete the following information):**
 - Windows 8.1 64bit
 - DOSBox-X 0.83.15

**Comment by Wengier** [comment]
I think this is an interesting question. As the name of the config option ("drive z expand path") suggests, it is for expanding %PATH% in Drive Z. If you move the Z drive to a different drive, then it is longer "Drive Z". The config option was added for compatibility purpose with existing [autoexec] options etc, and I think relatively few people actually move Drive Z to a different drive, and in such case you can always set the %PATH% environment variable properly, e.g. ``PATH=A:\;A:\SYSTEM;A:\BIN;A:\DOS;A:\4DOS;A:\DEBUG;A:\TEXTUTIL``.

But I will fix this case in any case. Thanks for pointing this out!

**Comment by Wengier** [comment]
@piula I have already fixed this so that it should work even if the Virtual Drive has been moved. Please check out the updated 64-bit Visual Studio SDL1 build:

* [dosbox-x-64-update.zip](http://cndos.fam.cx/dosware/dosbox-x-64-update.zip)

**Comment by piula** [comment]
Great! Works as expected, thanks for your quick fix 👍
