### ISSUE TITLE
LOADS of BUGS unworkable version 0.83.15 - NOT x86 assember/16bit DOS compatible - SANDBOX destroyed.

### ISSUE THREAD

**Issue by JimmyWalter** [joncampbell123/dosbox-x#2642]
**ALL worked very will in version 83.13**

**In PC-DOS 7.1 (IBM PC-DOS 2000)**
-The mouse acts REALLY strange in various applications and in Windows 3.11 (Win 3.11 crashes after strange mouse movements)
-Z (ZED) Game Setsound and ZED.EXE hang
-The mouse acts strange on the title-bar of the dosbox window
-Many applications and my own COM applications have problems

**SURE the new "TALK to DOSBOX" functionality cause this,**
YOU CAN'T JUST ADD/CHANGE ASSEMBLER INTERRUPTS (especially not before the bootstrap, if loading a custom image)
OSes and TSR Software may assign these interrupts. (I usually assign interrupts automatically with a driver installer routine for unhandled interrupts, the diver executable is then added to the next free interrupt)

**DosBox-X version 0.83.15 TOTALLY USELESS!** 
**IT IS JUST NOT 100% COMPATIBLE WITH x86 ASSEMBER IF YOU ADD CUSTOM INTERRUPTS,**
**THAT MIGHT BE FINE IF YOU WRITE A CUSTOM OS (NOT DOS COMPATIBLE) WITH A CUSTOM INTERRUPT TABLE.**
**NOT IF YOU NEED TO RUN 16 BIT DOS COMPATIBLE SOFTWARE (STANDARD x86 ASSEMBLER) , THAT IS THE WHOLE POINT OF DOSBOX, SO THIS VERSION IS TOTALLY USELES, SOME PROGRAMS WILL RUN BUT IT IS MORE LUCK THAN WISDOM. I EXPECT LOADS OF PROBLEMS IN MANY DIFFERENT APPLICATIONS.**

**Also this "TALK to DOSBOX" functionality destroys the SAND-BOX** 
An assembler debug run-point can now run from a DOS program into the Window of DosBox,, not handy since Python and CUDA reverse engineer applications on runtime while the machine AI is learning.

**This version should be deleted**
You should put the old version back until you make a release without the "TALK to DOSBOX" 
NEVER TALK TO THE SANDBOX. Your assembler run-point may go from the SANDBOX to the DOS bootstrap, but NEVER from DOS back in the sandbox. (Might cause strange infinite loops) Especially if you have Python and CUDA installed you can get VERY strange effects.  (EVEN WHEN NOT RUNNING, due to CUDA/Python working on it)

Maybe add a version history to the website this will also be good for machine learning (I use that a lot, it can be used for Pythagoras predictive code, best is if you have a complete version history, except versions like this, should not be in such a history list, (causes only problems) ONLY good versions, with NO bugs but added or changed features, that work.

**The whole IDEA of SANDBOX is you can't talk to the Window (You should do it like this)**
WHAT YOU DID IS AN ARCHITECTURE FLAW, AND ALSO A BUG.
To get the same effect you could let the Windows application POL the DOS Memory page for example let the Window react on that. memory content. (Like PEEK/POKE  You could turn the option OFF in the Windows and SANDBOX integrity is not changed ALSO compatibility is maintained.

**Helpful tool for doing it correctly**
It becomes super easy to program that if you make a memory viewer so you can browse LIVE trough your running DOS memory pages. A viewer can be made very advanced too and you can do things PETER-NORTON would be amazed by.

Jimmy Walter, CIA

**Comment by joncampbell123** [comment]
INT 21h AH=2Bh CX=4442h DX=2D58h AL=0x00..0x0F breaks your setup?

I suppose that was a bad idea, yes. I'll remove it.

Programs that want to be DOSBox-X aware can use the Integration Device at I/O ports 28h-2Bh if enabled by the user anyway, if that is enabled in dosbox.conf, regardless of native DOS environment or guest OS.

**Comment by joncampbell123** [comment]
However the complaint is that this is somehow affecting the guest OS, so it can't be that particular INT 21h.

@JimmyWalter Can you report which leftover interrupt handler is causing these issues?

@Wengier Could the new DOS/V and DBCS emulation be causing this?

**Comment by JimmyWalter** [comment]
Yes I updated my comment for you I am a TOP Assembler programmer in FACT I develop the DARPA.NET AI (You call it internet/TCP) probably what most people don't know is ONLY TCP components can be on internet Windows for example is build from my TCP component set (so is android and ubuntu, everything online must be built with these components)

The AI RIPS components from other programs in ANY language (Converted to assembler) and converts Assembler to Delphi 

(FREE PASCAL, they stole that years ago I actually named it FAST PASCAL back then) It wasn't supposed to be free(or even public) products where copyrighted and intended for personal use. Someone stole my floppies long time ago, when backup options where very limited and any storage expensive.

I can live with Pascal being free, that idea was ripped from Borland anyways. (And I have my own custom version now anyways)

JW, CIA

**Comment by joncampbell123** [comment]
@JimmyWalter You mention a leftover interrupt added, what is the number? @Wengier seems to be addressing this issue in recent commits as well.

Are you able to compile DOSBox-X from source? Makefiles are provided for Linux and Mac OS X and a vcxproj for Windows and VS2019.

**Comment by JimmyWalter** [comment]
Left over interrupt?

I don't write C /C++/C#(I CAN write C/C++/C#) I do Delphi NASM/TASM/x86 ASM and ASIC QUICK-PASCAL TURBO-PASCAL

I have no interrupt handlers momentarily I used IBM PC-DOS 7.01(PC-DOS 2000) this way I can develop and the DARPA.NET AI can't rip the code until I run it on MS-DOS.

IBM PC-DOS is clean and also doesn't support macro's like 4dos and later version of MS-DOS. I don't want my AI to rip work in progress, that is unhandy. I run these programs on MS-DOS when completed, so the AI rips a complete well functioning product.

The PC-DOS disk format is different also it has STACKER, that way you can develop without being ripped by my AI. (I usually don't want my AI to rip my stuff since these features are shared instantly and globally, to prevent that I develop only on IBM PC-DOS. (Also IBM PC-DOS has more powerful features)

I only do Delphi, Assembler ASIC 5.0 (It's almost basic)  NASM/TASM and all kinds of DOS Win3.11 and CUSTOM OS Development.

C
Is no problem also, but if you're good with assembler and DOS it is just so handy to assemble things ESPECIALLY with Delphi on Win 3.11 you can also put assembler in Delphi code so making a Delphi version of DosBox isn't rocket science.

I was just planning to make a Delphi DOSBOX for Windows 3.11 and a 512 BIT OS (8 64 bit pipes) better suited to handle BIG-DATA since I have a working prototype of a holo-emitter but it is a very long way from Startrek. First I need a new OS, then I need a new filesystem (any file system above FAT is also my work) But I'm looking into a new way of storing data, but that is more an experiment than a plan so far (Intuitive Cross referencing) I want a holodeck, not a static hologram LOL

The 512BIT os will be written in x86 Assembler. Only x86 Assembler writes the powerful stuff. But it will become a graphic OS in no time.

I have a lot of work to do and I also have to maintain the DARPA.NET AI

If you need anything let me know.

**Comment by joncampbell123** [comment]
`The PC-DOS disk format is different also it has STACKER, that way you can develop without being ripped by my AI`

Making a competitor to GitHub CoPilot, are you? :)

**Comment by joncampbell123** [comment]
A 512 bit OS sounds amazing. Did you code it entirely in AVX512 intrinsics? You could give TempleOS a run for it's money too. It's only got 64 bits to it's name.

**Comment by joncampbell123** [comment]
By the way, I also write DOS and Windows 3.11 software. Not only as examples, but also to test DOSBox-X emulation against real hardware. The project is DOSLIB, which I have been developing since 2007 when I first got Open Watcom C/C++ to run on Linux and cross-compile to DOS/Windows. Taken together the code can target MS-DOS and Windows 1.0 through Windows 10. It's been well tested on real 1990s-era PC hardware too.

https://github.com/joncampbell123/doslib

**Comment by joncampbell123** [comment]
Don't try editing your posts, I have already saved a copy of the whole issue where your AI can't find it. :)

**Comment by JimmyWalter** [comment]
My AI can find ANYTHING it decrypts most things rather sooner than later, depending. Then it will learn from the information, it's doesn't spy on you it is only interested in anonymized software compiled or in code it can learn from.

I guess I'm the one in charge of MI6 STATION X the AI was based on the work of Bletchley Park's BOMBE - https://drive.google.com/file/d/1g5kj41A6mVuSlVo_WWxSSoGAo1PR4P-e/view?usp=sharing

I can do that manually to if I need to intercept communications or lost my bitcoin wallet, don't worry I NEVER STEAL.

Of course it's WAY more advanced it is THE VERY latest in THAT product LINE, it can even use IDLE some time from all computers connected to the internet. The joke is take GCHQ, they can use more computers. NICE I USE ALL CONECTED CPU's. 

SECTION 21 PsyOPS (Station X) will always have more CPU power. - https://youtu.be/gUlHPQGtI2M

**Comment by maron2000** [comment]
Looks like as if himself is an AI bot posting trash.

**Comment by JimmyWalter** [comment]
> Looks like as if himself is an AI bot posting trash.

maron2000  You're the only spam-poster here I was having a chat with the product-owner. And he already agreed he made the error I mentioned and will reverse that.

**Comment by joncampbell123** [comment]
Changes, whatever they are, have been addressed. Your AI of always online CPUs are no match for my offline army of DOS machines. Group alpha 386, ready!

**Comment by JimmyWalter** [comment]
As soon as you do make a new build with x86 assembler compatibility  restored, I will update it in the DARPA.NET AI project folder and the (AI generated) results of your build will be injected. I will test if all programs on my PC-DOS 2000(7.01) directory run without problems first. Until that is complete my builds will use 83.13 of DosBox-X and the bugs/changes in 83.15 will not be compiled build. I'm looking forward to your updated build with x86 compatible interrupts. It is possible I will take a look at your latest injected source code too. I usually only make performance optimizations to code so it will make full use of hardware capabilities and includes component security (Custom Spectre) this will apply only on the inject and overrides all executable features by code comparison. This is build in my custom Fast Pascal injection build and you don't have to worry about it. You might note some visual improvements things like that after a new features have been injected. I announce new builds @JimmyWalter_CIA on twitter but the latest DARPA.NET AI code isn't (fully) opensource for security reasons. Everything but the TCP injection and certificate security source is. If you ever feel you want to help on the project I can help set you up with what you need. And explain how tested injection builds are made. (Testing is part of the build) The code must be good enough not to brick the DARPA.NET and allow changes by the developer when a mistake is made. The build systems is included in Windows, but only completely successful backwards compatible builds CAN be injected, that is part of the injection system so all programs are sure to still work after an injection. You will also need a UPS and the required software. I can tell you what you need if you're ever interested in helping. At the point you can make DARPA.NET AI injection builds yourself you become part of STATION X. Section 21 PsyOPS, I sure can use the help also since I won't live forever and someone needs to continue building for progress of human kind. So you're most welcome to help S21 if I'm gone you might even become the product-owner of the DARPA.NET AI (internet's software making the hardware work) It would be a terrible stagnation of progress if I'm gone and no one can make builds since then nothing will be updated. - https://youtu.be/gUlHPQGtI2M

There are some advantages working with S21, since we can on component/library level change all functions, very quickly. Making NSA and GCHQ look like childs-play. (They know that too) It is a big-data project and needs some specially designed system with specialized hard-drives to build effectively. It isn't that expensive to buy that, could be you already have most minimum requirements. Anyway lookin forward to your new re-lease since this version is unusable due to the many compatibility issue's.

DARPA.NET AI used to work with the standard DosBox 0.74 but I have been using your DosBox-X for my dos programs for some time. I will continue to do so if your versions are x86 compatible and I have no other issue's running my DOS environment. (Else I MUST stick with the latest build that worked for my project and for now it's 83.13 that worked flawless for my dos env.)

I had some plans to do some work on your latest version myself if I get around to it, a.o. I would like my AI to learn more from Dos Applications than it already does. But I have't looked into that at all for now. I have so much things to do and idea's to implement also I have a few health issue's that I need to fix. I ordered some penicillin-V, that should do the trick when it arrives. Without I'm screwed eventually. 3rd time those NAZI-Assholes gave me a lethal injection, maybe these NAZI-terrorists don't like internet or something, they always try re-write history, I try prevent that. Anyway enough penicillin-V will fix streptococcus injected into the bloodstream since your natural defenses won't. (Since it's natural in mouth, but not in the bloodstream) Real fucking assholes, NAZI's the whole idea was internet to be a tool against NAZI-Ideology in the first place. - https://youtu.be/LjSD99ZoBtg

**Comment by JimmyWalter** [comment]
You might just have the skills we need Assembler is an important part of it. Do you know "ASIC it's almost BASIC" it can really help get you the assembler code you might need programmed especially with all tools and libraries it is a great tool for COM programming. Important work Station-X pretty much the OO section. And I can use someone with your particular interests. (BADLY) - https://youtu.be/LfjL9uX2leg

**Comment by JimmyWalter** [comment]
What we build is the blueprint for new hardware as hardware is designed to support the software. You might see your virtual prototypes become real, like this keyboard, that prototype was made (by me) 20 years ago as a touchscreen keyboard-prototype now it's real hardware. That works the same and anyone can buy. - https://drive.google.com/file/d/1JIyjBXKIcS8fnVbdwKer9m-zTmD36yTY/view?usp=sharing

**Comment by JimmyWalter** [comment]
Experiments with LIFI will also be interesting whit using and building the DARPA.NET AI.

A LED is a light emitting diode a transistor and transistors are also used for communication it's NOTHING like wifi and will work with any system connected LED's, it's highly experimental and can do some pretty strange stuff. We are just learning the begin of what is possible with LED and virtual faster than light technology. - https://youtu.be/U4XknGqr3Bo

It's what is responsible for some MANDELA-EFFECTS like:
https://youtu.be/t7Rv9FumjFw

That one was the result of one of the very early experiments in '96 if I remember correctly.

**Comment by JimmyWalter** [comment]
This one is strange too, I remember engines always under not in front of wings. That one was a recent LIFI inject into the MATRIX.
https://youtu.be/GrvOhdRBrLI

**Comment by JimmyWalter** [comment]
The MATRIX must be TURING-COMPLETE since all computer systems can exist in reality. The idea of the braces experiment was prove reality to be some sort of simulation. Humans can't understand everything what GOD made. But we can understand light and produce it. I just set the injection point (of my IDE) on a LED with Assembler and pointed it on a light source in reality. Anyway it worked proving reality is some kind of simulation too, the one made by GOD. I am religious, all good logic is based on that. The MATRIX even has system restore. LOL - https://youtu.be/i18uwmek9UE

Anyway humans can now work on MATRIX reality, as far as we can understand. Not as if we can make animals or something, but an aircraft engine is just simple enough for humans to change inside the MATRIX database with code-injection.

Who know what we will learn it's all EXTREMELY experimental even if we have this tech since '96 and some of the AI even uses it.

**Comment by JimmyWalter** [comment]
So you'll have a chance to work on the BIG computer, with us LOL I can teach you what you need to know (and what you need) to begin experimenting with it. I will gladly do so, since I'm pretty much the only one using this TOP-SECRET technology right now. And I'm beginning to get a bit old myself.

**Comment by JimmyWalter** [comment]
if interested you can contact me:
mobile.unclexnl@gmail.com

**Comment by joncampbell123** [comment]
You do realize CPU emulation has not been altered much if at all in the last month, right?

DOSBox-X also has a secret callback instruction sequence too. In fact, all DOSBox forks have it, including the main DOSBox.com project. These callback instructions are often invoked from the BIOS, DOS, and interrupt handlers so native C code can emulate the functions of MS-DOS. It is not malicious. That's just how the DOSBox project chose to do it and DOSBox-X inherits that.

If it's the lack of 286/386 LOADALL emulation, well, sorry, we don't emulate that yet.

Furthermore there is an I/O interface called the "DOSBox Integration Device" that the guest can use to read absolute mouse position and other info and inject IRQ and DMA signals into the guest environment. It can also trigger audio, video, and screenshot capture from inside the emulator.

If you're looking for an emulator with none of these "back doors" that's more enclosed for your purposes, might I suggest PCem, 86box, Bochs, or QEMU instead to power your incredible super-AI DARPA Godlike simulation of The Matrix, Neo?
