### ISSUE TITLE
DOSBox-X 0.83.14 config setting FILES doesn't work; always set to 200

### ISSUE THREAD

**Issue by pcdosretro** [joncampbell123/dosbox-x#2645]
**Describe the bug**
DOSBox-x.conf setting files=nn is ignored; files is always set to 200 and there are always two SFT blocks of 100 SFTs each.

**To Reproduce**
Specify files=nn (e.g. files=40) in dosbox-x.conf
Run my DOSINFO utility from here: https://sites.google.com/site/pcdosretro/sysvars

**Expected behavior**
You should be able to set files from 8 to 255.

**Environment (please complete the following information):**
Tested with DOSBox-X 0.83.14 on Windows 7 SP1 64-bit

**Additional context**
While settings FILES doesn't work, settings FCBS and LASTDRIVE do work as expected.

**Screenshots**
![command_000](https://user-images.githubusercontent.com/87035295/124646389-91d8d500-de62-11eb-9e9c-0855308dc4df.png)
![command_001](https://user-images.githubusercontent.com/87035295/124646407-98674c80-de62-11eb-9f20-449e54a61631.png)

**Comment by Wengier** [comment]
I can reproduce the issue with the said tool. It means that the system table for files is still fixed, but the FILES setting still has effect elsewhere. The system table needs to properly updated for FILES as well.

**Comment by emendelson** [comment]
@pcdosretro - this is off-topic, but I wanted to say that your site is extremely fascinating. I wish I had known about BOOTLDR during the many years when I could have used it...!

**Comment by pcdosretro** [comment]
The default for FILES should be much lower, say 30 or 40. I've never seen a DOS program open anywhere near 200 files at once. Lowering FILES would also free up additional conventional memory.

@Wengier - DOSBox-X is definitely more internally compatible than DOSBox. DOSINFO crashes in DOSBox because the SYSVARS table isn't filled in properly (e.g. no DPB pointer).

@emendelson - Thanks.

**Comment by pcdosretro** [comment]
If you want to mimic actual DOS then the first SFT block at CCh should have 5 SFTs (size = 12Dh in DOS 4+, size = 10Fh in DOS 3.1-3.31), followed by another block with the remaining SFTs (e.g. 35 more if FILES=40).

Note: Windows 3.x will open CON 5 times and search conventional memory for 5 successions of "CON" and use the distance between two CON strings (the filename in the SFTs) to determine the size of an SFT which is different depending on the DOS version (e.g. 3Bh in DOS 4+, 35h in DOS 3.1-3.31, 38h in DOS 3.0)

**Comment by Wengier** [comment]
@pcdosretro Yes, the goal is to mimic the actual DOS behavior. I think you are very familiar with the DOS calls. Are you able to fix them in the code? Thanks!

**Comment by pcdosretro** [comment]
I looked at the code and I see in dos_classes.cpp where it creates the 200 fake SFTs (even though the comments say 100) but since I'm not familiar with the code I have no idea why that was done. Why is the next set of SFTs offset by 0x26 paragraphs ?

I guess it should be something like:
	real_writed(segment,sftOffset+0x00,RealMake(NEXTSEG,0));	//Next File Table
	real_writew(segment,sftOffset+0x04,5);		//5 SFTs in DOS data segment
	real_writed(NEXTSEG,0x00,0xffffffff);		//Last File Table
	real_writew(NEXTSEG,0x04,files-5);

NEXTSEG would be the segment for the second block of SFTs. files would be the FILES= parameter (from 8 to 255).

The code in dos_tables.cpp in function DOS_SetupTables should also be changed to place the CON strings at the correct intervals (size of SFT), presumably in the dummy SFTs created in dos_classes.cpp.

 I also noticed there's a 19.6KB MSDOS memory block allocated which is mostly zeroes which seems strange as well.

**Comment by Wengier** [comment]
For the purpose of fixing the original problem I think the code can be changed to:
```
real_writew(segment,sftOffset+0x04,DOS_FILES/2);	//File Table supports DOS_FILES/2 files
real_writed(segment+0x26,0x00,0xffffffff);		//Last File Table
real_writew(segment+0x26,0x04,DOS_FILES-DOS_FILES/2);	//File Table supports DOS_FILES/2 files
```

The code can be additionally improved for other fixes of course. Thanks.

**Comment by pcdosretro** [comment]
I can verify this is fixed but it is still curious where the segment+0x26 comes from. Also, to better mimic DOS, the first block should have only 5 SFTs and the second block should have DOS_FILES-5 SFTs.

**Comment by joncampbell123** [comment]
@pcdosretro It's possible that code was inherited from DOSBox SVN when DOSBox-X forked from the main project, and has not been changed since. There was also code in SVN that was changed in DOSBox-X that used to hardcode the PSP segment of COMMAND.COM as a fixed offset from the DOS kernel.
