### ISSUE TITLE
Cyrus chess and 3D visualization not working with cga and cga_mono

### ISSUE THREAD

**Issue by pinop76** [joncampbell123/dosbox-x#2659]
Why with option cga or cga-mono cyrus.com not permit the 3d chess playing?

**Comment by Wengier** [comment]
Does it work with the standard video options then?

**Comment by pinop76** [comment]
> Does it work with the standard video options then?

Excuse me for bother. The problem was in dowloanded cyrus. Two another cyrus.zip have the files for 3d CGA.
It's OK. Excuse me.
