### ISSUE TITLE
Appveyor for automatic nightly builds

### ISSUE THREAD

**Issue by masaykh** [joncampbell123/dosbox-x#266]
https://ci.appveyor.com/signup/free

it can be set to use linux \ windows (native windows using msvc) enviroments to autobuild nightlies

what do you think about it?

**Comment by joncampbell123** [comment]
Nightly builds are fine with me. Understand that I don't work on the Windows parts of the code, and my development progress might break the Win32 side of things consistently.

**Comment by joncampbell123** [comment]
Hey, it actually built it. That's a good sign the .sln file is still valid.

**Comment by masaykh** [comment]
oh, can i have built version? 
i use MSVC 2015 community edition - and it cant build it showing something like 4000+ errors

**Comment by joncampbell123** [comment]
I'll find a way to do it. Appveyor is able to build, but getting the build placed somewhere is turning out to be a pain. Apparently it's unable to create releases on Github, so I'm trying to get it to post the build to Amazon S3 instead.

**Comment by joncampbell123** [comment]
Aarrrrgh what's the point of running builds if I can't get it to post the build nor download the build?

**Comment by masaykh** [comment]
as i understand it is done through config file , like this http://stackoverflow.com/questions/34273570/how-to-publish-beta-nuget-packages-out-of-appveyor

**Comment by joncampbell123** [comment]
Alright. So having wasted 2 hours on this, I'm not sure this will work out for me.

If you want to use it for builds, that's perfectly fine. I've created a master-win-ci branch that is to be the code in a "known good" state to compile for MSVC/Windows, while Linux development continues.

**Comment by masaykh** [comment]
https://www.appveyor.com/docs/deployment/github/
deployment to github releases

**Comment by joncampbell123** [comment]
Creating "appveyor-ci-1.0.113-does-this-really-work" release for repository "joncampbell123/dosbox-x" tag "appveyor-ci-1.0.113-does-this-really-work" commit "75943f6547d5b5f4237417406a1acaa8cc51c658"...Error creating GitHub release: Not Found

Even though appveyor was successful at creating the release, it won't deploy. The tag does exist. "Not Found" tells me nothing about what's going on and I don't care to pursue it further. The Amazon S3 push tells me it succeeded, but browsing the bucket shows nothing ever made it. There's nothing to tell me what's going on or to diagnose what's going on (typical modern software design). This is the best I can manage in 2 and a half hours of fiddling and rerunning the build and something that I also have no patience for. If you want to use Appveyor for integration builds that's perfectly fine with me.
