### ISSUE TITLE
A game no voice

### ISSUE THREAD

**Issue by 280696516** [joncampbell123/dosbox-x#2665]
dosbox-x 0.83.14

my dosbox.conf is 
[cpu]
cycles=20000
[autoexec]
mount c .\Sd
c:
run.bat

![title_021](https://user-images.githubusercontent.com/54297406/125176374-7aed0680-e205-11eb-8e5b-951895e675be.png)

[Sd.zip](https://github.com/joncampbell123/dosbox-x/files/6795942/Sd.zip)

in the spot of screenshot,only have music,no voice.        dosbox r4252 have both music and voice.

**Comment by Wengier** [comment]
I can confirm this issue with at least the default setting. But I wonder if there is any sound setup tool for the program, for setting sound IRQ etc? The default sound IRQ handling may be somewhat different between DOSBox and DOSBox-X.

**Comment by cimarronm** [comment]
It's using the Disney/Covox device for the voice so be sure to add that to the conf and that lpt1 is disabled.
```
[speaker]
disney = true
[parallel]
parallel1 = disabled
```
and it should work

**Comment by Wengier** [comment]
@cimarronm Yes, you are right. I can hear voice with the setting you posted too.
