### ISSUE TITLE
How to copy to clipboard under macOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2667]
I've been trying to figure out how to select and copy text to the clipboard, using only the keyboard, under macOS, but I still can't figure it out.

On the main menu, under Shared clipboard functions, I've checked "Via arrow keys (Home=start, End=end).

In a DOSBox-X screen with text, I can move the cursor with shift-arrow keys, but that's where I get lost. When the cursor is in position, I press Fn-left-arrow, which seems to be the Home key, but nothing happens.

What obvious fact am I missing? I'll be grateful for any explanation.

**Comment by Wengier** [comment]
@emendelson I run macOS in VMs, and I think it is the same for both Windows and macOS, using the Home key to start text selection. You can try enable the "Quick Edit" mode, then there is no need for holding the Shift key for these keys. I am apparently using the standard Windows keyboard though, not entirely sure if there is any difference for the macOS keyboard (which I don't have to test myself).

**Comment by josephillips85** [comment]
HI @emendelson 
for perform copy and paste from your keyboard on mac

1.Hold Function + Shift + Left Arrow
2.Hold Shift and use the arrow to highlight the text to select
3.Function + Shift + Right Arrow

**Comment by emendelson** [comment]
@josephillips85 - Thank you! That works! But It needs one more step to find the right place on screen to start highlighting. So here is what I think gets the job done:

1. Hold down the shift key, and use the arrow keys to move to the place where you want to start highlighting.
2. Press Function + Shift + Left Arrow (equivalent on Home on a Windows/Linux keyboard).
3. Hold Shift and use the arrow keys to highlight the text to select.
4. Press Function + Shift + Right Arrow (equivalent of End) to copy the highlighted text to the clipboard.

Thank you again for this!

@Wengier - A Mac laptop does not have Home and End keys, although those keys are on a full-size Mac keyboard. The steps spelled out by josephphillips85 are the ones needed on a Mac laptop. I'm very glad to have this. And I wonder whether it might be possible to have the menu on a Mac system specify something like

`Via Shift-arrow keys (Home [Fn-Shift-Left]=start, End [Fn-Shift-Right] = End)`

That's a lot to fit on a menu, but the existing one doesn't tell the user what to do.

**Comment by josephillips85** [comment]
@emendelson  great to hear is working
in the case to add the description on the menu it's not necessary  you dont have home ,end ,page up, and page down on MBP or any short keyboard because by design they want to keep the keyboard short. and mapped with the funcions keys

any apple extended keyboard have home and end key 

so can be confusing for users with extended keyboard

**Comment by Wengier** [comment]
Glad to see you got it working! In order to make it clear that Fn-Shift-Lef and Fn-Shift-Right can be used in place of Home and End keys on macOS laptops, I have already added them in the dosbox-x config reference files and the draft DOSBox-X Wiki. Thanks a lot for rising the issue!
