### ISSUE TITLE
ide.cpp without mman.h cant compile

### ISSUE THREAD

**Issue by masaykh** [joncampbell123/dosbox-x#267]
https://gist.github.com/masaykh/99a67da43b2b296ec45105daf9f8de22

but if i add mman.h from msys - it compile but not link at the end, so can you at least check that section of code?

**Comment by joncampbell123** [comment]
Now that I think of it, "interface" is taken in the Windows environment in order to define COM/OLE interfaces.

I'll have to change the variable name.

**Comment by joncampbell123** [comment]
the latest commit renames that parameter to ide_interface

**Comment by masaykh** [comment]
yes it fixed problem, same problem with floppy.cpp

**Comment by joncampbell123** [comment]
latest commit fixes floppy.cpp as well.
