### ISSUE TITLE
Undefined References MinGW

### ISSUE THREAD

**Issue by masaykh** [joncampbell123/dosbox-x#268]
So i managed to solve problems like that i reported here.
i added _MSC_VER=1400 define so behave more in windows way
d3d9.h removed on ./configure step as it dont like to build with it
#include <endian.h> changed to #include "portable_endian.h"
https://gist.github.com/panzi/6856583

but in result i got :

g++  -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -mmmx -msse -msse2 -Wno-strict-aliasing -std=gnu++0x    -o dosbox-x.exe dosbox.o winres.o debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a -L/mingw32/lib -lmingw32 -lSDLmain -lSDL -mwindows -lpng -lz -lfluidsynth -lopengl32 -lwinmm
dos/libdos.a(dos_files.o): In function `Z17Network_CloseFilet':
D:\newmsys\dosbox-x-master\src\dos/dos_network2.h:115: undefined reference to `_nhandle'
gui/libgui.a(sdlmain.o): In function `Z22DoExtendedKeyboardHookb':
D:\newmsys\dosbox-x-master\src\gui/sdlmain.cpp:1459: undefined reference to `SDL_DOSBox_X_Hack_Set_Toggle_Key_WM_USER_Hack'
D:\newmsys\dosbox-x-master\src\gui/sdlmain.cpp:1495: undefined reference to `SDL_DOSBox_X_Hack_Set_Toggle_Key_WM_USER_Hack'
gui/libgui.a(sdlmain.o): In function `SDL_main':
D:\newmsys\dosbox-x-master\src\gui/sdlmain.cpp:4482: undefined reference to `ImmDisableIME@4'
gui/libgui.a(midi.o): In function `ZN17MidiHandler_synth9PlaySysexEPhj':
D:\newmsys\dosbox-x-master\src\gui/midi_synth.h:287: undefined reference to `fluid_midi_parser_parse'
gui/libgui.a(midi.o): In function `ZN17MidiHandler_synth7PlayMsgEPh':
D:\newmsys\dosbox-x-master\src\gui/midi_synth.h:274: undefined reference to `fluid_midi_parser_parse'
gui/libgui.a(midi.o): In function `ZN17MidiHandler_synth4OpenEPKc':
D:\newmsys\dosbox-x-master\src\gui/midi_synth.h:174: undefined reference to `fluid_log_config'
D:\newmsys\dosbox-x-master\src\gui/midi_synth.h:231: undefined reference to `new_fluid_midi_parser'

At least first three is C externs..and i dont understand what they supposed to do.

**Comment by joncampbell123** [comment]
The SDL library included with DOSBox-X for Visual Studio was hacked slightly to allow a low-level keyboard hook in order to manipulate the keyboard LEDs, that's why the DOSBox_X hack functions.

**Comment by masaykh** [comment]
ok but what about _nhandle and fluidsynth? 

i have fluidsynth and it is working

**Comment by masaykh** [comment]
so after i checked fluidsynth library - this import "fluid_midi_parser_parse" only present in static version

**Comment by joncampbell123** [comment]
_hnandle is part of the keyboard hack.

Feel free to #ifdef it out if Win32 but not MSVC.

**Comment by masaykh** [comment]
extern "C" int _nhandle;
 bool	Network_CloseFile(Bit16u entry)
{
		Bit32u handle=RealHandle(entry);
		int _Expr_val=!!((handle >= 0 && (unsigned)handle < (unsigned)_nhandle));
		//_ASSERT_EXPR( ( _Expr_val ), _CRT_WIDE(#(handle >= 0 && (unsigned)handle < (unsigned)_nhandle)) );
		if (!(handle > 0) || ( !( _Expr_val ))) {
			_doserrno = 0L;
			errno = EBADF;
			dos.errorcode=(Bit16u)_doserrno;
			return false;
		}

		if(close(handle)==0)
		{
			NetworkHandleList[entry]=0;

			DOS_PSP		psp(dos.psp());
			psp.SetFileHandle(entry,0xff);

			return	true;
		}
		else
		{
			dos.errorcode=(Bit16u)_doserrno;
			return	false;
		}
}

what can i change so it will work?
i cant just #ifdef it as it tell me that

**Comment by joncampbell123** [comment]
Ah. So _nhandle isn't part of my keyboard hack in Windows. I was mistaken.

I'm not sure what that code is, I've never tested or played with it.

**Comment by masaykh** [comment]
Ok so usefull (maybe) info - fluidsynth in mingw broken.
