### ISSUE TITLE
Freezing in windows 3.2 setup checks hard disk

### ISSUE THREAD

**Issue by leoxxx** [joncampbell123/dosbox-x#2686]
DOSBox-X 0.83.15 mingw-sdl2 win64
![setup_000](https://user-images.githubusercontent.com/5364709/126040455-013c4d30-789c-4066-93ba-e1ef847e52e2.png)
I want to install windows 3.2 in DOSBox-X. https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-3.x With conf from this wiki. If virutal hard disk no windows3.x, it will freeze in setup checks hard disk. https://github.com/joncampbell123/dosbox-x/issues/917#issuecomment-538632626 With DOSBox's conf is the same result. But DOSBox is O.K.

**Comment by rderooy** [comment]
@leoxxx thanks for your report.

I'm not quite sure from your report. Are you:
- installing into a shared folder from the integrated DOS in DOSBox-X
- installing into a harddisk image from the integrated DOS in DOSBox-X
- Or are you booting DOS from a harddisk image?

To be honest, I have never tried Windows 3.2 before, as it is a Chinese version of Windows 3.1. I just thought it would be the same as Windows 3.1

**Comment by leoxxx** [comment]
mount c g:\win3.2

installing into a shared folder from the integrated DOS in DOSBox-X

Installing into g:\win3.2

**Comment by Wengier** [comment]
@leoxxx I tried Windows 3.2 Setup myself and I think it may be related to the code page. Can you try set ``country=86,936`` 
(and ensure ``output=ttf`` it set) in the config file and then run Setup again and see if it works? You can confirm it with the CHCP command. A screenshot showing the Setup screeen:

![image](https://user-images.githubusercontent.com/8216923/126077114-b7bdd372-28e5-424a-9280-497a17938bae.png)

**Comment by leoxxx** [comment]
@Wengier
THX. Just set country=86,936, then it's not freezing.
BTW, how to change the toobar into Chinese?

**Comment by Wengier** [comment]
@leoxxx There are Chinese (both Simplified and Traditional) language files for DOSBox-X in the repository, downloadable from:

https://github.com/joncampbell123/dosbox-x/tree/master/contrib/translations/zh

You can load them via "language" config option, e.g. `language = zh_CN.lng` in [dosbox] section, and also load a TTF font that supports Chinese characters via "font" config option, e.g. `font=simkai` in [ttf] section ("simkai.ttf" is included in Windows, but you can use other TTF fonts too). I am using the [SarasaGothicFixed.TTF](https://github.com/joncampbell123/dosbox-x/raw/master/contrib/fonts/SarasaGothicFixed.ttf) font, which I think look better and use it for the screenshot:

![image](https://user-images.githubusercontent.com/8216923/126108108-9cafb9d6-737f-421b-a143-b95888a44f03.png)

**Comment by leoxxx** [comment]
I see. I found your thread in PPX
