### ISSUE TITLE
Bug with Piping

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2687]
i was just randomly testing piping in dosbox-x , when i typed `echo|command` , it typed echo is On to command prompt , then didn't stop spamming E:\> prompt , why?
![image](https://user-images.githubusercontent.com/71384075/126052991-d263ddf0-2f33-436b-97ac-033643af8e81.png)

**Comment by crashGG** [comment]
Yes it is. The same command has different results under dosbox svn. It's interesting :)
<img width="322" alt="echo1" src="https://user-images.githubusercontent.com/80488411/126072307-e81f92c4-7b7f-4b07-9003-6e8d5536028d.png">
<img width="322" alt="echo2" src="https://user-images.githubusercontent.com/80488411/126072312-bd323907-98b1-44bd-bb08-ddabe890022a.png">

**Comment by Wengier** [comment]
DOSBox SVN (or other builds) does not support piping at all. It will ignore EVERYTHING after the pipeline (|), so it is not truly comparable.

DOSBox-X on the other hand supports piping just like in real DOS system. I have tried this in a real DOS machine too, and the command ``ECHO|COMMAND`` will cause real DOS systems to completely hang. So the behavior of this command in DOSBox-X is more or less correct based on the actual DOS system behavior.

**Comment by Siddhant-Mashalkar** [comment]
ok, there's a bug with Dosbox-X , when i try `any command|command` on real DOS System, it would run it normally using COMMAND.COM and keyboard will not work anymore, but dosbox-x spams current directory prompt after that , why?

**Comment by Wengier** [comment]
@Siddhant-Mashalkar In real DOS systems, it is not just the keyboard will not work anymore, but the entire DOS system has locked up. I agree there is a bug, but it is a minor one, in the sense that the behavior is not exactly the same as DOS to just lock up the system.
