### ISSUE TITLE
MS-DOS 3.31 Freezes and Dosbox-X crashes on "Microsoft RAM Drive Version 1.22"

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2692]
i made a Windows 1.04 Floppy Disk, i copied XMGR.SYS (xms manager i downloaded from some website) and Ramdrive.sys (Ram Driver from Windows 1.04 Setup Disk) , and loaded it in config.sys , it froze at "Microsoft Ram Drive Version 1.22" and Dosbox-X crashed.

**Comment by Wengier** [comment]
@Siddhant-Mashalkar Can you attach the image file so that we can take a look at? Thanks.

**Comment by Siddhant-Mashalkar** [comment]
this is the floppy image
[Windows1_Floppy_RamDrive.zip](https://github.com/joncampbell123/dosbox-x/files/6847363/Windows1_Floppy_RamDrive.zip)

**Comment by Wengier** [comment]
@Siddhant-Mashalkar Thanks for uploading the image. I can confirm the freeze with loading RAMDRIVE.SYS. However, it can be solved by using XMSDSK instead, and then it will boot to Windows.

![image](https://user-images.githubusercontent.com/8216923/126309816-c33b3edb-6a21-4eaa-9ebe-212d7506b66e.png)

**Comment by Siddhant-Mashalkar** [comment]
ok, i made Windows 3.0 Live Floppy that used Ramdrive.sys version 3.06 , but it worked fine
but why does ramdrive.sys version 1.22 appear to freeze?

**Comment by Wengier** [comment]
@Siddhant-Mashalkar XMGR.SYS is a rather new DOS XMS driver. I wonder if it is supported by such an old version of RAMDRIVE.SYS at all.

**Comment by Siddhant-Mashalkar** [comment]
ok
