### ISSUE TITLE
Problems installing freedos 1.2 Lite

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2697]
when freedos setup tries to partition drive , i get this same error
i booted from FreeDos 1.2 Lite IMG File
![image](https://user-images.githubusercontent.com/71384075/126530229-240b9b77-9f14-49ac-86a2-0d4fc1a4fa4f.png)

**Comment by Wengier** [comment]
I think this issue is the same as issue #2528. Try set ``core=normal`` in the configuration.

**Comment by Siddhant-Mashalkar** [comment]
ok, it works
