### ISSUE TITLE
Config tool UI is broken when using 3840*2160 @ 150% DPI

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#2698]
**Describe the bug**

It does not take into account DPI scale.

**Screenshots**

![2021-07-21_20-57-46](https://user-images.githubusercontent.com/1537591/126544542-e6b2315d-20a0-4ae9-a4b4-52ce2cf010da.gif)

![explorer_2021-07-21_20-58-49](https://user-images.githubusercontent.com/1537591/126544564-b41d5b34-dace-4e6f-a5ed-363add387934.png)

**Comment by Wengier** [comment]
I don't have a 3840*2160 screen myself, but with 150% DPI setting I have not been able to reproduce this issue on my (smaller) screen so far. And I am not quite sure if this is a DPI awareness issue or Config Tool scaling issue. Can you change the setting of the option "dpi aware" (to true or false) and see if anything changes? On the other hand, if this is a Config Tool scaling issue, then I think @ant-222 may want to take a look at it.

**Comment by 1abcd** [comment]
My computer 1920*1080, win7x64, 150% DPI
I also have the same ui display problem.
@Wengier 
滑鼠點擊的座標通通是正確的。
在畫面顯示，選單列(menu bar)的反白標示是正確的，只有選單表內的反白項目標示錯誤，意思是滑鼠點擊的東西和反白的東西不一樣。

**Comment by Wengier** [comment]
@1abcd Is it because of the forced scaler mentioned above? Try disable any scalers and see if it works as expected.

**Comment by 1abcd** [comment]
@Wengier
沒有使用強制縮放。
組態工具在小視窗畫面，反白項目跟滑鼠箭頭是對齊的。
一旦視窗放大後，反白項目和滑鼠箭頭產生偏移(僅在選單表內)，但滑鼠點擊的東西沒有偏移。

**Comment by Wengier** [comment]
@1abcd Perhaps there is a different cause of the issue. I wish I could reproduce the problem on my own computer.

**Comment by 1abcd** [comment]
@Wengier 以我的使用經驗這 DOSBOX-X 非特例，是系統 DPI 縮放150%造成滑鼠移動時的座標跟著縮放，只是看能不能在應用程式內修正。

**Comment by Wengier** [comment]
@1abcd What if you change the setting of the option "dpi aware" (to true or false) and see if anything changes?

**Comment by 1abcd** [comment]
@Wengier
when dpi aware is true or auto, 問題存在
when dpi aware is false, 問題消失，但視窗畫面打糊，不清晰

**Comment by aybe** [comment]
fixed 7240fe839cfb8def4b91ab72a3a4b86258e2a097

**Comment by Wengier** [comment]
@aybe Thanks for the fix. Perhaps you can mention it in the CHANGELOG too.
