### ISSUE TITLE
.LNG sentence starting with dot are ignored

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#2701]
**Describe the bug**

Since some sentences are simply too long, they have to be rethought completely to be meaningful.

But like the following, nothing is shown:

**Screenshots**

![Code_2021-07-21_21-29-29](https://user-images.githubusercontent.com/1537591/126548406-d998eea5-7d89-41bf-a3b7-6ec61122485a.png)

**Comment by aybe** [comment]
Somehow it's possible to use something else:

![dosbox-x_2021-07-21_21-32-32](https://user-images.githubusercontent.com/1537591/126548751-631158fe-a0b1-45e0-93d8-8554d34a67a8.png)

But still, it's expected that a **single dot** signals the end of the text.

**Comment by Wengier** [comment]
Thanks for reporting this! It is hopefully fixed in the latest code already.

**Comment by aybe** [comment]
Nice. Le 22 juil. 2021 09:26, Wengier ***@***.***> a écrit :
Thanks for reporting this! It is hopefully fixed in the latest code already.
