### ISSUE TITLE
CP/M compat work

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#273]
1. Add code that, if HMA is enabled, writes a copy of the JMP instruction in HMA that corresponds to F01D:FEF0 so CP/M code works even with A20 enabled
2. Add option to select between one of two behaviors noted with the CALL FAR in the PSP segment: one, the MS-DOS 2.x behavior of using the offset field for the size of the data segment (as it does now) and two, the MS-DOS 5.x and higher behavior of writing one of two target addresses depending on whether 64KB or more of memory is available or not.
3. Add code to emulate "Create PSP" INT 21h bug where CP/M CALL FAR address is off by two (noted from DEBUG.COM), but Load Program INT 21h call encodes correct instruction.
4. Find DOS programs that use the CP/M entry point and test against them (DEMO.COM?)

**Comment by joncampbell123** [comment]
Most of these are done.

The only one left to add is the off-by-2 error when DEBUG.COM creates a PSP but does not load a program.

**Comment by sikthehedgehog** [comment]
Not sure if relevant, but is quitting a program with `ret` also emulated?
https://stackoverflow.com/a/12593311

**Comment by joncampbell123** [comment]
Of course.

RET works because the first bytes at offset 0 of the PSP are "INT 20h" which exits to DOS.

**Comment by joncampbell123** [comment]
This is done, as far as I know.
