### ISSUE TITLE
Finnish/Swedish/Noregian keyboard layouts don't work proprerly

### ISSUE THREAD

**Issue by Snowtiger256** [joncampbell123/dosbox-x#2733]
Finnish, Swedish and Norwegian keyboard layouts are messed up.
- Pressing the keys "äöå" doesn't work (as in not producing any input on the command line) , the " ' " key produces the input "ä"
- the symbol keys next to the enter key and between the "0" (zero) key and backspace don't produce input at all, with the exception of the " ' " key which produces the input "ä".
- also the "-" key next to "." and "," produces a "+" or a "?" on input.
- All of the above applies to Finnish/Swedish keyboard layouts, but Norwegian is also affected similarly (missing or incorrect input). 

To reproduce:
- Change keyboard layout to Finnish Swedish or Norwegian (for finnish input "Keyb fi" into Dosbox-X command prompt).
- Test affected keys by pressing them ("å" should be on the right side of "p" and "ö" and "ä" on the right side of "l" with "ö" between "l" and "ä")  

OS: Manjaro Cinnamon
DosBox-X: version 0.83.15 installed from AUR.

**Comment by Wengier** [comment]
Yes, you are right that version 0.83.15 may have issues with some keys in international keyboard layouts. There have been similar report in the following thread, and fixes were made accordingly:

https://github.com/joncampbell123/dosbox-x/issues/2663

Can you try to compile the latest repository code and see if it fixes the issue? Thanks!

**Comment by Snowtiger256** [comment]
I am new to linux and don't know how to do that, sorry.

**Comment by Wengier** [comment]
Please check out the BUILD page for information on building/compiling the DOSBox-X source code:

https://github.com/joncampbell123/dosbox-x/blob/master/BUILD.md

**Comment by Snowtiger256** [comment]
Issue Fixed as of version 0.83.16.

**Comment by maron2000** [comment]
I think this issue can be closed.
