### ISSUE TITLE
System menu items don't work with Windows SDL1 code

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2735]
When I build the Windows SDL1 version of current code, items in the Windows system menu (except for Minimize, etc.) have no effect. If you click on Hide/Show Menu Bar, nothing happens. Nothing happens if you click Configuration Tool or Mapper Editor. This problem doesn't occur in the SDL2 build.

Steps to reproduce:
Build VS2019, Release version.
Launch DOSBox-X.
Click on the system menu (at the left end of the title bar).
Click any item beneath the "Close" item. Nothing happens.

Expected behavior:
The menu items will do what they say they do.

EDIT: And it turns out this problem is also in the released version 0.83.15, SDL1 only. Surprising that no one reported this earlier!

**Comment by Wengier** [comment]
@emendelson Thanks for reporting. There was a bug in the modified SDL1 library, which is hopefully fixed by now (before the release). Please check out the new code.

**Comment by emendelson** [comment]
@Wengier - Yes, fixed now. Thank you!
