### ISSUE TITLE
ne2000 network

### ISSUE THREAD

**Issue by RBTCHENTPE** [joncampbell123/dosbox-x#2738]
DEAR SIR,

The  DOSBOX-X SDL2 is great, The  NETWORK is able to connect auto. and Mount it in good order. 

The question : unable to print assigned to Novell Printer Server(How to set printer to Novell Printer Server)

ACCESS PRINT IS NOT ABLE TO SEND TO PRINTER SERVER OF NOVELL?

PLEASE KINDLY HELP TO TEACH ME HOW TO SOLVE THE TROUBLE AS ABOVE STATEMENT.

Following condition: SET IPX=FALSE & NE2000=FALSE THEN LOAD NETWORK Module AS FLWS (DOES NOT WORK):
set nwlanguage=english
c:\NWCLIENT\LSL.com
c:\NWCLIENT\NE2000.com    (unable to find ne2000)
c:\NWCLIENT\IPXODI.com
c:\NWCLIENT\netx ps=andys

NET.CFG : (FILE DETAIL)
SPX CONNECTIONS=65
file handles=54
Link Driver NE2000
        PORT 300
        IRQ 10
        FRAME Ethernet_802.2
 NetWare DOS Requester
     PREFERRED SERVER=ANDYS
     FIRST NETWORK DRIVE = F
     NETWARE PROTOCOL = BIND NDS

SHELL-332-27: THE NUMBER SPECIFIED IN THE "FILES=" PARAMETER IN CONFIG.SYS PLUS
"FILE HANDLES=" IN NET.CFG EXCEEDS 254. PLEASE RECONFIGURE ONE OF THESE PARAMETER
I HAD SET FILES=200 ON CONGIS & FILE HANDLES=54 ON NET.CFG BUR STILL
BEING THE SAME PROBLEMS

![image](https://user-images.githubusercontent.com/88087368/127451662-ec453c7c-5726-4136-b31a-430b3c449125.png)

THANKS A LOT,
B. RGDS.,
ROBERT CHEN / sales.yrsoft@msa.hinet.net

**Comment by rderooy** [comment]
You need to have ``ne2000=true`` and ``ipx=false`` otherwise there is no emulated network adapter. And you need to load the netware requester as you seem to have done. But I have not tried actually using a netware requester in the last 25+ years. But if I remember correctly you need to boot real DOS for it to work, not use the integrated DOS.

**Comment by RBTCHENTPE** [comment]
Dear Sir,

 

Thanks a lot for the kind prompt reply,

 

B. Rgds.,

Robert Chen

**Comment by RBTCHENTPE** [comment]
Dear Sir,

 

Run dosbox-x SDL2 :

 

SET DEFAULT LANGUAGE IN TRADITIONAL CHINESE (TW)

Shown the alert message : “Could not load language message file 'TW' Tdefault language will be used.”

 

Would you please advise me how to download the package of “LANGUAGE OF TRADITIONAL CHINESE (TW)”



PART OF dosbox-x.conf:

[dosbox]

# language: Select a language file for DOSBox-X to use. Encoded with either UTF-8 or a DOS code page.

# You can set code page either in the language file or with "country" setting in [config] section.

 

language                  = TW

title                     = 

fastbioslogo              = false

startbanner               = true

bannercolortheme          = default

dpi aware                 = auto

quit warning              = auto

working directory option  = default

working directory default = 

show advanced options     = false

resolve config path       = true

hostkey                   = mapper

mapper send key           = ctrlaltdel

ime                       = auto

synchronize time          = false

machine                   = svga_s3

captures                  = capture

autosave                  = 

saveslot                  = 1

savefile                  = 

saveremark                = true

forceloadstate            = false

a20                       = mask

memsize                   = 63

nocachedir                = false

freesizecap               = cap

 

B. Rgds.,

Robert Chen

 

From: ***@***.*** ***@***.*** 
Sent: Thursday, July 29, 2021 6:22 PM
To: 'joncampbell123/dosbox-x'; 'joncampbell123/dosbox-x'
Cc: 'Author'
Subject: RE: [joncampbell123/dosbox-x] ne2000 network (#2738)

 

Dear Sir,

 

Thanks a lot for the kind prompt reply,

 

B. Rgds.,

Robert Chen

**Comment by Dobby233Liu** [comment]
download [zh_TW.lng](https://github.com/joncampbell123/dosbox-x/raw/master/contrib/translations/zh/zh_TW.lng) and put it in the directory of dosbox-x.exe
then change language = TW to language = zh_TW
you may also look at these pages, it may or may not help:
- https://dosbox-x.com/wiki/Guide%3ARegional-settings-in-DOSBox%E2%80%90X
- https://dosbox-x.com/wiki/Guide%3AEast-Asian-language-support-in-DOSBox%E2%80%90X

**Comment by RBTCHENTPE** [comment]
Dear Wenyuan,

 

Thanks a lot for your kindly prompt reply,

 

1.      I haw press url link zh_TW.lng got html page shown as hereunder:

2.      I select All and copy to clipboard.

3.      Apple note open a new file copy all contents and then save it as zh_TW.lng 

4.      put zh_TW.lng in the directory of dosbox-x.exe

 

5.     Run dosbox-x SDL2 :

6.     SET config language = zh_TW

7.       Shown the same alert message : “Could not load language message file 'TW' Tdefault language will be used.”

8.        

9.      Would you please kindly advise me if I should download the language file of “zh_TW”

 

10.  Would you please kindly advise me the download url address of the zh_TW file?

 

Link zh_TW.lng got html contents parts as follows:

:DOSBOX-X:LANGUAGE:Traditional Chinese

:DOSBOX-X:CODEPAGE:950

:DOSBOX-X:VERSION:0.83.16

:DOSBOX-X:REMARK:建議使用繁體/正體中文DOS/V模式或者TTF輸出選項和字碼頁950配合中文TTF字型以直接支援中文顯示和列印

:AUTOEXEC_CONFIGFILE_HELP

本段落各行指令將在啟動時執行.

你可以把 MOUNT 指令寫在本處.

.

:CONFIGFILE_INTRO

# 這是給 DOSBox-X %s 使用的組態檔案。(敬請用最新版 DOSBox-X)

 

B. Rgds.,

Robert Chen
