### ISSUE TITLE
Reset window after exiting Mapper editor?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2746]
With current code, at least in macOS, if my DOSBox-X window isn't a standard 25x80 window, I need to reset the window size after exiting the Mapper editor. Could the program reset the window automatically after exiting the Mapper window? Many users won't know how to reset the window size, and there's probably no reason why it should be reset by hand. At least, could this be an option, even though I can't figure out any situation where it wouldn't be useful? Thanks for any help with this.

**Comment by Wengier** [comment]
Thanks for reporting this. It is hopefully fixed in the latest code. Please check it out.

**Comment by emendelson** [comment]
@Wengier - Fixed! Thank you.
