### ISSUE TITLE
Strange artifact in macOS SDL1 mapper editor - ignore: only occurs in patched code

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2749]
EDIT: Wait, ignore this, it occurs only in my slightly patched build, not in the standard code. Apologies for time-wasting. 

With current code, after I build SDL1 in macOS and start the mapper editor, a strange black rectangle appears in the lower left of the window, slightly blocking the mod2 and mod3 rectangles:

![Screen Shot 2021-07-31 at 9 25 22 AM](https://user-images.githubusercontent.com/5208505/127747736-63376fa4-7c8e-41e8-a0fc-acc6e5427c8e.png)

This doesn't occur with the SDL2 build.

**Comment by Wengier** [comment]
@emendelson I think this issue could indeed occur wuth the previous code, but only if you press a key to output some information in the Mapper Editor. It should be fixed in the release version.
