### ISSUE TITLE
Error when installing 0.83.16 for "just me"

### ISSUE THREAD

**Issue by blindphoneman** [joncampbell123/dosbox-x#2757]
Hi:

When I try to install 0.83.16 on Windows 10, 64-bit, and select the option to install for me only, it seems to install, but, I get the following error.

Setup
IPersistFile::Save failed; code 0x80070005.
Access is denied.
OK 

This does not occur when I run the install as administrator, regardless of which option I choose.

Thanks!

**Comment by yxmline** [comment]
Install with administrator privileges

**Comment by blindphoneman** [comment]
Yes, that avoids the error.  However, in the "Install for me only "
mode, the shortcuts should be placed in the User's area.  The reason
for the error is that the installer is trying to copy the shortcut to
the system "Public" Desktop, which is not the desired behavior when
this mode is selected.  No doubt, the script just needs a little
tweaking.  This is the first time this particular installer has been
used.  No big deal.

**Comment by Wengier** [comment]
@blindphoneman Please download the 64-bit installer again and see if fixes the issue.

**Comment by blindphoneman** [comment]
Looks like that did the trick.  Thanks!
