### ISSUE TITLE
Issues with debugger

### ISSUE THREAD

**Issue by martinlindhe** [joncampbell123/dosbox-x#276]
Hello, I can break into the debugger using ALT-PAUSE (on a build configured with --enable-debug=heavy)

However, launching a program and breaking into the debugger seems to be broken.

In old dosbox, it was possible to launch "DEBUG PROGRAM.EXE" to have the debugger break at program start.

Today (using e3c2874), when I run DEBUG program.exe, a single "-" is shown in the dosbox window, and the following in the log:

```
LOG:   51676485 ERROR MISC:DOS:0x37:Call for not supported switchchar
LOG:   51676947 ERROR DOSMISC:Get SDA, Let's hope for the best!
```

**Comment by martinlindhe** [comment]
NOTE: as a workaround, one can inject "INT 3" in the start of the program, and in dosbox debugger run "BPINT 3", then launch program to break at program start.

**Comment by joncampbell123** [comment]
DEBUG in DOSBox-X is an MS-DOS-like DEBUG taken from (I think) FreeDOS. The old DEBUG command is named DEBUGBOX

**Comment by martinlindhe** [comment]
Oh! Wonderful, then I can stop hacking "int 3" into my programs ;-) No issue then
