### ISSUE TITLE
Can't Mount Windows 1.01 Install Floppies

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2761]
i was trying to install Windows 1.01 from 360k floppy disks, when i try to mount images , it says "Cannot Create Drive From File"
i checked images, they were not corrupted, i had to mount drive A: as 360kb ramdisk and use freedos diskcopy to copy disk1 to drive A:

**Comment by rderooy** [comment]
Hmm... I have installed Windows 1.01 before, instructions are on the wiki, and did not have any such problems.

**Comment by Siddhant-Mashalkar** [comment]
here are install disks, check if these work on Dosbox-X or no
[Windows1.01.zip](https://github.com/joncampbell123/dosbox-x/files/6936712/Windows1.01.zip)

**Comment by cimarronm** [comment]
It looks like the zip has only read-only file permissions on the image files. Mount it as read-only in dosbox or change the permissions on the IMG files to include write access.
