### ISSUE TITLE
JMP illegal descriptor type C

### ISSUE THREAD

**Issue by piula** [joncampbell123/dosbox-x#2778]
**Describe the bug**
I wanted to have a look at REAL/32 and booted the install floppy of REAL/32 version 7.94. It fails with the error message "JMP illegal descriptor type C".

The boot image is downloaded from
https://winworldpc.com/download/5d67515f-f2b6-11e8-9b71-fa163e9022f0
(in case the link doesn't work, use https://winworldpc.com/product/real-32/7x and download version 7.94)

I haven't tried any other versions yet but want to do so.

**To Reproduce**
1. Insert floppy "ims794_1.img" into virtual floppy drive A:
2. BOOT A:
3. See error

**Expected behavior**
I do not know whether this is supposed to work at all. Maybe REAL/32 is unsupported at all (such as OS/2). In this case, please apologize and ignore my report.
However, 32bit-mode seems to be supported to some point as Win9x runs flawlessly within DOSBox-X. So maybe the observed issue might be relevant for other uses of the emulation as well.

**Environment (please complete the following information):**
 - Operating system: Windows 8.1 pro 64bit
 - DOSBox-X release version: 0.83.16 SDL1 64bit
 - Used configuration, e.g. ```dosbox-x.conf```

contents of dosbox-x.conf:

[sdl]
autolock = false
clip_key_modifier = shift
clip_mouse_button = right
clip_paste_speed = 30
fulldouble = false
fullresolution = desktop
fullscreen = false
mapperfile = mapper-dosbox-x.sdl1.map
mapperfile_sdl2 = mapper-dosbox-x.sdl2.map
mouse_emulation = never
mouse_wheel_key = -1
output = default
priority = higher,normal
sensitivity = 100
showbasic = false
showdetails = false
showmenu = true
titlebar = 
transparency = 5
usescancodes = auto
usesystemcursor = true
waitonerror = true
windowposition = 
windowresolution = original

[log]
logfile = 

[dosbox]
captures = capture
disable graphical splash = true
fastbioslogo = false
freesizecap = cap
language = 
locking disk image mount = true
machine = svga_s3
mapper send key = ctrlaltdel
memsize = 16
nocachedir = false
nocachedir = true
quit warning = false
savefile = 
saveslot = 1
show advanced options = false
startbanner = false
synchronize time = true
title = 
unmask keyboard on int 16 read = true

[video]
vmemsize = -1
vmemsizekb = 0
high intensity blinking = true

[pc98]
pc-98 BIOS copyright string = false
pc-98 fm board = auto
pc-98 enable 256-color = true
pc-98 enable 16-color = true
pc-98 enable grcg = true
pc-98 enable egc = true
pc-98 bus mouse = true
pc-98 force ibm keyboard layout = false

[render]
aspect = false
autofit = true
euro = -1
frameskip = 0
glshader = none
monochrome_pal = green
scaler = normal2x

[ttf]
blinkc = 6
font = 
ptsize = 20

[vsync]
vsyncmode = off
vsyncrate = 75

[cpu]
core = auto
fpu = true
cputype = auto
cycles = auto
cycleup = 10
cycledown = 20
cycle emulation percentage adjust = 0
apmbios = true
integration device = true

[keyboard]
aux = true
controllertype = auto
auxdevice = intellimouse

[voodoo]
voodoo_card = auto
glide = false
splash = true

[mixer]
nosound = false
swapstereo = false
rate = 44100
blocksize = 1024

[midi]
mpu401 = intelligent
mpubase = 0
mididevice = default
midiconfig = 
samplerate = 44100
mpuirq = -1
mt32.romdir = 
fluid.driver = default
fluid.soundfont = 

[sblaster]
sbtype = sb16
sbbase = 220
irq = 7
dma = 1
hdma = 5
enable speaker = false
sbmixer = true
oplmode = auto
oplemu = default
oplrate = 44100
oplport = 
hardwarebase = 220
goldplay = true
blaster environment variable = true

[gus]
gus = false
gusrate = 44100
gusmemsize = -1
gus master volume = 0.00
gusbase = 240
gusirq = 5
gusdma = 3
gustype = classic
ultradir = C:\ULTRASND

[innova]
innova = false
samplerate = 22050
sidbase = 280
quality = 0

[speaker]
pcspeaker = true
pcrate = 44100
tandy = auto
tandyrate = 44100
disney = false
ps1audio = off
ps1audiorate = 22050

[joystick]
joysticktype = auto
timed = true
autofire = false
swap34 = false
buttonwrap = false

[mapper]
joy1deadzone0- = 0.60
joy1deadzone0+ = 0.60
joy1deadzone1- = 0.60
joy1deadzone1+ = 0.60
joy1deadzone2- = 0.60
joy1deadzone2+ = 0.60
joy1deadzone3- = 0.60
joy1deadzone3+ = 0.60
joy1deadzone4- = 0.60
joy1deadzone4+ = 0.60
joy1deadzone5- = 0.60
joy1deadzone5+ = 0.60
joy1deadzone6- = 0.60
joy1deadzone6+ = 0.60
joy1deadzone7- = 0.60
joy1deadzone7+ = 0.60
joy2deadzone0- = 0.60
joy2deadzone0+ = 0.60
joy2deadzone1- = 0.60
joy2deadzone1+ = 0.60
joy2deadzone2- = 0.60
joy2deadzone2+ = 0.60
joy2deadzone3- = 0.60
joy2deadzone3+ = 0.60
joy2deadzone4- = 0.60
joy2deadzone4+ = 0.60
joy2deadzone5- = 0.60
joy2deadzone5+ = 0.60
joy2deadzone6- = 0.60
joy2deadzone6+ = 0.60
joy2deadzone7- = 0.60
joy2deadzone7+ = 0.60

[serial]
serial1 = dummy
serial2 = dummy
serial3 = disabled
serial4 = disabled
phonebookfile = phonebook-0.83.7.txt

[parallel]
parallel1 = disabled
parallel2 = disabled
parallel3 = disabled
dongle = false

[printer]
printer = true
dpi = 360
width = 85
height = 110
printoutput = png
multipage = false
docpath = .
timeout = 0

[dos]
autoloadfix = true
automount = true
automountall = false
dos clipboard api = true
dos clipboard device enable = false
dos clipboard device name = CLIP$
dosv = off
drive z expand path = true
ems = true
hma = true
int33 = true
keyboardlayout = auto
lfn = auto
mountwarning = true
quick reboot = false
shell configuration as commands = false
startcmd = false
startquiet = false
startwait = true
umb = true
ver = 
xms = true
xms handles = 0

[ipx]
ipx = false

[ne2000]
ne2000 = false
nicbase = 300
nicirq = 3
realnic = list

[ide, primary]
enable = true
pnp = true

[ide, secondary]
enable = true
pnp = true

[ide, tertiary]
enable = false
pnp = true

[ide, quaternary]
enable = false
pnp = true

[ide, quinternary]
enable = false
pnp = true

[ide, sexternary]
enable = false
pnp = true

[ide, septernary]
enable = false
pnp = true

[ide, octernary]
enable = false
pnp = true

[fdc, primary]
enable = false
pnp = true
mode = ps2

[4dos]
;InstallPath=R:\DOS\4DOS
Swapping=XMS, EMS, Z:\TEMP, None
TreePath=Z:\TEMP
UMBAlias=Yes
UMBDirHistory=Yes
UMBEnvironment=Yes
UMBFunction=Yes
UMBHistory=Yes
UMBLoad=Yes
AmPm=No
ANSI=Auto
AppendToDir=No
BeepLength=1
CompleteHidden=Yes
CopyPrompt=Yes
DecimalChar=.
Descriptions=No
Environment=2048
EscapeChar=Ctrl-P
EditMode=InitInsert
HistCopy=No
HistDups=Last
HistMove=Yes
HistWrap=Yes
ListRowStart=1
ThousandsChar=,
UnixPaths=No
UpperCase=Yes

[config]
break = on
country = 
device = 
devicehigh = 
dos = high, umb
fcbs = 100
files = 200
install = Z:\SYSTEM\MOUNT.COM -Z B:
install = B:\SYSTEM\MOUNT.COM R: U:\DOSLIFE
installhigh = 
lastdrive = z
numlock = off
rem = This section is DOS's CONFIG.SYS file, not all CONFIG.SYS options supported
set path = B:\;R:\TOOLS\VARIOUS
set prompt = $P$G
set temp = 
shell = R:\DOS\4DOS\4DOS.COM

[autoexec]

**Comment by piula** [comment]
Same issue with REAL/32 version 7.6, so I suppose it's a general problem with this OS.

**Comment by joncampbell123** [comment]
I see this happen at a point where it is in 32-bit protected mode and it does a JMP FAR CS:DWORD PTR [address], which leads to F8:0000. Segment F8 in the GDT is type C.

    00F8: b:00000068 type: 0C parbg
          l:00009118 dpl : 0  10000

Code that causes crash (from protected mode)

    00E0:00001CD6 2EFF2D101C0000      jmp  far dword cs:[00001C10]

Registers are DS=0080   ES=0000   FS=0000   GS=0020   SS=0080    CS=00E0

Type C according to Intel docs is a "386 Call Gate", which neither DOSBox-X nor DOSBox SVN implement. I guess it's time to add it.

**Comment by joncampbell123** [comment]
DOSBox-X and DOSBox SVN do support 286/386 call gates for CALL, not JMP, so the solution seems to copy the case block from CALL to JMP and remove all the stack switching stuff. Testing now.

**Comment by joncampbell123** [comment]
REAL/32 boots, though it seems to be waiting for something that never arrives.

Also there seems to be a failure to virtualize the interrupt controller properly, and it waits with IRQ0 and IRQ1 masked.

**Comment by piula** [comment]
Thank you for fixing this.

I just tested with v0.84.1 and REAL32 can be installed without any problem and seems to run without issues, too! 👍
