### ISSUE TITLE
Bug or Correct ? Error using the "|" character with [autoexec] ECHO

### ISSUE THREAD

**Issue by rebb** [joncampbell123/dosbox-x#2784]
**Describe the bug**
Using the "|" character inside the [autoexec] block with ECHO seems to make DosBox think it's a file piping action.
In this case it was just a visual element.

So i'm unsure if this is a bug or actually also how real DOS would react to encountering this character in an ECHO line ?
Reporting it just in case.

**To Reproduce**
1. Add something like "ECHO | Hi |" to the [autoexec] block of a .conf file that will be used
2. Launch DosBox
3. See error

**Expected behavior**
Unsure

**Screenshots**
![dosbox_x_error](https://user-images.githubusercontent.com/3278522/128627319-12e498a2-4d39-49e0-ba8e-7da210957e04.png)

**Environment (please complete the following information):**
 - Windows 7
 - DOSBox-X 0.83.16
 - custom .conf with mentioned content inside [autoexec]

**Comment by yxmline** [comment]
Please set temp in the [autoexec] first

**Comment by rebb** [comment]
What would i set temp to ?

This is pretty much directly copied from an existing .conf file that ships with the GoG Ultima Underworld.
It doesn't set any environment variables. This is used to display the pre-game DOS menu for it.
But afaik the default DosBox that comes with GoG games doesn't support the Piping operator ?

It's not a big issue - just wondering if normal DOS would do this too when trying to use "|" in an ECHO statement.

**Comment by rebb** [comment]
Ok, never mind, it seems this was a problem of using a text-viewer that converts the ANSI "double line" character into a "|", and i copied from that one into a new file.

Another editor displays the ANSI .. well at least not like an "|".
Sorry about that.
