### ISSUE TITLE
On Mac SDL1 version, key 'A' does not work since 0.83.15

### ISSUE THREAD

**Issue by tsupplis** [joncampbell123/dosbox-x#2787]
The A key (scan code 0) does not work on Mac since version 0.83.5. The key is unresponsive.

To test, just start DOSBox-x and type key a. Reverting to 0.83.14 works perfectly

**To Reproduce**
1. Start dosbox-x sdl1 on Mac, 
2. Type key 'a'
3. No result

**Expected behavior**
0.83.14 works properly

**Screenshots**

**Environment (please complete the following information):**
 - Operating system (11.5.1)
 - DOSBox-X release version or commit SHA1 this issue occurred on 0.83.15 and 0.83.16
 - Used configuration, Default

**Additional context**

**Comment by emendelson** [comment]
Works here:

![Screen Shot 2021-08-09 at 5 50 42 PM](https://user-images.githubusercontent.com/5208505/128779134-a45eae8a-4d22-4bd0-a5d1-e35c3ceeeabb.png)

**Comment by maron2000** [comment]
Hi, it seems that some people work while some don't. 
Can you try changing the `usescancodes` option (true, false, auto) and see if it changes?
Also, please provide information what mapper editor shows when 'a' key is pressed.

The figure below is when I pressed 'a' on Windows SDL1 version.
![mapper_screenshot](https://user-images.githubusercontent.com/68574602/128790452-92e32571-8d1b-429b-b3cd-c76e78443305.png)

**Comment by tsupplis** [comment]
# On 0.8.3.16 and 0.8.3.15:

With usescancode=true
<img width="633" alt="image" src="https://user-images.githubusercontent.com/11035456/128849380-5067049f-f09e-4e19-a176-b05286607025.png">
With usescancode=false and usescancode=auto
<img width="553" alt="image" src="https://user-images.githubusercontent.com/11035456/128849683-16880071-d345-45d1-bf96-032e2462024a.png">

# On 0.8.3.14:

With usescancode=true (Looks very strange)
<img width="553" alt="image" src="https://user-images.githubusercontent.com/11035456/128850239-58a9b0ca-9041-4670-a385-9069d59590c1.png">

So the net is it works with scancode=auto/false. Solution to the bug. But aweird change in 0.8.3.15 happened.

**Comment by maron2000** [comment]
@tsupplis Thanks for the information. So we can confirm that some fix is required for `usescancodes=true` option.
The fix on 0.83.15 and 16 was intended to fix the incorrect key names (not only Macs but Windows and Linux as well).
But it was unfortunate that a bug arised in Mac, but I think I got enough clues from you to think of a fix.
Meanwhile, I appreciate it very much if you inform here if other keys have weird results, so that I can fix it as well.

**Comment by tsupplis** [comment]
Here is a validation with a simple checkout test with scancode to true. A aka scan code 0 is the only one not working.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/11035456/128859921-6aeff7e6-f782-408b-a895-4ccadf679dd9.png">

**Comment by maron2000** [comment]
@tsupplis Thank you again for your information.
For the fix of 'A' key, I think the following piece of code in `sdl_mapper.cpp` needs to be fixed.
If you can build on your own, can you try it?

```c++
/* Portion of code from GetKeyCode() function in sdl_mapper.cpp */
#if defined (MACOSX)
    /* before */    
    // if ((keysym.scancode == 0) && (keysym.sym == 'a')) key = keysym.sym;  // zero value makes the keyboard crazy
    /* after */
    if ((keysym.scancode == 0) && (keysym.sym == 'a')) return keysym.sym;  // zero value makes the keyboard 
#endif
```

**Comment by tsupplis** [comment]
So I built the source HEAD with the recommended fix and it works perfectly.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/11035456/128866905-035a3510-cb51-4bcd-b761-51579b5d251a.png">

**Comment by maron2000** [comment]
Thank you for your prompt confirmation.
I will make a pull request for this fix.
Thanks again for your cooperation.

**Comment by maron2000** [comment]
I think this issue can be closed.
