### ISSUE TITLE
Only the first track is played using CUE/MP3

### ISSUE THREAD

**Issue by kehak** [joncampbell123/dosbox-x#2795]
When using DOSBox-X to play older games with digitized CDs (cuesheets and MP3s), only the first track can be heard throughout the game. Other tracks aren't played.

This works fine with DOSBox and DOSBox-staging using the same configuration.

**To Reproduce**
- Convert a DOS CD game into a cuesheet with MP3 files (haven't tried with OGG). I'm using Screamer 2 as it allows to select a track without the need to go through the game.
- imgmount d "/path/to/GAME.CUE" -t iso
- d:\game.exe
 
**Expected behavior**
All music tracks should be heard.

**Environment (please complete the following information):**
 - macOS 11.3, Windows 10 (updated)
 - DOSBox-X 0.83.16. I noticed this problem since I installed DOSBox-X in Feb. 2021.
 - Problem can be replicated with the default configuration on several machines

**Comment by Candlemass** [comment]
I had the same problem trying to do this with Quake a while back and mentioned the issue in another report.

I guess the devs decided to do nothing about it. Seems par for the course, sadly.

They would rather blame everyone else or attempt to have you invest a million hours jumping through hoops trying to find a workaround rather than fix their code.

So I moved on to another fork where the devs actually care about bugs in their software.

**Comment by joncampbell123** [comment]
Can you try any other BIN/CUE combination and see if it works?

My test case seems to work fine, including the GOG release of "Alone in The Dark".

**Comment by maron2000** [comment]
Tried Screamer 2, and totally no problem, I think. (0.83.16 release Windows SDL1 64-bit)

Uploaded a video. You need to change the extension to '.avi' to see.
[startl_000.avi.txt](https://github.com/joncampbell123/dosbox-x/files/6989707/startl_000.avi.txt)

For your reference, the following is the cue sheet I used.
```
FILE "SCREAM2.BIN" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Track02.mp3" MP3
  TRACK 02 AUDIO
    INDEX 02 00:00:00
FILE "Track03.mp3" mp3
  TRACK 03 AUDIO
    INDEX 03 00:00:00
FILE "Track04.mp3" mp3
  TRACK 04 AUDIO
    INDEX 04 00:00:00
FILE "Track05.mp3" mp3
  TRACK 05 AUDIO
    INDEX 05 00:00:00
FILE "Track06.mp3" mp3
  TRACK 06 AUDIO
    INDEX 06 00:00:00
FILE "Track07.mp3" mp3
  TRACK 07 AUDIO
    INDEX 07 00:00:00
FILE "Track08.mp3" mp3
  TRACK 08 AUDIO
    INDEX 08 00:00:00
FILE "Track09.mp3" mp3
  TRACK 09 AUDIO
    INDEX 09 00:00:00

REM  TRACK 02 AUDIO
REM    PREGAP 00:02:00
REM    INDEX 01 21:41:60
REM  TRACK 03 AUDIO
REM    INDEX 01 25:46:47
REM  TRACK 04 AUDIO
REM    INDEX 01 29:54:70
REM  TRACK 05 AUDIO
REM    INDEX 01 34:03:48
REM  TRACK 06 AUDIO
REM    INDEX 01 38:06:65
REM  TRACK 07 AUDIO
REM    INDEX 01 42:00:06
REM  TRACK 08 AUDIO
REM    INDEX 01 45:35:00
REM  TRACK 09 AUDIO
REM    INDEX 01 49:43:62
```

**Comment by kehak** [comment]
This is weird, I still have this issue.

To help troubleshooting this, I've uploaded a troublesome game here:
https://drive.google.com/file/d/1-s37Y2axgjtEI7h7hxqkgZw-wUvrj1XR/view?usp=sharing

To replicate:
- Edit the path in SWIV.BAT according to your system (it just mounts the CUE file), then start the game.
- Press a key to leave the short intro sequence, and get to the main menu. The background music (track1) should be heard.
- Select the "Test" player, then "Retry Mission" and pick any level.

-> There should be no background music with DOSbox-X, while this should work with DOSbox-staging.

Can you replicate this issue?

**Comment by maron2000** [comment]
@kehak 
I tried and indeed I got no sound after the mission starts, as you mentioned.
I checked the original cue sheet of CD-DA tracks(cue + bin), and found that each track besides track 02 **_have both indices 00 and 01_**.
I amended SWIV,cue as follows to match with the original cue+bin one, and confirmed that we get music.

So your issue is kind of special, that DOSBox-X doesn't fall back to INDEX 01 if it fails to play INDEX 00. 
I don't know whether this is a bug, but I think the cue sheet of ISO+MP3 _should include INDEX 00_ if the original cue sheet does.

BTW, my copy has up to 10 tracks but yours only have seven(7). You may want to check it.
```
FILE "SWIV.BIN" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
FILE "01.OGG" OGG
  TRACK 02 AUDIO
    INDEX 01 00:00:00
FILE "02.OGG" OGG
  TRACK 03 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "03.OGG" OGG
  TRACK 04 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "04.OGG" OGG
  TRACK 05 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "05.OGG" OGG
  TRACK 06 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "06.OGG" OGG
  TRACK 07 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "07.OGG" OGG
  TRACK 08 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
```

**Comment by kehak** [comment]
@maron2000 

Thank you for your help, now there is some progress. Using your CUE file, I manage to get the music for the main menu and the first two levels, but not the rest of the game. I also managed to get the last track playing by messing with the pregaps, although it crops the start of the track.

Can you confirm you get the background music for level "Breakout!" for instance?

Indeed I'm aware the games uses 10 tracks, the last three ones are only played if you select the classical music style, which I don't use so I didn't rip them back then.

**Comment by grapeli** [comment]
@kehak 
Leave the older version of the cue file and replace "blank" iso image with this version.
[SWIV.BIN.txt](https://github.com/joncampbell123/dosbox-x/files/7008696/SWIV.BIN.txt)

**Comment by kehak** [comment]
@grapeli 
Thank you, there's more progress. Now only level 2 and 3 are mute, I get the music everywhere else.
How did you create this BIN file?

I tried ripping the original CD again and converting the tracks in MP3 (bchunk + lame), in case something was wrong with the previous ripping.

This makes apparently no difference: level 2 and 3 are still mute with your BIN file, and only levels 1 and 2 play with @maron2000 CUE file. I'm not sure what can trigger this behavior. Does the "-X" fork differ substantially from DOSbox and DOSbox-staging when playing CUE + MP3 files?

**Comment by grapeli** [comment]
@kehak 
In this way - `mkisofs -XA -V "CDROM" -r -o SWIV.BIN .`.

In my opinion, this iso/cue is not properly prepared (I can be wrong).

You can try to do better. Use [dbx-conv](https://www.vogons.org/viewtopic.php?f=31&t=77260) BIN/CUE to ISO/CUE converter. I don't know what systems it works under (for sure under Linux).

I don't know how to get to the next levels in this game.

**Comment by grapeli** [comment]
I checked two different combinations. The new cue file suggested by @maron2000 and your version of the cue file with my iso image.
In both combinations it works:
- 01.ogg soundtrack in the main menu
- 02.ogg soundtrack on level 1.
- playback correctly the other five by running `cdplay` from disk from `z:`.

Share the save file from other levels I will be happy to test.

**Comment by maron2000** [comment]
I didn't think that the cue sheet work for only limited tracks!
We might be able to find a way to work, but may have to look into the source, since staging works. 
I actually don't know what part of the source, but I think where it parses the cue sheet is the point.

**Comment by maron2000** [comment]
I think the save file is SWIV.CFG.

**Comment by grapeli** [comment]
@maron2000 
Playback order.
01.OGG Main Menu
02.OGG Rookie
03.OGG Seek & Destroy
04.OGG Estuary Assault
05.OGG Breakout!
06.OGG Lakeside Sweep
07.OGG The Volcano
They actually don't play some tracks properly.

**Comment by maron2000** [comment]
@grapeli Thanks for the information. 
Meanwhile I was taking a look at cdrom_image.cpp of Dosbox-staging,  and found that there are sooooo many differences...

**Comment by maron2000** [comment]
So I enabled logging to see what DOSBox-X is trying to play when the sound is missing.
It seems that the calculation of offset is incorrect? 
6.7min.-mark should be no sound.
Also, I don't know why it trys to play the data track.

```
Game tries to play the data track. Not doing this: 0
Game tries to play the data track. Not doing this: 0
Game tries to play the data track. Not doing this: 0
 CDROM: Playing track 2 at 44.1 KHz 2-channel at start sector 63026 (6.7 minute-mark), seek 71284416 (skip=0,dstart=32718,secsize=2352), for 22372 sectors (298.3 seconds)
```

**Comment by kehak** [comment]
Oh wow, I didn't expected so much activity. Thank you all for diving into this issue.
@maron2000, let me know if I can help you with this. I'll be reading your updates with great interest.

**Comment by grapeli** [comment]
@maron2000 
I downloaded the full version of SWIV 3D (from eXoDOS) and the play time of each track is different. 

  eXoDOS | this version
01 7:11.51 7:13.92
02 6:42.20 6:44.56
03 4:57.76 5:00.17
04 4:59.89 5:02.03
05 4:30.49 4:32.69
06 4:51.80 4:54.22
07 4:56.28 4:58.68

**Comment by maron2000** [comment]
@kehak Well, I'm not a experienced developer so don't expect too much from me, but I'll try if I can find something.

**Comment by kehak** [comment]
@Candlemass Could you provide a copy of your non functioning Quake game, including the cuesheet? If you're having the same problem, it would help to have a second game to test.

**Comment by grapeli** [comment]
@kehak 
I tried to adjust a cue file on your audio tracks. Without a satisfactory result.

I have prepared a new one. Compressed with the opus codec. On these it plays as it should be. Check.
https://drive.google.com/file/d/1aWJMOKtU6tdWmlnyASWimvvmB5o_iKz2/view?usp=sharing

**Comment by grapeli** [comment]
Out of curiosity, I launched the Windows version of SWIV 3D (3DFX) under wine. Game image mounted with CDEmu. All audio tracks are played correctly. Graphically, it looks much better than the DOS version.

https://user-images.githubusercontent.com/452325/130427045-5ba26662-1cd3-4739-975a-a87438fe1603.mp4

**Comment by kehak** [comment]
@grapeli 
Just got back from holidays, sorry for the late answer.

> @kehak
> I tried to adjust a cue file on your audio tracks. Without a satisfactory result.
> 
> I have prepared a new one. Compressed with the opus codec. On these it plays as it should be. Check.
> https://drive.google.com/file/d/1aWJMOKtU6tdWmlnyASWimvvmB5o_iKz2/view?usp=sharing
> 
> Compressed Ogg Vorbis.
> https://drive.google.com/file/d/10GgYrKB90PgrCrw-udBMPKJbC6NCyUce/view?usp=sharing

Amazing, this solves the problem! How did you generate this new cue file?

> Out of curiosity, I launched the Windows version of SWIV 3D (3DFX) under wine. Game image mounted with CDEmu. All audio tracks are played correctly. Graphically, it looks much better than the DOS version.

Indeed, the Windows version uses the 3DFx or DirectX API with antialiasing and filtering, so it's no surprise it looks better than the "raw" DOS version.

Apparently this problem is game-specific and not so much an issue with DOSBox-X per se, so I guess we can close the issue for now. Thanks a bunch for solving this problem.

**Comment by grapeli** [comment]
@kehak 
> Amazing, this solves the problem! How did you generate this new cue file?

Based on other ripped audio files. One file (05) did not play. I made minor adjustments and tested. Except that his starting position influenced the next ones. In the end, either approach was successful.
