### ISSUE TITLE
Can't start Windows 3.1 with DosBox-X version 0.83.16

### ISSUE THREAD

**Issue by signer-ink-beast** [joncampbell123/dosbox-x#2800]
**Describe the bug**
Starting my installation of Windows 3.1 with version 0.83.16 of DosBox-X crashes DosBox-X. I use a file on the root of my mounted C drive, windows.bat, to start windows. It has the following content:

```
@c:\windows\smartdrv.exe
@SET PATH=%PATH%;C:\WINDOWS; 
@SET TEMP=C:\WINDOWS\TEMP
@lh devlod C:\SB16\DRV\CSP.SYS /UNIT=0 /BLASTER=A:220
@lh devlod C:\SB16\DRV\CTMMSYS.SYS
@SET SOUND=C:\SB16
@SET BLASTER=A220 I7 D1 H5 P330 T6
@SET MIDI=SYNTH:1 MAP:E
@C:\SB16\MIXERSET /P /Q
@windows\win /b
```

**To Reproduce**
1. Start DosBox-X from the terminal
2. Do your C drive mounts and switch to your C drive as usual.
3. Run windows.bat
4. DosBox-X crashes.

**Expected behavior**
I expected Windows 3.1 to run within DosBox-X as it always did without crashing the emulator. Last version I used where it worked was 0.83.14. This same batch file also works in vanilla DosBox, both stable and svn.

**Screenshots**

**Environment (please complete the following information):**
 - Linux Mint 20.2 with DosBox-X installed via flatpak
 - DOSBox-X 0.83.16
 - Default config with mounts in autoexec.bat, and `core=normal`

**Additional context**
Log of program output attached
[dosbox-x-win3.1-83.16.log](https://github.com/joncampbell123/dosbox-x/files/6988634/dosbox-x-win3.1-83.16.log)

**Comment by Siddhant-Mashalkar** [comment]
for me, core=dynamic and core=normal both work fine
have you installed Windows to a hard disk image file, or shared folder
if in hard disk image, what is version of DOS?
if you want SB16 drivers to load, you can add them through Windows 3.1 control panel and removing these lines:
```
@lh devlod C:\SB16\DRV\CSP.SYS /UNIT=0 /BLASTER=A:220
@lh devlod C:\SB16\DRV\CTMMSYS.SYS
@SET SOUND=C:\SB16
@SET BLASTER=A220 I7 D1 H5 P330 T6
@SET MIDI=SYNTH:1 MAP:E
@C:\SB16\MIXERSET /P /Q
```

**Comment by Siddhant-Mashalkar** [comment]
try reinstalling Windows 3.1

**Comment by signer-ink-beast** [comment]
Good news. Did a complete reinstall of Windows 3.11  within DosBox-X. I still have my windows.bat file with the contents shown in [this comment](https://github.com/joncampbell123/dosbox-x/issues/2800#issuecomment-907382820), and now it starts without issues. I have no idea what happened to my previous install that broke it with DB-X, but not vanilla DB. Maybe some file corruption somewhere. Oops. Thanks for the help, @Siddhant-Mashalkar .

For anybody else who happens to stumble across a similar issue to this one in the future, try a complete reinstall, not an upgrade (delete your old Windows 3.1's WINDOWS folder in whatever directory you use as your virtual C drive with DosBox-X, then run the installer after copying the contents to a folder, like "install", in the root of your virtual C). See if any of the issues you had with your old installation persist after that.
