### ISSUE TITLE
hercules or mda with monochrome_pal= gives wrong colour

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#2802]
**Describe the bug**
- Starting with ``machine=mda`` defaults to **white**.
- Starting with ``machine=hercules`` defaults to **white**.
- Starting with ``cga_mono`` defaults to **green**.

With ``machine=cga_mono``  setting ``monochrome_pal=white``,  ``monochrome_pal=green`` or  ``monochrome_pal=amber`` work properly.

But with either ``machine=mda`` or ``machine=hercules``, setting ``monochrome_pal=green`` gives white and setting ``monochrome_pal=white`` gives green.

**Comment by Allofich** [comment]
Assuming the linked PR fixed this, this should be closed.

**Comment by rderooy** [comment]
Thanks @Allofich I'm sure it does, but cannot test right now.
