### ISSUE TITLE
[feature suggestion] PC-98 support

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#281]
The NEC PC-9801 was the Japanese version of the PC. It has many architectural differences when compared to the standard IBM PC, even more than the PCjr had.  But it's a wonderful machine that runs a custom version of MS-DOS and has a huge library of games.

Wikipedia article:
https://en.wikipedia.org/wiki/PC-9800_series

Technical info is available here:
https://www.vogons.org/viewtopic.php?f=9&t=47469

**Comment by joncampbell123** [comment]
This is a dup of a feature request I already added myself:

https://github.com/joncampbell123/dosbox-x/issues/106

Patches are welcome to add to it.
