### ISSUE TITLE
Dosbox-X Command Shell broken in Windows 1.x and 2.x

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2812]
i tried launching Dosbox-X Command Shell (COMMAND.COM) From Windows 2.x and 1.x , Doesn't work on 1.x , Windows 1 stops responding and reboot guest system doesn't work , it works on Windows 2.x , but it just displays ">" prompt, no output is displayed but commands are executed, windows 2.x doesn't freeze. why is Command Shell so broken under Windows 2.x

**Comment by maron2000** [comment]
I guess you have many questions, but can you give us feedbacks to the given answers?
I think it is also important for others.

**Comment by Siddhant-Mashalkar** [comment]
ok

**Comment by Siddhant-Mashalkar** [comment]
i don't have many questions, just some

**Comment by maron2000** [comment]
Many and some will not substantially change what I have mentioned, right?

**Comment by Siddhant-Mashalkar** [comment]
wait , i am confused
