### ISSUE TITLE
Does this branch (dosbox-x) include patches that included in Dosbox SVN Daum branch?

### ISSUE THREAD

**Issue by wean-irdeh** [joncampbell123/dosbox-x#282]
List of patches on Dosbox SVN Daum branch:

Direct3D with pixelshaders, OpenglHQ, Innovation, Glide, zip/7z mount, Beep, NE2000 Ethernet, Graphical user interface (menu), Save/Load states, Vertical sync, CPU flags optimization, Various DOS commands (PROMPT VOL, LABEL, MOUSE, etc) and CONFIG.SYS commands (DEVICE, BUFFERS, FILES, etc), Continuous turbo key, Core-switch key, Show details (from menu bar), Nice DOSBox icon, Font patch (cp437), MAKEIMG command, INTRO, Ctrl-break patch, DBCS support patch, Automatic mount, Printer output, MT-32 emulation (MUNT), MP3CUE, Overscan border, Stereo-swap, SDL_Resize, Internal 3dfx voodoo chip emulation, Amstrad & PS/1 sound emulation, Fluidsynth soundfont support, Timidity++ backend support, CGA w/ Monochrome Monitor Support, Improve PC Speaker emulation accuracy patch, Pentium MMX, Dongle support, Secondary display, DOSBox-X branch, File-locking support patch, xBRZ scaler, etc.

**Comment by joncampbell123** [comment]
This codebase inherited from Daum SVN, yes. Some of it may have bitrotted, but it's still there.

Daum doesn't seem to have updated his codebase recently as far as I know.

**Comment by wean-irdeh** [comment]
Thanks for the answer
