### ISSUE TITLE
Cant' type the letter "a"

### ISSUE THREAD

**Issue by betzburger** [joncampbell123/dosbox-x#2826]
I use v0.83.16 and wanted to switch to the German keyboard layout.
In the [dos] section I set the keyboardlayout setting to "de" and in the [config] section I set the country to 049.
Everything seems fine but I can't type the character "a".

**Comment by emendelson** [comment]
See #2787. Are you using a Mac?

**Comment by betzburger** [comment]
Yes. I use the MacBook Pro M1. Thanks for the link.

**Comment by maron2000** [comment]
I think this issue can be closed.
