### ISSUE TITLE
Compiling on Visual studio 2017 fails (including fix)

### ISSUE THREAD

**Issue by ggnkua** [joncampbell123/dosbox-x#284]
Hi,

I just pulled the latest source tree and tried to build on my VS2017 on Win10 and it failed because of redefinition of std::isinf - apparently this was needed in VS2008 but it seems that the definition is present on new versions of VS.

So in order to get it to build I modified src\fpu\fpu_instructions.h, line 316 to

`#if defined(WIN32) && (_MSC_VER<1910)`

and that did the trick. It might work with VS earlier than 2017 (my guess would be up to 2013) but I cannot test.

Sorry for not making a pull request but I'm absolutely terrible when it comes to stuff like this :).

**Comment by joncampbell123** [comment]
I recommend this instead:

#if defined(WIN32) && defined(_MSC_VER) && (_MSC_VER<1910)

Does that work?

I'm not sure what the preprocessor would do with (_MSC_VER<1910) when _MSC_VER is not defined.

**Comment by ggnkua** [comment]
Hi,

Your suggestion seems to work fine. Just out of curiosity I tried adding `#undef _MSC_VER` just before the `#if` and tried both your suggestion and mine. The compiler didn't throw any errors because of the undefined symbol. So it's a matter of preference I suppose.

**Comment by nzjpnboy** [comment]
I ran into an issue when trying to compile in both VS 2015 and VS 2017. (Windows 10)
The "fpu_instructions.h" file had an error on Line 457 where the "std::isinf" was expecting an identifier. Would love to know how you got past that one ggnkua.. 
My solution was bad to say the least. I just commented out the if.
The below is the offending code:

`	if (CPU_ArchitectureType<CPU_ARCHTYPE_386) {
		if (std::isinf (fpu.regs[st].d) && std::isinf(fpu.regs[other].d)) {
			/* 8087/287 consider -inf == +inf and that's what DOS programs test for to detect 287 vs 387 */
			FPU_SET_C3(1);FPU_SET_C2(0);FPU_SET_C0(0);return;
		}
	}
`

**Comment by ggnkua** [comment]
Hi there,

Did you try my proposed fix above?

**Comment by nzjpnboy** [comment]
Ah, I thought it was already applied to the code. I have changed it to the solution provided by joncampbell and it seems to work.

**Comment by nzjpnboy** [comment]
A word for the weary, when I cloned the repo with the VS 2017 git it missed the "zconf.h" file.

**Comment by aybe** [comment]
fixed on develop branch (the branch that should include the latest fixes to be merged with master branch)
