### ISSUE TITLE
The register used in the mouse call Int 33, AX=13h may be incorrect

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#2840]
DOSBox-X uses register BX in handling this call. This is inherited from SVN, which also still uses BX.

```
    case 0x13:      /* Set double-speed threshold */
        mouse.doubleSpeedThreshold = (reg_bx ? reg_bx : 64);
        break;
```

But online sources say the register used is DX.

https://stanislavs.org/helppc/int_33-13.html
http://www.ctyme.com/intr/rb-5976.htm

**Comment by joncampbell123** [comment]
Seems about right.

**Comment by joncampbell123** [comment]
I can confirm from other sources and the Microsoft Programmers PC Sourcebook vol 2. that it is indeed DX.
