### ISSUE TITLE
Grammatik for DOS crashes with "Ran out of CacheBlocks"

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#2847]
When running Grammatik 5 Version 1.1 for DOS, Grammatik completes the checking of the file, but terminates with this error message at the Grammatik prompt to save the checked file:

```
E_Exit
Ran out of CacheBlocks
```

I see from [this page](https://dosbox-x.com/doxygen/html/cache_8h_source.html) that this is a DOSBox-X error.

Windows Pro 7 32-bit; DOSBox-X 0.83.16; my DOSBOX-X.conf file is attached.
[DOSBOX-X.CONF.txt](https://github.com/joncampbell123/dosbox-x/files/7051093/DOSBOX-X.CONF.txt)

This problem does NOT occur with @Wengier's vDosPlus, and, incidentally, Grammatik's grammar check runs much more quickly under vDosPlus than it does under DOXBox-X.

Many thanks for any help!

Rob in Toronto

**Comment by Wengier** [comment]
Not sure if same version, but I tried both Grammatik 5 included with WordPerfect 6 and Grammatik IV 1.0 downloaded from https://winworldpc.com/product/grammatik/iv, and they both appear to run. Perhaps you can provide instructions on how to reproduce the said problem? Thanks!

**Comment by RobertJSawyer** [comment]
I apologize for wasting your time, my friend Wengier! Upon further investigation, I find that Grammatik only throws up that error message if the DOS terminate-and-stay-resident (TSR) program American Heritage English Dictionary, 3rd edition, is loaded before Grammatik is run.  If AHED is not resident, Grammatik executes flawlessly. I can work around this limitation.

Again, my apologies!

All best wishes.

Rob

**Comment by Wengier** [comment]
@RobertJSawyer I am glad to hear that you had already solved the problem so that it works fine for you now. Closing the issue.
