### ISSUE TITLE
U key does not register with Turkish-F keyboard

### ISSUE THREAD

**Issue by bitigchi** [joncampbell123/dosbox-x#2848]
**Describe the bug**
U key does not register when pressed with Turkish-F layout.

**To Reproduce**
1. Change system keyboard layout to Turkish-F
2. Change dosbox-x keyboard layout to `tr440` in the preference file (using a fresh setup)
3. Press the u key (it's the a button on a QWERTY layout)
4. Nothing registers

**Expected behavior**
The letter u should appear on screen.

**Environment (please complete the following information):**
 - macOS 11.5.2
 -  v0.83.16
 - Fresh configuration with the `tr440` addition above

**Comment by maron2000** [comment]
Thank you for testing, and glad to hear that it worked.
I'll post a pull request later on.
