### ISSUE TITLE
Pausing issue

### ISSUE THREAD

**Issue by MuYing-wSakura** [joncampbell123/dosbox-x#2853]
**Describe the bug**
Mouse cursor can't be released when pressing Ctrl+F10 while pausing the emulation  
(Seem's that Alt+Tab can solve this,but when switch back to the dosbox-x main window,it still will be captured by dosbox-x)
**To Reproduce**
1. Go to 'Main'
2. Click on 'Pause emulation'
3. Click on 'Capture mouse'
4. find error

**Expected behavior**
I don't know ;(

**Screenshots**
It can't be clearly see by screenshot,so no screenshots here.

**Environment (please complete the following information):**
 - Operating system
 Windows 10 Ver 21H1(19043)
 - Dosbox-x ver 0.83.16

**Comment by Wengier** [comment]
The pausing function released the keyboard but not the mouse, and I fixed it so that both are released, and you cannot capture mouse when the emulation is paused.
