### ISSUE TITLE
Can't mount 1.72M Floppy Disk, get Disk I/O Error when booting

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2855]
hi, so i just downloaded Mini-Windows Beta 2 , and was trying it on Dosbox-X, when i tried mounting image::
![command_000](https://user-images.githubusercontent.com/71384075/131209904-b1f5d449-20cc-4428-b798-1aae83741cac.png)

and when i tried to boot directly from image:
![guest os_001](https://user-images.githubusercontent.com/71384075/131209926-7639970a-8c70-4f63-a32a-17c330f849d5.png)

why i can't boot into image?

**Comment by rderooy** [comment]
See https://github.com/joncampbell123/dosbox-x/issues/1472

**Comment by Siddhant-Mashalkar** [comment]
> See #1472

ok
