### ISSUE TITLE
MOUNT command not working - Bad Command or File Name

### ISSUE THREAD

**Issue by ComradePaulT** [joncampbell123/dosbox-x#2858]
I've just updated Dosbox-X to the latest version but when I try to mount my directory as C drive the Mount command says "Bad Command or File Name".

Is there something I need to do at my end to update this?

**Comment by Siddhant-Mashalkar** [comment]
just type this if you get error:
set PATH=%PATH%;Z:\SYSTEM

**Comment by ComradePaulT** [comment]
That worked. Thank you
