### ISSUE TITLE
Improving the current code base

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#286]
## **Short term**

~~DosBox-X 0.801 will not run on XP SP3 #238 **TODO is this really useful?**~~
Default dosbox.conf contains the string Message not Found! #226
~~ZIP Releases #217~~
SDL can't select an output method other than 'surface' and 'overlay' #212
~~**Have a CHANGELOG to keep track of changes #292**~~
~~**Packages of releases for Windows should contain extra files: changelog, licence, etc #293**~~
**Describe the content and purpose of each branch. #294**

## **Mid term**
~~Mapping a WASD-like layout on joystick does not allow movement on 2 axes #202
(the better joystick patch, that'll assess my merging skills!)~~

## **Longer term**

~~So, how did the code base grew up to such monster ? #210~~
Scaling does not work #96
PhysPt for linear AND physical memory addresses #264 
~~Pentium Pro instruction set implementation #305~~
~~MMX instruction set recompiler for core=dynamic #290~~

### SDL2
Port from SDL 1.x to SDL 2.x #112
SDL2 migration #306

(strike-through means that it has been completed somehow, i.e. implemented or merged but not necessarily in master branch)

---

Rendering:

If I understand correctly, you have an arbitrary ratio bitmap scaler ? I guess it can be enhanced to support nearest neighbor and integer scaling relatively easily.

Now what about scalers, I guess you'd like to keep them,

How with minimum fuss can we leverage all these, your scaler, fancy scalers, shaders ?

I didn't catch that rendering silliness, well actually I do understand what it does, but not why it's done that way; explanations would be welcome.

Other:

Will all these branches ever be merged ? They've been here for ages, sure it'll be a nightmare to merge, if ever.

This fork is pretty cool, but there's no list of features that have been added, what are they ?

etc

**Comment by joncampbell123** [comment]
They're not all that fancy.

If you want to see what they look like, there's an initial implementation in "dosbox-rewrite" that works on RGB data.

In my professional work, another version of the code works on planar YUV frames (video).

**Comment by joncampbell123** [comment]
There's one basic idea in the code in that code duplication is reduced by very conservative use of C++ templates, and typedefs for pixels, and then specialization for MMX, SSE, and AVX.

**Comment by aybe** [comment]
I'm talking about Sai, Eagle, HQX etc ... style they give to a game is questionable, i.e. IMO nothing beats unfiltered stuff, except maybe those CRT shaders like Royale or a real CRT screen.

Looked at the rewrite and it looks promising, but it's even more puzzling : 

What are we supposed to do then ? Wait for it or continue improve this fork with a possibility of one day to make an expensive switch to it ?

I'd gladly help but i don't know DOS, ASM or advanced C++ stuff, I can only watch and see for the low-level stuff ... when I wrote that joystick patch I mostly used common sense and cppreference, i.e. I see myself a little further than novice in C++.

Actually what I know is C#, WPF, basic C++ and good programming practices (if there are any !).

**Comment by joncampbell123** [comment]
So far everything in dosbox-rewrite is just a mess of experimental code to test with.

**Comment by aybe** [comment]
Alright !

Hmmm ... i've been trying to track down that NumLock bug (if it's supposed to be) that forces to press the key twice to get it right, but failed miserably ! Problem is, there's a bunch of code that i'd happily prune and start from scratch, i.e. either a state synchronized with host or not but a dozen questions arises then, such as was it desired and so on.

What would really help is to know whether scratching parts is okay, for instance we could already clean out some of the code like D3D and so on. The other thing would be an overview of how DOSBox works, frankly I could figure it out with lots of time but a wiki of some sort would greatly help. Could you do that ? (unfortunately VS Code Map does not work for C++, even though it'd look like crazy)

Was going to ask about SDL2 but since you're talking about the rewrite, maybe for a first we could lay down some abstraction, refine it, then easily push the actual SDL, if that works then I guess it'll be good enough. These are merely some ideas, I think there really should be some FUTURE.MD like future direction, improvements and so on, but presented nicely in a small markdown file that gets to point without getting lost in too much details, i.e. try to get a bigger picture first.

What's your take on this ? Could this project be somehow cleaned with some abstraction or is the nature of it so anarchic that it won't fit or simply be a waste of time ?

**Comment by Jarvik7** [comment]
It sounds like it might be more practical to just start cleaning up the sections you're interested in (SDL2 port, removing DX, etc.) and make things more modular as you go along. A full rewrite is probably a long way off, and your cleaned sections will make it easier to structure the rewrite anyways.

**Comment by joncampbell123** [comment]
Agreed. Dosbox-rewrite is a fun sandbox to play around but a rewrite anytime soon is not practical. If anything in Dosbox-rewrite comes out as useful, I'll transplant it into DOSBox-X. The most likely candidate might be the "opcc" compiler that generates header files for you that decompose x86 opcodes.

**Comment by aybe** [comment]
Sorry, didn't have much time, had some today and made a few improvements for Windows, updated the TODO list in the mean time.

So, to make it clear,
Do you want to keep that surface/overlay for things like Raspberry Pi ?
Or is the future paved with only SDL2 and OpenGL along shaders ? (would be great, cleaner and easier)

**Comment by aybe** [comment]
Would be great if you guys could assist on the short term tasks in bold I've just added 🥇 I'll handle the dirty part of the work.

**Comment by joncampbell123** [comment]
Here's an issue that should be worked on long-term to reduce confusion when developing the codebase as well:

Long term cleanup: Too much code uses PhysPt for linear AND physical memory addresses #264

Contributers will make mistakes if the same datatype is used for both physical and virtual (linear) memory addresses.

**Comment by aybe** [comment]
Updated my post,

(I guess you can edit my post directly, because I was able to edit yours)

**Comment by aybe** [comment]
to ASM experts : is **MMX instruction set recompiler for core=dynamic #290** worth merging ?

**Comment by aybe** [comment]
I don't know if you received tons of updates from me, but I labeled all open issues, adding a few of them in the mean time ... now it is just easy to find all issues about a specific topic.

**Comment by joncampbell123** [comment]
@aybe I see that, thanks! It helps.

**Comment by joncampbell123** [comment]
@aybe I would like to see DOSBox-X develop with both software rendering (surface) and hardware (OpenGL) rendering. OpenGL is nice to have when a GPU is present (as it usually is), but on embedded systems or other systems where GPU rendering is not available, OpenGL becomes a lot SLOWER than software rendering code dedicated to the specific rendering task. I'm fine with OpenGL as a requirement when the user wants to use shader effects (like CRT bloom/scanlines) but not as a hard requirement to use DOSBox-X at all.

**Comment by joncampbell123** [comment]
@aybe as I demonstrate in the DOSBox-rewrite experiments, fast 2D bilinear scaling (without rotation) can be accomplished in software in C++ with some generics, especially if MMX/SSE/AVX extensions are available in the system. If scaling to correct the aspect ratio is needed by the user that code can do the trick just fine without OpenGL.

**Comment by sikthehedgehog** [comment]
Honestly, software rendering even without bilinear filtering would be fine by me - I'd see software rendering as a fallback in case hardware acceleration is not working correctly for whatever reason (conversely, I'd make OpenGL available only if it's guaranteed to be hardware accelerated).

Incidentally, if DOSBox-X gets ported to SDL2, you can just use the renderer API for the job, even let it automatically pick up whether it wants hardware acceleration or not. (if you want shaders you probably want to still handle OpenGL directly yourself, though... don't do the dumb thing of trying to touch OpenGL directly and using the renderer at the same time, that's not supposed to work)

**Comment by aybe** [comment]
Alright, that makes sense.

Since your scaler is still in an early stage, why don't try to integrate the concepts [PAR/SAR/DAR](https://en.wikipedia.org/wiki/Aspect_ratio_(image)#Distinctions) along integer/bilinear scaling, that would cover pretty much any desired output combination ?

We would then render on your scaler, then SDL or OpenGL would bit that in return, right ?

And about the scalers, you still want them in the non-accelerated output (i.e. rewrite them) ?

**Comment by joncampbell123** [comment]
Sure!

I think I can adapt the scalar to do line-wise rendering, MMX/SSE/AVX or not. It just has to be a bit more stateful when doing that.

The DAR is pretty easy: DOS for the most part assumes a 4:3 aspect ratio as if a traditional CRT monitor. dosbox.conf could specify an alternative aspect ratio (like 16:9) if desired.

**Comment by aybe** [comment]
Alright !

I wanted to look at SDL2 and looked at your master-sdl2 branch, but there are tons of errors and obviously does not compile. Is this branch any good or shall we restart from scratch ?

Also I was wondering why didn't you simply use the development package instead of the sources, practical reasons/more control ?

**Comment by aybe** [comment]
No point for me in rushing to code, so let's clarify some more SDL2-related stuff,

Looking at https://github.com/joncampbell123/dosbox-x/blob/master-sdl2/vs2015/sdl/include/SDL_version.h, it's still the old version or I missed something ?

Static linking or not ?
http://wiki.libsdl.org/Installation#Static_linking

This fork is up to date (automated)
https://github.com/spurious/SDL-mirror

I was thinking of the following,

Why not allow entire blocks of dosbox to be disabled/redirected to a null device ? We'd then be able to say, switch off sound, fix it, put it back on and so on. Or is dosbox life not as easy as that ?

Thing is, seeing hundreds to thousands of errors to fix in the project before it sees the light of the day (months) is likely to be depressing and pretty cheap IMO, hence my above idea.

This is pure speculation from me, so I'll wait for an informed advice.

**Comment by joncampbell123** [comment]
I've been able to compile the SDL2 branch in Linux just fine, though without working CD-ROM emulation. Are you trying to compile in Windows? If so, then yes, the SDL copy in the VS2015 branch is still SDL 1.x. You'll need to rip that out in the SDL2 branch and copy in SDL2 source code to get VS2015 to compile with SDL2.

**Comment by joncampbell123** [comment]
Long-term though, I think it would be better if the two branches slowly merged until the master branch could be ./configure'd to select either SDL1 or SDL2 and compile as such. The guys over at QEMU seem to have master that so far, though there's word of removing SDL 1.x support slowly.

**Comment by aybe** [comment]
Alright, I will take a look the branch and bring in SDL2.

**Comment by aybe** [comment]
Going to open a dedicated issue about SDL2 migration !

**Comment by aybe** [comment]
Here it is,

SDL2 migration #306

**Comment by joncampbell123** [comment]
I have merged code together to allow DOSBox-X to compile with either SDL 1.x or SDL 2.x.

Long term I intend to support both until about 2020 when SDL 1.x will be gradually deprecated.
