### ISSUE TITLE
Inaccuracies in the description of 486old in the wiki

### ISSUE THREAD

**Issue by skitt** [joncampbell123/dosbox-x#2861]
I was looking at the details of `CPU_ARCHTYPE_486OLD` v. `CPU_ARCHTYPE_486NEW` in the source code, and noticed that the implementation doesn’t match the [CPU settings in the wiki](https://dosbox-x.com/wiki/Guide%3ACPU-settings-in-DOSBox%E2%80%90X). Specifically, `CMPXCHG` throws an illegal opcode exception in `src/cpu/core_full/op.h` and `src/cpu/core_normal/prefix_66_0f.h` for anything older than `486NEW`, and `CPUID` is ignored in `src/cpu/cpu.cpp`.

**Comment by rderooy** [comment]
Thanks. I have updated the draft wiki, the main one should be updated in the next day or so.
https://github.com/wengier/dosbox-x-wiki/wiki/Guide%3ACPU-settings-in-DOSBox%E2%80%90X

**Comment by skitt** [comment]
Thanks for the quick fix!
