### ISSUE TITLE
Alien Trilogy asking for CD after installation, CD is in the drive

### ISSUE THREAD

**Issue by Zeether** [joncampbell123/dosbox-x#2869]
I am trying to get Alien Trilogy to work but every time I successfully install it to the C: drive and try to run it with TRILOGY.EXE it keeps saying "Please insert your Alien Trilogy CD into the drive." I have the game mounted properly with a BIN/CUE file, it will launch fine on normal DOSbox but not DOSbox-X for some reason.

**Comment by maron2000** [comment]
I installed it to C drive and mounted CD on D drive, and works flawlessly.
![alien](https://user-images.githubusercontent.com/68574602/131772199-eb54251f-04ac-4613-aa5e-8268431ca48c.png)

**Comment by Zeether** [comment]
That's odd, my iso isn't mounted like yours. It's just showing an empty drive for me.
![command_003](https://user-images.githubusercontent.com/8504728/131868936-4225fd7d-59ec-4d53-97c3-e424cabf87f8.png)

**Comment by Zeether** [comment]
Now I'm having this weird issue where the main menu doesn't show up, it just flashes ASCII garbage. I took a capture but it came out showing a strange image of the title screen.
![trilogy_000](https://user-images.githubusercontent.com/8504728/131931562-0807be25-cd12-459f-896c-a603f6465ae3.png)

**Comment by maron2000** [comment]
Very interesting. I can't reproduce that.
Are you using default settings?
The screenshots below is taken using DOSBox-x's feature. (Not using Alt+Print Screen)
![trilogy_000](https://user-images.githubusercontent.com/68574602/131950292-ddaae9be-e428-4d06-bbc7-8bba434b69c1.png)
![trilogy_001](https://user-images.githubusercontent.com/68574602/131950300-11409de1-bfbe-4cb2-ae4c-1cb959f20b12.png)

**Comment by Zeether** [comment]
I'm using default settings. The screen shows a bunch of ASCII characters flashing instead of the splash screen that shows the copyrights as well. I don't know what the deal is.

**Comment by maron2000** [comment]
I think this issue can be closed.
