### ISSUE TITLE
Boot Image not mounting (image geometry auto detection issue?)

### ISSUE THREAD

**Issue by divid3byzer0** [joncampbell123/dosbox-x#2871]
Just installed Dosbox-X 0.83.17 (SDL2, Windows 10) and my previous Windows 95 installation config file is not working anymore:

![image](https://user-images.githubusercontent.com/6065102/131811696-919a69a0-3ab6-4f9b-874c-e0c5c161d6aa.png)

The previous version worked without any issue with the same config file which has the following:

[autoexec]
IMGMOUNT C hdd.img
IMGMOUNT D cd.iso -ide 2m
BOOT C:

**Comment by divid3byzer0** [comment]
Nevermind, it wasn't a Dosbox problem.

**Comment by divid3byzer0** [comment]
Actually, I made a mistake, the issue seems to be Dosbox-X related.

I tried with the previous version, and it worked:

![image](https://user-images.githubusercontent.com/6065102/131817664-3bd30d98-c810-4b0b-837c-0c95057b6f6c.png)

**Comment by yxmline** [comment]
try imgmount 2 hdd.img -t hdd -fs none

**Comment by divid3byzer0** [comment]
> 
> 
> try imgmount 2 hdd.img -t hdd -fs none

That worked, thanks! Will have to change my configs then.

**Comment by blindphoneman** [comment]
I, also notice this problem.  It seems to occur with drives larger then 2 gigs.  Version is set to 7.10.

Here are the results of a trial command which previously worked in 0.8.3.16:

Z:\>imgmake test.img -t hd_8gig
Creating image file "test.img" with 1023 cylinders, 255 heads and 63 sectors

Z:\>imgmount c test.img
Image geometry auto detection: -size 512,63,255,1023
Cannot create drive from file.



Hope this helps.

**Comment by rderooy** [comment]
if mounting without driveletter works, I would suspect something with the filesystem code. If you mount without a drive letter, you will not be able to access the contents in dosbox-x, but you can still boot from it.

**Comment by blindphoneman** [comment]
Well, I thought it was just drives larger than 2 gigs, but, looks like it's having trouble autodetecting anything.

**Comment by rderooy** [comment]
Mounting a 8GB image seems to work fine here on 0.83.17

![command_000](https://user-images.githubusercontent.com/17701098/131882419-0d9981d5-307b-4fd7-b594-2ca184351dfe.png)

**Comment by rderooy** [comment]
Note that images larger then 2GB must be FAT32, which can only be mounted with DOS 7.1+ (or you need to set ``lfn=true`` in your config file).

Images smaller can be either FAT16 or FAT32 (within certain limits)

**Comment by rderooy** [comment]
Likewise mounting a 2GB FAT32 partition with Win98 also works fine here with 0.83.17.

If I know how to reproduce the issue which causes it to work with 0.83.16 but not with 0.83.17, I can do a "git bisect" on it to track down the offending commit.

**Comment by marcelofrau** [comment]
![image](https://user-images.githubusercontent.com/1341820/132363485-7666a51d-3215-4139-8790-43870cc838cd.png)

I am also facing this issue with the 0.83.17 version on windows, tried to use SDL2 version but I have the same results.. Is there a way to make this work? Perhaps I have something missing..

**Comment by blindphoneman** [comment]
Hi: I have not been too successful with mounting images in 0.8.3.17.  I went back to .16, for now. I know John has a lot of stuff going on right now, so, hopefully, he’ll get around to it eventually.

**Comment by rderooy** [comment]
@marcelofrau, @divid3byzer0  I'm wondering if it is because I'm using Linux and your using Windows.

**Comment by Allofich** [comment]
I can confirm the inability to mount an HDD image file, and bisected it down to this commit.
https://github.com/joncampbell123/dosbox-x/commit/6621f07ecad8798a1d311949eb61e85ed748ac39

I reproduced with the following setup:
VS2019 SDL1 build on Windows 10, 64-bit, for the above commit and all commits since that I tested, including the latest code (https://github.com/joncampbell123/dosbox-x/commit/844ff48ea3be4d8dfef84460a06e10ede34e2eef).

Download the hdd-256mb image from this site: https://sites.google.com/site/dotalshoff/games/dosbox and extract it.
Run DOSBox-X with no .conf file (default settings) and try to mount the extracted image like
IMGMOUNT c: "(path)hdd-256mb.img"

https://github.com/joncampbell123/dosbox-x/commit/6621f07ecad8798a1d311949eb61e85ed748ac39 and later fail with the message:

Image geometry auto detection: -size 512,63,16,520
Cannot create drive from file.

Commits earlier than https://github.com/joncampbell123/dosbox-x/commit/6621f07ecad8798a1d311949eb61e85ed748ac39 successfully mount.

@rderooy, can you try reproducing on Linux with the image and steps I wrote here?

**Comment by Allofich** [comment]
Strange, I compared the before and after of https://github.com/joncampbell123/dosbox-x/commit/6621f07ecad8798a1d311949eb61e85ed748ac39, and it looks like it was strictly a move of the code, with no modifications to the contents.

**Comment by marcelofrau** [comment]
> @marcelofrau, @divid3byzer0 I'm wondering if it is because I'm using Linux and your using Windows.

I'll try on Linux environment in a couple hours to check (don't have access right now), and will let you know. if you need any log, or test any scenario in particular, please let me know.

**Comment by Allofich** [comment]
When successfully mounting the image before https://github.com/joncampbell123/dosbox-x/commit/6621f07ecad8798a1d311949eb61e85ed748ac39, the log output is:

```
IDE: index 0 slave=0
Using partition 0 on drive (type 0x06); skipping 63 sectors
Mounted FAT volume is FAT16 with 65444 clusters
Mapping BIOS DISK C/H/S 520/16/63 as IDE 520/16/63
```

but when it fails in https://github.com/joncampbell123/dosbox-x/commit/6621f07ecad8798a1d311949eb61e85ed748ac39, the output is:

```
IDE: index 0 slave=0
Possibly invalid partition table in disk image.
Failed to read partition table
```

In the failing case, the function  `PartitionLoadMBR` is returning false for
```
if (smbr.magic1 != 0x55 || smbr.magic2 != 0xaa)
```

**Comment by rderooy** [comment]
@Allofich I have downloaded the 256 and 512mb image, and both mounts  just fine on Linux with 0.83.17

**Comment by Allofich** [comment]
@rderooy Thanks. So it would seem to be a Windows or MSVC problem.

**Comment by Allofich** [comment]
The problem seems to be caused by the `partTable` struct having been moved from `drives.h` to `bios_disk.h`, rather than the movement of the two functions.

**Comment by Allofich** [comment]
I noticed that in the original location in `drives.h`, there was a 
```
#ifdef _MSC_VER
#pragma pack (1)
#endif
```
before the `partTable` struct, and a
```
#ifdef _MSC_VER
#pragma pack ()
#endif
```
after it. Adding these before and after `partTable` in the new location in `bios_disk.h` appears to fix the issue, as I can mount the image file now.

**Comment by Allofich** [comment]
Simply moving the `#pragma pack(pop)` in `bios_disk.h` to be under the `partTable` struct also seems to fix the issue. I guess the `GCC_ATTRIBUTE(packed);` after the `partTable` struct allowed the Linux builds to work okay, but the MSVC builds needed the `#pragma pack` extended over the `partTable` struct's new location. I'll send a PR.

**Comment by blindphoneman** [comment]
Your post made me wonder, so I switched to a minGW build and I was able to mount images more reliably. However, even with ver set to 7.1, imgmake when asked to create an 8 gig drive, created a 4 gig one, so I guess I should put that under another issue.

**Comment by Allofich** [comment]
@blindphoneman, the problem with images not mounting is fixed, but what you said about imgmake may or may not be related. Please try the new code if you can, and if the imgmake problem still happens, create a new issue for it.

**Comment by rderooy** [comment]
Just want to report that I just build the latest code on Linux, and can still mount an image just fine.

**Comment by blindphoneman** [comment]
I must be dense, but, you mentioned new code that was just compiled.  I'm not too familiar with GitHub/GitLab, so, how do I find any new code before the next release?  Sorry for the newby question.

**Comment by rderooy** [comment]
If you go to the "Code" tab, the latest code is there. You would have to either install "git" tools to "clone" the repo, or download the latest code as an archive. You can then compile the code, assuming you have a compiler installed. There are instructions in the repository on how to compile the code for various platforms.

But a new version is normally released once a month at the beginning of the new month if you cannot compile it yourself.

**Comment by blindphoneman** [comment]
Ok, that's actually what I gathered, but, I just wasn't sure where to look. I'll run off and see if I can figure out how to get the proper VS build tools.

**Comment by Allofich** [comment]
@blindphoneman If you don't want to bother with setting up build tools, you can also download a build using the latest code from here https://ci.appveyor.com/project/Allofich/dosbox-x/builds/40714398/artifacts.
