### ISSUE TITLE
Adding MMX instructions to dynamic recompilator

### ISSUE THREAD

**Issue by wbcbz7** [joncampbell123/dosbox-x#288]
Hi all! :)

As far as I know, DOSBox-X does falling back to interpretator while executing MMX instructions when core=dynamic is used. Obviously, this approach leads to extremely slow performance while running MMX applications (such as [some late 90s DOS demos](https://demozoo.org/productions/tagged/needs-mmx/), Impulse Tracker, etc etc) comparing with regular integer/floating point instructions.

As dynrec is targeted to x86, it is possible (AFAIK again :) to dynamically recompile MMX code for native execution without performace (and probably compatibility) issues. So, there can be at least two approaches for recompiling MMX code:

- Drop-in recompilation
In this case, MMX instructions are placed to code cache blocks as-is (with address recalculations if needed), so they behaves just as if they are running under native x86 environment. This approach should not suffer from memory alighnment issues in most cases, but probably will lead to FPU save/restore issues (since an EMMS instruction will be required to return back to FPU mode)

- MMX to SSE2 recompilation
SSE2 supports integer operations hat are equivalent to MMX instructions but operating with wider registers (128 bit vs 64). Most SSE2 integer instructions shares their opcodes with their MMX equivalents, adding operand size prefix (0x66) before actual opcode (more info [here](http://ref.x86asm.net/coder32.html)), so conversions for most MMX instructions is pretty straightforward. As SSE2 regs won't collide with FPU stuff, there is no need to worry about FPU save/restore (yet again AFAIK =). However this approach will most likely lead to memory misalignment issues and therefore to performance drops/compatibility problems.

So, I tend to the first approach, since dynrec already has FPU save/restore logic and adding MMX instructions should be pretty safe.

Thanks in advance ;)

**Comment by joncampbell123** [comment]
Be aware that development primarily happens with the normal core, and that the dynamic core may have bitrotted at bit. It doesn't get any testing on my x86_64 dev system because it doesn't work there.
