### ISSUE TITLE
Mouse is unusable in PCJr mode

### ISSUE THREAD

**Issue by Jkapp76** [joncampbell123/dosbox-x#2882]
**Describe the bug**
Programs that use mouse in PCJr mode for me causes the mouse to be sluggish and the cursor glitches around the screen.

**To Reproduce**
I can get this result on both of my home PC's loading dosbox-x into a file manager like volkov commander or doszip. 

**Environment (please complete the following information):**
 - Operating system
 Windows 10
 - DOSBox-X release version or commit SHA1 this issue occurred on
 Last several versions of DOSBox-x

**Additional context**
I use volkov commander and doszip and the mouse can't be used in pcjr mode. works fine in cga mode and every other mode. I've tried changing several settings with no luck.

Update: mouse works with bard's tale games.

**Comment by Jkapp76** [comment]
The mouse cursor flashes around slowly like a slide-show. But if you're careful you can actually make it work, but it's pretty much unusable.

**Comment by joncampbell123** [comment]
Is this in general or only if the program is using the mouse with an interrupt callback function?

**Comment by Jkapp76** [comment]
I experimented a bit more.
I loaded Bard's Tale 2 and the mouse works good. Just doesn't work at start up with a file manager.
The graphics were garbled up on BT2 though if that matters.
Is there an alternate setting to get the mouse working with a file manager?

**Comment by joncampbell123** [comment]
If the program calls INT 33h to set an interrupt callback function, then mouse input will not work in some cases.

Currently those known cases are the Tandy, PCjr, and PC-98 machine types.

**Comment by Jkapp76** [comment]
Is there an alternate mouse driver or any way to get the mouse working in PCjr mode?
Mouse works with Tandy fine.

**Comment by joncampbell123** [comment]
DOSBox-X also supports serial mouse emulation. That doesn't work with interrupt mode yet either, but you might try disabling built-in INT 33h emulation and running CuteMouse or any other mouse driver that supports serial mice.

**Comment by Jkapp76** [comment]
Yes, using Ctmouse1.91 fixed the issue. (newer versions gave a message)

I now have my mouse working perfectly in PCJr mode. Thank you.
