### ISSUE TITLE
Cannot mount HDD image file anymore in version 0.83.17

### ISSUE THREAD

**Issue by piula** [joncampbell123/dosbox-x#2887]
I have a HDD image file and used to "imgmount x: x:\virtual\doslife.img" for mounting.

In version 0.83.17, mounting doesn't work anymore:

>Image geometry auto detection: -size 512,63,255,261
>Cannot create drive from file.

In the release notes, there is a short comment about "-bd" option added which I assume is the problem here. Unfortunately, this option is not documented (neither in "imgmount /?" nor in the wiki page) so I don't know how to mount this image now. I have already tried to add "-o partidx=1", but this doesn't work either.

Maybe @joncampbell123 or someone else can give me some hint. Thanks for helping!

**Comment by yxmline** [comment]
try imgmount 2: x:\virtual\doslife.img
see https://github.com/joncampbell123/dosbox-x/issues/2876

**Comment by piula** [comment]
This is working, but how can I assign a drive letter to the first partition then?

**Comment by rderooy** [comment]
> This is working, but how can I assign a drive letter to the first partition then?

You cannot. mounting with a drive number is only useful if your going to boot from it.
