### ISSUE TITLE
Can't get emm386 figured out to run Lemmings 2

### ISSUE THREAD

**Issue by Jkapp76** [joncampbell123/dosbox-x#2895]
**Please describe your question.**
I can't get "Lemmings 2 Tribes" to work on DOSBox-x
All of the other DOSBox versions fail as well, but I change the ems from true to emm386 and the others will work. I would like help getting this to work on DOSBox-x.

**Comment by rderooy** [comment]
what is the error? Is it something like "Can't open L2"?

If so, if the game is in ``c:\dosroot\lemm2`` you need to ``mount c c:\dosroot``, then you can ``cd lemm2`` and start the game. Lemmings 2 can apparently not be in the root of the emulated HDD. Some other games have this issue also.

**Comment by grapeli** [comment]
@Jkapp76 
Turn off hma.

Directly `dosbox-x -set "dos hma=false"`
or in a configuration file.
```
[dos]
hma  = false
```

**Comment by Jkapp76** [comment]
@grapeli 
I set hma to false. no luck
I also set hma to false and changed through every ems option within the conf file. Every option crashes with the same exact graphical mess on the screen.

Lemm2 is a folder within my mounted "Games" folder. 

Every other dosbox build does this same thing with ems set to true, but is fixed by setting ems to emm386. I wonder if there's a bug?

**Comment by grapeli** [comment]
@Jkapp76 
I downloaded the game from [here](https://the-eye.eu/public/Games/eXo/eXoDOS_v5/eXo/eXoDOS/Lemmings 2 - The Tribes (1993).zip) and checked it.
With `hma=true` it does not start
With `hma=false` works fine.

https://user-images.githubusercontent.com/452325/132704842-0641c784-4645-4a16-9e01-971ff73917d7.mp4

**Comment by Jkapp76** [comment]
Got it working. Thanks for the direction.
