### ISSUE TITLE
Won't mount harddrive images in DOSBox-x 0.83.17

### ISSUE THREAD

**Issue by RootUserSam** [joncampbell123/dosbox-x#2906]
**Describe the bug**
When I try to use imgmount to mount a hard drive image (example: freedos.img), it won't let me mount that image. I was using DOSBox-X 0.83.17. I am now using 0.83.16.

**To Reproduce**
imgmount c freedos.img

**Expected behavior**
I expected the program to mount the image.

**Screenshots**

**Environment (please complete the following information):**
 - Operating system=DOS 7.1
 - DOSBox-X release version or commit SHA1 this issue occurred on= 0.83.17
 - Used configuration freedos.conf
[freedos.zip](https://github.com/joncampbell123/dosbox-x/files/7150371/freedos.zip)
I have attached the conf file by zipping it.

**Additional context**

**Comment by Allofich** [comment]
I assume you're running a Windows release, as this issue exists on Windows releases in 0.83.17. It has since been fixed. Here is a build (SDL1 version) using the latest code:
https://ci.appveyor.com/project/Allofich/dosbox-x/builds/40714398/artifacts (shader files aren't included)

**Comment by Allofich** [comment]
This can be closed now. I think there may be a couple other still-open issues about this as a number of people reported it during 0.83.17.
