### ISSUE TITLE
DOSBox-X v0.83.17 crashes when printing from Windows for Workgroups

### ISSUE THREAD

**Issue by foontydos** [joncampbell123/dosbox-x#2908]
DOSBox-X v0.83.17 64-bit SDL2 crashes (DOSBox window suddenly disappears) when I try to print a document within Windows for Workgroups.

1. Startup DOSBox-X, run Windows for Workgroups.
2. Accessories group, Write, Open mail.wri
3. Click on File, Print
4. After a short delay, the DOSBox window disappears.  There is no output.

The DOSBox-X printer emulator works fine when printing from WFW in version v.083.13 but not in later versions.  It would output to the the printer or to a  PNG file depending on configuration setting.

Environment:
 - Windows 10 Pro
 - DOSBox-X v0.83.17 64-bit SDL2
 - Windows for Workgroups 3.11
 - Epson Generic 24-Pin Printer Driver v1.1dE (downloaded from epson.com, installed in Windows for Workgroups)
 
Changes made to dosbox-x.conf`:
 - fullscreen=false
 - fulldouble=true
 - fullresolution=desktop
 - windows resolution=original
 - output=direct3d
 - aspect=true
 - printoutput=png
 
Also, the DOSBox-X printer emulator (v.0.83.17) seems to work fine when printing from the DOS prompt and from DOS programs.

**Comment by Allofich** [comment]
Does the crash also happen with SDL1? Do you remember if the v.083.13 that worked was SDL1 or SDL2?

**Comment by foontydos** [comment]
> Does the crash also happen with SDL1? Do you remember if the v.083.13 that worked was SDL1 or SDL2?

Worked with DOSBox-X v0.83.13 64-bit SDL2.  It have not used SDL1 in a long time--I'll try v0.83.17 64-bit SDL1 to see what happens.

**Comment by foontydos** [comment]
> > Does the crash also happen with SDL1? Do you remember if the v.083.13 that worked was SDL1 or SDL2?
> 
> Worked with DOSBox-X v0.83.13 64-bit SDL2. It have not used SDL1 in a long time--I'll try v0.83.17 64-bit SDL1 to see what happens.

I did some testing:
 - Printing from Windows for Workgroups works with DOSBox-X v0.83.13 SDL1 and SDL2.
 - Printing from Windows for Workgroups does not work with DOSBox-X v0.83.17 SDL1 and SDL2.

**Comment by Wengier** [comment]
Not sure if this issue is the same as issue #3040. If so, it is already fixed by @jamesbond3142.

**Comment by foontydos** [comment]
Similar to issue #3040 except I am running the Windows platform DOSBox-X (Windows 10).
In addition, I tried DOSBox-X v0.83.18 and v0.83.19--printing from the DOS prompt also does not work.  For example, I type in "DIR > LPT1" and then DOSBox-X freezes.  I'm using the same DOSBox-X configuration I mentioned in my original comment.

**Comment by Wengier** [comment]
@foontydos The command `DIR>LPT1` works for me, but you may need to manually send a form-feed before the printing starts (see "DOS" menu => "Send form-feed"). Also, please check your settings of the config options "parallel1" (in [parallel] section) and "printoutput" (in [printer] section) to see if they are correctly set. Last but not the least, please try the updated DOSBox-X binary below (with fix in #3040 applied) to see if there is any change:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Hope this helps.

**Comment by foontydos** [comment]
I tried the updated the DOSBox-X Windows SDL1 binary (dosbox-x-update.zip).  Printing from the DOS prompt now works.  Also, printing from within Windows for Workgroup also works.  Thanks!

**Comment by Wengier** [comment]
@foontydos Thanks for the confirmation. Closing.
