### ISSUE TITLE
Have a CHANGELOG to keep track of changes

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#292]
Ideally, one would take one minute updating it for each change they add/remove etc, we'd then know what's in that distribution.

For the current changes as of today, I might be able to spot a few ones, but not all of them in that spaghetti code.

EDIT

actually there is one @ https://github.com/joncampbell123/dosbox-x/blob/master/ChangeLog
but it's from the original dosbox :)

**Comment by joncampbell123** [comment]
I agree. Will do. It will be easier to read than the Git commit log.

**Comment by aybe** [comment]
Definitely, I will, too :)
