### ISSUE TITLE
autoexec commands are executed after a given program exits.

### ISSUE THREAD

**Issue by crocket** [joncampbell123/dosbox-x#2925]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Gentoo Linux

### What version(s) of DOSBox-X have this bug?

0.83.17

### Describe the bug

~/.config/dosbox-x/dosbox-x-0.38.17.conf

```
...

[autoexec]
mixer master 30
```

If I execute `dosbox-x -userconf something.exe`, `mixer master 30` is executed after something.exe exits.

Thus, `mixer master 30` fails to lower volume while the program is running.

### Steps to reproduce the behaviour

1. Put `mixer master 30` in `autoexec` section of a configuration file.
2. Execute `dosbox-x something.exe`

**Comment by Wengier** [comment]
Closing as the documentation has been updated accordingly.
