### ISSUE TITLE
if i mount Drive 0 or 1 as Floppy Drive, DOSBOX-X won't allow me to "Change Current Floppy Image"

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#2942]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 Version 21H1 Home Single Language x64

### Relevant hardware info

no

### What version(s) of DOSBox-X have this bug?

0.83.16

### Describe the bug

When i make a blank Floppy image, without any fs and mount it as drive 0 or 1, trying to "Change Current Floppy Image" says "No Floppy Drive is currently available"

### Expected behavior

expected to change floppy image

### Steps to reproduce the behaviour

1.open dosbox-x
2.imgmake floppy.img -t fd_1440 -nofs
3.imgmount 0 floppy.img
4.Go to "DOS" and click "Change Current Floppy Image"
5.See Error "No Floppy Drive is currently available"

### Used configuration

```ini
link :https://github.com/joncampbell123/dosbox-x/files/7166857/conf.txt
```

**Comment by Wengier** [comment]
It is supported now, so closing.

**Comment by Siddhant-M3** [comment]
still doesn't work 
![image](https://user-images.githubusercontent.com/94912008/143075853-9f7873e6-7e52-42b6-a720-dc197809fad0.png)

**Comment by Wengier** [comment]
@Siddhant-M3 It should work in the development code of DOSBox-X 0.83.20 instead of DOSBox-X 0.83.19 release version. Please try the latest Windows builds below for it:

* Windows SDL1: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)
