### ISSUE TITLE
screenshot is always 24-bit, regardless of video mode

### ISSUE THREAD

**Issue by FyiurAmron** [joncampbell123/dosbox-x#2955]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 7 64-bit (any)

### What version(s) of DOSBox-X have this bug?

dosbox-x-mingw-win64-20210901044459

### Describe the bug

Vanilla DOSBox captures output from palettized modes to an 8-bit palettized PNG, allowing easy reverse-engineering the palettes themselves, without a need to debug INT 10h calls etc. I tried many combinations (e.g. normal/SDLDraw/2/Lowend, OpenGL vs DirectX vs surface, no scaler, different scalers etc.) and only got 24-bit PNGs as an output, for whatever reason.

### Expected behavior

either act like vanilla and produce a PNG matching current video mode (i.e. palletized 8-bit in palletized VGA 256 colour modes, 24-bit in True Color/VESA modes etc.), or be able to set it via a conf option.

### Steps to reproduce the behaviour

1. Launch any game/app in palletized 256-colour VGA mode,
2. Capture a screenshot :)

### Used configuration

Many :)

**Comment by joncampbell123** [comment]
VGA emulation will always render to 24-bit. While normally 256 colors are used at once, palette changes mid frame are possible.

EGA and CGA emulation will always render to 8-bit 256-color because those standards cannot make more than 16 (CGA) or 64 (EGA). Composite CGA is rendered using an algorithm inherited from SVN that also uses 8-bit 256-color SDL output as far as I know.

**Comment by joncampbell123** [comment]
I am however open to the idea of adding an option to select whether the screenshot and video capture functions could just take the 256-color display (video memory and palette) and capture it as-is.

Perhaps the code responsible for rendering VGA could also copy the video memory it rendered to another off-screen buffer for the screen capture to use, along with storing the VGA palette some small offset after the end of vertical blanking.

AVI capture could use the same offscreen buffer as well, and ZMBV would encode the palette for the frame for palette changes.

Here's a bit of a problem of course: It's not just the color palette and display data in memory that determine what colors are shown. There is also DAC mask and the attribute controller that remap colors as well (yes, even in 256-color mode!). That circuitry that exists for register-level backwards compatibility with EGA doesn't magically go away for VGA modes, though it is generally true that EGA/VGA bitplanar stuff *does* magically disappear in SVGA modes.

**Comment by BridgeHeadland** [comment]
![image](https://user-images.githubusercontent.com/85258509/166685462-b14a1a20-d5a5-419b-be61-d725f743bb5c.png)
I do not think I fully understand this here, but are there such things that make you get incorrect colors in DOSBox, which are almost correct, as in this picture here, if you understand?

**Comment by BridgeHeadland** [comment]
> ![image](https://user-images.githubusercontent.com/85258509/166685462-b14a1a20-d5a5-419b-be61-d725f743bb5c.png) I do not think I fully understand this here, but are there such things that make you get incorrect colors in DOSBox, which are almost correct, as in this picture here, if you understand?

For those of you who do not see it: The picture is a little darker than it really is, and the light colors have a slightly lower saturation as well.

**Comment by BridgeHeadland** [comment]
> > ![image](https://user-images.githubusercontent.com/85258509/166685462-b14a1a20-d5a5-419b-be61-d725f743bb5c.png) I do not think I fully understand this here, but are there such things that make you get incorrect colors in DOSBox, which are almost correct, as in this picture here, if you understand?
> 
> For those of you who do not see it: The picture is a little darker than it really is, and the light colors have a slightly lower saturation as well.


Can anyone please answer this? I'm so confused!

**Comment by maron2000** [comment]
Indeed there are slight color differences compared to Dosbox-Staging.
The scaling of 18bits(6bits x 3colors) to 24bits is different.
As far as I see the code, Dosbox-x shifts 2bits? but it may result in compressing dynamic range.

**Comment by BridgeHeadland** [comment]
> Indeed there are slight color differences compared to Dosbox-Staging. The scaling of 18bits(6bits x 3colors) to 24bits is different. As far as I see the code, Dosbox-x shifts 2bits? but it may result in compressing dynamic range.

Any way to fix it?

**Comment by BridgeHeadland** [comment]
> > Det er faktisk små fargeforskjeller sammenlignet med Dosbox-Staging. Skaleringen av 18bits (6bits x 3colors) til 24bits er forskjellig. Så vidt jeg ser koden, skifter Dosbox-x 2bits? men det kan resultere i komprimering av dynamisk område.
> 
> Noen måte å fikse det på?

Or was the explanation not meant for me?

**Comment by BridgeHeadland** [comment]
> > > Det er faktisk små fargeforskjeller sammenlignet med Dosbox-Staging. Skaleringen av 18bits (6bits x 3colors) til 24bits er forskjellig. Så vidt jeg ser koden, skifter Dosbox-x 2bits? men det kan resultere i komprimering av dynamisk område.
> > 
> > 
> > Noen måte å fikse det på?
> 
> Eller var ikke forklaringen ment for meg?

ANYBODY HOME?

**Comment by maron2000** [comment]
Well, thank you for your polite comment
I was busy so don't make me rush.
I am not a teacher so you will have to google or at least read the previous comments in this thread.
I will never respond to you any more.

**Comment by Jookia** [comment]
@BridgeHeadland could you try an older version and see if that fixes it?

**Comment by BridgeHeadland** [comment]
@Jookia I do not think it matters which version of DOSBox-X I use, I even tested it with DOSBox SVN Daum, and the result will be the same, so I do not think the fault lies in the DOSBox. I have researched a bit, and it seems that the original CGA/EGA color palette has been replaced with the 16 VGA colors (which were used in Wolfenstein 3D, among other things), which are almost identical to the CGA/EGA palette, but not 100%, except black then. I discovered the color error when I got the new SDD for the PC, I reckon it has something to do with it.

**Comment by Jookia** [comment]
So is this error on your physical hardware?

**Comment by BridgeHeadland** [comment]
@Jookia I think so.

**Comment by joncampbell123** [comment]
Coming back to this issue, a command was added to take a "raw" snapshot of the video mode. That means one that matches the color palette and pixel data of the source (or as close as possible).

To clarify: The normal snapshot will output whatever the rendering code does, which is always 24bpp for VGA, and the "raw" snapshot will use only the number of colors and the color palette of the source.
