### ISSUE TITLE
Request: Support for running Windows 2.x/386 in 386 Mode 

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2957]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

yes, see #2954 

### What you want

support for Windows 2.x/386 in 386 Mode, Windows boots but mouse never works in 386 mode

**Comment by rderooy** [comment]
Is it really necessary to open a second issue for the same problem?
