### ISSUE TITLE
Stuttering voices and glitching graphics in _Freddy Pharkas: Frontier Pharmacist_

### ISSUE THREAD

**Issue by jlancaster86** [joncampbell123/dosbox-x#2960]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 21H1

### What version(s) of DOSBox-X have this bug?

0.83.17 (SDL1, 64-bit)

### Describe the bug

All character speech stutters and graphics sometimes glitch around characters' mouths and the menus.

Capture: https://youtu.be/7w7mr5frriQ

### Steps to reproduce the behaviour

Click "play" and listen to the opening dialogue.

### Used configuration

```ini
sbtype = sb16
```

### Additional context

_No response
[dosbox-x.conf.txt](https://github.com/joncampbell123/dosbox-x/files/7274795/dosbox-x.conf.txt)
_

**Comment by grapeli** [comment]
Regarding the sound. The correct configuration for this game is `sbtype=sbpro2`.
https://en.wikipedia.org/wiki/Sound_Blaster_16#Reception

What is the purpose of pasting the entire configuration file including comments? 
-Present only the one that differs from the default.
-Attach the configuration file, those interested will download it.

**Comment by jlancaster86** [comment]
> What is the purpose of pasting the entire configuration file including comments? -Present only the one that differs from the default. -Attach the configuration file, those interested will download it.

Fair point—I guess I was confused by the bug report form. I've edited the original post to make it easier to read.

> Regarding the sound. The correct configuration for this game is `sbtype=sbpro2`. https://en.wikipedia.org/wiki/Sound_Blaster_16#Reception

Switching to SBPro2 does fix the stuttering voices, but the game explicitly supports SB16 (and it works in vanilla DOSBox). The graphical issues are also still present.

**Comment by joncampbell123** [comment]
It's kind of hard to tell exactly but the back of the box according to these screenshots only mentions Sound Blaster, not Sound Blaster 16.

It may rely on Sound Blaster Pro quirks that don't exist on Sound Blaster 16.

In any case, I purchased the GOG.COM version for testing.

https://www.mobygames.com/game/dos/freddy-pharkas-frontier-pharmacist/cover-art

**Comment by grapeli** [comment]
@jlancaster86 
Regarding these graphical glitches, they also appear in dosbox-SVN. Sample screenshots (dosbox-SVN).

![out1577](https://user-images.githubusercontent.com/452325/136010683-1bb7e7df-b970-423b-88c7-eecbe352843c.png)
![out1696](https://user-images.githubusercontent.com/452325/136010704-e889d5e7-b72b-4065-bdf9-5053375b14db.png)
![out2103](https://user-images.githubusercontent.com/452325/136010715-9234ccc4-d18f-45bb-8b1b-efc98fe8f97c.png)

I don't notice them when I turn them on normally. I notice them at the time of frame-by-frame playback of the ripped video.
Youtube resources are full of them. Two examples.
https://www.youtube.com/watch?v=xcUZh0BZQSQ  (3:54)
https://www.youtube.com/watch?v=CrZZAJjXndY  (4:40)

"Unchained tearlines" - very similar to those in this [thread](https://github.com/joncampbell123/dosbox-x/issues/1809#issuecomment-840691428). Certainly difficult to eliminate. Maybe through the right choice of configuration (although I doubt it).

**Comment by Allofich** [comment]
This and https://github.com/joncampbell123/dosbox-x/issues/2909 seem like they may be related.

**Comment by grapeli** [comment]
The difference between 8-bit sampling and 16-bit sampling is audible.
You can hear distortions (vertical lines on the spectrogram).
Noise level difference (dosbox-staging sbpro2 vs sb16).

01-dosbox-staging-sbpro2
![01-dosbox-staging-sbpro2](https://user-images.githubusercontent.com/452325/136611160-6c7fdc97-7f8e-4fd3-8218-e0a63fd74743.png)
[01-dosbox-staging-sbpro2.flac.txt](https://github.com/joncampbell123/dosbox-x/files/7313564/01-dosbox-staging-sbpro2.flac.txt)

02-dosbox-staging-sb16
![02-dosbox-staging-sb16](https://user-images.githubusercontent.com/452325/136611216-9a3c244c-3da6-4081-8a4e-4bf6593cb49f.png)
[02-dosbox-staging-sb16.flac.txt](https://github.com/joncampbell123/dosbox-x/files/7313570/02-dosbox-staging-sb16.flac.txt)

03-dosbox-x-sbpro2
![03-dosbox-x-sbpro2](https://user-images.githubusercontent.com/452325/136611255-67c6a79f-9383-4363-9db0-439a8c0262c6.png)
[03-dosbox-x-sbpro2.flac.txt](https://github.com/joncampbell123/dosbox-x/files/7313575/03-dosbox-x-sbpro2.flac.txt)

https://github.com/dosbox-staging/dosbox-staging/wiki/Games%2Dthat%2Dplay%2D16%2Dbit%2Daudio
https://nerdlypleasures.blogspot.com/2011/06/
http://www.sierrahelp.com/Patches-Updates/Patches-Updates-Misc/UpdatedSoundCardDrivers.html

**Comment by grapeli** [comment]
Works great under ScummVM.

https://user-images.githubusercontent.com/452325/136713568-764df945-6932-4b1d-9a6a-a37b4c3f107d.mp4

**Comment by joncampbell123** [comment]
Latest commit fixes stuttering with sbtype=sb16. The game changes DSP block size for the spoken dialogue using DSP command 0x48, and that DSP command is supposed to accept the block size in BYTES which DOSBox-X assigned as SAMPLES. The game uses 16-bit PCM mono when playing to sbtype=sb16, so this means the DSP block size per IRQ was being emulated as if twice as much as the game intended.
