### ISSUE TITLE
DBCS codepage is not set properly

### ISSUE THREAD

**Issue by 1abcd** [joncampbell123/dosbox-x#2975]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Win7 (6.1.7601)

### What version(s) of DOSBox-X have this bug?

0.83.16-0.83.18

### Describe the bug

Problem A:
If reset VM or re-dos, some menu items become a mess. (language=zh_TW; dosv=tw)
<img width="645" alt="未命名" src="https://user-images.githubusercontent.com/1331388/137040039-d9812ad7-94b0-4991-8726-d13f7032edde.png">

Problem B:
If I change the language from menu item "Restart DOSBOX-X with language file...", it will not set codepage properly. This makes me need to spend more time to change dosv or counrty option.
<img width="373" alt="未命名" src="https://user-images.githubusercontent.com/1331388/137041687-c155d578-b0df-4fc3-b7ec-d41a7dab1e82.png">

### Steps to reproduce the behaviour

Problem A:
Choose "Reset virtual machine" or "Reboot guest system" from Main menu.

Problem B:
Choose "Restart DOSBOX-X with language file..." and select any DBCS language file.

**Comment by 1abcd** [comment]
@Wengier 不好意思 我又看到了新問題

-lang 的參數會修改 language 選項並執行 dosbox-x，從主選單選擇重開執行個體，dosbox-x 會將修改的設定儲存和載入和刪除。

-langcp 的參數也是會修改 language 選項，但從主選單選擇重開執行個體，結果為亂碼，我觀察到的是 codepage 沒有一起修改和儲存。

**Comment by Wengier** [comment]
@1abcd Fixed，应该已修正，谢谢告知。可以再试试看我发的更新版下载连结（内容已更新）。
