### ISSUE TITLE
Why does DOSBox-X detect CHS 2030/16/63 as 1015/32/63 ?

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#3019]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

if image file has more than 1024 cylinders, like CHS 2030/16/63, why does it change the value of heads to 32 and cylinders to 1015. instead of using CHS 2030,16,63 , it uses 1015,32,63 , why? 
mounting image file with imgmount `IMGMOUNT C HDD.IMG -size 512,63,16,2030` gives error `Cannot Create Drive From File`

**Comment by Siddhant-Mashalkar** [comment]
also , why isn't it possible to use sector size 2048 bytes or 4096 bytes instead of 512? will it be possible?

**Comment by rderooy** [comment]
Because disks were overwhelmingly (almost exclusively) 512 bytes/sector. The only exception I encountered back in the day were 500 bytes/sector option for AS400 disks.

4KB/sector is something quite new and not applicable to DOS emulation.
