### ISSUE TITLE
Regression between 0.83.6 and 0.83.7 in terms of Performance

### ISSUE THREAD

**Issue by egrath** [joncampbell123/dosbox-x#3023]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 8.1 and Windows 10

### What version(s) of DOSBox-X have this bug?

0.83.7

### Describe the bug

There seems to have some regression between 0.83.6 and 0.83.7 introduced, in Terms of performance. I use DERIVE 4.1 regulary and noticed a significant performance drop when switched to 0.83.7 - the impact is so noticeable, you can even watch the screen building up.

The issue happens no matter if the MinGW or Visual Studio built version is used. 

### Expected behavior

Performance on par with 0.83.6

### Steps to reproduce the behaviour

1. Install DERIVE 4.1
2. Run with 0.83.6 and work a little bit with it, something like plotting a graph
3. Run with 0.83.7 and also work a little bit with it. Notice the performance drop

### Used configuration

```ini
[dosbox]
machine=svga_s3
#machine=svga_et4000
vmemsizekb=2
memsize=4

[sdl]
output=openglnb
fullscreen=false
fulldouble=true
fullresolution=1920x1080
windowresolution=1280x960
windowposition=8,32
autolock=false
usescancodes=true
showmenu=false
priority=higher,pause

[render]
scaler=normal2x forced
aspect=false

[cpu]
core=dynamic

# matches pentium 133 mhz
cputype=pentium
cycles=fixed 72000

# matches pentium 60
#cputype=pentium
#cycles=fixed 32000

# matches 386DX/33
#cputype=386
#cycles=fixed 7800

apmbios=true

[ne2000]
ne2000=true
nicbase=300
nicirq=3
#realnic=list
realnic=3

[mixer] 
#nosound=false
nosound=true 
swapstereo=false 
rate=44100 
blocksize=1024 
prebuffer=12 

[sblaster] 
sbtype=sbpro1
sbbase=220 
irq=7
dma=1 
hdma=3 
sbmixer=true 
oplmode=auto 
oplemu=default 
oplrate=44100 
hardwarebase=220 

[dos]
xms=true
ems=true
umb=true
keyboardlayout=gr

#[pci]
#voodoo=opengl

[autoexec] 
@echo off
cls
mount c: DOS_C
keyb gr 437
loadfix
path z:\;c:\brief;C:\tools;C:\pockd;C:\CW4
set bpath=;c:\brief\macros
set bhelp=c:\brief\help
set bflags=-i120k1rtz -mAA
C:
cd \DERIVE
DERIVE
```

**Comment by Wengier** [comment]
DOSBox-X 0.83.7 added support for the dynamic_x86 core. It is generally noticeably faster than the dynamic_rec core, and as a result ``core=dynamic`` defaults to dynamic_x86 instead of the dynamic_rec core in 0.83.7. But it may be possible that the result is opposite for certain programs. Try set ``core=dynamic_rec" in the config to use the old dynamic_rec core as in 0.83.6.

**Comment by egrath** [comment]
Thank you very much, setting `core=dynamic_rec` solved the issue and restored performance with DERIVE to the state before.
