### ISSUE TITLE
80x25 command does nothing until after you run MODE CON LINES=25 once

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#3027]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 (64-bit latest updates)

### What version(s) of DOSBox-X have this bug?

SDL1 Visual Studio, code, built from 1e3d36a

### Describe the bug

Z:\TEXTUTL\80x25 has no effect when you start DOSBox-X with this conf file:

```
[sdl]
output = ttf
[ttf]
lins = 43
```
However, if you run this command to switch to 25-line mode:

`mode con lines=25`

and then this command to go back to 43-line mode:

`mode con lines=43`

after this, the Z:\TEXTUTIL\80x25 command correctly switches back to 25-line mode.

It seems as if at least 25-line mode has to be forced by MODE before the 80x25 command works correctly. I have no idea of why!

### Expected behavior

The 80x25 command should switch to 25-line mode without doing anything else first.

### Steps to reproduce the behaviour

See above.

### Used configuration

```
[sdl]
output = ttf
[ttf]
lins = 43
```

**Comment by joncampbell123** [comment]
Anyone wishing to submit more bug fixes: Go ahead and do some more bug fixes today up until midnight tonight, I'll be busy with Halloween, friends and family tonight. I'll start the build tomorrow morning.

**Comment by Wengier** [comment]
I think I had fixed it already - by using the builtin functions for 80x25, 80x43, etc, for better compatibility with TTF output. The MODE command without a parameter will show the current screen dimension.

**Comment by emendelson** [comment]
Yes, this is fixed now. Thank you, @Wengier
