### ISSUE TITLE
"Failed to mount the PhysFS drive" after installing win98 according to wiki

### ISSUE THREAD

**Issue by keenerb** [joncampbell123/dosbox-x#3029]
I've followed the win98 installation instruction according to wiki and after the final setup and reboot I'm unable to mount the hard drive file.

It seems to be a valid image file still, I can browse it with 7zip and other utilities, but "mount c win98.img" returns the error "Failed to mount the PhysFS drive" even though it's worked many times during the install.

Where should I start investigating this?

Debugger shows

PHYSFS couldn't mount 'win98.img': unsupported                                  PHYSFS calling PHYSFS_deinit()                 

I've tried running as administrator.

**Comment by keenerb** [comment]
I can't mount disk images that I am creating inside the same session, either...

![image](https://user-images.githubusercontent.com/1183671/139707829-048ec655-6a18-45aa-a92d-d544c48163c0.png)

**Comment by keenerb** [comment]
[test.zip](https://github.com/joncampbell123/dosbox-x/files/7454864/test.zip)
Here is a test hard disk image I created, using "imgmake test.img -t hd_250"

Running 0.83.18 64-bit on WIndows 10 64-bit.  This all worked perfectly well yesterday morning!  I've uninstalled and re-installed Dosbox-X as well.

**Comment by Wengier** [comment]
Have you tried to mount the image with `IMGMOUNT`, instead of `MOUNT`? The latter is for mounting directories,  not disk images.

**Comment by keenerb** [comment]
Oops.

You can close this ticket now.  I guess I forgot imgmount vs. mount while I was sleeping last night...
