### ISSUE TITLE
mount issue (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by aroaas** [joncampbell123/dosbox-x#3030]
DOSBox 0.74-3 and DOSBox-X 0.83.19 does not behave similar when mounting directories on mounted partition (/dev/sda2).
DOSBox-X says directory does not exists, DOSBox mounts without problem. Any idea why?
![Screenshot-20211102111605-1734x578](https://user-images.githubusercontent.com/60800447/139830254-98cb3619-967b-4cce-9ca5-3759582b8a2d.png)

**Comment by rderooy** [comment]
Are you using the flatpak version? If so, it is running in a sandbox and does not have access to the whole filesystem, only to /home

**Comment by aroaas** [comment]
Yes I am. Thank you for simple but important information :-)
