### ISSUE TITLE
[PC-9821] "Fit to aspect ratio" enforces 4:3 instead of 16:10

### ISSUE THREAD

**Issue by spaztron64** [joncampbell123/dosbox-x#3032]
### Code of Conduct & Contributing Guidelines

- [x] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 7 x64, Windows 10 x64 1607

### What version(s) of DOSBox-X have this bug?

DOSBox-X 0.83.19

### Describe the bug

Unlike graphics standards made for IBM PC compatibles, designed to stretch 320x200 to a 4:3 display, NEC PC-98 machines were designed to display a 640x400 image at it's native 16:10 aspect ratio. 
Turning off "Fit to aspect ratio" leads to the image being stretched on other types of displays in fullscreen mode.

### Expected behavior

How the image should look like:
https://i.imgur.com/U450H0T.png

How the image actually looks like with "Fit to aspect ratio" enabled:
https://i.imgur.com/ZzG7rtS.png

### Steps to reproduce the behaviour

1. Make sure to be using machine=pc9821
2. Go to "Video"
3. Click "Fit to aspect ratio"

**Comment by joncampbell123** [comment]
I was not aware of that... but I suppose a square pixel aspect ratio helped many game developers.

**Comment by maron2000** [comment]
There were debates, but pixel aspect ratio of PC-98 is concluded to be square, since the circle drawn by Graphic BIOS assumes square pixel.
Many people were confused since aspect ratio of CRT monitors were 4:3, and in many cases the screen were stretched to fit the monitor.
Pixels of laptops with 640x400 screen are indeed square.

**Comment by joncampbell123** [comment]
Many programs on the IBM PC drew circles as if square pixels too, but most of the INT 10h modes are anything but.

Laptops of course are going to distort the image like that. Video hardware in the 1990s did not support scaling the image to fit the screen, or if it did (late 1990s) it was often nearest neighbor scaling that looked like crap (my 1997 Toshiba laptop with a Chips and Tech SVGA chipset does that). So if the screen was smaller than the LCD, it often just centered the image with a larger black border.

I'm concerned with how PC-98 CRT monitors displayed the image (prior to changing the connector to VGA). Did they show it as 16:10 or 4:3?

**Comment by spaztron64** [comment]
On 24kHz compatible displays of the time, always as 16:10.

Examples:
https://imgur.com/a/qLQFecK

**Comment by joncampbell123** [comment]
I see. What do these monitors do with the image on later systems when the video mode is switched to 640x480?

**Comment by spaztron64** [comment]
Someone I know has tested on a Tri-sync monitor:
-640x480 @ 31kHz Hsync is displayed fullscreen
-640x480 @ 24kHz Hsync is letterboxed

**Comment by spaztron64** [comment]
Sorry, I accidentally closed.

**Comment by joncampbell123** [comment]
Thank you. I want to clarify I do not mean 640x480 when a separate Cirrus or S3 SVGA chipset is initiated by Windows, I mean when the PC-98 video hardware is switched by the BIOS to 640x480 (and often 256-color) mode via INT 18h.

**Comment by joncampbell123** [comment]
Preliminary conclusions, may be revised later:

![Firefox_Screenshot_2021-11-03T19-20-36 091Z](https://user-images.githubusercontent.com/6245486/140178368-b1f0fc69-c7da-41f7-ae02-3842fcbbd3b2.png)

**Comment by maron2000** [comment]
I basically agree with the above figure, but I don't know whether 640x480@24kHz mode exists.
According to the following page, it says there are 31kHz only for 640x480.
https://web.archive.org/web/20041228000117/http://www2.muroran-it.ac.jp/circle/mpc/program/pc98dos/256mode.html

**Comment by joncampbell123** [comment]
My understanding is that the dot clock and video timings are such that with a 24KHz horizontal sync rate, 640x480 @24KHz would produce a refresh rate too slow for most monitors to handle (below 50Hz if I understand it), so I totally understand why the BIOS INT 18h interface would not allow that.
