### ISSUE TITLE
Change window position after starting Windows 3.1x?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#3046]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What you want

I've set up a DOSBox-X (SDL1) system that runs Windows 3.11 at 1024x768 resolution. On a Mac, when I start this system, the DOSBox-X window extends below the foot of the screen and extends to the right of the screen and I have to move it back to make it fully visible. 

The windowposition = setting doesn't seem to have any effect. (I've tried 20,40 and similar settings). Is there any way to tell DOSBox-X to position this window correctly on a Mac - perhaps by automatically centering it on screen?

If I'm missing something obvious, I apologize for wasting bandwidth.

**Comment by Wengier** [comment]
@emendelson It appears that windowposition= setting works better in macOS SDL2 builds. You can also center the window by the command `config -set windowposition=`.

For macOS SDL1 builds, try set the environment variable `SDL_VIDEO_WINDOW_POS` before starting DOSBox-X, e.g. `export SDL_VIDEO_WINDOW_POS=20,40`. Hope this helps.

**Comment by emendelson** [comment]
@Wengier - That suggestion works perfectly. Thank you! My system uses an AppleScript wrapper, which uses a shell script to launch the DOSBox-X binary with a specified conf file. I simply changed the shell script command to start like this:

`do shell script "export SDL_VIDEO_WINDOW_POS=20,40 && " & [commands to run DOSBox binary, etc. etc.]`

Thank you again!

**Comment by Wengier** [comment]
The issue that the windowposition= setting has no effect in Linux/macOS SDL1 builds is hopefully fixed in the code.

**Comment by emendelson** [comment]
@Wengier - I saw the code fix, and it looks excellent. Thank you. 

I had already modified my AppleScript so that it calculates the x,y positions in order to center the Win311 window on the main screen of whatever Mac it is running on. is there any possibility of creating a config option that would center the window on the main screen? (Perhaps the setting would need to include the dimensions of the window, for example, 1024x768.)

**Comment by grapeli** [comment]
For SDL1, the environment variable `SDL_VIDEO_CENTERED` can be used. Only for windib, directx and x11 video outputs.

`SDL_VIDEO_CENTERED= dosbox-x`

**Comment by Wengier** [comment]
@emendelson Setting windowsposition= to empty also centres the screen. It uses SDL_VIDEO_CENTERED internally.

**Comment by emendelson** [comment]
@Wengier - Ah, that's excellent. I should have read the conf documentation...

**Comment by Wengier** [comment]
Closing since it has been resolved.
