### ISSUE TITLE
Is the HX version dead?

### ISSUE THREAD

**Issue by pinop76** [joncampbell123/dosbox-x#3051]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

Hi,

excuse me for bother but in last two version there is not the Dos HX version. Why?

### What you want

the new HX version

**Comment by Wengier** [comment]
You can download the new HX-DOS build from:

* [dosbox-x-mingw-hx-dos-20211101234567.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.19/dosbox-x-mingw-hx-dos-20211101234567.zip)

Confirmed to work in real MS-DOS:

![image](https://user-images.githubusercontent.com/8216923/140866823-c26f428c-2d21-4cb9-8df1-45dd2dd6acc4.png)

Hope this helps.
