### ISSUE TITLE
DOSBox-X overrides WordStar's cursor-sizing choices after shelling to DOS

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#3052]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 7 32-bit SP1

### What version(s) of DOSBox-X have this bug?

0.83.18 both SDL1 and SDL2 32-bit

### Describe the bug

WordStar for DOS 7.0 has a very useful (but optional) feature: it can use different cursor sizes for insert and overwrite modes. You can have a block cursor for insert and an underscore cursor for overwrite, or vice versa, according to your preference.

This works fine under DOSBox-X _until_ you shell to DOS with ^KF from with a WordStar file, or with "File | Run a DOS Command" from the opening menu.

After you return to WordStar from the shell, WordStar no longer toggles cursor shape when switching from insert mode to overwrite, which you can do with WordStar's ^V command from within a file, or just by pressing the INS key. Instead, it always gives an underscore cursor.

The same thing happens if you edit a WordStar macro (since that process shells to DOS in the background to run WSC.EXE and WSD.EXE, the WordStar macro compiler and decompiler programs respectively).

The user _can_ regain control over the cursor shape by running WordStar's Advanced Page Preview graphics mode from within a file (with the ^OP command or by choosing "View | Preview" from the pulldown menus); upon returning from preview mode, DOSBox-X's grip on the cursor sizing has been released.

### Expected behavior

Cursor shape should change when toggling insert/overwrite mode; it ceases to do so after shelling to DOS from within WordStar.

### Steps to reproduce the behaviour

To reproduce, use either of these two methods to set different cursor sizes for insert and overwrite modes:

**Method 1: Use the WSCHANGE menu tree**

From a DOS prompt in the folder in which WordStar is stored, execute:

`WSCHANGE WS.EXE`

Go to menu A (Console), C (Monitor patches), F (Cursor size for all other monitors), then select:

Then select B (Block cursor during insert mode) and press enter

Then select C (Thin cursor during overtype mode) and press enter

Then select E (Thin cursor after WordStar) and press enter

Then issue ^X (Ctrl-X) to finish making changes.

**Method 2: Use the WSCHANGE's autopatcher**

Download the attached file **cursiz.txt** to your WordStar folder (typically C:\WS):

From a DOS prompt in the folder in which WordStar is stored, execute:

`WSCHANGE WS.EXE`

Go to menu E (Patching, A (Patch from file), then enter the filename **cursiz.txt**.

Then issue ^X (Ctrl-X) to finish making changes.

After completing one or the other above methods, you should be at the DOS prompt.

**To continue testing:**

Once back at the DOS prompt, run WordStar (WS), open any document, and observe that the cursor shape does indeed toggle from a block to an underscore with each press of the INS key, or each issuing of WorStar's ^V command.

Now, shell to DOS and run any command, such as:

DIR > TEST.TXT

Return to WordStar, and again try to toggle the cursor shape with INS or ^V.

You'll see that it no longer works.

Now, try running WordStar's Advanced Page Preview by issuing WordStar's ^OP command (or choosing "View | Preview" from the pulldown menus).

When you return to WordStar, you'll see that cursor sizing with INS or ^V is working again.

[cursiz.txt](https://github.com/joncampbell123/dosbox-x/files/7492896/cursiz.txt)

**Comment by Wengier** [comment]
@RobertJSawyer I can indeed reproduce the said problem. Please check out the updated DOSBox-X build below:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Thanks!

**Comment by RobertJSawyer** [comment]
You're the best, Wengier! Thank you very much! That update does indeed fix the problem. I'm very grateful -- it was driving me nuts!

All best wishes!
