### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by kaine4223** [joncampbell123/dosbox-x#3056]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

windows 10

### What version(s) of DOSBox-X have this bug?

0.83.19

### Describe the bug

I cannot take screenshots of my games. Program doesnt create a capture directory and nothing is happening when i hit the hotkeys or take screenshot via the menu.

### Expected behavior

I dont know where the screenshots are going

### Steps to reproduce the behaviour

I hit take screenshot on the menu, nothing.
I use the hotkeys and still nothing.

### Emulator log

```text
[12:22:27]: Saved. (Slot 2)
Capturing Screenshot to capture\ultimaii_006.png
Capturing Screenshot to capture\ultimaii_007.png
Capturing Screenshot to capture\ultimaii_008.png
```

**Comment by rderooy** [comment]
Based on the log output, screenshots are being created. Just look for a "capture" directory. By default the capture directory is normally located where you dosbox-x config file is located, unless you set a capture directory location in your config file.

**Comment by Allofich** [comment]
Check "C:\Users\(your user name)\AppData\Local\DOSBox-X" for a "capture" directory.

**Comment by kaine4223** [comment]
still nothing. and the conf file is in the dosbox-x directory

**Comment by Allofich** [comment]
Does your .conf file have something set for the `captures =` setting? By default it is just "capture", which should be a folder with that name in the folder of the .conf file.

You could do a Windows search for "ultimaii_006.png" on your hard drive(s) to be sure whether the screenshots exist or not. If they don't exist at all, then maybe there is some issue with reading/writing in your DOSBox-X directory. You could try moving DOSBox-X to a different directory or hard drive.

**Comment by Wengier** [comment]
@kaine4223 I have added a dialog box to show the file name when the screenshot is taken. Also, the full path of the file name will be saved in the log file. Please check out the updated Windows build:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Hope this helps.

**Comment by kaine4223** [comment]
I actually got this working for screencapping last night after moving my dos games, dosbox, and dosbox-x into its own directories under a dosbox directory. I just forgot to post here cause i fell asleep. thanks everyone! wow neat update!

**Comment by Wengier** [comment]
The release version of DOSBox-X version 0.83.20 already has this feature. So closing.
