### ISSUE TITLE
Windows 95 OSR2 freezes on shutdown most of the time when changing the current CD image

### ISSUE THREAD

**Issue by ThisIsNotRTS** [joncampbell123/dosbox-x#3062]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 21H1

### What version(s) of DOSBox-X have this bug?

0.83.18 SDL1, 64 bit

### Describe the bug

This issue is somewhat similar but different enough from #79 to prompt me to open this issue (the CTRL+ALT+DEL trick explained in #79 does not work here).

I installed Win95 OSR2 following the official guide provided by this project here: https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-95. Whenever I shutdown the Win95 OSR2 system, most of the time it freezes. The freeze occurs almost instantly after initiating the shut down.

This has brought me a significant problem: The next time I start the system, it goes to scan the disk. Most of the time the disk scan does not find any problems. But from time to time it finds corrupted files and this has led me to losing a couple of savegame files, thereby losing the progress in those games. There is a chance that the freeze is not the culprit, but it's my only suspect, as the savegame files work like normal before the shutdown freeze.

The freeze seems to occur mostly when I change the current CD image (my system always starts with an inserted CD, so that I can change the current CD image using the GUI while my system is running).

### Expected behavior

Windows 95 OSR2 can always be shutdown with no freeze.

### Steps to reproduce the behaviour

1. Install Windows 95 OSR2 following the guide: https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-95
2. Start Windows 95 OSR2.
3. Change the current CD image, by going to 'DOS -> Change current CD image...' and browse for a different CD image there.
4. Shutdown the system.

### Used configuration

```ini
[sdl]
autolock=true

[dosbox]
title=Windows 95
memsize=480

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
# Set 'ver=7.1' if using Win95 OSR2 (95B) or later
ver=7.1
hard drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal
#core=dynamic_x86

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
IMGMOUNT C hdd.img
IMGMOUNT D Win95.iso
BOOT C:
```

**Comment by Wengier** [comment]
Seems to be the same issue as #2894.

**Comment by ThisIsNotRTS** [comment]
The quick response is very much appreciated @Wengier yep this looks like the exact same problem as #2894... I wonder if it is possible to execute DOSBox-X commands while the Win95 guest system is running. Is this possible? This way I could try commands like `MOUNT` to change the current CD image without using the GUI and see if I get the same bug. Thanks!

**Comment by Wengier** [comment]
@ThisIsNotRTS It is not possible to execute DOSBox-X commands while a guest system is running. However, after further investigations, I think I have fixed the original problem (Windows 9x freeze on shutdown after changing CD image). Please check out the updated Windows build:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by ThisIsNotRTS** [comment]
Can confirm!! v0.83.20 fixes this problem!! Thank you so much.
