### ISSUE TITLE
Can run Norton Utilities 8 installer program

### ISSUE THREAD

**Issue by Keatah** [joncampbell123/dosbox-x#3065]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

How can I get INSTALL.EXE to run for Norton Utilities 8?
https://winworldpc.com/product/norton-utilities/80

The installer says:
"Cannot run in a Windows DOS Box."
"You may either return to Windows and run install using the File/Run command, or exit Windows and run install directly from DOS." [[OK]]

I poked around for "virtualization" or environment options that I thought may address this. No luck in finding anything.

The installer, when run on original DosBox 0.74, proceeds to as for options and whatnot. But freezes when on latest Win64 build of DosBox-X.

**Comment by Wengier** [comment]
@Keatah It looks like the NU8 installer checks for the Windows clipboard function and refuses to run when it is available. Either disable the clipboard API (in "Main" => "Shared clipboard functions"), or try the updated Windows build below:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

Hope this helps.

**Comment by Keatah** [comment]
Yes it works. Thanks for tip.
