### ISSUE TITLE
DOS command "DIR > NUL" crashes/hangs emulator when CD-ROM image is mounted

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#3068]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 Pro 21H1

### What version(s) of DOSBox-X have this bug?

0.83.19 SDL2 Visual Studio 64 bit

### Describe the bug

I was trying to apply the patch attached to the game Screamer 2 and I noticed that the installation file S2patch.bat always stopped without displaying the message that it had been executed. In the batch file I found several commands like "copy s2_*.exe %1:\%2 > nul" or "attrib start*.exe -r > nul". I tried typing the command "DIR > NUL" at prompt and the emulator freezes with the cursor blinking or restarts, but only when the game CD-ROM image is mounted. If no CD-ROM is mounted, the command works. I tried it in DOSBox 0.74-3 and the command works even with a mounted CD-ROM image.
By the way I have found this old closed issue: CTTY emulation can cause DOSBox to hang if you run command shell while "CTTY NUL" #116.

[Screamer 2 patch (v1.11).zip](https://github.com/joncampbell123/dosbox-x/files/7519219/Screamer.2.patch.v1.11.zip)

### Expected behavior

DOSBox-X should display the prompt again without any output, as in real DOS.

### Steps to reproduce the behaviour

1) Mount a CD-ROM image file
2) Type "DIR > NUL" at C: prompt

### Used configuration

```ini
I only added the line "IMGMOUNT D D:\DOSBox-X\CD\SCREAM2.cue -t iso" in the [autoexec] section.
```

### Emulator log

```text
Crash & reboot:
LOG: SHELL:Redirect output to nul
LOG:   72030398 ERROR CPU:Illegal Unhandled Interrupt Called 6
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Removing UMB block 0xcc00-0xdfff
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: menuScale=1
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: font texture id=2 will make 128 x 256
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)

Freeze:
LOG:   67851704 ERROR CPU:Illegal Unhandled Interrupt Called 6
```

**Comment by Wengier** [comment]
I can confirm this issue in DOSBox-X 0.83.18 and 0.83.19, and it only happens with LFN support disabled. The previous DOSBox-X 0.83.17 did not have this issue. Doing a `git bisect` shows that this is the first commit having this issue: 9a00b9f ("Fix to open devices added by device.com to allow IOCTL and other operations").

@nanshiki probably wants to take a look at this - I think it is somewhat similar to issue #3012 that you fixed earlier. I tried commands like `dir>con` and `echo>test` which also crash or hang in this case, in addition to `dir>nul` mentioned above.

**Comment by Wengier** [comment]
@nanshiki I added a name check for the CON device before calling GetInformation(), which seems to fix this issue, although I am not exactly sure if there is any better way to address this. The commit is here: https://github.com/joncampbell123/dosbox-x/commit/7d18e2b57187c9fab1a335ab0f101f4e19193638

@MX9000 Please check out the updated DOSBox-X below:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by nanshiki** [comment]
@Wengier #3071 to fix it.
Because CON is mistakenly registered in Devices[] in DOS_CheckOpenExtDevice(), please fix this.
Also, if you judge it by CON, you will not be able to add a device driver with a device name of CON.

**Comment by Wengier** [comment]
@nanshiki I confirm that PR #3071 fixes this issue. Thanks. An updated Windows build with your fix applied (without a name check) is available from:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by MX9000** [comment]
@nanshiki, @Wengier I just tested the latest build and the bug is fixed.
Thanks to all.
