### ISSUE TITLE
Pentium II in DOSBox-X

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3078]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

Will a upcoming version of DOSBox-X emulate Pentium II in a near future? I know some Windows 9x games behaves choppy without the Pentium II emulatoin that the current version of DOSBox-X is missing.

**Comment by joncampbell123** [comment]
Apparently the only new instructions added by the Pentium II are SYSENTER and SYSEXIT.

If those instructions were added, and reported by CPUID, DOSBox-X could begin some passable Pentium II emulation.

https://en.wikipedia.org/wiki/X86_instruction_listings#Added_with_Pentium_II

**Comment by joncampbell123** [comment]
Code at that level may require the conditional move instructions as well (CMOVcc, etc) and RDPMC. The GCC compiler when asked to compile for "i686" expects a Pentium Pro and can make use of CMOVcc instructions.

**Comment by joncampbell123** [comment]
I went ahead and added cputype=pentium_ii to begin Pentium II emulation.

At this time, it's mostly the same as Pentium Pro emulation but with the addition of SYSENTER/SYSEXIT instructions (which are stubs for now), and one MSR related to the local APIC because Windows Millennium Edition assumes the MSR is there if it detects a Pentium II.

Neither Windows 98 nor Windows ME actually uses SYSENTER/SYSEXIT, so it's kind of hard to test and develop right now. I may have to find a Linux distro that will run downlevel enough for a Pentium II with a kernel compiled to enable those instructions to test that.

**Comment by grapeli** [comment]
> I may have to find a Linux distro that will run downlevel enough for a Pentium II with a kernel compiled to enable those instructions to test that.

It's best to use a [buidlroot](https://buildroot.org/) and build it yourself. It will take 10 minutes to compile the minimum total of toolchain, kernel and userland (busybox) on modern hardware.
![buildroot](https://user-images.githubusercontent.com/452325/142615876-d318210d-1541-472a-b032-ebeb28df8338.png)

For a quick build linux under i686 including pentium II.
[linux.zip](https://github.com/joncampbell123/dosbox-x/files/7569887/linux.zip)
`dosbox-x -fastlaunch -set cputype=pentium_ii -c "mount c linux.zip" -c "c:" -c "linux.bat"`

Starts up, runs, and works fine. Although it seems that the pentium II Klamath should include support for the mmx instructions.
https://en.wikipedia.org/wiki/Pentium_II#Klamath

**Comment by grapeli** [comment]
[Cpuid](https://en.wikipedia.org/wiki/CPUID) doesn't show `SYSENTER/SYSEXIT` or `mmx` under DOSBox-X.
```
cat /proc/cpuinfo
flags: fpu tsc msr cx8 cmov cpuid
```
Under Qemu, yes.
`qemu-system-x86_64 -machine pc,accel=tcg -cpu pentium2 -vga std -display sdl -net none -kernel ./vmlinuz -initrd ./linux.sqf -append 'root=/dev/ram0 ro vga=normal ide-core.noprobe=0.1 ide-core.noprobe=1.0 ide-core.noprobe=1.1 quiet loglevel=1'`

`flags: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 mmx fxsr cpiud hyp`

The [cmov test](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/tree/tools/testing/selftests/x86/test_FCMOV.c?h=linux-4.19.y
) bundled with linux sources fails on DOSBox-X.
/usr/bin/test_FCMOV_32
Under Qemu it ends successfully.
[test_FCMOV_32.tar.gz](https://github.com/joncampbell123/dosbox-x/files/7571728/test_FCMOV_32.tar.gz)
[linux.zip](https://github.com/joncampbell123/dosbox-x/files/7571734/linux.zip)

**Comment by joncampbell123** [comment]
Is that a failure of CMOV or the floating point conditional moves (FCMOV?)

DOSBox-X doesn't implement the machine specific registers (MSRs) needed for SYSENTER/SYSEXIT so I imagine the Linux kernel decided not to use them when WRMSR caused a fault writing to the undefined register.

**Comment by grapeli** [comment]
> Is that a failure of CMOV or the floating point conditional moves (FCMOV?)
FCMOV

> I don't think normal core implements conditional FCMOV yet.
Hmm.
With `core=normal`, the test passes. Although linux itself works poorly. It is best to turn on - Turbo (Fast Forward).

**Comment by joncampbell123** [comment]
@grapeli It just occurred to me: Did you run the test with core=dynamic? I haven't yet changed the code to add SYSENTER/SYSEXIT to dynamic core, and it probably doesn't have FCMOV either.

**Comment by grapeli** [comment]
@joncampbell123 
The test is attached to the linux.sqf image. I attached the file in the previous post.

`core=dynamic_x86`
![core dynamic_x86](https://user-images.githubusercontent.com/452325/142773024-0db12e99-9c73-4f13-9cf9-e539ad9b3153.png)

`core=normal`
![core normal](https://user-images.githubusercontent.com/452325/142773034-c5e75b2a-6a9d-4f49-81b2-97b5862e1e21.png)

**Comment by joncampbell123** [comment]
I just figured out why the Linux kernel in your image was not attempting to use SYSENTER/SYSEXIT.

It won't attempt to unless CPUID reports a Pentium II with at least family 6, model 3, stepping 3.

DOSBox-X currently reports itself as family 6, model 3, stepping 2.

Apparently there was some kind of problem with SYSENTER/SYSEXIT with early Pentium II and Pentium Pro processors, such as CPUID reporting SEP but not actually implementing it.

Interestingly enough, this is noted on a website about SEP and the Windows NT kernel: https://www.geoffchappell.com/studies/windows/km/cpu/sep.htm?tx=256

![Firefox_Screenshot_2021-11-22T15-20-28 815Z](https://user-images.githubusercontent.com/6245486/142887385-88bc1126-f0e1-4919-b550-334fb66a259a.png)

If I make CPUID report stepping level 3, the Linux kernel is definitely seen writing the MSRs corresponding to SYSENTER/SYSEXIT (and then kernel panics because /sbin/init actually tries to use it and crashes).

**Comment by joncampbell123** [comment]
Well, I added SYSENTER and SYSEXIT, but the Linux kernel is crashing after the first SYSCALL. I'll have to look into it later.

**Comment by grapeli** [comment]
Thanks for that clarification.
In the kernel sources this `sep` instruction reporting bug is included.
[arch/x86/kernel/cpu/intel.c](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/tree/arch/x86/kernel/cpu/intel.c?h=linux-4.19.y#n386)

There is also a patch that emulates CMOV and NOPL in the kernel. This way, it allows you to run binaries built for i686 on i586 class processors.
https://lore.kernel.org/lkml/20210626130313.1283485-1-marcos@orca.pet/T/#u

**Comment by grapeli** [comment]
@joncampbell123 
I checked quickly with the same kernel only built under pentium pro.
With debian [busybox](http://ftp.debian.org/debian/pool/main/b/busybox/busybox-static_1.30.1-7+b1_i386.deb) also has the same bug.
I used busybox from the PLD distribution (it is not dedicated only to i686?) and this one worked.
ftp://ftp.pld-linux.org/dists/3.0/PLD/i686/RPMS/busybox-1.31.1-2.i686.rpm

`cputype=ppro_slow`
![procinfo ppro_slow](https://user-images.githubusercontent.com/452325/142930188-36ea4d9f-bf36-4e3e-96d9-7627ea7e4c7a.png)

`cputype=pentium_ii`
![procinfo pentium_ii](https://user-images.githubusercontent.com/452325/142930223-31127b4a-080a-4758-81f7-31dbd17cdd3b.png)

I will try to rebuild the toolchain buildroot with a different configuration.

**Comment by joncampbell123** [comment]
You're certainly having better luck than I am. Here on Linux, normal core is unable to boot Linux with SYSENTER/SYSEXIT without crashing after a few syscalls from /sbin/init.

**Comment by joncampbell123** [comment]
By the way the requirement for stepping 3 is not a bug, but based on actual Intel documentation that says that SEP is reported by CPUID when it's not actually implemented in previous versions of the Pentium II.

**Comment by grapeli** [comment]
@joncampbell123 
This is what it looks like now on the same kernel, but with a more debug build.

![loadlin_000](https://user-images.githubusercontent.com/452325/142934779-fd62ad43-9db8-405d-95ab-55d39670b42d.png)

**Comment by RNMB15** [comment]
Is it now possible to install Windows XP with the Pentium II on DOSBOX.X?

**Comment by brunocastello** [comment]
Apparently no.

**Comment by grapeli** [comment]
@joncampbell123 
Try this build.
[linux.zip](https://github.com/joncampbell123/dosbox-x/files/7584925/linux.zip)

I recompiled toolchain buildroot to a more standard one (`-march=i686 -mtune=generic`)
Also the kernel under the pentium pro (and more debug).
Debugfs can now be mounted.
`mount -t debugfs none /sys/kernel/debug`

Works with `cputype=ppro_slow`. Also with `core=normal`.
With `cputype=pentium_ii` - **no**.

**Comment by grapeli** [comment]
@joncampbell123 
I completely forgot about it. Support for SYSENTER/SYSEXIT can be turned off.
>nosep           [BUGS=X86-32] Disables x86 SYSENTER/SYSEXIT support.

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/tree/Documentation/admin-guide/kernel-parameters.txt?h=linux-4.19.y#n3066

Adding to linux.par `nosep` also works with `cputype=pentium_ii`.

**Comment by joncampbell123** [comment]
I figured out why SYSENTER/SYSEXIT was crashing. Changing cpu.cpl wasn't enough for proper ring transitions, because DOSBox-X inherits the DOSBox SVN design where ring transitions must also modify the page table TLBs to match page permissions. Linux is running fine now with SYSENTER/SYSEXIT.

**Comment by grapeli** [comment]
I compared sep vs nosep by running this [microbenchmark](https://github.com/arkanis/syscall-benchmark/blob/master/03_getpid_vdso.c).
The difference in favor of sep is clear with virtualization. It is small in emulation.

The difference in benefits of sep.
150.97% qemu kvm -cpu host
9.23% qemu tcg -cpu pentium2
4.67% dosbox-x cputype=pentium_ii

**Comment by brunocastello** [comment]
Even with tcg alone the performance is impressive, I have both Intel and M1 Macs and I have been using two QEMU VMs with Windows 98 (i386) and Windows XP (x86_64). 

Only XP struggles on intel if there is no HVF acceleration from QEMU, while it is speedy on M1. 

98 does not use it because qemu-system-i386 has no support for it. But has no problems whatsoever with speed.

**Comment by joncampbell123** [comment]
DOSBox-X might get better performance with SYSENTER if not for how CPL privilege level changes are done in src/cpu/cpu.cpp. CPU_SetCPL() runs through all cached TLB pages and modifies their permissions, EVERY TIME it is called.

The other reason is that SYSENTER and INT 80h all consume one CPU cycle in the DOSBox SVN/DOSBox-X scheme of emulation, not including potential delays related to page faults.
