### ISSUE TITLE
The "segment limits" option should perhaps default to false for at least the 8086 CPU

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#3092]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

The PC Booter game "Karnov" will hang on starting gameplay if using the 8086 cpu with the message

```
Limit check ffff+2-1 = 10000 > ffff DS:SI
Segment limit violation
```

filling the log.

Setting "segment limits = false" in the .conf file allows the game to run with the 8086 emulation, seemingly without problems.

Before the point where the hang occurs, the game code appears to check whether the CPU is an 8086 or not, and runs different code according to the result.

cpu=8086_prefetch. Hangs with "segment limits = true".
```
6B9B:00000011  cmp  word [CD24],0186           ds:[CD24]=0086         EAX:0000DC45 EBX:00000000 ECX:00000000 EDX:00000000 ESI:0000FFFF EDI:0000D970 EBP:000017C6 ESP:000017C6 DS:8239 ES:8239 FS:0000 GS:0000 SS:8FD0 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
6B9B:00000017  jc   0000001C ($+3)             (down)                 EAX:0000DC45 EBX:00000000 ECX:00000000 EDX:00000000 ESI:0000FFFF EDI:0000D970 EBP:000017C6 ESP:000017C6 DS:8239 ES:8239 FS:0000 GS:0000 SS:8FD0 CF:1 ZF:0 SF:1 OF:0 AF:0 PF:1 IF:1
```

cpu=286_prefetch. Doesn't hang with "segment limits = true".
```
6B9B:00000011  cmp  word [CD24],0186           ds:[CD24]=0286         EAX:0000DC45 EBX:00000000 ECX:00000000 EDX:00000000 ESI:0000FFFF EDI:0000D970 EBP:000017C6 ESP:000017C6 DS:8239 ES:8239 FS:0000 GS:0000 SS:8FD0 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
6B9B:00000017  jc   0000001C ($+3)             (no jmp)               EAX:0000DC45 EBX:00000000 ECX:00000000 EDX:00000000 ESI:0000FFFF EDI:0000D970 EBP:000017C6 ESP:000017C6 DS:8239 ES:8239 FS:0000 GS:0000 SS:8FD0 CF:0 ZF:0 SF:0 OF:0 AF:0 PF:1 IF:1
```

Should "segment limits" perhaps default to false for at least the 8086 CPU?

**Comment by Allofich** [comment]
"Guerilla War" is another PC booter game with the same issue. With the 8086 CPU, it hangs with "Segment limit violation" a short time into gameplay if using "segment limits = true". If using "segment limits = false" with 8086, or if using a non-8086 CPU (I tested with 286_prefetch), it runs fine.

**Comment by joncampbell123** [comment]
The segment limit check should be disabled for 8086 and 80186 cpu types because the 8086 has no such exception and I don't think the 80186 has that either. That exception as far as I know was added in the 286 when protected mode and segment/selector limits were added.

That would suggest the game is reading/writing a WORD value in some segment with offset FFFFh, correct?

So the fix is to compile out that check when compiled against *_8086.cpp normal/prefetch core.

**Comment by Allofich** [comment]
> That would suggest the game is reading/writing a WORD value in some segment with offset FFFFh, correct?

That's correct.

> So the fix is to compile out that check when compiled against *_8086.cpp normal/prefetch core.

Alright, sounds easy enough. I'll look at it in a while. Thanks.
