### ISSUE TITLE
possible compile bug on ubuntu 20,04

### ISSUE THREAD

**Issue by drhax9908** [joncampbell123/dosbox-x#3093]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Ubuntu 20.04

### What version(s) of DOSBox-X have this bug?

DOSBox-X 0.83.19 2021-11-01 10:33 to commit 6f185f9025d30ef57855d52cab553b13ef111616

### Describe the bug

Dosbox-X downright fails to compile on Ubuntu 20.04

### Expected behavior

The expected outcome was to build properly

### Steps to reproduce the behaviour

Download the source code and extract if using a zip file download
Run the build script (i tested "build" and "build-debug-sdl2"
Eventually, it gives an sdl build error

### Additional context

This is the error I got

`g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -I../../src/aviwriter "-DRESDIR=\"\"" -I../../src -I../../src/libs/mt32 -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wno-deprecated-declarations   -Wconversion-null   -Wsign-promo   -Wlogical-op   -pedantic   -Wunused   -Wextra   -Wall   -I/root/dosbox-x-dosbox-x-v0.83.19/vs2015/sdl2/linux-host/include/SDL2 -D_REENTRANT -I/root/dosbox-x-dosbox-x-v0.83.19 -I/root/dosbox-x-dosbox-x-v0.83.19/vs2015/sdlnet/linux-host/include -I/root/dosbox-x-dosbox-x-v0.83.19/vs2015/sdlnet/linux-host/include/SDL  -g -std=gnu++14  -O2 -msse  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/root/dosbox-x-dosbox-x-v0.83.19 -I/root/dosbox-x-dosbox-x-v0.83.19/vs2015/sdlnet/linux-host/include -I/root/dosbox-x-dosbox-x-v0.83.19/vs2015/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -MT render.o -MD -MP -MF $depbase.Tpo -c -o render.o render.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from sdlmain.cpp:143:
display2.cpp: In function ‘void DISP2_Refresh(Bitu)’:
display2.cpp:97:78: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
   97 |   DISP2_WriteChar(new_pos/80,new_pos%80,host_readw(&disp2.memory[new_pos<<1])&0xff00|new_ch);
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
sdlmain.cpp: In function ‘void MenuDrawTextChar(int&, int, unsigned char, Bitu, bool)’:
sdlmain.cpp:2547:61: error: ‘loadlang’ was not declared in this scope
 2547 |         if ((IS_PC98_ARCH || IS_JEGA_ARCH || isDBCSCP()) && loadlang && (c || !check)) {
      |                                                             ^~~~~~~~
sdlmain.cpp:2579:61: error: ‘loadlang’ was not declared in this scope
 2579 |         if ((IS_PC98_ARCH || IS_JEGA_ARCH || isDBCSCP()) && loadlang && (c || !check)) {
      |                                                             ^~~~~~~~
sdlmain.cpp: In function ‘void MenuDrawTextChar2x(int&, int, unsigned char, Bitu, bool)’:
sdlmain.cpp:2665:61: error: ‘loadlang’ was not declared in this scope
 2665 |         if ((IS_PC98_ARCH || IS_JEGA_ARCH || isDBCSCP()) && loadlang && (c || !check)) {
      |                                                             ^~~~~~~~
sdlmain.cpp:2697:61: error: ‘loadlang’ was not declared in this scope
 2697 |         if ((IS_PC98_ARCH || IS_JEGA_ARCH || isDBCSCP()) && loadlang && (c || !check)) {
      |                                                             ^~~~~~~~
sdlmain.cpp: In function ‘void GFX_HandleVideoResize(int, int)’:
sdlmain.cpp:6172:55: warning: comparison of integer expressions of different signedness: ‘Bitu’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
 6172 |             userResizeWindowWidth = currentWindowWidth==sdl.surface->w?0:(unsigned int)currentWindowWidth;
      |                                     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
sdlmain.cpp:6173:57: warning: comparison of integer expressions of different signedness: ‘Bitu’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
 6173 |             userResizeWindowHeight = currentWindowHeight==sdl.surface->h?0:(unsigned int)currentWindowHeight;
      |                                      ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
sdlmain.cpp: In function ‘bool clear_menu_callback(DOSBoxMenu*, DOSBoxMenu::item*)’:
sdlmain.cpp:11440:17: warning: unused variable ‘mname’ [-Wunused-variable]
11440 |     const char *mname = menuitem->get_name().c_str();
      |                 ^~~~~
render.cpp: In function ‘std::string LoadGLShader(Section_prop*)’:
render.cpp:1135:17: warning: unused variable ‘ssrc’ [-Wunused-variable]
 1135 |     const char *ssrc=shader_src.c_str();
      |                 ^~~~
sdlmain.cpp: In function ‘bool DOSBOX_parse_argv()’:
sdlmain.cpp:9843:26: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
 9843 |                     chdir(tmp.c_str());
      |                     ~~~~~^~~~~~~~~~~~~
In file included from ../../include/../src/dos/../libs/libchdr/chd.h:49,
                 from ../../include/../src/dos/cdrom.h:38,
                 from ../../include/bios_disk.h:24,
                 from sdlmain.cpp:129:
../../include/../src/dos/../libs/libchdr/coretypes.h: At global scope:
../../include/../src/dos/../libs/libchdr/coretypes.h:29:15: warning: ‘size_t core_fsize(FILE*)’ defined but not used [-Wunused-function]
   29 | static size_t core_fsize(core_file *f)
      |               ^~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-int-to-void-pointer-cast’
cc1plus: warning: unrecognized command line option ‘-Wno-int-to-void-pointer-cast’
make[3]: *** [Makefile:435: sdlmain.o] Error 1
make[3]: *** Waiting for unfinished jobs....
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-int-to-void-pointer-cast’
cc1plus: warning: unrecognized command line option ‘-Wno-int-to-void-pointer-cast’
make[3]: Leaving directory '/root/dosbox-x-dosbox-x-v0.83.19/src/gui'
make[2]: *** [Makefile:529: all-recursive] Error 1
make[2]: Leaving directory '/root/dosbox-x-dosbox-x-v0.83.19/src'
make[1]: *** [Makefile:400: all-recursive] Error 1
make[1]: Leaving directory '/root/dosbox-x-dosbox-x-v0.83.19'
make: *** [Makefile:333: all] Error 2
`

**Comment by Wengier** [comment]
I think this happens only if you compile the code without FreeType/TTF support. It is hopefully fixed in the code.

**Comment by drhax9908** [comment]
> I think this happens only if you compile the code without FreeType/TTF support. It is hopefully fixed in the code.

so I had no idea freetype and fontconfig's dev packages weren't installed on my pc, let me see if installing them fixes it

**Comment by drhax9908** [comment]
update, I tested the commit before the patch was applied, it was in fact freetype that caused this bug

**Comment by Wengier** [comment]
Thanks for confirming.  Closing.
