### ISSUE TITLE
Zool hangs for extended periods

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#3096]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Linux F35

### What version(s) of DOSBox-X have this bug?

0.83.20git

### Describe the bug

This seems to be specific to DOSBox-X. Starting the game "Zool", it seems to hang on startup, but eventually continues. There is one error in the log at this point:
```
LOG:   21487228 ERROR EXEC:stack underflow/wrap at EXEC SS:SP=0000:0000
```

Proceeding to start the actual gameplay, again seems to hang, but after a long wait it continues. The log shows these errors:
```
LOG:   90155528 ERROR DOSMISC:End of cluster chain reached, but maybe good afterall ?
LOG:   90826479 ERROR DOSMISC:End of cluster chain reached, but maybe good afterall ?
LOG:   91229544 ERROR DOSMISC:End of cluster chain reached, but maybe good afterall ?
LOG:  302255032 ERROR DOSMISC:End of cluster chain reached, but maybe good afterall ?
LOG:  303048204 ERROR DOSMISC:End of cluster chain reached, but maybe good afterall ?
```

Launching the game from dosbox-svn or dosbox-staging, and it starts straight away.

### Steps to reproduce the behaviour

The game was started as follows:
```
dosbox-x -defaultconf -c "imgmount a Zool.img" -c a: -c Zool
```

### Additional context

Zool2 also seems to suffer from slowdowns on startup.

**Comment by rderooy** [comment]
It seems the above issue only happens if you run the game directly from the 720KB floppy disk image. If you copy the contents to the (folder mounted) HDD, it runs fine.

**Comment by Allofich** [comment]
I recently added separate I/O delay for floppies, which defaults to slower than hard drive/CD delay. Does setting "floppy drive data rate limit" under the [dos] section in the .conf file to 0 fix the hangs?

**Comment by rderooy** [comment]
I will need to check when I get back home. I had seen that option, but thought it was disabled by default.

**Comment by Allofich** [comment]
By default it is -1, which is supposed to give a reasonable delay (same as "hard drive data rate limit").

I set that default delay to 5000 bytes/second, in order to display PC booter startup screens for a few seconds instead of having them instantly disappear.

However, I think that value was too small. For some reason at the time I thought I was setting it faster than a real drive, but after looking online, I think it should be a higher value.

According to someone here:
https://stackoverflow.com/questions/52841124/how-fast-could-you-read-write-to-floppy-disks-both-3-1-4-and-5-1-2

> The actual disks always maxed out around 100-250kbps and I've never seen above 250kbps on a floppy.

We could take the average of that as 175 kbps. 175 * 1024 = 179,200 bps. 179,200 bps / 8 = 22,400 Bps. So I think I'll change the default to 22400 (regardless of whether this is the cause of this issue).

**Comment by Allofich** [comment]
I sent in a new PR to change the default floppy speed to 22400. Can you try testing with

[dos]
floppy drive data rate limit = 22400

and see if the issue is fixed?

**Comment by grapeli** [comment]
@Allofich 
The current default value is discussion. Not everyone guessing what reason the reading from the floppy disk is so slow.

For the test, I downloaded this image of one floppy Linux.
https://pupngo.dk/xwinflpy/xwoaf_rebuild.img
In the domestic value of `floppy drive data rate limit=-1`, `bzimage` and `Image.gz` reads over **4 and a half minutes**.
At changed `floppy drive data rate limit=0` -  **1 second**.

**Comment by rderooy** [comment]
@Allofich when I start it as such it indeed starts somewhat faster.
```
dosbox-x -defaultconf -set "dos floppy drive data rate limit=22400" -c "imgmount a Zool.img" -c a: -c Zool 
```

But even if I set the limit to 0 it still takes considerably longer start the game, unlike if I start it from a folder mounted hdd where it starts instantaneous.

**Comment by Allofich** [comment]
@rderooy Thanks for testing. So the floppy limit has some effect but something else is affecting it, too.

**Comment by Wengier** [comment]
@rderooy What if you try an previous release, such as version 0.83.19 (before the "floppy drive data rate limit" setting was added) and see if the issue also occurs?

**Comment by rderooy** [comment]
Sorry for the delay, yes I can confirm that with 0.83.19 it starts straight away. Unfortunately I don't have the time right now to do a git bisect.

**Comment by rderooy** [comment]
closing this as I tried to recreate it today and could not.
