### ISSUE TITLE
Bug in joystick correction (with code 'patch')

### ISSUE THREAD

**Issue by Baderian** [joncampbell123/dosbox-x#3097]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Linux Mint 20.2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 0.83.19 - Compiled using build-debug-g3-sdl2

### Describe the bug

Setting config parameter joy1response1 and/or joy1response2 to 0.8 makes the joystick almost unusable.

More precisely, going to the 'negative' zones (normally left and/or down) produces erratic response.

### Steps to reproduce the behaviour

1. Set config parameter joy1response1 to 0.8 within [joystick]
2. Test joystick with JOYTEST.EXE or TMSCOPE.EXE

### Additional context

Traced the problem to source file src/gui/sdl_mapper.cpp, within function GetJoystickVector, currently lines 2030 and 2031:

        float x1 = (sgn(v.X) * fabs(pow(v.X, response)));
        float y1 = (sgn(v.Y) * fabs(pow(v.Y, response)));

Calling function pow(x,y) requires that x be positive if y is not an integer. Else for example pow(-1,0.5) would be legit, and that's sqrt(-1).
As it is, x1 (resp y1) gets set to 'nan' if v.X (resp v.Y) is negative and response is not integer.

So most probably the author intended to write those lines instead:

        float x1 = (sgn(v.X) * pow(fabs(v.X), response));
        float y1 = (sgn(v.Y) * pow(fabs(v.Y), response));

Tested that little 'patch', indeed it works much better.

Hope this helps. It's an amazing project!

**Comment by Wengier** [comment]
I have already applied your fix. Thanks!
