### ISSUE TITLE
[Demo] void main (1999) - does not work fully properly

### ISSUE THREAD

**Issue by grapeli** [joncampbell123/dosbox-x#3102]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

linux

### What version(s) of DOSBox-X have this bug?

git 918c7e4 SDL2

### Describe the bug

https://www.pouet.net/prod.php?which=24442

Requires a processor with **mmx**.

### Expected behavior

Works perfectly fine from start to finish under dosemu2 (linux).
Partly works under Qemu with Freedos 1.2 (no sound).

https://user-images.githubusercontent.com/452325/143423586-ae2729ee-9ca4-4b84-b020-3bc41538f4fb.mp4

### Steps to reproduce the behaviour

https://http.hu.scene.org/parties/1999/demoparty99/demo/voidmain.zip

### Emulator log

```text
CPU:Illegal/Unhandled opcode 0F43
CPU:Illegal/Unhandled opcode 0F43
CPU_Exception: Exception 6 already in progress, triggering double fault instead
CPU:Illegal/Unhandled opcode 0F43
CPU_Exception: Double fault already in progress == Triple Fault. Resetting CPU.
++ exception method is not compatible with dynamic core when emulating reset
DEBUG MISC:Emulation threw a signal to reboot the system
DEBUG MISC:Dispatching VM event DOS exit, reboot begin
```

**Comment by joncampbell123** [comment]
Funny that! I was just looking over that very demo yesterday to see if I could resolve a memory corruption crash! It seems to corrupt memory below 64KB midway through. The demo also periodically checks for keyboard input using INT 21h (a sort of kbhit() type call), so eventually when it calls INT 21h a fatal exit happens when that corruption overwrites the DOS kernel and/or the interrupt descriptor table. I was also interested to see if the demo would run fully with recent MMX instruction improvements.

You'll need to use cputype=pentium_mmx.

The demo requires MMX instructions. It has code to detect MMX, but it is flawed in that it does one bitmask test against CPUID that falsely detects MMX if CMPXCHG8B, APIC, or other features are enabled. cputype=pentium and CMPXCHG8B will trigger that false detection, and that is why it crashes.

DOSBox SVN reports little enough in CPUID that the demo does correctly detect the lack of MMX instructions.

**Comment by grapeli** [comment]
>I was also interested to see if the demo would run fully with recent MMX instruction improvements.

That's why I checked.

> You'll need to use cputype=pentium_mmx.

I made it clear.

Under both tcg and kvm qemu, there is an error somewhere in the middle of this demo.
![voidmain-qemu](https://user-images.githubusercontent.com/452325/143473053-83dfb4a4-f863-4390-a77b-1d2853d561e3.jpg)

**Comment by joncampbell123** [comment]
Here in my testing I either get random code execution throughout real-mode or an E_Exit() error about INT 21h and the interrupt table. But the crash is the same.

**Comment by grapeli** [comment]
Runs at `memsize` > 18.
`dosbox-x -set memsize=19 -set cputype=pentium_mmx -set core=dynamic_x86`
Error occurs after some time.
`E_Exit: IRET:Illegal descriptor type 12`

With `memsize=48`.
![voidmain dosbox-x](https://user-images.githubusercontent.com/452325/143491497-24b11577-911f-47a8-b0fd-1c434454e1a1.png)

**Comment by joncampbell123** [comment]
Yup, that's exactly what I see here.

I'm not sure where the demo corrupts conventional memory or why (possible NULL pointer dereference?) but I have it on my list of demos to check when CPU improvements are made.

It doesn't seem to be the DOS kernel at fault because the demo crashes in the same manner if I boot into MS-DOS and run it in DOSBox-X.

**Comment by grapeli** [comment]
With `memsize=21`.
Segmentation fault. I am attaching the gdb log. Maybe it will be useful.
[backtrace.log.txt](https://github.com/joncampbell123/dosbox-x/files/7605079/backtrace.log.txt)

**Comment by grapeli** [comment]
There are also such errors.
`DOS fatal memory error: Corrupt MCB chain`

![voidmain dosbox-x](https://user-images.githubusercontent.com/452325/143505416-1c9e430f-4c0c-47ac-8e75-26020ee9c186.png)

**Comment by grapeli** [comment]
@joncampbell123 
Does this demo use mmx instructions in its code?
Starts and stops running in the same place with `cputype=ppro_slow` (on video about 47 seconds).

![voidmain_001](https://user-images.githubusercontent.com/452325/143513567-d2e60db1-b2a3-425c-8be4-a4dd48302f4e.png)

**Comment by joncampbell123** [comment]
It definitely does. Whenever the demo is cross-fading frames, the debugger shows a particular tight loop of MMX instructions.

A recent commit to master even updates the debugger interface to correctly decode and display MMX instructions.

    0868:0021E10F 0F6EF0              movd mm6,eax
    0868:0021E112 0F60F7              punpcklbw mm6,mm7
    0868:0021E115 0F6E06              movd mm0,[esi]
    0868:0021E118 0F6E0B              movd mm1,[ebx]
    0868:0021E11B 0F60C7              punpcklbw mm0,mm7
    0868:0021E11E 0F60CF              punpcklbw mm1,mm7
    0868:0021E121 0FD5C5              pmullw mm0,mm5
    0868:0021E124 0FD5CE              pmullw mm1,mm6
    0868:0021E127 0FFDC1              paddw mm0,mm1
    0868:0021E12A 0F71E008            psraw mm0,08
    0868:0021E12E 0F6E5604            movd mm2,[esi+0004]

Pentium Pro includes MMX instructions if I am correct.

**Comment by joncampbell123** [comment]
I have no idea why it suddenly corrupts lower memory. One remote possibility is that it might rely on a particular MMX instruction to update some particular pointers in memory and maybe DOSBox-X isn't quite emulating that one instruction properly. Other than that I don't really know what makes it crash there yet.

**Comment by grapeli** [comment]
Under Qemu, the error occurs more or less in the same place. This demo works for me until the end only under dosemu2. Dosemu2 works with [fdpp](https://github.com/dosemu2/fdpp).
The voidmain demo uses [PMODE/W](https://en.wikipedia.org/wiki/PMODE) v1.33 DOS extender. Maybe fdpp works better with this extender.

**Comment by grapeli** [comment]
Running under Qemu (kvm) with Win98SE it works fine until the end. Although in the same Qemu with Freedos 1.2 and MSDOS 6.22 it fails in the same place.

**Comment by grapeli** [comment]
> It definitely does. Whenever the demo is cross-fading frames, the debugger shows a particular tight loop of MMX instructions.
> 
I do not know. Under Qemu, you can turn off support for individual instructions.
`qemu -cpu help`

This demo works under win98se running this way.
`-cpu kvm32,-mmx`
Running `cpuid` does not show mmx.

**Comment by grapeli** [comment]
It also works perfectly well under win 95 in DOSBox-X.

![voidmain win95 dosbox-x](https://user-images.githubusercontent.com/452325/143612487-c865ff4c-5043-47fc-be19-639bd12e2a4e.png)

**Comment by joncampbell123** [comment]
That's hilarious considering the demo's NFO file recommends running it under DOS.

Perhaps there's a memory corruption bug that doesn't make itself apparent within the DOS VM under Windows 95?

**Comment by joncampbell123** [comment]
In fact, from what I remember, 1999 is when sound cards were entirely PCI and ISA cards were no longer being made. Some cards, like the Sound Blaster Live! had Windows drivers that automatically provided emulation for DOS VMs, but you had to do a little extra work and load EMM386.EXE to get the DOS emulation to work. Other sounds cards either had poor SB emulation or didn't bother at all. Understandably that made pure DOS mode testing harder.

**Comment by joncampbell123** [comment]
I can confirm it runs in a VM under Windows 95 just fine here too. Even with dynamic core.

**Comment by grapeli** [comment]
https://user-images.githubusercontent.com/452325/143623453-b92e9e1a-9f36-416d-9dfa-a1d254bebf86.mp4

**Comment by joncampbell123** [comment]
So far on the Windows 95 image I'm testing, the demo crashes in pure DOS mode! It doesn't even work. In fact it caused a segfault in DOSBox-X because the page table directory points outside system memory! I added code in src/cpu/paging.cpp to check for that and substitute 0xFFFFFFFF if that happens, and it just causes an E_Exit() on call to INT 21h.

I'll try again with EMM386.EXE loaded.

**Comment by joncampbell123** [comment]
If I remove EMM386.EXE so it runs in pure real mode DOS, it starts.

However even from a Windows 95 boot image, it crashes at the same point in the same way.

One last test I will do is run it on an old Pentium 133MHz MMX laptop of mine in pure DOS mode and see if it crashes the same.

**Comment by joncampbell123** [comment]
Before you go, here is a video of it crashing on a 133MHz Pentium MMX laptop.

https://user-images.githubusercontent.com/6245486/143627012-621440ee-5319-45f5-9e92-4faa9feb3b0b.mp4

**Comment by grapeli** [comment]
@joncampbell123 
Using the HX DOS Extender, Void Main works fine in Dos DOSBox-X sessions.
Two files are enough - `DPMILD32.EXE HDPMI32.EXE`.
