### ISSUE TITLE
0.83.20/14: "CPU:Illegal Unhandled Interrupt Called 6" in Pools of Darkness 1.00

### ISSUE THREAD

**Issue by psavola** [joncampbell123/dosbox-x#3108]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Linux, CentOS 8, kernel 4.18.0-348.2.1.el8_5.x86_64

### What version(s) of DOSBox-X have this bug?

0.83.19 SDL2; also occurred with 0.83.14 SDL1

### Describe the bug

Dosbox-x crashes when playing Pools of Darkness (DOS) and moving on from Limbo to Thorne's cave with infinite number of "CPU:Illegal Unhandled Interrupt Called 6" errors. I played through the same game in June 2021 without problems. The version then was likely 0.83.14, but that didn't work now. I also tried upgrading to 0.83.19, but that didn't work either. I tried with empty dosbox-x.conf (so default configs), didn't work.

I found https://github.com/joncampbell123/dosbox-x/issues/1380 and also tried by running "loadfix" first, didn't work.

Because I managed to play through last June with the same version 0.83.14, I suspect this may be related to some changes in the Linux kernel running dosbox-x (or the firmware CPU fixes loaded up in the boot). But even if this worked with the previous kernel, it is not obvious whether this is a dosbox-x issue or a kernel issue.

 

### Expected behavior

No crash.

### Steps to reproduce the behaviour

Run Pools of Darkness. Go from Limbo to Thorne's cave.

### Used configuration

```ini
Default
```

### Emulator log

```text
LOG:  537565676 ERROR CPU:Illegal Unhandled Interrupt Called 6
```

**Comment by psavola** [comment]
Also tested 0.83.19 with kernel-4.18.0-240.22.1.el8_3.x86_64, which I was using last June. Also didn't work.

**Comment by psavola** [comment]
For what it's worth, the game also crashes (without errors) with dosbox-staging 0.77.1.

**Comment by Wengier** [comment]
I wonder if it is possible that your copy of the game is now corrupted? I tried the said game I downloaded earlier in DOSBox-X (in both Windows and Linux) and DOSBox Staging (in Windows) and they all worked. Perhaps you can re-download the game and try again?

**Comment by psavola** [comment]
For clarification, the game works in general, but a specific event (moving between dimensions that occurs 10 times during the game) apparently not. I tried to grab another copy (from first link - wowroms) and copied the save files, but that didn't work either. If you can, try if it works for you or there is anything special with attached saves. Load save "A", select "Move on", then "Thorne" and "Yes". 
[pod_save.zip](https://github.com/joncampbell123/dosbox-x/files/7613060/pod_save.zip)

**Comment by grapeli** [comment]
It works.

https://user-images.githubusercontent.com/452325/144255325-3fea8c1b-bf81-4df2-a96b-8dd934407622.mp4

You must provide more details on how to reproduce this bug.

Memory Deny Write Execute (SELinux also) has no effect, this game should only run on `core=normal`. Anyway, it works fine on DOSBox-X with W^X and `core=dynamic_x86`.

**Comment by psavola** [comment]
Interesting. You used version 1.10 which can only be bought as part of the GOG FRUA package. I wonder if it also works for you if you try to grab the "classical" version 1.00 from somewhere? If it works, I wonder how it would be possible to further figure out the differences (possibly in Linux setup).

**Comment by psavola** [comment]
FWIW I have selinux enabled (no errors). /proc/cpuinfo consists of two following kind of cpus, if it could be relevant.

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Celeron(R) CPU G1840 @ 2.80GHz
stepping	: 3
microcode	: 0x28
cpu MHz		: 2800.000
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 s
s ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmpe
rf pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 sdbg cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer xs
ave rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust erms invpcid xsaveopt dther
m arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5597.18
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**Comment by psavola** [comment]
I wonder if this could also be related to file access. The same bug occurs for me if I deposit a lot of items to the vault (choose deposit and items). Usually this occurs after putting third character's items to the vault. Depositing in the vault creates a TMPVAULT.DAT file in the save game folder. In a similar fashion, moving on between dimensions destroys almost all items the characters have, so the game has to go through all the characters and remove them.

**Comment by grapeli** [comment]
The reasons may be different. Incorrect dosbox-x configuration, game version, but also inadequate write permissions on the file system in which the game is located, etc.

**Comment by psavola** [comment]
I found a copy of 1.10 that appears to work. GOG may have changed something when republishing the game. Previously I have tested two versions 1.00 and neither worked. It might be interesting to hear if someone else can reproduce the problem with 1.00 (available from the net from wowroms, for example).

**Comment by grapeli** [comment]
I downloaded this game(version 1.00) from this source and used your saves.

After executing the following sequences:
PLAY--->LOAD SAVED GAME--->POOLS--->A--->BEGIN ADVENTURING
and finally pressing Enter three times, you quit the game **without any error message**.

The same is true for **DOSBox-X**, **dosbox-SVN**, and **dosbox-staging**.

**Comment by psavola** [comment]
> I downloaded this game(version 1.00) from this source and used your saves.
> 
> After executing the following sequences: PLAY--->LOAD SAVED GAME--->POOLS--->A--->BEGIN ADVENTURING and finally pressing Enter three times, you quit the game **without any error message**.
> 
> The same is true for **DOSBox-X**, **dosbox-SVN**, and **dosbox-staging**.

You probably obtained a copy which includes the copy protection, requiring an answer from the manual (also available on the net). After three tries it quits to DOS. Sorry for forgetting that.

**Comment by psavola** [comment]
Here is a replacement game.exe and .ovr of version 1.00 where the copy protection goes away by pressing enter once.
[game.zip](https://github.com/joncampbell123/dosbox-x/files/7636860/game.zip)

**Comment by grapeli** [comment]
It should have been pointed out.
I solved these puzzles.

Each of these three versions of dosbox is the same. The game stops at the same point (screenshot from dosbox-staging).

![game_000](https://user-images.githubusercontent.com/452325/144307199-2f5faadf-eb78-4fe7-ab82-0a5e716715db.png)
Except that only dosbox-x reports in the log:
`ERROR CPU: Illegal Unhandled Interrupt Called 6.`

**Comment by grapeli** [comment]
It has nothing to do with the version or type of operating system.
The same is true for dosbox-x-vsbuild-win64-20211130230328 (sdl2).

**Comment by grapeli** [comment]
Additionally.
Pools of Darkness (version 1.00) stops running in the same place after loading your game state under: Freedos in Qemu, dosemu, dosemu2 and in [dosbox](https://www.emulatrix.net/) running in firefox.

**Comment by Allofich** [comment]
I can confirm the crash.

> I wonder if this could also be related to file access. The same bug occurs for me if I deposit a lot of items to the vault (choose deposit and items). Usually this occurs after putting third character's items to the vault. Depositing in the vault creates a TMPVAULT.DAT file in the save game folder. In a similar fashion, moving on between dimensions destroys almost all items the characters have, so the game has to go through all the characters and remove them.

Based on this comment, I experimented with deleting all the characters in that save except for one, then trying to move to Thorne, and then no crash occurred. So maybe there is indeed some issue involving lots of items, multiple characters, or similar.

**Comment by psavola** [comment]
In addition, I noticed that at the end of the game (except an additional special mission), the game (both 1.00 and 1.10) quits to dos after the three difficult final battles, even though the dialogue should continue (no messages in dosbox-x console):
![ending](https://user-images.githubusercontent.com/95160994/144863395-37697efb-89c8-4073-919b-43544bf0bf0f.png)

This can be prevented by using LOADFIX which allows the game to load VACE.EXE and then shift back to GAME. A similar issue occurs when starting up: start.bat triggers CONTROL.EXE which is supposed to load GAME.EXE, but that doesn't work without LOADFIX. But as far as I can tell, this is a more generic thing that can be avoided that way.

**Comment by psavola** [comment]
Also occurs with 0.83.20.

**Comment by grapeli** [comment]
It won't work 99% and in the next version of dosbox-x.
The error is in the game. It was probably fixed in 1.10, because this one does not appear. Maybe this save game is not from version 1.00.

I stated where I tested it and it didn't work.
One more example.

https://user-images.githubusercontent.com/452325/145122917-245bf525-27a8-4c15-9108-23b3ff745062.mp4

An error appears at the end - **invalid opcode**.

**Comment by grapeli** [comment]
from under dos-a win98se
error: **The program tried to execute an invalid instruction.**

https://user-images.githubusercontent.com/452325/145486002-57108d63-fb6d-47de-bac1-7b2937c31e02.mp4

**Comment by psavola** [comment]
It is confusing that this has worked before with dosbox, but obviously there is some more detailed issue that depends on the characters you are playing etc. that is triggering this. But clearly this is a bug in the game and there is very little that dosbox-x can do about this; luckily version 1.10 did not appear to have the same problem.
