### ISSUE TITLE
Add comp and/or fc commands

### ISSUE THREAD

**Issue by pcdosretro** [joncampbell123/dosbox-x#3110]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What you want

Add comp and/or fc commands for completeness since most other standard DOS commands are present in DOSBox-X.

**Comment by Wengier** [comment]
Good suggestion! Please try the updated DOSBox-X build, now with both DOS commands (and also EDLIN command):

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by pcdosretro** [comment]
Will these be in the next release (0.83.20) ? I doubt anyone cares about EDLIN, that was an awful program; it barely qualifies as an editor.

Also, shouldn't there be a FILES command since there are FCBS, BUFFERS, and LASTDRIVE commands to change those values.

**Comment by Wengier** [comment]
The EDLIN command is a standard DOS command in some DOS versions. Also, I agree there should be a FILES command if the other commands (FCBS etc) are there.

**Comment by Wengier** [comment]
DOSBox-X 0.83.20 is released with these commands available.
