### ISSUE TITLE
Can I change dosbox-x default startup drive to something other than z:

### ISSUE THREAD

**Issue by Gamespeople** [joncampbell123/dosbox-x#3111]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

When I searched for the above I only found one reply on an external website that said "I don't think so.". 
So I'm asking it here.
I want to try out DOSBox-x on my mac running XP home edition under Fusion. I was able to install DB-X just fine, however it comes default with Z: which is the same default used in Fusion for access to the shared directories on my computer.
I tried changing the "set path =" to Y:\;Y:\SYSTEM;Y:\BIN;Y:\DOS;Y:\4DOS;Y:\DEBUG;Y:\TEXTUTIL
...which didn't change the default, just ruined the path (I assume).
So, is there a secret way to make the default Y: or something else? Could be handy in some setups I think!
I tried playing with:
`working directory option  = prompt
working directory default = Y:\`
No success, tried "Y" and "Y:" too...
Thanks!

**Comment by Gamespeople** [comment]
I think I found it in the dosbox-x.conf file - "working directory default". Will check that further...

**Comment by Wengier** [comment]
You can try enter the following command or put it in [autoexec] section of dosbox-x.conf:

`mount -z y`

Then Z: will become Y:

You can also mount other drives with MOUNT or IMGMOUNT commands.

Hope this helps.

**Comment by Gamespeople** [comment]
Ah, almost correct, it needs to be set as this:

mount -z y:\
set path  = Y:\;Y:\SYSTEM;Y:\BIN;Y:\DOS;Y:\4DOS;Y:\DEBUG;Y:\TEXTUTIL
mount z z:\ (and so on...)

and that works correctly...

Thanks for the tip, that is great! Now to see if I can fix that other problem we have been chatting about...

I'll keep poking away...
