### ISSUE TITLE
Not possible to select .conf files via Restart DOSBox-X with config file

### ISSUE THREAD

**Issue by tedmundc** [joncampbell123/dosbox-x#3113]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

macOS Monterey 12.0.1 M1 Max

### What version(s) of DOSBox-X have this bug?

0.83.19

### Describe the bug

It is not possible to select .conf files via Restart DOSBox-X with config file in macOS (Monterey 12.0.1 on an M1 Max machine). The .conf files - including ones generated by DOSBox-X itself - are greyed out and cannot be selected.
<img width="299" alt="Screenshot 2021-11-29 at 22 23 33" src="https://user-images.githubusercontent.com/94480551/143945076-3e9b7694-2d20-4f92-82d8-da5bb7b9852e.png">

### Expected behavior

.conf files should be selectable in the file picker

### Steps to reproduce the behaviour

Copy the DOSBox-X binary (either dosbox-x or dosbox-x-sdl) to the /Applications folder
Open DOSBox-X and select any working directory (tried both default in the app bundle as well as a folder in ~/Documents)
Save a config file from the configuration tool
Try and load that config file via Main> Restart DOSBox-X with config file

**Comment by Wengier** [comment]
I can reproduce the issue in macOS. It is hopefully fixed.
