### ISSUE TITLE
0.83.20 MinGW packages missing shader files

### ISSUE THREAD

**Issue by rebb** [joncampbell123/dosbox-x#3118]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Win7

### What version(s) of DOSBox-X have this bug?

0.83.20

### Describe the bug

The portable MinGW packages for 0.83.20 seem to be missing the shader files, no "shaders" directory is present in the archives, compared to the VSBuild packages.

### Expected behavior

The "shaders" directory as well as all the shader files should probably be included in all portable packages.

### Steps to reproduce the behaviour

1. Open MinGW portable package archive
2. Look for shader files
3. Sad face

**Comment by Wengier** [comment]
Direct3D shaders are now added to MinGW portable packages just like the Visual Studio packages. However, you are strongly recommended to use the Windows installer(s) instead, which also includes things like GLSL shaders and TTF fonts etc, for a more complete installation.

**Comment by rebb** [comment]
Thanks :)
