### ISSUE TITLE
"Capture" Menu In Windows Does Not Do Anything

### ISSUE THREAD

**Issue by TheKins** [joncampbell123/dosbox-x#312]
1. Open the latest release build of DOSBox-X for Windows as of this time of writing (windows-20170914-115932).
2. Click the "Capture" menu on the toolbar, and select "Screenshot".
3. Check the folder you placed DOSBox-X in to confirm that nothing has happened.
4. Use the keyboard shortcut for taking screenshots (CTRL-F5)
5. Check the folder you placed DOSBox-X in to confirm that a "capture" folder has been created, and a screenshot saved to it.

**Comment by joncampbell123** [comment]
Does the keyboard shortcut (in the mapper) do anything?

It may be that the code to handle the MENU is broken, but the capture function is functional still.

**Comment by TheKins** [comment]
As mentioned, the keyboard shortcut (CTRL-F5) works fine. It's the menu that doesn't do anything.

Worth noting: This also applies to videos and presumably other forums of capturing, so presumably it's something wrong with the menu.

**Comment by joncampbell123** [comment]
Fixed.
