### ISSUE TITLE
MinGW portable packages don’t include GPL

### ISSUE THREAD

**Issue by Jayman2000** [joncampbell123/dosbox-x#3120]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [ ] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows in general (I was actually running it in Wine, but that’s unimportant)

### What version(s) of DOSBox-X have this bug?

0.83.20

### Describe the bug

[`COPYING`](https://github.com/joncampbell123/dosbox-x/blob/master/COPYING) says
>    You should have received a copy of the GNU General Public License along
>    with this program; if not, write to the Free Software Foundation, Inc.,

The [MinGW portable packages](https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md#windows-packages-installer-or-portable) don’t include a copy of the GPL.

### Expected behavior

I would expect those packages to include a copy of the GPL, just like all the other packages.

### Steps to reproduce the behaviour

1. Download either MinGW portable package: [Win32](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.20/dosbox-x-mingw-win32-20211201234567.zip) or [Win64](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.20/dosbox-x-mingw-win64-20211201234567.zip).
2. Extract it.
3. `grep -ri 'gpl'`

### Used configuration

```ini
Not applicable.
```

### Emulator log

```text
Not applicable.
```

### Additional context

I did find #293 which is similar, but that was more of a feature proposal that, from what I can tell, was accepted (all the other Windows packages include the GPL). This is a bug with the implementation of that feature proposal.

**Comment by Wengier** [comment]
Extra files such as FREECG98.BMP, COPYING and Direct3D shaders are now added to MinGW packages. If you find other packages with missing packages, feel free to report or add them by sending PRs.
