### ISSUE TITLE
No dosbox.conf?

### ISSUE THREAD

**Issue by Muyfa666** [joncampbell123/dosbox-x#313]
There is no dosbox.conf included with the program. How to config my parameters?

**Comment by joncampbell123** [comment]
it uses built-in defaults if no dosbox.conf.

You can have it dump all dosbox.conf to a file by typing:

config -all -wc dosbox.conf

That will create a dosbox.conf from the defaults, with ALL settings listed. There are a lot.

**Comment by Muyfa666** [comment]
Great! Worked perfectly. :-)
