### ISSUE TITLE
CD Audio error; v0.83.20; Win 98SE Japanese

### ISSUE THREAD

**Issue by ShriveledSquirrel** [joncampbell123/dosbox-x#3132]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

Dosbox-X v0.83.20
Windows 98SE, Japanese
Installed following directions shown on: https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-98

Problem: When the game attempts to play music from the CD, gives the error: 

> MMSYSTEM282 The designated parameter goes beyond the bounds of this command.

When I attempt to play the music again, it shows:

> MMSYSTEM265 This alias is already being used by this program. Please use a different name.

When I attempt to play the game without the game.mdf mounted, it shows this upon attempting to play music:

> MMSYSTEM266 Failed to read device. Please make sure the driver is correctly installed.

In the game's readme, it says to run specifically in 256 color and the following:

> This application uses CD-DA as its sound source. You cannot use a media player or CD player at the same time. Please make sure such applications are closed when starting this application.

Error messages were translated by me to English and may not perfectly match official translations. The computer is currently in 256 color. No additional drivers have been installed, changed, or deleted. Minor changes were made to the conf file following completion of the installation guide. Attempts to fix the problem by changing conf file were recorded below.

![DosBoxXWin98SEjpErrors](https://user-images.githubusercontent.com/95885200/145485752-09be3609-a671-4e49-a28d-8bd081a1319b.png)

Win98.conf:

[sdl]
autolock=true

[dosbox]
title=Windows 98
memsize=512

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=auto
cycles=auto
isapnpbios=true

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
IMGMOUNT C hdd.img

#attempted the below, but did not fix problem
#[sblaster] 
#pic unmask irq=true
#[cpu]
#segment limit=false
#cputype=pentium_mmx, 8086, auto
#core=auto, normal
#[ide, primary and secondary]
#cd-rom spinup time     =1000
#cd-rom spindown timeout=1000
#cd-rom insertion delay=4000

**Comment by rderooy** [comment]
I'm reasonably sure the SDW.DLL dialogs are not standard windows, but rather from the application or game your trying to run.

From what I find online the MMSYSTEM282 error may indicate that the CD Audio drive is set to the incorrect value in the Windows Multimedia properties. Can you try the resolution suggested here: https://jeffpar.github.io/kbarchive/kb/160/Q160712/

I assume your mounting the CD-ROM image from a CUE/BIN file type, since it obviously must have CD Audio (redbook) tracks on it?

**Comment by ShriveledSquirrel** [comment]
Unfortunately that did not resolve the issue as it was already pointed at the correct drive. I did attempt all drives regardless. I also attempted mounting both the original .MDF file, and converted the MDF to an ISO and tried that, but the errors remain and music still does not play. The MDF file came with an MDS file, but I am not quite sure what to do with the MDS file.

Thank you though, that was a good idea.

**Comment by rderooy** [comment]
ISO will not help as ISO only supports single-track Data CDs. If the game is trying to use CD Audio it must be a mixed-mode (hybrid) CD containing both Data and Audio tracks. And this is not possible with the ISO format, hence the reason I mentioned CUE/BIN. But MDF/MDS should also support mixed mode CDs, although I have no experience with it.

**Comment by ShriveledSquirrel** [comment]
Sorry if this is a dumb question, but do you have any idea what I do with the MDS file? So like, I attempted to mount both the MDF and MDS file to the same drive through the terminal, but of course it wouldn't accept the MDS file; so then does Windows just not have access to the MDS file when it's looking at the drive? I don't know if it's necessary for it to be able to play the music or not.

I understand that you don't have experience with MDF/MDS, so if you can't answer this question hopefully someone can.

**Comment by rderooy** [comment]
https://en.wikipedia.org/wiki/Media_Descriptor_File explains what MDF/MDS is.

**Comment by ShriveledSquirrel** [comment]
Yeah I read that, I just wasn't too sure what to make of it. I'm not very familiar with what that actually means for me; but as someone unfamiliar with it it looks like it might be related to my problem?

**Comment by maron2000** [comment]
I think the easiest way is to convert your MDF/MDS image to cue+bin format, which is the format DOSBox-X natively supports for mixed mode CDs. 
You may want to try Iso workshop or WinISO to convert your image.

**Comment by ShriveledSquirrel** [comment]
> I think the easiest way is to convert your MDF/MDS image to cue+bin format, which is the format DOSBox-X natively supports for mixed mode CDs. You may want to try Iso workshop or WinISO to convert your image.

Thank you, that was a good idea but perhaps there is something wrong with my file as neither ISO Workshop nor WinISO were able to recognize the file. I'm not sure. I was able to find a PC98 version of it, which doesn't have this issue, so I suppose my issue is resolved.
