### ISSUE TITLE
Guide:Managing image files in DOSBox‐X MacOS

### ISSUE THREAD

**Issue by jonasgit** [joncampbell123/dosbox-x#3134]
Regarding "Accessing image files from MacOS?", I suggest something like (someone fluent in english may wish to make corrections):
Using harddisk images in MacOS

MacOS (at least 12.0.1) has built in support for images containing regular format as used by Windows 98 for example (traditional partition table and filesystem FAT16). In a terminal type:

  **hdiutil attach filename.IMG**

You get a report showing the result. Please take note of device names reported.
Now the image is available both in terminal and in Finder as /Volumes/Untitled or similar.
When finished remember to detach using devicename reported above:

  **hdiutil detach /dev/diskX**

Detaching can also be done in Finder by clicking on eject button along the name.

Also, one tool which is able to open harddisk images is 7-Zip.

**Comment by rderooy** [comment]
Thanks for the information. Could you provide some screenshots of where you mount and unmount an image file with hdiutil? Are you able to also mount FAT32 images?

**Comment by jonasgit** [comment]
Yes on both questions
<img width="1440" alt="Skärmavbild 2021-12-11 kl  18 17 11" src="https://user
<img width="1440" alt="Skärmavbild 2021-12-11 kl  18 18 38" src="https://user-images.githubusercontent.com/379642/145685692-02ab07b2-2ccd-4080-ac6f-655b12f767b4.png">
-images.githubusercontent.com/379642/145685690-fcc0c8f2-d90e-4b83-bc6d-792d5a52ea3a.png">
.

**Comment by rderooy** [comment]
Thanks. From what I find online, `hdiutil` should also work for ISO images. But can you not simply open an ISO image directly from the Finder like you can from the file manager on Linux and Windows?

Also, I guess you can also mount simple floppy disk images the same way with 'hdiutil'?

**Comment by jonasgit** [comment]
I am new to MacOS, this is how I learn. You are absolutely right. I tried to open all of them in Finder and it works, ie all of ISO, IMG för both harddrive and floppy (1.44M).
hdiutil is probably what is happening behind the GUI of Finder.

**Comment by rderooy** [comment]
@jonasgit I have updated the draft wiki, you can have a look here: https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X

The draft wiki will become the new wiki with the next DOSBox-X release which should be early next month.

If you have further suggestions for improvements, let me know. For instance, I have provided detailed instructions on using 'hdiutil' for mounting HDD images, but not so for floppy or CD image files as I did not have a sample output. Likewise I don't know about mounting CUE+BIN or MDF images on macOS.

**Comment by jonasgit** [comment]
@rderooy The draft looks fine, thanks. This issue can be closed as far as I am concerned.
