### ISSUE TITLE
Is there a way to "ignore" files when loading DOSBox ? Similar to .gitignore

### ISSUE THREAD

**Issue by rebb** [joncampbell123/dosbox-x#3138]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

Is there a way to ignore files, so they don't show up inside DOSBox, even though they may exist in the directory that DOSBox has loaded ?

Something similar to .gitignore maybe ? Or something in a .conf section ?

Just wondering. It's not very useful, but may be nice if someone wants to tidy up what they see inside DOSBox, like stray .conf files or similar. I guess one could set the files to have the hidden attribute otherwise.

**Comment by Wengier** [comment]
FYI: You can hide files on the Z drive with the “drive z hide files” option.

For mounted local drives, you may consider loading overlay drives for them (with `-t overlay` option for MOUNT command), and then delete files you do not want to see in DOSBox-X. These files will not be removed from the original directory but will no longer be visible in DOSBox-X as long as you load the same overlay drive each time DOSBox-X starts.

**Comment by Wengier** [comment]
Alternatively, you can set hidden attributes for files and directories with the ATTRIB command, e.g. ATTRIB +H [files], and these files will no longer be visible when you execute for example DIR command. Some programs may see them though with this approach.
