### ISSUE TITLE
Support MAME-formatted HDI images

### ISSUE THREAD

**Issue by einstein95** [joncampbell123/dosbox-x#3140]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Arch Linux

### What version(s) of DOSBox-X have this bug?

0.83.18

### Describe the bug

After formatting an HDI image created using NHC and formatted using MAME's PC-9801RS driver with MS-DOS 6.22, I am left with an HDI image that, while having a valid PC-98 partition label according to `parted` (after stripping the header), fails to mount in DOSBox-X. This occurs even if I install MS-DOS completely onto the HDI image.

DOSBox-X claims in the log that it is not formatted, and just saying "Cannot create drive from file." in the window.

I have attached the HDI image, it will boot in MAME to a DOS prompt.
[test.zip](https://github.com/joncampbell123/dosbox-x/files/7704717/test.zip)

parted output:
```
Model:  (file)
Disk /path/to/test.img: 51609600B
Sector size (logical/physical): 512B/512B
Partition Table: pc98
Disk Flags: 

Number  Start   End        Size       File system  Name         Flags
 1      65536B  39387135B  39321600B               MS-DOS 6.20  boot
```

DOSBox-X log:
```
LOG: IDE: index -1 slave=0
LOG: Image file has .HDI extension, assuming HDI image and will take on parameters in header.
LOG: HDI header: sectorsize is 512 bytes/sector, header is 4096 bytes, hdd size (plus header) is 51609600 bytes
LOG: HDI: Geometry is C/H/S 100/16/63
LOG: FAT: Partition type is IPL1 (PC-98)
LOG: Using IPL1 entry 18446744073709551615 name 'MS-DOS 6.20     ' which starts at sector 1008
LOG: Boot sector appears to have been created by FDISK.EXE but not formatted
```

### Steps to reproduce the behaviour

1. Extract the zip
2. In DOSBox-X, do `imgmount a test.hdi`

**Comment by grapeli** [comment]
>DOSBox-X claims in the log that it is not formatted, and just saying "Cannot create drive from file." in the window.

You must indicate where your disk image is located. Specifying its location by entering the access path (to host or local).

>2. In DOSBox-X, do imgmount a test.hdi

You do not have this disk image on the "**z:**" drive. Hence the message:
**Cannot create drive from file.**

Try this:
`dosbox-x -c "imgmount 2 /tmp/test.hdi -size 512,63,16,100 -t hdd -fs none" `

**Comment by einstein95** [comment]
> You must indicate where your disk image is located. Specifying its location by entering the access path (to host or local).

I'm launching dosbox-x in the folder with the hard drive images.

> Try this:
> `dosbox-x -c "imgmount 2 /tmp/test.hdi -size 512,63,16,100 -t hdd -fs none" `

Yes, doing `imgmount 2 test.hdi` works, however it does not mount any partitions in the image

**Comment by maron2000** [comment]
I mounted your image on Anex86 and np21, both PC-98 emulators, but both fails to boot.
I think it is a problem of MAME rather than Dosbox-x.

**Comment by joncampbell123** [comment]
Can you try mounting your image with the debug console open?

According to the debug console on mine, it's saying your HDI is formatted with C/H/S 100/16/63, then the IPL1 table says that the MS-DOS partition starts at CHS 1/0/0 and ends at CH/S 6/0/0. From that, it computes that the MS-DOS partition starts at sector 1008 which is clearly wrong (I see the FAT boot sector at sector 136 in the image aka file offset 0x12000 (remember, subtract 4096 because HDI header)). HDI header says 512 bytes per sector. The FAT driver finds nothing, and it fails.

PC-98 formats require the correct disk geometry because the partition table uses C/H/S values. It does not provide linear sector numbers. If the geometry is wrong, or the C/H/S values were generated from incorrect geometry, then it will not work.

IBM PC MBR records are easier to support without geometry because they DO provide a linear sector number alongside the C/H/S values. PC-98 IPL1 tables do not provide linear sector numbers.

**Comment by maron2000** [comment]
I successfully mounted and booted `test.hdi` by the geometry shown in the figure below.
It only recognizes 40MB despite the image is 50MB.
![command_000](https://user-images.githubusercontent.com/68574602/145908912-18834d49-f577-4f85-b3c2-3c8adc923a31.png)

**Comment by einstein95** [comment]
So taking what @maron2000 noted and modifying the image header to reflect that geometry has helped and... may have found a different bug.
```
LOG:   18665293 DEBUG EXEC:Parsing command line: imgmount a test.hdi
LOG:   18665296 DEBUG DOSMISC:DOS=HIGH, XMS enabled, A20 gate disabled. Reenabling A20 gate on INT 21h call.
LOG:   18665296 DEBUG MISC:MEM_A20_Enable(1)
LOG:   18665296       EXEC:Execute Z:\SYSTEM\imgmount.COM 0
LOG:   18665296       FILES:file open command 0 file Z:\SYSTEM\imgmount.COM
LOG:   18665300 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x0048) = 0x08ca-0x0911
LOG:   18665300 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x96ec) = 0x0913-0x9ffe
LOG:   18665307 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x0913) blocks=0x0040
LOG: IDE: index -1 slave=0
LOG:   18665310 DEBUG DOSMISC:DOS_GetMemory(0x0004 pages,"imgDTASeg") = 0xc004
LOG: Image file has .HDI extension, assuming HDI image and will take on parameters in header.
LOG: HDI header: sectorsize is 512 bytes/sector, header is 4096 bytes, hdd size (plus header) is 51609600 bytes
LOG: HDI: Geometry is C/H/S 17/8/1000
LOG: FAT: Partition type is IPL1 (PC-98)
LOG:   18665310 DEBUG DOSMISC:IPL #0: boot=1 active=1 startchs=1/0/0 endchs=600/0/0 'MS-DOS 6.20     '
LOG: Using IPL1 entry 18446744073709551615 name 'MS-DOS 6.20     ' which starts at sector 8000
LOG: Boot sector appears to have been created by FDISK.EXE but not formatted
```
vs.
```
LOG:   92384292 DEBUG EXEC:Parsing command line: imgmount a test.hdi -size 512,17,8,1000
LOG:   92384295       EXEC:Execute Z:\SYSTEM\imgmount.COM 0
LOG:   92384295       FILES:file open command 0 file Z:\SYSTEM\imgmount.COM
LOG:   92384299 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x0048) = 0x08ca-0x0911
LOG:   92384299 DEBUG DOSMISC:DOS_AllocateMemory(blocks=0x96ec) = 0x0913-0x9ffe
LOG:   92384306 DEBUG DOSMISC:DOS_ResizeMemory(seg=0x0913) blocks=0x0040
LOG: IDE: index -1 slave=0
LOG: Image file has .HDI extension, assuming HDI image and will take on parameters in header.
LOG: HDI header: sectorsize is 512 bytes/sector, header is 4096 bytes, hdd size (plus header) is 51609600 bytes
LOG: HDI: Geometry is C/H/S 17/8/1000
LOG: FAT: Partition type is IPL1 (PC-98)
LOG:   92384309 DEBUG DOSMISC:IPL #0: boot=1 active=1 startchs=1/0/0 endchs=600/0/0 'MS-DOS 6.20     '
LOG: Using IPL1 entry 18446744073709551615 name 'MS-DOS 6.20     ' which starts at sector 136
LOG:   92384309 DEBUG DOSMISC:FAT: BPB says 17 sectors/track 8 heads 1024 bytes/sector
LOG: Disk indicates 512 bytes/sector, FAT filesystem indicates 1024 bytes/sector. Ratio=2:1 shift=1
LOG: Using logical sector size 1024, offset by 0 physical sectors
LOG:   92384309 DEBUG DOSMISC:FAT driver: Using absolute sector access
LOG: Mounted FAT volume is FAT12 with 2468 clusters
LOG:   92384309       FILES:file search attributes 8 name A:\*.*
LOG:   92384313       DOSMISC:DIRCACHE: Set volume label to $INSTAL$$$$
```

So apparently specifying `-size` changed the IPL1 parsing?

**Comment by joncampbell123** [comment]
@einstein95 Yes. The IBM PC partition table lists both C/H/S and LBA sector numbers. The IPL1 partition table used by PC-98 lists only C/H/S numbers, and is highly dependent on having the correct disk geometry to make sense of correctly.

https://github.com/gnu-mirror-unofficial/parted/blob/master/libparted/labels/pc98.c#L85

**Comment by joncampbell123** [comment]
Although the debug output shown shows me that the debug messages need some bug fixing, and printf() style typecasting. There aren't that many IPL1 entries.

**Comment by maron2000** [comment]
@einstein95 The log output you have shown is kind of weird.
C/H/S is 17/8/1000 in your post, which should be 1000/8/17.
You may want to try the latest version (0.83.20).
I modified the .hdi file you posted as attached and works flawlessly. 
I confirmed that the image can be booted on np21 as well.
[test3.zip](https://github.com/joncampbell123/dosbox-x/files/7708757/test3.zip)

```
IDE: index 0 slave=0
Image file has .HDI extension, assuming HDI image and will take on parameters in header.
HDI header: sectorsize is 512 bytes/sector, header is 4096 bytes, hdd size (plus header) is 51609600 bytes
HDI: Geometry is C/H/S 100/8/17
FAT: Partition type is IPL1 (PC-98)
Using IPL1 entry 4294967295 name 'MS-DOS 6.20     ' which starts at sector 136
Disk indicates 512 bytes/sector, FAT filesystem indicates 1024 bytes/sector. Ratio=2:1 shift=1
Using logical sector size 1024, offset by 0 physical sectors
Mounted FAT volume is FAT12 with 2468 clusters
Mapping BIOS DISK C/H/S 100/8/17 as IDE 100/8/17
```

**Comment by grapeli** [comment]
@maron2000 
> I successfully mounted and booted `test.hdi` by the geometry shown in the figure below. It only recognizes 40MB despite the image is 50MB.

The system also starts up.
`dosbox-x -set machine=pc98 -c "imgmount c ./test.hdi -size 512,17,8,1000" -c "boot c:"`
![guest os_000](https://user-images.githubusercontent.com/452325/145957810-55b7e4ca-5e57-460f-a295-8dc7764da079.png)

**Comment by maron2000** [comment]
@grapeli Thank you for confirming.
We have to be reminded that the Cylinder value (1000 for `-size 512,17,8,1000`) is a tentative value,
and should be changed to an adequate value for a 50MB image.
If I understand correctly, I believe it would be 741 (=100\*16\*63/8/17).
