### ISSUE TITLE
[PC-98] Can't load saved states after restarting Windows

### ISSUE THREAD

**Issue by fonic** [joncampbell123/dosbox-x#3144]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

0.83.20

### Describe the bug

While playing _Rusty_, I noticed that saved states can only be loaded if _Windows has not been restarted_ between saving and loading. Once Windows is restarted, trying to load a saved state results in crashing DOSBox-X (no error message, window just closes).

For my playthrough, I resorted to hibernating/resuming Windows between sessions, which does not seem to affect saving/loading.

### Expected behavior

It should be possible to load a previously saved state even if Windows has been restarted between loading and saving a state.

### Steps to reproduce the behaviour

1. Start DOSBox-X in PC-98 mode
2. Load _Rusty_
3. Begin Game
4. Save state when in stage/level
5. Close DOSBox-X
6. Restart Windows
7. Start DOSBox-X in PC-98 mode
8. Load _Rusty_
9. Load previously saved state -> crash

### Used configuration

```ini
[sdl]
mapperfile = dosbox-x.map

[cpu]
cycles = 6000

[autoexec]
imgmount 3 rusty.hdi -t hdd -fs none
boot -l d
```

### Emulator log

[dosbox-x-mingw-win64-20211201234567.log](https://github.com/joncampbell123/dosbox-x/files/7729656/dosbox-x-mingw-win64-20211201234567.log)
[dosbox-x-vsbuild-win64-20211130230328.log](https://github.com/joncampbell123/dosbox-x/files/7729657/dosbox-x-vsbuild-win64-20211130230328.log)

**Comment by Wengier** [comment]
Can you try MinGW builds (instead of Visual Studio builds) and see if they work in this case?

**Comment by fonic** [comment]
I've now set this up within a Windows 10 VM for further testing and to provide further information without sacrificing my saved states.

Behavior within the Windows 10 VM is exactly the same: save state, restart OS, load state -> crash

I tested these two builds, both exhibit the same issue:
dosbox-x-mingw-win64-20211201234567
dosbox-x-vsbuild-win64-20211130230328

I've also added logs to my original post.

**Comment by yetmorecode** [comment]
So I've been able to reproduce this on my machine. It looks like this is some issue with the scaler at:

https://github.com/joncampbell123/dosbox-x/blob/ad7f6c3def0b54340a7f3f9f60d2086d7a89d1da/src/gui/render.cpp#L289

```
Exception thrown: write access violation.
**cache** was 0x4DC36E0. occurred
```

```
>	dosbox-x.exe!RENDER_FinishLineHandler(const void * s) Line 292	C++
 	dosbox-x.exe!VGA_DrawSingleLine(unsigned int __formal) Line 3000	C++
 	dosbox-x.exe!PIC_RunQueue() Line 745	C++
 	dosbox-x.exe!Normal_Loop() Line 350	C++
 	[Inline Frame] dosbox-x.exe!DOSBOX_RunMachine() Line 630	C++
 	dosbox-x.exe!CALLBACK_RunRealInt(unsigned char intnum) Line 209	C++
 	dosbox-x.exe!DOS_Shell::Execute(char * name, const char * args) Line 1497	C++
 	dosbox-x.exe!DOS_Shell::DoCommand(char * line) Line 274	C++
 	dosbox-x.exe!DOS_Shell::ParseLine(char * line) Line 457	C++
 	dosbox-x.exe!DOS_Shell::Run() Line 907	C++
 	dosbox-x.exe!SHELL_Run() Line 1890	C++
 	dosbox-x.exe!VM_Boot_DOSBox_Kernel() Line 10387	C++
 	dosbox-x.exe!BIOS::cb_bios_boot__func() Line 9375	C++
 	dosbox-x.exe!Normal_Loop() Line 372	C++
 	dosbox-x.exe!DOSBOX_RunMachine() Line 631	C++
 	dosbox-x.exe!SDL_main(int argc, char * * argv) Line 15271	C++
 	dosbox-x.exe!main(int argc, char * * argv) Line 284	C
 	dosbox-x.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * hPrev, char * szCmdLine, int sw) Line 371	C
 	[External Code]	
 	kernel32.dll![Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	Unknown
```

```
&scalerSourceCache	                                0x03055e10 {dosbox-x.exe!scalerSourceCache_t scalerSourceCache} scalerSourceCache_t *
sizeof(scalerSourceCache)	                        0x00a8c000 unsigned int
cache	                                                0x04dc36e0 {0x00000000} unsigned int *
(char*)&scalerSourceCache + sizeof(scalerSourceCache)	0x03ae1e10 ""	char *
```

**Comment by yetmorecode** [comment]
Those cases are easy to detecd after all. I suppose somewhere the between changing modes (which the game seems to do a lot), the cache is not properly reset.. 
```
static void RENDER_FinishLineHandler(const void * s) {
    if (s) {
        const Bitu* src = (Bitu*)s;
        Bitu* cache = (Bitu*)(render.scale.cacheRead);

        if ((char*)cache + render.src.start < (char*)&scalerSourceCache + sizeof(scalerSourceCache)) {
            for (Bitu x = render.src.start; x > 0; x--) {
                // cache valid?
                cache[0] = src[0];
                src++;
                cache++;
            }
        }
        else {
            LOG_MSG("out of bounds access in scaler cache\n");
        }
        
    }
    render.scale.cacheRead += render.scale.cachePitch;
}
```
