### ISSUE TITLE
TTF output is not as fast as it was.

### ISSUE THREAD

**Issue by grapeli** [joncampbell123/dosbox-x#3148]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

linux

### What version(s) of DOSBox-X have this bug?

sdl2

### Describe the bug

This [commit](https://github.com/joncampbell123/dosbox-x/commit/c6d7e95e57e90495d45f589ee49a8fda9fdea2a9) **init TTF color scheme** - affects the performance change.

### Expected behavior

It would be better if you could disable color scheme initialization in the configuration.

### Steps to reproduce the behaviour

How to test?
Download fractinit and runtime.
https://fractint.org/ftp/current/dos/fradev.zip
https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/devel/runtime.zip

Run version (c6d7e9):
`./dosbox-x -set output=ttf -c "mount c ./test" -c "c:" -c "cd fractint" -c "runtime fractint @FRACT19.PAR/NEWTON-REAL video=af4 textsafe=no virtual=no batch=yes overwrite=yes"
`
Repeat for the previous version (eee8a7).

The difference on my hardware is ~**16%**.

Linux perf shows what additional functions come:
```
c6d7e9-------------------------------------------------------eee8a7
1.50% SDL_MapSurface (SDL_UpperBlit_REAL, SDL_LowerBlit_REAL) 0.07%
0.94% TTF_RenderUNICODE_Shaded 0.05%
```

**Comment by Wengier** [comment]
@grapeli The said commit ("init TTF color scheme" in https://github.com/joncampbell123/dosbox-x/commit/c6d7e95e57e90495d45f589ee49a8fda9fdea2a9) was made to fix an issue as the result of an earlier commit ("Update TTF screen by executing palette change function in int 10h" in https://github.com/joncampbell123/dosbox-x/commit/3094559a9f9a27e85503621e8c0e0b6b1a1d96a2) by @nanshiki. I noticed that if I did not do the color scheme initialization, then if I run programs like VIEW, WIPE, etc in PC-Tools 9, then the screen color palette will be corrupted in the TTF output since the latter commit. This was affected in e.g. DOSBox-X version 0.83.18, see a screenshot below for running VIEW from PC-Tools 9:
 
![image](https://user-images.githubusercontent.com/8216923/146469517-62497347-6a1b-4654-b64f-8083f5538259.png)

And after the "init TTF color scheme" change:

![image](https://user-images.githubusercontent.com/8216923/146469479-fcc8f04b-c1c8-406a-a5ec-854e84a139da.png)

Perhaps @nanshiki knows a better way to fix the above issue.

**Comment by grapeli** [comment]
@Wengier 
VIEW it also works fine under dosbox-x version eee8a7. You just need to initiate the color scheme yourself.
`dosbox-x -set output=ttf -set "ttf colors=#000000 #0000aa #00aa00 #00aaaa #aa0000 #aa00aa #aa5500 #aaaaaa #555555 #5555ff #55ff55 #55ffff #ff5555 #ff55ff #ffff55 #ffffff"
`It is not too complicated. Installing PC Toools is much more complicated.

I don't mind the current default state. I only propose the possibility of restoring the previous one as non-default. The loss of performance is an important argument from my perspective. Not losing what was already there.

The `ttf` output, apart from the benefits known to all, also has another important feature. This is the fastest video output under dosbox-x (sorry I was wrong - IT WAS). In conjunction with `videodriver=dummy`, they can be classified as RAW power dosbox-x. If someone intends to use dosbox-x for automated batch processing, such as compiling, compressing, etc. then I strongly recommend using it `-set videodriver=dummy -set output=ttf`.

**Comment by grapeli** [comment]
For now, I can undo this commit without any problems.

**Comment by grapeli** [comment]
For now, I can undo this commit without any problems.

**Comment by Wengier** [comment]
@grapeli What if you try the latest code and see how it works?

**Comment by grapeli** [comment]
@Wengier 
It is very good now.

Even slightly faster than with the undo of this [commit](https://github.com/joncampbell123/dosbox-x/commit/c6d7e95e57e90495d45f589ee49a8fda9fdea2a9).
Thanks.

**Comment by grapeli** [comment]
@Wengier 
This report is a false positive. So related to this commit `c6d7e9` with a decrease in the performance of the ttf output.

A mysterious case. Before sending the bug report, I repeated the fractint test at least three times for each of the `c6d7e9` and `eee8a7` builds (as well as the latest code). Each time the results were clear. 

Yesterday and today I cannot reproduce it at all. These binaries are built on top of the static SDL2 library. I really don't know how to explain this.

Sorry for the confusion.

**Comment by grapeli** [comment]
@Wengier 
This report was correct. I forgot, I got goofs. It did not apply to `videodriver=dummy`. It only happened for the default SDL2 output. In my case `x11`.

Your yesterday's [patch (fix)](https://github.com/joncampbell123/dosbox-x/commit/2aea9904c441347456ff11957f997134ba6ef75d) actually restored the performance of `ttf` output (for the default SDL2 video output) to that of commit `eee8a7`. I confirm it now with 100% certainty.

Thanks again.
