### ISSUE TITLE
Truetype Output crash in PC-98 mode

### ISSUE THREAD

**Issue by Eirle** [joncampbell123/dosbox-x#3159]
Hello, I'm using DOSbox-X 0.83.20 (SDL2) with the built-in Sarasa Gothic font for the TTF output, but in PC-98 mode it just crash.
It seems to be a bug more than a incompatibility.
![ttf_crash](https://user-images.githubusercontent.com/67406344/146827229-8ee20d03-b0b7-49a6-8f4b-b60b48a0291e.png)
Aaaand...it crash.
Any idea?

**Comment by maron2000** [comment]
Hmm, that's strange. I don't see any flaws.
You may want to check your ttf and font settings.
Works with SDL1 version as well.
![pc98](https://user-images.githubusercontent.com/68574602/146858252-081fa464-cda5-4435-90b3-7689021df4b9.png)

**Comment by Wengier** [comment]
@Eirle It works fine for me too, either SDL1 or SDL2 builds. Perhaps you can post the config file you used and see what is going on.

**Comment by Eirle** [comment]
> @Eirle It works fine for me too, either SDL1 or SDL2 builds. Perhaps you can post the config file you used and see what is going on.

[dosbox-x.txt](https://github.com/joncampbell123/dosbox-x/files/7757706/dosbox-x.txt)

Everything seems right for me...

**Comment by Eirle** [comment]
Is there any way I can have a debug logfile? Maybe it can to recognize the problem.

**Comment by Wengier** [comment]
@Eirle Thanks for posting the config file. I checked it and found that the crash occurred in the following config combination:

``output=ttf``
``machine=pc98``
``dosvfunc=true``

I fixed this by disabling ``dosvfunc`` for the PC-98 mode; please check out the updated Windows SDL2 build:

* [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by Wengier** [comment]
@Eirle You can have a debug logfile with the config option ``logfile`` in [log] section, e.g. ``logfile=dosbox-x.log``. This issue is already fixed, but you may want to have a debug logfile for other purposes.

**Comment by Eirle** [comment]
> @Eirle You can have a debug logfile with the config option `logfile` in [log] section, e.g. `logfile=dosbox-x.log`. This issue is already fixed, but you may want to have a debug logfile for other purposes.

Thanks, this issue shall now be closed :D

**Comment by Wengier** [comment]
Thanks for the confirmation. Closing.
