### ISSUE TITLE
Increase windows environment variable space 

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3163]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

dear sir,
Increase windows environment variable space  in DOSBOX-X.

**Comment by Wengier** [comment]
You can increase the environment variable size in DOSBox-X with the advanced config option ``shell environment size`` in [dosbox] section of dosbox-x.conf. The default size is 720 bytes, but you can for example increases it to 2048 bytes with the setting:

``shell environment size = 2048``

Hope this helps.

**Comment by Arthur3032** [comment]
ok, Thank you very much .
