### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by aaron-is-the-best2114** [joncampbell123/dosbox-x#3167]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Raspberry pi os Buster 32-bit

### What version(s) of DOSBox-X have this bug?

N/A ?

### Describe the bug

I was trying to install Windows 98 on my Raspberry Pi 4 8GB with this guide, https://magpi.raspberrypi.com/articles/run-windows-98-on-raspberry-pi-with-dosbox-x and when I ran the ./build command when installing dosbox-x and got an error which cause it not to install properly so I tried it again and still got the same error. 

### Expected behavior

I expected it to install as it should and not have any problems.  

### Steps to reproduce the behaviour

1. I typed these commands 

`sudo apt install automake libncurses-dev nasm libsdl-net1.2-dev libpcap-dev libfluidsynth-dev ffmpeg libavdevice58 libavformat-* libswscale-* libavcodec-*`
`git clone https://github.com/joncampbell123/dosbox-x.git`
`cd dosbox-x`
`./build`

2. The ./build script started this command: mv -f $depbase.Tpo $depbase.Po
3. 5 minutes later I ended up with this: 

depbase=`echo output_tools_xbrz.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -I../../src -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wno-deprecated-declarations   -Wconversion-null   -Wsign-promo   -Wlogical-op   -pedantic   -Wunused   -Wextra   -Wall   -I/home/pi/dosbox-x/vs/sdl/linux-host/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/home/pi/dosbox-x -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include/SDL -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/arm-linux-gnueabihf  -g -std=gnu++14  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/pi/dosbox-x -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -MT output_tools_xbrz.o -MD -MP -MF $depbase.Tpo -c -o output_tools_xbrz.o output_tools_xbrz.cpp &&\
mv -f $depbase.Tpo $depbase.Po
rm -f liboutput.a
ar cru liboutput.a output_direct3d.o output_opengl.o output_surface.o output_surface_sdl2.o output_surface_sdl.o output_tools.o output_tools_xbrz.o 
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib liboutput.a
make[4]: Leaving directory '/home/pi/dosbox-x/src/output'
make[3]: Leaving directory '/home/pi/dosbox-x/src/output'
make[3]: Entering directory '/home/pi/dosbox-x/src'
depbase=`echo dosbox.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I..  -I../include "-DRESDIR=\"/usr/share/dosbox-x\"" -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wno-deprecated-declarations   -Wconversion-null   -Wsign-promo   -Wlogical-op   -pedantic   -Wunused   -Wextra   -Wall   -I/home/pi/dosbox-x/vs/sdl/linux-host/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/home/pi/dosbox-x -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include/SDL -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/arm-linux-gnueabihf  -g -std=gnu++14  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/pi/dosbox-x -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -MT dosbox.o -MD -MP -MF $depbase.Tpo -c -o dosbox.o dosbox.cpp &&\
mv -f $depbase.Tpo $depbase.Po
dosbox.cpp: In function ‘void DOSBOX_SetupConfigSections()’:
dosbox.cpp:1190:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
 void DOSBOX_SetupConfigSections(void) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
g++  -g -std=gnu++14  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/pi/dosbox-x -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include -I/home/pi/dosbox-x/vs/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L   -L/home/pi/dosbox-x/vs/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a misc/libmisc.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a libs/decoders/internal/libopusint.a aviwriter/libaviwriter.a  libs/xBRZ/libxbrz.a  libs/fluidsynth/libfluidsynth.a -lasound -lm -ldl -lpthread -L/home/pi/dosbox-x/vs/sdl/linux-host/lib -Wl,-rpath,/home/pi/dosbox-x/vs/sdl/linux-host/lib -lSDL -lX11 -lXext -lpthread -ltinfo -lfreetype -lSDL_net -lz -lpng -lz -lpcap -lX11 -lXrandr -lfluidsynth -lavcodec -lavformat -lavutil -lswscale -lavcodec -lGL
/usr/bin/ld: hardware/serialport/libserial.a(misc_util.o): in function `enet_time_get':
/home/pi/dosbox-x/src/hardware/serialport/../../../include/enet.h:5174: undefined reference to `__atomic_load_8'
/usr/bin/ld: /home/pi/dosbox-x/src/hardware/serialport/../../../include/enet.h:5186: undefined reference to `__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:469: dosbox-x] Error 1
make[3]: Leaving directory '/home/pi/dosbox-x/src'
make[2]: *** [Makefile:529: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/dosbox-x/src'
make[1]: *** [Makefile:400: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/dosbox-x'
make: *** [Makefile:333: all] Error 2
pi@raspberrypi4:~/dosbox-x $

**Comment by Wengier** [comment]
Can you try add the atomic library via option ``-latomic`` to the final g++ compilation line and see how it works?

**Comment by maron2000** [comment]
Hi, it seems that depending on the version of gcc, you have to explicitly add `-latomic` option,
https://github.com/Haivision/srt/issues/2048#issuecomment-907284580

**Comment by Wengier** [comment]
I just made a change to the configure script trying to conditionally add the -latmoic option. You can try if the code works for you.

**Comment by aaron-is-the-best2114** [comment]
> I just made a change to the configure script trying to conditionally add the -latmoic option. You can try if the code works for you.

The Build script is now successful and I am able to run dosbox-x now. Thank you for your help.

**Comment by Wengier** [comment]
Thanks for the confirmation. Closing.
