### ISSUE TITLE
How to launch DOSBox-X without changing the current host folder

### ISSUE THREAD

**Issue by AlejandroSdeL** [joncampbell123/dosbox-x#3170]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

Hi.  I would like to run DB-X from a batch file without changing the current host folder.  If I use `\DOSBox-X\dosbox-x.exe` the program asks for a folder.  If I use `\DOSBox-X\dosbox-x.exe /nopromptfolder`, the program does not ask for a folder, but a warning appears ("Could not load language message file").  Even that, the default configuration file (which I assume is `\DOSBox-X\dosbox-x.conf`) is honored.  I do not know whether other setting are lost because of running the program from outside its installation folder.  Then two questions:

1. How to launch DB-X from any folder, obtaining the same virtual machine (except the current host folder) that is obtained when the program is launched from its installation folder?
2. Why the default configuration file is loaded when the program is launched from any folder, while the language file is missing?

Thanks.

**Comment by Wengier** [comment]
You can use the ``-defaultdir`` option to specify a working directory for DOSBox-X, e.g.

``\DOSBox-X\dosbox-x -defaultdir \DOSBox-X``

If you don't use this option, DOSBox-X will search for many paths for the config file, but it will not be the working directory, and the language file search is more limited than the config file search.

Hope this helps.

**Comment by AlejandroSdeL** [comment]
Yeah, thank you for your answer.   Almost what I wanted.  I would like to point out that with `\DOSBox-X\dosbox-x -defaultdir \DOSBox-X` it seems that the current host folder within the emulation is `\DOSBox-X,` while with `\DOSBox-X\dosbox-x -nopromptfolder` the folder is the original host folder (besides the already mentined fact that the language file is missing).  Anyway I will not use the current host folder within the emulation, so I am fine with this difference.

I assume that it is not possible to specify the folder where the language file is located.  I mean, for the configuration file I may use `\DOSBox-X\dosbox-x -conf \DOSBox-X\dosbox-x.conf`, but no similar option exists for the language file (at least by now).  Please let me know if I am wrong.

**Comment by Wengier** [comment]
You can of course specify a language file too, with the ``-lang`` option, e.g.

``\DOSBox-X\dosbox-x -conf \DOSBox-X\dosbox-x.conf -lang \DOSBox-X\mylang.lng``

But if you don't specify the ``-defaultdir`` option, any other paths specified in the config file will be relative to the original host folder.

**Comment by AlejandroSdeL** [comment]
Great.  Thanks.
