### ISSUE TITLE
How to adjust the cursor flashing speed

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3171]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

dear sir,
How to adjust the cursor flashing speed, when CPU in Turbo mode, flashing too fast, will be stressful

**Comment by Wengier** [comment]
If you are in the TTF mode, you can adjust its speed with the “blinkc” option, whose value is between 1 (fastest) and 7 (slowest), or 0 for no cursor. It can be changed with CONFIG -set command at runtime too. Hope this helps.

**Comment by Arthur3032** [comment]
ok, Thank You.

**Comment by curvedlinee** [comment]
i tried and testing turbo=true

how can i control the scrolling speed and the cursor movement speed?
there seems to be no middle of pages except top and end

**Comment by Wengier** [comment]
The setting ``turbo=true`` increases the emulation speeds in all directions. If you want to type something using keyboard, try temporarily disable ``turbo=true`` for now. Hope this helps.

**Comment by Wengier** [comment]
I think it is probably better to add a config option to automatically stop the Turbo mode when a keyboard input is detected. Please try the updated DOSBox-X Windows build:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
