### ISSUE TITLE
Use of DOSBox-X code for RetroWave OPL3 support in ScummVM

### ISSUE THREAD

**Issue by NMIError** [joncampbell123/dosbox-x#3173]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

I'm one of the ScummVM developers and I've been working on supporting the RetroWave OPL3 in ScummVM. I've based this code on the DOSBox-X code for integrating this sound card. You can view the draft PR here: https://github.com/scummvm/scummvm/pull/3583

Do you have any objections to us using your code for our project? If not, how would you like us to credit you in the source files?

**Comment by Wengier** [comment]
I don't see there are any objections for porting the RetroWave OPL3 code to your project. You can mention in the source files/documentation that the code is ported from the DOSBox-X project. ScummVM is definitely a great project too.

**Comment by NMIError** [comment]
Thank you very much! I use DOSBox-X a lot for checking the original behavior of games; it's great!
The source files currently mention: "Based on RetroWave OPL3 integration code of DOSBox-X" . Is this sufficient?

**Comment by Wengier** [comment]
I think it should be fine. Thanks for your support!
