### ISSUE TITLE
Planned Pentium III support?

### ISSUE THREAD

**Issue by PythonBlue** [joncampbell123/dosbox-x#3179]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What you want

First of all, I must say that, having found this emulator recently, I'm impressed with the open source effort. Even managed to find a way to get MIDI input working via an internet connection courtesy of the pcap library, though I'll delve into that another time unless asked.

That being said, one reason I took an interest was to emulate an old Windows 98 MIDI driver, which, judging from my additional experiments in the horribly sluggish UTM/QEmu, seem to require a Pentium III processor for some of the included sounds. I realize Pentium II support was only just rolled out, so I don't expect this to be worked on any time soon: just am curious if this is a planned feature.

### Describe alternatives you've considered

I realize this might be a fringe case, especially insofar as how I'm using DosBox-X. For that matter, the most responsive alternative I found using said MIDI driver, including support for the sounds of concern, was VMWare Fusion, an alternative I'd prefer to avoid long-term due to VMWare's apparent refusal to support Intel emulation on Apple Silicon.

### Additional context

Not that it should matter beyond the scope of emulated system requirements, but the MIDI program I'm trying to get fully functional is the VL Virtual Acoustic plugin for Yamaha's S-YXG100. Doubt it's a licensing issue, because I even went as far as copying related system files from my VMWare setup, with no luck.

**Comment by joncampbell123** [comment]
Pentium II was fairly easy to add in that you take pentium_pro and add SYSENTER/SYSEXIT and update CPUID accordingly. Some fake MSRs are added because Windows ME assumes they are valid (else it will BSOD) and it even uses those to try to do a CPU microcode update (!) if it detects a Pentium II. SYSENTER/SYSEXIT was tested using the Linux kernel built to optionally support it.

Pentium III emulation will require the addition of SSE registers and instructions. Unlike MMX, the SSE registers are their own register file. This also means support for the newer CPU instructions that save and restore the SSE registers in addition to FPU state.

I'd like to see that, it's just that it needs some work to build up.

**Comment by PythonBlue** [comment]
Like I said, I don't expect this idea to be implemented immediately. Good to know you're open to it, though, and also good to know the technical ease of enabling Pentium II relative to III.

**Comment by joncampbell123** [comment]
Looking over the Pentium III opcode map, I think the biggest possible disruption to the normal core code is the difference between prefixes like F3h and 66h as prefixes vs "mandatory prefixes".

Some SSE instructions re-use other SSE instruction encodings with a F3h/F2h (REP) or 66h (32-bit) "mandatory" prefix.

**Comment by joncampbell123** [comment]
Consider for example: MULPS vs MULPD

![Firefox_Screenshot_2021-12-27T21-52-54 030Z](https://user-images.githubusercontent.com/6245486/147509530-43453c59-0b57-4349-9de5-aa0a157303ad.png)

**Comment by joncampbell123** [comment]
Fortunately Intel encoding so far has always had one "mandatory prefix" prior to the instruction, so this could be done by remembering the last prefix opcode byte and acting on it at instruction decoding.

**Comment by joncampbell123** [comment]
There's the wacky VEX encoding to pack these mandatory prefixes together into fewer bytes, but those didn't happen until 2008 or so and we don't care to emulate anything by that point anyway.

**Comment by joncampbell123** [comment]
A test program in DOSLIB shows that SSE instructions can work in real mode too, at least on real Pentium III hardware.

https://github.com/joncampbell123/doslib/blob/master/hw/cpu/sse.c#L69

**Comment by joncampbell123** [comment]
Now that I've thought it out, perhaps Pentium III emulation could begin in January. It's too close to the end of the month to add it now, DOSBox-X follows a cycle where the last week is bug fixes only for release at the end of the month.

**Comment by PythonBlue** [comment]
Glad to hear! Also will report an unrelated minor issue insofar as building the source code soon.

**Comment by joncampbell123** [comment]
Pentium III emulation is basically implemented as of March, want to try anything against it?

Linux seems happy with it.

**Comment by PythonBlue** [comment]
Does this include dynamic core mode? The last I tried a few months ago saw me notice that it only worked for normal core mode back then. Either way, will download the latest build and let you know.

**Comment by PythonBlue** [comment]
Yep, confirmed it, possibly, using the MIDI driver I've been talking about. I get a BSOD when using dynamic core to select a sound that requires a Pentium III CPU, while normal core mode I can occassionally get somewhat close to the correct result, as glitchy as it is due to seemingly no sound acceleration like what Parallels, VMWare, and, to a lesser extent, QEmu, offer on Intel hosts. Here is the log for the former scenario, if it helps.

[log.txt](https://github.com/joncampbell123/dosbox-x/files/8813099/log.txt)

**Comment by PythonBlue** [comment]
Irrelevant update, but until now, practically all of my tests were with the SDL1 builds due to the blue color not rendering properly in SDL2. Happy to see that may have been fixed since the last time I tested.
