### ISSUE TITLE
strcpy to be avoided?

### ISSUE THREAD

**Issue by nachtklavier** [joncampbell123/dosbox-x#3182]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

All

### What version(s) of DOSBox-X have this bug?

Current

### Describe the bug

Hi there,

For security reasons, might strcpy be replaced by
` *((char *) mempcpy (dst, src, n)) = '\0';`
or
`snprintf(dst, sizeof(dst), "%s", src);`

Source: src/dos/cdrom.cpp:

`bool CDROM_Interface_SDL::SetDevice(char* path, int forceCD) { `
`(void)forceCD;//UNUSED`
`char buffer[512];`
`strcpy(buffer,path);`
`upcase(buffer);`

### Steps to reproduce the behaviour

See above

**Comment by joncampbell123** [comment]
strncpy() might be a better choice.

That may have been inherited from DOSBox SVN because I don't believe it's been modified since.

**Comment by Wengier** [comment]
I fixed it by making a conditional strncpy/strcpy in the code.

**Comment by joncampbell123** [comment]
@Wengier strncpy will automatically stop at n-1 bytes or the end of the string, there's no need to check on it's behalf.

Also strncpy will not add a NUL at the end if it runs out, be aware of that.

What I would do is:

    buffer[sizeof(buffer)-1] = 0
    strncpy(buffer,path,sizeof(buffer)-1);
    if (buffer[sizeof(buffer)-1] != 0) return /* failure condition because string was too long */

**Comment by Wengier** [comment]
@joncampbell123 I checked it to avoid the case that the string runs out, in such case a "0" is manually added. Otherwise (when no overflow) strcpy can be used. I tested a few strings with that code and the code you just showed, and the results appear to be identical.

**Comment by yetmorecode** [comment]
@Wengier Looking at ```SetDevice()``` in general, I think the whole ```buffer``` and ```strcpy()``` is is only necessary to make at case-sensitive comparision at https://github.com/joncampbell123/dosbox-x/blob/f3caf64ebc9837985ad2fd0d1cbd5902de79b8a3/src/dos/cdrom.cpp#L84. So if ww just used something along the lines of ```strncasecmp``` it should be possible to "simplify" the local buffer away? I can prepare a PR for that.

**Comment by Wengier** [comment]
@yetmorecode You can definitely try to improve the code if you see a better way to do so, using constant(s) if necessary.
