### ISSUE TITLE
Dosbox-X crashes when pressing joystick button

### ISSUE THREAD

**Issue by Danfun64** [joncampbell123/dosbox-x#319]
I'm using the latest automated build (windows-20170914-115932 as of this writing, and i've tried both 64-bit and 32-bit executables)

Visual Studio gives this error message when I click "debug" on the windows crash screen

Unhandled exception at 0x00007FF6B91A29F1 in dosbox-x.exe: 0xC0000094: Integer division by zero.

**Comment by joncampbell123** [comment]
Does it provide a source file and line number?

I'm guessing the divide by zero is something to do with a failure to read the valid range of the joystick.

**Comment by Danfun64** [comment]
...Not really? Somehow I doubt the automatic builds you post are debug builds.

**Comment by joncampbell123** [comment]
I don't make the Windows builds.

**Comment by Danfun64** [comment]
In that case, how do I build debug builds then? (Both Visual Studio and MinGW-W64)

**Comment by Danfun64** [comment]
In that case, how do I compile debug builds (using either Visual Studio or MinGW-W64)?

**Comment by joncampbell123** [comment]
For Visual Studio, the .sln and .vcproj files should provide Debug and Release build options. Use the Debug build option and rebuild all.

**Comment by WarlockSVG** [comment]
try joysticktype=fsc in the config.

**Comment by WarlockSVG** [comment]
Found a working Solution.

Start dos "game/program" then got to the mapper ( ctlr+F1) assign a button one is enough example "ESC to the back button of the game-pad / joystick" save it and no more crashes for the games/program that are using that assigned mapper file

Just define the mapper file in the config file

[sdl]
mapperfile="game name".map

**Comment by WarlockSVG** [comment]
Start dos "game/program" then got to the mapper ( ctlr+F1) go back to the box and no more crashes. Looks like I have to do this everytime.

**Comment by WarlockSVG** [comment]
Start dosbox-x then got to the key mapper ( CTRL+F1 ) go back to the box and no more crashes. Looks like I have to do this everytime.

**Comment by joncampbell123** [comment]
I'm not able to reproduce this on Windows. Joystick input works fine, both SDL1 and SDL2 builds.

**Comment by joncampbell123** [comment]
I'm not able to reproduce this. Reopen if you can provide more information:
- OS and version
- Model of joystick

**Comment by WarlockSVG** [comment]
This is a smal part from the log. I'm not sure if the WARN msg helps.
It's the only thing that is "gamepad" related in the log.

0 DEBUG MISC:Joystick type != none, SDL reports 1 sticks
One joystick reported, initializing with 4axis
0 DEBUG MISC:JOYSTICK: Stick 0 enable=1
Using joystick DUALSHOCK®4 USB Wireless Adaptor with 6 axes, 14 buttons and 1 hat(s)
0 DEBUG MISC:JOYSTICK: Stick 1 enable=1
**0 WARN  MISC:Can't find matching event for hand_caprawopl**
0       MISC:MAPPER: Loading mapper settings from .config-x\..\.key-mapper\alien carnage (1993)(apogee software) 1.0.map

[alien carnage (1993)(apogee software) 1.0 ( no crash).log](https://github.com/joncampbell123/dosbox-x/files/1565051/alien.carnage.1993.apogee.software.1.0.no.crash.log)

[alien carnage (1993)(apogee software) 1.0 (crash).log](https://github.com/joncampbell123/dosbox-x/files/1565052/alien.carnage.1993.apogee.software.1.0.crash.log)

![sshot-60](https://user-images.githubusercontent.com/33853101/34073539-19e60402-e29c-11e7-86c8-0a21bb19bead.png)

**Comment by joncampbell123** [comment]
6 axes and 14 buttons??????

**Comment by joncampbell123** [comment]
I'm guessing that if I can find a joystick with that many buttons, perhaps I could recreate the crash.

I have a wired USB Playstation 3 controller and a wired XBox 360 controller that I'll test against right now, assuming Linux can work with them.

**Comment by joncampbell123** [comment]
No crash here, not in Linux.

Also, playing DOOM with the D-pad as the joystick is terrible.

**Comment by WarlockSVG** [comment]
O yeeeh the dualshock has 14 buttons and 6 axis... and 1hat ( up down left right ) how cool is that ;-)

If you are into DIY and want to build a cool arcade controller then this is cool https://goo.gl/3rnDEu Joystick Controller 36 Buttons ( 32 + 1HAT ) and 8 axis ( analog )

Okay... tomorrow I gone see if i have this error with other game pads on the computer. The funny thing is, is that I don't have this error/crash when I first go to the Key-mapper. But then again windows can be a B...tch.

**Comment by joncampbell123** [comment]
Apparently Windows 10 doesn't recognize the PS3 controller, but I was able to play through 3 levels of DOOM just fine using an old XBox 360 controller without any crashes.

Can you verify this on your end, using the latest binary I released?

**Comment by WarlockSVG** [comment]
I'm using dosbox-x-windows 20171215-0823 ...DosBox-X shows 0.801 but I guess updating the "version variable" slipt your mind ;-). The Windows version does not shows the version number on the window title-bar while your "screen shots" shows the version on the window title-bar ;-)
![sshot-63](https://user-images.githubusercontent.com/33853101/34083197-7c43c154-e36c-11e7-9a0b-b5bd97aae8d6.png)


I found out when there are 2 controller connected that DosBox-X does not crash if I press a button without going to the key-mapper ( ctrl+f1 )
![sshot-65](https://user-images.githubusercontent.com/33853101/34083148-c73674fa-e36b-11e7-8d59-0bd5456add5a.png)

So when there is 1 controller connected DosBox-X crashes on my computer without going to the key-mapper. ( my laptop does not have this problem )
![sshot-66](https://user-images.githubusercontent.com/33853101/34083204-a280ef04-e36c-11e7-9f08-11ef9d3fc065.png)

... just thinking out loud her ;-) Maybe some "variable" is set or gets another value when the key-mapper is called ( ctrl+f1 ) ... and no crash as a result of that ? Danfun64 had a "Integer division by zero." error so I guess it could be an Integer that is not set for some reason and gets a value when the key-mapper is called.

**Comment by joncampbell123** [comment]
It could be divide by zero.

Hard to tell when Windows insists on the now-standard "duh problem but u 2 stoopid to understand so me not tell you anything" type of UI design when a program crashes.

**Comment by joncampbell123** [comment]
I'm shopping online now to purchase a Dualshock 4 controller and USB wireless adapter for testing. When it comes in I could try reproducing the issue myself.

**Comment by WarlockSVG** [comment]
I'm not convinced that it's a PS4 controller isolated problem, probably a Windows problem... the same controller setup works without any problem on my laptop with DosBox-X. So I hope you're not just buying this controller + USB adapter only for this problem.

**Comment by joncampbell123** [comment]
It helps the variety of test cases I can run. I have no interest in a PS4 personally but the controller probably works quite well with Linux and it would be a good test case.

**Comment by WarlockSVG** [comment]
It's definitely a good controller to have... and with the USB adapter you can easy connect it to other devices without the need to rebind it.

The PS4 controller has also an "audio device" build in and when u use it with the USB adapter you can direct audio output to you PS4 controller ( on windows at least )
![sshot-67](https://user-images.githubusercontent.com/33853101/34083648-181664ea-e374-11e7-948f-25fc8770ff31.png)

It also works fine on Android tablets using an OGT cable.

**Comment by joncampbell123** [comment]
Amazon tells me it should be arriving today, I will be able to begin testing this issue.

**Comment by joncampbell123** [comment]
No crashes here. Tried all buttons.

**Comment by joncampbell123** [comment]
Try moving your mapper file out of the same directory and running with the default mapper settings.

**Comment by joncampbell123** [comment]
Also Windows 10 helpfully assumed I wanted all my audio to come out of the DualShock controller XD

**Comment by WarlockSVG** [comment]
moving / deleting mapper file does not help.

**Comment by joncampbell123** [comment]
Bizarre... what version of Windows is this on?

**Comment by WarlockSVG** [comment]
Windows 10 Pro 64Bit and Window 7 ultimate 64Bit

**Comment by WarlockSVG** [comment]
I set the "Preferred device" and now DosBox-X crashes from the moment it starts. Can't unset it :-(
![sshot-75](https://user-images.githubusercontent.com/33853101/34320036-7618e90c-e7f0-11e7-980d-068ff776b2e5.png)

**Comment by joncampbell123** [comment]
Ironically that's good, you've described one way I could deliberately recreate the issue. I'll try that.

**Comment by joncampbell123** [comment]
Windows 10 already considers my controller preferred, no crashes.

I'm still not clear on what is causing it, other than the fact that the mapper code is a mess.

**Comment by WarlockSVG** [comment]
I had to set the controller as preferred... it was on "None" but now that option is gone.

**Comment by joncampbell123** [comment]
The bug hit! For whatever reason, Windows 10 and an XBox 360 controller triggers it!

sdl_mapper.cpp line 853

emulated_buttons == 0

**Comment by joncampbell123** [comment]
A joystick bind button group that's a 4-axis is considered "dummy" and no buttons, I see. So it's divide by zero.

**Comment by joncampbell123** [comment]
Fixed, I think.

**Comment by WarlockSVG** [comment]
Looks like you did. I had to delete the already existing mapper file(s)... and reconfigure new ones. But no crashes after that process.
