### ISSUE TITLE
Include config_package.h in the VS project

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#3190]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What you want

Sometimes it's convenient to edit the strings in config_package.h when building under Visual Studio. Could the file be added to the project file? That makes it easier to search and find. Thank you!

**Comment by Wengier** [comment]
@emendelson I think it is already listed under “External Dependencies” in VS. Hope this helps.
