### ISSUE TITLE
macOS: config -set ptsize= size too large for screen ->DOSBox-X crashes

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#3194]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

macOS Monterey 12.1

### What version(s) of DOSBox-X have this bug?

0.83.21

### Describe the bug

Latest version, in macOS 12.1, both SDL1 and SDL2 crash if you enter a command like this with a point size too large for the screen:

`config -set ptsize=nn`

In Windows, an error message appears when you choose a point size, and then DOSBox-X crashes, but the crash is immediate in macOS.

### Expected behavior

DOSBox-X should revert to a point size that fits on the screen, instead of crashing.

### Steps to reproduce the behaviour

See the command above. Keep entering larger point sizes until the crash occurs.

**Comment by Wengier** [comment]
It is hopefully fixed as part of PR #3425.
