### ISSUE TITLE
dosbox-x does not work properly with winget

### ISSUE THREAD

**Issue by ix0rai** [joncampbell123/dosbox-x#3216]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

0.83.16 onwards.

### Describe the bug

First issue:
When upgrading dosbox-x with Winget, it always give an `installer hash does not match` error.

Second issue:
Winget always thinks that there's an update to be applied to dosbox-x, even when there is none.  This causes it to always have to download and run the installer, which ends up changing nothing.
when running `winget upgrade`
![image](https://user-images.githubusercontent.com/66223394/149019922-69d9b3d2-63d9-4850-9290-00fcdfa8dfc5.png)
after upgrading the package and running again:
![image](https://user-images.githubusercontent.com/66223394/149020332-20b4b3e2-5cc1-42ab-a921-133e1c4cd70c.png)
Winget still finds an upgrade to Dosbox-x, even though there is none.

### Expected behavior

Winget should only find a new update when there is one available.

### Steps to reproduce the behaviour

1. Install Winget
2. Run `winget install dosbox-x`
3. Run `winget upgrade`
4. See that there is an update available, even though we have just downloaded the latest version of the program.

### Used configuration

all configurations are affected

**Comment by Jookia** [comment]
I hit issue 2, but not issue 1.

'Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 101.0.1210.32' seems to have this issue too.

**Comment by Jookia** [comment]
Looks like it might be related to https://code.videolan.org/videolan/vlc/-/issues/26850

**Comment by Jookia** [comment]
I'm not sure exactly how to fix this- but the DisplayVersion registry key is being set to "0.83.25 (64-bit)" which is seen as older than "0.83.25". In ./contrib/windows/installer/DOSBox-X-setup.iss 'AppVersion={#MyAppVersion} {#MyAppBit}' shouldn't include the bitness.

I have no idea how to build the installer on my system but changing the DisplayVersion in registry to remove the 64-bit fixed this for me.

This seems to have been broken in 0.83.16 commit 6bd448cca6e7cd2b82f41dda653adf5c663a604c by @Wengier

**Comment by Wengier** [comment]
I am not exactly sure how this specific issue can be fixed either, but for people who may know how this can be fixed, they can certainly take a look at the Windows installer build script for finding a way to actually address it:

https://github.com/joncampbell123/dosbox-x/blob/master/contrib/windows/installer/DOSBox-X-setup.iss

https://github.com/joncampbell123/dosbox-x/blob/master/build_windows_installer.bat

**Comment by Jookia** [comment]
I think the fix is to remove the bitness from the version.

**Comment by ix0rai** [comment]
updated versions affected from all to 0.83.16 onwards as per @Jookia's comment

**Comment by Wengier** [comment]
@Jookia Yes, but if the bitness is removed from the version, how may people differentiate between the two (32-bit vs 64-bit). Perhaps add the bitness in the application name instead? Not sure if this may possibly cause issue though.

**Comment by Jookia** [comment]
Putting it in the name might work.
