### ISSUE TITLE
Make disk image

### ISSUE THREAD

**Issue by joshudson** [joncampbell123/dosbox-x#3220]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

Found your project when getting frustrated with (non-overlapping) bugs in QEMU and Dosbox.

I don't know if you're interested but I have a tool for making disk images inside dosbox.

### What you want

Z:\> mount y: ~/images
Z:\> newimage Y:\c.img 200M

(the tool I have already knows how to adjust the size and make it rectangular; max size 2TB)

### Describe alternatives you've considered

Making disk image with host software, but that involves supporting more than one operating system in the tool.

**Comment by Torinde** [comment]
Maybe DOSbox-X [IMGMAKE ](https://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X) covers that?

**Comment by joshudson** [comment]
@Torinde : Ah fun. IMGMAKE and mine turned out to be complimentary. IMGMAKE makes images of a small number of hard disk sizes and floppy disks, mine makes only hard disk images, but any size rounded up to the next 504KB.

**Comment by rderooy** [comment]
"a small number of hard disk sizes"? You can specify any size up to a theoretical 2TiB with the ``-size`` option. Or you can specify the CHS geometry.

e.g. to make a 1024MB*100=100GiB image file:
```
imgmake hdd.img -t hd -size 102400
```
