### ISSUE TITLE
Color error when text mode 132 x43

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3222]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 21H2

### What version(s) of DOSBox-X have this bug?

0.83.21

### Describe the bug

dear sir,
Color error when text mode 132 x43

[T_INKE.rar.zip](https://github.com/joncampbell123/dosbox-x/files/7861046/T_INKE.rar.zip)

### Steps to reproduce the behaviour

 execute T_inke.exe in 80x25 text mode
and then execute T_inke.exe in 132x43 text mode
their color is different

**Comment by Wengier** [comment]
I tried your program, and I think the colors appear to be the same in both cases:

![image](https://user-images.githubusercontent.com/8216923/149565851-60fcb256-6800-40fa-894c-d38762bbebe8.png)

![image](https://user-images.githubusercontent.com/8216923/149565780-83e85be0-38d8-4870-b6a7-a9aefd7addbf.png)

**Comment by Arthur3032** [comment]
I don't know where the setting is wrong, you can refer me to your doxbox-x.conf

**Comment by Arthur3032** [comment]
![擷取](https://user-images.githubusercontent.com/93595854/149614165-ba9d6291-9599-4331-b76d-4ceb2888b34d.JPG)

**Comment by Wengier** [comment]
@Arthur3032 You can try this command to start and run your program:

``
dosbox-x -defaultconf -set output=ttf -langcp zh_tw -set cols=132 -set lins=43
``

The config file will be irrelevant in this case.

**Comment by Arthur3032** [comment]
Thank You.
