### ISSUE TITLE
Notebook DELL Precision M6800 hot keys / multimedia keys print characters in SDL1 builds

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#3231]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 Pro 21H2 64 bit

### What version(s) of DOSBox-X have this bug?

0.83.21 SDL1 builds

### Describe the bug

On my laptop (DELL Precision M6800) when i press these hot keys / multimedia keys when the emulator window is in focus, the characters highlighted in the image below are printed at the DOS prompt:

![DELL Precision M6800](https://user-images.githubusercontent.com/58113425/150116976-65e4990c-9bd6-4bf7-8851-61b9957a6ae1.jpg)

I also tried deleting the file mapper-dosbox-x.map but to no avail.

### Expected behavior

Hot keys / multimedia keys should be ignored

### Steps to reproduce the behaviour

Try pressing the hot keys / multimedia keys on your notebook with focus on the emulator window to check if the issue is also on your model.

**Comment by rderooy** [comment]
The SDL1 version has poor keyboard support, only really supporting a standard US layout keyboard. Although there are hacks in place in the DOSBox-X and bundled SDL1 code to support non-US layouts to a limited extend.

Did you test if the SDL2 version has the same problem, because it should have much better support for different input devices, and is actively maintained (unlike SDL1 which is abandoned by now).

**Comment by MX9000** [comment]
Yes you are right, SDL2 versions do not have this problem.
I'm using the SDL1 version because it is proposed by default during the installation and it displays the menu bar even with OpenGL shaders.

**Comment by Torinde** [comment]
I also encounter issues in some games with Break key and Numlock state - will try SDL2

@rderooy SDL1 is mentioned as default [here](https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md#windows-packages-installer-or-portable)

**Comment by maron2000** [comment]
Hi, I added some code to ignore media keys on Windows SDL1 version.
If you can build on your own, can you try it?
https://github.com/maron2000/dosbox-x-1/tree/Keyboard_Fix
The actual changes in the code is found here 1233b7cf740673025a43d52b2186419a659525f7

**Comment by MX9000** [comment]
@maron2000 , @rderooy the fix works flawlessly, many thanks to all!
