### ISSUE TITLE
LibRetro core build

### ISSUE THREAD

**Issue by PythonBlue** [joncampbell123/dosbox-x#3247]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What you want

First of all, happy to see the progress with my prior request of Pentium III support, and overall, it's working great sans the one MIDI synth I've talked about.

This request is on behalf of a friend, and it's not crucial for me, so by all means, put this on the backburner if you need to, but said friend has expressed interest in this project being ported as a LibRetro core for things like RetroArch. This may not be possible depending on what this demands, and I personally wouldn't expect it to be rolled out any time soon if it is due to other things being worked on, but all the same, we feel it best to ask all the same if you've considered making this available for LibRetro.

### Additional context

The friend of concern also has a deep interest in retro computing, and the reason for this request, to my knowledge, is that he also loves messing around with LibRetro for his livestreams.

**Comment by Dobby233Liu** [comment]
There is some discussion about this in #893

**Comment by PythonBlue** [comment]
Ah, thanks. Guess I didn't look hard enough through the issue list. Apologies.
