### ISSUE TITLE
rpm build failure

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#3255]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Fedora 35

### What version(s) of DOSBox-X have this bug?

0.83.22

### Describe the bug

Trying to build the RPMs, I run into this build failure:
```
In file included from debug.cpp:35:
../../include/fpu.h:109:1: warning: 'typedef' was ignored in this declaration
  109 | typedef union alignas(8) MMX_reg {
      | ^~~~~~~
../../include/fpu.h:196:1: warning: 'typedef' was ignored in this declaration
  196 | typedef union alignas(16) XMM_Reg {
      | ^~~~~~~
debug.cpp: In function 'void DEBUG_PrintMMX(int, char)':
debug.cpp:1742:19: error: format not a string literal and no format arguments [-Werror=format-security]
 1742 |     DEBUG_ShowMsg(tmp);
      |                   ^~~
debug.cpp: In function 'void DEBUG_PrintSSE(int, char)':
debug.cpp:1796:19: error: format not a string literal and no format arguments [-Werror=format-security]
 1796 |     DEBUG_ShowMsg(tmp);
      |                   ^~~
debug.cpp: In function 'bool ParseCommand(char*)':
debug.cpp:3305:18: warning: unused variable 'ticks' [-Wunused-variable]
 3305 |         uint32_t ticks=mem_readd(BIOS_TIMER);
      |                  ^~~~~
debug.cpp: In function 'void DEBUG_Enable_Handler(bool)':
debug.cpp:4256:39: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 4256 |     if (debugrunmode==1) ParseCommand("RUN");
      |                                       ^~~~~
debug.cpp:4257:44: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 4257 |     else if (debugrunmode==2) ParseCommand("RUNWATCH");
      |                                            ^~~~~~~~~~
In file included from ../../include/gmock/internal/gmock-internal-utils.h:47,
                 from ../../include/gmock/gmock-actions.h:145,
                 from ../../include/gmock/gmock.h:59,
                 from ../../tests/gmock/gmock.cc:31,
                 from ../../tests/tests.h:6,
                 from debug.cpp:51:
../../include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperNE(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]':
../../tests/dos_files_tests.cpp:383:2:   required from here
../../include/gtest/gtest.h:1624:28: warning: comparison of integer expressions of different signedness: 'const int' and 'const long unsigned int' [-Wsign-compare]
 1624 | GTEST_IMPL_CMP_HELPER_(NE, !=)
      |                            ^
../../include/gtest/gtest.h:1614:12: note: in definition of macro 'GTEST_IMPL_CMP_HELPER_'
 1614 |   if (val1 op val2) {\
      |            ^~
../../include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]':
../../include/gtest/gtest.h:1564:23:   required from 'static testing::AssertionResult testing::internal::EqHelper::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; typename std::enable_if<((! std::is_integral<_Tp>::value) || (! std::is_pointer<_Dp>::value))>::type* <anonymous> = 0]'
../../tests/dos_files_tests.cpp:382:2:   required from here
../../include/gtest/gtest.h:1545:11: warning: comparison of integer expressions of different signedness: 'const long unsigned int' and 'const int' [-Wsign-compare]
 1545 |   if (lhs == rhs) {
      |       ~~~~^~~~~~
debug.cpp: At top level:
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: some warnings being treated as errors
make[3]: *** [Makefile:369: debug.o] Error 1
make[3]: Leaving directory '/home/rderooy/rpmbuild/BUILD/dosbox-x-dosbox-x-v0.83.22/src/debug'
make[2]: *** [Makefile:529: all-recursive] Error 1
make[1]: *** [Makefile:400: all-recursive] Error 1
make: *** [Makefile:333: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.PUjr76 (%build)
```

### Steps to reproduce the behaviour

rpmbuild -ba <spec file>

**Comment by grapeli** [comment]
This has already been reported.
#3039
No response from devolopers.

I use this patch.
[0001-format-security.patch.txt](https://github.com/joncampbell123/dosbox-x/files/7981086/0001-format-security.patch.txt)

**Comment by rderooy** [comment]
Thanks @grapeli. Your patch does not actually solve this particular breakage, but I made a new one that does. I also included your patch into it.

Do you want me to create a PR for this, or do you want to do it yourself?
[01-debug-format.patch.txt](https://github.com/joncampbell123/dosbox-x/files/7981782/01-debug-format.patch.txt)

**Comment by grapeli** [comment]
I very rarely build "hardened" versions. Meanwhile, the `debug_gui.cpp` code has grown.
If you can, create a PR.

Now that you've built the new dosbox-x. By the way, run dosbox-x with `output=opengl`, start mapper editor, quit it and resize dosbox-x window (maximize or press F12-Backspace).

**Comment by rderooy** [comment]
I have created a PR with the patch.

In any case, the Copr build is in progress, it should hopefully be ready in the next 10 or so minutes
https://copr.fedorainfracloud.org/coprs/rob72/DOSBox-X/build/3289643/

My previous Copr build failed on Fedora Rawhide. For some reason configure is failing on Rawhide:
```
checking checking for C++14 support... checking whether g++ accepts " -std=gnu++14 "... no
checking checking for C++11 support... checking whether g++ accepts " -std=gnu++11 "... no
configure: error:  Your compiler must support C++11 or better 
```
Not sure what is going on, perhaps Rawhide is simply broken atm. For now I simply disabled the Rawhide builds in copr.

**Comment by rderooy** [comment]
@grapeli, I tried your crash method and it did not crash here.

I started DOSBox-X with ``dosbox-x -set output=opengl`` (even though opengl is the default output on Linux).

I then pressed F12-M to go to the mapper editor, and exited. I then pressed F12-F to go fullscreen, and back to windowed mode a couple of times. I also resized the window with the mouse, and pressed F12-Backspace to reset the window size.

I tested this on Fedora 35 with DOSBox-X running in Xwayland on a notebook with Intel graphics (CometLake).

**Comment by rderooy** [comment]
If gdb points to Mesa, then it may either be Mesa version dependent, or dependent on the video card.
I can try it later today on my system with Radeon RX590 to see if it makes a difference.

In any case 0.83.22 is now available in Copr for EPEL8 and Fedora 34 and 35.

I also tried to create an EPEL9 build, but there were some missing packages (fluidsynth and libslirp). So I either ignore EPEL9 for the time being until they are (hopefully) available, or I need to special-case it in the RPM spec file and reduce the functionality of DOSBox-X on EPEL9. I noticed that there is at least a bug report in bugzilla for the missing fluidsynth.

For rawhide, I'm not sure what to do. I may just wait a month and try again to see if the issue resolves itself. Or if I find the time, I can install it in a VM and try to see if I can troubleshoot the issue.

**Comment by grapeli** [comment]
> 
> For rawhide, I'm not sure what to do. I may just wait a month and try again to see if the issue resolves itself. Or if I find the time, I can install it in a VM and try to see if I can troubleshoot the issue.

Must have to do with the newest [gcc 12](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/BBERLMHDXIRFP7OK2MYY7AK4SRUWVF6D/) that recently came to rawhide. It generates a lot of problems. I suspect it doesn't match any of the flags yet (maybe - `-flto -ffat-lto-objects`), and it stops at this "-std=gnu++14" test. Probably a temporary thing. If you are interested in it you just have to follow these events. I don't think you need to test rawhide at this stage.
