### ISSUE TITLE
Incorrectly named release 2021-01-31

### ISSUE THREAD

**Issue by nyanpasu64** [joncampbell123/dosbox-x#3261]
https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.83.22 was created on 2022-01-31 but is labeled 2021-01-31. This release date error is also present on the website https://dosbox-x.com/.

**Comment by rebb** [comment]
Looks like the little mistake is still on the main dosbox-x.com page, but correct in the release notes.

**Comment by Wengier** [comment]
Both should be correct now.
