### ISSUE TITLE
Formatting errors in wiki

### ISSUE THREAD

**Issue by nyanpasu64** [joncampbell123/dosbox-x#3263]
https://github.com/joncampbell123/dosbox-x/wiki/Guide:Setting-up-MIDI-in-DOSBox%E2%80%90X and https://dosbox-x.com/wiki/Guide:Setting-up-MIDI-in-DOSBox%E2%80%90X have a formatting error:

> If set to -1, the default IRQ address for the IBM PC or NEC PC-98 will be used. * For the IBM PC XT with a single PIC, this will be IRQ 2 * For the IBM PC AT (or later) this will be IRQ 9 * For the NEC PC-98 it will be IRQ 6.

To fix the formatting, I think you need two newlines before the first bullet asterisk.

This is the only occurrence of "` * `" on that page. I'm not sure if other wiki pages have similar formatting issues; I don't know how to automatically search for them, and the "`(?<!\n)\n* `" regex has too many false positives.

**Comment by rderooy** [comment]
Thanks for the heads up. I fixed it on the draft wiki, which will be pushed to the main wiki when the next release is out.
https://github.com/Wengier/dosbox-x-wiki/wiki/Guide:Setting-up-MIDI-in-DOSBox%E2%80%90X

**Comment by nyanpasu64** [comment]
Also the GitHub wiki and the dosbox-x website have a `<p>` within every `<li>`, resulting in extra space between list items. I'm not sure if that's intentional, or if it can be disabled (in Markdown you have to ensure no empty lines between bullets, but those are already absent here).

**Comment by rderooy** [comment]
Actually most (all?) of the wiki is written in AsciiDoc as it allows things like an automatically generated TOC.

But I don't think we can do anything about the extra paragraph tags as the conversion is not done by us.
