### ISSUE TITLE
FN & Other Media Keys crash DosBox-X v0.83.22 in case if videodriver=directx

### ISSUE THREAD

**Issue by Bitterman94** [joncampbell123/dosbox-x#3265]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

v0.83.22 SDL1

### Describe the bug

Hello there! The issue with media keys is not fixed in v0.83.22 release.
When using "videodriver=directx" and pressing "FN" key DOSBOX-X crashes with the error attached above.

Please release a hotfix.

If leaving videodriver field empty like "videodriver= " then it does not crash, but without "directx" driver the game performs considerably slow.

### Expected behavior

Crash should not occur, media keys must work.
At the moment I can't do operations like volume increase/decrease because combination FN+Volume Up crashes DOSBOX-X.

### Steps to reproduce the behaviour

1) Set videodriver=directx in DosBox-X.conf
2) Launch the game (widowed or fullscreen)
3) Press FN button on your laptop
4) Crash occurs

See the screenshot.

### Used configuration

```ini
N/A
```

### Emulator log

```text
N/A
```

### Additional context

![bug](https://user-images.githubusercontent.com/99081041/152648403-10392aab-920d-4b02-b45c-2e99fb235927.png)

**Comment by maron2000** [comment]
Commented here. Let's not separate comments for similar (or even same) issues. 
https://github.com/joncampbell123/dosbox-x/issues/2976#issuecomment-1030743256
