### ISSUE TITLE
Question about using USB Parallel port with 0.83.22 (Linux SDL2) 

### ISSUE THREAD

**Issue by rcooke** [joncampbell123/dosbox-x#3273]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

Using the FLATPAK under Ubuntu 20.04.3 LTS.

I have an old DOS6 proprietary program that uses serial port and has a license dongle on the printer port.

I have two well supported USB devices for both:

`Bus 002 Device 003: ID 067b:2305 Prolific Technology, Inc. PL2305 Parallel Port`
`Bus 001 Device 004: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port`

Adding them to my config file seemed easy following the config guide and "how to print":

`...`
`serial1       = directserial realport:ttyUSB0`
`...`
`parallel1 = reallpt realport:/dev/usb/lp0`

I added my user to the lp group and rebooted.  

When I start DOSbox-X the serial port connects, but the parallel port gets an error: **failed to claim port.**

Full Log attached: [dosbox-x.log](https://github.com/joncampbell123/dosbox-x/files/8043218/dosbox-x.log)

Can anybody shed some light upon this?  

I tried changing the printer to a file:
`
parallel1 = file dev:/dev/usb/lp0
`

This did not get any errors, but I doubt whatever software checks the license dongle will work with it.  

Thanks in advance!
Richard

**Comment by rderooy** [comment]
Can you show the permissions of the `/dev/usb/lp0` device in the filesystem?

e.g.,
```
ls -l /dev/usb/lp0
```

I don't have a USB parallel port adapter, and just assumed it to be automatically part of the `lp` group, but perhaps its not and needs to be adjusted with udev.

**Comment by rcooke** [comment]
When I started, lp0 already had the lp group attached.  I chmod 777 to open it right up after my first tests failed.

`/dev/usb:`
`total 0`
`drwxrwxrwx  2 root root     60 Feb 10 09:02 ./`
`drwxr-xr-x 23 root root   4540 Feb 10 09:03 ../`
`crwxrwxrwx  1 root lp   180, 0 Feb 10 09:02 lp0`

and

`drwxrwxrwx   2 root       root          60 Feb 10 09:02 usb/`


and what you asked:

`technician@technician-Aspire-5349:~$ ls -l /dev/usb/lp0`
`crwxrwxrwx 1 root lp 180, 0 Feb 10 09:02 /dev/usb/lp0`

**Comment by rderooy** [comment]
Thanks for the clarification. `770` permissions and ownership of `root:lp` should be fine if your user is part of the `lp` group. And with 777 even that does not matter.

Perhaps @joncampbell123 knows more about this if a legacy parallel port vs a USB parallel port looks different to an application. Or perhaps, since parallel ports are pretty rare these days, support for it was broken at some point and nobody noticed.

**Comment by joncampbell123** [comment]
I don't use USB parallel ports or even normal parallel ports in Linux much. I assume that if it's like Linux's serial port (TTY) support, it's probably the same user-mode interface, just named differently under /dev/ depending on USB or motherboard.

**Comment by rcooke** [comment]
I was wondering, kinda surprised me!

The Print setup guide mentions **/dev/usblp0** and **/dev/ttyUSB0**.

Note in my config file, I just use _ttyUSB0_, and that connects to the port fine.  But I tried usblp0 (no port found) and /dev/usblp0 (no port found).

In my dev folder, there is no device named usblp0.  But there is a usb folder, and in that folder there is a lp0 device.

After I changed my config to the full path "/dev/usb/lp0" I stopped getting port not found errors, now its **failed to claim port**.

I looked at the code, and this error is thrown after all the expected errors are detected/checked for.  Unless the detection code is out of date? Like, have the return error codes changed?

**Comment by rcooke** [comment]
The impression I got was that anything with a serial interface will get a tty device.  And anything else, like with a parallel interface, will wind up USB/lpx.  And I can certainly see that the interface chip is pretty standard.  I read a few posts where the printer had a USB cable, but it was the Prolific parallel chip that comes up.

I'm wondering about making a pointer named usblp0 and just goes to the full device path?  I would not think that would matter/help.  But it wont take long to try it.  so....
