### ISSUE TITLE
There was an error in executing the shell command

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3275]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

0.83.22 (SDL1) dos V7.10

### Describe the bug

dear sir:
The same program can be executed normally at 0.83.21, but can't be executed at 0.83.22
shown as the sample file test.bat

### Steps to reproduce the behaviour

in dosbox-x
execute TEST.bat

[error.rar.zip](https://github.com/joncampbell123/dosbox-x/files/8054056/error.rar.zip)

**Comment by Wengier** [comment]
Just let you know the default setting of the config option ``starttranspath`` (in [dos] section) has changed between 0.83.21 and 0.83.22. It should work with ``starttranspath=false``, regardless of the version.

**Comment by Arthur3032** [comment]
It's OK, Thank You!
