### ISSUE TITLE
The Oscar game cannot to excecute

### ISSUE THREAD

**Issue by FloLore** [joncampbell123/dosbox-x#3280]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

windows 10 pro 64b

### What version(s) of DOSBox-X have this bug?

0.83.22

### Describe the bug

When i start the Oscar game, after the setup step when the game must start , launching the game loops infinitely without never to begin the menu.

Work perfecly with dosbox and dosbox svn daum. not with dosbox-x 0.83.22

### Steps to reproduce the behaviour

trying to start the oscar game

### Used configuration

```ini
dosbox-x.conf by default
```

**Comment by grapeli** [comment]
Before starting the game, add the command `loadfix -a`.

**Comment by FloLore** [comment]
Thank you Grapeli, i didn't know this DOS command, the game starting perfecly with ;)
