### ISSUE TITLE
dBase-IV printing locks up DOSBox-X

### ISSUE THREAD

**Issue by hcw3** [joncampbell123/dosbox-x#3290]
I'm stumped...

For years, I've been using dBase-IV via a Windows7 'DOS-window' using VMWare Fusion from my Mac... argh! I know, only just a bit convoluted.

Now a new M1 Mac Mini, and trying to simplify. 

Success installing dBase-IV in DOSBox-X (mostly)
 
Now trying to get dBase printing again using the postscri.pr3 dBase 'Postscript driver', using a Postscript network printer.

I've set the DOSBox-X config to print to a  '.ps' file - which works. Tested with a DOSBox commandline "DIR >LPT1" , and can then stream these Postscript output files to the printer using the Mac-OS print queue or Preview.

But, from inside dBase, any dBase print-output command I initiate in dBase locks up DOSBox-X so I have to restart the DOSBox instance.

In dBase's settings, the Postscript printer is pointing at LPT1:
- in Windows I used 'Net Use' to redirect LPT1: to the Network Printer share (the Network Printer is set up for Windows with a Postscript driver)

Can I get DOSBox to log where dBase is getting stuck? How might I debug this? I'm pretty rusty with DOS, but I do have a little experience (long time ago!) with it...

Anyone have any experience with dBase printing with DOSBox-X?

Thanks for any help!

**Comment by emendelson** [comment]
Could you try this - simply print to LPT1 - and let me know if it works? Read the section on printing, a long way down the page:

http://www.columbia.edu/~em36/dosboxapp.html

**Comment by hcw3** [comment]
Yes, I'm able to print directly on the DOS command-line with a redirect - ie: using "dir >lpt1.

I'll look into the option screen mentioned in the link you provided. Thanks.

**Comment by emendelson** [comment]
Yes, the Option menu can be useful. Hold down the Option key when you launch my application. Choose the option to customize printer settings. You'll find the command that you need to add to your DOSBox-X setup for printing PostScript to LPT1 (it's the lpr command). Also study the wiki on printing.

**Comment by hcw3** [comment]
Edward, on initially running your the app, the script gives me an error "extrapath.txt: Read-only file system"
I don't normally log in as an Admin user, just as a "Standard" user.
Are there some file permissions I need to change for the script to run?
Thanks.

**Comment by emendelson** [comment]
@hcw3 - Sorry to take so long to get back here. I've never tried running my system as a standard user, so I probably can't help. If the app is in your Applications folder, try moving it somewhere in your home folder (desktop, home folder, the Applications folder inside your home folder, etc.). That may help.

**Comment by hcw3** [comment]
Ah! Thank you! I'm glad I checked the discussion thread - I almost missed your edited posting.
I'll try it again (after I get my taxes finished... argh)
Thanks for your effort and time with this.

**Comment by hcw3** [comment]
@emendelson, what I realized was that I'd installed it on my desktop... Out of laziness, I imagine. Once I moved the app to the /Applications folder, it worked fine. (My apologies for sending you down the wrong road.)

However, I still have the same problem with dBase. Any call to a print command from dBase causes a lockup of the system. Requires a Ctrl-Alt-Del reboot. I tried various dBase print drivers.

Printing from the DOS prompt works fine in DOSbox, however.

This is with the M1 Mac. 

Tomorrow I'll try DOSbox printing from dBase with my older Intel Mac, to see if that also has a problem.

**Comment by hcw3** [comment]
Thanks. I was thinking that might be the way to go. 

Your fork provides some good printer support, however, so I might like to use it eventually. Otherwise, I'm unclear about how to get print output from DOSbox to use the default Mac-OS printer, and I see that your app used some Applescript to achieve this.

Thanks again for your help.

**Comment by emendelson** [comment]
@hcw3 You can see the way my app works by looking at the conf file that the app creates in its Contents/Files folder. If DOSBox-X gets fixed so that dBase printing doesn't lock up, I'll of course add the fixes to my fork.

**Comment by hcw3** [comment]
Thanks for pointing that out (Contents/Files). I'll dig into it and see how far my limited experience gets me!
Otherwise I'll look forward to your next release. Today's latest DOSBox-X release addressed the lockup problem with dBase-IV, and it's working now.
Thanks again!
