### ISSUE TITLE
Is there a limit to the number of -c "command" options you can specify on the command line?

### ISSUE THREAD

**Issue by RrnR** [joncampbell123/dosbox-x#3293]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

It seems to be limited to around 9-10 commands.  I was wondering if there was indeed a limit (it doesn't seem to be mentioned in the Wiki) and whether it can be increased with some configuration option.

**Comment by grapeli** [comment]
This limit is set hard (11) in the [shell.cpp](https://github.com/joncampbell123/dosbox-x/blob/master/src/shell/shell.cpp#L1064) file.

I don't know if it can be so freely increased. I did not try.

**Comment by grapeli** [comment]
These limitations are hidden somewhere deeper, they are related to the dosbox-x shell.

With freecom running under dosbox-x and after modifying the [shell.cpp](https://github.com/joncampbell123/dosbox-x/blob/master/src/shell/shell.cpp) file, the maximum number of switches I was able to call was 18.

https://user-images.githubusercontent.com/452325/154936782-78e9cb2f-e167-46a4-98ba-bef905540c30.mp4

**Comment by RrnR** [comment]
Yep, still a bit restricted really.  I opted for a single call to another batch file, which can be as big as we like.

Also, hand-building a sequence of commands with the -C option becomes unwieldy if you need IF statements and the like.

Thanks for looking at this.
