### ISSUE TITLE
mounting issue in Linux

### ISSUE THREAD

**Issue by nerun** [joncampbell123/dosbox-x#3297]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

- Linux Debian 11.2 64 bits
- DOXBox-X 0.833.22 (via flatpak)

Trying to mount my DOSBox game folder:
```
Z:\>mount c /media/Melchior/DOSBox
Directory /media/Melchior/DOSBox does not exist.
```
My drives:
```
/dev/nvme0n1p5   /
/dev/sda1        /media/Melchior
/dev/sda2        /media/Balthazar
/dev/sdb1        /media/Gaspar
```
However, any of these options works fine:
```
mount c ~
mount c ~/anything
mount c /
```
It should be noted that mounting via menu also works `Drive > C > Mount folder as hard drive`. I can mount `/media/Melchior/DOSBox` easy. But if i add `mount c /media/Melchior/DOSBox` to dosbox-x config Autoexec it does not work.

Once i have mounted `/media/Melchior/DOSBox` with menu, a folder called `/var/run/user/1000/doc/9600e070/DOSBox` is created. So i can:
```
Z:\>mount c /var/run/user/1000/doc/9600e070/DOSBox
Drive C is mounted as local directory /var/run/user/1000/doc/9600e070/DOSBox/
```
Add `mount c /var/run/user/1000/doc/9600e070/DOSBox` to `dosbox-x-0.83.22.conf` autoexec session also works fine.

Maybe because /media/Melchior is another drive (/dev/sda1), not the same as root and home (/dev/nvme0n1p5).

**Comment by rderooy** [comment]
Your error is expected with the flatpak edition due to sandbox restrictions. It is described here: https://github.com/flathub/com.dosbox_x.DOSBox-X

**Comment by nerun** [comment]
Thank you!

Fixed with:
`sudo flatpak override --filesystem=/media com.dosbox_x.DOSBox-X`
