### ISSUE TITLE
DOSBox-X loses long filenames; vDosPlus doesn't

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#3304]
I'm using the latest public DOSBox-X, 0.83.22 (SDL1, 32-bit) under Windows 7 Professional 32-bit, with WordStar for DOS 7.0 on a hard drive formatted as NTSF. In the DOSBox-X config file, I have:

```
ver = 7.1
lfn = auto
```

WordStar is blissfully ignorant of long filenames, showing in its directory only `AWORLD~1.TXT` for a file named "`A World Without Work.txt`". That's fine and to be expected. But editing and saving the file under DOSBox-X causes the long filename to be lost so that even LFN-aware programs and utilities show the saved version as only `AWORLD~1.TXT` with no corresponding long filename.

This does not happen with either vDosPlus or TameDOS; after saving a file with a long filename with WordStar under either of those, the long filename is preserved (although the backup file, as with DOSBox-X, is given only a short filename: `AWORLD~1.BAK`, but that's not a serious problem).

Is there some setting I can change in DOSBox-X to get it to not lose the long filename, please? Thank you!

**Comment by joncampbell123** [comment]
DOS programs have to be written to support long filenames, which is an API that is an entirely different set of INT 21h calls. If a program does not use the long filename API, then it will only see the short 8.3 names.

Does Wordstar claim to support long filenames?

**Comment by RobertJSawyer** [comment]
Jonathan, as I said, WordStar does not, but that is not the issue I'm bringing up. Please, my friend, re-read my original post; I took pains to anticipate your questions and addressed them before you asked them. :) To reiterate:

1) WordStar itself only shows short filenames; it does not support them. Its directory displays will only show files as the corresponding short filenames in the standard truncated short form, such as, for example, `AWORLD~1.TXT`

2) However under **other DOS environments**, such as vDosPlus created by Wengier, and TameDOS, saving a file under WordStar **does not** not destroy the longfile name; rather, it preserves it after saving the file, so that the DOS command DIR /x will show both the short filename and the long filename (and Windows Explorer will show the long one).

3) **But** under DOSBox-X -- and, of the emulators/systems I've listed above, **only** under DOSBox-X -- the long filename disappears after saving under WordStar. That is, WordStar is fully capable of **not** damaging the long filename under vDosPlus or TameDOS, and indeed it does not; but it **does** under DOSBox-X, and only DOSBox-X, which is why I raised the question here.

Thank you!

**Comment by joncampbell123** [comment]
@RobertJSawyer Got it. And for reference, what you're asking for is what Windows 95 does with 8.3 access as well.

**Comment by RobertJSawyer** [comment]
Thank you, Jonathan. 

Re: how Windows 95 handles it, under all three systems -- DOSBox-X, vDosPlus, and TameDOS -- I use 4DOS as my command processor, and for all three I have 4DOS's initialization file (separate 4DOS.ini files under vDosPlus and TameDOS; specified under the [4dos] section of  DOSBox-X.conf under DOSBox-X) set to with these relevant values:

```
win95lfn       = YES
win95sfnsearch = YES
```

**Comment by emendelson** [comment]
The same problem occurs with WordPerfect When you open a file in WP, using the 8.3 name for a file with a long filename, and then save the file, vDos preserves the long file name, but DOSBox-X saves only the 8.3 name and the long name disappears.

**Comment by emendelson** [comment]
This should be fixed by some code sent to me by an anonymous programmer, and included in this pull request:

https://github.com/joncampbell123/dosbox-x/pull/3311

**Comment by emendelson** [comment]
The PR is merged. This issue can be closed now.
