### ISSUE TITLE
Missing /X parameter/switch in DIR command

### ISSUE THREAD

**Issue by trubler** [joncampbell123/dosbox-x#3306]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

I need it to shell out from a DOS program to use DIR /X to be able to retreive LFN's from the short filenames.

### What you want

I need (ASAP actually) the /X parameter/switch in the DIR command.

### Describe alternatives you've considered

No alternative. I need the /X parameter very much.

**Comment by rderooy** [comment]
The /X parameter is specific to later versions of Windows. It is not supported by either MS-DOS or Windows 95, 98, 98SE or ME.

**Comment by trubler** [comment]
Any change that it could be implemented anyway?
The software i use stops and can't continue.
Because, after the message "invalid switch" is displayed, the program doesn't find the data it needs.

**Comment by RobertJSawyer** [comment]
If what you need is a directory utility that displays both short and long filenames and works under DOSBox-X, Eric Meyer's old DTA.COM does that just fine. Unfortunately, it won't redirect its output.
[DTA.zip](https://github.com/joncampbell123/dosbox-x/files/8173745/DTA.zip)

**Comment by Wengier** [comment]
If your DOS program really expects a /X option for DIR, then it is not a real DOS program, as no version of DOS supports DIR /X as far I as know. Try use a different DOS program in this case.

**Comment by trubler** [comment]
> If what you need is a directory utility that displays both short and long filenames and works under DOSBox-X, Eric Meyer's old DTA.COM does that just fine. Unfortunately, it won't redirect its output. I've attached it to this comment.
> 
> [DTA.zip](https://github.com/joncampbell123/dosbox-x/files/8173745/DTA.zip)

Thanks, but i needed to capture the output for further processing.

**Comment by trubler** [comment]
> If your DOS program really expects a /X option for DIR, then it is not a real DOS program, as no version of DOS supports DIR /X as far I as know. Try use a different DOS program in this case.

It was always used in XP, in a DOS box. And yes, it is a real DOS program, but build to use LFN.
I created the program for a custom, specific purpose. There is no other program in this world that does what this program does.
It's too specific.
Besides: there's no LFN in DOS, but there is in DOSBox-X ? But no DIR /X ?
BTW, i have solved this now by spending hours modifying the program to deal with this.

**Comment by rderooy** [comment]
There is LFN in DOS with MS-DOS 7.0, 7.1 and 8.0 which were respectively included with Windows 95, 95OSR2 and ME. You can boot these DOS versions without starting Windows.

So yes, there was never a stand-alone commercial release that supported LFN, but it does exist and can be used stand-alone as a regular DOS version, unlike with DOS box of XP.

**Comment by Wengier** [comment]
ROM-DOS 7.1 as another DOS variant does natively support LFN, and it is a stand-alone commercial release, although it is less famous and used by fewer people than MS-DOS. In any case, some versions of DOS do support LFN, perhaps with the help of DOSLFN, but as mentioned above they do exist and can be used stand-alone as regular DOS versions.

**Comment by trubler** [comment]
Since this was only a request for the /X parameter in the DIR command, and comments are already going sideways, i close this.

**Comment by Wengier** [comment]
If any version of DOS supports DIR /X, then it can be considered. But unfortunately, no DOS version (whether or not they support LFN) has such an option as far as we know.

**Comment by trubler** [comment]
At least the DOS box in XP does. That's what i used, as i wrote earlier.
But it doesn't matter anymore. I have solved the problem.
(BTW. strange that, after i closed this issue, people still can comment.)
