### ISSUE TITLE
S3 emulation status

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#3307]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

On the draft wiki
https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3AVideo-card-support-in-DOSBox%E2%80%90X#s3-graphics-experimental-support

All the S3 chipset emulation (apart from the Trio64) is currently marked as experimental.

Do you feel that I can remove the experimental tag from some of them, like perhaps the 86c928 and Vision864/868 chips?

**Comment by joncampbell123** [comment]
So far Windows 3.1, 95, and 98 seem to work fine without any issues for Vision864/868 through Trio64V+. ViRGE is experimental and currently incomplete, of course. ViRGE/VX doesn't seem to work with any Windows drivers yet.

86c928 should remain experimental only because of a known display issue in Windows 95 that only happens in "highcolor (16-bit)" mode that affects the start menu and window decorations.

**Comment by rderooy** [comment]
Thanks @joncampbell123 

I have adjusted the draft wiki accordingly.

I have also created earlier today a new flatpak and COPR RPM packages.

**Comment by rderooy** [comment]
One issue I noticed, if I run "whatvga.exe" v1.50 with any of the following cards, it will report the following:

S3 86c928
![whatvga_002](https://user-images.githubusercontent.com/17701098/156227057-750c5803-9098-4aad-9bbd-959ffa21fbf5.png)

S3 Vision864 or Vision868
![whatvga_000](https://user-images.githubusercontent.com/17701098/156226692-41aa6c4b-c16d-44e9-8695-73676ea0c129.png)

S3 Trio32, Trio64, Trio64V+, ViRGE or ViRGE/VX
![whatvga_000](https://user-images.githubusercontent.com/17701098/156227234-a8d6ef1d-09de-4d37-8bfe-9e8bedeab40d.png)

It always reports Trio64 in the VESA BIOS string, and the chip ID is the same for lots of them.

**Comment by joncampbell123** [comment]
Good find. That may explain why machine=svga_s3virgevx causes Windows 3.1 ViRGE drivers to mysteriously drop back to DOS if you run WIN.COM, and why Windows 98 ViRGE drivers are never satisfied enough with ViRGE/VX emulation for the driver to even load.

**Comment by rderooy** [comment]
Video RAM reporting also does not work properly. It seems to support no more then 2MB, if you specify more with ``vmemsize=``, it reports 512KB. But that may be a limitation of the program.

**Comment by rderooy** [comment]
For reference, I found a newer WHATVGA 2.00beta here: https://web.archive.org/web/20081217030257/http://home.worldonline.dk:80/finth/vgadoc4b.zip

Apparently this was the latest version as of the 3rd of August 2000
https://web.archive.org/web/20081217030257/http://home.worldonline.dk:80/finth/

And there is also a version 2.20 and 2.40 beta
https://web.archive.org/web/20081218213031/http://home.worldonline.dk/finth/beta.html

This is what it shows with any of the s3 vision 864/868/964/968 chips (yes it thinks they are all 864 chips):
![whatvga_001](https://user-images.githubusercontent.com/17701098/163844151-4e6d3e52-df2e-439d-b317-8069a0a9410c.png)
