### ISSUE TITLE
Is there any possibility that PWADs will be able to run perfectly in DOSBox-X without source ports?

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3309]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

I know it's problematic in DOSBox SVN Daum and in regular DOS in real hardware, and that it crashes, but I reckon you can do it so that it will go smoothly without crashes in DOSBox-X. I know there are source ports, but I prefer to play Doom WADs in 320x200 and Gravis Ultrasound, without aspect ratio - I run DOS games in DOSBox-X in Windows resolution 2560x1600 in this case - it's bad that it does not exsist a 2574x1600 resolution in Windows, in the Jazz Jackrabbit mind.

**Comment by joncampbell123** [comment]
DOSBox, DOSBox-X, and other forks are just MS-DOS and MS-DOS PC hardware emulators. Whether or not a PWAD is compatible is entirely up to the DOOM executable running inside the emulator.

If you are experiencing crashes, try increasing available memory for the game. Default memory size is 16MB. Perhaps the PWAD is so detailed that there is not enough memory to load it.

**Comment by BridgeHeadland** [comment]
![DoomCrash](https://user-images.githubusercontent.com/85258509/156882946-92e39121-10f8-48f2-b5aa-517d5f20bcc7.png)
I have increased the memsize up to 260, and still it crashes. Do I need to increase more, or is 260 too much?

**Comment by joncampbell123** [comment]
That error is actually a limitation of the original DOOM engine. It happens if there are too many floor and ceiling planes on screen at once. https://doom.fandom.com/wiki/Visplane_overflow

I don't think memsize has any effect on that limit.

**Comment by BridgeHeadland** [comment]
I have downloaded the source port MBF 2.04, MBF is a kind of successor to Boom, 2.04, the latest version, is an unofficial but a known version, where 2.03 is the latest official version. When I went into setup, I realized that I could not run MFB with Gravis Ultrsound, where MFB only supported Gravis Ultrasound PnP. I set the gustype to interwave, although it may be experimental to this day - at least it was a few versions ago (versions of DOSBox-X, of course). I have Gravis Ultrasound Extreme, which should be the successor to Gravis Ultrasound Plug & Play, installed in the C drive directory, so Extreme should, according to my calculations, be better than Plug & Play.

Here is my GUS configuration:
gus=true
gusrate=44100
gusmemsize=-1
gus master volume=0.00
gusbase=240
gusirq=5
gusdma=3
gustype=interwave
ultradir=C:\ULTRASND

And if you look at that picture, you see that there is no check mark next to GUSPNP.
![No chin](https://user-images.githubusercontent.com/85258509/157106753-06fa82af-67f8-4edb-a8bf-67b5aa04cacf.png)
![No chin 2](https://user-images.githubusercontent.com/85258509/157106759-34db9946-583c-48c1-a922-4b212fda7631.png)

**Comment by joncampbell123** [comment]
DOSBox-X at this time only emulates up to the Gravis Ultrasound MAX, though placeholder settings are there for Interwave and PnP. It also does not yet implement the WSS codec chip that MAX cards had as digital playback separate from the GF1 synthesizer.

**Comment by joncampbell123** [comment]
There is another issue open already discussing Gravis Ultrasound emulation and MAX vs PnP/Interwave. It also discusses increasing GUS memory past 1MB.
