### ISSUE TITLE
Windows builds of SDL 1.x are randomly generating duplicated mouse motion events, causing large random jumps in games

### ISSUE THREAD

**Issue by Zanmato27** [joncampbell123/dosbox-x#331]
I'm having some seriously problems with using the mouse when playing games such as Doom when using the novert.com program (found [here](https://www.doomworld.com/idgames/utils/misc/novert)) to help with mouse controls within DOSBox, however with DOSBox-X, there is a major problem I'm seeing. Whenever I use novert.com and try to play the game using the mouse, the mouse suddenly jerks around in one directions and another with the slightest movement often. With the original DOSBox, it works fine and helps with mouse controls, but with DOSBox-X, it almost renders mouse controls unplayable.

**Comment by joncampbell123** [comment]
I assume novert.com is a utility that blocks vertical mouse movement?

Does turning on or off the 8042 aux emulation help?

**Comment by Zanmato27** [comment]
Yes, novert.com is a utility that blocks vertical mouse movement and was often used for playing Doom (or other games using the id Tech 1 engine) since moving the mouse vertically also moves your character which can make turning with mouse difficult, and no, disabling 8042 aux emulation does not solve this issue for me.

**Comment by joncampbell123** [comment]
Just tried it with DOOM 1.9 shareware, works fine on my end.

Can you provide your dosbox.conf?

**Comment by Zanmato27** [comment]
This is the conf file that I have. I haven't made much changes other than the 8042 emulation and few video settings. [dosbox.txt](https://github.com/joncampbell123/dosbox-x/files/1553822/dosbox.txt)

I'm also having a very annoying problem where DOSBox-X is turning off Num Lock on my keyboard off without my permission to do so.

**Comment by joncampbell123** [comment]
@Zanmato27 Windows builds have code that, when you capture the mouse, synchronize num/caps/scroll lock on your keyboard so that the guest state is reflected through the LEDs on your keyboard. I'll make that an option that is off by default.

**Comment by joncampbell123** [comment]
No issues from my dosbox.conf, but using your dosbox.conf I am able to recreate the issue. Strange.

**Comment by joncampbell123** [comment]
To be fair, some similar issues have been noted with Windows 3.1, the mouse integration driver, and Windows 10. Using a touchscreen, the cursor jumps to 0,0 when removing the finger from the screen.

**Comment by joncampbell123** [comment]
I tried having DOSBox-X log mouse motion as it got it from SDL, and when it adds it to the "mickey counters" in INT 33h emulation, and I didn't see anything odd there.

I also noticed the mickey counter variables are type "float", which may or may not be related to the issue.

DOOM in my tests is calling INT 33h to read motion data (the mickey counters). I notice that's when the float values are typecast to a 16-bit integer as part of INT 33h emulation.

I wonder if there's anything off about VS2017 regarding float to integer typecast when the SSE extensions aren't involved, since the SDL 1.x builds (where this happens) don't use the SSE instructions and the SDL 2.x builds (immune to this problem) use SSE instructions (because SDL 2.x demands it). Somehow that's consistent between x86 and x64 builds.

Perhaps it would be handy to add to the programs on drive Z: a built-in INT 33h mouse test program to catch this kind of thing, one that lets you see what INT 33h is returning for position, motion, and button state when you move your mouse.

**Comment by joncampbell123** [comment]
Debug output, moving mouse around in DOOM. Strange large jumps in value?

mickey=19.005,-3.000 reg=19,-3
mickey=4.001,-2.000 reg=4,-2
mickey=24.007,-6.001 reg=24,-6
mickey=25095.613,-11996.789 reg=25095,-11996     <--here
mickey=15.004,0.000 reg=15,0
mickey=30.008,0.000 reg=30,0
...
mickey=-10.002,0.000 reg=-10,0
mickey=-1.000,0.000 reg=-1,0
mickey=-3157.000,0.000 reg=-3157,0     <--here
mickey=-2.000,0.000 reg=-2,0
mickey=-4.000,0.000 reg=-4,0
...
mickey=-6.001,0.000 reg=-6,0
mickey=-6.002,0.000 reg=-6,0
mickey=-4466.001,0.000 reg=-4466,0     <--here
mickey=-16.004,0.000 reg=-16,0
mickey=-10.003,0.000 reg=-10,0

**Comment by joncampbell123** [comment]
Okay so it seems at random that on Windows SDL 1.x is sending many redundant mouse movement events which accumulate into large mickey counts that cause the large jumps.

dx/dy=27.007,4.001 dm=27.007,8.002 mick=0.000,0.000
dx/dy=33.009,4.001 dm=33.009,8.002 mick=27.007,8.002
dx/dy=35.010,5.001 dm=35.010,10.003 mick=60.017,16.004
mickey=95.026,26.007 reg=95,26
dx/dy=27.007,4.501 dm=27.007,9.002 mick=0.000,0.000
dx/dy=34.009,5.001 dm=34.009,10.003 mick=27.007,9.002
dx/dy=34.009,5.001 dm=34.009,10.003 mick=61.017,19.005
dx/dy=34.009,5.001 dm=34.009,10.003 mick=95.026,29.008
dx/dy=34.009,5.001 dm=34.009,10.003 mick=129.036,39.011
dx/dy=34.009,5.001 dm=34.009,10.003 mick=163.045,49.014
dx/dy=34.009,5.001 dm=34.009,10.003 mick=197.055,59.016
dx/dy=34.009,5.001 dm=34.009,10.003 mick=231.064,69.019
dx/dy=34.009,5.001 dm=34.009,10.003 mick=265.074,79.022
dx/dy=34.009,5.001 dm=34.009,10.003 mick=299.083,89.025
dx/dy=34.009,5.001 dm=34.009,10.003 mick=333.093,99.027
dx/dy=34.009,5.001 dm=34.009,10.003 mick=367.102,109.030
dx/dy=34.009,5.001 dm=34.009,10.003 mick=401.111,119.033
dx/dy=34.009,5.001 dm=34.009,10.003 mick=435.121,129.036
dx/dy=34.009,5.001 dm=34.009,10.003 mick=469.130,139.039
dx/dy=34.009,5.001 dm=34.009,10.003 mick=503.140,149.041
dx/dy=34.009,5.001 dm=34.009,10.003 mick=537.149,159.044
dx/dy=34.009,5.001 dm=34.009,10.003 mick=571.159,169.047
dx/dy=34.009,5.001 dm=34.009,10.003 mick=605.168,179.050
dx/dy=34.009,5.001 dm=34.009,10.003 mick=639.178,189.052
dx/dy=34.009,5.001 dm=34.009,10.003 mick=673.187,199.055
dx/dy=34.009,5.001 dm=34.009,10.003 mick=707.197,209.058
dx/dy=34.009,5.001 dm=34.009,10.003 mick=741.206,219.061
dx/dy=34.009,5.001 dm=34.009,10.003 mick=775.216,229.064
dx/dy=34.009,5.001 dm=34.009,10.003 mick=809.225,239.066
dx/dy=34.009,5.001 dm=34.009,10.003 mick=843.234,249.069
dx/dy=34.009,5.001 dm=34.009,10.003 mick=877.244,259.072
dx/dy=34.009,5.001 dm=34.009,10.003 mick=911.253,269.075
dx/dy=34.009,5.001 dm=34.009,10.003 mick=945.263,279.077
dx/dy=34.009,5.001 dm=34.009,10.003 mick=979.272,289.080
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1013.282,299.083
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1047.291,309.086
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1081.301,319.089
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1115.310,329.091
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1149.319,339.094
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1183.329,349.097
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1217.338,359.100
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1251.348,369.102
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1285.357,379.105
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1319.366,389.108
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1353.376,399.111
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1387.385,409.114
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1421.395,419.116
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1455.404,429.119
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1489.413,439.122
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1523.423,449.125
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1557.432,459.127
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1591.442,469.130
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1625.451,479.133
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1659.460,489.136
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1693.470,499.139
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1727.479,509.141
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1761.489,519.144
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1795.498,529.147
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1829.507,539.150
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1863.517,549.153
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1897.526,559.155
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1931.536,569.158
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1965.545,579.161
dx/dy=34.009,5.001 dm=34.009,10.003 mick=1999.554,589.164
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2033.564,599.167
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2067.573,609.169
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2101.583,619.172
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2135.592,629.175
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2169.602,639.178
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2203.611,649.181
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2237.621,659.183
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2271.630,669.186
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2305.640,679.189
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2339.649,689.192
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2373.659,699.195
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2407.668,709.198
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2441.678,719.200
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2475.688,729.203
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2509.697,739.206
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2543.707,749.209
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2577.716,759.212
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2611.726,769.214
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2645.735,779.217
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2679.745,789.220
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2713.754,799.223
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2747.764,809.226
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2781.773,819.228
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2815.783,829.231
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2849.792,839.234
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2883.802,849.237
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2917.811,859.240
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2951.821,869.242
dx/dy=34.009,5.001 dm=34.009,10.003 mick=2985.830,879.245
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3019.840,889.248
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3053.849,899.251
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3087.859,909.254
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3121.868,919.256
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3155.878,929.259
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3189.887,939.262
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3223.897,949.265
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3257.906,959.268
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3291.916,969.271
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3325.926,979.273
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3359.935,989.276
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3393.945,999.279
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3427.954,1009.282
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3461.964,1019.285
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3495.973,1029.287
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3529.983,1039.290
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3563.992,1049.293
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3598.002,1059.296
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3632.011,1069.299
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3666.021,1079.301
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3700.030,1089.304
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3734.040,1099.307
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3768.049,1109.310
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3802.059,1119.313
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3836.068,1129.315
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3870.078,1139.318
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3904.087,1149.321
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3938.097,1159.324
dx/dy=34.009,5.001 dm=34.009,10.003 mick=3972.106,1169.327
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4006.116,1179.329
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4040.125,1189.332
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4074.135,1199.335
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4108.145,1209.338
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4142.154,1219.341
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4176.163,1229.344
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4210.172,1239.346
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4244.182,1249.349
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4278.191,1259.352
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4312.200,1269.355
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4346.209,1279.358
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4380.219,1289.360
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4414.228,1299.363
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4448.237,1309.366
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4482.247,1319.369
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4516.256,1329.372
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4550.265,1339.374
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4584.274,1349.377
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4618.284,1359.380
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4652.293,1369.383
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4686.302,1379.386
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4720.312,1389.388
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4754.321,1399.391
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4788.330,1409.394
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4822.339,1419.397
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4856.349,1429.400
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4890.358,1439.402
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4924.367,1449.405
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4958.376,1459.408
dx/dy=34.009,5.001 dm=34.009,10.003 mick=4992.386,1469.411
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5026.395,1479.414
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5060.404,1489.417
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5094.414,1499.419
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5128.423,1509.422
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5162.432,1519.425
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5196.441,1529.428
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5230.451,1539.431
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5264.460,1549.433
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5298.469,1559.436
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5332.479,1569.439
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5366.488,1579.442
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5400.497,1589.445
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5434.506,1599.447
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5468.516,1609.450
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5502.525,1619.453
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5536.534,1629.456
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5570.543,1639.459
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5604.553,1649.461
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5638.562,1659.464
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5672.571,1669.467
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5706.581,1679.470
dx/dy=34.009,5.001 dm=34.009,10.003 mick=5740.590,1689.473
dx/dy=34.009,4.001 dm=34.009,8.002 mick=5774.599,1699.475
dx/dy=34.009,4.001 dm=34.009,8.002 mick=5808.608,1707.478
dx/dy=34.009,4.001 dm=34.009,8.002 mick=5842.618,1715.480
dx/dy=34.009,4.001 dm=34.009,8.002 mick=5876.627,1723.482
dx/dy=34.009,4.001 dm=34.009,8.002 mick=5910.636,1731.484
dx/dy=34.009,4.001 dm=34.009,8.002 mick=5944.646,1739.486
dx/dy=34.009,4.001 dm=34.009,8.002 mick=5978.655,1747.489
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6012.664,1755.491
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6046.673,1763.493
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6080.683,1771.495
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6114.692,1779.497
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6148.701,1787.500
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6182.710,1795.502
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6216.720,1803.504
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6250.729,1811.506
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6284.738,1819.508
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6318.748,1827.511
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6352.757,1835.513
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6386.766,1843.515
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6420.775,1851.517
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6454.785,1859.519
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6488.794,1867.522
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6522.803,1875.524
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6556.813,1883.526
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6590.822,1891.528
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6624.831,1899.530
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6658.840,1907.533
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6692.850,1915.535
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6726.859,1923.537
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6760.868,1931.539
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6794.877,1939.541
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6828.887,1947.544
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6862.896,1955.546
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6896.905,1963.548
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6930.915,1971.550
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6964.924,1979.552
dx/dy=34.009,4.001 dm=34.009,8.002 mick=6998.933,1987.555
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7032.942,1995.557
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7066.952,2003.559
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7100.961,2011.561
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7134.970,2019.563
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7168.979,2027.566
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7202.989,2035.568
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7236.998,2043.570
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7271.007,2051.572
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7305.017,2059.574
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7339.026,2067.577
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7373.035,2075.579
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7407.044,2083.581
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7441.054,2091.583
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7475.063,2099.585
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7509.072,2107.588
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7543.082,2115.590
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7577.091,2123.592
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7611.100,2131.594
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7645.109,2139.596
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7679.119,2147.599
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7713.128,2155.601
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7747.137,2163.603
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7781.146,2171.605
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7815.156,2179.607
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7849.165,2187.610
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7883.174,2195.612
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7917.184,2203.614
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7951.193,2211.616
dx/dy=34.009,4.001 dm=34.009,8.002 mick=7985.202,2219.618
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8019.211,2227.621
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8053.221,2235.623
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8087.230,2243.625
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8121.239,2251.627
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8155.249,2259.629
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8189.258,2267.632
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8223.268,2275.634
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8257.277,2283.636
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8291.287,2291.638
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8325.297,2299.640
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8359.307,2307.643
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8393.316,2315.645
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8427.326,2323.647
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8461.336,2331.649
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8495.346,2339.651
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8529.355,2347.654
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8563.365,2355.656
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8597.375,2363.658
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8631.385,2371.660
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8665.395,2379.662
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8699.404,2387.665
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8733.414,2395.667
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8767.424,2403.669
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8801.434,2411.671
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8835.443,2419.673
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8869.453,2427.676
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8903.463,2435.678
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8937.473,2443.680
dx/dy=34.009,4.001 dm=34.009,8.002 mick=8971.482,2451.682
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9005.492,2459.684
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9039.502,2467.687
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9073.512,2475.689
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9107.521,2483.691
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9141.531,2491.693
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9175.541,2499.695
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9209.551,2507.698
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9243.561,2515.700
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9277.570,2523.702
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9311.580,2531.704
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9345.590,2539.706
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9379.600,2547.708
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9413.609,2555.711
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9447.619,2563.713
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9481.629,2571.715
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9515.639,2579.717
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9549.648,2587.719
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9583.658,2595.722
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9617.668,2603.724
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9651.678,2611.726
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9685.688,2619.728
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9719.697,2627.730
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9753.707,2635.733
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9787.717,2643.735
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9821.727,2651.737
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9855.736,2659.739
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9889.746,2667.741
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9923.756,2675.744
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9957.766,2683.746
dx/dy=34.009,4.001 dm=34.009,8.002 mick=9991.775,2691.748
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10025.785,2699.750
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10059.795,2707.752
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10093.805,2715.755
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10127.814,2723.757
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10161.824,2731.759
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10195.834,2739.761
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10229.844,2747.763
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10263.854,2755.766
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10297.863,2763.768
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10331.873,2771.770
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10365.883,2779.772
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10399.893,2787.774
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10433.902,2795.777
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10467.912,2803.779
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10501.922,2811.781
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10535.932,2819.783
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10569.941,2827.785
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10603.951,2835.788
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10637.961,2843.790
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10671.971,2851.792
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10705.980,2859.794
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10739.990,2867.796
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10774.000,2875.799
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10808.010,2883.801
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10842.020,2891.803
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10876.029,2899.805
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10910.039,2907.807
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10944.049,2915.810
dx/dy=34.009,4.001 dm=34.009,8.002 mick=10978.059,2923.812
dx/dy=33.009,3.001 dm=33.009,6.002 mick=11012.068,2931.814
mickey=11045.077,2937.816 reg=11045,2937
dx/dy=28.008,4.501 dm=28.008,9.002 mick=0.000,0.000
dx/dy=24.007,4.501 dm=24.007,9.002 mick=28.008,9.002
mickey=52.014,18.005 reg=52,18
dx/dy=9.002,2.501 dm=9.002,5.001 mick=0.000,0.000

**Comment by joncampbell123** [comment]
I just confirmed that SDL itself (from the DIB event handler i.e. non-DirectX) part of the code is occasionally generating many redundant SDL mouse motion events, which causes this to happen. Nothing in DOSBox-X is causing this issue.

**Comment by joncampbell123** [comment]
Hey, guess what?

SDL is not *intentionally* generating duplicate mouse motion events. Rather, what seems to be happening on Windows 10 is that, when the DIB mouse motion tracking resets the cursor position, it doesn't reposition the cursor *immediately*, there's enough of a delay from Windows 10 that if the message pump is polled fast enough to see the same mouse motion again.

Let me make this clear: The age-old Windows technique of detecting relative mouse motion by reading cursor deviation from the center and re-setting the cursor to center, doesn't work very well anymore in Windows 10. There's enough of a round trip delay (or caching?) between the application and the compositing engine to make SetCursorPos() non-immediate. SetCursorPos(), once immediate in prior versions of Windows, is no longer immediate, and that's what breaks relative mouse motion detection.

**Comment by joncampbell123** [comment]
I just fixed the issue by imposing a 60Hz polling rate on the wingdi mouse motion detector. That seems to fix the sudden jumps.

**Comment by joncampbell123** [comment]
It's fixed as far as I can tell.
