### ISSUE TITLE
I wish DOSBox-X would dim the top line when its window is inactive (which is what vDosPlus does)

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#3314]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What you want

[vDosPlus](http://vdosplus.org/) dims the first line of text on your display when the vDosPlus window is not active. I wish DOSBox-X would do the same thing since when running DOSBox-X full-screen without the menu bar, there's no easy way to tell whether the DOSBox-X window is the active one or not.

Thank you for your kind consideration -- and your terrific product.

**Comment by Wengier** [comment]
Already fixed in #3331.
