### ISSUE TITLE
Moonbugs which uses 160x100 CGA mode doesn't display properly

### ISSUE THREAD

**Issue by pcdosretro** [joncampbell123/dosbox-x#3323]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 7 SP 1 64-bit

### What version(s) of DOSBox-X have this bug?

0.83.23

### Describe the bug

The old CGA game Moonbugs which uses CGA 160x100 16-color hybrid text/graphics mode does not display properly.

### Steps to reproduce the behaviour

Download Moonbugs from here - https://www.digger.org/moonbugs.zip
You must run this game using 8088 XT 4.77 MHz

**Comment by joncampbell123** [comment]
Have you tried machine=cga?

CGA 160x100 mode is a tweaked text mode specific to the CGA video mode and hardware. If your machine type is EGA/VGA then, same as on real hardware, it is not expected to display properly.

If the game expects to use composite color artifacts, then use machine=cga_composite

**Comment by pcdosretro** [comment]
I tried dosbox -set machine=cga and it makes no difference.

**Comment by MobyGamer** [comment]
I just tested the most recent release with machine=cga in my .conf file and it runs just fine, displays properly.

**Comment by Jkapp76** [comment]
I recommend setting machine to CGA in the conf file, not the command line. I've had issues with setting machine type in the command line like this.

**Comment by pcdosretro** [comment]
The problem was output=ttf in my .conf file. Changing this to output=default solved the problem. Closing.
