### ISSUE TITLE
Rise of the Triad Dark War can not be install

### ISSUE THREAD

**Issue by 280696516** [joncampbell123/dosbox-x#3325]
install from cd,
![dosbox_000](https://user-images.githubusercontent.com/54297406/158005049-854f9cec-db4c-4672-b822-1d35bc752d48.png)

**Comment by 280696516** [comment]
[INSTALL.zip](https://github.com/joncampbell123/dosbox-x/files/8238326/INSTALL.zip)

**Comment by grapeli** [comment]
This is a bug on the authors side of this game.
https://www.vogons.org/viewtopic.php?t=16233

The same happens under dosbox-SVN and -staging.
Look for the version with the repaired installer.

**Comment by MX9000** [comment]
The installer works with DOSBox-X booting real MS-DOS 6.
