### ISSUE TITLE
Robert E. Lee Civil War General can not run

### ISSUE THREAD

**Issue by 280696516** [joncampbell123/dosbox-x#3326]
[c.zip](https://github.com/joncampbell123/dosbox-x/files/8237115/c.zip)
black screen

**Comment by maron2000** [comment]
At least you can start the game on Win98 guest.
![relee](https://user-images.githubusercontent.com/68574602/158018453-7b52fa06-5cd8-448d-beb0-fa02d4967c55.png)

**Comment by rderooy** [comment]
@280696516 Sorry, but you can at least TRY to provide some details. How are you running the game, what settings are you using? Did you do any troubleshooting yourself?

I'm not familiar with this game, but there seem to be at least 2 version of it, for Win 3.1 and Win95? Or was it just a Win 3.1 game that also ran on Win95?

**Comment by 280696516** [comment]
I think it's a windows 3.x game.     

dosbox.conf    is  here.
[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount c c
imgmount d CivilWarGeneral.iso -t cdrom
c:
cd windows
win

I only upload c directory.

**Comment by 280696516** [comment]
run    c\SIERRA\CIVILWAR\BOBBYLEE
