### ISSUE TITLE
Is there a way to set the refresh rate using configuration or command lines?

### ISSUE THREAD

**Issue by ndgibson** [joncampbell123/dosbox-x#3328]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

I really need to be able to set the Video Refresh Rate programmatically. I only see a GUI option in the menu bar. Is there an ability to set it via conf file or command line arguments?

**Comment by rderooy** [comment]
If you look at the config file, there is a
```
[video]
forcerate=
```
setting.

**Comment by ndgibson** [comment]
Awesome, thanks.
