### ISSUE TITLE
Additional video modes for PCJr machine

### ISSUE THREAD

**Issue by Jkapp76** [joncampbell123/dosbox-x#3330]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

I think it would be useful to be able to set the machine for the different PCJr screen modes exactly how it is done for CGA machines... cga_rgb, cga_composite, cga_composite2.

Only it would be pcjr_composite1 and pcjr_composite2 only. 

This would allow us to start certain games in the correct mode.

### What you want

Just a small additional bit of code so we can start the pcjr emulation in composite modes 1 or 2. Just as it's already done for CGA modes.

**Comment by rderooy** [comment]
Have a look at the wiki, there are already such options.

https://dosbox-x.com/wiki/Guide%3AVideo-card-support-in-DOSBox%E2%80%90X#_ibm_pcjr

**Comment by Jkapp76** [comment]
Yes. I missed this. closing.
