### ISSUE TITLE
Unable to compile (GCC 7.2.0 on Archlinux)

### ISSUE THREAD

**Issue by madnessmike** [joncampbell123/dosbox-x#334]
`drive_local.cpp:479:16: error: cannot convert ‘bool’ to ‘FILE* {aka _IO_FILE*}’ in return
         return false;
                ^~~~~
drive_local.cpp: In member function ‘virtual void* localDrive::opendir(const char*)’:
drive_local.cpp:920:16: error: cannot convert ‘bool’ to ‘void*’ in return
         return false;
`
Also the compiler often reports this warning:
`warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
`

**Comment by joncampbell123** [comment]
Correct. "false" is not NULL.

If you change "return false" at that line to "return NULL" does that fix the issue?

**Comment by madnessmike** [comment]
Yes, it worked, thank you! :)

I had to change the return also in line #920 of the same file
