### ISSUE TITLE
Windows XP support (changing headers in auto-compiler to 5).

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#336]
Hi, thanks for excellent and greatly supported Dosbox mod.
Currently release builds doesnt run on Windows XP, but really - it's perfectly supported if i change both headers from 06 06 to 05 05 (Required OS version / Subsystem version) (or even 04 (Win 9x) would be better)
http://picsee.net/upload/2017-12-09/dfc3a334de74.png
http://picsee.net/upload/2017-12-09/bc519b501b4f.png
Could you change this preset in git compiler you are using to build.

**Comment by joncampbell123** [comment]
I'm using VS2017 to compile the Windows builds. Anything past VS2015 claims to support Windows XP but doesn't seem to compile right.

The only other method others use to compile Windows binaries is MinGW, which you might try (haven't tried myself, yet).

**Comment by Corak667** [comment]
Strange VS2017 cannot change headers?
https://msdn.microsoft.com/en-us/library/6sehtctf.aspx?f=255&MSPPError=-2147217396

**Comment by joncampbell123** [comment]
I'm not using WINVER defines.

**Comment by roytam1** [comment]
Sorry to ask here, but: does dosbox-x compilable with VC2013?

**Comment by joncampbell123** [comment]
I don't know, I don't have VS2013. Probably, probably not. It depends on how compatible the .sln and .vcproj files are.

**Comment by roytam1** [comment]
@joncampbell123 There is only one line is incompatible to vs2013:

````
diff --git a/src/fpu/fpu_instructions.h b/src/fpu/fpu_instructions.h
index 125759df..81506b2c 100644
--- a/src/fpu/fpu_instructions.h
+++ b/src/fpu/fpu_instructions.h
@@ -461,7 +461,7 @@ static void FPU_FCOM(Bitu st, Bitu other){
         *       "none" for no FPU, 287 or 387 for cputype=286 and cputype=386, or "auto" to match the CPU (8086 => 8087).
         *       If the FPU type is 387 or auto, then skip this hack. Else for 8087 and 287, use this hack. */
        if (CPU_ArchitectureType<CPU_ARCHTYPE_386) {
-               if (std::isinf(fpu.regs[st].d) && std::isinf(fpu.regs[other].d)) {
+               if ((std::isinf)(fpu.regs[st].d) && (std::isinf)(fpu.regs[other].d)) {
                        /* 8087/287 consider -inf == +inf and that's what DOS programs test for to detect 287 vs 387 */
                        FPU_SET_C3(1);FPU_SET_C2(0);FPU_SET_C0(0);return;
                }

````
I can copy vc2015 folder as vc2013 and change every vcxproj ToolsVersion to 13.0 and PlatformToolset to v120_xp, I can compile a working binary, tested and it works in XP SP3.

**Comment by joncampbell123** [comment]
Why does adding parenthesis around std::isinf make it compatible? That doesn't make much sense to me...

**Comment by roytam1** [comment]
> Why does adding parenthesis around std::isinf make it compatible? That doesn't make much sense to me...

short answer: because isinf is a #define in VS2013.
long answer: https://stackoverflow.com/questions/12375745/parenthesis-around-function-call

**Comment by joncampbell123** [comment]
Done

**Comment by Corak667** [comment]
The only problem in XP support was compiler version header 6.x, so when you try to run binary it just says "No access"
http://picsee.net/upload/2017-12-16/7bb190bdda3f.png
The same problem in last compile. So the ONLY fix was aneeded are - changing hex "06 00 00 00 00 00 00 00 06" to "05 00 00 00 00 00 00 00 05", that what i have to do to get it working.

**Comment by joncampbell123** [comment]
Right, sorry. I meant the std::isinf patch was done.

I'll try to get VS2017 to compile a Windows XP target soon.

**Comment by joncampbell123** [comment]
It compiles 99% of the way, but can't find DXGUID.LIB.

**Comment by joncampbell123** [comment]
I just copied DXGUID.LIB from the DirectX SDK into the project to make it work. It runs and compiles. A PE viewer tool confirms the compiled EXE has minimum OS version 5.1 (Windows XP). It looks like I will be able to provide XP compatible binaries.

**Comment by Corak667** [comment]
send me a binary to test on xp

**Comment by joncampbell123** [comment]
Certainly. Here's a beta.
[dosbox-x-windows-20171215-2121-beta.zip.zip](https://github.com/joncampbell123/dosbox-x/files/1564524/dosbox-x-windows-20171215-2121-beta.zip.zip)

**Comment by Corak667** [comment]
Yep, it's working now, thanks!

**Comment by Corak667** [comment]
Also in latest beta you seems broke relative dir mounting
http://picsee.net/upload/2017-12-16/3953f8428ad1.png

**Comment by joncampbell123** [comment]
Noted! Thanks!

https://github.com/joncampbell123/dosbox-x/issues/367

**Comment by roytam1** [comment]
> https://github.com/joncampbell123/dosbox-x/issues/336#issuecomment-352091270

@joncampbell123 please fix this as well!
https://github.com/joncampbell123/dosbox-x/commit/65ca09049fbfed3bdad320f06e246b6119d37bc5#r26317263

**Comment by joncampbell123** [comment]
Yes.

**Comment by joncampbell123** [comment]
Relative mounting seems to work here, on Linux.

It was made possible from Windows-based dosbox.conf as well by a recent commit that takes the host path in IMGMOUNT and MOUNT and converts backslashes to forward slashes.

**Comment by joncampbell123** [comment]
Windows XP support is done, and relative mounting seems to work, so I will close this issue unless I'm wrong.

**Comment by Corak667** [comment]
Nope, not works
http://picsee.net/upload/2017-12-23/b12f5747f070.png

**Comment by joncampbell123** [comment]
Quick question: This is Windows XP you're running it on, right?

Guess what Microsoft broke?

https://github.com/joncampbell123/dosbox-x/issues/403

Yes, they broke _stat() on Windows XP. DOSBox-X can't mount or check the existence of ANYTHING you ask to mount without _stat().

I'm going to have to undo my changes to make Windows XP work because an emulator that can't mount anything is pointless.

But if anyone else here can make WinXP binaries using VS2013 or older, then have at it.

**Comment by Corak667** [comment]
Yes, XP of course

**Comment by Corak667** [comment]
But it had mounted normally on your build 2017-12-09, so you broke it somewhere

**Comment by Corak667** [comment]
As you see:
http://picsee.net/upload/2017-12-23/4fb9f6dfc413.png

**Comment by joncampbell123** [comment]
That build pre-dates making VS2017 target Windows XP, so that comes from your patching the OS version in the PE header.

I'm not sure why targeting Vista or higher fixes the XP _stat() bug, but apparently that's what you're going to have to do to make it run under XP.

I suppose if I sat down for a day I could whip up my own _stat() function to replace Microsoft's but I have more interesting things to do in life than that.

**Comment by Corak667** [comment]
Ok then, i will fix it, not a big deal) 
or why you cannot make some binary autopatcher that changes just 2 bytes in headers? :D

**Comment by joncampbell123** [comment]
Noted #404

**Comment by roytam1** [comment]
> But if anyone else here can make WinXP binaries using VS2013 or older, then have at it.

Yes I do. But I wonder if you will include vs2013 project files?

**Comment by joncampbell123** [comment]
It depends. Are you OK with them in a vs2013 subdirectory?

Are you OK with the fact that over time, some source files will be added to the project and the vs2013 files will have to be updated to reflect that?

**Comment by roytam1** [comment]
> Are you OK with the fact that over time, some source files will be added to the project and the vs2013 files will have to be updated to reflect that?

meanwhile I'm doing this actually. zipped folder(project files only, all sources are referenced to ..\vs2015\*) attached. (rename vs2013.docx to vs2013.zip for extraction)
[vs2013.zip](https://github.com/joncampbell123/dosbox-x/files/1584273/vs2013.docx)

**Comment by joncampbell123** [comment]
Done.

I don't move or add source files around much but be prepared to submit patches to the vs2013 when it happens.

**Comment by joncampbell123** [comment]
@roytam1 Quick question: How much of the C++11 standard does VS2013 implement?

**Comment by roytam1** [comment]
> Quick question: How much of the C++11 standard does VS2013 implement?

https://msdn.microsoft.com/en-us/library/hh567368.aspx
