### ISSUE TITLE
Enabling Disney (Covox) Sound in the Configuration file causes a SegFault

### ISSUE THREAD

**Issue by JacobTheGuy** [joncampbell123/dosbox-x#3360]
This issue seems to be specific to the Linux SDL2 version, as running the exact same build on Windows doesn't cause this issue.
The last line written to the log in the termial is:
`LOG: LPT1: User explicitly assigned Disney Sound Source to this port`
Followed by a Segmentation Fault.

**Comment by rderooy** [comment]
I just tried it Fedora using the COPR RPM packages, and there is no segfault.
```
dosbox-x -defaultconf -set parallel1=disney -set disney=true
```

**Comment by BridgeHeadland** [comment]
[AUDDISNY.ZIP](https://github.com/joncampbell123/dosbox-x/files/8693635/AUDDISNY.ZIP)
Try this to. I think it works as an amplifier.

**Comment by joncampbell123** [comment]
This bug has been fixed. Furthermore, the code has been updated to correctly handle both DOSBox SVN style "disney=true" and DOSBox-X style "parallel1=disney"
