### ISSUE TITLE
Lemmings palette swap works in dosbox but not dosbox-x with same settings

### ISSUE THREAD

**Issue by MatthewRobertDunn** [joncampbell123/dosbox-x#3365]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

0.83.23 SDL Visual Studio

### Describe the bug

The game lemmings uses a palette swap on a vertical interrupt, in dos-box this interrupt works correctly when machine=vgaonly is set:

![image](https://user-images.githubusercontent.com/15967209/160539704-ee913842-9c4a-4219-90e6-bf0f17b24a44.png)

However using the same settings in dosbox-x causes the palette to be swapped in the wrong part of the screen

![image](https://user-images.githubusercontent.com/15967209/160539649-550f399b-08b8-4ca7-8304-4bdeaf1755f9.png)

Perhaps this could be related to? https://github.com/dosbox-staging/dosbox-staging/issues/1526

See also https://www.vogons.org/viewtopic.php?t=57254

### Expected behavior

Palette swap in vga lemmings should work correctly, as it does in dos-box

### Steps to reproduce the behaviour

Download lemmings for dos https://www.myabandonware.com/game/lemmings-16x#download

 In config set machine=vgaonly

Run lemmings and select VGA. 

![image](https://user-images.githubusercontent.com/15967209/160540259-f2b534e4-800a-4d10-8e95-43b2cf893fe9.png)

Then select 2. (High performance PC)

![image](https://user-images.githubusercontent.com/15967209/160540215-5ebce772-5a0b-4313-8576-523c88dc98c7.png)

Start a game with F1.

Note palette corruption that occurs in doxbox-X:

![image](https://user-images.githubusercontent.com/15967209/160540343-bcaeee37-ea67-4077-9c56-20c13c61e93e.png)

Repeat same with dosbox 0.74-3. There is no corruption

**Comment by MatthewRobertDunn** [comment]
Found some additional information about this -- setting frame-skip to '1' resolves this issue. Palette swap only appears to be wrong every second frame..strange.

**Comment by grapeli** [comment]
I don't see any difference. With the same settings. DOSBox-X started with the default `frameskip=0`.

https://user-images.githubusercontent.com/452325/160602801-22318048-e4b0-427c-a47a-d6ac10dde84a.mp4

**Comment by MatthewRobertDunn** [comment]
Hmm...I'm able to reproduce this on three different host machines; though all windows. 
Perhaps it's a windows or SDL1 specific issue?

https://user-images.githubusercontent.com/15967209/160615978-e96f25b1-2d85-43f0-8223-5880ffae4f58.mp4

**Comment by grapeli** [comment]
The last released version of dosbox-x which worked fine was 0.82.14.

https://user-images.githubusercontent.com/452325/160690364-1641ae86-fc9a-4ab3-aec0-0051dd4887d2.mp4

The last good commit is this one 8a89f5e.
Something went wrong with this change beaea4e.

**Comment by grapeli** [comment]
Changes to PIT [src/hardware/timer.cpp](https://github.com/joncampbell123/dosbox-x/commits/master?after=876254fee902fe0b6dafbeb3660a0bd4754f9b68+34&branch=master&path%5B%5D=src&path%5B%5D=hardware&path%5B%5D=timer.cpp) made between versions 0.82.14 to 0.82.15 have a major impact on how Lemmings works under DOSBox-X.

I already noted in Issue #3211 that dosbox-x's PIT does not work properly compared to -SVN and -staging. GP2 also works differently at 0.82.14 than at 0.82.15. Under GP2 it is less noticeable and certainly not on computers with 4.5-5GHz CPUs.

**Comment by maron2000** [comment]
Hi, isn't the current version (0.83.23 release) playing the game slowly?
You can see it by looking at the remaining time of the game.
I think a single line should be fixed.
```
Line 278 of timer.cpp
//double tmp = fmod(index,(double)delay) * 2; //before
double tmp = fmod(index,(double)delay * 2);  // after
```

Capture of 0.83.23 release (glitchy graphics and working slowly)

https://user-images.githubusercontent.com/68574602/160967337-943bf018-d233-40f4-a8d7-e7f4b05afb8a.mp4

Patched version (from latest commit)

https://user-images.githubusercontent.com/68574602/160967387-3b72b54c-1120-4d9e-97c3-859595bafb23.mp4

**Comment by grapeli** [comment]
@maron2000 
Your patch fixes Lemmings working in dosbox-x. I confirm.

Unfortunately, nothing improves on GP2, but that's a different bug report.

**Comment by maron2000** [comment]
@grapeli Thanks for confirming. Regarding GP2, is it because of fmod() function? If so, proposed patch shouldn't work because it uses fmod() anyway.

@Wengier  Thank you for applying the patch to your PR. Nice work!

**Comment by grapeli** [comment]
@maron2000 
I was showing the exact result with linux perf in a #3211 bug report. Under dosbox-x the load from libm (fmod) is several times higher than under dosbox-SVN.
The dosbox-x-0.82.14 version of `timer.cpp` **is very close** to that of -SVN. The load generated by libm is significantly lower (GP2). Optimization of libm functions (fmod) is closely related to the type of CPU and its capabilities. Maybe under my CPU (intel westmere) with sse4_2 without avx, avx2, avx512,... performs worse.

**Comment by maron2000** [comment]
I think we can close this issue for now.
We can reopen this when a problem arises on modifying timer code.
