### ISSUE TITLE
Errors are displayed, Chinese word, is mistaken for a frame line

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3367]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

DosBox-X v0.82.23

### Describe the bug

Errors are displayed, the same Chinese word, is mistaken for a frame line 
ex:
喜美19楓樹
喜美23國際
喜美43永豐
喜美21大豐

### Steps to reproduce the behaviour

in dosbox-x 0.83.23:
1. rename testdbf.rar.jpg to testdbf.rar
2. unWinrar testdbf.rar
3. execute: TestDbf.exe
![testdbf rar](https://user-images.githubusercontent.com/93595854/160751252-e0b88786-5d40-4ddd-93e2-47091ea489cf.jpg)

**Comment by Wengier** [comment]
Try disable auto box-drawing character detection in this specific case (under “Video” menu -> “TTF options”). Automatic box-drawing character detection can never be 100% perfect, so you may need to disable it in such rare conditions.

**Comment by Arthur3032** [comment]
OK, Thank You very much.

**Comment by Arthur3032** [comment]
dear sir: Accessing dos files in dosbox-x is much slower than accessing them in pure windows, and there are ways to improve them

**Comment by rderooy** [comment]
Try to set

```
[dos]
hard drive data rate limit=0
floppy drive data rate limit=0
```

**Comment by Arthur3032** [comment]
I already set it like this. But the performance is still slow, is there any other place to set it?

**Comment by rderooy** [comment]
I don't know what you consider to be significantly slower. But emulation is not free, some delay is normal.

If you run with the above settings any DOS benchmark application, the disk access on a system with SSD or NVME will be very fast compared to actual systems from back in the day.

**Comment by Arthur3032** [comment]
For example: 
the same DBF file, use Visual FoxPro to access it in windows, and DosBox-x, use Clipper to access it. DosBox-X is much slower.
Currently, I have to use Visual FoxPro to read the data, and then pass it to Clipper for subsequent processing.

**Comment by kcgen** [comment]
@Arthur3032 , in your DOSBox-X `Z:\>` prompt, type **`config -set cpu cycles=max`**, as follows:

![2022-04-02_10-50](https://user-images.githubusercontent.com/1557255/161395141-f26cbc62-ddc6-4164-b2e2-5074f1161fe4.png)

Then launch Visual FoxPro and retry the save.

**Comment by Arthur3032** [comment]
The screen display is significantly faster, but Disk fwrite() is not faster
