### ISSUE TITLE
Bring out my old "automake to VS2008"  generator because VS2017 project management is a pain in the ass

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#338]
Way back in 2010 I wrote a project that primarily targeted Linux but also supported Visual Studio 2008.

It was done by adding non-standard variables to Makefile.am and configure.ac that are ignored by automake/autoconf but then interpreted by a Perl script I wrote that then auto-generate VS2008 compatible .sln and .vcproj files to compile the same.

I should drag out that code, and update it for VS2017, because getting SDL and SDL2 targets, debug and release, win32 and x64, to work proved that anything beyond a simple project "solution" is a pain to do in VS2017 and it would be less time consuming to just have my Linux system auto-regenerate the VS2017 files from the makefiles.

**Comment by heydojo** [comment]
I don't even think that the people at Microsoft are using VS (the IDE application.) Looks like they install it for it's tools and then script their builds using powershell.
Actually, I just had a thought that might be worth mentioning, in that Microsoft are testing a C++ packaging system on github you might may be interested in.
https://github.com/Microsoft/vcpkg
