### ISSUE TITLE
DOSBox Integration Device documentation?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#3385]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

I've been using the DOSBox Integration Device for seamless mouse movement in my Windows 3.11 setup running under Windows 10/11. It seems to work perfectly. But this wiki page -

https://dosbox-x.com/wiki/Guide%3ACPU-settings-in-DOSBox%E2%80%90X#_integration_device

- suggests that it isn't ready for anyone except developers. Is it possible to document this with a link to the binaries and installation file?

Or should we use the VMmouse driver instead, which seems to accomplish the same thing?

**Comment by Wengier** [comment]
DOSBox-X’s Integration Device is currently considered experimental, as mentioned in the config file or Wiki. Specific functions may work in some degree, but I do not think they are officially considered in production state, and no full documentation appears to be currently available. I recommend using it at your own risk.

**Comment by emendelson** [comment]
OK. The VM mouse driver seems to do the same job, and I'll switch to that. Closing this
