### ISSUE TITLE
Wrong version of application attached to release

### ISSUE THREAD

**Issue by iliadmitriev** [joncampbell123/dosbox-x#3391]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

any

### What version(s) of DOSBox-X have this bug?

0.83.24 MacOS arm64 SDL1

### Describe the bug

I downloaded version: 0.83.24 MacOS arm64 from this page
https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.83.24
with this link
https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.24/dosbox-x-macosx-arm64-20220401072034.zip

### Expected behavior

there are two applications SDL1 and SDL2 builds of one version `0.83.24` inside downloaded archive

### Steps to reproduce the behaviour

1. download archive
2. unpack some where
3. check version:
* SDL1 - `0.83.23` ❌
* SDL2 - `0.83.24`✅

**Comment by iliadmitriev** [comment]
may be connected to #3383

**Comment by Wengier** [comment]
I believe it is the same issue as #3383 indeed.
