### ISSUE TITLE
Lameduke in GUS and VESA, if possible

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3406]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

Actually not.

### What you want

Yes, I'm fully aware that Lameduke is an early, buggy prototype for Duke Nukem 3D, which is why it has never been possible to run Lameduke with GUS and / or VESA (640x480), even if you replace dos4g with dos32a, but I look at DOSBox in general as a non-standalone operating system for standalone Windows operating systems (between XP and 11), which is much better than regular DOS, which is a standalone operating system, where Windows 1, 2, 3 and 9x / ME are non-standalone operating systems, and therefore I think that a future DOSBox can even make Lameduke run in VESA, especially when DOSBox-X is updated about every month - I'm a little unsure if Lameduke will be able to run in GUS , I have barely been able to get the prototype game to run in VESA, but it will not start if I set the sound to GUS, or other sound setups outside of Sound Blaster and Adlib, and there will be no sound with Adlib.

### Describe alternatives you've considered

I was thinking of an experimental MS-DOS 8.0 emulation, but I do not know if it is possible.

**Comment by joncampbell123** [comment]
Be aware some early betas that offer VESA modes aren't exactly stable.

There is a beta of DOOM, for example, that offers a 16bpp VESA mode that doesn't work.

Duke Nukem 3D (the release) works with VESA in the latest commit. I'll test lame duke.

**Comment by joncampbell123** [comment]
The water mirror effects in 320x200 chained VGA mode don't work properly, neither does the security camera effect.

**Comment by joncampbell123** [comment]
The 640x480 VESA mode in lameduke seems to crash with a divide by zero very quickly.

**Comment by joncampbell123** [comment]
The divide by zero happens in the menu demo mode. When the distant object hits the ground, divide by zero.
If you're quick enough with the menu, you can start the game before that happens. But then the game is a little glitchy looking even then. Enemy sprites do not render any scanlines in the top 1/4th of the screen. If you go into the room with a mirror or security camera that renders another view, then it changes the view port to draw a 320x200 image in the upper left hand corner of the 640x480 display. The water mirror effects do not work at all.

**Comment by joncampbell123** [comment]
I don't believe the VESA 640x480 mode issues are DOSBox-X's fault. This is beta code and it looks like it was tested only with the one particular 320x200 256-color mode.
