### ISSUE TITLE
do not let the user directly close dosBox-X Windows.

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3408]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

dear sir,
How to set, do not let the user directly close dosBox-X Windows. Be sure to end DOSBOX-x via the option in the Clipper program.
In this way, dbf files are less susceptible to damage.

**Comment by Wengier** [comment]
Instead of closing directly, I think there should be always a warning message showing up when you click the close button in such case.

**Comment by Arthur3032** [comment]
I mean, don't allow the DOSBOX-X window to be closed directly after the warning message is issued.
Close the window only if the "exit command" from command mode is allowed.
我的意思是, 發出警告訊息之後, 也不要允許直接關閉DOSBOX-X視窗.
只要允許由command mode 發出 "exit 指令" 才關閉視窗

**Comment by Wengier** [comment]
You can try set ``allow quit after warning = false`` to disable the quit option with the Windows build below:

https://github.com/joncampbell123/dosbox-x/suites/6113571621/artifacts/212490000

**Comment by Arthur3032** [comment]
Okay, very good, thank you.
This is the x86 version, is there an x64 version too?

**Comment by Arthur3032** [comment]
In addition, for DOSBOX-X Traditional Chinese, is it possible for the operator to enlarge or reduce the size of the window? (Not setting the font size)

**Comment by Wengier** [comment]
64-bit Windows build:

https://github.com/joncampbell123/dosbox-x/suites/6116905958/artifacts/212681261

You can enlarge or reduce the window size via “Increase TTF font size” and “Decrease TTF font size” options, either from menu (“Video” => “TTF options”) or via keyboard shortcuts found there. Hope this helps.

**Comment by Arthur3032** [comment]
Understood, thank you
