### ISSUE TITLE
Windows 98 on dosbox-x is unable to see the mounted iso image.

### ISSUE THREAD

**Issue by sudosuse** [joncampbell123/dosbox-x#3418]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 8.1 Pro

### What version(s) of DOSBox-X have this bug?

DosBox-X 0.83.24 SDL1

### Describe the bug

Hello, let me explain right here, basically when i run Windows 98SE there no cd-rom drive even when i add "IMGMOUNT D Win98SE.iso" at my configuration file, it doesnt work. Here my command that i use to launch dosbox-x and the configuration file

Here the command that i use to launch dosbox-x:

```
cd C:\Dosbox-x

dosbox-x -conf win95.conf -ide auto
```

And here is the autoexec part of my config file:
```

[autoexec]

# Lines in this section will be run at startup.

# You can put your MOUNT lines here.

IMGMOUNT C hdd.img

IMGMOUNT D C:\Users\Adam\Documents\cd\win98SE.iso

boot c:

```

I hope there a workaround since this bug is annoying, and i tried to use Windows 95 but some installers for some games freeze the entire VM.

### Expected behavior

To see the CDROM drive appears in My Computer, and to see the mounted iso file working.

### Steps to reproduce the behaviour

1. add IMGMOUNT D "path to iso file"\"isofile" in the autoexec part of the config file
2.  Install Windows 98 Second Edition
3. Open My Computer.

### Used configuration

```ini
[ide, primary]
#         enable: Enable IDE interface
#            pnp: List IDE device in ISA PnP BIOS enumeration
#    int13fakeio: If set, force IDE state change on certain INT 13h commands.
#                   IDE registers will be changed as if BIOS had carried out the action.
#                   If you are running Windows 3.11 or Windows 3.11 Windows for Workgroups
#                   you must enable this option (and use -reservecyl 1) if you want 32-bit
#                   disk access to work correctly in DOSBox-X.
# int13fakev86io: If set, and int13fakeio is set, certain INT 13h commands will cause IDE emulation to
#                   issue fake CPU I/O traps (GPF) in virtual 8086 mode and a fake IRQ signal. You must
#                   enable this option if you want 32-bit disk access in Windows 95 to work with DOSBox-X.
#
# Advanced options (see full configuration reference file [dosbox-x.reference.full.conf] for more details):
# -> irq; io; altio; enable pio32; ignore pio32; cd-rom spinup time; cd-rom spindown timeout; cd-rom insertion delay
#
enable         = true
pnp            = true
int13fakeio    = true
int13fakev86io = true

[ide, secondary]
enable                 = true
pnp                    = true
int13fakeio            = true
int13fakev86io         = true
cd-rom insertion delay = 4000

[ide, tertiary]
enable = false
pnp    = true

[ide, quaternary]
enable = false
pnp    = true

[ide, quinternary]
enable = false
pnp    = true

[ide, sexternary]
enable = false
pnp    = true

[ide, septernary]
enable = false
pnp    = true

[ide, octernary]
enable = false
pnp    = true

[fdc, primary]
#         enable: Enable floppy controller interface
#            pnp: List floppy controller in ISA PnP BIOS enumeration
# int13fakev86io: If set, certain INT 13h commands will cause floppy emulation to issue fake CPU I/O
#                   traps (GPF) in virtual 8086 mode and a fake IRQ signal. You must enable this
#                   option if you want 32-bit floppy access in Windows 95 to work with DOSBox-X.
#           mode: Floppy controller mode. What the controller acts like.
#                     ps2                          PS/2 mode (most common)
#                     ps2_model30                  PS/2 model 30
#                     at                           AT mode
#                     xt                           PC/XT mode
#
# Advanced options (see full configuration reference file [dosbox-x.reference.full.conf] for more details):
# -> irq; io; dma; instant mode; auto-attach to int 13h; chip
#
enable         = false
pnp            = true
int13fakev86io = true
mode           = ps2

[4dos]
rem = This section is the 4DOS.INI file, if you use 4DOS as the command shell

[config]
#       rem: Records comments (remarks).
#     break: Sets or clears extended CTRL+C checking.
#              Possible values: on, off.
#   numlock: Sets the initial state of the NumLock key.
#              Possible values: on, off.
#     shell: Specifies the command shell (COMMAND.COM or 4DOS.COM).
#       dos: Reports whether DOS occupies HMA and allocates UMB memory (if available).
#      fcbs: Number of FCB handles available to DOS programs (1-255).
#     files: Number of file handles available to DOS programs (8-255).
#   country: Country code for date/time/decimal formats and optionally code page for TTF output and language files.
# lastdrive: The maximum drive letter (A-Z) that can be accessed by programs.
#              Possible values: a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z.
rem         = This section is DOS's CONFIG.SYS file, not all CONFIG.SYS options supported
break       = off
numlock     = 
shell       = 
dos         = high, umb
fcbs        = 100
files       = 200
country     = 
lastdrive   = a
set path    = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL
set prompt  = $P$G
set temp    = 
install     = 
installhigh = 
device      = 
devicehigh  = 

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
IMGMOUNT C hdd.img
IMGMOUNT D C:\Users\Adam\Documents\cd\win98SE.iso
boot c:
```

**Comment by rderooy** [comment]
I don't know what your trying to accomplish with the ``-ide auto`` option, but there is no such startup option for dosbox-x. You can see the list of valid options here on the wiki: https://dosbox-x.com/wiki/DOSBox%E2%80%90X%E2%80%99s-Command%E2%80%90Line-Options

I don't know what is causing the problem, but could you comment out the `boot c:` line and see if the IMGMOUNT of the ISO is failing?

**Comment by sudosuse** [comment]
No i tried this before i change the a other version of Windows (which works with the cdrom) and its correctly, i can access to the D: and it works like it should but on  Windows 98 it does not seems see the drive.

**Comment by rderooy** [comment]
When you boot Win98 are there any errors in device manager? Does it report a CD-ROM? If so, what resources is it setup for?

I don't know what is causing your problem, as it is working just fine here.

You say your using the SDL1 version. I assume the VS (visual studio) build? Have you tried the SDL2 VS version or any of the minGW versions?

**Comment by sudosuse** [comment]
No i aven't try, there aren't but when trying to make Windows detect an new hardware, it finds a other ide controller, which does not resolve the bug.

**Comment by rderooy** [comment]
Another thing you can try is when mounting the ISO is to add the option `-ide 2m`. This will force it to master on the secondary IDE controller, instead of letting DOSBox-X work it out itself which IDE device to use for it.

**Comment by sudosuse** [comment]
i already tried this yesterday and it didn't work.

**Comment by Wengier** [comment]
I think you can try boot into the DOS mode of Windows 98, with DOS CD-ROM driver loaded (e.g. OAKCDROM.SYS or VIDE-CDD.SYS + MSCDEX.EXE) and see if it works there. If so, type WIN to run Windows 98 GUI (without removing the DOS CD-ROM driver) and see if the CD-ROM works.

**Comment by maron2000** [comment]
I currently have no problem by explicitly specifying CD and ide controller.
`imgmount D your.iso -t cdrom -ide 2m`
In this case make sure that your hard drive images are NOT mounted to the secondary controller.

**Comment by sudosuse** [comment]
i'll try it later thanks !

**Comment by dpuza** [comment]
I believe the same thing is happening to me.

DOSBox-X 0.83.24
Fresh installs of both Win95 and Win98 SE to clean blank images.

However I'm mounting an actual physical CD drive.  The mounted drive works until Windows is booted.  Tried mounting with various parameters.  For example:

MOUNT D D: -t cdrom
MOUNT D D:
MOUNT D "D:" -t cdrom -label LABEL
MOUNT D "D:" -t cdrom -usecd 0 -ioctl
MOUNT D D: -t cdrom -ide 2m

The only other thing in my autoexec conf is this.  I tried mounting the D before and after the C in the autoexec.  The output says it is successful.  If I comment out the BOOT I am able to use the D drive without issue.

IMGMOUNT C "C:\PATH\TO\MY.IMG"
BOOT C:

The rest of the conf is copied and pasted from here: https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-95

memsize=480

[dos]
ver=7.1

Had ver=7.0 at first until I realized I had missed that.  But it doesn't work with either.

**Comment by dpuza** [comment]
I'm able to see a CD ROM drive within Windows for the first time, but that's by using IMGMOUNT instead of trying to mount an actual CD drive with MOUNT.  So my issue seems to be a different one... 

At first when I tried mounting both, DOSBox-X would terminate when I try to DIR the IMGMOUNT one.  But then I added a tertiary ide section, and explicitly specified -ide 1m, 2m, and 3m for each mount.  Windows still doesn't see my physical CD drive though.  Only the IMGMOUNT one.

**Comment by dpuza** [comment]
Found this.  So apparently what I'm trying to do won't work, at least as of 2 years ago.

https://www.reddit.com/r/dosbox/comments/jdsm7t/windows_98_in_dosbosx_no_cd_drive/

**Comment by rderooy** [comment]
Your problem is not the same as the original poster. You cannot use a folder mounted (or real) CD-ROM when you **boot** a guest OS in DOSBox-X. Only image files (e.g., ISO, CUE/BIN) are possible when booting a guest OS. This is documented on the wiki.

What you can do nowadays is change the CD image after booting an OS from the menus. So you don't have to shutdown and restart the guest OS to access a CD image that was not originally specified.

**Comment by dpuza** [comment]
@rderooy Agreed, and thanks for pointing out the DOS menu > "Change current CD image" option.  That's very helpful.  I had been looking under the Drive menu and all the options are disabled.

As a complete newbie as of yesterday I'm saying it could be clearer on the wiki that you cannot folder mount for guest OS.  The wiki has a lot of great information, I'm sure it's mentioned somewhere.  Just saying there were a lot of relevant spots on the wiki that I was referring to where it would have been helpful to have been mentioned.  Since it's a wiki, perhaps I can submit edits.
