### ISSUE TITLE
SimFarm: Cannot save game, "Not enough disk space free"

### ISSUE THREAD

**Issue by driver1998** [joncampbell123/dosbox-x#3419]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 19044 x64, Windows 11 Insider 22598 ARM64

### What version(s) of DOSBox-X have this bug?

after 0.83.0, only tested MSVC x64 and ARM64 builds

### Describe the bug

Start a game and try to save, the game reports "Not enough disk space free".
![simfarm_000](https://user-images.githubusercontent.com/22699485/163785876-f082c66e-61a8-4041-b500-e8c6ce4a8e37.png)

This is broken since 0.83.0 (0.83.0 itself works), I have only tested MSVC x64 and ARM64 releases.

### Expected behavior

It should save correctly.
![simfarm_000](https://user-images.githubusercontent.com/22699485/163786748-ef3f81ad-326f-4deb-b54a-4c017365dcec.png)

### Steps to reproduce the behaviour

1. Install the game from disk images on archive.org: https://archive.org/details/000543-Simfarm. Install target (C:) is mounted as folder.
2. Start a new game
3. Try to save

**Comment by rderooy** [comment]
Try limiting the amount of disk space reported by using the `-freesize` option during mount.

e.g.,
```
mount c . -freesize 32
```

The above command will mount the current working directory as the C: and report a maximum of 32MB of free space.

**Comment by driver1998** [comment]
It does work after limiting the disk space, so I guess this is some overflow happened in the game then.
Why it worked in 0.83.0 (and normal DOSBox 0.72) though...

**Comment by driver1998** [comment]
Looks like it is limited to 256MB before, and unlimited by default now, so this is expected.
Closing the issue.

**Comment by rderooy** [comment]
Some DOS programs can handle larger disk sizes then others. But your right in that some kind of overflow most likely happens.

For late era dos programs 256 free is not enough, and for early programs it can already be too much. So there is not a golden setting.

Another thing that DOSBox-X handles a little different is that in regular DOSBox you always have 256MB available, even if you create new files and there is not actually that much disk space available on the drive (disk full or nearly full). While in DOSBox-X it will take the actual available disk space into account, so if you specify `-freesize 256` and there is actually only 100MiB available, you will see 100MiB free, not 256.
