### ISSUE TITLE
Remapping keys of some menu items?

### ISSUE THREAD

**Issue by oredaze** [joncampbell123/dosbox-x#3422]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

I can remap keys with the mapper-dosbox-x.map file, but not all of the menu items have an equivalent entry in that file (at least mine did not have). For example what is the "hand_????" name for the Video>Force Scaler menu entry? I need to remap this one.

**Comment by Wengier** [comment]
There are so many menu items, and indeed not all are available in the Mapper Editor. Why not just click the menu option(s) in case they do not appear in the mapper?

**Comment by oredaze** [comment]
I toggle that one on and off quite often depending on the game, so it's pointless to set it in the config, also it's almost the only one that I don't have a hotkey for, except switching CPU's. I wanted to make those be 1,2,3,4...etc. It would be nice if I can get rid of the menu and use only keys.

**Comment by Wengier** [comment]
The "force scaler" menu item (along with "Print text screen") has been added to the mapper. If you use Windows, you can try the builds below:

32-bit build: https://github.com/joncampbell123/dosbox-x/suites/6224862055/artifacts/220580530
64-bit build: https://github.com/joncampbell123/dosbox-x/suites/6224862067/artifacts/220581000

Hope this helps.

**Comment by oredaze** [comment]
Thanks so much for the fast action. This obviously wasn't of any priority.
I use linux, so I'll compile it during the next stable release.
