### ISSUE TITLE
Darker doesn't work in v0.83.24, worked well in v0.83.23 with the same settings

### ISSUE THREAD

**Issue by rarioj** [joncampbell123/dosbox-x#3423]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

macOS Monterey Intel i5

### What version(s) of DOSBox-X have this bug?

0.83.24 (version 0.83.23 works)

### Describe the bug

Running the game on v0.83.24 produces blank screen. It doesn't respond to anything. Log messages in the console doesn't produce any error. The only way to exit is to force quit DOSBox-X.

This game worked well on older version (tested on v0.83.23).

Darker: https://www.myabandonware.com/game/darker-2dn

### Expected behavior

Blank screen on 0.83.24:
<img width="640" alt="Darker_-_DOSBox-X_0_83_24__40000_cycles_ms__X" src="https://user-images.githubusercontent.com/1491389/164275562-9faf443d-9ae0-4cbc-b113-2bc04eaa673f.png">

Working on 0.83.23:
<img width="640" alt="Darker_-_DOSBox-X_0_83_23__40000_cycles_ms__X" src="https://user-images.githubusercontent.com/1491389/164275212-417efcb1-5ac6-4cda-abef-21dce0111e36.png">

### Steps to reproduce the behaviour

Run DOSBox-X.
Load the game
```
C:
CD C:\DARKER
X.EXE
```

### Used configuration

```ini
cycles=40000 fixed
```

### Emulator log

```text
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (1280.000 x 800.000 pixels) at (0.000 x 0.000) (286.449 x 179.031 mm) (11.278 x 7.048 in) (113.500 x 113.500 DPI)
LOG: Screen report: Method 'CoreGraphics' (1280.000 x 800.000 pixels) at (0.000 x 0.000) (286.449 x 179.031 mm) (11.278 x 7.048 in) (113.500 x 113.500 DPI)
LOG: pixratio 1.200, dw true, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (1280.000 x 800.000 pixels) at (0.000 x 0.000) (286.449 x 179.031 mm) (11.278 x 7.048 in) (113.500 x 113.500 DPI)
LOG: Screen report: Method 'CoreGraphics' (1280.000 x 800.000 pixels) at (0.000 x 0.000) (286.449 x 179.031 mm) (11.278 x 7.048 in) (113.500 x 113.500 DPI)
LOG: pixratio 1.000, dw true, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (1280.000 x 800.000 pixels) at (0.000 x 0.000) (286.449 x 179.031 mm) (11.278 x 7.048 in) (113.500 x 113.500 DPI)
LOG: Screen report: Method 'CoreGraphics' (1280.000 x 800.000 pixels) at (0.000 x 0.000) (286.449 x 179.031 mm) (11.278 x 7.048 in) (113.500 x 113.500 DPI)
```

**Comment by grapeli** [comment]
The same code change f9a9d6b as the Classic Jumpman (#3380) is causing Darker to not start properly.

**Comment by maron2000** [comment]
I could start Darker by the patch to fix both Jumpman and Lemmings.
https://github.com/joncampbell123/dosbox-x/issues/3380#issuecomment-1100627651

You can test this macos version
https://github.com/maron2000/dosbox-x-1/suites/6144413663/artifacts/214498111

![darker](https://user-images.githubusercontent.com/68574602/164337589-696b39e9-8f39-4673-b733-8920e187962f.png)

**Comment by rarioj** [comment]
@maron2000 that's awesome. I'm afraid I couldn't test it myself as I use dosbox-x with homebrew cask. When I tried to run the binary you provided it showed me this error:

```
dyld[96186]: Library not loaded: /usr/local/opt/libslirp/lib/libslirp.0.dylib
  Referenced from: /Applications/dosbox-x.app/Contents/MacOS/dosbox-x-sdl1
  Reason: tried: '/usr/local/opt/libslirp/lib/libslirp.0.dylib' (no such file), '/usr/local/lib/libslirp.0.dylib' (no such file), '/usr/lib/libslirp.0.dylib' (no such file)
```
So I believe this will be fixed on the upcoming version :)

**Comment by maron2000** [comment]
@rarioj The patch is already included in the PR list, so hopefully it will be applied in the next release. (I hope it will not induce other bugs...)
And for your log, it seems that libslirp is missing, you may want to try installing it.
`brew install libslirp` 
I know some people don't want to install additional softwares, so it's only up to you to install and try.

**Comment by grapeli** [comment]
@maron2000 
I confirm. Darker is back in operation after this change 2f48151.

**Comment by maron2000** [comment]
I think we can close this issue for now.
We can reopen this if the issue arises again when someone modifies the timer code.

**Comment by joncampbell123** [comment]
Confirmed working, 0.84.1 master commit.
