### ISSUE TITLE
Games testing: Briganty: Introduction may not be showing all slides and sprites. Game runs with vertically squeezed screen. Crashes when ems=true

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#343]
Issues:
- Blank screens for some portions of the dialog, which seems wrong (but verify against real hardware)
- No FM music, even though configuration menu suggests it should be enabled
- Game crashes after introduction with "memory over" error.

Game testing discretion advised: One scene in the introduction has very mild nudity.

Main menu.
![shsw_000](https://user-images.githubusercontent.com/6245486/33809528-451abbb6-ddad-11e7-97f3-76349d13e2b8.png)

![shsw_001](https://user-images.githubusercontent.com/6245486/33809529-49a7cf0c-ddad-11e7-9e53-e773cd9e3372.png)

This blank screen continues for what is probably an entire scene.
![shsw_002](https://user-images.githubusercontent.com/6245486/33809530-4d5032a2-ddad-11e7-9afe-dd81b5743811.png)

Note the background. Is that intentional, or the garbled contents of the previous blank screen we missed out on?
![shsw_003](https://user-images.githubusercontent.com/6245486/33809543-712bef0e-ddad-11e7-835a-f1592414b852.png)

Memory over.
![shsw_004](https://user-images.githubusercontent.com/6245486/33809541-6b8788ba-ddad-11e7-9249-e187a2b4e109.png)

**Comment by joncampbell123** [comment]
I just ran the copy I have on real hardware, and apparently (at least under Windows 95 DOS mode) it has the same problems as it does in DOSBox-X.

I'm guessing that the copy of Briganty I test with is corrupted somehow, or missing files.

Using SETVER.EXE to force MS-DOS version 3.30 doesn't help, in fact it prevents the game from running.

**Comment by joncampbell123** [comment]
The copy I have seems corrupted or missing files, so this issue isn't worth keeping open over a bad copy.

**Comment by joncampbell123** [comment]
Hey, Briganty runs if ems=false!

It crashes with ems=true.

**Comment by joncampbell123** [comment]
![shsw_000](https://user-images.githubusercontent.com/6245486/37504429-7bd390cc-289b-11e8-8982-91e7cdcf9619.png)

**Comment by joncampbell123** [comment]
Briganty appears to make calls to EMS (INT 67h), if it's there.

However, at game start, it crashes executing opcode FFFFh, triple faults, reboots the system.

**Comment by joncampbell123** [comment]
Running with xms=false and ems=false shows the game using the HMA directly (at FFFF:0).

**Comment by joncampbell123** [comment]
Even if the A20 gate is turned off when you start the game, the game turns A20 on right away.

**Comment by joncampbell123** [comment]
The game knows better than to play with the HMA though if XMS is enabled.

**Comment by joncampbell123** [comment]
Game crashes when it zeroes out memory at 0000:0000, wiping out the interrupt vector table, for some reason. But only when ems=true

**Comment by joncampbell123** [comment]
Also noteworthy is that the game likes to save/restore the EMS page frame a lot.

**Comment by joncampbell123** [comment]
The crash comes from Briganty copying data, but then at one point, using segment 0000 as a destination, blowing away the interrupt table and then crashing.

**Comment by yksoft1** [comment]
I wonder why there are so many games on PC-98 that come with their own XMS/HMA/EMS drivers and access hardware directly where they always available as DOS drivers... Is that because of PC-98 hardware is much more unified than IBM PCs?

**Comment by joncampbell123** [comment]
My impression of PC-98 is that it's as standard in it's design as IBM PC, at least where standard functions and interfaces are. It may have been developer attitudes on whether the BIOS or DOS functions were too slow, useless, or whether they thought they could do it better by themselves. Many early IBM games and demoscene executables have the same problem, which is why they don't work on newer or older IBM PC hardware. Some of these hardware dependencies persist today such that modern BIOSes still emulate the 8042 keyboard interface.

**Comment by joncampbell123** [comment]
I forgot to mention the problem with vertically squeezed gameplay was fixed in my most recent commits regarding GDC cursor spec line height and graphics GDC scanline doubling.

**Comment by yksoft1** [comment]
Intel Macs' BIOS compatibility module don't emulate i8042 at all, only BIOS interrupts of keyboard devices.

**Comment by joncampbell123** [comment]
Most modern BIOSes. Not all. 8042 emulation may disappear when BIOSes eventually drop the legacy MBR boot.

Motherboard USB chipsets since 1998 have provided an interrupt where accessing the 8042 I/O ports triggers an SMI interrupt, and the BIOS can use that to emulate the 8042 using the USB keyboard.

**Comment by sikthehedgehog** [comment]
The idea is to drop the BIOS altogether and leave only UEFI (no idea if SMM may go away with it, seeing as its main purpose is to do emulation, but also apparently handles some other stuff like power management?). That will also likely mean no more real mode. Also since we talk about legacy emulation: VGA support. For what matters, IBM's idea was for software to never access hardware directly (not even video)... that didn't work because performance wasn't up to it yet.

Anyways, regarding PC-98, it seems its compatibility is mostly just enough for DOS to run (which itself didn't rely much on the hardware aside from the CPU being real mode x86). NEC never intended it to be compatible otherwise.

**Comment by joncampbell123** [comment]
I would be 100% okay with dropping the traditional BIOS on modern systems, to be honest.

**Comment by joncampbell123** [comment]
Back on topic, Briganty runs fine, IF:

- You set the FM music board IRQ to 12
- You run DOSBox-X with expanded memory disabled (ems=false)

Recent fixes resolved the squeezed screen.

Fixed.
