### ISSUE TITLE
Using IBM VGA BIOS

### ISSUE THREAD

**Issue by bugrepo** [joncampbell123/dosbox-x#3437]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 7 SP1

### What version(s) of DOSBox-X have this bug?

0.83.21-0.83.24

### Describe the bug

Hangs on white character:

![This is an image](https://www.upload.ee/image/14095590/ibmvga.png)

If launch with `-fastlaunch`, then OK:

![This is an image](https://www.upload.ee/image/14095561/ibmvga2.png)

### Expected behavior

No hanging :-)

### Steps to reproduce the behaviour

1. [Download IBM VGA BIOS](https://www.upload.ee/files/14095558/ibm-vga.zip.html).
2. `machine = vgaonly`
3. `vga bios use rom image = true`
4. `vga bios rom image = ibm-vga.bin`

### Used configuration

```
[dosbox]
machine = vgaonly

[video]
vga bios use rom image = true
vga bios rom image = ibm-vga.bin
```

**Comment by joncampbell123** [comment]
Something is causing the BIOS screen to call INT 10h AH=1Bh (Get VGA state with ES:DI pointed at the ROM BIOS), and then it crashes...?

I don't recall anything at the boot screen using AH=1Bh.

**Comment by joncampbell123** [comment]
:) I see how INT 10h can be called one extra time during that BIOS screen.

The IBM VGA BIOS changes the contents of AX on return, so the extra call becomes whatever values comes back in AH.

Sooner or later that value is AH=1Bh and it crashes.

**Comment by joncampbell123** [comment]
Apparently the VGA BIOS will cause a crash if you call INT 10h AH=FAh, which Microsoft CodeView does for some reason at startup. The reason appears to be that IBM's VGA BIOS does an "INT 42h" if the value of AH is larger than the largest function call number it supports. INT 42h points at nothing in the ROM BIOS, so it crashes.

**Comment by joncampbell123** [comment]
The VGA BIOS routine in question (INT 10h handler):

    C000:000006EF 8AC4                mov  al,ah
    C000:000006F1 98                  cbw
    C000:000006F2 D1E0                shl  ax,1
    C000:000006F4 8BF0                mov  si,ax
    C000:000006F6 58                  pop  ax
    C000:000006F7 83FE3A              cmp  si,003A
    C000:000006FA 730A                jnc  00000706 ($+a)         (no jmp)
    C000:000006FC 2E8E1E1C07          mov  ds,cs:[071C]           cs:[071C]=0000
    C000:00000701 2EFFA4A706          jmp  near word cs:[si+06A7] [illegal]
    C000:00000706 5F                  pop  di
    C000:00000707 5E                  pop  si
    C000:00000708 5B                  pop  bx
    C000:00000709 59                  pop  cx
    C000:0000070A 5A                  pop  dx
    C000:0000070B 1F                  pop  ds
    C000:0000070C 07                  pop  es
    C000:0000070D 5D                  pop  bp
    C000:0000070E CD42                int  42   <--
    C000:00000710 CF                  iret

**Comment by joncampbell123** [comment]
The reason for that is that INT 42h is supposed to be the original INT 10h handler that the EGA/VGA BIOS replaced. So to avoid crashes, DOSBox-X is going to have to provide a dummy INT 10h stub at BIOS POST for the VGA BIOS to replace when initialized.

http://www.ctyme.com/intr/rb-6158.htm

**Comment by cimarronm** [comment]
I believe one issue is that the VGA bios replaces int 42 handler with a fixed address (presumably matching existing IBM bios location for int 10). 

```
C000:00000048 FA                  cli
C000:00000049 C7064000E106        mov  word [0040],06E1       ds:[0040]=CA60
C000:0000004F 8C0E4200            mov  [0042],cs              ds:[0042]=F000
C000:00000053 C706B401E406        mov  word [01B4],06E4       ds:[01B4]=CA60
C000:00000059 8C0EB601            mov  [01B6],cs              ds:[01B6]=F000
C000:0000005D C706080165F0        mov  word [0108],F065       ds:[0108]=CA60.      <---- (int 42) points to dead code now
C000:00000063 C7060A0100F0        mov  word [010A],F000       ds:[010A]=F000.      
C000:00000069 C706A804C605        mov  word [04A8],05C6       ds:[04A8]=0000
C000:0000006F 8C0EAA04            mov  [04AA],cs              ds:[04AA]=0000
C000:00000073 C7067C008D3B        mov  word [007C],3B8D       ds:[007C]=CA60
C000:00000079 8C0E7E00            mov  [007E],cs              ds:[007E]=F000
```

If I nop out instructions at 0x5d and 0x63 so that int 42 still points to the existing int 10, it does not crash

**Comment by joncampbell123** [comment]
@cimarronm That would explain why at the time of crashing, INT 42h points at some specific address in segment F000.

**Comment by joncampbell123** [comment]
@cimarronm Please try the latest commit to master and confirm the VGA BIOS runs without crashing.

**Comment by cimarronm** [comment]
@joncampbell123 Looks good

**Comment by bugrepo** [comment]
Found another bug: video modes `7` and `7+` don't work.
In Bochs with IBM VGA BIOS this modes work fine.
Mode 7 stands for `80x25 9x14 720x350 Mono`
Mode 7+ stands for `80x25 9x16 720x400 Mono`
Tested with [VGATEST](https://github.com/barotto/VGATEST).

**Comment by bugrepo** [comment]
Video mode `0Fh` (Graphics, 640x350, Monochrome) doesn't work either.

Bochs is OK.

**Comment by bugrepo** [comment]
@joncampbell123 Great job! No more hanging :) Tested on latest version 0.83.25.

I wish I could figure things out that way, with all those debuggers and disassemblers...
