### ISSUE TITLE
Environment variables are passed into DosBox-X

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3438]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows W21H2

### What version(s) of DOSBox-X have this bug?

DosBox-X v0.83.24

### Describe the bug

dear sir,
C:\DOSBox-X\dosbox-x.exe -c "set USERNAME=%USERNAME%" -c "set COMPUTERNAME=%COMPUTERNAME%" 
Environment variables are passed into DosBox-X.
However, in Autoexec.bat, the batch file is directly executed, and these variables cannot be captured.
After the batch file is finished, it can be captured in Command mode.

### Steps to reproduce the behaviour

1. C:\DOSBox-X\dosbox-x.exe -c "set USERNAME=%USERNAME%" -c "set COMPUTERNAME=%COMPUTERNAME%" 
2. in autoexec.bat
    do aa.bat
3. aa.bat 
echo %COMPUTERNAME%   ... is empty

do_myAPP
4. D:\>set ...... Can found 
     COMPUTERNAME=WINSRV

**Comment by Arthur3032** [comment]
中文描述:
欲將Windows 系統環境變數傳遞至DosBox-X中, 
在autoexec.bat中, 執行某個批次檔(aa.bat), 則在 (aa.bat中看不到傳入之環境變數)
要等到結束aa.bat, 回到 DosBox-X指令模式, 才可以看到這些變數。
希望在Autoexec.bat時, 就能看得到.

**Comment by Wengier** [comment]
@Arthur3032 Try set this in dosbox-x.conf:

[config]
...
set USERNAME=%USERNAME%
set COMPUTERNAME=%COMPUTERNAME%

Instead of ``-c "set USERNAME=%USERNAME%" -c "set COMPUTERNAME=%COMPUTERNAME%"``. Hope this helps.

**Comment by Arthur3032** [comment]
I have used it, thank you very much!
