### ISSUE TITLE
Add product version and file version to Windows builds?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#3444]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

With the Windows builds of DOSBox-X, if you choose Properties->Details from the right-click menu, nothing appears in the Program Version or File Version fields. Inno Setup installers (and probably others) can use the version numbers to decide whether to overwrite an existing file. Is there any way to add those numbers to the build? I've spent some time searching for an answer, but can't find one.

**Comment by Wengier** [comment]
It is hopefully fixed in #3443 (before the upcoming release).

**Comment by emendelson** [comment]
Thank you, @Wengier. It is fixed now. One small point (and I may be wrong about this): I was unable to open winres.rc in Visual Studio 2022 until I changed one of the include lines to read:

`#include "../config.h"`

I don't know if this is correct, but it does let me open the file.
