### ISSUE TITLE
DosBox-X, zoom in to the maximum

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3445]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

dear sir,
How to set the window size in DosBox-X, zoom in to the maximum, such as full screen, but also to be able to see the windows task bar.

DosBox-x V0.83.24 Chinese mode

**Comment by Arthur3032** [comment]
There is no windows work column, it is inconvenient to input Chinese (because I don't know whether it is in English or Chinese input state)

**Comment by Wengier** [comment]
If you want to have maximized window while still being able to see the Windows taskbar, then you need to use maximized window mode. The TTF output does not strictly give you this, although you can increase the window coverage with via ``winperc`` config option or via keyboard shortcuts. If you strictly want maximized window mode instead, then you need to set to an output such as Direct3D. Try start DOSBox-X with the following:

``dosbox-x -set output=direct3d -set maximize=true``

And try use the following builds (which fix an issue with IME input position):

32-bit Windows builds: https://github.com/joncampbell123/dosbox-x/suites/6328739696/artifacts/227596823
64-bit Windows builds: https://github.com/joncampbell123/dosbox-x/suites/6328739701/artifacts/227597421

You can find out the current system IME status from the Windows taskbar which is visible in maximized window mode.

Hope this helps.

**Comment by Arthur3032** [comment]
Yes, as mentioned above.
Is it possible to change the font?
1. The original TTC is more beautiful.
2. The current wireframe is not aligned.
![擷取](https://user-images.githubusercontent.com/93595854/166127054-5e678532-9ad7-4332-9a84-3c22570b15d5.JPG)
![擷取2](https://user-images.githubusercontent.com/93595854/166127101-dd41a705-93a6-4c31-a247-2152376eb4e1.JPG)

**Comment by Wengier** [comment]
Sure, TTF fonts generally look nicer. Non-TTF outputs use bitmap fonts, which can be controlled via font-related options in [dosv] section, since DOS/V fonts will be used in such case. For example, set ``fontxdbcs=stdfont.15`` to use stdfont.15 font from ETen.

The non-alignment issue is a minor known issue I think.

Hope this helps.

**Comment by Arthur3032** [comment]
These instructions did exactly what I needed, thank you very much for your help. DOSBOX-X is great.
Thank you very much.
