### ISSUE TITLE
PC-98: Yu-No instantly quits in internal DOS

### ISSUE THREAD

**Issue by Pawlicker** [joncampbell123/dosbox-x#3452]
Yu-No for the PC-98 in PC-98 mode (with the translation [here](https://archive.org/download/nec-pc-9801-translations)) refuses to launch, and if the game is attempted to be launched again the virtual machine locks up. This happens on Linux and Windows X64. The Slave PIC message comes up if you attempt to launch the game again. The HDI file also will not boot in Dosbox-X. 

Dosbox-X version: DOSBox-X version 0.83.25 (Linux SDL2)

![yuno nothing](https://user-images.githubusercontent.com/92184373/166404138-f9d68ff8-c89e-42db-92f7-b36ca1227edc.png)
![failed to boot](https://user-images.githubusercontent.com/92184373/166404398-46f65f32-90da-4176-b5b9-5690151d8ef3.png)

Log with EMM386 and A20 checked, and both attempts to load it:
LOG: Image file has .HDI extension, assuming HDI image and will take on parameters in header.
LOG: HDI header: sectorsize is 256 bytes/sector, header is 4096 bytes, hdd size (plus header) is 41564160 bytes
LOG: HDI: Geometry is C/H/S 615/8/33
LOG: FAT: Partition type is IPL1 (PC-98)
LOG: Using IPL1 entry 0 name 'MS-DOS 6.20     ' which starts at sector 264
LOG: Disk indicates 256 bytes/sector, FAT filesystem indicates 1024 bytes/sector. Ratio=4:1 shift=2
LOG: Using logical sector size 1024, offset by 0 physical sectors
LOG: Mounted FAT volume is FAT16 with 19712 clusters
LOG: Pentium CMPXCHG8B emulation is enabled
LOG: EMS page frame at 0xd000-0xdfff
LOG: INT 18H AH=0Ah warning: K-CG dot access mode not supported
LOG: PC-98 INT 18 AH=42h CH=0xC0
LOG: Slave PIC: still to handle irr=30 imrr=33 isrr=ef

When choosing EMS emulation as checked along with A20:
LOG: INT 18H AH=0Ah warning: K-CG dot access mode not supported
LOG: PC-98 INT 18 AH=42h CH=0xC0
LOG: 1868384031 ERROR CPU:Write a04 to rom at ef002
LOG: 1868384032 ERROR CPU:Write 96 to rom at ef004
LOG: 1868384034 ERROR CPU:Write 5a3b to rom at ef006
LOG: 1868384035 ERROR CPU:Write 96 to rom at ef008
LOG: 1868384037 ERROR CPU:Write 69db to rom at ef00a
LOG: 1868384038 ERROR CPU:Write 96 to rom at ef00c
LOG: 1868384040 ERROR CPU:Write 797b to rom at ef00e
LOG: 1868384043 ERROR CPU:Write f28 to rom at ef010
LOG: 1868384045 ERROR CPU:Write 4a9b to rom at ef012
LOG: 1868384046 ERROR CPU:Write f28 to rom at ef014
LOG: 1868384048 ERROR CPU:Write 5a3b to rom at ef016
LOG: 1868384049 ERROR CPU:Write f28 to rom at ef018
LOG: 1868384051 ERROR CPU:Write 69db to rom at ef01a
LOG: 1868384052 ERROR CPU:Write f28 to rom at ef01c
LOG: 1868384054 ERROR CPU:Write 797b to rom at ef01e
LOG: 1868384057 ERROR CPU:Write f30 to rom at ef020
LOG: 1868384059 ERROR CPU:Write 4a9b to rom at ef022
LOG: 1868384060 ERROR CPU:Write f30 to rom at ef024
LOG: 1868384062 ERROR CPU:Write 5a3b to rom at ef026
LOG: 1868384063 ERROR CPU:Write f30 to rom at ef028
LOG: 1868384065 ERROR CPU:Write 69db to rom at ef02a
LOG: 1868384066 ERROR CPU:Write f30 to rom at ef02c
LOG: 1868384068 ERROR CPU:Write 797b to rom at ef02e
LOG: 1868384071 ERROR CPU:Write f38 to rom at ef030
LOG: 1868384073 ERROR CPU:Write 4a9b to rom at ef032
LOG: 1868384074 ERROR CPU:Write f38 to rom at ef034
LOG: 1868384076 ERROR CPU:Write 5a3b to rom at ef036
LOG: 1868384077 ERROR CPU:Write f38 to rom at ef038
LOG: 1868384079 ERROR CPU:Write 69db to rom at ef03a
LOG: 1868384080 ERROR CPU:Write f38 to rom at ef03c
LOG: 1868384082 ERROR CPU:Write 797b to rom at ef03e
LOG: 1868384085 ERROR CPU:Write f40 to rom at ef040
LOG: 1868384087 ERROR CPU:Write 4a9b to rom at ef042
LOG: 1868384088 ERROR CPU:Write f40 to rom at ef044
LOG: 1868384090 ERROR CPU:Write 5a3b to rom at ef046
LOG: 1868384091 ERROR CPU:Write f40 to rom at ef048
LOG: 1868384093 ERROR CPU:Write 69db to rom at ef04a
LOG: 1868384094 ERROR CPU:Write f40 to rom at ef04c
LOG: 1868384096 ERROR CPU:Write 797b to rom at ef04e

**Comment by maron2000** [comment]
Didn't play it but I confirmed it boots on Windows 0.83.25 x64 VS build (SDL1/SDL2).
![yu-no](https://user-images.githubusercontent.com/68574602/166410621-e34b007a-e971-4c97-80f6-f039315f8c8b.png)

**Comment by grapeli** [comment]
Try it like this.
`dosbox-x -set machine=pc98 -c "imgmount 2 ./yu-no.hdi -t hdd -fs none" -c "boot c:"`

this is what it looks like under dosbox-x 0.83.25 sdl2 linux

https://user-images.githubusercontent.com/452325/166423999-2002b3e0-24c4-49b6-9ca3-3f8ecdec5355.mp4

**Comment by Pawlicker** [comment]
> Try it like this. `dosbox-x -set machine=pc98 -c "imgmount 2 ./yu-no.hdi -t hdd -fs none" -c "boot c:"`
> 
> this is what it looks like under dosbox-x 0.83.25 sdl2 linux
> dosbox-x.yu-no.mp4

Thank you so much, this works. I'm keeping the issue open however and just changed the title to make it more accurate: it simply doesn't boot in the internal DOSBox DOS environment.

**Comment by maron2000** [comment]
For reference, the error messages of PLAY6 shown in the screenshot is as follows.
The first one (play6 r : this should come later, because this command releases the TSR)
`Sound interrupt is already in use by another program.`
The latter one (play6 s -#20)
`PLAY6 is already on memory.`

**Comment by joncampbell123** [comment]
The game does run under the internal DOS kernel IF you do not first run the PLAY6 and AMD commands.
It's silent of course, but it works.

**Comment by joncampbell123** [comment]
Hm.... PLAY6.EXE terminates using INT 21h AH=31h terminate and stay resident.

In the debugger, DOS MCBS shows that there is a PLAY6 memory block, but then after INT 21h AH=31h, the block disappears from the MCB list.

So the instability may be simply that DOSBox-X is failing the "stay resident" part of "terminate and stay resident"

**Comment by joncampbell123** [comment]
Wait a minute... before terminating to stay resident, PLAY6.EXE calls INT 21h to free it's own code segment. What?

**Comment by joncampbell123** [comment]
I just set up a breakpoint on INT 21h AH=31h to trigger after booting the HDI image.

Yes, indeed. If you free your own PSP segment then terminate with INT 21h AH=31, DOS will magically turn it back into an allocated block.

Let's see which versions of DOS do that.

So far we now know PC-98 versions of MS-DOS do this.
Do IBM PC versions of DOS do this too?

**Comment by joncampbell123** [comment]
Try the latest commit. It appears to fix the issue.

Naturally if a TSR sets up interrupts and then effectively removes itself from memory so that other things load over it, things get crashy.

**Comment by maron2000** [comment]
I confirm PLAY6.EXE works and Yu-No can start without booting NEC MS-DOS.
I also confirm that FMP disk 8 mentioned in #3456 also works without booting MS-DOS with this commit.

**Comment by joncampbell123** [comment]
Sounds good. Reopen this issue if somehow it regresses.
