### ISSUE TITLE
EGA monitor emulation issues

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#3460]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Fedora 36

### What version(s) of DOSBox-X have this bug?

0.83.25

### Describe the bug

An EGA adapter could be paired with any of the following monitor types:
- Monochrome monitor
- CGA monitor
- EGA monitor

Right now, DOSBox-X only handles the EGA monitor type. However, some software expects a CGA monitor such as Fantasy Land, which was an early EGA demo from IBM.

When run in DOSBox-X with `machine=ega` it results in the following (flickering between the two):
![fland_000](https://user-images.githubusercontent.com/17701098/166740768-bb058cb9-a38e-4121-8848-145f42df7451.png)
![fland_001](https://user-images.githubusercontent.com/17701098/166740769-4c16f0b8-87dc-4040-89c3-153d6f4d46c9.png)

The explanation of what is going on can be found here:
https://www.os2museum.com/wp/fantasyland-on-vga/

This may also be of use:
https://www.os2museum.com/wp/reconstructing-the-ega-bios/

You can see what fantasy land should look like here:
https://www.pcjs.org/software/pcx86/demo/ibm/ega/

### Steps to reproduce the behaviour

See above

**Comment by joncampbell123** [comment]
Interesting, however adding 200-line EGA would count as a new feature, so it will have to wait until after release.

**Comment by RNMB15** [comment]
The 86Box already has a setting for the EGA monitor type.

![Zwischenablage01](https://user-images.githubusercontent.com/56356083/171506290-e2983209-9e5f-4d85-9edf-475b2b521b35.png)

**Comment by joncampbell123** [comment]
Please try the latest commit, if you can compile from source. I added a machine type to emulate EGA with 200-line CGA compatible modes and fixed panning issues with the game.

Use machine=ega200.
