### ISSUE TITLE
Output TTF mode switching breaks when running ELKS

### ISSUE THREAD

**Issue by Jookia** [joncampbell123/dosbox-x#3463]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Ubuntu 22.04 amd64

### What version(s) of DOSBox-X have this bug?

latest master SDL, SDL2, flatpak

### Describe the bug

Triggering a TTF output switch to OpenGL by trying to open a GUI or take a screenshot causes the virtual machine to lock up and the TTF mode to become unavailable.

### Expected behavior

The machine should switch back to TTF mode like it does in DOS mode.

### Steps to reproduce the behaviour

1. Boot an ELKS image
2. Try to open a menu while in TTF mode

### Used configuration

```ini
Default configuration with TTF enabled.
```

**Comment by Jookia** [comment]
(I understand this bug report is sub-par but I intend to dig more in to it myself)

**Comment by Jookia** [comment]
It seems to happen when I switch from non-TTF output to TTF in ELKS.

**Comment by Jookia** [comment]
Log for when switching to TTF in ELKS:

```
SDL: TTF activated DejaVuSansMono.ttf
Loaded system codepage: 437
DOS MCB dump:
FINAL: Type=0x7c(|) Seg=0x021d size=0xfae5 name='F5­1^^AKP'
End dump
E_Exit: Corrupt MCB chain
```

Log for switching from booted TTF in ELKS:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x2e0000d
  Serial number of failed request:  69
  Current serial number in output stream:  70
```

Booting FreeDOS in the VM and switching doesn't create this issue.

**Comment by grapeli** [comment]
If you start with the `ttf` video output then you can switch to other outputs or go back to `ttf` without any problems.

I tested the ELKS on this image.
https://github.com/jbruchon/elks/releases/download/v0.5.0/fd1440.img
`dosbox-x -fastlaunch -set "dosbox quit warning=false" -set "dos floppy drive data rate limit=0" -set output=ttf -c "imgmount 0 ./fd1440.img -t floppy -fs none" -c "boot a:"`

**Comment by Jookia** [comment]
Interesting. Using those commands I can reproduce that switching TTF doesn't break anything- however opening the configuration GUI breaks thing. It gives a lot of "LOG:    1552189 ERROR CPU:Illegal Unhandled Interrupt Called 0". Same with taking a screenshot.

**Comment by Wengier** [comment]
Does the issue only happen with ELKS? I do not think it is DOS, and text-mode is not supported in Linux as needed by TTF output. When TTF output is active in other cases, I think the Configuration Tool works fine in both my Surface Pro running Windows 10 and Pinebook Pro running Linux (aarch64).

**Comment by Jookia** [comment]
It seems to only happen with ELKS.

**Comment by Jookia** [comment]
Doing some more debugging, I think there might be multiple bugs here:

- Opening configuration from TTF when ELKS running crashes the guest and requires a VM reboot

- Settting output from surface to TTF causes DOSBox-X to detect a corrupted MCB and reboot the guest, but leaves the surface output broken
- This happens with the debugger running with the OS paused
This broken state somehow has the system running, with any debugger broken. From here on you can set the output 
- Setting output to OpenGL/TTF or triggering a switch to surface using GUI shows the rebooted guest OS correctly
- From then on I can successfully switch to TTF from ELKS and back or any surface without any corruption
- Opening configuration will still crash the guest

- Sometimes DOSBox-X will crash with a BadWindow

**Comment by Jookia** [comment]
Looks like there were two bugs. Merging those should close this issue.

**Comment by grapeli** [comment]
@Jookia thanks a lot for these patches.

**Comment by Jookia** [comment]
No problem. I think this is fixed, closing!

**Comment by grapeli** [comment]
@Wengier 
Unfortunately this commit a0c26c4 broke loading Linux in text mode if the video output is not ttf.
I only inform. Running Linux is not the essence of dosbox-x.

[linux.zip](https://github.com/joncampbell123/dosbox-x/files/8645029/linux.zip)

I run like this.
`dosbox-x -set cputype=pentium -set core=dynamic_x86 -c "mount c ./lin" -c "c:" -c "linux.bat"`
You can change the text mode to another in the `linux.par` file, change `video=normal` to `video=ask` or `video=777`, `video=3843`, etc.

**Comment by Jookia** [comment]
Yikes. Could you open a bug for that? Did you bisect to find that commit or is it an estimated guess?

**Comment by grapeli** [comment]
Based on git bisect.
I have repeatedly run Linux under dosbox-x in text mode. I know it worked.
The last good commit was c77f4a1.

This application form discourages me from making entries. **It is significantly overcomplicated.**

For me, it is not crucial or super important.
This bug is closely related to this report.

**Comment by Jookia** [comment]
What about commit 67a9e8a0ffb587547ea4f3358d3f4eba90ad1ab6 ?

**Comment by grapeli** [comment]
> What about commit [67a9e8a](https://github.com/joncampbell123/dosbox-x/commit/67a9e8a0ffb587547ea4f3358d3f4eba90ad1ab6) ?

Is good.

**Comment by Jookia** [comment]
So is that the last good commit or is c77f4a1 the last good commit?

**Comment by grapeli** [comment]
It is he who is the last good.
I was wrong.

**Comment by Jookia** [comment]
Ah okay then. Does disabling double byte character support fix Linux booting?

**Comment by grapeli** [comment]
`char9=false` doesn't change anything here.

**Comment by Jookia** [comment]
Right now I don't have the time to look at this. I'll try to remember this issue and get back to it later, but it's very hard to find given it's in an unrelated and closed bug.

**Comment by Wengier** [comment]
I definitely hope to address it considering I made the commit, but I do not have time to do it today either. Thanks both @grapeli for reporting the bug and @Jookia for trying to solve it.

**Comment by Wengier** [comment]
Meanwhile, it has been mentioned that the issue report form may be overcomplicated. Perhaps it can be simplified somewhat.

**Comment by Wengier** [comment]
The issue as reported by @grapeli is hopefully already fixed in commit https://github.com/joncampbell123/dosbox-x/commit/5172a1f07528e5e01df5261b3bdef4bf0f69ff6c.

**Comment by grapeli** [comment]
@Wengier Thanks.
Now booting linux (via LOADLIN) in text mode works fine for non-ttf video outputs.

Switching to `tff` output didn't work, but it didn't work before. Interestingly, when booting in `ttf` mode, such switching to a different video output mode is possible, though **only once**.

**Comment by Jookia** [comment]
Please open a bug for the second issue @grapeli . The bug report form has been tweaked a bit. If it's not good enough yet please explain why here.

**Comment by Wengier** [comment]
@grapeli I could reproduce the issue with TTF output switch issue in LOADLIN. Considering that the issue was already reported here I decided to go ahead to fix it in commit https://github.com/joncampbell123/dosbox-x/commit/ef06b8bcaa427d5d450fde9bf956b70daab7c83b, which you can have a test. Meanwhile, as @Jookia said above, it is recommended to open new bug report for such issues considering that the bug report form has been updated by @Dobby233Liu in https://github.com/joncampbell123/dosbox-x/pull/3473. People can continue to give feedback to the bug report form to improve it further of course.

**Comment by grapeli** [comment]
With loadlin, switching between different video outputs works fine. Thanks alot.
If you boot Linux from a floppy disk image, iso cdrom, or from hdd, switching will not work. This is the biggest drawback of this solution.

As for reporting bugs. Dosbox-x in my scope is to be used to run DOS programs. Secondly, also win 3.x. I treat the ability to run win 95, 98 as alpha status. One should not expect too much in this case.
Running other systems is just a curiosity. Something may work or not at all. A moot point. Because you could create 50 of them every day. As a last resort, they will be ignored.
