### ISSUE TITLE
Cyberia / Cyberia 2 games freezes after save state reloading during CD-ROM video scenes

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#3492]
### Describe the bug

Save states works correctly when the protagonist walks through corridors and rooms.
But reloading save states taken during a rail-shooting scene, freezes the game almost immediately (but by pressing the ESC key very quickly you can display the menu and reload the scene or exit).
Rail-shooting scenes are videos read from the CD-ROM, which in fact must always be mounted even after the game has been installed on the hard disk: it seems that something related to the state of the emulated CD-ROM drive is lost after a save state reload.
Could this bug be related to the solved issue #1582?
The save states works correctly in the unofficial DOSBox SVN version linked in the issue mentioned above.
I enclose the installed game folder patched to latest version 1.87 and a saved state, let me know if you also need the ISO.
[Cyberia_installed.zip](https://github.com/joncampbell123/dosbox-x/files/8688726/Cyberia_installed.zip)
[Save_state.zip](https://github.com/joncampbell123/dosbox-x/files/8688742/Save_state.zip)

### Steps to reproduce the behaviour

1. Launch the game CYBERIA.BAT (password "MARCO")
2. Skip the introduction with ESC key
3. In the load menu scroll all the way down and select the last scene
4. With the cursor keys move the man in the room e try to save and reload save states (working)
5. Go to the computer terminal to the right near the door and launch the drone selecting the second icon on the desktop with the space bar (or load my saved state)
6. When the drone is flying in the corridor try to save and reload another save state (freeze)

**UPDATE:** I recently tested the sequel as well, Cyberia 2 Resurrection, and the save state behaviour is similar: works in the unofficial DOSBox SVN, gets stuck in an endless loop in DOSBox-X.
Out of curiosity I opened the save state files with WinRAR and I noticed that in the one generated by DOSBox SVN there is a section called "Cdrom" which is missing in the DOSBox-X save state file. The "Cdrom" section contains some binary data if there is a CD-ROM mounted, it is empty otherwise.

### Expected behavior

The scene should continue from the last save state

### What operating system(s) this bug have occurred on?

Windows 10 Pro version 21H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 0.83.25 SDL1 & SDL2 64 bit

### Additional information

[dosbox-x.conf.zip](https://github.com/joncampbell123/dosbox-x/files/8688713/dosbox-x.conf.zip)
[dosbox-x.log.zip](https://github.com/joncampbell123/dosbox-x/files/8688720/dosbox-x.log.zip)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by aaaaaaaCatOnMyKeyboard** [comment]
this game is unknown to me and i'm not a developer, but as long no one else respond..
you mounted an iso so it's not a mixed/mode image, it should be possible to copy the content from the CD to your Harddisk and mount this directory as CD with something like "MOUNT D D:\DOSBox-X\HD\CYBERIA\CDDATA -t cdrom" and see if this makes a difference in comparison to IMGMOUNT.

**Comment by rderooy** [comment]
ISO images have better compatibility, it seems unlikely that copying the contents to a directory would improve matters.

**Comment by rderooy** [comment]
Basically save states are still a work in progress and they may or may-not work. @Wengier has been working on them in the past.

**Comment by MX9000** [comment]
Thanks for the suggestion @aaaaaaaCatOnMyKeyboard! I repeated the test but the save state still freezes. I have also tried increasing the RAM beyond 16 MB but the issue persists. Thanks to all anyway!

**Comment by MX9000** [comment]
I have tested again the Cyberia and Cyberia 2 games in the latest version 2022.09.0 and noticed that the status saves actually work in some builds:

Cyberia

- VSbuild 64-bit SDL1	FREEZE
- VSbuild 64-bit SDL2	FREEZE
- VSbuild 32-bit SDL1	OK
- VSbuild 32-bit SDL2	OK
- MinGW 64-bit SDL1	FREEZE
- MinGW 64-bit SDL2	FREEZE
- MinGW 32-bit SDL1	OK
- MinGW 32-bit SDL2	OK

Cyberia 2

- VSbuild 64-bit SDL1	FREEZE
- VSbuild 64-bit SDL2	FREEZE
- VSbuild 32-bit SDL1	FREEZE
- VSbuild 32-bit SDL2	FREEZE
- MinGW 64-bit SDL1	OK
- MinGW 64-bit SDL2	OK
- MinGW 32-bit SDL1	OK
- MinGW 32-bit SDL2	FREEZE
