### ISSUE TITLE
CHOICE command parameter order issue

### ISSUE THREAD

**Issue by Banjo-Oz** [joncampbell123/dosbox-x#3494]
### Describe the bug

Using
CHOICE /N /C:123
causes the instance to lock up (cannot press a key to make a choice or continue).

It seems that the allowed keys parameter is being ignored ("/C:123" is shown onscreen and none of those keys respond to continue).

Using
CHOICE /C:123 /N
works as expected.

This indicates that parameter processing order is likely the cause of the bug.

### Steps to reproduce the behaviour

Type "CHOICE /N /C:123" in DOSBox-X

### Expected behavior

Either combination of parameter should work.

I tried CHOICE /C:123 /N on the latest versions of DOSBox Staging, DOSBox ECE and DOSBox vanilla and it works fine on all those versions. Thus, this seems to be a DOSBox-X only issue.

### What operating system(s) this bug have occurred on?

Windows 7 x64

### What version(s) of DOSBox-X have this bug?

0.83.25

### Additional information

Copying CHOICE.COM from DOSBox Staging (which works correctly) and running it in DOSBox-X causes the whole program to crash.

Copying CHOICE.EXE from FreeDOS (https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/choice.html) works correctly in DOSBox-X (with /n either before or after the /c parameter) and doesn't cause a crash.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Wengier** [comment]
@Banjo-Oz CHOICE is a builtin command in both DOSBox-X and DOSBox Staging as actually implemented in the source code, instead of a regular program. So you cannot really copy the program in either of them and use elsewhere. But you can surely replace it with the DOS binaries from FreeDOS (or MS-DOS etc) if you want. In any case, the builtin CHOICE commands was updated in the last release (0.83.25) with support for /T option (similar to DOSBox Staging but with somewhat different implementation), but the update may have introduced the said bug. I assume that the previous releases (0.83.24 and earlier) did not have this bug.

**Comment by Banjo-Oz** [comment]
@Wengier Yeah, that was my thinking on why copying the COM from Staging didn't work but FreeDOS's CHOICE.EXE does work (i.e. it's standalone). I incidentally put that in my DRIVEZ folder in the subfolder DOS and renamed it from EXE to COM and it now replaces the DOSBox-X version internally in every use (awesome implementation of how that works, by the way!). This is of course a temporary measure until the bug is fixed and I can go back to the default builtin CHOICE (though the added "beep" parameter of the FREEDOS version is rather cool).

I will test a previous build of DOSBox-X for this for you (I think I have an older copy installed somewhere else still) to confirm, but I suspect you're right that the bug is recent as I use CHOICE a lot and expect I would have noticed this before now otherwise.

**Comment by Wengier** [comment]
It turns out that it was not really a lockup, but simply that the ``/c:123`` part got ignored in this case. Pressing Y or N did work, which are the default choices. I hopefully fixed the bug in PR #3515.
