### ISSUE TITLE
Xbox 360 Controller RT not working out-of-box, joystick = auto

### ISSUE THREAD

**Issue by instinctualjealousy** [joncampbell123/dosbox-x#3497]
### Describe the bug

DOSBox-X is correctly using 4axis mode for the controller. However, the triggers aren't matching to the axes correctly.
(I imagine it is supposed to be something like LT is X+ and RT is X-?)

I noticed the issue when starting up Screamer and my analog gas and brake weren't working correctly on known working config. I'm mainly showing mapper for clean visual of what's going on.

LT is as such
No press:
![nopress](https://user-images.githubusercontent.com/13276804/168496134-47df6057-fb67-48b6-9d7a-ab53031c40e9.PNG)

Half press:
![halfpress](https://user-images.githubusercontent.com/13276804/168496146-a629b881-9f95-4406-aac0-3d3b8cba6f1b.png)

Full press:
![fullpress](https://user-images.githubusercontent.com/13276804/168496152-302403a7-5d93-4b63-bdb4-6f546ce00b31.png)

And as stated, RT is not mapped to anything mapper shows. Instead, LT covers the entirety like moving a joystick left to right.

This has worked correctly for me before in older versions, but I may have been using the SDL1 build without realizing it. This could be a system configuration issue, or it could be a regression, or a particular edgecase. I am currently using DOSBox-X through a scoop manifest (0.83.25) that unpacks the Release SDL2 version, but I doubt anything about the unpack could misconfigure things in such a way.

I also looked for SDL2 configs in environment variables or anything else I could've done that would make the program behave incorrectly or interpret the controller incorrectly.

### Steps to reproduce the behaviour

1. Open up mapper while using Xbox 360 controller (mine's wireless)
2. Push left trigger and see it behave as pictured
3. Push right trigger and see it isn't associated with an axis in mapper

### Expected behavior

For both triggers to be usable for commands in mapper and with real joystick support in games that support it.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

0.83.21 SDL2, 0.83.25 SDL2, perhaps all older SDL2

### Additional information

The bug occurs with the stock shipped dosbox-x.conf as well as my modified game configs that successfully worked in older builds. I tried an older build that I knew was working for me (0.83.21), and it also failed on SDL2. SDL1 works as expected, with LT residing on X+ and RT residing on X-. I still don't believe I have an incorrect SDL2 config messing things up, but it's not impossible. Either I messed up SDL2, or I was using SDL1 build and didn't realize it and this is an outstanding problem with SDL2 builds.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by aybe** [comment]
There are two solutions in here:

https://github.com/joncampbell123/dosbox-x/issues/1789#issuecomment-1249226494
