### ISSUE TITLE
Tetris Deluxe

### ISSUE THREAD

**Issue by sikthehedgehog** [joncampbell123/dosbox-x#3500]
### Describe the bug

Tetris Deluxe refuses to run (the intended way). Trying to run it gives the following message:

```
Sorry, this program will not run reliably under Windows.
Please exit to DOS and try again.
```

### Steps to reproduce the behaviour

1. Go to directory where Tetris Deluxe is installed
2. Type `tetris` and press Enter (the usual way to run it)

### Expected behavior

Tetris Deluxe runs normally.

### What operating system(s) this bug have occurred on?

Ubuntu 22.04

### What version(s) of DOSBox-X have this bug?

0.83.25

### Additional information

The check in question is present in `TETRIS.BAT`, which first calls `WINCHECK.COM` which returns whether it detected Windows or not in the errorlevel. Removing this check lets the game run normally.

The real reason for this is that the game was written back when Windows was 16-bit only and it doesn't really work properly at all there (this game uses text mode and then loads a custom character set to pretend it's using graphics mode). The author decided to make it check if Windows is running and show the error message.

Fun fact: the described workaround is also suitable for Windows 98 (just make sure to run it full screen).

The error message showed up with the default configuration (in fact I had just installed DOSBox-X and I was messing with my old DOS folder to try it), later I looked to see if there was any setting that could be affecting this but I'm not sure what needs to be touched (or if it's an outright bug), though even then it *probably* shouldn't behave as if Windows was running by default.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by MX9000** [comment]
Greetings everyone, unfortunately I am not a programmer and cannot help you, but I found this article in November 1992 issue of PC Magazine explaining the assembly code of the WINCHECK.COM utility (I hope it is the same one included in Tetris Deluxe): https://books.google.it/books?id=RJBJPJvct40C&pg=PA492&lpg=PA492&dq=utility+wincheck.com&source=bl&ots=fyImcYYUha&sig=ACfU3U1ZL77Cu38Xi1HFHE8Lh23QiejOPQ&hl=it&sa=X&ved=2ahUKEwjlwvTC1-P3AhUrhP0HHXwQBGMQ6AF6BAgVEAM#v=onepage&q=utility%20wincheck.com&f=false

**Comment by cimarronm** [comment]
Interesting find @MX9000...it's nice to see these old articles in PCMag. It doesn't appear to be the same utility or at least not the same revision as the one with this game. It does share in common the call AX=1600h/int 2fh for windows check which DosBox reports as non-windows, but also checks for WinOldAp (AX=1700h/int 2fh) which DosBox uses for DOS clipboard API. As that returns a valid value on installation check, WINCHECK assumes windows must be running. You can work around this by disabling the DOS clipboard (unchecking Menu item Shared Clipboard Functions->Enable DOS clipboard API for applications) or setting configuration item "dos clipboard api" item to false under the DOS section.

**Comment by cimarronm** [comment]
Should be resolved with #3501 which reports WinOldAp as not installed if invoked by WINCHECK

**Comment by MX9000** [comment]
Thank you @cimarronm, I really enjoy looking through old computer magazines!

**Comment by sikthehedgehog** [comment]
Closing this one since I just tried with the latest release and it works as intended now (I'd have checked earlier but I couldn't figure out how to download the repo with that specific patch lol)
