### ISSUE TITLE
ECHO command for new/blank lines incomplete implementation

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#3503]
### Describe the bug

While experimenting with batch files in MS-DOS 5 and 6 virtual machines in VirtualBox, I noticed that blank lines can be printed with the following ECHO commands:
ECHO. (the only one I knew before)
ECHO;
ECHO:
ECHO[
ECHO]
ECHO\\
ECHO/
ECHO"
ECHO+
However, only these commands works in DOSBox-X:
ECHO.
ECHO\\
ECHO/

### Steps to reproduce the behaviour

Type these commands at prompt

### Expected behavior

Same behaviour as real DOS

### What operating system(s) this bug have occurred on?

Windows 10 Pro version 21H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 0.83.25 SDL1 & SDL2 64 bit

### Used configuration

```ini
Standard
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Please try the latest commit.

**Comment by MX9000** [comment]
@joncampbell123 Thanks for your explanation!
