### ISSUE TITLE
command "MIXER /GUI" not working

### ISSUE THREAD

**Issue by aaaaaaaCatOnMyKeyboard** [joncampbell123/dosbox-x#3504]
### Describe the bug

when i enter the command "MIXER /GUI" in DOSBox-X v0.83.25, it shows a dialog asking for aspect ratio.
in DOSBox-X v0.83.24 the command works as expected.

![Mixer](https://user-images.githubusercontent.com/105523746/168874269-d9f47c6f-9a73-4183-b9f6-8f6172bff491.PNG)

### Steps to reproduce the behaviour

start DOSBox-X v0.83.25 and enter the command "MIXER /GUI".

### Expected behavior

it should show show the mixer summary

### What operating system(s) this bug have occurred on?

Windows 10 Pro 21H2

### What version(s) of DOSBox-X have this bug?

0.83.25

### Used configuration

```ini
Default Config
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Wengier** [comment]
I think the issue was resulted from commit https://github.com/joncampbell123/dosbox-x/commit/0cbec537942bb8298c2a7e825c336d2939d2b1cf. It is fixed in PR #3515.
