### ISSUE TITLE
Softscape PC-Tool 2.01 does not exit properly in Normal core

### ISSUE THREAD

**Issue by Wengier** [joncampbell123/dosbox-x#3521]
### Describe the bug

There is a DOS utility known as Softscape PC-Tools 2.01, which is an improved version of Central Point PC-Tools 5.0, downloadable from:

https://github.com/joncampbell123/dosbox-x/files/8496488/pc.zip

In the latest DOSBox-X builds the software no longer exits properly from the main interface if DOSBox-X is run with the normal core. In such case the screen will turn red completely with garaged characters (see screenshot below). The issue does not occur with the dynamic core.

On the other hand, the software worked as expected in DOSBox-X version 0.83.24 with either normal or dynamic core (at least with FPU enabled). Doing ``git bisect`` indicates the issue is related to the recent FPU improvements. The commit https://github.com/joncampbell123/dosbox-x/commit/aaabe77facb51a0f0ea4515acab672ab766f90af ("FPU Improvements" by @cimarronm) was the first commit that Softscape PC-Tools was unable to run with normal core, causing a crash when launching the software in this case. The crash was later fixed in commit https://github.com/joncampbell123/dosbox-x/commit/395efa99cf6367b81d16d2af8964f568c93dbc4c ("Update all FPU load constant instructions to account for rounding mode" also by @cimarronm), so that Softscape PC-Tools will indeed launch with normal core, but will not be able to exit properly from the main screen with normal core, as shown in the screenshot:

![image](https://user-images.githubusercontent.com/8216923/170802122-af2ff558-71e0-4c18-a9b3-53513e794052.png)

### Steps to reproduce the behaviour

1. Start DOSBox-X (latest build) with ``core=normal``
2. Run PC.EXE
3. Press Enter on the welcome screen
4. Press ESC on the main screen

### Expected behavior

A red popup dialog box shows up in the bottom asking whether you want to exit from the software:

![image](https://user-images.githubusercontent.com/8216923/170802093-a2f28173-4ded-4cd4-a628-3e78320d87a9.png)

### What operating system(s) this bug have occurred on?

Windows (at least)

### What version(s) of DOSBox-X have this bug?

Last repo code since the FPU improvements

### Used configuration

```ini
[cpu]
core=normal
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by cimarronm** [comment]
@Wengier I'll take a look

**Comment by cimarronm** [comment]
@Wengier What build are you testing with? I am unable to reproduce on macOS. I tried the vsbuild-win64 and mingw-win64 builds for the 0.83.25 release and don't see the crash or exit problem.

**Comment by Wengier** [comment]
@cimarronm Haven't tried on macOS yet, but for Windows build you can certainly tried any recent CI builds in [Actions](https://github.com/joncampbell123/dosbox-x/actions), such as this:

https://github.com/joncampbell123/dosbox-x/actions/runs/2399919293

Then run with e.g. ``dosbox-x -defaultconf -set core=normal`` and see if the exit problem occurs on your end.

**Comment by grapeli** [comment]
Works fine in dosbox-x-git under linux. I confirm.

**Comment by Wengier** [comment]
I have only tested it on Windows indeed, due to time. Not sure if there are other factors that can cause the issue, but I will try to test it on different machines too including non-Windows platforms when possible.

**Comment by cimarronm** [comment]
I see the problem...working on a fix

**Comment by cimarronm** [comment]
@Wengier Try out #3524 and let me know if it fixes it on your machine.

**Comment by Wengier** [comment]
@cimarronm Thanks for the fix. I can confirm that it addresses the said issue with normal core on my computer.
