### ISSUE TITLE
DemoLinux. The keyboard does not respond right after startup.

### ISSUE THREAD

**Issue by grapeli** [joncampbell123/dosbox-x#3525]
### Describe the bug

It stops working when selecting the language version. It works in the boot loader (syslinux).

Works fine on `ttf` output.

### Steps to reproduce the behaviour

Download [DemoLinux](https://drive.google.com/file/d/0BwO8xuhb9OwrT0laRmd3bGV5WDQ/view?usp=sharing).

`dosbox-x -set "dos hard drive data rate limit=0" -set "dos floppy drive data rate limit=0" -set cputype=pentium -set memsize=256 -c "imgmount d ./demolinux-2.0.iso -t iso" -c "imgmount 0 -el-torito d -t floppy" -c "boot a:"`

Choose one of the resolutions 640, 800, 1024 and press enter.

### Expected behavior

In this case, the keyboard is functional.
`dosbox-x -set "dos hard drive data rate limit=0" -set "dos floppy drive data rate limit=0" -set cputype=pentium -set memsize=256 -set output=ttf -c "imgmount d ./demolinux-2.0.iso -t iso" -c "imgmount 0 -el-torito d -t floppy" -c "boot a:"`

### What operating system(s) this bug have occurred on?

linux

### What version(s) of DOSBox-X have this bug?

newest and older

### Additional information

It is one of the first Live Linux CD. From 2000.
password: demo

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I tried it on Windows x64 0.83.25 SDL1/SDL2 but successfully went through setup.
Perhaps this issue is limited to Linux?

**Comment by grapeli** [comment]
@maron2000 
Under linux for default video outputs it does not work properly:
sdl2 - `opengl`,
sdl1 - `surface`.
With `ttf` output it works.

**Comment by maron2000** [comment]
@grapeli 
So I tested the latest commit 72d8cb6d SDL2 version, but seems to work well.
I explicitly added `output=surface` or `output=opengl` and both went through the setup and reached the login screen.

**Comment by grapeli** [comment]
Thanks for checking this out. Ultimately, it works fine for me.

Sorry for the confusion.
I proposed the initial settings, to which I added myself notoriously `-set cycles="max 105%"` and surprisingly they are the cause of these problems. Surprisingly, this `cycles` setting causes this behavior.

**Comment by grapeli** [comment]
For settings other than `cycles=auto`, the DemoLinux log says:
```
Keyboard timeout [2]
Keyboard timeout [2]
```
![guest os_000](https://user-images.githubusercontent.com/452325/171001322-a13f1508-6ee4-4114-9e82-d1b04927e15f.png)

Although on `output=ttf`  it may work fine for `cycles` other than the default `auto`.
