### ISSUE TITLE
Overlay mount can't create deep subdirectories

### ISSUE THREAD

**Issue by ducksys** [joncampbell123/dosbox-x#3527]
### Describe the bug

When using an overlay filesystem on top of your existing, mounted filesystem, you can't create subdirectories 2 levels deeper than the deepest directory that exists on the overlay filesystem, on your intended path.

DOS will respond with the error message: `Unable to create directory - <DIRNAME>`

### Steps to reproduce the behaviour

1. Mount a host directory in dosbox that already has the following directory structure: `\FOLDER\SUB` as `C`
2. Mount an empty host directory as an overlay filesystem on top of the existing `C` mount
3. In dosbox, navigate to `C:\FOLDER\SUB`
4. Create any subdirectory

### Expected behavior

The subdirectory and its entire path is created on the overlay filesystem.

### What operating system(s) this bug have occurred on?

Windows 11 x64, 10.0.22000.708

### What version(s) of DOSBox-X have this bug?

v0.83.25, MinGW/VSbuild SDL1/SDL2, 64-bit/32-bit

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I asked it to MKDIR ANYTHING.

I see in strace:

mkdir("overlay/folder/sub", 0755);
mkdir("overlay/folder/sub/anything",0755);

At no time does it make the subsequent mkdirs valid with:

mkdir("overlay/folder",0755);

**Comment by joncampbell123** [comment]
Please try the latest commit and confirm it works now.

It works for me now on Linux and Windows.

**Comment by ducksys** [comment]
Tested CI build 72d8cb6 on Windows 11 x64, 10.0.22000.708

mingw win32 SDL 1 ✔
mingw win32 SDL 2 ✔
mingw win64 SDL 1 ✔
mingw win64 SDL 2 ✔
vsbuild win32 SDL 1 ✔
vsbuild win32 SDL 2 ✔
vsbuild win64 SDL 1 ✔
vsbuild win64 SDL 2 ✔

All work as expected now.

**Comment by joncampbell123** [comment]
Awsome. :+1:
