### ISSUE TITLE
SDL2 binaries from dosbox-x-mingw-win32-20220531123456.zip do not work in Windows XP

### ISSUE THREAD

**Issue by gfernval** [joncampbell123/dosbox-x#3539]
### Describe the bug

When execured dosbox-x.exe gives the error: "The procedure entry point AcquireSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll"

### Steps to reproduce the behaviour

Run dosbox-x 0.84 SDL2 mingw in a Windows XP system

### What operating system(s) this bug have occurred on?

Windows XP Service Pack 3

### What version(s) of DOSBox-X have this bug?

0.84 SDL2 mingw

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
@gfernval I'm not a Windows user, but by design Windows XP is only supported by MinGW low-end and 32-bit Visual Studio builds. Other Windows builds require Windows Vista and won’t run in Windows XP.
