### ISSUE TITLE
Games testing: Touhou Project 1 - The Highly Responsive to Prayers - Unknown INT DCh calls and garbled text over playfield.

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#354]
![op_000](https://user-images.githubusercontent.com/6245486/33810694-e44698fe-ddbc-11e7-9d52-10c711c93e87.png)

**Comment by joncampbell123** [comment]
The calls to INT DCh are still unknown, but it turns out TH01 is calling INT 18h to read the FONT RAM.

**Comment by joncampbell123** [comment]
Still to investigate: Whether the game really does show "HARRY UP" or if that's an emulation error.

**Comment by joncampbell123** [comment]
This emulation capture suggests that it does indeed show "HARRY UP".

https://www.youtube.com/watch?v=GgGhm7u6sr4

**Comment by joncampbell123** [comment]
![op_000](https://user-images.githubusercontent.com/6245486/37547435-dd57d964-292e-11e8-9e2b-c03e4df04ae5.png)

**Comment by sikthehedgehog** [comment]
> This emulation capture suggests that it does indeed show "HARRY UP".

That's Engrish for "HURRY UP" (stay around too long and it'll throw a barrage of bullets at you)

**Comment by joncampbell123** [comment]
Thought so. Thanks!
