### ISSUE TITLE
Parallel passthrough with ECP

### ISSUE THREAD

**Issue by AleoDan** [joncampbell123/dosbox-x#3547]
### Is your feature request related to a problem? Please describe.

DOSBox-X is the only solution to use a physical parallel port on a 64-bit OS. I need it to transfer files from/to an old homemade HC-91 (Z80 computer with CP/M). The software was written by me long ago for both systems. On the PC, it needs an ECP parallel port, but it only uses this facility to switch data transfer direction by changing one bit in the ECP base registers.

After configuring DOSBox-X to use "reallpt realbase:378 ecpbase:778" (adresses of the mainboard's ECP parallel port), the transfer works fine PC->HC, but NOT HC->PC. The emulator writes successfully to the parallel port (because it doesn't matter if it is SPP or ECP), but it cannot switch direction and reads zeros from the data port.

### What you want

A patch to be able to use all ECP port adresses. This should be useful for a lot of applications that use the parallel port to atach various devices or for hobby electronics.

### Describe alternatives you've considered

There is no alternative, because VirtualBox or VMware both have only SPP ports, not ECP.

### Additional information

I think the emulator simply ignores any IN/OUT to the ECP base adresses. I think this is an essential issue, not a trivial one, and it should be easy to implement.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by AleoDan** [comment]
Because the configuration contains some reference to ECP base registers, this can be considered a BUG !

**Comment by joncampbell123** [comment]
For DOSBox-X to pass ECP port, additional I/O ports need to be exposed to the guest.

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Parallel%20port/Extended%20Capabilities%20Port%20%2d%20Specifications%20by%20Microsoft%20%281993%2d07%2d14%29%20v1%2e06%2epdf

![Firefox_Screenshot_2022-06-05T08-10-54 717Z](https://user-images.githubusercontent.com/6245486/172041692-96a8606d-bc5b-4627-980e-a9deacd0e5ba.png)

**Comment by joncampbell123** [comment]
One potential problem that ioport handling cannot resolve, is that ECP ports support generating an interrupt, which the host OS is unlikely to forward to us.

At that point host OS support for ECP is going to be needed.

**Comment by AleoDan** [comment]
The ports are availlable at the host, and the interrupt is not needed in most cases.

![image](https://user-images.githubusercontent.com/106826356/172043393-da6c6a95-6242-4b23-bfe9-4ba2d2212cee.png)

**Comment by AleoDan** [comment]
And this is default Windows configuration, without interrupt (the interrupt in former configuration was activated by me):

![image](https://user-images.githubusercontent.com/106826356/172043508-09801643-215b-46e0-aef5-68d403b7f1b0.png)

**Comment by AleoDan** [comment]
In most applications, only the access to the ECP ports is enough. So, I did't know that the ECP ports are not exposed to the guest. This is unfortunately, as there is a configuration word "ecpbase". It looks to me like a BUG...

**Comment by rderooy** [comment]
Please keep in mind that this is a free project. People are not paid to work on it. It is all volunteer time, and typically people work on it in their free time on things they are interested in.

If this is so important to you, you could also try to learn something new.

**Comment by AleoDan** [comment]
I know that. Of course this is true. But no one have time and energy to learn everything. Maybe others should learn how to design a processor (that I do for work) when encounter hardware bugs ?!

Anyway, this is a great project and deserves all my respect, even witout other enhancements!

**Comment by grapeli** [comment]
If you want to expand your experience and are ready to learn, get interested in a project like QEMU. Switch to Linux and you will get direct access (passthrough) and support for every device on the virtual system.

Check out the [documentation](https://www.qemu.org/docs/master/system/qemu-manpage.html). Search for parport.
https://gitlab.com/qemu-project/qemu/-/blob/master/hw/char/parallel.c
