### ISSUE TITLE
Monopoly Star Wars crashes in DOSBox-X but works on equivalent hardware

### ISSUE THREAD

**Issue by renodr** [joncampbell123/dosbox-x#3548]
### Describe the bug

When attempting to play Monopoly: Star Wars (1997) under Windows 98 in DOSBox-X, the game crashes with an invalid page fault.

When playing the game on equivalent hardware, the game runs properly. The game appears to crash while playing the introduction, which is full-motion video. I'm not sure what to do further because running WinDbg on the program causes the emulated Windows 98 SE environment to hang while debugging.

![image](https://user-images.githubusercontent.com/11901488/171954608-83dccbc9-fa47-4ecf-9091-1f3dbe67bc12.png)

Screenshot of the relevant text from the crash message:

![image](https://user-images.githubusercontent.com/11901488/171955087-24c567f1-b637-48ea-be2a-9131d0cb2d73.png)

### Steps to reproduce the behaviour

Step 1: Install Windows 98 in DOSBox-X
Step 2: Install Monopoly: Star Wars
Step 3: Attempt to launch Monopoly: Star Wars - after the LOADING screen, you'll see a screen with an introductory video, and the crash occurs in the first few seconds of playing the video.

### Expected behavior

Monopoly Star Wars runs properly.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

0.84.0 SDL1, 64-bit (also occurs in 0.83)

### Used configuration

```ini
[sdl]
autolock=true

[dosbox]
title=Windows 98
memsize=512

[video]
vmemsize=16
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[ne2000]
ne2000=true
nicirq=10
backend=pcap

[ethernet, pcap]
realnic="Killer Wireless-n/a/ac 1535 Wireless Network Adapter"

[dosbox]
captures=capture

[parallel]
parallel1=file timeout=2000

[autoexec]
imgmount c hdd.img
imgmount d MONOPOLY_STARWARS.iso -ide 2m
boot c:
```

### Additional information

If you need a copy of the game, you can find it here: https://archive.org/details/Monopoly_-_Star_Wars_CD-ROM_Edition_1997_Hasbro_

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
It worked fine for me.
How about trying default settings?

![monopoly](https://user-images.githubusercontent.com/68574602/171991091-d20b9f29-7c30-4f79-8bc3-5a0d0a7e7364.png)

**Comment by renodr** [comment]
Thank you for the suggestion!

With default settings this did work properly, so I'll experiment with the configuration file I have a bit to allow networking support while keeping the other settings at the default.

Thank you so much! I think we can close this one :)

Have a nice day!
