### ISSUE TITLE
ECP passthrough not working

### ISSUE THREAD

**Issue by AleoDan** [joncampbell123/dosbox-x#3552]
### Describe the bug

With parallel port passthrough active, any program that uses IN/OUT to ECP registers of the parallel port, no matter what base address is specified, has no effect. Only IN/OUT to the LPT base has effect.

### Steps to reproduce the behaviour

1. Get a modern mainboard that has ECP parallel port (any Asus C/CSM still has it!);
2. Change configuration to parallel port passthrough (ex: "reallpt realbase:378 ecpbase:778");
3. Verify that ECP mode is active in BIOS (Gigabyte mainboards don't have the option!);
4. Run any program that changes the data port from output to input dirrection by toggling a bit in one of the ECP configuration registers (see ECP documentation!);
5. See that the input is forced to zero or has no change, despite changing any data pins from zeros to ones;
6. Alternative: run any transfer program that requires ECP bidirectional facilities.

### Expected behavior

The parallel passthrough should be functional at the ECP base addresses too, not only at LPT base registers.

### What operating system(s) this bug have occurred on?

Windows 11 build 22000.527

### What version(s) of DOSBox-X have this bug?

All

### Used configuration

```ini
serial1 = directserial realport:COM1
parallel1 = reallpt realbase:378 ecpbase:778
```

### Output log

```text
The emulator itself can't report anything, just programs that read the LPT port by changing dirrection using ECP registers don't function!
```

### Additional information

The correction should be simple: just let passthrough to function with ECP registers too, not only with LPT registers! 

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
This is already addressed in another issue:

https://github.com/joncampbell123/dosbox-x/issues/3547
