### ISSUE TITLE
Intermittent startup failure with flashing menu bar

### ISSUE THREAD

**Issue by ducksys** [joncampbell123/dosbox-x#3553]
### Describe the bug

About once in every 100 launches DOSBox-X will fail to start up and will only show a flashing menu bar and the following console output:

`Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
      3000 DEBUG MISC:Win32: loading and attaching menu resource to DOSBox-X's window`

### Steps to reproduce the behaviour

1. Start DOSBox-X
2. If it starts up correctly hit Ctrl-F9 and go to step 1. (triggering the bug could take up to 100 tries)

### Expected behavior

DOSBox-X starts up correctly every time

### What operating system(s) this bug have occurred on?

Windows 11 x64, 10.0.22000.708

### What version(s) of DOSBox-X have this bug?

v0.84.0, VSbuild SDL2, 64-bit

### Additional information

log file: https://pastebin.com/raw/JntVZYdu
video: https://streamable.com/qmyet3 @ 1:17

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Please try the latest commit. It appears to be a bug unique to x64 Windows SDL2 builds where SDL2 and DOSBox-X get stuck in an infinite loop updating the menu bar and processing window resize/position events.

**Comment by ducksys** [comment]
testing 5dcedba , ~200 iterations in, a new message appeared, and once again, DOSBox-X refuses to start up
![image](https://user-images.githubusercontent.com/50127012/172072687-5c127c9c-1e26-4e1d-823f-792c6ac463f3.png)

**Comment by joncampbell123** [comment]
I just found out that a missing break statement causes SDL_SYSWMEVENT to fall through and mishandle the event as if a SDL_WINDOWEVENT. That doesn't help things, obviously.

**Comment by joncampbell123** [comment]
Please try the latest commit, if you can compile from source.

**Comment by ducksys** [comment]
I ran the startup test 1000 times on e750d37 and never encountered the hanging bug

**Comment by joncampbell123** [comment]
I ran it for a half hour without hitting anything. I'll close this. If it happens again, reopen this issue.
