### ISSUE TITLE
Windows 98SE only recognizes 3 CD drives

### ISSUE THREAD

**Issue by skipcress** [joncampbell123/dosbox-x#3557]
I have not tried this on any other Windows 9X OSs, but when I IMGMOUNT a CD ISO as the G: drive, then boot Windows 98SE, only CD drives D, E, and F are recognized. I have confirmed that the IMGMOUNT command is succeeding. As far as I can tell from period documentation, Windows 9X could theoretically support drives A-Z, so I don't think it's a Windows limitation. Anybody have any ideas as to why this is not working?

**Comment by rderooy** [comment]
I think you need to enable additional IDE controllers for that to work. You can have 2 devices per IDE controller, and by default there are 2 IDE controllers enabled as that was typical back in the day. From your description you are currently setup with one HDD and 3 CD-ROM, so 4 IDE devices in total, so this makes sense.

There are options for up to 8 IDE controllers in the config file. But beware, each controller will need non-conflicting resources!
