### ISSUE TITLE
Regression: timing issue in a couple of scene demos

### ISSUE THREAD

**Issue by digistorm79** [joncampbell123/dosbox-x#3560]
### Describe the bug

Compared to version 0.83.23 a couple of scene demos have timing issues. These are:
- The demo [Shattered Minds](https://www.pouet.net/prod.php?which=77397)
- The demo [My summer demo](https://www.pouet.net/prod.php?which=71415)
- The demo [303](https://www.pouet.net/prod.php?which=44)
- The demo [Riprap](https://www.pouet.net/prod.php?which=306)
- The demo [Solstice](https://www.pouet.net/prod.php?which=106)

This is both using Intel and ARM64 build, and both using normal and dynamic core.
When using the ARM64 build with the dynamic core, there are more problems and most demos will not even start. The timing routines just seem way off, running too slow.

### Steps to reproduce the behaviour

Download the demo.
Run it.
It is obvious.

### Expected behavior

On the pouet pages there are YouTube captures of the expected behaviour. In addition, since this is a regression, in version 0.83.23 things were just okay.

### What operating system(s) this bug have occurred on?

macOS Monterey

### What version(s) of DOSBox-X have this bug?

0.84.0

### Additional information

All tests were performed on a M1 Pro Macbook Pro.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
The timing issue has been discovered and (I think) resolved, as well as timing issues with "Eden". Please check out the latest commits from master and try the demos again.

**Comment by digistorm79** [comment]
Great that you found out the problem. I didn't succeed in building the dosbox project myself, I am totally unfamiliar with the build proces and I have no idea what I am doing.
