### ISSUE TITLE
menu DOS, create blank image, fails if path is on network and has space

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#3563]
### Describe the bug

Not able to create an image from menu DOS. Either due to:
- location being on the network
- location having space in the path (the name of the main "share drive" inside the "network computer")
- name of the main "share drive" starting with "_"
- some user mistake?

### Steps to reproduce the behaviour

DOSBox-X 0.84.0, DOS menu, Create blank image, 2GB, selecting as target a network location with space in the path. Results in:

Drive C is mounted as local directory \\\NETLOC\\_folder NAME\DOSBOXX\\
Z:\>Creating image file "\\\NETLOC\\_folder" with 1023 cylinders, 64 heads and 63 sectors

The file "\\\NETLOC\\_folder" cannot be opened for writing.
Z:\>

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

0.84.0

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
Tested with \\\NETLOC\ShareNAME\ - it works. So, the reason are some of the path characteristics in \\\NETLOC\_share NAME\

**Comment by Torinde** [comment]
Image file is created, but PCDOS7 complains about it - setup refuses to use it and fdisk shows "Non-DOS"
![image](https://user-images.githubusercontent.com/97228894/173251354-cdd75379-cdfe-47c2-ab3f-5dcab6db25e8.png)

DOSbox-X/FreeDOS fdisk:
![image](https://user-images.githubusercontent.com/97228894/173251552-3e6b550b-5e9d-4806-bc2d-0ebe4f3dee7c.png)


When using the "hdd-2gb.img" - PCDOS7 fdisk:
![image](https://user-images.githubusercontent.com/97228894/173251422-4168d932-8622-4b0a-9989-f5a918fa10bc.png)

DOSbox-X/FreeDOS fdisk:
![image](https://user-images.githubusercontent.com/97228894/173251455-9a7a2d95-ddc1-4644-829d-5834d19863ac.png)


So, maybe the format can be chosen by the user in the creation menu?

Also, why is there difference in the reported size 2014MB vs 2016MB ?

**Comment by Torinde** [comment]
So, the FAT32 is clear - I have ver=710 in config, so per the [Wiki](http://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X#_creating_harddisk_images) imgmake uses FAT32 >512MB.

Still - why is there a difference shown between integrated DOS (2016 MB) and guest DOS (2016 MB)?

And of course - the main problem - "create image" menu command doesn't work with "_network SHARE", but works with "networkSHARE".

**Comment by maron2000** [comment]
I think I got your point. DOS (and Win9x) needs double quotations.

![dosprompt](https://user-images.githubusercontent.com/68574602/173823154-3aff2650-888d-4086-8de4-00270c777e61.png)

**Comment by Torinde** [comment]
Yes, but when using the "Create blank disk image..." menu user selects the path via dialog box, thus can't add quotes:
![image](https://user-images.githubusercontent.com/97228894/173889745-a93fe57a-4ad9-4a28-ab2a-9606050754c4.png)

DOSbox has to **add quotes** when passing the path to imgmake, I think

**Comment by Torinde** [comment]
In general - it feels as if DOSbox-X doesn't "like" relying on network share paths - I had it hang multiple times on right after "Have fun with DOSbox-X !", e.g. on the spot where my config file executes the mount command with a target on  \\\NETWORKHOST\\_network SHARE\DOSBOXX\

**Comment by Torinde** [comment]
0.84.1 resolves the problem with creating image from the menu when having space in the path (and per the changelog - space was the problem, not _). Thank you, @Wengier.

Partition size discrepancy between DOSbox DOS and PC DOS - I'll open another issue with that question specifically.

Hanging due to tricky paths, network share usage over Wi-Fi - happens multiple times, but can't consistently reproduce it so far, so I'll open another issue if I succeed in that.
