### ISSUE TITLE
Interrupt 21h service 4Dh should unconditionally clear Carry Flag

### ISSUE THREAD

**Issue by ecm-pushbx** [joncampbell123/dosbox-x#3581]
### Describe the bug

A user reported that running one of my programs does not work, it simply ends as if the program displayed nothing and did nothing.

I figured out that my short DOS v1 check fails on DOSBox and DOSBox-X. I don't expect that the DOSBox developers will care however as these are no legacy games.

The problem is that interrupt 21h service 4Dh should unconditionally clear the Carry Flag when entered with the Carry Flag set. This is the code in which I use this property: https://hg.pushbx.org/ecm/tsr/file/daca203fa216/transien.asm#l49 (I will likely change this code to support both original DOSBox and current/older DOSBox-X but it is still a bug in DOSBox-X.)

### Steps to reproduce the behaviour

1. Download https://pushbx.org/ecm/download/tsr.zip (this will move to https://pushbx.org/ecm/download/old/tsr/20211109.zip once I have updated my applications)
2. Extract tsr.com
3. Run tsr.com

### Expected behavior

Output such as:

```
TSR example 1.00: high loaded using 160 byte, on multiplex 00h.
```

### What operating system(s) this bug have occurred on?

Debian Linux

### What version(s) of DOSBox-X have this bug?

0.83.10

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by ecm-pushbx** [comment]
Just updated with `flatpak update com.dosbox_x.DOSBox-X` to DOSBox-X 0.84.0 and the result is the same.

**Comment by joncampbell123** [comment]
Referring to this call? http://www.ctyme.com/intr/rb-2976.htm

**Comment by joncampbell123** [comment]
Looks like this has been addressed: https://github.com/joncampbell123/dosbox-x/blob/master/src/dos/dos.cpp#L2313

Can you confirm if you are able to compile the latest code, or from the latest release?

**Comment by ecm-pushbx** [comment]
Yes, on "v2022.12.26, Linux SDL2, 64-bit" the problem is fixed.
