### ISSUE TITLE
MORE command to use any writable drive when C is not mounted

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#3594]
### Is your feature request related to a problem? Please describe.

When you use something like `dir /s | more` an error comes: "Failed to create/open a temporary file for piping. Check the %TEMP% variable." In 0.83.22 @Wengier made it to automatically fallback to C:

### What you want

Please add also check for other writable drives when C: is not mounted. And/or make a writable TEMP folder on the otherwise read-only Z: - and config selector "tempformore": settemp, tryc, tryczab, tryaz, ztemp, setztemp
- use only %TEMP%, error message when no %TEMP% is set. `settemp`
- when no %TEMP%, try using C:\ `tryc`
- when no %TEMP%, try using any writable drive (trying from C: -> Z:, then A: and B:) `tryczab`
- when no %TEMP%, try using any writable drive (trying from A: -> Z:) `tryaz`
- when no %TEMP%, use Z:\TEMP `ztemp`
- add SET TEMP=Z:\TEMP (special writable folder on read-only drive) to the integrated "autoexec.bat" `setztemp`

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Wengier** [comment]
Thanks for reporting this. I think it may be addressed with the use of temporary devices. Please check the latest builds:

https://dosbox-x.com/devel-build.html

Hope this helps.

**Comment by Torinde** [comment]
It works! Straight out of the build, without any config changes. Although I wonder where the temporary pipe... files reside since Z: is not writable and I didn't have other drives mounted?

BUT - borders of the welcome screen use wrong characters instead of lines:
![image](https://user-images.githubusercontent.com/97228894/178143514-6793288e-78c6-4cf0-8e0a-a68e045f771a.png)

**Comment by rderooy** [comment]
That is probably because the codepage you are using does not have the border characters. This is normal. DOS codepages can only have 256 characters, and different regions used different codepages with different characters at those 256 character points.

The same thing happens on a real retro DOS PC, depending on codepage.

**Comment by Torinde** [comment]
Yes - 0.84.1 without customizations gives codepage 437. The current developer build - codepage 1252. I assume that's some testing ongoing and the regular release will have 437 by default...

**Comment by Torinde** [comment]
Latest artifact as of 2023-05-23 has 437 as default.

MORE still works without any mounted drive.

I still wonder where where the temporary pipe... files reside since Z: is not writable...?
