### ISSUE TITLE
IBM Music Feature Card emulation 

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#3596]
### What you want

It seems [Scali Bohemiq](https://scalibq.wordpress.com/2019/03/26/the-ibm-music-feature-card-and-yamaha-fb-01/) was already successful in adding [IBM Music Feature Card](https://en.wikipedia.org/wiki/IBM_Music_Feature_Card) emulation to DOSbox.

Interesting to add as that's maybe the only sound card from the official platform owner, IBM.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Just want to mention, that the PCjr pre-dates this and has additional sound support. Also, it is not the only sound card from IBM. IBM later also made the MWave cards which can emulate Adlib and SoundBlaster.

But yes, it would be nice to add it, even though few games support it, and those that do typically also support the superior Roland MT32.

**Comment by Torinde** [comment]
I'm not sure if this card's emulation includes full emulation of Z80 (one of the chips used on the card), but if it does - maybe the code can be utilized for the 8080 mode in NEC V-series CPUs used in some PC-9800s?

**Comment by RNMB15** [comment]
The Youtuber (LGR) made a video of the map:
https://www.youtube.com/watch?v=lyIBfjsTZcQ

**Comment by Torinde** [comment]
[List of games supporting the card](https://www.mobygames.com/attributes/attribute/22/):
Code-Name: Iceman (1989 · DOS, Amiga, Atari ST...)
Conquests of Camelot: The Search for the Grail (1990 · DOS, Windows, Amiga...)
Hero's Quest: So You Want to Be a Hero (1989 · DOS, Amiga, Atari ST...)
Hoyle: Official Book of Games - Volume 1 (1989 · DOS, Amiga, Atari ST...)
King's Quest IV: The Perils of Rosella (1988 · DOS, Amiga, Atari ST...)
Leisure Suit Larry Goes Looking for Love (In Several Wrong Places) (1988 · DOS, Amiga, Atari ST...)
Leisure Suit Larry III: Passionate Patti in Pursuit of the Pulsating Pectorals (1989 · DOS, Amiga, Atari ST...)
Leisure Suit Larry: Triple Pack (1990 · DOS, Amiga)
Mario's Early Years: Preschool Fun (1994 · DOS, SNES)
Mixed-Up Mother Goose (1991 · DOS, Amiga, Apple II...)
Police Quest 2: The Vengeance (1988 · DOS, Amiga, Atari ST...)
Roberta Williams' King's Quest I: Quest for the Crown (1990 · DOS, Amiga)
Silpheed (1986 · DOS, Apple IIgs, TRS-80 CoCo...)
Sorcerian (1987 · DOS, Genesis, TurboGrafx CD...)
Space Quest III: The Pirates of Pestulon (1989 · DOS, Amiga, Atari ST...)
The Colonel's Bequest (1989 · DOS, Windows, Amiga...)
The Space Quest Trilogy: Roger Wilco the Other World Series (1992 · DOS)

**Comment by RNMB15** [comment]
There is a dosbox version where the IBM Music Feature card has been implemented. This is the link to the dosbox version with source code (imfc.cpp, imfc_rom.c).
https://drive.google.com/drive/folders/1DlTUIyn1BZT3N7WfZKAMa4QFYSvBca23

[Nuked-OPM]
https://github.com/nukeykt/Nuked-OPM

Software to:
https://archive.org/details/mvle-imf/MVLE_000.png
http://cd.textfiles.com/swextrav1993/disk4/pcspkr/

These are the roms. the original links no longer work:
[001.zip](https://github.com/joncampbell123/dosbox-x/files/11012090/001.zip)
[002.zip](https://github.com/joncampbell123/dosbox-x/files/11012092/002.zip)

This is the documentation for the card:
https://www.ibm-pc.org/manuals/ibm/options/IMFTechnicalReference.pdf

**Comment by RNMB15** [comment]
@Allofich Could you embed the code from the (IBM Music Feature Card emulation) from dosbox-staging into dosbox-x?

**Comment by Allofich** [comment]
I started importing the code, but it uses more modern C++ features than does the DOSBox-X code. For example, it uses std::clamp. I'm using Visual Studio 2022, and std::clamp is only provided by the <algorithm> library if the project is set to use at least C++17 features.

Currently when I look at the DOSBox-X solution properties in Visual Studio 2022, the C++ features are at the default, which is C++14. When compiling DOSBox-X, a message appears that it is intended to still compile on C++11.

If it's OK to upgrade the project to C++17, I can probably finish importing the code.

**Comment by kcgen** [comment]
@Allofich : use the cpp file I mentioned here: <https://github.com/joncampbell123/dosbox-x/issues/3596#issuecomment-1486339609>, it will apply inside X (and SVN) without any API or language changes needed.

**Comment by Allofich** [comment]
OK, I think RNMB15 wanted the DOSBox-Staging version, but I'll go ahead and try with the version you mentioned.

**Comment by kcgen** [comment]
Hopefully it goes smooth, @Allofich !

There was only one function change I added, which is adding a delay in the threaded while-loop:

### Original

```c++
while (true) {
	//log_debug("DEBUG: heartbeat in MUSIC_MODE_LOOP %i", debug_count++);
	//MUSIC_MODE_LOOP_read_MidiIn_And_Dispatch(); //FIXME: reenable
	MUSIC_MODE_LOOP_read_System_And_Dispatch();
	logSuccess();
}
```

### With delay

```c++
while (true) {
	//log_debug("DEBUG: heartbeat in MUSIC_MODE_LOOP %i", debug_count++);
	//MUSIC_MODE_LOOP_read_MidiIn_And_Dispatch(); //FIXME: reenable
	MUSIC_MODE_LOOP_read_System_And_Dispatch();
	logSuccess();
	SDL_Delay(1);
}
```

This prevents the while loops from spinning at max speed when idle, however the trade-off is that it adds one full millisecond of latency before starting the process new MIDI messages.  I felt this was an acceptable tradeoff.

All the other changes on the Staging side are non-functional (with regard to IMFC): they tie-in to the mixer, IO ports, and conf, coding-style modernization (enum instead of defines), and get it passing CI with compiler warning cleanups.
