### ISSUE TITLE
Use year.month as version number?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#3603]
### What you want

Perhaps it would make sense to use the year and month for the version number, rather than the very arbitrary 0.84.xx? The current version would be 2022.07. This would make it easier for everyone to keep track of when the version they're using was created. This is just a suggestion...

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Jookia** [comment]
Yeah, it's a little silly to still be at version 0 when we're shipping monthly releases of a mature software project with backwards compatibility in mind. Having predictable version numbers also makes it easy to just know if someone's up to date. Jumping to 2022.07 would solve this.

**Comment by Jookia** [comment]
Solved. Next version will be 2022.08.0
