### ISSUE TITLE
When writting a certain command crashes programm.

### ISSUE THREAD

**Issue by SanekGamer007** [joncampbell123/dosbox-x#3613]
### Describe the bug

When i try to enter a command (rem | choice) crashes.

### Steps to reproduce the behaviour

Just enter a "rem | choice" or "echo" without letter "y" or "n".

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 0.84.1 2022-07-01 09:45 (SDL2)

### Used configuration

```ini
#all is default except
[sdl]
autolock
[autoexec]
C:
cls
@echo off
echo Starting MS-DOS...
echo:
echo:
echo HIMEM is testing extended memory...done.
echo:
echo C:\C:\DOS\SMARTDRV.EXE /X
@echo on
```

### Have you checked that no similar bug report(s) exist?

- [x] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Your said command freezed on PC-DOS 6.3 booted on VMware as well.
In what case does the command work without freezing?

**Comment by SanekGamer007** [comment]
> Your said command freezed on PC-DOS 6.3 booted on VMware as well. In what case does the command work without freezing?

This command works fine on VMware 16 with DOS 7.1
![изображение](https://user-images.githubusercontent.com/100200807/177092396-08fc8164-02c1-444b-8563-5a0f0dcfa337.png)

**Comment by maron2000** [comment]
What I refer to freeze is that you can't select either `Y` nor `N` for me.
I also tried Windows 98 Boot disk but no luck also.
![choice](https://user-images.githubusercontent.com/68574602/177139635-56d23dbd-eae8-48ac-a781-e14b3df77208.png)

**Comment by maron2000** [comment]
> in my case a entire dos-box freezes. that you can't select "y" and "n" i know about that.

You also said that it works fine on VMware.
Was that a mistake?
Anyway, according to @kcgen 's explanation it shouldn't work.

**Comment by Torinde** [comment]
Agree that the `rem | choice` is a strange (and apparently non-working) commands combination. But it fit Sanek's theme it seems - look at his AUTOEXEC.BAT - kind of imitates/fakes MS-DOS startup with `echo`'s that actually don't do anything?
So, it's interesting what the purpose is here, yes. @SanekGamer007 ?

But the point is - DOSbox-X freezes (e.g. menus become unresponsive) when encountering this combination. 
![image](https://user-images.githubusercontent.com/97228894/177479320-e63c2590-91b9-433c-ab3e-dc9bb9f5eecf.png)
VMware (per previous posts) - doesn't freeze - it's just that `choice` waits till eternity. I just tested - VirtualBox also does like VMware.

Besides freezing the emulator itself - another difference is that in Virtualbox/VMware you see `[Y , N]?` and a blinking cursor (another proof it's not frozen, but just waiting for input normally... input, which `rem` never provides). In DOSbox-X 0.84.1 no `[Y , N]?` appears.

**Comment by rderooy** [comment]
Can you break out of it in VMware with ctrl-c?

**Comment by SanekGamer007** [comment]
> @rderooy I tried CTRL-C as per your suggestion but didn't work, however, CTRL-Break worked on VMware + MS-DOS 7.1.
> 
> @SanekGamer007 Very weird. Tested both SDL1, SDL2 and no freezes.
> 
> ![choice](https://user-images.githubusercontent.com/68574602/177508513-df4dc8ed-165c-4c0f-83af-ea9c286f5a62.png)

really weird, now it working, but with numbers - still freezes

**Comment by maron2000** [comment]
@SanekGamer007 
We already know from the previous comments that if you pipe characters that does NOT satisfy `choice` it will definitely NOT work.

**Comment by Jookia** [comment]
I'm not sure how other DOSes do this but I've made a PR that fixes this by automatically quitting CHOICE when there's no more input piped. See #3648
