### ISSUE TITLE
Did the MEMDUMP, MEMDUMPBIN debugger commands get broken?

### ISSUE THREAD

**Issue by AK5GH** [joncampbell123/dosbox-x#3629]
### Describe the bug

When I try to use the Debugger commands like these: 

`MEMDUMPBIN 0:0 100000`
 and
`MEMDUMP 0:0 100000`

show the "success" message in the debugger output/log window,

`DEBUG: Memory dump binary success.`
`DEBUG: Memory dump success.`

but the both MEMDUMP.BIN and MEMDUMP.TXT files have **0** bytes length. 
However, these commands were working fine in the older 0.83.x versions a while back (on the same host system).

Is it me doing something wrong?
Or is there something in my environment?
Or is  it a bug in the newer version of the  Dosbox-X?

### Steps to reproduce the behaviour

1. Run `dosbox-x.exe` without any parameters
2. Press `Alt+Pause` to break into the Debugger
3. Issue the `MEMDUMP*` commands as above and check the resulting dump files.

### Expected behavior

That `MEMDUMPBIN` command should produce MEMDUMP.BIN file of exactly 1 MB big. 
Also, that `MEMDUMP` command should produce a text file > 4MB big.

### What operating system(s) this bug have occurred on?

Windows 7 SP1, 32-bit

### What version(s) of DOSBox-X have this bug?

0.84.1 SDL1 from "dosbox-x-vsbuild-win32-20220701165140.zip" release

### Used configuration

```ini
The default "dosbox-x.conf" included in the release ZIP file without any other command line options.
```

### Additional information

This used to work in the Dosbox-X versions < 0.83.10.  I didn't check any versions in between.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
These commands worked correctly up to version 0.83.21.

Exactly from this b084c17 change in the code, they stopped working properly.

**Comment by grapeli** [comment]
@AK5GH 
I am not very familiar with this topic. This parser does not seem to work properly at present. As if it were getting rid of the first character for length.
For `memdump 0:0 100000` interprets it as `memdump 0:0 00000`.

If you precede the declared length with any other character, you will get the desired effect.
`memdump 0:0 0100000`

**Comment by AK5GH** [comment]
Many thanks, @grapeli for your recommendation!

That workaround works. But in my opinion it's counter-intuitive. So this issue should be either _explained_ or fixed.
I will keep it open for now...

**Comment by Jookia** [comment]
@grapeli thanks for your work bisecting! Not just here but all bug reports you've been around in. :)

This is definitely a bug if it's dropping hex characters. I'll have a look at it soon.

**Comment by Jookia** [comment]
I looked at this today, it seems that GetHexValue is greedily consuming spaces when it shouldn't. #3647 should fix this.
