### ISSUE TITLE
Why PC-98 emulation in version 084.1 is MUCH SLOWER than 083.4?

### ISSUE THREAD

**Issue by AK5GH** [joncampbell123/dosbox-x#3631]
### Question

After nearly 2 years I was looking for a chance to upgrade the older Dosbox-x version 0.83.4 to the latest version 0.84,1
To my surprise, the **same** PC-98 software and the **same** .CONF file produced **10~20x slower** results in the newer version. Also, the screen redrawing speed is dramatically slower, too.

Please see the attached screen recordings (AVI files) and the .CONF file below.  The software involved are nothing special, just booting into the PC-98 command prompt and extracting of a couple of .LZH files (using the LHA archiver). 

This command line used to call Dosbox-x (in Win7 SP1, 32-bit) is:
`"C:\Program Files\Dosbox-x\dosbox-x.exe" -nodpiaware -fastbioslogo -log-con -console -conf "TestPC98_01.conf"`

Configuration [TestPC98_01.zip](https://github.com/joncampbell123/dosbox-x/files/9124794/TestPC98_01.zip)
Video from version 0.83.4 [LHA_08304.zip](https://github.com/joncampbell123/dosbox-x/files/9124798/LHA_08304.zip)
Video from version 0.84.1 [LHA_08401.zip](https://github.com/joncampbell123/dosbox-x/files/9124801/LHA_08401.zip)

Can someone, please, look at my configuration file a help me to figure our what is causing such a _dramatic drop_ in the emulated CPU performance?

Thanks a lot for any comments or recommendations!

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
For newer versions you have to correct your config. Make such settings.
```
[dos]
hard drive data rate limit=0
floppy drive data rate limit=0
```
Without them, unpacking the zip archive for me is 157x slower.

Second thing, change `core=normal` to `core=auto`.

**Comment by AK5GH** [comment]
> For newer versions you have to correct your config. Make such settings.
> 
> ```
> [dos]
> hard drive data rate limit=0
> floppy drive data rate limit=0
> ```
Thank you again, @grapeli !
Changing the `hard drive rate limit` from `-1` to `0` did the trick. Also, I added the similar line regarding the floppy as per your advice.

> Second thing, change `core=normal` to `core=auto`.

This change doesn't produce any _visible_ effect.  Can you please elaborate on what do you think _should be_ improved?
Note that I'm using a **PC-98** mode, which is a DOS 6.22-like environment with Real 16-bit mode programs only. 
Nothing like Win9x or later.  So, if I'm not mistaken, a `core=normal` or `core=simple` would be OK. I don't think any type of `dynamic_*` cores would be acceptable. 
However, my understanding of this parameter _could be_ wrong. I would welcome any additional information on this subject. Thanks a lot one more time!

**Comment by AK5GH** [comment]
Solution is to use =0, instead of default -1.
```
[dos]
hard drive data rate limit=0
floppy drive data rate limit=0
```
