### ISSUE TITLE
[GTA1] CD-Rom incorrectly copied as read only preventing configuration changes

### ISSUE THREAD

**Issue by henk717** [joncampbell123/dosbox-x#3639]
### Describe the bug

The Grand Theft Auto 1 DOS installer makes use of XCOPY, copying the file attributes as well.
In DOSBox Daum the files on the disk are read as regular files, so when XCOPY copies them over they will be written to disk as writable files. In DOSBox-X 0.84.1 when the GTA installer is ran the system will report the files as Read Only, so the files written to disk are marked as Read Only. This makes it impossible to change the settings of the game and select your sound card until you manually remove the read only flag.

### Steps to reproduce the behaviour

Use an ISO image of the GTA 1 installer for DOS and run trough it with the default options with the C: drive mounted to a folder. The files copied over will now be marked Read Only preventing future modification by the game.

### Expected behavior

The files on the disk do not have read only attributes inside the DOS environment (Does DOS normally have this?) resulting in a working copy of the game.

### What operating system(s) this bug have occurred on?

Windows 10 (Likely platform agnostic)

### What version(s) of DOSBox-X have this bug?

Tested on 0.84.1 MingGW, likely all versions

### Used configuration

```ini
100% default
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I seem to remember that MS-DOS had always set the read-only bit for files on CD-ROM because, well, it's read only anyway. Is the game using XCOPY with a flag that says to remove the read-only bit or ignore attributes?

**Comment by henk717** [comment]
I assume so, its of course a closed source setup. When I replace zcopy with the one from dos the behavior dissapears so that has been my workaround for now. Dosbox would need either an updated xcopy that handles it correctly or a mode where like daum the read only flag is ignored when saving to disk.

**Comment by Switch123456789** [comment]
I ran into the same problem today (with GTA1 and plenty of other programs), I am on arch & use ext4 filesystem. The thing that makes it quite confusing to me is that it was working fine at some point last year. If xcopy wasn't changed since 15+ years, why did it work last year then? :thinking:

**Comment by Switch123456789** [comment]
Nice :) I gave the latest version a try and the file-attributes are correct now. GTA works fine as expected, thanks!
