### ISSUE TITLE
Clipper Programm verhält sich anders als bei DOSBox SVN

### ISSUE THREAD

**Issue by hardl1** [joncampbell123/dosbox-x#3649]
### Describe the bugI have an old Clipper program running under DOSBox SVN.

An array is expanded with AADD() in a menu function.

### Steps to reproduce the behavior

i:=3
mArray has elements 1.8, 2.1, 3.0

In the example, the existing mArray with 3.1 "XY" is correctly expanded with AADD(mArray[i],"XY").

The same program code generated under DOSBox-x
element "XY" under 2.2, although i=3 with AADD(mArray[i],"XY") would have to create element under 3.1.

Anyone have an idea why?

### Expected behavior

_No reply_

### What operating system(s) this bug have occurred on?

macOS Monterey 12.4

### What version(s) of DOSBox-X have this bug?

DOSBox-X 0.84.1

### Used configuration

_No reply_

### Output log

_No reply_

### Additional information

_No reply_

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
@hardl1 Dies ist ein englischsprachiges Forum. Ich glaube nicht, dass einer der Core-Entwickler Deutsch spricht.

For those wondering what he wrote, he has a clipper program that he says behaves differently in DOSBox SVN and DOSBox-X.

**Comment by hardl1** [comment]
Sorry, I corrected that.

**Comment by Jookia** [comment]
Could you provide a test program?

**Comment by maron2000** [comment]
I don't know whether my test program is as @hardl1 intended, but I don't see any flaws.

![command_002](https://user-images.githubusercontent.com/68574602/181199218-b3a7f6bc-1ae2-4a1b-9b3c-bc723d9614db.png)

**Comment by hardl1** [comment]
I think it's a bug in my clipper program.
The MENUE_FU.PRG and the MENUE_FU.PPO have different program lines and therefore [i] is still 2.
It is not yet clear to me why this was not noticed in DOSBox-SVN.
<img width="1638" alt="Bildschirmfoto 2022-07-27 um 11 37 35" src="https://user-images.githubusercontent.com/38688960/181217856-cf3223ab-61d9-4ab8-bd33-1a5ddc8b9912.png">

**Comment by hardl1** [comment]
Is it possible that the autoexec in DOSBox-x is interpreted differently than in DOSBox SVN?
Can I check the SET environment?
<img width="575" alt="Bildschirmfoto 2022-07-28 um 13 33 58" src="https://user-images.githubusercontent.com/38688960/181497708-59839abb-e68e-4e11-9a02-720206f7bfdb.png">

**Comment by rderooy** [comment]
Sure, you can echo any environment variables. e.g.
```
echo %INCLUDE%
```

**Comment by hardl1** [comment]
naturally....
I've already used that.
SET also returns the environment.
sorry
The environment is ok.
I just can't figure out why the same program runs under SVN and not under -X.

**Comment by rderooy** [comment]
btw.
Looking at your `INCLUDE` statement, it seems that the second path is incomplete? The way it is written, it will be interpreted as a relative path. I assume you meant to write `C:\CLIPPER\CAT\INCLUDE`.

**Comment by hardl1** [comment]
Thanks, Correct, but change didn't change anything.

**Comment by hardl1** [comment]
I don't understand that now: 
I installed the ARM64 version 0.84.1 on my macbook M1 and the Clipper program gives wrong results.
After many changes and trials I have now installed the macosx-x86_64 version and it works perfectly.

**Comment by rderooy** [comment]
Try to use `core=normal`, I suspect some issue with the dynamic core on ARM64.

**Comment by hardl1** [comment]
No also with core="normal" error, but the X86_64 version runs fine.
Only printing from the macbook via WiFi does not work yet.

**Comment by maron2000** [comment]
According to #2401 some combination including CPU core type works and some don't, so we only have to try.
