### ISSUE TITLE
Windows builds: NE2000 support not enabled (at compile time)

### ISSUE THREAD

**Issue by Paukan777** [joncampbell123/dosbox-x#365]
Just tried enabling NE2000 mod with Windows 98 guest OS installed. Windows didn't detect network card, and console doesn't show any information about interfaces list.

NE2000 related part of my config

[ne2000]
ne2000=true
nicbase=300
nicirq=5
macaddr=AC:DE:48:88:99:AA
realnic=list

**Comment by joncampbell123** [comment]
NE2000 is not enabled in config.h in Windows builds.

**Comment by joncampbell123** [comment]
Done
