### ISSUE TITLE
Remove Line Breaks in Text Copied to Clipboard 

### ISSUE THREAD

**Issue by XYwriter** [joncampbell123/dosbox-x#3650]
Pardon me if this has been raised before and I can't find it.

I am running XYwrite 4 in DosBox-X-App, Edward Mendelson's Mac port of DosBox for word processors.

I Select in XYwrite and send to the clipboard, then from the clipboard to TextEdit or a Google Doc.   This was seamless in the XY4 branch of VDosDisk (thank you Wengier Wu!), but Monterey destroyed that compatibility, and DosBox is the recommended replacement. 

Now, when I paste the selected text into Mac's TextEdit or a Google Doc, sometimes I don't get the full selection. The last line or so is cut off. I can't figure out whether there is a character limit--it happens randomly with paragraph-long or page-long selections.

Also, when I copy the clipped text from XY4 iinto TextEdit or a Google Doc, it shows line breaks (left arrow) and paragraph breaks (circle and musical note). I can delete them but I have to do that manually. Is there a way to keep the breaks but make the arrows/circle/note not show?

I have tried using the online Line Breaks Remover tool at textfixer.com, and it removes the line breaks,  but it retains the circle/musical note paragraph breaks.

Thanks for any workarounds. I am very grateful for DosBox-X.

**Comment by emendelson** [comment]
Perhaps this could be expressed as a simple feature request: 

Could there be an option to strip line breaks and other control characters when copying from DOSBox-X to the Windows/Mac clipboard?

That would accomplish what this post asks for.

**Comment by Jookia** [comment]
Have you tried setting up DOS clipboard handling, or is that what's happening? Does it happen with other text editors?

**Comment by XYwriter** [comment]
Thank you for the edit, emendelson. That is far more concise.  

Jookia, I'm not clear what setting up DOS clipboard handling means, sorry to say. 

I have relied on the XyWrite list for evolving programs to move XYWrite's selected text--which is likely the DOS clipboard--to Windows and now Mac clipboards. I have the vintage CLIP.VBS and CLIP.EXE (for 32-bit Windows and VDosDisk) if it would help to examine them, but I no longer invoke them. 

With DosBox-X-X, I highlight and select XY4 text and use Ctrl-Z for DosBox-X's Copy to Clipboard.

The control characters show up in every text editor: TextEdit, Pages and BBEdit on the Mac; Google Docs, Gmail and Yahoo Mail online; even here.

Here is an example.♪
○Next paragraph.♪

**Comment by Jookia** [comment]
DOS has native clipboard support doesn't it? Or am I misunderstanding something that DOSBox adds.

Could you upload or send your DOSBox setup to me so I can reproduce your issue? Or link to files to test with?

**Comment by rderooy** [comment]
DOS never had clipboard support. Clipboard support is something specific to DOSBox-X as implemented by @Wengier

**Comment by emendelson** [comment]
@XYwriter - perhaps you could edit the title of this issue to something like:

`Remove linebreaks from text copied to clipboard?`

That way, it might attract interest from people who aren't interested in XyWrite.

**Comment by XYwriter** [comment]
@emendelson 
Thank you for the suggestion -- done. I wonder if other DOS word processors have the same issue.

**Comment by maron2000** [comment]
I don't see any flaws except the left arrow on a x86 Mac, Monterey 12.4.
I personally don't think the left arrow itself is a bug, since you can see it on the screen.
![clipboard](https://user-images.githubusercontent.com/68574602/181740251-8b9bdce4-aa75-46dd-b51b-2709bbba0cc1.png)

**Comment by XYwriter** [comment]
Interesting. If I select text and run CLIP.EXE within XY4 (from the XYWWWEB package) and paste from DOSBox-X into TextEdit, I get this:

This is a sample file in XyWrite. You are using it to learn to identify the parts of the main screen. You are also using it to learn to do some of the following tasks with either a mouse or a keyboard.♪
♪
○Select options from...→

Eighth-note and circle control characters are shown. 

OTOH, using DOSBox-X's Copy to Clipboard generates this: the whole window.  

C:\XYca sample
                                              1 C:\XY\SAMPLE 8:04 PM      c  N I
────────────────────────────────────────────────────────────────────────────────
This is a sample file in XyWrite. You are using it to learn to identify the
parts of the main screen. You are also using it to learn to do some of the
following tasks with either a mouse or a keyboard. ←
←
     Select options from...

On first glance that looks better, although it includes the command line (easily deleted). 

But: Copy to Clipboard is preserving the line breaks as they happen in the XyWrite window -- something like a screen grab -- instead of copying the text without it getting wrapped. So Copy to Clipboard version requires taking out every line break --  after "identify the" and "some of the" -- when pasted into something that doesn't use the same margins.  

That's more tidying up than just fixing the paragraph endings. 

Similarly, if I select the text with the DOSBox-X Clipboard function,  the line breaks from the XY window are preserved and would have to be removed. 

What I'm hoping for is something like what I had in VDosPlus-Mac: Selected text (sent to CLIP$ with CLIP.EXE)  would go into the Mac clipboard as a string of ASCII characters, preserving the paragraph breaks. Then, when pasted, it didn't show the eighth-note and circle control characters. 

Hope this is a clearer explanation.

**Comment by Wengier** [comment]
@XYwriter I think this issue is specific to non-Windows platforms. I hope my PR #3650 fixes it.

**Comment by Jookia** [comment]
This helps a bit. The previous pasted text:

```
only to wind up with zilch.♪
♪
Sometimes you grab whatever is close at hand and just get busy. The hours go by like minutes, and the next thing you know, the bucket is full.♪
♪
So it was for Neil Young on August 11, 1976, at Indigo Studios in Malibu.♪
→
```

now pastes as:

```
Sometimes you grab whatever is close at hand and just get busy. The hours go by like minutes, and the next thing you know, the bucket is full.

So it was for Neil Young on August 11, 1976, at Indigo Studios in Malibu.
→
```

Not entirely sure where the arrow at the end is coming from. Is it XyWrite?

**Comment by maron2000** [comment]
I thought you use only DOSBox-X built-in clipboard function (I tried right mouse click),
since you mentioned you no longer invoke CLIP.exe.

Anyway, you don't need to use CLIP.exe, but simply use the command `savedef CLIP$`
Works fine, no un-needed line breaks and control characters at least on Windows build.

Maybe some difference in the Mac builds, as @Wengier mentioned.

![clip_test](https://user-images.githubusercontent.com/68574602/181908416-3a5952e6-1492-4a9b-bada-783f36d2fe22.png)

**Comment by emendelson** [comment]
My DOSBox-X app for the Mac is now updated with the corrected code:

http://www.columbia.edu/~em36/dosboxapp.html

**Comment by XYwriter** [comment]
Problem solved! 

My enduring gratitude to Wenger and emendelson.
