### ISSUE TITLE
 Will it be relevant to be able to edit the CGA palette?

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3668]
### Is your feature request related to a problem? Please describe.

No.

### What you want

Yes, I know there is an EGA shader file, wich only contain the CGA palette, in the shader folder, including CGA shaders, which is even easy to edit. As far as I know, I don't think it's easy to change any CGA color to whatever color you want the specific CGA color to be changed to.
Therefore, I suggest an CGA palette editing option. I also hope it can work, if the machine is set to something higher than cga (e.g. vesa_nolfb).

Edit: I have made a major edit in this post/issue, and changed its name. It's because I've learned a lot about such things in the last few days.

### Describe alternatives you've considered

```ini
[cga palette editor]
# 00: Set the prefered web color.
# 01: Set the prefered web color.
# 02: Set the prefered web color.  
# 03: Set the prefered web color.
# 04: Set the prefered web color.
# 05: Set the prefered web color.
# 06: Set the prefered web color.
# 07: Set the prefered web color.
# 08: Set the prefered web color. 
# 09: Set the prefered web color. 
# 10: Set the prefered web color. 
# 11: Set the prefered web color. 
# 12: Set the prefered web color. 
# 13: Set the prefered web color. 
# 14: Set the prefered web color. 
# 15: Set the prefered web color. 
#
# 00 = 000000
# 01 = 0000AA
# 02 = 00AA00
# 03 = 00AAAA
# 04 = AA0000
# 05 = AA00AA
# 06 = AA5500
# 07 = AAAAAA
# 08 = 555555
# 09 = 5555FF
# 10 = 55FF55
# 11 = 55FFFF
# 12 = FF5555
# 13 = FF55FF
# 14 = FFFF55
# 15 = FFFFFF
```

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by kcgen** [comment]
@BridgeHeadland , GitHub's markdown editor treats lines starting with "#" as headings.

For your example `[ega palette]` conf section, put it all inside three back-ticks, like this:

```
```ini
[ega palette]
#000000 red: Set the selected custom RGB color code number (e.g. 0). -1 means  default.
#000000 green: Set the selected custom RGB color code number (e.g. 0). -1 means default.
#000000 blue: Set the selected custom RGB color code number (e.g. 0). -1 means default.
```

And end it with three back ticks: ` ``` `
