### ISSUE TITLE
Dosbox-x crashes while starting Windows for Workgroups 3.11 with the built in SVGA driver

### ISSUE THREAD

**Issue by alexmocanu** [joncampbell123/dosbox-x#3676]
### Describe the bug

Dosbox-x crashes if I start WfW 3.11 with the built in SVGA driver. 
Switching back to the VGA driver works. 

I have attached the logs and configuration file
[log.txt](https://github.com/joncampbell123/dosbox-x/files/9331044/log.txt)
[dosbox-x.conf.txt](https://github.com/joncampbell123/dosbox-x/files/9331046/dosbox-x.conf.txt)
.

### Steps to reproduce the behaviour

1. Install Dosbox-x
2. Set CPU core to Normal Core and CPU type to 486
3. Mount a directory as drive C
4. Install WfW 3.11 with VGA driver
5. Start Windows and change the driver to Super VGA 800x600, 256 colors, small fonts
6. Try to start windows again, and dosbox-x will crash
7. Switch back to the vga driver (using the setup command from the windows directory) and WfW 3.11 starts

### Expected behavior

Dosbox shouldn't crash in this situation. Windows should either load or crash with some error without bringing dosbox-x down with it. 

### What operating system(s) this bug have occurred on?

Windows 10 Pro 21H2, build 19044.1889, 64 bit

### What version(s) of DOSBox-X have this bug?

DOSBox-X version 2022.08.0 (Windows SDL1)

### Used configuration

```ini
Attached in description. Can't post here because Github throws this error: Comment is too long (maximum is 65536 characters)
```

### Output log

```text
Attached in description. Can't post here because Github throws this error: Comment is too long (maximum is 65536 characters)
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Which SVGA driver did you install?
I see from your config file, that you are using the default S3 Trio64 video chipset emulation in dosbox-x.

Did you follow the wiki instructions?
https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-3.x

**Comment by maron2000** [comment]
Unless you strongly intend to use SVGA driver, using Trio64 driver works fine.
![krnl386_000](https://user-images.githubusercontent.com/68574602/184480141-88a6febc-ad03-4e0c-acee-08b2422622e4.png)

**Comment by alexmocanu** [comment]
Using S3 drivers works perfectly, there are no more crashes with that one, thanks for the suggestion. 

As for the crash:

I used the built in svga driver that comes with WfW 3.11:
1. I went to Program Manager->Main->Windows Setup->Options->Change System Settings
2. In the "Display" dropdown I replaced "VGA" with "Super VGA (800x600, 256 colors, small fonts)"
3. I clicked on OK, the driver was replaced (I have the installation files on the same drive/mounted folder as Windows to avoid messing with floppy images)
3. At the end I clicked on "Restart Windows" -> dosbox-x closed itself. 

At this point this log was generated:
[log_first_crash.txt](https://github.com/joncampbell123/dosbox-x/files/9331314/log_first_crash.txt)

I started dosbox-x again, started Windows, the dosbox-x window resized itself for a moment then crashed with this log
[log_second_crash.txt](https://github.com/joncampbell123/dosbox-x/files/9331316/log_second_crash.txt)

I did follow those instructions in the wiki and the result is the same: dosbox-x crashes with the default SVGA driver that comes with WfW 3.11

**Comment by maron2000** [comment]
SVGA driver which comes with Windows 3.x doesn't work with S3 video cards.
You can patch it to work, but it will still have some limitations.
Google "svga256 patch" for details.

**Comment by joncampbell123** [comment]
Selecting the "Super VGA" driver in Windows 3.1 doesn't crash DOSBox-X here, it just makes Windows 3.1 complain that it cannot initialize the video adapter.

**Comment by maron2000** [comment]
Yeah, and it isn't a bug on the DOSBox-X side, but it is just that the built-in driver isn't generic to all video cards.
The driver doesn't work on VMware and Virtual box without patches as well.
Therefore it makes no sense to use the built-in driver instead of Trio64V driver on DOSBox-X.
I think this issue can be closed.

**Comment by joncampbell123** [comment]
I'm curious though, what card is "Super VGA (640x480) 256-color" supposed to support anyway? Any particular card or chipset? Some obscure thing IBM made?

**Comment by maron2000** [comment]
There is a list of cards supported by the built-in driver at Vogons.
https://www.vogons.org/viewtopic.php?t=20130
