### ISSUE TITLE
OpenGL disabled during configure.

### ISSUE THREAD

**Issue by Achaean** [joncampbell123/dosbox-x#3680]
### Describe the bug

**Hi!** :-)
I tried to compile the latest stable version at PCLinux.
However, OpenGL can't be enabled during configure time.

I installed the requirements (hopefully all of them) and I ran the build-debug-sdl2 script.
The related lines are below (at output log).

### Steps to reproduce the behaviour

Run the  build-debug-sdl2 script.

### What operating system(s) this bug have occurred on?

PCLinux.

### What version(s) of DOSBox-X have this bug?

Latest stable v.2022.08.

### Output log

```text
.
.
.
checking for main in -lGL... no
checking for main in -lopengl32... no
checking for GL/gl.h... yes
.
checking whether opengl display output will be enabled... no
.
.
.
```

### Additional information

If you want me to zip the entire console's output (>5.000 lines) and upload it here, please tell me.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Jookia** [comment]
It looks like on PCLinuxOS libGL is not in the library PATH by default. The correct thing to do here is for configure.ac to query 'pkg-config --libs' which returns '-L/usr/lib64/libglvnd/ -lGL' and builds correctly.

This bug doesn't show up when building the SDL2 version.
