### ISSUE TITLE
DOSBox-X hangs when trying to use ABICOMP encoding (code page 3848, for Brazil)

### ISSUE THREAD

**Issue by FeralChild64** [joncampbell123/dosbox-x#3681]
### Describe the bug

Emulator hangs when trying to set code page 3848 (ABICOMP).

### Steps to reproduce the behaviour

Execute command inside the emulator:

`keyb br 3848`

### What operating system(s) this bug have occurred on?

Gentoo Linux, AMD64

### What version(s) of DOSBox-X have this bug?

d0066f0e585d45679577722b3abec5a8cb098a82

### Output log

```text
LOG:   32989870 ERROR CPU:Illegal Unhandled Interrupt Called 6

(repeated endlessly)
```

### Additional information

DOSBox Staging suffers from the same problem - https://github.com/dosbox-staging/dosbox-staging/issues/1866

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Maybe built-in EGA18.cpx is corrupted. (for DOSBox-staging as well?)
If I copy EGA18.cpx from FreeDOS and run the command, it looks working.

![command_001](https://user-images.githubusercontent.com/68574602/185300136-450ee485-feee-49de-99da-00430358eb63.png)

**Comment by grapeli** [comment]
According to the information in the `DOC/CPIDOS/CODEPAGE.TXT` file from [cpidos.zip](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/unstable/base/cpidos.zip), the `EGA18.CPX` file corresponds to this code page.

>EGA18
>-----
>  856 - Hebrew II
> 3846 - Turkish
> 3848 - Brazilian ABICOMP

After copying this file, it works as expected.

**Comment by grapeli** [comment]
This file is definitely correct.
After copying from `Z:\CPI\EGA18.CPX` to another location (disk) it works as it should.
Otherwise, the log is spammed.
```
ERROR CPU:Illegal Unhandled Interrupt Called 6
      CPU:Illegal/Unhandled opcode FF7E
```

**Comment by maron2000** [comment]
@FeralChild64  As I mentioned, the one I used is included in FreeDOS distribution.
Do you mean that your copy of EGA18.CPX didn't work?
If so, try @grapeli 's suggestion.

**Comment by grapeli** [comment]
Another way to work around the inability to load the embedded codepage is to put this file (`EGA18.CPX`) directly in the dosbox-x executable directory.
