### ISSUE TITLE
Running-automounting programs directly from console command "dosbox-x.exe" "%1"

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#369]
Hi, i'm missing very important and basic feature - running (with directory automounting to C:) programs directly from console command 
for example: we have "Dosbox-x" folder and "Game" folder. I do 
```
cd Dosbox-x
dosbox-x.exe "..\GAME\start.bat"

```
so it will
1. mount GAME folder as C:
2. run (call) start.bat
If i want to associate dosbox-x or run it from a batch (as i always do)...
Instead of creating new copy of .conf file every time just to change some "autoexec" strings - i prefer there will be clean "autoexec" section and i could just select bat file dosbox will be running.
Currently it does nothing

**Comment by joncampbell123** [comment]
Is this what the main DOSBox project does?

**Comment by Corak667** [comment]
Yes, dosbox main project does it, dosbox-daum too
http://picsee.net/upload/2017-12-16/07cfca0b91ae.png

**Comment by WarlockSVG** [comment]
Hey Corak.
You can use 2 config files to start you dosbox-x
dosbox-x.exe -conf "**default.conf**" -conf "**game??.conf**"

The first will be loaded first... use it with your default settings.
The 2nde will load 2nde, it will override whatever is defined is the first config.

This way you can use the 2nde config file to act as your start.bat using the [autoexec] section.

**Comment by joncampbell123** [comment]
@WarlockSVG Good workaround. But long-term, if that is what DOSBox does, then DOSBox-X will do it too.

**Comment by Corak667** [comment]
@WarlockSVG thanks for advice! Good, but still i prefer .bat, because if i want to run my game on real DOS (or another virtual machine) then, i dont need to copy this strings from .conf, i will have working already gamepack with preset batches

**Comment by WarlockSVG** [comment]
Using the config to start your bat file will give you the same result.

> dosbox-x.exe "..\GAME\start.bat"
> 
>   or
> 
>  dosbox-x.exe ( no %1 parrameter )
> **dosbox.conf**
> [autoexec]
> call "..\GAME\start.bat"

It just comes down to what you prefer... or what your setup layout already is ;-)

**Comment by Corak667** [comment]
@WarlockSVG I understand, but this are not useful enough. Because: 
1. If i use want to use associated (with shortcuts or Keys in Total Commander) dosbox on ANY .bat file - i will have to auto-create .conf file for EVERY DOS .bat/exe file i'm trying to run. And if i'm trying to run it on totally write-protected drive - it will be a problem.
2. I don't want to mess with thousands .conf files to direct them to another bat/exe files, i better just use some bat file as preset to quickstart selected exe/bat

**Comment by joncampbell123** [comment]
Done.

If a .BAT file is given on the command line, it auto inserts into AUTOEXEC.BAT commands to mount the current working directory as C: and then call each BAT file one by one, then unmount drive C: and continue on to the [autoexec] section of dosbox.conf normally.
