### ISSUE TITLE
Tandy 3-Voice does not work when Tandy is enabled, as long as the machine emulation is set to EGA or higher

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3695]
### Describe the bug

According to the speaker emulation Tandy, it says "Enable Tandy Sound System emulation. For 'auto', emulation is present only if machine is set to 'tandy'.", and then the emulation should be present, regardless of machine emulations. I prefer NOLFB, but would prefer not to have to switch from vesa_nolfb to tandy, and vice versa. I reckon it's a bug, which has existed since the first version of the regular DOSBox, but I reckon something can be done about it with a future version of DOSBox-X. I've tested Ducktales: The Quest for Gold, and only PC speaker sound comes out (in vesa_nolfb), even though Tandy is set to on. If it is not an bug, the description of tandy=auto must be poorly worded.

### Steps to reproduce the behaviour

1. Go to speaker
2. Click on Tandy
3. Scroll down to On
4. PC speaker instead for Tandy 3-Voice

### Expected behavior

I expect Tandy 3-Voice to work in the Tandy games, which support T3V, not only in the machine emulations Tandy and PCjr in general, but also newer ones, like everything from EGA to VESA NOLFB.

### What operating system(s) this bug have occurred on?

Windows 10 Home, 21H2, 19044.1766

### What version(s) of DOSBox-X have this bug?

All DOSBoxes, as far as I know. Even 0.84.3 SDL1.

### Used configuration

```ini
language                  = 
title                     = 
fastbioslogo              = false
startbanner               = true
bannercolortheme          = default
dpi aware                 = auto
quit warning              = auto
working directory option  = default
working directory default = 
show advanced options     = false
resolve config path       = true
hostkey                   = mapper
mapper send key           = ctrlaltdel
ime                       = auto
synchronize time          = false
machine                   = vesa_nolfb
captures                  = capture
autosave                  = 
saveslot                  = 1
savefile                  = 
saveremark                = true
forceloadstate            = false
a20                       = mask
memsize                   = 16
nocachedir                = false
freesizecap               = cap
convertdrivefat           = true

pcspeaker    = true
pcrate       = 65536
tandy        = on
tandyrate    = 44100
disney       = true
ps1audio     = on
ps1audiorate = 22050
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
It does not work like that. Games used different methods.

Some games simply allow you to choose the sound output. For those games you may be able to simply set `tandy=on`.

But quite a few games have some autodetect logic, where they detect a PCjr or Tandy machine type and ONLY then will give you Tandy or PCjr sound. The Tandy and PCjr machine types have been created to support this detection logic (different games uses different detect logic).

**Comment by BridgeHeadland** [comment]
@rderooy I understand. Are there driver files or similar, which ignore this autodetect logic, and allow you to choose freely between Tandy 3-Voice and PC speaker in these games? Perhaps there should have been a feature included in the configuration, where one could choose, if possible.

**Comment by rderooy** [comment]
No, the detection logic is hardcoded in the games and different games uses different methods to detect if they are running on a Tandy, PCjr or something else.

**Comment by NebularNerd** [comment]
There was an old VOGONS post that discussed this idea, it could be done but you would likely need a `machine=tandyvga` or similar, as @rderooy mentions, Tandy software often looks to see if you are on a Tandy system so you still need their BIOS present (Amstrad do the same for their PPC only software as well).

[Tandy with VGA @ VOGONS](https://www.vogons.org/viewtopic.php?t=66388)
[VGA on Tandy 1000 SX](https://www.reddit.com/r/vintagecomputing/comments/fab4s0/i_finally_added_a_vga_monitor_to_my_tandy_1000_sx/)
[Tandy 1000 FAQ](http://www.oldskool.org/guides/tvdog/1kfaq.html#II.B)  

Fitting a VGA card into a Tandy is a valid configuration, mostly, some needed a driver/tsr, jumpers altering, or simply were not capable. The question really would be, why? Most games that support VGA likely offer ADLIB, SB16, GUS, MT32 audio which would be far better (Although, Tandy Audio Outrun is pretty good). The main reason behind VGA on real Tandy hardware in the day was to make the best of what you had, with DosBox you can simply use a better machine.

I guess if there are some very early VGA titles that were pre SB16 era it would be useful, I can't think of any off the top of my head but there might be some in this list: [Video Modes Supported : Tandy / PCjr @ Mobygames](https://www.mobygames.com/attribute/sheet/attributeId,31/)

**Comment by BridgeHeadland** [comment]
@NebularNerd Can machine=tandyvesa_nolfb work?

> Det var et gammelt VOGONS-innlegg som diskuterte denne ideen, det kunne gjøres, men du vil sannsynligvis trenge en `machine=tandyvga`eller lignende, som@rderooynevner, ser Tandy-programvaren ofte ut for å se om du er på et Tandy-system, slik at du fortsatt trenger BIOS til stede (Amstrad gjør det samme for deres eneste PPC-programvare også).
> 
> [Tandy med VGA @ VOGONS ](https://www.vogons.org/viewtopic.php?t=66388) [VGA på Tandy 1000 SX ](https://www.reddit.com/r/vintagecomputing/comments/fab4s0/i_finally_added_a_vga_monitor_to_my_tandy_1000_sx/) [Tandy 1000 FAQ](http://www.oldskool.org/guides/tvdog/1kfaq.html#II.B)
> 
> Å montere et VGA-kort i en Tandy er en gyldig konfigurasjon, for det meste trengte noen en driver/tsr, endrede jumpere, eller var rett og slett ikke i stand. Spørsmålet ville egentlig vært, hvorfor? De fleste spill som støtter VGA tilbyr sannsynligvis ADLIB, SB16, GUS, MT32-lyd som ville vært langt bedre (selv om Tandy Audio Outrun er ganske bra). Hovedårsaken bak VGA på ekte Tandy-maskinvare i dag var å gjøre det beste ut av det du hadde, med DosBox kan du rett og slett bruke en bedre maskin.
> 
> Jeg antar at hvis det er noen veldig tidlige VGA-titler som var før SB16-æraen, ville det være nyttig, jeg kan ikke komme på noen av hodet, men det kan være noen på denne listen: [Videomoduser som støttes: Tandy / PCjr @ Mobygames](https://www.mobygames.com/attribute/sheet/attributeId,31/)

**Comment by NebularNerd** [comment]
> @NebularNerd Can machine=tandyvesa_nolfb work, do you think?

No, it would need @joncampbell123 or the main DosBox team to create a specific machine (or machines) in the code base, much like the existing Tandy, Amstrad, FM Towns and PC98 machine options.

**Comment by rderooy** [comment]
@NebularNerd Indeed, to me this request makes little sense. Show me a game that supports VGA, but only supports Tandy sound (and not CMS, Adlib or SB).

Tandy sound is only 3 voice (+ noise) FM. While CMS has 2x6, and Adlib has 9 voice FM.
Late Tandy 1000 models did add an 8-bit 22kHz DAC, but few games support it, and those games probably also support SB 1.x which has equivalent DAC support.

https://dosbox-x.com/wiki/Guide%3ASound-card-support-in-DOSBox%E2%80%90X

**Comment by Torinde** [comment]
#3860
