### ISSUE TITLE
MSD (Microsoft Diagnostics) misdetects CPU as NEC V20 when cputype=8086

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#37]
Other programs that misdetect as well:
- PC-CHECK v7.15 & v7.20

**Comment by joncampbell123** [comment]
Okay, we're making progress. Now instead of misdetecting us as 80186 it now sees us as NEC V20. Closer, but not correct.

**Comment by Allofich** [comment]
`MSD.EXE` is fixed now after the latest code. I don't know about PC-CHECK.
