### ISSUE TITLE
Microprose Gunship fails to play on DosBox-X works elsewhere

### ISSUE THREAD

**Issue by NebularNerd** [joncampbell123/dosbox-x#3703]
### Describe the bug

Trying to play Microprose Gunship on DosBox-X does not work. Game should be run from `GS.COM` but after asking a couple of setup questions it dumps you back to command line. Basic online version of DOSBOX SVN plays it just fine.

https://user-images.githubusercontent.com/8470449/188490793-1b67589c-8525-47d6-aa85-477cb6eb28d7.mp4

### Steps to reproduce the behaviour

Steps to reproduce:
- Grab this zip [GUNSHIP.zip](https://github.com/joncampbell123/dosbox-x/files/9491199/GUNSHIP.zip) this is from my own genuine original floppy but I've tested with other copies found elsewhere with the same results.
- Open DosBox-X and mount/add the contents of the zip somewhere you can see them (with write access).
- Try running `GS.COM` and see if you can enter the game.
- You should find you get dumped back as the command prompt after a brief screen flash.

Now try it in the online emulator:
- Head here [JS-Dox Box Demo](https://caiiiycuk.github.io/dosify/) 
- Upload the same zip file and alter the command line to `"-c", "cd GUNSHIP"` then click RUN
- Once it's loaded run `GS.COM`
- It will moan about the Roster file being corrupt as it's not able to write to the disk but it at least loads.
- Same results can be had here [www.myabandonware.com](https://www.myabandonware.com/game/gunship-85/play-85). you need to change to the GUNSHIP directory and then run GS.COM (I did test the .zip available from here to test against my own copy and it behaves the same.

### Expected behavior

Should play the game the same as the basic DosBox's

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

dosbox-x-vsbuild-win64-20220901051309

### Used configuration

```text
See attached in Additional Comments
```

### Output log

```text
N/A
```

### Additional information

Tried with configuration as shared, default conf, deleted all conf files, grabbed the JS-DOSBOX config, no luck with any of them.
[PLAYGAME.zip](https://github.com/joncampbell123/dosbox-x/files/9491296/PLAYGAME.zip)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
Try it like this

`dosbox-x -set hma=false`

or

`dosbox-x -c "loadfix -a"`.

**Comment by NebularNerd** [comment]
> Try it like this
> 
> `dosbox-x -set hma=false`
> 
> or
> 
> `dosbox-x -c "loadfix -a"`.

Thanks @grapeli both of those worked, the `loadfix -a' makes it handy to pop into a bat file for autoloading.
