### ISSUE TITLE
[git] Sound is not recorded with MPEG-TS enabled - ffmpeg recording is broken.

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#3715]
### Describe the bug

I tried to record a video but sound is missing.

Audio is not recorded with both ffmpeg 4.x and ffmpeg 5.x

Git commit used: d132799

### Steps to reproduce the behaviour

1. grab latest git code commit
2. build dosbox-x with ffmpeg 4 workaround as seen in bug #3705 (cf bug #3283 )
4. Run dosbox-x
5. Try to record a video within dosbox

### Expected behavior

Recording both video and audio

### What operating system(s) this bug have occurred on?

Linux

### What version(s) of DOSBox-X have this bug?

git commit d132799

### Used configuration

```ini
Here are the building options I used with ffmpeg 4.4.


sed -i 's|"$LIBS -lavcodec -lavformat -lavutil -lswscale "`pkg-config libavcodec --libs`|`pkg-config libavcodec libavformat libavutil libswscale libswresample --libs`"$LIBS"|' configure.ac
  ./autogen.sh
  PKG_CONFIG_PATH="/usr/lib/ffmpeg4.4/pkgconfig" ./configure --enable-core-inline --enable-debug --enable-avcodec --prefix=/usr --enable-sdl2
```
```


### Output log

_No response_

### Additional information

_No response_

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by FredBezies** [comment]
Commenting code doesn't change anything. Sound is still missing.

My last working git build: d860527f6

**Comment by FredBezies** [comment]
> Are you sure [d860527](https://github.com/joncampbell123/dosbox-x/commit/d860527f67d22958f005db23fc7297ba05b78dd6) works? Could you bisect this please then to see which commit broke it? What application are you running for sound?

Yes, I'm sure commit d860527 is working. I kept an archive of this build.

Bissecting results:

Last working commit: b097760
First broken commit: d9ccf8591

It looks like ffmpeg modifications starting with "hardware: Don't use FFMPEG 4.3 hacks on FFMPEG 5" is broken.

My audio system? Pipewire.

My ffmpeg 5.x: 5.1.1

I also have ffmpeg 4.x installed.

**Comment by Jookia** [comment]
Are you building with 5? The broken commit should have no effect on FFMPEG 5.

**Comment by FredBezies** [comment]
> Are you building with 5? The broken commit should have no effect on FFMPEG 5.
> […](#)
> On Wed, Sep 07, 2022 at 12:32:04PM -0700, FredBezies wrote: > Are you sure [[d860527](https://github.com/joncampbell123/dosbox-x/commit/d860527f67d22958f005db23fc7297ba05b78dd6)]([d860527](https://github.com/joncampbell123/dosbox-x/commit/d860527f67d22958f005db23fc7297ba05b78dd6)) works? Could you bisect this please then to see which commit broke it? What application are you running for sound? Yes, I'm sure commit [d860527](https://github.com/joncampbell123/dosbox-x/commit/d860527f67d22958f005db23fc7297ba05b78dd6) is working. I kept an archive of this build. Bissecting results: Last working commit: [b097760](https://github.com/joncampbell123/dosbox-x/commit/b09776031541cc4fd9690a3feb2204935210600d) First broken commit: [d9ccf85](https://github.com/joncampbell123/dosbox-x/commit/d9ccf8591d800626773908a95c9753e9e9f30ca0) It looks like ffmpeg modifications starting with "hardware: Don't use FFMPEG 4.3 hacks on FFMPEG 5" is broken. My audio system? Pipewire. My ffmpeg 5.x: 5.1.1 I also have ffmpeg 4.x installed. -- Reply to this email directly or view it on GitHub: [#3715 (comment)](https://github.com/joncampbell123/dosbox-x/issues/3715#issuecomment-1239791304) You are receiving this because you commented. Message ID: ***@***.***>

I reported the bug using ffmpeg5.  No audio. I had to use fflmpg4 while bissecting and found the bad commit.

Once again, using either ffmpeg 4 or 5 with the last commit => no audio recorded if you select MPEG codec. Default codec is still ok.

**Comment by Jookia** [comment]
How are you testing this?

**Comment by FredBezies** [comment]
> How are you testing this?

I just try to record a video using dosbox-x and then playing it in mpv. With the last commit, no audio. With the last working commit, it was OK.

**Comment by Jookia** [comment]
The DOSBox shell doesn't play any audio, maybe that's the issue?

**Comment by FredBezies** [comment]
> The DOSBox shell doesn't play any audio, maybe that's the issue?

I can hear audio is played. It is not in the recorded file :(

Annoying.

**Comment by Jookia** [comment]
What audio do you hear?

**Comment by FredBezies** [comment]
> What audio do you hear?

The one from the game I'm recording.

Will post tomorrow morning a video showing this bug.

**Comment by Jookia** [comment]
So you're running a game? Could you give the game name or whatever so I can test this please?

**Comment by FredBezies** [comment]
> So you're running a game? Could you give the game name or whatever so I can test this please?
> […](#)

I was running Planet X3 from the 8 bit Guy.

But I think any dos game with a music can be used

**Comment by Jookia** [comment]
I see this in the console output:

```
[mpegts @ 0x562769c2cc80] Stream 0, codec none, is muxed as a private data stream and may not be recognized upon reading.
[mpegts @ 0x562769c2cc80] Stream 1, codec none, is muxed as a private data stream and may not be recognized upon reading.
```

**Comment by Jookia** [comment]
I can confirm ffmpeg 4.4 works on master just fine so this is just an ffmpeg 5 issue.

**Comment by Jookia** [comment]
Okay yeah looks like I majorly messed up the ffmpeg 5 patch and it just accidentally worked. Time to fix!

**Comment by Jookia** [comment]
I spent a few hours debugging this and managed to find out that:

- Switching to use codecpar is the proper solution here
- AAC demands the codecpar reference the ctx's working extradata

I SUSPECT this is a bug in ffmpeg? Since unless you remove the reference before freeing the ctx it double frees

**Comment by Jookia** [comment]
Okay I think I was just finding some internal behaviours there. Using avcodec_parameters_from_context after the codec is initialized seems to fix things.

This seems to work with mpv on ffmpeg 5 and I assume ffmpeg 4. VLC seems upset? I'll have to do more testing.

**Comment by FredBezies** [comment]
Thanks a lot for the long commit fix :)

**Comment by Jookia** [comment]
No problem. Could you test it and check if it works on your machine? I'm on Arch too and I'm fairly sure I fixed it but the feedback would be nice.

**Comment by FredBezies** [comment]
> No problem. Could you test it and check if it works on your machine? I'm on Arch too and I'm fairly sure I fixed it but the feedback would be nice.

I tested it and it worked perfectly. By the way, I'm also AUR maintainer for both dosbox-x-sdl2 and dosbox-x-sdl2-git packages :)

**Comment by Jookia** [comment]
Nice, nice, nice. I did put a message on the AUR page about the next release but if you have any other packaging-related issues please open an issue. I believe I've fixed them all.
