### ISSUE TITLE
Major (S3) graphics emulation improvement noted since DosBox 0.83.24!

### ISSUE THREAD

**Issue by dodleh** [joncampbell123/dosbox-x#3737]
I have been monitoring feature improvements in recent DosBox-X versions and there was one that was a major milestone, from my perspective, and I would like to share my sincere appreciation for the work that has been done.

Excerpt from DosBox-X 0.83.24 changelog:
 Revise S3 Trio64 XGA line drawing code to
    add comments, and obey the "skip last pixel" bit
    so that the Windows drivers can better draw polygon
    line segments.

This modification, if I had singled it correctly, had a tremendous effect in terms of graphics accuracy in Windows Emulation, and manifested only in Windows, as far as I had determined.

Not only polygons are drawn right in this instance of Autocad 12! (focus on the path, the red outline of the fountain on the Courtyard, the black Autodesk logo drawing accuracy, as well as text or even interface buttons positioning and drawing, the mostly empty group near the top right corner). Other applications are affected but it is most easily visible in Autocad.

Just about any DosBox distribution or classic PC emulator (PCEM, 86BOX) has issues with drawing accurately and no other developer has focused so much energy on this small issue. Until recently, only real machines could draw the screen correctly, as shown below. 

![image](https://user-images.githubusercontent.com/76946049/189717140-0bb1552e-ed73-4f32-9ffc-a1caee395a91.png)

I hope it is not inappropriate, but congratulations to John Campbell and everyone else that made fantastic contributions to DosBox. You definitively deserve our highest gratitude!

**Comment by Jookia** [comment]
Nice! Glad to see working applications. :) Though if you're pretty sure that's the bug you might want to report it to 86Box as a heads up in their bug tracker.

**Comment by joncampbell123** [comment]
Appreciate it! The initial test case that brought the issue to my attention was what happens when you draw a circle in Microsoft Word 2.0. While you move the mouse, it uses XOR to draw a circle to show you the result. The overlapping pixel made the XOR circle broken up and very discontinuous because, well, XORing twice restores the original pixel value of course. The same under the stock VGA 640x480 16-color driver did not exhibit these issues.

**Comment by joncampbell123** [comment]
Another known test case is the "curves" screensaver in Windows 95, which also relies on the "skip last pixel" bit to correctly draw smooth curves without artifacts or leftover pixels on screen.
