### ISSUE TITLE
Mounting ISO Windows 98

### ISSUE THREAD

**Issue by sobek16** [joncampbell123/dosbox-x#3739]
I am trying to mount an iso file here is my auto exec I'm not sure what I'm doing wrong:
 this is my autoexec

imgmount 2 windows98.img -size 512,63,255,522 -t hdd -fs none
imgmount D counting.iso -t cdrom -fs iso -ide 2m

boot -l c

**Comment by maron2000** [comment]
Before doing everything in autoexec, type the commands manually and see if there are any errors.
If you are trying to install Windows, carefully follow the instructions found in the Wiki.

**Comment by rderooy** [comment]
Indeed as @maron2000 said, follow the Windows installation instructions on the dosbox-x wiki.

There is no need to mount the HDD image to a device number, or specify the size. DOSBox-X supports FAT32 as long as you set the dos version to 7.1.

e.g. something like the following will work (adjust filenames and possibly paths as necessary).
```
ver set 7.1
imgmount c windows98.img
imgmount d counting.iso
boot c:
```

**Comment by sobek16** [comment]
This is displaying however when I start it the d drive is not mounted inside windows.
