### ISSUE TITLE
How about enabling the Discussions tab?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#3750]
### What you want

Maybe that could remove some pressure from the Issues tab?

That would enable a place for people who simply want to discuss and not have to open an issue about that.

Now of course, that a makes a second to place to manage...

It could be tried and always disabled if that turns out to be an inconclusive move.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Allofich** [comment]
Sounds like a good idea to me. The issues list is full of "issues" marked as "question". If it's possible to move all of these to a discussions area, that would make it easier to find code issues to work on.

**Comment by aybe** [comment]
@joncampbell123 

Can you enable the Discussions tab so we can give it a try?

Thank you.

**Comment by aybe** [comment]
@joncampbell123 

How about setting up a bot for closing stale issues?

https://github.com/marketplace/actions/close-stale-issues

**Comment by Torinde** [comment]
Automatically getting "stale" label after a set period may be OK. But I see only negatives if closing the stale issues after another period.
- currently you can order "by recent activity" which gives you the same effect - without moving non-actually-solved items to the "closed" category (which worsens the situation)
- many items are _expected_ to remain open for long time - unanswered questions (which may be moved to discussions per above, although there is already a label "questions" with the same effect), feature requests that are "nice to have, but not immediate priority" (which are actually _most_ of the feature requests), etc.

Instead I suggest to list here reasons for "open issues" to be polluted - and assign labels / milestones (as proxy of "priority"?) to those?
- discussion / question -> already has label, maybe move to discussion tab
- feature request -> already has label, also has "assignee" (e.g. if nobody is assigned, probably no progress can be expected soon), can be assigned to a "milestone"
- open issue, where the next required action is for the OP/somebody else to provide further info (e.g. test a game with another setting, provide more details/context, etc.) -> e.g. "submitter input required"

**Comment by Dobby233Liu** [comment]
> How about setting up a bot for closing stale issues?
> 
> https://github.com/marketplace/actions/close-stale-issues

IIRC Jon stated that he will not set up a stale bot in the Discord server

**Comment by aybe** [comment]
Yes, I guess you're right, simplicity is the best in the end.

**Comment by Torinde** [comment]
> * open issue, where the next required action is for the OP/somebody else to provide further info (e.g. test a game with another setting, provide more details/context, etc.) -> e.g. "**submitter input required**"

Adding such label - will that help? Or even that is not needed?

**Comment by aybe** [comment]
There are clearly too many labels, 61 exactly which half of them have been used less than 10 times.
7 of them are not used and could be deleted immediately.
Overall, only a handful of them are frequently used in the end.

There is https://github.com/joncampbell123/dosbox-x/labels/help%20from%20user but it's been used only twice...
Tried appending some character to it to bring it on top of the list but that had no effect at all.

Clearly, these should be reduced, there will be losses in the process but for the sake of clarity.

**Comment by aybe** [comment]
I propose the following:

Delete all labels with less than 10 issues, that will halve the list, there are 33 of them.

Consolidate these groups of topics:

https://github.com/joncampbell123/dosbox-x/labels/suggestion (45)
https://github.com/joncampbell123/dosbox-x/labels/feature%20request (280)
https://github.com/joncampbell123/dosbox-x/labels/feature%20improvement (17)

https://github.com/joncampbell123/dosbox-x/labels/topic%3A%20hardware (50)
https://github.com/joncampbell123/dosbox-x/labels/topic%3A%20storage (52)

https://github.com/joncampbell123/dosbox-x/labels/SDL1 (20)
https://github.com/joncampbell123/dosbox-x/labels/SDL2 (23)

https://github.com/joncampbell123/dosbox-x/labels/DOS%20gaming (75)
https://github.com/joncampbell123/dosbox-x/labels/non-working%20game (18)

This will already give some fresh air to the section.

**Comment by Torinde** [comment]
- Suggestion / feature request / feature improvement - those can be combined, I assume
- DOS gaming / non-working game - maybe also OK to combine
- SDL1 vs SDL2 - those seem quite specific to me, merging will be a loss (e.g. you can't filter per SDL type anymore)
- Hardware vs Storage - for sure some of the topics labeled with "hardware" are storage-related, but they have both labels (same as having both hardware and audio, etc.)

Is there somewhere a documentation / legend / policy on the meaning and application of the labels?

**Comment by aybe** [comment]
Yes, going to look at some popular repositories to grab some ideas from them.



> Is there somewhere a documentation / legend / policy on the meaning and application of the labels?

Not sure.

**Comment by aybe** [comment]
Deleted these unused ones:

<img width="889" alt="chrome_tRncqUfWDo" src="https://user-images.githubusercontent.com/1537591/203748912-3a5e818a-dcd1-4c33-9c6e-0910eadd6fb8.png">

Deleted these with 1 issue:

<img width="888" alt="chrome_22mfowyUfT" src="https://user-images.githubusercontent.com/1537591/203751109-d48ac31d-6dc3-4c04-8182-17dfe456a415.png">

Deleted these with 2 issues:

<img width="891" alt="chrome_OZHEqou4pd" src="https://user-images.githubusercontent.com/1537591/203751746-d6e5d981-60bd-4c54-ad1d-c631ae98a0a6.png">

Deleted also:

<img width="890" alt="chrome_oXiUcHUTWd" src="https://user-images.githubusercontent.com/1537591/203754263-3be88b56-a305-4850-8ba6-c0f3b0c5e357.png">

Deleted these meaningless and/or too generic and/or rare ones:

<img width="689" alt="chrome_SsQwU4xgnb" src="https://user-images.githubusercontent.com/1537591/203760423-9c3a8245-5228-475f-8625-bbbfaa2ee646.png">

<img width="622" alt="chrome_RgAfbhkMWK" src="https://user-images.githubusercontent.com/1537591/203760661-24bbd898-e7e4-4930-8957-fcdb3ad6d801.png">

<img width="647" alt="chrome_JbedbPf05m" src="https://user-images.githubusercontent.com/1537591/203760825-93f3b694-a12e-4571-936a-cfd6a59dbc15.png">

<img width="624" alt="chrome_Cqq1cUmQsK" src="https://user-images.githubusercontent.com/1537591/203761026-27af318b-7d37-4f7b-8d71-ace9f2a16ea7.png">

Merged these:

<img width="122" alt="chrome_lqJVOQcaoe" src="https://user-images.githubusercontent.com/1537591/203750109-06a4eaf2-fedb-4ecb-8f84-e0595a24cc66.png">

Merged these:

<img width="901" alt="chrome_wyy2NonwTX" src="https://user-images.githubusercontent.com/1537591/203753653-64a1b1a7-b89f-4882-ba21-1fcc2c5a1a13.png">

Merged these:

<img width="148" alt="chrome_423siGGKuj" src="https://user-images.githubusercontent.com/1537591/203755725-a0a3210c-99d5-462b-8663-892620e4e68c.png">

I think that is enough for the time being, from 61 to 35 which is quite a change.

Turns out that making really generic labels was a terrible idea in the end.

The `topic: hardware` is rather hard to remove because it's catchall at the same time.

From what I've seen there should be something like `topic: COM/LPT/modem`.

In the end, I guess less is more when it comes to labels.

**Comment by joncampbell123** [comment]
Discussions tab open.

**Comment by Allofich** [comment]
Is it possible to move over existing issues to the discussions tab? Just looking at the current 1st page of issues, 11 of 25 issues have the "question" tag. It would certainly help thin out the number of open issues.

I would note, though, that some issues marked "question" are what I would consider as issues (i.e. reporting a problem, or at least something the reporter perceives as a problem), not questions. Such as https://github.com/joncampbell123/dosbox-x/issues/3819.
