### ISSUE TITLE
Blood crash MS-DOS

### ISSUE THREAD

**Issue by AITUS95** [joncampbell123/dosbox-x#3752]
### Describe the bug

When I play a new game, the game crashes in the menu while the audio is playing, it happens with vesa and normal, I allow the game to run normally without ms-dos.

### Steps to reproduce the behaviour

1. Run Dosbox-x
2. Boot MS-DOS
3. Run Blood
4. Select New Game
5. Crash

### What operating system(s) this bug have occurred on?

Windows 10 Pro x64

### What version(s) of DOSBox-X have this bug?

v0.84.0, Windows SDL2, 64-bit

### Additional information

[log.TXT](https://github.com/joncampbell123/dosbox-x/files/9591766/log.TXT)

[dosbox-x.TXT](https://github.com/joncampbell123/dosbox-x/files/9591768/dosbox-x.TXT)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by NebularNerd** [comment]
I was just testing this as I was looking at #1285 and grabbed a copy of the [Internet Shareware 1.11](http://www.r-t-c-m.com/knowledge-base/downloads-rtcm/blood-shareware/blood1.11sw.exe) from [RTCM](http://www.r-t-c-m.com/knowledge-base/downloads-rtcm/blood-shareware/) 

Unpack the `blood1.11sw.exe` either inside DoxBox (put it in a directory by iteself) or you can unpack with WinZip/7z etc on your host OS. Run the `install.exe` then `setup.exe` and set it for Soundblaster with default address settings and highest voices/mixing etc...  and it runs a treat.

Where is you copy of Blood from?

**Comment by AITUS95** [comment]
i am using cd, it is retail version 1.0 without patch.

https://user-images.githubusercontent.com/48457684/190927160-3a658786-1a31-4364-9cea-605a2b37a0fc.mp4

https://user-images.githubusercontent.com/48457684/190927171-cac3ae2c-6771-4014-aaf7-d7f1a0c8451e.mp4







 **here is when I don't load the cd.**

 https://user-images.githubusercontent.com/48457684/190927209-9a5e21f8-f2b0-4f07-8470-061895c4fb02.mp4

**Comment by AITUS95** [comment]
with dosbox-x integer i have no problems, the problem is only on ms-dos.

**Comment by maron2000** [comment]
According to the log you pasted, the ATAPI command issued by the game is illegal.
`Unknown ATAPI command 1b 00 00 00 03 00 00 00 00 00 00 00`
Byte 4 should NOT be 3. (Refer to https://www.manualslib.com/manual/54879/Fujitsu-Mcm3064ap.html?page=147)

Indeed updated versions (I tried 1.11) runs fine on PC-DOS assuming that the bug (issuing an illegal command) is fixed.
DOSBox-X built-in DOS seems to handle such command better than genuine DOS.

**Comment by AITUS95** [comment]
I compared the CRC of my disk with the CRC of Redump and they are similar, the image is from an original copy, I tried to start the game on windows 95 to get the cutscenes too, but the game crashes anyway.

**Comment by maron2000** [comment]
Freezed on PC-DOS 6.3 on VMware as well. 
CD mounted on Daemon tools, since VMware doesn't support cue+bin format.
I really don't think DOSBox-X is to be blamed.
![blood](https://user-images.githubusercontent.com/68574602/191237057-f0f9d384-d7b8-4e40-8f77-6596cb4b89f1.png)

**Comment by AITUS95** [comment]
> Are you using Daemon Tools inside DosBox or mounting through Daemon from your host OS and then attaching to DosBox? Also were you previously using the CD directly or mounting an .iso/.bin+.cue made from it?

i am using daemon tools inside dosbox with windows 95, previously i used bin + cue files to mount the image.

**Comment by NebularNerd** [comment]
I only had the shareware internet demo but have just grabbed a copy of the 1.00 CD from the [.zip @ archive.org](https://archive.org/download/msdos_Blood_1997), it's in the cd subdirectory and in a cue/img format. The CD is complete with soundtracks so should be a close match to yours.

Started up Dosbox (using SDL2 from recent autobuild [dosbox-x-mingw-win64-20220918203221](https://github.com/joncampbell123/dosbox-x/suites/8348337152/artifacts/367641294)) with a mounted folder share and the .cue mounted as a CD on drive D. Installed, ran setup and set everything  the same as before. the game plays without issue and with CD Audio.


https://user-images.githubusercontent.com/8470449/191298599-a2b219b7-7f51-4713-b39e-cb738782a638.mp4

Setting up a DOS 6.22 HD Image with CD drivers and attaching the same cue/img give the interesting result of not being able to see files on the BLOOD CD. However a basic iso works fine which you can see at the top of the screenshot.

![guest os_000](https://user-images.githubusercontent.com/8470449/191317596-542670a6-a706-43bc-9f09-39547165d32f.png)

Were I to take a guess, DosBox-X is not happy with cue/img or cue/bin style mounts under MS-DOS environments.

**Comment by AITUS95** [comment]
> I only had the shareware internet demo but have just grabbed a copy of the 1.00 CD from the [.zip @ archive.org](https://archive.org/download/msdos_Blood_1997), it's in the cd subdirectory and in a cue/img format. The CD is complete with soundtracks so should be a close match to yours.
> 
> Started up Dosbox (using SDL2 from recent autobuild [dosbox-x-mingw-win64-20220918203221](https://github.com/joncampbell123/dosbox-x/suites/8348337152/artifacts/367641294)) with a mounted folder share and the .cue mounted as a CD on drive D. Installed, ran setup and set everything the same as before. the game plays without issue and with CD Audio.
> 
>  Blood.000-1.mp4 
> Setting up a DOS 6.22 HD Image with CD drivers and attaching the same cue/img give the interesting result of not being able to see files on the BLOOD CD. However a basic iso works fine which you can see at the top of the screenshot.
> 
> ![guest os_000](https://user-images.githubusercontent.com/8470449/191317596-542670a6-a706-43bc-9f09-39547165d32f.png)
> 
> Were I to take a guess, DosBox-X is not happy with cue/img or cue/bin style mounts under MS-DOS environments.

strange, what CD driver are you using?  I have no problem mounting .cue .bin

**Comment by NebularNerd** [comment]
> strange, what CD driver are you using? I have no problem mounting .cue .bin in MS-DOS.

I was using UIDE.SYS from FreeDOS as recommended in the DosBox-X wiki, I'll try some others and see what happens.

**Comment by AITUS95** [comment]
> > strano, che driver cd stai usando? Non ho problemi a montare .cue .bin in MS-DOS.
> 
> Stavo usando UIDE.SYS da FreeDOS come consigliato nel wiki DosBox-X, ne proverò altri e vedrò cosa succede.

try OAKCDROM.SYS, I use that and I have no problem recognizing the CD, maybe it could be OAKCDROM.SYS causing the freeze of blood?

**Comment by NebularNerd** [comment]
Yup UIDE.SYS was the culprit, I swapped to one I used to use for all my boot disks back in the day and the game plays with CD Audio just fine under MS-DOS 6.22. One minor issue is that I could not change the volume of the CD Music through the in-game menu but not really a big deal.

Try this one....
[IDE-CD.zip](https://github.com/joncampbell123/dosbox-x/files/9615069/IDE-CD.zip)

**Comment by AITUS95** [comment]
> Sì, UIDE.SYS era il colpevole, sono passato a uno che usavo per tutti i miei dischi di avvio in passato e il gioco funziona con CD Audio bene sotto MS-DOS 6.22. Un problema minore è che non ho potuto modificare il volume del CD Music tramite il menu di gioco, ma non è un grosso problema.
> 
> Prova questo.... [IDE-CD.zip](https://github.com/joncampbell123/dosbox-x/files/9615069/IDE-CD.zip)

fantastic !  so the freeze problem was the ide driver, i will do a test as soon as i get home, i would be curious to know if another ide driver can solve the audio adjustment problem.

**Comment by maron2000** [comment]
@NebularNerd Great! I tried IDE-CD.sys on PC-DOS2000 and was able to start "New game" on Blood ver 1.00.
