### ISSUE TITLE
Pentium Pro Issues

### ISSUE THREAD

**Issue by Alevam-Inc** [joncampbell123/dosbox-x#3758]
### Question

When I chose "Pentium Pro" as the CPU type I get this error message while trying to run Windows98SE:
![Screenshot 2022-09-23 220309](https://user-images.githubusercontent.com/50853470/192081027-7ed39dc4-e632-4811-a5e1-8ece8ebf6bc4.png)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Are you using the Win98 config template from the wiki? If so,did you make any other changes to it other then the CPU type?

**Comment by Alevam-Inc** [comment]
I did increase the system RAM, but reducing it back to 128MB doesn’t help.

**Comment by Alevam-Inc** [comment]
Here is the .conf file if you want to have a look:
[dosbox-x.txt](https://github.com/joncampbell123/dosbox-x/files/9638948/dosbox-x.txt)

**Comment by rderooy** [comment]
I can confirm the issue here. The moment I change `cputype=pentium_mmx` to `cputype=ppro_slow` it shows this error.

Looking online, this seems to be either an APM or ACPI issue, but even with both disabled the issue occurs.

Question. Did you do the installation with it set to ppro_slow, or did you change it afterwards? It could be that you need to install Win98 with it set to ppro_cpu and not change it later.

Also, do you actually need a ppro cpu type? A P2 has the same (and more) instructions.

**Comment by Alevam-Inc** [comment]
I guess I don't NEED a ppro CPU, It's just that I wanted a CPU more powerful than a regular Pentium but the emulator seems to have trouble with MMX instructions.

**Comment by rderooy** [comment]
Unless you need specific CPU instructions, or the program checks for a certain CPU type, there is no need to change to a "faster" cpu. The guest CPU speed is not determined by the CPU type, but rather the cycles setting.

I'm guessing you did not install Win98 with the CPU type set to `ppro_slow` then?

**Comment by Alevam-Inc** [comment]
No, I installed it with the CPU type set to Pentium III.

**Comment by leslietoo** [comment]
I can confirm this problem on my machine.

**Comment by joncampbell123** [comment]
It's entirely possible that Windows 98 SE might install some different files if the install detects a Pentium III than if it detects anything lower.

I also know that error can happen if you installed with NE2000 emulation enabled, then then for some reason, DOSBox-X is not able to provide NE2000 emulation. Switching to wireless 802.11 from Ethernet and running it again, for example.

Windows XP and higher do something similar with the NT kernel at install time based on whether you have a single core or multicore machine, if I recall correctly.

**Comment by joncampbell123** [comment]
Windows 98 is using WRMSR on a register for Pentium Pro not yet implemented by DOSBox-X.

WRMSR on an unsupported register causes a fault exception which apparently Windows 98 does not expect, and therefore the error.

Register 0x8B.

According to the Linux kernel sources, that's an MSR related to processor microcode (MSR_IA32_UCODE_REV).

Pentium II and III emulation already required implementing microcode MSRs (only to ignore them of course) but I wasn't aware Windows did that for the Pentium Pro as well.

**Comment by joncampbell123** [comment]
Latest commit fixes Windows 98 crashes with Pentium Pro.
