### ISSUE TITLE
Mouse problem with Fast Tracker 2.08 and earlier

### ISSUE THREAD

**Issue by nickysn** [joncampbell123/dosbox-x#3775]
I'm using dosbox-x 2022.09.0 with SDL2 under Linux (Fedora 36 x86_64, GNOME & Wayland).

When I start Fast Tracker 2, the mouse cursor in the program doesn't move at all, until I press Ctrl+F10 to enable "Capture Mouse". After that, the cursor moves, but is constrained inside a part of the screen, instead of the entire screen. The problem doesn't appear with Fast Tracker 2.09 and 2.10. However, I want to be able to use earlier versions for testing purposes (I'm working on a tracker, so I want to test for compatibility and quirks on multiple FT2 versions).

Many Fast Tracker versions (2.03 to 2.10) are available here (the files are ft2*.zip):
https://files.scene.org/browse/resources/music/trackers/

**Comment by joncampbell123** [comment]
If a program only reads relative motion, DOSBox-X cannot provide meaningful mouse input until you capture the mouse cursor to the emulator window.

The program in question must ask for absolute mouse position if you want to use it without capturing the mouse to the emulator window.

**Comment by joncampbell123** [comment]
I'm aware some other forks like DOSBox Staging or (I think?) Pure are willing to turn mouse motion across the emulator window into something resembling motion, but it never matches the mouse cursor host to guest and you may often have to repeatedly circle around and move the mouse cursor again and again to do it.

**Comment by joncampbell123** [comment]
To explain the difference, there are interfaces to read absolute mouse position, and interfaces to read relative motion.

DOS programs use a standard interrupt interface INT 33h, which can return absolute mouse position as well as relative motion counters. It also allows installing an interrupt procedure callback which is given the same information.

DOSBox-X, when the cursor is not captured, is designed to provide through INT 33h the absolute mouse position within the emulator window as the absolute position on the DOS screen, where a DOS program can read it. But not all DOS programs read movement using cursor position. Some programs instead read the relative motion counters also provided by INT 33h and do not pay attention to cursor position, even if they then use the relative motion to move the mouse cursor. DOSBox-X cannot map the mouse cursor position in the game to the host cursor if the game is only using relative, and so to avoid surprises, will not report any relative motion until you capture the mouse cursor.

**Comment by joncampbell123** [comment]
Other hardware interfaces including PS/2 mouse, serial mouse, and PC-98 bus mouse emulation also only provide relative motion, and have the same limitations.

**Comment by joncampbell123** [comment]
There is a mouse driver you can install for Windows 3.1 (in the DOSLIB project) that can talk to the DOSBox-X Integration Device and allow you to directly map host cursor to guest (Windows 3.1) cursor without capturing the cursor.

**Comment by grapeli** [comment]
@nickysn 
Such or similar problems are most often caused by SDL2.
With SDL2-git works fine. From this change.
https://github.com/libsdl-org/SDL/commit/ad29875ee692deb9a3517f4d470bde4a83ff76ad

https://user-images.githubusercontent.com/452325/194752643-1f93698b-8c7b-4fd7-8d9b-4dd0dd286b26.mp4

Dosbox-x under wayland has a lot of minor annoying bugs. **I really recommend using Xwayland** in this situation.

**Comment by nickysn** [comment]
I understand that programs that use relative mouse motion need "Capture Mouse" in order to work. I'm fine with that, the real problem is, it still doesn't work with "Capture Mouse" on, the mouse is still confined in an area, it doesn't reach the entire screen. I need to test if SDL-git fixes this issue. Looking at the commit, it looks likely.

**Comment by maron2000** [comment]
Hi, on Windows version, it seems that you can move your mouse wherever you want it to on both 2.08 and 2.10 versions. (You need to "Capture mouse")
Tested on 2022.09.0 x64 VS SDL1 & SDL2.
I know that it's not your case, but just for your reference.

**Comment by grapeli** [comment]
I assure you that sdl2-git works fine with the library.

One more remark.
There is no reference to wayland or pipewire in the source code of dosbox-x itself. If dosbox-x works fine under x11, XWayland, kms, alsa, pulseaudio, jack then the reasons should be looked elsewhere. First in SDL2. It is also best to report bugs to SDL2 developers.

**Comment by joncampbell123** [comment]
I just tested FT203.ZIP on ARM-based Mac OS, seems to work fine here. Cursor is not constrained in any way, once I capture the mouse cursor to enable relative motion. Perhaps this is a window manager issue on Linux?

**Comment by nickysn** [comment]
Yes, it appears to be Wayland & SDL2-related. SDL2 version 2.26.0 appears to fix the issue. After upgrading to Fedora 37 (which includes SDL2 2.26.0), the cursor works fine, when you enable "Capture mouse".
