### ISSUE TITLE
E_Exit Illegal descriptor type 0 for int 8 comes on Duke Nukem Caribbean

### ISSUE THREAD

**Issue by sriramkukillaya** [joncampbell123/dosbox-x#3778]

**Comment by NebularNerd** [comment]
Hi @sriramkukillaya could you close this empty topic as your question was answered in #3779 it will help the devs with housekeeping :)

**Comment by sriramkukillaya** [comment]
Definitely

**Comment by sriramkukillaya** [comment]
Please update the dosbox
