### ISSUE TITLE
Shaders for HX-DOS

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3782]
### Is your feature request related to a problem? Please describe.

no.

### What you want

If possible, I wonder if it is possible to adapt future HX-DOS to be able to use some type of shaders. There is perhaps a certain limit to what kind of shaders you can use in DOS. An EGAfilter shader file is most likely possible, but I think CRT.D3D.br, for example, is unlikely to work.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by BridgeHeadland** [comment]
Why react with thumbs down emoji? Did I say something wrong?

**Comment by joncampbell123** [comment]
Are you aware that HX-DOS runs with absolutely *no* hardware acceleration?

There's no GPU support whatsoever, and therefore, no way to do OpenGL shaders.
