### ISSUE TITLE
Cool World does not start

### ISSUE THREAD

**Issue by grapeli** [joncampbell123/dosbox-x#3789]
### Describe the bug

 Exactly as in the title.

### Steps to reproduce the behaviour

For testing, I used the version downloaded from here.
https://www.old-games.ru/game/download/get.php?fileid=4499&modal=1

### What operating system(s) this bug have occurred on?

not relevant

### What version(s) of DOSBox-X have this bug?

all

### Output log

```text
LOG:    3814585 WARN  FPU:ESC 3:Unhandled group 7 subfunction 7
LOG:    3814587 DEBUG MISC:IO write slow path port=ff data=ca60 iolen=2: device matches=0
LOG:    3814587 DEBUG MISC:IO write slow path port=ff data=60 iolen=1: device matches=0
LOG:    3814587 DEBUG MISC:IO write slow path port=100 data=ca iolen=1: device matches=0
```

### Additional information

Unfortunately, it does not work under any version of dosbox-x.
I also checked it on the 30848ddc version right after adding -daum. Of course, it also doesn't work in dosbox-daum itself.

In the main dosbox branch, the game started running from version 0.70.
Exactly from this change (in the FPU code).
https://github.com/dosbox-staging/dosbox-staging/commit/3500ea88eb54e697b532bbdaf299aeef4a3c6303

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
When running Cool World in dosbox-x with `machine=vgaonly`, these lines are repeated in the log.
```
DEBUG CPU:Illegal GRP4 Call 5
      CPU:Illegal/Unhandled opcode FE6C
ERROR CPU:Illegal Unhandled Interrupt Called 6
```


Under dosbox-svn < [@2644](https://sourceforge.net/p/dosbox/code-0/2644) (0.65) Cool World also fails to start and its logs are very similar.
```
CPU:Illegal/Unhandled opcode F..
CPU:Illegal Unhandled Interrupt Called 6
```

This patch [@2644](https://sourceforge.net/p/dosbox/code-0/2644) does not seem to be fully integrated into dosbox-daum, and dosbox-x still inherits these shortcomings.

**Comment by grapeli** [comment]
I ran git bisect incorrectly in dosbox mainline.
This minor code change [@2641](https://sourceforge.net/p/dosbox/code-0/2641) made Cool World launch in dosbox-svn.
Specifically, just that one line in `src/ints/bios.cpp`.
```
// Gameport
config |= 0x1000;
```

Unfortunately, this doesn't work with dosbox-x.

**Comment by Allofich** [comment]
Confirmed. After looking at where DOSBox-X and DOSBox mainline (where the game starts) code diverges, they get a different return value from an INT 11 call to get equipment information from the BIOS.

Mainline return value:
D426 (1101010000100110)

DOSBox-X return value:
5426 (0101010000100110)

The difference is the left-most bit. The `config` you mentioned in bios.cpp is the value being read. Looking around some more I found this difference in how  `config` is set in mainline and DOSBox-X.

Mainline:
```
		// set number of parallel ports
		// if(ppindex == 0) config |= 0x8000; // looks like 0 ports are not specified
		//else if(ppindex == 1) config |= 0x0000;
		if(ppindex == 2) config |= 0x4000;
		else config |= 0xc000;	// 3 ports
```

DOSBox-X:
```
            config |= bios_post_parport_count() << 14;
            config |= bios_post_comport_count() << 9;
```

By default, from looking at the dosbox-x.conf reference, it has 1 parallel port and 2 COM ports configured.
1 << 14 is 0100000000000000.
2 << 9 is   0000010000000000.

After experimenting I found that Cool World seems to need 1100010000000000 to be set here. We can get the left-most 2 bits (like is gotten in mainline with 0xC000) by specifying 3 parallel ports in dosbox-x.conf, like

parallel1 = printer
parallel2 = file file:output1.prn
parallel3 = file file:output2.prn

and we already get the other bit from the default COM port settings.

I don't know what the correct fix is, but having 3 parallel ports will allow the game to start.

**Comment by Allofich** [comment]
The game is checking the return value from INT 11 against D426. If equal, it does some things with ports 70 and 71, which it doesn't do otherwise.

From SVN (Cool World starting)
```
01ED:00000111  int  11                                                EAX:00000000 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
F000:00001120  callback 0009  (Int 11 Equipme                         EAX:00000000 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:000001FA DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:0
F000:00001124  iret                                                   EAX:0000D426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:000001FA DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:0
01ED:00000113  cmp  ax,[0004]                  ds:[0004]=D426         EAX:0000D426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000117  je   0000011C ($+3)             (down)                 EAX:0000D426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000011C  mov  al,30                                             EAX:0000D426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000011E  out  70,al                                             EAX:0000D430 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000120  in   al,71                                             EAX:0000D430 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000122  mov  cl,al                                             EAX:0000D400 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000124  mov  al,31                                             EAX:0000D400 EBX:00000005 ECX:00000000 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000126  out  70,al                                             EAX:0000D431 EBX:00000005 ECX:00000000 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000128  in   al,71                                             EAX:0000D431 EBX:00000005 ECX:00000000 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000012A  mov  ch,al                                             EAX:0000D43C EBX:00000005 ECX:00000000 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000012C  mov  al,15                                             EAX:0000D43C EBX:00000005 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000012E  out  70,al                                             EAX:0000D415 EBX:00000005 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000130  in   al,71                                             EAX:0000D415 EBX:00000005 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000132  mov  bl,al                                             EAX:0000D480 EBX:00000005 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000134  mov  al,16                                             EAX:0000D480 EBX:00000080 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000136  out  70,al                                             EAX:0000D416 EBX:00000080 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000138  in   al,71                                             EAX:0000D416 EBX:00000080 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000013A  mov  bh,al                                             EAX:0000D402 EBX:00000080 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000013C  xor  dl,dl                                             EAX:0000D402 EBX:00000280 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:0000013E  mov  al,12                                             EAX:0000D402 EBX:00000280 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
01ED:00000140  out  70,al                                             EAX:0000D412 EBX:00000280 ECX:00003C00 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:02F1 ES:02F1 FS:0000 GS:0000 SS:034D CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
...
```

From DOSBox-X (when Cool World doesn't start)
```
0823:00000111  int  11                                                EAX:00000000 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:0927 ES:0927 FS:0000 GS:0000 SS:0983 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
F000:0000CB20  callback 0009  (Int 11 Equipment)                         EAX:00000000 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:000001FA DS:0927 ES:0927 FS:0000 GS:0000 SS:0983 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:0
F000:0000CB24  iret                                                   EAX:00005426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:000001FA DS:0927 ES:0927 FS:0000 GS:0000 SS:0983 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:0
0823:00000113  cmp  ax,[0004]                  ds:[0004]=D426         EAX:00005426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:0927 ES:0927 FS:0000 GS:0000 SS:0983 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1
0823:00000117  je   0000011C ($+3)             (no jmp)               EAX:00005426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:0927 ES:0927 FS:0000 GS:0000 SS:0983 CF:1 ZF:0 SF:1 OF:1 AF:0 PF:1 IF:1
0823:00000119  jmp  000001B0 ($+94)            (down)                 EAX:00005426 EBX:00000005 ECX:00000008 EDX:00000000 ESI:00000112 EDI:00000568 EBP:00000478 ESP:00000200 DS:0927 ES:0927 FS:0000 GS:0000 SS:0983 CF:1 ZF:0 SF:1 OF:1 AF:0 PF:1 IF:1
```
(port 70 and 71 instructions jumped over)

**Comment by maron2000** [comment]
Not about Cool World but I was wondering if we should set bit 0 to 1 since Dosbox-X always have drive A as floppy.

**Comment by Allofich** [comment]
I tried running the Cool World executable from the above link in 86Box (within real MS-DOS on a virtual disk) and it fails to start with "Divide overflow," whether I configure it to have 3 parallel ports and 2 COM ports or not.

I also found this in the Cool World readme file.

```
 Changing your System :
 ----------------------

 Due to the complex nature of the file system used in Cool World, it may no
 longer function correctly if any major hardware attributes of your PC change
 in any way (eg adding extra RAM or an additional Hard Disk).  If this is the
 case then you must re-install Cool World from the origional floppy disks.
 ```
 
This seems to imply that the game somehow configures itself to whatever the machine configuration at the time of installation. I found a couple PC floppy images of the Cool World installation disks online and tried installing them in 86Box. With one set installation failed at the very end (this is noted by the uploader, supposedly because of missing copy protection). The files are in the Cool World folder but the executable doesn't run. The other set, though, successfully installed, and this Cool World executable ran successfully in 86Box.

The Cool World installation consists of just a few files:
COOLWRLD.EXE
READ.ME
WIPECOOL.EXE (uninstall program)

and a COOLWRLD.BAT file that runs the executable as COOLWRLD.EXE %1 %2 %3 %4 %5, but whether you use this or just launch COOLWRLD.EXE directly doesn't seem to affect whether it starts or not.

Comparing  COOLWRLD.EXE from the 3 installations (the one from the link above, the one from the failed installation, and the one from the successful installation), they are identical except for some data at the end of the file (missing entirely in the failed installation file), so it looks like this data at the end of the COOLWRLD.EXE affects whether it runs or not.

Next I'm going to try installing from the disk images in DOSBox-X.

**Comment by grapeli** [comment]
I also tried installing from floppy images. The installation always completed with an error message. From what I read [here](https://www.vogons.org/viewtopic.php?t=48989), there is a copy protection applied there.

>@ripsaw8080
>"Fatal Error FF44" is physical copy protection. Same kind of protection used on a few other Ocean titles: the installed >game executable will not work until it is "branded" by the installer, which doesn't happen if the installer is not satisfied >with the original disk.

Under dosbox-svn, cool world does not start with this configuration.
```
[serial]
serial1=dummy
serial2=dummy
serial3=dummy
```
Under dosbox-x, disabling com ports and parallel doesn't change anything.
`dosbox-x -set parallel1=disabled -set printer=false -set serial1=disabled -set serial2=disabled`

**Comment by Allofich** [comment]
The same disk image set also works in DOSBox-X (no need to add parallel ports or anything) and the installation produced a COOLWRLD.EXE unique from the other 3.

I checked the return value it's comparing against with the INT 11 call, and it's comparing against 5427 now.

So, it looks to me like there is not an issue with DOSBox-X here, the problem is that Cool World creates its executable file at the time of installation according to the system configuration of the computer it is being installed on. Probably the linked Cool World download was from an installation on a computer that produced D426 in its INT 11 call, and so it only runs if DOSBox or DOSBox-X also returns that value.

**Comment by Allofich** [comment]
@grapeli, one set of images fails on installation, but there is another one that is successful. https://archive.org/details/002687-CoolWorld Please try the other one.

Even though this one also says the copy protection is missing, it installs successfully, unlike the other.

**Comment by grapeli** [comment]
@Allofich 
I confirm. With these installation floppy disks, Cool World will start up and run fine in DOSBox-X (with the default configuration).

Thanks for the investigation that cleared up and solved this whole problem.

**Comment by Allofich** [comment]
> Not about Cool World but I was wondering if we should set bit 0 to 1 since Dosbox-X always have drive A as floppy.

I just did some testing with this, again with 86Box (since it lets me use real MS-DOS and real BIOS code, in this case a 1992 AMIBIOS).

The results I got don't seem to match online documentation of Int 11, though. Nor do they match DOSBox-X.

Online documentation of Int 11 (http://www.ctyme.com/intr/rb-0575.htm) says
```
Bit(s)  Description
0      floppy disk(s) installed (number specified by bits 7-6)
...
7-6    number of floppies installed less 1 (if bit 0 set) 
```

Same here (https://stanislavs.org/helppc/int_11.html)

```
on return:
	AX contains the following bit flags:

	|F|E|D|C|B|A|9|8|7|6|5|4|3|2|1|0|  AX
	 | | | | | | | | | | | | | | | `---- IPL diskette installed
	 | | | | | | | | | | | | | | `----- math coprocessor
	 | | | | | | | | | | | | `-------- old PC system board RAM < 256K
	 | | | | | | | | | | | | | `----- pointing device installed (PS/2)
	 | | | | | | | | | | | | `------ not used on PS/2
	 | | | | | | | | | | `--------- initial video mode
	 | | | | | | | | `------------ # of diskette drives, less 1
	 | | | | | | | `------------- 0 if DMA installed
	 | | | | `------------------ number of serial ports
	 | | | `------------------- game adapter installed
	 | | `-------------------- unused, internal modem (PS/2)
	 `----------------------- number of printer ports
...
	- bits 7 & 6,  number of disk drives attached, when bit 0=1
	    00 - 1 drive	     01 - 2 drives
	    10 - 3 drive	     11 - 4 drives
```

What I got in testing though was:
Bit 0 is always 1 (even if all floppies are disabled in the BIOS setup screen and all floppies removed in the emulator configuration)
Bit 6 is 0 until you have at least 2 floppies physically present (enabled in the emulator configuration) and the BIOS is set up to detect at least 1 floppy, at which point Bit 6 becomes 1.
Bit 6 is still 1 even if you have 2 floppies physically present and 2 set up in the BIOS, or if you have 3 floppies physically present and 2 configured in the BIOS (the BIOS only allows up to 2).
Bit 7 is always 0.

My testing method was to check the output of int 11 with "debug" like so (my input in bold):

**debug**
-**a**
1770:0100 **int 11**
1770:0102 **(pressed enter for an empty line)**
-**p =0100 1**

and check the contents of AX.

Not sure what to do, though. Why doesn't the output match the online documentation?

**Comment by Allofich** [comment]
I assume that, if the BIOS supported more than 2 floppies, bit 7 would also come into play. Bits 6 and 7 would then mean "Number of floppy drives physically connected and set up in the BIOS, minus 1".
Maybe bit 0 actually just means "supports floppy drives"?

I'll try testing a different BIOS.

**Comment by Allofich** [comment]
Tried a 1993 Award BIOS, with the same results. I guess I'll go ahead and make a new issue for this.

**Comment by Allofich** [comment]
Another source
http://www.bioscentral.com/misc/bda.htm
says

Bit 7-6 indicate the number of floppy drives installed
0b = 1 floppy drive
1b = 2 floppy drives

which seems to suggest that Bit 7 will always be 0.

**Comment by grapeli** [comment]
Unfortunately, Cool World only starts correctly in DOSBox-X during an installation session.

An attempt to start an already installed game in a new  session DOSBox-X fails.

**Comment by grapeli** [comment]
When the floppy drive is available it starts up.

**Comment by Allofich** [comment]
Similarly, in 86Box, the working installation is giving me "Divide overflow" now. I changed around the 86Box configuration a lot for testing, switching BIOSes and whatnot, but even after returning to what I thought was the earlier configuration, and even with Disk 1 or Disk 2 mounted, it won't run anymore. It seems like Cool World is extremely sensitive to system changes. I wonder if it was meant as an additional copy protection measure. I'm going to try installing it in 86Box again, ending the session, and then playing it again, with no configuration changes.

**Comment by Allofich** [comment]
It works now in 86Box again, even after ending the session and restarting, and even without either of the disks mounted.

I can confirm that DOSBox-X still worked as long as the images were still mounted, but stopped working when they were removed.

It may happen because DOSBox-X dynamically adds or removes drives as you add or remove them, whereas they generally static in a real system (or 86Box, as long as you don't adjust settings), so we have to "recreate the system configuration" of the time of installation by mounting the images again.

**Comment by Allofich** [comment]
More specifically, we just have to have any image mounted in the floppy drive for Cool World to continue working in DOSBox-X.

**Comment by grapeli** [comment]
Any, rather not.
It must be a floppy drive with a capacity like the installation images.
`imgmake disk.img -t fd_720`

**Comment by grapeli** [comment]
The latest changes #3802 in bios.cpp also require the reinstallation of Cool World.
Of course, it is a bit of a pain (just a little), but it is also the same on real hardware (the quote from the READ.ME file confirms this).
