### ISSUE TITLE
Trial of bumping SDL2 library (2.0.9 -> 2.24.1)

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#3792]
### Is your feature request related to a problem? Please describe.

SDL2 library has been updated quite regularly and the difference between those in the DOSBox-X distribution is getting larger.
I tried to bump the source to the latest release to date (2.24.1)
There are slight amendments in the DOSBox-X distribution mostly regarding IME support. I tried to apply it to the latest source as well.

The source can be successfully built for all platforms besides MinGW low-end version.
There are plenty of warnings and errors, and fixing them all may not be practical.

Anyway. I will share my repository and if many people find it beneficial, I would put a PR.
I only tried starting up 64bit Windows build and played some games, but I'd like to ask everyone to try other platforms as well.

My commit: 87857b63c9eabe173ffc347ab7ca3e8ced5e1c9d (Bump to SDL2.24.1)

64bit MinGW build: https://github.com/maron2000/dosbox-x-1/suites/9027282095/artifacts/416604757
64bit VS build: https://github.com/maron2000/dosbox-x-1/suites/9027282104/artifacts/416594723
MacOS(intel) build: https://github.com/maron2000/dosbox-x-1/suites/9027282097/artifacts/416594007
Linux build: https://github.com/maron2000/dosbox-x-1/suites/9027282105/artifacts/416596759

### What you want

A screenshot of VS x64 SDL2 (2.24.1) build, typing some Japanese.
![imeinput_SDL2](https://user-images.githubusercontent.com/68574602/197955432-140301c8-70dc-4dfb-ac81-c95452e4a27a.png)

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

Edit: I updated some codes for Linux and MacOS, and fixed the links accordingly.

**Comment by maron2000** [comment]
I missed updating some codes for Linux (Wayland) and MacOS so I edited my primary post accordingly.
Linux builds seems to work fine as far as I tried on Ubuntu 20.04 LTS.

**Comment by maron2000** [comment]
Forgot to close.
The SDL2 of current code tree is updated.

**Comment by rderooy** [comment]
2.28.5 is the latest SDL2 release ;)

**Comment by maron2000** [comment]
Oh, yes so I closed this 2-year old outdated issue.
The current in-tree code is 2.28.2 so we shouldn't be so much behind.
