### ISSUE TITLE
Getting DOSBox-X to emulate a 'Real Mode' (i.e. 8086) PC with MS-DOS, without that 'Protected Mode' cruft

### ISSUE THREAD

**Issue by gotofan** [joncampbell123/dosbox-x#3793]
### Question

I'm seeking advice on configuring DOSBox-X for realistic emulation of a true 'real mode' only computer (i.e. something akin to a fast IBM PC XT clone w/ 8086 CPU emulation but running at the speed of my host processor, just 1MB system RAM, and no XMS or A20 line), for booting genuine MS-DOS 3.30 in a no-frills environment. I think I've come close, but there are a couple of questions: 

i ) In the dosbox-x.conf file, should any special setting be placed in the [fdc *] and [ide *] sections?

ii) Is there a way of emulating expanded memory, without the need for an i386 CPU and EMM386?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
You should be able to set cputype=8086 to emulate a very fast 8086. It should be able to directly access the first 1MB of memory, and the method of emulation inherited from DOSBox SVN should remap the EMS page region into extended for expanded memory.

**Comment by gotofan** [comment]
> You should be able to set cputype=8086 to emulate a very fast 8086. It should be able to directly access only the first 1MB of memory, and the method of emulation inherited from DOSBox SVN should remap the EMS page region into extended for expanded memory from the otherwise inaccessible extended memory.

That works well for my purpose. I was hesitant at first to choose 8086 core emulation due to that "experimental" warning, but results have been good so far. Thanks again for your help.
