### ISSUE TITLE
Floppy drive return data from Int 11 doesn't match real BIOS output

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#3799]
### Describe the bug

While looking at https://github.com/joncampbell123/dosbox-x/issues/3789, the issue of the return value from Int 11 came up.

Testing using 86Box (MS-DOS 6.22 with an 80386DX and a 1992 AMIBIOS, then a 1993 Award BIOS), the return value for Int 11 doesn't match either DOSBox-X or online documentation for Int 11.

From the linked issue:

The results I got don't seem to match online documentation of Int 11, though. Nor do they match DOSBox-X.

Online documentation of Int 11 (http://www.ctyme.com/intr/rb-0575.htm) says
```
Bit(s)  Description
0      floppy disk(s) installed (number specified by bits 7-6)
...
7-6    number of floppies installed less 1 (if bit 0 set) 
```

Same here (https://stanislavs.org/helppc/int_11.html)

```
on return:
	AX contains the following bit flags:

	|F|E|D|C|B|A|9|8|7|6|5|4|3|2|1|0|  AX
	 | | | | | | | | | | | | | | | `---- IPL diskette installed
	 | | | | | | | | | | | | | | `----- math coprocessor
	 | | | | | | | | | | | | `-------- old PC system board RAM < 256K
	 | | | | | | | | | | | | | `----- pointing device installed (PS/2)
	 | | | | | | | | | | | | `------ not used on PS/2
	 | | | | | | | | | | `--------- initial video mode
	 | | | | | | | | `------------ # of diskette drives, less 1
	 | | | | | | | `------------- 0 if DMA installed
	 | | | | `------------------ number of serial ports
	 | | | `------------------- game adapter installed
	 | | `-------------------- unused, internal modem (PS/2)
	 `----------------------- number of printer ports
...
	- bits 7 & 6,  number of disk drives attached, when bit 0=1
	    00 - 1 drive	     01 - 2 drives
	    10 - 3 drive	     11 - 4 drives
```

What I got in testing though was:
Bit 0 is always 1 (even if all floppies are disabled in the BIOS setup screen and all floppies removed in the emulator configuration)
Bit 6 is 0 until you have at least 2 floppies physically present (enabled in the emulator configuration) and the BIOS is set up to detect at least 1 floppy, at which point Bit 6 becomes 1.
Bit 6 is still 1 even if you have 2 floppies physically present and 2 set up in the BIOS, or if you have 3 floppies physically present and 2 configured in the BIOS (the BIOS only allows up to 2).
Bit 7 is always 0.

### Steps to reproduce the behaviour

Check the output of int 11 with "debug" like so (input in bold):

**debug**
-**a**
1770:0100 **int 11**
1770:0102 **(press enter for an empty line)**
-**p =0100 1**

and check the contents of AX. For a simple 386DX machine in 86Box I always either got
4421 (0100010000100001)
or
4461 (0100010001100001)

### Expected behavior

Match real BIOS and MS-DOS behavior.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

Probably all of them

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
@Allofich
Thank you for picking up this issue.
According to the IBM Personal System/2 and Personal Computer BIOS Interface Technical Reference (http://bitsavers.trailing-edge.com/pdf/ibm/pc/ps2/PS2_and_PC_BIOS_Interface_Technical_Reference_Apr87.pdf) , the content resembles those of the document you have shown.

On the other hand, according to OADG technical reference, a de facto reference for PC/AT architecture in Japan published in 1992, it says that bit 0 is **always** set to 1, which matches the situation you explained.
(https://archive.org/details/OADGDOSV1992)
So maybe relatively new PCs bit 0 is always 1, and older ones (perhaps late 80s) it depends whether it is really equipped with a floppy drive.

**Comment by Allofich** [comment]
Another discrepancy:

DOSBox-X and mainline always set bit 12 to 1, for the "Gameport". This is supported by http://www.ctyme.com/intr/rb-0575.htm and https://stanislavs.org/helppc/int_11.html, which say this bit means "game port installed" or "game adapter installed".

Another source, http://www.bioscentral.com/misc/bda.htm, though, says this bit is "reserved".

When testing in 86Box, I'm finding this bit to be 0, in both the AMIBIOS and Award BIOS, even when I add a joystick through the emulator configuration (and whether or not I have a real joystick device attached to my computer). There is no BIOS setting I can find for a game port.

> So maybe relatively new PCs bit 0 is always 1, and older ones (perhaps late 80s) it depends whether it is really equipped with a floppy drive.

Maybe so. I think in general DOSBox/DOSBox-X try to emulate a 90s computer by default, so I would think 90s-era BIOS behavior should be preferred, at least as default behavior.

**Comment by maron2000** [comment]
According to the Technical Reference, bit 12 of PC/AT is "NOT USED". (And as you can see, bit 0 is "1").
Older PC (PC/XT and PCjr) bit 12 is defined as "Game I/O attached".
You can find relevant documents here (https://www.pcjs.org/documents/manuals/ibm/).


Cited from IBM 5170(Models 319 and 339) Technical Reference (PC/AT)
![PCAT_EquipmentList](https://user-images.githubusercontent.com/68574602/198914775-eda7836a-ba10-49ef-ad53-15985870739f.png)

Cited from IBM 5160 Technical Reference (PC/XT)
![PCXT_EquipmentList](https://user-images.githubusercontent.com/68574602/198914842-8de422e6-9e97-4d7e-8a43-5bdf5d82bb29.png)

**Comment by Allofich** [comment]
@maron2000 Thank you for the information. It is reassuring to see some backup in documentation for what the test results showed.

Currently, DOSBox-X (and DOSBox mainline) always set bit 12 to 1. The PR I sent removes this, so it will be always be 0 instead. It would be good to improve this to also have it become 1 for XT and PCjr machines (Tandy too?) when Game I/O is attached.

**Comment by Allofich** [comment]
I wonder if the PR will cause any XT or PCjr games that had working joystick input to no longer have it?

**Comment by Allofich** [comment]
https://issuu.com/old-computers/docs/1kprog
This "Tandy 1000 programmer's reference" also says bit 12 is for Game I/O.
![image](https://user-images.githubusercontent.com/19624336/198934891-a8b52254-fdaf-48de-9221-47de3e2090ef.png)

**Comment by Allofich** [comment]
I adjusted the PR to set bit 12 to 1 if a joystick is configured in the .conf file for PCJr and Tandy. I didn't see a way to easily check for PC/XT so that will still have 0. Emulation of PC/XT seems to be spread out among several different settings that emulate aspects of a PC/XT system.

**Comment by Torinde** [comment]
Automating the choice is good, but I hope you also leave a user-adjustable setting in .conf for it (and mention this issue, so people can get the background info/meaning) - it seems there may be some unforeseen edge cases...

**Comment by Allofich** [comment]
If you mean bit 12, the only potential issue I foresee is, if playing a PC/XT game with a joystick, there might be an issue if the game expected bit 12 to be 1, since it was always 1 until now but won't be now (until some manner of detecting that a PC/XT is being emulated can be checked, at which point we can base it off that). 

I don't intend to add a .conf setting, but I do think it is reasonable to wait until after releasing the next version to merge this, if a release is planned soon. If a problem or edge case comes up, I think we should just fix the code for it, or revert this change if necessary until we can work it out, as these changes are very simple.

**Comment by Allofich** [comment]
Although, there is also the question of what, say, PC-98 does. Since bit 12 is "unused" by PC/AT, I suppose a safer approach is to default bit 12 to 1 (same as current behavior) for everything except PCJr and Tandy, which are the only ones with tests so far in my PR.

**Comment by rderooy** [comment]
How about setting bit 12, if the CPU type is 8086? That should cover the original IBM PC and PC XT use cases.

**Comment by Allofich** [comment]
That sounds like a good idea. According to https://en.wikipedia.org/wiki/Tandy_1000, Tandy 1000, which the programmer's guide I linked to above mentioned, was an 8088, so it will also be covered by that. It says "1000 TX" was an 80286, so that will not be covered, but that seems like it may be correct. So I'm thinking, set as 1 or 0 based on presence of a joystick for an 8088/8086, otherwise leave as 0. We could leave it as 1 for "not used" cases like I mentioned above, but then we may never know whether setting it to 0 would be a problem, and it will not be true to hardware for PC/AT. So, let's make it 0 to be true to hardware for PC/AT and see if any problems come up.

Never mind what I said about PC-98 above, that's already separated out from this behavior in the code.

**Comment by Allofich** [comment]
Adjusted the PR. Thanks rderooy.

**Comment by rderooy** [comment]
PCjr was 8088 like the PC and PC XT. Tandy started out as 8088 but there were indeed later model Tandy 1000's that had the 286 (or 386SX). But those had issues with the sound chip IO ports having moved due to those original ports conflicting with IO ports used by the second DMA controller on the IBM AT.

I did not check, but I guess that when you set `machine=tandy`, dosbox simply does not enable the second DMA controller and keeps the sound chip at the original IO ports.

**Comment by Jkapp76** [comment]
> I wonder if the PR will cause any XT or PCjr games that had working joystick input to no longer have it? Probably I should modify the PR to leave the bit as 1 for those systems to prevent that. It could later be improved to include whatever the 0 case is for those systems.

@Allofich I'm wondering if some Xt/PCJr games that never worked with a joystick will now work because of this PR? Castle Wolfenstein is a good example of a PCJr game I've never got a joystick to work with on any DOSBox.

**Comment by Allofich** [comment]
The previous behavior was to always set the game I/O port bit as on. After the PR I sent, it will now will be off if no joystick is attached, or if you are using the IBM AT. So I don't expect any game that didn't work with joystick input to work now, but if there were any problems related to the emulated computer wrongly thinking you have a joystick when you had disabled it, those might be fixed.
