### ISSUE TITLE
Booting real MS-DOS with DOSBox-X: Expanded Memory (EMS) getting interpreted as Extended Memory?

### ISSUE THREAD

**Issue by gotofan** [joncampbell123/dosbox-x#3800]
### Question

I'm attempting a highly specialized configuration of DOSBox-X for compatibility with a select set of programs: Essentially, it's to emulatate a 80286 CPU core, but with the A20 gate permanently disabled (no use for extended memory here, so treating it like an enhanced 8086 for simplicity's sake). The specification also calls for booting into real MS-DOS 5.0 since a QBASIC interpreter might be needed. Others also require the presence of EMS (Expanded Memory services), supposedly enabled by setting 'ems=emsboard' in the configuration file along with 'memsize=2' (1MB base RAM + 1MB EMS). However, when I run the DOS utility MEM, it reports  that I have:
    655360 bytes total conventional memory
    655360 bytes available to MS-DOS
    587600 largest executable program size

   1048576 bytes total contiguous extended memory
   1048576 bytes available contiguous extended memory

So that extra 1MB of memory earmarked for EMS is presented as Extended Memory, which was I'd presumably disabled in config. How can MS-DOS be made to recognize that as extended memory? The idea is not resolution by EMM286 or some like program (if that were the case, I'd have chosen 386 or higher, enabled A20 and loaded the official EMM386); it's to emulate a functional expanded memory board.

------------------------------------------------------------------------------------------------------------------------
My CONFIG.SYS contents:
------------------------------------------------------------------------------------------------------------------------
C:\DOS\SETVER.EXE
FILES=20

------------------------------------------------------------------------------------------------------------------------
My AUOTEXEC.BAT contents:
------------------------------------------------------------------------------------------------------------------------
@ECHO OFF
PROMPT $p$g
PATH C:\DOS
SET TEMP=C:\DOS
C:\DOS\DOSKEY.COM /INSERT

------------------------------------------------------------------------------------------------------------------------
My dosbox-x.conf contents:
------------------------------------------------------------------------------------------------------------------------
[log]
logfile=D:\DOSBox-X\error.txt

[dosbox]
title=MS-DOS
machine=vgaonly
a20=off
memsize=2

[render]
;monochrome_pal=white

[video]
vmemsize=1
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
xms=false
hma=false
ems=emsboard
umb=false
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
core=normal
fpu=false
cycles=max
cputype=286_prefetch
apmbios=false

[voodoo]
voodoo_card=false

[midi]
mpu401=none

[sblaster]
sbtype=none

[speaker]
pcspeaker=true

[ide, primary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[ide, secondary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[ide, tertiary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[ide, quaternary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[ide, quinternary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[ide, sexternary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[ide, septernary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[ide, octernary]
enable                  = true
pnp                     = false
irq                     = 0
io                      = 0
altio                   = 0
int13fakeio             = false
int13fakev86io          = false
enable pio32            = false
ignore pio32            = false
;cd-rom spinup time      = 0
;cd-rom spindown timeout = 0
;cd-rom insertion delay  = 0

[fdc, primary]
enable=true

[render]
scaler=none

[autoexec]
IMGMOUNT C: D:\DOSBox-X\vdds\dos5\msdos5.img -t hdd
BOOT C:

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
EMS emulation as implemented still shares a lot of how DOSBox SVN implements it's emulation, which has always used extended memory even if pretending to be an EMS board.

**Comment by gotofan** [comment]
> EMS emulation as implemented still shares a lot of how DOSBox SVN implements it's emulation, which has always used extended memory even if pretending to be an EMS board.

I see. Thank you for the clarification.
