### ISSUE TITLE
Herules adapter not detected 

### ISSUE THREAD

**Issue by doimus** [joncampbell123/dosbox-x#3806]
### Describe the bug

I'm trying to run a few games in Hercules amber monochrome mode in dosbox-x, with crt shaders and all. Most notably Sierra's Leisure Suit Larry 1, running on AGI interpreter.

The dosbox window starts fine, in monochrome mode, but games refuse to run, failing to find a graphic adapter. 

The same games with the same settings, start and run fine, in hercules monochrome, in Dosbox 0.74.

### Steps to reproduce the behaviour

Enable hercules mode in configuration (settings pasted later) and start the game.

### What operating system(s) this bug have occurred on?

Windows 10 build 19043

### What version(s) of DOSBox-X have this bug?

2022.09.0 64bit SDL2

### Used configuration

```ini
machine = hercules
memsize = 1
doublescan = false
monochrome_pal = amber
cputype = 286
cycles = 1500

#everything else at default
```

### Output log
```
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
      4999       VGA:h total  98 end  80 blank ( 80/ 98) retrace ( 81/ 96)
      4999       VGA:v total 370 end 350 blank (350/370) retrace (336/352)
      4999       VGA:VGA refresh rate is now, 49.816
      4999       VGA:screen: 1.333, scanfield: 1.535, scan: 0.975, vratio: 1.829
      4999       VGA:h total 0.05425 (18.43kHz) blank(0.04429/0.05425) retrace(0.04484/0.05315)
      4999       VGA:v total 0.00000 (infHz) blank(18.98875/20.07382) retrace(18.22920/19.09725)
      4999       VGA:video clock: 16.26MHz mode M_HERC_TEXT
      4999       VGA:640x350, 49.82Hz, 8bpp, screen 1.333
pixratio 1.371, dw false, dh false
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
   1002768       INT10:Set Video Mode 3
   1002768       INT10:Set Video Mode 7
   1002768       MOUSE:New video mode is the same as the old
   1002771       DOSMISC:DOS clipboard device (dummy access) is enabled with the name CLIP$
XMS: 50 handles allocated for use by the DOS environment
   1002771       MISC:UMB assigned region is 0xc800-0xdfff
EMS page frame at 0xe000-0xefff
CPU is 286 or lower, setting EMS emulation to ems=emsboard and disabling VCPI and v86 startup
EMS:Unable to allocate EMS system handle. disabling VCPI
COMMAND.COM env size:             720 bytes
COMMAND.COM environment block:    0x0701 sz=0x002d
COMMAND.COM main body (PSP):      0x072f sz=0x009a
COMMAND.COM stack:                0x0749
   1002771       FILES:file open command 2 file CON
   1002776       FILES:file open command 2 file CON
   1002781       FILES:file open command 2 file CON
   1002786       FILES:file open command 2 file PRN
   1002786       MOUSE:INT 33H emulation enabled
   1337745       FILES:Special file open command 80 file Z:\AUTOEXEC.BAT
   1337745       FILES:Closing file AUTOEXEC.BAT
   1337745       FILES:Special file open command 80 file Z:\AUTOEXEC.BAT
   1337745       FILES:Closing file AUTOEXEC.BAT
   1337984       EXEC:Execute Z:\SYSTEM\mount.COM 0
   1337984       FILES:file open command 0 file Z:\SYSTEM\mount.COM
   1337984       FILES:Closing file MOUNT.COM
   1338554       DOSMISC:DIRCACHE: Set volume label to C_DRIVE
   1338558       FILES:Closing file CON
   1338558       FILES:Closing file CON
   1338558       FILES:Closing file CON
   1338558       FILES:Closing file CON
   1338558       FILES:Closing file LPT1
   1338560       FILES:Special file open command 80 file Z:\AUTOEXEC.BAT
   1338560       FILES:Closing file AUTOEXEC.BAT
   1338640       FILES:Special file open command 80 file Z:\AUTOEXEC.BAT
   1338640       FILES:Closing file AUTOEXEC.BAT
  38082162       FILES:file search attributes FFF7 name "C:\LARRY*.*"
  38451838       FILES:file search attributes FFF7 name "C:\LARRY1"
  53499737       EXEC:Execute sierra.COM 0
  53499737       FILES:file open command 0 file sierra.COM
  53499737       FILES:Closing file LARRY1\SIERRA.COM
  53499827       FILES:file open command 0 file agi
  53500009       FILES:Closing file LARRY1\AGI
  53500032       FILES:file open command 0 file agidata.ovl
  53500052       FILES:Closing file LARRY1\AGIDATA.OVL
  53965904       FILES:Closing file CON
  53965904       FILES:Closing file CON
  53965904       FILES:Closing file CON
  53965904       FILES:Closing file CON
  53965904       FILES:Closing file LPT1
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I don't see any flaws here.
Tested on 2022.09.0 VS x64 SDL1&2.
`dosbox-x.exe -set machine=hercules -set monochrome_pal=amber`
![larry](https://user-images.githubusercontent.com/68574602/199485761-19a2b28f-d5cf-44ee-bf60-3f9e9ad09d2e.png)

**Comment by grapeli** [comment]
It works for me too.

[lsl1-dosbox-x-hercules.webm](https://user-images.githubusercontent.com/452325/199515574-c3646576-fc7c-4db4-a38a-4f8dcaa6033e.webm)

**Comment by rderooy** [comment]
Please make sure your version does not have some files stripped. It was unfortunately not an uncommon practice for people to delete some drivers that they did not need for their setup.

**Comment by doimus** [comment]
I've found the culprit. Obviously, not all settings were at _default_, d'uh.
I've had ```vsyncmode=host``` enabled which I probably misunderstood as not related to the emulated machine, but apparently it changes sync rate in the DOS environment.
And AGI and other software probably uses display sync rate for graphic adapter (auto)detection, hence the errors.

Accidentally, when using ```machine=cga``` AGI defaulted to drawing CGA 16-color composite low res graphics instead of 4-color palette, probably interpreting the 60Hz refresh rate of my laptop's display as a NTSC composite monitor.
Kind of cool, actually.

**Comment by rderooy** [comment]
`machine=cga` will default to displaying composite, for games using. This is not specific to your laptop.

Have a look at the wiki:
https://dosbox-x.com/wiki/Guide%3AVideo-card-support-in-DOSBox%E2%80%90X

**Comment by joncampbell123** [comment]
This Hercules detect issue should be noted in the Wiki that vsyncmode=host might cause problems with some DOS games.
