### ISSUE TITLE
Mystery files that appear in the save folder, and mysteriously disappeared

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3807]
### Question

Just out of the blue, some files appeared in the save folder, in addition to the save files, which allowed me to load what I have saved in Minesweeper in Windows 3.11, which I couldn't do without the mysterious files. And now they are suddenly gone. Strange events, if you ask me. Maybe someone here could tell me what this strange thing was, and what I should do to make them appear again?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by BridgeHeadland** [comment]
[save.zip](https://github.com/joncampbell123/dosbox-x/files/9932240/save.zip)
There they are again, and this time I'm uploading them here so they don't disappear again.
Maybe someone here knows what kind of files there are, and why they appear from time to time? I have almost no idea what I'm doing until they show up.

**Comment by emendelson** [comment]
You can easily find the answer yourself by searching for the filenames in the source code. Hint: look in savestates.cpp.

**Comment by NebularNerd** [comment]
The .sav files are .zip files, all you are seeing is the content of the .sav/.zip file being created in the save folder, these are then added to the .sav/.zip then deleted, evidently if your system is slow enough or the save state large enough you may see these appear while the .sav is being created.

**Comment by BridgeHeadland** [comment]
@NebularNerd I think the pieces are starting to fall into place, if you know what I mean. The only downside now is that after you run DOSBox-X, after you exit it, it's impossible to load what you've saved, or, in the worst case scenario, DOSBox-X crashes, which can easily happen. DOSBox-X can also be exited if someone accidentally restarts or switches off the device - or if the computer shuts down due to lightning.
Now that I've backed up those files (not the save files, but the files I uploaded here yesterday) - sorry if I'm asking silly - I'm wondering if there is any possibility to copy something from something in or from the DOSBox, because to replace/ the old ones in the unidentified files - that is, to copy and paste - so that I can load what I have saved a previous time the DOSBox-X has run? I doubt if it is possible.

**Comment by NebularNerd** [comment]
Save and Load seems to works for me, not heavily tested mind but it functions as advertised.

You can't see the menu clicks in the video just to be awkward, behaves the same regardless of exiting/restarting or simply using Main->Reset Virtual Machine:

https://user-images.githubusercontent.com/8470449/200032462-52427041-7881-4df9-bc99-be5786c5a9c7.mp4

I can't post anything more exciting as everytime the resolution changes any app recording a DosBox window (including DosBox) stops when the resolution changes.

I'm not sure about the rest of your post, are you trying to find out if you can somehow restore a lost save using those files you uploaded? The answer would be no. Looking at your file there is no `MEMORY` file meaning that beyond some basic system stuff the contents of the ram are not present.


![Screenshot 2022-11-04 170555](https://user-images.githubusercontent.com/8470449/200034421-5f843a03-0c1c-46d8-b722-9a308d827524.jpg)


Regarding DosBox crashes and exits corrupting saves, this is by no means unique to this program, everyone everywhere has at some point clicked a button somewhere and bombed out of something, or managed to find a glitch that has lost them work, it's horrible but it happens.

**Comment by BridgeHeadland** [comment]
I understand, but will there be a memory file later one day, if possible?

**Comment by NebularNerd** [comment]
> I understand, but will there be a memory file later one day, if possible?

In the image I pasted above, the `MEMORY` file is there inside the .sav/.zip, the assortment of files you uploaded only had a few files, mainly some config stuff. From testing further I only see some files briefly appear when loading a save state (similar to the ones you posted), never when saving one.

**Comment by NebularNerd** [comment]
Have you tried the whole saving/loading a state again? Does it work or are there still issues? If not please consider closing this to keep the issues board tidy.

**Comment by BridgeHeadland** [comment]
@NebularNerd I now see on the picture that it is a memory file. I misread (which I do very often) and thought that you wrote that there is no memory file, but now I see that you wrote that there is no memory file which means that the contents of ram are not present beyond some basic system stuff, and that I should rather ask if something like that comes instead.
No, I haven't tried the whole saving/loading a state again yet. I have a disease in my brain, which makes my brain tired quickly, which is also the reason why I read incorrectly sometimes, and that I ask strange questions. I'll test out the save/load thing tomorrow when my brain clears. 🙂

**Comment by NebularNerd** [comment]
Just a thought for when you're retesting, make sure when saving the folder has none of the temp files. I have `memsize=63` and it saves near enough instantly for me but on a slower system it might take a few vital seconds more.

If you have Winzip or 7zip installed you can also right click on the .sav and use 'Open Archive' to view the contents and see if you have the same files as mine, every .sav should contain the same files but obviously have different sizes depending on your setup.

**Comment by BridgeHeadland** [comment]
![image](https://user-images.githubusercontent.com/85258509/201202319-48d9ec1a-b39e-46d0-a018-7ba1e0b8a4d6.png)
I have, you see. :)
What else should I do? I still cannot upload what I have saved, even if the files in the save file or the slot are outside, in the save folder. It still crashes, even though the memsize is 63 and I haven't restarted DOSBox-X before loading.

**Comment by NebularNerd** [comment]
To upload a .sav you would need to pop it in a .zip as github only accepts a few file types. Also you would need to supply an exact copy of your used hd image/folder setup as DosBox has to recreate all the exact environment.

From your original post you were trying to save/load states with Win 3.1, was this the same with the attempt you tried again. If so does a more basic test work a bit like the examples I posted. For example just boot up and run a quick `DIR` then save/load that.

**Comment by BridgeHeadland** [comment]
When you say I should do a quick dir before saving, do you mean I should type "DIR" in the command prompt, be it in DOS or CMD for example? I'm taking this very literally, but what do you really mean? I'm not much of a computer expert, you know, at least not a retro computer expert.
When you say that I have to supply an exact copy of my used HD image/folder setup (which I assume also applies to mounted folders in general), as DOSBox has to recreate all the exact environment, I don't have a very good vocabulary, so could you explain it better, or post a video, or a set of pictures here on how to do it?

**Comment by NebularNerd** [comment]
In your original post you mentioned the issue was while trying to play Minesweeper so I'm assuming you were in a Win 3.1 environment. My suggestion was to try some simpler tests forst to see if we can find where you run into the issue. For all tests if exiting then restarting DosBox you should ensure the same commands or .conf file are used so the starting point remains the same.

**Super Basic Test:**
- Start DosBox
- In DosBox run `DIR` so you have something on the screen
- Save State
- Use Main->Reset Virtual Machine *or* `F11+R`
- Once it's restarted Load State, if that works you'll see the previous `DIR` results
- If above works, exit DosBox completely, restart DosBox and try Load State again.

**Game Test**
- Repeat as above using Pinball Mania which we both have from our discussion in the other thread.

**Windows Test**
- Repeat as above but using your Windows environment and Minesweeper as before.

**Potential Issues**
I've not got Windows installed on DosBox yet so I've not tested in that environment but I've found that some games do not like being re-loaded from a state, for example CyberBox in #3780 has really weird file handling and graphical behaviour, try saving/loading states with that and you get garbage.

**Comment by BridgeHeadland** [comment]
Finally I understand. I still hope that the save/load stuff will be heavily improved during a future update of DOSBox-X. The reason I want an advanced and flawless save/load system is because, as you can see, I want to complete certain advanced games that are difficult to complete (get 100% on) otherwise.
I am now closing the thread, we can talk a lot about such things at https://github.com/joncampbell123/dosbox-x/issues/842
