### ISSUE TITLE
unable to compile on debian testing (bookworm)

### ISSUE THREAD

**Issue by sparky4** [joncampbell123/dosbox-x#3813]
`/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h: In function ‘bool RENDER_DrawLine_scanline_cacheHit(const void*)’:
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1431:1: error: inlining failed in call to ‘always_inline’ ‘int _mm_movemask_epi8(__m128i)’: target specific option mismatch
 1431 | _mm_movemask_epi8 (__m128i __A)
      | ^~~~~~~~~~~~~~~~~
In file included from ../../include/logging.h:22,
                 from render.cpp:27:
render.cpp:209:51: note: called from here
  209 |                 if (GCC_UNLIKELY(_mm_movemask_epi8(cmp) != 0xFFFF))
      |                                  ~~~~~~~~~~~~~~~~~^~~~~
../../config.h:343:43: note: in definition of macro ‘GCC_UNLIKELY’
  343 | #define GCC_UNLIKELY(x) __builtin_expect((x),0)
      |                                           ^
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:1345:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_cmpeq_epi32(__m128i, __m128i)’: target specific option mismatch
 1345 | _mm_cmpeq_epi32 (__m128i __A, __m128i __B)
      | ^~~~~~~~~~~~~~~
render.cpp:208:46: note: called from here
  208 |                 __m128i cmp = _mm_cmpeq_epi32(v, c);
      |                               ~~~~~~~~~~~~~~~^~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:701:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_loadu_si128(const __m128i_u*)’: target specific option mismatch
  701 | _mm_loadu_si128 (__m128i_u const *__P)
      | ^~~~~~~~~~~~~~~
render.cpp:207:44: note: called from here
  207 |                 __m128i c = _mm_loadu_si128((const __m128i*)cache);
      |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/i686-linux-gnu/12/include/emmintrin.h:701:1: error: inlining failed in call to ‘always_inline’ ‘__m128i _mm_loadu_si128(const __m128i_u*)’: target specific option mismatch
  701 | _mm_loadu_si128 (__m128i_u const *__P)
      | ^~~~~~~~~~~~~~~
render.cpp:206:44: note: called from here
  206 |                 __m128i v = _mm_loadu_si128((const __m128i*)src);
      |                             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
make[3]: *** [Makefile:437: render.o] Error 1
make[3]: *** Waiting for unfinished jobs....
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
make[3]: Leaving directory '/home/sparky4/p/dosbox-x/src/gui'
make[2]: *** [Makefile:536: all-recursive] Error 1
make[2]: Leaving directory '/home/sparky4/p/dosbox-x/src'
make[1]: *** [Makefile:400: all-recursive] Error 1
make[1]: Leaving directory '/home/sparky4/p/dosbox-x'
make: *** [Makefile:333: all] Error 2
`

**Comment by grapeli** [comment]
**Format it so that a human can read it.** Paste it neatly. It is illegible in this form.

This error message seems to be the most significant:
`target specific option mismatch.`

It is very possible that you are using the compiler flag `-march=native` under virtualbox or some other vm.

`gcc -march=native -Q --help=target`
is different from flags from `cat /proc/cpuinfo`.

**Don't use** `-march=native` in a virtual machine or cloud vm.

**Comment by sparky4** [comment]
hmm i have a 64 bit kernel and the system is 32 bit... hmmm

**Comment by sparky4** [comment]
ill compile on 32 bit kernel

**Comment by sparky4** [comment]
ah so i used the 32bit kernel on the 32bit system and now it works... i got a strange system on my computer. it was an originally a 32 bit install. but later on i installed a 64 bit kernal and i think something is confused

**Comment by grapeli** [comment]
This is a kind of cross compilation.

`uname -m`
architecture is different for
`i386 uname -m`

You have to mark it during the initial configuration stage.
`./configure --host=i686-pc-linux-gnu ...`
There is no exception to dosbox-x.

**Comment by sparky4** [comment]
thanks for the info
