### ISSUE TITLE
32-bit SDL2 get the wrong midi device when configed mididevice=FluidSynth

### ISSUE THREAD

**Issue by leslietoo** [joncampbell123/dosbox-x#3817]
### Describe the bug

set mididevice=FluidSynth (and soundfont) in config file, run 32bit SDL2, then run the menu Sound->Show MIDI device configuration, the UI says MIDI device is Win32 and soundfont is not available. See the picture.

32bit SDL1 and 64bit SDL1&SDL2 have no such problem.

![image_64](https://user-images.githubusercontent.com/9415065/200471181-2137c404-d265-4e6f-bdd9-2e12c1dd604a.png)

### Steps to reproduce the behaviour

1.set mididevice=FluidSynth (and soundfont) in config file
2. run 32bit SDL2
3. run the menu Sound->Show MIDI device configuration, the UI says MIDI device is Win32

### What operating system(s) this bug have occurred on?

Windows 10 Pro 21H1

### What version(s) of DOSBox-X have this bug?

2022.09.0 32BIT SDL2 Visual Studio

### Used configuration

```ini
mididevice = fluidsynth
fluid.soundfont = "C:\DOSBox-X\soundfonts\SGM-v2.01-NicePianosGuitarsBass-V1.2.sf2"
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
I suspect your dosbox-x build does not have fluidsynth built in.

**Comment by NebularNerd** [comment]
Can confirm on a recent commit build, falls back to Win32 on 32bit VS SDL2:
![image](https://user-images.githubusercontent.com/8470449/200547467-d3553757-17ff-47a2-bafe-a5990d0bf7a5.png)

Same commit 32bit VS SDL1 build has Fluidsynth support:
![image](https://user-images.githubusercontent.com/8470449/200547929-e71cb333-1dec-4155-991b-105b253bd572.png)

**Comment by maron2000** [comment]
Try changing `fluid.driver` from `default` to `dsound`.
