### ISSUE TITLE
Something is wrong with the use of the START command. I doubt the TranslateHostPath function.

### ISSUE THREAD

**Issue by darac-10** [joncampbell123/dosbox-x#3820]
### Describe the bug

The problem occurs when the option is turned on:
```
[dos]
starttranspath = true
```

Let's assume that we have a directory on the host computer with two files file1.pdf and file2.pdf.
Inside DOSBox-X, mount the c drive to the directory defined above.
Now we run the command. `start file1.pdf`
The result is quite expected, the file file1.pdf is opened in the pdf browser.

If we now run the `start file2.pdf` command, the result: the file file1.pdf is opened in the pdf browser.
If we now run the `start cmd` command, the result: the file file1.pdf is opened in the pdf browser.

Conclusion:
When using the start command for the first time, the command is well interpreted.
On every other use of the start command, the command line is not properly interpreted and is repeated
the one from the first use.

The described problem is on a Windows-10 (64 bit) host computer, but the same problem manifests itself on
to a linux computer (fedora-36), only there is the `start -open file1.pdf `command.

### Steps to reproduce the behaviour

On the host computer, we have a directory c:\dos in which there are two files file1.pdf and file2.pdf

1. Start dosbox-x
2. make `mount c: c\dos` or if we are on linux `mount c: ~/dos`
3. type: `start file1.pdf` or on linux `start -open file1.pdf`
4. type: `start file2.pdf` or on linux `start -open file2.pdf`

After the second command, the file file1.pdf instead of file2.pdf was opened in the pdf browser.

### Expected behavior

The expected result is that after the second command the file file2.pdf is opened in the pdf browser.

### What operating system(s) this bug have occurred on?

Windows-10 21H2 64-bit, Fedora-36 dosbox-x in flatpak

### What version(s) of DOSBox-X have this bug?

v2022.09.0 

### Used configuration

```ini
[dosbox]
working directory option = autoprompt

[cpu]
cputype = pentium_iii
cycles = max

[sdl]
output = ttf

[ttf]
#winperc = 60
ptsize = 25

[4dos]
rem = This section is the 4DOS.INI file, if you use 4DOS as the command shell

[dos]
keyboardlayout = hr234
startcmd = true
starttranspath = true
ver = 7.1
lfn = true
hard drive data rate limit = 0
floppy drive data rate limit = 0

[config]
# rem: Records comments (remarks).
rem         = This section is DOS's CONFIG.SYS file, not all CONFIG.SYS options supported
COUNTRY     = 38,852
set path    = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL;E:\FPD26;C:\bin;C:\sbin;e:\nc
set prompt  = $P$G
set temp    = 

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount c: ~/.dosemu/drive_c
mount e: ~/oldHome/darko/Projects/DOS -nocachedir -label DOSPRG -o local
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by darac-10** [comment]
**I think I found the solution!**

I assumed that the error occurs in the TranslateHostPath function (dos.cpp).
Through analysis, I confirmed that the wrong result is in the next line
`hostname = ldp->GetHostName(fullname);`
(Since localDrive is used in the example)

So the problem is not in the function TranslateHostPath but in the function **GetHostName (drive_local.cpp)**
```
std::string localDrive::GetHostName(const char * name) {
    char newname[CROSS_LEN];
    strcpy(newname,basedir);
    strcat(newname,name);
    CROSS_FILENAME(newname);
    dirCache.ExpandName(newname);
    const host_cnv_char_t* host_name = CodePageGuestToHost(newname);
    ht_stat_t temp_stat;
    static std::string hostname = host_name != NULL && ht_stat(host_name,&temp_stat)==0 ? newname : "";
    return hostname;
}
```

Upon further analysis, I found that the problem arises because the hostname variable is defined as a static variable, although there is no need.
When I deleted the static everything worked fine!!!

`static std::string hostname = host_name != NULL && ht_stat(host_name,&temp_stat)==0 ? newname : "";`
--->
`std::string hostname = host_name != NULL && ht_stat(host_name,&temp_stat)==0 ? newname : "";`

i compiled the program (linux fedora-36) and everything worked correctly!!!
I am not able to check on other platforms.

Please check this fix and include it in the code.
Thank you.

**Comment by aybe** [comment]
Not sure about the implications of this member made as static but a better fix would be:

```
static std::string hostname;
hostname = host_name != NULL && ht_stat(host_name,&temp_stat)==0 ? newname : "";
```

**Comment by NebularNerd** [comment]
@aybe 
I just tried a test build with your solution and found the same behaviour. VS x64 Win 10 if that make any odds.
https://github.com/NebularNerd/dosbox-x/blob/master/src/dos/drive_local.cpp#L2010

**Comment by aybe** [comment]
That's why I said that I'm not sure about the implications, I haven't stepped through the code.
When looking at it, I assume there was a good reason that it's been made static, i.e. host name does not change, supposedly.
I'm not really versed in C++ but, could it be that `hostname` is never `null` since it's initialized by the runtime?
If it's the case then, shouldn't the check be made against [std::string.empty()](https://cplusplus.com/reference/string/string/empty/) instead of `NULL`?

**Comment by darac-10** [comment]
@aybe 
I agree that your correction proposal is better, because then the hostname variable is still of static std::string type.

Regarding the option to remove the static modifier and the implications for the rest of the code, my opinion is as follows:

A static variable retains its value between two calls to the same function, but in the case of the localDrive::GetHostName function, the last value is not used or checked anywhere (it does not exist on the right side of the expression), but is calculated each time based on the `basedir` and `name` variables. The only place it is used is the return command. Because of this, the meaning of the static variable is lost and it behaves like an ordinary local variable. (on the right side, `hostname` is not checked, but `host_name`, which is another variable)

I can confirm that your correction method is correct.
Tested on Fedora-36 x64, GCC 12.2.1

**Comment by NebularNerd** [comment]
@darac-10 Did you modify anything other than using @aybe's suggested fix? I replaced line 2010 as you can see in my link above and it behaved the same as before the fix. Did I do something wrong or is there a chance that it's a Win/*nix thing?

**Comment by darac-10** [comment]
@NebularNerd No, I didn't change anything other than @aybe's suggestion.

I did not have access to a computer with windows 10 and visual studio. Yesterday I installed visual studio community edition 2022 and downloaded the source from your repository. I opened the solution file vs\dosbox-x.sln and made a win32 build. I started dosbox-x and tried the commands start file1.pdf, start file2.pdf and start cmd. Everything was working properly. I then did an x64 build and everything worked correctly again.

Maybe your settings are different. Maybe you should do a clean project. 
Attempt to make declaration and initialization in the same line in the source file line 2010  `static std::string hostname = ""`

So I can confirm that @aybe's correction method is correct,
Tested on Win10, VS Community Edition 2022, win32 and x64 builds.

**Comment by NebularNerd** [comment]
@darac-10 That got it, changed it so the code was only on one line:
`static std::string hostname; hostname = host_name != NULL && ht_stat(host_name,&temp_stat)==0 ? newname : "";`

It was a new source base to start with but I did a clean/build just for good measure, Windows SDL1 and SDL2 VS x64 builds both behave as they should opening different files.
