### ISSUE TITLE
linear memory version of debugger command SM?

### ISSUE THREAD

**Issue by leslietoo** [joncampbell123/dosbox-x#3826]
### Question

There's a SM command built into the debugger:
    SM <seg> <off> [bytes in hex]               Set memory at <seg>:<off> to byte values given

SM works under real mode apps/games, but it seems not to work under 32bit protected apps/games like in windows98, I tried SM but nothing changed. So maybe we need a linear memory version SM for protected mode?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
"SM" as inherited from DOSBox SVN expects a 16-bit segment:offset. Unless there's any reason not to, it should support protected mode segment:offset as well.

How does "SML" sound for the linear (virtual) flat memory model version?

Understand that the write may fail in protected mode if the debugger attempts a write but the page is marked not present by the guest OS. I'd rather not accidentally cause the debugger to resume execution just for a page fault so it needs to fail that way. However perhaps there should be a debugger command that explicitly touches a guest page with the expectation of resuming execution for guest page faults.

**Comment by joncampbell123** [comment]
By the way DOSBox-X development should allow you to use the register names in the SM command instead of typing in the hex value manually.

For example:

SM DS:SI 40 20 80

**Comment by joncampbell123** [comment]
Latest commit adds a "SMV" command, enjoy!
