### ISSUE TITLE
Umlaute (öäü) aren't correctly read from the config file

### ISSUE THREAD

**Issue by Commatch** [joncampbell123/dosbox-x#3836]
### Describe the bug

Hello,

I got an issue with the German umlaute (öäü)!
The autoexec section of my config file contains a command that should change into the Win95 autostart folder.
In the German Win95 version, the path to the autostart folder looks like this: "c:\windows\startmenü\programme\autostart"
That "ü" there in "startmenü" makes some trouble!
I can execute the command just fine by typing. But when Dosbox-X is supposed to read the command from the config file the ü gets jumbled up!
I tried both with Visual Studio SDL1 & SDL2 builds. 

### Steps to reproduce the behaviour

1. create a folder called öäü (let's say C:\Test\öäü)
2. then create a config file with the following commands in the autoexec section:
mount c c:\Test
c:
cd öäü
3. Load the configuration file
4. Study the results!

For me, it looks like this:
![command_000](https://user-images.githubusercontent.com/77196566/202867032-803b1b82-666c-4186-9dcf-15d2fad81425.png)

### Expected behavior

I expected that that the umlaute (öäü) I wrote into the configuration file would be correctly read by Dosbox-X.

### What operating system(s) this bug have occurred on?

Windows 10 Pro 21H2

### What version(s) of DOSBox-X have this bug?

2022.09.0 64-bit Visual Studio SDL1, SDL2

### Used configuration

```ini
[autoexec]
mount c "c:\Test\"
c:
cd öäü

[sdl]
autolock=true
convertdrivefat=true

[dosbox]
title=Windows 95 OSR2.5
memsize=64

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
# Set 'ver=7.1' if using Win95 OSR2 (95B) or later
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0
#keyboardlayout=de129

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by emendelson** [comment]
You will need to create the configuration file in a DOS text editor, not in Windows Notepad. Also, you can experiment with editor programs that can save text files in codepage 850. When I created that config file in a DOS editor, it worked perfectly. When I created it in Notepad, I saw the same error that you reported.

**Comment by Commatch** [comment]
I was close to figuring out the ANSI part, but thanks for pointing me towards the codepage bit! I guess I missed that piece of obscure knowledge! I already use Notepad++, it's a great program! Thanks again!
