### ISSUE TITLE
Boot from CD

### ISSUE THREAD

**Issue by poalchTRUNK** [joncampbell123/dosbox-x#3837]
### Question

Hi! I wanted to experiment with DOSBox-X not long ago. I tried to install different Windows versions, and stuck on Vista (TinyVista by eXPerience). I can't boot from a disk. I tried using a method from #182, and https://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox‐X but it throws an error "El Torito bootable floppy not found". How can I fix it?

### Have you checked that no similar question(s) exist?

- [x] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by poalchTRUNK** [comment]
demo video: 

https://user-images.githubusercontent.com/110284837/202868547-c752dbcc-f407-42d5-97b0-5c520d2ac448.mp4

**Comment by rderooy** [comment]
Are you trying to boot Windows Vista in DOSBox-X? That is not supported. Try something more realistic, such as Windows 98.

Regarding El Torito. DOSBox-X supports only **one** CD boot method, namely El Torito boot floppy emulation, as used by **some** Windows 95/98/ME CD versions.

**Comment by poalchTRUNK** [comment]
oh, thanks!
