### ISSUE TITLE
FluidSynth requires "fluid.driver = dsound"

### ISSUE THREAD

**Issue by EatWork** [joncampbell123/dosbox-x#3849]
### Describe the bug

It seems that for at least the SDL2 version of the lastest DOSBox-X the fluidsynth default audio driver setting does not target dsound as is described on https://dosbox-x.com/wiki/Guide%3ASetting-up-MIDI-in-DOSBox%E2%80%90X

With the following configuration I cannot get it to work:
mididevice              = fluidsynth
fluid.soundfont       = "D:\DOSBox\S\MIDI\FLUID\ROLAND.sf2"

Relevant logging output for the above config is:
MIDI:fluidsynth: Can't create audio driver
MIDI:Cannot open device:fluidsynth with config:. Finding default handler.
MIDI:Opened device:win32

Changing the config to include forcing the fluid driver to dsound:
mididevice              = fluidsynth
fluid.driver              = dsound
fluid.soundfont       = "D:\DOSBox\S\MIDI\FLUID\ROLAND.sf2"

Relevant logging output for the above config is:
MIDI:fluidsynth: Loaded SoundFont: D:\DOSBox\S\MIDI\FLUID\ROLAND.sf2
MIDI:Opened device:fluidsynth

### Steps to reproduce the behaviour

Set fluid.driver = default or uncomment the option to get the "Can't create audio driver".

### Expected behavior

fluid.driver = default under Windows should target the dsound driver, just like manual explains.

### What operating system(s) this bug have occurred on?

Windows 10 22H2 x64

### What version(s) of DOSBox-X have this bug?

2022.09.1 (32-bit SDL2)

### Used configuration

```ini
mididevice              = fluidsynth
#fluid.driver              = dsound
fluid.soundfont       = "D:\DOSBox\S\MIDI\FLUID\ROLAND.sf2"
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
This has been already reported in #3817 and fixed.
Try the nightly build.

**Comment by EatWork** [comment]
Checked out latest the nightly where FluidSynth works without the driver=dsound requirement. Also tried one of those nightlies before actually, but I think that was from like 1 or 2 days before this fix was introduced.

Anyway...closing.
