### ISSUE TITLE
Latest Build: Can't find the conf file anymore nor my current one works.

### ISSUE THREAD

**Issue by Yui12** [joncampbell123/dosbox-x#386]
I can't find it anywhere on the PC in this version. No longer in app data either.  Windows 7 by the way.

**Comment by joncampbell123** [comment]
It doesn't write one unless you ask it to.

To write a default:

config -wc dosbox.conf

To write ALL options:

config -all -wc dosbox.conf

**Comment by Yui12** [comment]
Oh it does work. I tired it earlier and it didn't work, I did something wrong then. Thanks for the quick reply.
