### ISSUE TITLE
DOSBOX-X and Windows 3.11 for Workgroup BUG

### ISSUE THREAD

**Issue by vandenk** [joncampbell123/dosbox-x#387]
Hello,

For you can to reproduce the problems, here are the VMs used.

[1. Version 1 (Using folders for editing)](http://infonetservices02.chez.com/Win311FR.rar)
- Unzip the archive add DosBox-X SDL1 (x64 and x86)
- Test with DosBox x86 SVN Daum (launched in Admin): it works well, winfile starts properly.
- Do the same with DosBox-X : Error opening 2 program groups and if I launch winfile Windows reboot.

[2. Version 2 (Using Disk Images)](http://infonetservices02.chez.com/Win311FR-HDDXn.rar)
- Unzip the archive (DosBox-X x86/x64 SDL1 20171216-0941 is included).
- Test XnView 1.50 (images in D:) with DosBox x86 SVN Daum (on my system it takes 5-6 sec to open each image) made a hard drive test with WinBench96 (3100-3200 on my system).
- Do the same thing with DosBox-X x64: XnView put more than 2min40 sec to open each image ! The WinBench test gives a result of 0.001 !
- Mount an iso image: OK with DosBox x86 SVN Daum, Win3.11 reboot with DosBox-X x64 when trying to access the CD (If you want the CD with DosBox-X change in config.sys:
DEVICEHIGH / L: 2 = C: \ DOS \ oakcdrom.sys / D: IDE-CD by DEVICE = C: \ DOS \ oakcdrom.sys / D: IDE-CD)
- Test with DosBox-x x86, message: PROGRAM application error caused an illegal instruction in module S3TRIO.DRV

**Comment by joncampbell123** [comment]
Can you try with the normal core? You might be using the dynamic core, which has bitrotted since DOSBox-X forked.

**Comment by vandenk** [comment]
I tested with core=normal : it's exactly the same !

**Comment by joncampbell123** [comment]
I'm unpacking your RAR files to a test directory now.

**Comment by joncampbell123** [comment]
I can confirm it's saying (I think, I'm not good with French) that it can't find two group files. Both files it mentions have accents in the filename, which is not base ASCII.

DOSBox-X recently added code to convert filenames from the MS-DOS code page in the guest to unicode in the host, in order to allow the filenames to exist without forcing the host to deal with invalid character encodings.

Rename the two GRP files on your host system to resemble the accented characters the guest expects, and then try again.

**Comment by joncampbell123** [comment]
Your dosbox.conf also shows that "mount c: .\C" is Windows-specific and fails on Linux where the path separator is a forward slash, which is something to probably fix.

**Comment by joncampbell123** [comment]
No wonder it's so slow.

DOSBox-X is running at 100 cycles/second. That's not very fast!

DOSBox-X doesn't support the configuration option to run at a percentage of 100% rather than cycle count.

**Comment by joncampbell123** [comment]
![cycles100](https://user-images.githubusercontent.com/6245486/34245103-5572cdea-e5dd-11e7-87e4-bc5d9f8ba7d8.jpg)

**Comment by sikthehedgehog** [comment]
> DOSBox-X is running at 100 cycles/second. That's not very fast!

Wait, are you sure it's *100* cycles? I recall that in vanilla DOSBox the number is actually divided by some value to avoid inserting too many zeroes (to be fair it's pretty confusing though). Did you ever change that?

**Comment by vandenk** [comment]
> I can confirm it's saying (I think, I'm not good with French) that it can't find two group files. Both files it mentions have accents in the filename, which is not base ASCII.
> 
> DOSBox-X recently added code to convert filenames from the MS-DOS code page in the guest to unicode in the host, in order to allow the filenames to exist without forcing the host to deal with invalid character encodings.
> 
> Rename the two GRP files on your host system to resemble the accented characters the guest expects, and then try again.

OK I renamed "DÉMARRAGE.GRP and RÉSEAU.GRP" by "DEMARRAGE.GRP and RESEAU.GRP" then I modified PROGRAM.INI accordingly.
it works with the x64 version both groups open and winfile does not crash anymore.
**But why Accents Works on "Version 2 (Using Disk Images)" ?**

By cons with the x86 version :
![x86error](https://user-images.githubusercontent.com/11425010/34248798-98134148-e637-11e7-8640-44504858d586.jpg)
Same mistake as on "version 2" with DosBox-X x86.


> No wonder it's so slow.
> 
> DOSBox-X is running at 100 cycles/second. That's not very fast!
> 
> DOSBox-X doesn't support the configuration option to run at a percentage of 100% rather than cycle count.

On my system I never have 100 cyc/ms, just max 100% cyc/ms : 
![cycles](https://user-images.githubusercontent.com/11425010/34249018-72e789d2-e638-11e7-837e-6419ba69dcfd.jpg)
However I tested with core=normal + cycles=6000 :
![6000](https://user-images.githubusercontent.com/11425010/34249648-c06b4a48-e63a-11e7-9a05-e83624aa92ab.jpg)
It's worse : 4 minutes 23 seconds to open an image !!

**Comment by joncampbell123** [comment]
I take it you're looking to use the maximum cycles available, rather than fixed?

Try cycles=max

**Comment by joncampbell123** [comment]
Filename code page translation was added for files accessed on your host filesystem through mounting a folder. Code page translation is not used for disk images because there no need to worry about making the filename within the image compatible with your host filesystem.

**Comment by joncampbell123** [comment]
@sikthehedgehog DOSBox and DOSBox-X defines CPU speed in terms of instruction cycles per millisecond (probably added due to the millisecond precision offered by SDL_GetTicks).

**Comment by vandenk** [comment]
I tested with core=normal + cycles=max : it's better (47 seconds) ...
I also tested core=auto + cycles=max : **it's OK 5-6 secondes : perfect !**

Now there is the problem with DOXBOX-X x86, WinBench 96 and the CDROM driver when it is in high memory

**Comment by joncampbell123** [comment]
I'll get to that when I can. Until then, can you tell me what happens if you don't load them into high memory?

**Comment by vandenk** [comment]
OK, thanks !

(On version 2) when you load oakcdrom.sys in high memory (config.sys:
DEVICEHIGH /L:2 =C:\DOS\oakcdrom.sys /D:IDE-CD) if you want to access the CD with DosBox-X Win3.11 reboot instantanly. (But it's OK with SVN Daum)
If I don't load oakcdrom.sys into high memory, trying to access the CD with DosBox-X is OK.

**Comment by joncampbell123** [comment]
Sound like a problem with A20 gate emulation.

DOSBox-X defaults to "fast" emulation (compatible with main DOSBox project).

Try:

[dosbox]
a20=full

**Comment by vandenk** [comment]
Great ! it works !

**Comment by vandenk** [comment]
Hello,

I just tested the latest version (DosBox-X 20171231-032702).
Now the x86 version works perfectly.
But Opengl does not work anymore !
output=opengl
LOG: Output does not support hardware scaling, switching to normal scalers
Switch to openglnb and can not switch to opengl or direct3d (once windows has started)
But if I put output=direct3d I can manually switch to opengl (once windows started) and it works !

On the other hand I always have the same problem of slowness with XnView (even with core = auto + cycles = max or core = normal + cycles = max).
I do not understand why it worked the last time !!
Because even with DosBox-X x64 SDL1 20171216-0941 it does not work anymore !
I do not understand anything !

**Comment by joncampbell123** [comment]
The x86 version works perfectly now because I removed the dynamic core. The dynamic core has not been maintained and it is incompatible with the non-recursive page fault handling in DOSBox-X.

Perhaps Windows updated it's drivers behind your back and broke OpenGL?

**Comment by vandenk** [comment]
> Perhaps Windows updated it's drivers behind your back and broke OpenGL?

No since it works with DosBox-X x64 SDL1 20171216-0941.
Also as I said with the DosBox-X version 20171231-032702 if I put "output=opengl" in the dosbox.conf file,  opengl does not work :
_LOG: Output does not support hardware scaling, switching to normal scalers_
DosBox-X 20171231-032702 switch to openglnb and impossible to switch to opengl or direct3d (once windows has started).
**On the other hand if I put output=direct3d (in dosbox.conf) I can manually switch to opengl (once windows started) and it works !**

**Comment by joncampbell123** [comment]
Please follow the OpenGL issue here: https://github.com/joncampbell123/dosbox-x/issues/436

**Comment by vandenk** [comment]
Hello,

Why did you close this issue ?
I still have 2 unresolved issues with XnView and Winbench ...

Ok for Opengl.

**Comment by joncampbell123** [comment]
I thought you said that renaming the program groups fixed the issue because the filename translation initially made the host name invalid to the guest and that running emulation with a20=full fixed a problem with drivers and software loaded high.

**Comment by vandenk** [comment]
Yes, it's true (Thanks for the reactivity)

But I also said :

- I always have the same problem of slowness with XnView (even with core=auto + cycles=max or core=normal + cycles=max).
I do not understand why it worked the last time !!
Because even with DosBox-X x64 SDL1 20171216-0941 it does not work anymore !
I do not understand anything !
**XnView is about 8 times slower to open an image with Dosbox-x than with Dosbox SVN Daum, why ?**

- **WinBench 96 disk test gives a result of 0.001 (at any setting) with Dosbox-X** whereas with Dosbox SVN it gives this : 
![winbench96](https://user-images.githubusercontent.com/11425010/34497989-ed45051c-efff-11e7-9f93-76938d1008c1.jpg)
With WinBench 95 Dosbox-x and Dosbox SVN give a consistent result (a little bit lower with Dosbox-x)
**Why ?**

**Comment by joncampbell123** [comment]
SVN Daum probably still has the dynamic core. DOSBox-X removed the dynamic core because of changes to overall emulation.

I have no idea what WinBench 96 is looking for to cause a change in score.

**Comment by vandenk** [comment]
> SVN Daum probably still has the dynamic core. DOSBox-X removed the dynamic core because of changes to overall emulation.

OK you're definitely right, I did some tests with SVN Daum :
- core=normal (SVN dosbox.conf) : XnView not working (win32s error)
- core=normal (SDL1 dosbox.conf) : Very very Slow >15min !
- core=dynamic (any dosbox.conf) : 5-6sec
- core=auto (any dosbox.conf) : 5-6sec

But it is penalizing with XnView, I hope that it concerns only some programs.
