### ISSUE TITLE
No new version the last 3 months

### ISSUE THREAD

**Issue by github-fanuser** [joncampbell123/dosbox-x#3870]
### Question

What is going on? Is Dosbox-x no longer maintained? There has not been a new version released is the past 3 months.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by aybe** [comment]
<img width="336" alt="chrome_sgZfrc5nkM" src="https://user-images.githubusercontent.com/1537591/205427330-45c2ce95-592e-4aaa-b361-2561a4c3e09c.png">
