### ISSUE TITLE
File manager dialogs show up empty 

### ISSUE THREAD

**Issue by Paolo86cripple** [joncampbell123/dosbox-x#3873]
### Describe the bug

Dialogs where you choose a file by GUI, such as the configuration directory picking at startup show up completely empty. Thus you are not able to select anything whatsoever via quick launch or any instance which requires you to pick a file via GUI.

Using Arch (EndeavourOS), the build is self compiled 

### Steps to reproduce the behaviour

Starting the program for the first time or going to quick launch

### What operating system(s) this bug have occurred on?

Arch Linux

### What version(s) of DOSBox-X have this bug?

Latest Git 

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I don't see any flaws. Just updated ArchLinux by `pacman -Syuu` so I assume it's the latest version, and built latest commit of DOSBox-X.
![archlinux](https://user-images.githubusercontent.com/68574602/206344771-0995a679-37a5-4877-a607-e11645c17a45.png)

**Comment by Paolo86cripple** [comment]
![dosbox-x](https://user-images.githubusercontent.com/964181/206490871-ae8af8c3-e272-4514-a284-09673a3aa04d.png)
Here's my current situation on startup

**Comment by grapeli** [comment]
Works fine for me on Archlinux too.

![s1](https://user-images.githubusercontent.com/452325/206531845-63f99400-9485-4f70-8710-624938667985.png)


If it does not work, you need to look for the reason in the program used to display the dialogues. What programs are supported can be found in the [source code](https://github.com/joncampbell123/dosbox-x/tree/master/src/libs/tinyfiledialogs). Tinyfiledialogs is a wrapper for other programs.

DOSBox-X is functional without these dialogs

**Comment by maron2000** [comment]
You can try `-defaultdir` option or `-conf` option.
Consult the Wiki page for details.

**Comment by grapeli** [comment]
On unix you need one of the following: applescript, kdialog, zenity, matedialog, shellementary, qarma, yad, python (2 or 3)/tkinter/python-dbus (optional), Xdialog or curses dialogs (opens terminal if running without console).

Tinyfiledialogs has bugs. I checked briefly.
For example, if someone is using [yad](https://github.com/v1cont/yad), in this particular directory selection example, they will only see two buttons to choose from - Cancel and OK.

[Yad](https://github.com/v1cont/yad) does not include options like `--file-selection`.
Currently yad is called like this.
`yad --file-selection --directory --title="Select folder where to run emulation, which will become the DOSBox-X working directory"`
Did not work.

This way it works properly.
`yad --file --directory --title="Select folder where to run emulation, which will become the DOSBox-X working directory"`

**Comment by Paolo86cripple** [comment]
I checked and my system currently  uses Yad. Do I need to install another dialog manager or do I need to include the yad instruction you included via terminal?

**Comment by grapeli** [comment]
> I checked and my system currently uses Yad.

These things must be clearly marked when reporting.

>Do I need to install another dialog manager or do I need to include the yad instruction you included via terminal?

This is a trivial problem.

Yes you can install zenity, kdialog.
You can use yad with this error and in this particular example press Cancel first then Yes.
You can also fix this functioning yad.
As I wrote the error is in tinyfiledialogs. If you want it to be fully functional with dosbox-x you need to fix this bug.
`sed -i 's|yad --file-selection|yad --file|g' src/libs/tinyfiledialogs/tinyfiledialogs.c`
Then re-compile.

These dialog functions are not necessary for dosbox-x to work. Dosbox-x can also run without them.

**Comment by rderooy** [comment]
This should be report upstream, such that it can be fixed there https://sourceforge.net/projects/tinyfiledialogs/

**Comment by grapeli** [comment]
You can fix yad in an already existing dosbox-x binary.

A bit lame, can be improved, but it works.
`hexdump -ve '1/1 "%.2X"' ./dosbox-x | sed "s/796164202D2D66696C652D73656C656374696F6E/796164202D2D66696C6520202020202020202020/g" | xxd -r -p > dosbox-x.patched && mv ./dosbox-x.patched ./dosbox-x ; chmod +x ./dosbox-x
`

**Comment by Paolo86cripple** [comment]
The aforementioned fixworked. Thanks!

**Comment by michaja** [comment]
> You can also fix this functioning yad. As I wrote the error is in tinyfiledialogs. If you want it to be fully functional with dosbox-x you need to fix this bug. `sed -i 's|yad --file-selection|yad --file|g' src/libs/tinyfiledialogs/tinyfiledialogs.c` Then re-compile.

This has been fixed in yad ([v3.11, 2c12fb0](https://sourceforge.net/p/tinyfiledialogs/code/ci/2c12fb0436ebc20a5828e2b3298f9c29320f2dc4/tree/tinyfiledialogs.c?diff=2b4e3ef0f6cac2217af9ec31e323eb262459cd09)), so maybe worth pulling that in.

**Comment by vareille** [comment]
Hi, I've corrected this in tinyfiledialogs v3.12
