### ISSUE TITLE
Support FFmpeg 5.0

### ISSUE THREAD

**Issue by skitt** [joncampbell123/dosbox-x#3874]
### What you want

FFmpeg 5.0 drops support for `avcodec_encode_video2()` function (compare [the 4.4 docs](https://ffmpeg.org/doxygen/4.4/group__lavc__encdec.html) and [the 5.0 docs](https://ffmpeg.org/doxygen/5.0/group__lavc__encdec.html)).

The result is that DOSBox-X can no longer be built with `--enable-avcodec` in a number of distributions, including Fedora 37, the forthcoming Debian 12, and Ubuntu 22.10.

It would be great if DOSBox-X could be adapted to the FFmpeg 5.0 API (which is also supported in earlier versions, since at least 3.1). I might get round to it myself at some point but I can’t promise anything.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Jookia** [comment]
This is already fixed in master

**Comment by skitt** [comment]
So it is, by https://github.com/joncampbell123/dosbox-x/commit/61d554278468f6912bb333675839a8d02574535a, https://github.com/joncampbell123/dosbox-x/commit/81e11c69f6eb8154affeff1027bd50d14b240e28 and the follow-up patches, thanks for the info!
