### ISSUE TITLE
Release schedule question

### ISSUE THREAD

**Issue by Paolo86cripple** [joncampbell123/dosbox-x#3875]
### Question

It's been three whole months since the last stable release, while the project is being worked on, are there any issues with it?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
You may want to post such questions to the "Discussions" Tab.

**Comment by aybe** [comment]
#3822
