### ISSUE TITLE
Accumulated sum is wrong

### ISSUE THREAD

**Issue by alfonsec** [joncampbell123/dosbox-x#3880]
### Describe the bug

A DOS application I have been using for years worked in DOSBox, but does not work correctly in DOSBox-X.
The program shows (among others) two columns, one of which is made of numbers, and the second is the accumulated sum of the first.  With DOSBox 0.74, the second column is correct; with DOSBox-X (last version), the second column is all zeros.

I'm providing a screen image showing the difference between DOSBox and DOSBox-X for the same program. If requested, I can provide the executable program and the source (which was written in C).

![IssueDOSBox-X](https://user-images.githubusercontent.com/13149344/206546306-f8d9eb32-e4ef-4184-9313-b7d3621a2a7e.jpg)

### Steps to reproduce the behaviour

1. Put the four attached files in a folder.
2. In the folder, execute CONTABLE.EXE under DOSBox or DOSBox-X
3. Go down uno position, to "Informe Cuenta"
4. Type "telefono"
5. Compare result under DOSBox and DOSBox-X

I cannot upload the files, because executable files are not allowed.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2022-09-0

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by aybe** [comment]
zip all the files so you can upload it.

**Comment by alfonsec** [comment]
Enclosed please find the zipped files.
[Contab.zip](https://github.com/joncampbell123/dosbox-x/files/10189548/Contab.zip)

**Comment by rderooy** [comment]
Does it use the FPU? If so, please try the windows mingw version.

Or if the program supports CPUs without FPU unit, try to disable the FPU in the config file.

**Comment by alfonsec** [comment]
Thank you! I've downloaded the mingw version and now it works.
