### ISSUE TITLE
Blank screen when screen (or remote desktop session) is 15/16/24bpp

### ISSUE THREAD

**Issue by roytam1** [joncampbell123/dosbox-x#389]
Tried every output (including surface/opengl) but all blank screen in both SDL and SDL2 binary.
Vanilla DOSBox has no such issue.

Rev: 862072d2, VS2013 self compile ( @joncampbell123 please update vcxproj files when you separating functions into new C/CPP files! )

**Comment by joncampbell123** [comment]
Understood. However I can only do one side at a time. First on Linux, then later reboot to Windows to update the VS2017.

**Comment by joncampbell123** [comment]
I'm fixing up the VS2017 files now.

**Comment by joncampbell123** [comment]
Pull from the latest commit to the "develop" branch, I just fixed the VS2017 files.

**Comment by roytam1** [comment]
@joncampbell123 In PC-98 mode in RDP session, red color is missing (so white becomes cyan for example)

![rdp](https://user-images.githubusercontent.com/1192577/34475291-a80541fe-efc5-11e7-8c6c-8c5191635071.png)

**Comment by joncampbell123** [comment]
That can happen if SDL is unable to tell DOSBox-X what your bit depth and RGB bit field arrangement is. This visual error can happen if your RDP session is 32-bit RGB, and DOSBox-X is rendering ARGB when the RDP session is using BGRA.

**Comment by roytam1** [comment]
Just checked my RDP config.
in 32bpp, it display normally on both PC98 mode and non-PC98 mode.
in 24bpp/16bpp, problem occurs.

**Comment by joncampbell123** [comment]
24bpp is confirmed not to show anything.

However, DOSBox and DOSBox-X do not support 24bpp SDL output anyway.

**Comment by joncampbell123** [comment]
However 15/16bpp also don't show anything.

The odd thing is that the DOSBox-X window will show the mapper UI and configuration UI, just not the emulator screen.

**Comment by joncampbell123** [comment]
Hold on, the same thing happens if you run it on Windows 7 with the desktop bit depth set to 16-bit RGB as well, without remote desktop.

**Comment by joncampbell123** [comment]
Same problem, if I configure Linux X11 to run in 16-bit RGB mode as well.

**Comment by joncampbell123** [comment]
I just noticed that Windows 7 remote desktop is using 16bpp even if I ask for 24bpp, which might be related.

I *almost* have this fixed, but SDL seems to be messing up 32bpp to 16bpp conversion when the screen (usually) is the 5:6:5 RGB format.

**Comment by joncampbell123** [comment]
Yes! Whoever wrote the PMAKE() macro in render_scalers.cpp / render_template.h made an off-by-one bit shift mistake in the 32bpp -> 16bpp 5:6:5 RGB conversion code.

Fixing it now allows proper display when the display is 16bpp.

**Comment by joncampbell123** [comment]
So far, so good.

DOSBox-X now renders correctly IF you use a 16-bit color mode. The SDL 1.x build still makes incorrect colors if you use the 15-color mode through RDP, however I haven't seen any desktop use the 5:5:5 RGB format in a while nor is that format as common as 5:6:5 RGB, so I consider this fixed.

**Comment by roytam1** [comment]
Fix confirmed, thanks!

**Comment by joncampbell123** [comment]
Yes! I forgot to mention here that I fixed the display issues with 15-bit color.
