### ISSUE TITLE
Can't delete directory on dosbox x

### ISSUE THREAD

**Issue by TheSenate13** [joncampbell123/dosbox-x#3894]
### Question

I can access directories and create them, but I can't delete them.
Any idea why this is happening? 
![Screenshot 2022-12-23 003154](https://user-images.githubusercontent.com/121275756/209271288-a2e8df73-6b20-4975-9bc7-8c4c680e5799.png)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
DOS commands for deleting directories are `rd` and `deltree`.
`del` is for deleting files.

**Comment by maron2000** [comment]
You can't delete directories with `DEL` command. You have to use `rmdir`.
Not only DOSBox-X but it is the same on Command Prompt on Windows.
And you have to be sure that the directory you want to delete is totally empty.

**Comment by TheSenate13** [comment]
> You can't delete directories with `DEL` command. You have to use `rmdir`. Not only DOSBox-X but it is the same on Command Prompt on Windows. And you have to be sure that the directory you want to delete is totally empty.

Thank you so much

**Comment by TheSenate13** [comment]
> DOS commands for deleting directories are `rd` and `deltree`. `del` is for deleting files.

Thank you so much

**Comment by joeskeen** [comment]
Am I missing something then?
![image](https://github.com/user-attachments/assets/31c748a6-b96a-447a-af0b-7ebe1b8f313b)

**Comment by rderooy** [comment]
> Am I missing something then?

Are you sure the directory is indeed empty, there may be hidden files. Check with `dir /ah`

![image](https://github.com/user-attachments/assets/9afb1a5f-cb09-4935-b26f-68768d4e09c6)

**Comment by maron2000** [comment]
Working fine here as well.
RD command can delete it the directory when it is empty.

![image](https://github.com/user-attachments/assets/07d63bd4-3588-44aa-b95d-d3777cad5c4d)

**Comment by joeskeen** [comment]
Yeah, I think my issue was the hidden files. I've grown so accustomed to Linux filesystems that I forgot how painful it was to delete a folder in DOS... thanks.
