### ISSUE TITLE
Having override configuration from a common configuration file

### ISSUE THREAD

**Issue by breadncup** [joncampbell123/dosbox-x#3901]
### Is your feature request related to a problem? Please describe.

It is cumbersome when I create all the configuration files for each game.

If I could have a common configuration file and run with a delta only, it would make life easier.

### What you want

For example,

* dosbox-common.conf
```
[log]
logfile=log.txt

[sdl]
output=overlay
autolock=true
mouse_emulation=never
mapperfile=dosbox-common.map
```

* dosbox-specific-game.conf
```
[include]
include=~/dataconfig/dosbox-common.conf

[sdl]
mapperfile=dosbox-this-game.map

[autoexec]
imgmount 1 ABC.FDI -t floppy -fs none
boot -l a

```

Something like that.

So, most of the common part is in the common.conf and I only write a delta for a specific game.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
You can already do this by specifying multiple `-conf` options on the commandline.

**Comment by NebularNerd** [comment]
You can also specify a fairly wide range of options inside DosBox-X through the `config -set` command, great for making batch files up without having loads of .conf files.

Examples:
`config -set "cycles=306000"`
`config -set "output=opengl"`
`config -set "scaler=hq3x forced"`

Some things that you cannot set internally without a restart are `machine`, `memsize` or switching from SB to GUS (you can but it seems to be a bit hit and miss)

**Comment by breadncup** [comment]
> You can already do this by specifying multiple `-conf` options on the commandline.

Thanks, so, it looks like the later configuration would override the backward configuration.

For example,
```
dosbox-x -conf CONFIG1.conf -conf CONFIG2.confg
```
If I run it like the above, the CONFIG2 will override the CONFIG1.

This works, too.

Thanks,


> You can also specify a fairly wide range of options inside DosBox-X through the `config -set` command, great for making batch files up without having loads of .conf files.
> 
> Examples: `config -set "cycles=306000"` `config -set "output=opengl"` `config -set "scaler=hq3x forced"`
> 
> Some things that you cannot set internally without a restart are `machine`, `memsize` or switching from SB to GUS (you can but it seems to be a bit hit and miss)

It is good to know that I can override in the dosbox. Thank you!
