### ISSUE TITLE
[macOS] Image covers one fourth of the window only

### ISSUE THREAD

**Issue by CarterLi** [joncampbell123/dosbox-x#3906]
### Describe the bug

<img width="720" alt="image" src="https://user-images.githubusercontent.com/6134068/209893421-febb94b9-7df2-4a17-9284-202c86e4cda2.png">

### Steps to reproduce the behaviour

1. Open dosbox-x

### What operating system(s) this bug have occurred on?

macOS 13.1

### What version(s) of DOSBox-X have this bug?

0.83.9 SDL2 arm64

### Additional information

Seems to be a regression on 0.83.9. It didn't happen on the previous version

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Try to change the `dpi aware =` option in the dosbox-x config file.

**Comment by CarterLi** [comment]
Where can I find the config file?

**Comment by rderooy** [comment]
In dosbox-x type `config -wcd` and it will create a default config file and give you the path.

**Comment by CarterLi** [comment]
It was `auto`. I tried `true`, `false`, `0` and `1` and none of them worked.

**Comment by emendelson** [comment]
Right-click on the app; choose Show Package Contents. Edit info.plist. If it opens in Xcode, change High Resolution Capable from Yes to No. If it opens in a text editor change the one under NSHighResolutionCapable form YES to NO.

I suggested ages ago that this should be the default in the app, but it hasn't happened yet.

**Comment by CarterLi** [comment]
~~It does resolve the issue, but making app not high resolution capable makes the window blurring.~~

~~I have said that It worked for the old (2022.09.0) version, but not the latest version~~

---

I knew what was wrong. That was because the latest version [DOSBox-X 2022.12.26 2022-12-26 19:55](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2022.12.26) contains an very old dosbox-x version [dosbox-x-macosx-arm64-20201226002957.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-macosx-arm64-20201226002957.zip)

Let's wait for https://github.com/joncampbell123/dosbox-x/issues/3903 to be fixed

**Comment by Dobby233Liu** [comment]
> Let's wait for #3903 to be fixed

I'd assume the official releases should be unaffected, since they're built with the in-tree SDL2 fork with IME enhancements. Probably the wrong file was uploaded.

**Comment by CarterLi** [comment]
Filed a new issue: https://github.com/joncampbell123/dosbox-x/issues/3909
