### ISSUE TITLE
 dosbox-x-mingw-win32-lowend-20221227040427.zip does not have the debugger

### ISSUE THREAD

**Issue by gfernval** [joncampbell123/dosbox-x#3908]
### Describe the bug

 dosbox-x-mingw-win32-lowend-20221227040427.zip does not have the debugger, this version is the only that works in Windows XP

### Steps to reproduce the behaviour

Run dosbox-x.exe in Windows XP, does not have the debugger

### What operating system(s) this bug have occurred on?

Windows XP

### What version(s) of DOSBox-X have this bug?

20221227040427

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
This is not a bug.
You need to use Visual Studio win32 build if you want to use the debug options.
Consult the INSTALL page below for details.
https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md

**Comment by gfernval** [comment]
The Visual Studio win32 build does not work in Windows XP. I have tested all the builds, the only that works in Windows XP is mingw lowend builds.

**Comment by maron2000** [comment]
Didn't know that. So it will be impossible to use the debugger for the time being, since it is not supported in MinGW builds.

**Comment by maron2000** [comment]
Maybe installing Visual Studio version via installer still work. 
Sorry if you have already tried.
The link below are some information mentioned a year ago.
https://github.com/joncampbell123/dosbox-x/issues/2879#issuecomment-958488113
