### ISSUE TITLE
Wrong file was uploaded for macOS arm64 in the latest release (2022.12.26)

### ISSUE THREAD

**Issue by CarterLi** [joncampbell123/dosbox-x#3909]
### Describe the bug

<img width="863" alt="image" src="https://user-images.githubusercontent.com/6134068/210030030-9597ddb7-86db-4ecd-ae1d-11c53b139f65.png">

### Steps to reproduce the behaviour

N/A

### Expected behavior

`dosbox-x-macosx-arm64-20221226190321.zip` should be uploaded as [dosbox-x-macosx-x86_64-20221226190321.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-macosx-x86_64-20221226190321.zip)

### What operating system(s) this bug have occurred on?

N/A

### What version(s) of DOSBox-X have this bug?

2022.12.26

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Crap, this means all the past builds still sitting in the User directory of my Macbook need to be cleaned out 😛

**Comment by joncampbell123** [comment]
Okay, it's been fixed 😆
