### ISSUE TITLE
Thank you, whoever you are, for the great Windows 98 walkthrough!

### ISSUE THREAD

**Issue by rhaleblian** [joncampbell123/dosbox-x#3911]
### Question

This is not a question!  Sorry for the hijack.
I refer to, of course,
https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-98

Also, thanks to developers for making this process actually work.
Great project.

Please close this issue at will.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
@rderooy , I assume?
