### ISSUE TITLE
https://dosbox-x.com/  issue

### ISSUE THREAD

**Issue by JimPawl** [joncampbell123/dosbox-x#3918]
![image](https://user-images.githubusercontent.com/99772596/210844728-b530db8f-54b6-4ef3-88fb-12033c92a92b.png)

![image](https://user-images.githubusercontent.com/99772596/210844787-d6ea75da-4ca2-4493-98aa-b2e8579cef4e.png)

Attempted download from home page link "https://dosbox-x.com/" goes to github "https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-win64-2022.12.26-setup.exe" with return of 404.

Pictures included to show issue

**Comment by Torinde** [comment]
Related to #3914

**Comment by JimPawl** [comment]
https://github.com/joncampbell123/dosbox-x/issues/3929

still same issue

**Comment by Torinde** [comment]
Links on the webpage will work after the _next_ release, I think. In the meantime you can get [nightly builds](https://github.com/joncampbell123/dosbox-x/issues/3822) of the installers, e.g. artifacts section [here](https://github.com/joncampbell123/dosbox-x/actions/runs/3976412953).
