### ISSUE TITLE
I can no longer get the whole DOSBox-X to run slower when I use Mo'Slo to slow down Norton Commander

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3923]
### Describe the bug

Once upon a time, I could easily get all the software, at once, even the entire command prompt, to run slower (or vice versa) than they would under the when-and-then configuration, just by using Mo'Slo to make NC.EXE run slower. Obviously I can't do that now, at least not on my PC/device, but I can get one software at a time, like older CGA games, like Donkey Kong, to run slower. I know I can adjust the speed with F11 and F12, but I prefer to use the good old Mo'Slo, which I'd rather only prefer to have on C:\>.

### Steps to reproduce the behaviour

If you have both Norton Commander and Mo'Slo in the same directory, type for example "MOSLO /15 NC.EXE" on the command prompt, then test any software, like for example the Donkey Kong CGA game.

### Expected behavior

I expect the whole DOSBox-X to run slower or faster after changing the speed of Norton Commander with Mo'Slo.

### What operating system(s) this bug have occurred on?

Windows 10 Home, 21H2, 19044.2364

### What version(s) of DOSBox-X have this bug?

As far as I know, DOSBox-X Visual Build win64 20230106010455

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
You know, you can just change the speed with the config command, if you want to automate it from DOS scripts.

e.g.,

```
config -set cycles=750
```

**Comment by BridgeHeadland** [comment]
@rderooy Sure enough, it worked!
