### ISSUE TITLE
Problems with Ducktales: The Quest for Gold when machine is set to Tandy

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3925]
### Describe the bug

When I run Ducktales: The Quest for Gold with machine set to Tandy, this pattern appears, and sometimes it flashes.
![image](https://user-images.githubusercontent.com/85258509/211361098-66323744-5bf6-4a1f-b8ce-03d7d5c56689.png)

### Steps to reproduce the behaviour

Run Ducktales: The Quest for Gold with machine set to Tandy.

### Expected behavior

That Ducktales: The Quest for Gold is running that way it should in Tandy.

### What operating system(s) this bug have occurred on?

Windows 10 Home, 21H2, 19044.2364

### What version(s) of DOSBox-X have this bug?

At least the two latest development builds.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by NebularNerd** [comment]
Can you attach the copy of Ducktales you are using? From your previous thread #3846 all three copies I tested played in Tandy mode fine.

**Comment by BridgeHeadland** [comment]
[DUCKTALE.zip](https://github.com/joncampbell123/dosbox-x/files/10376173/DUCKTALE.zip)

**Comment by grapeli** [comment]
I confirm.
Disney's Duck Tales - The Quest for Gold (1990) stopped working properly with `machine=tandy` as of this change 982c441.

**Comment by NebularNerd** [comment]
@BridgeHeadland @grapeli 

Can confirm this as well, tested using a recent compile I was testing from here: [Build 3873360889](https://github.com/joncampbell123/dosbox-x/actions/runs/3873360889 )

This needs to be flagged up as an issue, in the meantime tiresome as it may be this can be cured using:
`-set memsize=0 -set memsize=640` on the commandline.

Testing a couple of other Tandy games in my collection, OutRun and Gunship showed no issues.

**Comment by NebularNerd** [comment]
> I think you meant: `-set memsize=0 -set memsizekb=640`

I did, got distracted by a notification appearing while typing. 🤦‍♂️ Thanks for the correction, I have edited my post. 🙂

**Comment by joncampbell123** [comment]
The Tandy change was made for another game that did not work properly without the maximum memory size of 736KB. It liked to allocate from top of DOS conventional memory and then caused a "MCB chain corruption" error when the Tandy video mode changed and overwrote it.

Perhaps the proper fix here is that you should be allowed to specify 736kb but Tandy defaults to 640kb.

Just to confirm though... if anyone has a Tandy system with the full 736KB of RAM, please try running the game on that system and see if it fails in exactly the same way.

**Comment by joncampbell123** [comment]
I think the real mistake here is that Tandy mode is not paying attention to the "allow more than 640kb base memory" setting which should be false by default. You should set it to true if you do want the 768KB Tandy configuration and memsizekb=768 though.

**Comment by rderooy** [comment]
According to this vogons post https://www.vogons.org/viewtopic.php?t=40991

A real Tandy needs 768KB to run MM3 or Wing Commander.

**Comment by joncampbell123** [comment]
So it seems the way Ducktales determines where the Tandy video RAM is, is as follows:

Call INT 21h, allocate as much RAM as possible (before anything else is allocated). Note the base segment and size returned by AH=48h. Then free it.

Add the base and size to get the end of the segment which gives the base video memory address 0x9C00 when memsizekb=640kb.

I'm also noticing that after it sets up 320x200 16-color Tandy mode, it takes 64KB off the top instead of 32KB so it can do Tandy page flipping as it renders. There is code to alternate between drawing to segment 9000h and 9800h.

I think what is happening here is that when memsizekb=768 and machine=tandy, DOSBox-X maps the RAM up to the base of video memory but the MCB chain stops at 640KB. Ducktales probably determines the segment is A000h and A800h neither of which is currently supported as video RAM (should it be? can you make the RAM at segment A000h video RAM?).

It would help if someone with a Tandy with 768KB were to confirm whether Ducktales actually works with a 768KB Tandy configuration.

**Comment by joncampbell123** [comment]
I added some debug messages and it's writing to segments A000h and A800h while the Tandy emulation is instructed to page flip between B000h and B800h. So of course... nothing appears.

So if a Tandy has the full 768KB memory expansion, does the DOS MCB chain extend up into it or does it still stop at the first 640KB?

**Comment by joncampbell123** [comment]
No, even Wikipedia suggests that a Tandy with 768KB still uses only the low 640KB for MS-DOS. https://en.wikipedia.org/wiki/Tandy_1000

However I can't find anything out there about problems with this game and 768KB Tandy units. Either nobody noticed and the game breaks on 768KB or DOSBox-X is in the wrong here.

With 768KB the game uses DOS memory allocation to determine (from the end of the allocated block) where video memory is, comes up with segment A000h, and draws everything with page flipping at A000h and A800h. Which doesn't appear on screen. Hm...

![image](https://user-images.githubusercontent.com/6245486/219446385-1cde446a-c908-4372-a0f5-8a4b3db61d01.png)

**Comment by joncampbell123** [comment]
The reason I say this is that there seem to be games that run on Tandy but they don't check that the machine is set up they way they think it is. The Might and Magic game for example makes no attempt to handle any case where it must share the top of DOS memory with the 32KB Tandy modes and it crashes when it corrupts itself writing to the top 32KB video memory. I wonder if this is a case where the games programmers only tested their code on a Tandy with 640KB or less (and therefore shared video memory with top of DOS memory) and none of them had a Tandy with 768KB of RAM in it.

**Comment by joncampbell123** [comment]
If you give the game memsizekb=512 it uses Tandy 3-voice but uses CGA graphics (not enough memory otherwise?).
If you give the game memsizekb=576 you get the same failure mode as seen in your screenshot at the top of this issue, and it is directing the CRT to show segment 9000h/9800h. I think one problem is that this game is hardcoded to always use the latter 64KB for page flipping within the 128KB region assigned to video memory and it assumes the top of DOS memory available is a multiple of 128KB.

I can also imagine how any TSR or other MCB at the top of DOS might confuse this game given how it locates video memory.

**Comment by joncampbell123** [comment]
No. Even hacking the DOS MCB to extend it up to B8000h for the game doesn't work.

As far as I can tell, DOSBox-X is in the right here and  the game doesn't seem to have been tested properly on Tandy systems with 768KB of RAM installed.

To remedy this I also fixed the bug that always allowed more than 640KB for machine=tandy and restored older behavior so it should work as it does with SVN now.

![ducktale_000](https://user-images.githubusercontent.com/6245486/219459047-b2c5752a-8a46-41eb-89f8-dcd9d6121ee0.png)

**Comment by NebularNerd** [comment]
It's a terrible game, just a slapdash of minigames thrown together. I imagine the coding effort was very much a 'that'll do', as long as it worked on a few base configs they likely called it a day and left it at that. If only they had put as much effort into the game as they did the copy protection.

Coming from the Amiga it was a shock on DOS at the time finding you sometimes had to wrangle a game to life by trying to find that last 1 or 2k in the right spot.

**Comment by kcgen** [comment]
@joncampbell123 , thanks for documenting your findings and sharing your thought processes. Very interesting and helpful!

**Comment by joncampbell123** [comment]
> It's a terrible game, just a slapdash of minigames thrown together. I imagine the coding effort was very much a 'that'll do', as long as it worked on a few base configs they likely called it a day and left it at that. If only they had put as much effort into the game as they did the copy protection.
> 
> Coming from the Amiga it was a shock on DOS at the time finding you sometimes had to wrangle a game to life by trying to find that last 1 or 2k in the right spot.

I will say that taking the time to do page flipping and sprite rendering for Tandy is certainly more impressive than other code out there.

It was a mistake to limit DOS to 640KB like that, but then again, the choice of the 8086 limited the overall memory map to 1MB. So we PC users got to deal with hacks like bank switching memory through a expanded memory window in adapter RAM or indirect access to extended memory.

The cramped 640KB space only got worse through the mid 1990s when you had to share it with the mouse driver, CD-ROM driver and MSCDEX.EXE, etc. until finally most DOS games went 32-bit and ran in protected mode atop DOS and then it wasn't a problem before.

**Comment by NebularNerd** [comment]
The 640k thing was a pain to get used to, once I got the hang of tuning my config.sys and autoexec.bat I was up and running. I used to work for a company that built and sold PC's in the mid 90's, the amount of testing I did with various CD-Rom drivers to find a low resource one was quite absurd to my colleagues. 🤣
