### ISSUE TITLE
Menu Toolbar is broken. 

### ISSUE THREAD

**Issue by Yui12** [joncampbell123/dosbox-x#393]
The menu bar that is found in stable releases doesn't even work when it comes to switching things such as scaling, aspect ratio, and even sound for example. It's been like this for a long time, but I don't know when it started. It gotten worse with the latest release from 12-16-2017.

**Comment by joncampbell123** [comment]
It depends on the output. Try the OpenGL or Direct3D outputs. The surface output doesn't always follow aspect ratio.

I did fix the Aspect Ratio menu item recently.

**Comment by joncampbell123** [comment]
It is also broken in some ways because the code to choose scaler, aspect ratio, and output is a tangled mess in the source code and needs to be cleaned up, which I intend to tackle.

**Comment by Yui12** [comment]
I can no longer mute the sound too or change most options. The screen will blink once and nothing happens. I am already using Direct3D. OpenGL didn't work either. So it is a known issue. I'll just leave it open until it's fix so no one else will repeat a topic like this.  So yeah, all I have to do is stick to using .conf for now.

**Comment by joncampbell123** [comment]
I just went through the menu items on the 32-bit and 64-bit builds (SDL 1.x). All menu items respond as expected.

**Comment by Yui12** [comment]
I'm not using the SDL version since I can't enable fullscreen with that build for some reason. That same issue with a blink on the screen screen and nothing happens. Like I said I'm using the build from 12-16-2017.

**Comment by joncampbell123** [comment]
The SDL 2 builds are "Release SDL2" and "Debug SDL2".

The SDL 1 builds are "Release" and "Debug".

**Comment by joncampbell123** [comment]
I haven't yet ported the Windows menu bar to the SDL2 builds.

**Comment by Yui12** [comment]
Oh I notice it now. I tested all of these once again and I still have the same problems. The scaler doesn't work and setting CPU cycles through the menu bar will crash the emulator.

**Comment by joncampbell123** [comment]
What version of Windows is this?

**Comment by Yui12** [comment]
Windows 7.

**Comment by joncampbell123** [comment]
Try the latest build. I'm still not sure what's going wrong here.

**Comment by Yui12** [comment]
Well it looks like you can mute the sound again, but the scaler doesn't work, setting cpu cycles still crashes the emulator (not raising it with CTRL+11 or 12 which works fine), and it doesn't matter what back end I use for it Direct3d or OpenGL. Settings also don't even save, and I can no longer find the setting for cpucycles in the conf anymore. I have no idea what is going on my end, but at least you tried so I thank you for that. I already gave up long ago, so no big deal. 

I tried both 32 bit and x64 bit builds.

**Comment by joncampbell123** [comment]
Should I go ahead and close this?

**Comment by Yui12** [comment]
I can close it myself, but I didn't want to since I'm not sure if I'm the only one, but I guess I am. how unlucky, but that is fine.
