### ISSUE TITLE
Can't change SB type with DOS scripts

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3932]
### Describe the bug

Usually I set the SB type to sb16vibra, but occasionally I want to run certain software in Sound Blaster Pro, and then sbpro2 is preferable. When I write "config -set sbtype=sbpro2", no changes occur. It works perfectly when I write "config -set cycles=750".
I reckon it's a bug, but I'm not 100% sure.

### Steps to reproduce the behaviour

Befor you start DOSBox-X, set sbtype to sb16vibra in the config file. Start DOSBox-X. type "config -set sbtype=sbpro2" and press enter. Start any software/setup/install where you can set the sound to Sound Blaster Pro, and see if you can set the sound to Sound Blaster Pro.

### Expected behavior

I expect the Sound Blaster type to change from the current sbtype value to the desired sbtype value, when I type "config -set sbtype=X" in the DOS script.

### What operating system(s) this bug have occurred on?

Windows 10 Home, 21H2, 19044.2364

### What version(s) of DOSBox-X have this bug?

DOSBox-X, Visual Studio Build, win64, 20230111015646

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Not a bug. Not all settings can be modified without restarting DOSBox-X. This is one of them. Similar with the `machine=` setting.

**Comment by BridgeHeadland** [comment]
@rderooy Will something be done about this, sometime?

**Comment by NebularNerd** [comment]
Changing sb types (or switching to GUS) is equivalent to physically yanking out a sound card on real hardware. One of the reasons you cannot do so is resource allocation is fixed under DOS at boot to a large extent, it was not really until XP that hot swapping hardware while booted was a thing (you could do it on 9x and NT but it usually borked). It's also the reason why you cannot change machine types automatically or on the fly.

For example to change to GUS you typically need to use these at the command line (assuming your not using a different .conf):
` -set sbtype=none -set gus=true`

For Tandy it's best to have:
`-machine Tandy -set sbtype=none`
As this then allows proper Tandy 3 voice and sounds effects to work (Tandy [Outrun](https://github.com/joncampbell123/dosbox-x/issues/2380#issuecomment-1244577594) needs this for example)

**Comment by rderooy** [comment]
> @rderooy Will something be done about this, sometime?

Who knows. What I can tell you is that hot-swapping soundcards **is** supported with the latest DOSBox Staging version.

**Comment by NebularNerd** [comment]
> > @rderooy Will something be done about this, sometime?
> 
> Who knows. What I can tell you is that hot-swapping soundcards **is** supported with the latest DOSBox Staging version.

Interesting, not essential for my setup but would be interesting to see for testing games.

**Comment by joncampbell123** [comment]
> > @rderooy Will something be done about this, sometime?
> 
> Who knows. What I can tell you is that hot-swapping soundcards **is** supported with the latest DOSBox Staging version.
> 
> ![dosbox_001](https://user-images.githubusercontent.com/17701098/212497781-712e5903-52d7-487b-8d70-3cd10bf41960.png)

That's kind of iffy. Does it change the environment variable too? What if you were to run it within a DOS shell or under Windows especially if the sound card is in use?

**Comment by rderooy** [comment]
Yes it changes the environment variable.
![Screenshot from 2023-02-13 08-51-26](https://user-images.githubusercontent.com/17701098/218400712-ba98cb79-3339-48b3-b38b-236d7e6e0285.png)

But cannot comment right now on DOS shell or DOS when running Windows.
