### ISSUE TITLE
[SB16] 45454Hz is clamped to 44100Hz, causing issues

### ISSUE THREAD

**Issue by 8bitbubsy** [joncampbell123/dosbox-x#3935]
### Describe the bug

45kHz (~45454.55Hz, time constant 234) is a perfectly valid output rate on SB16 (even for non-Vibra cards), but the SB16 emulator in DOSBox-X limits it to 44100Hz. This causes pitch errors in programs that expect this rate, like Impulse Tracker 2. This tracker uses 45kHz by default for SB16.

I have confirmed that 45kHz works on older SB16 cards, so the Creative documentation is wrong (not surprised).

In `DSP_RateLimitedFinalSB16Freq_New()`, the max integer frequency should be 45455 (regardless of Vibra or not).
In `DSP_RateLimitedFinalTC_Old()`, the max time constant should be 234 (regardless of Vibra or not).

Here's another bugreport for this problem: https://github.com/joncampbell123/dosbox-x/issues/3333

### Steps to reproduce the behaviour

Try to run Impulse Tracker 2 using SB16. This will use 45454Hz by default. If you play a song, the pitches will be off. If you run IT2 with the `/m43478` command line parameter, songs will play at the correct pitch.

### What operating system(s) this bug have occurred on?

Irrelevant

### What version(s) of DOSBox-X have this bug?

All, even latest repo

### Have you checked that no similar bug report(s) exist?

- [ ] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I already pointed out in #3333 that the upper limit 44100Hz/233 is causing issues, and the setting to workaround.
I left it as is, since @joncampbell123 is already aware of this, but you can of course make a PR to change the upper limit to 45454Hz/234.

**Comment by joncampbell123** [comment]
Actually based on timing tests done against real hardware... you're right. It's consistent whether using the SB Pro or SB16 DSP commands to set sample rate:

http://hackipedia.org/raw/Computer/Platform/PC%2c%20IBM%20compatible/Sound%20and%20Music/Creative%20Labs/Sound%20Blaster/Collection/DOSLIB%20documentation/Creative%20Sound%20Blaster%2016%20ViBRAC%20PnP%20CT4180/graphs/rates/Creative%20Sound%20Blaster%2016%20ViBRAC%20PnP%20CT4180%2etxt%2esb16%2epng

That rate limit was added erroneously before these tests were done.

**Comment by 8bitbubsy** [comment]
> I already pointed out in #3333 that the upper limit 44100Hz/233 is causing issues, and the setting to workaround.
I'm aware, and I even referenced #3333 in the report. The reason I made a new one was to make one that mentions the exact issue in the title (for clarity), and also as a way to show that this bug should have a higher priority.

**Comment by joncampbell123** [comment]
On a related note, perhaps DOSBox-X mixer rate should default to 48000 instead of 44100. There's a practical reason for this: Ever since sound cards went to using the AC'97 standard in the late 1990s, they all render and upsample to 48KHz at the DAC anyway. And modern sound cards, especially if also sending audio to HDMI, can only do 32KHz, 44.1KHz, or 48KHz, and the OS will often just software mix to 48KHz anyway. Gone are the days when the sound card could take a divider value to do arbitrary rates like the old Sound Blaster cards did.

**Comment by 8bitbubsy** [comment]
AFAIK, the DAC _can_ be set to different rates on modern sound cards, it's not necessarily resampled to 48kHz in the end. In Windows for example, you can set many sound cards to output at 96kHz+. And quite a few devices, especially Bluetooth headsets, still default to 44.1kHz. I'd say it's not worth changing the default audio output rate to 48kHz, as resampling from 44.1kHz to 48kHz is almost transparent these days (good resampling algorithms are being used).

However, the SB16 frequency limit problem is worth fixing though, as it creates big issues for some software setting the SB16 to 45kHz. It's not a problem of resampling, it's a problem where the program expects a 45kHz stream. It's calculating the voice pitches from that rate. Even the BPM of the songs will be off, as they are also calculated to tick after N output samples. In other words, you should remove the Vibra check in the range limiting, as _all_ SB16 sound cards accept the 45kHz (234) setting.

I have verified that a time constant of 234 works for non-Vibra SB16 cards (older cards). Though I have not verified if it works when you set the frequency directly (not using a time constant). Impulse Tracker 2 uses the time constant method for SB16, so that alone is still worth fixing.

**Comment by joncampbell123** [comment]
> AFAIK, the DAC _can_ be set to different rates on modern sound cards, it's not necessarily resampled to 48kHz in the end. In Windows for example, you can set many sound cards to output at 96kHz+. And quite a few devices, especially Bluetooth headsets, still default to 44.1kHz. I'd say it's not worth changing the default audio output rate to 48kHz, as resampling from 44.1kHz to 48kHz is almost transparent these days (good resampling algorithms are being used).
> 
> However, the SB16 frequency limit problem is worth fixing though, as it creates big issues for some software setting the SB16 to 45kHz. It's not a problem of resampling, it's a problem where the program expects a 45kHz stream. It's calculating the voice pitches from that rate. Even the BPM of the songs will be off, as they are also calculated to tick after N output samples. In other words, you should remove the Vibra check in the range limiting, as _all_ SB16 sound cards accept the 45kHz (234) setting.
> 
> I have verified that a time constant of 234 works for non-Vibra SB16 cards (older cards). Though I have not verified if it works when you set the frequency directly (not using a time constant). Impulse Tracker 2 uses the time constant method for SB16, so that alone is still worth fixing.

It's been fixed. Most sound cards did only 48KHz for the longest time, 96KHz came somewhat later. All the AC'97 hardware rates are 32KHz, 44.1KHz, or 48KHz or they are multiples of those standard rates.

**Comment by 8bitbubsy** [comment]
Nice! Now the next step would be to handle the SB frequency as a floating point number, to maintain maximum accuracy.
As said, time constant 234 is actually 45454.5454Hz (recurring), so by truncating it to integer you are losing some very slight precision.

This is not important though, but maybe something to think about in the future.

**Comment by joncampbell123** [comment]
The mixer code uses fractions for interpolation and resampling. Maybe the "set sample rate" call could accept a fraction which could represent 45454.5454Hz and therefore allow that to work.

**Comment by joncampbell123** [comment]
Actually, that code is already there. sblaster.cpp just needs to use it.

**Comment by 8bitbubsy** [comment]
> Ironically conversion to float would lose some very slight precision.

That's not a concern here. You don't need a lot of mantissa bits to store the "time constant -> Hz" decimals with sufficient accuracy. They are basic fractions.

**Comment by maron2000** [comment]
@joncampbell123 
Since the upper limit of sampling rate is now fixed, I think issues #3178 and #3333 can be closed.
