### ISSUE TITLE
Vista and WinXP - installers and builds

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#3943]
Workflow for automatic building for WinXP portable executables (win32, win32-low end, win64) would be of course good to add.
What about also:
- automatic building of WinXP installers (or actually bundling those as part of the current win32 and win64 installers?) - dosbox-x.com homepage link is defined as "32-bit Setup (XP+)" @JoeBroesele

_Originally posted by @Torinde in https://github.com/joncampbell123/dosbox-x/issues/3926#issuecomment-1386537129_
            
Results from testing under WinXP x64 SP2 on VirtualBox 6.1.40
- [installers](https://github.com/joncampbell123/dosbox-x/actions/runs/3965310395): win32 works, *win64 doesn't work* ("is not a valid win32 application").
- builds from above win32 installer: 
-- doesn't work and that's already explained in INSTALL.md: mingw SDL1, mingw SDL2
-- **doesn't work and that contradicts INSTALL.md**: x86 SDL1 (VS?), x86 SDL2 (VS?)
-- works: mingw-lowend SDL1, mingw-lowend SDL2
- builds from [XP builds](https://github.com/joncampbell123/dosbox-x/actions/runs/3965310393):
-- **doesn't work and contradicts INSTALL.md**: x86 SDL1 (VS2017), x64 SDL1 (VS2017)
-- works: x86 SDL2 (VS2017), x64 SDL2 (VS2017)

Results from testing under WinXP 32-bit SP3 on VirtualBox 6.1.40
- [installer](https://github.com/joncampbell123/dosbox-x/actions/runs/3965310395): win32 works
- builds from above win32 installer: 
-- doesn't work and that's already explained in INSTALL.md: mingw SDL1, mingw SDL2
-- **doesn't work and that contradicts INSTALL.md**: x86 SDL1 (VS?), x86 SDL2 (VS?)
-- works: mingw-lowend SDL1, mingw-lowend SDL2
- builds from [XP builds](https://github.com/joncampbell123/dosbox-x/actions/runs/3965310393):
-- **doesn't work and contradicts INSTALL.md**: x86 SDL1 (VS2017)
-- works: x86 SDL2 (VS2017)

So, there are the following issues:
- win64 installer doesn't work under WinXP x64. win64 installer from 2022.08 gives the same error.
- Installers are using builds from VS2019/2022 *only*. I suggest adding to them the VS2017 builds and ideally disabling as a choice under WinXP the VS2019/2022 ones (in the same way mingw builds are disabled under WinXP). Under Vista+ VS2017 ones may remain as secondary option. 
- VS2017 XP builds - SDL1 versions don't work. Both win32 and win64 builds 2022.08 VS SDL1 work. 
 
@maron2000 @JoeBroesele

**Comment by maron2000** [comment]
I don't see any flaws on 32bit versions.(As already confirmed in #3909)
I personally couldn't test on XP 64bit but if there are incompatibilities, anyone can simply make it quit building those.

![xp_latest](https://user-images.githubusercontent.com/68574602/213830361-bf4372b6-edc8-4a32-86b6-4d7d0f54b239.png)

**Comment by Torinde** [comment]
Regarding the builds - I think problem is with SDL1 - not with x64. For me:
VS2017 XPx64 SDL2 build works. The SDL1 doesn't. 2022.08 works.
VS2017 XPx86 SDL2 build works. The SDL1 doesn't. 2022.08 works. The same happens under both WinXP x64 and x86.

![image](https://user-images.githubusercontent.com/97228894/213864519-28d22dab-c9aa-4975-9cff-cc7ffcd7746b.png)

**Comment by maron2000** [comment]
So as the error message mentions, Xinput.dll is missing in your environment.
Try reinstalling DirectX runtime or make sure you have updated you OS to the latest.
As I already mentioned twice, SDL1 version works.

**Comment by Torinde** [comment]
I'll try re-installing DirectX, but as shown in previous comment - 2022.08.0 SDL1 doesn't give a XINPUT error.

**Comment by JoeBroesele** [comment]
Probably the best would be to inlcude the XP builds into the existing two Windows installers - 32 bit and 64 bit. The magic is all in the build scripts for the installers. GitHub CI will require only marginal changes like checking for additional dependecies.

Unfortunately, I am not an expert for the installer build scripts. Also, I don't have Windows XP 64 bit available for testing and also no Windows running on ARM.

**Comment by JoeBroesele** [comment]
Just as a though: Are people still running Windows XP? I mean, is it worth the effort for the XP builds?

**Comment by maron2000** [comment]
Confirmed all XP builds (x86/x64, SDL1/2) run on a clean installed XP x64 with DirectX Jun 2010 runtime redistributables installed.
Based on @Torinde 's comment, I believe runtime installation is required for x86 builds on a 32bit XP as well.

![xp_x64](https://user-images.githubusercontent.com/68574602/213872017-06ecd2e2-476c-460f-874c-1bd9abfacaa9.png)

**Comment by maron2000** [comment]
@JoeBroesele 
You don't have to feel obligated.
We can contribute whatever we can, and your contribution is already a help for others.
If the request is tough for you, no one will blame you for that.
It may be better with a comprehensive installer but we can cope without it.

**Comment by Torinde** [comment]
@maron2000 , 2023.01.21 XP SDL1 build - works for me after installing directx_mar2009_redist.exe Strange, because 2022.08.0 SDL1 works on a clean WinXP x64 install, without anything extra. So, something definitely changed in the last 3 months?

Also, all four 2023.01.21 XP builds work under Windows 11.

@JoeBroesele , are people still running WinXP - there were questions about it (see issue linked at the top here), so it seems the answer is yes, at least some...

I'm trying to check - which versions of the win64 installer work under which versions of Windows - to help nail down when/what the change was. Results so far:
2022.12.26 win32 installer works under Windows 11, six of its builds work under Windows 11, two of its builds I can't test (ARM32)
2022.12.26 win64 installer works under Windows 11, four of its builds work under Windows 11, two of its builds I can't test (ARM64)
2022.12.26, 2022.09.0, 2022.08.0 win64 installers - not working in WinXP x64, Vista x64 - error "is not a valid win32 application"

I'll check more combinations later.

**Comment by Torinde** [comment]
2022.12.26 win64 installer works under Windows 10.
all versions back to 0.83.16 win64 installer doesn't work under XP64 and Vista : "is not a valid Win32 application".
0.83.15-setup-allusers doesn't work under XP64 and Vista: "is not a valid Win32 application".
0.83.15-setup works under XP64 and Vista, provides both 32-bit and 64-bit builds and includes the "MinGW with custom drawn menus".
then back to 0.83.5-setup - same result, works under XP64 and Vista. I didn't see "allusers" variants of those installer versions.

I'll try Windows 7 next. But so far it seems either:
- the "allusers" option is enabled by default in installers after 0.83.5 and somehow that's a problem for Vista and XP?
- when the custom drawn menus build was removed - some of the changes broke the installer on Vista and XP?

**Comment by Torinde** [comment]
2022.12.26 win64 installer works under Windows 7 and starts with:
![image](https://user-images.githubusercontent.com/97228894/213911364-a90c54dd-346b-4dee-a6f0-aebf412f0404.png)
versions from there backwards to 0.83.16 show the same question first.

0.83.15-setup-allusers shows different one:
![image](https://user-images.githubusercontent.com/97228894/213911449-06171a04-9cd0-4beb-a197-97611163dade.png)

0.83.15-setup and previous versions don't have those and show immediately:
![image](https://user-images.githubusercontent.com/97228894/213911503-12db1d5d-a79c-4ffd-b41d-d88c10e27577.png)

2022.12.26 win32 installer under Win7x64 also doesn't have the "all users question" and shows immediately:
![image](https://user-images.githubusercontent.com/97228894/213911540-eb4587cb-80af-45b6-9c60-f2c9305d8313.png)

So, could it be that x64 variants of Vista and XP have some issue with running "all users" setup? I tried with "Run as admin" - didn't help. Turning off User Account Control in Vista didn't help (haven't tried XP yet). Any other ideas?

**Comment by Torinde** [comment]
Some documentation about [ALLUSERS property](https://learn.microsoft.com/en-us/windows/win32/msi/allusers) - Win7, Vista, XP.
Why are only win64 installers affected and not win32?

**Comment by Torinde** [comment]
WinXP installer (for both x86 and x64) - #3988

**Comment by BridgeHeadland** [comment]
@JoeBroesele If I'm not mistaken, it is somewhat possible to run Windows XP in DOSBox-X - not sure if DOSBox-X can run 64-bit WXP. If I'm right, then I expect that running Windows XP on newer hardware will become a trend one day, that is to say that even though there are not that many people running Windows XP today, it does not necessarily mean that fewer will run Windows XP in the future. For example, I remember well, over time, when fewer people ran Windows 3.x, as Windows 9x became more popular and usual, despite what 9x can't do, that 3.x can do, until it was discovered that you can run it type of Windows operating system in regular DOSBox. I think it will become a trend to run a 32/64-bit build for Windows XP, in Windows XP, which in turn runs in DOSBox-X for PC with Vista+ (and ARM), Mac, and even Linux - it will as we say in Norway: butter on pork on butter.

**Comment by Torinde** [comment]
@johnnovak, do you have an idea why the installer (NSIS based) doesn't work under Vista x64?
Vista x86 works, Win7 x64 works, even XP 32/64 combined installer works...
Above I suspect something related to ALLUSERS property, but maybe it's something else...

**Comment by johnnovak** [comment]
> @johnnovak, do you have an idea why the installer (NSIS based) doesn't work under Vista x64? Vista x86 works, Win7 x64 works, even XP 32/64 combined installer works... Above I suspect something related to ALLUSERS property, but maybe it's something else...

Short answer: no.

To make it clear, I don't work on DOSBox-X, only Staging, and staging uses the Inno installer.

I'm using NSIS in my own project (Gridmonger), but as I don't care about anything older than Win 7 (and even that just barely), I have no idea.

**Comment by Torinde** [comment]
Besides the 64-bit installer not working in Vista, there is also #4050 - MinGW builds not working in Vista (only the lowend one works).

So, it would be good Installers to not offer MinGW32/64 on Vista.

The overall compatibility chart, per my understanding:
![image](https://user-images.githubusercontent.com/97228894/223396135-4141573f-0e9f-4f6e-ad1e-90d184cac200.png)

Since XP installer works also under Vista x64 - maybe that installer can be expanded that to offer all compatible builds depending on the host OS/CPU, while keeping all other features of the default (non-XP) installer. To have a SINGLE installer for all builds and all Windows versions. @aybe, are you interested in that?

**Comment by johnnovak** [comment]
You went all out on that one Torinde 😅

Just curious, what's the motivation here? How many people still use Vista and XP these days?

Note that because the dev teams are not testing stuff on these old OSes, things might break on XP / Vista in any future release without warning. Are you willing to test every single release on XP and Vista in the future? If so, I'm not against it, of course, but I don't think anybody else has any interest in this extra work.

Don't want to discourage you, I'm just being realistic.

On the other hand, I think there are other areas where your talents would make a much bigger difference (e.g. general testing on OSes that people actually use 😄)

**Comment by aybe** [comment]
If even installers have given up on compatibility... 😅

I was going to suggest to use an older version but maybe it wouldn't even be  compatible with current systems 🤣

See for the simplest and most effective, if it fails, fallback to a zip file I guess?

**Comment by Torinde** [comment]
Surprisingly, when the standard builds stopped working on XP, there were people asking about that (for example the issue in the top message here). Then during testing I discovered the problem with Vista x64 installer.

What's the motivation... good question, no good answer 😊

I agree neither XP nor Vista should be any kind of priority (if I have to pick: emulation of AWE32+, Aureal3D/Vortex2, the various proprietary GPUs of the 90s), but I presented my findings here - in case somebody has an easy/obvious solution. In the meantime, what I and others did was - correct documentation/website to mention which installer/build is compatible with what OS. A little messy, but hopefully helpful for the people not closely following, but wanting to install there.

Future releases - if they are not coming very often I may test them, but as you say priority is low... for sure if somebody raises the question and I see or am tagged - I'll gladly test.

**Comment by johnnovak** [comment]
Sure, not trying to discourage your anything, and this is good info. It just seems you put a lot of energy into this, and unless you're going to repeat the same testing exercise every 6 months (roughly) when a new release comes out, then this one-off effort is a little bit waisted. Everybody will want the latest version anyway.

Thanks for your research 😄

**Comment by kcgen** [comment]
@aybe yeah, talking about installers: nothing is worse than when software is wrapped up in an executable that doesn't even run on the platform in which it's intended. 

I remember in the mid 90s some DOS game patches were bundled in win32s installers 😂

**Comment by aybe** [comment]
If you remember, many DOS games on CD-ROM actually did have a Windows installer, even with .PIF files sometimes.

Regarding NSIS, it could work but it's messy, there's a VSCode extension to ease the pain but still.

Something that might be worth a try, has a wizard and uses NSIS internally: https://portableapps.com/development

**Comment by Torinde** [comment]
2023.09.01 combined 32/64bit installer now works on Vista x64.

It would be good if it doesn't offer MinGW builds when on Vista, because they don't work (#4050). Is it possible to detect the OS from inside the installer?
