### ISSUE TITLE
High sierra and LOADLIN - workflows for automatic building

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#3946]
- automatic building of macOS high sierra portable (last seen [2022.09.0](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.84.3)). If it's decided that this won't be build with every release, then INSTALL.md should link to the latest one.
- automatic building of LOADLIN portable (last seen [0.83.25 2022-05-01](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.83.25)). If it's decided that this won't be build with every release, then INSTALL.md should link to the latest one.

_Originally posted by @Torinde in https://github.com/joncampbell123/dosbox-x/issues/3926#issuecomment-1386537129_
           
High sierra: [INSTALL.md](https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md#macos-packages-portable) explicitly states "Such a build for the latest DOSBox-X version is available from the [DOSBox-X homepage](https://dosbox-x.com/).", but it's found neither in releases nor in nightly builds artifacts.

LOADLIN: INSTALL.md states such build is available only at "some versions of DOSBox-X", thus the latest available version is reflected via #3945 until an automatic workflow is created.

**Comment by Torinde** [comment]
LOADLIN - INSTALL.md changed via #3945 

I can make a PR for mentioning latest High-sierra in INSTALL.md - but that makes sense only if it will NOT be generated with every release. And currently INSALL.md states the opposite?

**Comment by Torinde** [comment]
@grapeli, can you automate the building of LOADLIN or High sierra builds?

**Comment by grapeli** [comment]
@Torinde 
For various reasons, I am not interested in it. By the way, how to build such a minimal Linux system I gave here #3429.
The ideal basis for this is [buildroot](https://buildroot.org/), which can still run properly even on a 486 cpu.
