### ISSUE TITLE
Source code for scanres.com etc.

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#3962]
### Discussed in https://github.com/joncampbell123/dosbox-x/discussions/3858

<div type='discussions-op-text'>

<sup>Originally posted by **skitt** November 28, 2022</sup>
### Question

Is the original source code for scanres.com and the other text utilities available? cga/ega/vga.com are trivial, as is clr.com; but for redistribution purposes (in Debian) it would be helpful to have source code. I can recreate it if necessary, but it’s worth asking first!

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.</div>

**Comment by aybe** [comment]
I suppose you searched the web, I did and found nothing...

There are two versions of it, one is 200 bytes, the other 211 bytes:

https://www.vogons.org/viewtopic.php?p=167991#p167991

https://www.vogons.org/viewtopic.php?p=168131#p168131

_Originally posted by @aybe in https://github.com/joncampbell123/dosbox-x/discussions/3858#discussioncomment-4259278_

**Comment by aybe** [comment]
You welcome.

_Originally posted by @aybe in https://github.com/joncampbell123/dosbox-x/discussions/3858#discussioncomment-4271712_

**Comment by aybe** [comment]
Looking into this further, `scanres.com` isn’t actually useful in DOSBox-X since DOSBox-X supports varying the number of scanlines directly, unlike DOSBox.

_Originally posted by @skitt in https://github.com/joncampbell123/dosbox-x/discussions/3858#discussioncomment-4276895_

**Comment by aybe** [comment]
Oh okay, I don't know to be honest but I guess you are right!😁

_Originally posted by @aybe in https://github.com/joncampbell123/dosbox-x/discussions/3858#discussioncomment-4281528_

**Comment by Torinde** [comment]
Original issue was #3854

**Comment by Torinde** [comment]
@skitt

**Comment by skitt** [comment]
@Torinde this was resolved by removing `scanres.com`, see https://github.com/joncampbell123/dosbox-x/pull/3861; the other files are trivial, I recreated the source code. I can’t close this but there’s not much point in keeping it open (unless ripsaw8080 shows up here).
