### ISSUE TITLE
dosbox-x 2022.12.26 Can't run Game Command and Conquer but DOSBox 0.74 can

### ISSUE THREAD

**Issue by dongminghao** [joncampbell123/dosbox-x#3975]
### Describe the bug

when I use dosbox-x to play the game "Command and Conquer " can not run the game.
the game download from https://www.moddb.com/games/cc-gold/downloads/command-and-conquer-dos
DOSBox 0.74 can run it well.
DOSBox-X 2022.12.26 use same config file but fail

### Steps to reproduce the behaviour

1.the game download from https://www.moddb.com/games/cc-gold/downloads/command-and-conquer-dos
2.change file "0 Launch Command and Conquer.bat"  to use dosbox-x 
here is I do
dosbox-x.exe  -conf "F:\CC_DOS_Full\C&C-DOS\dosbox.conf" -conf "F:\CC_DOS_Full\C&C-DOS\CnC-game.conf" -console
3.them I got  this 
![image](https://user-images.githubusercontent.com/481847/215419411-c97d1d76-7e9f-40fe-af09-92718ae49e60.png)

4.from console winodws I got this
LOG: Win32 EnumDisplayDevices #4: name=\\.\DISPLAY5 string=AMD Radeon(TM) Graphics
LOG: DOSBox-X version 2022.12.26 (Windows SDL1)
LOG: Windows keyboard layout ID is 0x0804
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: The overlay output has been removed.
LOG: The following output will be switched to: direct3d
LOG: Configured windowposition: -
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: ISA BCLK: 8333333.333Hz (25000000/3)
LOG: monopal: green,
LOG: Active save slot: 1 [Empty]
LOG: USING AVI+ZMBV
LOG: Max 3670016 sz 16384
LOG: Final 16384
LOG: MIDI:Opened device:win32
LOG: Pentium CMPXCHG8B emulation is enabled
LOG: VOODOO LFB now at d0000000
LOG: Serial1: BASE 3f8h
LOG: Serial2: BASE 2f8h
LOG: disney=true. For compatibility with other DOSBox forks and SVN, LPT1 has been reserved for Disney Sound Source. Initializing it now.
LOG: DOSBox-X also supports disney=false and parallel1=disney
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: Allocated APM BIOS pm entry point at f000:ce20
LOG: Writing code to fce20
LOG: Writing code to fce40
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: Windows: IID_ITaskbarList3 is available
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG: WARNING: No translation support (to host) for code page 0
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG:   11155021 ERROR EXEC:stack underflow/wrap at EXEC SS:SP=0000:0000
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (406.400 x 228.600 mm) (16.000 x 9.000 in) (120.000 x 120.000 DPI)
LOG:   11173158 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:   11173236 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:   11186900 ERROR BIOS:INT15:Unknown call ax=BF01

### Expected behavior

![image](https://user-images.githubusercontent.com/481847/215420270-f624d3b0-5078-41ce-993f-56d8e567cec6.png)
![image](https://user-images.githubusercontent.com/481847/215420336-7b9f5890-7fda-46e0-b92c-b3500141d90a.png)

### What operating system(s) this bug have occurred on?

windows 10 22H2

### What version(s) of DOSBox-X have this bug?

2022.12.26

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Simply installed the game from CD, and no problem with default DOSBox-X settings.
![C C](https://user-images.githubusercontent.com/68574602/215690699-7a18999e-9afa-4aa6-8653-91ccbf4ee4b9.png)
![C C2](https://user-images.githubusercontent.com/68574602/215691313-350da131-8721-4cf7-8284-b022e59ad5d7.png)

**Comment by grapeli** [comment]
I also run this indicated copy without any problems with the default settings (dosbox-x-sdl2-linux).
`dosbox-x -c 'mount c .' -c 'c:' -c "C&C.COM -cd.\cd"`

**Comment by dongminghao** [comment]
> I also run this indicated copy without any problems with the default settings (dosbox-x-sdl2-linux). `dosbox-x -c 'mount c .' -c 'c:' -c 'C&C.COM -cd.\cd'`
I tried this command in cmd.exe but still this problem.
 maybe I built DOSBox-x in windows use virsual studio 2022 the other game run well  but this game.

**Comment by grapeli** [comment]
As I mentioned, it starts without any problems with default settings. Just mount the game folder and run.
It is not difficult.

[cc.dosbox-x-2022.12.26-sdl2-linux-x86_64.webm](https://user-images.githubusercontent.com/452325/216025323-38bc83e9-0b4f-496f-861d-0706e8b97dd7.webm)

Just because you can't run it doesn't necessarily mean it's a bug in dosbox-x as you flagged in the report.

**Comment by joncampbell123** [comment]
I can confirm here, C&C works perfectly fine.

**Comment by joncampbell123** [comment]
I can also confirm the recent fixes to IPX emulation allow two instances of DOSBox-X to run C&C in multiplayer over the "network"

**Comment by Lewiscowles1986** [comment]
Well I just got this same bug on an apple M1 when trying to play Star Trek TNG, a Final Utility on dosbox-x; so I am a bit miffed that "works for me" is the answer. I Think it has something to do with games that try to introspect display modes

```
LOG: IDE: index 1 slave=0
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: surface consider=720x400 final=720x400
LOG: Screen report: Method 'CoreGraphics' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (629.265 x 360.947 mm) (24.774 x 14.211 in) (77.500 x 76.000 DPI)
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: surface consider=720x400 final=720x400
LOG: Screen report: Method 'CoreGraphics' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (629.265 x 360.947 mm) (24.774 x 14.211 in) (77.500 x 76.000 DPI)
LOG: Screen report: Method 'CoreGraphics' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (629.265 x 360.947 mm) (24.774 x 14.211 in) (77.500 x 76.000 DPI)
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: surface consider=720x400 final=720x400
LOG: Screen report: Method 'CoreGraphics' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (629.265 x 360.947 mm) (24.774 x 14.211 in) (77.500 x 76.000 DPI)
LOG:   15156114 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:   15156192 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG: DOSBox-X has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox-X's options.
LOG:   15167943 ERROR BIOS:INT15:Unknown call ax=BF01
LOG: E_Exit: Illegal descriptor type 0 for int 31
E_Exit: Illegal descriptor type 0 for int 31
```

If I change the graphics setup changes some options, but then the game complains that it cannot load UNIVBE.DRV

**Comment by Lewiscowles1986** [comment]
so I deleted all the fs and started from scratch, without a dosbox.conf

`dosbox-x -c 'mount C ./c' -c 'c:' -c 'imgmount D ./cd/disk.cue' -c 'cd sttng' -c 'sttng' -c 'exit'` now runs the game smooth as butter. So I don't know if it's the gpu setting or something else amiss from my old dosbox.conf, but this is likely always a config issue when encountered.
