### ISSUE TITLE
website links

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#3979]
Hi

The windows download links are broken on the website

**Comment by Torinde** [comment]
Please see #3914, it's resolved and at the next release the links should work. In the meantime you can use [Nightly builds](https://github.com/joncampbell123/dosbox-x/issues/3822) such as [these](https://github.com/joncampbell123/dosbox-x/actions/runs/4067391675).

**Comment by maron2000** [comment]
The broken links are now linked to the portable packages to at least avoid a 404 error, since installers are not released for 2022.12.26.
It's expected to be linked to installers again at the next release as @Torinde mentioned.

**Comment by blender-girl** [comment]
Why are sometimes no installers released? For true fans of dosbox-x, it's sad :(
I like the project too but i'm a beginner :)

**Comment by Torinde** [comment]
In the issue I linked above it was discussed a little bit, I think
