### ISSUE TITLE
Improve syntax highlighting and implement copy-to-clipboard button in on-site wiki

### ISSUE THREAD

**Issue by Dobby233Liu** [joncampbell123/dosbox-x#3986]
### Is your feature request related to a problem? Please describe.

Courtesy of @rderooy 

> The code block syntax highlighting on dosbox-x.com/wiki is rather limited. It does not actually do any highlighting (unlike on the GH wiki), all it does is when you hover over the code block, in the top-right corner a 'INI' or "CONSOLE" or "SHELL" word shows in grey.

> Ok, because it also does not give the easy clipboard option that GH wiki gives.

### What you want

Rough implementation idea
1. Add asciidoctor and related deps to Gemfile
2. Implement build-time syntax highlighting through Rouge or anything else
3. Adapt ctc from here https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/61#issuecomment-1250380863

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Dobby233Liu** [comment]
I would like to be assigned

**Comment by aybe** [comment]
@Dobby233Liu I just assigned you.
