### ISSUE TITLE
No portable or installer?

### ISSUE THREAD

**Issue by Blackpearl1** [joncampbell123/dosbox-x#3989]
### Question

The link for installer or the portable version of dosbox-x are invalid.
And I can't find also a binary for windows on github. right?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
Please see https://github.com/joncampbell123/dosbox-x/issues/3914 about the installers, it's resolved and at the next release the links should work. 
Portable versions are as usual at the Release page? Also you can download latest nightly build from the Tab Actions here.

**Comment by aybe** [comment]
The portable releases are here:

<img width="593" alt="chrome_UmJXPvb1QB" src="https://user-images.githubusercontent.com/1537591/217044896-10b158a7-a58b-45e3-a10b-174650986760.png">

**Comment by maron2000** [comment]
It maybe useful to also show the link to previous releases in the web site.
Just in case for broken links.
![Screenshot_20230208-201430~2](https://user-images.githubusercontent.com/68574602/217515727-3a446844-7f7c-41b0-9368-6d7dbcb818d8.png)
