### ISSUE TITLE
This change 00378e8 creates problems when booting a linux kernel with APM enabled. Linux won't start. When starting with `apm=debug`, it stops right there.

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#3990]
This change 00378e8 creates problems when booting a linux kernel with APM enabled. Linux won't start. When starting with `apm=debug`, it stops right there.

```
apm: BIOS version 1.2 Flags 0x03 (Driver version 1.16ac)
apm: entry f000:ce40 cseg16 f000 dseg f000
 cseg len ffff, dseg len ffff
 cseg16 len ffff
```

You can get around this by disabling apm with a kernel parameter (`apm=off`), or by disabling apm in dosbox-x (`apmbios=false`).
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/kernel/apm_32.c

_Originally posted by @grapeli in https://github.com/joncampbell123/dosbox-x/issues/3797#issuecomment-1298213575_
            
Also, [Skipped SVN commits.txt](https://github.com/joncampbell123/dosbox-x/blob/f926efa473c77047ba2625831e874ee6fd02c474/patch-integration/Skipped%20SVN%20commits.txt) is not updated with those (and some previous ones?) @Allofich

**Comment by joncampbell123** [comment]
The most likely reason is the change from mem_readw/mem_writew to real_readw/real_writew.

Those entry points are designed to be called from either real mode or 16-bit/32-bit protected mode because the APM standard can potentially allow that.

I'm not entirely sure that the change to INT 21h would cause the Linux kernel any issues.

**Comment by joncampbell123** [comment]
I'm not sure if this breaks UNLZEXE again, but I believe I fixed it carefully to retain real mode stack pointer rollover only for real mode.
