### ISSUE TITLE
ucdos cannot run on win64 verion

### ISSUE THREAD

**Issue by l1t1** [joncampbell123/dosbox-x#3991]
### Describe the bug

aftern run ucdos.bat, the screen became black and no response.

### Steps to reproduce the behaviour

1. download the file https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-vsbuild-win64-20221226190454.zip or https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-mingw-win64-20221227040641.zip and unizp it to d:\dosbox-x
2. copy ucdos directory into d:\dosbox-x\c in windows 7
3. run d:\dosbox-xdos\box-x.exe by click it
4. mount c d:\dosbox-x\c
5. cd ucdos
6. ucdos
7. see error

### Expected behavior

it runs and shows Chinese characters.

### What operating system(s) this bug have occurred on?

windows7 64bits

### What version(s) of DOSBox-X have this bug?

dosbox-x-vsbuild-win64-20221226190454

### Additional information

[ucdos.zip](https://github.com/joncampbell123/dosbox-x/files/10660023/ucdos.zip)
[dosbox-x.zip](https://github.com/joncampbell123/dosbox-x/files/10660026/dosbox-x.zip)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by l1t1** [comment]
BTW:
use https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-mingw-win32-20221227040728.zip ,
ucdos works on windows7 32bits
and
does not work on windows7 74bit

**Comment by maron2000** [comment]
You may want to take a look at this.
![ucdos](https://user-images.githubusercontent.com/68574602/216907908-0b3ff06c-47b7-40dc-bed6-f131a67263fd.png)

**Comment by l1t1** [comment]
thanks, it works
@maron2000

**Comment by l1t1** [comment]
@maron2000 could you tell me how to set in dosbox 0.74-3?
at first, the problem is same as that in dosbox-x, 
then I  modify the dosbox.conf with following lines
```
[dos]
#            xms: Enable XMS support.
#            ems: Enable EMS support.
#            umb: Enable UMB support.
# keyboardlayout: Language code of the keyboard layout (or none).

xms=false
ems=false
umb=false
keyboardlayout=auto
```
it can run, but show strange characters at the screen, 

but when I modi comm in foxpro 2.5 the Chinese characters can be shown.
and more, when run the prg file, the Chinese characters are missing.
![2023-02-06_165058](https://user-images.githubusercontent.com/23301704/216927813-cef3688f-b044-4248-a4bd-5747dd74db6d.png)
![2023-02-06_165040](https://user-images.githubusercontent.com/23301704/216927819-cad8b47e-5dea-42f7-8574-a034b5696241.png)
![2023-02-06_164010](https://user-images.githubusercontent.com/23301704/216927827-c4851eb2-7dc9-44cb-81b5-01ddd270f256.png)
![2023-02-06_163549](https://user-images.githubusercontent.com/23301704/216927832-3d23f1f2-50d8-455f-91df-e69499eb236b.png)

**Comment by rderooy** [comment]
For regular DOSBox, please go to their support site at https://vogons.org

**Comment by l1t1** [comment]
@rderooy Thanks
