### ISSUE TITLE
Feature request issue template doesn't add any labels for default

### ISSUE THREAD

**Issue by Dobby233Liu** [joncampbell123/dosbox-x#3993]
### Describe the bug

When you create an issue for this repo with the template "Feature request", the issue is not automatically labeled.

### Steps to reproduce the behaviour

1. Go to https://github.com/joncampbell123/dosbox-x/issues/new
2. Select "Feature request"
3. Scroll down
4. See that the issue you're about to create doesn't have any labels assigned for default

### Expected behavior

The "feature request" label should be assigned.

### What operating system(s) this bug have occurred on?

Does not apply here - perhaps there should be a "meta" bug report template now that I think about it

### What version(s) of DOSBox-X have this bug?

Current master, f926efa

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by aybe** [comment]
Fixed, b8a2df10e3537139f81e22e4d6b53b71bd820a10, thanks! 😁
