### ISSUE TITLE
Problems with CTSOUND /  CTSB16.SYS - Invalid argument when specifying Low DMA on parameter (CONFIG.SYS related)

### ISSUE THREAD

**Issue by rockleevk** [joncampbell123/dosbox-x#3999]
Note: using latest release of DOSBoX-X >> [dosbox-x-mingw-win64-20221227040641.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-mingw-win64-20221227040641.zip)
Hi here, been testing to load the Creative SoundBlaster's CTSOUND driver (CTSB16.SYS file specifically) using DOS/V version J5.00 and J7.00 (Japanese) while booting with an HDD image, installing SB16 drivers on the "Guest OS", and in order to use this CTSOUND driver instead of the basic CSP(Low-level driver), added the line on CONFIG.SYS:

`DEVICE=C:\SB16\DRV\CTSB16.SYS /UNIT=0 /BLASTER=A:220 I:7 D:1 H:5`
So, sound card is loaded as 
Address: 0220, 
IRQ: 7, 
Low DMA: 1, 
High DMA: 5

Of course, my soundcard has been set on AUTOEXEC.BAT as:
`SET SOUND=C:\SB16`
`SET BLASTER=A220 I7 D1 H5 P330 T6`
Where A parameter is Address, I parameter is IRQ, D is Low DMA, H is High DMA. P is MIDI port address and T is an indicator of what sound card I am setting, so T6 for SB16 card.

Till this point is all good, but when booting, I get the following error message, telling me argument "D" is invalid on CTSOUND Driver:
`ERROR CTSOUND1010: Invalid "/Blaster=D:x" argument.`

Thanks a lot and wish we can figure out what is causing this issue on DOSBox-X. 
This is needed in order to run a DOS/V game that requires CTSOUND/CTSB16.SYS loaded on boot in order to be able to detect and play any FM or MIDI sound (BGM/OST of the game). If not, the game just throws an error saying that "Enviroment variable is not set up correctly" in Japanese. So the game proceeds to load, without any FM or MIDI sound, saying that SoundBlaster cannot be used.
![error](https://user-images.githubusercontent.com/26289659/218208300-633a6284-ad4c-4046-9e29-96b2d810b840.PNG)

**Comment by maron2000** [comment]
There also seems to be differences in the diagnosis result.
On a booted PC-DOS2000, Low DMA detection fails.
![guest os_000](https://user-images.githubusercontent.com/68574602/218240018-59c3636e-cb19-48e4-a33d-81441f264260.png)

But succeeds on native DOSBox-X.
![diagnose_000](https://user-images.githubusercontent.com/68574602/218240034-0c392688-3e7b-460d-a3a0-54009dc41ca5.png)

**Comment by joncampbell123** [comment]
> There also seems to be differences in the diagnosis result. On a booted PC-DOS2000, Low DMA detection fails. ![guest os_000](https://user-images.githubusercontent.com/68574602/218240018-59c3636e-cb19-48e4-a33d-81441f264260.png)
> 
> But succeeds on native DOSBox-X. ![diagnose_000](https://user-images.githubusercontent.com/68574602/218240034-0c392688-3e7b-460d-a3a0-54009dc41ca5.png)

I vaguely recall for low DMA the program does something absurd like send a 1 byte DMA transfer for 16-bit playback or perhaps only the L sample of stereo playback. I think it also does a record test as well with 1 byte. It was a long while ago when I patched DOSBox-X to handle test programs of this kind.

**Comment by joncampbell123** [comment]
> Note: using latest release of DOSBoX-X >> [dosbox-x-mingw-win64-20221227040641.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2022.12.26/dosbox-x-mingw-win64-20221227040641.zip) Hi here, been testing to load the Creative SoundBlaster's CTSOUND driver (CTSB16.SYS file specifically) using DOS/V version J5.00 and J7.00 (Japanese) while booting with an HDD image, installing SB16 drivers on the "Guest OS", and in order to use this CTSOUND driver instead of the basic CSP(Low-level driver), added the line on CONFIG.SYS:
> 
> `DEVICE=C:\SB16\DRV\CTSB16.SYS /UNIT=0 /BLASTER=A:220 I:7 D:1 H:5` So, sound card is loaded as Address: 0220, IRQ: 7, Low DMA: 1, High DMA: 5
> 
> Of course, my soundcard has been set on AUTOEXEC.BAT as: `SET SOUND=C:\SB16` `SET BLASTER=A220 I7 D1 H5 P330 T6` Where A parameter is Address, I parameter is IRQ, D is Low DMA, H is High DMA. P is MIDI port address and T is an indicator of what sound card I am setting, so T6 for SB16 card.
> 
> Till this point is all good, but when booting, I get the following error message, telling me argument "D" is invalid on CTSOUND Driver: `ERROR CTSOUND1010: Invalid "/Blaster=D:x" argument.`
> 
> Thanks a lot and wish we can figure out what is causing this issue on DOSBox-X. This is needed in order to run a DOS/V game that requires CTSOUND/CTSB16.SYS loaded on boot in order to be able to detect and play any FM or MIDI sound (BGM/OST of the game). If not, the game just throws an error saying that "Enviroment variable is not set up correctly" in Japanese. So the game proceeds to load, without any FM or MIDI sound, saying that SoundBlaster cannot be used. ![error](https://user-images.githubusercontent.com/26289659/218208300-633a6284-ad4c-4046-9e29-96b2d810b840.PNG)

Do you hear a popping noise while the driver is testing?

When the driver is testing, I get in the DOSBox-X log file:

`LOG:   98897522 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98900241 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98902961 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98905681 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98908401 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98911121 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98913841 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98916561 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98919281 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98922002 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)
LOG:   98924721 WARN  DMA_CONTROL:BUG: Attempted DMA channel read when DMA channel is configured by guest for writing (to memory)`

That would suggest that for whatever reason the DMA channel is programmed to transfer the wrong way from what the sound card is supposed to transfer and that's why it's failing.

**Comment by joncampbell123** [comment]
Hold on... so it's saying the DMA channel is attempting a read when the driver has just issued DSP command 0xCA which is 8-bit PCM record (ADC)? In record mode it's supposed to issue a DMA write to memory. Hm..

**Comment by joncampbell123** [comment]
If you can compile the latest commit, there is new code in the Sound Blaster emulation to properly handle recording DSP commands and send audio back, which also satisfies the DMA test in CTSB16.SYS.

As a nice side effect of how it was added, the framework is now there in the Sound Blaster emulation for recording audio in general, though at this time, only generated fake source are supported. They are: silence, hiss, and a 1KHz test tone. If you record audio in the guest the recording should contain that generated audio.

**Comment by Torinde** [comment]
Great! Only two items remain from https://github.com/joncampbell123/dosbox-x/issues/1824#issuecomment-687309564
> default to the fake silence source until the user confirms with the interface they do in fact intend for the DOS program to record them
> Faking input from a WAV file
_Originally posted by @joncampbell123 in https://github.com/joncampbell123/dosbox-x/issues/1824#issuecomment-687309564_

**Comment by rderooy** [comment]
The problem with faking input from a file, is that you probably need some control over start, pause, stop of that file. Input from the host PCs Mic input may be easier?

**Comment by Torinde** [comment]
I think both are valid options.

Input from file - ideally some UI to control is best, but even without that - can be used just from the begin of the file, when DOSbox-X "uses the mic/input" pointer is moved forward the equivalent of the "passed duration". If DOSbox-X stops using the input, the pointer stops (OK, can be a .conf setting for the pointer to progress in real time after first use the mic). When file finishes - another .conf setting to cycle from the beginning, give silence/hiss/1kHz/second file/etc.

**Comment by rockleevk** [comment]
> If you can compile the latest commit, there is new code in the Sound Blaster emulation to properly handle recording DSP commands and send audio back, which also satisfies the DMA test in CTSB16.SYS.
> 
> As a nice side effect of how it was added, the framework is now there in the Sound Blaster emulation for recording audio in general, though at this time, only generated fake source are supported. They are: silence, hiss, and a 1KHz test tone. If you record audio in the guest the recording should contain that generated audio.

https://github.com/joncampbell123/dosbox-x/suites/10924278675/artifacts/552307721
Tried with this, now I do hear a 'popping' sound when the driver is being loaded, but, still results on same error with DOS/V J5.00 and J7.00, (tested on different HDD images with the above artifacts link):
`ERROR CTSOUND1010: Invalid "/Blaster=D:x" argument.`

Atm do not have my linux machine near, but can test that to rule out it's an issue with Windows if you need confirmation on that end.

Thanks a lot for the fast reply and action on this issue, appreciated.

**Comment by maron2000** [comment]
Currently there are some flaws for all Windows related builds.
You can try the following MinGW build, fixed quite recently.
https://github.com/joncampbell123/dosbox-x/actions/runs/4153286858

**Comment by rockleevk** [comment]
> Currently there are some flaws that all Windows related builds fail. You can try the following MinGW build, fixed quite recently. https://github.com/joncampbell123/dosbox-x/actions/runs/4153286858

Thanks for the link and your contributions @maron2000 !
Just gave it a go and... It works on first try! Can't express enough how great this is. Thanks a lot, as far my issue goes, now it's solved at least for the game in question that started it all "Power DoLLS 2" for DOS/V (ver J5.00 or higher), working flawlessly on both versions that did test before on, J5.00 and J7.00.

Huge thanks to @joncampbell123 for making it possible to run this things on this fork of DOSBox, 
DOS/V is one of my favourite niche(s).
Wish this new addition has many other users hooked on "-X" fork for any program or games that require this driver.

And a small pic showing the driver loading successfully on recent MinGW build:
![image](https://user-images.githubusercontent.com/26289659/218288624-72d612d6-0750-4d60-bb56-35090dbe8f2e.png)
Will make sure to report any other things, if there is any. 
More testing incoming of old software, but first, enjoying a bit of gaming for a while, have a nice day! = D

**Comment by maron2000** [comment]
@rockleevk
I just want to point out that the fixes are not my contribution but @joncampbell123 and @amol- did it all.
Anyway, I'm happy to hear that it worked.
