### ISSUE TITLE
Free space shown is from drive where DOSbox-X executable is, not from the mounted drive

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4004]
### Describe the bug

- DOS version set to 7.1. freesizecap=false.
- SMB share mounted as drive letter in DOSbox-X. 
- Using DIR command in the DOSbox-X shell.
- free space result is wrong: 156.98GB
![image](https://user-images.githubusercontent.com/97228894/218300179-3646cc52-48de-4303-92ec-728d17a02878.png)
- correct free space (from Windows CMD.exe) is ~2TB:
![image](https://user-images.githubusercontent.com/97228894/218300205-37f23a94-e952-4224-b5df-9ee58a46645a.png)
- the 156.98GB is coming from the drive where `dosbox-x.exe` is located:
![image](https://user-images.githubusercontent.com/97228894/218300237-304d829d-3f3e-4585-87fb-e176ea388028.png)
- if `dosbox-x.exe` is run from the SMB share, then DIR gives another wrong result: 544.14GB
![image](https://user-images.githubusercontent.com/97228894/218300375-1a72ad64-808f-458d-897a-da4b89686f78.png)

### Steps to reproduce the behaviour

mount SMB share as as drive letter in DOSbox-X. Execute DIR.

### Expected behavior

Free space from the correct location to be shown. If there is a limitation due to being "too big for DOS", then it should be one of those?
![image](https://user-images.githubusercontent.com/97228894/218300946-529c2116-bff0-41f6-8220-e5e841ca64b9.png)

Seeing that DOSbox-X shell shows properly 8GB files (beyond the 4GB max for FAT32), I assume it's possible to show volume sizes beyond 2TB as well. Please consider that it's feasible to have a volume with dozens of TB free space (a few high capacity HDDs in NAS).

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

SDL1 MinGW64 2022-11-20

### Additional information

Not sure if related to #2157

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
Another thing - when using a freesize cap I get up to a maximum of 1919 MB. Values above give wrong result of 1919MB:
![image](https://user-images.githubusercontent.com/97228894/218303658-1d9c7021-ebb6-4841-a067-7ee6e0bcd8da.png)

**Comment by Torinde** [comment]
OK, so I discovered where the 544.14GB comes from: ~2.5TB (real free space) - 2TB = 544GB. Numbers match and also tested it by adding a 8GB file (which lowered the wrongly reported free space to ~536GB).
So there are three issues:
1. dosbox-x.exe location free size reported instead of the actual SMB share
2. when free size is above 2TB, then is reported the difference (e.g. some counter reaches a limit and overflows?)
3. when cap is used and cap is above 1919 - only 1919 MB are reported

**Comment by Torinde** [comment]
Problems 1 and 2 happen also if using `convertdrivefat=true` and `convert fat free space` (and booting MS-DOS 7.10): 
1. dosbox-x.exe location determines the maximum free space, not the actual mounted drive location.
2. when running dosbox-x.exe from the 2.5TB free location I get ~500GB free in MS-DOS
3. it seems the `convert fat free space` works properly above 1919MB (but I can't really test for values above 540GB, because I don't have more than 2.5TB free space).

**Comment by Torinde** [comment]
@Wengier, can you help with that one please?

**Comment by rderooy** [comment]
He has gone completely inactive, and told me last year he no longer has time to assist. Just look at his git activity level.
https://github.com/Wengier

**Comment by Torinde** [comment]
:( yes, I remember he wasn't maintaining the installers anymore, but I wondered if he wants to do such smaller fix...

It seems "easy":
- one value is coming from the wrong path (CWD vs MOUNT)  
- one variable is restricted to "2TB" and overflows if value goes above that

Can you point me to relevant file(s) in the code? To try finding more and eventually fixing it?

**Comment by Torinde** [comment]
Where is defined "%17s"? Is this the 17th parameter given to the function when called? 

@maxpat78, do you know how to fix this misreporting of the free space?

**Comment by maxpat78** [comment]
> Where is defined "%17s"? Is this the 17th parameter given to the function when called?
> 
> @maxpat78, do you know how to fix this misreporting of the free space?

Not sure you were asking me @Torinde.
However, DosBox-X 2023.05.01 (built with VS tools 2022) actually shows the bytes free on the parent disk (=parent of the mounted folder), not the one where the executable resides - just tried with 4 volumes on Win11.

**Comment by maxpat78** [comment]
Now I see... the problem arises with SMB drives only.

Perhaps the line `uint8_t drive=dta.GetSearchDrive();` in shell_cmds.cpp, line 2080, returns wrong drive number (zero = C: ?) when a Win32 network drive is queried? I'll try to investigate.

**Comment by maxpat78** [comment]
Bug is in drive_local.cpp, localDrive::AllocationInfo, `uint8_t drive=strlen(basedir)>1&&basedir[1]==':'?toupper(basedir[0])-'A'+1:0;` where `basedir` for a SMB is typically in form `\\HOST\path` and not CHAR-COLON -- result is always zero.

**Comment by maxpat78** [comment]
> 2. when free size is above 2TB, then is reported the difference (e.g. some counter reaches a limit and overflows?)
> 3. when cap is used and cap is above 1919 - only 1919 MB are reported

That is more complicated, seems a design choice. 

GetDiskFreeSpaceEx Win32 API would avoid doing calculations and return directly byte sizes... but in _64-bit_ form: `localDrive::AllocationInfo` wants 16-bit answers, in pure ol' DOS fashion... perhaps something like `fatDrive::AllocationInfo32` should be implemented also in `localdrive::`, but probably your multi-TB drives would need 64-bit integers even in such case.

**Comment by maxpat78** [comment]
> Another thing - when using a freesize cap I get up to a maximum of 1919 MB. Values above give wrong result of 1919MB: ![image](https://user-images.githubusercontent.com/97228894/218303658-1d9c7021-ebb6-4841-a067-7ee6e0bcd8da.png)

In src\dos\dos_programs.cpp:
![image](https://github.com/joncampbell123/dosbox-x/assets/2823136/dbab9399-34ee-4163-beb3-c8d781ad1746)
