### ISSUE TITLE
Link to build for Mac OS 10.13

### ISSUE THREAD

**Issue by hxlnt** [joncampbell123/dosbox-x#4014]
### Question

Per the readme: 

> If you have an older macOS version such as macOS High Sierra (10.13) and Mojave (10.14), or you use a newer macOS version but do not need any additional features provided by external libraries such as libslirp or libfluidsynth, you can use the alternative macOS builds below instead, which include both SDL1 and SDL2 versions of the DOSBox-X (named dosbox-x-sdl1 and dosbox-x-sdl2 respectively in the package). These are intended to be builds for "low-end" systems with no need for external libraries to run them in your macOS. Such a build for the latest DOSBox-X version is available from the [DOSBox-X homepage](https://dosbox-x.com/).

I was not able to find these builds; all the links just redirected to 10.15+ versions. Is this information still accurate?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Releases can be built on GitHub Actions but is not the case for deprecated OSs.
Fortunately, there is a hack to build binaries for Windows XP, but it will sooner or later also will become not build-able.
I think those cannot be built on Github Actions are built by volunteers, so you may be the one.

**Comment by Torinde** [comment]
You can see the link to the latest High Sierra build in #3946 
I don't know if newer versions will be released by the developers.
