### ISSUE TITLE
Mismatch Swiss French keyboard touch

### ISSUE THREAD

**Issue by Sebiohazard** [joncampbell123/dosbox-x#4017]
### Describe the bug

Hello I have a problem with the Swiss French keyboard the " \ " key does not work & does not give the right match.

It's very annoying to navigate in a DOS system for example to access " C:\DOS\GAMES " it's just impossible.

### Steps to reproduce the behaviour

Try typing this with a Swiss keyboard: " C:\DOS\GAMES "

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

0.84.3 SDL1

### Used configuration

```ini
keyb sf
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
The first thing you should try for non-US keyboards is to use the SDL2 version, which is clearly mentioned in the README or Wiki, or if you have used the installer you have seen it during the installation.
If you want to try SDL1, try changing `usescancodes=true`.

**Comment by maron2000** [comment]
Good to hear that it worked!
