### ISSUE TITLE
Windows 98 Black Box Mouse Cursor

### ISSUE THREAD

**Issue by Slo2018** [joncampbell123/dosbox-x#4030]
### Describe the bug

If i set more then 16 Colors in Windows 98 i have Black Box Mouse Cursor (see picture):

![2023-02-22_035053](https://user-images.githubusercontent.com/45156187/220509095-bde9b541-3529-495e-8b36-42207188577a.png)

### What operating system(s) this bug have occurred on?

Windows 11

### What version(s) of DOSBox-X have this bug?

2022.09.0

**Comment by rderooy** [comment]
Did you follow the Win98 guide on the dosbox-x wiki?
