### ISSUE TITLE
Windows: VS2017 custom build step to patch EXE version numbers to make XP compatible

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#404]
Write a tool that VS2017 can run as part of a custom build step.

It should compile first, as a dependency of DOSBox-X.

Then, when DOSBox-X is finished compiling, the custom build step runs the tool against the binary to patch the OS version in the PE header to make it run under Windows XP (to version 5.1)

This is preferable to the "Windows XP" target in VS2017 because of broken C runtime functions in that toolset like _stat().

**Comment by roytam1** [comment]
There is a tool already:
https://github.com/roytam1/rtoss/blob/master/pehdr/pehdr-lite.c

**Comment by joncampbell123** [comment]
@roytam1 OK that will work. Let me try it.

**Comment by joncampbell123** [comment]
Apparently _stat() is broken on XP no matter whether you target XP, or target Vista and patch the OSVersion to XP.

![image](https://user-images.githubusercontent.com/6245486/34321337-273b6528-e7c1-11e7-8bc4-e02920a10e04.png)

**Comment by joncampbell123** [comment]
It seems we'll have to take the VS2013 route for XP compatibility. Fine.
