### ISSUE TITLE
Reduce flickering of rapidly redrawn graphics

### ISSUE THREAD

**Issue by evertvorster** [joncampbell123/dosbox-x#4040]
### Is your feature request related to a problem? Please describe.

I am reviewing games from the early 1980's at the moment. As such, I am also recording the output from DOSBox-x with OBS studio.
There is a small problem that pops up with the high refresh rate and low frame capture rate. Games of the era relied on the afterglow effect of the phosphor displays to temporally reduce flickering of rapidly redrawn graphics. 
The method worked like this
1. draw graphic
2. blank it out
3. draw graphic in a slightly different place. 

At the time, it worked great, and no one noticed. 
However, now with much faster response times on displays it is very noticeable. Also, as I am only capturing less than half the frames produced, I see this even more. 

Here is a short video of the effect described:

https://user-images.githubusercontent.com/12045269/221840577-400c90d4-0e7b-4def-816f-8fe4ae06b4a1.mp4

The "Novatron" that is bouncing around should be fully drawn every time, but it's not. 

### What you want

A video filter that smooths the frames temporally. 

Each time a graphic is drawn, if the next frame is black in that area it needs to have some "afterglow" of the graphic that was just there, just like what used to happen on the phosphor displays at the time. 
Ideally, there should be a value that you can set for this fade. Maybe in frame redraws? 0 for off, 1 for one frame persistence, and so on... 

### Describe alternatives you've considered

I have tried different output options on DOSBox-x

### Additional information

I am running on Linux, but I suppose everyone that is playing games of the era would be interested in smoother graphics?

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by evertvorster** [comment]
I guess I am looking for a what to make sure that each time the graphics are fully drawn, this does not seem to happen reliably, and quite often I am seeing large parts of the graphics are missing in the captured video.

**Comment by grapeli** [comment]
If you want to avoid flickering in Novatron (1982) in the main menu, you have to run it with `machine=cga` or `machine=tandy`.

**Comment by evertvorster** [comment]
On your example it flickers. 
I just tried it on my machine, and it also flickers. How can we get DOSBox-x to fully draw the bit that is moving?

https://user-images.githubusercontent.com/12045269/221901791-2bd0902e-d51a-4fab-8965-7a981bce60d0.mp4

**Comment by grapeli** [comment]
Regarding your last recording, it's not surprising if this sequence flickers. Your recording is at 25 fps, and the actual number of frames during the scrolling credit is **11.6**. Far too little.

**Comment by BridgeHeadland** [comment]
[TANDY.zip](https://github.com/joncampbell123/dosbox-x/files/10853815/TANDY.zip)
I don't know which output value you prefer to use, but this batch file automatically restarts the DOSBox with Tandy output, you don't have to reconfigure the output in the config file so much.

**Comment by evertvorster** [comment]
OK, there does seem to be some miscommunication here. Maybe calling it a flicker is the wrong terminology. Most frames are not fully drawn on my display, and it does not matter what graphics card I use, VGA, CGA, tandy of pcjr, they all do it.
From the video you sent, the frames are not fully drawn on your display either. The following images are frames from the video you posted, which was captured at 60fps. 
As you can see, some of the images the "NOVATRON" text does not show at all, and in most of them it is not properly drawn. 

![untitled_00001](https://user-images.githubusercontent.com/12045269/221976654-396ddef2-3e59-4fe5-9bf2-00885cbb1625.jpg)
![untitled_00002](https://user-images.githubusercontent.com/12045269/221976663-618081db-d778-4141-8fbc-14299afcfa88.jpg)
![untitled_00003](https://user-images.githubusercontent.com/12045269/221976670-510fd769-fcab-41a0-b55c-212ff00e8e11.jpg)
![untitled_00004](https://user-images.githubusercontent.com/12045269/221976676-22f29d4c-04ec-4b5e-8bd9-0b0bc4df370e.jpg)
![untitled_00005](https://user-images.githubusercontent.com/12045269/221976678-f6a33af1-9d75-40ae-a3c2-05ba9eecf18d.jpg)
![untitled_00006](https://user-images.githubusercontent.com/12045269/221976682-f63cf663-ec8b-4682-89e7-bd6b3bf6d081.jpg)
![untitled_00007](https://user-images.githubusercontent.com/12045269/221976688-b52c6291-16b6-434f-8bbe-3ff550b28c96.jpg)
![untitled_00008](https://user-images.githubusercontent.com/12045269/221976696-9887e1fc-84b9-48b5-b43f-2dedacea5278.jpg)
![untitled_00009](https://user-images.githubusercontent.com/12045269/221976704-2b92900f-54a0-41ee-8c90-523ab14916ff.jpg)
![untitled_00010](https://user-images.githubusercontent.com/12045269/221976707-e016ec85-540f-4a6c-ad83-2ab516724ed4.jpg)
![untitled_00011](https://user-images.githubusercontent.com/12045269/221976716-0968c038-60e4-4612-8ae5-558c378f7d8a.jpg)
![untitled_00012](https://user-images.githubusercontent.com/12045269/221976721-ee5c7a27-90a2-41fc-8708-b0c5fc1cece0.jpg)
![untitled_00013](https://user-images.githubusercontent.com/12045269/221976722-677c8515-9afc-4077-b293-d76be631aaa9.jpg)
![untitled_00014](https://user-images.githubusercontent.com/12045269/221976725-52a54059-c627-426d-9370-07c15cffedc5.jpg)

How do I make DOSBox-x wait for a frame to be fully drawn before displaying it? (and then keeping on displaying that frame until the next is fully drawn) 

I have been messing around with the vsync rate, but this did not seem to have any effect. 

Where did you get the 11.6 from?  

Oh, and thank you for looking into this!

**Comment by evertvorster** [comment]
After reading up a bit on this, it appears that the CGA adapter had no buffer to write into, so everything was written to the active memory, and as the CPU was fairly slow on these machines, you can actually see it happening. 

For my application, I am going to set my video recording to 60fps, my screen refresh rate is already 60fps, and lock vsync of CGA games to host. In this way, even though the sprites are not fully drawn on some frames, it simulates what was done in real time back then, and when you watch the video at 60fps, your eyes will fill in the missing redraws, just like old times!

**Comment by joncampbell123** [comment]
You might try:

- Set the CPU cycles count down to IBM 5150 levels (somewhere between 300 and 1000).
- Set the vmemdelay option to larger values (300, 600, 1000, 1200) in nanoseconds to slow down access to video memory to try to emulate the slow CGA video memory.

**Comment by grapeli** [comment]
My recording is at cycles=300. Different vmemdelay values have no apparent effect.

**Comment by evertvorster** [comment]
@joncampbell123 Thanks so much for looking at this.
For games of the era, I have my cycles set to 240. There are a couple of games for which this is too fast still! In one game I had to go down to 80 cycles for it to be playable, which can't be right. 

But, I digress. 

For the current matter, my plan of locking the vsync did not work so well, as that messes with the sound. 
So, the emulator runs unlocked, and the recording happens at 60fps, and the flickering is so fast now that my eyes fill in the blanks and it's almost not noticeable. It is certainly good enough for what I want to do with it. 

Saying that, I also tested the vmemdelay, and I tried values as high as 120000 with no appreciable effect.

**Comment by grapeli** [comment]
https://user-images.githubusercontent.com/452325/222674875-1149fa2e-1214-4862-a852-14ca6c2b647a.mp4

You want this text to not fade away, to achieve the opposite effect from the intended one.

The text should disappear and reappear. Look carefully at what is happening with the NOVATRON inscription on real equipment. It shifts and gradually disappears and reappears. In the final phase, when the pcspeaker is activated, the fade-out frequency changes radically (the text flashes).
The only sensible settings for dosbox-x are `CGA` mode, `cycles` value in the range of 290-320.

Don't set absurd `vmemdelay` values. In the description you can read what they are recommended.
