### ISSUE TITLE
in game "Seal Magic Eye" - graphics error, incorrect videomode

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#4042]
### Describe the bug

Hi.
In game "Seal Magic Eye / Moyan Xieshen / 魔眼邪神" (RPG/1994/DOS) there is some graphic error, incorrect videomode.
Compared to Dosbox Daum build:
Normal (Dosbox Daum): 
![image](https://user-images.githubusercontent.com/7928889/222032226-23692244-d084-4ecf-987d-fbbf8f33abf6.png)
Bad (Dosbox-X):
![image](https://user-images.githubusercontent.com/7928889/222032381-37718286-d8a3-49de-9c1d-ae39efb18104.png)

Game to test:
http://coraksoft1.narod.ru/games/RPG/Seal-Magic-Eye-GameTChn.7z

### Steps to reproduce the behaviour

Game to test:
http://coraksoft1.narod.ru/games/RPG/Seal-Magic-Eye-GameTChn.7z

### What operating system(s) this bug have occurred on?

Windows XP

### What version(s) of DOSBox-X have this bug?

latest

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
Works fine with:
`dosbox-x -set 'ignore odd-even mode in non-cga modes=true'`.

**Comment by maron2000** [comment]
Based on @grapeli 's findings and https://www.vogons.org/viewtopic.php?t=45808, it seems that odd-even mode should be ignored for mode 13h, which is I believe `vga.mode == M_VGA`.
Maybe @joncampbell123 have some ideas about this?

```diff
--- a/src/hardware/vga_memory.cpp
+++ b/src/hardware/vga_memory.cpp
@@ -308,7 +308,8 @@ template <const bool chained> static inline void VGA_Generic_Write_Handler(PhysP
      * 
      * NTS: Real hardware experience says that despite the name, the Odd/Even bit affects reading as well */
     if (chained) {
-        if (!(vga.seq.memory_mode&4) && !non_cga_ignore_oddeven_engage)/* Odd Even Host Memory Write Addressing Disable (is not set) */
+        if (!(vga.seq.memory_mode&4) && !(vga.mode == M_VGA) && !non_cga_ignore_oddeven_engage)/* Odd Even Host Memory Write Addressing Disable (is not set) */
             mask &= 0xFF00FFu << ((rawaddr & 1u) * 8u);
         else
             mask &= 0xFFu << ((rawaddr & 3u) * 8u);
```
![ingame_000](https://user-images.githubusercontent.com/68574602/222150202-3c2df4fa-bf17-4d56-b579-b85cb5d1d59a.png)

**Comment by joncampbell123** [comment]
I just realized I got this confused with the usual conversations I have with DOSBox Staging :)

I'll go ahead and add this to DOSBox-X default on for 256-color mode.

I want to add that odd/even mode should be emulated by default for all other standard VGA modes including 16-color planar because I think that's what standard hardware does *and* I think odd/even mode might be key to the poorly understood EGA 640x350 4-color planar mode that was reportedly offered by IBM EGA cards that had only 64KB of video RAM.

To explain why, 640x350 16-color mode requires 80*350 = 28000 bytes per bitplane. 64KB would mean a maximum of 16KB per bitplane. Note that 640x200 is 80*200 = 16000 bytes per bitplane and 320x200 is 40*200 = 8000 bytes per bitplane. Supposedly the 4-color mode was just 2 bitplanes tied together. I think odd/even mode in planar graphics might be key to making such a mode work.

**Comment by joncampbell123** [comment]
Alright. Here's what I've noticed about the game.

First, you need to add under the [dosbox] section:

    ignore odd-even mode in non-cga modes=true

Second, even if the game displays somewhat normally, the random garbled water on the screen when the game starts, and the artifacts when the water animates will remain even if you do this, *unless* you also add or set:

    machine=svga_et4000

I also notice the files of the game are dated 1993, which is generally when Tseng ET4000 cards were widely popular on PCs. I think this game was written on ET4000 cards and never really tested much on other VGA hardware. It's not too unusual, there's a lot of pre-1994 Demoscene stuff with the same problem.

Whether Tseng ET4000 cards ever pay attention to odd/even in 256-color mode given the odd way they do "chained" 256-color mode compared to normal VGA is another matter I must test.

**Comment by joncampbell123** [comment]
Reading the link... that would make sense at a hardware level to either do chain 4 (bit 3) or odd/even (bit 2) because doing both at the same time is rather silly.

**Comment by joncampbell123** [comment]
Latest commit should run it as well as standard VGA. For flawless VGA emulation for this game, use machine=svga_et4000.
