### ISSUE TITLE
Running 64-bit software inside DOSBOX-X

### ISSUE THREAD

**Issue by Infopaie** [joncampbell123/dosbox-x#4044]
### Question

Is it possible ? If yes, how ?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
This is not possible directly. I don't think that will ever be possible in the future.

You can only run such code through another emulator for example, qemu. This also applies to other architectures - arm, mips, etc.
Some time ago I prepared a minimal [x86_32 linux image](https://github.com/copy/v86/files/9285244/qemu.copy.sh.img.zip) with qemu-system-x86_64 and bootable x86_64 linux for [copy.sh](https://github.com/copy/v86/discussions/585#discussioncomment-3353201) testing purposes.

It also works under DOSBox-X.
`dosbox-x -set cputype=pentium_ii -set memsize=62 -c 'imgmount 2 ./qemu.img' -c 'boot -l c'`
Once 32-bit linux is loaded, press cursor up and enter.

![guest os_000](https://user-images.githubusercontent.com/452325/222488789-fa7621e8-12e4-4396-a17f-d4900d0b05f4.png)

**Comment by joncampbell123** [comment]
x86_64 came too far after the MS-DOS era for DOSBox-X to consider supporting.

DOSBox-X is only concerned with 32-bit systems during and before Windows XP. I have to do this cut off or the DOSBox-X codebase would become far messier than it already is now :)

If you need x86_64 please use an emulator better built to support it including Bochs, QEMU, and VirtualBox.

**Comment by Infopaie** [comment]
No problem. I found another way like pausing my software when 64-bit
program will run outside DOSBOX and then resume after. Thank you anyway !

*Bonne journée !*

*PS : notre nouvelle adresse postale et notre nouveau numéro de télécopieur
:*

*979, rue Caron, local 309*
*Granby (QC)   J2J 2R9*
*Fax : (450) 915-0207*



*www.infopaie.com <http://www.infopaie.com>*
*www.facebook.com/Infopaie <http://www.facebook.com/Infopaie>*

*Alain Roy,*

*Infopaie*


Le jeu. 2 mars 2023 à 17:00, Jonathan Campbell ***@***.***> a
écrit :
