### ISSUE TITLE
MinGW builds not working due to video_debug_overlay

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4051]
### Describe the bug

> [e2d9c60](https://github.com/joncampbell123/dosbox-x/commit/e2d9c60c853119e1d9be6c7d2685283be6dc7e1c) to [4823def](https://github.com/joncampbell123/dosbox-x/commit/4823def4ea9fdf44b1e943d65789b481e35744d7) Because of `E_Exit:DOSBoxMenu::get_item() No such item 'video_debug_overlay'` message mingw32 and mingw64 cannot run，build is ok vsbuild is working and run ok

_Originally posted by @yxmline in https://github.com/joncampbell123/dosbox-x/commit/4823def4ea9fdf44b1e943d65789b481e35744d7#commitcomment-103089243_

### Steps to reproduce the behaviour

Per report above all minGW builds don't work.

I tested minGW-lowend in WinXP x86 - got the same error message.

### What operating system(s) this bug have occurred on?

WinXP and maybe others

### What version(s) of DOSBox-X have this bug?

4823def

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
The code to add it was mistakenly put within a #if C_DEBUG block, and MinGW builds do not have the debugger.

**Comment by Torinde** [comment]
Logo is OK in latest build.

During testing (changing Surface/D3D/OpenGL/TTF from the menu and restarting to see the logo) I saw that if you run the dosbox-x.exe without anything else (e.g. without .conf file) - it's a little bit iffy, sometimes Restart/Reset doesn't work (e.g. window closes, but no new window appears).

That's not a common situation, of course, but mentioning it in case it's easy to solve (e.g. add if some default value for a setting is missing).
