### ISSUE TITLE
Option to disable warning window "Recording completed" on every screenshot

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#4060]
### Describe the bug

Hi! 
Is there any option to disable warning window "Recording completed" on every screenshot? I didn't found.
![image](https://user-images.githubusercontent.com/7928889/223644505-fbc044d4-0b66-45a8-82cf-815fa6ddfd92.png)

### Steps to reproduce the behaviour

Make screenshot

### What operating system(s) this bug have occurred on?

Windows XP

### What version(s) of DOSBox-X have this bug?

latest

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
```
[dosbox]
show recorded filename=false
```

`dosbox-x -set 'show recorded filename=false'`

**Comment by Corak667** [comment]
> ```
> [dosbox]
> show recorded filename=false
> ```
> 
> `dosbox-x -set 'show recorded filename=false'`

Thanks! It works!
