### ISSUE TITLE
Problem with a CGA Math game from Atlantis Software

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#4062]
### Question

I haven't played this math game in almost 30 years, so I don't remember the title, even though I have the floppy disk. All I know is that it's an Atlantis Software game and the executable is MATH.EXE.
Problem is, even if I have the floppy in the floppy drive, the files in a mounted folder - which emulates an A drive, or both, I still get the message to insert the floppy, as if it's not in there.
I don't know if it's a DOSBox thing or if there's something wrong with the files. I load the contents from the disk, which are identical to the files of the pre-installed game - No, I can't run the game from either the disk drive or the main drive.
![image](https://user-images.githubusercontent.com/85258509/223785919-6fd28cab-10c0-4486-9451-a4135a2f1219.png)
[MATH.ZIP](https://github.com/joncampbell123/dosbox-x/files/10923229/MATH.ZIP)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
It may be looking for the floppy disk based on the LABEL, so if you use folder mounts, you must supply the label of the original disk.

Or just a disk image instead (IMGMOUNT), as that will include the label.

**Comment by Allofich** [comment]
I can confirm the described behavior. I tried also setting LABEL to MATH and ATLANTIS, but no luck with either. No luck when running from a booted MS-DOS either.

I can't find any information about this game online. BridgeHeadland, you said you have the floppy. Do you mean the real physical floppy? Do you have a floppy drive in your computer? If so, can you try starting DOSBox-X with the floppy inserted, then at the Z: prompt, typing "imgmake -source a". I think this should create a floppy image file called IMGMAKE.IMG in your DOSBox-X folder. If you are able to do that, can you then post the IMGMAKE.IMG file here?

**Comment by joncampbell123** [comment]
It's not using DOS to read the volume label. I see it trying to read the boot sector of the floppy drive using INT 13h which it could probably pick out the volume label that way.

When you mount a local folder as a drive, that INT 13h emulation isn't available. You need to find a floppy disk image of the game, not just the files.

**Comment by Allofich** [comment]
All the files from the posted .zip taken together are only 291 KB all together, so it may have been on a 360K floppy.
I can't find any mention of this game online. It would be nice to get an image file of it online to prevent it from being lost.
I haven't used "imgmake -source a" before, but will that create an appropriate .img file? Or are extra parameters needed, like maybe the size of the image file to make?

@BridgeHeadland, do you have a floppy drive that can read the disk, and can you try what I asked above? Also if you can take a photo of what the disk looks like and post that, it would be good for preservation.

**Comment by BridgeHeadland** [comment]
@Allofich 
![image](https://user-images.githubusercontent.com/85258509/224491844-1ac4fa04-c938-4de1-bcc1-acd5b11988fb.png)
![image](https://user-images.githubusercontent.com/85258509/224492182-f3466e98-42a2-446e-92ed-7603001e6325.png)
![image](https://user-images.githubusercontent.com/85258509/224492429-c42b4c55-b01c-4472-a745-6a1a91e194e3.png)
I tried but it didn't work, as you see, and as you see on the disk, the title is 'LETT MATEMATIKK'. It is Norwegian for 'EASY MATH'.
I remember on the title screen that there was a drawing of a guy thinking and pondering.
I mean to recall that it is this CGA palette that was used in the game.

**Comment by Allofich** [comment]
Thank you for trying and for the picture. Wouldn't "LETT MATEMATIKK" be the title? I can't find any information on it online, though.

@joncampbell123 Does the output from imgmake mean anything to you? Any idea how it could be made to work or does it look like the disk is damaged?

@BridgeHeadland Are you able to check the label of the disk? Such as by going to A: at a DOS prompt and typing DIR to see the label, or I think you can see it in "My Computer" if you have the disk in the drive in Windows. Did you make the MATH.ZIP that you attached above by reading files from the disk?

**Comment by Allofich** [comment]
BTW as you can see the disk cover instructs to use A > ATLANTIS to run the program. In the attached MATH.ZIP above, ATLANTIS is a batch file containing:

```
echo off
math !%%
```

Running it causes "echo off" to be printed to the screen and then you are returned to the prompt. The program doesn't run and no message about drive A.

**Comment by joncampbell123** [comment]
Does that output mean that track 51 is bad or that sector 51 is bad.

I wonder if it would be possible to combine the incomplete image read (skipping over the bad sectors) with a fresh disk image of the files provided. It looks (so far) like all we need is the first track, sector 0.

**Comment by Allofich** [comment]
I made an 360K floppy image of the unzipped contents of MATH.ZIP the other day. It has the same issue of not starting.
[IMGMAKE.zip](https://github.com/joncampbell123/dosbox-x/files/10948952/IMGMAKE.zip)

Should @BridgeHeadland have an incomplete image file in his DOSBox-X directory after having run imgmake? If not, do you know how to capture the incomplete contents?

@BridgeHeadland Can you check if such a file was created in your DOSBox-X directory and, if so, upload it here?

**Comment by joncampbell123** [comment]
If the program doesn't delete the file when it gives up, there should be an incomplete disk image file you could at least use.

**Comment by Allofich** [comment]
@BridgeHeadland, sorry for so many questions and requests, but one more thing I want to ask is, are the files in the MATH.ZIP that you attached unmodified files from the disk? If you are not sure that they are, can you make a new .zip file of the unmodified contents? (and check the disk label while you are at it)

No hurry on any of this, just whenever you may have time. Thanks.

**Comment by Allofich** [comment]
Looks like the incomplete file should still be there.
Here is the failure case code, in `dos_programs.cpp`.

```
            // maybe delete f if it failed?
            if(!ReadDisk(f, src.c_str()[0],retries))
                WriteOut(MSG_Get("PROGRAM_IMGMAKE_CANT_READ_FLOPPY"));
            fclose(f);
            if (setdir) runRescan("-Q");
            return; 
```

**Comment by joncampbell123** [comment]
Ah, even if you run "MATH !%%" it still checks INT 13h AND it pokes at the floppy controller registers 3F0h-3F6h.

**Comment by joncampbell123** [comment]
Apparently DOSBox-X floppy emulation isn't good enough for it, so it hangs.

I also see in the IRQ 6 handler a fair bit of self modifying code to deliberately hang unless certain criteria are met. There's a JMP $ (jmp to self) that another part of the IRQ handler patches with NOP NOP if the right criteria is met.

**Comment by BridgeHeadland** [comment]
@Allofich It doesn't matter if you ask a lot of questions. :)
The files in MATH.ZIP are all the files from the diskette. One thing I have noticed is that the PARAM file is not a special type of file, but just a file. I opened it with HEX Editor and it said ".YY" (without those quotes, of course ;)), I don't know what things like that mean.

**Comment by Allofich** [comment]
Regarding the PARAM file, it shows up in the `HDINST.BAT` file.

The contents of that file are

```
c:
cd..
cd..
md math
cd math
copy a:*.*
a:
math<param
```

That moves to the C: drive, creates a directory called "MATH" and copies all the files from A: into it, then moves back to A: and executes MATH.EXE with the contents of "param" as input. Maybe ".YY" (in hex 1B 59 59) tells MATH.EXE to run from the hard drive. It still won't start this way in DOSBox-X, though.

**Comment by joncampbell123** [comment]
\**snort*\* In "hard disk" mode, run from drive C: under C:\MATH, it calls INT 25h to read the first sector of your C drive. Except it reads sector 1 instead of zero, which would suggest it's looking for the first sector of the FAT table? Is it trying to read the media type byte stored in the first two FAT table entries?

**Comment by Allofich** [comment]
I can't get it to run in 86Box, either. I made a new, 1.44 MB-sized image to test with because the BIOS I'm using on that emulated machine (80386DX) didn't have an option for a 360 KB 3 1/2 inch floppy drive. It either hangs if run with the disk image in drive A, or if run from drive C without anything in drive A, it asks for the disk.

@BridgeHeadland, please do upload the incomplete image file that should have been created when you ran IMGMAKE. It should be a file called IMGMAKE.IMG in your DOSBox-X folder, or another name if you specified a different file name. The image file I uploaded is not a replacement for the incomplete image file you made.

**Comment by joncampbell123** [comment]
I guess you're going to have to "crack" the game.

From ripsaw8080 on the Vogons forums:

That game executable is inside a copy protection wrapper, a commercial protection named Cop's Copylock II, somewhat akin to another commercial protection wrapper, Rob Northen Copylock. There are anti-debugger tricks, execution-time decryption using the trap flag (trace decoding), and multiple decryption steps that only occur after each of several disk checks. However, unlike RNCL there is no data needed from the original disk in order to decrypt -- only debugger skill and patience are required.

A relatively complete FDC emulation would be needed to support the protection, but a standard disk image (only sector data) is not sufficient, and in fact some more advanced image formats are not sufficient. The most difficult aspect of the protection is that it measures sector gap timing, and my understanding is that only Transcopy and Kryoflux images containing multiple rotations could possibly (not certainly) satisfy the timing check.

**Comment by Torinde** [comment]
dosbox-staging/dosbox-staging/issues/1671:
> TC DOSBox binaries have been released by NewRisingSun, which allow handling of the TC image format. Unfortunately he has explicitly refused to share these modified DOSBox sources when asked.

Comment is for another game, Boppie's Great Word Chase (1985) and there's a [binary](https://github.com/dosbox-staging/dosbox-staging/files/8693734/tc_dosbox.zip).
