### ISSUE TITLE
Is it possible to change the device name of the CD-ROM drive?

### ISSUE THREAD

**Issue by Kurist2010** [joncampbell123/dosbox-x#4066]
### Question

The CD-ROM device name when booting with DOSBox-X is "MSCD001", but is it possible to change it to something else?

In particular, when using in PC-98 mode, it may be assumed that the standard CD-ROM device name is "CD_101", so it would be nice if it could be set arbitrarily.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
That's a good idea. It turns out it was fairly trivial to add. The latest commit will add a dosbox.conf option to control the device name.

**Comment by joncampbell123** [comment]
Done
