### ISSUE TITLE
Is it possible to config dosbox running win95 as sandbox?

### ISSUE THREAD

**Issue by cwz0522** [joncampbell123/dosbox-x#407]
I want to run win95 in sandbox, but after config -securemode, boot is blocked.
Is there any way to booting win95?

or, is it possible to have a secureboot option, like to assign a hash value to do protection?

**Comment by joncampbell123** [comment]
I don't think the securemode code was written with that in mind.

I think the securemode was intended for the DOSBox DOS environment only.

**Comment by cwz0522** [comment]
You mean there is no way for virus in guest OS to infect host after boot command?

And, the guest OS has no way to use DOS function or utilities?

**Comment by joncampbell123** [comment]
Right. Once you boot a guest OS, the DOSBox DOS environment unloads and all built-in commands become unavailable.

**Comment by cwz0522** [comment]
Great! Thanks for the good project.
