### ISSUE TITLE
Unable to mount a hard drive image created external to dosbox-x

### ISSUE THREAD

**Issue by nt4boy** [joncampbell123/dosbox-x#4073]
### Question

Hi. Trying to run a laptop in DosBox-x. I cloned the drive, and ran sysprep for W98 on the clone, so it will rebuild its drivers in any new environment.
This prepped drive has been imaged using vmware-vdiskmanager and will boot ok into vmware and build into a running VM.
I'd like to try this in DosBox-x and have failed totally to turn this vmdk into an image that DosBox-x can read.
If I use imgmake -t hd_8GB 8GB.img I get a raw file.
I can attach my prepped vmdk to an Ubuntu vm and also the 8GB.img as a/dev/loop10. using losetup -f -P
I then tried dd if=dev/sda1 (the vmdk boot partition) of=/dev/loop10p1.
Back in w10 world, this image can be archive opened with 7zip, and reads with all its files apparently present.
If this .img is mounted in Ubuntu, its a bootable FAT32 LBA drive again with all its files present.
In DosBox-x, I can mount this as drive C, but its not seeing any data as below. (Vol serial number is correct..)

Z:\>dir c:

 Volume in drive C has no label
 Volume Serial Number is 07CF-0411
 Directory of C:\

W wX t$¶ Φ¶¶      2,779,096,485 11/04/2038 11:38 W wX t$¶.Φ¶¶
    1 File(s)     2,779,096,485 Bytes
    0 Dir(s)      2,072,674,304 Bytes free

Z:\>
fdisk reports
Partition Status Type Vol Label MBytes System Usage
C: 1         A        PriDOS    None  8033   Fat32ext  100%
Any advice on a better way to make this image work, gratefully received

I have already tried Starwind, and qemu converters. also various types of VHD file.

Thanks

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Works flawlessly.
![starwind](https://user-images.githubusercontent.com/68574602/224676270-ac420fdc-fd5a-46ea-9889-4b566c79b569.png)
![command_001](https://user-images.githubusercontent.com/68574602/224676384-5476b6bc-a96c-4b6f-af8a-8a676d7539c6.png)

**Comment by maron2000** [comment]
I forgot to mention, you may have to try with the nightly (development) builds since there were some fixes regarding VHD support.

**Comment by nt4boy** [comment]
Thanks for looking,
I get this.
![image](https://user-images.githubusercontent.com/113193761/224679739-76f5fc05-3a6e-4399-a975-7286a72a25a1.png)

I'll try another build.

**Comment by nt4boy** [comment]
Sorry, one stupid question. What is the SDL build and should I be using it?

**Comment by maron2000** [comment]
There are plenty of useful information in the docs, not only regarding the differences between SDL builds.
https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md
You may also want to consult the Wiki.

**Comment by nt4boy** [comment]
Tried the latest Nightly build, still the same answer.
What type of vmdk did you Starwind convert to vhd?
I'll try to populate the empty img by mounting the vmdk in Windows and then xcopying in DOS BOX-X.
Might at least get the files to be visible, then find a way to sys it from a win98 floppy.

**Comment by nt4boy** [comment]
Oh yes, read your link to the SDL builds and none the wiser sadly.
So will continue with the defaults.

**Comment by nt4boy** [comment]
Success of sorts.
![image](https://user-images.githubusercontent.com/113193761/224769730-7c6e5cc7-9bf1-447d-90d4-e24adac4f272.png)
Bit long winded as of course xcopy isn't the right tool. Actually copied the files from my vmdk to img file using rsync in linux VM in the end.
Used the w98 Conf file from the wiki. Mounted and booted from a floppy image and mounted the img as C: Sys'ed C: and lo, it boots. Sadly asking for a TouchPad Synapsis driver I don't have, and now locked up at the second reboot where you start Windows proper.
![image](https://user-images.githubusercontent.com/113193761/224779936-f53b4340-d7c1-49fb-aa13-69bcab18d182.png)

**Comment by nt4boy** [comment]
I am still clueless about what I might try to get this to work. To me the point of using the SysPrep tool on the original image, was that it would rebuild the hardware driver setup from scratch, and therefore be like a fresh W98 install. Which from you wiki installs fine.
One other thing I maybe ought to mention is that this image is a W98 First Edition, not SE.
Am I maybe asking this question in the wrong place?
Thanks

**Comment by rderooy** [comment]
I have no experience with SysPrep. I wrote the wiki installation guides, and for that tested with all major retail/oem versions of Win9x, including the original Win98. For more regular testing, I typically only test with 98SE.

I do normally use answer files, as I cannot be bothered to sit there answering questions when doing an install test.

**Comment by nt4boy** [comment]
Thanks for your response Robert.
The project I am involved with is to preserve venerable laptops used to fire up old F1 and Indycars. Hence the desire to keep the installed software intact.
I’ve had some success with VMWare, but it’s not as stable as I would like with W98 hence this adventure with DOSBox-x.
I guess I should try and install and run a clean out of the box W98FE for myself in my environment.
What is an answer file by the way?
Rupert


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nt4boy** [comment]
Sorry, an answer file is the msbatch.inf. That sysprep knows about.
I used a basic one of those, but could have paid more attention to its contents perhaps.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rderooy** [comment]
To be frank, the Win9x support in DOSBox-X has quite a few problems with emulation. You may want to consider something like 86box if you need more accurate emulation.
