### ISSUE TITLE
King's Quest I - Quest for the Crown (1990 SCI version) install from .img files fails

### ISSUE THREAD

**Issue by Wilstorm** [joncampbell123/dosbox-x#4075]
### Question

I've been trying to install King's Quest I (1990-SCI version) from .img files but it fails. I get the initial install screen shown below (which is correct). The next screen should allow you to pick your adapter/monitor combo. In dosbox-x it drops me back to the a: prompt with no errors. 

I also tested with regular dosbox and it works fine, which is shown in the second screenshot. That is the next screen that should pop up. 

I am running dosbox-x 2022.12.26 (SDL1) on Windows 10. I also tried SDL2 to the same effect. Do I need to tweak my config possibly? Thanks for any help provided!

![image](https://user-images.githubusercontent.com/8192258/224752151-8d2ff871-5a3a-4a44-80d7-4cf3bc276a6e.png)

![image](https://user-images.githubusercontent.com/8192258/224751989-d8fa20fe-a9b0-49f8-8ab8-979b4929f640.png)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
Works fine in dosbox-x just run `loadfix -a` first and then `install.exe`.

You can achieve the same effect with the right configuration:
`dosbox-x -set hma=false`
or 
`dosbox-x -set a20=off`
or
`dosbox-x -set dos="low,umb"`.

**Comment by Wilstorm** [comment]
@grapeli - Thanks a bunch for the help, that worked perfectly. I also updated the title to reflect the proper game. Thanks again and have a good day! :)
