### ISSUE TITLE
Thexder (sierra game) doesn't launch. Works fine on plain DOSBox.

### ISSUE THREAD

**Issue by scrutinizer80** [joncampbell123/dosbox-x#4078]
### Describe the bug

Trying to launch the game under DOSBOX-X fails with a "Packed file is corrupt" error.
Same game launches fine on plain Dosbox.

### Steps to reproduce the behaviour

Launch thexder.com.

### Expected behavior

Game should load.

### What operating system(s) this bug have occurred on?

Windows 11, x64.

### What version(s) of DOSBox-X have this bug?

2022.12.26 (SDL2) (mingw)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by gfernval** [comment]
What exactly does "loadfix -a" do? it seems it is mandatory in running many games.

**Comment by scrutinizer80** [comment]
> A search in the git issues here, which you indicated searching, would have provided you with the answer. As would a simple google search.
> 
> run `loadfix -a` before starting the game.

I guess I missed that one.
What does loadfix do exactly? and why is it needed in dosbox-x and not in plain dosbox?

**Comment by joncampbell123** [comment]
Some games crash or malfunction if loaded too low in conventional memory (below the 64KB mark) if extended memory is enabled and the A20 gate is on.

The purpose of "loadfix -a" is to allocate and occupy all free space below the 64KB mark so that those games work again.

https://www.os2museum.com/wp/the-a20-gate-it-wasnt-wordstar/

**Comment by grapeli** [comment]
Repeated reports of this problem start to get tiresome in the long run. Again, still this "banal" problem.
So, if automatic removal attempts with `autoa20fix` and `autoloadfix` fail completely or almost always, there is no information about what the user should do. After all, it is the simplest and at the same time I suspect the most effective way. Currently, `autofixwarning` is disabled by default, let the user be informed at this final stage with simple information on how to work around this error.

DOSBox-X behaved identically to dosbox mainline until this 331cb7a change. **Everything worked then**. I don't know if that was the reason for this change. This change can now be undone without much difficulty.

There are [7200 titles on the list of eXoDOS DOS games](https://github.com/joncampbell123/dosbox-x/files/11005307/exodos.games.list.txt), I bet that this problem may affect 20-30 of them. Really tiny. Except that it usually reveals itself on hacked `.com` loaders. Ultimately, I can't decide for myself whether this is an essential, important issue to fix, you can look at it in different ways.
