### ISSUE TITLE
dosbox-x crashes when using "imgmount a -u" after installing a game

### ISSUE THREAD

**Issue by Wilstorm** [joncampbell123/dosbox-x#4086]
I'm fairly new to using dosbox-x but over the past week I've used it quite a lot and I've seen it crash on me frequently when using the ```imgmount a -u``` command.

A typical scenario would be to mount my install dir, change to the .img directory, mount the disks with ```imgmount a disk1.img disk2.img disk3.img disk4.img disk5.img -t floppy``` and install a game.

A typical directory would be something like kings_quest_4_the_perils_of_rosella\kings_quest_4_the_perils_of_rosella (the directory is repeated twice when unzipped. I only add this thought as the path is long when mounting a bunch of disks up to 9 at a time but maybe that's irrelevant.

I never have an issue mounting or installing, it's been rock solid 100%. I only see the issue _after_ installing, I might run the game and play a bit. After I exit a game I might use ```imgmount a -u``` command and it dumps me out of dosbox-x with no errors. I then restart the program with no issues. Out of 20 or so installs I've seen it 6 or 7 times. I'm running dosbox-x 2202.12.26 (64-bit SDL1) on Windows 10.

It's not a show stopper by no means but I thought I would ask. I did search and didn't find anything relating to it but did see the handy wildcard mount command. Yay for that--I'll being giving that a go for sure! :)

**Comment by Wilstorm** [comment]
@grapeli - Hi, thanks a bunch for the help (again :) and verifying the issue. I'll use the wildcard mounting and see if that helps.

Out of curiosity is this a bug and should I open a ticket or is this good enough? Is it related to using the long form of mounting or something else entirely?

**Comment by grapeli** [comment]
@Wilstorm 
No, simplification of mounting will not help to avoid this bug. It simplifies the installation of, for example, 16 floppy disks significantly, less entering the names of diskette images.
You want to avoid this error, do not unmount the images of floppy disks after the game.

**Comment by grapeli** [comment]
@Wilstorm 
I noticed that to avoid this crash it is enough to switch the floppy image to the first one in the index.
This can be done with a command or from the dosbox-x menu.
`imgswap a 1`
Then unmounting is safe.
`imgmount a -u`

**Comment by Wilstorm** [comment]
@grapeli - That sounds good. I'll try that before unmounting. I appreciate the help and information. I'll close this out for now. Have a great weekend and thanks again! :)

**Comment by Allofich** [comment]
Even if it can be avoided, it's still a bug so this should stay open until the crash is fixed IMO.

**Comment by Allofich** [comment]
I can confirm that a crash happens if you try to unmount when you have multiple disk images mounted and the currently selected disk is not the first one. You don't have to have installed a game or anything like that. I'll open a new issue for this.
