### ISSUE TITLE
DOS: Raw mode input of standard input is unexpectedly echoed

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#4088]
### Describe the bug

Raw mode input set by Ioctl system call is not properly handled on DOSBox-X DOS.

PC-98 game KATALITH seems using this feature for keyboard input. Because of this, input is unexpectedly echoed on the screen like the attached image (numkey pad input):

![katalith_001](https://user-images.githubusercontent.com/1381939/226094116-f7f23d05-2650-489f-860f-57122a049f53.png)

### Steps to reproduce the behaviour

1. Start DEBUG command (I used MS-DOS 2.11 version)
2. Use "a" command and input the program in the attached image
3. Use "g" command to run the program and type "a" key
4. The key "a" should not be echoed.

Default configuration case:

![debug_001](https://user-images.githubusercontent.com/1381939/226094784-78c076b9-5fb8-4661-8376-48e515f727a7.png)

PC-98:

![debug_000](https://user-images.githubusercontent.com/1381939/226094274-578cb081-4aba-4672-8a66-5ce91dc1a826.png)

### Expected behavior

Input during raw mode should not be echoed.
The attached image is on PC-98 MS-DOS 6.2.

![guest os_000](https://user-images.githubusercontent.com/1381939/226094471-120008fe-3a21-4ac3-bbdf-f5c0e63dfc02.png)

### What operating system(s) this bug have occurred on?

DOSBox-X internal DOS

### What version(s) of DOSBox-X have this bug?

commit  f65425e911ba7d7d5e7560ea5117aa32d69a9444

### Additional information

I looked at the code and found that the file src/dos/dos_ioctl.cpp looked like the code handling ioctl system call. It looks like the "Set Device Information" does not set anything - raw mode is not supported yet?

https://github.com/joncampbell123/dosbox-x/blob/9b2dd8e219cbfdf0531fc83b35a2f4b806f0d117/src/dos/dos_ioctl.cpp#L648-L650

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Seems to be fixed? Looks like it's posted by the same guy.
https://mobile.twitter.com/hdk_2/status/1638691326605791232

**Comment by hdk1983** [comment]
Yes, it is fixed. Thanks.
