### ISSUE TITLE
Arm32 build for Windows 10, build 15035?

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [joncampbell123/dosbox-x#4095]
### Question

I was looking to run the Arm32 build of DOSBox-X on my Surface RT, but well I am unsuccessful in doing so. Reason being is somehow there’s no OpenGL32.dll present in this rare build of Windows 10. There is an Arm32 version of regular DOSBox but X has some nice features that I grew to like.

when I originally saw there were Arm32 builds, I thought it would’ve potentially worked out of the box on my RT. Guess those were for the Pro X only, despite being the proper architecture for the OG.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
Can you run DOSbox-X in Direct3D or Surface modes instead of OpenGL?

If I'm not mistaken the arm32 build is expected to work on WinRT.

**Comment by RetroSoftwareRepository** [comment]
> Can you run DOSbox-X in Direct3D or Surface modes instead of OpenGL?
> 
> 
> 
> If I'm not mistaken the arm32 build is expected to work on WinRT.

It wants **opengl32.dll** which is not present for some reason on 15035. The app just straight up won't start without that DLL.

**Comment by joncampbell123** [comment]
On a related note I've noticed that my Windows 10 ARM-based surface tablet does have OpenGL but that doesn't seem to work properly.

Perhaps Win32 ARM builds should just omit OpenGL support entirely?

**Comment by Torinde** [comment]
You can also try copying the DLL from another PC into the arm32 dosbox-x folder (while still selecting surface/d3d in .conf)

As for OpenGL support in Windows-on-ARM: [not supported are x86 apps using OpenGL version later than 1.1 or requires hardware-accelerated OpenGL.](https://learn.microsoft.com/en-us/windows/arm/apps-on-arm-troubleshooting-x86) - maybe that applies also to ARM programs?

**Comment by RetroSoftwareRepository** [comment]
> You can also try copying the DLL from another PC into the arm32 dosbox-x folder (while still selecting surface/d3d in .conf)
> 
> 
> 
> As for OpenGL support in Windows-on-ARM: [not supported are x86 apps using OpenGL version later than 1.1 or requires hardware-accelerated OpenGL.](https://learn.microsoft.com/en-us/windows/arm/apps-on-arm-troubleshooting-x86) - maybe that applies also to ARM programs?

I tried that on my RT, but it seems like the DLL found on DLL websites are x86/x86-64 and not ARM32. I don't have access to anything else that'd have the specific ARM32 DLL either.

**Comment by joncampbell123** [comment]
The latest commit, if you are able to compile from source, disables OpenGL entirely for Windows ARM-based targets (ARM and ARM64), not only to resolve the issue with Windows RT as described but also because OpenGL doesn't seem to work properly anyway on my ARM-based Surface tablet.

**Comment by joncampbell123** [comment]
The latest commit from master has been updated to disable OpenGL support entirely for ARM/ARM64 Windows builds. One, because OpenGL doesn't seem to work properly anyway on my Surface tablet (ARM-based), and two, because according to this issue, Windows RT does not have the OpenGL DLL anyway.

**Comment by joncampbell123** [comment]
I stand corrected, I guess I did update the ARM tablet to Windows 11. :shrug:

**Comment by joncampbell123** [comment]
March 31st release coming up. Windows ARM/ARM64 Surface tablet binaries should no longer use OpenGL in any way, which should then allow DOSBox-X to run on Windows RT... I think. I don't own that kind of Surface tablet so I can't verify that, I'll need your help @RetroSoftwareRepository to confirm that, ok?

**Comment by RetroSoftwareRepository** [comment]
> March 31st release coming up. Windows ARM/ARM64 Surface tablet binaries should no longer use OpenGL in any way, which should then allow DOSBox-X to run on Windows RT... I think. I don't own that kind of Surface tablet so I can't verify that, I'll need your help @RetroSoftwareRepository to confirm that, ok?

Will happily confirm that soon 😉 as I have my Surface RT booting up right now!

**Comment by RetroSoftwareRepository** [comment]
![image](https://user-images.githubusercontent.com/8545874/232249621-95af3972-136b-43cc-b6e5-2df55c1203a5.jpeg)

Can confirm! Works perfectly. 😁
