### ISSUE TITLE
PC-98: ROLL UP/ROLL DOWN swap option

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#4106]
### Is your feature request related to a problem? Please describe.

ROLL UP = Page Down and ROLL DOWN = Page Up on PC-98 Windows. Currently they are opposite and hard coded:

https://github.com/joncampbell123/dosbox-x/blob/443241c60e92053bba9a0a829fb6b036431b6739/src/hardware/keyboard.cpp#L1304-L1305

### What you want

New option swapping the ROLL UP/ROLL DOWN key code. I think ROLL UP=Page Down and ROLL DOWN=Page Up should be default, but existing users might feel tricky, so adding an option is good for them.

### Additional information

On some PC-9821 keyboard, "PgDn" and "PgUp" are printed on the front side of ROLL UP and ROLL DOWN key respectively. You can see pictures of such keyboard on the following auction page:

https://noncky.net/item/u1077935735 

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
If the standard keyboard layout is that "roll up" means Page Down, and "roll down" means Page Up, then that should be the *default* mapping, and it's currently wrong.

So the correct fix would be to flip them anyway.

**Comment by Allofich** [comment]
I'm not familiar with the PC-98 myself, but are "roll up" and "roll down" frequently used with it? If they are just like Page Up and Page Down then an option to swap seems a little excessive to me. Can't they just be remapped like any other key if someone doesn't like the default assignment for some reason?

**Comment by Allofich** [comment]
Oh, I see the reporter said those keys are hard-coded, so I guess they can't be remapped currently. Seems like making them remappable would be preferable to a swap option, though.

**Comment by joncampbell123** [comment]
According to the screen shot, Page Up "rolls down" and Page Down "rolls up" which I guess makes sense. If you page down the content scrolls upward, right?

**Comment by hdk1983** [comment]
https://github.com/joncampbell123/dosbox-x/commit/ebfae74eed0aa915467eaef9319422555f03bcca
It looks like the scancode is forgotten to be modified...

**Comment by maron2000** [comment]
> If you page down the content scrolls upward, right?
I don't have the actual machine to confirm but other emulators (Anex86 and np21/w) behave as you mentioned.

**Comment by hdk1983** [comment]
Now it is fixed. Thanks.
