### ISSUE TITLE
Suggestion: Update mt32emu to 2.3.0

### ISSUE THREAD

**Issue by basic2004** [joncampbell123/dosbox-x#411]
I think to add this issue when I want DOSBox-X update mt32emu to 2.2.0,
but mt32emu 2.3.0 has released today.
https://github.com/munt/munt/releases/tag/libmt32emu_2_3_0

Older MT-32(ROM ver 1.07) emulation has almost fully accurate since munt 2.2.0.
you can use DOSBox-mt32-patch/dosbox-SVN-r4025-mt32-patch.diff in this archive.

**Comment by heydojo** [comment]
I'm going to try and test the mt-32 emu with munt. I will post back if I can get it to work.
In the meantime, here are some outstanding mt-32 reports which should be rolled into one and or closed:
https://github.com/joncampbell123/dosbox-x/issues/310
https://github.com/joncampbell123/dosbox-x/issues/115

**Comment by heydojo** [comment]
OK so I tested it. mt-32 currently does not work with munt here on Windows 64 bit.
I was testing with the Legend of Kyrandia game which has mt32 support in it's setup routine using munt_2_3_0 pre-compiled from Sourceforge. If anyone has a recommendation of a mt32 demo application to try, please chime in.

The patch mentioned by @basic2004 is [here](https://github.com/munt/munt/blob/master/DOSBox-mt32-patch/dosbox-SVN-r4025-mt32-patch.diff) looks like it fixes https://github.com/joncampbell123/dosbox-x/issues/322 looking at: https://github.com/joncampbell123/dosbox-x/blob/6091cfde92caf4e18f734c7d558dc3876eb2bcce/src/gui/midi_mt32.h#L104

Could this patch be evaluated and merged please?

**Comment by heydojo** [comment]
I couldn't get mt32 in dosbox-x to work so I created a branch and rebased it using the code at https://github.com/munt/munt and [this](https://github.com/heydojo/dosbox-x/tree/mt32) is the result.
I don't have a build environment set up so I don't know if this code even builds.
The patch is [here](https://github.com/heydojo/dosbox-x/tree/mt32/patch) for anyone who wants to play with it.

**Comment by heydojo** [comment]
I looked into this and thought it would be more trivial than it is. The patch does not merge cleanly.
The two projects (dosbox-x and munt) use different build systems. munt uses cmake and dosbox-x uses autoconf/automake.
cmake and autoconf are two different ways of doing the same thing.
Dosbox-x has had munt's library shoehorned into it's build. This makes it difficult to import newer versions of munt into dosbox-x unless you were the person who merged the munt library into dosbox-x.
There are a large number of changes in the newer version of munt. However, when trying to merge the new code, I just found circular header dependencies.

**Comment by joncampbell123** [comment]
If your interested in hacking it into compile with DOSBox-X's codebase, that's fine, otherwise don't worry about it. I could pick a future weekend to try that.

It couldn't be any worse than the work of incorporating FM synthesis code from Neko Project II, considering NP2 emulation works very differently from DOSBox-X.

**Comment by heydojo** [comment]
That's going to be a no from me. But thanks for asking. :)

**Comment by heydojo** [comment]
So, I got it to build...
https://github.com/heydojo/dosbox-x/releases/tag/Win10-X86_64-mt32-17-03-2018
https://github.com/heydojo/dosbox-x
I need to test if this fixes the issue at hand but I have stuff to do IRL, so I'll just leave this here.
@joncampbell123 I'll shoot you over a pull request in a few days if testing works out.

**Comment by heydojo** [comment]
Hi @joncampbell123 
I managed to port the code over and it builds on Windows 10. But I am stuck with an issue where Dosbox-X crashes as soon as the mixer is opened. https://github.com/heydojo/dosbox-x-midi/blob/mt32/src/gui/midi_mt32.h line 388.
I put a return in place to prevent the crash.
If you have any time to look at this code it would be appreciated.
It might be something really obvious. If not, I'll leave the tree up for a few months in case it is useful to anyone else. The log output is very verbose and the code is heavily commented.

The alternative might be to rip out mt32 (and fluidsynth because that doesn't run either) from master.
What do you think?

**Comment by joncampbell123** [comment]
If you submit a pull request I'll happily merge it into DOSBox-X.

A good example that I was given is the game "Lure" which supports the MT-32, though only if you set the cycles count low enough for it's MPU-401 detection to work.

**Comment by lexa2** [comment]
@heydojo @joncampbell123 Hi, I'm wondering if PR was ever raised/merged updating munt version bundled with DosBox-X? Actually I'm wondering what version of munt is being included currently in DosBox-X master branch? I wasn't able to spot any "readme" or "version" file inside mt32 folder :-(.

**Comment by joncampbell123** [comment]
I'll try MT32 with VS2017 again, see if it works.

I'm not sure what version of munt is in DOSBox-X, I only know it's what was in Daum's branch sometime 2014 or in DOSBox SVN when I first started this in 2011.

**Comment by yksoft1** [comment]
> I'll try MT32 with VS2017 again, see if it works.
> 
> I'm not sure what version of munt is in DOSBox-X, I only know it's what was in Daum's branch sometime 2014 or in DOSBox SVN when I first started this in 2011.

Daum's munt requires SSE2 to work. This limits it to x86 platforms..

**Comment by joncampbell123** [comment]
I was able to add working MT32 for Windows by adding a #define C_MT32 1 to vs2015\config.h

**Comment by lexa2** [comment]
@joncampbell123 I guess your change is a fix for issue #827 rather than this one?

**Comment by yksoft1** [comment]
I tried to upgrade mt32emu to 2.3.0 and succeeded. However, although it had better sound, newer mt32emu uses a lot more CPU than the one bundled since DOSBox Daum (from about 2013?).

**Comment by joncampbell123** [comment]
So they made it that much more accurate then!

**Comment by lexa2** [comment]
Also it might be that optimizations are not turned on by default in 2.3.0. Still it'll be interesting to check how does new mt32emu copes on low power systems like RPi2. IIRC mt32emu is mostly single threaded so question would be if a single core performance of RPi2 is enough for new mt32emu.

**Comment by rderooy** [comment]
I don't know what version of munt is currently integrated into DOSBox-X, but DOSBox ECE just released a new version with the latest munt 2.4.0
https://www.vogons.org/viewtopic.php?p=895941#p895941

**Comment by Wengier** [comment]
@rderooy It is not very clear the exact version of the previous MUNT in DOSBox-X. But sincethe copyright year apparently referred to 2013, it must be a very old version. In any case, I have already updated MUNT to 2.4.0 in the repository. Please check out the latest code.

**Comment by kcgen** [comment]
@Wengier, this is just a personal request so feel free to ignore.  I would find it very helpful if you could link to the change when you've mentioned already implementing a change. 

For example, in this case, the only open PR is the libslirp change, and likewise I've scrolled through the last month worth of closed PRs and there's zero mention of Munt in those descriptions.

I know this is more work, but I think it would help those interested in seeing said changes (or at the least take any guesswork out of it). Much thanks!

**Comment by Wengier** [comment]
@kcgen The MUNT update is here: https://github.com/joncampbell123/dosbox-x/commit/4c3432c3c7056084c67147376177283ed3397e2b

**Comment by Wengier** [comment]
@kcgen Also, I will try to link to the actual commit when I implement a change in the future too. Thanks for the suggestion.

**Comment by kcgen** [comment]
Thank you @Wengier!

**Comment by basic2004** [comment]
Thanks to update, @Wengier 
I forgot this issue long time, I'm sorry.
You can close this issue because I confirmed this.

**Comment by Wengier** [comment]
I will close the issue for now. Thanks for making the suggestion to update the library.
