### ISSUE TITLE
Multiple DOSbox-X instances running on the same computer for multiplayer

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4113]
I can also confirm the recent fixes to IPX emulation allow two instances of DOSBox-X to run C&C in multiplayer over the "network"

_Originally posted by @joncampbell123 in https://github.com/joncampbell123/dosbox-x/issues/3975#issuecomment-1486432740_
            
@joncampbell123, do you mean two DOSbox-X instances on the same PC? Or on two separate PCs?

It would be great if a multiple instances can run on the same PC and be used by multiple persons simultaneously.

Multiple DOSbox-X instances running on the same computer (big screen 8K/SuperUltraWide) - for multiplayer. 

Input via:
- virtual keyboard/mouse/joystick
- assigning keyboard to 1st instance, mouse to 2nd, joytsick1 to 3rd, etc.
- assigning PART of keyboard to first instance, another PART to second instance, etc.
- ManyMouse and customizing keyboard parts in-game (e.g. one instance gets ASDW, the second instance gets the arrows) dosbox-staging/dosbox-staging/pull/2000

Sound output via different audio devices or just mute all but one instances.

**Comment by joncampbell123** [comment]
I tested two side by side instances on the same PC, using a localhost TCP/IP socket for IPX emulation.

I don't see any reason why it wouldn't work across multiple PCs as long as they can connect to one another.

**Comment by Torinde** [comment]
My feature request is to be able to run multiple DOSbox-X instances on the same PC (as you did) and for each of them to have workable inputs/ouputs (mouse, keyboard, video, sound) at the same time, so that multiple persons can play a multiplayer game while sitting next to each other.

I haven't tried it, but I expect the input parts to be problematic - that's why I list potential solutions for that...

Do you say that it's already possible to do?? Maybe I should just try...

**Comment by joncampbell123** [comment]
> My feature request is to be able to run multiple DOSbox-X instances on the same PC (as you did) and for each of them to have workable inputs/ouputs (mouse, keyboard, video, sound) at the same time, so that multiple persons can play a multiplayer game while sitting next to each other.
> 
> I haven't tried it, but I expect the input parts to be problematic - that's why I list potential solutions for that...
> 
> Do you say that it's already possible to do?? Maybe I should just try...

I mean, yes, you can run the multiple instances, that doesn't mean you can play them simultaneously. If it works over localhost 127.0.0.1 then it should work over a network as well. Most of my dev is on my laptop in my spare time so it's just easier to test that it works over localhost.

At least with Speed 2 in multiplayer, the multiple instances allowed me to see that the car I was driving was also moving and visible in the other instances.

**Comment by Torinde** [comment]
> you can run the multiple instances, that **doesn't mean you can play them** simultaneously.

No, no - I'm not objecting the logic "if IPX works between multiple instances on the same PC, then it'll work over a network as well" - I agree with that.

The purpose of that issue is the reverse - a **feature request** exactly for PLAYING multiple instances on the same PC. That'll be very useful for people with big screens (anybody who has desktop monitor nowadays?)

I understand it won't happen overnight, but please leave it open since obviously it's not possible yet.

**Comment by Torinde** [comment]
SDL3 feature that may help: libsdl-org/SDL/issues/7498
