### ISSUE TITLE
Installing Windows 2000 and XP with dynamic core and cycles=max results in a system that eventually "forgets" and ignores the keyboard and mouse

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#4120]
### Describe the bug

Windows 2000 and XP have some kind of weird timing issue with dynamic core and cycles=max that sometime between 2nd stage install and the final desktop, it decides to ignore the keyboard and mouse and it becomes impossible to use the system at all.

### Steps to reproduce the behaviour

1. Start DOSBox-X with cycles=max and core=dynamic
2. Go through the installation process with Windows 2000 or XP
3. Observe that sometime between the second "graphical" setup phase and the final desktop, the system no longer responds to keyboard or mouse input and will often no longer show a cursor. Also bring up the debugger, use the "PIC" command, and observe that even though IRQ 1 (keyboard) and IRQ 12 (mouse) are pending "R", they are masked off by the guest OS "M" and ignored. Forcibly unmasking the IRQ with the debugger has no effect.

### Expected behavior

Keyboard and mouse continue to work as normal and the system remains usable.

### What operating system(s) this bug have occurred on?

x86_64 Linux

### What version(s) of DOSBox-X have this bug?

DOSBox-X master commit as of March 30, 2023

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
A fixed cycle count prevents the NT kernel from seeing the IDE controller???

**Comment by joncampbell123** [comment]
Also, Windows 2000 S3 Trio support appears to use hardware acceleration in a way that DOSBox-X doesn't quite emulate correctly. Note the black "blinds" over the back of most icons.

![image](https://user-images.githubusercontent.com/6245486/229026443-863744b5-c46a-4885-a55d-14decbacf603.png)

**Comment by joncampbell123** [comment]
Here's hoping last night's Pentium RDTSC changes might make Windows NT/2000/XP happier.

**Comment by joncampbell123** [comment]
Apparently this is no longer a problem with Windows NT except Windows NT 3.5 that quite reliably forgets how to talk to the keyboard :facepalm:

**Comment by joncampbell123** [comment]
Good lord, Windows NT 3.5 seems insistent *not* to talk to the PS/2 keyboard and mouse! At all. Even after 8 installation tries!

**Comment by Torinde** [comment]
Just to share - I'm happy to see you're progressing on the NT/2K/XP and OS/2 support!

**Comment by joncampbell123** [comment]
Windows 2000 and XP no longer randomly forget about the keyboard and mouse so I'm going to close this issue and open a separate one about Windows NT 3.5 keyboard and mouse issues.
