### ISSUE TITLE
Windows XP and problem is with SDL1

### ISSUE THREAD

**Issue by zibijani** [joncampbell123/dosbox-x#4131]
### Describe the bug

After installing "dosbox-x-winXP-2023.03.31-setup.exe", "SDL1" does not work!
After running it shows a missing "XINPUT9_1_0.dll".
The same problem is with "dosbox-x-vsbuild-XP-20230401023040.zip" and "dosbox-x_XPx86_SDL1.exe"

### Steps to reproduce the behaviour

?

### What operating system(s) this bug have occurred on?

Windows XP

### What version(s) of DOSBox-X have this bug?

dosbox-x-winXP-2023.03.31-setup.exe,  dosbox-x-vsbuild-XP-20230401023040.zip

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Does installing the latest version of DirectX help? I mean the latest version Windows XP supports.

**Comment by maron2000** [comment]
This is a known error, you need to install DirectX runtime from now on.

**Comment by Torinde** [comment]
For the same problem see [#3943](https://github.com/joncampbell123/dosbox-x/issues/3943#issuecomment-1399240590)

**Comment by zibijani** [comment]
Installing the latest version of DirectX9 (for XP) solved the problem - thank you.

**Comment by maron2000** [comment]
Just as reminder, as mentioned in #3974, you need a Xinput compatible joystick of you use SDL1.
You can close this issue since I think it is solved.
