### ISSUE TITLE
INT 10 character output and scrolling does not honor screen size in BIOS data area

### ISSUE THREAD

**Issue by ThomasKjoernes** [joncampbell123/dosbox-x#4132]
### Describe the bug

There are some programs that sets a custom text mode based on mode 3 (80x25) and therefore modify the BDA vars for screen width and height. One such tool is SVGATextMode. Another use with be to use the VGA virtual screen and panning features

On real hardware this works as expected because the BIOS will use the BDA vars to calculate the size of the screen for wrapping, scrolling and clearing.

The scrolling routine INT10_ScrollWindow gets the dimensions from BDA, but then calls into the routines TEXT_CopyRow and TEXT_FillRow to do the actual work. These routine will always refer to CurMode=>twidth for getting the width.

Suggested fix would be to make the following changes to int10_char.cpp:

// inside INT10_ScrollWindow, add the 'ncols' variable to these two calls:

TEXT_CopyRow(ncols,cul,clr,start,start+nlines,base);

TEXT_FillRow(ncols,cul,clr,start,base,attr);

// the two methods above need to refer to the new parameter 'width' instead of CurMode=>twidth:

static void TEXT_CopyRow(uint8_t width, uint8_t cleft,uint8_t cright,uint8_t rold,uint8_t rnew,PhysPt base) {
    PhysPt src,dest;
    src=base+(rold*width+cleft)*2u;
    dest=base+(rnew*width+cleft)*2u;
    MEM_BlockCopy(dest,src,(Bitu)(cright-cleft)*2u);
}

static void TEXT_FillRow(uint8_t width, uint8_t cleft,uint8_t cright,uint8_t row,PhysPt base,uint8_t attr) {
    /* Do some filing */
    PhysPt dest;
    dest=base+(row*width+cleft)*2;
    uint16_t fill=(attr<<8)+' ';
    for (uint8_t x=0;x<(Bitu)(cright-cleft);x++) {
        mem_writew(dest,fill);
        dest+=2;
    }
}

---

I am not familiar enough with the codebase to be able to decide if this will have other side affects or if it should be fixed in several other places as well. It seems a bit random whether the BDA values or the CurMode values are used throught the int10 code. 

### Steps to reproduce the behaviour

Simplest way to reproduce would be by running STM.EXE from SVGATextMode (https://www.ibiblio.org/pub/historic-linux/ftp-archives/sunsite.unc.edu/Sep-29-1996/utils/console/)

stm 132x30x9

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

2022.12.26 (64-bit SDL2) (master download on march 19)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
It does now... I think. The copy of STM.EXE you linked to includes a TCONFIG file that it itself doesn't like :facepalm: but I verified the change by manually changing the rows and columns in the BDA.

**Comment by ThomasKjoernes** [comment]
Yep, it seems that version of STM wasn't quite production ready.
Just built master locally and can confirm the fix is working.
