### ISSUE TITLE
2023.03.31 - SDL2 build fails on macOS Ventura

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#4136]
### Describe the bug

macOS Ventura, Apple Silicon Mac:. `build-macos-sdl2` fails with these errors:

```
/Users/edward/Development/dosbox-x-dosbox-x-v2023.03.31/vs/sdl2/src/video/cocoa/SDL_cocoakeyboard.m:269:21: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    IOHIDElementRef elem = IOHIDValueGetElement(value);
                    ^
/Users/edward/Development/dosbox-x-dosbox-x-v2023.03.31/vs/sdl2/src/video/cocoa/SDL_cocoakeyboard.m:326:21: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    CFDictionaryRef keyboard = NULL, keypad = NULL;
                    ^
/Users/edward/Development/dosbox-x-dosbox-x-v2023.03.31/vs/sdl2/src/video/cocoa/SDL_cocoakeyboard.m:586:15: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    CFDataRef uchrDataRef = TISGetInputSourceProperty(key_layout, kTISPropertyUnicodeKeyLayoutData);
              ^
/Users/edward/Development/dosbox-x-dosbox-x-v2023.03.31/vs/sdl2/src/video/cocoa/SDL_cocoakeyboard.m:666:13: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    NSView *parentView = [nswindow contentView];
            ^
/Users/edward/Development/dosbox-x-dosbox-x-v2023.03.31/vs/sdl2/src/video/cocoa/SDL_cocoakeyboard.m:720:20: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
    unsigned short scancode = [event keyCode];
                   ^
3 warnings and 7 errors generated.
make: *** [build/SDL_cocoakeyboard.lo] Error 1
```

### Steps to reproduce the behaviour

Open a terminal in macOS Ventura; enter `build-macos-sdl2`.

### Expected behavior

Build completes without errors

### What operating system(s) this bug have occurred on?

macOS Ventura 13.3, M1 Mac

### What version(s) of DOSBox-X have this bug?

source code of latest release, 2023.03.31

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
The opposite problem of #4109 ?

**Comment by emendelson** [comment]
@Torinde - I'm being dense, I know, but I don't understand what you mean by "opposite". Could you explain?

**Comment by joncampbell123** [comment]
I ran into that right after making this month's release. I guess the Xcode
update had something to do with it. I made a commit that should fix it. Not
sure why SDL2 was suddenly so worried about C89 compiler compatibility lol.

**Comment by joncampbell123** [comment]
I mean even if the SDL2 library was intended to compile on compilers that old, DOSBox-X isn't. We're not interested in the 1989 revision of the C compiler standard :)

**Comment by emendelson** [comment]
That's great - thank you. Apple can be very weird sometimes, clearly.

Now, if someone could fix the problem in SDL2/macOS/output=ttf, where full-screen mode extends slightly beyond the edges of the screen, and doesn't occupy a pixel-perfect rectangle inside the screen, like SDL1, all would be well...!

**Comment by Torinde** [comment]
> I'm being dense, I know, but I don't understand what you mean by "opposite". Could you explain?

4109 says "2022.12.26 works only in Ventura" while this issue says "2023.03.31 fails on Ventura" - so Ventra support flipped, problems are opposite of each other?

> problem in SDL2/macOS/output=ttf, where full-screen mode extends slightly beyond the edges of the screen

I had same problem in Windows, but recent versions are OK (just tried 2023.03.31 VS x64).

**Comment by emendelson** [comment]
> > problem in SDL2/macOS/output=ttf, where full-screen mode extends slightly beyond the edges of the screen
> 
> I had same problem in Windows, but recent versions are OK (just tried 2023.03.31 VS x64). ![image](https://user-images.githubusercontent.com/97228894/229446351-b7b2f6fd-28ed-4af9-bb0b-c807ac4cac94.png) Specifically - I tried "[dosbox-x-vsbuild-win64-20230401023040.zip](https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2023.03.31/dosbox-x-vsbuild-win64-20230401023040.zip)" - since there are doubles of most VS builds

Still not fixed in macOS, unfortunately.

**Comment by joncampbell123** [comment]
The compile issue is fixed at least on my end by telling SDL2 to compile without the warning flag that triggers that message. The TTF output issue should have it's own bug. If that was already done, go ahead and post a link to it here.

**Comment by emendelson** [comment]
Ah, good!

The TTF bug is here:

https://github.com/joncampbell123/dosbox-x/issues/3731

which is probably related to this one:

https://github.com/joncampbell123/dosbox-x/issues/4096
