### ISSUE TITLE
Please explain in each release about any variants

### ISSUE THREAD

**Issue by lwcorp** [joncampbell123/dosbox-x#4151]
### Is your feature request related to a problem? Please describe.

The installation explains ["The Visual Studio builds are the default Windows builds to use"](https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md#windows-packages-installer-or-portable). But [the latest release](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2023.03.31) seems to contain two variants of which: `dosbox-x-vsbuild-win64-20230401005056.zip` and `dosbox-x-vsbuild-win64-20230401023040.zip` (i.e. **20230401005056** VS **20230401023040**).

It's also interested it was released in 2023-03-31, yet many of the downloads are called 20230401.

### What you want

When variants exist, please explain in the release page the differences and which should be the default to download.

Also please mention it in the general installation notes (first link of this post).

### Describe alternatives you've considered

Downloading the ZIP file and extracting it to find an explanation about the differences produced no results.

### Have you checked that no similar feature request(s) exist?

- [x] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
What I published at or near midnight on March 31st was only one of the vsbuild packages. The other builds are by other users that contribute to this build. There is also an automated build system.

vsbuild Windows builds are compiled with Microsoft Visual Studio 2019 Community Edition. mingw builds are compiled using the MinGW toolchain and environment on Windows. HX DOS builds are also compiled with MinGW and intended to run atop MS-DOS using the HX DOS extender.

**Comment by lwcorp** [comment]
So do you always recommend to download the first VSBuild build if there are multiple ones?

**Comment by joncampbell123** [comment]
If you're looking only for builds that I posted, yes.

**Comment by lwcorp** [comment]
I don't know, you tell me...
