### ISSUE TITLE
Windows NT 3.5 keyboard and mouse input stops working the instant you type anything

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#4158]
### Describe the bug

For whatever reason, Windows NT 3.5 is fine with the PS/2 mouse emulation *until* you type anything at the keyboard. The instant you do, both keyboard and mouse stop working.

### Steps to reproduce the behaviour

1. Install Windows NT 3.5
2. Run it through the MS-DOS install phase, then the second boot phase
3. When it presents the setup program to enter information, observe the mouse works
4. Press a key to start typing in Name and Organization. Observe the instant a key is pressed, the mouse stops working. Neither keyboard or mouse input works. Therefore, you cannot complete Windows NT 3.5 setup.

### What operating system(s) this bug have occurred on?

Linux x86_64

### What version(s) of DOSBox-X have this bug?

Latest master branch 2023-04-02

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
Did you test with the serial mouse emulation instead?

I can test also with physical mouse connected to USB-to-RS232 and passthrough to DOSbox-X if you think that may help.

**Comment by joncampbell123** [comment]
I don't think the problem is the *external* connection to the emulator, it's whatever Windows NT 3.5 does with the internal emulation.

The weird thing is that Windows NT 3.1 still works even today in DOSBox-X, although for some weird reason, it now pauses at the NT startup text until you press a key which I do need to look at.

**Comment by joncampbell123** [comment]
Got it.

DOSBox-X didn't quite emulate keyboard reset command 0xFF properly. Windows NT sends that command at startup and expects the 0xAA byte and the BAT (0x00) byte.
