### ISSUE TITLE
Can it automatically wrap before the final output of 'do you need to keep the dosbox', like dosbox?

### ISSUE THREAD

**Issue by 4everImmortality** [joncampbell123/dosbox-x#4160]
### Is your feature request related to a problem? Please describe.

Dosbox will automatically wrap before outputting 'do you need to keep dosbox'. Can I add it to Dosbox x. Is this feature included in the settings.

### What you want

End output asks if it is necessary to keep the automatic line wrap before Dosbox
![image](https://user-images.githubusercontent.com/69960602/230772967-63d1e264-e714-41b0-82ba-f0440abc8f63.png)
![image](https://user-images.githubusercontent.com/69960602/230773155-a0499e8c-672d-46da-8e02-d8b403a5c23f.png)

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by emendelson** [comment]
This absolutely baffling question may perhaps refer to this:

https://blog.csdn.net/qq_51625007/article/details/125226756

**Comment by Torinde** [comment]
I also don't understand the background of the request - @4everImmortality, what are you running before getting that message?
