### ISSUE TITLE
Remove dynamic core

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#417]
By this point changes in fault handling and guest OS work has made the dynamic core obsolete. To avoid further problems, the dynamic core will be removed in the next release.

**Comment by sikthehedgehog** [comment]
The dynamic core was 32-bit x86 only anyway, right? It never worked on
64-bit which made DOSBox-X a lot slower than DOSBox for me (sucks for late
DOS games that expected a 200MHz Pentium! Yes I have some of those)

I suppose the existing dynamic core is already useless by now, though I'd
also suggest considering making a whole new dynamic core in the long term
(that's both more in line with existing emulation and supports recompiling
for newer CPUs). I don't think CPUs will get fast enough to emulate that
stuff at a decent speed any time soon :P

**Comment by joncampbell123** [comment]
That's the point. The existing dynamic core has bitrotted and it's time to remove it. It was never used for 64-bit builds either. The existing dynamic core is also incompatible with the recursive page fault method used in the code now which would make it useless for Windows 95 emulation.

**Comment by joncampbell123** [comment]
Hopefully in the future a new dynamic core can be implemented for both x86 and x64.

**Comment by joncampbell123** [comment]
Another option is to see if I can learn from QEMU how to use the "virtualization" extensions in modern CPUs.
