### ISSUE TITLE
The Tale of Peter Rabbit (DOS): Segment Limit Violation on Normal Core

### ISSUE THREAD

**Issue by NopaWax** [joncampbell123/dosbox-x#4174]
### Describe the bug

This very obscure DOS program/audiobook by Knowledge Adventure is very unstable when the "normal" core is being used and has a very high tendency to crash while the mouse is moving. Upon looking at the log, I see it is infinitely spitting out a segment limit violation error. The program seems to run normally when using any of the dynamic cores.

### Steps to reproduce the behaviour

1. Launch the program.
2. Allow the intro to play out or press the ESC key to skip it.
3. When you're allowed to use the mouse, start moving it back and forth at a fast speed.
4. DOSBox-X will eventually freeze. It sometimes happens immediately, and other times it takes a few seconds.

### Expected behavior

The program should run normally regardless of how much the mouse is moved/there should be no errors.

### What operating system(s) this bug have occurred on?

Windows 11 x64

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2023.03.31 32-Bit SDL1 MinGW

### Used configuration

```ini
core = normal
```

### Output log

```text
Limit check ffff+2-1 = 10000 > ffff DS:SI
Segment limit violation
```

### Additional information

I have been troubleshooting this program across several emulators for several months now, as I have been wanting to find the ideal solution for launching my DOS/Early Windows collection through LaunchBox. I have been testing this and a large number of other games from Knowledge Adventure through 86Box, PCem, vanilla DOSBox, and various forks of DOSBox. From what I've tried so far, vanilla DOSBox and PCem appear to run this program flawlessly, while 86Box and SVN-based DOSBox forks (e.g., DOSBox-X) are problematic. While other Knowledge Adventure games (e.g., 3-D Dinosaur Adventure, SPEED) also have inconsistent mouse tracking and other game-breaking bugs in different places, this is the only one I've found where the system crashes simply by moving the mouse.

Equivalent 86Box issue:
https://github.com/86Box/86Box/issues/3249

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Dynamic core does not enforce segment limits. Neither does any core in DOSBox SVN and most other forks.
Assuming this program runs in real mode, it's usually caused by DOS code that does a 16-bit WORD memory read or write at byte offset 0xFFFF in any segment. (0xFFFF+2) > 0x10000 therefore segment limit.

This means on real hardware, where segment limits are normal, the program will crash in the same manner. However HIMEM.SYS on most DOS systems maintains "flat real mode" which can prevent these programs from crashing on 386 and higher systems.

Does the game crash with cputype=286?

**Comment by NopaWax** [comment]
No, it does not! I never thought of trying anything below a 386, as the program's from 1992 and shipped on a CD. I'm quite astonished. I'll have to try this on the other programs I have from this set and see if this fixes them as well. Those don't crash immediately like this one does, so I didn't focus on those.

**Comment by joncampbell123** [comment]
> No, it does not! I never thought of trying anything below a 386, as the program's from 1992 and shipped on a CD. I'm quite astonished. So, does that leave this program in a sort of gray area in terms of accurate emulation?

Yes. It depends on how the environment has set up the real mode and whether it's "flat real mode" or just normal real mode. It also suggests that if you ran the program under Windows or any other virtual 8086 mode environment, where 64KB segments are strictly enforced (v86 mode fixes the segment limits at 64KB as far as I know), you'll probably see the same crash,

**Comment by joncampbell123** [comment]
However the 286 also has segment limits as you probably know, so how would it work on a 286, right?

Well there's something about 286 and 386 segment limits I've noticed that isn't clearly documented. If the segment limit is set to the largest possible value on that processor, then there is no segment limit. Else, there is a segment limit.

On a 286, segment limits are not enforced at all if you set the limits to the (default) 64KB-1 = 65536 bytes.
On a 386, segment limits are not enforced at all if you set the limits to 4GB-1 = 0xFFFFFFFF bytes, otherwise they are enforced. Real mode has a default limit of 64KB, so any attempt to access byte 65536 by reading a word value from offset 65535 triggers the segment limit.

Make sense?

**Comment by NopaWax** [comment]
Yes, this is making sense. So, the issue here is that this program needs "flat real mode" in order to work on a 386 or higher (which I'd argue is what you need to run this program in the first place), and DOSBox-X emulates standard real mode, which enforces these segment limits when the normal core is used. In the case of real hardware, this program would need HIMEM.SYS and no kind of EMS emulator (like EMM386 or QEMM) running in order to work. Am I on the right track?

**Comment by joncampbell123** [comment]
Right. Way back in the mid 1990s when I had just upgraded to Windows 95 and I was learning how to use an assembler and linker in pure DOS mode, I found out by accident that HIMEM.SYS, when EMM386.EXE isn't active, likes to keep the CPU in "flat real mode" at all times (it makes the extended memory copy API faster and simpler that way). My ASM code could just set ES=0 and "MOV ESI,B8000h" "MOV ES:[ESI],AX" to draw on the screen and it didn't fault. If I loaded EMM386.EXE and made it active, then it did fault. And within a Windows 95 "DOS Box", it faulted as well.

**Comment by joncampbell123** [comment]
I had also at the time found a shareware compilation CD-ROM with "Zone 66" on it, which is a game that also requires a working flat real mode and extended memory to run properly.

**Comment by NopaWax** [comment]
I'll have to try this on the other games from this company that I have to see if it changes their behavior. They tend to be quite unstable, but don't crash right away like this one does.

This also explains another aspect of these games I always found odd: The installers for these games ask to create Windows shortcuts. These shortcuts don't launch the game within Windows. They instead exit to DOS, then launch the game, then restart Windows once the game closes. That indicates that they were fully aware that this was an issue...you'd think they'd put a warning somewhere that said "Don't run this with EMM386 running" or something like that, but in my many experiments with these games, I have seen no such indication.

Then again, this is not the only mind-boggling configuration-related mishap I've had with these games.

In any case, thanks for clearing that up for me. I wish it didn't take me so long to figure it out. I've been wanting to use DOSBox-X as my primary solution for running these...curiosities, and this issue was keeping me from doing so.

**Comment by grapeli** [comment]
I can't confirm anything like that (even if I moved the mouse very fast for three minutes).
It works identically to dosbox-staging and dosbox-SVN.
I have attached the version I tested.
[talepete.zip](https://github.com/joncampbell123/dosbox-x/files/11223084/talepete.zip)

Please specify how and when this DOSBox-X bug occurs as well as when the "Segment Limit Violation" message appears. Please provide the exact version and configuration of DOSBox-X if it differs from the default.

In the development version of dosbox-x-git, starting from the change in the ab3c94c code, the highlighted read text is desynchronized. It is highlighted much too quickly for the lines being spoken. This is actually a DOSBox-X bug.

**Comment by NopaWax** [comment]
> I can't confirm anything like that (even if I moved the mouse very fast for three minutes). It works identically to dosbox-staging and dosbox-SVN. I have attached the version I tested. [talepete.zip](https://github.com/joncampbell123/dosbox-x/files/11223084/talepete.zip)
> 

The version you have is the floppy disk version. I just tested your version with the segment limit option enabled, and it did not crash. Interesting...

The version I've been testing is the CD-ROM version, which does not seem to have been uploaded anywhere.

When the error occurs, no visible indication is given. The program simply freezes. The "segment limit violation" message is endlessly repeated in the log file until DOSBox-X is closed.

**Comment by 80486DX2-66** [comment]
@joncampbell123 
> On a 286, segment limits are not enforced at all if you set the limits to the (default) 64KB-1 = 65536 bytes.

Did you mean 65535 bytes (0xFFFF)?

**Comment by joncampbell123** [comment]
> @joncampbell123
> 
> > On a 286, segment limits are not enforced at all if you set the limits to the (default) 64KB-1 = 65536 bytes.
> 
> Did you mean 65535 bytes (0xFFFF)?

Yes.

**Comment by joncampbell123** [comment]
Peter Rabbit is using the RTC interrupt for timing. It sets the RTC Periodic Interrupt to 256Hz instead of the normal 1024Hz.

In the latest code, InitRtc() is called when the BIOS is asked to get time, which sets it back to 1024Hz, which happens after Peter Rabbit has set it to 256Hz. Therefore, music is going 4 times as fast.

**Comment by joncampbell123** [comment]
Also if you tell Peter Rabbit you have a Sound Blaster 16 and set sbtype=16 the program assumes IRQ7 and then (of course) fails to detect the IRQ (I have irq=5 for testing).

I mean, it could read the BLASTER environment variable or read specific mixer registers on SB16 that indicate the DMA and IRQ it's set to..... but, nah, just assume IRQ7. :facepalm: Maybe the card was too new for proper support at the time.

**Comment by joncampbell123** [comment]
Finally, the 3rd page will very reliably crash if digitized sound is enabled. It will crash to a DOS prompt with a "Divide Error". You can't see it because it's a jumble of pixels due to 256-color unchained mode, but --log-con in DOSBox-X reveals it. Sometimes the crash is that it just hangs and doesn't respond.

It crashes the same in DOSBox SVN and DOSBox Staging.

**Comment by joncampbell123** [comment]
:laughing: Even though SETUP.EXE doesn't offer ANY way to specify the IRQ and DMA in a user friendly manner, you can correct it's misconceptions about IRQ and DMA by editing KA.CNF.

Set it to Sound Blaster 16 and then set SoundDevParams : A220 I5 D1

Don't try D5, the program clearly doesn't support 16-bit PCM.

**Comment by NopaWax** [comment]
> Also if you tell Peter Rabbit you have a Sound Blaster 16 and set sbtype=16 the program assumes IRQ7 and then (of course) fails to detect the IRQ (I have irq=5 for testing).
> 
> I mean, it could read the BLASTER environment variable or read specific mixer registers on SB16 that indicate the DMA and IRQ it's set to..... but, nah, just assume IRQ7. 🤦 Maybe the card was too new for proper support at the time.

> 😆 Even though SETUP.EXE doesn't offer ANY way to specify the IRQ and DMA in a user friendly manner, you can correct it's misconceptions about IRQ and DMA by editing KA.CNF.
> 
> Set it to Sound Blaster 16 and then set SoundDevParams : A220 I5 D1
> 
> Don't try D5, the program clearly doesn't support 16-bit PCM.

This, I've already experienced in my previous experiments with this program, and this is not the only KA game/program to do this. You've just seen the start of it, pal. These games are a freaking mess! I've gotten the process of getting MIDI and digital sound working with these games down to a science...because it's not just as simple as choosing "MIDI".

In the games that let you select MIDI as a sound option, it ONLY sets up the music. In order to have sound effects, you need to manually edit the KA.CNF file and tell it which driver file to use (I have "SBPDIG.DRV" memorized because I've had to do this so many times across several emulators, and yes, even if you're using an SB16, all of these games use an SB Pro driver for digital sound), but that's not all!

In one of the games, specifically America Adventure, if you install the game with MIDI, it does not install ANY of the drivers for digital sound at all! You have to manually copy the sound driver files from the CD in order for digital sound to work. I smacked my head so hard when I figured that one out.

> Finally, the 3rd page will very reliably crash if digitized sound is enabled. It will crash to a DOS prompt with a "Divide Error". You can't see it because it's a jumble of pixels due to 256-color unchained mode, but --log-con in DOSBox-X reveals it. Sometimes the crash is that it just hangs and doesn't respond.
> 
> It crashes the same in DOSBox SVN and DOSBox Staging.

I can also confirm from experience that this is a thing.

**Comment by joncampbell123** [comment]
Now that I think of it... I once came across something that looks like it has similar interface controls and the same 320x400 256-color unchained graphics mode that my father had in his random stash of CDs back in the mid 1990s. It was some educational point and click about the human body and human anatomy. Did they make that too? That would explain the sometimes erratic behavior on my 386 at the time!

**Comment by NopaWax** [comment]
> Now that I think of it... I once came across something that looks like it has similar interface controls and the same 320x400 256-color unchained graphics mode that my father had in his random stash of CDs back in the mid 1990s. It was some educational point and click about the human body and human anatomy that was evidently made sometime around 1993-1994. Did they make that too? That would explain the sometimes erratic behavior on my 386 at the time!
> 
> I'd take a photo if only I knew wherever it went..

Did it look like this?

![kav_000](https://user-images.githubusercontent.com/122238513/232135007-4d64b1d0-4fd2-4390-a5a3-1dcad100c18b.png)
![kav_001](https://user-images.githubusercontent.com/122238513/232135020-ab969ace-8c77-4045-924c-33d6913fa3ad.png)

If so, then yes, it's from the same company. It's called 3-D Body Adventure. Out of the games from this set, this one is probably the most well-known due to it being shipped with a lot of OEM machines during that time period...which is also how my family got it.

**Comment by joncampbell123** [comment]
That's exactly it. :+1:

**Comment by NopaWax** [comment]
> > Finally, the 3rd page will very reliably crash if digitized sound is enabled. It will crash to a DOS prompt with a "Divide Error". You can't see it because it's a jumble of pixels due to 256-color unchained mode, but --log-con in DOSBox-X reveals it. Sometimes the crash is that it just hangs and doesn't respond.
> > It crashes the same in DOSBox SVN and DOSBox Staging.
> 
> Interesting...I just tested the version that was sent and it does indeed crash at that spot...the CD version seems to be working fine, though...maybe a bad dump? I had the complete files for the floppy version on a drive I don't have access to right now...I'll have to test that when I'm able.

I just tested my dump of the floppy version, and it appears to be perfectly stable (well...as stable as it CAN be, I guess). Stuff like this is why I try to avoid scene dumps of DOS games when I can, especially for these games.

I've thought about sharing my dumps of these games for a couple years now, and now it's looking like I might have to for the sake of archiving these...wonders of DOS history.
