### ISSUE TITLE
CPUID instruction

### ISSUE THREAD

**Issue by CandyMan30** [joncampbell123/dosbox-x#4175]
### Describe the bug

Why does executing a CPUID instruction on DosBoxX with an invalid level value (EAX register equal 3) throw an exception?
It should return zero values in the remaining registers (EAX, EBX, ECX, EDX).

### Steps to reproduce the behaviour

Run attached program TEST.EXE.
[test.zip](https://github.com/joncampbell123/dosbox-x/files/11221259/test.zip)

### Expected behavior

If it throws an exception you will see the message "#6".

### What operating system(s) this bug have occurred on?

Windows 7

### What version(s) of DOSBox-X have this bug?

2022.12.26

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I see. Intel documentation backs that up as does Felix (https://www.felixcloutier.com/x86/cpuid).

I must have confused unknown behavior with what RDMSR/WRMSR do with unknown indexes.
