### ISSUE TITLE
int 21h 3dh open file undocumented access mode compatibility

### ISSUE THREAD

**Issue by shaiku** [joncampbell123/dosbox-x#4184]
### Describe the bug

I'm debugging an old Pascal program and it is using an apparently undocumented file open access parameter which dosbox-x is not emulating properly.  The access mode is documented like this:
```
AH = 3Dh
AL = bits 0-2 Access mode

    000 = read only
    001 = write only
    010 = read/write 
```
Note that bit 2 is always 0.  The program is using an access mode of 100 which is undefined/undocumented however this results in read/write access on real DOS.  Under dosbox, however, this gives read-only access which causes the program to fail with a file access error.

I have not probed this further but I have a suspicion that read/write may be the default case in real DOS and only RO and WO cases are explicitly checked.

### Steps to reproduce the behaviour

Open an existing file with int 21h, ax=3d44h, try to write to the file with int 21h, ax=4000h.

### Expected behavior

File is writable

### What operating system(s) this bug have occurred on?

DOS

### What version(s) of DOSBox-X have this bug?

2022.12.26

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by ThomasKjoernes** [comment]
I tested this in (real) DOS 6.22 and any file mode above 2 will result in carry flag set and error code 0x0c  Invalid access mode (open mode is invalid).

**Comment by shaiku** [comment]
I'll need to look into this a little further then.  The program in question will not run under dosbox-x and shows ax==3d44h in the debugger when int 21h is called.

AL is being loaded from a variable in the data segment that is initialized to 2 but is overwritten with 44h before the interrupt call.
Here's the progression:
```
dseg:0436 byte_373A6      db 2
<...>
mov     byte_373A6, 44h
<...>
mov     al, byte_373A6
mov     ah, 3Dh
int     21h
```
I don't see any jumps or any way to skip the mov instruction that overwrites 2 with 44h, so if this really is invalid then perhaps that data is supposed to be read-only but dosbox is allowing it to be written?

**Comment by ThomasKjoernes** [comment]
What DOS version did you test with? And if you could provide the program I could take a look?

**Comment by shaiku** [comment]
I dug into this some more and it looks like I was wrong.  The program in question is LORDCFG.EXE from here http://lord.lordlegacy.com/allfiles/versions/lord407.zip   Versions prior to 4.07 all run on DOS just fine and I assumed that 4.07 does as well, but that turns out not to be the case.  It runs under the NTVDM and OS/2 MDVM which is interesting.  I guess dosbox is doing the right thing since its aim is to emulate DOS and not the Dos Virtual Machine.  My apologies for wasting your time :(

I tried with DOS 6.22, 7.10, and the Win98SE boot disk and LORDCFG did not work properly on any of them.  It does, however, work in a cmd box under NT and XP or above.  Again, so sorry for wasting your time.
