### ISSUE TITLE
Copying files to floppy.IMG - silent crash

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4189]
### Describe the bug

DOSbox-X closes without any error message when trying to copy files to a mounted image.

### Steps to reproduce the behaviour

In a folder with a few small files:
1. IMGMAKE FDD.IMG -t fd
2. IMGMOUNT a FDD.IMG
3. copy . a:

DOSbox-X SDL1 MinGW64 2023-04-15: DOSbox-X closes (silent crash)
DOSbox-X SDL1 MinGW64 2022-11-20: files get copied properly

### What operating system(s) this bug have occurred on?

Windows 10 x64

### What version(s) of DOSBox-X have this bug?

SDL1 MinGW64 2023-04-15

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I'm not able to recreate this issue. x86_64 Linux compiled with GCC.

Could this be some issue with MinGW compiled versions?

**Comment by Torinde** [comment]
Will try other Windows builds.
Strange if nobody else stumbled upon such basic bug, maybe some mixup on my side.

**Comment by Torinde** [comment]
With the latest artifacts as of today (2023-04-22), running the above three commands, without any .conf file, just with the dosbox-x.exe files in a local folder on the host (no SMB shares involved):
- MinGW32 - works OK
- MinGW64 - silent close/crash
- VS64 - works OK

**Comment by Torinde** [comment]
Tested with 2023-05-13 MinGW64 of Maxpat78 and master - both work correctly. Maxpat78 VS64 also works.

So, it seems some of the recent changes solved the problem?

Just to check my sanity - I tested again with 2023-04-22 - got same results as above. So, if somebody is interested in WHY/HOW that was fixed - should check the changes in between those dates.
