### ISSUE TITLE
if you Cant type 'z' letter, then change this comment.

### ISSUE THREAD

**Issue by ghkgrk** [joncampbell123/dosbox-x#4192]
### Describe the bug

if you Cant type 'z' letter

### Steps to reproduce the behaviour

just type 'z' check whether it is typed or not. 

### Expected behavior

this will type 'x' instead of 'z'

### What operating system(s) this bug have occurred on?

asfdad

### What version(s) of DOSBox-X have this bug?

i downloaded this version at 13/04/2023

### Used configuration

```ini
i just used default configuration.
```

### Additional information

106 line's '//~' comment  will comment next line 107 when compile. 
that's why whenever type 'z' letter will be shifted sofore will type 'x'. 
![image](https://user-images.githubusercontent.com/1733743/232784574-10ac5eb0-b081-43ca-ba5a-4ec28087e777.png)

change 106 line comment to this way.
![image](https://user-images.githubusercontent.com/1733743/232784298-33c73ed5-a9c4-4da0-93f0-7601d48e451f.png)

![image](https://user-images.githubusercontent.com/1733743/232786024-303457af-81c9-4c45-b329-3ba483ef0bad.png)

thanks you dosbox-x team!!

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by NebularNerd** [comment]
I think this might fix #3816 as well.
