### ISSUE TITLE
Dynamic VHD driver is buggy

### ISSUE THREAD

**Issue by maxpat78** [joncampbell123/dosbox-x#4194]
### Describe the bug

DOSBOX-X 2023.03.31 can't correctly read blocks from a Dynamic VHD (currently supported, according to code in bios_vhd.cpp).

### Steps to reproduce the behaviour

- create a 2GB Dynamic VHD, both with Windows 11 Diskpart or my Python FATtools mkvdisk from GitHub; MBR partition and FAT-16 format it
- copy a 48MB self-extracting DOS RAR archive into the VHD image with Windows Explorer, and dismount the VHD
- start dosbox-x w/o any particular configuration
- mount the folder containing such RAR as drive X, and the VHD containing its copy as drive Y
- perform archive self-test from dosbox-x shell on X: - it works fine
- perform the same on Y: - it fails with CRC error at some point, symptom of some read failure

### Expected behavior

RAR self-test described above works fine *twice*

### What operating system(s) this bug have occurred on?

Windows 11 x64

### What version(s) of DOSBox-X have this bug?

2023.03.31 (dosbox-x-vsbuild-win64-20230401023040)

### Used configuration

```ini
Default
```

### Additional information

This test confirms the reason why an O/S can't be installed on a Dynamic VHD (strange errors occurred during setup), while the same operation works fine on a "plain" RAW image.

Moreover, dosbox-x internal shell freezes while attempting to copy items into the Dynamic VHD.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maxpat78** [comment]
Also, I've tried another test with this tiny 16-bit C utility RDWR.C:
[RDWR.C.TXT](https://github.com/joncampbell123/dosbox-x/files/11272051/RDWR.C.TXT)

RDWR.EXE and BLOB.BIN are copied from Windows into a 2 GB Dynamic VHD image.

Running `RDWR r` from the VHD mounted as T: gives the following result:
![command_001](https://user-images.githubusercontent.com/2823136/233050449-70d7a123-444b-43de-b74b-555eb78ba61b.png)

**Comment by grapeli** [comment]
I can confirm using a dynamic VHD image in DOSBox-X is buggy.
Recently #4056, I was testing The Longest Journey Dynamic on a dynamic vhd image and while the process of copying around 10000 was successful, the attempt to run this game ended in failure. The files or file system were corrupted. I also experienced this when reinstalling. Of course, the third time I used a traditional RAW disk image, any problems with trying to run the game suddenly disappeared.

I advise against using dynamic VHD images under DOSBox-X. Outside of tests.

**Comment by maxpat78** [comment]
I've checked more source code while executing `RDWR R` and found this problem:

```
LOG: Mapping BIOS DISK C/H/S 520/128/63 as IDE 4160/16/63

[...]
MYDBG: fatDrive::readSector(8000), absolute=0
MYDBG: fatDrive::readSector -> cylindersize 8001 = Heads(127)xSPC(63)
MYDBG: imageDisk::Read_Sector(sectnum 8000 from C=0, H=126, S=63)
MYDBG: Read_AbsoluteSector 8000 -> blockNumber=1, sectorOffset=00000F40
MYDBG: Read_AbsoluteSector 8000 -> hasData=1
MYDBG: Read_AbsoluteSector 8000 -> fseeko64 003E9A00
MYDBG: fatDrive::readSector(8001), absolute=0
MYDBG: fatDrive::readSector -> cylindersize 8001 = Heads(127)xSPC(63)
MYDBG: imageDisk::Read_Sector(sectnum 8064 from C=1, H=0, S=1)
MYDBG: Read_AbsoluteSector 8064 -> blockNumber=1, sectorOffset=00000F80
MYDBG: Read_AbsoluteSector 8064 -> hasData=1
MYDBG: Read_AbsoluteSector 8064 -> fseeko64 003F1A00
MYDBG: fatDrive::readSector(8002), absolute=0
MYDBG: fatDrive::readSector -> cylindersize 8001 = Heads(127)xSPC(63)
MYDBG: imageDisk::Read_Sector(sectnum 8065 from C=1, H=0, S=2)
MYDBG: Read_AbsoluteSector 8065 -> blockNumber=1, sectorOffset=00000F81
MYDBG: Read_AbsoluteSector 8065 -> hasData=1
MYDBG: Read_AbsoluteSector 8065 -> fseeko64 003F1C00
```

Initially, VHD is mapped as BIOS DISK 520/128/63; but  `fatDrive::readSector` converts absolute sector number using a `BPB.v.BPB_NumHeads` that is 127 at most, not 128 - so the cylinder size gets shrinked from 8064 to 8061!
And this seems the amount of bytes skipped while reading the VHD block.

**Comment by maxpat78** [comment]
Having debugged more deeply, I've found the source of the problem was not dosbox-x, but the boot sector BPB on the disk: it had H=0x7F instead of H=0x80. 
Once fixed that with a bin editor, Dynamic VHD worked as a charm in dosbox-x.
However, other disk image related utilities (7-zip, dosbox 0.74-3) seem not to rely on the CHS geometry stored in MBR/BPB.

**Comment by maxpat78** [comment]
My test image CHS geometry did not matter, after all.

I've tried a simpler test.

Having a good VHD (i.o.w., operated without errors from both Virtualbox and Windows 11) with a folder containing some CAB archives, mounted as C:, and another RAW image mounted on drive D:, I've booted a MS-DOS floppy and tried to XCOPY (with the true MS-DOS command) such folder from C: to D:.

Cabinets in D: are corrupted, source items are, obviously, good.

**Comment by joncampbell123** [comment]
Please try the latest master commit, a fix has been made for dynamic VHD images.

**Comment by maxpat78** [comment]
> Please try the latest master commit, a fix has been made for dynamic VHD images.

Ok, I've built and tried latest master (with my little patch merged), and now VHD works as expected (particularly, interchange with Windows 11: mounting, copying into etc.).

Please notice, however, that copying the famous self-extracting RAR from inside DOSBox-X does not work as expected, both with internal COPY and with internal 4DOS COPY: the file gets silently corrupted during copy operation.
This is probably another bug, not VHD related: I've booted an MS-DOS floppy, and repeated COPY operation - this way, self testing completed without errors.
