### ISSUE TITLE
CGA Flickering artifacts in Super Zaxxon

### ISSUE THREAD

**Issue by scrutinizer80** [joncampbell123/dosbox-x#4197]
### Describe the bug

Super Zaxxon which uses the CGA composite mode is having some weird distortion/flickering on both sides of the screen
This behavior doesn't seem to change when switching output modes, cycle count or aspect ratios.

### Steps to reproduce the behaviour

Run SUPERZAX.COM

### What operating system(s) this bug have occurred on?

Windows 11 x64 SDL2

### What version(s) of DOSBox-X have this bug?

2023.03.31 SDL2 mingw

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Are you using the OpenGL/Direct3D output?

**Comment by scrutinizer80** [comment]
> Are you using the OpenGL/Direct3D output?

Tried all, including Surface...

**Comment by joncampbell123** [comment]
Alright, here's what I see about this:

It looks like the game both uses hardware panning with the CRTC offset while at the same time redrawing the menu on the left side. But it seems to do it without regard for vsync in a way that suggests it was only intended for IBM PCs and their timing.

https://user-images.githubusercontent.com/6245486/234143704-499946af-61ef-4d64-93f2-b802f6b6ef14.mp4

**Comment by joncampbell123** [comment]
However with some specific emulation parameters I can eliminate that artifact:

    [dosbox]
    machine=cga_composite
    vmemdelay=300
    enable pci bus=false

    [cpu]
    core=normal
    cputype=8086
    cycles=300

https://user-images.githubusercontent.com/6245486/234144291-4a3c5bda-c75f-41af-988a-e479f093a97e.mp4

**Comment by grapeli** [comment]
The version downloaded from eXoDOS works fine with default settings.

`dosbox-x -set machine=cga -set cycles=300 -c 'mount c ./SuperZax' -c 'c:' -c 'SZAXXON.EXE'`

[Super Zaxxon (1984).zip](https://github.com/joncampbell123/dosbox-x/files/11319088/Super.Zaxxon.1984.zip)
