### ISSUE TITLE
Single step debugging skips instructions

### ISSUE THREAD

**Issue by friol** [joncampbell123/dosbox-x#4202]
### Describe the bug

I'm trying to debug some old demoscene DOS productions, that are compiled with DOS extenders and 32 bit code, and, when I stop the execution in the middle of the 32 bit code, pressing F10 skips multiple instructions instead of going to the next one.

For example, here are 2 successive screenshots with just one pression of F10. You can see multiple instructions and multiple cycles have been skipped:

![ss1](https://user-images.githubusercontent.com/4502137/233823229-e6fa8132-e7da-495c-a0b5-faa39741cd6e.png)

![ss2](https://user-images.githubusercontent.com/4502137/233823234-6cea5ede-d2ed-48c2-a27a-6faf1940813a.png)

You can reproduce the problem, for example, with this production here:
https://files.scene.org/get:nl-https/demos/groups/haujobb/licht3.zip

### Steps to reproduce the behaviour

1. Try to debug a 32 bit dos executable, for example https://files.scene.org/get:nl-https/demos/groups/haujobb/licht3.zip
2. Step with F10 in the debugger
3. Multiple instructions are skipped with a single pression of F10

### Expected behavior

Execution should go to the next instruction with a single press of F10.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

dosbox-x-vsbuild-win64-20230401023040

### Additional information

The same problem occurs trying to debug other 32 bit dos programs.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
You're probably using dynamic core, which batches instructions as part of it's JIT.

Switch to normal core.

**Comment by friol** [comment]
Right.
