### ISSUE TITLE
How about a "drivec" folder in addition to the "drivez" folder already present?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#4203]
### What you want

It would be rather convenient to have a `drivec` folder in addition to the already present `drivez`.

That would allow one to simply drop its files on that folder and immediately access them without having to mount anything.

The feature could be passively enabled, if the folder exists, then it will be mounted, otherwise just normal behavior.

While we're on it, couldn't simply any folder present with the naming scheme `drive[c-y]` simply be automatically mounted?

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
For completeness, also drive[a-b]? 
I assume booting from those won't be easy (maybe possible if some default boot sector is appended), but just reading/writing files should be OK?

**Comment by aybe** [comment]
Got the thing up for drive C up to drive Y: https://github.com/joncampbell123/dosbox-x/pull/4207

Not sure about mounting A and B as local drives; I mean, that would introduce Frankenstein floppy drives 🧟‍♂️😅.
