### ISSUE TITLE
Is there a way to dump the actual VGA palette?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#4205]
### Question

I would like to know what is the VGA palette while this game is running:

<img width="321" alt="dosbox-x_DAsc570GYi" src="https://user-images.githubusercontent.com/1537591/233959845-f76b0641-e923-4b23-be47-bfcc43f7e9e3.png">

Is there a relatively easy way to dump it from within DOSBox-X?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
There are two ways to view (not yet dump) the palette.

First way: Bring up the debugger, type "VGA DACPAL" and hit enter. It will print out the palette as 6-bit RGB hex codes.

Second way: Go to the Debug menu and enable "Video debug overlay".

There is already an issue open about being able to dump and save the screen and palette in a snapshot.

**Comment by aybe** [comment]
That's exactly what I need and even more, I just discovered the _Video debug overlay_: 😲

![dosbox-x_rpwINpI9He](https://user-images.githubusercontent.com/1537591/234219099-1a3cb2e5-31c6-4ea8-9322-b7943fbd70cc.png)

It immediately answered the second thing I had in mind: the palette does not change.

Truly impressive feature, thanks! 🎯

**Comment by joncampbell123** [comment]
One additional thing about that debug feature is that it's deliberately rendered out where the screenshot and record to video functions can see it.

So, not only can you see that the palette isn't changing, you can record it too.
