### ISSUE TITLE
When inputting Chinese, there will be an extra American letter in front

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#4227]
### Describe the bug

When inputting Chinese, there will be an extra American letter in front
Like This: k大j家v好
Version 2022.12.26 is right
Version 2023.03.31 is not ok
Version 2023.05.01 is not ok

### Steps to reproduce the behaviour

1.Execute C:\DosBox-X> Dosbox-x -noconfig 
1. into command prompt: input Chinese 
大家好
but it will appear
 k大j家v好

2. Input 
非凡系統有限公司大家好 [Enter](22bytes)
it will appear
非凡系統有限公n (cut into 15Byte)

3.When the cursor stops at the first byte of the Chinese character, a cursor appears;
But when stopping at the second byte of the Chinese character, no cursor appears

### What operating system(s) this bug have occurred on?

Win10 22H2

### What version(s) of DOSBox-X have this bug?

Version 2023.03.31 is not ok / Version 2023.05.01 is not ok

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by jvidalw** [comment]
what is an "American" letter?

**Comment by Arthur3032** [comment]
Enter 1 Chinese character, one more letter appears in front
Like this
k大

**Comment by Arthur3032** [comment]
Input Chinese 大
and then appers
k大

**Comment by Arthur3032** [comment]
https://user-images.githubusercontent.com/93595854/236083454-c4020862-3a40-4703-a752-ee3f275dadc7.mp4

**Comment by jvidalw** [comment]
I believe what you mean is a LATIN letter

**Comment by Arthur3032** [comment]
Please show the video

**Comment by Arthur3032** [comment]
I want to input 大家好
But dosbox- x appear
k大j家v好

**Comment by maron2000** [comment]
I'm not sure but maybe we need some more fix added to #3995.

**Comment by nanshiki** [comment]
It may be fixed by changing the !IS_JDOSV part of the fix of #3995 to !IS_DOSV.
Chinese environment, do you use [dosv] dosv= in dosbox-x.conf?

**Comment by Arthur3032** [comment]
> It may be fixed by changing the !IS_JDOSV part of the fix of #3995 to !IS_DOSV. Chinese environment, do you use [dosv] dosv= in dosbox-x.conf?

dosv = off

**Comment by Arthur3032** [comment]
![image](https://user-images.githubusercontent.com/93595854/236675872-e38ffa84-01cf-45f7-8aff-935d30e72462.png)

**Comment by Arthur3032** [comment]
![image](https://user-images.githubusercontent.com/93595854/236675951-64a2606a-d105-4c9e-b754-e21fff231097.png)

**Comment by Arthur3032** [comment]
![image](https://user-images.githubusercontent.com/93595854/236676044-54fff403-1702-41ba-83fb-d8e04c2a53de.png)

**Comment by nanshiki** [comment]
I think you have enabled IME by setting the codepage in [dos] country.
I was able to reproduce it here as well, so I fixed it.
#4253
