### ISSUE TITLE
DOSBox-X 2023.05.01 MinGW crashes on SoundBlaster 16 initialization

### ISSUE THREAD

**Issue by scrutinizer80** [joncampbell123/dosbox-x#4233]
### Describe the bug

Any attempt to use the SoundBlaster 16 causes an immediate crash on DOSBox-X 2023.05.01 MinGW edition. Both SDL1 & SDL2.
Previous DOSBox-X versions work fine.

### Steps to reproduce the behaviour

run anything that's accessing the SoundBlaster 16

### What operating system(s) this bug have occurred on?

Windows 11 x64

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2023.05.01 Mingw SDL2

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Non MinGW builds seem to work fine. Is there something about MinGW that is causing crashes and errors?

**Comment by scrutinizer80** [comment]
Both SDL1 & SDL2 MinGW builds crash.

**Comment by scrutinizer80** [comment]
I can't use the VS build since that one still causes a crash in Dos Navigator.

**Comment by maron2000** [comment]
I ran the diagnosis program but I see no flaws.
Tested mingw x64 SDL1, 2 2023.05.01 release and the latest commit f2f4a10 SDL1.
![diagnose_000](https://github.com/joncampbell123/dosbox-x/assets/68574602/c322eaca-ab6f-46b4-9199-30befc7ef4cc)

**Comment by Allofich** [comment]
@scrutinizer80, can you check if this is fixed with the latest code and if so, close it? Thanks.

**Comment by scrutinizer80** [comment]
> @scrutinizer80, can you check if this is fixed with the latest code and if so, close it? Thanks.
The MinGW build still crashes when accessing the sound card on my end.
Using the same dosbox-x.conf file, the previous version works fine.

**Comment by Allofich** [comment]
Thanks for checking. I just tested the MinGW builds from the 05.01 release (SDL2, both x32 and x64), though, and using the default configuration, I had no crash when using the SoundBlaster 16 in a game's sound setup program.

I can see that @maron2000, above, didn't have a crash, either, so I think you're going to need to provide more information to reproduce the problem before anyone can find a fix. What are your dosbox-x.conf settings? Do you have crash when using default settings? What programs crashed when trying to use the SoundBlaster 16?

**Comment by maron2000** [comment]
Tried 2023.05.01 MinGW x64 SDL1release again, and I think you can hear the music playing.
![monkey](https://github.com/joncampbell123/dosbox-x/assets/68574602/31dde43c-41e1-4ba5-b182-24b02f5035b5)

https://github.com/joncampbell123/dosbox-x/assets/68574602/6b52509d-4114-497f-b8a1-da4b6b968ed9

**Comment by scrutinizer80** [comment]
> Thanks for checking. I just tested the MinGW builds from the 05.01 release (SDL2, both x32 and x64), though, and using the default configuration, I had no crash when using the SoundBlaster 16 in a game's sound setup program.
> 
> I can see that @maron2000, above, didn't have a crash, either, so I think you're going to need to provide more information on how to reproduce the problem before anyone can find a fix. What are your dosbox-x.conf settings? Do you have a crash when using default settings? What programs crashed when trying to use the SoundBlaster 16?

This is very strange.
I just checked again. Latest MinGW win64 crashes immediately. The VS build does not. As are older versions. All using the same config file.
I tried pasting my conf file into pastebin.com but it deemed it "offensive" (!) :)
Any other way I can post it?

Thanks

**Comment by scrutinizer80** [comment]
@Allofich

Are you experiencing the crash when using my config file?

**Comment by Allofich** [comment]
I can't access the file at the link. It says it is private or pending moderation.

Anyway can't you attach it here? If you can't do it directly, try putting it in a .zip file first.

**Comment by scrutinizer80** [comment]
@Allofich 

I've made some progress. It seems that not only audio related applications are crashing. I'm having Norton Commander crash on the mingw build as well, while some games do run with audio at times. 
running the SB16 utility MIXERSET.EXE crashes the mingw build 100% of the times yet all is well using the vs build. (sdl2)

Here's my dosbox-x.conf

[dosbox-x.conf.zip](https://github.com/joncampbell123/dosbox-x/files/11814405/dosbox-x.conf.zip)

**Comment by Allofich** [comment]
I can confirm that MIXERSET.EXE crashes with the 2023.05.01 x64 MinGW releases, both SDL1 and SDL2, using default settings. The x32 MinGW releases do not crash.

With the x64 releases, the game setup program I tested with before still doesn't crash, so it varies by the program run.

No crash either when running with a x64 VS build, although this is built from more recent code.

**Comment by Allofich** [comment]
The 2023.03.31 x64 MinGW releases don't crash, so presumably some change in April caused the crash to start happening.

**Comment by scrutinizer80** [comment]
> Here is an x64 MinGW build using the latest commit. Scroll down to "Artifacts" and you can download it:
> https://github.com/Allofich/dosbox-x/actions/runs/5333343427

I can confirm this build using the latest commit is working fine and doesn't crash on my end.
I'm however uncomfortable not knowing where the issue stems from and why it doesn't affect the vs builds. It might return at any given moment.

In any case, the current "released" MinGW x64 builds should probably be marked as defective.

**Comment by Allofich** [comment]
In my testing the issue seems to first appear from this commit:
https://github.com/Allofich/dosbox-x/commit/2218b065373ac2f0c922d756c3c1cd960f15de5c

**Comment by Allofich** [comment]
I haven't confirmed it, but probably this PR fixed this issue:
https://github.com/joncampbell123/dosbox-x/pull/4229

**Comment by scrutinizer80** [comment]
Version 2023.09.01 no longer has this issue.
