### ISSUE TITLE
Where is dosbox-x-mingw-hx-dos-20230501152329.zip file?

### ISSUE THREAD

**Issue by gfernval** [joncampbell123/dosbox-x#4235]
### Question

Where is dosbox-x-mingw-hx-dos-20230501152329.zip file?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I never made one.

**Comment by Torinde** [comment]
@maron2000 - is this related to #4142? I see @joncampbell123 reverted it at https://github.com/joncampbell123/dosbox-x/commit/932012cd1af7bbe8050c11fd3bdc356bf5fc7316

Currently HX DOS actions/build artifacts also fail.

**Comment by maron2000** [comment]
As mentioned in #4142, that fix was a temporary fix that works for the 2023.03.31 release only, so it has to be reverted anyway.
However, the problem still remains so we either have to make a temporary fix again or find a definite solution.

**Comment by Torinde** [comment]
I see the HX DOS workflow is using `*` for the date part of the filename, where other workflows use `${{ env.timestamp }}`

Is that the problem?
