### ISSUE TITLE
Attempt to build on OpenBSD with CLang resulted in `cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t' `

### ISSUE THREAD

**Issue by anoduck** [joncampbell123/dosbox-x#4244]
### Describe the bug

Dosbox-x is more suitable for the work that I do on Dos than dosbox is, so I thought I would give it a try to compile. Since it appears to support compilation on both linux and MacOS, and supports use of clang, it stood a chance of being successfully compiled on OpenBSD. So I have it a go. 

Regardless of whether it was built using gcc (egcc in OpenBSD) or clang the end result was the same, and it does not appear to be the result of a missing library or unsupported feature.

### Steps to reproduce the behaviour

1. Have an OpenBSD system for testing.
2. Install the required libraries using `pkg_mgr`
3. Download the newest release.
4. Attempt to compile.

### Expected behavior

Especially in clang, I sincerely thought the program would compile without a hitch, since it got so close to completion.

### What operating system(s) this bug have occurred on?

OpenBSD 7.3 CURRENT SNAPSHOT

### What version(s) of DOSBox-X have this bug?

dosbox-x-v2023.05.01.tar.gz

### Output log

```text
dos_programs.cpp:5866:40: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                                return NULL;
                                       ^~~~
/usr/include/sys/_null.h:12:14: note: expanded from macro 'NULL'
#define NULL    nullptr
                ^~~~~~~
dos_programs.cpp:6219:17: warning: variable 'ptype' set but not used [-Wunused-but-set-variable]
        uint8_t ptype = 0;     // Partition Type
                ^
dos_programs.cpp:7237:9: warning: unused variable 'cp' [-Wunused-variable]
    int cp=dos.loaded_codepage;
        ^
dos_programs.cpp:8199:14: warning: variable 'open' set but not used [-Wunused-but-set-variable]
        bool open=false;
             ^
33 warnings and 1 error generated.
*** Error 1 in src/dos (Makefile:460 'dos_programs.o')
*** Error 1 in src (Makefile:567 'all-recursive': @fail=;  if (target_option=k; case ${target_option-} in  ?) ;;  *) echo "am__make_running_...)
*** Error 1 in . (Makefile:429 'all-recursive': @fail=;  if (target_option=k; case ${target_option-} in  ?) ;;  *) echo "am__make_running_wi...)
*** Error 2 in /home/user/dosbox-x-dosbox-x-v2023.05.01 (Makefile:337 'all')
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Try `return 0;`

**Comment by anoduck** [comment]
> 

That would totally be a logical alternative. Let me see if it will fly now.

**Comment by anoduck** [comment]
past the previous error, but a new issue emerged, and the prospects of a successful compilation are appearing beyond my reach at this moment. 

I tried the build process in two different ways, by using the `build-debug-with-clang` script and by
manually running `autoconf . ; ./configure --enable-debug=heavy --prefix=/usr/local ; make
-j$(gnproc) -k`. The latter of the two generated hundreds of error, which was obviously the
incorrect method for installation. The former stopped at ‘SDL_bsdaudio.c:306:5’ with an implicit
declaration error. 


``` bash
/bin/sh ./libtool --mode=compile /usr/bin/clang -g -O2  -Iinclude -I/home/user-x/dosbox-x-dosbox-x-v2023.05.01/vs/sdl/include -D_GNU_SOURCE=1 -fvisibility=hidden -I/usr/local/include -D_REENTRANT  -I/usr/X11R6/include -DXTHREADS -DHAVE_USBHID_H -DUSBHID_UCR_DATA -DUSBHID_NEW -D_REENTRANT -Wall -c /home/user-x/dosbox-x-dosbox-x-v2023.05.01/vs/sdl/src/thread/pthread/SDL_syscond.c  -o build/SDL_syscond.lo
/home/user-x/dosbox-x-dosbox-x-v2023.05.01/vs/sdl/src/audio/bsd/SDL_bsdaudio.c:306:5: error: use of undeclared identifier 'audio_info_t'
    audio_info_t info;
    ^
/home/user-x/dosbox-x-dosbox-x-v2023.05.01/vs/sdl/src/audio/bsd/SDL_bsdaudio.c:308:5: warning: implicit declaration of function 'AUDIO_INITINFO' is invalid in C99 [-Wimplicit-function-declaration]
    AUDIO_INITINFO(&info);
    ^
libtool: compile:  /usr/bin/clang -g -O2 -Iinclude -I/home/user-x/dosbox-x-dosbox-x-v2023.05.01/vs/sdl/include -D_GNU_SOURCE=1 -fvisibility=hidden -I/usr/local/include -D_REENTRANT -I/usr/X11R6/include -DXTHREADS -DHAVE_USBHID_H -DUSBHID_UCR_DATA -DUSBHID_NEW -D_REENTRANT -Wall -c /home/user-x/dosbox-x-dosbox-x-v2023.05.01/vs/sdl/src/thread/pthread/SDL_syscond.c -o build/SDL_syscond.o
/home/user-x/dosbox-x-dosbox-x-v2023.05.01/vs/sdl/src/audio/bsd/SDL_bsdaudio.c:308:21: error: use of undeclared identifier 'info'
    AUDIO_INITINFO(&info);
```

**Comment by FrostKnight** [comment]
@anoduck if you ever get it working, say something, because dosbox-x would be a good interesting project for OpenBSD even if the internet wouldn't work, which in my opinion, would be more of my expectation of how OpenBSD would do it anyways.

No security problems would occur then because it would be disconnected from the internet.

**Comment by maron2000** [comment]
According to #3883 I think this is a known issue.
> OpenBSD fails with bundled sdl1 due to audio driver error, its system one use sndio instead of bsdaudio, I have no plan to fix this.

**Comment by FrostKnight** [comment]
> According to #3883 I think this is a known issue.
> 
> > OpenBSD fails with bundled sdl1 due to audio driver error, its system one use sndio instead of bsdaudio, I have no plan to fix this.

Must be OpenBSD specific, I am using Hyperbola and sndio is the sound system I am currently using. Very interesting.

**Comment by anoduck** [comment]
@FrostKnight I wouldn't mind giving it a once over, as my knowledge has significantly expanded since I originally opened this issue. Regretfully, I just have too much going on right now. 

The question is, can dosbox-x be compiled without audio support?

**Comment by FrostKnight** [comment]
> @FrostKnight I wouldn't mind giving it a once over, as my knowledge has significantly expanded since I originally opened this issue. Regretfully, I just have too much going on right now.
> 
> The question is, can dosbox-x be compiled without audio support?

Actually, I wasn't asking that, I was asking more specifically, which part prevents OpenBSD from having dosbox-x support?
I recall sndio was the reason given, but I currently am using sndio in a different operating system and it works with dosbox-x.

Hyperbola is very bizzaro though, so maybe that's why it works with sndio?  Its a distro though.

**Comment by anoduck** [comment]
You are not the only one confused, it makes me scratch my head as well. The only thing that comes to mind is if they ported bsdaudio over and are just using sndio for network server management. I can't even remember what NetBSD was using, mostly because I was only using NetBSD as a server back then. Odd indeed.
