### ISSUE TITLE
PC98: Interlacing graphic error on battle in Game "Shiritsu Tantei MAX 2: Master of Elemental"

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#4245]
### Describe the bug

Hi!
There is some Interlacing graphical issue in game "Shiritsu Tantei MAX 2: Master of Elemental" / "私立探偵マックス2 マスター・オブ・エレメンタル" ( jRPG / 1991-08-02 / PC98 ) on BATTLE attack:
Gamepack to test:
http://coraksoft1.narod.ru/games/jRPG/Shiritsu-Tantei-MAX-2-Master-of-Elemental-PC98-DosboxX.7z
Screebs:
normal battle start: http://coraksoft1.narod.ru/scr/2021-11/168345081661_kiss_26kb.png
distorted after BATTLE option: http://coraksoft1.narod.ru/scr/2021-11/168345086897_kiss_20kb.png

### Steps to reproduce the behaviour

1. Start game on latest Dosbox-X.
2. Skip intro. 
3. Go on field to next battle.
4. Press BATTLE option to strike.

### What operating system(s) this bug have occurred on?

Windows XP

### What version(s) of DOSBox-X have this bug?

latest

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
The first thing you should try if you find graphic glitches on PC98 games is to change GDC option to either 2.5 or 5.0 MHz.

**Comment by Corak667** [comment]
@maron2000 
Thanks! Working now normally with parameter:
[pc98]
pc-98 start gdc at 5mhz=true
http://coraksoft1.narod.ru/scr/2021-11/168348665923_kiss_89kb.jpg
