### ISSUE TITLE
Minimizing DOSbox results in missing text after restoring

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4248]
### Describe the bug

DOS console text disappears when DOSbox-X window is restored from minimized state.
Initial status:
![image](https://user-images.githubusercontent.com/97228894/236663211-ab225522-ddfe-4236-b379-f41120048969.png)
Minimize, then restore window:
![image](https://user-images.githubusercontent.com/97228894/236663220-737da495-a415-4aad-a2f5-0e2f6b0115c9.png)
Pressing Enter or entering any command works normally - from there onwards, but prior text above isn't shown:
![image](https://user-images.githubusercontent.com/97228894/236663258-4961dea4-4e26-46b3-99f3-b1bea1c36e00.png)

### Steps to reproduce the behaviour

1. Minimize DOSbox-X window
2. Restore DOSbox-X window

### Expected behavior

Text to be kept regardless of window state/position/size changes.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2023.03.31 SDL1 64-bit

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
Ugh... now that I started testing with SDL2, different output types, etc. - I can't reproduce it... even with the SDL1 I was using when it happened :(

If that helps - the minimize/restore thing happened while I was doing the screenshots/captures for the CPU and CHKCPU tests #4246

**Comment by maron2000** [comment]
I guess I found out how to reproduce your issue.

Issue1: Launch DOSBox-X SDL1 (Windows) by `output=ttf` and minimize the window.
Issue2: When in TTF mode (SDL1, Windows), capture video. Screen will automatically switch to non-TTF output. Stop capture and minimize the window.

PR #4462 fixes both issues.

**Comment by Torinde** [comment]
Thanks, @maron2000!
I can't test right now, but happy that you found & fixed it.
