### ISSUE TITLE
Break key is Scroll lock in Opera games (Goody, Living, Mission)

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4249]
### Question

Opera software games are supposed to use the `Break` key to return to the title screen (when you are playing). But both in DOSbox-X and Staging - `Pause/Break` doesn't do anything (even with AltGr+Pause, Alt+Pause, [Ctrl+NumLock](https://en.wikipedia.org/wiki/Break_key#Modern_keyboards))
![image](https://user-images.githubusercontent.com/97228894/236670089-fb36399b-f83d-4f9c-8085-c94cfe011320.png)
![image](https://user-images.githubusercontent.com/97228894/236670176-29cbb30d-b083-4f4f-95eb-2cf25e790098.png)

With `Scroll Lock` it works!

Are these two key mixed up on the DOSbox side - or the games' title screens are wrong? (as e.g. Breack is misspelled in Goody)

Could it be that Spanish keyboard has those scancodes different from other keyboards? 

@aybe @FeralChild64

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
In general, there are no dedicated key for Break key but, CTRL+Scroll Lock and CTRL+Pause.
So pressing Scroll Lock as Break makes sense to some extent.
The behavior of actual machine shouldd be checked before suspecting this is a bug.

**Comment by Torinde** [comment]
When I say "With `Scroll Lock` it works!" - I mean with Scroll lock ONLY. Not a CTRL+/ALT+ combination. That's why I think either keys are swapped or game instructions are wrong.

I'll try running those on a physical system...

**Comment by maron2000** [comment]
Yes I perfectly understood your explanation.
I mentioned `pressing Scroll Lock`, not CTRL+Scroll Lock.
You can additionally try `CTRL+Pause` which is the first thing you should try if you have Pause/Break key.

**Comment by Torinde** [comment]
Ran Goody on modern laptop booting FreeDOS - Scroll lock works, Pause/Break doesn't work.

So, conclusion is Opera software problem, not DOSbox problem?
