### ISSUE TITLE
fatDrive::readSector and writeSector address wrong absolute sector according to loadedDisk CHS geometry

### ISSUE THREAD

**Issue by maxpat78** [joncampbell123/dosbox-x#4251]
### Describe the bug

SYNOPSIS:
Accessing a VHD (both Fixed and Dynamic) in LBA mode with INT 13:[43|42]h works always fine, while using DOS emulation to write/read data very often corrupts the file system (except some rare corner cases), resulting in scrambled data.

SYMPTOMS:
I've prepared in Windows 11 a 500MiB DYNAMIC VHD, MBR partitioned and FAT16 formatted; then I've copied a 50M self-extracting ZIP to it.

At this point, if the ZIP self-test is launched from MS-DOS (booted from floppy), it succeeds; also, MS-DOS CHKDSK reports no errors on the mounted DYNAMIC VHD disk.

If the self-test is launched from DOSBox-X shell (or internal 4DOS), instead, it fails; also, executing MS-DOS CHKDSK from it, reports about 50MB lost cluster chains on that mounted VHD drive.

Since the VHD container was healthy (Win11, 7-Zip, and even real MS-DOS from DosBox-X can correctly access the FAT FS in it), it seems that DosBox-X internal FAT emulation/cache does not work properly with VHDs.

Quitted DOSbox-X, I've noticed that the allocated VHD blocks (=container size) are less than data supposed to have been written: about 50MiB data, but only 36MiB container.

Please note that this (old) bug affects VHD drives only (BOTH DYNAMIC AND FIXED), not RAW disk images.

Moreover, I've tried to read/write sequentially a binary file with my upgraded 16-bit RDWR utility:
[RDWR.C.TXT](https://github.com/joncampbell123/dosbox-x/files/11427655/RDWR.C.TXT)

A strange behaviour happens: while you fwrite(512) / fseek(-512) / fread(512), all seems fine (data are written to cache and picked from there?); but when you launch the exe again, to check the file, it is corrupted.
This happens as soon as you ask to write 8MB, for less data there are no erros.

Probably something in fatDrive::writeSector where CHS calculations occur (actually, VHD driver uses fake VHD pseudo-geometry, and looking at debug console shows that some "absolute" sectors are accessed more than required during write) - since a FIXED VHD is like a RAW image with a footer appended, at least that kind of image should work without problems!).

### Steps to reproduce the behaviour

See above.

### Expected behavior

Data written to VHD won't get silently scrambled/discarded.

### What operating system(s) this bug have occurred on?

Windows 11 x64 22H2

### What version(s) of DOSBox-X have this bug?

2023.05.01

### Used configuration

Default with dynamic_x86/Pentium emulation.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maxpat78** [comment]
Another proof that CHS matters some way is that accessing the same drive in LBA mode with INT 13:42h (look at attachment: [RDWRRAW.C.TXT](https://github.com/joncampbell123/dosbox-x/files/11432717/RDWRRAW.C.TXT) ), writing/reading 64M gives no error.

**Comment by maron2000** [comment]
I guess this issue can be closed since the PR is merged.
If you put `Fixes #4251` in the PR  then the issue will automatically be closed when the PR is merged.
Anyway, great effort for the fix!
