### ISSUE TITLE
Free size limit 2TB not to overflow, 2GB limit to be increased

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4258]
> 2. when free size is above 2TB, then is reported the difference (e.g. some counter reaches a limit and overflows?)
> 3. when cap is used and cap is above 1919 - only 1919 MB are reported

That is more complicated, seems a design choice. 

GetDiskFreeSpaceEx Win32 API would avoid doing calculations and return directly byte sizes... but in _64-bit_ form: `localDrive::AllocationInfo` wants 16-bit answers, in pure ol' DOS fashion... perhaps something like `fatDrive::AllocationInfo32` should be implemented also in `localdrive::`, but probably your multi-TB drives would need 64-bit integers even in such case.

_Originally posted by @maxpat78 in https://github.com/joncampbell123/dosbox-x/issues/4004#issuecomment-1541717976_
            
For item2:
If there is a limitation due to being "too big for DOS", then it should be one of those?
![image](https://user-images.githubusercontent.com/97228894/218300946-529c2116-bff0-41f6-8220-e5e841ca64b9.png)

Seeing that DOSbox-X shell shows properly 8GB files (beyond the 4GB max for FAT32), I assume it's possible to show volume sizes beyond 2TB as well. Please consider that it's feasible to have a volume with dozens of TB free space (a few high capacity HDDs in NAS).

In any case if actual free space is above the limit, DOSbox should report the limit instead of overflowing (e.g. 2TB+1byte available should not be reported as 1 byte free).

For item3:
when using a freesize cap I get up to a maximum of 1919 MB. Values above give wrong result of 1919MB:
![image](https://user-images.githubusercontent.com/97228894/218303658-1d9c7021-ebb6-4841-a067-7ee6e0bcd8da.png)

**Comment by maxpat78** [comment]
Did you look at `localDrive::AllocationInfo` ? Before touching that code, the question is: why a so long and complex code, to express results in clusters and clusters _ratios_?
Intuitively, I would start from 64-bit size and do 64-bit math as long as possible, converting to 32/64-bit at last, but it could break compatibility with something... or make a variable-size AllocationInfo structure to adapt to caller needs.
Also, counterpart Linux code should be written and checked.

**Comment by Torinde** [comment]
I can relate to your intuitive remark. Will it break something? I don't know, not enough experience to have opinion on whether that code is messy or not...

As I wrote at your PR - it solves the 2TB limit, but I don't know where the 1919MB cap limit is coming from or why cap gets ignored in your PR...

If you have ideas for tests to do - let me know.
