### ISSUE TITLE
Laggy response (keycheck.com) since 2023.3.31 build (Windows VS x64)

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#4268]
### Describe the bug

Response when a key is preseed on a keyboard checking program `keycheck.com` downloaded from [here](https://www.ers.kestar.com.au/dos.html) is very laggy.
You can see that the circulating symbol sitting below of R/ALT is moving intermittently.

### Steps to reproduce the behaviour

1. Boot dosbox-x with default config `dosbox-x -defaultconf`
2. Download the `keycheck,com` and run it.

### Expected behavior

Works without lag on 2022.12.26 release. 

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

VS x64 build SDL1/SDL2 2023.03.31 and 2023.5.01

### Used configuration

```ini
Default conf (`dosbox-x -defaultconf`)
```

### Output log

```text
Nothing special is shown, just `LOG: Flush STDIN`
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
This may be an issue with the INT 28h "idle API" that was fixed soon after May 1st.

**Comment by maron2000** [comment]
Sorry, I wasn't aware of the fix.
As you said. I confirm that this issue is already solved in the latest commit.

**Comment by Torinde** [comment]
INT 28h - it seems there is a related DR-DOS command "[IDLE](https://www.os2museum.com/wp/idle-dr-dos/)" (built-in capability similar to MS-DOS POWER.EXE) - OS2museum made a test driver for it.

Maybe IDLE and POWER.EXE can be emulated in DOSbox-X.
