### ISSUE TITLE
No dosbox.conf on Mac os 

### ISSUE THREAD

**Issue by sussyboiiii** [joncampbell123/dosbox-x#4276]
### Question

Hello,
I have tried to run doom 1993 on my Apple Silicon macbook with dosbox-x and it runs, but I unfortunatley can't configure dosbox to always run in fullscreen which I would prefer. I have looked for the config file in ~/Library/Preferences but unlike said in a different post about this topic its not to be found, I also made a search on my whole drive but it didn't find the config file.
After this I ran the build-macos file but it didnt change anything. 
Hopefully someone can help me on this!
Thank you!

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by sussyboiiii** [comment]
I have tried to save my config in the configuration tool and it wanted to save to ~/Library/Preferences but it didn't save but also didn't give me an error or anything.

**Comment by ezathashim** [comment]
It only seems to save the file when you set the working location for the DosBox app. Usually that prompt appears when you launch DosBox. The default location is somewhere in the DosBox package but I manually make a folder in Documents or somewhere for this.

**Comment by sussyboiiii** [comment]
I redownloaded dosbox-x and put it back into programs but I couldn't specify the direcory

**Comment by ezathashim** [comment]
In the DosBox menu, there is a configurator tool that you can use. Adding a modification to it (like in autoexec.bat or in the printing options) and pressing save should create a preferences file in ~/Library/Preferences. It is currently names something like 'DOSBox-X 2023.05.01 Preferences'.

**Comment by sussyboiiii** [comment]
I have pressed save there but it didn't save it unfortunatley

**Comment by joncampbell123** [comment]
It used to be nothing saved if you ran from the Finder because the Finder made "/" the current working directory! You can't write there, even if you're super-user!

**Comment by sussyboiiii** [comment]
Ok, so should I run ist from the save directory with terminal or is it fixed because you say used to?

**Comment by sussyboiiii** [comment]
For some reason it now just works? Whatever
