### ISSUE TITLE
Linux compilation: src/cpu/core_dyn_x86/Makefile.in not found

### ISSUE THREAD

**Issue by legluondunet** [joncampbell123/dosbox-x#428]
Hello,

I can no more compile dosbox-x on linux:

`
configure.ac:628: error: required file 'src/cpu/core_dyn_x86/Makefile.in' not found`

The folder is no present on github but configure still need it.

Thank you for your help.

**Comment by joncampbell123** [comment]
I recently removed the dynamic core.

However I forgot to update configure.ac to match.

Fixing that now.

**Comment by joncampbell123** [comment]
Fixed.

**Comment by legluondunet** [comment]
Thanks.
