### ISSUE TITLE
Volkov Commander has very laggy keyboard input

### ISSUE THREAD

**Issue by oboroc** [joncampbell123/dosbox-x#4285]
### Describe the bug

May 1, 2023 version fixed lag in Pacific C I reported earlier (https://github.com/joncampbell123/dosbox-x/issues/4211), but now Volkov Commander 4.05 (https://vvv.kiev.ua/download/) got very laggy keyboard input. It was working fine in previous version.

### Steps to reproduce the behaviour

1. Download Volkov Commander 4.05 from the developer site: https://vvv.kiev.ua/download/vc405sw.zip
2. Unpack in VC directory, run VC.COM
3. Move arrows up/down, type something.
4. If you disable clock in top-right corner, keyboard lag is gone.

### Expected behavior

Volkov Commander is written in x86 assembly and is very responsive even on a base 8088 @ 4.77MHz. There should be no keyboard lag.

### What operating system(s) this bug have occurred on?

Windows 10 Pro 22H2

### What version(s) of DOSBox-X have this bug?

dosbox-x-winXP-2023.05.01-setup.exe

### Used configuration

```ini
Default configuration
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
There are some flaws remaining in the May release, such as mentioned in #4280 and some other tickets.
Try the recent development builds and see if your mentioned issue is solved.

**Comment by oboroc** [comment]
@maron2000 thank you, is there a place I can download nightly builds? Or do I have to compile myself?

Also, is there a way to disable power saving keyboard stuff, so it's back to vanilla DosBox behavior?

**Comment by maron2000** [comment]
If you go to the DOSBox-X website https://dosbox-x.com/ there is a link to the development builds.

**Comment by oboroc** [comment]
@maron2000 I did look, but didn't find any development builds. If you think the issue is resolved, please close it.

**Comment by maron2000** [comment]
Are you sure that you can't find it?
From the link below, click the link to the build you desire.
On the bottom of the page you can find the ARTIFACTS, which are development builds built by github.
https://dosbox-x.com/devel-build.html

**Comment by pppq** [comment]
There is also a pinned issue in this repository: https://github.com/joncampbell123/dosbox-x/issues/3822
