### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#430]
Well, well, well, I've seen the many recent contributions and really wanted to help a bit but was mad sick :(

For the little I've seen on the Windows-side I didn't like how that VS solution slowly went from shiny to spaghetti monster, with lots of black magic and partial usability (some configurations simply don't work).

So I've thought *Why not try CMake all that !?* :) The first days were tough and I was left in the dust, but today it gets interesting as those 2 weeks of work now sound like it was worth the trouble !

Lemme introduce you CMake for dosbox-x:

![2017-12-31 00_09_06-dosbox-x - microsoft visual studio](https://user-images.githubusercontent.com/1537591/34457866-d6e47f2a-edbe-11e7-8bde-7a89e0288b1f.png)

**It is not yet finished but looks promising and works rather well.**

I wanted to push it to the extreme and provide the best possible experience and ease of use, e.g. the folder structure that looks like sources.

The strong selling point of this IMO is that the Visual Studio solution is now **only** a generated stub, nothing more. It was bulky, confusing, and platform-specific. With a CMake approach, it opens the door to auto-generate files for your favorite IDE on your favorite platform, whatever it is (help wanted).

Also, wide changes should be applicable through the CMakeLists.txt to propagate globally instead of Windows-only, e.g. disable `core dynamic` component files etc ...

## Notes

Here's the (preliminary) README:
https://github.com/joncampbell123/dosbox-x/blob/cmake/README.CMAKE.md

Here's the (preliminary) CMakeLists.txt:
https://github.com/joncampbell123/dosbox-x/blob/cmake/CMakeLists.txt

Here's the (preliminary) release with pre-built components (as a reference than anything else):
https://github.com/joncampbell123/dosbox-x/releases/tag/cmake

It required only that tiny change in the sources : https://github.com/joncampbell123/dosbox-x/commit/36c616387773b68d95079a328c8af660044313c0

In regards to additions made to SDL (luckily there was only one), I've ported them to a [dedicated folder in the sources](https://github.com/joncampbell123/dosbox-x/tree/cmake/src/sdl_patches), IMO these should be either in this form or, providing the need of having a custom-version of SDL, in a dedicated repository (they'd be extremely difficult to follow otherwise).

Many things are still needed,

- port all of `config.h.in` flags
- provide download of a package of dependencies ready to use
- polish
- *whatever*
- testing

Waiting for your remarks and improvements,

Other than that I will continue bringing all of the remaining configuration options through CMake to get it on par with the actual solutions (currently, just the vital minimum was enabled to assess of the feasibility of this new approach).

**Comment by joncampbell123** [comment]
VS2017 forced me to make a mess because somewhere along the way conditional per-target build dependencies disappeared, so there's no way to tell VS2017 I don't want SDL1 compiled in for SDL2 builds.

If the cmake based system improves this situation, then it works for me. I'll keep the autoconfig stuff on the Linux side working.

**Comment by aybe** [comment]
Not sure I understand,

Something has been lost somehow and you restored more or less that functionality, differently ?

Until I clearly understand your answer, I think CMake should be able to model such behavior.

**Comment by joncampbell123** [comment]
VS2017 won't let me say that "Release" should compile only against SDL1, and "Release SDL2" should compile only against SDL2. It insists on SDL1 as a dependency for both, without the option not to.

What is needed is the Release/Debug builds to compile only against SDL1, and Release/Debug SDL2 to compile only against SDL2.

**Comment by aybe** [comment]
Yes, that's weird because I have been able to replicate such behavior on a mini test project.

Anyway, there is an alternative for CMake : `add_executable`  where basically, we'd end up with 3 projects : SDL1, SDL2, SDL1+SDL2.

Here are the advantages I see in this approach:
- configurations are kept as usual, Debug/Release
- since each flavor is a project there wouldn't be unnecessary rebuilds because they're separated
- it is very easy to implement

I still need to bring in SDL2 in the config then I'll take a look at this issue.

**Comment by aybe** [comment]
Closing until further notice, focusing to `Fixing and cleaning up the Visual Studio solutions #438
` instead.

While this is interesting, it has been very time consuming and still going to be + the fact that external dependencies are already well setup in the manually crafted VS solution.

(I really don't have the CMake expertise to get it up in a reasonable time frame)
