### ISSUE TITLE
What is the status of the merging of SDL 1 and 2 ?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#431]
I would like to know the situation on this, at the same time this issue could be the de-facto hub centralizing all stuff related to this enhancement.

Not really sure about what and how to ask,

Rather, I was hoping that the authors of it could sketch out a mini-report of the situation.

**Comment by joncampbell123** [comment]
The main and develop branches already have both SDL1 and SDL 2 support merged together. You can choose one or the other at compile time. The VS2017 project files have it too.

**Comment by joncampbell123** [comment]
I was able to merge SDL 2 support in a way that preserves CD-ROM emulation even if SDL2 builds can no longer directly talk to the CD-ROM drive on the host system.

**Comment by aybe** [comment]
Let's make it clear because it's not for me,

For the build to succeed:
 - SDL 1 is mandatory, correct ?
 - SDL 2 is optional, correct ?
 - or either can be used ?
 - or something else ?

(for the little I've seen, `C_SDL1` is used nowhere which made me end up it's implicitly used, on the other hand, `C_SDL2` usage is visible throughout the code and its intent is clear.)

**Comment by joncampbell123** [comment]
If you tell ./configure to use SDL1, then only SDL1 is needed.

If you tell ./configure to use SDL2, then only SDL2 is needed.

It may fallback to SDL1 if SDL2 sdl2-config is not in your PATH.

Make sure your distribution includes the development headers and sdl2-config tool for SDL2 if you want SDL2.

**Comment by joncampbell123** [comment]
Make sure to check config.log as well.

**Comment by aybe** [comment]
Alright,

**Comment by joncampbell123** [comment]
I also want to point out that SDL 1.x Linux builds of DOSBox-X now compile against it's own internal version of SDL 1.x rather than the systemwide version, and that the internal version contains several bug fixes I've made since.

**Comment by aybe** [comment]
Is it the version that is sitting in `vs2015` ?

**Comment by joncampbell123** [comment]
It is.

**Comment by aybe** [comment]
Okay I will look at reusing it instead of bringing a package of pre-built dependencies.

**Comment by aybe** [comment]
Closing ! -> Fixing and cleaning up the Visual Studio solutions #438
