### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [joncampbell123/dosbox-x#432]
Hi, the latest git source cannot build on my Fedora27.

make[3]: Entering directory '/home/hoge/aho/d/src'
g++  -g -O2  -std=gnu++11  -mmmx -msse -msse2  -Wno-strict-aliasing  -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L    -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a aviwriter/libaviwriter.a mt32/libmt32.a -lasound -lm -ldl -lpthread -lSDL -lpthread -lSDL_net -lpng -lz -lX11 -lfluidsynth -lGL
ints/libints.a(bios.o): In function `BIOS::cb_bios_post__func()':
/home/hoge/aho/d/src/ints/bios.cpp:4132: undefined reference to `DEBUG_CheckCSIP()'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:415: dosbox-x] Error 1
make[3]: Leaving directory '/home/hoge/aho/d/src'
make[2]: *** [Makefile:448: all-recursive] Error 1
make[2]: Leaving directory '/home/hoge/aho/d/src'
make[1]: *** [Makefile:379: all-recursive] Error 1
make[1]: Leaving directory '/home/hoge/aho/d'
make: *** [Makefile:320: all] Error 2

**Comment by joncampbell123** [comment]
Short term: Compile with --enable-debug=heavy.

Long term: I'll push a commit to fix that.

**Comment by joncampbell123** [comment]
Pull the latest commit and try again, without the debugger.

**Comment by tokumeiwokiboushimasu** [comment]
Fixed. Thanks.
