### ISSUE TITLE
are there doing to be more hx-dos builds ?

### ISSUE THREAD

**Issue by stuaxo** [joncampbell123/dosbox-x#4321]
### Question

I discovered you can run the hx-dos build of dosbox-x inside dosemu2.

However the most recent releases don't have an hx-dos build, will it be coming back ?

https://github.com/dosemu2/dosemu2/issues/2014#issuecomment-1579262054

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Already you can download the latest development builds, where you can find the link in the DOSBox-X website.
Some change in github system made HXDos build to fail but is hopefully fixed for the coming release.
