### ISSUE TITLE
TITLE.COM cannot display Chinese

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#4346]
### Describe the bug

Please check the program
scr\dos\dos_program.cpp

About TITLE.COM
To display Chinese characters, the program is OK as below:

*-----------------------------
class TITLE : public Program {
public:
    void Run(void);
private:
	void PrintUsage() {
        constexpr const char *msg =
           "Sets the window title for the DOSBox-X window.\n\n"
           "TITLE [string]\n\n"
           "  string       Specifies the title for the DOSBox-X window.\n";
        WriteOut(msg);
	}
};

bool CodePageGuestToHostUTF8(char *d/*CROSS_LEN*/,const char *s/*CROSS_LEN*/);

void TITLE::Run()
{
	// Hack To allow long commandlines
	ChangeToLongCmd();

	// Usage
	if (cmd->FindExist("-?", false) || cmd->FindExist("/?", false)) {
		PrintUsage();
		return;
	}
	char *args=trim((char *)cmd->GetRawCmdline().c_str());
    char title[4096];
    if(CodePageGuestToHostUTF8(title, args)) {
        dosbox_title=title;
    } else {
        dosbox_title=args;
    }
    SetVal("dosbox", "title", dosbox_title);
    GFX_SetTitle(-1,-1,-1,false);
}

static void TITLE_ProgramStart(Program * * make) {
    *make=new TITLE;
}

### Steps to reproduce the behaviour

in DosBox-X
d:\> TITLE  非凡系統

The modification was correct before, but the code of the current website has been changed to the wrong one.

### What operating system(s) this bug have occurred on?

Windows 11 22H2

### What version(s) of DOSBox-X have this bug?

v2023-06-21

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Arthur3032** [comment]
there #4325, does not fix, please check again

**Comment by maxpat78** [comment]
should be decided if restore the old, deleted patch, or apply your new one

**Comment by maron2000** [comment]
It seems to be working.
Since the PR isn't merged yet, make sure you're trying the appropriate build.

![title](https://github.com/joncampbell123/dosbox-x/assets/68574602/2714331b-c636-4014-aa8f-a6a33e2c4d87)

**Comment by Arthur3032** [comment]
> It seems to be working.
> Since the PR isn't merged yet, make sure you're trying the appropriate build.

Ok, I see, Thank you.
