### ISSUE TITLE
Why has there been no official launch this June?

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#4348]
### Question

I would like to know what the reason is.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
My professional work has kept me very busy all summer. Now that things are settling down I will have a September 1st release.
