### ISSUE TITLE
Built-in mouse driver limited to 80 columns in some modes

### ISSUE THREAD

**Issue by FeralChild64** [joncampbell123/dosbox-x#4353]
### Describe the bug

In some tweaked screen modes (like 94x25 in some versions of _DOS Navigator_) it is not possible to move mouse cursor past 80th column.

The problem is in `Mouse_AfterNewVideoMode` function in `mouse.cpp` - for text mode 0x3 it takes numbers of rows from the BIOS, but uses hardcoded number of columns; this won't work correctly if the guest software tweaks the number of columns too.
Until recently used to have the same problem in _DOSBox Staging_ (https://github.com/dosbox-staging/dosbox-staging/blob/main/src/hardware/input/mouseif_dos_driver.cpp, `MOUSEDOS_AfterNewVideoMode` function).

### Steps to reproduce the behaviour

1. Get DOS Navigator OSP 6.4.0 (might work with some other forks too) - https://dnosp.su/
2. After running DOS Navigator, select _"diamond" menu_ (top-left screen corner) -> _Change Screen Mode_ -> _94 x ??_ -> select any
3. Try to move mouse cursor over 80th column - won't work

### What operating system(s) this bug have occurred on?

Linux

### What version(s) of DOSBox-X have this bug?

e62dd921669e8321b190e9e5ffcc3444322c1e64

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Arthur3032** [comment]
mouse cursor position, you can calculate it by yourself in proportion
