### ISSUE TITLE
Windows: OpenGL output starts up in OpenGL NB mode, even if output=opengl

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#436]

**Comment by joncampbell123** [comment]
output=opengl is causing OpenGL output to start up without bilinear interpolation.

The menu code mis-interprets this as having selected OpenGL-NB output

**Comment by joncampbell123** [comment]
Fixed it. I will post a binary soon.

**Comment by vandenk** [comment]
Ok thanks

**Comment by joncampbell123** [comment]
Binary was posted.

**Comment by vandenk** [comment]
works
