### ISSUE TITLE
Kaeon - Horizontal Scrolling Corruption

### ISSUE THREAD

**Issue by JWatersMeet** [joncampbell123/dosbox-x#4361]
### Describe the bug

When running the shoot-em-up Kaeon, the graphics are corrupt in game when the playfield scrolls horizontally. See the video below.

https://github.com/joncampbell123/dosbox-x/assets/136824455/af061dce-eb08-43be-9063-d0f2a82e8c1e

### Steps to reproduce the behaviour

Start Kaeon, Start New Game, Notice Corruption.

### Expected behavior

The playfield should scroll horizontally smoothly.

### What operating system(s) this bug have occurred on?

Windows 11

### What version(s) of DOSBox-X have this bug?

All Known

### Additional information

I have tried all kinds of options to fix, including manually adjusting CPU cycles to get the timing right, but no luck. The game renders correctly in x86Box.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Have you tried different VGA adapter options, in particular `machine=vgaonly`?

**Comment by JWatersMeet** [comment]
Thanks for the suggestion, but no luck unfortunately, including vgaonly.

**Comment by grapeli** [comment]
This is a regression that came with some patch backported from dosbox-svn. I briefly checked under dosbox 0.74-2 it works fine. Under dosbox-svn and dosbox-staging incorrectly. Probably, and under one of the older versions of dosbox-x, it also worked correctly.

**Comment by MX9000** [comment]
@grapeli I don't know if this information would be helpful in identifying the regression cause, but the game guide refers to a particular screen refresh technique that is used only if a certain range of RAM addresses are not allocated to high memory.

![kaeon_000](https://github.com/joncampbell123/dosbox-x/assets/58113425/2b4b80ae-2d98-4164-bf87-f597b94113e7)

**Comment by JWatersMeet** [comment]
Thanks all - I've tracked the regression range down by a manual bisection - the rendering broke in the Jan 11th 2016 build of DOSBox-X.

https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-v0.801.gusandbootfixes.b4

_Gravis ultrasound DMA, IRQ, and DMA streaming emulation fixes. Boot stage reorganization, to shift to hardware -> BIOS -> DOS bootup process. S3 graphics emulation fixes. Linear framebuffer fixes, Windows no longer crashes with S3 emulation. VESA BIOS hacks were added for games that have modelist reading problems._

As such, I assume the regression is in the changes at yhe link below.
https://github.com/joncampbell123/dosbox-x/compare/dosbox-x-windows-v0.801.newyears.b3...dosbox-x-windows-v0.801.gusandbootfixes.b4

**Comment by grapeli** [comment]
I ran git bisect. With default settings it was working fine until before this commit c0e07de. With this change, you need to change the default s3 card to et4000.

Works correctly.
`dosbox-x -set machine=svga_et4000`

**Comment by JWatersMeet** [comment]
Setting it to an ET4000 fixes it - many thanks!

Though, I definitely see it break under the default S3 SVGA option and VGA Only options in the regression range i posted above - is that becuase this would also break on a real S3 card and the changes in the regression rane actually make that behaviour accurate?

**Comment by grapeli** [comment]
@JWatersMeet 
I just tentatively assumed it might be a regression. It's hard to say what it should look like (I'm not a programmer). Operation in dosbox-x is the same as in dosbox-staging and dosbox-svn, for correct operation use `machine=svga_et4000`. It's not a big hassle or complication.

Just out of curiosity, I checked the operation of this game under Qemu and Dosemu2, in both cases the graphics are displayed correctly, but in both cases the game runs much, much too fast.

**Comment by JWatersMeet** [comment]
I'll mark as closed given there's a fix. Yes, it runs too fast as well, but at least it runs now.
