### ISSUE TITLE
Running program on identical hardware works on one,  not on the other.

### ISSUE THREAD

**Issue by VdErik** [joncampbell123/dosbox-x#4364]
### Question

A friend of mine recently bought 2 identical PC's (same MSI MB, same memory).  I have an old MS-DOS Clipper 5.3 program,  compiled with (the then default) Exospace compiler which I try to run on both these PC's.   
One one,  it runs out of the box without any modifications whatsoever in the DOSBOX-X config file, but it will not run on the other.   
The program itself starts & it shows a first B/W screen "Loading Configuration",  but then it exits to the prompt (while as the "working" configuration goes to the login-screen) .  What can I do to start debugging what parameters (if any?) to change? 
![20230429_102003](https://github.com/joncampbell123/dosbox-x/assets/138674127/aa706aaf-ea81-4f4a-8f41-1d4cac8e9f9a)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Well, clearly there must be a difference. Do they run completely local, no networking?

I assume with "exits to the prompt", you mean the Clipper application exits back to the DOSBox-X DOS prompt?

I would start with checking the DOSBox version, DOSBox config and Clipper program and data files for differences.

Also in the screenshot you are NOT using DOSBox-X, but rather DOSBox 0.74-3.

**Comment by VdErik** [comment]
Hi Robert,  thx for answering.
Program & data are indeed on a local (D) drive,  and indeed - the "crashing" one comes back to the DOSBox-X DOS prompt (without any error message).  Sure,  the screenshot is from the 'standard' DOSBox (on the working configuration), - that's why I tried DOSBox -X (2023-05-01),  which still works on the working config,  but (both) do not work on the PC with the problem.   Both run on 64 bit Windows 11 22H2, with 16Gb RAM.  

I've completely reinstalled the non-working PC from scratch, DOSBox-X being the first program to install after reset, still same error.  If I install out of the box without any adjustments to the config,  it runs on one but not on the other,  so question is:  with what parameter(s) should I start to fiddle ;-) (there are thousands of permutations)

**Comment by rderooy** [comment]
You should use the same "dosbox.conf" config file for both (assuming you are not using a custom config file). So take the one from the working system and move it to the non-working one. Also take the program and data files (e.g. zip them) on the working system and copy them to the non-working one.

Really there is no point in starting to fiddle with dosbox settings if you already have a working setup. And you are right there is often no quick and easy way, it could be a dosbox setting, it could be something as simple as running loadfix before the program, or perhaps something is wrong with the data files (or even the host filesystem permissions if you are using a host folder in dosbox-x).

**Comment by VdErik** [comment]
Hi Robert,
unfortunately,  I've done all what you describe above.  Zipped all data from the working config + DOSBox-X config file & copied it to the nonworking PC (incl same rights).  I have 3 other Win 11 systems of my own (different brands,  different configs): all work as a charm.  Didn't try loadfix (& will do this this evening) but I doubt it will help,  as the Exospace Linker was especially created to handle High Memory...

**Comment by VdErik** [comment]
All,   unfortunately Loadfix didn't do the job,  but found a solution.   The program loads a font from a config file & pushes it into video memory.  At that point the program crashes.  Making a (program) config which does not do that & defaults to the ROM-font allowed the program to start.
Thanks for the efforts
