### ISSUE TITLE
Virtual machine (Win98/WinME) can't write to mounted dir of host, and Dosbox-x crashed when shutdown

### ISSUE THREAD

**Issue by Fans1681** [joncampbell123/dosbox-x#4368]
### Describe the bug

When I mount a dir on host, e.g. 

mount D D:\game

Then, In Win98/WinME I can see D:, also I can edit the file in D:, but it's NOT really write to D:\game of host. 

Also, when Win98/WinME shutdown, Dosbox-X crashed.  If I remove "mount D D:\game"  inside the  win98.conf,  Win98/WinME will shutdown successfully, and Dosbox-X has no crash.

### Steps to reproduce the behaviour

1. Setup the Win98 Virtual machine
2. mount a dir of host in the CONF file, e.g.

[autoexec]
IMGMOUNT C: WinME.img
MOUNT D: "D:\game"
BOOT C:

3. In Win98 Virtual machine, I can see D:, I can even to edit the file inside D:, it seems sucessfully. But, in fact, NOTHING changed into D:\game of my host ( Win7 x64), no file changed, no file added.

4. When  Win98 Virtual machine shutdown, Dosbox-X crashed.

### Expected behavior

I think any programmer don't like his software crashed, so fix it first. As for another bug, it can be regarded as a "read-only" mode now,  and it should be fixed later.

### What operating system(s) this bug have occurred on?

Win7 x64 professional SP1 (Simply Chinese)

### What version(s) of DOSBox-X have this bug?

dosbox-v2023.05.01

### Used configuration

```ini
[autoexec]
IMGMOUNT C: WinME.img
MOUNT D: "D:\game"
BOOT C:
```

### Output log

```text
The last content of logs when Dosbox-X crashed are below, it seems crash happened after switching to 640*480.

( Is the next step is to unmount D: ? )


 436993435 ERROR CPU:Write 20 to rom at c25c3ffc
 436993437 ERROR CPU:Write 7 to rom at c25c3ffd
 436993440 ERROR CPU:Write 20 to rom at c25c3ffe
 436993442 ERROR CPU:Write 7 to rom at c25c3fff
pixratio 1.200, dw true, dh false
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
Plug & Play OS reports itself inactive
INT 15h mouse reset


( Dosbox-X crashed and log file ended here )
```

### Additional information

About the configure of NE2000, It's NO NEED to install wincap/NCap in  Windows, because we can easily get the adapter name "Realtek PCIe GBE Family Controller #2" by "Network Property" panel.

Also, we can run " ipconfig /all " in cmd console and easily copy the adapter name:

C:\Users\Admin>ipconfig /all

Windows IP 配置

以太网适配器 本地连接 3:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller #2    <------  The adapter name It's here !
   物理地址. . . . . . . . . . . . . : 00-E0-4C-1B-41-43
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.7(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.1.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 本地连接 4:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter
   物理地址. . . . . . . . . . . . . : 0A-00-27-00-00-14
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::7466:6324:6d94:6349%20(首选)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Fans1681** [comment]
About this issue, if it's not replied within this month, may be it is difficult to solve, or it is no need to solve it. In this case, I should close this topic until 1st August.

The function of sharing host directory is available in VirtualBox and VMware. The situation now, is the shared directory is read-only, but it doesn't seem to trouble me, even though dosbox-x carshed when win98 shutdown.

However, of Dosbox, this issue may be some troubles, because the virtual directory must be converted to FAT format, also the problem of updating the files in real time. ( and somehow, the dir exceeds 4GB ?)

That's all right, thank you again for developing such a good VM tool.

**Comment by rderooy** [comment]
The easiest solution to your problem is to use IMGMOUNT to mount a HDD Image file, instead of trying to use folder mounts. Folder mount support with a Guest OS is relatively new, and not tested extensively.

Also the main developer has other real-world priorities that are preventing him from being as active as he used to be. Perhaps he will find some time again in the future.

**Comment by Fans1681** [comment]
I think any programmer don't like his software crashed, so fix it first. As for another bug, it can be regarded as a "read-only" mode now,  and it should be fixed later.

So I close this issue because I'm sure the "crashed" bug will be fixed sooner or later.  

That's all right, thank you again for developing such a good VM tool.
