### ISSUE TITLE
Can't detect SB16 in Win98 (device is not working properly)

### ISSUE THREAD

**Issue by Notarget137** [joncampbell123/dosbox-x#437]
![sbsettings](https://user-images.githubusercontent.com/35071628/34527621-28557f76-f0b7-11e7-8587-2332a2c5267e.png)

dosbox.conf

[sblaster]

sbtype=sb16
sbbase=240
irq=5
mindma=-1
irq hack=none
dma=7
hdma=0
pic unmask irq=false
enable speaker=true
enable asp=false
disable filtering=false
dsp write buffer status must return 0x7f or 0xff=false
pre-set sbpro stereo=false
sbmixer=true
oplmode=auto
adlib force timer overflow on detect=true
oplemu=default
oplrate=44100
hardwarebase=240
force dsp auto-init=false
force goldplay=false
goldplay=true
goldplay stereo=true
dsp require interrupt acknowledge=auto
dsp write busy delay=-1
blaster environment variable=true
sample rate limits=true
instant direct dac=false
stereo control with sbpro only=true
dsp busy cycle rate=-1
dsp busy cycle always=-1
dsp busy cycle duty=-1
io port aliasing=true

**Comment by joncampbell123** [comment]
This is already known. #244
