### ISSUE TITLE
mouse is unusable in Ubuntu 20.04 due to being too fast

### ISSUE THREAD

**Issue by gfernval** [joncampbell123/dosbox-x#4373]
### Describe the bug

I have compiled dosbox-x 2023.05.01 source code in Ubuntu 20.04, mouse is unusable in Ubuntu 20.04 due to being too fast, changing sensitivity in dosbox-x.conf does not help. Have tried MS-DOS 5.0 Edit and Windows 3.1

### Steps to reproduce the behaviour

I have compiled dosbox-x 2023.05.01 source code in Ubuntu 20.04, mouse is unusable in Ubuntu 20.04 due to being too fast, changing sensitivity in dosbox-x.conf does not help. Have tried MS-DOS 5.0 Edit and Windows 3.1

### Expected behavior

Mouse should work fine, like in Dosbox for Windows

### What operating system(s) this bug have occurred on?

Ubuntu 20.04

### What version(s) of DOSBox-X have this bug?

 dosbox-x 2023.05.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Are you using the SDL1 or SDL2 build? Input is handled by the SDL library, and the versions behave different in various ways.

**Comment by gfernval** [comment]
My fault, forget to say that I use Ubuntu in Virtualbox,  I use SDL2 build (cannot compile in SDL1 due to missing libs?) Anyway, in https://gaming.stackexchange.com/questions/16565/mouse-jumps-around-when-using-dosbox found the solution: " this was an issue with VirtualBox's mouse integration. To fix it, disable your virtual machine's mouse integration by right clicking on the mouse icon in the bottom right-hand corner (second icon from the right" Doing this mouse works fine.

Another thing I found is that Spanish keyboard does not work (does not map keys correctly), only works US keyboard, I have tried to enable and disable uescancodes in dosbox-x.conf with no result

**Comment by gfernval** [comment]
keyb.com from MS-DOS 5.0 does not work well in Dosbox for Linux (does not map correctly keys), but works well in Dosbox for Windows, anyway I have found a replacement (ckeysp.com) that works well in Dosbox for Linux, problem solved.

About using real serial ports in Linux, In dosbox-x.conf I have the line:

"serial1       = directserial realport:ttyS0"

that works well if I run "sudo ./dosbox-x -conf dosbox-x.conf" (without sudo does not work) is this correct?

About using real parallel ports in Linux, what is the correct syntax in dosbox-x.conf?

parallel1 = reallpt realport:/dev/parport0

or 

parallel1 = reallpt realport:parport0

I use a motherboard with integrated parallel ports (no PCI parallel cards, no USB to parallel adapters)

(I haven´t checked the motherboard with the parallel port)

**Comment by rderooy** [comment]
If serial ports work with sudo, but not without, there is clearly a permission issue that you user does not have access to the serial port, which is totally normal.

Most linux distributions have a group called "dialout", and just adding your userid to that group should be sufficient.

As to your issue with spanish keyboard, I don't know what the issue is, I tested a variety of European keyboard layouts some months ago with the SDL2 build and did not run into any issues.
