### ISSUE TITLE
Hercules InColor bug

### ISSUE THREAD

**Issue by viti95** [joncampbell123/dosbox-x#4375]
### Describe the bug

Wrong behaviour testing Learn222 program with latch.lst listing (Hercules InColor driver floppy, TUTOR folder [http://www.dosdays.co.uk/media/hercules/incolor/hercules_incolor.zip](http://www.dosdays.co.uk/media/hercules/incolor/hercules_incolor.zip))

86Box (correct):
![screen](https://github.com/joncampbell123/dosbox-x/assets/8323882/ce2567f4-50ae-412e-ab0a-0db9f72bb7fb)

DosBox-X (wrong):
![screen01](https://github.com/joncampbell123/dosbox-x/assets/8323882/6de00e45-0564-4456-b51d-12f0a1a0e715)

### Steps to reproduce the behaviour

1. Load learn222 program
2. press enter
3. write "read", press enter
4. write "latch.lst", press enter
5. press multiple times enter, each step will update the screen

### Expected behavior

Show correct screen changes

### What operating system(s) this bug have occurred on?

Linux Lubuntu 22.04

### What version(s) of DOSBox-X have this bug?

Tested on commit 2e6f70c3ed9dd35a384a2e221acbd9f5e9101a5e, pretty sure the bug is elsewhere

### Used configuration

```ini
machine=hercules_incolor
```

### Additional information

I think there is something wrong handling the latch register from the video card, but haven't debugged the issue in detail. Seems like the latch isn't preserved between calls.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I'm kind of at a loss here... it's drawing the line in MPlot by making a bitmask (0x80 >> (x & 7)) and then ORing it to video memory.

That means it reads from video memory, which triggers the color compare on read, and writes the OR of the color compare result and (0x80 >> (x&7)) to video memory.

Write mode 1 writes for each pixel either the foreground color (if bit set) or latch contents (if bit clear). Foreground color is 3 (cyan).

Once it's written cyan to the leftmost pixel in the byte (0x80), reading back (color comparison) is 0x80, so the next byte sent to the card is 0x80 | (0x80 >> 1). Then 0xC0 | (0x80 >> 2). And so on. Which eventually fills the entire byte with cyan.

So I'm not clear how MPlot, ORing one bit at a time, despite documentation that the 1 bits are to become cyan, is supposed to generate a line consisting entirely of the latch pattern.

**Comment by joncampbell123** [comment]
See also: https://www.seasip.info/VintagePC/incolor.html

**Comment by joncampbell123** [comment]
I suppose it's worth looking into why the other lines don't draw though.

**Comment by joncampbell123** [comment]
Hey wait a minute... a diagram in the PC & PS/2 Video Systems programming book gives me a clue.

Maybe the InColor loads the latch according to the "latch protect" bits, and then compares the _latch_ against the colors, not the raw video memory contents. And the LATCH.LST script sets all the latch protect bits.

![PXL_20240630_215152597 MP sm](https://github.com/joncampbell123/dosbox-x/assets/6245486/12a114ca-8ddd-49bc-9f92-c8264a192ffa)

**Comment by joncampbell123** [comment]
Ha, well, that's _better_ at least.

![learn222_000](https://github.com/joncampbell123/dosbox-x/assets/6245486/bcddfe29-781d-47a9-b696-2a252d585fed)

**Comment by joncampbell123** [comment]
Wait, I get it. I misread the Latch Protect as somehow protecting _bitlanes_, it protects individual bits across all four bitplanes. :facepalm:

**Comment by joncampbell123** [comment]
Retesting the code, it appears to make the same result as the 86Box screenshot, so, this issue is resolved.
![scr1](https://github.com/user-attachments/assets/a86f1a0d-9d9d-4493-982c-9077667339da)
