### ISSUE TITLE
Changing, adding or deleting keyboard shortcuts

### ISSUE THREAD

**Issue by wallstreetobserver** [joncampbell123/dosbox-x#4382]
### Is your feature request related to a problem? Please describe.

I'm using DOSBox-x to run an old dos word processor (leading edge word processor) and a function within the processor uses a keyboard short cut (ctrl+F10) that DOSBox-x uses which removes a lot of functionality from the word processor. The keyboard mapper does not seem to address mapping key combinations. 

### What you want

To be able to edit, add or delete the keyboard shortcuts in DOSBox-x to accommodate programs with shortcuts.

### Describe alternatives you've considered

A useful feature would be to include a simple editor to edit, add, or delete keyboard shortcuts. If such a function is  already within the keyboard mapper an example on to make the change on the wiki page under the key mapper would be helpful. 

### Additional information

Thanks for your consideration. Your work on the project is greatly appreciated!

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
Workaround is to use the Mapper in reverse - if your DOS program requires Ctrl+F10, but doesn't use F11, then you can map F11 physical key = F10 DOSbox signal.

**Comment by wallstreetobserver** [comment]
DOSBox-x already has a mechanism for accomplishing the desired function. Open DOSBox-x and engage the keyboad mapper F11+M. Save without making changes. Go to the DOSBox-x directory, most likely C:\DOSBox-x and edit the newly created file mapper-dosbox-x.map with notepad. Change the desired line entry,which in this case is hand_capmouse "key 291 mod1" to hand_capmouse "key 293 mod1". The DOSBox-x function is now accomplished by using Ctrl+F12 instead of Ctrl+F10. There is a list at the end of the file showing the numerical equivalents of the keys on the  keyboard, making it easy to substitute the correct key. You can easily change any key or key combination used by the DOSBOX-x program or a program within the box to avoid encroachments.  It is easier than using the Mapper especially when editing built-in key combinations for the DOSBox-x program.
