### ISSUE TITLE
DOSBox-X doesn't update directory listing to show files added outside of DOSBox-X

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#4395]
### Describe the bug

I used the 4DOS command interpreter included with DOSBox-X. While running a DOSBox-X session, any file added to a folder from outside DOSBox-X (by, for instance, using Windows Explorer or ZtreeWin to add the file) does not show up in the folder, even if you re-log into that folder under DOSBox-X. Neither the dir command nor any MS-DOS application running under DOSBox-X will see the added file; the only way to get it to show up that I've found is to exit DOSBox-X altogether, then reload DOSBox-X.

### Steps to reproduce the behaviour

1. Open a DOSBox-X session and log into any folder you wish.
2. Outside of DOSBox-X, use Windows Explorer, or any other method you wish, to copy a new file into the same folder you have open under DOSBox-X.
3. Issue "dir" at the  DOSBox-X command prompt.
4. Note that the newly added file isn't listed.
5. At the DOSBox-X command prompt, use the CD or CDD command, or simply enter a different drive letter (one supported by the "MOUNT" directive in your DOSBox-X.conf file) followed by a colon to log onto any other drive or folder.
6. Return to the folder you were in previously.
7. Issue "dir" at the DOSBox-X command prompt.
8. Note that the newly added file _still_ isn't listed.

### Expected behavior

The newly added file _should_ be listed.

### What operating system(s) this bug have occurred on?

Windows 7 32-bit SP1

### What version(s) of DOSBox-X have this bug?

DOSBox-X version 2023.05.01 (32-bit SDL1)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Did you try using the `rescan` command, or the rescan option under the DOS menu item?

**Comment by RobertJSawyer** [comment]
Thanks, Robert! I'd never noticed that option (I run DOSBox-X with the menu bar hidden). Manually selecting **DOS** | **Rescan all drives** does indeed provide a workaround. Thank you!

**Comment by maron2000** [comment]
You can consider adding `-nocachedir` option of `MOUNT` command if you need to rescan frequently.

**Comment by RobertJSawyer** [comment]
Thank you, maron2000. I accept that this is not a bug — but might I ask what the rationale is behind this intended behavior? Why, by default, are directories cached? Thank you!

**Comment by rderooy** [comment]
In short, it is something that was inherited from vanilla DOSBox.

But see https://github.com/joncampbell123/dosbox-x/issues/491 and https://github.com/dosbox-staging/dosbox-staging/issues/1265 for some more recent takes on this.

p.s. There is also a key-combo you can press to do the re-scan if you don't want to open the menu bar, or cannot type `rescan`.

**Comment by maron2000** [comment]
My understanding is that it is due to performance issues where you have to first of all convert your host directory to what DOS can understand.
After that, you have to do that all over again if the directory is changed externally.
This would be time consuming if you mount a folder with a large number of files, so rescanning frequently may lead to poor performance, such as mentioned in issue #3572.
Anyway, DOSBox-X has the option, and you can even set all drives not to cache by an option in the .conf file.
