### ISSUE TITLE
`keyb us` after `keyb no` leads to wrong codepage

### ISSUE THREAD

**Issue by mobluse** [joncampbell123/dosbox-x#4398]
### Describe the bug

If I give the command `keyb no` and then `keyb us` it is still code page 858 and not 437 as it says. It's OK if it stays on the same code page but now the information is misleading. Once you are in CP858 it's sometimes difficult to switch back even with `keyb us 437`.

### Steps to reproduce the behaviour

1. Start DOSBox-X
2. Give the command: `keyb no`
3. Give the command: `keyb us`
4. Test using numeric keyboard with Num Lock: Alt+181 and Alt+224
5. This types characters from CP858 (ÁÓ) and not CP437 (╡ `&boxvL;` and α `&alpha;`)

### Expected behavior

It should have the codepage that is printed by the command. After `keyb us` it prints "Keyboard layout us loaded for codepage 437".

### What operating system(s) this bug have occurred on?

Debian GNU/Linux 11 (bullseye) aarch64

### What version(s) of DOSBox-X have this bug?

2023.03.31 (64-bit SDL1) from Pi-Apps

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Your said bug is already fixed by PR#4318.
You may want to build the latest code or wait for the next release.

![command_000](https://github.com/joncampbell123/dosbox-x/assets/68574602/44b8d4a9-8d06-460e-88ef-66e696a785b9)
![command_001](https://github.com/joncampbell123/dosbox-x/assets/68574602/b5d7a34f-dfb2-4b42-99fd-c43f038aa33c)

**Comment by maron2000** [comment]
This issue can be closed since the PR is now included in the current release.
