### ISSUE TITLE
Can't use English with Japanese Locale

### ISSUE THREAD

**Issue by Jazz392** [joncampbell123/dosbox-x#4402]
### Question

I am using Japanese locale in Windows 10, but I want DOSBox-X's language and font to remain in English. However, there doesn't seem to be any way to do this, even if I set language to en_US. Only after deleting the Japanese language file could I get it to display in English, but it still tries to force a Japanese font to be used. Is there a way around this?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Where are you setting the language? Starting dosbox-x with `dosbox-x -lang ja_JP` seems to do the trick on Linux.

**Comment by Jazz392** [comment]
I'm setting it in the config file. Also wouldn't that display it in Japanese? I want it to display in English. It starts in English and then immediately changes to Japanese.

**Comment by rderooy** [comment]
Ahh yes, other way around. `dosbox-x -lang en_US`

**Comment by Jazz392** [comment]
Unfortunately it still switches to Japanese even with that command line option. Also I want to clarify that when I say locale I'm referring to the language for non-Unicode programs.

**Comment by rderooy** [comment]
Perhaps I don't understand your problem properly. DOSBox-X itself is a Unicode program, and most of the DOSBox-X provided DOS commands are actually also (they are not true DOS programs, but actually part of DOSBox-X).

The language option, only effects which language file DOSBox-X will use. 

Your own DOS programs that you can run **inside** DOSBox-X will not be Unicode, but will use the regular DOS codepage. You can set a DOS codepage with for instance `keyb us 437` to set a US keyboard layout with the standard US codepage (437).

**Comment by Jazz392** [comment]
Windows has an setting to set a language for non-Unicode programs. This is the setting that DOSBox-X is using to determine the language to display the interface in. DOSBox-X may be a Unicode program but that's the only setting that I have on Japanese. It seems to me that DOSBox-X is ignoring the setting in my dosbox-x.conf file.

**Comment by maron2000** [comment]
You can also try `chcp 437` which changes the codepage while the keyboard layout remains.
Simillar to `chev us` for real DOS/V.
