### ISSUE TITLE
How I can suppress LOG output

### ISSUE THREAD

**Issue by jmalak** [joncampbell123/dosbox-x#4405]
### Question

How I can suppress "LOG: Logging output has been disabled." message?
I am using -silent and -nolog option, but this message is output.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I don't know why but you cannot suppress the message since this is intended.
You currently need to tweak the following code yourself.
https://github.com/search?q=repo%3Ajoncampbell123%2Fdosbox-x%20%22Logging%20output%20has%20been%20disabled%22&type=code

**Comment by jmalak** [comment]
It is very confusing because this message is always included into output and combine with application output.
What is purpose -nolog option if it doesn't suppress all messages, what value has "LOG: Logging output has been disabled." message with -nolog?

**Comment by joncampbell123** [comment]
You're right. I am removing that message now.
