### ISSUE TITLE
Wiki - video cards after ATI not visible

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4407]
### Describe the bug

At [Guide: Selecting a video adapter in DOSBox-X](http://dosbox-x.com/wiki/Guide%3AVideo-card-support-in-DOSBox%E2%80%90X) nothing is visible after the ATI table:
![image](https://github.com/joncampbell123/dosbox-x/assets/97228894/c8f9d7c6-e2e3-4cbb-ae77-c34572058e5e)

### Steps to reproduce the behaviour

open wiki link and scroll to the bottom

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

website wiki as of today

### Additional information

@rderooy 

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Thanks. Issue is fixed on the draft wiki pages. github.com:rderooy/dosbox-x-wiki.git

@joncampbell123 will need to pull the update.

**Comment by Torinde** [comment]
That change (along with the other one for ATTRIB) still do not appear despite the release of 2023.09.01. So, Wiki update doesn't happen automatically at release time?

**Comment by Dobby233Liu** [comment]
No

**Comment by rderooy** [comment]
It is a manual step. I asked @joncampbell123 to pull the changes, which he did and you can view them at https://github.com/joncampbell123/dosbox-x/wiki

But there is another step to re-generate from that the wiki pages at https://dosbox-x.com/wiki/ which has not yet been done.
