### ISSUE TITLE
Readonly imgmount

### ISSUE THREAD

**Issue by emxd** [joncampbell123/dosbox-x#4410]
### Question

Hello,

Is the readonly switch from https://github.com/joncampbell123/dosbox-x/issues/427 still supported? I'm trying to use it on a FAT16 disk that contains Win98SE, but on windows boot dosbox complains about the drive being read only. Or does it not work on IDE drives?

 
![dosbox-x_iTFPtAesMM](https://github.com/joncampbell123/dosbox-x/assets/6156912/54f404be-25f2-4a73-b155-f9d23472e883)

Edit: That said, you could argue that it *works* by preventing writes, but my understanding was that this would something akin to the readonly blockdevice mount in qemu, where writes are done on a different file and upon VMexit they're discarded. If I can set the drive to readonly but can't use it... that's not very useful. Obviously I'm missing something.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
No, `-ro` it is not what you expect, but literally a write-protected drive.
`MOUNT` command has `-overlay` option, which seems to match your requirement, but I don't know there is such solution for mounted images.

**Comment by emxd** [comment]
Well, what's the difference between setting the readonly flag on the drive in Windows and settting -ro in dosbox config? I'll try the overlay option when I get back to the PC, thanks.

**Comment by emxd** [comment]
Unfortunately, the overlay switch doesn't work with imgmount. Closed.
