### ISSUE TITLE
Lionking jump button does not work

### ISSUE THREAD

**Issue by petran79** [joncampbell123/dosbox-x#4411]
### Describe the bug

I used the latest nightly build. All other Buttons and directions work, however jump command is disabled. Even when I map it to a different keyboard button at the game menu, there is no difference 

### Steps to reproduce the behaviour

you can start the game and press space key to jump. Or you can change the buttons in game menu

### Expected behavior

Character csn run in all directions, Duck and look up, yet can not jump

### What operating system(s) this bug have occurred on?

Windows 10 latest

### What version(s) of DOSBox-X have this bug?

latest nightly 

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I don't see any flaws.
Downloaded Visual Studio x64 build from here. https://dosbox-x.com/devel-build.html

https://github.com/joncampbell123/dosbox-x/assets/68574602/598058a0-ce88-41a7-b2a4-3e083a1d3ef1

**Comment by petran79** [comment]
Yes, my mistake, it seems version I was using was not as recent, dated 17th of July.

**Comment by petran79** [comment]
It seems the culprite was the gamepad that would mess with inputs even after calibration. Had to disable joystick emulation
