### ISSUE TITLE
What does Z:\textutil\clr.com do?

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#4415]
### Question

The other programs in Z:\textutil are documented here:

[https://dosbox-x.com/wiki/DOSBox%E2%80%90X%E2%80%99s-Supported-Commands](https://dosbox-x.com/wiki/DOSBox%E2%80%90X%E2%80%99s-Supported-Commands
)

But there's no reference I can find anywhere to what clr.com (CLR.COM) is supposed to do. Issuing it on my system just seems to clear the screen, and the name sort of suggests that might be its function -- but there's already a cls command for that purpose built in.

Thank you!

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by JoeC4281** [comment]
CLR.COM is a program to use in place of the CLS command.

DOSBox's CLS sets mode 3,
so you loose the current mode and any loaded font;
but this program uses the scroll window function to clear the screen,
as real DOS does,
and the current mode and font are preserved.

Ref: https://www.vogons.org/viewtopic.php?p=167991#p167991

Joe

**Comment by RobertJSawyer** [comment]
Thank you, Joe!
