### ISSUE TITLE
WordPerfect 6.2 freezes every 2-3 seconds when writing/moving the mouse

### ISSUE THREAD

**Issue by iblowmymind** [joncampbell123/dosbox-x#4419]
### Describe the bug

Using DOSBox-x, WordPerfect will stutter every 2-3 seconds for about 2 seconds when writing something or moving the mouse. This issue does not occur when any menus are open and only when a typing window is focused. Setting CPU speed to max does nothing to help (it is set to max in my case), and I don't get this issue using DOSBox Staging with the same drive and (similar) settings. I use the SDL2 build, but DOSBox Staging does too.

![dosbox-x_x3RbB1buZz](https://github.com/joncampbell123/dosbox-x/assets/28228415/082d8b0d-2b1c-4121-a7d0-17b703125344)

### Steps to reproduce the behaviour

1. Install WordPerfect 6.2 from CD (with all options)
2. Launch it
3. Try to write something
4. See the lag

### Expected behavior

No stutters while typing

### What operating system(s) this bug have occurred on?

Windows 10 22H2 (19045.3324)

### What version(s) of DOSBox-X have this bug?

2023.05.01 (64-bit SDL2)

### Used configuration

```ini
Check additional information, the message is too long
```

### Output log

```text
LOG: Early LOG Init complete
LOG: DOSBox-X's working directory: D:\Applications\WPDOS62
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 2023.05.01 (Windows SDL2)
LOG: Windows keyboard layout ID is 0x0409
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: SDL2 reports desktop display mode 1920 x 1080
LOG: SDL: TTF activated
LOG: Configured windowposition:
LOG: SDL: Current window pixel format: SDL_PIXELFORMAT_RGB888
LOG: SDL: You are running in 24 bpp mode, this will slow down things!
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: ISA BCLK: 8333333.333Hz (25000000/3)
LOG: monopal: green,
LOG: Active save slot: 1 [Empty]
LOG: USING AVI+ZMBV
LOG: Max 3670016 sz 16384
LOG: Final 16384
LOG: MIDI:Opened device:win32
LOG: Pentium CMPXCHG8B emulation is enabled
LOG:
LOG: Printer Device List
LOG: -------------------------------------------------------------
LOG: 01 OneNote (Desktop)
LOG: 02 Microsoft XPS Document Writer
LOG: 03 Microsoft Print to PDF
LOG: 04 HP LaserJet M130a
LOG: 05 Fax
LOG: 06 Adobe PDF
LOG:
LOG: VOODOO LFB now at d0000000
LOG: Serial1: BASE 3f8h
LOG: Serial2: BASE 2f8h
LOG: Parallel1: BASE 378h
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
LOG: Memory I/O complexity optimization enabled aka option 'memory io optimization 1'. If the game or demo is unable to draw to the screen properly, set the option to false.
LOG: The 'scanline render on demand' option is available and may provide a modest boost in video render performance if set to true.
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Allocated APM BIOS pm entry point at f000:ce40
LOG: Writing code to fce40
LOG: Writing code to fce60
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Windows: IID_ITaskbarList3 is available
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: SDL: TTF activated
LOG: SDL: TTF activated
LOG: SDL: TTF activated
LOG: WARNING: No translation support (to host) for code page 0
LOG: Loaded system codepage: 437
LOG: Loaded system codepage: 857
LOG: Unmapped character: 213 -    0
LOG: Unmapped character: 231 -    0
LOG: Unmapped character: 242 -    0
LOG: DOS keyboard layout loaded with main language code TR for layout tr
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG:   11331423 ERROR BIOS:INT1A:Undefined call 5C
LOG:   11331616 ERROR BIOS:INT1A:Undefined call 35
LOG:   11345247 ERROR BIOS:INT1A:Undefined call 5B
LOG:   11492152 ERROR BIOS:INT1A:Undefined call 35
LOG:   11503894 ERROR BIOS:INT15:Unknown call ax=64AA
LOG:   11508152 ERROR BIOS:INT15:Unknown call ax=64AA
LOG:   31453653 ERROR BIOS:INT15:Unknown call ax=64AA
LOG: SDL: TTF activated
LOG: SDL: TTF activated
LOG: SDL: TTF activated
LOG:   36327916 ERROR BIOS:INT15:Unknown call ax=FF00
LOG:   36442133 ERROR BIOS:INT1A:Undefined call 36
```

### Additional information

dosbox-x.conf: https://hastebin.com/share/yagojexodo.makefile

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by emendelson** [comment]
Try this custom setup: 

http://www.columbia.edu/~em36/wpdos/dosboxwp.html

If your browser gives you a 404 error, that's because it changed http:// to https://  Remove the "s" and try again.

**Comment by iblowmymind** [comment]
I know about that custom setup, but I feel more comfortable doing everything myself instead of using an external setup.

**Comment by emendelson** [comment]
You'll have to experiment with the settings in the [cpu] section of the configuration file. The custom setup already has settings that you can start with if you want. If you find any better settings, please let us know.

**Comment by joncampbell123** [comment]
There is a DOS option that is on by default to emulate a HLT instruction when the idle interrupt is called, instead of just returning immediately. Turn off the idle option and try again.

**Comment by iblowmymind** [comment]
After setting "dos idle api = false", nothing has changed.

**Comment by scrutinizer80** [comment]
This does not happen in 2023.03.31.
Using a newer build that @Allofich gave me in order to test a different issue works fine too.

**Comment by iblowmymind** [comment]
Were you able to repro the issue using 2023.05.01?

**Comment by iblowmymind** [comment]
Yep, I can confirm that the regression does not occur when using 2023.03.31, MingW x64 Windows. There is no noticable lag.

**Comment by scrutinizer80** [comment]
> Were you able to repro the issue using 2023.05.01?

Yes of course.
2023.05.01 is completely unusable for me for many other reasons, as some of which described in #4233 .
Frankly, I think it should've been pulled.

The build @Allofich has provided me with fixed all those as I mentioned, incl. the WordPerfect issue.
I just use that one while I wait for an official release with the fixed code.

**Comment by iblowmymind** [comment]
I also have issues with AutoCAD r12 on 2023.05.01, I realised. (it would fail to start 80% of the time) I reverted back to the previous version for the time being.

**Comment by scrutinizer80** [comment]
> I also have issues with AutoCAD r12 on 2023.05.01, I realised. (it would fail to start 80% of the time) I reverted back to the previous version for the time being.

As I mentioned in the other open issue, I have Norton Commander crashing instantly on 2023.05.01. 
This build is unusable, but the problem seems to have been fixed in recent code.

**Comment by joncampbell123** [comment]
WordPerfect 6.2 using the latest code seems to work fine, both keyboard and mouse.

**Comment by scrutinizer80** [comment]
> WordPerfect 6.2 using the latest code seems to work fine, both keyboard and mouse.

Yes it works fine using the latest code, but not on the latest official release.
Even Norton Commander crashes immediately on that one.
As of right now, downloading the official release from the DosBox-X page gets you a version that doesn't represent the project well. We really need an official release using the latest working code. :-)

**Comment by Dobby233Liu** [comment]
> We really need an official release using the latest working code. :-)

I'd say the [devel builds](https://dosbox-x.com/devel-build.html) are semi-official

**Comment by scrutinizer80** [comment]
> > We really need an official release using the latest working code. :-)
> 
> I'd say the [~nightlies~ devel builds](https://dosbox-x.com/devel-build.html) are somewhat official

For us on GitHub, maybe. It's a whole different thing when someone simply goes to https://dosbox-x.com & downloads DosBox-X.

**Comment by scrutinizer80** [comment]
@iblowmymind 
Version 2023.09.01 is out now and no longer has this issue. I think it can be closed now.
