### ISSUE TITLE
ATTRIB - Wiki description on where it works and where it does not

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4425]
### Question

Per [DOSBox‐X’s Supported Commands](http://dosbox-x.com/wiki/DOSBox%E2%80%90X%E2%80%99s-Supported-Commands):
> Changing file attributes only works on mounted local, overlay and FAT drives.

I tested it on SMB shared folder mounted with MOUNT - and changing the attributes works there as well.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment]
@rderooy, what do you think?

**Comment by rderooy** [comment]
I did not author that, but feel free to make a PR against my wiki branch. Once the new release it out, I will pester @johnnovak to pull the changes ;-)

**Comment by Torinde** [comment]
Topic here is -X wiki, not Staging.

Also, I'm unsure how to word the changes. Currently it's written it works ONLY on 3 places. I found a 4th. Which are the other possibilities? Let's list all and test where it works?

**Comment by rderooy** [comment]
> Topic here is -X wiki, not Staging.

I'm not sure what you mean. My fork of the DOSBox-X wiki can be found here: https://github.com/rderooy/dosbox-x-wiki

> Also, I'm unsure how to word the changes. Currently it's written it works ONLY on 3 places. I found a 4th. Which are the other possibilities? Let's list all and test where it works?

I did not do any testing, and will not be doing any testing for the next week or so in any case, as I am traveling. Also, to my understanding, directly mounting an smb share is a Windows host exclusive, and I don't run Windows.

**Comment by Torinde** [comment]
> I will pester @johnnovak to pull the changes ;-)

> I'm not sure what you mean.

I meant that John Novak is doing Staging and here we speak about -X

> directly mounting an smb share is a Windows host exclusive

That surprises me, but OK. I tested on Windows with SMB share mounted as drive letter in DOSbox-X and ATTRIB works there.

Submitted rderooy/dosbox-x-wiki/pull/2, but a further improvement in my opinion will be to list/test the other cases where it doesn't work.

**Comment by rderooy** [comment]
Ahh yes, sorry. Was indeed mixing things up. PR accepted.
