### ISSUE TITLE
"cannot create drive from file" while it works in the original DOSBox

### ISSUE THREAD

**Issue by lwcorp** [joncampbell123/dosbox-x#4434]
### Describe the bug

DOSBox-X fails to run `IMGMOUNT a` over a certain IMG file, while it does work in the original DOSBox.

### Steps to reproduce the behaviour

1. [Download Kryoflux](https://www.kryoflux.com/?page=download) for Windows and extract
1. Enter https://archive.org/details/WWFEuropeanRampageTourOcean199235Kryoflux.7z
1. Download the **Kryoflux Dump** there
1. Use Windows CMD to enter `kryoflux_3.00_windows\dtc\DTC_x64\`
1. Use [KryoFlux COMMAND LINE EXAMPLES](https://github.com/archivistsguidetokryoflux/archivists-guide-to-kryoflux/blob/master/1%20PART%20ONE%20Getting%20Started/1.2%20USING%20THE%20KRYOFLUX/readme.md#command-line-examples) of **Create formatted image files in deviceless mode (i.e., using stream files)** to create a standard IMG file, e.g. 
`dtc -f"WWF European Rampage Tour (Disk 1)(Ocean)(1992)(3,5'')\track00.0.raw" -i0 -fdisk1.img -i4 -m1`
`dtc -f"WWF European Rampage Tour (Disk 2)(Ocean)(1992)(3,5'')\track00.0.raw" -i0 -fdisk2.img -i4 -m1`
 1. Note the second command produces errors:
`00.0    : Bad sector found`
`00.0    : Read operation failed`
`00.1    : Bad sector found`
`00.1    : Read operation failed`
`01.0    : Bad sector found`
`01.0    : Read operation failed`
`01.1    : Bad sector found`
`01.1    : Read operation failed`
`02.0    : Bad sector found`
`02.0    : Read operation failed`
`02.1    : Bad sector found`
`02.1    : Read operation failed`
`03.0    : Bad sector found`
`03.0    : Read operation failed`
`03.1    : Bad sector found`
`03.1    : Read operation failed`
`04.0    : Bad sector found`
`04.0    : Read operation failed`
`04.1    : Bad sector found`
`04.1    : Read operation failed`
1. Run `imgmount a disk2.img`
1. It works in DOSBox, but in DOSBox-X Drive A isn't mounted with the message `cannot create drive from file`

### Expected behavior

Drive A should be loaded and usable

### What operating system(s) this bug have occurred on?

Windows 10 22H2 64-bit

### What version(s) of DOSBox-X have this bug?

1. 2024.03.01, Windows SDL2, 64-bit
1. 2023.09.01, MingGW SDL2, 64-bit
1. 2023.09.01, Windows SDL1 64-bit
1. 2023.09.01, MingGW SDL1, 64-bit

### Output log

LOG: No geometry

### Additional information

1. There's no such issue with the first folder (i.e. disk1.img)
1. It also fails with `-t floppy` (which isn't required by DOSBox-X but is by DOSBox)
1. There's no such issue in the original DOSBox, it just shows in Drive A a file called `WWF.2`:
![image](https://github.com/joncampbell123/dosbox-x/assets/1773306/7df98ef7-0df0-473f-878e-8965a9b22d7d)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
PR #4434 may fix the problem, however, the floppy image should be justified that it is really dumped correctly.

**Comment by lwcorp** [comment]
It seems you linked the issue to itself, so you may want to edit.
How unfortunate that it missed the last release by 2 weeks. I wish you to try it, but pre-releases like https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.84.3 are quite rare, and I've found no instructions how to try it directly from the source cod.e

**Comment by maron2000** [comment]
The image size of disk2.img converted is 900kB, which I think is incorrect.
It should be 720kB, as same as disk1.img.

**Comment by lwcorp** [comment]
Well, since I can't test it you can try to install the installer from disk1, and swap to disk when requested, then see if the game works after the installation.

**Comment by lwcorp** [comment]
Any idea why does one must log in in order to download?
In any case, it gets stuck in disk1. You can run install.exe but it just beeps when trying to approve the path.
Meanwhile DOSBox has no issue there, and thus reaches the end of the installation (where you can't proceed since DOSBox doesn't support swapping floppy disks).

**Comment by lwcorp** [comment]
> In any case, it gets stuck in disk1. You can run install.exe but it just beeps when trying to approve the path. Meanwhile DOSBox has no issue there, and thus reaches the end of the installation of disk1 (where you can't proceed to disk2 since DOSBox doesn't support swapping floppy disks).

Can you reopen?

**Comment by lwcorp** [comment]
While it wasn't re-opened it just made it to production. Now you can proceed to disk2 only to end up with "FATAL installation error FF44", which opens the debugger at "DOS fatal memory error: Corrupt MCB chain".

All I can say is that it does work if instead of using KryoFlux's official converter one uses DOSBox-TC's `flux2tc --consolidate track00.0.raw diskX.tc`. But this converts to TC files which DOSBox-X doesn't support...

![image](https://github.com/joncampbell123/dosbox-x/assets/1773306/f915bb5f-b757-4c84-b007-937f806f7b98)
![image](https://github.com/joncampbell123/dosbox-x/assets/1773306/a0845f2d-21ca-45a9-8b97-24988c8128d1)

**Comment by lwcorp** [comment]
A new production version was released, and took us back in time.
Now it beeps again, just like [back in dev](https://github.com/joncampbell123/dosbox-x/issues/4434#issuecomment-1997990527) and unlike [in the last official release](https://github.com/joncampbell123/dosbox-x/issues/4434#issuecomment-2211290463). You can still achieve the previous behavior by swapping the disks while it beeps,
Did you undo something?

Meanwhile, I've noticed after it beeps (instead of asking to switch to disk2) it doesn't get fully stuck but lets you click escape. If you do this, you get taken back to DOS where it states `Could not find any fixed disk's...` (I assume it means disks and not disk's), which is weird because how did it manage to run install.exe if not from a fixed disk?

**2025 update:** I assume it was closed because the original issue was indeed solved (not being able to load disk2), so I've moved the rest to a standalone issue.
