### ISSUE TITLE
Mkdir commands causes crash on Mingw build

### ISSUE THREAD

**Issue by Freda-Chan** [joncampbell123/dosbox-x#4435]
### Describe the bug

Using `mkdir `command for example: `mkdir games` causes crash on mingw build.

### Steps to reproduce the behaviour

1: imgmake -t hd -size 1000 hdd.img -fat 16
2: mount C: hdd.img
3: C:
4: mkdir games
And crash!

### Expected behavior

A directory should be created.

### What operating system(s) this bug have occurred on?

Windows 11

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2023.05.01 Mingw Windows

### Used configuration

```ini
Default settings
```

### Additional information

I tried to reproduce same error on vsbuild, but it doesn't give the same result and creates the directory as it should.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
You may want to try the latest release which seems to work fine.
Since the website is yet to be updated, go to the [Release](https://github.com/joncampbell123/dosbox-x/releases) page to grab the one you desire.

**Comment by Freda-Chan** [comment]
I tested latest release, the problem solved on 2023.09.01 release.
