### ISSUE TITLE
DOSBox-X start screen in German with wrong line wrapping

### ISSUE THREAD

**Issue by JoeBroesele** [joncampbell123/dosbox-x#4439]
### Describe the bug

After installing DOSBox-X 2023.09.01 and starting it with the default dosbox-x.conf configuration file, the line wrapping on the start screen appears to be wrong

### Steps to reproduce the behaviour

1. Install DOSBox-X 2023.09.01 using the Windows installers on a Windows 10 PC with a German OS version.
2. Select Visual Studio 64 bit.
3. Select DOS 6.22.
4. Keep all other options as default.
5. Start DOSBox-X.
6. The line wrapping on the start screen is wrong.

### Expected behavior

The line wrapping on the start screen should be correct, to display the text in a clean box made from ASCII character.

### What operating system(s) this bug have occurred on?

Windows 10 Pro 22H2, German

### What version(s) of DOSBox-X have this bug?

SDL Visual Studio 64 bit 2023.09.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by JoeBroesele** [comment]
![DOSBox-X start screen German](https://github.com/joncampbell123/dosbox-x/assets/56547187/9eed8785-7c76-408a-833b-a6c166cf5510)

**Comment by JoeBroesele** [comment]
The problem is caused by the entry `language=de_DE` in the section `[dosbox]` of the file `dosbox-x.conf`. Setting `language=` resolves the problem.

**Comment by maron2000** [comment]
I think this is because the required padding spaces were deleted in the commit by @Link-Mario shown below.
You can download and replace the lang file with the old one for the time being.

![de_lang1](https://github.com/joncampbell123/dosbox-x/assets/68574602/40866230-5869-4a7a-8e0c-dca480e57877)
![de_lang2](https://github.com/joncampbell123/dosbox-x/assets/68574602/3fdeff4e-86e2-4186-b311-6381a49dddae)

**Comment by maron2000** [comment]
No glitches using old lang file. 
It is needless to say that maybe there are translation flaws using the old file, since there are some items fixed since the May release.
![de_lang3](https://github.com/joncampbell123/dosbox-x/assets/68574602/02243b8f-431f-4dc3-8e44-64cc2e7943b2)

**Comment by JoeBroesele** [comment]
Yes, adding the spaces at the end of the lines fixes the problem! It seems that *all* trailing spaces got erased in the new version. This may have some negative effects besides the start screen.
