### ISSUE TITLE
Message confirmation setting (snapshot / avi video)

### ISSUE THREAD

**Issue by github-fanuser** [joncampbell123/dosbox-x#4449]
### Question

I have the 09/01/2023 version.  The first item in the change log:

Disable by default message confirmation after snapshot and AVI video
capture, but leave the option there for those who want to enable it (joncampbell123).

I can't find the setting to enable message confirmation.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
See section [dosbox] setting "show recorded filename".

Default was true, which was changed to false. Set it to true.

**Comment by github-fanuser** [comment]
Thank you! I had to enable advance options  to see the setting.
