### ISSUE TITLE
Tony & Friends in Kellogg's Land DOS game slowness and blue flickering (raster water effect)

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#4467]
### Describe the bug

The game runs fine in DOSBox 0.74-3 if you configure the emulator as recommended by ripsaw8080 in this thread: https://www.vogons.org/viewtopic.php?f=31&p=1193373#p1193373
But with the same configuration in DOSBox-X the game is very slow and the audio stutters.
Moreover, the machine=vgaonly setting does not solve the water related problem as it does in DOSBox (blue flickering).
In this thread I found a comment by sikthehedgehog regarding a particular raster effect used by this game to display water: https://github.com/joncampbell123/dosbox-x/issues/256

DOSBox water effect
![DOSBox water](https://github.com/joncampbell123/dosbox-x/assets/58113425/1f17e4d8-dddc-499c-912f-24fe62e76bba)

DOSBox-X water effect
![DOSBox-X water](https://github.com/joncampbell123/dosbox-x/assets/58113425/c20b6d9c-40cc-4ac0-8f6a-355e24097dbf)

Game
[Tony & Friends in Kellogg's Land.zip](https://github.com/joncampbell123/dosbox-x/files/12605603/Tony.Friends.in.Kellogg.s.Land.zip)

### Steps to reproduce the behaviour

1. Modify dosbox-x.conf (machine=vgaonly ; core=normal ; cycles=10000)
2. Copy the KELLOGG directory in your C drive (preconfigured with SoundBlaster output)
3. Launch the game by typing START.EXE

### Expected behavior

The game should work the same as in DOSBox

### What operating system(s) this bug have occurred on?

Windows 10 Pro 22H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2023.09.01 VSbuild & MinGW 32 bit

### Used configuration

```ini
Standard apart from these changes:
machine = vgaonly (to display the water raster effect correctly)
core    = normal (with the auto setting the sound is pops and cracks only)
cycles  = 10000
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
Changes to PIT src/hardware/timer.cpp made between versions 0.82.14 to 0.82.15 have a major impact on how this game works.
On versions older than dosbox-x 0.82.15, the game works correctly.

[tonyandfriends.dosbox-x.0.82.14.webm](https://github.com/joncampbell123/dosbox-x/assets/452325/cc533c12-63dd-4940-975e-21f24b0d05cf)

**Comment by joncampbell123** [comment]
The game uses PIT mode 2 but it's constantly changing the counter value (tick rate) which is... odd...

**Comment by joncampbell123** [comment]
This game is using some rather interesting elaborate event timing with both PIT 0 (timer interrupt) and PIT 2 (PC speaker counter). It uses PIT 0 for interrupt timing and PIT 2 for precise timing.

The bug was that the game writes the PIT 2 counter value with the gate off, and the code failed to update the counter value read back in that case even if the game later turned on the gate and read it back 1ms later, causing timing issues.

Please try this game with the latest commit and verify it works properly now.

**Comment by grapeli** [comment]
In my opinion, it works correctly, identically to dosbox-staging. In version 0.82.14 there were slight vibrations, but it probably shouldn't look like that (it probably doesn't function as a music visualizer).

**Comment by MX9000** [comment]
@joncampbell123 and @grapeli thank you all!
Now the game runs well and graphics and sound are smooth, particularly at full screen with v-sync set to 60 Hz.
