### ISSUE TITLE
May I ask how to install the voodoo graphics card driver for Windows 98 installed on DOS-Box X?

### ISSUE THREAD

**Issue by wangwet007** [joncampbell123/dosbox-x#4469]
### Question

I installed Windows 98 in DOS Box-X to play the old version of Resident Evil 1 released in 1996, but it always showed driver errors. Although I have found several versions of drivers to install, they are of no use. Can someone tell me where to download the correct driver?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
It is mentioned on the wiki
https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-98#_3dfx_voodoo

**Comment by wangwet007** [comment]
> 维基百科上提到了 https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-98#_3dfx_voodoo
I have also seen this, and the display drivers in the system are all installed, but I don't know why they just reported an error.

**Comment by wangwet007** [comment]
> 很抱歉，您没有提供任何真实的信息来继续。您使用的是 voodoo emulation、opengl、glide pass-through 软件吗？错误是什么？
> 
> 除了Win98安装指南之外，wiki上还有一份3dfx Voodoo指南，推荐大家看一下。

Sorry, I forgot to attach a screenshot, that's it
![1111111](https://github.com/joncampbell123/dosbox-x/assets/145081185/8be54346-c31c-488b-8748-61e5f0c787ee)

**Comment by BridgeHeadland** [comment]
@wangwet007 What is the machine value set to? I don't think 16 colors and 640x480 resolution is perfect for the Voodoo graphics. You should set machine to svga_s3virgevx, it is perfect for DOS, Windows 1-3/3.x and Windows 9x. I'm not sure if the mentioned machine value is perfect for pre-W2K Windows NTs, but for Windows 2000 and XP, svga_s3trio64v+ is the most perfect value - currently.
