### ISSUE TITLE
INT 21/AX=6523h permits only YN characters

### ISSUE THREAD

**Issue by maxpat78** [joncampbell123/dosbox-x#4477]
### Describe the bug

When a DOS program relies on INT 21h to get a yes/no keyboard character from the user, DOSBox-X allows only English [Y]es/[N]o answer.

### Steps to reproduce the behaviour

Use a program with INT21/AX=6523h support

### Expected behavior

Yes/No characters should be language-file dependent.

### What operating system(s) this bug have occurred on?

Any

### What version(s) of DOSBox-X have this bug?

Any

### Used configuration

```ini
-
```

### Output log

```text
-
```

### Additional information

-

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Ref: http://www.ctyme.com/intr/rb-3165.htm
