### ISSUE TITLE
Unlike in real MS-DOS, Borland C‘s „ftell(stdin)“ fails on redirected file

### ISSUE THREAD

**Issue by TeaRex73** [joncampbell123/dosbox-x#4480]
### Describe the bug

I have a Borland C program CAS666.C that contains the following code (minimal example):

```
#include <stdio.h>
#include <stdlib.h>
int main(void)
{
    long filepos;
    filepos = ftell(stdin);
    if (filepos == -1L) {
        perror("ftell failed“);
        exit(EXIT_FAILURE);
    }
    return EXIT_SUCCESS;
}

```
The compiled program is supposed to be called e.g. like this:

`CAS666 < YOOMP.CAS > YOOMP.WAV`

This works in real DOS as well as it does in Win32 or Linux, but errors out in DOSBox-X (compiled with Mingw from current git repository). In DOSBox-X, ftell(stdin) seemingly always returns -1 even with such an Input redirection, which seems to be incorrect.

### Steps to reproduce the behaviour

Compile my bit of code in Borland C 3.1 and run it as described.

### Expected behavior

The function ftell should return a non-negative number.

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

Current GIT as of 2023-09-21

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maxpat78** [comment]
Do you mean Borland C++ 3.1? 
Your code fragment seems to work right. Perhaps output file was locked by some anti-virus...?

**Comment by TeaRex73** [comment]
I couldn't reproduce the bug now. It seems there was really some other kind of problem.

**Comment by TeaRex73** [comment]
Wrong close reason.

**Comment by TeaRex73** [comment]
Wrong close reason
