### ISSUE TITLE
EMM Manager does not map enough pages for swapping

### ISSUE THREAD

**Issue by flaviofornazier** [joncampbell123/dosbox-x#4483]
### Describe the bug

Hi Guys,

Congratulations for your efforts.

I never was able to run that software on any DOS emulators versions.
For years I tried a lot of ways to do it, including EMSMAGIC, but with 
no success.

That software works fine on VMWare or VirtualBOX, using MS-DOS or
FreeDOS, with EMM386 RAM or JEMM386 RAM options.

Any suggestion?

Any reply would be greatly appreciated.

Thank you in advanced.

PS: As I am a licensed user I can send a copy for review.

![Uploading Capture_MEM.PNG…]()
![Capture_DTM](https://github.com/joncampbell123/dosbox-x/assets/50641373/34b25092-5ba1-4ac9-a8b0-43aa1663a2c6)

### Steps to reproduce the behaviour

Please see the attached images.

### Expected behavior

Expanded memory support like a real EMM386 or JEMM386.

### What operating system(s) this bug have occurred on?

Windows 10 21H2

### What version(s) of DOSBox-X have this bug?

Current Version on Windows.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
DOSBox-X, like the main DOSBox project it came from, uses a 64KB region as the EMS page frame. Is 64KB not enough? Does it need a 128KB page frame?

**Comment by flaviofornazier** [comment]
Mr. Campbell,

First of all, thank you very much for the reply.

Well, I'm not a computer enginer, i.e., a guru like you, I'm just a ordinary programmer.
I will check the manuals now and try to find more info.

Cheers.

- Flávio -

PS: Please don't forget me, I trying to run that software on DOS emulators for many, many years! =)

**Comment by flaviofornazier** [comment]
Mr.Campbell,

When and only when you have a free time please take a look at attached PDF that contains the small chapter about memory configuration. I'm trying to use a single-user only version, DTM's network has its own internal methods, i.e., it does not use OS methods like redirect drives, etc.

Thank you very, very much. =)

[63SMCH07.PDF](https://github.com/joncampbell123/dosbox-x/files/12705506/63SMCH07.PDF)

**Comment by maron2000** [comment]
You can try Jemmex.exe as mentioned in issue #3762.
You need to diable built-in XMS and EMS feature.

**Comment by flaviofornazier** [comment]
Mr.Maron,

I'll try it now.

Thank you so much.

Cheers.

**Comment by flaviofornazier** [comment]
Mr.Maron,

First of all, thanks a lot! =)

I disabled built-in XMS and EMS and tried JEMMEX at E000, C000 and D000.
Unfortunately it still does not work.
![capture2](https://github.com/joncampbell123/dosbox-x/assets/50641373/9ba08f17-9d51-4d40-9957-af6de4eefb1f)

Any suggestion?
![capture1](https://github.com/joncampbell123/dosbox-x/assets/50641373/328927e8-0834-42c6-adaf-12b837b51e7b)

**Comment by flaviofornazier** [comment]
Mr.Maron,

It works with FRAME=8000. It's okay?

Now I will start hard tests with the software.

I don't know how to thank you! =)

**Comment by maron2000** [comment]
Sure you can set the frame on conventional memory, but it will occupy 64kB memory.
That's why we want to put it somewhere around C000-EFFF.
I tried myself and still seems that D000 is a valid setting on DOSBox-X, but if it doesn't work for your software, we have no choice.
Maybe better to set it to 9000 to avoid segmentation of your conventional memory.
![jemm](https://github.com/joncampbell123/dosbox-x/assets/68574602/8850caa1-e1f3-4873-9c90-c9ea9a355819)

**Comment by flaviofornazier** [comment]
Mr.Maron,

I'll try set it to 9000 before start database tests.

Thanks a lot!

**Comment by flaviofornazier** [comment]
Mr.Maron,

You were right. It works with D000 too.

Thank you!
