### ISSUE TITLE
SBLASTER:DSP:Unhandled (undocumented) command A6

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#4492]
### Describe the bug

This game, "Chickens" from 1996, when run with DOSBox-X causes loads of these errors on each bomb drop.
https://github.com/dosbox-staging/dosbox-staging/issues/2879

Due to the amount of log messages, it even causes the game to freeze for a moment.

Feel free to close if not of interest.

### Steps to reproduce the behaviour

- Start the game
- Use the mouse to take a bomb from the box, and drop it

### What operating system(s) this bug have occurred on?

Fedora 38

### What version(s) of DOSBox-X have this bug?

git

### Used configuration

```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=32
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=max
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
cd ..
cd ..
mount c .\eXoDOS\Chicken
c:
@cd Chicken
@cls
mreset
@chickens
exit
```

### Output log

Tons of these messages:
```text
LOG:   41687664 ERROR SBLASTER:DSP:Unhandled (undocumented) command A6
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Okay, so here's what I see:

The game starts up and writes DSP command 0xD0 (halt 8-bit DMA) something like 1000 times.
Then writes DSP command 0xD1 (enable speaker) 1000 times.
Then writes DSP command 0x40 (set time constant) 1000 times.
Then writes DSP command 0xA6 (I assume the time constant?) 1000 times.

It would be perfectly valid if it simply wrote "0x40 0xA6" but it apparently likes to write each DSP command something like 1000 times. Why?

**Comment by joncampbell123** [comment]
The loop to write the DSP command is coded such that every time the DSP busy bit is set, it goes back and writes the command again.

It beats the DSP over the head with the same command until the busy bit is clear.

This happens to work on real hardware because the DSP ignores your writes while it _is busy_. I can imagine this screwing with any kind of TSR or Windows driver emulation though almost as badly as the Crystal Dream "nagging the DSP" technique.

**Comment by joncampbell123** [comment]
Here's the routine. I'm not kidding.

    0DC9:00000E87 8B161F3C            mov  dx,[3C1F]              ds:[3C1F]=022C
    0DC9:00000E8B 8A4606              mov  al,[bp+06]             ss:[CF64]=12A6
    0DC9:00000E8E EE                  out  dx,al
    0DC9:00000E8F 8B16213C            mov  dx,[3C21]              ds:[3C21]=022C
    0DC9:00000E93 EC                  in   al,dx
    0DC9:00000E94 2480                and  al,80
    0DC9:00000E96 3C00                cmp  al,00
    0DC9:00000E98 75ED                jne  00000E87 ($-13)        (up)

**Comment by joncampbell123** [comment]
Notice it writes the DSP command first and then checks the busy bit to decide whether to write it again.

Writing the DSP command if it wasn't busy will make it busy, which means it will write it repeatedly until not busy, which might occur when the DSP has just become *not* busy and might mistake the repeated command byte as the next byte.

What was the programmer thinking?

**Comment by joncampbell123** [comment]
You can fix the code to talk to the card *properly* as follows. These steps should work in any fork of DOSBox (including DOSBox-X) with a working debugger interface.

1. Start the game.
2. Immediately break into the debugger.
3. Type: "c cs:e87" and hit enter to bring up the DSP write code.
4. Type: "sm cs:e99 f9" and hit enter to change the instruction at E98 from "JNE E87" to "JNE E93" (meaning to loop until busy bit clear *without* writing the command again).
5. Resume emulation and play the game, observe sound effects work properly.

**Comment by joncampbell123** [comment]
Another option in DOSBox-X is to set the DSP to "instant DAC mode":

    [sblaster]
    instant direct dac=1
    dsp write busy delay=0
