### ISSUE TITLE
setcolor.com has no effect [when output=ttf]

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#4503]
### Describe the bug

Z:\BIN\SETCOLOR 2 #005500   --> #00aa00  not #005500

### Steps to reproduce the behaviour

![image](https://github.com/joncampbell123/dosbox-x/assets/93595854/ec78db74-fc35-4e3d-a561-d9686f278182)

Z:\BIN\SETCONT
Z:\BIN\SETCOLOR 2 #005500

### What operating system(s) this bug have occurred on?

Windows 11 22H2

### What version(s) of DOSBox-X have this bug?

dosbox-x 2023-09-01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maxpat78** [comment]
@Arthur3032 Just tried to `SETCOLOR 0` or `SETCOLOR 1` ... color change is effective, at least in VS2022 x64 Build - only it reports as command output the _previous_ color, not the target (new) color.

**Comment by Arthur3032** [comment]
Please try SETCOLOR 2, SETCOLOR 3

**Comment by maxpat78** [comment]
I've just tried `setcolor 2 #FF0000` with the latest commit (built by me), also: it works as expected, and it changes in real time the color of the "HAVE FUN WITH DOSBox-X !" string displayed by the shell.

Perhaps only a particular build/SDL combo is affected?

**Comment by maxpat78** [comment]
Update:
I've looked at your screenshot... you're right: SETCOLOR does not work, but _only when_ Video/Output menu is set to "True Type font". Direct3D (default for me), OpenGL, etc. work right.

**Comment by maxpat78** [comment]
Note while debugging: setVGADAC in output_ttf.cpp seems getting the right altBGR1 matrix to IO_WriteB, but such change has no effect on display.

**Comment by Arthur3032** [comment]
However, it worked normally before
This will only be the case after v2023-

**Comment by maxpat78** [comment]
Patch works as expected!

**Comment by maron2000** [comment]
@maxpat78 Thank you for testing. I'll prepare a PR.

**Comment by Arthur3032** [comment]
It's OK, Thank you.
