### ISSUE TITLE
Black background blinks in Ultima VI: The False Prophet (2023-10-06 regression)

### ISSUE THREAD

**Issue by TeaRex73** [joncampbell123/dosbox-x#4507]
### Describe the bug

In a freshly installed, unconfigured DOSBOX-X release 2023-10-06 (but not in 2023-09-01), when running an unmodified Ultima VI: The False Prophet - copied to hard disk from the Ultima Collection CD  - when entering the game proper after "Journey Onward" is selected from the Main Menu and after the game is loaded (note: NOT in the intro), everything on the screen that is supposed to be black instead blinks between black and grey. This makes the game very ugly.

The bug does not seem to depend on output= or machine= settings, as long as the machine selected is VGAONLY or SVGA_S3; I didn't try the other SVGA variants yet. It does NOT happen with machine type set to MCGA.

### Steps to reproduce the behaviour

1. Install DOSBox-X release 2023-10-06 on Windows 10. Select all the standard options, except select Direct3D output instead of TTF (probably doesn't matter though).
2. From Windows, Create a directory C:\DOS.
3. Copy the directory ULTIMA6 from the root of The EA/Origin 1998 Ultima Collection CD [https://archive.org/details/Ultima_Collection_1998_Electronic_Arts_-_Origin_compilation](url)    to C:\DOS\ULTIMA6
4. Run DOSBox-X.
5.  MOUNT C C:\DOS
6. C:
7. CD \ULTIMA6
8. LOADFIX -A ULTIMA6.EXE
9. Cancel the introduction with the ESC key
10. Click on "Create a Character" in the main menu and go through the character creation sequence. It's not important whether you select A or B on any of the questions.
11. When the second part of the intro appears (purple background, altar), press ESC again
12. Wait for the game to load completely
13. Watch the black elements on the screen. They blink between black and grey.

### Expected behavior

The black areas should be black only.

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

2023-10-06 Visual Studio SDL1 64-bit official release build. But other 2023-10-06 too, at least MinGW 64 and 32 locally compiled from source.

### Used configuration

```ini
The configuration was unchanged from the default.
```

### Output log

```text
No log was produced.
```

### Additional information

I built the MinGW 32 and 64 bit versions locally on this machine from unmodified GIT with the ./build-mingw command in MSYS2 and the result was the same. If you need a video capture, there is one in the comment below.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by TeaRex73** [comment]
Video capture (Zipped):

[ultima6_000.zip](https://github.com/joncampbell123/dosbox-x/files/12838180/ultima6_000.zip)

**Comment by TeaRex73** [comment]
Bisection shows that Commit [https://github.com/joncampbell123/dosbox-x/commit/47845297ca2cb2deb9523a9730d7b191652890db](url) (the setcolor TTF fix) is the culprit. The master tree branch right before that works fine, this commit introduces the erroneous behaviour.

**Comment by TeaRex73** [comment]
Further investigation shows that the culprit is line 245 of src/ints/int10_pal.cpp which was introduced by that commit:

`    setVGAColor(value, imap[index]);`

Commenting out that line makes the problem go away. Unfortunately I don't understand the code well enough to tell what exactly that line is supposed to do.

**Comment by TeaRex73** [comment]
Issue #4510 is caused by the same line of code.

**Comment by joncampbell123** [comment]
> Further investigation shows that the culprit is line 245 of src/ints/int10_pal.cpp which was introduced by commit [4784529](https://github.com/joncampbell123/dosbox-x/commit/47845297ca2cb2deb9523a9730d7b191652890db):
> 
> ` setVGAColor(value, imap[index]);`
> 
> Commenting out that line makes the problem go away. Unfortunately I don't understand the code well enough to tell what exactly that line is supposed to do.

It was supposed to fix output=ttf, looks like it fixes more than that. I'll try something in master.

**Comment by maron2000** [comment]
Sorry for the flaws, the line can be deleted for the time being.
It was required so that if you change the color in TTF mode, the change will be applied to non-TTF mode as well.

**Comment by TeaRex73** [comment]
Thanks for all your work and your gracious help with this. Works now with current GIT, feel free to close.

**Comment by TeaRex73** [comment]
Closed.

**Comment by turol** [comment]
This bug also affected Master of Magic. It made most of the screen to slowly flash red.
