### ISSUE TITLE
Anybody using dBase Classic on DOSBOX-X latest version?

### ISSUE THREAD

**Issue by IowaAlex** [joncampbell123/dosbox-x#4509]
### Question

I am planning to buy dBase Classic from https://dbaseclassic.com/.
They have their own version of DOS emulator - https://dbdos.com/ based on DOSBOX.
They say they haven't tested dBase Classic on DOSBOX-X. 
Does anybody have experience with dBase Classic on DOSBOX-X?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
I am not aware of anyone testing dBase.

**Comment by IowaAlex** [comment]
Thanks
Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm 

    On Sunday, October 8, 2023 at 07:35:46 AM CDT, Robert ***@***.***> wrote:  
 
 


I am not aware of anyone testing dBase.

**Comment by IowaAlex** [comment]
That’s nice to know. dBASE 5.0 for DOS was the fastest version of the dBASE/DOS versions. Is there a question here? Or are you sharing this information because you’re happy with the results?

Ken

From: Alex Campbell ***@***.***>
Sent: Thursday, October 12, 2023 6:54 AM
To: Paul McGee ***@***.***>; dBase Sales ***@***.***>; dBase Tech Support ***@***.***>; joncampbell123/dosbox-x ***@***.***>
Subject: Running dBase V in DOSBOX-X. Looks good in first try. Very fast!

[Inline image]

Alex Campbell
====================================================
Always read what you have written to see if you've any words out.
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm

**Comment by IowaAlex** [comment]
Happy with results. 


Sent from Yahoo Mail for iPhone


On Thursday, October 12, 2023, 11:04 AM, Ken Mayer ***@***.***> wrote:


That’s nice to know. dBASE 5.0 for DOS was the fastest version of the dBASE/DOS versions. Is there a question here? Or are you sharing this information because you’re happy with the results?
 
  
 
Ken
 
  
 
From: Alex Campbell ***@***.***> 
Sent: Thursday, October 12, 2023 6:54 AM
To: Paul McGee ***@***.***>; dBase Sales ***@***.***>; dBase Tech Support ***@***.***>; joncampbell123/dosbox-x ***@***.***>
Subject: Running dBase V in DOSBOX-X. Looks good in first try. Very fast!
 
  
 

 
  
 
Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm

**Comment by IowaAlex** [comment]
Thanks – just making sure. 😉

Ken

From: Alex Campbell ***@***.***>
Sent: Thursday, October 12, 2023 9:05 AM
To: Ken Mayer ***@***.***>; Paul McGee ***@***.***>; dBase Sales ***@***.***>; dBase Tech Support ***@***.***>; joncampbell123/dosbox-x ***@***.***>
Subject: Re: Running dBase V in DOSBOX-X. Looks good in first try. Very fast!

Happy with results.

Sent from Yahoo Mail for iPhone<https://mail.onelink.me/107872968?pid=nativeplacement&c=Global_Acquisition_YMktg_315_Internal_EmailSignature&af_sub1=Acquisition&af_sub2=Global_YMktg&af_sub3=&af_sub4=100000604&af_sub5=EmailSignature__Static_>


On Thursday, October 12, 2023, 11:04 AM, Ken Mayer ***@***.******@***.***>> wrote:

That’s nice to know. dBASE 5.0 for DOS was the fastest version of the dBASE/DOS versions. Is there a question here? Or are you sharing this information because you’re happy with the results?



Ken



From: Alex Campbell ***@***.******@***.***>>
Sent: Thursday, October 12, 2023 6:54 AM
To: Paul McGee ***@***.******@***.***>>; dBase Sales ***@***.******@***.***>>; dBase Tech Support ***@***.******@***.***>>; joncampbell123/dosbox-x ***@***.******@***.***>>
Subject: Running dBase V in DOSBOX-X. Looks good in first try. Very fast!



[Inline image]



Alex Campbell
====================================================
Always read what you have written to see if you've any words out.
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm

**Comment by IowaAlex** [comment]
Being using it for several months for light use with no problems.
