### ISSUE TITLE
Chess Master 3000 1.02 for MS-DOS has graphics artifacts

### ISSUE THREAD

**Issue by gfernval** [joncampbell123/dosbox-x#4510]
### Describe the bug

Running Chess Master 3000 1.02a for MS-DOS (available in https://dosgamezone.com/game/chessmaster-3000-the-7319.html) in MS-DOS 5.0 has graphics artifacts in the opening screen (blue bands instead simulated yellow bright bands), this not happens in the DOSBox-X 2023.09.01 release. It is not due tho the new SDL2 version, also happens in SDL1 dosbox-x versions. In Ubuntu Linux 20.04 exits dosbox-x abruptlely with a "stack smashing" error, but in Ubuntu Linux CGA version works fine. The versions that fail in Ubuntu Linux are VGA and EGA versions.
I have used the same version of dosbox-x.conf in both dosbox-x versions (2023.10.06 and 2023.09.01), dosbox-x.conf hasn´t changed in both versions (no new or modified parameters)

### Steps to reproduce the behaviour

Install and run Chess Master 3000 1.02a

### Expected behavior

There should not be graphics artifacts in the startup screen an Linux version should not exit

### What operating system(s) this bug have occurred on?

Windows 7

### What version(s) of DOSBox-X have this bug?

all versions

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by TeaRex73** [comment]
The culprit is exactly the same as in #4507 , i.e. line 245 of src/ints/int10_pal.cpp,

`    setVGAColor(value, imap[index]);`

Commenting it out makes this problem disappear too,
