### ISSUE TITLE
DosBox-X 2023.10.06 crashes running Civ I

### ISSUE THREAD

**Issue by fire-eggs** [joncampbell123/dosbox-x#4511]
### Describe the bug

DosBox-X updated to 2023.10.06 on my system. Start screen says "v2023.10.06, Linux SDL2, 64-bit".

Running Sid Meier's Civilization (version 1). When the player is informed they've learned a new technology, and prompted to "press any key to continue", DosBox-X dies [the window vanishes] after the keypress.

Been running Civ 1 on this system with earlier DosBox-X without issue.

### Steps to reproduce the behaviour

1. Invoke DosBox-X.
2. mount c ~/folder
3. C:
4. civ
5. 1, 1, 1 (vga, nosound, mouse+keyboard)
6. Load the attached game
7. End the turn

[civ.zip](https://github.com/joncampbell123/dosbox-x/files/12841356/civ.zip)

### Expected behavior

After ending the turn, the user is informed they have learned "Alphabet". The user is prompted to "press any key to continue".

Pressing any key, or clicking with the mouse, should continue the game. Instead, DosBox-X crashes and the DosBox-X app vanishes.

### What operating system(s) this bug have occurred on?

Kubuntu 22.04 / KDE Plasma 5.24.7 / X11

### What version(s) of DOSBox-X have this bug?

2023.10.06 SDL2 64-Bit

### Additional information

Couldn't find any log / config / whatever files.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Windows VS x64 SDL2 version works fine.
Tried the 2023.10.06 release and the latest commit cdcfb554999572e758b81edf85a007d398626b78.

![civ](https://github.com/joncampbell123/dosbox-x/assets/68574602/0fbe3011-721a-4410-9d26-3031efcb65a7)
![civ2](https://github.com/joncampbell123/dosbox-x/assets/68574602/245d391c-3c65-4f69-91e4-eb15ca7b102d)

**Comment by fire-eggs** [comment]
Thank you!
