### ISSUE TITLE
Wizardry VII black pixels get fully transparent: sky shows through

### ISSUE THREAD

**Issue by FFnewbie** [joncampbell123/dosbox-x#4534]
### Describe the bug

This version has regressed, unfortunately. 
https://ibb.co/rHrmKnF

What works:
**Dosbox-staging version 0.80.1 
https://ibb.co/59HsCFX
and 
vanilla Dosbox 0.74 work as expected.** 
https://ibb.co/4FGnw5R
Black pixels in above two remain as they should.  Both I tried without their conf files.

I had to go back to an older version of Dosbox-x - 2023.09.01. SDL2 -, so that works regards black pixels..  But that version  completely corrupts the game with its save states causing trash pixels filling the inventory screen and the inventory items disappear... :(  Then the treasure chest right before me either disappears on Save State reload or when I open it, the game doesn't give me the loot menu = instead it shows nothing, I don't get the items. Probably caused data corruption.. :(

Dunno. :(  Are there some CONF settings that are super-safe and don't cause this inventory corruption upon save-state reload?  :(        I have burned a lot of time to research and configure this system. :(

I'm using the same regular game save files, saved ingame the normal way for all of these. 

Dosbox_DAUM_20150125's  dosbox.exe can reload the same savegame and it's save state reload feature does not corrupt Wiz 7 data: the inventory screen remains pristine and the chest works normally as expected.  :(  Interestingly DAUM's dosbox_x64.exe crashes to desktop upon trying to reload a Save-State, only the 32-bit EXE works, which is okay.

I'll have to try even older Dosbox-x versions.  Or just go back to Staging and play without save-states. 

Dosbox Pure Libretro I'll have to doublecheck now, if it has a SBLASTER-SPEAKER option, because Dosbox-x plays digital audio effects very nicely with the SBLASTER-SPEAKER. 

### Steps to reproduce the behaviour

Just start dosbox-x latest. Load wizardry 7.

### Expected behavior

Screen should display black pixels as black and save states should not corrupt the game.

### What operating system(s) this bug have occurred on?

Win 10 Update 20H2 19042.572    (I won't update of course!)

### What version(s) of DOSBox-X have this bug?

Latest.

### Used configuration

```ini
default
```

### Additional information

I'll check older Dosbox-X versions. 

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Probably same as #4507.
Try the latest nightly build.

**Comment by FFnewbie** [comment]
Very nice results!! Thank You!
1. I downloaded dosbox-x-vsbuild-win32-20231013042514.zip and indeed in that one this palette bug is fixed!
2. I found that **dosbox-x_MinGWx64_SDL2.exe**, which is  2023.10.06 64-bit SDL2 Build Oct 07 2023 05:52:23am
has fantastic Save State support. I tried saving and re-loading and the save-states work beautifully and no matter how many times I abuse Save-State load, the game works flawlessly. No game-data corruption occurs!
Of course that version has the palette bug. 
3. So now I'll hunt down a build, that has the palette bug solved AND has flawlessly working save states!

Thank You for your time and energy!!!

**Comment by FFnewbie** [comment]
Downloaded  **dosbox-x-mingw-win64-20231013042514.zip**. This - SDL2 - has the palette bug fixed and I couldn't reproduce any game corruption by extensively saving and reloading states. 
You can close this bug report as it looks like it has been fixed!
Excellent work!!
