### ISSUE TITLE
Intel dosbox-x v2023.10.06 crashes on startup (MacOS 12.7)

### ISSUE THREAD

**Issue by bksugiyama** [joncampbell123/dosbox-x#4535]
### Describe the bug

Attempting to open the latest dosbox-x.app release on the latest MacOS version yields a popup window indicating that the application quit unexpectedly. Attempting to run the application via terminal yields the same result plus the following error message:
> dyld[15511]: Library not loaded: '@executable_path/arm64/libavcodec.60.dylib'
>   Referenced from: '/Users/achernar/Desktop/dosbox-x-macosx-x86_64-20231006231157/dosbox-x/dosbox-x.app/Contents/MacOS/dosbox-x'
>   Reason: tried: '/Users/achernar/Desktop/dosbox-x-macosx-x86_64-20231006231157/dosbox-x/dosbox-x.app/Contents/MacOS/arm64/libavcodec.60.dylib' (no such file), '/usr/local/lib/libavcodec.60.dylib' (no such file), '/usr/lib/libavcodec.60.dylib' (no such file)

### Steps to reproduce the behaviour

1. Download dosbox-x 2023.10.06 for Intel Mac
2. Unzip the file
3. Navigate to the unzipped directory in command line
4. xattr -cr dosbox-x/dosbox-x.app dosbox-x-sdl2/dosbox-x.app
5. chmod +x dosbox-x/dosbox-x.app/Contents/MacOS/dosbox-x dosbox-x-sdl2/dosbox-x.app/Contents/MacOS/dosbox-x
6. Right click dosbox-x.app to open

### What operating system(s) this bug have occurred on?

MacOS 12.7

### What version(s) of DOSBox-X have this bug?

2023.10.06 SDL1/SDL2

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Dobby233Liu** [comment]
May be dupe of #4438

**Comment by maron2000** [comment]
A fix is yet to be merged but you can try this one.
https://github.com/joncampbell123/dosbox-x/actions/runs/6508129119

**Comment by bksugiyama** [comment]
Thanks for your input @Dobby233Liu, that seems likely since both are missing libraries (although the libs that throw the error appear to be different).

Thanks for your build @maron2000, it looks like that did the trick. I'm going to close this issue.

Cheers!
