### ISSUE TITLE
Freeze when setting the codepage to 856 using CHCP

### ISSUE THREAD

**Issue by scrutinizer80** [joncampbell123/dosbox-x#4547]
### Describe the bug

When setting the codepage to 856 using the "CHCP 856" command, DosBox-X immediately freezes.
Other codepages seem to work.

### Steps to reproduce the behaviour

type chcp 856 at the command prompt.

### Expected behavior

It should set the codepage.

### What operating system(s) this bug have occurred on?

Windows 11 22H2

### What version(s) of DOSBox-X have this bug?

2023.10.06 SDL2 64bit

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
This is a known issue regarding EGA18.CPX.
A workaround is explained in #3681.
