### ISSUE TITLE
warning: cannot open swap file cwsdpmi.swp

### ISSUE THREAD

**Issue by Chipsum** [joncampbell123/dosbox-x#4548]
### Question

I am trying to run an old emulator
[FCEPP](https://web.archive.org/web/20000818044655/http://www.geocities.co.jp/SiliconValley-PaloAlto/2353/fcepp006.zip)

but it keeps saying:
`warning: cannot open swap file cwsdpmi.swp`

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I don't see such message.
You may want to explain the steps in more detail.
![fcepp](https://github.com/joncampbell123/dosbox-x/assets/68574602/302b093e-a84c-4aca-b151-cefa70f9843c)

**Comment by Chipsum** [comment]
after running it with argument (rom file) it did work
@maron2000 Thank you so much

**Comment by Chipsum** [comment]
https://drive.google.com/file/d/1sT0W3Yn7KQfTX07lOJ8zA6gH7tTFNoZ4/view

**Comment by maron2000** [comment]
That's good news.
Please close this issue, since it is solved.
