### ISSUE TITLE
Make C++11 the minimum C++ standard for this code

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#455]
- Require at least GCC 4.8 on Linux (which supports C++11 proper)
- Require at least VS2013 on Windows (as I understand VS2013 supports C++11)

**Comment by mkoloberdin** [comment]
Why not C++14? It's been default in both gcc and clang for some time. Are there any platforms dosbox-x targets which are not supported by recent versions of gcc or clang?

**Comment by joncampbell123** [comment]
Consider that development with DOSBox-X so far has been done against the GCC 4.6 "C++0x" standard setting.

There are some who still want to compile against Windows XP, using VS2013 which I'm sure doesn't support C++14.

I also have a Raspberry Pi that I like to compile DOSBox-X on from time to time, which seems to ship with an older GCC as well, though one can update to GCC 4.8 on it.

I don't see any compelling features in C++14 for me to force that requirement on the code, but I have found a few handy features that makes C++11 attractive.

**Comment by mkoloberdin** [comment]
* https://solarianprogrammer.com/2017/12/08/raspberry-pi-raspbian-install-gcc-compile-cpp-17-programs/

> At the time of this writing Raspbian is based on Debian Stretch, which comes with the stable but slightly outdated GCC 6.3 as the default C and C++ compiler.

* https://archive.raspbian.org/raspbian/pool/main/g/gcc-6/

Am I missing something?

Windows XP: perhaps this can be "fixed" by compiling with MinGW. If anyone wants to test on XP, I can put up some MinGW-built binaries.

**Comment by mkoloberdin** [comment]
Here is an overview of current gcc versions on various Linux distros: https://github.com/KDE/kwin/commit/ea5d611de1bc33869c13c27d75a7827201a5139d

**Comment by joncampbell123** [comment]
That's cool, but let's first move the code up to C++11.

As I've stated, I see no compelling reason to use C++14 features yet.

**Comment by joncampbell123** [comment]
Phase 1 now: Linux configure script now warns you that C++0x support is deprecated if your GCC compiler does not support -std=gnu++11 (C++11).

**Comment by sagamusix** [comment]
C++11 support is flaky in VS2012/2013 (both compilers have bugs). VS2015 is probably the oldest Microsoft compiler that's worth supporting at this point. Windows XP is still supported in the latest VS2017, so that shouldn't keep you from using C++14.

**Comment by joncampbell123** [comment]
Ah, see, that's why I'm cautious against making C++11 mandatory right away. Compiler bugs.

If MinGW support is good enough the VS2013 issues can be avoided by dropping the VS2013 directory.

**Comment by sagamusix** [comment]
Well, compiler bugs exist in all compiler versions, all the time. ;) But by now any C++11-specific bugs should be ironed out in pretty much all big compilers, though. It's been out for almost 7 years after all.

**Comment by joncampbell123** [comment]
I just updated configure.ac to make C++11 more of a requirement, with still a fallback for those who really want to compile with C++0x. But, C++11 will become a requirement soon.

**Comment by joncampbell123** [comment]
It's mandatory now. This task is done.
