### ISSUE TITLE
DOSBox-X  black screen

### ISSUE THREAD

**Issue by GitHub-Rep-8Ans** [joncampbell123/dosbox-x#4559]
### Describe the bug

When i try to run a "Super Boulder Dash" which is made for Tandy or PCJR macines and have better sound and graphic then on SVGA_S3, i have no graphic just a sound like it should. Appears black screen on DOSBox-X.

I try to drag-drop ".bat" file with running code, but nothing.
I also try to "mount" folder and run, but nothing again.

So, if i change:

machine=tandy or machine=pcjr, should work, but not.

It is same thing on DOSBox-X x86 or x64 (mingw, mingw-sdl2).

I will attach a problem screenshot, and the Game.zip with dosbox-x.conf.
In dosbox-x.conf, "machine" is changed to "tandy".

Link to the game: [](https://www.xtcabandonware.com/game/2071/super-boulder-dash)
![Problem](https://github.com/joncampbell123/dosbox-x/assets/68502401/aafc4327-c0e8-4c92-a3b1-470100cd9a1e)
[Game.zip](https://github.com/joncampbell123/dosbox-x/files/13176681/Game.zip)

### Steps to reproduce the behaviour

1. In DosBox-X folder, in file "dosbox-x.conf", section "[dosbox]" change option "machine" to "tandy or pcjr"
2. Create ".BAT" file in game folder with code "boot boulder.img"
3. Drag-drop ".BAT" file to "dosbox-x.exe" to run the game
4. When you want to start the game press "1" or "2" (this must be shown on the screen)
5. You will hear correct sound
6. Problem: Black Screen.

### Expected behavior

I expected to work like on DosBox...
I will attach the pictures for better explaining. This screenshots are from DosBox.

![1](https://github.com/joncampbell123/dosbox-x/assets/68502401/27f51ef5-2e65-463c-94eb-49863d716356)
![2](https://github.com/joncampbell123/dosbox-x/assets/68502401/f61f00f9-8a27-4748-8f9a-6d316c928d00)

### What operating system(s) this bug have occurred on?

Windows 7 Ultimate SP1

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Used configuration

```ini
This configuration is from "dosbox-x.conf", and changed just a single line, "machine" to "tandy".

[dosbox]

machine = tandy
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I don't see any blackscreen, however I see some wheeling glitches.
Tested on 2023.10.06release and latest nightly (VS and MinGW builds) by following command.
```
dosbox-x -defaultconf -set machine=tandy
```
and `boot boulder.img`

![boulder](https://github.com/joncampbell123/dosbox-x/assets/68574602/16e45698-1350-440f-9da9-ca49b137acfc)

**Comment by GitHub-Rep-8Ans** [comment]
When i run that command which you provided (DOSBox-X switches to tandy machine) i have picture and glitches like you (and that glitches should be solved). But did you run without that command ?

Directly change machine to tandy into "dosbox-x.conf", put "boulder.img" into DOSBox-X folder, run "dosbox-x.exe" and appears like without switching to tandy machine. It's acting like it is in SVGA_S3. When you then type  "boot boulder.img"  should appears black screen. DOSBox-X like not change to tandy directly from "dosbox-x.conf".

When i type "config -get machine" i have message "tandy", but when i boot the game, appears black screen of DOSBox-X.

Try that.

**Comment by maron2000** [comment]
I have no problem switching to `machine=tandy` using a dosbox-x.conf.
However, it seems that `cycles=auto` is making the game somewhat unstable including the aforementioned graphic glitches.
Try a fixed value and/or `core=dynamic_x86`.

```
[dosbox]
machine        = tandy

[cpu]
core           = normal
fpu            = true
cputype        = auto
cycles         = 80000

[render]
aspect         = true
scaler         = normal2x
```
![boulder](https://github.com/joncampbell123/dosbox-x/assets/68574602/013b5f44-b019-4fc2-9b98-0ac759547b2a)

**Comment by rderooy** [comment]
FYI, I had a quick look what eXoDOS does for this game, and they set `machine=pcjr`. But they leave other settings to default.

**Comment by GitHub-Rep-8Ans** [comment]
I try it, the same Black Screen and sound is stuttering because cycle 80000 is to high. When i change to dynamic_x86, sound works fine but black screen still persist. And i try that from eXoDOS, nothing.

But.. i do simple change to default dosbox-x.conf

I managed to solve the problem of black screen. In default settings into "dosbox-x.conf" in section "[sdl]", output is set to "ttf". Then i change it to "default" and "machine" to "tandy".


So the main problem is ---> output = ttf


When i run "dosbox-x.exe" (swithches window to tandy) and type "boot boulder.img" it works.

In my opinion DOSBox-X should come with default setting in section "[sdl]" option "output" with setting "default", then problem with black screen should be solved:


output = default


I temprarly solved problem with glitches. In dosbox-x.conf i changed in section "[cpu]" like this:


cycles = 1300


Everything up to, and with 3900 will produce glitches. From 1300 and below it's fine. From 4000 and above is fine up to 26000 (picture is displayed and no glitches) when start sound stuttering,.


So, the changes are:


[sdl]

output = default

[dosbox]

machine = tandy

[cpu]

cycles = 1300



But i found a way to eliminate the sound stuttering with high cycles (from 26000 and above), setting CPU like this:


[cpu]

core = dynamic_rec


My opinion is that shouldn't happen with high CPU cycle, in similar games like bomberman, i don't have that.


Thank you for your effort, I appreciate it. Cheers...

No black screen

![Solved](https://github.com/joncampbell123/dosbox-x/assets/68502401/53e9c7f6-84d8-4a57-81a8-e9bcf4fef178)

Switched to tandy (fonts are like stretched)

![Tandy Screen](https://github.com/joncampbell123/dosbox-x/assets/68502401/e5ca3d9f-3fbf-474c-a82b-42688a9d4bac)

**Comment by rderooy** [comment]
`output=default` is the default value, not ttf. Still it should not show a black screen with TTF...

**Comment by GitHub-Rep-8Ans** [comment]
No it's not... Many times i downloaded DOSBox-X and when look into [SDL] section, i see output = ttf
This is default value, when i download the package (VS and MinGW builds).

![Default](https://github.com/joncampbell123/dosbox-x/assets/68502401/8e9ca198-0d6f-45ed-887c-b26e622726c9)

**Comment by GitHub-Rep-8Ans** [comment]
As you see on this picture it's not even logical video output like ddraw, opengl, direct3d.... It's output to Fonts ?! TrueType Fonts ?!
Why ? I not understand. I just know when i run this game with TTF setting, i have black screen.

**Comment by TeaRex73** [comment]
It's true that with the current Windows installer, TTF output is what you get if you leave all changeable installer options on their default values. So it seems to be deliberate.

**Comment by maron2000** [comment]
Indeed something is wrong when `output=ttf`, not only Boulder Dash but other games as well.
You may want to try a patch I made to switch off TTF mode when changing to graphics mode.

https://github.com/maron2000/dosbox-x-1/actions/runs/6673965758

**Comment by GitHub-Rep-8Ans** [comment]
Sorry for late response,

I downloaded patched DOSBox-X from link you provided and it works - no black screen, it switched to logical ouput when i change machine to tandy or PCJR. Now default work like it should. DOSBox-X looking better. Thanks...

In Boulder Dash when you press 2 you start second game and glitches started from  cycles = 770 up to 2420.

If you can fixed glitches from game 1 and 2, DOSBOX-X will be much better.

No black screen:

![Solved](https://github.com/joncampbell123/dosbox-x/assets/68502401/790d0794-3163-4d04-969f-5728658865fc)


Glitches when you press 2, when you start second game:

![Glitches](https://github.com/joncampbell123/dosbox-x/assets/68502401/173380f3-00ff-46d0-80d4-3b64716d1811)

**Comment by maron2000** [comment]
Thank you for trying.
So the black screen issue can be solved so I will put a PR.
Regarding the screen or sound glitches, since the speed setting depends on your PC it's hard to say.
In my case, `core=normal` and `cycles=12010` works fine on both 1 and 2 but may not be your case.

**Comment by GitHub-Rep-8Ans** [comment]
OK... But i try other tandy game and find some issue. Since DOSBox-X change video output, it back again to  ttf  and can't keep aspect ratio. I will attach the game and screen shots. 

[dosbox]

machine      = tandy

[render]

aspect         = true
aspect_ratio   = 4:3

Game:
[mono1k68.zip](https://github.com/joncampbell123/dosbox-x/files/13197046/mono1k68.zip)


Can't keep ratio:


![Issue](https://github.com/joncampbell123/dosbox-x/assets/68502401/ac96a6e5-ad4a-4dd7-a87a-9d5ecb256470)


Normal ratio:

![ed](https://github.com/joncampbell123/dosbox-x/assets/68502401/16eb6ff0-f942-4a57-9a36-110740d7fa26)

**Comment by maron2000** [comment]
TTF mode cannot adjust aspect ratio, so if that counts forr you, don't use it.
You can see that the dropdown menu is greyed out in TTF mode.
