### ISSUE TITLE
DR-DOS 7.01.08 doesn't boot

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#4562]
### Question

I tried to boot DR-DOS 7.01.08 (2011), but it doesn't work in DOSbox-X (artifact as of today), reaches only up to here:
![image](https://github.com/joncampbell123/dosbox-x/assets/97228894/a8b1b37e-13a7-40bb-9d35-13f592f6a387)

In VirtualBox the same floppy image boots:
![image](https://github.com/joncampbell123/dosbox-x/assets/97228894/b44591bc-e222-4d16-80f1-49d2f9d149b7)

Also, there is a [2023 revision](https://github.com/the-grue/edrdos).

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Do you have the log output?

**Comment by Torinde** [comment]
With MinGW64 SDL2 2023-10-27:
```
LOG: Flush STDIN
LOG: Identified 'A.IMG' as C/H/S 80/2/18 512 bytes/sector
LOG: Booting guest OS stack_seg=0x7000 load_seg=0x07c0
LOG: Removing UMB block 0xcc00-0xdfff
LOG: Alright: DOS kernel shutdown, booting a guest OS
LOG:   CS:IP=0000:7c00 SS:SP=7000:0100 AX=0000 BX=7c00 CX=0001 DX=0000
LOG:    3054882 ERROR BIOS:INT15:Unknown call ax=4100
LOG:    3074034 ERROR BIOS:Disk 2 not active
LOG:    3074049 ERROR BIOS:Disk 2 not active
LOG: INT13: Check Extensions Present for drive: 0x0
LOG:    3074512 ERROR BIOS:Disk 1 not active
LOG: INT13: AH=41h, Function not supported 0x55aa for drive: 0x1
LOG:    3074527 ERROR BIOS:Disk 1 not active
LOG:    3074541 ERROR BIOS:Disk 1 not active
LOG:    3074592 ERROR BIOS:Disk 1 not active
LOG:    3116336 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116345 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116354 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116363 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116372 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116381 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116390 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116399 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116408 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116417 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116426 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116435 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116444 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116453 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116462 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116471 ERROR CPU:Illegal Unhandled Interrupt Called 21
LOG:    3116480 ERROR CPU:Illegal Unhandled Interrupt Called 21
```

With MinGW64 SDL1 2023-04-15 - DOSbox windows (log console and DOSbox-X itself) disappear without any error message.

Looking at LOG above and VirtualBox result - maybe some of the int13 settings can help?

**Comment by maron2000** [comment]
It boots successfully if you turn off `int 13 extensions` option.
Considering that DR-DOS 8.1 boots fine with the aforementioned option `true`, so the this maybe a bug on the DR-DOS7.01 side.
Note that the version of the int13h extension that DOSBox-X supports is `1.x` while VirtualBox is 3.0 so your information whether VirtualBox works is not necessarily important.

**Comment by maron2000** [comment]
DR-DOS 7.01.08 WIP (5.8.2023) works with `int 13 extensions=true`.
A 10GB image is properly recognized.
This supports my above-mentioned assumption that the bug is in the 21.7.2011 version.
![drdos](https://github.com/joncampbell123/dosbox-x/assets/68574602/5684d4ee-f0a0-45d5-babc-c5657c00c7f6)

**Comment by Torinde** [comment]
What's the difference between v1.x, v3.0, etc. of the INT13H extensions?

**Comment by Torinde** [comment]
@maron2000, where can I download the binary of the 2023 `COMMAND.COM`? 
Links I found have only the DRBIO.SYS and DRDOS.SYS. It boots with those, but I would like to test how COMMAND.COM will report the free space.

Are you using https://hg.pushbx.org/ecm/edrdos/ (mirrored at [the-grue/edrdos](https://github.com/the-grue/edrdos)) or some other variant?

**Comment by maron2000** [comment]
I wasn't aware that a newer `command.com` exists, but you can find it in the [forum](https://www.bttr-software.de/forum/mix_entry.php?id=20457).

The screenshot above was using the 21.7.2011 version, but the 2023 August version works (boots) as well.
![drdos](https://github.com/joncampbell123/dosbox-x/assets/68574602/efb37c8b-11f2-454f-8b23-838d0a72b839)

**Comment by Torinde** [comment]
Thanks. First time I didn't notice the binary link there. In the same package (20230820) there are also DRBIO and DRDOS files, resulting in:
![image](https://github.com/joncampbell123/dosbox-x/assets/97228894/4434e02a-b945-4344-b656-e9ee72962c0a)

Reading that forum link I'm not certain if the "2023 August" DRBIO/DRDOS files (by @ecm-pushbx) include all changes of the "5.8.2023" files (by CandyMan). Also, in the repository there is at least one commit made after 2023-08-20, so that clearly is not in that binary.

As for the starting question - yes, as you said - with `int 13 extensions = false` the 21.7.2011 version boots:
![image](https://github.com/joncampbell123/dosbox-x/assets/97228894/06552a7c-3eb4-4e77-b56f-10c2b3514808)

**Comment by ecm-pushbx** [comment]
The changeset fixing this is likely to be https://hg.pushbx.org/ecm/edrdos/rev/18f345fe99d5

> Reading that forum link I'm not certain if the "2023 August" DRBIO/DRDOS files (by @ecm-pushbx) include all changes of the "5.8.2023" files (by CandyMan). Also, in the repository there is at least one commit made after 2023-08-20, so that clearly is not in that binary.

I did copy almost all of the contributions by CandyMan. My repo contains some more patches that I developed on my own.

The latest automatic build of my repo (the https://hg.pushbx.org/ecm/edrdos repo) is always available at https://pushbx.org/ecm/download/edrdos.zip which is currently the same file as https://pushbx.org/ecm/download/old/edrdos/20230829.zip

**Comment by Torinde** [comment]
Great! I didn't know there are automatic builds.
