### ISSUE TITLE
Joystick is not recognized by DOSBox-X 2023.10.06. but works well with DOSBox 0.74 - Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by Yokovich5** [joncampbell123/dosbox-x#4573]
### Describe the bug

My Saitek Cyborg 3D joystick won’t recognized by DOSBox-X 2023.10.06. despite it can be seen by Ubuntu as /dev/input/js0. Moreover it can be calibrated under Ubuntu with both jscal and jstest-gtk.
When joystick_type=auto then areas of joysticks are disabled in the mapper.
While joystick_type=4axis, and mapper is reset, areas of joysticks become active partially but “missing joystick” message is shown below. Mapping of buttons and axes is not possible.

![ksnip_20231024-220513](https://github.com/joncampbell123/dosbox-x/assets/149582212/9feac83d-8451-4e0a-b34f-80c049e35f55)

The same problem is not experienced with DOSBox 0.74. The joystick works well with joycheck.exe and games (e.g. xwing) under DOSBox 0.74. Value of joystick_type is auto.

![ksnip_20231024-221032](https://github.com/joncampbell123/dosbox-x/assets/149582212/c1c50981-d77f-4c9e-b4aa-64b94470c80f)

Is it a DOSBox-X related issue or am I doing something wrong?

### Steps to reproduce the behaviour

Attach your joystick, it won't be recognized.

### What operating system(s) this bug have occurred on?

Ubuntu 18.04.6 LTS

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2023.10.06

### Additional information

dosbox-x.conf file:
[dosbox-x.zip](https://github.com/joncampbell123/dosbox-x/files/13226239/dosbox-x.zip)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Not Ubuntu but works fine including analog sticks when I hooked an old Dualshock 2 to ArchLinux.
Tried both SDL1 & SDL2 versions of the latest commit 07f0a9c408673b9cf3d07d545d738ec759c1dd2d.

![joystick](https://github.com/joncampbell123/dosbox-x/assets/68574602/492523de-63ac-492a-a44c-5a8932cb725c)

**Comment by rderooy** [comment]
No issue here on Fedora 39, with either the SDL1 or SDL2 build.
![image](https://github.com/joncampbell123/dosbox-x/assets/17701098/f65dfddd-bc14-4a2d-ad6c-0b1668cb89b1)

**Comment by BridgeHeadland** [comment]
@Yokovich5 I have about the same issue as you. I tried to enable the XBox Series X controller (using Windows 10) in Duke Nukem episode 1 (1991) as a joystick in DOSBox-X, but for some reason it didn't work. I tried activating the same XBox controller as a Gravis Gamepad Pro (I have the driver installed) in 102 Dalmatians: Puppies to the Rescue, which I installed and am now testing out for my sister, to no avail. I don't know if DOSBox ever emulated controllers in general for Windows 9x games.
My point is: what platform version of DOSBox-X are you using? I'm using current developer builds of 64-bit MinGW builds (for 7+) with SDL2.

**Comment by Yokovich5** [comment]
@maron2000 ; @BridgeHeadland ; @rderooy 

Thanks everyone for the quick response :)

Well, I've just found a solution.
Installing and running DOSBox-X from Falthub, that is described [here](https://flathub.org/apps/com.dosbox_x.DOSBox-X), solves the issue, the joystick works fine.
While running DOSBox-X, that was installed with Ubuntu Software manager, the joystick still doesn't work.
I don't understand what's going on here ... DOSBox-X version is the same, the following text is shown in the upper right corner:
"v2023.10.06, Linux SDL2, 64-bit" in both cases.


One more question. You mentioned that both SDL1 and SDL2 were tried but I don't how to switch between them. My DOSBox-X shows SDL2. Sorry, I'm not not familiar with them all.

**Comment by rderooy** [comment]
I compiled them myself from source. Only the SDL2 version is available via flatpak. SDL1 is older, and should probably be regarded as deprecated.

**Comment by rderooy** [comment]
In any case, it seems that the Ubuntu version was likely not compiled properly. This is not handled by the DOSBox-X team.

**Comment by Yokovich5** [comment]
@rderooy 
OK. Thanks for your help.
I hope this solution will help others also.
