### ISSUE TITLE
Can two instances of DOSBOX-X be run at the same time?

### ISSUE THREAD

**Issue by IowaAlex** [joncampbell123/dosbox-x#4580]
### Question

I am testing a lot of DOS dBase utilities in a DOSBOX-X instance on my Windows 10 PC.
I am entering the results of the tests in Excel in my 2nd monitor on the same PC. 
I would like to run another DOS program on the same computer to track the results.
Is it possible to have two DOSBOX-X windows or instances on the same computer?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by RobertJSawyer** [comment]
I do this all time; I have multiple instances of DOSBox-X running. I've tried this on both Windows 11 64-bit and Windows 7 32-bit systems and never had a problem.

**Comment by joncampbell123** [comment]
It shouldn't be a problem unless you're sharing mounted disk images between the two (or more) instances.

**Comment by IowaAlex** [comment]
I am very new to DOSBOX-X.How would I do that?Create a 2nd config file?
Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm 

    On Friday, November 3, 2023 at 11:35:03 PM CDT, Jonathan Campbell ***@***.***> wrote:  
 
 


It shouldn't be a problem unless you're sharing mounted disk images between the two (or more) instances.

**Comment by rderooy** [comment]
Just go to a command prompt, and start two instances. And yes you probably will want different config files for them with different mount points for the folder or disk image mounts.

**Comment by IowaAlex** [comment]
Thanks!
Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm 

    On Saturday, November 4, 2023 at 03:53:57 PM CDT, Robert ***@***.***> wrote:  
 
 


Just go to a command prompt, and start two instances. And yes you probably will want different config files for them with different mount points for the folder or disk image mounts.

**Comment by IowaAlex** [comment]
Thanks. Found info on -conf paramater in the wiki that I have used in a BAT file (see below) Works great.
My question is when running DOSBOX-X, I can use the mouse to adjust the size of the window and its location on the screen. Is there a way to save that to the config file? Would that involve a Capture, Save State? If not, what are Save States used for?
Thanks again.So much fun to be using DOS again. Alex
Furthermore, you can start DOSBox-X with the -conf parameter to load a specified configuration file and use its settings. If this parameter is used, then DOSBox-X will try to load the specified configuration file before try to load the configuration file from the current directory or the user directory. 

Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm 

    On Saturday, November 4, 2023 at 03:53:57 PM CDT, Robert ***@***.***> wrote:  
 
 


Just go to a command prompt, and start two instances. And yes you probably will want different config files for them with different mount points for the folder or disk image mounts.

**Comment by IowaAlex** [comment]
Thanks!
Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm 

    On Friday, November 3, 2023 at 10:10:23 PM CDT, RobertJSawyer ***@***.***> wrote:  
 
 


I do this all time; I have multiple instances of DOSBox-X running. I've tried this on both Windows 11 64-bit and Windows 7 32-bit systems and never had a problem.

**Comment by IowaAlex** [comment]
I set up two conf files and used bat files for dosbox-x to use them with -conf parameter. Works very well.
