### ISSUE TITLE
Scalers don't work

### ISSUE THREAD

**Issue by jez9999** [joncampbell123/dosbox-x#4586]
### Describe the bug

The scaler's simply don't seem to work.  I've tried changing the video output to surface/direct3d/opengl, and I've tried turning Doublescan on/off.  I've also tried turning "force scaler" on/off.  When I change scalers all that seems to happen is the window size sometimes doubles or triples, and the greyscale scaler does make things greyscale, but none of the other scalers change the graphics.

### Steps to reproduce the behaviour

1. Start DOSBox-X and run a game (like Colonization)
2. Change scaler

### Expected behavior

Scaler should change graphics output.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
With `Force scaler` option set, it seems to work for me regardless of `Doublescan` option.
I put a screenshot tried with `Advanced MAME 2x`, and you can see the jaggy font is smoothed.

![scaler](https://github.com/joncampbell123/dosbox-x/assets/68574602/36f0a91d-58c9-400d-ace9-488b487aeaef)

**Comment by maron2000** [comment]
Sorry, if I play a game, you need to disable `Doublescan` as you mentioned.
![scaler2](https://github.com/joncampbell123/dosbox-x/assets/68574602/71fb5652-79ba-4b28-91ff-7db397204586)

**Comment by maron2000** [comment]
I found the following description regarding doublescan option and the scalers,
but I agree it should be noted somewhere more easily found (conf file, wiki etc.)
https://github.com/joncampbell123/dosbox-x/blob/master/README.source-code-description

```
DOSBox-X will generally render all scanlines that would be sent to a CRT,
meaning that 200-line modes are doubled, by default for accuracy. 
This can be disabled by setting doublescan=false to get DOSBox SVN behavior.

The reason it matters is that the doublescan behavior prevents the advanced
scalers (such as 2xsai) from working.
To enable these scalers, turn off the doublescan mode.
```

**Comment by retropwned** [comment]
where is the option to turn on/off doublescan in the drop down menu?
