### ISSUE TITLE
Delay on video mode switch & black areas in picture

### ISSUE THREAD

**Issue by Pantalaim0n** [joncampbell123/dosbox-x#459]
Switching video modes seem to have a delay of a few seconds, with some artifacts visible. I've also noticed there are black areas in the picture after changing video modes.

To illustrate this issue, I've made a small video where I trigger some video mode changes from graphics mode to text mode and back.

https://www.youtube.com/watch?v=ackZICI4K0w

It clearly shows the black areas on screen the second time it switches to text mode, and it's only redrawn on moving the mouse over it. The delays are also quite noticable, and the artifacts here are most notable at the end of the video at the top of the screen.

The black area issue seems to be present in all output modes (I've tried surface, opengl and direct3d), in both SDL1 and SDL2 builds. The delay between video modes is not present in the SDL2 build, and is only gone in SDL1 with opengl output. The artifacts are visible though.

I've experienced the same in Dosbox Daum, except for the delays.

**Comment by joncampbell123** [comment]
I'll be honest, the GFX code is a mess, so it may take awhile to untangle.

As for the redraw bugs, yes, that happens on my Linux dev system as well and I'm not sure what's causing it yet.

**Comment by joncampbell123** [comment]
Please check the latest commit, if you can compile from source, to see if this issue still happens.

Let me know if this is a SDL1 or SDL2 build issue.

**Comment by Pantalaim0n** [comment]
The delays, artifacts and black areas seem to fixed in the latest version. I've checked both SDL1 and SDL2. Thanks!
