### ISSUE TITLE
Macos x86_64 version tries to load arm64 libraries

### ISSUE THREAD

**Issue by RetepV** [joncampbell123/dosbox-x#4591]
### Question

I might have messed things up by first downloading and trying to run the Macos Arm64 dosbox-x in my X86 Macos laptop. I had mixed up my laptops. And it obviously didn't work.

So, I after I realised what was happening, I downloaded the X86_64 version. But when I try to run that, it quits unexpectedly on trying to load library `@executable_path/arm64/libavcodec.60.dylib`.

I can't imagine that the build is wrong, so something else must be causing the app to try to load an arm64 library. Could it be that there is some setting somewhere that's causing this?

First part of the crash report:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               dosbox-x [37083]
Path:                  /Applications/Dosbox/*/dosbox-x.app/Contents/MacOS/dosbox-x
Identifier:            com.dosbox-x
Version:               2023.10.06 (2023.10.06)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-06 21:19:56.0668 +0100
OS Version:            macOS 12.6.6 (21G646)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        A7BC02D0-E592-167E-A569-CBC3DBE71FD2

Sleep/Wake UUID:       94391B54-3A72-4A37-A3EB-6C19291BD2BA

Time Awake Since Boot: 740000 seconds
Time Since Wake:       4189 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@executable_path/arm64/libavcodec.60.dylib'
Referenced from: '/Applications/Dosbox/*/dosbox-x.app/Contents/MacOS/dosbox-x'
Reason: tried: '' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)
```

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by RetepV** [comment]
Sorry for answering my own question about 30 minutes later... :/

After getting nowhere, I decided to build dosbox-x from source. That worked fine.

But the catch: now the downloaded version started working as well!

I guess my hunch was right: by first accidentally running the Arm64 version, something in Macos became confused and the app wanted to load the Arm64 libraries instead of the X86_64 libraries. By building everything from scratch, it must have been reset.

So, closing this question, but keeping it here as reference.

**Comment by maron2000** [comment]
For your information, the issue is fixed in the recent nightly builds. Refer to issue #4438.
