### ISSUE TITLE
Star Wars - TIE Fighter - Collector's CD-ROM crash on start up

### ISSUE THREAD

**Issue by casasfernando** [joncampbell123/dosbox-x#4593]
### Describe the bug

Title says it all. Star Wars - TIE Fighter - Collector's CD-ROM crash on start up with the following error:

```
DOS/4GW error (2001): exception 00h (divide by zero) at 160:00212A8A
TSF32: prev_tsf32 4FD0
SS        B0 DS       168 ES       168 FS         0 GS       168
EAX        0 EBX     2000 ECX   212A61 EDX        0
ESI       66 EDI        0 EBP     4F38 ESP     4F30
CS:IP  160:00212A8A ID 00 COD        0 FLG       56
CS=  160, USE32, page granular, limit FFFFFFFF, base        0, acc CF9A
SS=   B0, USE32, byte granular, limit     7CFF, base   153DF0, acc 4092
DS=  168, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
ES=  168, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
FS=    0, USE16, byte granular, limit        0, base       14, acc  0
GS=  168, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
CR0: PG:0 ET:1 TS:0 EM:0 MP:0 PE:1   CR2: 0 CR3: 0
Crash address (unrelocated) = 1:00078A8A


C:\TIECD>
```

### Steps to reproduce the behaviour

1. Install the game from the CD-ROM image
2. Configure sound (tried SB16 and GUS)
3. Launch the game either using TIEAUTO.EXE (this will launch a graphical menu, then select Play) or TIE.EXE directly.
4. DOS4GW starts and then crashes with the error mentioned in the bug description.

### Expected behavior

The game starts up successfully and plays normally.

### What operating system(s) this bug have occurred on?

Linux (Steam OS 3.4.11 on Steam Deck)

### What version(s) of DOSBox-X have this bug?

2023.10.06 (SDL2)

### Used configuration

```ini
[sdl]
fullscreen       = true
fulldouble       = true
fullresolution   = desktop
windowresolution = original
output           = openglnb
autolock         = true
sensitivity      = 100
waitonerror      = true
priority         = higher,normal
mapperfile       = "Star Wars - TIE Fighter - Collector's CD-ROM.map"
usescancodes     = false
 
[dosbox]
language = 
machine = svga_s3
captures = capture
memsize = 16

[render]
frameskip = 0
aspect = true
scaler = normal3x

[cpu]
core = auto
cputype = auto
cycles = auto
cycleup = 10
cycledown = 20

[mixer]
nosound = false
rate = 44100
blocksize = 1024
prebuffer = 25

[midi]
mpu401 = intelligent
mididevice = fluidsynth
fluid.soundfont = "FluidR3_GM_GS.sf2"

[sblaster]
sbtype = none
sbbase = 220
irq = 7
dma = 1
hdma = 5
sbmixer = true
oplmode = auto
oplemu = default
oplrate = 44100

[gus]
gus = true
gusrate = 44100
gusbase = 240
gusirq = 5
gusdma = 3
ultradir = "U:\ULTRASND\411"

[speaker]
pcspeaker = true
pcrate = 44100
tandy = auto
tandyrate = 44100
disney = false

[joystick]
joysticktype = auto
timed = false
autofire = false
swap34 = false
buttonwrap = false
circularinput = false
deadzone = 10

[serial]
serial1 = dummy
serial2 = dummy
serial3 = disabled
serial4 = disabled

[dos]
xms = true
ems = true
umb = true
keyboardlayout = es

[ipx]
ipx = false

[autoexec]
mount c "data"
imgmount d "cdrom/Star Wars - TIE Fighter - Collector's CD-ROM.chd" -t cdrom
mount u "ultrasnd"
c:
cd TIECD
TIE.EXE
```

### Output log

```text
LOG:  112941789 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:  112941867 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:  112955564 ERROR BIOS:INT15:Unknown call ax=BF01
LOG:  116887257 ERROR MOUSE:Unhandled videomode 69 on reset
LOG:  117019124 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:  117019202 ERROR BIOS:INT15:Unknown call ax=BFDE
LOG:  117032561 ERROR BIOS:INT15:Unknown call ax=BF01
```

### Additional information

Things I've tried to make it work, unsuccessfully:

1. Tried to run loadfix before loading the game
2. Changed core = dynamic
3. Changed cpu = pentium and cycles = 31545
4. Disabled umb and ems
5. Tried disabling GUS and enabling SB instead
6. Tried different versions of DOS4GW provided with the game and also DOS32A
7. Tried with different CD-ROM images found in archive.org to discard my disc is corrupted. They all failed in with the same error.
8. Tried limiting vesa modes with vesa modelist cap = 10
9. Tried different machines types: machine=vesa_nolfb and machine=vesa_oldvbe

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I get the same result on Dosbox-staging.
![staging](https://github.com/joncampbell123/dosbox-x/assets/68574602/30ab98bd-a24c-4b64-ae45-6dced3dd779b)

**Comment by maron2000** [comment]
The game started successfully when booted from guest MS-DOS.
I tried it on PCDOS2000 and Windows 98SE boot disk.
Config.sys should be minimal, I loaded `himem.sys` and a CD driver `oakcdrom.sys` or `xcdrom.sys`.
EMS managers such as `EMM386.EXE` should NOT be loaded.

A bug of mouse drifting is known, so set `timed=false` before launching guest OS.
![tiefighter](https://github.com/joncampbell123/dosbox-x/assets/68574602/6a9a4b84-ab4b-45f7-a24b-4bec74fb886f)

**Comment by grapeli** [comment]
Star Wars TIE Fighter (Collector's CD-ROM) downloaded from eXoDOS works fine with the default DOSBox-X configuration.

[SWTieCD.dosbox-x.webm](https://github.com/joncampbell123/dosbox-x/assets/452325/9dbbcdb0-1530-4dd0-9a31-2b166258dc7f)

The fact that there are versions of various problematic games circulating on the Internet is no surprise.

**Comment by casasfernando** [comment]
Thanks for your comments and your help with this.

@maron2000 it's great to know that using MS-DOS instead of the emulated DOS from DOSBox-X works. Unfortunately the drawback for me is that I will forced to use an image for the C: drive instead of a host folder (currently I'm mounting ZIP files -using fuse-zip- and overlays -using fuse-overlayfs- to play the games)

@grapeli I'm not familiar with eXoDOS and I would prefer to use my own disc image whenever possible (I verified the dump is correct using redump.org checksum)

Yesterday while playing around with a dozen settings changes I found a combination that worked with DOS4GW 1.92 (included in the game disc). Unfortunately I was dumb enough to assume that the problem was DOS4GW 1.97 or 1.95 (also included with the game) and by mistake reseted all the settings back to default without making a backup first.
Now I'm pulling my hair off trying to find again the working combination again.

Any specific settings suggestions are welcome.

**Comment by casasfernando** [comment]
I have a small update, the error I shared initially was incomplete since part of the text was not visible in DOSBox-X window. I ran `TIE.EXE > CRASH.TXT` and got the full output into the text file:

```
DOS/4GW error (2001): exception 00h (divide by zero) at 160:00212A8A
TSF32: prev_tsf32 4FD0
SS        B0 DS       168 ES       168 FS         0 GS       168
EAX        0 EBX     2000 ECX   212A61 EDX        0
ESI       66 EDI        0 EBP     4F38 ESP     4F30
CS:IP  160:00212A8A ID 00 COD        0 FLG       56
CS=  160, USE32, page granular, limit FFFFFFFF, base        0, acc CF9A
SS=   B0, USE32, byte granular, limit     7CFF, base   153DF0, acc 4092
DS=  168, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
ES=  168, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
FS=    0, USE16, byte granular, limit        0, base       14, acc  0
GS=  168, USE32, page granular, limit FFFFFFFF, base        0, acc CF92
CR0: PG:0 ET:1 TS:0 EM:0 MP:0 PE:1   CR2: 0 CR3: 0
Crash address (unrelocated) = 1:00078A8A
```

I will update my first post as well for anyone else finding this issue, to get the full error right from the start.

**Comment by maron2000** [comment]
It seems this is a bug of the installer.
After you install, check `CDROM.CFG` in the `TIECD` directory (or wherever you installed).
If it is missing, create it and check that the content is a single line `0 8082`.
(in my case it was `0 0`, but the one in the ExoDOS distribution that @grepeli mentioned was as such)
I installed by `Maximum Install` and setup the sound card with SB16 for both music and digital sound.
DOS4GW is version 1.97, and no need to shut off EMS.

**Comment by casasfernando** [comment]
> It seems this is a bug of the installer. After you install, check `CDROM.CFG` in the `TIECD` directory (or wherever you installed). If it is missing, create it and check that the content is a single line `0 8082`. (in my case it was `0 0`, but the one in the ExoDOS distribution that @grepeli mentioned was as such) I installed by `Maximum Install` and setup the sound card with SB16 for both music and digital sound. DOS4GW is version 1.97, and no need to boot guest DOS and/or shut off EMS.

This is it!
I was currently deep inspecting the eXoDOS package and one of the two differences I found was the CDROM.CFG and the FOPTION.CFG.

In my case I did a minimum install and the CDROM.CFG content was `9 0`, changed to `0 8082` and now the game starts successfully with the configuration I posted above.

Thanks for all your help @maron2000 , @grapeli .

**Comment by rderooy** [comment]
The fact that it works from real DOS and not from the emulated DOS still means there is an issue.

**Comment by casasfernando** [comment]
I suspect the game is trying to measure CD-ROM speed on first run, but this is just speculation.
CDROM.CFG doesn't exist after installation and it get's created on first run.
The behavior is not consistent as far as I could see, sometimes the file gets created with `9 0` inside, resulting in the divide by and nothing is logged in DOSBox-X log.
But I found that other times, following error message floods DOSBox-X log:

```
 165349247 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349251 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349255 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349259 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349263 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349267 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349271 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349275 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349279 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349283 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349287 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349291 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349295 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349299 ERROR CPU:Illegal Unhandled Interrupt Called 1
 165349303 ERROR CPU:Illegal Unhandled Interrupt Called 1
```
And then the game eventually crash or I need to quit DOSBox-X.
When this happens CDROM.CFG is created, yet without any content (empty, 0 bytes) and on the next run the game finds the file, it seems to skip part of the routine and the game boots successfully.
I'm currently playing with `hard drive data rate limit` value to try to confirm this is the problem but I tried with 'hard drive data rate limit = 307200' and I got the same behavior.

**Comment by RvN73** [comment]
The game works 100% with DosBox-X 2022.12.26, it crashes on all newer versions

**Comment by o-schneider** [comment]
I have the same issue with DOSBox-X 2024.03.01 using de CD version from GOG. The game starts properly on DOSBox version 0.74-3.

**Comment by maron2000** [comment]
Carefuly read the previous posts and explain your steps.
