### ISSUE TITLE
The Last Express not enough Extended memory

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#4602]
### Describe the bug

Game refuses to boot and claims not enough extended memory
![command_005](https://github.com/joncampbell123/dosbox-x/assets/68984176/95cfd3ce-8b2a-4a93-96dd-1cb646a90393)

### Steps to reproduce the behaviour

Install game from CD (only the 1st disk is needed to reproduce issue)
run Express from C:\Express\

### Expected behavior

Game should be booting.

### What operating system(s) this bug have occurred on?

Windows 10 x64

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
It starts and runs with the **default configuration**.

[last.express.dosbox-x.webm](https://github.com/joncampbell123/dosbox-x/assets/452325/3f5fffe5-f549-45c4-9220-547357b6b03b)

**Comment by rderooy** [comment]
> It starts and runs with the **default configuration**.
> 
>  last.express.dosbox-x.webm

Thanks. I did wonder about it, but did not test it. Especially since mobygames lists the memory requirements for the game as 8MB.

**Comment by grapeli** [comment]
README.TXT

> ...
> 8MB RAM Required, 16MB RAM Recommended
> ...
> Memory
> The Last Express requires 500K free conventional memory and 7100K
> free XMS memory to run.
>

**Comment by ualaa1** [comment]
I deleted my config file since it was causing some strange issues with certain games. With the config file deleted, I was able to get slightly further but got stopped by this issue. Unfortunately, I now cannot fin
d where my screenshots when using the screenshot mode in emulator, so I have to use a different way to do a screenshot. I originally also wanted to do a savestate as well but now I can't find where Dosbox-X puts the savestates ever since deleting the config folder.
![bandicam 2023-11-13 23-05-55-135](https://github.com/joncampbell123/dosbox-x/assets/68984176/3faf736a-d740-4694-9dcd-d4b40ad16dbc)
I am aware that in dosbox, it requires a file called HD.HPF to be in the directory, and it seems like in dosbox-X it is required as well. I am not sure if this is a game glitch or emulation glitch

**Comment by rderooy** [comment]
That file is part of the game, or possibly created by the games installer. If it is missing, just re-install the game.

**Comment by maron2000** [comment]
According to the vanilla DOSBox compatibility list, this seems to be a bug of the game's installer.
```
When the DOS installer from CD1 is used, it doesn't create a needed file called "HD.HPF", thus creating a broken game. However, when the Windows installer is used, this works perfectly and you can copy the HD.HPF from the Windows installation into DosBox, which will make the game runable and playable. Sound is okay and video playback is smooth, but there is one big problem: all the colors are fucked up. I tried running UNIVBE first, but it doesn't help. If the colors could be fixed somehow, this magnificant game would be fully playable in DosBox.
```

**Comment by ualaa1** [comment]
Thanks for the information. Closing for now as it seems to be a game bug and not an emulator one.
