### ISSUE TITLE
Future Wars refuses to install to HD as it claims it is already installed when in fact it isn't installed

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#4603]
### Describe the bug

I wanted to install game onto HD in order to config graphics and audio, but it refuses to install onto HD
Game still works fine when running from CD using FW.bat but with no sound effects and severe graphical flickering.
![install_000](https://github.com/joncampbell123/dosbox-x/assets/68984176/2535e992-c5d2-4976-bcc8-80cb32037e05)
Because I am unable to install to HD, I am unable to save config
![install_002](https://github.com/joncampbell123/dosbox-x/assets/68984176/3748df1f-6431-4c35-8a0b-61e03ec06fc3)

### Steps to reproduce the behaviour

Try to install from CD.

### Expected behavior

Game installs

### What operating system(s) this bug have occurred on?

Windows 10 x64

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I am too surprised that the installer worked like a charm.
Both CD and floppy versions works.

https://github.com/joncampbell123/dosbox-x/assets/68574602/455feafb-47ac-4466-8ece-1c4a42ae73d6

![install_000](https://github.com/joncampbell123/dosbox-x/assets/68574602/2b16a0a0-34dd-4400-aa8b-1955c4045bae)

**Comment by maron2000** [comment]
Looking at README.TXT in the CD, the recommended installation is to copy the whole directory manually to your hard drive.
If you carefully follow the instructions, it works as well.
```
INSTALLATION INSTRUCTIONS
  Future Wars can be played off of the CD-ROM, but we suggest copying the files to the hard drive 
for better performance.
1. Make a directory on your hard drive (for example, "MD C:\FW" at C:).
2. Copy all of the files from the Future Wars subdirectory on the CD-ROM to the subdirectory on your
   hard drive (for example, "COPY S:\FW\*.* C:\FW" if your CD-ROM drive is S:).
3. The files should be copied over to the hard drive.
   Whenever you want to play Future Wars, you will need to put the CD-ROM in your CD-ROM drive.
4. You will need to configure the program to your system.
   From the FW subdirectory on the hard drive, type INSTALL and press Enter.
   Follow the on-screen instructions.
5. When you are finished installing, exit to DOS and type FW Enter to start the game.
```

**Comment by ualaa1** [comment]
Seems to be a game bug and not emulation error that the GUI installer doesn't often work. Closing for now.
