### ISSUE TITLE
Star Fleet II Krellan Commander screen turns black after first screen (works with latest nightly)

### ISSUE THREAD

**Issue by tacticurn** [joncampbell123/dosbox-x#4607]
### Describe the bug

GOG version of the game is used.

Running the sf2.exe from DOXBox-X  shows a logo first, and on pressing space the screen turns black, while music plays, and stays so even after.

The same files opened in DOSbox Legacy works without problems, so that a game might be started after the two instroduction sequences.

### Steps to reproduce the behaviour

1. Launch SF2.exe
2. Press space after the first screen with music
3. Consider the black screen.

### Expected behavior

After pressing space, the game should show a title page with music playing (some classic piece). Upon pressing space a second time, the main menu of the software should be displayed.

### What operating system(s) this bug have occurred on?

macOS Ventura 13.5

### What version(s) of DOSBox-X have this bug?

2023.10.06 (SDL2)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment]
The tested version downloaded from eXoDOS runs correctly with default settings.

[Star.Fleet.II.dosbox-x.webm](https://github.com/joncampbell123/dosbox-x/assets/452325/2ef8ca32-1002-4f22-bb72-11be8922813e)

**Comment by maron2000** [comment]
Try the latest nightly build.

**Comment by tacticurn** [comment]
> Try the latest nightly build.
Eh, I should probably had done that before posting here. Thanks, it runs with the [6e74751 commit](https://github.com/joncampbell123/dosbox-x/commit/6e747515bd95aea93ac087d397569abc8a5dc6d0)

**Comment by tacticurn** [comment]
> The tested version downloaded from eXoDOS runs correctly with default settings.
> 
>  Star.Fleet.II.dosbox-x.webm

Haven't heard about ExoDos before.

**Comment by tacticurn** [comment]
Latest nightly seems to work fine with the game.
