### ISSUE TITLE
SDL 1.x: Maximizing the window should maximize the window and stretch (with or without aspect ratio correction) the screen to fill the window.

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#461]
On latest builds (on build 2017-12-25 and later:
https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-0.82.1
Expanding Dosbox window in Direct3d output now opening Fullscreen mode instead of just expanding in Windowed mode
On builds 2017-12-24 or earlier:
https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-20171224
Window expanding normally.
 
Seems that commit brokes that behavor: 
https://github.com/joncampbell123/dosbox-x/commit/b7c507dce925ae92e35122dfbb3efd1f24af737f

**Comment by joncampbell123** [comment]
That was intentional, yes. Maximizing the window for OpenGL and other output modes triggers fullscreen, so Direct3D should do the same.

Also, Direct3D in a maximized window stretches to fill (and distort the aspect ratio) within the window.

**Comment by Corak667** [comment]
Oh, that's very bad intention and unuseful now. I always prefered to set Direct3d just because of that great feature - maximized widowed mode (even distorted in aspect ratio) instead of fullscreen that very slow to switch task.

**Comment by joncampbell123** [comment]
I think what I'll do then is re-add it back, but for all modes if possible, and if the "aspect ratio" setting is on, to center the image in the window as well.

**Comment by Corak667** [comment]
Agree, this will be useful to auto resize maximized window if forced aspect mode on)

**Comment by joncampbell123** [comment]
In the development branch, I just fixed the code to let the window maximize rather than trigger fullscreen, and I managed to hack the Direct3D code to maintain aspect ratio when the window is maximized.

Do understand that OpenGL and Surface outputs haven't been updated the same yet and currently broken with a maximized window.

Commit:
https://github.com/joncampbell123/dosbox-x/commit/a6b3e7f95488ec0dd9eeb2ff85123d2a4a0ede87

**Comment by joncampbell123** [comment]
and another commit, to do the same with OpenGL output

**Comment by joncampbell123** [comment]
I'll post a binary soon for you to test. Direct3D and OpenGL output has been updated to work properly with a maximized window instead of going fullscreen. The surface output has been updated to center in the window properly in the same case.

**Comment by joncampbell123** [comment]
Binaries posted. Let me know if the changes are satisfactory enough to close this issue.

**Comment by Corak667** [comment]
Thanks! Tested, everything works as it should be. On forced aspect it corrects in windowed mode.
