### ISSUE TITLE
Increase Performance

### ISSUE THREAD

**Issue by bentrab** [joncampbell123/dosbox-x#4610]
### Question

I am trying to run a 16 bit COBOL executable on DosBox-X and am seeing significant performance issues compared to running the same program in Windows XP.  I have tried adjusting the cycles parameter and that does not seem to make any difference.  Are there any other parameters in the configuration that I should adjust?  The performance issues are most noticeable when loading large files into the program. 

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
DOSBox-X emulates disk I/O delays, set "hard drive data rate limit=0" under the [dos] section of your dosbox.conf.

**Comment by maron2000** [comment]
If I try to copy a large file like a CD image on a mounted directory (not a HDD image) within DOSBox-X, it copies the file around 70-120MB/s which I think not so bad.
But random access or accessing bunch of small files maybe much slower.

**Comment by maron2000** [comment]
If I copy a CD image to a HDD image, the transfer speed significantly droped to less than 1MB/s.
I hope I'm not doing it wrong, but `hard drive data rate limit` is set to `0`.

**Comment by bentrab** [comment]
Is there a parameter to dump memory to disk faster than the default?

**Comment by bentrab** [comment]
Really late here but setting "hard drive data rate limit=0" vastly improved the performance. Thanks!
