### ISSUE TITLE
Hungarian Translation

### ISSUE THREAD

**Issue by shungabubus** [joncampbell123/dosbox-x#4618]
### Is your feature request related to a problem? Please describe.

It's nice to see that you appreciate any contribution, but I found no reference on the translation so I tried to create a file for the Hungarian language file. 

### What you want

Please help me as either my experience and or my privileges were insufficient to succeed with any file upload.

### Describe alternatives you've considered

I tried github desktop and online creation.

### Additional information

The translation is READY so I'd just need to upload it somehow or mail to someone...

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
If you don't know how to create a pull-request, you can simply attach the file right here. Just rename the file to have a `.txt` extension and github will allow it.

**Comment by shungabubus** [comment]
Hello, I think I managed it under 4620 through a fork :)

**Comment by Torinde** [comment]
- #2820
