### ISSUE TITLE
prebuffer is defined but has no function...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#463]
Hello,
is it possible to bring back the "prebuffer" function like in the current vanilla SVN.
"prebuffer" is defined in the "dosbox.cpp" and have a function in the mixer.cpp of the Vanilla SVN but the mixer.cpp of Your fork is completely rewoten and the prebuffer is no more used.
I want the function back because it reducing the Sound crackling on high dosapp cpu usage Spikes.

**Comment by joncampbell123** [comment]
I suppose I could modify my rewrite to use it.

**Comment by joncampbell123** [comment]
Yes. Just committed the change now.

https://github.com/joncampbell123/dosbox-x/commit/0e25762592710569528450d785331b56c41ccc9c
