### ISSUE TITLE
How to send function keys to application in DOSBOX-X and not to Windows?

### ISSUE THREAD

**Issue by IowaAlex** [joncampbell123/dosbox-x#4630]
### Question

When I am running a DOS program in DOSBOX-X in Windows 10 64, the function keys are being used by Windows instead of the application. How can I set up the function keys for the application and not Windows?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Regular function keys should normally work. Are the function keys in windows perhaps being mapped to multimedia functions? If so your keyboard may have a "Fn" key that you need to press to get regular function keys.

For instance, on modern ThinkPads, by default F1 will be Mute. If you need F1 you actually need to press Fn-F1. This can be inverted in the BIOS, such that F1 is again F1 (if you need mute, you can still press Fn-F1 in that case).

There are however some keys that DOSBox-X cannot capture. In that case you can either select the key combination from the pull-down menus (e.g. CTRL-ALT-DEL), or you can re-map the key with the keymapper to a different key.

**Comment by IowaAlex** [comment]
That works. Thanks!
Alex Campbell
====================================================
Always read what you have written to see if you've any words out. 
courtesy of http://www-users.cs.york.ac.uk/susan/cyc/e/safire.htm 

    On Saturday, November 25, 2023 at 02:13:33 PM EST, Robert ***@***.***> wrote:  
 
 


Regular function keys should normally work. Are the function keys in windows perhaps being mapped to multimedia functions? If so your keyboard may have a "Fn" key that you need to press to get regular function keys.

For instance, on modern ThinkPads, by default F1 will be Mute. If you need F1 you actually need to press Fn-F1. This can be inverted in the BIOS, such that F1 is again F1 (if you need mute, you can still press Fn-F1 in that case).

There are however some keys that DOSBox-X cannot capture. In that case you can either select the key combination from the pull-down menus (e.g. CTRL-ALT-DEL), or you can re-map the key with the keymapper to a different key.

**Comment by rderooy** [comment]
If it solved your problem, please close the issue.

**Comment by IowaAlex** [comment]
Will do tonight


Sent from Yahoo Mail for iPhone


On Saturday, November 25, 2023, 3:55 PM, Robert ***@***.***> wrote:




If it solved your problem, please close the issue.

**Comment by IowaAlex** [comment]
Using my Fn key with Function keys fixed problem.
