### ISSUE TITLE
How to get 4DOS and install it in DOSBOX-X?

### ISSUE THREAD

**Issue by IowaAlex** [joncampbell123/dosbox-x#4631]
### Question

I found this, but I haven't found any place that tells me where to get 4DOS and how to install it. 

https://dosbox-x.com/wiki/DOSBox%E2%80%90X%E2%80%99s-Feature-Highlights

Support for 4DOS as the alternative shell with 4DOS 8.00 features and capabilities

You can set SHELL=4DOS.COM so that DOSBox-X will run the 4DOS 8.00 shell at start instead of the default shell.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
github provides search button, which you should be accustomed to using it.
https://github.com/search?q=repo%3Ajoncampbell123%2Fdosbox-x+4dos&type=wikis

**Comment by IowaAlex** [comment]
I discovered that there are two places - shell AND ver - that 4DOS need to be included in the conf file;

This reference that I had found only refers to [config] shell and not [dos] ver. 
https://github.com/joncampbell123/dosbox-x/wiki/DOSBox%E2%80%90X%E2%80%99s-Supported-Commands
4DOS (external command)

Starts the 4DOS 8.00 command shell for 4DOS features and capabilities.

Usage: 4DOS [option]

Note: You can set 4DOS.COM as the default shell to start (instead of COMMAND.COM) via the SHELL option in the config file. When in the 4DOS shell, type OPTION to set 4DOS options.

[dos]
ver=8.00

**Comment by IowaAlex** [comment]
When I added the ver number in addition to 4DOS when I typed Help at the dos prompt, then I go the 4DOS commands.

**Comment by IowaAlex** [comment]
[config]
shell=4DOS.COM

[dos]
ver=8.00
