### ISSUE TITLE
Setting DAC registers via VGA BIOS int 10h funct. 00h, subfunc. 12h with cx==16 always results in a black screen. cx<>16 works as expected. Original DOS 6.2, DOSBox and DOSBox-X 2023.03.31 don't show this behavior

### ISSUE THREAD

**Issue by EmoticonSmile** [joncampbell123/dosbox-x#4633]
### Describe the bug

```
;cx==16 always results in a blank screen on VGA int 10h func. 00h, subfunc. 12h
;...

mov   ax,0012h         ;resolution 640x480 / 10 colors
int   10h

mov   ax,cs            ;initialize VGA Attribute Controller with 0-15
mov   es,ax
mov   ax,1002h         ;func. 10h, subfunc. 02h
lea   dx,colormap  
int   10h
                              
lea   dx,colors_key    ;memo:  already ds=cs
xor   bx,bx
mov   cx,16            ; ***** <- bug happens when cx==16 : black screen (cx<=15 or cx>=17 works like expected) ****
mov   ax,0012h         ;0h, subfunc. 12h 
int   10h              ;set DAC registers 0 - 16 with colors (G,B,R) 

;black screen... that's it, man! Game over, man. Game over! What the %&%& are we gonna do now? What are we gonna do? 

;...
colormap db 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,0
colors db 000,000,000      ;background: black
db 23 dup (063,063,063)    ;rest of colors: intense white - a few more triplets that 15 for testing cx>=16
```

### Steps to reproduce the behaviour

Build with MASM into small *.exe or *.com and run.

### Expected behavior

Setting VGA DAC registers for 4/16 color mode with VGA BIOS 0h, subfunc. 12h and cx=16 malfunctions and results in a complete black screen in DOSBox-X-Windows-2023.10.06. On cx<>16 the call works correctly. Original DOS 6.2 on a real VGA PC, original DOSBox and DOSBox-X 2023.03.31 don't show this behavior.

### What operating system(s) this bug have occurred on?

Windows 11 21H2 Build 22000.2538

### What version(s) of DOSBox-X have this bug?

DOSBox-X-Windows-2023.10.06

### Used configuration

```ini
Tried dozends of configuations for 'output', 'videodriver' and tried on different machines. All show this behavior.
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Perhaps same as #4607, #4613.
Try the latest nightly build.

**Comment by EmoticonSmile** [comment]
> Perhaps same as #4607, #4613. Try the latest nightly build.

latest nightly build solved the issue. tnx
