### ISSUE TITLE
Long file name support not working on the PC-98

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#4637]
### Describe the bug

Apps with long file name support appear to be not working on the PC-98. No files are found when LFN support is enabled.

Tested both in PC-98 and PC/AT emulation modes, with DOS version set to 7.10 and lfn=auto on dosbox.conf

### Steps to reproduce the behaviour

MG is an image converter for legacy Japanese image formats used on the PC-98, FM-Towns, MSX etc. 

1. Download [mg lfn-v0.99c](http://www.6809.net/tenk/html/lib/dos16/mg-lfn-v0.99c.zip) from [this page](http://www.6809.net/tenk/html/lib/dos16/), that also has its source code.
2. Place some 16-color and 256 color BMP files in a folder. The BMP files must be legacy, without any fancy headers. GIMP can save them with the "Do not write color space information" compatibility option enabled.  XnConvert also, with the "OS/2 BMP" option enabled
3. Run mg with the following command line:
`mg .mag -l1 *.bmp`

The following error will be output:
`'*.bmp'が見つからない`
...that translates to: '*.bmp' not found

4. If LFN support is disabled with the following parameter, the files will be found, but with the truncated short file names:
`mg .mag -l0 *.bmp`

### Expected behavior

MG should be able to find the files with the -l1 parameter on a DOS that has LFN support.

### What operating system(s) this bug have occurred on?

macOS 12.7.1

### What version(s) of DOSBox-X have this bug?

2023.05.01

### Additional information

I tested mg.exe on Microsoft Windows [Version 10.0.19045.3031] 32bit/English and it worked fine with long file names.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Does it have anything to do with the shell, or Shift-JIS encoding?

**Comment by maron2000** [comment]
I haven't got in so deeply, but the screenshot provided, I accessed a file with ASCII characters only so ShiftJIS may not matter.

**Comment by nanshiki** [comment]
It seems that two extra bytes were copied due to structure padding, which was destroying the mg.exe work area.
Also, The date/time and other values in the LFN file information were incorrect.
#4645

**Comment by maron2000** [comment]
@sdsnatcher I think this issue can be closed.

**Comment by sdsnatcher** [comment]
> @sdsnatcher I think this issue can be closed.

I've just tested it, and it worked like a charm. Thank you!
