### ISSUE TITLE
Variable in DOS_Int21_71a6() dereferenced past its size

### ISSUE THREAD

**Issue by SmileTheory** [joncampbell123/dosbox-x#4644]
https://github.com/joncampbell123/dosbox-x/blob/f8e923696c29760aae974e9444229ed210d97cb9/src/dos/dos.cpp#L5357C204-L5357C204

On this line, `handle` is `uint8_t`, but the `sprintf()` call casts its address to a `char *` and attempts to pull four characters out of it.

Spotted this while looking at https://github.com/joncampbell123/dosbox-x/issues/4538 , don't know if it is the error, but it is at least an error.

**Comment by joncampbell123** [comment]
Good catch. Perhaps it's a programmer mistake considering all the other parameters are (char*)&something.

**Comment by SmileTheory** [comment]
https://github.com/joncampbell123/dosbox-x/commit/505231b81b6c43681190ec0e82b1bc7c412818e9 fixes this bug, but in investigating it I found another one, for which I have submitted a pull request in https://github.com/joncampbell123/dosbox-x/pull/4647 .
