### ISSUE TITLE
Joystick events not seen in Mapper under Windows 10

### ISSUE THREAD

**Issue by TRex691** [joncampbell123/dosbox-x#4665]
### Question

How do I get the Mapper to see joystick events under Windows 10?  Works fine under Win XP.  Joystick appears to install properly and calibrates but mapper cannot see events to map to keyboard presses.  Joystick is a Logitech Wingman Freedom 2.4 but I see same behavior with other joysticks.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by TRex691** [comment]
Build 2023.03.31 64 bit SDL1

**Comment by maron2000** [comment]
This issue is a duplicate of #3974.
Try SDL2 build or install a Direct input to Xinput converter for SDL1 build.

![joystick](https://github.com/joncampbell123/dosbox-x/assets/68574602/9df51e82-4651-451a-bbcd-1c68959b2f9a)

**Comment by TRex691** [comment]
That did it!  Thank you maron2000!  It turned out that only the 64 bit SDL2 version worked while the 32 bit did not.  The different versions cover more of the parameter space...

**Comment by maron2000** [comment]
Glad to hear good news.
Just for your reference, my joystick (Dualshock 2) works on the SDL2 VS x86(32-bit) build (latest nightly) so maybe there are particular settings for your joystick.
