### ISSUE TITLE
Black screen in loading Cisco Heat, in VGA mode only

### ISSUE THREAD

**Issue by FloLore** [joncampbell123/dosbox-x#4674]
### Describe the bug

Hi the team,

I have trying to run Cisco Heat in VGA mode, but this is a black screen always, only in VGA. The EGA and CGA mode run very well...

In dosbox.cfg, i have trying in machine category all the card, from vga, svga..., vesa... etc...

This game is compatible perfectly with other Dosbox, in VGA mode, but my favorites is your, so please help me to correct this issue ?

### Steps to reproduce the behaviour

To reproduce this bug, simply try to run Cisco Eat in VGA mode. The black screen appear in anything options of dosbox.cfg...

### What operating system(s) this bug have occurred on?

Windows 11 64 pro

### What version(s) of DOSBox-X have this bug?

All dosbox-x, i have trying from the last (2023.6.10) to 2020

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by FloLore** [comment]
The log with VGA enable :

Logging: opened logfile 'log' successfully. All further logging will go to this file.
DOSBox-X version 2023.10.06 (Windows SDL2)
SDL: version 2.28.2, Video windows, Audio directsound)
Windows keyboard layout ID is 0x040c
Host keyboard layout is now us (US English)
Mapper keyboard layout is now us (US English)
SDL2 reports desktop display mode 2880 x 1620
Configured windowposition: 
SDL: Current window pixel format: SDL_PIXELFORMAT_RGB888
SDL: You are running in 24 bpp mode, this will slow down things!
D3D:Using triple buffering
SDL: Windows 11 round corners will be disabled.
Screen report: Method 'Win98base' (2880.000 x 1620.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (144.000 x 144.000 DPI)
ISA BCLK: 8333333.333Hz (25000000/3)
monopal: green, 
Active save slot: 1 [Empty]
USING AVI+ZMBV
Max 3670016 sz 16384
Final 16384
Glide:LFB access: read-write (no aux)
Glide:Unable to load glide2x library, glide emulation disabled
MIDI:Opened device:win32
Pentium CMPXCHG8B emulation is enabled

**Comment by FloLore** [comment]
PS 2 : Strangely, there are a file created (LPT1 with O byte) in game directory, only with Dosbox-x, during my other trying with many dosbox, i haven't seen this file to be create...

**Comment by maron2000** [comment]
The October release has some color issues.
Try the latest nightly or older release.
I don't understand what you mean by `from the last (2021.6.10) to 2020`, since the September release (that means still 2023) works as well.
And don't forget to try the default configuration.

Screenshot of the latest nightly built on 13 Dec.
![cisco_nightly](https://github.com/joncampbell123/dosbox-x/assets/68574602/88bc1063-edb8-4120-b5ba-df691f6d3af1)

2023.09.01 release
![cisco_0901](https://github.com/joncampbell123/dosbox-x/assets/68574602/3a4b90d0-1bb0-4461-a31a-43007d7a3599)

**Comment by FloLore** [comment]
I don't understand, it s bug here, black screen, i trying just now with the conf "dosbox-x.reference.full.conf" default...

**Comment by maron2000** [comment]
I already told you above to `Try the latest nightly or older release.`
Your screenshot is 2023.10.06 release, isn't it?

**Comment by FloLore** [comment]
sorry i haven't seen... i try the nightly now, but i had trying older before, till 2020...

**Comment by FloLore** [comment]
In lastest release, there are the 7 october only, and i can't compiled the last in source, so we must wait...

**Comment by maron2000** [comment]
If it doesn't work, I think you screwed up the DOSBox-X settings.
Try the default setting. `dosbox-x -defaultconf`

Latest release never changes until the next dated one is released.
Nightly is found here.
![289731835-ddfe85c6-33d1-4dbd-9703-449b10b49aff](https://github.com/joncampbell123/dosbox-x/assets/68574602/300ce287-2615-42b6-a012-10c6a01f3af2)

**Comment by FloLore** [comment]
Thank you so much, for your help and patience, forgiven me for my english, it isn't my natural language... the issue is resolved with this nighly version !

**Comment by maron2000** [comment]
No need to apologize!
Happy to hear it worked.
