### ISSUE TITLE
Openglpp and scaling in fullscreen mode on Debian 12

### ISSUE THREAD

**Issue by vitmich** [joncampbell123/dosbox-x#4676]
### Question

Hello everyone,
I would like ask you about Openglpp and scaling in fullscreen mode on Debian 12.
I'm using latest flatpak version of DOSBox-X (2023.10.06). 
When I'm using DOSBox-X in fullscreen mode with output: Openglpp and doublescan disabled everything looks fine in game and screen is scaled but not in console. Console seems not be scaled in fullscreen mode and it looks like it's on default resolution which is very low. It's looking strange for me. For example in DOSBox staging I can get perfectly scaled console in full screen mode with pixel perfect by default. Why I can't get the same in DOSBox-X? Is it a bug or a feature? I'm not reporting this as bug because maybe it's normal behaviour by design.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Not Debian, but Pixel perfect output is stretched on both graphics (game) and text (command prompt) screen here on Windows SDL1/SDL2 version.
Of course no blurry pixels.

**Comment by vitmich** [comment]
> Not Debian, but Pixel perfect output is stretched on both graphics (game) and text (command prompt) screen here on Windows SDL1/SDL2 version. Of course no blurry pixels.
> 
> Edit: Confirmed on ArchLinux, the screen is also scaled in a pixel perfect manner. Edit2: MacOS Ventura both graphics and text screen scales as expected.

Thank you for confirmation. I'm not using KDE or GNOME but Fluxbox only. So maybe it's something in my OS.

**Comment by maron2000** [comment]
Or maybe the Flatpak's sandbox environment?
Not for sure but hoping we can track the problem down by someone else trying pixel perfect option.

**Comment by vitmich** [comment]
Hi. I just made a fresh instalki of linux Mint 21.2.
Same problem on openglpp - console on full screen not scaled. Other output methods OK.

**Comment by vitmich** [comment]
Thank you maron2000 but I just reported this as bug. Maybe someone can reproduce this behaviour.

**Comment by vitmich** [comment]
Problem
