### ISSUE TITLE
PC-98 Mouse emulation issues

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#4680]
### Describe the bug

When the Falcom Character CG app is run, two different types of issues happen, depending on the mouse driver used.

Case-1: If dosbox-x  boots its own internal HDD and uses its own mouse driver:

- The mouse coordinates are shown correctly at the status line
- But the mouse pointer is invisible
- Mouse button clicks are not registered at all

Case-2: If dosbox-x boots from the floppy disk image and uses the MS-DOS 3.10 and supplied MOUSE.SYS driver:

- The mouse coordinates don't work correctly. The mouse pointer just stays stationary.
- The mouse pointer is now visible
- Mouse button clicks are registered

Note: I tested the case-2 with the Neko Project II emulator, and the mouse worked just fine.

[Falcom Character CG [PC98].zip](https://github.com/joncampbell123/dosbox-x/files/13693703/Falcom.Character.CG.PC98.zip)

### Steps to reproduce the behaviour

Case-1: Internal mouse driver
1. Boot dosbox-x in PC-98 mode without any floppy disks
2. Insert FCCG_SYS.FDI on drive A:
3. On the DOS prompt, type the following commands:
```
A:
FPG
```

Case-2: MS-DOS 3.10 and its MOUSE.SYS driver
1. Boot dosbox-x in PC-98 mode
2. Select the menu option Drive->A->Boot from disk image 
3. Select the FCCG_SYS.FDI disk image
4. Press ENTER when the date and time is requested
5. On the DOS prompt, type the following command:
```
FPG
```

### Expected behavior

The mouse should work correctly on both cases: 

- The mouse pointer should be displayed
- The mouse coordinates should move accordingly
- The mouse button clicks should be correctly registered

### What operating system(s) this bug have occurred on?

macOS 12.7.1

### What version(s) of DOSBox-X have this bug?

https://github.com/joncampbell123/dosbox-x/actions/runs/7191033384

### Used configuration

```ini
Default configuration file, with only machine=pc98 changed.
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
At least booted MS-DOS seems to work.
Are you sure that you enabled mouse capture?
DOSBox-X requires to capture mouse as well as np2 forks, you can find it in the `Main` dropdown menu and its shortcut key.

Without booting, it seems there is a problem with the mouse driver, and need to use a external driver dedicated for PC-98.
I tried this one, but maybe NEC genuine MOUSE.COM may work. https://www.vector.co.jp/soft/dl/dos/util/se015186.html
However, I see some glitches in the text screen.
![falcomcg](https://github.com/joncampbell123/dosbox-x/assets/68574602/5899cfd0-4c42-44a9-b765-11c321840c36)

**Comment by sdsnatcher** [comment]
> At least booted MS-DOS seems to work.
> Are you sure that you enabled mouse capture?

I wasn't aware that it needed to be captured. Then it worked when booting the MS-DOS. Thanks for the tip!

> Without booting, it seems there is a problem with the mouse driver, and need to use a external driver dedicated for PC-98

Following this tip, I went after mouse drivers for the PC-98. I tested himouse, ozmouse, gsmdv and even found [the original Microsoft mouse driver for the PC-98](https://www.vector.co.jp/soft/dl/maker/ms/se010626.html).

- himouse is the one that works better, but with the text glitches on menus like you mentioned
- ozmouse behaves just like the dosbox-x built-in mouse driver
- gsmdv freezes the emulated pc-98 when installed
- Microsoft mouse driver shows a mouse pointer that clearly has inverted colors. The mouse buttons don't respond. If I use ENTER/ESC instead of the mouse buttons, I can "click" on the menus. Then the menu text show glitches identical to the ones that happen with himouse.

**Comment by nanshiki** [comment]
Try incorporating the MOUSE.SYS that exists in FCCG_SYS.FDI with the device command.
\> device mouse.sys

The reason why the coordinates are displayed in the wrong place may be due to the PC-98 specific behavior that the text is displayed in the lower right corner of the screen but does not scroll.
This should be fixed in #4700.

**Comment by sdsnatcher** [comment]
Using the DEVICE.COM command to load the MOUSE.SYS did function as a workaround, thanks! I wasn't aware of this command. 

The root of the problem seems to be that there are two different mouse APIs for the PC-98: one by NEC and another by Microsoft, but dosbox-x built-in mouse driver seems to support only the Microsoft API.

**Comment by joncampbell123** [comment]
> Using the DEVICE.COM command to load the MOUSE.SYS did function as a workaround, thanks! I wasn't aware of this command. 
> 
> The root of the problem seems to be that there are two different mouse APIs for the PC-98: one by NEC and another by Microsoft, but dosbox-x built-in mouse driver seems to support only the Microsoft API.
> 
> 

Is the NEC API documented anywhere? Perhaps DOSBox-X should implement it.

**Comment by maron2000** [comment]
Explanation of NEC API should be included in the MS-DOS Programmer's Reference manual.
Maybe I can find it in my bookshelf but not sure.

**Comment by nanshiki** [comment]
In the case of the NEC version of MOUSE.SYS, the cursor is drawn in only one plane and is displayed using XOR without masking.
The cursor size is also large (16x32).
![cursor](https://github.com/joncampbell123/dosbox-x/assets/42603716/2b16b0ec-06e3-4930-aed0-09e01faae754)
You can see that the green monochromatic area overlapping with the background graphic is inverted.
Also, there are various button-related differences with int 33h.
I found this in the PC-9801 Programmer's Bible, so I extracted only the parts that differ from the Microsoft version and converted them to text.
[mousej.txt](https://github.com/joncampbell123/dosbox-x/files/13765085/mousej.txt)
The translated version is also available.
[mousee.txt](https://github.com/joncampbell123/dosbox-x/files/13765087/mousee.txt)

**Comment by nanshiki** [comment]
@sdsnatcher 
Supported by #4712.
In [pc98] of dosbox-x.conf
pc-98 nec mouse function=true
Add the following.
Or on command line.
\> pc98util /nec
Set in NEC mouse function.

In addition,
\> pc98util /ms
Set the Microsoft mouse function.

**Comment by sdsnatcher** [comment]
@nanshiki 

This worked perfectly, thank you!
