### ISSUE TITLE
"intro special" is no effect

### ISSUE THREAD

**Issue by leoxxx** [joncampbell123/dosbox-x#4683]
### Describe the bug

Input "intro special",it's the same as "intro".  I test some "intro *", such as "intro a", "intro 2", it's also the same as "intro". But "intro mount", "intro cdrom" & "intro usage" are O.K. 
0.82.17 is O.K.

### Steps to reproduce the behaviour

Input "intro special", then goto "intro".

### Expected behavior

"intro special" goto special key page, as 0.82.17.

### What operating system(s) this bug have occurred on?

Windows 10 pro 22H2 64bit 

### What version(s) of DOSBox-X have this bug?

since DOSBox-X beta 0.82.18 2019-04-14 20:28

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
The command option was intentionally removed due to out-dated information.
You can check the Wiki or the dropdown menus for combination of shortcuts.

**Comment by leoxxx** [comment]
@joncampbell123 
If is's not a bug, please remove "intro special" from information.
