### ISSUE TITLE
No longer working: dim top line when DOSBox-X does not have focus

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#4686]
### Describe the bug

Per [this previous post](https://github.com/joncampbell123/dosbox-x/pull/3331), when using DOSBox-X in full-screen TTF mode, the top line of the screen used to dim when DOSBox-X did not have focus, a very useful feature on multiple-monitor setups.

As of 2023.10.06, both the 32-bit SDL1 and 64-bit SDL1 versions have lost this functionality.

Could this be reinstated, please? Thank you!

### Steps to reproduce the behaviour

Open DOSBox-X in TTF mode on one monitor and go to full screen mode. Take the focus away from DOSBox-X by activating an app on a second monitor. Note that the top line of the DOSBox-X no longer dims to show that focus has been lost.

### Expected behavior

The top line should dim, as it used to in previous versions.

### What operating system(s) this bug have occurred on?

Windows 11 Home 64 bit; also Windows 7 Pro 32-bit

### What version(s) of DOSBox-X have this bug?

DOSBox-X version 2023.10.016 SDL1, both 32-bit and 64-bit

### Used configuration

```ini
fullscreen        = true
fulldouble        = false
fullresolution    = desktop
windowresolution  = desktop
windowposition    = 0,0
display           = 0
output            = ttf
videodriver       =
transparency      = 0
maximize          = fullscreen
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I can't test it myself, but you can try this one and see if it works.
https://github.com/maron2000/dosbox-x-1/actions/runs/7259173379

**Comment by RobertJSawyer** [comment]
Hello, @maron2000. I must be daft, but I can't find anywhere on the page you linked to to download a test version:

[https://github.com/maron2000/dosbox-x-1/actions/runs/7259173379](https://github.com/maron2000/dosbox-x-1/actions/runs/7259173379)

I'm not a programmer, so I can't compile code. What file should I download to test this?

Many, many thanks! And my apologies for being so thick!

All best wishes.

Rob

**Comment by maron2000** [comment]
I see it on the bottom of the page built successfully.
I hpoe I'm not the only.one who can see it, but I might have to find another way for you to download.

**Comment by RobertJSawyer** [comment]
Thank you, my friend! You have indeed fixed the dimming of the top line when the DOSBox-X session is not in focus; that functionality has been restored.

BUT (there's always a but, isn't there?) screen updating is now messed up when switching to and from a DOSBox-X window. You don't need a dual-monitor display to test this. Just start a DOSBox-X session with your new build and also have some other Windows program or another DOSBox-X session running on the same monitor. Then flip back and forth between them with <ALT><TAB> and  you should see that the DOSBox-X screen does not restore properly when brought back into focus. The problem becomes particularly obvious when you move the mouse and the screen repaints in the wake of its movement

I've tested this now on three different Windows 7 32-bit systems with both single and multiple monitors. 

The screen capture attached shows two DOSBox-X sessions, one with a white background and one with a black one, and the mess that now occurs when flipping between them and then moving the mouse.

Many, many thanks for all your help, my friend!

Rob
![DOSBox-X Screen refresh](https://github.com/joncampbell123/dosbox-x/assets/14101897/58ec5116-47c2-49f2-834f-01e3803d318e)

**Comment by RobertJSawyer** [comment]
Thank
![DOSBox-X Screen refresh](https://github.com/joncampbell123/dosbox-x/assets/14101897/14f5979c-2904-45d1-9d5b-6ec5226e8fba)
 you, my friend! You have indeed fixed the dimming of the top line when the DOSBox-X session is not in focus; that functionality has been restored.

BUT (there's always a but, isn't there?) screen updating is now messed up when switching to and from a DOSBox-X window. You don't need a dual-monitor display to test this. Just start a DOSBox-X session with your new build and also have some other Windows program or another DOSBox-X session running on the same monitor. Then flip back and forth between them with and you should see that the DOSBox-X screen does not restore properly when brought back into focus. The problem becomes particularly obvious when you move the mouse and the screen repaints in the wake of its movement

I've tested this now on three different Windows 7 32-bit systems with both single and multiple monitors.

The screen capture attached shows two DOSBox-X sessions, one with a white background and one with a black one, and the mess that now occurs when flipping between them and then moving the mouse.

Many, many thanks for all your help, my friend!

Rob

**Comment by maron2000** [comment]
Thank you for trying, and at least we got a step forward but some regressions.
Maybe one version old may work better.

Download is available in the Artifact section of the following link.
https://github.com/maron2000/dosbox-x-1/actions/runs/7257743512

**Comment by RobertJSawyer** [comment]
You're the best, @maron2000! 

7257743512 works fine: the top line dims when not in focus, and switching between DOSBox-x and other applications or other instances of DOSBox-X seems to restore the screen just fine.

THANK YOU!

Rob

**Comment by maron2000** [comment]
Thanks for testing and promptly responding.
I'll clean up the fixed code and make a PR, which will hopefully be included in the coming release.
