### ISSUE TITLE
Screamer 2 Glide Emulation (glide=true) Graphics Corruption

### ISSUE THREAD

**Issue by drholr** [joncampbell123/dosbox-x#4688]
### Describe the bug

Hi, I think this issue is less to do with dosbox-x per se, but seems to be related to the interlacing issue described here: https://www.philscomputerlab.com/screamer-2--bleifuss.html , specifically with glide2x.ovl.

When I use dosbox-x with glide=true for glide passthrough with dosbox-x, I see image corruption when playing Screamer 2 (s2_3dfx.exe). Its like the bitmaps are corrupted, though the polygons in the game are fine, and much higher fps than with the voodoo emulation. In the above link, the issue is solved on real hardware  by replacing the original glide2x.ovl. I don't think this is possible in this case, as glide2x.ovl is a special file on dosbox-x's Z: and is specially created for the glide passthrough.

Any thoughts on how to tackle this graphical corruption?

### Steps to reproduce the behaviour

Enable glide=true
Install nglide / dgvoodoo2 etc. on Windows, or openglide on Linux.
Install Screamer 2
Install the voodoo 2 patch s2_3dfx from https://www.philscomputerlab.com/screamer-2--bleifuss.html (NOT s23dfx)
Launch s2_3dfx.exe

### What operating system(s) this bug have occurred on?

Windows 10, Linux (Steam Deck / SteamOS tested)

### What version(s) of DOSBox-X have this bug?

2023.10.06 32bit

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
You can elaborate what you say by graphic corruption like attaching a screenshot we can have some idea.
If the graphics are okay but colors are strange, trying the latest nightly might help.

**Comment by drholr** [comment]
Sorry -absolutely. first, what one expects 9taken with voodoo low-level, i.e. glide=false.
![20231219195314_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/7538a8bb-b201-4998-8b19-7a0dc671a604)
![20231219195300_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/b35d7dc3-9649-4ccc-89be-efb81cd670b3)
![20231219195221_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/e55fba2c-6cd8-4e11-b345-faa2f641ec5e)
![20231219195138_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/28a5b71c-7864-465c-85a1-abbb57f47e7f)

**Comment by drholr** [comment]
Now with glide=true:
![20231219202454_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/84c41641-3fe7-441f-9f54-b164c99e7e05)
![20231219202429_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/79844013-4ab1-44e4-a48c-21cbf84516fe)
![20231219202420_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/24b1baf7-c4a2-49a3-9b33-6eda5e2c51e2)
![20231219202410_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/6f447129-6c03-4387-84a4-490157a9037c)
![20231219202401_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/cac121bb-3de9-4259-9612-a4a17bbd259c)
![20231219202353_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/711121bb-6483-4920-a8d2-1b439f710c83)
![20231219202332_1](https://github.com/joncampbell123/dosbox-x/assets/75488291/bec06d2c-81d3-4dd2-8c48-43a453cf2a7e)

**Comment by drholr** [comment]
Aha - seems like user error on my part. I used lfb write_noaux which, sped up glide emulation, but caused the corruption shown above. When i changed it to lfb full_noaux, the graphics were as expected (albeit fewer fps). Closing!
