### ISSUE TITLE
bug with overflow flag in shl

### ISSUE THREAD

**Issue by martinlindhe** [joncampbell123/dosbox-x#469]
I think I found a bug in the shl instructions as implemented in dosbox-x.

Consider the following:

```asm
mov ax, 0
push ax
popf                    ; clear flags
mov ah,0xff
shl ah,byte 0xff
```
results in the following EFLAG:

    win-xp:    3046 = 0b11_0000_0100_0110
    dosbox-x:  0856 =    0b1000_0101_0110

The overflow flag is set when executing the above code in dosbox-x, but it is not set when run under Windows XP.

Also, according to cpu docs, aux flag is undefined by shl instruction, but is being set in dosbox-x.

The same issue on 16-bit shl:

```asm
mov ax, 0
push ax
popf                    ; clear flags
mov ax,0xffff
shl ax,byte 0xff
```

results in the same EFLAG as above.

The implementation in bochs looks to be correct, and follows the behavior seen in windows xp.

The bochs implementation can be seen at https://sourceforge.net/p/bochs/code/HEAD/tree/trunk/bochs/cpu/shift8.cc
starting at line 327
relevant snippet:

```cpp
result_8 = (op1_8 << count);
cf = (op1_8 >> (8 - count)) & 0x1;
of = cf ^ (result_8 >> 7);
```

From intel docs:

> The OF flag is affected only on 1-bit shifts. For left shifts, the OF flag is set to 0 if the most-significant bit of the result is the same as the CF flag (that is, the top two bits of the original operand were the same); otherwise, it is set to 1.

**Comment by joncampbell123** [comment]
I see.

A shift count of 0xFF on any x86 processor since the 8086 would be treated as a shift of 0x1F bits.

0xFF << 0xFF = 0xFF << 0x1F == 0x00

CF = should be zero
OF = should be zero because (bit 7) XOR (CF) == 0 XOR 0 == 0

Then there is this reference that says OF is only affected if the shift count is 1 bit (which doesn't seem right). https://c9x.me/x86/html/file_module_x86_id_285.html

**Comment by joncampbell123** [comment]
I changed the code in FillFlags() to reflect the reported behavior. Before I commit, I will run the asm sequence given on an old Intel 486 laptop to confirm the behavior.

**Comment by joncampbell123** [comment]
I see the behavior as documented occurring on an old 486 50MHz laptop, and I checked the changes behave the same, so I will commit the changes.

**Comment by joncampbell123** [comment]
Done.

**Comment by martinlindhe** [comment]
Nice work!

**Comment by joncampbell123** [comment]
Interesting discovery: Just found a PC-98 game who's graphic display routines depend on this SHL behavior.

I don't remember explicitly fixing the graphics issues with APPARE.EXE, but the SHL bugfix seems to have fixed the graphics. https://github.com/joncampbell123/dosbox-x/issues/340

![orfield_000](https://user-images.githubusercontent.com/6245486/35708118-758eb2c4-0761-11e8-9110-1cdeda131839.png)

**Comment by martinlindhe** [comment]
Now that's really cool!
