### ISSUE TITLE
DOSBox-X not scaled in openglpp in Debian 12 and Mint 21.2

### ISSUE THREAD

**Issue by vitmich** [joncampbell123/dosbox-x#4692]
### Describe the bug

Hello,

DOSBox-X console (prompt) is not scaled in openglpp output in Debian 12 and in Mint 21.2 both in maximized window and in fullscreen mode but after running game screen is scaled properly.
 
![Screenshot_2023-12-20_16-40-09](https://github.com/joncampbell123/dosbox-x/assets/10966761/44802f54-1d61-4aaf-a0b2-e3d7d74417bd)

### Steps to reproduce the behaviour

1. Open your "dosbox-x-2023.10.06.conf" file
2. Change "output = default" to "output = openglpp"
3. Change "aspect = false" to "aspect = true"
4.  Change "doublescan = true" to "doublescan = false"
5. Save and run DOSBox-X

### Expected behavior

Pixel perfect scaled console (prompt) in maximized window and in fullscreen mode

### What operating system(s) this bug have occurred on?

Debian 12, Mint 21.2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2023.10.06 (flathub version)

### Used configuration

```ini
Check additional information
```

### Output log

```text
Check additional information
```

### Additional information

[dosbox-x-2023.10.06.conf.txt](https://github.com/joncampbell123/dosbox-x/files/13730147/dosbox-x-2023.10.06.conf.txt)
[logi.txt](https://github.com/joncampbell123/dosbox-x/files/13730149/logi.txt)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
The width of your monitor is too small. You need 1440 but you have only 1280.
This is a expected behaviour, and any OS will not scale unless you use a bigger resolution monitor or try `char9=false`.

Games usally use 320 or 640 pixel width so it works with your 1280 width.

The following is your log, it has many useful information.
```
LOG: OpenGL PP: [1280x939]: 720x400 (1.35) -> [1x1] -> 720x400 (1.00)
LOG: X11 main window is 1280 x 973 maximized=1
```

**Comment by vitmich** [comment]
Holy cow. You are right. I just checked this on 1920x1200 monitor....and console is scaled properly both in maximized windows and fullscreen mode. So I have to use bigger screen. Thanks for checking my logs! I will close this issue.
