### ISSUE TITLE
Heroes of Might and Magic SETUP only shows black screen

### ISSUE THREAD

**Issue by brakenwagen** [joncampbell123/dosbox-x#4702]
### Describe the bug

when i try to use the SETUP program for Heroes of Might and Magic called INSTALL.EXE it only shows a black screen. this does not happen on regular dosbox. I was able to figure out that the setup program is running it just shows a black screen. but even when you hit escape to exit the program the black screen remains until you restart dosbox-x.   

### Steps to reproduce the behaviour

try to run Heroes of Might and Magic INSTALL.EXE

### Expected behavior

for the setup program to display

### What operating system(s) this bug have occurred on?

Win 10

### What version(s) of DOSBox-X have this bug?

dosbox-x-mingw-win32-20231007055223 sdl2

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by tazok81** [comment]
This is the same bug like was reported here:

https://github.com/joncampbell123/dosbox-x/issues/4581

Change cycles to number

**Comment by joncampbell123** [comment]
There are multiple versions of this game, which one? Out of One through Six?

**Comment by tazok81** [comment]
[heroes1.zip](https://github.com/joncampbell123/dosbox-x/files/14395704/heroes1.zip)
I think he talked about this version. I noticed the same. But swithing to gog version fixed the problem.

**Comment by joncampbell123** [comment]
Why is SETUP.EXE scanning all adapter memory backwards from 0xE8000000 byte by byte?

And then it fiddles with the voodoo 3Dfx card and crashes?

If I disable voodoo 3Dfx emulation it just scans all the way backwards to system RAM?

What the fuck is their setup program trying to do?

**Comment by joncampbell123** [comment]
All I see SETUP.EXE do is make some INT 15h calls and then read every single memory address from 0xE8000000 byte by byte backwards all the way to 0x0000000 and then segment limit crash and halt in the BIOS.

**Comment by joncampbell123** [comment]
This seems like a case of the program doing something internally, then eventually corrupting itself in memory and running in an infinite loop executing the junk corrupted instructions.

**Comment by joncampbell123** [comment]
It's not anti-debugger self-modifying prefetch queue trickery, which you can often get working with cputype=486_prefetch

**Comment by maron2000** [comment]
I think SETUP.EXE included in [heroes1.zip](https://github.com/joncampbell123/dosbox-x/files/14395704/heroes1.zip) is corrupted.
It didn't work on dosbox-staging 0.81.0 as well.

I copied INSTALL.EXE from the installation CD and it worked like a charm on the latest nightly as of 25th Feb.
Pretty confusing, since there was no such file as SETUP.EXE in the CD, and also the guy who originally posted this issue mentions INSTALL.EXE, not SETUP.EXE.

![heroes1](https://github.com/joncampbell123/dosbox-x/assets/68574602/935e4524-a630-4c20-9891-9334e0c5e645)

**Comment by tazok81** [comment]
This version is ripped. I believe that the guy who did it made this bug decades ago. This version is from some website and I believe author of this topic has it from there too. And i believe setup.exe/install.exe difference is only coincidence.

**Comment by joncampbell123** [comment]
Got it.
