### ISSUE TITLE
Directserial on Windows does not work

### ISSUE THREAD

**Issue by armctec** [joncampbell123/dosbox-x#471]
I can use it normally in official DosBox, but this one does not work. Using the line "serial1 = directserial realport: com1", the DosBox-X log returns "LOG: Invalid type for serial1".
Analyzing the source code, I verified that there is a #ifdef DIRECTSERIAL_AVAILIBLE, in the serialport.cpp file, I believe it should be disabled in the windows version.
Is it possible to be enabled? The original version works the same as DosBox-SVN, but DosBox-X has many more features than the others.

**Comment by joncampbell123** [comment]
Let me do a quick compile with it enabled, I don't see any reason it shouldn't work...

**Comment by joncampbell123** [comment]
Code compiles OK if I enable DIRECTSERIAL_AVAILABLE. I just pushed a change to enable that. Can you compile it with VS2015?

**Comment by joncampbell123** [comment]
I want to clarify the changes are in the "develop" branch, not the master branch.

**Comment by armctec** [comment]
I do not have VS2015, but I'm waiting when you upgrade to a new version, without haste

**Comment by joncampbell123** [comment]
I have VS2017, but the project files were made with VS2015.

**Comment by joncampbell123** [comment]
I'll just throw up a quick binary in the release section and call it beta. I was able to compile with directserial, directlpt and modem emulation enabled.

**Comment by joncampbell123** [comment]
Try this:

https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-20180131-0914

**Comment by armctec** [comment]
Works fine!!! thanks!!!

**Comment by joncampbell123** [comment]
No problem!
