### ISSUE TITLE
X-COM hangs after intro movie

### ISSUE THREAD

**Issue by caiiiycuk** [joncampbell123/dosbox-x#4713]
### Describe the bug

Players reported that x-com hangs after intro movie, I bisected master and found first bad commit 042d05ff44a55aa13620dc16ed916b3477073471 :

```
042d05ff44a55aa13620dc16ed916b3477073471 is the first bad commit 
commit 042d05ff44a55aa13620dc16ed916b3477073471
Author: Jonathan Campbell <jonathan@castus.tv>
Date:   Wed May 3 23:19:52 2023 -0700

    Revert DOS date/time to use cache DOS kernel copy for date and BIOS ticks for time to match what real MS-DOS does. Initialize time and date by RTC clock on startup. Revise CMOS emulation to run in emulator time, not real time

 CHANGELOG             |   7 +-
 src/dos/dos.cpp       |  75 +++++++++-----
 src/gui/sdlmain.cpp   |   4 +
 src/hardware/cmos.cpp | 279 +++++++++++++-------------------------------------
 src/ints/bios.cpp     |  26 ++++-
 5 files changed, 153 insertions(+), 238 deletions(-)
```

### Steps to reproduce the behaviour

[xcom.zip](https://github.com/joncampbell123/dosbox-x/files/13779470/xcom.zip)
1. Unzip archive
2. cd to xcom folder
3. run `dosbox-x --conf .jsdos/dosbox.conf`

### Expected behavior

Game start after movie

### What operating system(s) this bug have occurred on?

Ubuntu 22.04 x86 / Browser

### What version(s) of DOSBox-X have this bug?

latest

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Actually, if you switch to Turbo mode when the screen is blanked, you can go ahead to play the game.
Just an workaround though.

**Comment by tazok81** [comment]
Duplicite to #4581 
Issue is in core function.

**Comment by caiiiycuk** [comment]
Actually, in my case, DOSBox-X freezes frequently, particularly when I try to install something using InstallShield. However, I'm not sure whether it's a DOSBox-X bug or an issue with my JS-DOS fork. Regardless, I'm closing this as a duplicate.
