### ISSUE TITLE
Screen Refresh Extremely Slow

### ISSUE THREAD

**Issue by ezathashim** [joncampbell123/dosbox-x#4714]
### Describe the bug

I have a slightly different question, but maybe it is related to this current work.

My DOS app is a very simple accounting program. To get it turn run, I have to configure DOSBox with 'A20 = off'. If I do not do this, DOSBox is unable to open the file archives for the DOS app.

The issue I am having is that the screen refresh is extremely slow. Here is a video with me moving the cursor up and down:

![CleanShot 2023-12-27 at 10 11 52](https://github.com/joncampbell123/dosbox-x/assets/5372535/6caf56e0-1893-4a0a-bee0-ccd6cc272e42)

Would you know what there is such an unbearable lag? The lag is also present when trying to input text, rendering it very difficult to use. Previous versions of DOSBox did not have this, but I'm unsure of the version when this began.

Any ideas? I have played with some configurations but my efforts did not improve anything.

### Steps to reproduce the behaviour

- you would need a copy of my DOS program to test this

### Expected behavior

- relatively lag-free refresh and responsiveness

### What operating system(s) this bug have occurred on?

macOS 14 (Sonoma) on M1

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Used configuration

```ini
a20 = off
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
have you tried increasing the `cycles=` value? It is only at 3000 in your screenshot.

**Comment by ezathashim** [comment]
Yes, it seems to allow more responsive cursor movement, the the laggy screen remains. I tried it at 30000 and at max.

**Comment by rderooy** [comment]
Perhaps it is trying to read records from disk, dosbox-x by default introduces a delay which is needed for some games. Try to disable it.

```
[dos]
hard drive data rate limit = 0
```

**Comment by ezathashim** [comment]
No change with this setting.

**Comment by maron2000** [comment]
Try setting `dos idle api=false` in the conf file.

**Comment by ezathashim** [comment]
That worked! Many thanks!

- Ezat

**Comment by maron2000** [comment]
Good to hear that it worked.
You may want to change the title of this issue to include the name of the software so that others can recognize without digging in to this issue.
And of course, don't forget to close this since it is solved.

**Comment by ezathashim** [comment]
done - thanks!
