### ISSUE TITLE
Support for hdm disk images

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#4728]
### Is your feature request related to a problem? Please describe.

A lot of PC-98 software is available in hdm (BKDSK) floppy disk format, but dosbox-x doesn't support it.

### What you want

Please add support for the hdm (BKDSK) disk format.

### Describe alternatives you've considered

The only workaround right now is to convert the disk image to .fdi, but that doesn't always work.

### Additional information

Flashfloppy [seems to have hdm disk image support](https://github.com/keirf/FlashFloppy/issues/198) and could be used as a reference.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I dumped a NEC MS-DOS 6.2 install disk to BKDSK ("べた" in Japanese) format, and tried mounting from both dropdown menu and `IMGMOUNT` command.
Both seems working good. You may want to clarify in what case you say not working.

![hdm_mount](https://github.com/joncampbell123/dosbox-x/assets/68574602/b86ee5f3-794b-4f93-965c-95805d418f25)
![hdm_mount2](https://github.com/joncampbell123/dosbox-x/assets/68574602/cb76e03d-b13c-411b-a31b-bf365607ff56)
![hdm_mount3](https://github.com/joncampbell123/dosbox-x/assets/68574602/6499558e-f575-474d-bc17-2d8790cd8150)
![hdm_mount4](https://github.com/joncampbell123/dosbox-x/assets/68574602/c429a947-d19b-495d-bb95-bab10aa95c68)

**Comment by sdsnatcher** [comment]
Humm, ok. It indeed worked when using imgmount.exe and boot.exe.

This means that the problem is on the macOS GUI interface. It doesn't recognize the .hdm extension as disk images either to mount or to boot.  I (wrongly) assumed then that there was no support.

**Comment by maron2000** [comment]
Just rename the hdm to img. It should not be a pain to do so.

**Comment by sdsnatcher** [comment]
> Just rename the hdm to img. It should not be a pain to do so.

It was one of the first things I tried, but doesn't work.  It definitely would be nice if it also recognized the .dmg extension.

**Comment by sdsnatcher** [comment]
> Just rename the hdm to img. It should not be a pain to do so.

That also doesn't work. It complains that "Drive A: failed to mount."

**Comment by maron2000** [comment]
That's strange. I can't test on macOS right now, but at least on Windows it works flawlessly by renaming the hdm file to img.
Make sure that the image is not opened on another instance.

![hdm_to_img](https://github.com/joncampbell123/dosbox-x/assets/68574602/f2b40254-6f00-4e48-9e15-922a9f0fc909)

**Comment by sdsnatcher** [comment]
I'm beginning to suspect that the problem might be related to dôjinshi software that could be run on both the PC-98 and X68000 (sometimes even on the FM-Towns too).

I've seen two types of such software in the wild:

1) The simpler ones that have a standard boot sector for a specific computer family, and the instruction leaflet said to boot from another disk on the listed computer families, then insert the disk and run some batch file manually (usually AUTOEXEC.BAT)

2) The more elaborated ones featured a custom boot sector that detected the type of machine and launched the respective operating system accordingly. Those are much rarer.

Here's an example of a dôjinshi software of the type (1) that dosbox-x can't mount even if I rename the extension to .img:

[XCG Vol. 2 [FD].zip](https://github.com/joncampbell123/dosbox-x/files/13854575/XCG.Vol.2.FD.zip)

**Comment by maron2000** [comment]
You cannot mount a drive that is not FAT formatted.
Such as N-88 BASIC disks.

**Comment by sdsnatcher** [comment]
> You cannot mount a drive that is not FAT formatted. 

But the "XCG Vol. 2.hdm" above is FAT formatted. The Human68k DOS uses FAT as a filesystem just like MS-DOS.

I tested it on NekoProject II emulator and the PC-98 MS-DOS could read it's files normally. Booted it with MS-DOS 6.2 on drive A: and "XCG Vol. 2.hdm" on drive B:.

**Comment by maron2000** [comment]
OK. You can provide some information about Human68k floppy IPL, so that we can seek to make a fix.

**Comment by sdsnatcher** [comment]
You mean the BPB?  The Aaru project seems to be a nice source of information for all BPB variations that dosbos-x might need to mount Japanese floppy disks, including the Human68K and MSX.  More specifically, [here](https://github.com/aaru-dps/Aaru/blob/devel/Aaru.Filesystems/FAT/BPB.cs).
