### ISSUE TITLE
CPU test failed with betrayal in Antara

### ISSUE THREAD

**Issue by AITUS95** [joncampbell123/dosbox-x#4731]
### Describe the bug

I'm running Windows 3.11 on DOSBox-X with a mounted folder, so I'm trying to install Betrayal in Antara via disk. I have to skip the CPU test to avoid getting the 'integer divide by 0' error, even though all other tests pass without issues. I've tried using a lower cycle, but it yields the same results.

![krnl386_000](https://github.com/joncampbell123/dosbox-x/assets/48457684/6ee8e4a3-b8a8-4184-a0ff-c0c589fbe649)
![krnl386_002](https://github.com/joncampbell123/dosbox-x/assets/48457684/eac35a79-1872-43e0-8614-ebffc10ad493)

### Steps to reproduce the behaviour

1. Start Windows 3.11 in a mounted folder using DOSBox-X with the Windows 3.11.conf configuration file. 
2. Begin the installation of Betrayal in Antara via disk. 
3. Go through the steps to perform the tests. 
5. The installation returns an error in the CPU test."

### What operating system(s) this bug have occurred on?

Windows 10 pro x64 22H2

### What version(s) of DOSBox-X have this bug?

v.2023.10.06 Visual Studio SDL1 64-bit

### Used configuration

```ini
[sdl]
autolock=true

[dosbox]
title=Windows 3.1x
memsize=256

[dos]
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium
core=normal

[pci]
voodoo=false

[ide, primary]
int13fakeio=true
int13fakev86io=false

[render]
scaler=none

[autoexec]
@ECHO OFF
IMGMOUNT D "E:\DISCHI PC\Betrayal in Antara (Europe) (Disc 1)\Betrayal in Antara (Europe) (Disc 1).cue"
MOUNT C WIN31
C:
IF EXIST C:\WINDOWS\IFSHLP.SYS GOTO WFW
IF EXIST C:\WINDOWS\WIN.COM GOTO WINDOWS
ECHO No Windows installation found
GOTO END
:WFW
echo Starting Windows for Workgroups 3.1x
SET PATH=%PATH%;C:\WINDOWS;
SET TEMP=C:\WINDOWS\TEMP
DEVICE C:\WINDOWS\IFSHLP.SYS
C:\WINDOWS\NET.EXE START
C:\WINDOWS\WIN.COM
GOTO END
:WINDOWS
echo Starting Windows 3.1x
SET PATH=%PATH%;C:\WINDOWS;
SET TEMP=C:\WINDOWS\TEMP
C:\WINDOWS\WIN.COM
GOTO END
:END
EXIT
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Hm... I just realized IMGMOUNT has kind of a bug regarding CUE files (or maybe ones with spaces?)

.ISO files use the current working directory in the guest to resolve properly, .CUE files do not. So basically the relative path relative to the host current working directory must be explicitly given in IMGMOUNT, no matter the guest current working directory.

**Comment by joncampbell123** [comment]
No problems here, during the tests.

cycles=30000
cputype=pentium
core=normal
![krnl386_000](https://github.com/joncampbell123/dosbox-x/assets/6245486/6f7a973c-2e03-4548-897a-e83a447b5b4c)

**Comment by joncampbell123** [comment]
This is on x86_64 (64-bit) Linux, by the way.

**Comment by AITUS95** [comment]
What build are you using? I've tried different builds too, compiled with mingw, 32-bit, etc... but still getting the same error. It's happening even on a Windows 98 image, so I guess at this point I should try it on a Linux system instead of Windows.

**Comment by joncampbell123** [comment]
I am using the latest source code, try the nightly builds. Maybe 64-bit Windows should work as well. A lot has changed since the October 2023 release.

**Comment by AITUS95** [comment]
Awesome, with the latest build **(dosbox-x-mingw-x86_x64-20240224202329)**, the CPU test passes successfully. I'm curious though which build actually fixed this issue. Anyway, the bug has been sorted out.
