### ISSUE TITLE
The Terminator -  Future Shock No Audio In FMV Cutscenes

### ISSUE THREAD

**Issue by brakenwagen** [joncampbell123/dosbox-x#4738]
### Describe the bug

in terminator future shock when a cutscene plays there is no audio this dose not happen in regular dosbox.  

### Steps to reproduce the behaviour

play future shock and watch opening cutscene

### Expected behavior

for audio to play during fmv cutscene

### What operating system(s) this bug have occurred on?

Win 10

### What version(s) of DOSBox-X have this bug?

dosbox-x-mingw-win32-20231007055223 SDL2

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Related note: This game also seems to handle the Gravis Ultrasound badly when you click "test" in SETUP.EXE

**Comment by joncampbell123** [comment]
I'm able to get FMV audio working IF I turn off Gravis Ultrasound emulation and let it use the Sound Blaster emulation instead.

**Comment by joncampbell123** [comment]
Also when it comes to "MIDI" support this game has *terrible* support for the Gravis Ultrasound. It assumes port 220h and it *will not take any other value* and loading ULTRAMID doesn't help.

**Comment by joncampbell123** [comment]
It seems to be the best way to run this code is to set sbtype to sbpro2 to sb16 and set gus=false.

Unless it can be shown this game works properly with a GUS, I'm going to have to assume it's a case of crappy GUS support.

**Comment by joncampbell123** [comment]
I'm also aware some common libraries, especially in the Demoscene, can get a little confused if both ULTRASND and SBLASTER environment variables are present.

Before filing these issues:
- Try running the game's setup program and making sure the Sound Blaster or GUS I/O, IRQ, DMA settings match your dosbox.conf file. ISA Plug & Play wasn't a thing yet so the game generally depended on *you* during setup to tell it what sound card you had.
- Try setting gus=false to turn off Gravis Ultrasound emulation. Some games and/or demoscene executables just flat out have crap and crashy GUS drivers.
