### ISSUE TITLE
MotorMash strange color palette

### ISSUE THREAD

**Issue by Redysz** [joncampbell123/dosbox-x#4740]
### Describe the bug

The game motormash starts up with strange pink colors.

https://github.com/joncampbell123/dosbox-x/assets/25427869/3ef15533-5c4a-40f5-aa33-70e115e6c762

The game needed an additional d3drm.dll file - I uploaded from Windows 98 (Windows\System) as well as from the Internet (from the dll-files site) - in both cases it looks identical.

### Steps to reproduce the behaviour

1. Download the game from [here](https://www.old-games.com/download/6271/motor-mash)
2. Unpack it
3. Download missing dll file from [here](https://www.dll-files.com/d3drm.dll.html)
4. Run it with dosbox-x

### Expected behavior

Normal colors like [here](https://www.old-games.com/screenshot/6271-4-motor-mash.jpg)

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

2023.10.06 both SDL1 and SDL2

### Used configuration

```ini
Standard configuration (Lunch to run on the Windows host added)
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
The executable for DOS version is `motormbr.exe`, not the one you booted.
`motormsh.exe` is a Windows executable which cannot be run natively on DOSBox-X, and you can clearly see that from your captured video. (It launched it on your Windows 10 for you.)
You should ask the game maker for support to run motormsh.exe on Windows 10.

On the other hand, DOS version works flawlessly on DOSBox-X 10.06 release.
https://github.com/joncampbell123/dosbox-x/assets/68574602/87f9bc57-5bf9-4620-8997-0e0d35db1058

**Comment by Redysz** [comment]
@maron2000 Thank you. I misunderstood how Windows95-98 works (now read about it in wiki). Everything works great.
