### ISSUE TITLE
Cannot insert a disk image on a drive after a game is running

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#4741]
### Describe the bug

I'm trying to run Wrestle Angels 1 for the PC-98, but it requires the diskB to be inserted on the drive B: only after the game has booted.  The DOS and Drive menu options for inserting a new disk will be grayed out. It's only possible to replace a disk image from a drive that already has one inserted.

If you try to boot the PC-98 with the diskB already inserted on the drive B:, it will freeze with a horrible continuous beep and an error message "no system files" will be shown.

If I boot the diskA or bonus disk (*1) without any disks inserted on drive B:, the game will boot just fine. But then, again, it's not possible to insert a disk on drive B: anymore.

*1: The bonus disk might have been decompressed with a [mojibake](https://en.wikipedia.org/wiki/Mojibake) file name like Á¤¦.FDI

### Steps to reproduce the behaviour

1. Download Wrestle Angels 1 from [this link](https://archive.org/download/PC98GAMELIBRARY/PC-98%20GAME%20LIBRARY.tar/PC-98_Games_8ch-v-10866719%2FGreat%2FWrestle%20Angels%201%20%2B%20Omake%20Disk%20%28CGP%29.rar) and decompress it.
2. Boot the diskA.fdi disk image from drive A:  
3. After the game booted, try to insert the diskA.fdi disk image on drive B: either using the Disk or DOS menus
4. Repeat the test using the bonus.fdi disk image on step-2)

### Expected behavior

It should be possible to insert a disk on a drive after the game is running.

### What operating system(s) this bug have occurred on?

macOS 13.6.3

### What version(s) of DOSBox-X have this bug?

https://github.com/joncampbell123/dosbox-x/pull/4712

### Used configuration

```ini
Default configuration file, with only machine=pc98 changed.
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Insert an empty disk in drive B and swap it afterwards.

**Comment by sdsnatcher** [comment]
> Insert an empty disk in drive B and swap it afterwards.

That didn't solve the problem. Wrestle Angels 1 still doesn't boot even if the image inserted on drive B: is blank.

**Comment by maron2000** [comment]
Working just fine on Windows, 10.06 release (didn't test nightly builds).
First boot the game with disk A and B mounted, and replace disk A with C when instructed.

![wa](https://github.com/joncampbell123/dosbox-x/assets/68574602/8c847b83-8792-44f8-a022-5abd119207fb)
![wa2](https://github.com/joncampbell123/dosbox-x/assets/68574602/e942e881-c053-4079-b854-e87f5a1514bd)

**Comment by sdsnatcher** [comment]
@maron2000

Oh my, this is how the sanity goes out of the window. 😅  I tried some combinations until I could find why it worked for you and not here.

The boot bug happens if you insert the disk image on drive B: before you insert the drive A: image and then boot from the drive A:.

### Steps to reproduce the behaviour:
1. Insert the diskB.fdi disk image on drive B: using the Drive menu
2. Insert the diskA.fdi disk image on drive A: using the Drive menu
3. Select the menu Drive->A->Boot from drive

Result: The PC-98 will freeze with a horrible continuous beep and an error message "no system files" will be shown.

<img width="639" alt="Screenshot BootCrashed" src="https://github.com/joncampbell123/dosbox-x/assets/13080763/cc2cc524-5520-4c04-b248-c24282b4a41f">

If I insert the drive A: image first it boots correctly.

**Comment by maron2000** [comment]
Ok. So we are now on the same track.
For the time being, don't mount drive B first LOL.

**Comment by maron2000** [comment]
It seems from the source code that drive B is intentionally allocated as the boot drive (drive 0) if mounted in advance of drive A.
I think this is due to that PC-98 can boot from drive 2(Drive B) if drive A is empty,but since DOSBox-X assumes drive A only as bootable floppy, maybe we should neglect booting from drive B.

cited from dos_programs.cpp L4822
```cpp 
   else if (IS_PC98_ARCH) {
        //for pc-98 machines, mount floppies at first available index
        for (int index = 0; index < 2; index++) {
            if (imageDiskList[index] == NULL) {
                return AttachToBiosByIndex(image, index);
            }
        }
    }
```

**Comment by sdsnatcher** [comment]
While the PC-98 can indeed boot from the drive B:, AFAIK it will only do so if there's no bootable disk on drive A:

IOW, regardless of the order that the disks were inserted, the PC-98 will always boot the first disk it finds, from the lowest drive letter to the highest.

**Comment by maron2000** [comment]
Yes, and as I mentioned above, DOSBox-X does NOT support booting from Drive B even if PC-98 can, I think we should not do that, since it requires a bunch of fixes while very limited (or even no) benefits.

**Comment by sdsnatcher** [comment]
I agree that, given the current restrictions, this is the best approach.
