### ISSUE TITLE
Laggy keyboard input in Borland C++ 3.1

### ISSUE THREAD

**Issue by doimus** [joncampbell123/dosbox-x#4751]
### Question

I'm having issues with the Borland C++ 3.1 IDE.
Mainly that the keyboard input lags when a key is being held down. 
Ie, press an arrow key, hold it for a second and then release - and the keyboard still keeps receiving "phantom input" and moving the cursor further away. Also, it's not relevant to the cycle count and it's present on all values. If anything, it seems to be worse on pentium-level cycle-counts, and the IDE completely locks on low cycle-counts. It seems it's tied to it's syntax highlighting, but it's still present when syntax h. is turned off.
It's a shame really, as I really like this version of the IDE, it's a pinnacle of text-user-interface in DOS, with syntax highlighting, fantastic inline help etc... Besides this keyboard issue, seems like the best MSDOS programming environment that I managed to find.

I'm also fairly certain this is not a Dosbox-x issue, it's just that I don't know of a better place to ask about it. Also, this behavior is not present in any other text editors or IDEs, including Borland's own Turbo C. 

I've tried different cores and cpu types. I've tried to mess around the [keyboard] settings in the config file, and also those int16 options in the [dosbox] section, to no avail. Is there a way to reduce keyboard polling rate or something like that?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I believe this is a duplicate of #4351.
Give it a try.

**Comment by doimus** [comment]
Yes, the "dos idle api = false" under [dos] header, fixed it. Thanks! 
And I promise I'll look harder next time for previously asked questions... d'oh.
