### ISSUE TITLE
Incorrect colors on EGA video card [on Mac OS]

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#4753]
### Describe the bug

The palette is shown all in blueish colors when the EGA video card is used.

### Steps to reproduce the behaviour

1. Setup dosbox-x to use an EGA video card
2. Boot dosbox-x
3. The palette will already be blueish on both dosbox-x boot screen and DOS prompt:

<img width="638" alt="01_dosbox-x_EGA_bootscreen_blueish" src="https://github.com/joncampbell123/dosbox-x/assets/13080763/686619bb-4152-4e41-9cb5-2b41414a2f14">
<img width="644" alt="02_dos-promot_EGA_blueish" src="https://github.com/joncampbell123/dosbox-x/assets/13080763/f6e5092a-2e2e-4653-8d9a-4214a5c61343">

5. Run your favorite EGA game
6. All colors of the game will be blueish:

<img width="640" alt="03_indiFate_EGA_blueish" src="https://github.com/joncampbell123/dosbox-x/assets/13080763/002c20cb-9785-4f09-a1ed-4a95d4a6214a">

7. Curiously enough, screenshots taken by the dosbox-x Capture menu will have the correct colors, either in raw or cooked modes:

![04_playfate_001](https://github.com/joncampbell123/dosbox-x/assets/13080763/52c36097-a856-48ff-a1eb-429196124cd7)
![05_playfate_000 raw1](https://github.com/joncampbell123/dosbox-x/assets/13080763/c30ee715-3715-48b3-921e-4bc18e132544)

### Expected behavior

The EGA colors should be displayed correctly.

### What operating system(s) this bug have occurred on?

macOS 13.6.3

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Used configuration

```ini
Default dosbox-x.conf with the video card set to ega
```

### Additional information

Tested with the SDL2 version of dosbox-x

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I think this is common with #4571.
I heven't bisected it but this bug has been appeared since more older versions as well.
Try the SDL1 version.

**Comment by joncampbell123** [comment]
Please check the SDL2 version. SDL1 builds use a very odd RGBA channel order meaning R in the upper 8 bits (bits 31-24) and A (alpha) in the lower 8 bits, which is completely backwards from the normal ARGB that most Windows and Linux systems use.

I think SDL1 does that only because of older Mac OS X interfaces where perhaps RGBA made sense because of the older big Endian PowerPC systems.

**Comment by joncampbell123** [comment]
Some parts of code, still remnants of DOSBox SVN, assume a certain channel order and don't work right on Mac OS X SDL1 builds.

**Comment by sdsnatcher** [comment]
>  Try the SDL1 version. 

Using the SDL1 version indeed workarounds the EGA color bug.  Thanks!

> Edit: FYI unfortunately, SDL1 version isn't bug free regarding screen capture. See issue #4515.

Curiously enough, the SDL1 screenshots worked fine, at least on EGA.

**Comment by maron2000** [comment]
You can change the title of this issue since macOS is only affected, and is regarding SDL2 version only.
