### ISSUE TITLE
Raw screenshots have duplicated pixels and no Pixel Aspect Ratio metadata

### ISSUE THREAD

**Issue by sdsnatcher** [joncampbell123/dosbox-x#4754]
### Describe the bug

While taking raw screenshots for #4753, I noticed two problems with the saved png files:

1. There are duplicated pixels. Raw screenshots are supposed to be a direct copy of the video memory, without any sort of scaling
2. The Pixel Aspect Ratio metadata is not being stored in the png files, causing them to be viewed with square pixels on viewers that support PixelAspect Ratio, like XnView and the Win 10 image viewer.

Example:
![05_playfate_000 raw1](https://github.com/joncampbell123/dosbox-x/assets/13080763/99c0cc9f-7854-4f22-b58c-fc80bc1582d1)

### Steps to reproduce the behaviour

1. Run any DOS game. Preferably EGA 640x200 or 640x350 games, where the issue is more evident
2. Take a raw screenshot using the Capture menu

### Expected behavior

1. The raw screenshot should be a **raw** dump from the video memory, without any form of scaling
2. The Pixel Aspect Ratio metadata (PNG pHYs chunk) should be stored in the file

dosbox-staging [already implemented this on their raw screenshots](https://github.com/dosbox-staging/dosbox-staging/pull/2503).

Example (please view the image using [XnView](https://www.xnview.com/en/), since it supports the Pixel Aspect Ratio metadata to render rectangular pixels):
![06_playfate_000 raw1_corrected](https://github.com/joncampbell123/dosbox-x/assets/13080763/8de31a41-f129-445e-8194-71ef12b24c8c)

### What operating system(s) this bug have occurred on?

macOS 13.6.3

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
At this moment, the raw capture mode is more of a direct capture of the pixel values as rasterized by the monitor, so if your using a 200-line graphics mode on VGA, and the VGA is doubling each scan line as VGA normally does in those modes, then the raw capture will contain the raw pixel values, scan line doubled.

Good point on the aspect ratio fields though, I think I can figure out how to use libpng to write that.

**Comment by joncampbell123** [comment]
I'm sorry if "raw" is confusing in that it's not exactly a snapshot of video memory, but only a snapshot of the raw pixel values from video memory as they are rasterized to the screen.

**Comment by joncampbell123** [comment]
http://www.libpng.org/pub/png/book/chapter11.html#png.ch11.div.9

![image](https://github.com/joncampbell123/dosbox-x/assets/6245486/4d242585-b362-4497-b1d9-13f94e730750)

And the libpng function is png_set_pHYs but only if PNG_pHYs_SUPPORTED.

**Comment by joncampbell123** [comment]
Done. See latest commit.

**Comment by johnnovak** [comment]
FYI, DOSBox Staging now has a revised raw capture mode which writes the raw framebuffer, e.g., 640x200 stats 640x200.

Plus we also write the aspect ratio info into the PNG header, and we also have the "upscaled" mode which essentially does aspect ratio correct upscaling via bilinear sharp to roughly 1200px of vertical resolution as most image viewers can only do square pixels.
