### ISSUE TITLE
Configuring Intel AX210 network card with Windows 98SE

### ISSUE THREAD

**Issue by eat-sleep-code** [joncampbell123/dosbox-x#4767]
### Question

- installed the latest DOSBox 2023.10.06 (VS SDL2 64-bit) build (January 17, 2024).   
- installed _npcap 1.79_
- updated config to have the following under the __[ne2000]__ section: 

```
ne2000 = true
nicbase = 300
nicirq = 10
macaddr = random
backend = pcap
```

- launched DOSBox and clicked _Help > List network interfaces_.  Among the list is: `5 rpcap://Device\NPF_{D853C536-5654-4DE0-A402-5DA8726E3970} (Network adapter 'Intel(R) WiFi 6E AX210 160MHz' on local host)` 
- I exited DOSBox and edited my config file to have the following under the __[ethernet, pcap]__ section:

```
realnic = 5
timeout = default
```
- restarted DOSBox with this new config

This is however where I am stuck.  When I launch the __Network__ item under the __Control Panel__, of course it is empty.   I clicked _Add... > Adapter_ but unfortunately, I don't know what to select for the Adapter.  

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Please check the DOSBox-X wiki, in particular:
- https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X
- https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-98

In particular the warnings that pcap will not work with wireless adapters.

**Comment by eat-sleep-code** [comment]
> Please check the DOSBox-X wiki, in particular:
> 
> * https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox%E2%80%90X
> * https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-98
> 
> In particular the warnings that pcap will not work with wireless adapters.

Switching `realnic = 10` to select my Broadcom Ethernet adapter still results in the same behavior.   I am not seeing anywhere in that documentation on how to specify the adapter in Windows 98SE's Network Control Panel.

**Comment by rderooy** [comment]
The adapter is the "Novell NE2000 compatible", and you don't need to select the adapter. If it was properly enabled as mentioned on the wiki pages, the find new hardware wizard should find it (although possibly with the wrong IRQ...).

**Comment by jledgett** [comment]
@rderooy  Yup, went into Device Manager and it was disabled.   Enabled it, then went to Network and added the NE2000 compatible driver.   But it shows it as IRQ3 (guessing that should be 10 based on my config above) and it shows a conflict for the I/O address range of *200-21F?   What should that value be??

**Comment by eat-sleep-code** [comment]
@rderooy Yup, I into Device Manager and it was disabled. Enabled it, but every time I rebooted it would re-disable itself. I ended up purging it in Device Manager and then rescanning for hardware. I added it and now it is recognized, gets an IP address, DNS servers, etc.

But yet when I run ping, it can only see itself.

For example:

- Pinging it's own IP, 192.168.1.48: **works**
- Pinging the Gateway/DHCP router it just got it's IP from, 192.168.1.1: **fails with `4 packets sent, 0 received`**
- Pinging linksys.com: **fails with `Unknown host linksys.com.`**
- Pinging google.com: **fails with `Unknown host google.com`.**

Here is the output from ipconfig /all

![Screenshot 2024-01-20 172838](https://github.com/joncampbell123/dosbox-x/assets/3846471/fd31734b-533b-4e7a-93f6-dfcf7ef651fc)

**Comment by eat-sleep-code** [comment]
I think I figured it out.   It is at least working for the moment.  I believe that the list resorted itself when I restarted the computer.   It retained the old lease, but could no longer use nic "10".   

I disabled my second ethernet jack on the machine to avoid confusion then changed realnic="Broadcom" and it seems to be working.
