### ISSUE TITLE
macOS ARM builds report "macOS Intel" on the opening banner.

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#4770]
### Describe the bug

If I build current code under macOS on an ARM machine, the opening banner says the build is "v2023.10.06, macOS Intel SDL1 64-bit". The executable is in fact an arm64 build. The correct `OS_PLATFORM_LONG` string doesn't seem to get used, though I can't imagine why.

### Steps to reproduce the behaviour

Build current code under macOS on an ARM machine. Run `dosbox-x` and look at the opening banner.

### Expected behavior

The opening banner says `ARM` not `Intel`

### What operating system(s) this bug have occurred on?

macOS Sonoma 14.2.1 - M2 ARM

### What version(s) of DOSBox-X have this bug?

SDL1 macOS, build on ARM, code as of today

### Used configuration

```ini
Default configuratiton
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Thanks for testing the ARM build.
Since I can't test it myself, can you try replacing the following line?
```c
//#ifdef __arm__    /* before  */
#ifdef __arm64__    /* after   */
```

**Comment by emendelson** [comment]
@maron2000 - Yes, that change in `version_string.h` fixed the problem. Thank you. But the string `__arm__` occurs around ten more times in the code, in five or six other files. Should it be changed everywhere?

**Comment by maron2000** [comment]
There should be codes that target ARM 32-bit so we have to be careful to when replacing other places.

A simple search result below shows that architecture checks are generally done by libraries imported from other projects, so maybe better to discuss in the respective projects.
https://github.com/search?q=repo%3Ajoncampbell123%2Fdosbox-x+__arm__&type=code

**Comment by emendelson** [comment]
@maron2000 - Understood. Will try to figure out how to raise this elsewhere. But it may be possible to add an `#ifdef MacOSX` test to some of those other codes and that could sort it out.
