### ISSUE TITLE
SDL: Menubar doesn't return after full-screen toggle

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#478]
I can't find any earlier reference to this, so here goes: In the SDL build, when I toggle to full-screen and back, the menu bar doesn't reappear.

**Comment by joncampbell123** [comment]
I just posted the latest Windows binary. I am compiling the latest Windows async hack binary now.

**Comment by joncampbell123** [comment]
Try the latest binary release.

**Comment by emendelson** [comment]
Fixed now. Thank you!
