### ISSUE TITLE
Wing Commander 3 Audio Issues

### ISSUE THREAD

**Issue by brakenwagen** [joncampbell123/dosbox-x#4780]
### Describe the bug

In Wing Commander 3 the audio crackles and skips. This does not happen in regular dosbox.

### Steps to reproduce the behaviour

play wing commander 3

### Expected behavior

for audio to play like normal

### What operating system(s) this bug have occurred on?

Win 10

### What version(s) of DOSBox-X have this bug?

dosbox-x-mingw-win32-20231007055223 SDL2

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Based on the GOG.COM purchase I made, the first thing you need to try is:

Change cycles from "auto" to "20000"
CPU type from "auto" to "pentium"
Core from "auto" to "normal"

That seems to fix the intermittent pauses in audio for me.

Also noticed that the GOG.COM dosbox.conf disables GUS support. I wonder why :smirk:

**Comment by joncampbell123** [comment]
Well, actually, I forced the game to use the GUS for sound effects (it refuses to play music on it!) and actually it's playing the audio quite perfectly fine. So, good on them for not writing shit GUS drivers. :+1:
