### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by Lartenik** [joncampbell123/dosbox-x#4781]
### Question

"I have translated from en_US to Russian (ru_RU). Is it possible to adapt this file for the program to work correctly?"
[ru_RU.txt](https://github.com/joncampbell123/dosbox-x/files/14049016/ru_RU.txt)
p.s
Hello from Kazakhstan.
### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Of course your translation can be included in the code.
You need to make a pull request, but someone can do it for you if you are okay with it.

**Comment by Lartenik** [comment]
I agree
