### ISSUE TITLE
Int 10h mode 0x0F is broken on any VGA/SVGA machine

### ISSUE THREAD

**Issue by MrMadguy64** [joncampbell123/dosbox-x#4782]
### Describe the bug

I've added 640x350x1 (0x0F) and 640x480x1 (0x11) mode support to my [Engine version v0.29](https://github.com/MrMadguy64/Engine). 640x480x1 mode works properly, but 640x350x1 is broken. Picture is garbled for machine = any VGA or SVGA card. It works properly for machine = EGA. After analyzing DOXBox-X sources I've come to conclusion, that this problem is caused by hardcoding CRTC port number in some places. Because using 0x3b4 instead of 0x3d4 - is only difference between 640x480x1 and 640x350x1 modes.

How it should work:

![How it should work](https://github.com/joncampbell123/dosbox-x/assets/43206926/18467df4-171d-4f53-9119-9e2d9c6db506)

How it works:

![How it works](https://github.com/joncampbell123/dosbox-x/assets/43206926/ed6a0e43-fe03-41b3-a9b3-deed1cd3898d)

### Steps to reproduce the behaviour

1. Set machine to vgaonly or svga_any. 
2. Download [Engine version v0.29](https://github.com/MrMadguy64/Engine)
3. Edit Data\Engine.cfg: set Width=640, Height=350, Format=2
4. Run Launcher.exe

### What operating system(s) this bug have occurred on?

Windows

### What version(s) of DOSBox-X have this bug?

dosbox-x-mingw-win64-20231007055223

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
The VGA register dumps I've made suggest that you're right, the 640x350 mode 0xF should be port 0x3Bx, at least according to the Trident TVGA8900D dump.

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/VGA%20register%20snapshots

And mode 0xF is 640x350 mono, correct. http://www.ctyme.com/intr/rb-0069.htm

**Comment by joncampbell123** [comment]
Actually, hold on, my tests show that the I/O port in mode F is correctly at 3Bxh, but INT 10h is still using 3Dxh. Is your source engine using 3Bxh or is it using the BIOS to determine which I/O port or what?

**Comment by joncampbell123** [comment]
I'll examine the register dumps again, I think mode F isn't being programmed properly. Monochrome modes are supposed to be the planar modes with all but 1 bitplane disabled the the palette programmed accordingly.

**Comment by joncampbell123** [comment]
Fixed. Will close on release.

**Comment by MrMadguy64** [comment]
Thanks. For now I don't want to rely on BIOS, so ports are hardcoded for this mode. May be I should examine Misc port instead. I'm not sure for now. But these ports are used for page flip and vsync only. As both things worked properly, there couldn't be problem on my side.

**Comment by joncampbell123** [comment]
> Thanks. For now I don't want to rely on BIOS, so ports are hardcoded for this mode. May be I should examine Misc port instead. I'm not sure for now. But these ports are used for page flip and vsync only. As both things worked properly, there couldn't be problem on my side.

Your code relies on INT 10h to set the video mode, correct? The bug was that another part of INT 10h related to whether high intensity colors blink mis-programmed the attribute controller and accidentally set it up like a 640x350 garbled text mode, which that commit fixes.

**Comment by joncampbell123** [comment]
> Thanks. For now I don't want to rely on BIOS, so ports are hardcoded for this mode. May be I should examine Misc port instead. I'm not sure for now. But these ports are used for page flip and vsync only. As both things worked properly, there couldn't be problem on my side.

According to register dumps I've made of common cards, it's supposed to use port 3Bxh, but if you want to be sure, you could, for VGA, use port 3CCh to read back the misc register, or for EGA, use the BIOS data area to read what the BIOS has stored for CRTC I/O port (16-bit WORD at 0040:0063h). http://www.piclist.com/techref/bios/dataarea.htm

I mention the BDA because the EGA is one of the last of IBM cards that still has write-only I/O ports.

According to WHATVGA, port 3CCh is not readable, even if port 3C2h is writeable.

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/EGA/EGA%20Registers%20%28WHATVGA%20v2%2e00%29%20%281995%2d09%2d29%29%2etxt

**Comment by joncampbell123** [comment]
One more thing to check: Does your engine contain code to detect whether the video is MDA/CGA/EGA/VGA and maybe even Tandy or PCjr? Unfortunately that involves some calls to the BIOS to detect, not probing with I/O ports.

https://github.com/joncampbell123/doslib/blob/master/hw/vga/vga.c#L246

**Comment by MrMadguy64** [comment]
> > Thanks. For now I don't want to rely on BIOS, so ports are hardcoded for this mode. May be I should examine Misc port instead. I'm not sure for now. But these ports are used for page flip and vsync only. As both things worked properly, there couldn't be problem on my side.
> 
> Your code relies on INT 10h to set the video mode, correct? The bug was that another part of INT 10h related to whether high intensity colors blink mis-programmed the attribute controller and accidentally set it up like a 640x350 garbled text mode, which that commit fixes.
> 
> Also just for reference, if your engine intends to use 640x350 monochrome on both EGA and VGA, you'll want to use INT 10h because each variation programs the mode for proper display on the attached monitor.
> 
> EGA will set up 640x350 to match what the monitor expects and VGA will set up 640x350 as like a 640x400 mode but with additional blanking to "letterbox" it to 640x350 (yes, that's what VGA cards do with that mode!).

When I say, that I don't want to rely on BIOS, it doesn't mean, that I don't use Int 10h for mode switching. Of course I use it. I don't use manual hardware reprogramming. What I mean, is that I don't like to rely on BIOS data, exactly because it can be messed up. If it's known, that video mode is monochrome, then I can just hardcode 3Bxh. Am I wrong? Do you suggest relying on BIOS data instead, because on some cards mode 0Fh can use 3Dxh?

I know, that VGA supports only 640/ 720 width and 400/480 height and that 350 is "emulated".

> One more thing to check: Does your engine contain code to detect whether the video is MDA/CGA/EGA/VGA and maybe even Tandy or PCjr? Unfortunately that involves some calls to the BIOS to detect, not probing with I/O ports.
> 
> https://github.com/joncampbell123/doslib/blob/master/hw/vga/vga.c#L246

Yes, I use both 1A00h and 1015h to detect VGA.

**Comment by joncampbell123** [comment]
As someone who learned to code back in the 1990s, yes, I have some old hardware lying around :)

I think you can set DCR to make the 320 256-color mode even low resolution. That bit should be universally supported by VGA hardware to halve the clock like any other mode. That bit is how you turn 640x200 16-color mode into 320x200 16-color mode provided you reprogram the CRTC horizontal parameters to match. I seem to recall some Demoscene stuff in the early to mid 1990s like to do just that to make a 180x100 mode to do shitty shadebobs really fast :)

I'll double check. I think the only VGA hardware deviant enough to possibly upset any expectations here might be the old Tseng ET4000 I have lying around. As noted in DOSBox-X source code those cards have a bug in Color Select handling and they handle differently unchained 256-color mode in how memory access maps to planar memory on the card.

I've been using the old hardware over the past 16 years by this point to write the various code in DOSLIB which may be helpful. https://github.com/joncampbell123/doslib. It all started back when I finally got Open Watcom 1.8 to compile and run on Linux.

**Comment by MrMadguy64** [comment]
Yes, everything seems to work.

But I still have question. As you might notice, VGA support test is passed, even when machine=ega. Is it right behavior? Are EGA/VGA video cards actually possible? I know, that some cards have both VGA and EGA connectors. But do they support VGA BIOS features, when EGA monitor is connected to them? Do I need to perform extra "It's not EGA" test?

**Comment by joncampbell123** [comment]
How are you testing for EGA? As far as I know the only reliable way to determine EGA vs VGA is to do a few simple INT 10h tests. Even if you do I/O port tests that might detect the IBM EGA, clone cards will act differently. I know, I had a common EGA clone card in the late 1990s that failed the "most registers are write/only" myth.

**Comment by joncampbell123** [comment]
As for cards that had both EGA and VGA connectors (I have a Tseng ET3000 which apparently was just like that), I'm not sure exactly at this time if it drives both at the same time.

I do know when I was experimenting with adding old ATI Wonder VGA emulation to DOSBox-X that the ATI documention mentions registers with bits you can set to "enable EGA limitations" and "enable CGA/MDA limitations" and those cards apparently have dual connectors too, in fact, that VGA BIOS appeared to test the CRTC in a way that DOSBox-X failed the test and it was constantly coming up in it's EGA mode.

**Comment by MrMadguy64** [comment]
> How are you testing for EGA? As far as I know the only reliable way to determine EGA vs VGA is to do a few simple INT 10h tests. Even if you do I/O port tests that might detect the IBM EGA, clone cards will act differently. I know, I had a common EGA clone card in the late 1990s that failed the "most registers are write/only" myth.

I guess, EGA shouldn't support DAC-specific INT 10h calls, like 1015h. And of course it shouldn't support 1A00h. It's just not good, that I should perform both "It's VGA" and "It isn't EGA" tests. But, I guess, I'll have to do it, because EGA/VGA cards are possible.

**Comment by joncampbell123** [comment]
> > How are you testing for EGA? As far as I know the only reliable way to determine EGA vs VGA is to do a few simple INT 10h tests. Even if you do I/O port tests that might detect the IBM EGA, clone cards will act differently. I know, I had a common EGA clone card in the late 1990s that failed the "most registers are write/only" myth.
> 
> I guess, EGA shouldn't support DAC-specific INT 10h calls, like 1015h. And of course it shouldn't support 1A00h. It's just not good, that I should perform both "It's VGA" and "It isn't EGA" tests. But, I guess, I'll have to do it, because EGA/VGA cards are possible.

Not exactly. Look at how my DOSLIB project does it.

https://github.com/joncampbell123/doslib/blob/master/hw/vga/vga.c#L246

**Comment by joncampbell123** [comment]
See also: http://www.ctyme.com/intr/rb-0219.htm
See also: http://www.ctyme.com/intr/rb-0162.htm
