### ISSUE TITLE
interrupt masking not working (port 21h)

### ISSUE THREAD

**Issue by mills32** [joncampbell123/dosbox-x#4796]
### Describe the bug

Port 20h enables/disables  certain interrupts (floppy, keyboard etc).

While programming a game, I found writting to this port (to disable the keyboard interrupt) has no effect on Dosbox-x.

`
asm in  al, 21h    //Read existing bits.
	asm mov val,al
	asm or  al, 02h    //Turn off IRQ 1 (KEYBOARD)
    asm out 21h, al    //Write result back to PIC.

asm in  al, 21h     //Read existing bits.
    asm and  al, 0xFD   //Turn on IRQ 1 (KEYBOARD)
    asm out 21h, al     //Write result back to PIC.*/

`

I created a program testing this code to check it, this worked well on other emulators (official dosbox also worked) and real PC.

Thanks

### Steps to reproduce the behaviour

Test the uploaded code/program

### Expected behavior

Keyboard should be ignored while program is running (about 10 seconds).
[KEYBOARD.zip](https://github.com/joncampbell123/dosbox-x/files/14139688/KEYBOARD.zip)

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Used configuration

```ini
default dosbox-x config
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Are you programming port 20h as well? Port 21h is generally the interrupt mask but has other functions as well depending on what commands you are sending to port 20h. I will check that port 21h is masking properly.

See also: http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Interrupt%20controller/8259

**Comment by joncampbell123** [comment]
It just occurred to me why writing port 21h doesn't mask the keyboard IRQ.

It actually does. However DOSBox-X is written to emulate what some BIOSes do where when handling some INT 16h functions, the INT 16h handler will unmask IRQ 1 so that keyboard input works.

If your game hooks IRQ 1 (INT 9) for itself and handles the keyboard directly, and NEVER calls INT 16h nor any DOS interrupt call that would call INT 16h, you should be able to mask IRQ 1 and it should stay masked until someone calls INT 16h again.

**Comment by joncampbell123** [comment]
On a similar note, there are some demoscene entries and DOS games that expect INT 15h time delay functions to automatically unmask IRQ 8 (RTC timer interrupt) because if it does not, the time delay function never returns and the demo/game hangs.

**Comment by mills32** [comment]
Thanks!, it seems complicated, I'd better not use that functions for the game.
