### ISSUE TITLE
Populous (GOG) not working in VGA mode with DOSBox-X (only EGA). Works fine with bundled DOSBox 0.74-2.

### ISSUE THREAD

**Issue by dharmOS** [joncampbell123/dosbox-x#4802]
### Describe the bug

I have purchased the GOG version of Populous. Using the default DOSBOX 0.74-2 installed by GOG, the game works with VGA and Roland MT-32. However, if the same config file is run in DOSBox-X, the game runs (populous.exe VGA Roland MT-32) with a black blank screen and MT-32 audio. Only by using EGA mode (populous.exe EGA Roland MT-32) does it work, albeit in lower colour depth/resolution. 

### Steps to reproduce the behaviour

At DOS prompt:
$ populous.exe EGA Roland MT-32
Esc to quit application
$ populous.exe VGA roland MT-32

### Expected behavior

In DOSBox-X, using default machine=svga_s3 (have also tried vgaonly)

populous.exe EGA Roland MT-32 (graphics visible)
![image](https://github.com/joncampbell123/dosbox-x/assets/109996152/d970f45d-eec1-447b-a076-f913d42877a6)

populous.exe VGA roland MT-32 (black screen)
![image](https://github.com/joncampbell123/dosbox-x/assets/109996152/877faad4-b92f-4350-82f7-6f233998736a)

### What operating system(s) this bug have occurred on?

Win 11 for x86-64, Win 11 for ARM64

### What version(s) of DOSBox-X have this bug?

Tried both SDL1 and SDL2 of DOSBox-X  2023.10.06 for x86-64 and ARM64

### Additional information

[dosboxPOPULOUS.zip](https://github.com/joncampbell123/dosbox-x/files/14168245/dosboxPOPULOUS.zip)

Happy to share the Populous 1 binary if this helps for testing.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by dharmOS** [comment]
[dosboxPOPULOUS.conf.zip](https://github.com/joncampbell123/dosbox-x/files/14168316/dosboxPOPULOUS.conf.zip)
Cannot upload .conf file as not accepted by Github. Converted to zip file. 

File dosboxPOPULOUS.zip is same conf file.

**Comment by maron2000** [comment]
You may want to try the recent nightly builds.

**Comment by dharmOS** [comment]
I tried the 4 Feb 2024 nightly build and it works fine in VGA. Thank you, the bug is corrected.

**Comment by maron2000** [comment]
Please don't forget to close solved issues.
