### ISSUE TITLE
Compiled on Pi400 - Can't get any output to work besides surface

### ISSUE THREAD

**Issue by mdlarussa** [joncampbell123/dosbox-x#4803]
### Question

I'm trying to get fullscreen output called from EmulationStation, but I can't get the output to be anything but surface. Do I need to recompile with some different flags to get it working?  Main issue is that the scalers aren't doing anything and the output is only 1/8th of my screen.  Windowed or Fullscreen also doesn't seem to make a difference.

Config file attached.  Any assistance would be greatly appreciated.  I use output = ttf, scaler = normal5x, glshader = scan3x on my windows box and it works great. Figured I'd use the same on the Pi, but the output is proving tricky.

I'm using DosBox-X due to the long filename capability.  My DOS collection is all LFN on windows, and it would be a pain to reconfigure 100s of conf files with 8.3 names and paths.

Log File:
```
LOG: SDL1 auto-detected desktop as 1920 x 1080
LOG: The direct3d output is not enabled.
LOG: The following output will be switched to: opengl
LOG: Could not initialize OpenGL, switching back to surface

```
[dosbox.conf.txt](https://github.com/joncampbell123/dosbox-x/files/14174201/dosbox.conf.txt)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Shaders relies on OpenGL, which as you can see from the output cannot be initialised.

**Comment by mdlarussa** [comment]
So, back to the original question - do I need to enable a specific compile flag somewhere or am I just out of luck here?

**Comment by rderooy** [comment]
I'm not quite sure, but since your running without display server (X11 or Wayland), I don't know if you can use OpenGL. Try to start a display server, and then run DOSBox-X from there to test.

**Comment by mdlarussa** [comment]
I updated the conf file to match a repo-installed version of dosbox.  That version was working full screen using ttf output.  When I switched this build to ttf, I get a segfault.  So it looks like I either need to figure out how to get LFN support in a package maintained version, or somehow recompile this version w/o the segfault

**Comment by rderooy** [comment]
Only DOSBox-X supports TTF output, other DOSBox variants don't. So if it has a TTF option, it must be a (presumably) older DOSBox-X build.

**Comment by maron2000** [comment]
Some bugs in LFN APIs were fixed after the October release, so the segmentation fault may be due to the old code.
If the package build works with OpenGL, you may want to ask the package builder.
Or try building SDL2 version. The source code includes the instructions   for various build options.

**Comment by mdlarussa** [comment]
Recompiled it using ./build-sdl2 and it works great now.  normal5x zoom blows it up to almost full screen.  even tested some of the shaders successfully, but I don't use anything besides sharp normally.  Thanks for the help!
