### ISSUE TITLE
dosbox-x.app crashes immediately on Sonoma 14.3.1

### ISSUE THREAD

**Issue by heafnerj** [joncampbell123/dosbox-x#4819]
### Describe the bug

I've tried installing via Homebrew and the official releases. Both ways, the dosbox-x.app app crashes immediately. The library libavcodec.60.dylib seems to be missing from various places. I'm trying to run dosbox-x on my Intel MacBook Pro running Sonoma 14.3.1. The issue below seems to address the same problem and declares it fixed. I thought I was using the latest release but I will double check again.

See also https://github.com/joncampbell123/dosbox-x/issues/4638.

### Steps to reproduce the behaviour

Double click the app icon after dragging it to /Applications

### Expected behavior

My understanding is the app should launch.

### What operating system(s) this bug have occurred on?

macOS 14.3.1 (Sonoma)

### What version(s) of DOSBox-X have this bug?

dosbox-x-macosx-x86_64-20231006231157

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by heafnerj** [comment]
Okay the problem seems to have been fixed after the latest official release. I got the following nightly build and it seems to work. At least, the launch problem has been fixed.

https://github.com/joncampbell123/dosbox-x/actions/runs/7876516635

**Comment by maron2000** [comment]
You comment supports that the bug is fixed in the nightly builds.
Thanks for trying.
