### ISSUE TITLE
dosbox.conf option to control default state of menu bar, whether or not visible by default

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#482]
Again, this is probably something I simply haven't found, but is there an option NOT to display the menubar toolbar? For the purposes of my project, it isn't useful, so I've commented out a few (basically random) lines in the source to disable it, but it would be much easier to use an option. If that option already exists, apologies for wasting bandwidth...

**Comment by joncampbell123** [comment]
Do you mean in dosbox.conf? No, but there should be an option.

**Comment by emendelson** [comment]
Yes, that's exactly what I hoped for - an option in the conf file. Thank you.

**Comment by joncampbell123** [comment]
Done.

**Comment by emendelson** [comment]
Thank you! Perfect...
