### ISSUE TITLE
Key mapping in PC-98 mode

### ISSUE THREAD

**Issue by yoshitan98** [joncampbell123/dosbox-x#4831]
### Question

I'm using Japanese 109 keyboard.
https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:KB_Japanese.svg

When I run DOSBox-X (Windows) in PC-98 mode, backquote (`) is mapped as tilde (~) and tilde is mapped as backquote.  I don't find any problem in the default mode (svga_s3).

Could you solve the problem?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
This is NOT a problem since Shift+@ is indeed tilde on real PC-98.
I believe NP2 forks honor real PC-98 behavior as well.
It should be a JP keyboard specific option, if implemented in a certain way.

**Comment by yoshitan98** [comment]
Thank you for your reply.
JP keyboard option would be a great help for most users in Japan.

**Comment by maron2000** [comment]
Added a option to force JIS keyboard `pc-98 force JIS keyboard layout`.
Please try the nightly build.
The default is `false`, you can switch it on in the `PC98` section in the Configuration Tool menu.
