### ISSUE TITLE
DOSBox-X crashes on launch on Intel Macbook Pro, possible packaging/linking error.

### ISSUE THREAD

**Issue by ovvldc** [joncampbell123/dosbox-x#4835]
### Describe the bug

I decided to test out the DOSBox-X version on my 2018 Macbook Pro (Intel) and I ran into what looks like a packaging problem. It crashed immediately and the report below suggests it tries to load an ARM library on the x86_64 build.

### Steps to reproduce the behaviour

1. Install DOSBox-X
2. Set correct permissions
3. Run DOSBox-X
4. Observe crash

### Expected behavior

I would expect DOSBox-X to not have issues with the libraries.

### What operating system(s) this bug have occurred on?

MacOS Sonona 14.3.1

### What version(s) of DOSBox-X have this bug?

dosbox-x-macosx-x86_64-20231006231157

### Output log

```text
-------------------------------------
Translated Report [excerpt]
-------------------------------------
Process: dosbox-x [15121]
Identifier: com.dosbox-x
Version: 2023.10.06 (2023.10.06)
Code Type: X86-64 (Native)
OS Version: macOS 14.3.1 (23D60)
Report Version: 12
System Integrity Protection: enabled

Crashed Thread: 0
Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/arm64/libslirp.0.dylib
Referenced from: <1CCA865A-7A92-3A3A-BC45-173011993719> /Users/Shared/*/dosbox-x.app/Contents/MacOS/dosbox-x
Reason: tried: '/Users/Shared/Games/DOS/dosbox-x-macosx-x86_64-20231006231157/dosbox-x/dosbox-x.app/Contents/MacOS/arm64/libslirp.0.dylib' (no such file), '/usr/local/lib/libslirp.0.dylib' (no such file), '/usr/lib/libslirp.0.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I believe #4819 is an identical issue with yours which includes the solution.
You may want to give it a try, or a more recent nightly build.

**Comment by ovvldc** [comment]
I tired a nightly build, as suggested, and the bug seems fixed. Thank you, I will close the issue.
