### ISSUE TITLE
Cannot swap floppies in PC-98 mode via the application menu because ".fdi" file extension isn't selectable in macOS Finder dialog

### ISSUE THREAD

**Issue by gammalogic** [joncampbell123/dosbox-x#4845]
### Describe the bug

Running version 2022.09.0 on macOS 10.15 (Intel) I have my copy of DOSBox-X set to PC-98 mode. I have a PC-98 game that uses 3 floppy disks and I can boot the game from the DOS prompt like this:

```boot "/DOSPC98/GTZ/GTZ-A.FDI" "/DOSPC98/GTZ/GTZ-B.FDI"```

This loads the first two floppy disk images into floppy drives 0 and 1 respectively, and the game boots as expected and runs. When the game needs to load the 3rd floppy disk a prompt is display on-screen in the game. From the DOSBox-X menu, if I go to ```DOS > Change current floppy image...``` I can then (in theory) change the disk image by clicking OK on the window that says

```
Floppy drive 1 is currently mounted with the image:

/DOSPC98/GTZ/GTZ-B.fdi

Do you want to change the floppy disk image now?
```
but when the file dialog is displayed, the floppy disk image files are greyed-out and not selectable because they don't match the expected file extension.

### Steps to reproduce the behaviour

As per the description above.

### Expected behavior

If DOSBox-X can mount floppy disk images with an .fdi file extension at the DOS prompt then it would ideally be possible to select them from the file dialog via the application menus.

### What operating system(s) this bug have occurred on?

macOS 10.15 (Intel)

### What version(s) of DOSBox-X have this bug?

2022.09.0

### Additional information

Please note that I'm using an old version of DOSBox-X because the current downloadable release (2023.10.06) does not work on my computer due to an issue with the ARM libraries being incorrectly linked in the Intel build (issue #4438).

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Extensions are already added by PR #4616, after the October release.

**Comment by gammalogic** [comment]
> Extensions are already added by PR #4616, after the October release.

Thank you. I have just confirmed that this works in the latest development build.
