### ISSUE TITLE
MinGW 32bit dropped libslirp support resulting an build error on CI (nightly/release) builds

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#4849]
### Describe the bug

As described in the title, MinGW 32bit build fails due to that MSYS2 dropped 32bit libslirp support.
https://github.com/msys2/MINGW-packages/commit/d8a6205b9247c2f05dcc2945c9092a7cd1592347

I temporarily dropped installing libslirp library so that at least we can build DOSBox-X.
After I see that it builds successfully, I will put a PR.
https://github.com/maron2000/dosbox-x-1/actions/runs/8073996883

### Steps to reproduce the behaviour

Build DOSBox-X on a clean installed MinGW-w64 environment, installing the required libraries.

### What operating system(s) this bug have occurred on?

MinGW32 on MSYS2

### What version(s) of DOSBox-X have this bug?

All CI builds

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Well, I guess as long as MinGW can still compile to 32-bit Windows we're going to have to compile our own libraries now.

**Comment by maron2000** [comment]
The MSYS2 officials agreed to restore 32-bit libslirp support.
After it is actually restored, I will restore the MinGW build accordingly.
https://github.com/msys2/MINGW-packages/pull/20241
