### ISSUE TITLE
DOSBox-X stops rendering when UCDOS Special Display Utility（特显程序） TX.COM switching from Video Mode 0x0A to Video Mode 0x03 with glshader enabled

### ISSUE THREAD

**Issue by frank-deng** [joncampbell123/dosbox-x#4852]
### Describe the bug

When using UCDOS's Special Display Utility（特显程序） TX.COM with VESA.DRV UCDOS Video Driver loaded, along with DOSBox-X glshader enabled, DOSBox-X emulator will stop rendering once switching from Video Mode 0x0A (UCDOS specific VESA 640x480x256 color mode) to Video Mode 0x03 (Originally 80x25 16 color text mode, UCDOS made some tweaks for displaying Chinese character via graphics capability)

By enabling/disabling "Video debug overlay" from Debug menu, the emulator and UCDOS returns to normal.

It looks like that some updating operation was missing when switching back from Video Mode 0x0A (UCDOS specific VESA 640x480x256 color mode) to Video Mode 0x03 (Originally 80x25 16 color text mode, UCDOS made some tweaks for displaying Chinese character via graphics capability).

### Steps to reproduce the behaviour

1. Upload [TXDEMO.BAS](https://github.com/frank-deng/retro-works/raw/master/BASIC/TXDEMO.BAS) to emulator
2. Start UCDOS and TX.COM
3. QBASIC /RUN TXDEMO.BAS
4. Press keys until the demo ends.

### What operating system(s) this bug have occurred on?

Windows 11, Ubuntu 22.04

### What version(s) of DOSBox-X have this bug?

2023.09.01 and later versions

### Used configuration

[dosbox-x.conf.txt](https://github.com/joncampbell123/dosbox-x/files/14546579/dosbox-x.conf.txt)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I haven't tried but maybe the workaround explained in Issue #3991 might help.

**Comment by frank-deng** [comment]
It seems that the issue #3991 doesn't help, I always run UCDOS and TX.COM after booting into the guest os from hdd image and it always runs well in older versions of DOSBox-X.

The problem seems related to the implementation of VGA/VESA of S3 video adaptor.

**Comment by maron2000** [comment]
That's too bad.
If there is a known older version that works, you may want to bisect to track down which commit caused the regression.
https://git-scm.com/docs/git-bisect

**Comment by frank-deng** [comment]
DOSBox-X 2023.03.31 2023-03-31 23:59
The latest version which works well.

**Comment by frank-deng** [comment]
On the latest version, after problem occurs, by enable/disable "Video debug overlay", the emulator and UCDOS returns to normal.

**Comment by frank-deng** [comment]
For the newest version, set `scanline render on demand` with `true` or `false` will solve this problem.
