### ISSUE TITLE
Problem occurs when changing floppy image via menu

### ISSUE THREAD

**Issue by frank-deng** [joncampbell123/dosbox-x#4858]
### Describe the bug

When loading two floppy images for one drive via menu "Change current floppy image..." back and forth, with "locking disk image mount" enabled, one of the floppy images won't be able to be loaded and got "File in use" error instead.

Is it possible to only lock the floppy image current in use, and unlock the floppy image when unloaded or swapped out?

### Steps to reproduce the behaviour

Changing floppy image via menu "Change current floppy image..." with "locking disk image mount" on:

1. Load disk1.img via menu
2. Load disk2.img via menu
3. Load disk1.img via menu again
4. Load disk2.img via menu again, it will report that disk2.img is already locked and cannot be loaded.

### What operating system(s) this bug have occurred on?

Windows 11

### What version(s) of DOSBox-X have this bug?

2023.03.31

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maxpat78** [comment]
Please try a more recent build, it should be fixed already by #4556

**Comment by frank-deng** [comment]
I've tried DOSBox-X 2024.03.01, the problem still exists.

**Comment by frank-deng** [comment]
I've tried DOSBox-X 2024.03.01, it works well now.
