### ISSUE TITLE
If a folder drive no "autoexec" can be run, DOSBox-X will no response.

### ISSUE THREAD

**Issue by leoxxx** [joncampbell123/dosbox-x#4861]
### Describe the bug

If it's a floppy image drive, run "autoexec" go to you last mounted foler drive. If it's a folder drive,it will no response.

### Steps to reproduce the behaviour

1.Go to a no "autoexec" folder drive.
2.Run "autoexec".

### What operating system(s) this bug have occurred on?

Windows 10 pro 22H2 64bit

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2024.03.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I believe if [autoexec] section of your conf file has some contents, autoexec.bat will appear on Z drive.
If `PATH` is set to `Z:\`, it will be executed no matter whether the drives you mounted contains autoexec.bat (or exe or com).

**Comment by leoxxx** [comment]
```
[autoexec]
# Lines in this section will be run at startup.
mount d g:\pc98
d:
```
I just add this. I delete "d::". I input "d:" after dosbox-x running, then input "autoexec", no response. g:\pc98 have no autoexec, it's empty folder.

**Comment by leoxxx** [comment]
Sorry, my bad. I found a autoexec in the folder.
