### ISSUE TITLE
Request: "titlebar" [SDL] option instead of RunningProgram

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#487]
Could the [SDL] section of the conf file include a titlebar= option that would let the user enter a string that would appear in the titlebar instead of the current RunningProgram?

For Windows 3.1, the titlebar now reads KRNL386, but it would be more elegant to be able to set a string that identifies a game or merely "Windows 3.1".

I see that there is already a title= option, but it adds a string to the start of the titlebar, and doesn't take the place of the running program.

With the help of Wengier Wu, I have a titlebar option in my SVN-based project, but after hours of stumbling around incompetently, I don't know enough to make it work in DOSBox-X.

**Comment by emendelson** [comment]
Of course, as soon as I posted my question, I stumbled on an answer. I got this (probably hopelessly incompetent) code to work in sdlmain.cpp:

Add near the top:

`const char *titlebar;`

Then, just above "if (menu.hidecycles) {":

`Section_prop *section = static_cast<Section_prop *>(control->GetSection("SDL"));
	assert(section != NULL);
	titlebar = section->Get_string("titlebar");
	char TitleMsg[100] = { 0 };
	if (strlen(titlebar) != 0)
		sprintf(TitleMsg, titlebar);`

And, around line 4470, at the end of the list of sections added to the config:

`Pstring = sdl_sec->Add_string("titlebar", Property::Changeable::Always, " "); // emendelson 
	Pstring->Set_help("Change the string displayed in the DOSBox title bar."); // emendelson`

Then, change RunningProgram to titlebar in the various bits of code that set the title. Again, I don't have the faintest idea of what I'm doing, so this is more of a request than anything else.

**Comment by joncampbell123** [comment]
There's already a title= option in dosbox.conf under the dosbox section to add an additional message after the usual title.

**Comment by emendelson** [comment]
Yes, but it adds the string to the start of the line, and doesn't replace KRNL386 or whatever else might be there:

![capture](https://user-images.githubusercontent.com/5208505/35780812-693f81ba-09af-11e8-845d-4b8e656a12a9.PNG)

**Comment by emendelson** [comment]
As always, it will be obvious that I don't understand what I'm doing, and this code is probably incompetent, but here is a patch that allows the user to have a simple titlebar that displays only DOSBox-X and a string specified in a titlebar= option in the [SDL] section of the conf file.  (I realized afterwards that this should be more clearly SDL-only, not SDL2, but I'll fix that later.) If titlebar= is not specified, the normal titlebar appears. Again, this is only a suggestion, but I hope an improved version might someday be part of DOSBox-X itself:

https://github.com/emendelson/dosbox-x/commit/91d6a138a075cca6bb5bfe81aaede725a20b6358

**Comment by joncampbell123** [comment]
Looks good at first glance. I'll refine it if I see problems.

**Comment by emendelson** [comment]
There was line in the patch that referred to a variable that I had stopped using (TitleMsg); here's a patch to the patch that gets rid of that needless line:

https://github.com/emendelson/dosbox-x/commit/2323983415274d2b5fa033692caaac3046cfe8de

**Comment by joncampbell123** [comment]
Done. Check the latest commit.
