### ISSUE TITLE
SDL1 MacOS ARM: SDL1 does not work while SDL2 works fine

### ISSUE THREAD

**Issue by TK1-25** [joncampbell123/dosbox-x#4880]
### Describe the bug

- SDL1 version of  Dosbox-X (MacOS, ARM, 2024.03.01) does not work: I get an error message that the SDL2 library cannot be found.
- SDL2 version of Dosbox (MacOS, ARM, 2024.03.01) works fine.

Before updating to March 2024 I used an older version of Dosbox SDL1 from September 2023. This version works fine. I have got SDL runtime library version 20.30.1
<img width="260" alt="2024-03-07_10-36-05" src="https://github.com/joncampbell123/dosbox-x/assets/706454/8be715c0-04c1-48f9-9d5c-4ecbf4baf671">

Hint: I've tested Dosbox (MacOS) not-ARM version (x86_64; intel): Both SDL1 and SDL2 work fine. 
Of course I can use SDL2 version of Dosbox... but I am interested in why the SDL1 version no longer works.

### Steps to reproduce the behaviour

the error message appears directly after the programme start

### What operating system(s) this bug have occurred on?

macOS Sonoma 14.3.1 (23D60)

### What version(s) of DOSBox-X have this bug?

2024.03.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Intel version was fixed by #4732, sdl_net caused the flaw.
Maybe building in-tree sdl_net will work for ARM mac as well.

**Comment by maron2000** [comment]
Added a test to build a nightly ARM mac build.
Since I can't test myself, can you try it?
https://github.com/maron2000/dosbox-x-1/actions/runs/8243795766

**Comment by TK1-25** [comment]
Yes, this ARM version works :-)
Thank you very much.
