### ISSUE TITLE
Commit bfb1bfb caused DOSBox-X to crash if core is set to dynamic

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#4899]
### Describe the bug

The last nightly builds starting with "Begin adding ACPI emulation. Start with an independent memory region …", DOSBox-X hangs if dynamic, in general, is set as core value.

### Steps to reproduce the behaviour

Start the latest nightly DOSBox-X builds starting with "Begin adding ACPI emulation. Start with an independent memory region ...", with dynamic, generally, as the core value.

### Expected behavior

I expect DOSBox-X to be able to run without crashing or hanging, even if core is set to dynamic in general.

### What operating system(s) this bug have occurred on?

Windows 10 Home 2H22

### What version(s) of DOSBox-X have this bug?

DOSBox-X 64-bit MinGW portable builds for Windows 7+, 20240312082228 and onward (I have only tested 64-bit MinGW)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I believe I resolved this issue right away when it turned out I marked the RAM pages non-code by mistake.
