### ISSUE TITLE
Fix for swapping in DOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#490]
This small change makes it possible for programs like WordPerfect for DOS 5.1 and 6.x to swap out to DOS when opening a command prompt. (in WPDOS, the keystrokes are Ctrl-F1, Go to DOS.) This was given to me by a DOSBox developer, but he hasn't authorized me to use his name, so I won't use his name here. I've been using this in my SVN-based project for years with no bad effects, and my guess is that it hasn't got into SVN only because it isn't relevant for games. But it seems worth having in DOSBox-X.

In src\dos\dos.cpp, change line 1401 so that it reads:

`	reg_cx = 0x78c; // swap if in dos - changed from 0x80`

Again, I've been using this for many years with no bad effects. the original 0x80 makes it impossible to swap from WordPerfect for DOS, and perhaps for other programs also.

**Comment by joncampbell123** [comment]
So, it requires a larger swappable data area?

http://www.ctyme.com/intr/rb-3023.htm

Can you confirm any other value larger than 0x80 works?

**Comment by joncampbell123** [comment]
In fact, specifying a larger swappable data area might cause memory corruption in the DOS kernel area because the amount of memory your change reports is probably far larger than the actual SDA area allocated by the DOSBox/DOSBox-X DOS kernel.

Remember the point of the SDA is a region of memory a task switcher can copy to fake "multitasking" between DOS sessions.

**Comment by joncampbell123** [comment]
So the proper fix is to have the INT 21h call there return the actual size, then have the DOS kernel setup use a default value or dosbox.conf value to specify the size of the SDA and then place the size in a variable the INT 21h AX=5D06 call can return in CX.

**Comment by emendelson** [comment]
I'm going to close this because a newer issue makes it all
more clear: https://github.com/joncampbell123/dosbox-x/issues/638
