### ISSUE TITLE
ERROR CPU: Illegal Unhandled Interrupt Called 6 (Windows 98)

### ISSUE THREAD

**Issue by Juango501** [joncampbell123/dosbox-x#4910]
### Describe the bug

Latest version of DOSBOX-X. Installing Windows 98 following the guide provided in the wiki. AMD Ryzen Proccesor, with Vega Graphics. After finishing installation, virtual hard disk fails to boot with debugger screaming, "illegal unhandled interrupt called 6"

### Steps to reproduce the behaviour

Installed Windows 98 according to wiki guide.
Added network support according to wiki guide.
Finish setup, fail to boot hard disk.

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

Visual Studio 2024.03.01

### Used configuration

```ini
[sdl]
autolock=true

[dosbox]
title=Windows 98
memsize=512
synchronize time=true

[video]
vmemsize=16
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra
enable speaker=true
blaster environment variable=true

[serial]
serial2=disabled

[ne2000]
ne2000=true
nicirq=10
backend=pcap

[ethernet, pcap]
realnic=9

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
MOUNT E: NET
E:
SET MTCPCFG=E:\SAMPLE.CFG
NE2000.COM 0x60 10 0x300
DHCP.EXE
IMGMOUNT C hdd.img
IMGMOUNT D Win98.iso
IMGMOUNT A -BOOTCD D
```

### Output log

```text
ERROR CPU: Illegal Unhandled Interrupt Called 6
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
What are you trying to do here? This is not in the wiki...
```
[autoexec]
MOUNT E: NET
E:
SET MTCPCFG=E:\SAMPLE.CFG
NE2000.COM 0x60 10 0x300
DHCP.EXE
IMGMOUNT C hdd.img
IMGMOUNT D Win98.iso
IMGMOUNT A -BOOTCD D
```

You are meant to boot the C: drive after installation, not load NE2000 drivers or DHCP. If you want networking, use the Win98 networking, don't try to load a DOS network stack.

Just mount the hdd image, and any CD or floppy disk you want, and boot from the C: drive as documented on the wiki.
