### ISSUE TITLE
MSCDEX SEEK function not implemented (Silmarils Time Warriors CD tracks issue)

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#4916]
### Describe the bug

The DOSBox Staging developers have discovered that the game's audio tracks are not played because the SEEK function is not implemented in the dos_mscdex.cpp file.
- https://github.com/dosbox-staging/dosbox-staging/issues/3508
- https://github.com/dosbox-staging/dosbox-staging/pull/3516

In DOSBox 0.74-3 the music plays in Silmarils logo sequence and game intro but is missing in menu and game unless you use the TSR CDSEEK.COM developed by ripsaw8080.
- https://www.vogons.org/viewtopic.php?f=33&t=35046&p=299115

In DOSBox-X the game is completely silent and CDSEEK.COM does not seem to work.

### Steps to reproduce the behaviour

1. Mount the cue/bin image (I used the one from eXoDOS)
2. Install the game
3. Configure the audio card and launch the game
4. Try also to execute the CDSEEK.COM before the game

### Expected behavior

The game's audio tracks should play also in the game menu and during the fight.

### What operating system(s) this bug have occurred on?

Windows 10 Pro 22H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2024.03.01

### Used configuration

```ini
Default configuration except cycles = 52000
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by MX9000** [comment]
@maron2000 I just tried the build dosbox-x-mingw-win32-20240324145054.zip but it seems that the patch does not work completely.

Sound Blaster 16:
- Silmarils logo animation: music missing
- Game intro with fighters presentation: music missing
- Game menu and screen with countdown before the fight: music audible but at very low volume
- Fight start: announcer voice missing and background music with very low volume

Sound Blaster:
- Silmarils logo animation: music OK
- Game intro with fighters presentation: music missing and background buzz
- Game menu and screen with countdown before the fight: music OK
- Fight start: music OK but announcer voice and fight sounds with echo

Sound Blaster Pro:
- Silmarils logo animation: music OK
- Game intro with fighters presentation: music OK
- Game menu and screen with countdown before the fight: music OK
- Fight start: announcer voice and music OK

**Comment by maron2000** [comment]
I just imported the patch, but I think the patch itself is working as intended.
Is dosbox-staging working better?

**Comment by MX9000** [comment]
Also the latest build of DOSBox Staging (changelog-v0.82.0-alpha-330-gd7ff.txt.zip) shows some issues.
The game seems very speed-sensitive: https://github.com/dosbox-staging/dosbox-staging/issues/3512

Sound Blaster 16:
- Silmarils logo animation: music OK
- Game intro with fighters presentation: music OK
- Game menu and screen with countdown before the fight: music audible but at very low volume
- Fight start: announcer voice OK but background music with very low volume

Sound Blaster:
- Silmarils logo animation: music OK
- Game intro with fighters presentation: music missing and background buzz
- Game menu and screen with countdown before the fight: music OK
- Fight start: music OK but announcer voice and fight sounds with echo

Sound Blaster Pro:
- Silmarils logo animation: music OK
- Game intro with fighters presentation: music OK
- Game menu and screen with countdown before the fight: music OK
- Fight start: announcer voice OK but background music with very low volume

**Comment by maron2000** [comment]
I see, so I think the sound problem should be raised as another issue rather than further fixing the seeking function.
At least setting to SB Pro on DOSBox-X is the workaround. (or maybe vanilla DOSBox + CDSEEK.COM?)

**Comment by MX9000** [comment]
That's right, I think the only way to figure out the source of the problem would be to run tests on real hardware.
