### ISSUE TITLE
Suggestion: Ctrl-Alt-F#, not Ctrl-F#, for mapper functions

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#492]
This issue doesn't matter for most games, but it matters a lot for applications: 

Many of the mapper functions inherited from original DOSBox use Ctrl-Fkey assignments that conflict with keyboard assignments in many DOS applications. When working on my project, the first thing I do after downloading SVN etc. is to change MMOD1 to MMOD1|MMOD2 in a lot of places to avoid this problem. Someday I hope DOSBox-X might use these combinations by default.

Also, in Windows 3.x and later, Alt-Enter is the key-combination that brings up a Properties box. DOSBox uses Alt-Enter for the full-screen/window toggle. I change this to Ctrl-Alt-Enter and it avoids the problem.

I realize there's a limit to the number of Ctrl-Alt-Fkey assignments available, but a few important DOS applications use all twelve Ctrl-Fkey (and all twelve Alt-Fkey and Shift-Fkey) combinations and it would be useful - at least for those applications - not to have them conflict with DOSBox.

Just a suggestion...!

**Comment by joncampbell123** [comment]
The only issue with CTRL+ALT+Function combinations is that those cannot be used in Linux because those are taken by X11 and the Linux console for switching virtual terminals.

**Comment by emendelson** [comment]
Yes, I see. But for a Windows-only project based on DOSBox-X, I hope it will be possible to create Ctrl-Alt assignments in the source code, as it is now...

**Comment by joncampbell123** [comment]
Perhaps the mapper could be written to make CTRL+ALT default on Windows and some other combination on Linux. Defaults are defined in the source code, where C++ #ifdef blocks could modify it.

**Comment by joncampbell123** [comment]
I want to clarify that my modifications to the mapper will preserve existing mapper abilities. I will only be adding an extra "modifier" that allows VirtualBox-style "host key" combinations in order to clean up the default shortcuts, but you are always free to put the DOSBox shortcuts back. I won't remove that.

**Comment by joncampbell123** [comment]
When the host key modifier is developed, then I intend to change the *default* key mappings in order to reduce the conflicts between the guest OS and DOSBox-X. However, the ability to set the mapper back to DOSBox SVN defaults will always be there.

**Comment by emendelson** [comment]
> Perhaps the mapper could be written to make CTRL+ALT default on Windows and some other combination on Linux

This sounds like an excellent idea.
