### ISSUE TITLE
Documentation error on versions for MacOS

### ISSUE THREAD

**Issue by cszstl** [joncampbell123/dosbox-x#4923]
### Question

The page about DOSBox-X Installation and Released Packages at https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md#macos-packages-portable has a section about "macOS Packages (Portable)" which appears to assert that build 2022.09.0 (0.84.3) will run under Mojave (macOS 10.14).  That is incorrect; when executed, this build declares that it requires macOS 10.15.

I discovered this problem while searching for a solution to another one, namely that DOXBox-X release 0.83.14 (build 2021-06-01), which does run under Mojave, doesn't seem to have functional printer support for DOS -- only for Windows.  That search revealed that the archived release notes for versions 0.83.14 through 2022-09-0 do not indicate which release first imposed macOS 10.15 as a minimum requirement.

Furthermore, hours of searching through the DOSBox-X Website and the DOSBox-X part of github.com have not revealed any downloadable macOS executables between releases 0.83.14 and 2022-09-0.  If I could find those, I could at least download and test them to find which release is actually the last to run under macOS 10.14.  Are such executables available? and if so, where?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
@Torinde 
The current explanation in `INSTALL.md` mentions about "low-end" builds but the files in the link is `DOSBox-X-macos-(version)-high-sierra.zip`.
Some elaboration maybe considered?

I can't test whether High Sierra builds will actually work on Mojave,
but at least they are available for 0.84.0, 0.84.1, 0.84.2.

**Comment by maron2000** [comment]
If High Sierra builds don't work on Mojave, there will be no working Release for Mojave.
We have to see, but Mojave users may need to build DOSBox-X on their own in such case.

**Comment by cszstl** [comment]
Thank you, Torinde -- that file does contain an executable that runs under Mojave (10.14).  And the "ver" command then reports:
    DOSBox-X version 2022.09.0 (SDL1). Reported DOS version 6.22.
So it would now be appropriate to update the online documentation, and to make this package readily available to other Mojave users.

However, this package doesn't pick up my previous customization, so I have come configuration work to do.  But that's a reasonable price to pay.

Again, thanks!

Carl Scott Zimmerman, Campanologist 
Saint Louis, Missouri, USA -
 - 19th c. home of at least 37 bell founders or resellers 
Tel. +1-314-821-8437 
Webmaster for www.TowerBells.org
 * Avocation: tower bells
 * Recreation: handbells
 * Mission: church bellsWebmaster for www.TSCChapter134.orgTreasurer, World Carillon Federation
 

    On Sunday, March 24, 2024 at 01:13:05 AM CDT, Torinde ***@***.***> wrote:  
 
 


dosbox-x-macosx-0.84.3-high-sierra.zip - that is the file you need


If you have an older macOS version such as macOS High Sierra (10.13) and Mojave (10.14)


Did you try with it or with another one?
