### ISSUE TITLE
insufficient disk space error when version set to 7.1

### ISSUE THREAD

**Issue by blindphoneman** [joncampbell123/dosbox-x#4927]
### Describe the bug

Using latest version, when setting the DOS version to 7.1, when trying to copy a file or make a new file, I often get an error indicating insufficient disk space.

### Steps to reproduce the behaviour

Z:\>ver 7.1

Z:\>mount c cdrive
Drive C is mounted as local directory cdrive\

Z:\>c:

C:\>dir

 Volume in drive C is C_DRIVE
 Volume Serial Number is 0000-1234
 Directory of C:\

.              <DIR>            03/25/2024  8:21p .
..             <DIR>            03/25/2024  8:21p ..
COMMO          <DIR>            03/25/2024  4:06p COMMO
DL             <DIR>            03/25/2024  3:59p DL
TELIX          <DIR>            03/25/2024  3:12p TELIX
UL             <DIR>            03/25/2024  6:41p UL
    0 File(s)                 0 Bytes
    6 Dir(s)     84,517,715,968 Bytes free

C:\>dir \ul

 Volume in drive C is C_DRIVE
 Volume Serial Number is 0000-1234
 Directory of C:\UL

.              <DIR>            03/25/2024  6:41p .
..             <DIR>            03/25/2024  8:21p ..
MONOPOLY ZIP             53,695 03/25/2024 10:00p MONOPOLY.ZIP
PK250DOS EXE            207,394 03/01/1999  2:50a PK250DOS.EXE
PKZ204G  EXE            202,574 02/01/1993  2:04a PKZ204G.EXE
    3 File(s)           463,663 Bytes
    2 Dir(s)     84,518,076,416 Bytes free

C:\>dir \dl

 Volume in drive C is C_DRIVE
 Volume Serial Number is 0000-1234
 Directory of C:\DL

.              <DIR>            03/25/2024  3:59p .
..             <DIR>            03/25/2024  8:21p ..
    0 File(s)                 0 Bytes
    2 Dir(s)     84,522,041,344 Bytes free

C:\>copy \ul\MONOPOLY.ZIP \dl
Insufficient disk space - MONOPOLY.ZIP
   0 File(s) copied.

C:\>

### Expected behavior

The file should have copied over to the other directory.

### What operating system(s) this bug have occurred on?

Microsoft Windows Version 23H2 (OS Build 22631.3296) 

### What version(s) of DOSBox-X have this bug?

version 2024.03.01 (SDL1)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
There seems a regression.
If you need longfilename support, set ver to less than 7, and manually enable longfilename support as a workaround.
