### ISSUE TITLE
DOSBox-X doesn't detect joystick

### ISSUE THREAD

**Issue by Vitoria90** [joncampbell123/dosbox-x#4928]
### Describe the bug

The program won't detect my Thrustmaster T.Flight Stick X either on its own or using vJoy, regardless of what setting the Joystick option is set to (tried all of them). Neither the axes nor the buttons register. Regular DOSBox detects both just fine.

### Steps to reproduce the behaviour

1. Connect flight stick
2. (Optional) Activate vJoy
3. Launch DOSBox-X and try to configure the stick through the mapper or through a game's stick set-up (I.E. Wing Commander 3's Setup program or its in-game set up menu)
4. Try changing the joystick settings (auto, 2axis, 4axis, etc.), repeat step 3.
5. No response at all.

### Expected behavior

For the program to detect the input of the stick's axes or at least buttons.

### What operating system(s) this bug have occurred on?

Windows 10 Pro

### What version(s) of DOSBox-X have this bug?

v. 2024.03.01 (VS XP SDL1 64-bit)

### Additional information

Works on regular DOSBox v0.74.3
Config I'm using:
https://pastebin.com/WDucVwxM

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by pablokks** [comment]
Try SDL2. My Thrustmaster 16000M also is not seen in SDL1, but in SDL2 everything is fine

**Comment by Vitoria90** [comment]
How do I activate SDL2? I can't find it in the settings.

**Comment by maron2000** [comment]
All download files include both SDL1 and 2 binaries.
If you used the installer you may need to reinstall.
You can select an option to install all alternatives during the installation.
