### ISSUE TITLE
broken menu...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#493]
The menu is (maybe partially) broken now in Windows environment.
As example: it is now unable to select a filter (Video > Scaler > any scaler)

**Comment by joncampbell123** [comment]
Which build is this? Is it consistent?

**Comment by joncampbell123** [comment]
Windows builds have two different dev branches at this time: The "normal" branch and the new "async" branch. Both are made into releases. Which one?

**Comment by joncampbell123** [comment]
Do be aware that DOSBox and DOSBox-X by default do not use the scaler unless you're running a DOS game that uses a mode like 320x200 VGA. If you're in text mode or 640x480 VGA the scaler selection will have no effect. But you can force it to use the scaler if you select Scaler -> Forced.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
It`s the normal mster branch.
Another menu functions affected too.
The filter menu point was only an example.

**Comment by joncampbell123** [comment]
SDL queues as a "syswmevent" any Windows message it does not process itself. SDL's handling of syswmevent events is to queue it, but drop it if the queue becomes full. Win32 message chatter on a modern Windows system is enough to overflow that queue.

The latest change blocks all messages from that queue except WM_COMMAND (menu bar) and WM_SYSCOMMAND (system menu) which might resolve the issue by filtering out irrelevant messages DOSBox-X does not process.

Are you able to compile from source?

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Ok, the menu is now working again.
