### ISSUE TITLE
IMGSWAP not working

### ISSUE THREAD

**Issue by RvN73** [joncampbell123/dosbox-x#4932]
### Describe the bug

Using IMGSWAP to roll between mounted ISO images does not work. It's even impossible to roll mounted ISO images from the menu og the hotkey.

### Steps to reproduce the behaviour

Jusr mount several ISO images and try to change active ISO with IMGSWAP.

### What operating system(s) this bug have occurred on?

Windows 10 Pro

### What version(s) of DOSBox-X have this bug?

2024.03.01 (SDL2)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by RvN73** [comment]
I just tried with an earlier version i see i have use IMGSWAP, in version 2022.12.26 it is working. Tried the same .conf file in newer releases, not working.

**Comment by maron2000** [comment]
IMGSWAP command indeed doesn't work but swapping iso images by shortcut key (F11+D) worked for me.
2024.03.01 release SDL1 VS x64

**Comment by dreamyshorpy** [comment]
Having the same issue. Reverting to 2022.12.27 made it work. Also had this problem with DOSbox Staging for whatever reason. Cannot test it out on nightlies because your Linux nightlies don't include the needed libraries.

**Comment by maron2000** [comment]
We may stop distributing nightly builds for Linux if it doesn't work for Linux users out of the box.
It can't cover various distributions anyway.
