### ISSUE TITLE
Live MIDI settings update

### ISSUE THREAD

**Issue by Asterchades** [joncampbell123/dosbox-x#494]
I've recently begin the transition from Daum's 3-year-old DOSBox build to DOSBox-X, and have encountered a curious configuration issue.

For simplicity, I've rigged up a series of batch files which automatically adjust settings based on the game in question.  Number of cycles, CD ISO mounting and MIDI configuration, where applicable.  Of these settings, the MIDI configuration is being changed but the new setting is not being honoured - you can only change this via the configuration file.

NB I'm aware that the in-application MT-32 emulation is currently not functioning.  I don't pretend to understand why, but I do know that's a thing.

Essentially I've installed the MUNT driver, which in turn is available as MIDI device #2.  Switching to this from within DOSBox-X (eg "midiconfig 2") does nothing - no system message is shown from MUNT, and all MIDI continues to play through the default MIDI device (in this case, my system MIDI mapper setting).  Attempting to use MIDI device #1 (the MS GM synth) is equally ineffective, as is attempting to switch to Fluidsynth or Coreaudio (both of which should kick back an error, or at least be silent, as I have not configured them).

Other settings, such as the number of cycles requested, appear to be updating correctly in realtime.  At least, the ones I've been playing around with do.

_PS Another useful feature I miss from Daum's build is the environment variable feedback from the "config -get" command.  For example, running "config -get cycles" would set %CONFIG% to equal the current "cycles" setting - great for changing something back after exiting a game.  I have no idea how to submit suggestions individually, but felt I should at least include some mention of it somewhere for consideration._

**Comment by joncampbell123** [comment]
I just committed a change to reinitialize MIDI emulation when you change settings under the 'midi' section. It's a bit brutal, but should work fine as long as you don't change MIDI settings out from under Windows 3.1, in my tests.

**Comment by Asterchades** [comment]
Much appreciated.  I'll give it a go when I next get a chance.
