### ISSUE TITLE
mount a directory with spaces from command line

### ISSUE THREAD

**Issue by idanmiara** [joncampbell123/dosbox-x#4943]
### Question

How do I mount a directory name that contains spaces from the command line?
i.e. What's the equivalent of the following from command line?
```
dosbox-x.exe
mount c "c:\path to my dir"
```
I tied to escape the quotes (`dosbox-x.exe -c "mount c ""c:\path to my dir"""`) but it doesn't help.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I believe you're using Windows. Try the following.
```
dosbox-x -c "mount d 'folder with space'"
```

**Comment by joncampbell123** [comment]
If you want to avoid ugly escaping entirely, put the mount command in the dosbox.conf where you only have to double quote instead of double-double quote just so you can sneak double quotes past both the Windows command prompt and the DOSBox-X shell.

**Comment by joncampbell123** [comment]
Another possibility is that you could specify a -conf file that has only an autoexec section which then does what you want and the main dosbox.conf could just omit the autoexec section entirely.

**Comment by idanmiara** [comment]
Thanks for your comments!

I was able to achieve what I wanted with the following batch.
The purpose to be able to run dosbox with a single batch for different kinds of inputs - folder, executable file, or a zipped file.
it runs `dosbox.bat` if the input is a zip or a folder, and otherwise runs the given filename. 
It mounts the proper folder ahead and sets an overlay.

```
set "dosbox_dir=r:\DOSBox-X"
set "overlay_root=r:\overlay"
set "command=dosbox.bat"

if "%~1"=="" (
    @echo No input provided.
    exit /b 1
)

set "full_path=%~f1"
set "dir_path=%~dp1"
set "filename=%~nx1"
set "ext=%~x1"
set "mount=%full_path%"
set "overlay_name=%~pnx1"

:: Check if full_path is a directory or ends with a backslash
if not exist "%full_path%\*" (
    :: Check if the file has a zip or dosz extension
    if /i "%ext%"==".zip" goto run
    if /i "%ext%"==".dosz" goto run
    goto file
)
goto run

:file
@echo File mode
set "mount=%dir_path%"
set "command=%filename%"
set "overlay_name=%~p1"

:run
set "overlay=%overlay_root%%overlay_name%
mkdir "%overlay%"
"%dosbox_dir%\dosbox-x.exe" -c "mount c '%mount%'" -c "c:" -c "mount c '%overlay%' -t overlay" -c %command% -fs -defaultdir "%dosbox_dir%"
```
