### ISSUE TITLE
MAD TV 2 crashes DOSBox-X

### ISSUE THREAD

**Issue by jez9999** [joncampbell123/dosbox-x#4947]
### Describe the bug

Running MAD TV 2 causes DOSBox-X to hang.  The game runs in DOSBox ECE so it seems to be a DOSBox-X thing.  The fact that it actually hangs DOSBox-X means I can't even view logs or anything, there's no way to interact with the DOSBox-X window.  I just have to end task.

### Steps to reproduce the behaviour

1. Run MAD TV 2.
2. DOSBox-X hangs.

### Expected behavior

Game runs normally.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2024.03.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Max833** [comment]
DOSBox-Staging fixed this issue:

**Threads:**
https://github.com/dosbox-staging/dosbox-staging/issues/3668
https://github.com/dosbox-staging/dosbox-staging/issues/3675

**Commits:**
https://github.com/dosbox-staging/dosbox-staging/pull/3673
https://github.com/dosbox-staging/dosbox-staging/pull/3680

**Comment by joncampbell123** [comment]
Perhaps fixed by the same issue that plagued Dunkle Schatten, Mad TV 2 appears to work perfectly fine in the latest commit. Perhaps programmed by the same team, and has the same need to look into the SFTs.
