### ISSUE TITLE
PC-98: DOSBox-X ASCII uppercase conversion is mangling Shift-JIS

### ISSUE THREAD

**Issue by leonier** [joncampbell123/dosbox-x#495]
in PC-98 emulation mode DOS, there are some filenames look different than the correct one.
For example, TH4's "東方幻想.郷" displays as "東方幻岨.郷".
"想" in Shift-JIS is 91 7a and ”岨“ in Shift-JIS is 91 5a.
If you run the self-extractor of TH4 tryout version (http://www.kt.rim.or.jp/~aotaka/am/gen_ts1.exe) within DOSBox-x, you will find that generated filenames are wrong both inside and outside DOSBox.
![da](https://user-images.githubusercontent.com/6635408/35907224-325a48aa-0be5-11e8-87fc-e6810e235465.png)

**Comment by joncampbell123** [comment]
There's code in DOSBox-X to convert all filenames given to the DOS kernel to uppercase on host. The leading byte of the Shift-JIS happens to be in the range that uppercase conversion mistakes for ASCII.

**Comment by joncampbell123** [comment]
You'll notice that when the errors happen the difference in byte value is 0x20, which in ASCII is the difference between uppercase A-Z and lowercase a-z.

**Comment by joncampbell123** [comment]
I committed a change that fixes the dir cache and local drive support not to garble SHIFT-JIS in PC-98 mode. There is one case left to implement for older programs that use FCBs, but I'm not aware of any to test against.

Can you compile from source to verify?

**Comment by leonier** [comment]
I don't know about what applications use FCBs on PC-98 DOS however at least the problem is fixed for TH4 after applying your patch to our source tree today.

By the way this patch of creating short filenames shouldn't be only applied to PC-98 mode but to the generic codepage 932 (or 936/949/950 would they be implemented) emulation.

Also, there is a possibility that Shift-JIS (and Big5) double-byte character uses 0x5c '\' and this still pose a problem in DOSBox-X for example it won't find the directory or file named in "ソソソソ" or "十禄彌". There is such log in stderr that says:

> LOG: FindNext: Filename '.\c\僜僜僜? from guest is non-representable on the host filesystem through code page conversion

> LOG: FindNext: Filename '.\c\廫榎? from guest is non-representable on the host filesystem through code page conversion

(My host codepage is 936 (GB-18030) but it's not the problem).

**Comment by joncampbell123** [comment]
Long-term, yes, the path parsing in DOSBox-X needs to be updated to take the code page into account. I noted in the source code a similar problem with Shift-JIS that happens to contain the backslash character.

Code page 932 would also need to be considered in non-PC-98 modes when DOSBox-X implements DOS/V emulation.

At the moment, IBM PC emulation does not support code page 932.

**Comment by joncampbell123** [comment]
https://github.com/joncampbell123/dosbox-x/issues/496

**Comment by joncampbell123** [comment]
I don't know of any that use FCBs and Shift-JIS, but the DOSLIB2 project I have here on Github has example DOS code that demonstrates enumerating directories with FCBs and that was the only way I could verify that code change worked.
