### ISSUE TITLE
Language forces itself to japanese every time I launch the emulator

### ISSUE THREAD

**Issue by ChrisNonyminus** [joncampbell123/dosbox-x#4968]
### Describe the bug

On the latest stable release, after installing the program, every time I opened the emulator, for whatever reason non-TTF render modes used the PC-98 font. Trying to fix this by opening the en_US language file only ended up making the language Japanese.
![image](https://github.com/joncampbell123/dosbox-x/assets/50080567/ce9a6e56-7e19-48d2-9a5c-fa3c700e6c05)

### Steps to reproduce the behaviour

1. Install the latest version.
2. Set English as the default language.
3. Open the emulator and set render mode to non-TTF
4. (Optionally) set language to English (this part sets it to japanese instead for whatever reason)

### Expected behavior

The font should be CP437 and the language should be english

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2024.03.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
As a workaround, you can start as English if you make language option empty in your conf file.
```
language=
```

**Comment by maron2000** [comment]
The latest nightly works as intended.
`dosbox-x -defaultconf -set language=es_es`

![image](https://github.com/joncampbell123/dosbox-x/assets/68574602/5d591717-dc77-40b8-b040-fa2c3416801d)
