### ISSUE TITLE
Windows 95 and screen resolution 1920x1080

### ISSUE THREAD

**Issue by pgcsw** [joncampbell123/dosbox-x#4976]
### Question

Hello

i've installed Windows 95 (OSR1) in dosbox-x according to this guide: https://github.com/joncampbell123/dosbox-x/wiki/Guide:Installing-Windows-95/c6894fd3c687213e3466603941f4b0490c42b898

I've installed the VBEMP driver (from the 032MB directory) because i'll use Windows 95 with a screen resolution of 1920x1080 with 256colors. But it is only a maximum screen resolution of 1280x1024 available in Windows 95. If I understand this guide correctly - chapter (Emulated video adapter and video mode), this should be possible to use a screen resolution of 1920x1080 in Windows 95 with the VBEMP driver. What am I doing wrong that i can't select a screen resolution of 1920x1080?

My win95.conf file is:

```
[sdl]
autolock=true
fullscreen=false
fullresolution=1920x1080

[dosbox]
title=Windows 95
memsize=32

[video]
allow high definition vesa modes=true
allow unusual vesa modes=true
allow low resolution vesa modes=false

[dos]
ver=7.0
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
IMGMOUNT 0 empty -fs none -t floppy
IMGMOUNT 1 empty -fs none -t floppy -size 512,15,2,80
IMGMOUNT C win95-hdd.img -ide 1m
IMGMOUNT D empty -t iso -ide 2m
BOOT C:
```

Thank you in advance.

Best regards

_I have tryed to use the VESAMOED command bevore i run Windows 95 to set the screen resolution of 1920x1080 according to this issue: https://github.com/joncampbell123/dosbox-x/issues/1187
But it does not work for me._ 

Screenshot:
![guest os_001](https://github.com/joncampbell123/dosbox-x/assets/167681259/0232de3a-98d2-4638-833e-96eda371965a)

**Comment by joncampbell123** [comment]
Please try adding the vmemsize option. Try vmemsize=8.

    [video]
    vmemsize=8

**Comment by pgcsw** [comment]
Thank you for your response.
I now see the mistake that i made.
I've the lines `"vesa modelist width limit=0"` `"vesa modelist height limit=0" ` overwritten and `vmemsize=8` not listed. Now it works and i can use the screen resolution of 1920x1080 with 256 colors in Windows 95.

Here is my working win95.conf file if this is of interest to other people.

```
[sdl]
autolock=true
fullscreen=true

[dosbox]
title=Windows 95
memsize=32

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0
allow high definition vesa modes=true
allow unusual vesa modes=true
allow low resolution vesa modes=false

[dos]
ver=7.0
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
IMGMOUNT 0 empty -fs none -t floppy
IMGMOUNT 1 empty -fs none -t floppy -size 512,15,2,80
IMGMOUNT C win95-hdd.img -ide 1m
IMGMOUNT D empty -t iso -ide 2m
BOOT C:
```

Thank you. 

Best regards.

![guest os_005](https://github.com/joncampbell123/dosbox-x/assets/167681259/72129fb8-430e-431b-bc41-dd046394c07a)
