### ISSUE TITLE
Crash when inserting CD-ROM iso into empty drive using Windows 95 / 98

### ISSUE THREAD

**Issue by Groberts93** [joncampbell123/dosbox-x#4988]
### Describe the bug

Having followed [the guide](https://dosbox-x.com/wiki/Guide%3AInstalling-Windows-98) for setting up Windows 98 on the wiki using Installation Method 2 (copying the contents of the CD-ROM), I added the following section under autoexec:

```
IMGMOUNT 0 empty -fs none -t floppy
IMGMOUNT 1 empty -fs none -t floppy -size 512,15,2,80
IMGMOUNT C hdd.img -ide 1m
IMGMOUNT D empty -t iso -ide 2m
BOOT C:
```

This setup works fine.  I can boot into Windows, access the C: drive, run programs, and I can see the A: and D: drives in My Computer.  However, when I attempt to insert a CD image into the D: drive using the GUI menu option, dosbox-x waits for about a second and then immediately exits.  No error message or log is displayed.

This seems to be independent of the iso file which is being inserted into the empty drive.  I've tried the known good Windows CD and some other software and the same thing happens.  Furthermore, I repeated the same steps with a Windows 95 iso and get the exact same behaviour, so it doesn't seem to be specific to the version of Windows I'm using.

I am using Windows 98 SE (OEM).  The same thing seems to happen with Windows 95 (Version C, OSR2.5, OEM).

Any help with this would be greatly appreciated.

### Steps to reproduce the behaviour

1.  Install Windows 95 or Windows 98 SE using the guide on the wiki
2. Boot into guest OS
3. From the Dosbox-X menu bar, select DOS -> Change current CD image...
4. Select an .iso image and hit OK

### Expected behavior

Expected this to update the "empty" CD-ROM drive (D:) with the inserted .iso image.

### What operating system(s) this bug have occurred on?

Windows 11 Pro Version	23H2 22631.3447

### What version(s) of DOSBox-X have this bug?

Release ver.2024.03.01 (VS XP SDL2 64-bit)

### Used configuration

```ini
[sdl]
autolock=true

[dosbox]
title=Windows 98
memsize=128

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
IMGMOUNT 0 empty -fs none -t floppy
IMGMOUNT 1 empty -fs none -t floppy -size 512,15,2,80
IMGMOUNT C hdd.img -ide 1m
IMGMOUNT D empty -t cdrom -ide 2m
```

### Output log

```text
None
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I tried booting PC-DOS2000.
It properly loads the CD-ROM driver and MSCDEX with the drive empty, but crashes when loading an ISO from GUI.
So not only Windows but same thing occurs when booting DOS. 
It works on native DOSBox-X.

**Comment by cjr118a** [comment]
I am having the same issue with this.  Just crashes after a second after selecting the image

**Comment by m-p-3** [comment]
Just one inconsistency I noted

> IMGMOUNT D empty -t iso -ide 2m
is mentioned in the bug description

Then it says 
> IMGMOUNT D empty -t cdrom -ide 2m
in the `[autoexec]`

For reference, running `imgmount -help` gives the following output

```
Mounts floppy, hard drive and optical disc images.
IMGMOUNT drive file [-ro] [-t floppy] [-fs fat] [-size ss,s,h,c]
IMGMOUNT drive file [-ro] [-t hdd] [-fs fat] [-size ss,s,h,c] [-ide controller]
IMGMOUNT driveNum file [-ro] [-fs none] [-size ss,s,h,c] [-reservecyl #]
IMGMOUNT drive file [-t iso] [-fs iso]
IMGMOUNT drive [-t floppy] -bootcd cdDrive (or -el-torito cdDrive)
IMGMOUNT drive -t ram -size size
IMGMOUNT -u drive|driveNum (or  IMGMOUNT drive|driveNum file [options] -u)
 drive               Drive letter to mount the image at.
 driveNum            Drive number to mount, where 0-1 are FDDs, 2-5 are HDDs.
 file                Image filename(s), or IMGMAKE.IMG if not specified.
 -t iso              Image type is optical disc iso or cue / bin image.
 -t hdd|floppy|ram   Image type is hard disk (inc. VHD/HDI)|floppy|RAM drive.
 -fs iso             Filesystem is ISO 9660 (auto-assumed for .iso/.cue files).
 -fs fat             Filesystem is FAT - FAT12, FAT16 and FAT32 are supported.
 -fs none            Do not detect filesystem (auto-assumed for drive numbers).
 -reservecyl #       Report # number of cylinders less than actual in BIOS.
 -ide controller     Specify IDE controller (1m, 1s, 2m, 2s) to mount drive.
 -size size|ss,s,h,c Specify the size in KB, or sector size and CHS geometry.
 -bootcd cdDrive     Specify the CD drive to load the bootable floppy from.
 -o partidx=#        Specify a hard disk partition number to mount as drive.
 -ro                 Mount image(s) read-only (or leading ':' for read-only).
 -u                  Unmount the drive or drive number.
 -examples           Show some usage examples.
```

So the correct command would be `IMGMOUNT D empty -t iso -ide 2m`

However I can also report that attempting to use the *DOS > Change the current CD image...* option in the GUI while running Win9x does crash Dosbox-x

![image](https://github.com/user-attachments/assets/91dc9ddf-1a09-41ae-a739-d07abb4a1d97)

Also, I initially tried to do it by following [this guide](https://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X#_mounting_an_empty_cd_rom_drive) and I don't think the syntax is correct)

**Comment by yllekz** [comment]
Same issue here. Not only does it crash, it crashes with no error and no warning. The workaround is to directly IMGMOUNT a random ISO and then change it out later.

**Comment by bbuske** [comment]
Same issue here..
