### ISSUE TITLE
How do I get it to emulate a certain cpu?

### ISSUE THREAD

**Issue by dfgdgdgfd** [joncampbell123/dosbox-x#499]
No matter whether I select 386, 486 or pentium, topbench always detects the same speed cpu as it does with ordinary dosbox.

**Comment by joncampbell123** [comment]
Correct. CPU instructions are generally handled one cycle per instruction (excluding I/O delay and video memory delay).

**Comment by joncampbell123** [comment]
However, topbench should detect the CPU according to cputype

**Comment by dfgdgdgfd** [comment]
In that case, is there any advantage in me using this over regular dosbox, where I usually have to adjust the cycles?

**Comment by joncampbell123** [comment]
DOSBox SVN has the same problem, as I understand it.

DOSBox and DOSBox-X do not attempt to make cycle-accurate emulation of each instruction. If you need that, you may want to consider pcem instead.

**Comment by dfgdgdgfd** [comment]
Ok, just one more question - why doesn't the sdl2 version of the program have a menu bar? (main/cpu/video/sound etc)

**Comment by joncampbell123** [comment]
The SDL2 version originated on Linux, and then I ported it to Windows by conservatively hacking off all Win32-specific hacks to make sure it could compile correctly. So, no menu bar, no OpenGL or Direct3D output, no system menu, nothing Windows-specific.
