### ISSUE TITLE
dosbox-x "libc++" problem?

### ISSUE THREAD

**Issue by EhanMMMZET** [joncampbell123/dosbox-x#4998]
### Question

i attempted to launch dosbox-x and when i did, it crashed as soon as i did so i then ran it in terminal for logs and i got this:

dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Applications/dosbox-x.app/Contents/MacOS/x86_64/libjxl.0.8.dylib (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

also, im running macos 10.15.7 at the moment.

### Have you checked that no similar question(s) exist?

- [x] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by EhanMMMZET** [comment]
weirdly, everything was perfectly fine a few months ago so i'm not sure why this problem is here now

**Comment by maron2000** [comment]
You may want to try the nightly builds.

**Comment by EhanMMMZET** [comment]
thanks, worked!
