### ISSUE TITLE
error compilation Ubuntu 14.04

### ISSUE THREAD

**Issue by legluondunet** [joncampbell123/dosbox-x#5]
Hello,

I tried to compile dosbox-x on Ubuntu but I obtain this error:

$make
....
Making all in gui
make[3]: entrant dans le répertoire « /home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui »
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -g -O2 -std=gnu++11 -Wall -mmmx -msse -msse2 -D_FILE_OFFSET_BITS=64 -Wno-strict-aliasing  -MT midi.o -MD -MP -MF .deps/midi.Tpo -c -o midi.o midi.cpp
In file included from midi.cpp:131:0:
midi_timidity.h:16:21: fatal error: SDL_net.h: Aucun fichier ou dossier de ce type
 #include "SDL_net.h"
                     ^
compilation terminated.
make[3]: *** [midi.o] Erreur 1
make[3]: quittant le répertoire « /home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui »
make[2]: *** [all-recursive] Erreur 1
make[2]: quittant le répertoire « /home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015 »
make: *** [all] Erreur 2

I already installed sdl2-net-dev package:

$ locate SDL_net.h
/usr/include/SDL2/SDL_net.h

Thank you for your help.

**Comment by DominusExult** [comment]
I could be wrong but AFAIK Dosbox-x is still SDL 1.2x dependent. So you need (lib)sdl and (lib)sdl_net NOT SDL2 or SDL2_net (though they can happily coexist).

**Comment by legluondunet** [comment]
of course, thank you. I thought Dosbox-x used the last SDL version, it solves my last compilation error, but...a few compilation lines later:

$ make
.....
g++  -g -O2 -std=gnu++11 -Wall -mmmx -msse -msse2 -D_FILE_OFFSET_BITS=64 -Wno-strict-aliasing    -o dosbox dosbox.o  debug/libdebug.a dos/libdos.a fpu/libfpu.a hardware/libhardware.a cpu/libcpu.a shell/libshell.a gui/libgui.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/gui_tk/libgui_tk.a libs/porttalk/libporttalk.a hardware/reSID/libresid.a -lasound -lm -ldl -lpthread -L/usr/lib/x86_64-linux-gnu -lSDL -lGL -lpng -lz -lpcap -lX11
gui/libgui.a(midi.o): dans la fonction « MidiHandler_timidity::close_all() »:
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:183: référence indéfinie vers « SDLNet_TCP_Close »
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:184: référence indéfinie vers « SDLNet_TCP_Close »
gui/libgui.a(midi.o): dans la fonction « MidiHandler_timidity::connect_to_server(char const*, int, _TCPsocket**) »:
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:214: référence indéfinie vers « SDLNet_ResolveHost »
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:220: référence indéfinie vers « SDLNet_TCP_Open »
gui/libgui.a(midi.o): dans la fonction « MidiHandler_timidity::timidity_write_data(void const*, int) »:
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:322: référence indéfinie vers « SDLNet_TCP_Send »
gui/libgui.a(midi.o): dans la fonction « MidiHandler_timidity::fdgets(char*, unsigned long) »:
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:339: référence indéfinie vers « SDLNet_TCP_Recv »
gui/libgui.a(midi.o): dans la fonction « MidiHandler_timidity::timidity_ctl_command(char*, char const*, ...) »:
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:248: référence indéfinie vers « SDLNet_TCP_Send »
gui/libgui.a(midi.o): dans la fonction « __static_initialization_and_destruction_0 »:
/home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src/gui/midi_timidity.h:39: référence indéfinie vers « SDLNet_Init »
collect2: error: ld returned 1 exit status
make[3]: *** [dosbox] Erreur 1
make[3]: quittant le répertoire « /home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src »
make[2]: *** [all-recursive] Erreur 1
make[2]: quittant le répertoire « /home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015/src »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /home/legluondunet/Bureau/Dosbox-X/dosbox-x05022015 »
make: *** [all] Erreur 2

**Comment by joncampbell123** [comment]
I've seen this before. Whoever wrote the Timidity support stuck SDL_net.h in there whether or not you want it. I'll see if I can separate Timidity support and SDL_net from one another in the code. If not, then I'll conditionally disable Timidity support without SDL_net support for now.

**Comment by joncampbell123** [comment]
Fixed it. all code in midi_timidity.h is effectively #ifdef'd out now if SDL_net.h was not detected. A real cleanup step would be to remove midi_timidity.h entirely because the MIDI handler object is not used anywhere else in the code. But I'm also assuming that someone out there still wants Timidity support.

**Comment by joncampbell123** [comment]
legluondunet please confirm the latest code compiles on your end without issues and I'll close the bug.

**Comment by legluondunet** [comment]
Dosbox now compiles ok on Ubuntu 14.04, thank you! :+1:
