### ISSUE TITLE
PC98: Game "Heart of Saphilamun (Horror of Cridewell 2)" does not work on Dosbox-X

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#5003]
### Describe the bug

Hi there!
I tried to get work PC98/X68 game "Heart of Saphilamun (Horror of Cridewell 2)", but it seems does not start on Dosbox-X. Cannot find what the problem is.

### Steps to reproduce the behaviour

Gamepacks to test:
https://coraksoft1.narod.ru/games/vn/Heart-of-Saphilamun/Heart-of-Saphilamun-PC98-Game-Jp-dosbox-x.7z (unwork)
https://coraksoft1.narod.ru/games/vn/Heart-of-Saphilamun/Heart-of-Saphilamun-PC98-Game-Jp-np2next.7z (working)
https://coraksoft1.narod.ru/games/vn/Heart-of-Saphilamun/Heart-of-Saphilamun-X68-Game-Jp-xm6-winx68k.7z (working)

### Expected behavior

To game start
Instead - error
![image](https://github.com/joncampbell123/dosbox-x/assets/7928889/cbd34600-3ea4-4c8b-88a1-66cb4d5f5072)

### What operating system(s) this bug have occurred on?

Windows 7 Ultimate

### What version(s) of DOSBox-X have this bug?

Dosbox-x 20240301 SDL1

### Output log

```text
https://coraksoft1.narod.ru/scr/2024-02/171552844280_kiss_3kb.png
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
You should be joking. The file you uploaded (unwork ver.) works just fine.

https://github.com/joncampbell123/dosbox-x/assets/68574602/0ef26d3b-e256-44d4-b991-e596a0c6db88

**Comment by Corak667** [comment]
Seems my mistake, need to reconfig.
I started from command line autoexec.bat. What params you you used to mount as A:?

**Comment by maron2000** [comment]
I did nothing special, unzip your file, mount it via gui, and launched the game as seen in the above video.
