### ISSUE TITLE
DontPanic demo (1993) is missing the fixed GTSR.exe

### ISSUE THREAD

**Issue by Dutchmagic** [joncampbell123/dosbox-x#5006]
### Describe the bug

Observation:

According to the .conf file, there should be a GUSMOD folder with a fixed GTSR.EXE file in it - unfortunately I'm unable to find this anywhere in the repo. 

### Steps to reproduce the behaviour

Download the DontPanic demo from Scene.org (https://files.scene.org/view/mirrors/flerp/.1/DEMO.'93/TechnoPhob93/demo/dontpani.zip)
Use the dosconfig file from the repository: https://github.com/joncampbell123/demotest/tree/master/unpacked/ftp.scene.org/pub/parties/1993/technophobia93/demo/dontpani.zip
Notice that the GUSMOD folder is empty

### Expected behavior

Expected behavior:
GTSR.EXE should be in the GUSMOD folder from the repo. 
The demo should work as expected.

### What operating system(s) this bug have occurred on?

Windows 10 (but does not matter)

### What version(s) of DOSBox-X have this bug?

Latest Tue, 30 Apr 2024 build

### Used configuration

```ini
[dosbox]
memsize=1

[cpu]
core=normal
cputype=486
cycles=20000

[gus]
gus=true

[autoexec]
REM -------- NEEDS GUSMOD --------
SET GUSMOD=43300,C:\GUSMOD
REM -------- THE INCLUDED GTSR DOESN'T WORK, SUBSTITUTE
COPY C:\GUSMOD\GTSR.EXE C:\GTSR.EXE
REM -------- RUN DEMO --------
@CALL THEMO.BAT
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
DOSBox-X NEVER provides files that you expect in a C drive so you have to fetch and put it yourself.

**Comment by Dutchmagic** [comment]
According to the CONF files, it's a fixed .exe that was created by the X-team?

**Comment by Dutchmagic** [comment]
As an example - look at the DOSCONF for the FLOP 1995 demo. In order to make this demo work, a TSR was created and added to the repo. For the DontPanic demo, there should have been a GUSMOD, but that file is no longer in the repo.

**Comment by maron2000** [comment]
That's a problem of the dosconf side, not DOSBox-X, right?
DOSBox-X never follow up what is missing.

**Comment by Dutchmagic** [comment]
It’s Jon’s demo dosconfig repo that’s missing the file yes. I asked on discord if I should file a ticket, which I then did.

**Comment by maron2000** [comment]
You should report to the appropriate [repository](https://github.com/joncampbell123/demotest).
This is the third time I'm mentioning, this is NOT a problem on the DOSBox-X side.

**Comment by Dutchmagic** [comment]
I’ll talk to him on discord. Didn’t know I could open a ticket against his releases demo repo.
