### ISSUE TITLE
Raspberry Pi 5 build

### ISSUE THREAD

**Issue by actraiser30** [joncampbell123/dosbox-x#5008]
### Question

Hello I'm trying to build/compile Dosbox-X on a Raspberry Pi 5 in Raspbian bookworm but it fails on the dependencies packages:

automake libncurses-dev nasm libsdl-net1.2-dev libpcap-dev libfluidsynth-dev ffmpeg libavdevice58 libavformat-dev libswscale-dev libavcodec-dev

I get an unmeet dependencies packages error and an some of them are not installable error

Can you help me?

Thanks 

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by actraiser30** [comment]
It's not working similar errors again

https://ibb.co/FHy8qgR

**Comment by maron2000** [comment]
You should ask Raspbian to fix the dependency flaw.
Or you can try building with ffmpeg disabled.
`--disable-avcodec`
Refer to the build instructions for details.

**Comment by maron2000** [comment]
According to Raspberry pi official page, the command is slightly different from yours.

```
sudo apt install libtool autogen autoconf 
automake libncurses-dev gcc g++ make 
libncurses-dev nasm libsdl-net1.2-dev 
libsdl2-net-dev libpcap-dev libslirp-dev 
fluidsynth libfluidsynth-dev libavformat-dev 
libavcodec-dev libavcodec-extra libswscale-dev 
libfreetype-dev libxkbfile-dev libxrandr-dev 
```

https://www.raspberrypi.com/news/read-floppy-disks-and-cd-roms-with-raspberry-pi-5-magpimonday/

**Comment by actraiser30** [comment]
Thanks for the help

Will try and let you know

**Comment by maron2000** [comment]
That is good news. You can close this issue since it is solved.

**Comment by actraiser30** [comment]
Ok,just hope in a future release to add more cores support in the instance of dosbox than just one to improve performance 

Thanks

**Comment by actraiser30** [comment]
Thanks I'm not a genius

But what about using the total frequency of all cpu cores instead of searching for more cores
Bypass the search of more cores.and focus on the mhz

For example pi4 total frequency is 7200 mhz

Thanks
