### ISSUE TITLE
NE2000 on Linux?

### ISSUE THREAD

**Issue by sduensin** [joncampbell123/dosbox-x#501]
I've compiled DOSBox-X on Ubuntu 17.10 x86_64 with no issues.  However, when I load a packet driver for NE2000 I get a network address of FF:FF:FF:FF:FF:FF.  Shouldn't I be seeing the MAC from the conf file?

As it is, no data moves in or out.  :-/

**Comment by joncampbell123** [comment]
NE2000 support requires to you specify the interface.

Look at the log output on the console, and if enabled, to log.txt.

**Comment by sduensin** [comment]
Yeah, I did that.  One interface locks things up, the other "works" but I still get the bad MAC address.

**Comment by joncampbell123** [comment]
Then I suspect the one that produces the bad MAC addresses isn't the right interface.

As NE2000 emulation came from Bochs, it should show the same way the interfaces and the index to them. Are you certain you're not trying to use 'lo' (local loopback) as the interface to connect to?

**Comment by sduensin** [comment]
First, thank you for the amazingly rapid feedback.  Much appreciated!

Second, I figured it out!  Total user failure on my part.  I was using:

`NE2000.COM 0x60 3 300`

I *should* have been using:

`NE2000.COM 0x60 0x3 0x300`

Hex FTW!  :-)
