### ISSUE TITLE
VGA DAC behavior dispute: What does the VGA DAC really do between read and write index?

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#502]
DOSBox-X had not problems with certain demos when writing port 3c7h set the read index, and writing port 3c8h set the write index. But other demos had an off by one palette issue.

DOSBox-X was recently updated to follow DOSBox SVN's behavior where writing port 3c7h sets read index X and write index X + 1, and 3c8h write index X and read index X - 1. But while this fixed some demos, other demos develop a color palette issue.

The question is: What VGA hardware exactly does this odd behavior between read and write index? Can it be narrowed to specific SVGA chipsets? In fact, why would a SVGA manufacturer waste silicon implementing two DAC indexes like that when it's more economical to just have ONE index and read/write increment that one index?

In the meantime, perhaps another option could be added to dosbox.conf to change VGA DAC behavior manually for specific demos.

**Comment by joncampbell123** [comment]
The good news is that behavior on each DOS machine you test can be verified using only DEBUG.COM and some poking at ports 3c7h, 3c8h, and 3c9h. It is unlikely the BIOS will interfere with VGA DAC ports in the normal act of putting text on the screen even if you had set it to INT 10h mode 0x13.

**Comment by joncampbell123** [comment]
I do have one guess which SVGA chipset probably did the read = write + 1 behavior: Tseng ET4000 chipsets.

**Comment by joncampbell123** [comment]
http://www.osdever.net/FreeVGA/vga/colorreg.htm

**Comment by sikthehedgehog** [comment]
I wouldn't expect this behavior to be consistent among VGA clones to be
fair.

And yeah no idea why VGA had two separate commands for read and write for
starters. Maybe it needed to cache values in different ways and that's what
the command is for? (for writing you'd want to make sure all three values
are ready to write together, for reading maybe you need to wait for the
RAMDAC to get freed before the values can be fetched... or something? dunno
how VGA works here)

As for the offset by one: I could see it happening if internally the card
did preincrement in one case and postincrement in the other case.

**Comment by joncampbell123** [comment]
I just pulled out an old Compaq Elite laptop, and I see behavior that generally matches the behavior written in src/hardware/vga_dac.cpp. I think it's a Paradise SVGA chipset. I used DEBUG.COM.

At the DOS prompt I can set the background color of the text mode as expected:
- o 3c8,0
- o 3c9,1f
- o 3c9,1f
- o 3c9,1f

After that, reading 3c8 reads 0x01 (as expected)

I can read back index 0 as normal:
- o 3c7,0
- i 3c9
- i 3c9
- i 3c9

Reading 3c7h also works as indicated in src/hardware/vga_dac.cpp where writing an index to 3c7h reads back 0x03 from 3c7h, and writing an index to 3c8h reads back 0x00 from 3c7h.

Here's where it gets weird:
- o 3c7,ff
- o 3c9,1f
- o 3c9,1f
- o 3c9,1f

That changes color palette 0, not 0xFF.

Even weirder:
- o 3c8,ff
- i 3c9
- i 3c9
- i 3c9

That apparently reads index 0.

General behavior suggests that it's one register, that may increment automatically somehow if you start as if writing, but read or the other way around. Port 3C7h suggests to me that the DAC keeps track of it, or else the low two bits wouldn't keep track of it.

As mentionted in the source, perhaps fixing it up to actual hardware can be done without breaking Wari.

So that's the behavior of Paradise SVGA chipsets. I'll check other old hardware to see what other SVGA chipsets do.

**Comment by joncampbell123** [comment]
Additional thoughts: So based on this, src/hardware/vga_dac.cpp is somewhat wrong. The VGA DAC index acts as if it is set to the value provided by either 3c7h or 3c8h, and the DAC sets an internal flag indicating the direction of data it expects. If you follow that expectation, the DAC index you wanted is accessed properly. If data moves opposite of the DAC's expectations, then the index is incremented before handling the data. src/hardware/vga_dac.cpp doesn't follow this, but treats read/write as two separate indexes that are set one apart on writing the index, where write = read + 1, but apparently to avoid breaking Wari, they're not kept in sync during the palette reading/writing.

**Comment by joncampbell123** [comment]
I just noticed that if you do:
- o 3c7,ff
- o 3c9,1f
- o 3c9,1f
- o 3c9,1f
- i 3c8
00
- i 3c7
03

Despite having written a read index, then writing a DAC color (off by 1), the DAC still thinks it's in read mode (0x03)

- o 3c8,0
- i 3c7
00

**Comment by joncampbell123** [comment]
Hold on, the Paradise SVGA chipset seems to exhibit behavior that isn't just merely reading off by one color.

I'm starting to think that the off by one color behavior can be explained better if you think of the DAC as pre-reading the DAC color and buffering it for read, instead of just reading off by one.

Example 1 (perhaps the DAC had buffered palette index 0 and was returning it before 0xFF?):
- o 3c8,ff
- i 3c9
00
- i 3c9
00
- i 3c9
00

Example 2 (Ask to write 0xFF, the read from 3C8h seems to flush the buffer, and 3C9h returns the right entry):
- o 3c8,ff
- i 3c8
ff
- i 3c9
3f
- i 3c9
3f
- i 3c9
3f

I'm starting to think the Paradise DAC loads the DAC color into a buffer, and 3C9h returns that buffered color when you write 3C7h. But if you write 3C8h and then read 3C9h, you can confuse the DAC into returning what it buffered before then buffering the index you just asked for.

**Comment by joncampbell123** [comment]
Ah, OK. Maybe there's a read index and write index after all. Check this out:

Example (set read index 7, write index 0):
- o 3c7,7
- o 3c8,0
- i 3c9
2a
- i 3c9
2a
- i 3c9
2a
- i 3c9
00
- i 3c9
00
- i 3c9
00

It first returns color 7, then color 0.

**Comment by joncampbell123** [comment]
Writing x to port 3c7h then color palette RGB to 3c9h however does modify x + 1 instead.

**Comment by joncampbell123** [comment]
- o 3c8,0
- o 3c7,7
- i 3c9
2a
- i 3c9
2a
- i 3c9
2a
- i 3c9
1f
- i 3c9
1f
- i 3c9
1f

Switching the order is more normal. It returns color 7, then color 8.

**Comment by joncampbell123** [comment]
The original reason for starting this issue, the palette corruption in Crystal Dream II, was not related to the VGA DAC ports at all but was actually palette corruption during VGA modesetting that was resolved. This discussion however did provide some enlightening information on VGA DAC port behavior that led to palette issue fixes for old DOS software regardless.
