### ISSUE TITLE
Suggestion: Different start banner when program shells to DOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#503]
Plain DOSBox displays a different (one-line) startup banner when an application shells out to DOS, but it seems that DOSBox-X displays the same banner as it does when it launches.

Because we probably don't need the full introduction when we're shelling out to DOS from an application, could we have an alternate (one-line) startup banner for that purpose? It's a small thing, but it seems friendly...

**Comment by joncampbell123** [comment]
Sounds good to me.

**Comment by emendelson** [comment]
I tried doing it myself by lifting some code from SVN, but wasn't expert enough to get the non-/INIT banner to display without the standard banner... Sorry not to be more competent!

**Comment by joncampbell123** [comment]
Done.

**Comment by emendelson** [comment]
Excellent! Thank you!
