### ISSUE TITLE
Please add the "FIND" command to SHELL_Cmd cmd_list[]

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#5033]
### What you want

Please add the FIND command to SHELL_Cmd cmd_list[]

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Seems that you are aware of the cmd_list[], it mentions that only shell commands are included, and programs are not applicable.

**Comment by Arthur3032** [comment]
FIND is included in the shell command, in general DOS, not FIND.com / FIND.exe
