### ISSUE TITLE
Can't get MIDI Fluidsynth to recognize SF2 Sound font file in Arch Linux

### ISSUE THREAD

**Issue by zono50** [joncampbell123/dosbox-x#5034]
### Question

I've been dealing with this issue for almost 2 days. Tried doing alsa, pulseaudio, deleted and broke my sound system about 2 or 3 times getting this to work. I also tried doing overrides, and installed flatseal and gave my dosbox sandbox the entire file system access, and for whatever reason it will not recognize my SF2 file that i downloaded. I'm using the GeneralUser_GGS_v1.471.sf2, and i'm doing my command as such -

flatpak run com.dosbox_x.DOSBox-X -conf ~/.var/app/com.dosbox_x.DOSBox-X/config/dosbox/dosbox-x.conf

I have also attached my dosbox.conf file located at the following path - /home/zono50/.var/app/com.dosbox_x.DOSBox-X/config/dosbox/dosbox-x.conf

i have also attached my dosbox-x.conf file:

[midi]
mpu401=intelligent
mididevice=fluidsynth
midiconfig=/home/zono50/MIDI/SoundFonts/GeneralUser_GS_v1.471.sf2
fluid.samplerate=44100
fluid.driver=pulseaudio
fluid.soundfont=/home/zono50/MIDI/SoundFonts/GeneralUser_GS_v1.471.sf2 
fluid.buffersize=256
fluid.periods=16
fluid.threads=1
fluid.reverb=yes
fluid.chorus=yes
fluid.reverb.roomsize=0.61
fluid.reverb.damping=0.23
fluid.reverb.width=0.76
fluid.reverb.level=0.57
fluid.chorus.nr=3
fluid.chorus.level=1.2
fluid.chorus.speed=0.3
fluid.chorus.depth=8.0
fluid.chorus.type=0

If I run fluidsynth with pulseaudio, i can get it to play midis so it is working. I simply can't get dosbox-x to recognize my soundfont file in arch linux.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Make sure you have really set required permissions.
I don't use flatpak, but the soundfont loads fine so I think DOSBox-X has nothing to be blamed.
![fluidsynth](https://github.com/joncampbell123/dosbox-x/assets/68574602/aaa32170-28ac-4721-9e1f-5533b59e55ca)

**Comment by zono50** [comment]
As stated previously, I opened up my whole home folder to flatpak so the application would be able to access not only the soundfont file, but the config file as well. I checked the permissions on the soundbank file as well and it's owned by my user and group

-rwxr-xr-x 1 zono50 zono50  30M Feb  7  2017  GeneralUser_GS_v1.471.sf2

also the permissions on my conf file are as follows :

looks like my conf file was owned by root, but i changed it and got the same error.

-rwxr-xr-x 1 zono50 zono50  99K Jun  2 19:31 dosbox-x.conf

![image](https://github.com/joncampbell123/dosbox-x/assets/8764705/24f489fd-73de-4ce2-856a-03dd468b650d)

**Comment by maron2000** [comment]
This is my first time I installed via Flatpak.
Seems to work fine.

![flatpak](https://github.com/joncampbell123/dosbox-x/assets/68574602/73df3f79-5e43-4c7a-bba0-28bb0feb9392)

**Comment by joncampbell123** [comment]
Second issue I've run into: Fluidsynth needs an SF2 file that uses the RIFF chunk structure, and sometimes I find older files that are not RIFF.

**Comment by zono50** [comment]
Do you have quotes at all around the sound font file name or is dosbox
perfectly okay with those spaces?

**Comment by zono50** [comment]
Here is my dos output that I got, it can't use the soundfont file for some
reason

[image: image.png]

[image: image.png]

whether i put quotes around fluid.soundfont or not makes no difference, the
dosbox can't seem to pick it up. I know it's not a version issue cause we
are using the same soundfont file. Wonder what else could be preventing it.

**Comment by zono50** [comment]
can i see your dosbox.conf file midi section just to make sure i have everything correct on mine?
