### ISSUE TITLE
PC-98 MEM command requires a very specific DOS version

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#5060]
### Describe the bug

A PC-98 version of MEM.EXE was added, which is nice, but it will only run if the DOS version is set to a very specific value (version 6.20).

### Steps to reproduce the behaviour

Start DOSBox-X with machine=pc98.
Type mem.
Observe complaint about DOS version in Japanese.
VER SET 3 30.
Observe complaint about DOS version in Japanese.
VER SET 3 0.
Observe complaint about DOS version in Japanese.
VER SET 6 20.
Program displays memory list.

### Expected behavior

Like the IBM PC MEM version from FreeDOS, I expect it to be able to list memory regardless of DOS version, within reasonable limits of course. I don't expect MEM to reliably list memory with a DOS version less than 3.0 but I do expect it to be more flexible than this.

https://github.com/joncampbell123/dosbox-x/pull/5059

### What operating system(s) this bug have occurred on?

Linux x86_64

### What version(s) of DOSBox-X have this bug?

Latest build

### Used configuration

```ini
[dosbox]
machine=pc98
```

### Additional information

A link was given to the source code of MEM: https://github.com/lpproj/mem.nec/

If I am able to compile it from source, I can remove the version check. Then use the various PC-98 boot disks to see how well it works on any version of DOS other than 6.20.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Sorry for the confusions, but I can't reproduce. Tested the latest nightly VS x64 SDL1. 

![image](https://github.com/joncampbell123/dosbox-x/assets/68574602/f112c2d7-cab4-4e85-a96e-def6918a1331)

![image](https://github.com/joncampbell123/dosbox-x/assets/68574602/578e1bf9-4e3b-4263-a4a7-34bb3d06c5a3)

![image](https://github.com/joncampbell123/dosbox-x/assets/68574602/d8830604-8132-4d61-8a48-6539f70a988e)

**Comment by maron2000** [comment]
I don't get any messages in Japanese.
I suppose you have a MEM.exe in some path in your environment?

**Comment by joncampbell123** [comment]
Now that you mention it, at the root of my DOSBox-X PC-98 configuration I copied MEM.EXE from a MS-DOS 6.20 bootdisk several years ago. I'll remove it and try again.

**Comment by joncampbell123** [comment]
It works.
