### ISSUE TITLE
"Shell" configuration option is broken and should be replaced

### ISSUE THREAD

**Issue by steviator** [joncampbell123/dosbox-x#5063]
### Describe the bug

The shell option in the config.sys section of the configuration file does not behave like the shell option in MS-Dos config.sys, because it is restricted only to the unwritable drive Z:

Since it has no valid values other than the names of the two included command interpreters on drive Z, it should be changed in name and appearance to prevent confusion with the more useful MS-Dos config.sys shell= option which allowed a user to select any shell they wanted.

This switch could more easily and accurately be represented as a boolean 4dos on/off switch, since that it is its only effective functionality, and that would be less likely to cause breakage when users confuse this crippled option for the one with 
the exact same name in MS-Dos config.sys.

### Steps to reproduce the behaviour

1. Put value other than z:\command.com or z:\4dos\4dos.com into shell= configuration setting
2. Fail

### Expected behavior

UI element should not impersonate config.sys options with new novel ones that don't behave the same as the originals. 
UI elements should not show a variable when they really have boolean functionality.

### What operating system(s) this bug have occurred on?

All

### What version(s) of DOSBox-X have this bug?

Don't know

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Dobby233Liu** [comment]
You can put your shell program in the drivez directory so that it will appear in the Z: drive and doing smth like `shell = Z:\NC\NC.EXE` will work

**Comment by steviator** [comment]
It turns out that there is a way to mount disks before config.sys runs (install=mount.com), which is something that is - at least for my addled brain - not an obvious way that immediately springs to mind. 

I'm surprised there's not a way to make the drive mounts from the menu permanent, or to spe cify permanent mounts in the config file, that would have my last few hours of dinking around much less frustrating. Even a note somewhere in the UI that this is the trick for making permanent hard drive mounts would have been great.

I wasn't aware that the z: drive was just a bunch of files somewhere that I could monkey with. I've been so focused on trying to find someway to fix it the way I want that I didn't even consider that. At any rate I was completely wrong.
