### ISSUE TITLE
Sword of the Samurai (GOG) "Filename not found"

### ISSUE THREAD

**Issue by Vitoria90** [joncampbell123/dosbox-x#5067]
### Describe the bug

On regular DOSBox, the game starts normally, but on DBX it shows the initial splash screen just as on DOSBox, but then gives out an error "Filename not found". This also happens if you manually run SAMURAI.COM or SAMLOADR.bat.

### Steps to reproduce the behaviour

1. Install game from either GOG Galaxy or GOG's offline installer.
2. Try to run the game through DOSBox-X in any way (change the default shortcut to use DBX instead of regular DB, manually mount the folder in DBX and run SAMLOADR.bat or SAMURAI.COM)
3. "Filename not found" error

### Expected behavior

For the game to boot into the next screen where it asks you if you have a joystick and then what kind of soundcard you have.

### What operating system(s) this bug have occurred on?

Windows 11 Home v10.0.22631

### What version(s) of DOSBox-X have this bug?

2024.03.01 (VS XP SDL1 64-bit)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by MX9000** [comment]
Try typing LOADFIX SAMURAI.COM

**Comment by Vitoria90** [comment]
Thank you, I was unaware of this command, will keep it in mind in the future.
