### ISSUE TITLE
Disable IME input method for SDL2

### ISSUE THREAD

**Issue by liuzhier** [joncampbell123/dosbox-x#5072]
### Is your feature request related to a problem? Please describe.

I encountered a problem with the Chinese input method popping up in the win98 game of DOSBOX-X.

### What you want

May I ask if it is possible to provide users with a feature to disable the IME input method?

### Describe alternatives you've considered

 Please refer to a commit in SDLPAL: https://github.com/sdlpal/sdlpal/commit/e7578009233946171f58b3a6338cf6562e1f041a

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Did you try `ime=false` option?

**Comment by liuzhier** [comment]
![QQ截图20240628143004](https://github.com/joncampbell123/dosbox-x/assets/83107010/e30c634d-fc64-43a1-b1c6-475d3a2ac9b1)
May I ask if this is the case......
It doesn't seem to work......

**Comment by maron2000** [comment]
No, you shouldn't add the option. It's already located in the [dosbox] section, probably `ime=auto`.

Some explanation can be found here.
https://github.com/joncampbell123/dosbox-x/wiki/Guide%3AEast-Asian-language-support-in-DOSBox%E2%80%90X

**Comment by liuzhier** [comment]
Thank you for @maron2000 help.  It has been resolved and this issue will be closed.
