### ISSUE TITLE
NukedOPL sounds wrong in the latest commit

### ISSUE THREAD

**Issue by huytd2109** [joncampbell123/dosbox-x#5078]
### Describe the bug

In the latest commit (actually, I found this in commit cf76664), if you use "oplemu=nuked", any program and game using OPL will sound wrong. The only workaround for this is to change "oplemu" to something else (preferably default). Here are some samples:
- Wolfenstein 3D: https://drive.google.com/file/d/1oP-LslOAdXhD7OQoSSWrV72ysUsHLkHf/view?usp=sharing
- Cosmo's Cosmic Adventure: https://drive.google.com/file/d/1TDGnC6gWCaQXEcvd7csHCmG4PYGFU1C8/view?usp=sharing 

### Steps to reproduce the behaviour

You just need to change "oplemu=nuked", run any game with OPL support and listen to the music and sound.

### What operating system(s) this bug have occurred on?

Windows 11 23H2

### What version(s) of DOSBox-X have this bug?

SDL2 MinGW, commit b243a006c11a2c7042c6f1dfe0f505aba43297c0, commit cf76664f749eaab75e2d3329915f3c9707603dce

### Used configuration

```ini
[sblaster]
sbtype                       = sb16
sbbase                       = 220
irq                          = 7
listen to recording source   = false
recording source             = silence
dma                          = 1
hdma                         = 5
enable speaker               = false
sbmixer                      = true
oplmode                      = auto
oplemu                       = nuked
oplrate                      = 49716
oplport                      = 
retrowave_bus                = serial
retrowave_port               = 
hardwarebase                 = 220
goldplay                     = true
blaster environment variable = true
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Was this the breaking change?

https://github.com/joncampbell123/dosbox-x/commit/b951519a39be7c2132789554bb2c3df6ead4ff86

**Comment by huytd2109** [comment]
I have tested both 7017ed5d006e286b57068f977291732ddcf951a5 and b951519a39be7c2132789554bb2c3df6ead4ff86 and confirmed that b951519a39be7c2132789554bb2c3df6ead4ff86 was the breaking change.

**Comment by StevenSYS** [comment]
Here you go!
#5079

**Comment by joncampbell123** [comment]
Nice. If you can confirm that here within the next hour or two, I will start the July 1st release.

**Comment by huytd2109** [comment]
Confirm that the fix works for VS build. Closing now.
