### ISSUE TITLE
Build failure of 2024.07.01 Windows installer release and alternative download link

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#5086]
### Describe the bug

The latest release version of 2024.07.01 Windows installer build failed.
Download the [portable builds](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2024.07.01) instead if you wish to use the July release, or try the [nightly builds](https://github.com/joncampbell123/dosbox-x/issues/3822).
Using the XP installer maybe an alternative, although not recommended.

Edit2: The following instructions are not valid anymore due to expiration.
~~The following link includes an identical build of the release.~~
~~Edit: Due to a [bug](https://github.com/joncampbell123/dosbox-x/pull/5093) the version number is shown as 2024.03.01, which is fixed after the release.~~

~~https://github.com/joncampbell123/dosbox-x/actions/runs/9754660669~~

~~Scroll down to the `Artifacts` section of the link above.~~
~~You must be logged in to github to download the file.~~

### Steps to reproduce the behaviour

None

### What operating system(s) this bug have occurred on?

Windows 7 and after

### What version(s) of DOSBox-X have this bug?

2024.07.01 Release Windows installer

### Additional information
Version number shows 2024.03.01 as mentioned above.
![image](https://github.com/user-attachments/assets/1f8e7dd6-5d01-4e9c-8b68-cbd6dff67a83)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by scrutinizer80** [comment]
Thanks!
This should also be added to the dosbox-x.com website

**Comment by maron2000** [comment]
Hopefully next release will be fixed by PR #5087 but remain this issue open to make people aware of this.

**Comment by mralext20** [comment]
be aware that github only stores artifacts for up to 90 days - https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#about-workflow-artifacts

**Comment by rohded3691** [comment]
Is the July 1 version still not available?   I downloaded from the link and still says 0301 version.
 When will it be on the DOSBOX X page?

**Comment by NathanWailes** [comment]
I'm confused; am I supposed to download the latest release at https://github.com/joncampbell123/dosbox-x/releases ?

**Comment by HunterZ** [comment]
Artifacts are expired.

**Comment by maron2000** [comment]
Closing this issue since 2024.10.01 Windows installer is uploaded successfully.

**Comment by rohded3691** [comment]
Does that mean there is a Oct 1 version?

I only see the July version listed.

**Comment by maron2000** [comment]
I see both Oct and July release  notes.
Of course. Installer of July release is not available.
Where did you search?

https://github.com/joncampbell123/dosbox-x/releases

**Comment by rohded3691** [comment]
My mistake.  I was just looking at the DOSBOX X webpage.    It still shows July.   The GITHUB does show the correct one.

 

Thanks

**Comment by rohded3691** [comment]
When I downloaded the GITHUB version,  it does not included the setup.exe.   Am I missing something?

**Comment by maron2000** [comment]
The update for the link to the latest release in the website is on its way (#5230).
