### ISSUE TITLE
vs 2015 compile error...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#511]
Hello,
when i trying to compile dosbox-x master branch then i get an error:
c3861 'min': identifier not found
in file core_prefetch.cpp

thanks.

**Comment by emendelson** [comment]
Try compiling under VS 2017.

**Comment by joncampbell123** [comment]
It's not that. There's a bit of disagreement between GCC and VS2017 about min() vs std::min().

However, try putting #include <algorithm> at the top of the source file and see if that helps.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
#include what???

**Comment by joncampbell123** [comment]
#include \<algorithm\>

Sorry, forgot that \< and \> have special meaning here.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Yes, thank you.
now it's working.

**Comment by joncampbell123** [comment]
Good, I'll commit a change to include the fix.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Thanks.
and keep on your excellent work. :-)
