### ISSUE TITLE
4dos not starting when requested in config file system initialisation

### ISSUE THREAD

**Issue by crestr1** [joncampbell123/dosbox-x#5116]
### Describe the bug

![Screenshot from 2024-07-11 07-07-28](https://github.com/user-attachments/assets/042d4c3b-f0ea-4037-87ad-172a85222229)
A cut from the tail end of my config file:
rem         = This section is DOS's CONFIG.SYS file, not all CONFIG.SYS options supported
break       = off
numlock     = 
shell       = 4DOS.COM
dos         = high, umb
fcbs        = 0
files       = 0
country     = Australia
lastdrive   = a
set path    = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL
set prompt  = $P$G
set temp    = 
install     = 
installhigh = 
device      = 
devicehigh  = 

### Steps to reproduce the behaviour

request 4dos in tail of config file
[dosbox-x.conf.txt](https://github.com/user-attachments/files/16185515/dosbox-x.conf.txt)

### Expected behavior

"ls" command should work after program loads ;see initial screenshot

### What operating system(s) this bug have occurred on?

Linux  Mint: see additional info

### What version(s) of DOSBox-X have this bug?

Pull from git 10 July 24

### Used configuration

```ini
See end additional info
```

### Output log

```text
see attached screenshot "ls" command failed after Dosbox-x  load
```

### Additional information

System:
  Kernel: 6.5.0-35-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33
    wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Mini-pc System: Micro (HK) Tech product: Venus series v: N/A serial: <superuser required>
  Mobo: Shenzhen Meigao Equipment model: F7BSC serial: <superuser required>
    UEFI: American Megatrends LLC. v: 1.09 date: 11/20/2023
CPU:
  Info: 8-core model: AMD Ryzen 9 7940HS w/ Radeon 780M Graphics bits: 64 type: MT MCP
    smt: enabled arch: Zen 3 rev: 1 cache: L1: 512 KiB L2: 8 MiB L3: 16 MiB
  Speed (MHz): avg: 462 high: 1397 min/max: 400/5263:6228:5903:5583:5743:5423:6067 cores: 1: 400
    2: 1397 3: 400 4: 400 5: 400 6: 400 7: 400 8: 400 9: 400 10: 400 11: 400 12: 400 13: 400 14: 400
    15: 400 16: 400 bogomips: 127763
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD driver: amdgpu v: kernel pcie: speed: 16 GT/s lanes: 16 ports: active: HDMI-A-1
    empty: DP-1, DP-2, DP-3, DP-4, DP-5, DP-6, DP-7, HDMI-A-2 bus-ID: c4:00.0 chip-ID: 1002:15bf
    class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 96 s-size: 1016x571mm (40.0x22.5") s-diag: 1165mm (45.9")
  Monitor-1: HDMI-A-0 mapped: HDMI-A-1 model: Lenovo L28u-35 serial: <filter> res: 3840x2160
    hz: 60 dpi: 157 size: 620x350mm (24.4x13.8") diag: 712mm (28") modes: max: 3840x2160
    min: 640x480
  OpenGL: renderer: GFX1103_R1 (gfx1103_r1 LLVM 15.0.7 DRM 3.54 6.5.0-35-generic)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2 direct render: Yes
Audio:
  Device-1: AMD driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16 bus-ID: c4:00.1
    chip-ID: 1002:1640 class-ID: 0403
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor driver: snd_pci_ps v: kernel
    pcie: speed: 16 GT/s lanes: 16 bus-ID: c4:00.5 chip-ID: 1022:15e2 class-ID: 0480
  Device-3: AMD Family 17h HD Audio driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s
    lanes: 16 bus-ID: c4:00.6 chip-ID: 1022:15e3 class-ID: 0403
  Sound Server-1: ALSA v: k6.5.0-35-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes[](url)
[dosbox-x.conf.txt](https://github.com/user-attachments/files/16185292/dosbox-x.conf.txt)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by crestr1** [comment]
[Dosbox-x start log.txt](https://github.com/user-attachments/files/16185841/Dosbox-x.start.log.txt)
complete startup log

**Comment by maron2000** [comment]
Default settings works fine.
I think you screwed up something in your .conf file.

`dosbox-x.exe -defaultconf -set shell=4dos.com`

BTW, `ls` is not supported by 4DOS.COM but DOSBox-X provides the executable in Z: drive.

![image](https://github.com/user-attachments/assets/bb3d8114-4ebd-437c-b3fb-f7691f6977b8)

**Comment by crestr1** [comment]
4Dos is there,I thought 4dos was more like a shell, thought it had its own prompt and bigger command memory. 

'ls' problem is path to z is gone by overwrite of my paths. not a 4dos problem
 
We really need TCC/LE  11.00    2010-02-08 - 11:21  3245 KB  current build Version 11.40 which is more like a real shell

**Comment by crestr1** [comment]
Fix missing 'ls' Command add "%PATH%;"   in front of your own unilateral path directives to add your new paths to existing paths to Z

**Comment by crestr1** [comment]
discussion on 4dos and TCC/LE :https://4dos.info/v4dos.htm
