### ISSUE TITLE
Problem with DOSBox-X if you run Windows as a guest

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#5119]
### Describe the bug

This is what happens every time I run Windows as a guest. So far I have only run Windows 98 SE Plus, in a dynamic VHD, created with Disk Manager for Windows 11 (latest upgrade), with allocation unit size 32k, 32 GB and FAT32, after experiencing this for the first time.
Here is the screenshot.
![image](https://github.com/user-attachments/assets/d2e11e11-011a-477b-b9f1-4c254e1316d5)
Here is the config.
[w98.zip](https://github.com/user-attachments/files/16196298/w98.zip)

### Steps to reproduce the behaviour

Run Windows as a guest in DOSBox-X and see what happens. You can also compare different Windows that DOSBox-X can run.

### Expected behavior

I expect old-school Windows to run perfectly without an issuer in DOSBox-X.

### What operating system(s) this bug have occurred on?

Windows 10 Home 21H2

### What version(s) of DOSBox-X have this bug?

The latest builds, MinGW Win64

### Used configuration

```ini
Check the description. :)
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Is Windows using the stock S3 drivers?

The S3 drivers tend to use VESA BIOS extensions to setup the video mode and they assume modes, rather than query.
