### ISSUE TITLE
WordStar graphic page preview no longer working properly with latest DOSBox-X

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#5120]
### Describe the bug

I'm using WordStar for DOS 7.0 Rev. D. which has a graphical "Advanced Page Preview" feature, which was working just fine with DOSBox-X until the 2024.07.01 release. It should show a full page of preview; instead, it now only shows the top half of the page, and repeats part of the top half immediately below. I'm using WordStar's VESA 1024x768 graphics driver.

What it used to look like:
![wordstar-correct](https://github.com/user-attachments/assets/8e3e87f8-28ad-4d21-8674-349fa9965c79)

What it looks like now:
<img width="513" alt="wordstar-incorrect" src="https://github.com/user-attachments/assets/bd0f6892-3cd1-4b2e-a178-d16f31029bdd">

My configuration file:
[sawyer.txt](https://github.com/user-attachments/files/16200952/sawyer.txt)

I see in the 2024.07.01 release notes that A LOT of graphics thing have been changed/fixed, but I have no clue which of those changes might have screwed up WordStar.

Many thanks for any help!

### Steps to reproduce the behaviour

Invoke Advanced Page Preview from with a WordStar document.

CRT_TYPE in WordStar's FONTID.CTL file set to VESA1024.WGD, although I've trade various other configurations, as well

### Expected behavior

Page preview should work, as it has until the 2024.07.01 release.

### What operating system(s) this bug have occurred on?

Windows 11 Pro

### What version(s) of DOSBox-X have this bug?

DOSBox-X version 2024.07.01 (VS SDL1 64-bit)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I haven't thoroughly bisected, but the regression maybe due to some changes between beginning and end of last April.

**Comment by maron2000** [comment]
I narrowed down the commit which resulted in regression.
Wordstar 7.0d with `CRT_TYPE=VESA1024.WGD` set in FONTID.CTL.

@joncampbell123 Can you take a look?

Commit 678f28f2d032c8e1825989b40e0a9569a2c059df Good
![image](https://github.com/user-attachments/assets/918e3b13-f55b-44e3-b9be-251544f6f08d)

Commit 2ec98af9af7d9428e334f6333d78a2b729c358c9 Bad
![image](https://github.com/user-attachments/assets/f8fdcbd2-fff1-4076-b3f1-93e0a76a12f9)

**Comment by joncampbell123** [comment]
Fixed. Any use of 16-color planar VESA BIOS modes above 800x600 had this issue.

**Comment by RobertJSawyer** [comment]
Thank you so, so much, both @maron2000 and @joncampbell123. You guys are the best! I'm very grateful.
