### ISSUE TITLE
Line Wars II: S3 acceleration that assumes some sort of bizarre 800x600 SVGA behavior

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#5124]
### Question

For the past two years now the S3 acceleration mode in Line Wars II has left me stumped why it doesn't render properly.

However I noticed the developer mentions that it uses an internal sort of 1024x1024 video mode within the 800x600 display.

I use VESAMOED to change mode 0x203 (It assumes mode 0x203, does not query!) so that, instead of 800x600x256, it becomes 1024x768x256.

Sure enough, it renders correctly! Though now with extra space on the right, and you can see it rendering the next frame below.

This raises more questions about the game's S3 acceleration.

What S3 card did the developer write the S3 acceleration against?

Did the card happen to have a BIOS that for whatever reason set up 800x600 256-color mode to have a 1024 bytes per scanline layout? In the same way that the oldest S3 drivers for Windows 3.1 have a 24-bit 640x480 mode with a power-of-2 bytes per scanline?

What cards does this game happen to work on? Would it mis-display on real Trio64 cards the same way it mis-displays in DOSBox-X now?

Answer:

        ; Get chip revision:
        ; AH = 81h = 86C911
        ; AH = 82h = 86C924
        ; AH = 90h = 86C928 Rev A
        ; AH = 91h = 86C928 Rev C / Rev D
        ; AH = 94h = 86C928 Rev D / Rev E
        ; AH = A0h = 86C801/86C805 Rev A or Rev B
        ; AH = A2h = 86C801/86C805 Rev C

Does the game do anything to the S3 registers to change the bytes per scanline by itself including XGA scanline? (so far, it doesn't appear to change any of those registers! It only manipulates the registers related to linear address window and display offset needed for "page flipping").

I could provide a way to make the game work regardless by offering a dosbox.conf option or perhaps a VESAMOED option to specify that 800x600 should have a specific display pitch.

Testing the game on real hardware with various S3 chipsets (ISA, EISA and PCI) would help here.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
DOSBox-X INT 10h modesetting includes code to set up the XGA display width that controls how XGA acceleration sees the screen, so if the video mode says 1024 pixels, the XGA registers will be set up for a 1024 pixel wide display. That's why VESAMOED works here.

**Comment by maron2000** [comment]
https://www.vogons.org/viewtopic.php?f=33&t=27723

The above thread in VOGONS may give you some idea?

```
The S3 hardware that I targetted in LW2 was the original S3 911/924 adapter, 
and I also had to make some changes later on
 to be able to support adapters up to 864. 
However, on adapters later than 928 the Linear Address
 Window handling was changed, 
and I used that to draw the planet directly to the graphics adapter RAM, 
so the code disables direct graphics memory access in adapters later than 928.

I still have the full source code of LineWars II, 
and can post the S3 -relevant parts if those are still needed or useful? 
For example, this is the part that tries to determine the adapter type:

        ;-------
        ; Get chip revision:
        ; AH = 81h = 86C911
        ; AH = 82h = 86C924
        ; AH = 90h = 86C928 Rev A
        ; AH = 91h = 86C928 Rev C / Rev D
        ; AH = 94h = 86C928 Rev D / Rev E
        ; AH = A0h = 86C801/86C805 Rev A or Rev B
        ; AH = A2h = 86C801/86C805 Rev C
        ;-------
        mov     al,30h
        out     dx,al
        inc     dx
        in      al,dx
        mov     ah,al
        dec     dx                      ; DX = 3D4h
        cmp     ah,90h
        jb      i_old_s3
IF 1
        cmp     ah,0C0h                 ; 0C1h = S3 864
        jae     i_old_s3
ENDIF
        ;-------
        ; Modify code for 86C801/86C805/86C928
        ;-------
        mov     cs:[s3_NOP_or_AND],0FE24h       ; { and al,0FEh }
        mov     cs:[s3_NOP_or_OR],010Ch         ; { or al,1 }
        ;-------
        ; 801/805/928: CPU Base Address bits 18 and 19 = 0 (use only 1 MB)
        ; Note: 801/805 Rev B error: Accessing CR51 using word I/O accesses
        ; occassionally causes the display to jump.
        ; Solution: Use 8-bit I/O when accessing CR51.
        ;-------
        mov     al,51h
        out     dx,al
        inc     dx
        in      al,dx
        and     al,11110011b            ; bit18 = 0, bit 19 = 0
        out     dx,al
        dec     dx
        ;-------
        ; 801/805/928: Set Linear Address Window into 0A000h
        ;-------
        mov     ax,0A5Ah                ; OUT_CRT 05ah,00001010b
        out     dx,ax
        mov     al,59h                  ; OUT_CRT 059h,00000000b,11111100b
        out     dx,al
        inc     dx
        in      al,dx
        and     al,11111100b
        out     dx,al
        dec     dx                      ; DX = 3D4h
i_old_s3:
Patrick "Pate" Aalto
```

**Comment by joncampbell123** [comment]
It doesn't mention anything about the "offset" register which controls the pixels per scanline. The game sets up 800x600 mode but expects 1024 bytes per scanline, and I don't see any attempt to reprogram the offset register or the XGA register related to screen width that would be necessary for it to display properly.
