### ISSUE TITLE
Dead key ^ not working for typing â or ê using br274 keyboard layout

### ISSUE THREAD

**Issue by ckoshikumo** [joncampbell123/dosbox-x#5127]
### Describe the bug

Using:

`keyb=br274`

characters like ã, ç and é work perfectly using the corresponding dead keys. But not â or ê; what I get is \^e and \^a.

### Steps to reproduce the behaviour

Use `keyb=br274` and try to use \^ as a dead key to produce ê and others.

### What operating system(s) this bug have occurred on?

MacOS Sonoma 14.4.1 (M1)

### What version(s) of DOSBox-X have this bug?

Tested on 2024.07.01, 2024.03.01, 2023.10.06

### Additional information

I checked with DosBox and dosbox-staging, and they both exhibit correct behavior with \^.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Seems this commit 0f4eaf98a45245c305aa67ea4c4ae54941d45773 caused the regression, such a long time ago.
Many places are patched, so we have to see which place is the cause.
