### ISSUE TITLE
Put old dynamic core back, though without page fault handling

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#513]
A fork of DOSBox-X is working to maintain the dynamic core to run 16-bit real mode games because the maintainer of the fork likes the performance gains on low end Atom notebooks (to play Touhou Project 1-5, of course).

I've been saying repeatedly that the dynamic core was removed because it was incompatible with the page fault changes needed to run Windows 95, but 16-bit real mode generally does not need page fault handling, so it might be OK to restore the dynamic core and let it run IF paging is disabled and reflect to the normal core if paging is enabled.

I'll need to pull out an older Linux laptop of mine that still has 32-bit Linux to test this, but it might be workable.

The only remaining issue then is to somehow handle the throw int() exceptions used to boot the guest OS or exit the emulator.

Remember the primary issue that triggered the removal was that on Linux C++ exceptions did not work properly when thrown from a function called from the dynamically generated code. GCC has an exception handling system that requires tracing the stack and identifying which exception handler frame to use, which the dynamically generated code did not provide, so when an exception was thrown the runtime effectively ignored all catch blocks and aborted the program with the default handler.

If the workaround is effective enough I might be able to use the same to restore dynamic core with page fault handling.

Also worth considering is whether the old dynamic core as written could be conditionally changed to support x86 and x86_64 targets.

**Comment by sikthehedgehog** [comment]
Wait, the problem was just some issue with C++? I had thought it was
something not being emulated (or emulated wrong) that would have required a
big rewrite to fix. Huh.

If you add x64 support then later you may also want to consider ARM as it
seems the other major CPU where DOSBox is usually run on... though 32-bit
and 64-bit ARM are two completely different beasts (unlike x86 vs x64 where
only a bunch of opcodes differ), so that may make it even trickier.

**Comment by joncampbell123** [comment]
It was a problem with C++ and exceptions. It may have worked on Windows, but on Linux the dynamically generated code confused the C++ runtime and prevented exceptions from working.

**Comment by joncampbell123** [comment]
ARM support might be fun, it would make DOS gaming possible in realtime on my Raspberry Pi 3.

**Comment by joncampbell123** [comment]
In the develop-dynamic-core branch, the dynamic core has been put back and verified to work with real-mode DOS games so far. Still crashes in odd ways though with 32-bit protected mode and paging (Windows 3.1), but this time, the dynamic core has been patched to reflect to normal core when paging has been enabled to avoid that.

In 32-bit Windows builds the C++ exception handling has been confirmed to work properly through the dynamic core so far.

**Comment by joncampbell123** [comment]
So what this change means is that you won't get full performance with Windows 95 or Windows 3.1 or any DOS game that uses paging, but you will get full performance with 16-bit DOS games and 32-bit DOS games that do not use paging.

Most DOS games though should get the full performance boost because DOS extenders generally DO NOT enable paging unless EMM386.EXE is active.

**Comment by joncampbell123** [comment]
Dynamic core is back in the develop branch, though with the restriction that paging must be disabled.

I will not close this issue however until the C++ exception handling issues on Linux and dynamic core are resolved.

**Comment by joncampbell123** [comment]
Huh.... I just commented out the "defer to normal core if paging enabled" and Windows 95 through Windows 98 SE seem to run just fine even under load with core=dynamic. That doesn't necessarily mean there aren't any subtle bugs with instruction state and page faults, but it seems to be pretty stable.

I think what I'll do for now is add a one-time message like "WARNING: core=dynamic and paging is enabled, stability is not yet guaranteed", but then allow dynamic core to do it's thing.

For x86_64 there might be some adaptation that I can do to the opcode byte values to make it work on 64-bit builds.

**Comment by joncampbell123** [comment]
I don't know what changed from then to now but I'm no longer seeing any issues even on Linux with the page fault handling exception and dynamic core.

**Comment by joncampbell123** [comment]
I don't know how Windows does it, but it managed to maintain the facade of working with dynamic core for the first 30 minutes, then progressively became more and more crashy until any change I made was a guaranteed BSOD.

*This* is the reason I disabled dynamic core in the first place.

However when paging is not involved, dynamic core is perfectly fine.

**Comment by joncampbell123** [comment]
Done. Dynamic core cannot handle 80386 paging and page faults, so the core has been updated to defer to normal core when paging is enabled. It cannot handle page faults, I tried. The generated asm cannot be interrupted safely and will cause Windows 95 to crash erratically.

DOS games that run in 16-bit real mode, and games that use 16/32-bit protected mode *without* paging will run fine with the dynamic core at full performance.

**Comment by sikthehedgehog** [comment]
Wild guess, but that the issues only arise after a while may mean that
Windows becomes unstable only once it starts recycling pages or something?
If any sort of caching is ever done on the emulator side that definitely
could be interferring (and would suggest a full flush whenever pages change)

**Comment by joncampbell123** [comment]
I doubt that. When core=dynamic crashed with Windows, it was very quick. It would usually happen in less than a second the minute Windows started page faulting in protected mode during startup.
