### ISSUE TITLE
dos box x not responding to keyboard in full screen unless a dos program is opened then it works for as long as the instance is open

### ISSUE THREAD

**Issue by supertails12** [joncampbell123/dosbox-x#5142]
### Describe the bug

dos box x not responding to keyboard in full screen unless a dos program is opened then it works for as long as the instance is open then when you reopen it it stops working again this was not the case when i first downloaded the emulator

### Steps to reproduce the behaviour

1. open dos box x on windows 11 
2. go fullscreen 
3. notice the bug

### Expected behavior

the keyboard working smoothly from boot

### What operating system(s) this bug have occurred on?

Windows 11 Home 23H2

### What version(s) of DOSBox-X have this bug?

dos box x mingw sdl2 latest version

### Used configuration

```ini
the only change i made from the default was changeing the type of soundblaster to sbpro2
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
No problem here if you are not in TTF output.
Keyboard is actually responding, but for somehow the screen doesn't update in TTF output.
Try adding the following two lines in the [autoexec] section, as a workaround if you want to start in TTF mode.
```
config -set output=default
config -set output=ttf
```

**Comment by supertails12** [comment]
sorry for late reply i dont know what u meant by that

**Comment by supertails12** [comment]
figured it out thank u the fix worked

**Comment by maron2000** [comment]
PR #5262 will fix this issue so that you don't need to manually add the commands in the [autoexec] section.
