### ISSUE TITLE
One commit makes windows 3.2 crash to DOS

### ISSUE THREAD

**Issue by palxex** [joncampbell123/dosbox-x#5146]
### Describe the bug

I found this problem by downloading an [old Chinese game's dosbox-bundle](http://www.emumax.com/pcgame/detail/29471), and found that when replace original dosbox 0.74-3 with dosbox-x it will constantly crashes to MSDOS. 
The bundle was a combination of windows 3.2( which only released in CN mainland ), and the installed game files in D partition(with its dependencies, like video for windows, etc.). 
After hundreds of bisecting, I found the cause of the problem was commit 1544a71. Once the commit was reverted, the problem gone. 
@joncampbell123 Could you please look at this?

### Steps to reproduce the behaviour

1. download the bundle from the link(via the non-VIP download ) mentioned above, extract it anywhere and move dosbox-x.exe inside
2. cp dosbox.conf dosbox-x.conf, then remove every line besides [autoexec] (prevent other configure breaks windows loading - I've experienced that in several old build, but autoexec only always work)
3. double click dosbox-x, after windows 3.2 logo blink several seconds, it immediately crash to DOS ( no any operation needed in dosbox)
4. `git revert 1544a71` and rebuild; redo step 3, windows start well; capture mouse in dosbox-x and double click TPGame, the game will start.

### What operating system(s) this bug have occurred on?

Windows 11 23h2

### What version(s) of DOSBox-X have this bug?

07.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I found a copy of Windows 3.2 and got it to install without any problems.

Perhaps it's not Windows 3.2 itself but a driver or VXD/386 system that has a problem with the change?

**Comment by joncampbell123** [comment]
I found the bundle on that site.

Why is vmemsize=24? That means 24MB. That's well beyond what Windows 3.1 S3 drivers can handle!

Probably not the issue, still looking into it now.

**Comment by joncampbell123** [comment]
I moved the INT 3 routine to another place unlikely to conflict with anything, the 7z packed game works in DOSBox-X now.

**Comment by palxex** [comment]
> Perhaps it's not Windows 3.2 itself but a driver or VXD/386 system that has a problem with the change?

It is very likely, since I found that there are quite a few pre-installed dependencies in this package( This game itself cannot work without installation, too ). But I'm afraid it will be difficult to identify them one by one:) 

> Why is vmemsize=24? That means 24MB. That's well beyond what Windows 3.1 S3 drivers can handle!

Not sure where the packager got the value from... BTW, what the value should be for this situation? 

And most important, thanks for the fix:) Verified it works well in my end. The issue could be close now.
