### ISSUE TITLE
Native ui menu Vs in window dos-style nenu

### ISSUE THREAD

**Issue by blitmaps** [joncampbell123/dosbox-x#5150]
### Question

Hey there,

I recently installed on Windows, and the application has the winforms menu, where on Linux I had in-window menus with dos-style dropdowns.  Is there any way to specify that I would like the dos-style regardless of platform?

Apologies if this has been answered, I did search.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
That's a compile-time option. By default the OS provided menus are used if available, otherwise it draws it's own.

**Comment by blitmaps** [comment]
Thanks Jonathan, I'll read the build script.

**Comment by maron2000** [comment]
According to the comment below, you need to edit the following line.
https://github.com/joncampbell123/dosbox-x/blob/master/vs/config.h#L90

https://github.com/joncampbell123/dosbox-x/issues/3240#issuecomment-1021630314
