### ISSUE TITLE
Tales of Peter Rabbit - Game renders slowly

### ISSUE THREAD

**Issue by ualaa1** [joncampbell123/dosbox-x#5151]
### Describe the bug

Game renders slowly for some reason. Each screen requires time to render

### Steps to reproduce the behaviour

Install the game from 
[dos2.zip](https://github.com/user-attachments/files/16481428/dos2.zip)
Then run the game and see the game slowly render itself

### Expected behavior

Game to load screen immediately

### What operating system(s) this bug have occurred on?

Windows 11 x64

### What version(s) of DOSBox-X have this bug?

2024.03.01

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
I see the birds flying quite fast so if it runs faster, I bet kids couldn't see how it moves.

Is it so slow than the movie below?
https://www.youtube.com/watch?v=5CK2VxX--tM

**Comment by ualaa1** [comment]
Yeah... Around that speed. But still trying to move the cursor is very laggy. I tested on a 386SX on 86 Box and it was somewhat smoother. 
Here's my test on Dosbox-X:

https://github.com/user-attachments/assets/c905f1d5-1962-4d73-9122-4521411b2620

And on 86-box running a 386 SX

https://github.com/user-attachments/assets/df0f28a3-3919-48f1-8105-30b2f764d590

**Comment by joncampbell123** [comment]
Try a higher cycle count. A cycle count of 3000 is roughly equivalent to 386SX that is probably far slower than your 386SX.

Try cycles=8000 or cycles=10000

**Comment by maron2000** [comment]
Adjusting cycle count as you suggested makes going to the next page a lot faster. 

https://github.com/user-attachments/assets/037f12ed-b7ab-403b-b671-3807c1beb742
