### ISSUE TITLE
Language files loading doesn't work

### ISSUE THREAD

**Issue by lkintact** [joncampbell123/dosbox-x#5174]
### Describe the bug

Loading most of the language files doesn't work.

### Steps to reproduce the behaviour

1. Run DOSBox-X
2. Click on "Main" -> "Load language file..."
3. Select any (except for `en_US.lng` and `it_IT.lng`) `.lng` file from the `languages` folder and click on "Open". Instead of switching the UI language, DOSBox-X quits.

### Expected behavior

DOSBox-X should switch the UI language and not quit.

### What operating system(s) this bug have occurred on?

Windows 10 Home 22H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2024.07.01 2024-07-01 21:45 (SDL1)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Tried several languages and I see no flaws.

![image](https://github.com/user-attachments/assets/fb9d85f4-468e-4713-aba4-8ffa71bae7ec)

![image](https://github.com/user-attachments/assets/f39c069a-19c5-4758-898b-a5fa6231d416)

![image](https://github.com/user-attachments/assets/b73c3f62-7df5-4697-a29e-8bb701a51e30)

**Comment by maron2000** [comment]
The crash occurs when your host keyboard is US layout or when you set `keyboardlayout=none`.
Try the nightly build after it is merged.

**Comment by lkintact** [comment]
@maron2000, @joncampbell123: Thank you guys, I just tried the nightly build ([dosbox-x-mingw-win32-20240815173317](https://github.com/joncampbell123/dosbox-x/actions/runs/10407922741/artifacts/1816959174)), and the issue is gone for me.

**Comment by maron2000** [comment]
Good to hear that the fix works.
