### ISSUE TITLE
Ys The Vanished Omens hanging after title screen, then sometimes resetting glitched

### ISSUE THREAD

**Issue by timmyLaJimmy** [joncampbell123/dosbox-x#5181]
### Describe the bug

When mounting Ys I into the A drive with the machine set to pc98, the game loads as expected. The music plays, the title image is shown, and the game waits for the player to hit "z." Upon doing so, the music fades and the screen fades to black, also as expected. After that, the game does nothing. The screen remains black, no audio plays, and pressing buttons does nothing.

### Steps to reproduce the behaviour

1. Mount the Ys I disc image to the A drive.
2. Press "z" on the title screen.
3. Wait for a minute or two while silent black screen is shown.
4. Black screen will either show indefinitely, or title screen will suddenly play again with parts of the in-game HUD displaying on either side of the screen.

### Expected behavior

Upon hitting "z" and exiting the title screen, the game should start after an initial loading phase.

### What operating system(s) this bug have occurred on?

Windows 11 Pro 23H2

### What version(s) of DOSBox-X have this bug?

2024.07.01, MinGW SDL1 64-bit

### Used configuration

```ini
Engine set to "pc98"; unchanged otherwise.
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by timmyLaJimmy** [comment]
This is what happens when the title screen reappears:

![image](https://github.com/user-attachments/assets/9337b5ad-6e7d-440e-b5e4-f915961bafef)

Note the sides on the bottom of the screen.

**Comment by joncampbell123** [comment]
During the blank screen, the code is in a hard REP CMPSB loop looking for "BEPMU1" in a directory listing (16 bytes per entry) where "BEPMU1" doesn't exist. The code doesn't seem to check whether it's gone beyond the directory, so it just continues on into the junk data afterward.

If I run GNU "strings" on the NFD Image the BEPMU1 is in the directory. Either the game doesn't load the entire directory or there's something about disk emulation that causes misloading of the directory.

**Comment by joncampbell123** [comment]
Uh, no, wait. The only way it could properly load the directory is if somehow the first INT 1Bh call returns with C/H/S the same but the head value flipped from 0 to 1?

**Comment by joncampbell123** [comment]
Ah.... the true problem is that this game uses copy protection type tricks within the floppy image.
Look at the debug output of DOSBox-X's NFD parser, notice how each track has TWO copies of sectors 1-5?

NFD 10/4238: ofs=448 data=70672 cyl=0 head=0 sec=11 len=256
NFD 11/4238: ofs=464 data=70928 cyl=0 head=0 sec=12 len=256
NFD 12/4238: ofs=480 data=71184 cyl=0 head=0 sec=13 len=256
NFD 13/4238: ofs=496 data=71440 cyl=0 head=0 sec=14 len=256
NFD 14/4238: ofs=512 data=71696 cyl=0 head=0 sec=15 len=256
NFD 15/4238: ofs=528 data=71952 cyl=0 head=0 sec=16 len=256
NFD 26/4238: ofs=704 data=72208 cyl=0 head=0 sec=1 len=1024
NFD 27/4238: ofs=720 data=73232 cyl=0 head=0 sec=2 len=1024
NFD 28/4238: ofs=736 data=74256 cyl=0 head=0 sec=3 len=1024
NFD 29/4238: ofs=752 data=75280 cyl=0 head=0 sec=4 len=1024
NFD 30/4238: ofs=768 data=76304 cyl=0 head=0 sec=5 len=1024
NFD 52/4238: ofs=1120 data=77328 cyl=0 head=1 sec=1 len=1024
NFD 53/4238: ofs=1136 data=78352 cyl=0 head=1 sec=2 len=1024
NFD 54/4238: ofs=1152 data=79376 cyl=0 head=1 sec=3 len=1024
NFD 55/4238: ofs=1168 data=80400 cyl=0 head=1 sec=4 len=1024
NFD 56/4238: ofs=1184 data=81424 cyl=0 head=1 sec=5 len=1024
NFD 78/4238: ofs=1536 data=82448 cyl=0 head=1 sec=1 len=1024
NFD 79/4238: ofs=1552 data=83472 cyl=0 head=1 sec=2 len=1024
NFD 80/4238: ofs=1568 data=84496 cyl=0 head=1 sec=3 len=1024
NFD 81/4238: ofs=1584 data=85520 cyl=0 head=1 sec=4 len=1024
NFD 82/4238: ofs=1600 data=86544 cyl=0 head=1 sec=5 len=1024
NFD 104/4238: ofs=1952 data=87568 cyl=1 head=0 sec=1 len=1024
NFD 105/4238: ofs=1968 data=88592 cyl=1 head=0 sec=2 len=1024
NFD 106/4238: ofs=1984 data=89616 cyl=1 head=0 sec=3 len=1024
NFD 107/4238: ofs=2000 data=90640 cyl=1 head=0 sec=4 len=1024
NFD 108/4238: ofs=2016 data=91664 cyl=1 head=0 sec=5 len=1024
NFD 130/4238: ofs=2368 data=92688 cyl=1 head=0 sec=1 len=1024
NFD 131/4238: ofs=2384 data=93712 cyl=1 head=0 sec=2 len=1024
NFD 132/4238: ofs=2400 data=94736 cyl=1 head=0 sec=3 len=1024
NFD 133/4238: ofs=2416 data=95760 cyl=1 head=0 sec=4 len=1024
NFD 134/4238: ofs=2432 data=96784 cyl=1 head=0 sec=5 len=1024
NFD 156/4238: ofs=2784 data=97808 cyl=1 head=1 sec=1 len=1024
NFD 157/4238: ofs=2800 data=98832 cyl=1 head=1 sec=2 len=1024
NFD 158/4238: ofs=2816 data=99856 cyl=1 head=1 sec=3 len=1024
(and so on)

**Comment by joncampbell123** [comment]
PC-98 games that use copy protection tricks are not supported by DOSBox-X at this time.

**Comment by timmyLaJimmy** [comment]
Gotcha. Thanks for figuring it out, though.
