### ISSUE TITLE
Sync with SVN

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#5193]
### What you want

Last sync with upstream I see is 
- #4072 @Allofich 

https://sourceforge.net/p/dosbox/code-0/4483/ saa1099 - Fix compilation in Visual Studio 2008
https://sourceforge.net/p/dosbox/code-0/4484/ Fix wav capture glitches on buffer wrap around

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Allofich** [comment]
Waiting to make sure https://sourceforge.net/p/dosbox/code-0/4483/ compiles in DOSBox-X, then I'll open a PR for it.
The change from https://sourceforge.net/p/dosbox/code-0/4484/ (adding `read += left*2` in `CAPTURE_AddWave`) already exists in DOSBox-X so isn't applicable.
