### ISSUE TITLE
GOG BIN/CUE file extentions

### ISSUE THREAD

**Issue by archlyn** [joncampbell123/dosbox-x#5195]
### Is your feature request related to a problem? Please describe.

In order to get GOG games that use  custom file extensions for their bin/cue files (for example .inst for the .CUE  file and .gog for the .BIN file I always have to rename the files to game.bin and game.cue respectively and then edit the .CUE file so that the filename for track 1 matches GAME.BIN

### What you want

I would like DosBox-x to be able to recognize intuitively that a file is a .CUE without having to rename the file so that the extension is .CUE  file and treat the associated file listed as Track 1 in the file as the .BIN

### Describe alternatives you've considered

DosBox Staging has this feature but I llike all the other features that DosBox-x has

### Additional information

I'm using Linux Mint 22 Wilma

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
It was confirmed that #4882 fixed mounting some gog files without renaming them.
I personally recommend renaming the extension to .cue for better handling of CUE sheets.

**Comment by Allofich** [comment]
The ".gog" extension as ".bin" is already working. ".inst" does not, but it should be an easy fix.
