### ISSUE TITLE
MDA/Hercules - wrong mono text mode attributes

### ISSUE THREAD

**Issue by MrMadguy64** [joncampbell123/dosbox-x#5204]
### Describe the bug

MDA/Hercules text attributes - are mysterious thing. Different sources can provide different info about them. Author of [this article](https://www.classicdosgames.com/tutorials/characterattributes.html) claims, that he has tested everything on real hardware and software. I'm not sure, if old real hardware is needed, because attribute controller should support mono attributes even on new hardware. It should be supported for compatibility with mode 0x07. I've written my application according to this information. And it doesn't work properly in DOSBox-X.

How I expected it to work? There are just 4 possible monochrome attributes:
1) Black on black - can't be combined with any intensity bits
2) Normal - can be combined with foreground intensity bit only
3) Underline - can be combined with foreground intensity bit only
4) Reversed - can be combined with both intensity bits
5) Any other attribute - should be white on white according to documentation, but it actually falls back to normal attribute on real hardware.

But it looks this way in DOSBox-X:
![Mono attributes](https://s1.hostingkartinok.com/uploads/images/2024/09/c5519e29f14c6fc61bb1cc5a7cca452d.png)

Foreground is left, background is right. Foreground is controlled by X coordinate, background is controlled by Y. Bit 0 controls color bits, bit 1 controls intensity bit.

As you can see, background intensity is supported in normal mode, but isn't supported in reversed mode, that is opposite to how it should actually work.

P.S. Please don't forget about [this issue](https://github.com/joncampbell123/dosbox-x/issues/5055)! It isn't connected to distorted image - it's connected to how 64 color palette is chosen. It should be chosen for any 350 modes, not only 640x350.

### Steps to reproduce the behaviour

Run following BASIC program:

CLS
OUT &H3B8, &H8
DEF SEG = &HB000
FOR Y = 0 TO 3
FOR X = 0 TO 3
C = (X AND 1) * &H7 + (X AND 2) * &H4
C = C + (Y AND 1) * &H70 + (Y AND 2) * &H40
POKE Y * 160 + X * 4, &HDD
POKE Y * 160 + X * 4 + 1, C
NEXT X
NEXT Y

### Expected behavior

According to [this article](https://www.classicdosgames.com/tutorials/characterattributes.html)

### What operating system(s) this bug have occurred on?

Windows

### What version(s) of DOSBox-X have this bug?

Latest

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Emulation is build around this documentation: http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/MDA/Monochrome%20Display%20Adapter%20Notes%20by%20John%20Elliott%20%282005%2d11%2d06%29%2ehtml

And this one for how Hercules cards do it: http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/Hercules/HGC%2b/Hercules%20Graphics%20Card%20Plus%20Notes%20by%20John%20Elliott%20%282012%2d08%2d09%29%2ehtml

**Comment by joncampbell123** [comment]
Then I must have made a mistake in that part of the code when fixing it up.

I did have to rewrite the code somewhat when adding HGC+ and InColor emulation, maybe that's where the error crept in.

**Comment by joncampbell123** [comment]
DOSBox-X has the blink mode on by default, therefore F0h F8h should be 70h 78h with blinking, not a bright background.
That part DOSBox-X is emulating correctly.
It sounds like DOSBox-X has it wrong for F0h F8h if you turn off blinking.

**Comment by joncampbell123** [comment]
Just pushed a commit that should fix F0h/F8h non-blinking MDA attributes.

**Comment by MrMadguy64** [comment]
Also I'm not sure about background intensity bit. There might be difference between MDA and Hercules. While Hercules seemed to support it for normal attribute, MDA might not. Can't say it for Hackipedia documentation, because picture it provides seems to relate to blinking on and blinking off picture is missing. But my article states it explicitly - 0/3 background isn't turned into 1/3 via background intensity bit.

**Comment by MrMadguy64** [comment]
Also check colors themselves. Remember, that intensity should be +1/3 as on CGA and EGA? I.e. bright should be 3/3, normal should be 2/3 and dim should be 1/3.

**Comment by MrMadguy64** [comment]
Seems like problem is fixed.
