### ISSUE TITLE
Begin adding PC-98 INT 1Ch emulation

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#521]
https://twitter.com/yksoft1/status/966332714105298944

**Comment by joncampbell123** [comment]
[test3.zip](https://github.com/joncampbell123/dosbox-x/files/1745067/test3.zip)

**Comment by joncampbell123** [comment]
Relevant code in Neko Project II:

https://github.com/joncampbell123/xnp2/blob/master/bios/bios1c.c#L28

Thoughts:
- I thought I/O ports 0x70 to 0x7F were CRTC I/O ports?
- Why INT 7? (note writing to interrupt vector table at 0x1C-0x1F). Does the BIOS system timer interrupt just "int 7h" if a flag is set as part of it's procedure? Is it the PC-98 equivalent of IBM PC/AT IRQ 0 -> INT 1Ch then?

**Comment by leonier** [comment]
From what I read on books I/O port 71H, 73H (or 3FDBH?), 75H and 77H are used by PIT in PC-98 just as IBM PC uses 40H, 41H, 42H and 43H.
77H is used to set the PIT counter mode, similar to IBM-PC's 43H.

**Comment by joncampbell123** [comment]
That's correct. I forgot that 71-77h odd are the PIT registers. 70h-7Eh even are CRTC control registers, if I recall.

**Comment by joncampbell123** [comment]
Hey, according to the ROMIMAGE in NP2, the system timer interrupt counts down from BIOS data area location 0x58a and then does an INT 7h when it expires (also turning off the timer at that point).

https://github.com/joncampbell123/xnp2/blob/master/romimage/BIOS/VECT08.X86

**Comment by joncampbell123** [comment]
DONE
