### ISSUE TITLE
Is it possible that the hardware is limiting the virtual RAM memory in DOSBox-X?

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#5218]
### Question

As I see it, there are apparently divided opinions about how high you can set the virtual RAM memory (memsize). I find that the limit is 3.5 GB (3584) in my case, while in @Torinde's case he experiences that the limit is 4 GB (4096) (if I remember correctly). I myself have added 4096 as the memsize value, but the start of DOSBox-X still says 3584.

I have checked the performance of my PC device.
Basic Speed: 3.80 GHz
Sockets: 1
Cores: 8
Logic Processors: 16
Virtualization: Enabled
L1 Cache: 512 KB
L2 Cache: 4.0 MB
L3 Cache: 32.0 MB

Can at least some of you compare the performance of your PC/Mac as well, with how high the virtual RAM memory can be increased in DOSBox-X in the same device? I wonder if the performance of the devices actually limits the virtual RAM, and maybe other things as well.
If someone has a computer device with a better performance than mine, preferably far more in every way, I'm extra curious about the virtual RAM memory limitation. I've done my research this summer, and read that some PCs have a basic speed of 9.12 GHz.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
> @joncampbell123 I just tried the latest developer build, the memory size can now be increased up to 3968MB, well done. :) I'm saying it so everyone knows. :)

While testing that, I discovered Windows 3.1 will not run with 512MB or more memory. It acts like some paging overcommit value is too large even if you enter the value as prescribed. Especially if you set the maximum memory size :)

**Comment by rderooy** [comment]
> While testing that, I discovered Windows 3.1 will not run with 512MB or more memory. It acts like some paging overcommit value is too large even if you enter the value as prescribed. Especially if you set the maximum memory size :)

Official max memory for Windows 3.1x was 256MB.

**Comment by joncampbell123** [comment]
One more comment worth noting: Only 64-bit builds of DOSBox-X can go up to 4GB (well, just below 4GB).

32-bit builds of DOSBox-X are limited to 1GB. It's not me imposing arbitrary limits, it's that 32-bit processes only have a 4GB virtual address space, and up to half of that (Windows) or a quarter of that (Linux) is occupied by the OS kernel, and more is occupied by system and OS libraries. 1GB is a a safe limit in that scenario, and anyway most DOS games that you'd run in DOSBox-X don't use much beyond 8-16MB and maybe 64-128MB if the game is from the late 1990s.

**Comment by joncampbell123** [comment]
DOSBox-X allows you to use up to that amount of memory for several reasons. Maybe someone is writing a DOS game and they need to make sure it works on a machine that supports both MS-DOS and lots of memory. Maybe you're interested in how older OSes like Windows 3.x/9x/ME break with too much RAM. I'm not big on the idea of limiting all emulation to 63MB or less like the main DOSBox SVN project seems to want to do.
