### ISSUE TITLE
Help with tracking what file a program is trying to open

### ISSUE THREAD

**Issue by TeddyTheMan** [joncampbell123/dosbox-x#5223]
### Question

I am running an old engineering program (to access an old design) that seems to be searching for a specific .FON file to run. It uses it for a graphical output. I've been trying to jury-rig it to work (by giving it a directory with all the .FON files I would expect it to be trying to use) but keep getting told that it can't find the font it's looking for. Documentation for the thing is not great. Is there a way to track which font the program is trying to open? I've been trying to play around with the debugger but honestly don't know where to start. Any help would be appreciated!

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
You can try enable logging with `files=true` option.
Consult explanation in the .conf file or the help screen of configuration tools for details.

**Comment by TeddyTheMan** [comment]
> You can try enable logging with `files=true` option. Consult explanation in the .conf file or the help screen of configuration tools for details.

Thank you, that was helpful and was exactly what I was trying to do. Unfortunately, it appears the program finds all .FON files and tries to open every one sequentially (rather than a specific one) and does some sort of iternal check to see if its suitable (non-loggable after turning everything on) . Looks like I may be stuck, absent finding some archive of the actual .FON files used in Windows 3.0.
