### ISSUE TITLE
About ESS sound cards

### ISSUE THREAD

**Issue by usuck32** [joncampbell123/dosbox-x#523]
Dear DOSBox-X Staff,
Please include ability to emulate ESS sound cards.
OK.

**Comment by joncampbell123** [comment]
There is already ESS688 emulation in DOSBox-X. Other ESS chipsets can be added if desired.

If you desire to add support, feel free to fork DOSBox-X and pick a datasheet to study:

http://hackipedia.org/browse/Computer/Platform/PC,%20IBM%20compatible/Sound%20and%20Music/ESS%20Technology

Have fun.

**Comment by empsmoke** [comment]
But how long is going to take this part of VS2017??
![bang](https://user-images.githubusercontent.com/14072545/36552686-21dbc79a-1803-11e8-84b5-fec34db6fe7b.PNG)

**Comment by joncampbell123** [comment]
The install could take up to 1-2 hours. Once installed, getting started is relatively quick.
