### ISSUE TITLE
Bug with "SET PATH=Z:\" in capital letters in [AUTOEXEC] category (dosbox-x.conf)

### ISSUE THREAD

**Issue by FloLore** [joncampbell123/dosbox-x#5232]
### Describe the bug
Hi the dosbox-x team,

If "SET PATH=Z:\" is written in capital letters in [AUTOEXEC] category (dosbox-x.conf), all the next command aren't recognized by dosbox-x : "bad command or filename" and not possible to use the MOUNT command...

But if i change the command "SET PATH=Z:\" in lowercase : "set path=z:\" them all is ok.

This bug is present in all versions, from the latest to the version of "20240810". With the 20240810 and old versions, it works fine.

This bug appear with the 20240811 version (SET /FIRST DOSBox-X extension for demos like Out of Control with lazy…)

Please if you can to try fix that, thank you.

### Steps to reproduce the behaviour

set "SET PATH=Z:\"  in capîtal letters in the dosbox-x.conf, in the [autoexec] category.

### What operating system(s) this bug have occurred on?

windows 11 23h2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2024.10.01 2024

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
This is intended since you disabled path to `MOUNT` command.
Capital or lower case doesn't matter. 

In capital
![image](https://github.com/user-attachments/assets/5545627b-b283-488c-ac42-1e4852bf2da6)

In lower case
![image](https://github.com/user-attachments/assets/4e7c11bf-b3c3-4493-a3b1-dbc93cc5d08a)

**Comment by maron2000** [comment]
`SET PATH=C:` doesn't seem to be a valid syntax.
Genuine dos doesn't work as well

You need to explicitly specify C: drive even you set path to `C:`
![image](https://github.com/user-attachments/assets/8fa2e069-fd6a-4ce0-af74-4a6da27f6aa2)

Same on PC-98 DOS
![image](https://github.com/user-attachments/assets/5e33a06a-a2b8-47e3-bfa2-6201c4a41dd9)

**Comment by FloLore** [comment]
This bug is really present, in capital letters only for the command : SET PATH=Z:\
This bug is in dosbox-x since the  20240811 version (SET /FIRST DOSBox-X extension for demos like Out of Control with lazy…)

For proof :
In this test i use the latest dosbox-x, with the dosbox-x.reference.full.conf per default.

In capital letters :

<img width="1440" alt="Desktop Screenshot 2024 10 04 - 06 13 38 88" src="https://github.com/user-attachments/assets/af177068-c10d-4732-bdb1-be1fd1827d8b">

 in lowercase :

<img width="1440" alt="Desktop Screenshot 2024 10 04 - 06 14 40 14" src="https://github.com/user-attachments/assets/923fea16-775b-48b3-bb89-026199ef53c3">

So thank you to have tried to help me to fix that, but i don't understand your test, I hope these additional details will help to correct this problem.

**Comment by FloLore** [comment]
Hi Maron 2000,

Thank you for your help and informations, but i don't understand why with your test the lowercase and capital letters doesn't differences... I know for the path=z:\system but it doesn't help all, per example the command keyb doesn't work with, and more...

This is my test in next, i using the latest dosbox-x versions with dosbox-x.reference.full.conf per default :

In capital letters

<img width="1440" alt="373501770-af177068-c10d-4732-bdb1-be1fd1827d8b" src="https://github.com/user-attachments/assets/0815b250-dded-426b-9f12-bab27310bf6b">

In lowercase : 

<img width="1440" alt="373501870-923fea16-775b-48b3-bb89-026199ef53c3" src="https://github.com/user-attachments/assets/ce218086-4e7a-4dd5-8bb1-63bf27869bc5">

There is indeed a problem with the capital letter, perhaps it is confused with an ascii character or other confusion?

I have 311 dos games, so with one file dosbox-x.conf for each game. I can't change all for the lowercase only while this problem isn't maybe not too much to fix.

I hope we will find a solution, thank you again for your help.

**Comment by maron2000** [comment]
Now I understand. Your initial explanation was `SET PATH=Z:` not `SET PATH=Z:\` so it was confusing.
Anyway, try the nightly build after PR #5237 is merged.

![image](https://github.com/user-attachments/assets/3da15391-0db6-4134-9d0f-594fdb95ca7a)

**Comment by FloLore** [comment]
Hi Maron2000,

Yes i don'tknow why the "\" letter was not validated by the github editor... Anyway, i want to thank you very much for providing a fix so quickly and efficiently!
It works very well, best regards,

FloLore
