### ISSUE TITLE
Crash when using Configuration Tool

### ISSUE THREAD

**Issue by Zanzibarik** [joncampbell123/dosbox-x#5233]
### Describe the bug

Visual Studio builds  (SDL1/SDL2) x32 - crashes when using Configuration Tool.
Visual Studio builds  (SDL1/SDL2) x64 - Configuration Tool works fine.
MINGW bulds - Configuration Tool works fine.

### Steps to reproduce the behaviour

1. Go to "Main" -> "Configuration Tool" or press F11+C 

### What operating system(s) this bug have occurred on?

Windows 8.1 x64

### What version(s) of DOSBox-X have this bug?

v.2024.10.01 builds for WinXP

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Visual Studio builds XP x86 SDL1 working fine here on Windows 10 x64.
It's going to be difficult to find out what the problem will be on deprecated OSs.
(Windows 10 will also be deprecated soon.)

![image](https://github.com/user-attachments/assets/2797fbdb-c525-4300-bdd6-89452b3d57f7)

**Comment by movlps** [comment]
Same here: Windows 7 Ultimate SP1 X64 - ver. 2024.10.01 (VS SDL1 32 bit build)
Almost instant crash, when I open the Configuration tool from the menu, or press F11+C.

**Comment by joncampbell123** [comment]
Could it be a problem with uninitialized memory?

I will investigate here on Linux using Valgrind.

**Comment by joncampbell123** [comment]
When it comes to obsolete versions of Windows, there's always VirtualBox, or old PCs from the local thrift store, to run them.

**Comment by joncampbell123** [comment]
I'm installing Windows 7 64-bit in a VirtualBox VM to see if I can reproduce the crash.

**Comment by joncampbell123** [comment]
Worthless piece of garbage, as usual.

This is the most debugging I've been able to do so far. Meaning.... none.

![image](https://github.com/user-attachments/assets/85a559b8-9cad-4606-b2af-e3398bcf6964)

**Comment by joncampbell123** [comment]
Trying again by mounting \\vboxsrv\share as a network drive letter doesn't make it any better.

**Comment by joncampbell123** [comment]
Well, that's something. 32-bit debug build. I'll check to see if it has anything to do with the dynamic core.
![image](https://github.com/user-attachments/assets/92bd7009-1d19-45d2-997d-1e6209ef28c0)

**Comment by joncampbell123** [comment]
Nope, that was normal core.

**Comment by joncampbell123** [comment]
Hold on, their site says Windows 7 SP1. This is just plain Windows 7.

**Comment by joncampbell123** [comment]
Bah, it just crashes.

**Comment by joncampbell123** [comment]
That's it? Code that tries to use Dark mode in Windows 10?
![image](https://github.com/user-attachments/assets/70be8b23-9878-4aa5-ae23-3302805aedb5)

**Comment by maron2000** [comment]
@aybe You may want to take a look with the dark mode detection code?

**Comment by joncampbell123** [comment]
> @aybe You may want to take a look with the dark mode detection code?

For now, I fixed it by disabling the code entirely. I will get back to dark mode detect later.
