### ISSUE TITLE
Host system application . Window auto-closing at end of execution

### ISSUE THREAD

**Issue by pmatei** [joncampbell123/dosbox-x#5238]
### What you want

First of all, thank you for the wonderful software. I would like an option that I can't find. I'm working in a FoxPro program and I'm launching another program, let's say 7z.exe. Everything is going well but at the end of 7z.exe execution  the window does not close by itself, it displays "The command execution is completed. Press any key to continue..." . If possible, I would like the window to close by itself at the end of the execution.

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by pmatei** [comment]
I forgot to mention: My OS is W11

**Comment by maron2000** [comment]
Can you show a specific example to test?
Such as how you launch 7z.exe, for example.

**Comment by pmatei** [comment]
Under DosBox-X , current folder contain 7z.exe, launched 7.exe without arguments(or with any arguments, how you want) the command window appears, 7z does his job but at end, the command window  stay open with message "The command execution is completed. Press any key to continue..."
For example using VDosPlus under similar conditions, the command window auto-close and dissapears, and the execution control returns to Vdosplus. Same computer same OS (Windows 11).
I would like, if possible, the same behavior in DosBox-X.

**Comment by maron2000** [comment]
I can't launch 7z.exe so that's why I'm asking.
It tries to launch but finishes silently.
Of course the same file launches on Windows 10 native command prompt.
![image](https://github.com/user-attachments/assets/d6040c70-6d97-4ecc-b885-22f67a86b80e)

**Comment by pmatei** [comment]
@maroon2000
![DosBoxX](https://github.com/user-attachments/assets/c2a4d648-8831-45c3-8db3-cea5e418cfee)
On W11 this is happen, even with legacy console selected

**Comment by pmatei** [comment]
I've tested on W10, same behavior, command window do not close. And with Quiet Mode not selected, after few seconds, the following message appears:
![DosBox2](https://github.com/user-attachments/assets/cd246eea-e32a-441e-b319-c21330c4ecae)

**Comment by maron2000** [comment]
@rderooy  Thanks for your info. I already enabled `startcmd` option when I mentioned above but somehow I can't get it doesn't work as all of you can.

Launched DOSBox-X by `-defaultconf -set startcmd=true`
Anyway, I give up for the time being.

![image](https://github.com/user-attachments/assets/00ba3d24-be6f-479a-afd3-a397578fe678)

**Comment by maron2000** [comment]
Seems that I shouldn't mount the drive in relative path such as in the screenshot below.
Mounting folder by absolute path worked.
I don't know if I can implement your request, but at last I got to the start point.

![image](https://github.com/user-attachments/assets/7412f8eb-fe15-45d5-b9bd-f7862751b225)

**Comment by pmatei** [comment]
I think I found a clue where I think it can start. But the approach is beyond my knowledge.
In the file dosbox-x.reference.full.conf  there are the following lines:
#                                        startwait: Specify whether DOSBox-X should wait for the host system applications after they are started.
#                                       startquiet: If set, before launching host system applications to run on the host DOSBox-X will not show messages like "Now run it as a Windows application".
#                                       startincon: START command will start these commands (separated by space) in a console **and wait for a key press before exiting**.
This is the indication that a key wait is coming from DOSBox-X. I suppose.

**Comment by pmatei** [comment]
Yes, it works exactly as I expected. Yes, it also works from a FoxPro executable. Thank you very much!

**Comment by pmatei** [comment]
I'm very happy with the new startnopause option. It works exactly as I wanted but I would like to draw the attention of other users that the combination of startnopause=true and startwait=false can be very dangerous. Execution control returns to DosBox-X, but the process that is launched ends indefinitely. In conclusion, if you use startnopause=true then the startwait=true setting is almost mandatory
