### ISSUE TITLE
About LAPC-I emulation and upcoming features

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#524]
Dear DOSBox-X team,
Please include LAPC-I emulation which would work.
Please, and also include other features like full XGA emulation and full MCA emulation, which will activate the M-ACPA emulation and ChipChat emulation (if there would be ROMs for the M-ACPA and the ChipChat), and also a full DecTalk emulation would be nice.

**Comment by usuck32** [comment]
and also to rename DOSbox-X to Project86.

**Comment by joncampbell123** [comment]
I have no documentation on MCA or DecTalk. DOSBox-X already inherits MT32 emulation (which the LAPC-I is based on, I understand). I have no documentation on the original XGA card. The closest thing to XGA in DOSBox-X is the S3 SVGA chipset emulation (the way S3 implemented it).

This is a hobby of mine and I work on it in my spare time. I will develop what I think needs to be done. This project inherited the general mess from DOSBox and cleanup is one of the general tasks that needs to be done. For other features, feel free to fork this project and try out the improvements on your end before submitting pull requests.

**Comment by empsmoke** [comment]
But can you implement a TV tuner / capture card emulation?

**Comment by joncampbell123** [comment]
No. Can you?

**Comment by empsmoke** [comment]
What software do I need to compile it??

**Comment by joncampbell123** [comment]
For Windows, You can use Visual Studio 2017 community edition.
For Linux, all you need is GCC and the development libraries it depends on. Use the ./build-debug script or ./build-debug-no-avcodec script.

**Comment by joncampbell123** [comment]
It's also possible to compile on Mac OS X using "gcc" (which is really llvm/clang) into a working application if XCode is installed.

**Comment by empsmoke** [comment]
But VS2017 takes waaay too much space.

**Comment by joncampbell123** [comment]
Yes, that is the way of Microsoft software. Make room and prepare to wait a few hours :)

Others here have compiled it using MinGW, which I am unfamiliar with, so you might ask them how.

**Comment by empsmoke** [comment]
Can I edit the BIOS logo so it says Project86?

**Comment by joncampbell123** [comment]
At the moment the logo is a BMP file compiled in to the source code using binary to C array conversion using the xxd tool in Linux. The BMP file needs to be a specific format (and there's another version for machine=cga to change as well).

I would make sure there is no other project or product out there already using "project86" first to be honest.

As a fork of DOSBox-X please acknowledge in the README and documentation where you forked the source code from, just as I acknowledge the origins from the DOSBox project in DOSBox-X.

https://github.com/joncampbell123/dosbox-x/issues/525

**Comment by empsmoke** [comment]
I actually forked it from.
