### ISSUE TITLE
Application window has no minimum window size on linux

### ISSUE THREAD

**Issue by heldderarbeit** [joncampbell123/dosbox-x#5240]
### Is your feature request related to a problem? Please describe.

On linux, at least on the desktop environments Plasma and Gnome (both Wayland / XOrg) it's possible to resize the application window to a very small vertical strip that's not really usable anymore. In this state, the window controls (minimize, maximize, close) are completely hidden.

[GnomeWaylandScreencast From 2024-10-10 23-44-31.webm](https://github.com/user-attachments/assets/b695c0b7-08fe-4a04-a1df-cd0f4ca1ffee)
[Peek 2024-10-10 23-50.webm](https://github.com/user-attachments/assets/f0044118-d431-4f73-86bb-3d6a5a3ec950)

### What you want

I'd appreciate to have a fixed minimum size for the window set that can not be made smaller beyond a certain threshold. At least the window title bar including the control buttons should remain visible in all cases. E.g. to have it like in DosBox Staging:

[Screencast From 2024-10-10 23-52-58.webm](https://github.com/user-attachments/assets/bf888c02-c74c-419a-8a0f-b17242ab0f35)

### Additional information

Tested on:
Plasma 6.2.0 Wayland
Plasma 6.2.0 XOrg
Gnome 47.0.1 Wayland
Gnome 47.0.1 XOrg
DosBox-X Version 2024.10.01 from Flathub

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
It does have a minimum size if you use output=surface. It does not set a minimum size for hardware accelerated modes like OpenGL.
if you need to set the window size back to normal, use the menu to "reset window size".

**Comment by joncampbell123** [comment]
Although that has only been tested on X11 and Windows. Not sure if Wayland supports that.

**Comment by rderooy** [comment]
Yes the resize menu option works on Wayland.

Log fragment:
```
LOG: DOSBox-X version 2024.10.01 Commit 70ade1c (Linux SDL2 64-bit)
LOG: Prevent capture: 0
LOG: SDL: version 2.30.3, Video wayland, Audio pulseaudio
LOG: Host keyboard layout is now  ()
LOG: Mapper keyboard layout is now  ()
LOG: SDL2 reports desktop display mode 2560 x 1440
LOG: The default output for the video system: opengl
LOG: Configured windowposition: -
LOG: SDL: Current window pixel format: SDL_PIXELFORMAT_RGB888
LOG: SDL: You are running in 24 bpp mode, this will slow down things!
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) at (0.000 x 0.000) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
```

**Comment by heldderarbeit** [comment]
Setting the sdl config option is not something I have explored yet. Seems like `output = ttf `is the best option to enforce a minimum window, with the cost of not being able to resize the window at all.

There's also 

```
output = surface
output = gamelink
```

Both enforce a minimum window size too, with the cost of having the window glitch around (But I assume that should be a separate issue).

[Screencast From 2024-10-20 15-57-44.webm](https://github.com/user-attachments/assets/638aac2e-9b4e-4d4c-89a7-7ca0cc2aad6f)
