### ISSUE TITLE
LS command causes to change the color of the output back to default

### ISSUE THREAD

**Issue by d1m4s1k** [joncampbell123/dosbox-x#5243]
### Describe the bug

I want to change the color of the screen text and after that list the files in the current directory but it happens to reset the color back to white which is default. I suppose it occurs because of the using the ls command that highlights some files with colors.
![image](https://github.com/user-attachments/assets/96faf7b3-005b-4a05-97c5-8464bdf3e86c)

### Steps to reproduce the behaviour

1. Type "color 0a"
2. Type "ls"

### Expected behavior

The color of the text had not changed

### What operating system(s) this bug have occurred on?

Windows 10 HSL

### What version(s) of DOSBox-X have this bug?

V2024.10.01, Visual Studio SDL1 64-bit

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I don't know about this. ANSI codes don't provide a way to read back state to restore it later.
On my Linux system, ls --color will reset any attributes I set on the terminal prior to it.
It makes logical sense that "ls" would have the same limitation: Resets the attribute to normal white on exit.

Unless DOS somehow allows "ls" to restore the attribute exactly as it was, it would be better for your program/script to re-apply the ANSI attributes it needs after running "ls".

**Comment by joncampbell123** [comment]
What I mean is, if MS-DOS ANSI.SYS provides no way to save/restore attributes in that way, then neither should DOSBox-X.
