### ISSUE TITLE
Configuration tool is not saving "configuration tool theme" setting to dosbox-x.conf

### ISSUE THREAD

**Issue by LukasThyWalls** [joncampbell123/dosbox-x#5245]
### Describe the bug

Hello.

DOSBox-X Configuration tool new setting for "Theme" works fine, although when I tried to save `dosbox-x.conf` through the Configuration Tool and restart DOSBox-X, the theme is always reset to "LCD Reversed - Dark" (which seems the default when using dark mode in the OS).

From DOSBox-X' `dosbox-x.conf`:
```
#  configuration tool theme: Theme for the configuration tool.
#                              If not set, host dark mode setting will be followed.
#                              
#                              Possible values: Windows Default, Arizona, Black Leather Jacket, Bordeaux, Cinnamon, Designer, Emerald City, Fluorescent, HotDog Stand, LCD Default Screen Settings, LCD Reversed - Dark, LCD Reversed - Light, Mahogany, Monochrome, Ocean, Pastel, Patchwork, Plasma Power Saver, Rugby, The Blues, Tweed, Valentine, Wingtips.

(...)

configuration tool theme  = 
```

If you set manually some value to `dosbox-x.conf` (for example "Bordeaux"), it uses it in the next boot, but if you try to change it and save it through the configuration tool, the theme setting is not changed (It maintains "Bordeaux").

It's not even needed to restart DOSBox-X to see this: If you enter the configuration tool, change the theme to other one, exit the configuration tool, enter again the configuration tool, and the theme set is the first one, not the other one you picked (If you have set one manually in `dosbox-x.conf`, it uses that one).

### Steps to reproduce the behaviour

1. Open DOSBox-X.
2. Open _Main_ dropdown menu -> _Configuration tool_.
3. Open _Theme_ dropdown menu inside the Configuration tool window.
4. Pick any other theme to change the colours of the Configuration tool window.
5. Push _Save ..._ button.
6. Push _Save & Restart_ (You can also push _Save_, exit DOSBox-X and start it again).
7. Open _Main_ dropdown menu -> _Configuration tool_ again.

### Expected behavior

The Configuration tool is set to the theme last picked that is supposedly saved in dosbox-x.conf.

### What operating system(s) this bug have occurred on?

Windows 10 Pro 22H2

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2024.10.01 (MinGW SDL2 64 bit) and DOSBox-X 2024.10.14 (MinGW SDL2 64 bit) https://github.com/joncampbell123/dosbox-x/actions/runs/11325938394

### Additional information

Thanks!

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Fixed, along with some cleanup on theme menu handling.
