### ISSUE TITLE
Documentation: Describe how to compile/change the BIOS logo in the source code

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#525]

**Comment by joncampbell123** [comment]
The BIOS logo is a Windows bitmap file compiled into the source code using the 'xxd' tool in Linux (take a binary file and convert to a C char array). The BMP file must follow a specific format. 

There are two versions:

- A 16-color version for VGA, EGA, and PC-98 startup
- A 4-color version for CGA

**Comment by empsmoke** [comment]
VS2017 takes too much time at "Give us a minute. We'll be done soon..." part.

**Comment by empsmoke** [comment]
VS2017 takes too much time at "Give us a minute. We'll be done soon..." part.

**Comment by joncampbell123** [comment]
It's a Microsoft minute... it has a proprietary unit of time.

**Comment by joncampbell123** [comment]
Is it installing now?

**Comment by empsmoke** [comment]
Not.

**Comment by joncampbell123** [comment]
What happened?

**Comment by empsmoke** [comment]
How do I fix GTA 1 and 2 speed issues in Project86 (which is my upcoming project)?

**Comment by joncampbell123** [comment]
Well, you first need to compile the code...

**Comment by joncampbell123** [comment]
Any luck compiling the code?

**Comment by empsmoke** [comment]
I cannot download VS, because the internet speed is like I am connected to a 56k Dialup modem!

**Comment by joncampbell123** [comment]
Guess not
