### ISSUE TITLE
PC-98 MS-DOS recognizes a mounted HDD image as both IDE and SCSI drive

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#5253]
### Describe the bug

PC98 MS-DOS recognizes a mounted HDD image as two drives.
It seems this isn't a recent regression.
I see the same on 2023.10.06 release as well. (I haven't checked older releases)

![image](https://github.com/user-attachments/assets/397ddcf9-d842-4d7d-aa5a-a6c3d22e429a)
![image](https://github.com/user-attachments/assets/9abdb21d-924c-4edb-bf87-2e6f77813ce0)

On 2023.10.06 release
![image](https://github.com/user-attachments/assets/ff48a580-7abe-4657-b365-43c716c91caf)

### Steps to reproduce the behaviour

1. Start PC-98 mode
2. IMGMOUNT a HDD image and boot a MS-DOS 6.2 install floppy
3. MS-DOS asks you which drive to install, and you see two drives (an IDE and SCSI drives) available instead of one.

### Expected behavior

Only IDE connected HDD should appear.

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

at least 2023.10.06 Release and after 

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Yes, to maximize compatibility with MS-DOS and bootable images, it responds to both IDE and SCSI versions of the BIOS interrupt for a hard drive.

**Comment by maron2000** [comment]
@joncampbell123 
Thank you for you comment.
So I understood this is intensional, so closing this issue.
