### ISSUE TITLE
PC-98: Microsoft MOUSE.COM complains "Mouse hardware not connected"

### ISSUE THREAD

**Issue by leonier** [joncampbell123/dosbox-x#528]
![nomouse](https://user-images.githubusercontent.com/6635408/36595005-6eb9c310-1898-11e8-96de-9fe468e6d63a.png)

The log reads:
```
3750317215 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=100C
PC-98 8255 MOUSE: IO write port=0x7fdf val=0x93
PC-98 8255 MOUSE: IO read port=0x7fdd

```

I think the reverse engineering of MOUSE.COM could be the first step of low-level emulation of PC-98 bus mouse.
[MOUSE.zip](https://github.com/joncampbell123/dosbox-x/files/1751690/MOUSE.zip)

**Comment by joncampbell123** [comment]
The mouse is wired in hardware to something that acts like an Intel 8255 so the trick is to figure out what bit it expects to be set, cleared, or toggled somehow.

**Comment by joncampbell123** [comment]
The mouse driver appears to read ports of the 8255 not yet emulated, and it appears to change one of the ports and one half of port C to the other direction momentarily.

I think the best way to fix this and model for other parts of the system based on the 8255 is to define an Intel8255 class that models the A, B, C, and control registers so things can be emulated more accurately.

On real hardware, I noticed that the 8255 remembers the output value you wrote UNTIL you change that port to an input, where it forgets it and resets it back to zero when you change it back to an output.

One more confusing thing is that the mode byte 0x90, used often in games, sets the upper half of port C to an input, when most games in that mode write to the upper half to latch the mouse, select the nibble, and enable interrupts. Is there some undocumented 8255 behavior here where a port configured as input can have an effect when writing the port regardless?

**Comment by joncampbell123** [comment]
A C++ class to simulate the 8255 I/O ports and behavior has been implemented. So far it's working as the 8255 to emulate the system ports 31h-37h odd. Next step is to use the C++ class to implement the 8255 connected to the bus mouse on PC-98.

**Comment by leonier** [comment]
How about to also get DIP switches / memory switches emulated ?

**Comment by joncampbell123** [comment]
I have some DIP switches mapped out with their functions, according to one source, but I have no documentation on DIP switches 2-1 to 2-8, except that 2-8 has something to do with GDC clock frequency.

**Comment by joncampbell123** [comment]
I just ported the 8255 mouse emulation to the C++ class framework for 8255 emulation.

I don't seem to have broken anything, and it seems that whatever MOUSE.COM didn't like, it's now OK with DOSBox-X's emulation.

At this point the only game that isn't happy with it is "Chrome Paradise - Ginhakushoku no Rakuen" and as far as I can tell, the game isn't properly acknowledging the mouse interrupt. The mouse is on IRQ 13 so it needs to acknowledge the slave and master PIC. Chrome is only acknowledging the master PIC, leaving the slave PIC stuck.

**Comment by joncampbell123** [comment]
Seems to work now.
