### ISSUE TITLE
Windows ARM32 build failure

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#5281]
### Describe the bug

CI builds currently fails for ARM 32-bit versions. 
Maybe fixed soon, but consider apply older SDK versions if this problem persists.

https://github.com/actions/runner-images/issues/10981

### Steps to reproduce the behaviour

Currently all ARM 32-bit Visual Studio nightly builds suffer this issue.

### What operating system(s) this bug have occurred on?

Windows SDK 10.0.26100.0

### What version(s) of DOSBox-X have this bug?

All current CI builds

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
The workaround by PR #5283 seems working fine.

**Comment by maron2000** [comment]
Closing this issue since Microsoft dropped ARM 32bit support in the latest Windows SDK, and the current workaround will be permanent.

https://github.com/actions/runner-images/issues/10981#issuecomment-2502968957

**Comment by joncampbell123** [comment]
> Closing this issue since Microsoft dropped ARM 32bit support in the latest Windows SDK, and the current workaround will be permanent.
> 
> [actions/runner-images#10981 (comment)](https://github.com/actions/runner-images/issues/10981#issuecomment-2502968957)

Ooh, that's gonna hurt for anyone who still wants binaries to run on their jailbroken Windows 8 Surface tablets.

**Comment by joncampbell123** [comment]
Does the MinGW project support ARM32? Or is it specific only to x86 and x86_64?

The original MinGW project, last I checked in 2017, could still compile down to Windows 98, and even Windows 95 if you were willing to install MSVCRT.DLL to get it to run.

**Comment by maron2000** [comment]
MinGW seems not to support Windows on 32bit ARM, but LLVM/Clang compiler supports Windows on ARM/ARM64.
https://github.com/mstorsjo/llvm-mingw
Visual Studio builds successfully by reverting the Windows SDK version, but it doesn't run on Windows 8 Surface tablets?
