### ISSUE TITLE
VGA 800x600 16-color mode 0x6A is incorrectly emulated

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#5288]
### Describe the bug

Two issues:
1. Standard VGA does not offer the 800x600 mode. It can't do it. It _can_ but the dot clock isn't fast enough to bring the refresh rate up to at least 50Hz needed for a VGA monitor to support it. See the IBM PS/2 model 30 VGA register dump here, notice no 0x6A mode: http://hackipedia.org/raw/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/VGA%20register%20snapshots/IBM%20PS%2d2%20MODEL%2030%20286%20with%20VGA%20%282019%2d09%2d28%29%2etar%2exz
2. SVGA cards do offer it. DOSBox-X emulation doesn't program the dot clock properly and the resulting refresh rate is too low (37Hz). Even if using the 28MHz dot clock that only results in 40Hz. The S3 Virge register dump suggests that 800x600 is possible if you use higher dot clocks than standard VGA: http://hackipedia.org/raw/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/VGA%20register%20snapshots/S3%20Virge%20DX%20%28PCI%29%2etar%2exz

### Steps to reproduce the behaviour

1. Run a DOS program that sets INT 10h mode 0x6A.
2. Observe that this is allowed for machine=vgaonly, which is wrong.
3. Observe that with machine=svga_s3, it is allowed as it should, the log file reports a refresh rate of 37Hz 

### Expected behavior

The refresh rate for 800x600 16-color should be at least 60Hz (maybe 56Hz?). Examine S3 register dump to determine what it should be.

Maybe 85Hz? http://martin.hinner.info/vga/timing.html

### What operating system(s) this bug have occurred on?

Linux x86_64

### What version(s) of DOSBox-X have this bug?

Latest commit

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by MrMadguy64** [comment]
Well, [this software](https://github.com/jharg93/SvgaBGI) seems to be real software and it has 800x600 tweaked mode support. But calculations show, that it uses 28MHz pixel clock and 45Hz vertical refresh rate. I guess, standard VGA monitor wouldn't handle it. Or may be would. Who knows.

**Comment by MrMadguy64** [comment]
MiscClock = 2 is usually reserved for external clock. I'm not sure, what it means. Clock from feature connector may be? I don't even know, what this thing was used for. Something like SLI?

Have you read [manual](http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/SVGA/S3%20Graphics%2c%20Ltd/S3%20ViRGE%20Integrated%203D%20Accelerator%20%281996%2d08%29%2epdf)? It says nothing about MiscClock = 2 both for Trio and Virge. But MiscClock = 3 is used for programmable clock generator.

**Comment by MrMadguy64** [comment]
Why do you think, MiscClock = 2? According to dump 3CCh = 2Fh, i.e. MiscClock = 3.

**Comment by MrMadguy64** [comment]
Therefore it's SVGA mode. Shouldn't it be just alias for 102h?

**Comment by joncampbell123** [comment]
> Therefore it's SVGA mode. Shouldn't it be just alias for 102h?

Yes. That's exactly how mode ox6A is documented.

**Comment by joncampbell123** [comment]
A-ha. The S3 code to set clock == 3 and set up the VGA clock for 800x600x16 was only called if setting up mode 0x102. Setting up the same mode through 0x6A did not take that path. Fixed.
