### ISSUE TITLE
2024-10-1 installs again and again with winget in Windows

### ISSUE THREAD

**Issue by fritzmueller** [joncampbell123/dosbox-x#5296]
### Describe the bug

Windows has an internal tool called "winget", a command-line tool close to "apt-get" in Linux.
The actual version of DOSBox-X 2024.10.01 is already installed. Nevertheless winget reports:
joncampbell123.DOSBox-X  < 2024.10.01 available version: 2024.10.01, source: winget,

 winget downloads from https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v2024.10.01 /dosbox-x-windows-2024.10.01-setup.exe 
Then 95,7 MB are downloaded, installation is started, you have to confirm yes/no/abort. DOSBOX-X works.

As soon as you reboot and open winget the next time the installation starts again.

Thx for reading.

Fritz

### Steps to reproduce the behaviour

1.  check installation routine with winget. If an older version is already installed,  winget with admin rights looks for updates.

### What operating system(s) this bug have occurred on?

Win 11 Pro, 24 H 2

### What version(s) of DOSBox-X have this bug?

v2024-10-01, Visual Studio SDL1 64-bit

### Used configuration

```ini
Please test winget with admin rights.
```

### Output log

```text
none
```

### Additional information

none

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Isn't this more likely a bug of winget?
DOSbox-X installer doesn't repeat installing by itself.

**Comment by fritzmueller** [comment]
i assumed it maybe a problem of the version number, correct file name of zip file or somthing related as it says that the existing file is older than the new one.

 
 

Sent: Saturday, November 30, 2024 at 12:56 PM

**Comment by maron2000** [comment]
Well, that's just your assumption, ask the winget guys what they see as I already mentioned.

**Comment by maron2000** [comment]
Registry clearly says the right version.
I reverted to 2024.07.01 and reinstalled, and I get the same result as well.
![image](https://github.com/user-attachments/assets/75453b0e-3afa-4308-a9c6-59bebd8f75d7)

**Comment by maron2000** [comment]
Installation information in the registry seems fine as well.

![image](https://github.com/user-attachments/assets/9933f109-fc9e-4c4c-bb1f-d8ea7198a4b4)
![image](https://github.com/user-attachments/assets/fad84ec9-d424-4cd8-9c35-a16df09c53b5)

**Comment by maron2000** [comment]
I uninstalled everything and installed 2024.03.01 and then installed by 2024.10.01 from the official installers (not winget).
I see no duplicate installs, 2024.10.01 installer simply overwritten the old installation.
Therefore this is a problem of winget, and maybe they can suggest some changes in the DOSBox-X installer to meet their version management if any.

Anyway, seems that you managed to workaround, you can close this issue.
