### ISSUE TITLE
After the War

### ISSUE THREAD

**Issue by Neville0097** [joncampbell123/dosbox-x#5299]
### Describe the bug

This game fails to show the main menu, at least with default options. It works fine with the latest official version of DOSBox, which I find strange.

### Steps to reproduce the behaviour

Start the game, ask to load Part I. After the loading screen the emulator shows garbled graphics. You can proceed from here, but in-game graphics are also messed up.

### Expected behavior

The game becomes unplayable due to corrupted graphics

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2024.10.01

### Used configuration

```ini
Default options
```

### Output log

```text
I haven't noticed any error messages nor does the emulator crash
```

### Additional information

The game itself is peculiar. Rather than a real DOS port it seems to play the Spectrum version of the game under an emulator. Pedro Gimeno, author of an early ZX Spectrum remulator, is credited with the "conversion".

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by MX9000** [comment]
@Neville0097 try older releases: I have a machine with a very old DOSBox-X 2022.12.26 in which the game graphics are OK.

**Comment by Neville0097** [comment]
I can play the game just fine with DOSBox v0.74-3. I can't see why I should try older releases of DOSBox-X, unless that helps to pinpoint the origin of the bug. Is this what you're suggesting?

**Comment by MX9000** [comment]
Of course, it looks like a regression introduced in some recent release.

**Comment by maron2000** [comment]
It seems you need to switch off `doublescan` option.

![image](https://github.com/user-attachments/assets/b1c552ab-0ae8-4b0a-a459-c35a76ec2ab2)
![image](https://github.com/user-attachments/assets/9a262e82-b963-4b22-a00a-8b8bf01bdb5f)

**Comment by Neville0097** [comment]
I'm still having trouble after disabling doublescan. Main menu shows this:

https://i.imgur.com/1qxqdWF.png

**Comment by maron2000** [comment]
Try switching `output` to something else than ttf.

**Comment by Neville0097** [comment]
> Try switching `output` to something else than ttf.

That solves it. Thank you. Just wondering, do these options break a lot of games? Because if they do, I think they should be disabled by default.

**Comment by joncampbell123** [comment]
TTF output is intended for text mode, not games. It uses a TrueType font instead of the standard VGA bitmap font to render the console. TTF output shouldn't be default. If TTF output is coming up as a default, that needs to be fixed.

**Comment by joncampbell123** [comment]
Testing the game with machine=ega.

It looks like the game's "graphics" are really just 40x25 text mode, but with some register tweaks to turn text mode into a sort of 320x200 graphics mode.

Since DOSBox-X by default emulates the EGA 350-line raster for machine=ega, this means the game is squeezed into the top half and the bottom half is gray lines leftover from text mode. So either it's mis-detecting the EGA, or it was coded for EGA cards configured for CGA-compatible 200-line output.

**Comment by joncampbell123** [comment]
Uh, but then some of the bottom of the "graphics" gets cut off for machine=ega200. Huh.

Works correctly with machine=vgaonly.

**Comment by joncampbell123** [comment]
Is there some weird CPU timing detect in the game? A cycle count below 30000 causes a garbled display?

**Comment by joncampbell123** [comment]
I see the game is EGA and VGA aware by the INT 10h calls to set the EGA palette, and then the VGA palette, using INT 10h. It reorders the color palette though. It arranges the color palette in a manner that seems to match the ZX Spectrum: https://lospec.com/palette-list/zx-spectrum

And then it calls INT 10h AH=12h BL=30h to reconfigure text mode into a 200-line display mode (as in, 8x8 CGA graphics). http://www.ctyme.com/intr/rb-0167.htm

**Comment by joncampbell123** [comment]
This game handles EGA/VGA hardware in a weird way that isn't a simple fix. I'll keep this issue open.

**Comment by joncampbell123** [comment]
If the game detects it is on VGA, it calls INT 10h to set 200-line text mode.
If the game detects it is on EGA (by whether the VGA INT 10h call fails), it modifies 16-bits in the BIOS data area at 0x487-0x488. It appears to hack those bits to trick the EGA BIOS into thinking that the DIP switches are in "Enhanced Display Emulation Mode" which I think means 200-line CGA-like text mode, and it hacks the other bits to convince the BIOS that the EGA only has 64K of RAM.
![image](https://github.com/user-attachments/assets/2952183e-aa18-40cd-876e-b5781ad9e127)
![image](https://github.com/user-attachments/assets/d2972463-f81b-4451-9c77-b6ed5726f9ff)

**Comment by joncampbell123** [comment]
Latest commit fixes the game's weird Spectrum graphics emulation hackery for VGA (machine=vgaonly), now to fix for machine=ega.

**Comment by joncampbell123** [comment]
Fixed for machine=ega now.

**Comment by Neville0097** [comment]
Terrific. Thanks for looking into this issue.
