### ISSUE TITLE
Project86

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#530]
Dear Jon Campbell,
I am working on Project86,
a new emulator which includes major and minor fixes from this, 
and will be in alpha since that is still in development.

**Comment by joncampbell123** [comment]
Good for you.

Don't file issues here unless you have actual issues with DOSBox-X. Issues with Project86 don't count here.

This issue tracker is not for your announcements. If you have anything to say do it in your project86 repository and issue tracker.

**Comment by joncampbell123** [comment]
If you wish to promote your project please do it on your own account on your social media site or forum of your choice.
