### ISSUE TITLE
Armored Fist: Mouse is not automatically captured

### ISSUE THREAD

**Issue by Neville0097** [joncampbell123/dosbox-x#5301]
### Describe the bug

After loading the game and reaching the main menu, the mouse pointer stays at the top right corner of the screen and remains unresponsive until I press the mouse middle button.

### Steps to reproduce the behaviour

Normally load the game, wait until main menu appears. Or press ESC to skip the intros.

### Expected behavior

Mouse should be automatically captured?

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

DOSBox-X v2024.12.04, Visual Studio, SDL1, x64

### Used configuration

```ini
Default options, except for cycles=15000. I was advised to use this speed a long time ago in VOGONS, because cycles=auto causes the mouse pointer to disappear when accessing the map screen in-game (with ESC).
```

### Output log

```text
I haven't seen any error messages.
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
If the game is using INT 33, that means it's using the relative mouse motion calls, not the calls to read absolute mouse position. Therefore, it cannot auto capture the mouse.

**Comment by Neville0097** [comment]
Not a bug, then? In that case we should close the issue.
