### ISSUE TITLE
dosbox-x machine -ega shows blue background; COLOR 0 is blue, COLOR 2 is magenta, etc.

### ISSUE THREAD

**Issue by blandbyte** [joncampbell123/dosbox-x#5309]
### Question

I launch dosbox-x like on macOS 15.0.1:

```
dosbox-x -machine ega -c cls
```

This is the result:

![01-cls](https://github.com/user-attachments/assets/bbaed469-2485-4a4f-846d-ba2c73688efc)

Why is the background blue?

Now I do some color tests:

![02-color](https://github.com/user-attachments/assets/ef0400f5-86cb-4fc8-a667-cb73d5c7e546)

![03-test](https://github.com/user-attachments/assets/fe516141-e884-4614-acee-241a3a42a894)

So `COLOR. 70` is background color `7` (white) and foreground color `0` (black). But why does the foreground color appear blue?

Likewise `COLOR 72` is foreground color `2` (green). But why does the foreground color appear magenta?

This problem does not happen in dosbox though. Like so:

```
dosbox -machine ega -c cls
```

![dosbox](https://github.com/user-attachments/assets/fbd9f194-f418-4656-b1a0-69cfe35f06bf)

Anyone knows what's going on here? Can I make dosbox-x behave like dosbox when launched with `-machine ega` so that the background color is black and the `COLOR` command gives the documented output?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by blandbyte** [comment]
If I take a screenshot of dosbox-x using the menu item Capture--Take screenshot or F12+P, I see correct colors in screenshot.

I mean on my laptop screen I see incorrect colors this:

![03-test](https://github.com/user-attachments/assets/afdefbd9-c344-4b8f-a9bf-6efb0abf935e)

But if I take a screenshot with F12+P, the screenshot written by dosbox-x shows correct colors like this:

![command_002](https://github.com/user-attachments/assets/cb66dc74-6f44-4507-bfc8-6240222053a4)

Any idea why this difference?

**Comment by maron2000** [comment]
This has been reported several times, (#4571, #4753) but haven't been fixed yet.
It is a problem of SDL2 build with OpenGL output. Try either `output=surface` or SDL1 build.
SDL1 build has color glitches with screenshots (#4515).
