### ISSUE TITLE
Will modify diskio_delay() function have any side effects?

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#5312]
### Question

I would like to ask: The speed of changing this is obviously much faster. I wonder if there are any side effects.

![Diskio_delay](https://github.com/user-attachments/assets/00c9cf49-8502-4ae3-8b92-261b0c3eb635)

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
It is better to use dosbox.conf to set the hard disk and floppy disk delay to 0 to disable them.

**Comment by Arthur3032** [comment]
Set disk delay to 0 in .conf, but the speed is not significantly improved.
As above
// do { // mark by Arthur
 // CALLBACK_Idle();
 // } while (PIC_FullIndex() < endtime);
The speed increase is obvious.
But I wonder if there will be a bug?

**Comment by Arthur3032** [comment]
Got it, thank you very much.

**Comment by joncampbell123** [comment]
Of course. I would never code something like a disk delay without giving you a dosbox.conf option to control it or disable it.
