### ISSUE TITLE
[Version 2024.12.04] [Win9x/NT4+ Build] Will not start. Error: "The DOSBOX-X.EXE file is linked to missing export KERNEL32.DLL:GetConsoleWindow."

### ISSUE THREAD

**Issue by dg410a** [joncampbell123/dosbox-x#5314]
Not sure if this is a bug or if I'm missing something. So, I'll post this as a blank issue.

I just downloaded the Windows 9x build of DOSBox-X and I could not get it to start on my Windows 98 SE machine. I get the following error:

"The DOSBOX-X.EXE file is linked to missing export KERNEL32.DLL:GetConsoleWindow."

The OS has all updates installed through the Windows 98 SE Unofficial Service Pack 2.1 and I also have Visual C++ 2005 Redistributable installed. I'm not sure what else I need to make this work or if the Win9x build is just broken at the moment. Of course, I could just use KernelEx, but I don't want to go through the trouble of installing it just to get DOSBox-X working on Win 98 SE. For clarification, I am using the latest version of DOSBox-X as I write this.

**Comment by MrMadguy64** [comment]
GetConsoleWindow requires Windows 2000. Such functions shouldn't be imported statically. Only via GetProcAddress.

**Comment by dg410a** [comment]
Ok. So, based on the comments so far, I went ahead and tried the Win9x build version 2024.03.01, and I was able to start it under Windows 98 SE. 

So, something must've definitely changed in how it was compiled with regards to the latest version (2024.12.04 as of this writing). Probably the only option for now is to compile it myself, but I'll probably need instructions as to how to properly create a build that actually works under Windows 9x. Or maybe something in the package is broken to the point where it doesn't work on Win9x period no matter how I would compile it.

**Comment by Dobby233Liu** [comment]
On Discord:
![image](https://github.com/user-attachments/assets/c9dfe05e-bdbc-4d39-ba0d-fe3ed71bd343)

**Comment by Dobby233Liu** [comment]
Personally I suspect it being caused by the tinyfiledialogs update

**Comment by MrMadguy64** [comment]
Searching is sources shows following references to GetConsoleWindow:
\src\debug\debug.cpp: 4460, 4465
\src\gui\menu_callback.cpp: 2352, 2364
\src\gui\sdlmain.cpp: 6862, 8651, 8652

**Comment by Dobby233Liu** [comment]
> Searching in sources shows following references to GetConsoleWindow:

All of these have a `!defined(_WIN32_WINDOWS)` guard

**Comment by MrMadguy64** [comment]
> > Searching in sources shows following references to GetConsoleWindow:
> 
> All of these have a `!defined(_WIN32_WINDOWS)` guard

Yeah, you're right. 

tinyfiledialogs.c has following references to GetConsoleWindows, that aren't guarded: 2744, 2860, 2902, 3036, 3104, 3158, 3213

**Comment by maron2000** [comment]
Can you try the nightly build by PR #5319.
