### ISSUE TITLE
Can I use ChinaSea for this font?

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#5315]
### Is your feature request related to a problem? Please describe.

I use the default font of Dosbox-X and can use ChinaSea. However, when selecting this font (TW-Kai-98_1.ttf), I cannot use ChinaSea.

[TW-Kai-98_1.rar.zip](https://github.com/user-attachments/files/18131959/TW-Kai-98_1.rar.zip)

### What you want

I hope that when using TW-Kai-98_1.ttf, I can also use CHinaSea

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by 1abcd** [comment]
You need to use a font that includes ChinaSea characters, such as the default TTF font.

Or you can download the custom fonts made by Wengier few years ago from cndos.rthost.win/dosware/hanfullsea.zip

**Comment by Arthur3032** [comment]
> You need to use a font that includes ChinaSea characters, such as the default TTF font.
> 
> Or you can download the custom fonts made by Wengier few years ago from cndos.rthost.win/dosware/hanfullsea.zip

Great, thank you very much for this information.
