### ISSUE TITLE
PSE in 486

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#5318]
### What you want

Thank you @joncampbell123 for beginning to add PSE! 
Do you plan for PSE-36 and PAE as well? I would like to try NT/2K/XP with [more than 4GB RAM](https://github.com/joncampbell123/dosbox-x/issues/4185#issuecomment-1520997202).

It seems some late i486 CPUs (stepping 9?) support PSE as well - that's how I interpret its [CPUID EDX 0xB result](https://x86.fr/universal-chip-analyzer-supports-486/).

Other functions found only in some 486:
- [Virtual-8086 mode extensions](https://en.wikipedia.org/wiki/Virtual_8086_mode#VME) (VME)
- RSM - [System Management Mode](https://en.wikipedia.org/wiki/System_Management_Mode)
- [Model-specific registers](https://en.wikipedia.org/wiki/Model-specific_register) and RDMSR/WRMSR instructions in [IBM 486](https://web.archive.org/web/20040604002243/http://debs.future.easyspace.com/Programming/OS/cpuid.txt)

Related functions found only in some 386:
- MSR in [IBM 386](https://web.archive.org/web/20040604002243/http://debs.future.easyspace.com/Programming/OS/cpuid.txt)
- RSM - [System Management Mode](https://en.wikipedia.org/wiki/System_Management_Mode)
- C&T Super386 has a [CPUID variant](https://www.os2museum.com/wp/more-on-the-ct-super386/#comment-327662) providing CPU type, CPU stepping, microcode stepping.

Is RSM/SMM supported in DOSbox-X?

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
I just added PSE-36 support, though I'm not 100% certain I will be able to map memory above 4GB yet.

Yes, I am planning on PAE support, though within the framework of the current codebase, it will be kind of a hack to fit it within the TLB design.

**Comment by joncampbell123** [comment]
PSE is now supported in cputype=486, but not cputype=486old. That is why this issue is closed now.
