### ISSUE TITLE
Nightly build crashes when switching to PC-98 mode

### ISSUE THREAD

**Issue by maron2000** [joncampbell123/dosbox-x#5320]
### Describe the bug

Commit ad30600bf9d494936034a37c4b1b1b3a6d40b0a1 crashes when switching to PC-98 mode

### Steps to reproduce the behaviour

1. Launch DOSBox-X in normal mode, e.g svga_s3
2. Switch to PC-98 mode by command `config -set machine=pc98`

### Expected behavior

No crash in switching to PC-98 mode.

### What operating system(s) this bug have occurred on?

Windows 10 22H2 VS x64 build

### What version(s) of DOSBox-X have this bug?

commit ad30600bf9d494936034a37c4b1b1b3a6d40b0a1

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Ugh, never mind. It's making a decision based on CPU type when CPU type hasn't been read and determined yet, and then defaulting to 36 bits.

**Comment by joncampbell123** [comment]
Fixed.

**Comment by maron2000** [comment]
Thank you. I confirm switching to PC-98 mode is possible again.
