### ISSUE TITLE
"IBM ROM BASIC NOT IMPLEMENTED"

### ISSUE THREAD

**Issue by joho1968** [joncampbell123/dosbox-x#5326]
### Question

Trying to run programs compiled with Borland Pascal 7 for 8086/8088, they either hang hard, or start outputting "IBM ROM BASIC NOT IMPLEMENTED" over and over again.

I wonder if I've missed a setting somewhere?

> DOSBox-X version 2024.12.04 (32-bit SDL2) running in a Windows 10 32-bit guest which has a VirtualBox 7.x host (Windows 10 64-bit). Upon start, it says 16384KB memory installed, Video card is S3 Trio64 SVGA, 8086 CPU present, APM interface active, and ISA Plug & Play BIOS active.

_(This is with `fpu` set to `false` and `cputype` to `8086` in the configuration)_

Running other programs, like one built with Watcom 10.6 C/C++, seems to be working just fine. Also, BP.EXE and BPC.EXE themselves hang with similar behavior. TASM.EXE (Turbo Assembler) works fine.

If I change the `cputype` to `80186`, I get a warning that an 80286 or better is required. But the programs actually compiled with it seems to run. Maybe I should just leave it set to that and move on, but I'm curious 😎 

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment]
Seems you need to load the original IBM BASIC ROM. Get the ROM and specify its location and name in the dosbox-x config file.
```
[dosbox]
ibm rom basic                                   = <filename.rom>
```

**Comment by joncampbell123** [comment]
Please use this file: https://github.com/joncampbell123/dosbox-x/blob/master/ROMs/IBMROMBASIC-F6000h-1982-10-27.ROM

This file was obtained from the ROM collection that the PCem/86box devs like to maintain elsewhere here on Github,

**Comment by lgblgblgb** [comment]
I guess, interrupt 18h was indeed intended as the way starting ROM BASIC (in very early [?] PCs), but various programs (including at least Turbo Pascal what I remember now ...) re-used that interrupt for its own purposes. So maybe it's not really the lack of ROM BASIC what the problem here? Well, at least I don't see too much reason that Turbo (Borland?) BASIC 7 would need the ROM BASIC for real. But for sure, I can be wrong here.

**Comment by joncampbell123** [comment]
http://www.ctyme.com/intr/rb-2241.htm

**Comment by lgblgblgb** [comment]
> http://www.ctyme.com/intr/rb-2241.htm

Yes that was the original purpose. Indeed, as I've written.

**Comment by joncampbell123** [comment]
> > http://www.ctyme.com/intr/rb-2241.htm
> 
> Yes that was the original purpose. Indeed, as I've written.

Of course. I thought it would help others better understand what INT 18h is for.

**Comment by joho1968** [comment]
> Maybe it's not really the lack of ROM BASIC what the problem here? Well, at least I don't see too much reason that Turbo (Borland?) BASIC 7 would need the ROM BASIC for real. But for sure, I can be wrong here.

Yes, Borland. No, I can't see any reason for it either. If I change the CPU to 80286 or better, there are no issues at all. Perhaps it's some "DOS Extender" or other similar thing at work.

Thank you both for the feedback.

**Comment by lgblgblgb** [comment]
> > Maybe it's not really the lack of ROM BASIC what the problem here? Well, at least I don't see too much reason that Turbo (Borland?) BASIC 7 would need the ROM BASIC for real. But for sure, I can be wrong here.
> 
> Yes, Borland. No, I can't see any reason for it either. If I change the CPU to 80286 or better, there are no issues at all. Perhaps it's some "DOS Extender" or other similar thing at work.

Unfortunately, other than my faint memory from the past I could only find this:

_Turbo Pascal, Turbo C and Turbo C++ repurposed INT 18 for memory allocation and paging. Other programs also reused this vector for their own purposes._

It's on this wikipedia page:  https://en.wikipedia.org/wiki/BIOS_interrupt_call#INT_18h

But at least this seems to be closer the root of the issue than assuming a Pascal compiled program really needs ROM BASIC.

**Comment by joncampbell123** [comment]
> > > Maybe it's not really the lack of ROM BASIC what the problem here? Well, at least I don't see too much reason that Turbo (Borland?) BASIC 7 would need the ROM BASIC for real. But for sure, I can be wrong here.
> > 
> > 
> > Yes, Borland. No, I can't see any reason for it either. If I change the CPU to 80286 or better, there are no issues at all. Perhaps it's some "DOS Extender" or other similar thing at work.
> 
> Unfortunately, other than my faint memory from the past I could only find this:
> 
> _Turbo Pascal, Turbo C and Turbo C++ repurposed INT 18 for memory allocation and paging. Other programs also reused this vector for their own purposes._
> 
> It's on this wikipedia page: https://en.wikipedia.org/wiki/BIOS_interrupt_call#INT_18h
> 
> But at least this seems to be closer the root of the issue than assuming a Pascal compiled program really needs ROM BASIC.

So if somehow the original vector gets restored and then the still running program allocates memory, it will end up calling the BIOS to reboot the system? Ha! :)

**Comment by lgblgblgb** [comment]
> So if somehow the original vector gets restored and then the still running program allocates memory, it will end up calling the BIOS to reboot the system? Ha! :)

Well, yes ... Unfortunately I cannot remember the details but I think I had the same issue with my own project many-many years ago, when I wanted to write my "own DOSEMU" (called DOSRUN) which utilized the Linux kernel's vm86()/vm86plus() syscall and had only very limited functionality barely enough to run programs (no graphical modes etc) I wanted. Surely, it can be the case that it was something different, getting old does not spare my memory either :(
