### ISSUE TITLE
The version released on 2024.12.04 cannot input Uincode Chinese characters.

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#5327]
### Describe the bug

The version released on 2024.12.04 cannot input Uincode Chinese characters.
For example: 煊, 綉, 菓...
Version 2024-09-14, can be input normally.
When tested in different versions, the dosbox-x.conf settings are the same.

### Steps to reproduce the behaviour

1.execute Dosbox-x.exe
2.D:\> keyin 煊, 綉, 菓
3. Uicode fonts will not appear

### What operating system(s) this bug have occurred on?

Windows 11 23H2

### What version(s) of DOSBox-X have this bug?

2024.12.4

### Used configuration

```ini
output = ttf
[ttf]
gbk = true 
chinasea = false
uao  = true 
[config]
country = 886,951
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
Can you try the following build? (Maybe you have to wait until the building process is completed)
https://github.com/maron2000/dosbox-x-1/actions/runs/12444533954

![image](https://github.com/user-attachments/assets/eafcc466-17c3-4cb5-ba86-98fa7027a49d)

**Comment by Arthur3032** [comment]
> Can you try the following build? (Maybe you have to wait until the building process is completed) https://github.com/maron2000/dosbox-x-1/actions/runs/12444533954
> 
> ![image](https://private-user-images.githubusercontent.com/68574602/397922015-eafcc466-17c3-4cb5-ba86-98fa7027a49d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3Nzk3OTMsIm5iZiI6MTczNDc3OTQ5MywicGF0aCI6Ii82ODU3NDYwMi8zOTc5MjIwMTUtZWFmY2M0NjYtMTdjMy00Y2I1LWJhODYtOThmYTcwMjdhNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDExMTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYTY3MWY5MGQzNjdjNTM5ZWQ5NGRhMWQ4ODE5NDcwYjk0YTFkMmQxYmNjZWIwY2JiYjk0NTlhMDJmZjg0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XCGOUnCgv-PPDpYJiFDfttLgFz1ToEV9I6GqBhmrLxY)

OK, I'll try,
Thank you very much.

**Comment by maron2000** [comment]
It says the build finished in 19 min. in total?

![image](https://github.com/user-attachments/assets/90105135-2438-4e0e-8f8b-7b6f261c5a9e)

**Comment by 1abcd** [comment]
@Arthur3032
You must log in before you see the download buttons at the bottom of Summary page.

**Comment by 1abcd** [comment]
Hi @maron2000. Can you fix the problem below?

<img width="264" alt="2024-12-22 003343" src="https://github.com/user-attachments/assets/f555c2e4-b1bb-498a-b583-ee64053bfc82" />

**Comment by Arthur3032** [comment]
> Can you try the following build? (Maybe you have to wait until the building process is completed) https://github.com/maron2000/dosbox-x-1/actions/runs/12444533954
> 
> ![image](https://private-user-images.githubusercontent.com/68574602/397922015-eafcc466-17c3-4cb5-ba86-98fa7027a49d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MzQxNjUsIm5iZiI6MTczNDgzMzg2NSwicGF0aCI6Ii82ODU3NDYwMi8zOTc5MjIwMTUtZWFmY2M0NjYtMTdjMy00Y2I1LWJhODYtOThmYTcwMjdhNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDAyMTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NWM3MDk5Njk4MjkxNmZhZDVkNmM0NmMwZTkxMjM0YzQ2NDBmYzJjOTE5MTA0ODM3ZjE0OGU5YTNlZDJjY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.01GkTbKp90dAbjroiyrEDoAfiKddC44BhQo2a-AC_ow)

I can input normally. Where can I download the source code?

**Comment by maron2000** [comment]
@1abcd 
Try the following build.
Since I don't know the difference between CP950 and CP951, I'm not sure it is working or not.

https://github.com/maron2000/dosbox-x-1/actions/runs/12450744095

**Comment by 1abcd** [comment]
> @1abcd Try the following build. Since I don't know the difference between CP950 and CP951, I'm not sure it is working or not.
> 
> https://github.com/maron2000/dosbox-x-1/actions/runs/12450744095

I try to use two .lng files. The other file is uao.lng. ([UAO.LNG.txt](https://github.com/user-attachments/files/18220941/UAO.LNG.txt) remove the extension .txt and put it in languages folder)

![螢幕擷取畫面 2024-12-22 141753](https://github.com/user-attachments/assets/553c6691-a8b5-4c20-990c-375ea4d44452)

It seems not always working correctly.
Maybe the problem is too complicated to find a solution. Thanks for your effort.

**Comment by Arthur3032** [comment]
language=  ; output = ttf  ; gbk = true ; chinasea = false ; uao  = true  ; country = 886,951

Unicode Chinese characters can be entered correctly,
But the system menu is in English.

If language=zh_TW, the system menu is in Chinese, but Unicode Chinese characters cannot be input.

How do I set it up so that I can have a Chinese system menu and be able to input Uincode Chinese characters?

**Comment by maron2000** [comment]
@1abcd 
The following build seems working but please try.

https://github.com/maron2000/dosbox-x-1/actions/runs/12453833359

![image](https://github.com/user-attachments/assets/2e05c5ab-f762-4a19-8589-673209f48f2e)

**Comment by maron2000** [comment]
@Arthur3032
Try the latest build mentioned above.
I don't reproduce.

![image](https://github.com/user-attachments/assets/a556f327-12dc-43bd-b1ae-5b9755735fcb)

![image](https://github.com/user-attachments/assets/dc3930f8-fa66-48c6-bef8-f92ce728f043)

**Comment by Arthur3032** [comment]
> @Arthur3032 Try the latest build mentioned above. I don't reproduce.
> 
> ![image](https://private-user-images.githubusercontent.com/68574602/397983891-a556f327-12dc-43bd-b1ae-5b9755735fcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzAwNzMsIm5iZiI6MTczNDg2OTc3MywicGF0aCI6Ii82ODU3NDYwMi8zOTc5ODM4OTEtYTU1NmYzMjctMTJkYy00M2JkLWIxYWUtNWI5NzU1NzM1ZmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDEyMTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYTNlYWVkZmRmNWExNGEwN2QwMDM2NTlkNTQ4NzIzMDg2NmI0MDdiZWU4ZjJhOWM3MzZjMjBhOTRjMDg0N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iKeImRPkg-WXYZJbhMPD_TZ0LY4VWSx027WmfXKPk_8)
> 
> ![image](https://private-user-images.githubusercontent.com/68574602/397983999-dc3930f8-fa66-48c6-bef8-f92ce728f043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzAwNzMsIm5iZiI6MTczNDg2OTc3MywicGF0aCI6Ii82ODU3NDYwMi8zOTc5ODM5OTktZGMzOTMwZjgtZmE2Ni00OGM2LWJlZjgtZjkyY2U3MjhmMDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDEyMTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMDg1MGRjMjAyYjQ2NmI5ZGFhYjZhYjEzNDM3NWNiMDkyNDkzZGZlOTc3MzZkNzM1NTRlODM0NWM5ZDQ1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fUSa2zYYCNMERt-nkwt2Ljhi0izIkNAHC9F7O71p3yI)

OK, great, thank you!

**Comment by Arthur3032** [comment]
https://github.com/maron2000/dosbox-x-1/actions/runs/12453833359
![Menu3](https://github.com/user-attachments/assets/39465c72-2bd4-4422-9989-46d02a3b5de3)


In this version, this symbol will not appear when typing \


language= ; output = ttf ; gbk = true ; chinasea = false ; uao = true ; country = 886,951

**Comment by maron2000** [comment]
I can't reproduce.
If further fix isn't trivial, I propose not going further since it may induce more regressions.

```
dosbox-x -defaultconf -set output=ttf -set gbk=true -set chinasea=false -set uao=true -set country=866,951 -set keyboardlayout=tw
```
![image](https://github.com/user-attachments/assets/e018be55-d9a5-4584-9e9a-3114b03a4f83)

```
dosbox-x -defaultconf -set output=ttf -set gbk=true -set chinasea=false -set uao=true -set country=866,951 -set keyboardlayout=tw -set language=zh_tw
```
![image](https://github.com/user-attachments/assets/90546f3f-8639-433d-83e2-b47d04896251)

**Comment by Arthur3032** [comment]
dosbox-x -defaultconf -set output=ttf -set gbk=true -set chinasea=false -set uao=true -set country=866,951 -set keyboardlayout=tw -set language=zh_tw

Yes. That's fine now. Thank you very much.

**Comment by maron2000** [comment]
Loading uao.lng switching to CP950 works, but I don't know if it is worth it, since you lose some characters as you see in the screenshot.

![image](https://github.com/user-attachments/assets/2f3f9c6c-7de6-4503-af44-5e98bdf38bec)

**Comment by Arthur3032** [comment]
The problem has been solved now.
I found that there are some differences in the contents of your dosbox-x.conf and the one posted by joncampbell123.
Did the two go their separate ways?

**Comment by maron2000** [comment]
No, I have never touched the default values of the options in the conf file, so never diverts from the original repository.
`-defaultconf` option ensures you are really using the default options, which is a good benchmark to start with when you find any flaws.
So it's not my conf, but is the default.

**Comment by maron2000** [comment]
So I will go ahead and make a PR for switching the language files with CP950/951.

**Comment by Arthur3032** [comment]
So. I download the Source code of Doxbox-X,
Are dosbox-x-1-master and dosbox-x-master the same?

**Comment by maron2000** [comment]
`master` in my repository is totally identical with the original but not always up to date, so use Jon's original.
In other words, don't use the one in mine to avoid confusions.
The PR is now merged so there is no reason to use mine.

**Comment by Arthur3032** [comment]
> `master` in my repository is totally identical with the original but not always up to date, so use Jon's original. In other words, don't use the one in mine to avoid confusions. The PR is now merged so there is no reason to use mine.

Got it, thank you!
