### ISSUE TITLE
GIT download failure

### ISSUE THREAD

**Issue by sthanduther** [joncampbell123/dosbox-x#5334]
### Question

2 times tried and the GIT show me this error. Just reporting If solved, I delete this issue.

```
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 1728 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by sthanduther** [comment]
Still having probem.

```
git clone https://github.com/joncampbell123/dosbox-x.git
Cloning into 'dosbox-x'...
remote: Enumerating objects: 190609, done.
remote: Counting objects: 100% (1541/1541), done.
remote: Compressing objects: 100% (582/582), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 14217 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

**Comment by rderooy** [comment]
No issue here. I suspect the issue is on your side.

```bash
$ git clone https://github.com/joncampbell123/dosbox-x.git
Cloning into 'dosbox-x'...
remote: Enumerating objects: 190609, done.
remote: Counting objects: 100% (1494/1494), done.
remote: Compressing objects: 100% (584/584), done.
remote: Total 190609 (delta 1065), reused 916 (delta 910), pack-reused 189115 (from 5)
Receiving objects: 100% (190609/190609), 631.60 MiB | 28.11 MiB/s, done.
Resolving deltas: 100% (151786/151786), done.
```

**Comment by sthanduther** [comment]
Maybe...

> No issue here. I suspect the issue is on your side.
> 
> ```shell
> $ git clone https://github.com/joncampbell123/dosbox-x.git
> Cloning into 'dosbox-x'...
> remote: Enumerating objects: 190609, done.
> remote: Counting objects: 100% (1494/1494), done.
> remote: Compressing objects: 100% (584/584), done.
> remote: Total 190609 (delta 1065), reused 916 (delta 910), pack-reused 189115 (from 5)
> Receiving objects: 100% (190609/190609), 631.60 MiB | 28.11 MiB/s, done.
> Resolving deltas: 100% (151786/151786), done.
> ```

**Comment by sthanduther** [comment]
Ok. Solved after system reboot. Deleting this issue in 10min.
