### ISSUE TITLE
Windows 3.1 COMMDLG.DLL debug output on screen

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#534]
Bringing up the File Open dialog box in any application causes printing debug information to the screen.

I have not yet determined whether this is done through the DOS CON driver or INT 10h.

It's a minor nuisance using the standard 640x480 16-color VGA driver, but it's especially annoying with S3's SVGA driver because the debug spew causes Windows to crash.

![krnl386_000](https://user-images.githubusercontent.com/6245486/36634503-67627d2e-195a-11e8-8083-a4bf66767e39.png)

This doesn't appear when running Windows 3.11, only Windows 3.1.

I'm curious if Windows 3.1 expects to manipulate the DOS kernel somehow to prevent that from appearing at all.

**Comment by joncampbell123** [comment]
Contrary to my initial impression, it has nothing to do with whether a particular version of the Win32s files are installed or not.

**Comment by joncampbell123** [comment]
I forgot to mention the debug messages shown in the screenshot come from COMMDLG.DLL not from DOSBox-X.

**Comment by joncampbell123** [comment]
This happens in both 286 standard and 386 enhanced mode.

**Comment by Wengier** [comment]
I have checked that Windows 3.1 COMMDLG.DLL writes 43 bytes containing this debug string to DOS CON via int 21/ah=40h. It changes the DOS PSP address via Int 21/ah=50h right before this call, and restores the DOS PSP address immediately after. I can confirm that the COMMDLG.DLL debug output will not be shown if the int 21 call is blocked in some way in the code.

**Comment by joncampbell123** [comment]
File handle is 2 (STDERR), correct?

**Comment by Wengier** [comment]
Yes, that is right. The handle is 2 (STDERR) rather than 1 (STDOUT).

**Comment by Wengier** [comment]
So it appears that this is an error message from COMMDLG.DLL when Drive A & B are always reported by dos_ioctl.cpp (function al=8h) as "Removable" even if they are not mounted. One way to suppress the message is to change Line 128 of dos_ioctrl.cpp from:
```
if (drive < 2) reg_ax=0;
else if ...
```
To:

```
if (drive < 2) {
  if (Drives[drive]) reg_ax=0;
  else {
    DOS_SetError(DOSERR_INVALID_DRIVE);
    return false;
  }
}
else if ...
```
Then Windows 3.1 COMMDLG.DLL will no longer display that message on screen when the File Open dialog box shows up if Drive A & B are not mounted.

Tested on Windows 10, 64-bit.
