### ISSUE TITLE
Rambo III game install.bat crashes DOSBox-X

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#5340]
### Describe the bug

Trying to install the game from the original floppy images (https://archive.org/details/000452-Rambo3) the batch file install.bat causes the emulator to close after the request for the second floppy disk: however, the game is installed on the hard disk anyway.
If I boot an hd image with MS-DOS 6.22 the crash does not occur.

### Steps to reproduce the behaviour

1. Mount the 2 floppy images
2. At the A prompt: type "install a: c:"
3. When the message requesting the second disk appears, swap the floppies
4. Press a key and the emulator closes

### Expected behavior

The emulator does not crash and the batch file ends normally

### What operating system(s) this bug have occurred on?

Windows 10 Pro 22H2 64 bit

### What version(s) of DOSBox-X have this bug?

DOSBox-X 2024.12.04

### Used configuration

```ini
Standard
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
There is an `exit` command in the end of the installation .bat file, so this behavior is kind of intended.

- EXIT (internal command)
  Exits from the batch file or **_DOSBox-X._**

**Comment by MX9000** [comment]
@maron2000 thank you very much, I had missed the EXIT command.
Sorry,

**Comment by maron2000** [comment]
Some other people may encounter this so no problem.
