### ISSUE TITLE
Its rounded corners are misaligned.

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#5341]
### Describe the bug

Excuse me:
When Dosbox-X -default -set output=default,
Which glyph file it uses.
Its rounded corners are misaligned.

### Steps to reproduce the behaviour

C:\Dosbox-x\> Dosbox-X -default -set output=default
As shown below:
![default](https://github.com/user-attachments/assets/ac8f7b7b-1081-4c6c-b914-2b2646b45133)

### What operating system(s) this bug have occurred on?

Windows 11 23H2

### What version(s) of DOSBox-X have this bug?

version 2024-12-04

### Used configuration

```ini
-default -set output=default
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
Is this a possible issue with the multibyte encoding commonly used by Chinese and Japanese DOS?

**Comment by maron2000** [comment]
Japanese DOS (CP932 aka Shift-JIS) doesn't have rounded corner box-drawing character.
Tried CP950, but there is indeed some problem in rounded corners, but not in square corners.
[boxtest.txt](https://github.com/user-attachments/files/18244796/boxtest.txt)

![image](https://github.com/user-attachments/assets/d9839f96-6977-4102-9c73-34062ba4b621)

**Comment by Arthur3032** [comment]
> Japanese DOS (CP932 aka Shift-JIS) doesn't have rounded corner box-drawing character. Tried CP950, but there is indeed some problem in rounded corners, but not in square corners. [boxtest.txt](https://github.com/user-attachments/files/18244796/boxtest.txt)
> 
> ![image](https://private-user-images.githubusercontent.com/68574602/398546486-d9839f96-6977-4102-9c73-34062ba4b621.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTc0MzksIm5iZiI6MTczNTExNzEzOSwicGF0aCI6Ii82ODU3NDYwMi8zOTg1NDY0ODYtZDk4MzlmOTYtNjk3Ny00MTAyLTljNzMtMzQwNjJiYTRiNjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA4NTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMmQ5ZmFmOWI2OTY1ZDg0OGJiNzVhYTc1ZGUyMWZlMjUzZjgwMWQwOTBkMmJmYjEzNTliOWFhZThjZDdmZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tMd3Uiz4Eu1z6w5Xfm2_aiUxtbs3HIQviB5yDCcy_BY)

Yes, but rounded corners look better.
If we know which font file we are using, we can use font editor modify it.

I used the font editor to modify the wireframe font, and the dialog box will look better.
![s46](https://github.com/user-attachments/assets/0cc0ae8e-6c5c-4a34-bce5-4f8b39d6dc4b)

**Comment by maron2000** [comment]
You mentioned `output=default` in the first place, but you all of a sudden change to `output=ttf`?
Don't silently change the prerequisite, that makes everyone confused.

Anyway, the default font (sarasagothicfixed.ttf) shows the corners fine, so the problem may be in the font you are using.

`output=default` (the one I showed above)
![image](https://github.com/user-attachments/assets/b077fea9-e0ba-47de-84b1-ad1a5776e3aa)

`output=ttf` with sarasagothicfixed.ttf
![image](https://github.com/user-attachments/assets/0966e978-233c-4ae2-8b63-782b695ffffb)

**Comment by Arthur3032** [comment]
> You mentioned `output=default` in the first place, but you all of a sudden change to `output=ttf`? Don't silently change the prerequisite, that makes everyone confused.
> 
> Anyway, the default font (sarasagothicfixed.ttf) shows the corners fine, so the problem may be in the font you are using.
> 
> `output=default` (the one I showed above) ![image](https://private-user-images.githubusercontent.com/68574602/398551694-b077fea9-e0ba-47de-84b1-ad1a5776e3aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTk5MjMsIm5iZiI6MTczNTExOTYyMywicGF0aCI6Ii82ODU3NDYwMi8zOTg1NTE2OTQtYjA3N2ZlYTktZTBiYS00N2RlLTg0YjEtYWQxYTU3NzZlM2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA5NDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDNiMWMwZDQ3MTg5ODk4MGExMGFjMzk0NGFjZmUzNDc5ZDBlODU4NjQ1NTMwZTJjM2I2MzQxMzk4MTUwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-Eo9llg0xvBSFQ1dCfcFbiIg9OwXCAVIT_XGGX0SiRY)
> 
> `output=ttf` with sarasagothicfixed.ttf ![image](https://private-user-images.githubusercontent.com/68574602/398554878-0966e978-233c-4ae2-8b63-782b695ffffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTk5MjMsIm5iZiI6MTczNTExOTYyMywicGF0aCI6Ii82ODU3NDYwMi8zOTg1NTQ4NzgtMDk2NmU5NzgtMjMzYy00YWUyLThiNjMtNzgyYjY5NWZmZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA5NDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDhmNzg1N2MyYTBjYWQyYTMyNDc0MjY5NjY1MTNhNDFhNzg1MjdmNTRiYmRjNjM1MWM5ZmU3MzYxNzIyYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OZ9285axR6o0GoCbvUStbIjN_g5l3zFjmpkUL1vX4_M)

sorry!

**Comment by maron2000** [comment]
Depending on the font size, there seems a slight glitch.
![image](https://github.com/user-attachments/assets/15eb7f4e-dd3b-44f2-b16c-d936d0a9e2f1)

**Comment by Arthur3032** [comment]
Which font file is used?

**Comment by maron2000** [comment]
I already mentioned above it's the default ttf font (sarasagothicfixed.ttf).

[Noto Sans CJK](https://github.com/notofonts/noto-cjk/releases/tag/Sans2.004) seems to work more stably, if you don't mind the margin between the lines.
![image](https://github.com/user-attachments/assets/1a661819-e26f-45c1-9182-98d52b23e751)

**Comment by Arthur3032** [comment]
fine thanks!
