### ISSUE TITLE
EGA Enhanced colors in game Rambo III (Boca / Paradise EGA cards)

### ISSUE THREAD

**Issue by MX9000** [joncampbell123/dosbox-x#5345]
### Question

This game offers the option for enhanced EGA modes with improved colors: 

![rambo_menu](https://github.com/user-attachments/assets/5d7d6aed-66a1-45f0-a719-3191fb8e5b53)

If I select the enhanced modes in the configuration menu, the colors change slightly but are different from those shown on Moby Games: https://www.mobygames.com/game/5023/rambo-iii/screenshots/dos/541319/

- Enhanced EGA mode on Moby Games
![16244281-rambo-iii-dos-start-mission-1-watch-out-for-guards-ega-enhanced-](https://github.com/user-attachments/assets/3a680937-7046-4d1a-b914-0a19093bf913)
- Enhanced EGA mode in DOSBox-X
![rambo_enhanced_EGA](https://github.com/user-attachments/assets/22d7a78e-a9ca-455a-bc98-f7f7dd5c4f23)
- Standard EGA mode in DOSBox-X
![rambo_EGA](https://github.com/user-attachments/assets/7e456c6c-8e93-4336-9a51-0414fd718643)

Apparently the Moby Games screenshots were created with PCE/ibmpc emulator: https://www.reenigne.org/blog/why-the-ega-can-only-use-16-of-its-64-colours-in-200-line-modes/
Is it possible to configure DOSBox-X to emulate these modes, or the features of these Boca and Paradise EGA boards are undocumented / unimplementable?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment]
This might be a test case for a report on another issue that says that EGA monitors use the polarity of a sync signal, not number of scan lines, to determine whether to handle the signals as CGA-like RGBI or EGA-like RRGGBB.

**Comment by joncampbell123** [comment]
Possible useful reference: https://forum.vcfed.org/index.php?threads/ega-and-64-colors-mode.67207/

**Comment by joncampbell123** [comment]
Also: http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/EGA/EGA%20Registers%20%28WHATVGA%20v2%2e00%29%20%281995%2d09%2d29%29%2etxt
![image](https://github.com/user-attachments/assets/4650b523-805d-4944-9336-4bf4baaf4140)

**Comment by joncampbell123** [comment]
https://www.reenigne.org/blog/why-the-ega-can-only-use-16-of-its-64-colours-in-200-line-modes/
![image](https://github.com/user-attachments/assets/60222d43-9e23-42b2-83be-f59473737508)

**Comment by joncampbell123** [comment]
Done. Latest commit. When the daily build finishes, it should show correct colors with machine=ega.

**Comment by joncampbell123** [comment]
![rambo_000](https://github.com/user-attachments/assets/cbd187b8-e77e-43e7-823f-da9606d90a49)
![rambo_001](https://github.com/user-attachments/assets/8f983a3c-60f3-49db-80c1-c52547baf841)
![rambo_002](https://github.com/user-attachments/assets/dba068bd-30cd-43a0-b36b-a515415e29c5)

**Comment by joncampbell123** [comment]
https://web.archive.org/web/20170324084325if_/http://minuszerodegrees.net/oa/OA%20-%20IBM%20Enhanced%20Color%20Display%20(5154).pdf
![image](https://github.com/user-attachments/assets/122376eb-40f5-4760-a8c8-c4ffb7b1dbb7)
![image](https://github.com/user-attachments/assets/7b368417-6c33-46b0-b18e-10bcbd9cf6ec)

**Comment by MX9000** [comment]
@joncampbell123 thank you very much!
