### ISSUE TITLE
Remove DirectX driver and OpenGL HQ options

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#535]
https://www.vogons.org/viewtopic.php?f=41&t=31881&p=653102#p653102

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Is OpenGL HQ not longer supported?

**Comment by joncampbell123** [comment]
I'm told that it doesn't work reliably.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Sorry,
I read this first time!
Can You also remove the menu entry and the conf Option.
Thank You.

**Comment by joncampbell123** [comment]
DONE
