### ISSUE TITLE
Raspberry PI 400 64bit build latest version fails

### ISSUE THREAD

**Issue by CleversonSA** [joncampbell123/dosbox-x#5355]
### Describe the bug

I´m trying compile the latest version of code on my Raspberry PI 400 with latest Raspbian 64bit OS (_6.6.51+rpt-rpi-v8_) and GCC 12(_gcc (Debian 12.2.0-14) 12.2.0_)

I´ve followed the pre-requisites steps to build, but I´m stuck into this error:

 `dosbox.cpp:1355:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
 1355 | void DOSBOX_SetupConfigSections(void) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
g++  -g -std=gnu++14  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wno-error=format-security   -Wno-error=incompatible-pointer-types   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wsuggest-override   -Wnon-virtual-dtor   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/pi/dosbox-x-master -I/home/pi/dosbox-x-master/vs/sdlnet/linux-host/include -I/home/pi/dosbox-x-master/vs/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L   -L/home/pi/dosbox-x-master/vs/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/passthroughio/libpassthroughio.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a misc/libmisc.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a libs/decoders/internal/libopusint.a aviwriter/libaviwriter.a   libs/xBRZ/libxbrz.a libs/mt32/libmt32.a libs/fluidsynth/libfluidsynth.a -lasound -lm -ldl -lpthread -L/home/pi/dosbox-x-master/vs/sdl/linux-host/lib -Wl,-rpath,/home/pi/dosbox-x-master/vs/sdl/linux-host/lib -lSDL -lX11 -lXext -lpthread -lGL -lrt -ltinfo -lfreetype  -latomic -lncurses -lSDL_net -lz -lpng -lz -lpcap -lslirp -lglib-2.0  -lX11 -lXrandr -lxkbfile -lfluidsynth
/usr/bin/ld: cpu/libcpu.a(cpu.o): in function `CPU_DynamicCoreCannotUseCPPExceptions()':
/home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dynrec_Run()'
/usr/bin/ld: /home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dynrec_Run()'
/usr/bin/ld: /home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dyn_X86_Run()'
/usr/bin/ld: /home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dyn_X86_Run()'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:480: dosbox-x] Error 1
make[3]: Leaving directory '/home/pi/dosbox-x-master/src'
make[2]: *** [Makefile:540: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/dosbox-x-master/src'
make[1]: *** [Makefile:402: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/dosbox-x-master'
make: *** [Makefile:335: all] Error 2
`
I tried these approachs, but I got the same error:

- Run _build_ only
- Run _build-debug_ only
- Build with _--disable-dynamic-core_ and _--disable-avcodec_
- Modify the cpu.cpp file to force disable dinamyc core, created another error.

Any ideas?

Regards

### Steps to reproduce the behaviour

1. Get the latest master branch code
2. Run 'build-debug' with normal (non sudo) account

### What operating system(s) this bug have occurred on?

 Raspbian 64bit OS (_6.6.51+rpt-rpi-v8_)

### What version(s) of DOSBox-X have this bug?

Latest master branch - GCC 12 compiler

### Used configuration

```ini
Tried modify the build-debug script with this line:

./configure --enable-debug=heavy --disable-dynamic-core --disable-avcodec --prefix=/usr "${@}" "${opt}" || exit 1
```

### Output log

```text
dosbox.cpp:1355:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
 1355 | void DOSBOX_SetupConfigSections(void) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
g++  -g -std=gnu++14  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wno-error=format-security   -Wno-error=incompatible-pointer-types   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wsuggest-override   -Wnon-virtual-dtor   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/pi/dosbox-x-master -I/home/pi/dosbox-x-master/vs/sdlnet/linux-host/include -I/home/pi/dosbox-x-master/vs/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L   -L/home/pi/dosbox-x-master/vs/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/passthroughio/libpassthroughio.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a misc/libmisc.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a libs/decoders/internal/libopusint.a aviwriter/libaviwriter.a   libs/xBRZ/libxbrz.a libs/mt32/libmt32.a libs/fluidsynth/libfluidsynth.a -lasound -lm -ldl -lpthread -L/home/pi/dosbox-x-master/vs/sdl/linux-host/lib -Wl,-rpath,/home/pi/dosbox-x-master/vs/sdl/linux-host/lib -lSDL -lX11 -lXext -lpthread -lGL -lrt -ltinfo -lfreetype  -latomic -lncurses -lSDL_net -lz -lpng -lz -lpcap -lslirp -lglib-2.0  -lX11 -lXrandr -lxkbfile -lfluidsynth
/usr/bin/ld: cpu/libcpu.a(cpu.o): in function `CPU_DynamicCoreCannotUseCPPExceptions()':
/home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dynrec_Run()'
/usr/bin/ld: /home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dynrec_Run()'
/usr/bin/ld: /home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dyn_X86_Run()'
/usr/bin/ld: /home/pi/dosbox-x-master/src/cpu/cpu.cpp:3216: undefined reference to `CPU_Core_Dyn_X86_Run()'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:480: dosbox-x] Error 1
make[3]: Leaving directory '/home/pi/dosbox-x-master/src'
make[2]: *** [Makefile:540: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/dosbox-x-master/src'
make[1]: *** [Makefile:402: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/dosbox-x-master'
make: *** [Makefile:335: all] Error 2
```

### Additional information

I already installed 'dosbox' repo, that works fine for my games.

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
At this time, all ARM core related builds seems to fail, since there are some additional features at work.
Check the commits and pick one that has a green check mark which means Windows, mac, Linux builds are all successful, including Windows and mac ARM builds.
https://github.com/joncampbell123/dosbox-x/commits/master/

**Comment by joncampbell123** [comment]
dynamic_rec should be supported on ARM based systems including the Pi, did you make sure to tell ./configure to enable it?

I get that the code should not assume dynamic core, that should be fixed, definitely.

**Comment by CleversonSA** [comment]
> dynamic_rec should be supported on ARM based systems including the Pi, did you make sure to tell ./configure to enable it?
> 
> I get that the code should not assume dynamic core, that should be fixed, definitely.

Is it enabled in configure by default? I checked the doc page, but not found any parameter like _--enable-dynamic-x86_  or have I manually change the config.h file?

**Comment by herrnst** [comment]
JFYI, this is on macOS arm64 (ie. Apple Silicon) with "brew reinstall dosbox-x" initially installed with --HEAD as of current GIT HEAD from a few minutes ago:

```
==> Cloning https://github.com/joncampbell123/dosbox-x.git
Updating /Users/redacted/Library/Caches/Homebrew/dosbox-x--git
From https://github.com/joncampbell123/dosbox-x
   24e0d7063..d93d37c95  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at d93d37c95 Merge pull request #5356 from maron2000/fix_chcp
==> Reinstalling dosbox-x 
==> ./autogen.sh
==> ./configure --enable-debug=heavy --enable-sdl2 --disable-sdl2test --disable-sdl --disable-sdltest
==> make
Last 15 lines from /Users/redacted/Library/Logs/Homebrew/dosbox-x/03.make:
ranlib libgamelink.a
clang++ -DHAVE_CONFIG_H -I. -I..  -I../include "-DRESDIR=\"/opt/homebrew/Cellar/dosbox-x/HEAD-d93d37c/share/dosbox-x\"" -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wno-deprecated-declarations   -Wnon-virtual-dtor   -Wsuggest-override   -Wconversion-null   -Wsign-promo   -Wno-error=incompatible-pointer-types   -Wno-error=format-security   -pedantic   -Wunused   -Wextra   -Wall   -I/usr/local/include -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -D_THREAD_SAFE -I/private/tmp/dosbox-x-20241230-11395-19214r -I/private/tmp/dosbox-x-20241230-11395-19214r/vs/sdlnet/linux-host/include -I/private/tmp/dosbox-x-20241230-11395-19214r/vs/sdlnet/linux-host/include/SDL -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libpng/include/libpng16 -DLIBSLIRP_STATIC -I/opt/homebrew/Cellar/libslirp/4.8.0/include/slirp -I/opt/homebrew/Cellar/glib/2.82.4/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.82.4/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.44/include  -g -std=gnu++14  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wno-error=format-security   -Wno-error=incompatible-pointer-types   -Wsign-promo   -Wconversion-null   -Wsuggest-override   -Wnon-virtual-dtor   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/private/tmp/dosbox-x-20241230-11395-19214r -I/private/tmp/dosbox-x-20241230-11395-19214r/vs/sdlnet/linux-host/include -I/private/tmp/dosbox-x-20241230-11395-19214r/vs/sdlnet/linux-host/include/SDL  -c -o dosbox.o dosbox.cpp
clang++  -g -std=gnu++14  -O2  -Wall   -Wextra   -Wunused   -pedantic   -Wno-error=format-security   -Wno-error=incompatible-pointer-types   -Wsign-promo   -Wconversion-null   -Wsuggest-override   -Wnon-virtual-dtor   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/private/tmp/dosbox-x-20241230-11395-19214r -I/private/tmp/dosbox-x-20241230-11395-19214r/vs/sdlnet/linux-host/include -I/private/tmp/dosbox-x-20241230-11395-19214r/vs/sdlnet/linux-host/include/SDL   -L/private/tmp/dosbox-x-20241230-11395-19214r/vs/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/passthroughio/libpassthroughio.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a misc/libmisc.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a libs/decoders/internal/libopusint.a aviwriter/libaviwriter.a gamelink/libgamelink.a  libs/xBRZ/libxbrz.a libs/mt32/libmt32.a libs/fluidsynth/libfluidsynth.a -L/opt/homebrew/lib -lSDL2 -framework OpenGL -framework Carbon -framework CoreFoundation -framework CoreMIDI -framework AudioUnit -framework AudioToolbox -framework ApplicationServices -framework AppKit -framework IOKit -L/opt/homebrew/opt/freetype/lib -lfreetype -lz -lpng -lz -lpcap -L/opt/homebrew/Cellar/libslirp/4.8.0/lib -lslirp -L/opt/homebrew/Cellar/glib/2.82.4/lib -lglib-2.0 -L/opt/homebrew/opt/gettext/lib -lintl -lfluidsynth -liconv
Undefined symbols for architecture arm64:
  "CPU_Core_Dyn_X86_Run()", referenced from:
      CPU_DynamicCoreCannotUseCPPExceptions() in libcpu.a[3](cpu.o)
  "DEBUG_EnableDebugger()", referenced from:
      CPU_SYSENTER() in libcpu.a[3](cpu.o)
      CPU_SYSEXIT() in libcpu.a[3](cpu.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [dosbox-x] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

So besides the CPU_Core_Dyn_X86_Run() issue, something goes wrong with DEBUG_EnableDebugger() aswell.

**Comment by joncampbell123** [comment]
Brew does not enable the debugger?

The problem code is the code that allows you to set a breakpoint on the SYSENTER/SYSEXIT instruction.

**Comment by joncampbell123** [comment]
Got it. Try the latest commit fb11ee58d287c8a0eb3f8c6ad177f872c5f17ff7.

**Comment by CleversonSA** [comment]
Sounds promissing the latest commit. I´ll try build complete again (It takes +- 30min long to build on my RPi). :)

**Comment by CleversonSA** [comment]
> Got it. Try the latest commit [fb11ee5](https://github.com/joncampbell123/dosbox-x/commit/fb11ee58d287c8a0eb3f8c6ad177f872c5f17ff7).

Worked! Compiled and running. Thanks.

**Comment by herrnst** [comment]
> Got it. Try the latest commit [fb11ee5](https://github.com/joncampbell123/dosbox-x/commit/fb11ee58d287c8a0eb3f8c6ad177f872c5f17ff7).

Built on macOS arm64 via brew aswell, and also runs:

```
HEAD is now at fb11ee58d Revise dynamic core CPP exception test not to refer to cores that are not compiled in. Such as, the X86 dynamic core on an arm64 Macbook
==> Reinstalling dosbox-x 
==> ./autogen.sh
==> ./configure --enable-debug=heavy --enable-sdl2 --disable-sdl2test --disable-sdl --disable-sdltest
==> make
==> make install
🍺  /opt/homebrew/Cellar/dosbox-x/HEAD-fb11ee5: 77 files, 41.8MB, built in 1 minute 16 seconds
==> Running `brew cleanup dosbox-x`...
```

Thanks!
