### ISSUE TITLE
Request: DynRec Core or Dynamic Core with old Paging...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#537]
Hello,
Your DosBox-X  Project is verry great but the Normal core is too slow for newer DOS games (on my Xeon X5670 - 2.93Ghz machine).
OK, i know that the dynamic core is not compatible with Your modified paging System.
Is it possible to add the dynrec core instead or let's the user to chose a paging System with dynamic core (the new modified paging for Win95 [and win3.x???] and the old one for pure DOS things mostly games wich works mostly good with dynamic core with paging.

thank You verry much.

**Comment by joncampbell123** [comment]
I brought back the dynamic core code for 32-bit. It turns out it's perfectly fine so long as paging is disabled. While this prevents performance gains for Windows 95 and later, it does allow performance gains for DOS programs since most common DOS extenders will leave paging disabled.

**Comment by joncampbell123** [comment]
I (or anyone else) would need to port dynrec from DOSBox to make it work.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
I have also detected a problem when using the dynamic core when paging is not used.
In the DosBox-x.conf i set the priority to normal,pause (mean running in normal priority if DosBox have focus, pauses if have not the focus).
When i switch out of DosBox and then back in, the dynamic core don't work anymore "dynamic".
In the titlebar the cyclescounder is static now and everything is working much slower before DosBox lost it focus.

**Comment by fr500** [comment]
Lets hope someone ports the x86 dynarec (and hopefully x86_64 in the future)

**Comment by joncampbell123** [comment]
Dynrec was ported to DOSBox-X. This includes x86_64 and arm targets
