### ISSUE TITLE
IMGMOUNT with -t ram (ram drive) and no size causes infinite loop

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#545]
shane32 recently committed a nice feature that allows creation and mounting of a RAM drive.

However, not specifying a size causes the code to enter an infinite loop from the FAT driver trying to read a too-small image.

Any nonzero size prevents this infinite loop.

**Comment by joncampbell123** [comment]
I suggest enforcing a minimum size at mount time if not specified.

I'll take a look at what causes the FAT driver to get stuck like this, so that when bugs of this sort come up, the FAT driver can mercifully error out and let the emulator continue running.

**Comment by joncampbell123** [comment]
Ref: https://github.com/joncampbell123/dosbox-x/pull/541

**Comment by Shane32** [comment]
When I debugged it, it was looping within in the formatting code, as it had taken the total number of sectors (0) and subtracted 1.  Perhaps a similar math error is occurring wherever you saw it looping.

I could also add a default size if it's not specified, but then what should it be?  20mb perhaps?  200mb?  It shouldn't really matter too much.

**Comment by joncampbell123** [comment]
I have two suggestions.

You could set a low default of 8-16MB, since the creation of the drive allocates additional memory.

You could also modify the code to return with an error if no size is given.

**Comment by joncampbell123** [comment]
Let me know when the loop is fixed, and I'll close this issue.

**Comment by Shane32** [comment]
It was fixed in pull https://github.com/joncampbell123/dosbox-x/pull/547 .  As of now, an error is given if no size is specified.
