### ISSUE TITLE
error compiling on vs2017

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#546]
Hello,
I'm unable to compile the current master.
VS2017 gives out the following error msg:
vs2015\libpdcurses\curses.h(155): warning C4005: 'MOUSE_MOVED': macro redefinition (compiling source file ..\src\misc\support.cpp)
C:\Program Files (x86)\Windows Kits\8.1\Include\um\wincon.h(118): note: see previous definition of 'MOUSE_MOVED' (compiling source file ..\src\misc\support.cpp)
..\src\shell\shell_misc.cpp(725): warning C4102: 'failed': unreferenced label

**Comment by joncampbell123** [comment]
I just fixed that. Pull the latest commit.

**Comment by joncampbell123** [comment]
Some files moved around, and some needed to be added to the VS2017 project file.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Commit 3465 fixed the error.

Thank You verry much.
