### ISSUE TITLE
Request: Show / Hide menu bar also enabling / disabling menu hotkey...

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [joncampbell123/dosbox-x#548]
Hello,
Is it possible to implement a .conf switch also to enable / disable the menu hotkey toggle (ctrl-alt-enter) like showmenu=true forced or showmenu=false forced?

Thank You.

**Comment by joncampbell123** [comment]
That can be controlled through the mapper interface. Bring up the mapper (shift+F1) and look for the ToggleMenu shortcut. Click on the button, and then down below where it shows the key combination, click the "delete" button. Click "save".

**Comment by joncampbell123** [comment]
![mappertogglemenu](https://user-images.githubusercontent.com/6245486/36708006-c6f2b5ca-1b25-11e8-90f1-1a66ad36ec62.png)
