### ISSUE TITLE
About "nullmodem server" option

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#549]
Dear Jon,
Can you describe what does the nullmodem server option do?
BTW: DO NOT LABEL THIS AS SPAM OR ELSE I WILL NUKE YOU LIKE NORTH KOREA!!!

**Comment by empsmoke** [comment]
OK, I understood it from VOGONS.

**Comment by joncampbell123** [comment]
How did you steal nukes from North Korea? Kim Jung Un would be very interested to know!

**Comment by joncampbell123** [comment]
nullmodem server instructs serial emulation to listen to a port on localhost for a telnet connection. It can be used to connect serial emulation to another program over a network socket.
