### ISSUE TITLE
Windows 95 Cannot connect to Internet even with drivers installed [because realnic=list]

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#550]
Dear Jon,
can you tell me how to fix this issue with Windows 95 not connecting to Internet?
I would be interested.
![ne2kerror](https://user-images.githubusercontent.com/14072545/36683517-720524c0-1b26-11e8-9ba4-04b8dd7ccbd7.PNG)

**Comment by empsmoke** [comment]
But that is not the issue, it's actually enabled via the config.

**Comment by joncampbell123** [comment]
There is log output to explain what is going on. It should say whether or not it's able to set up the network card as required. On Windows, you will need the winpcap driver for it to work.

**Comment by empsmoke** [comment]
I have it installed.

**Comment by joncampbell123** [comment]
Add this to the top of your dosbox.conf

    [log]
    logfile=log.txt

And then run dosbox-x with the --debug flag.

All log output should go to log.txt

**Comment by empsmoke** [comment]
But I will send it after I will boot DOSBox-X.

**Comment by empsmoke** [comment]
It's a Windows 95 OSR 2.5 machine.

**Comment by empsmoke** [comment]
I would also hope for USB 0.8 to USB 1.1 support aswell.

**Comment by empsmoke** [comment]
OK, I think I chose the 2nd one.
