### ISSUE TITLE
Slow emulation with Debug x64 mode

### ISSUE THREAD

**Issue by Shane32** [joncampbell123/dosbox-x#560]
When running in Debug x64 build, it seems that the emulation is slower and/or works different that Debug x86 or Release x86/x64 builds.  You can tell at the command prompt that simply typing characters have lag.  For a better demo, running SimCity 2000 is quite slow (but works fine in the other 3 builds).  Dosbox auto sets the cycles to 100 when starting the game, but while manually increasing the cycles, the mouse moves slower.  Setting the cycles to 30000 slows the mouse movement in SimCity to about 3fps, and the game doesn't seem to necessarily run any faster.

Is this normal?  I had not expected Debug x64 to run much different than Debug x86.  Note that CPU usage seems to be about the same level in either build.

My CPU is i7-7567U for reference.  Compiled with VS2017 on Windows 10.

**Comment by joncampbell123** [comment]
That's known, yes. Not sure why that is, except that debug mode might disable a lot of inline code generation that makes it fast.

**Comment by Shane32** [comment]
You can close the issue if you want, by the way.  Wasn't sure if this was a bug or not.
