### ISSUE TITLE
Check where dosbox-x is already running

### ISSUE THREAD

**Issue by frank-deng** [joncampbell123/dosbox-x#561]
Is it nessessary to check whether dosbox-x is already running, so as to evade potential corruptions on disk images, floppy images, files in mounted directories?

**Comment by joncampbell123** [comment]
No. No other emulator does either.

**Comment by joncampbell123** [comment]
Writing code to determine if a particular file is open by any process is difficult and platform specific. I know how to do it on Linux, but doing it on Mac OS X and Windows is unknown to me.
