### ISSUE TITLE
FM sound (Adlib, Sound Blaster or PC-98 ones) is stuck playing after using "reset system

### ISSUE THREAD

**Issue by leonier** [joncampbell123/dosbox-x#562]
If I choose "reset system" from menu while playing sound from OPL2/OPL3/OPNA, DosBox-X will stuck playing the last note until an application initialize the sound chip again. 
I think the process of a system reset should involve a reset on the FM sound generators.

**Comment by joncampbell123** [comment]
That's true. I threw in the menu command on a whim, now it's time to implement a proper reset of the components.

**Comment by joncampbell123** [comment]
DONE
