### ISSUE TITLE
Patch file name format and file extension

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#564]
Dear Jon,
How do I edit the patch file name format and file extension?
P.S.: I could also make an emulation of the infamous FDIV bug and also the F00F bug aswell.

**Comment by joncampbell123** [comment]
What patch are you talking about?

Assuming you got the code to compile, here's everything you need to know to implement those CPU bugs. Have fun. Let me know when you have a pull request.

https://en.wikipedia.org/wiki/Pentium_FDIV_bug

https://en.wikipedia.org/wiki/Pentium_F00F_bug

**Comment by joncampbell123** [comment]
https://github.com/joncampbell123/dosbox-x/issues/566
