### ISSUE TITLE
Patch file name format and file extension (@empsmoke)

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#566]
#564 
Jon,
I was supposedly talking about all the patches with the file format .diff and .patch, OK.

**Comment by empsmoke** [comment]
And I could pack shaders into .p86 files... which says in my ToDo list.

**Comment by wonderbead** [comment]
Look up patch and diff online. Google will tell you everything you need to know.

**Comment by empsmoke** [comment]
OK, I am waiting a response from Jon, not you, OK!

**Comment by joncampbell123** [comment]
I know what "diff" and "patch" are. I use them all the time on Linux.

There are two different formats for "diff", the universal -u format and the original patch format.

Please take this issue tracker seriously, which you have yet to do so far.

**Comment by joncampbell123** [comment]
![empsmoke566](https://user-images.githubusercontent.com/6245486/36806311-81f60012-1c74-11e8-89cf-1d4dd46ac77a.png)

**Comment by empsmoke** [comment]
I could rename the "diff" and "patch" formats to the new "p86patch" format, which will make those old formats I mentioned obsolete.

**Comment by joncampbell123** [comment]
There's a new source code patch format? Where can I find the tools to use it? I've never heard of "p86patch" before.

What does "p86patch" do better than diff/patch?

**Comment by empsmoke** [comment]
It's going to do more better than diff/patch, but how do I rename it from source code?

**Comment by empsmoke** [comment]
Is there an SLN file for the project?

**Comment by joncampbell123** [comment]
You don't rename from source code, you make patches from two copies of the source code to record the changes from one to another.

**Comment by joncampbell123** [comment]
There are SLN and VCXPROJ files under the vs2015 directory. I keep those up to date with VS2017 community edition.

**Comment by empsmoke** [comment]
OK.

**Comment by empsmoke** [comment]
And I will also pack the shaders into ".p86" files just like how Valve did to Half-Life 2 as it was with the VPK system.

**Comment by empsmoke** [comment]
But where's the diff/patch thing in the source code.

**Comment by joncampbell123** [comment]
"diff" and "patch" are external tools not included in the DOSBox-X source tree.

In Linux they are often provided by the distribution, or you can compile from source.

They're not there in Windows, but if you're using VS2015 or VS2017 the built-in GIT support can help in making commits and pushing to Github.

Make your changes in your git repo. You can submit pull requests to DOSBox-X when you want changes to be merged in.

**Comment by empsmoke** [comment]
And I would change the CONF file format to the new P86CONFIG file format, as I will also make a Project86 Configuration program that will configure that if a user doesn't understand the one seen in the emulator itself.

**Comment by joncampbell123** [comment]
I'm not familiar with the P86CONFIG file format. Is that anything like JSON?

**Comment by empsmoke** [comment]
No, it's just like CONF but more common for me.

**Comment by joncampbell123** [comment]
So it's INI-like the way dosbox.conf is already but with sections and settings renamed to your taste?

If that's what you're going to do may I suggest changing the default conf filename to project86.conf then so other people's dosbox.conf files don't confuse your fork?

However it might be wiser to just stick with dosbox.conf if you would rather support Project86 being able to take incremental improvements from DOSBox-X.

**Comment by empsmoke** [comment]
But where do I find the strings dosbox.conf in which Visual C++ file?

**Comment by joncampbell123** [comment]
Did you check sdlmain.cpp?

Don't forget VS2017 has a "find" function as well.

**Comment by empsmoke** [comment]
But the logo in itself?

**Comment by joncampbell123** [comment]
It's in a header file. Look for unsigned char array dosbox_vga16_bmp.

**Comment by empsmoke** [comment]
But where?

**Comment by empsmoke** [comment]
But to edit the header file?

**Comment by empsmoke** [comment]
and that banner when DOSBox started up?

**Comment by joncampbell123** [comment]
The unsigned char array defines a BMP file in memory. It was made using a tool like "xxd" to convert binary to a C unsigned char array. So all you need to do is make your own logo as a 16-color BMP file (dithered to VGA colors), and then use a tool to convert the BMP to an unsigned char array and put it in the header file.

**Comment by empsmoke** [comment]
How do I dither it?

**Comment by joncampbell123** [comment]
The BIOS screen text is printed to screen in src/ints/bios.cpp in function cb_bios_startup_screen__func().

**Comment by joncampbell123** [comment]
How dithering is done is not up to me, it's up to whatever image/photo editor you use when you ask it to convert/dither to a VGA 16-color palette. You might use the GIMP program to do that. https://www.gimp.org/

**Comment by empsmoke** [comment]
I cannot find cb_bios_startup_screen__func().

**Comment by joncampbell123** [comment]
It's defined as cb_bios_startup_screen__func(void)

**Comment by empsmoke** [comment]
But how to change the icon?

**Comment by joncampbell123** [comment]
You mean the one Windows shows for the application, and in the window titlebar? That would be ./src/dosbox.ico

**Comment by empsmoke** [comment]
But how do I find the diff and patch detecting thing in DOSBox-X?

**Comment by joncampbell123** [comment]
What?

**Comment by empsmoke** [comment]
The DIFF and PATCH scripting.

**Comment by joncampbell123** [comment]
I don't understand what you're talking about.

**Comment by empsmoke** [comment]
I said, I cannot find the DIFF and PATCH strings in DOSBox-X.

**Comment by joncampbell123** [comment]
What?

DIFF and PATCH are not internal commands to DOSBox-X.

If they exist at all they are commands on your host OS provided by an installed application on Windows or your Linux distro.

**Comment by empsmoke** [comment]
OK, Thanks.
