### ISSUE TITLE
VirtualBox-style "host" key

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#569]
I think there's too many things attached to the function keys and modifiers that it's time to start thinking about cleaning that up.

One way I think would help is if one key on the keyboard were designated as the "host" key, much like VirtualBox does, and then all shortcuts are defined as host key + modifier + key.

This would be done in a way that the user can define the host key, and it would allow the user to define any other key combination (with or without host key) with the mapper if they would rather associate CTRL+ALT+F5 with screenshots still or use the mappings already defined in their mapper file.

The proposed change is to add a 4th modifier key to define the "host key", and then change the default mappings to use that host key and some other key combination.

Eventually some key combinations could be removed when the menu bar in Windows is made more generic, and becomes available to the user on any platform supported by DOSBox-X, to avoid eventually defining all 101 or so keys of the keyboard with shortcuts.

One mapper shortcut will be defined to call up the menu bar itself in order to navigate the menu bar with keyboard or mouse/touchscreen.

VirtualBox usually uses one of the two CTRL keys. Any suggestions?

**Comment by joncampbell123** [comment]
NOTE: Please do not suggest using the "Windows logo" key as the host key, that will only cause endless problems with Windows!

**Comment by joncampbell123** [comment]
Or... we could forgo the 4th modifier key and just re-define the shortcuts to use a CTRL+SHIFT or CTRL+ALT combination unlikely to be used in a DOS game or in Windows? Suggestions?

**Comment by joncampbell123** [comment]
The only other issue with a 4th modifier key is that some keyboards can only register 3-4 keys held down at once.

**Comment by sikthehedgehog** [comment]
Shift keys are usually exempt from that limitation (they are often wired in
a different way to prevent precisely that issue).

Ctrl+Alt+Shift+<key> seems the most unlikely to clash, but pressing four
keys (even if three of them are together) seems uncomfortable.

Laptops that like to remove just about every key that isn't a letter isn't
helping the case. If you could assume a full keyboard you'd get a lot of
unlikely combinations there to try like Ctrl+Menu or so (reminds me, it'd
be nice if Alt+<non-numpad-number> could be used to enter ASCII codes, at
least when using the built-in BIOS).

**Comment by sikthehedgehog** [comment]
Er modifier keys, not shift keys.

**Comment by emendelson** [comment]
What about: tap Right-Ctrl (or Left-Ctrl or anything else that the user prefers) and **THEN** accept the next keystroke combination as a special key sent to DOSBox-X?

I use an accented/specIal keystroke utility that works this way: it uses Right-Ctrl as trigger: type Right Ctrl, then e, then apostrophe in order to type é. DOSBox-X could use Right-Ctrl then any key combination with worrying whether it conflicts with the DOS or Windows keyboard.

**Comment by joncampbell123** [comment]
@emendelson That's an interesting idea... the mapper could be written to define a mapper trigger that then enables further keyboard shortcuts for the next keystroke. Only, Right-CTRL might be a problem as there are plenty of old DOS games that use ctrl, shift, and even alt as game input.

Perhaps what could be defined in the mapper is a host key trigger. When triggered, it's treated as a 4th modifier that's "held down" until you enter the next keystroke. Then shortcuts could be defined against it in the mapper interface.

**Comment by emendelson** [comment]
That's even better. If I understand you correctly, the software would virtually "hold down" the key until the next keystroke. The user would not need to hold it down physically.

I'm mentioning this because of the possibility that you might somehow run into this issue : as things tend now, the special keys require (I think) that you release the modifier key before using it again. In other words. if you hold down Alt and press Enter, you toggle fullscreen/windowed, but if you continue to hold down Alt and press Enter again, the toggle doesn't work. You have to release Alt and then press it again and press Enter. 

I'm not sure this is relevant at all, but it's something that keeps tripping me up with the current keyboard assignments.

**Comment by joncampbell123** [comment]
I've been thinking that right ctrl would be a poor choice because of old DOS games, and alt would make it impossible to use Windows 3.1, but F12 is not widely used by either and it might make a good host key.

**Comment by joncampbell123** [comment]
Those who use keyboard shortcut-heavy programs that involve F12 can re-define it to something else in the mapper, of course.

**Comment by emendelson** [comment]
As long as we can change it to something like Right-Ctrl, that's fine! I hope it will be easy for those of us who build DOSBox-X to modify the code...

**Comment by joncampbell123** [comment]
Good! It will be a modifier that you can change in the mapper, of course!

**Comment by emendelson** [comment]
While we're on the subject, can DOSBox-X distinguish between left and right Ctrl? I don't think DOSBox can do that....

**Comment by joncampbell123** [comment]
Yes, it can. So can the original DOSBox.

**Comment by emendelson** [comment]
I'm on the road so I won't ask about this again until I get back, but all I remembered for the MAPPER_AddHandler function were indicators like MMOD1 and MMOD2 - will search for the method of  distinguishing left/right MMOD1 or MMOD2 when I get back.

**Comment by Shane32** [comment]
F12 sounds good as a host key.  Most games and programs used F1-F10 rather than F11 and F12.

I'm assuming that pressing the host key then waits for another key or combination to be pressed.  I'd suggest that if the next key combination that involves the host key, it would pass through.  So like F12 + F12 = F12 in game, or F12 + Ctrl-F12 = Ctrl-F12 in game.

Another option is if the host key works as a modifier.  Then I'd suggest the host key and regular modifiers pass through -- e.g. F12, shift-F12, ctrl-F12 and alt-F12 pass through.  But F12+M (pressed together) opens the dosbox-x menu.

**Comment by joncampbell123** [comment]
There is now a "host" modifier key.

**Comment by joncampbell123** [comment]
As implemented now, you have to hold F12 and then hit the key. Is that OK?

**Comment by joncampbell123** [comment]
I've modified the mapper to allow shortcuts to be defined that don't have a default binding, and I've moved a good portion of the default shortcuts to the host key.

Any comments?

**Comment by emendelson** [comment]
I'm away from my development machine today, but this looks very interesting and useful. Quick question: for my project, which runs DOS applications like WordPerfect that use F9, presumably I can change the F9 host key to Ctrl-Alt-F9 by adding MMOD1|MMOD2 as in older versions?

Will try this out as soon as I can.

**Comment by joncampbell123** [comment]
@emendelson The host key is a modifier that can be moved to any other key you want. I don't think you can make the host key a combination of keys however.

@Shane32 The host key is re-definable like any other modifier. I made combinations to avoid conflicts in a very conservative way. I chose to map some to shift or CTRL out of concern that since 'c', 'd' and 'f' are so close together on the keyboard it might be too easy to accidentally go fullscreen when you intended to swap disks or CD.

**Comment by emendelson** [comment]
OK - understood. So that means that the host key could be Scroll Lock or Pause?

**Comment by joncampbell123** [comment]
@emendelson Yes. Pause however is already taken by the DOSBox pause function and debugger interface, so you'll need to remove those from the mapper first for Pause.

**Comment by emendelson** [comment]
Understood. For DOS applications, most of the mapper keys just get in the way, so I've removed almost all of them except the full-screen toggle and a (temporary) one that restores the window to its original size after stretching. (I'll take that out after the option to disable stretchable windows goes back in.) Now my job is to figure out a host key that will be on a laptop but won't get in the way of WordPerfect....

Alternatively, it occurs to me, I might have enough skill to write an internal SCRNTOGL command that would make it unnecessary to use a host key (just run a WordPerfect macro that shells to DOS and runs the command). Or maybe there's already a config command that does this?

I've got a second project that runs WfW311, and this won't be an issue there, I think.

**Comment by joncampbell123** [comment]
@emendelson On second thought a problem with the Pause key just occurred to me. Pause is the only key on the keyboard that sends only a keypress instead of a 'key down' and 'key up' message, for some weird legacy reason. The host key as implemented now requires holding the key, so making "pause" the host key is currently impossible.

This isn't DOSBox-X's fault, this is just how the "pause" key works :(

**Comment by emendelson** [comment]
That still leaves ScrollLock - and thank you for letting me know why Pause wouldn't work when I get a chance to try out the new code!

**Comment by Shane32** [comment]
I’d leave it as F12 by default, personally. It works for nearly all mainstream applications (besides WordPerfect) and games. There’s plenty of alternatives if someone wants to change it, depending on their needs or what device they are using. Such as tilde, scroll lock, and the pop up menu key. 

I would suggest an entry in the conf file for the default host key scan code. Then (1) a conf file for WordPerfect can be written without an mapper file as well and (2) the config utility can change the scan code from within dosbox on the fly (so it can change the host key just before starting WordPerfect)

**Comment by joncampbell123** [comment]
CONFIG.COM could just accept a new command line parameter defining the mapper key without adding to dosbox.conf.

The mapper file (funny enough) defines which key is the mapper key, so having another option in dosbox.conf would be redundant.

**Comment by emendelson** [comment]
Another thought: If I tap the host key, then release it without holding it down and pressing a mapper key, could you simply pass the host key to the application? That would clear up all such potential problems.

**Comment by joncampbell123** [comment]
@emendelson At this time, F12 is both the host key and seen by the guest as F12. So if you don't trigger any shortcuts using the host key, the guest sees you press F12.

**Comment by joncampbell123** [comment]
@emendelson This is the only major difference from VirtualBox's implementation that never sends the host key to the guest.

**Comment by emendelson** [comment]
Aha!! Perfect!! I'm sorry to have wasted your time! I was thinking in terms of VirtualBox. Hoping to get back to my development machine soon to try this out. Thank you.

**Comment by joncampbell123** [comment]
Windows builds have moved the default host key to F11. F12 is already taken by some code deep in the Windows kernel to trigger a debugger.

**Comment by joncampbell123** [comment]
Here's something interesting about laptop keyboards that's worth noting.

I just got a new HP laptop, which apparently omits the menu (popup) key. That is interesting, considering that key has been a staple of keyboards since Windows 95.

It also puts the Pause key as fn + right shift. Bringing up the debugger is going to be very interesting that way!

F12 is still there though!

**Comment by parkerlreed** [comment]
I'm not sure what could be done here but the src/shell/shell.cpp has "Host key is F11" hardcoded. Was confusing for a second until I realized that's only there due to the Windows keybind. Would there be a way to have that dynamic? (Even if just at compile time)

**Comment by joncampbell123** [comment]
@parkerlreed Definitely. I would like to see the intro text, help text, and menus all reflect what the mapper says the shortcut is. The menus do that already.

The intro text however is harder to do that with because of the way the ANSI text and border are laid out.

My plan is to first write an "ANSI construction set" so that C++ code can just draw the border and text with basic layout code and then emit it as ANSI as the intro text. Once that is done, the shortcut can be printed inline with the rest of the text.
