### ISSUE TITLE
Freedos UIDE.SYS as CDROM driver results in failure

### ISSUE THREAD

**Issue by Jarvik7** [joncampbell123/dosbox-x#57]
Booting MSDOS 6.22 or 7.10 as a native OS:
In config.sys:
DEVICEHIGH=c:\cdrom\uide.sys /d:mscd001 /s5
^-- limiting cache size to 5mb

When the driver loads, the following error is put in the console:
"Unknown IDE/ATA command A1"
"IDE abort dh=0xa0 with error on 0x1f0"

Trying to access the drive (by changing to D) results in an error in the dosbox console:
"WARNING: ATAPI READ TOC Format=1 not supported"
^-- repeated a total of 4 times.

In the dos window there is an "Out of memory" error and retry/ignore/fail/abort options.

I can privately provide a small hdd image if necessary.

**Comment by joncampbell123** [comment]
Interesting. I tried UIDE.SYS and MS-DOS 6.22 and all I saw that was UIDE.SYS completely failed to see the CD-ROM drive, no other errors.

Go ahead and post the hdd and dosbox.conf if you want. I wonder if your setup does something more elaborate to cause out of memory errors.

**Comment by joncampbell123** [comment]
I want to add the "Unknown IDE/ATA command A1" is UIDE.SYS doing what most MS-DOS drivers like to do which is to issue both command A0 and A1 (PACKET and ATA IDENTIFY) commands. The ATA emulation doesn't support the PACKET IDENTIFY commands, and so on. That's normal.

It sounds like the true issue is that UIDE.SYS is using a form of READ TOC I haven't implemented yet.

**Comment by Jarvik7** [comment]
I sent you the link to the image on vogons via PM.

**Comment by joncampbell123** [comment]
Hm... still seeing the same thing. It fails to detect the CD-ROM drive but it doesn't crash or run erratically.

Can you provide the dosbox.conf you're using?

**Comment by Jarvik7** [comment]
Do you have an iso mounted to d?
I've actually been using daum at work and -x at home, but trying now with the latest -x binary gives the same results.

**Comment by Jarvik7** [comment]
DOSBox LOG: DOSBox version DOSBox-X
DOSBox LOG: Copyright 2002-2015 DOSBox Team, published under GNU GPL.
DOSBox LOG: ---
DOSBox LOG: DOSBox_CheckOS results: id=2 major=6 minor=1
DOSBox LOG: GUI: Press Ctrl-F10 to capture/release mouse.
     Save your configuration and restart DOSBox if your settings do not take effect.
DOSBox LOG: SDL:Unsupported output device direct3d, switching back to surface
DOSBox LOG: A20: fast remapping (64KB+1MB) DOSBox style
DOSBox LOG: ROM BIOS range: 0xf0000-0xFFFFF
DOSBox LOG: ROM BIOS range, final: 0xf0000-0xFFFFF
DOSBox LOG: ROMBIOS_GetMemory(0x00034 bytes,"BIOS ID string",align=1,mustbe=0xfe00e) = 0xfe00e
DOSBox LOG: ROMBIOS_GetMemory(0x00016 bytes,"BIOS version string",align=1,mustbe=0xfe061) = 0xfe061
DOSBox LOG: ROMBIOS_GetMemory(0x00400 bytes,"BIOS 8x8 font (first 128 chars)",align=1,mustbe=0xffa6e) = 0xffa6e
DOSBox LOG: I/O delay 1020ns
DOSBox LOG: ROMBIOS_GetMemory(0x01600 bytes,"DOSBox callback area",align=1,mustbe=0x00000) = 0xfe46e
DOSBox LOG: ROMBIOS_GetMemory(0x0000e bytes,"DOSBox vm86 hack",align=1,mustbe=0x00000) = 0xfffe2
DOSBox LOG: Callback area starts at f000:e46e
DOSBox LOG: PIT: Hacks disabled
DOSBox LOG: VGA memory I/O delay 0ns
DOSBox LOG: APM BIOS allow: real=1 pm16=1 pm32=1
DOSBox LOG: voodoo: ogl=0
DOSBox LOG: MIDI:Opened device:win32
DOSBox LOG: ROMBIOS_GetMemory(0x00005 bytes,"BIOS default reset location",align=1,mustbe=0x00000) = 0xfffdd
DOSBox LOG: ROMBIOS_GetMemory(0x00001 bytes,"BIOS default handler location",align=1,mustbe=0x00000) = 0xfffdc
DOSBox LOG: ROMBIOS_GetMemory(0x00013 bytes,"BIOS default IRQ0 location",align=1,mustbe=0x00000) = 0xfffc9
DOSBox LOG: ROMBIOS_GetMemory(0x00015 bytes,"BIOS default IRQ1 location",align=1,mustbe=0x00000) = 0xfffb4
DOSBox LOG: ROMBIOS_GetMemory(0x00007 bytes,"BIOS default IRQ2 location",align=1,mustbe=0x00000) = 0xfffad
DOSBox LOG: Registered ISA PnP read port at 0x20b
DOSBox LOG: ROMBIOS_GetMemory(0x00021 bytes,"ISA Plug & Play BIOS struct",align=16,mustbe=0x00000) = 0xfff80
DOSBox LOG: ISA Plug & Play BIOS enabled
DOSBox LOG: ROMBIOS_GetMemory(0x00010 bytes,"BIOS configuration (INT 15h AH=0xC0)",align=16,mustbe=0x00000) = 0xfff70
DOSBox LOG: ROMBIOS_GetMemory(0x00058 bytes,"BIOS video table (INT 1Dh)",align=1,mustbe=0x00000) = 0xfff18
DOSBox LOG: VGA BIOS occupies segment 0xc000-0xc2ff
DOSBox LOG: DOS: MAXENV=65535 ENV_KEEPFREE=1024
DOSBox LOG: Dynamic DOS kernel mode, structures will be allocated from pool 0x0070-0x9bff
DOSBox LOG: DOS_GetMemory(0x0001 pages,"DOS_IHSEG") = 0x0070
DOSBox LOG: DOS_GetMemory(0x0020 pages,"DOS_INFOBLOCK_SEG") = 0x0071
DOSBox LOG: DOS_GetMemory(0x0008 pages,"DOS_CONDRV_SEG") = 0x0091
DOSBox LOG: DOS_GetMemory(0x000a pages,"DOS_CONSTRING_SEG") = 0x0099
DOSBox LOG: DOS_GetMemory(0x0056 pages,"DOS_SDA_SEG") = 0x00a3
DOSBox LOG: DOS_GetMemory(0x0010 pages,"DOS_CDA_SEG") = 0x00f9
DOSBox LOG: DOS_GetMemory(0x0040 pages,"DOS_FIRST_SHELL") = 0x0109
DOSBox LOG: DOS kernel alloc:
DOSBox LOG:    IHSEG:        seg 0x0070
DOSBox LOG:    infoblock:    seg 0x0071
DOSBox LOG:    condrv:       seg 0x0091
DOSBox LOG:    constring:    seg 0x0099
DOSBox LOG:    SDA:          seg 0x00a3:0x0000
DOSBox LOG:    CDS:          seg 0x00f9
DOSBox LOG:    first shell:  seg 0x0109-0x0148
DOSBox LOG: [private segment @ this point 0x0070-0x9c00 mem=0x100000]
DOSBox LOG: DOS_GetMemory(0x0004 pages,"dos.tables.mediaid") = 0x0149
DOSBox LOG: DOS_GetMemory(0x0004 pages,"dos.tables.tempdta") = 0x014d
DOSBox LOG: DOS_GetMemory(0x0004 pages,"dos.tables.fcbdelete") = 0x0151
DOSBox LOG: DOS_GetMemory(0x000c pages,"dos.tables.dbcs") = 0x0155
DOSBox LOG: DOS_GetMemory(0x0002 pages,"dos.tables.filenamechar") = 0x0161
DOSBox LOG: DOS_GetMemory(0x0019 pages,"dos.tables.collatingseq") = 0x0163
DOSBox LOG: DOS_GetMemory(0x0004 pages,"Fake FCB SFT") = 0x017c
DOSBox LOG: DOS_GetMemory(0x0002 pages,"dos.tables.dpb") = 0x0180
DOSBox LOG: DOS_GetMemory(0x0006 pages,"Fake disk buffer head") = 0x0182
DOSBox LOG: DOS_GetMemory(0x0000 pages,"DOS_MEM_START") = 0x0188
DOSBox LOG:    mem start:    seg 0x0400
DOSBox LOG: DOS private segment set to 0xc300-0xcaff
DOSBox LOG: DOS_GetMemory(0x0001 pages,"xms_callback") = 0xc300
DOSBox LOG: UMB ending segment 0xf000 conflicts with BIOS at 0xf000, asking BIOS to move aside
DOSBox LOG: UMB ending segment 0xf000 conflicts with BIOS at 0xf000, truncating region
DOSBox LOG: UMB assigned region is 0xcb00-0xefff
DOSBox LOG: DOS_GetMemory(0x0002 pages,"ems_baseseg") = 0xc301
DOSBox LOG: EMS: OS handle allocated 0x00110000-0x00127fff
DOSBox LOG: Enabling VCPI emulation
DOSBox LOG: EMS:EMM OS handle is associated with memory on an odd megabyte. Enabling A20 gate to avoid corrupting DOS state
DOSBox LOG: DOS_GetMemory(0x0001 pages,"i33loc") = 0xc303
DOSBox LOG: FDC installing to io=3f0h IRQ=6 DMA=2
DOSBox LOG: IDE: Not registering port 3F7h, FDC will occupy it.
DOSBox LOG: DOS_GetMemory(0x0080 pages,"COMMAND.COM stack") = 0xc304
DOSBox LOG: SHELL: psp_seg 0x0109
DOSBox LOG: SHELL: env_seg 0x011c
DOSBox LOG: DOS_AllocateMemory(blocks=0x0045) = 0x0419-0x045d
DOSBox LOG: DOS_AllocateMemory(blocks=0x9ba0) = 0x045f-0x9ffe
DOSBox LOG: DOS_ResizeMemory(seg=0x045f) blocks=0x0040
DOSBox LOG: DOS_AllocateMemory(blocks=0x0045) = 0x0419-0x045d
DOSBox LOG: DOS_AllocateMemory(blocks=0x9ba0) = 0x045f-0x9ffe
DOSBox LOG: DOS_AllocateMemory(blocks=0x0045) = 0x0419-0x045d
DOSBox LOG: DOS_AllocateMemory(blocks=0x9ba0) = 0x045f-0x9ffe
DOSBox LOG: DOS_ResizeMemory(seg=0x045f) blocks=0x0040
DOSBox LOG: DOS_AllocateMemory(blocks=0x0045) = 0x0419-0x045d
DOSBox LOG: DOS_AllocateMemory(blocks=0x9ba0) = 0x045f-0x9ffe
DOSBox LOG: DOS_ResizeMemory(seg=0x045f) blocks=0x0040
DOSBox LOG: IDE: index 0 slave=0
DOSBox LOG: DOS_GetMemory(0x0002 pages,"imgDTASeg") = 0xc384
DOSBox LOG: Using partition 0 on drive; skipping 63 sectors
DOSBox LOG: Mounted FAT volume is FAT16 with 64439 clusters
DOSBox LOG: Mapping BIOS DISK C/H/S 1023/64/63 as IDE 4092/16/63
DOSBox LOG: DOS_AllocateMemory(blocks=0x0045) = 0x0419-0x045d
DOSBox LOG: DOS_AllocateMemory(blocks=0x9ba0) = 0x045f-0x9ffe
DOSBox LOG: DOS_ResizeMemory(seg=0x045f) blocks=0x0040
DOSBox LOG: IDE: index 0 slave=1
DOSBox LOG: DOS_AllocateMemory(blocks=0x0045) = 0x0419-0x045d
DOSBox LOG: DOS_AllocateMemory(blocks=0x9ba0) = 0x045f-0x9ffe
DOSBox LOG: DOS_ResizeMemory(seg=0x045f) blocks=0x0040
DOSBox LOG: IDE: index 0 slave=1
DOSBox LOG: DOS_GetMemory(0x0002 pages,"MSCDEX device header") = 0xc386
DOSBox LOG: DOS_GetMemory(0x0126 pages,"MSCDEX temp buffer") = 0xc388
DOSBox LOG: DOS_AllocateMemory(blocks=0x0045) = 0x0419-0x045d
DOSBox LOG: DOS_AllocateMemory(blocks=0x9ba0) = 0x045f-0x9ffe
DOSBox LOG: DOS_ResizeMemory(seg=0x045f) blocks=0x0040
DOSBox LOG: Booting guest OS stack_seg=0x7000 load_seg=0x07c0
DOSBox LOG: Removing UMB block 0xcb00-0xdfff
DOSBox LOG: Unmapping DOS private segment 0xc300-0xcaff
DOSBox LOG: Alright: DOS kernel shutdown, booting a guest OS
DOSBox LOG:   CS:IP=0000:7c00 SS:SP=7000:0100 AX=0000 BX=7c00 CX=0001 DX=0080
DOSBox LOG: DOSBox switched to max cycles, because of the setting: cycles=auto. If the game runs too fast try a fixed cycles amount in DOSBox's options.
DOSBox LOG: INT13: Check Extensions Present for drive: 0x80
DOSBox LOG: IDE ATA command a1 dh=0xa0 count=0x00 chs=00/00/00
DOSBox LOG: Unknown IDE/ATA command A1
DOSBox LOG: IDE abort dh=0xa0 with error on 0x1f0
DOSBox LOG: INT 15h mouse initialized to 3-byte protocol
DOSBox LOG: INT 15h reporting mouse device ID 0x00
DOSBox LOG: INT 15h reporting mouse device ID 0x00
DOSBox LOG: ATAPI CD-ROM: triggered to spin up from idle
DOSBox LOG: ATAPI CD-ROM: spinup complete
DOSBox LOG: WARNING: ATAPI READ TOC Format=1 not supported
DOSBox LOG: WARNING: ATAPI READ TOC Format=1 not supported
DOSBox LOG: WARNING: ATAPI READ TOC Format=1 not supported
DOSBox LOG: WARNING: ATAPI READ TOC Format=1 not supported
DOSBox LOG: ATAPI CD-ROM: spinning down
ion
     0x000fffe2-0x000fffef free=0 DOSBox vm86 hack
[end dump]
DOSBox LOG: TIMER: 1 leftover handlers (clean up!).

**Comment by joncampbell123** [comment]
I do have a mounted drive d, yes.

I also just thought of something: are you using an .iso file or a .cue file with multiple tracks?

**Comment by Jarvik7** [comment]
win98se.iso
![uidefail](https://cloud.githubusercontent.com/assets/6679920/7038307/d69801ae-ddea-11e4-9a30-9dd9cbdc5add.png)

**Comment by joncampbell123** [comment]
Well to help diagnose this, other information might help.

There are a few known issues with DOSBox-X and 64-bit builds. Is that a 64-bit build? What cpu core are you using? I see from the error log ems and vcpi are enabled. Do you get the same error on 32-bit builds? I'm trying the same on 32-bit and not getting the same problem.

**Comment by Jarvik7** [comment]
It's the 32bit build on 32bit Win7. Latest binary just downloaded within the past hour.
There is no conf file and I haven't changed anything, so it's all default settings (dynamic core, cpu auto)

Running as follows:
imgmount c <path>16bit_20150331.img
imgmount d <path>win98se.iso -t iso
boot -l c

Also, I get a blip of noise on my headphones when trying to change to D, so sounds like a memory corruption issue.

**Comment by joncampbell123** [comment]
Strange. I am running 32-bit on Linux and I reduced my dosbox.conf down to nothing but an [autoexec] section with your exact commands, and it still doesn't trigger the same effects.

I'll boot up Windows 7 and see if it happens there.

**Comment by joncampbell123** [comment]
OK. Here's what I think is wrong:

I accidentally broke SHR/SHL emulation in the normal core some commits before that build, and realized my mistake some commits after, which is why my latest commit doesn't have that problem.

The broken SHR/SHL emulation fetches the immediate shift count before decoding the effective address bytes, instead of fetching/decoding the effective address THEN the immediate shift count.

Having that, I'm disappointed that the working builds don't even factor into UIDE.SYS's detection.

**Comment by Jarvik7** [comment]
The latest daum binary exhibits the same problem, so the bug has been in the tree since at least before Jan 22 (the dosbox-x version daum is based off)

**Comment by joncampbell123** [comment]
Ok. Never mind the latest build still has the problem. But I don't think it's memory corruption or a bug in CPU emulation. I think it's a problem with ATAPI emulation and UIDE.SYS. The "out of memory" error is what the error code happens to be, but the driver still acts like it's talking to the drive, including waiting for the CD-ROM drive to spin up.

**Comment by joncampbell123** [comment]
Ok. I just fixed the issue by updating the READ TOC command emulation to support the "multisession" form of the command that UIDE.SYS likes to use. The same command code is used to read the Table of Contents and then another byte value is changed to ask the drive for multisession CD information.

**Comment by joncampbell123** [comment]
My latest commit contains the fix. On my end, I can now use your HDD image with a Windows 95 ISO image and run the setup program just fine.

**Comment by Jarvik7** [comment]
Great work!
I have another bug for you but I'll wait to compile the latest build on my home machine before filing it as it only occurs on OSX (graphics corruption causing the screen to always be blue and shades thereof).
