### ISSUE TITLE
USB 1.0-1.1 emulation and Virtual CD-ROM fix

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#570]
Dear Jon,
Can you add the USB 1.0-1.1 emulation, and fix the virtual CD drive emulation issues, like CD not recognized in Windows 95?
I would really hope for it.

**Comment by joncampbell123** [comment]
This is an open source project, feel free to try your hand at adding USB emulation in your fork and then submitting a pull request. Here's the spec for USB 1.0 and 1.1:

http://www.usb.org/developers/docs/devclass_docs/usbdi10.pdf

**Comment by joncampbell123** [comment]
As for CD-ROM emulation with Windows 95 the IDE emulation can support it. You need to enable int13fakev86io in order for Windows 95's IDE driver to successfully correlate the main hard drive C: with the IDE controller. IMGMOUNT supports specifying which IDE controller to attach to. DOSBox-X can already emulate a CD-ROM drive for Windows 95.

**Comment by joncampbell123** [comment]
If USB is a bit too much for you to handle, you could also look at the Bochs project and see how they implemented their USB emulation as a guide. You could port it to DOSBox-X your self as well. The NE2000 emulation in DOSBox/DOSBox-X came from Bochs, for example.
