### ISSUE TITLE
Homebrew version is really old

### ISSUE THREAD

**Issue by forthrin** [joncampbell123/dosbox-x#574]
`brew install dosbox-x` installs 0.801 from 2015. What's holding this back? Strict rules for stableness?

**Comment by joncampbell123** [comment]
I don't maintain the brew version of DOSBox-X, sorry.

**Comment by forthrin** [comment]
Who does? I don't know how brew publishing works. Is it automated? I see no author here, at least. https://github.com/Homebrew/homebrew-core/blob/master/Formula/dosbox-x.rb

**Comment by joncampbell123** [comment]
I have no idea. Perhaps someone made the package file and then forgot about it. I have no control over that.
