### ISSUE TITLE
Off-topic request for help with custom text modes

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#576]
There's no reason why anyone should take time over this unless it's of interest, because the question probably relates only to one of my projects, and not to anything else. I've been gradually moving a project from SVN to DOSBox-X, and came across this problem:

In my SVN-based project I have new text modes that use the standard VGA (9x16) font, but with screen sizes like 43x80 (43 lines of 80 characters each), 50x80, 60x80, 132x25, etc., etc.  I'll limit this question to 43x80 and 50x80.

I add these lines to int10_modes.cpp for 43- and 50-line modes:

`/* added 43-line mode */ //experimental plength changed from 2000 to 4000`
`{ 0x075  ,M_TEXT   ,720, 688, 80, 43, 9, 16, 8 ,0xB8000 ,0x4000, 100, 688, 80, 688, 0   },`
`/* Added 50-line mode */ //experimental plength changed from 2000 to 4000`
`{ 0x076  ,M_TEXT   ,720, 800, 80, 50, 9, 16, 8, 0xB8000 ,0x4000, 100, 800, 80, 800, 0   },`

(The second of these was given to me by one of the DOSBox devs.)

Then I add these commands in shell_cmds.cpp (along with a similar 25LINES command):

` void DOS_Shell::CMD_43LINES(char * args) {`
` 	HELP("43LINES");`
` 	if (CurMode->type == M_TEXT || IS_PC98_ARCH)`
` 		WriteOut("[2J");`
` 	else {`
` 		reg_ax = (Bit16u)CurMode->mode;`
` 		CALLBACK_RunRealInt(0x10);`
` 	}`
` 	reg_ax = 0x0075;`
` 	CALLBACK_RunRealInt(0x10);`
` }`

` void DOS_Shell::CMD_50LINES(char * args) {`
` 	HELP("50LINES");`
` 	if (CurMode->type == M_TEXT || IS_PC98_ARCH)`
` 		WriteOut("[2J");`
` 	else {`
` 		reg_ax = (Bit16u)CurMode->mode;`
` 		CALLBACK_RunRealInt(0x10);`
` 	}`
` 	reg_ax = 0x0076; `
` 	CALLBACK_RunRealInt(0x10);`
` }`

And of course I also add these same commands to the list near the top of the same file.

All of this works perfectly in SVN. In DOSBox-X, I can switch back and forth to 43-line mode, but 50-line comes up with double-width characters (as in old CGA 40-character text). I've played with the plength setting, but everything else I've tried causes a lockup.

Incidentally, perhaps I can contribute something useful by passing along this explanation of the ModeList settings, provided by a DOSBox dev:

> mode = mode number
> type = text, graphic, etc.
> sw, sh = width and height in pixels
> tw, th = width and height in columns and rows
> cw, ch = character width and height in pixels
> pt = page total(# of pages) 
> pstart = page start(linear address of first page)
> plength = page length(page size)
> htot,vtot = horizontal,vertical total(scan area)
> hde,vde = horizontal,vertical display end(display area)
> 

Again, this isn't a bug or anything else, but if anyone can suggest a way to get these other modes working in DOSBox-X as they do in SVN, I'll be very grateful.

**Comment by emendelson** [comment]
Again, I don't expect anyone to spend any time solving this, but it's still a puzzle to me why all these custom modes work in SVN, but three (as marked) don't work in DOSBox-X. If anyone has an inspiration, I'll be glad to hear about it:

`/* added by emendelson - 132x25, 132x43, 132x50, and 132x60 */
{ 0x071  ,M_TEXT   ,1056,400, 132,25, 9, 16, 8 ,0xB8000 ,0x4000, 192, 449, 132,400, 0 }, // 132x25 //doesn't work!!
{ 0x072,  M_TEXT   ,1056,688, 132,43, 9, 16, 8 ,0xB8000 ,0x4000, 192, 688, 132,688, 0 }, // 132x43 //192->160?
{ 0x073  ,M_TEXT   ,1056,800, 132,50, 9, 16, 8 ,0xB8000 ,0x4000, 192, 800, 132,800, 0 }, // 132x50 //192->160?
{ 0x074  ,M_TEXT   ,1056,960, 132,60, 9, 16, 8 ,0xB8000 ,0x4000, 192, 960, 132,960, 0 }, // 132x60 //192->160?
/* added by emendelson - 43-line mode */ //experimental plength changed from 2000 to 4000
{ 0x075  ,M_TEXT   ,720, 688, 80, 43, 9, 16, 8 ,0xB8000 ,0x4000, 100, 688, 80, 688, 0   }, // works
/* Added by emendelson - 50-line mode */ //experimental plength changed from 2000 to 4000 
{ 0x076  ,M_TEXT   ,720, 800, 80, 50, 9, 16, 8, 0xB8000 ,0x4000, 100, 800, 80, 800, 0   }, // doesn't work!!
/* Added by emendelson - 60-line mode */ //experimental plength changed from 3000 to 5000
{ 0x077  ,M_TEXT   ,720, 960, 80, 60, 9, 16, 1 ,0xB8000 ,0x5000, 100, 960, 80, 960, 0 },	// doesn't work!!
`
The 132x25 mode looks like this:
![132x25](https://user-images.githubusercontent.com/5208505/37877163-c66fa284-3024-11e8-9903-9584da9280e5.PNG)
and the 50-line and 60-line modes look like this:
![50line](https://user-images.githubusercontent.com/5208505/37877172-d50e8490-3024-11e8-900d-2884655bc189.PNG)
All the others work exactly as they should: the standard VGA font, but a larger window.

**Comment by joncampbell123** [comment]
I'll look into this soon.

Can you check your code against real hardware?

Also check what your program sends to the VGA using this reference to make sure it isn't setting any bits that would trigger this mode:

http://www.osdever.net/FreeVGA/vga/vga.htm

**Comment by joncampbell123** [comment]
Even better, can you provide a compiled EXE of your programs, so I can test it as well?

**Comment by joncampbell123** [comment]
Disregard my prior comments, I just noticed these are modes added to INT 10h, not standalone executables. Sorry.

**Comment by joncampbell123** [comment]
The decision making code whether to double horizontally and vertically can be found in src/gui/render.cpp, line 637, RENDER_SetSize()

**Comment by emendelson** [comment]
Exactly what I needed to know!! Thank you a thousand times over. This makes it possible for me to replace SVN with DOSBox-X in my main project.

**Comment by emendelson** [comment]
For the record, I modified render.cpp by adding this line after the line that begins double ratio =

`if (width < 1056 && height < 800) { `

and then closing the if statement with a bracket just above the line that reads render.src.width=width;

**Comment by emendelson** [comment]
And see issue 633 for further details.
