### ISSUE TITLE
MinGW 32-bit HX DOS extender target 

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#582]
YKSoft has been successful at compiling DOSBox-X to run in MS-DOS atop the HX extender, which is an interesting idea.

https://twitter.com/yksoft1/status/970910598111272960

Perhaps a MinGW-based HX DOS extender target could be made, that would revert SDL back to a single-window implementation compatible with HX.

**Comment by yksoft1** [comment]
This is what I did to build a Dosbox-X that runs under HX DOS Extender using MinGW.
Use this source tree: https://github.com/joncampbell123/dosbox-x/tree/6f87683029b7f90834d43689e04a5ace0847e8c3
Apply some patches to Dosbox-X files: 
[hx.zip](https://github.com/joncampbell123/dosbox-x/files/1787810/hx.zip)
define CFLAGS and CXXFLAGS with -DHX_DOS , 
configure SDL, make and make install.
configure DosBox-X with --disable-mt32 --disable-opengl.
This should make a dosbox-x.exe which works under HX DOS Extender, with default config file name changed to dosbox.ini.

BTW my Dosbox-X builds using MinGW works under Windows 2000 SP4, on my ancient Pentium MMX Sony PCG-C1S if output=surface is used. Of course it won't run anything at acceptable speed...
![dboxx-mmx](https://user-images.githubusercontent.com/37106774/37074495-10351fac-21c5-11e8-8f14-06f93e9811b3.png)

**Comment by joncampbell123** [comment]
Thanks!

To make the HX DOS extender version I will need to merge the code so that SDL reverts to the non-async version when compiled for HX.

**Comment by yksoft1** [comment]
As HX DOS extender just don't have a real window manager, add a new SDL1 target that omits the whole menu system would be ideal. Didn't know whether Dosbox-X with SDL2 runs under that.

**Comment by joncampbell123** [comment]
That's what I thought. I'll have the HX SDL version make a borderless window for HX.

**Comment by joncampbell123** [comment]
I got it to compile and run in HX-DOS!

Mouse input is working if I load CuteMouse first!

There are two more issues I see so far.

First is the keyboard mapping. The ; key is printing a tilde instead.

The second is that HXGUI is displaying a 800x600 screen and DOSBox-X looks a bit silly taking only the upper left hand corner. It would look better going fullscreen first.

**Comment by joncampbell123** [comment]
An interesting side effect is that the HX DOS build also runs under Windows 98.

**Comment by joncampbell123** [comment]
DONE
