### ISSUE TITLE
build error (if compiled without debugger)

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [joncampbell123/dosbox-x#583]
Hi,
current git source fails to build.
Writing

#define C_DEBUG 1

on the top of src/debug/debug_gui.cpp is a quick fix of this.

**Comment by leonier** [comment]
Or if you use Linux/MinGW/mingw-w64, --enable-debug in the configure command line would make it build.

**Comment by tokumeiwokiboushimasu** [comment]
Yes,  leonier is right. Writing "#define C_DEBUG 1 " can't fix the build. Sorry.

**Comment by joncampbell123** [comment]
Just fixed that now.
