### ISSUE TITLE
PC-98: GDC clock 2.5MHz/5MHz setting reversed?

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#592]
When I set "pc-98 start gdc at 5mhz" as false in dosbox.conf, games require 2.5MHz GDC (e.g. Rusty) don't run and just report that the GDC was set to 5MHz.

**Comment by joncampbell123** [comment]
Can you provide that exact line of dosbox.conf?

Also check whether your dosbox.conf autoexec section is using PC98UTIL to set the GDC to 5MHz before running the game.

I am unable to reproduce the issue.

**Comment by yksoft1** [comment]
[dosbox]
pc-98 start gdc at 5mhz=false

**Comment by joncampbell123** [comment]
Rusty from my testing requires the GDC in 5MHz mode. So do a few other games.

I can confirm that the false setting makes Rusty fail with an error message, and the 'true' setting allows it to run.

The default setting is "false" if you do not specify it in dosbox.conf.

**Comment by yksoft1** [comment]
However according to the error message, what it really need is the GDC clock to be set to 2.5MHz.

**Comment by joncampbell123** [comment]
This function is backwards then?

    virtual uint8_t inPortA(void) const {
        /* TODO: Improve this! What do the various 2-1 to 2-8 switches do?
         *       It might help to look at the BIOS setup menus of 1990s PC-98 systems
         *       that offer toggling virtual versions of these DIP switches to see
         *       what the BIOS menu text says. */
        return 0x63 | (gdc_5mhz_mode ? 0x80 : 0x00); // taken from a PC-9821 Lt2
    }

**Comment by yksoft1** [comment]
The problem might be in gdc_5mhz_mode_update_vars I think.

**Comment by joncampbell123** [comment]
I'm pulling out a PC-98 laptop now to double-check dip switch 2-8 and memory address 0x54D against the GDC setting.

**Comment by joncampbell123** [comment]
Right away, it looks like I got that port 31h handler backwards.

GDC at 5MHz:
I/O port 31h = 0x73
Mem 0x54D = 0x70

GDC at 2.5MHz:
I/O port 31h = 0xF3
Mem 0x54D = 0x50

**Comment by yksoft1** [comment]
I got the same values in Neko Project II. (Neko Project II series do have a BIOS setting screen, entered by pushing "HOME" key (the same as real PC-98s, NP2 mapped the key to "End" key on English keyboards) at boot.

**Comment by joncampbell123** [comment]
I believe I fixed this issue, will close unless otherwise.

**Comment by joncampbell123** [comment]
I believe the issue is fixed. Will close unless otherwise confirmed.

**Comment by yksoft1** [comment]
I could confirm this was fixed and you could close it safely now.
