### ISSUE TITLE
Segfault when mounting readonly floppy image files under Linux OR booting from a disk image with odd file size

### ISSUE THREAD

**Issue by frank-deng** [joncampbell123/dosbox-x#593]
When mounting floppy image files with only reading permission using `IMGMOUNT` under Linux, DOSBox-X will crash with Segmentation fault.

**Comment by joncampbell123** [comment]
Do you mean mounting with the -ro option, or mounting disk images marked read only by your host filesystem?

**Comment by frank-deng** [comment]
I tried to mount disk images marked read only on my Linux host filesystem.

**Comment by joncampbell123** [comment]
Ah, classic. Code that uses fopen() and doesn't check the return value against NULL, probably inherited from the original DOSBox project.

I'll check to see if this is the case.

**Comment by frank-deng** [comment]
Thanks!

**Comment by joncampbell123** [comment]
I'm not able to reproduce the issue, even if I make the floppy image read-only and immutable. It correctly errors out if the file is immutable and does not crash. Can you try the latest commit?

**Comment by frank-deng** [comment]
I tried the latest commit of DOSBox-X, the same problem occurs with the following dosbox command:
`imgmount 0 /home/frank/.dosbox/boot.img -t floppy -fs none`

**Comment by joncampbell123** [comment]
I still can't reproduce the issue, but I have come across this bizarre bug where mounting a disk image who's size doesn't match any geometry causes DOSBox-X to segfault.

**Comment by Shane32** [comment]
@frank-deng has the problem been solved with the latest commits?

**Comment by frank-deng** [comment]
Thanks. I'll try the latest commit some days later.

**Comment by frank-deng** [comment]
Thanks! It no longer segfaults when loading floppy disks with readonly permission under Linux.
