### ISSUE TITLE
IMGMOUNT hangs for creating a large ram disk after merging pull request #596

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#598]
Use this command:
> imgmount c -t ram -size 128000

Then Dosbox-X hangs.
Is it only on MinGW or will occur on a VS2017 build?

**Comment by joncampbell123** [comment]
That's a question for @Shane32. He may have fixed it in the latest pull request given to me.

**Comment by Shane32** [comment]
Fixed in pull #599

**Comment by Shane32** [comment]
Can you confirm the issue is fixed in MinGW, @yksoft1 ? I only have VS2017.

**Comment by joncampbell123** [comment]
While you're waiting, there's a typo in the C++ class.

https://www.vogons.org/viewtopic.php?f=41&t=31881&p=656664#p656664

**Comment by yksoft1** [comment]
Seemed that it was OK now on MinGW.
@joncampbell123

**Comment by Shane32** [comment]
Fixed the type-o with #603 
Also realized my image sizing was based on ATA limits instead of BIOS/MBR limits so I fixed that
Added a bunch of logging so you can see what c/h/s it selects when creating an image

**Comment by Shane32** [comment]
I tried to test it thoroughly.....but let me know if you find any issues!

**Comment by Shane32** [comment]
I suggest we close this issue now.

**Comment by joncampbell123** [comment]
Sounds good to me
