### ISSUE TITLE
PC-98: MS-DOS 5.0 (for PC-98) HIMEM.SYS complains that it cannot control A20 gate

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#602]
https://github.com/joncampbell123/dosbox-x/commit/abee0a9aa9dbb17c6ffad0db188a00861df42b28

**Comment by yksoft1** [comment]
MS-DOS 6.20's HIMEM.SYS (XMS 3.0) also complains this.
![gos](https://user-images.githubusercontent.com/37106774/37251194-0f54dd16-2503-11e8-971c-0a1c5a127cf9.jpg)

**Comment by joncampbell123** [comment]
Try the latest commit, I think I fixed it. At least MS-DOS 5.0 is happy now, on my end.

Port F6h can be treated as a A20 mask OR unmask, while writing port F2h always unmasks.

**Comment by joncampbell123** [comment]
Fixed.
