### ISSUE TITLE
BOOT causes DOSBox-X to crash if disk image is .FDD file

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#604]
Booting works fine with .FDI and .IMG but .FDD seems to cause a crash.

**Comment by yksoft1** [comment]
Virtual98 .fdd and P88SR/NP2 .d88 disk image formats might contain non-standard geometry, however the geometry itself is stored within those formats I remember.
By the way, some of those disk images may require ROM BASIC to boot (Disk BASIC-based games).

**Comment by joncampbell123** [comment]
Fixed

**Comment by yksoft1** [comment]
It seems that any older booter games use variable sector size between tracks as a way of copy protection.
DosBox-X currently don't support booting from such FDD images and complains

> VFD warning: sector size changes between track 0 and 1
in the log.

**Comment by joncampbell123** [comment]
That's a known divide by zero crash. DOSBox-X can't determine the disk geometry.

**Comment by yksoft1** [comment]
It won't crash but just refuses to boot or imgmount such FDD images.

**Comment by joncampbell123** [comment]
A lot of DOSBox-X's floppy handling design is written around the disk having a geometry, so format changes confuse the code at this point.

I'm not sure how to boot such disks, or even if the disks can run on PC-98.

**Comment by yksoft1** [comment]
Many of those disks definitely runs on PC-98 if you convert FDD images to D88 format using Virtual Floppy Image Converter, convert D88 to MAHALITO format using MOGREF, and then write such disks on real PC-98 with MAHALITO.

Virtual Floppy Image Converter:
https://www.vector.co.jp/soft/win95/util/se151106.html

MOGREF:
http://www.cug.net/~anonB/tool/

Mahalito:
https://www.vector.co.jp/soft/dos/util/se000604.html
