### ISSUE TITLE
PC-98 Enhancement request: BOOTing 2 floppy disk images in both drives and ability to change mounted floppy disks

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#605]
Many PC-98 booter games require 2 game disks in both floppy drives (such as "Program disk" and "Data disk") to boot, and may require inserting other disks playing the game.
What do I exactly want is, an option to not immediately boot when running BOOT command, give user a chance to "insert" both disks required to boot before actual booting.
And there should be a way to change IMGMOUNTed floppy disk images even with DosBox's DOS kernel disabled (such as running a booter game).

**Comment by joncampbell123** [comment]
:) I just added that!

Sort of... it kind of works, needs improvement.

IMGMOUNT 0 disk1.fdd -fs none
IMGMOUNT 1 disk2.fdd -fs none
BOOT -l a

**Comment by joncampbell123** [comment]
You may also try:

IMGMOUNT 1 diskB.fdd -fs none
BOOT disk1.fdd disk2.fdd disk3.fdd disk4.fdd

Then use the shortcut key for swapping disks (I think it should work!)

**Comment by yksoft1** [comment]
I confirmed that the imgmount -fs none trick worked after the last commit applied. However, I only find one non-DOS booter games working now: Alpha (Square). Falcom's Lord Monarch boots, but the sound is strange (plays when mouse moves, stops when mouse stops).

**Comment by joncampbell123** [comment]
There's still work to be done on the mouse, that's true.

**Comment by joncampbell123** [comment]
You can now imgmount multiple disk images on one drive.

It is possible to imgmount multiple disk images to B: and then boot the system disk on A:
