### ISSUE TITLE
PC-98: Sound board detected, but no sound in Rude Breaker

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#609]
It seemed that the sound driver FPLAY.COM detected sound board and used interrupt vector 7Fh for sound, but no sound at all in the game. The game itself otherwise is OK.
![clipboard01](https://user-images.githubusercontent.com/37106774/37272986-3c226250-25d0-11e8-9c42-0bb1637ebb82.jpg)

**Comment by joncampbell123** [comment]
I have no idea why, but here's what I see in DOSBox-X's debugger:

FPLAY detects the FM at INT0 (correct) which is IRQ 3, and installs an interrupt handler.

FPLAY also installs an INT 7Fh interrupt handler (as reported on the screen).

Rude Breaker is not calling INT 7Fh. Rude Breaker instead replaces INT 7Fh with it's own interrupt handler, though it does at least put back the original handler on exit to DOS.

So getting music to play means answering two important questions:
- How does Rude Breaker detect and call into FPLAY?
- How do you configure FPLAY to use a different interrupt number that doesn't conflict with Rude Breaker? (if that is possible)

**Comment by joncampbell123** [comment]
One more comment:

The interrupt handler Rude Breaker replaces INT 7Fh doesn't do anything. The interrupt handler is just an "IRET" for some reason.

**Comment by yksoft1** [comment]
According from here http://www.geocities.co.jp/Milkyway/7706/web/rescue/tech/v12/irq.html ,
Traditionally PC-98 uses IRQ 9 (INT 3) or IRQ 12 (INT 5) for sound board.

**Comment by joncampbell123** [comment]
I have a table of INT# lines to IRQ numbers I compiled from NP2 source code.

DOSBox-X so far has defaulted to IRQ 3 (INT0) which seems to work with a lot of games.

https://github.com/joncampbell123/dosbox-x/issues/594

**Comment by joncampbell123** [comment]
Here's an interesting discovery.

Rude Breaker won't do FM music if the FM board is on IRQ 3 (INT0), but it will do FM music if dosbox.conf says to put the FM board on IRQ 12 (INT5).

**Comment by joncampbell123** [comment]
This makes a convincing case to me that perhaps the default IRQ for PC-98 FM board emulation should be IRQ 12, not IRQ 3

**Comment by joncampbell123** [comment]
Setting FM board emulation IRQ 12 also resolves the Lord Monarch FM music issue.

**Comment by joncampbell123** [comment]
Issue is resolved by setting the FM board IRQ to 12.
