### ISSUE TITLE
CPU feature: core=log (debugging tool)

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#611]
At the cost of performance, it might help debugging if a "logging" core (based on the normal core) were implemented that records CPU state as each instruction is executed.

There are a class of DOS kernel and DOS application bugs that are hard to trace because the effect of the bug is not apparent until later on when the program attempts to call into a bad memory address.

**Comment by joncampbell123** [comment]
Then later, log_prefetch could be added to use the prefetch core code in the same way to help debug those naughty DOS games that use self-modifying prefetch queue anti-debugger trickery.

**Comment by nemo838** [comment]
So the SVN-daum version distributed two types of executables.
The debugging / logging module was included only in the version of the enhanced user distribution,
The other version did not include a debugging / logging module just for execution.

-translated by google-

**Comment by joncampbell123** [comment]
I just dug through the debugger code last night and I found that CPU logging as described is already implemented, so, no work needed on my part.

@nemo838 I had the same idea last night as well. Those who just want to play games might appreciate builds of DOSBox-X with the debugger functions disabled if it helps performance overall.
