### ISSUE TITLE
Yellow screen running Windows 98SE in more than 256 colours on macOS [16bpp renderer does not account for Mac OS X odd RGBA byte order]

### ISSUE THREAD

**Issue by jamesfreeman959** [joncampbell123/dosbox-x#614]
Hi there,

First of all, a huge thank you for continuing the development of DosBox - I'm a huge fan and have been playing with your builds recently. I run a Mac day to day so I am testing your latest macOS binary (v0.82.4). 

Yesterday I installed Windows 98SE (retail build, 2222A) into dosbox-x. It installs flawlessly and runs really well. However, I notice that as soon as I increase the color depth beyond 256 colours, I get what looks like a yellow filter across the whole screen. This occurs at any resolution, and at 16, 24 and 32-bit colour depths.

Is there a way to fix this - for example a setting that needs tweaking on the Mac? If there's anything I can do to help debug this please let me know.

Kind regards,

James

**Comment by joncampbell123** [comment]
If logging is enabled, provide that log file. The SDL init code provides the RGBA pixel layout given by the Mac OS X system.

As I understand it, Mac OS X uses an odd RGBA pixel layout and this is likely related to that.

**Comment by jamesfreeman959** [comment]
Thank you - I've generated a log file from a clean boot to Windows 98 and then shutdown. Not sure if my logging options are correct - let me know if you need something more generating.

[dosboxw98.log](https://github.com/joncampbell123/dosbox-x/files/1808568/dosboxw98.log)

**Comment by joncampbell123** [comment]
Please try running it from the Terminal app, at the command line, using the --debug switch. The logging level was not high enough for the GFX code to write the SDL RGB bitmasks.

**Comment by jamesfreeman959** [comment]
Sorry about that - please find a new log attached with the --debug switch specified.

[dosboxw98.log](https://github.com/joncampbell123/dosbox-x/files/1809006/dosboxw98.log)

**Comment by joncampbell123** [comment]
297067970       VGAMISC:VGA:S3:SEQ:Read from illegal index  9
 297067972       VGAMISC:VGA:S3:SEQ:Write to illegal index  9
 297068669       VGA:h total 336 end 256 blank (256/270) retrace (260/268)
 297068669       VGA:v total 806 end 768 blank (777/797) retrace (780/782)
 297068669       VGA:VGA refresh rate is now, 70.052
 297068669       VGA:screen: 1.333, scanfield: 1.345, scan: 0.817, vratio: 1.333
 297068669       VGA:h total 0.01771 (56.46kHz) blank(0.01349/0.01423) retrace(0.01370/0.01413)
 297068669       VGA:v total 14.26806 (70.09Hz) blank(13.76145/14.11568) retrace(13.81459/13.85001)
 297068669       VGA:video clock: 75.89MHz mode M_LIN16
 297068669       VGA:1024x768, 70.05Hz, 16bpp, screen 1.333
pixratio 1.000, dw false, dh false
 297068669 DEBUG MISC:GFX_SetSize 1024x768 flags=0x1148 scale=1.000x1.000
 297068669 DEBUG MISC:SDL video mode: 1024x768 (clip 1024x768 with upper-left at 0x0) 32bpp
 297068669 DEBUG MISC:   red: shift=8 mask=0x0000ff00
 297068669 DEBUG MISC:   green: shift=16 mask=0x00ff0000
 297068669 DEBUG MISC:   blue: shift=24 mask=0xff000000
 297068669 DEBUG MISC:   alpha: shift=0 mask=0x00000000
 297068669 DEBUG MISC:SDL video mode: 1024x768 (clip 1024x768 with upper-left at 0x0) 32bpp
 297068669 DEBUG MISC:   red: shift=8 mask=0x0000ff00
 297068669 DEBUG MISC:   green: shift=16 mask=0x00ff0000
 297068669 DEBUG MISC:   blue: shift=24 mask=0xff000000
 297068669 DEBUG MISC:   alpha: shift=0 mask=0x00000000

Whatever render code is in DOSBox-X to convert 16bpp to your host screen, isn't filling in the RGBA bytes correctly.

**Comment by jamesfreeman959** [comment]
Thanks! I'm not familiar with the dosbox-x codebase, but if there's anything I can do to help text/fix/debug this please let me know.

**Comment by joncampbell123** [comment]
Argh, so the problem was exactly what I thought it was: The renderer simple scaler assumes XRGB or XBGR pixel order. It can be adapted to Mac OS X's weird RGBA order, and that does fix the highcolor/truecolor formats, but then it breaks the VGA code that obediently follows the screen RGBA order.

**Comment by joncampbell123** [comment]
I added some hacks to both the renderer and the LIN32 renderer to make highcolor/truecolor formats display properly on Mac OS X systems. The hacks convert the RGB order to Mac OS X's weird BGRA order. 15/16/24/32bpp should display properly now (at least it does on my Mac Mini).

**Comment by srirangav** [comment]
Hi,

Thank you very much for all your working on dosbox-x.  It is a great resource.  

I see this issue on my M1 MacBook Air running Big Sur 11.6.2 when I use the pre-build SDL2 binary for dosbox-x 0.83.21, but not when I use the SDL1 binary for dosbox-x 0.83.21.

I ran the same Win98 instance using both binaries and generated the attached log files in which I switched form 256 colors to 16bit to 32bit and back.  

If there is something else I can do to help debug this, please let me know.

Thanks,

-ranga

 
[dosbox-x-sdl1.log](https://github.com/joncampbell123/dosbox-x/files/7885885/dosbox-x-sdl1.log)
[dosbox-x-sdl2.log](https://github.com/joncampbell123/dosbox-x/files/7885886/dosbox-x-sdl2.log)

**Comment by silverkors** [comment]
> Hi,
> 
> Thank you very much for all your working on dosbox-x. It is a great resource.
> 
> I see this issue on my M1 MacBook Air running Big Sur 11.6.2 when I use the pre-build SDL2 binary for dosbox-x 0.83.21, but not when I use the SDL1 binary for dosbox-x 0.83.21.
> 
> I ran the same Win98 instance using both binaries and generated the attached log files in which I switched form 256 colors to 16bit to 32bit and back.
> 
> If there is something else I can do to help debug this, please let me know.
> 
> Thanks,
> 
> -ranga
> 
> [dosbox-x-sdl1.log](https://github.com/joncampbell123/dosbox-x/files/7885885/dosbox-x-sdl1.log) [dosbox-x-sdl2.log](https://github.com/joncampbell123/dosbox-x/files/7885886/dosbox-x-sdl2.log)

I have this exakt same issue on my M1 MacBook Air running Monterey 12.0.1.

**Comment by silverkors** [comment]
> Hi,
> 
> Thank you very much for all your working on dosbox-x. It is a great resource.
> 
> I see this issue on my M1 MacBook Air running Big Sur 11.6.2 when I use the pre-build SDL2 binary for dosbox-x 0.83.21, but not when I use the SDL1 binary for dosbox-x 0.83.21.
> 
> I ran the same Win98 instance using both binaries and generated the attached log files in which I switched form 256 colors to 16bit to 32bit and back.
> 
> If there is something else I can do to help debug this, please let me know.
> 
> Thanks,
> 
> -ranga
> 
> [dosbox-x-sdl1.log](https://github.com/joncampbell123/dosbox-x/files/7885885/dosbox-x-sdl1.log) [dosbox-x-sdl2.log](https://github.com/joncampbell123/dosbox-x/files/7885886/dosbox-x-sdl2.log)

I have this exact same issue on my M1 MacBook Air running Monterey 12.0.1.
