### ISSUE TITLE
[Regression] Building on Windows 10 no longer possible from master

### ISSUE THREAD

**Issue by heydojo** [joncampbell123/dosbox-x#619]
It is not possible to build dosbox-x using Windows 10 and VS2017.

The commit is the patch to src/misc/regionalloctracking.cpp :
https://github.com/joncampbell123/dosbox-x/commit/95977e787cfac2360db252489d81c9adc2c273cf#diff-7bec259a6fcee0e81c3dfbad465fc17f

If I revert it, the build no longer fails.
Instead of reverting that commit, adding :
`typedef unsigned long ssize_t;`
to the top of regionalloctracking.cpp allows it to build. But I do not think it is the solution to this issue.

**Comment by joncampbell123** [comment]
That would mean VS2017 lacks ssize_t.

A short-term workaround then is:

    typedef signed long ssize_t

ssize_t is supposed to be signed.

**Comment by heydojo** [comment]
👍

**Comment by joncampbell123** [comment]
Good! Leave this issue open until I make a commit with that fix.

**Comment by joncampbell123** [comment]
Done

**Comment by heydojo** [comment]
Build now completes with commit https://github.com/joncampbell123/dosbox-x/commit/a4dd3ea777b572665fbc2bb8ee4310e57cabc42d
Issue resolved. Closing this issue.
