### ISSUE TITLE
JSDOSBox-X

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#622]
Dear Jon,
can you port DOSBox-X over to JavaScript for websites just to separate from DOSBox-X itself?

**Comment by joncampbell123** [comment]
I have no experience how to do this, sorry. I expect the javascript port of DOSBox involves some modifications and emscripten, but that's it.

**Comment by thfrwn** [comment]
@empsmoke I'd recommend trying to find who ported the original dosbox to JS. They could at least give you an idea about the complexity of such a project and maybe give some hints as to how work on it yourself...
There are other emulators that have been ported to HTML5/JS like PICO-8.. Finding the code and/or people behind those projects would be a good first step.

**Comment by empsmoke** [comment]
OK, I understood.
