### ISSUE TITLE
PC-98 request: emulate 31-KHz mode for PC-9821 emulation

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#624]
PC-9821 added a display mode that worked for standard PC VGA displays using 31KHz (70Hz) refresh rate, No other PC-98 emulators support this properly now and I wonder is there a way to support this in Dosbox-X.

**Comment by joncampbell123** [comment]
Good one!

I have been considering extending the PC-98 emulation to support first the 31KHz mode, and then the 15KHz mode!

This issue tracker would be a good place to collect information on that.

**Comment by joncampbell123** [comment]
Regarding the 31KHz mode, there are two references available to me.

The first is that there are numerous references and support for the 31KHz mode in the Neko Project II source code (enabled at compile time, behind #ifdef blocks).

The second is a PC-9821-V13 unit on my shelf who's default video mode is apparently the 31KHz mode.

**Comment by joncampbell123** [comment]
The PC-9821-V13 unit's 31KH mode is also a little buggy in that the BIOS seems to program horizontal sync parameters that cause horizontal sync to overlap active display by about 20 pixels, which causes problems with my capture cards either preventing them from capture or causing dark bands in the picture.

**Comment by yksoft1** [comment]
According to http://island.geocities.jp/cklouch/column/pc98bas/pc98dispout2_en.htm and http://tinyvga.com/vga-timing/640x350@70Hz ,
I tried to set the oscclock to 25.175MHz, GDC SYNC's HS to 2, VS to 2, VFP to 12, VBP to 35 and I got 70Hz refresh rate in PC-98 mode.
Not sure this is accurate but it seemed I found the way for implementing 31KHz mode.

**Comment by joncampbell123** [comment]
This is implemented and working in DOSBox-X now, so I will close this issue.
