### ISSUE TITLE
MinGW build fails in dos_programs.cpp after merging pull request #625

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#626]
> dos_programs.cpp: In member function 'imageDiskMemory* IMGMOUNT::CreateRamDrive(
> Bitu*, int, bool)':
> dos_programs.cpp:3011:11: error: cannot convert 'bool' to 'imageDiskMemory*' in
> return
>     return false;
>            ^~~~~
> dos_programs.cpp: In member function 'imageDisk* IMGMOUNT::MountImageNoneRam(Bit
> u*, int, bool)':
> dos_programs.cpp:3022:14: warning: NULL used in arithmetic [-Wpointer-arith]
>    if (ret != NULL) {
>               ^~~~
> make[3]: *** [dos_programs.o] Error 1

Why Microsoft's CL compiler thought that an object pointer could be converted to a bool?

**Comment by joncampbell123** [comment]
It looks like an honest mistake.

**Comment by joncampbell123** [comment]
Fixed.
