### ISSUE TITLE
Wrong settings for EGA  modes in int10_modes.cpp (from old SVN)?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#627]
This post on Vogons describes some fixes for the EGA modes in int10_modes.cpp, and these fixes are now (I think) in SVN, but not in DOSBox-X, which still uses the values from older versions of the SVN code:

https://www.vogons.org/viewtopic.php?f=32&t=43390

I came across this post while trying to solve the problem I described in this issue:

https://github.com/joncampbell123/dosbox-x/issues/576

I wonder if the problem I described in that post might be fixed by changing clock settings in int10_modes.cpp as described in the second code block of the Vogons post. What baffles me about my effort to create custom 50- and 60-line text modes is that the custom modes work perfectly in SVN, but not in DOSBox-X. The same problem occurs when I try to create a custom 132x25 mode. In each case, in DOSBox-X, a CGA-style double-width font gets selected instead of the VGA font, and I wonder if there's some timing issue that I don't understand that's causing the problem. 

But of course, the real issue for DOSBox-X is the possible wrong values described in the Vogons post, and any other changes made in SVN that haven't got into DOSBox-X.

**Comment by joncampbell123** [comment]
The decision to double vertically or horizontally is made somewhere in the GFX code upon modeset. It's generally based on number of scanlines, but it sounds like some oddity has cropped up there recently that needs to be examined.

**Comment by joncampbell123** [comment]
Also, the fixed values from DOSBox SVN do need to be incorporated. However, it's also possible SVN got it wrong as well. So some examination needs to be done.

**Comment by emendelson** [comment]
As of course you know (since you wrote the code!) DOSBox-X doesn't use the EGA_LINE_DOUBLE setting or similar settings, which seems to be why some numbers in the mode list won't match SVN anyway. 

By the way, the easiest mode-setting program I've found is David Manthey's VMODE:

https://www.orbitals.com/programs/index.html

It lets you test any mode with the command VMODE <mode number>. I thought of writing an equivalent into DOSBox, but I'm not expert enough to make a reliable conversion of a command-line parameter like "7" into "0x07" for use in the command. Someone expert could write this in five minutes, I would guess.

**Comment by joncampbell123** [comment]
I've *modified* the code over a long period of time, I can't claim I wrote the code. :)

I'll use that to look into DOSBox-X and real hardware, thanks.

**Comment by emendelson** [comment]
And I see that my attempt to write VMODE followed by "mode-number" in angle brackets didn't come through, so I edited my previous post to clarify what I was trying to say...

**Comment by joncampbell123** [comment]
I incorporated the latest EGA mode parameters from DOSBox SVN. I think that fixes it. However I will not mark the 200-line modes as doublescan, because EGA does not double the scanlines to the monitor. 200-line modes as far as I know become 200-line modes on the monitor, and 350-line modes become 350-line modes.

**Comment by sikthehedgehog** [comment]
Yep, in fact the 200-line modes are intended to be compatible with CGA monitors (hence also why it fixes the palette in those), although that only kind of works as many monitors burn up because two ground lines got repurposed (whoops).

**Comment by emendelson** [comment]
The fixed modes seem to work. Thank you. I'm still baffled at why some of the custom modes I describe in another issue still don't work in DOSBox-X, though they do work in SVN. I hoped this fix, might help, but it doesn't. (https://github.com/joncampbell123/dosbox-x/issues/576)

**Comment by emendelson** [comment]
And now those custom modes work, thanks to your help. Closing this issue...
