### ISSUE TITLE
SimCity 2000 Chinese Edition crashes in DOSBox-X

### ISSUE THREAD

**Issue by roytam1** [joncampbell123/dosbox-x#628]
Tested binary: dosbox-x-windows-20180316-212354-windows-mingw.zip, svga_s3
Tested game: SimCity 2000

Symptom: 
After typing SC2000[Enter], it shows DOS/4GW banner, and keeps in text mode with slow blinking cursor.

**Comment by yksoft1** [comment]
How about reinstalling the game using the default "VESA Super VGA" driver and Sound Blaster 16 audio?
It's OK in my own MinGW builds.

**Comment by joncampbell123** [comment]
@roytam1 If the cursor blinks slowly it usually means that there's a consistent error message going to the log. Try using the non-MinGW build, recreating the issue, and then using the menu to bring up the debugger.

**Comment by joncampbell123** [comment]
@roytam1 Actually, showing the console is enough (from the menu)

**Comment by roytam1** [comment]
> @roytam1 Actually, showing the console is enough (from the menu)

OK it keeps printing:
```
LOG:  281464941 ERROR CPU:Illegal Unhandled Interrupt Called 6
```

**Comment by joncampbell123** [comment]
@roytam1 Does changing core to normal, increasing RAM, or changing any other DOSBox conf setting change the error message?

**Comment by roytam1** [comment]
> @roytam1 Does changing core to normal, increasing RAM, or changing any other DOSBox conf setting change the error message?

I'm sharing same config with vanilla DOSBox, and such config works in vanilla DOSBox

**Comment by roytam1** [comment]
> @yksoft1
> How about reinstalling the game using the default "VESA Super VGA" driver and Sound Blaster 16 audio?
> It's OK in my own MinGW builds.

did you tried Chinese Edition?

**Comment by roytam1** [comment]
> @joncampbell123 
> Does changing core to normal, increasing RAM, or changing any other DOSBox conf setting change the error message?

nope, doesn't work with such config:
````
[dosbox]
machine=svga_s3
memsize=32

[cpu]
core=normal
cycles=15000
cycleup=500
cycledown=20
````

**Comment by roytam1** [comment]
temporary link for this, please tell me after finished downloading.
mega.nz/#!KYVk1JyS!h2FBX69HZL1xR7DSuHDuUUfZDY61FPdKeuR0Z1dAoes

**Comment by joncampbell123** [comment]
Got it. Testing now.

**Comment by joncampbell123** [comment]
Well, it does like to jump to undefined memory below 32KB does it.

Also, it reads 32MB of RAM as -32768KB of RAM.

**Comment by roytam1** [comment]
> Also, it reads 32MB of RAM as -32768KB of RAM.

Yes, that's why I set to 16MB RAM normally.
But even with 24MB, with vanilla DOSBox it works, but not with DOSBox-X.

**Comment by joncampbell123** [comment]
What cputype are you using?

**Comment by roytam1** [comment]
> What cputype are you using?

normal and auto, haven't tried others.

**Comment by joncampbell123** [comment]
So far, I see it doing setup in 16-bit protected mode and then going off into the weeds after a JMP 0000:0000, so something strange is going on here.

**Comment by joncampbell123** [comment]
However, I can get it running as follows (from the top directory of the game):

VESA\UNIVESA\UNIVESA.EXE
SC2000.EXE

So whatever "VESA" support the game needs it seems to need the UNIVESA driver's implementation, not what DOSBox-X is offering.

The JMP 0000:0000 makes me wonder if there's some VESA BIOS callback procedure that should be NULL or NOT NULL coming back from INT 10h, or if there's something about bank switching vs linear framebuffer going on.

**Comment by joncampbell123** [comment]
Hey, without UNIVESA.EXE, the game doesn't even try to call INT 10h AH=4Fh to contact the VESA BIOS! It just jumps to nowhere!

**Comment by joncampbell123** [comment]
SC2000.EXE seems to have problems being loaded too low in memory.

I can get it running (with non-garbled music even!) if I run it as follows:

LOADFIX
SC2000.EXE

**Comment by joncampbell123** [comment]
Update on the previous comment:

SC2000.EXE crashes if a specific amount of conventional memory is available.

If more than 600KB but less than 620KB of conventional memory is available, the game crashes and screws itself up.

So you can either use LOADFIX before loading the game,

or you can add this to your dosbox.conf

[dos]
minimum mcb segment=100

**Comment by joncampbell123** [comment]
The reason it works in DOSBox SVN is that recent commits of DOSBox SVN will leave as much conventional memory as possible (632KB) while DOSBox-X has less available (600KB) because it puts more of the DOS kernel in conventional memory.

**Comment by joncampbell123** [comment]
600KB is apparently the magic amount of conventional memory that VESA BIOS support other than UNIVESA.EXE will screw up and JMP to 0000:0000 and crash.

**Comment by yksoft1** [comment]
So it's another variant of the EXEPACK problems?

**Comment by joncampbell123** [comment]
Sort of...

DOS programs in general seem to have issues when loaded too low in memory. Whether it causes the program to crash depends on whether a critical part causes a segment register to wrap around or an overflow of some kind.

**Comment by joncampbell123** [comment]
It depends on the program. Some load just fine below 64KB, others have issues.

**Comment by joncampbell123** [comment]
I think it might also help to investigate the possibility that the DOS kernel may be writing to kernel structures below 64KB, but may be accidentally spilling out into adjacent memory. A spillover of that type could affect the DOS application if it's loaded too close to the DOS kernel down there.

**Comment by joncampbell123** [comment]
There seems to be some common issue with loading EXE files at segment 800h and crashiness in general (not just this game). There's something about loading at the 32KB mark that is causing problems. Loading things higher or lower helps resolves the issue. So that's something strange to investigate.

**Comment by joncampbell123** [comment]
Actually even loading at 800h with DEBUGBOX as the parent process resolves the crashiness and allows the game to run!

**Comment by joncampbell123** [comment]
I also noticed that DOSBox and DOSBox-X have DOS kernel code that allocates the command interpreter state in a special way not listed in the MCBs. I wonder if these DOS games have PSP parent/MCB tracing code that screws up in this arrangement.

**Comment by joncampbell123** [comment]
I just modded DOSBox's shell to allocate memory normally in the MCB chain and while that fixes the crash when minimum mcb segment=800, now it crashes when minimum mcb segment=680. The change only shifted the magic segment range down that causes crashes in DOS games.

However booting up a MS-DOS 5.0 bootdisk and looking at the MCB chain, the actual chain starts lower in memory. It starts at about segment 0x0216 and it includes the MS-DOS device drivers that were loaded at boot time. These blocks are marked 'SD'. Perhaps higher segment values cause crashes. Perhaps assumptions were made about the range of these values.

**Comment by joncampbell123** [comment]
There's something about loading the base of SC2000.EXE at segment 0x0680 to 0x0700 that causes the game to screw up and crash. None of my changes resolve that.

**Comment by joncampbell123** [comment]
If I shift it down by 0x80 segment value, and use DEBUGBOX.COM, it crashes the same.

**Comment by joncampbell123** [comment]
Since reloading the start address fixes the issue, I'm going to close this issue unless there's any reason I should not.

**Comment by roytam1** [comment]
Haven't test latest build without special config yet.
If it runs correctly with default config(like vanilla DOSBox), then this ticket can be closed.

**Comment by joncampbell123** [comment]
It does on my end.
