### ISSUE TITLE
FYI: Working on port for OpenBSD

### ISSUE THREAD

**Issue by thfrwn** [joncampbell123/dosbox-x#630]
Just letting you know that I'm working on porting dosbox-x to openbsd. We only got the stable release of original dosbox in ports which is many years old now. And its dynamic core conflicts with the goal of disabling W^X memory use as much as possible, so is deactivated by default.

dosbox-x seems to do everything our dosbox port does, only better :). 

The WIP of the port is here:

https://github.com/jasperla/openbsd-wip/tree/master/emulators/dosbox-x

I'm still reviewing and testing this, but it works! DOS games like Tie Fighter run much faster than with dosbox 0.74, and Win98 runs nicely, too! I even managed to see ingame of Deus Ex thanks to the voodoo emulation, although the performance is only on slideshow level.

Most of the patches are for {ftello,fseeko,fopen}64 function names. There's probably a more elegant way to do this.

Anyway, this post is primarily FYI that it runs nicely on OpenBSD and thanks for the great work on this!

**Comment by thfrwn** [comment]
Sorry, I found someone else looked into porting it before and removed it. Discussed it and there are some barriers to making this a port, so I removed it again. Still, thanks for all the work!

**Comment by joncampbell123** [comment]
@thfrwn I'm intrigued! Where is the FreeBSD port you refer to?

**Comment by thfrwn** [comment]
I don't know about FreeBSD, I only work on OpenBSD. The port can still be seen in the commit history, like here:

https://github.com/jasperla/openbsd-wip/tree/67a43a5699bbbc289dce88498565b82592361d58/emulators/dosbox-x

I have some questions that I'd prefer to discuss in PM. Will reach out to your email address if that's okay?
