### ISSUE TITLE
dosbox-x build with fluidsynth failed: undefined reference to `fluid_midi_parser_parse'

### ISSUE THREAD

**Issue by heavysink** [joncampbell123/dosbox-x#634]
Build complains about fluid_midi_parser_parse
g++  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt  -std=gnu++11  -msse  -Wno-strict-aliasing  -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -mmmx -msse -msse2  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a aviwriter/libaviwriter.a mt32/libmt32.a -lasound -lm -ldl -lpthread -L/usr/lib -lSDL -lpthread -ltinfo -lSDL_net -lpng -lz -lpcap -lX11 -lxkbfile -lfluidsynth -lGL
gui/libgui.a(midi.o): In function `MidiHandler_synth::PlaySysex(unsigned char*, unsigned long)':
midi.cpp:(.text._ZN17MidiHandler_synth9PlaySysexEPhm[_ZN17MidiHandler_synth9PlaySysexEPhm]+0x24): undefined reference to `fluid_midi_parser_parse'
gui/libgui.a(midi.o): In function `MidiHandler_synth::PlayMsg(unsigned char*)':
midi.cpp:(.text._ZN17MidiHandler_synth7PlayMsgEPh[_ZN17MidiHandler_synth7PlayMsgEPh]+0x44): undefined reference to `fluid_midi_parser_parse'
gui/libgui.a(midi.o): In function `MidiHandler_synth::Open(char const*)':
midi.cpp:(.text._ZN17MidiHandler_synth4OpenEPKc[_ZN17MidiHandler_synth4OpenEPKc]+0x85): undefined reference to `fluid_log_config'
midi.cpp:(.text._ZN17MidiHandler_synth4OpenEPKc[_ZN17MidiHandler_synth4OpenEPKc]+0x1a3): undefined reference to `new_fluid_midi_parser'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:450: dosbox-x] Error 1

building for archlinux with fluidsynth 1.1.10, 
configured with ./configure --prefix=/usr

**Comment by heydojo** [comment]
Your fluidsynth source needs to be patched with https://github.com/FluidSynth/fluidsynth/commit/4568e551b93c5c7fc90992a7edd5b8ce932c5b94

It was committed to fluidsynth master and then reverted by the same developer because he thinks it is abuse.. If there is a midi parser library which can replace fluidsynth's parser in the wild, here would be a great place to post a link. :)
