### ISSUE TITLE
Corrupt MCB chain after swapping out from WPDOS 5.1

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#638]
I'm not sure if the recent commits were designed to deal with this issue: https://github.com/joncampbell123/dosbox-x/issues/490 , but here's a report that may be related.

Building the current code, if I open WordPerfect for DOS 5.1 and use the File menu to Go to DOS (normally WP uses Ctrl-F1, but the Mapper uses that), WP opens a shell; I can then type EXIT to return to WordPerfect. And all is well. If I then exit WP 5.1, and try to open WordPerfect for DOS 6.2, I get "DOS fatal memory error: Corrupt MCB chain."

If, however, I change dos.cpp, line 1490 so that that reg_cx = 0x78c instead of 0x80, then the error does not occur and swapping from both programs is possible.

Again, if the recent changes were intended to fix this kind of problem, just ignore this!

**Comment by joncampbell123** [comment]
DOS kernel allocation of this type is in src/dos/dos.cpp starting at line 1918

**Comment by emendelson** [comment]
I'm not sure if you still need this information (because I don't understand the kernel allocation part of the code), but I can confirm that  reg_cx = 0x560 lets me swap in and out of WPDOS, and switch between versions after swapping, without any problem.

**Comment by joncampbell123** [comment]
I added an option to control the size of the SDA and to report that size through INT 21.

**Comment by joncampbell123** [comment]
Are you using the dynamic core? Try using core=normal.

**Comment by emendelson** [comment]
Will test tomorrow - thank you!

**Comment by emendelson** [comment]
The new code works perfectly. Thank you. I'll close this issue. But first:

1. If you want a WP51 setup for testing, just ask.

2. With the OLD code (prior to the latest commit), the core= setting had no effect; I got the same crash with core=normal as with core=auto or core=dynamic. When I ran WPDOS 5.1, then Go to DOS, and issued the MEM command, I got the debugger with the "corrupt MCB chain" message.

Again, this is entirely cleared up now.

**Comment by emendelson** [comment]
With this setting in dosbox.conf:

`dos sda size=0x80`

swapping works perfectly. Interesting...

**Comment by emendelson** [comment]
Yes, if I use the setting

[dos]
dos sda size=80

and run WPDOS 5.1, and Go to DOS, and enter MEM, I get the "corrupt MCB chain" error message.

I posted a mistaken message above, because I first tried this with "dos sda size=0x80" - but DOSBox-X interprets that as 0, not as 80, so I tried it again with plain "80" and got the same crash as before.
