### ISSUE TITLE
Specify DirectX SDK required? (or add DirectX to source?)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#639]
A minor issue: Is it stated somewhere that the DirectX SDK is required to build DOSBox-X in VS2017? I tried to build DOSBox-X on a 64-bit Windows 10 system with a fresh VS2017 installation, and got error messages saying that two files couldn't be opened: d3dx9math.h and d3dx9.h. I'm downloading the DirectX SDK now (on a slow connection), but I wonder if it might be possible to add the required files to the source tree?

**Comment by joncampbell123** [comment]
I may have to add the DirectX headers, yes. Getting the DirectX 2010 SDK installed is a pain in the ass in Windows 10. VS2017 doesn't seem to offer any obvious way to access the DirectX SDK.

**Comment by joncampbell123** [comment]
For legal reasons, I will first try to "fill in" from MinGW headers, and then copy in the rest from Microsoft's SDK where MinGW is lacking.

**Comment by heydojo** [comment]
> Getting the DirectX 2010 SDK installed is a pain in the ass in Windows 10.

It wasn't so bad for me.
I just downloaded it from Microsoft and installed it.
Then added the correct paths to the Visual studio project:
https://stackoverflow.com/questions/46755321/vs-2017-wont-find-directx-include-files

**Comment by heydojo** [comment]
> For legal reasons, I will first try to "fill in" from MinGW headers, and then copy in the rest from Microsoft's SDK where MinGW is lacking.

Actually, wine has dx9 headers which might do. However, it may be prudent to wait for the outcome of the Oracle Vs Google appeal trial. If the outcome of the appeal is found in favour of Oracle, then it could mean that including the dx9 headers would be too much of a legal grey area (in the US at least.)

_Disclaimer: I am no lawyer or any form of legal council. Please look at the available information about the appeal trial and Oracle's claims against Google; relating to Google's clean room implementation of java within Android. Doing so will assist you to best understand the implications of the outcome of the trial._

**Comment by joncampbell123** [comment]
Looking through the Windows SDK headers installed by VS2017 with grep, I might be able to compile against Direct3D9 by including d3d9.h instead of d3dx9.h and other minor changes.

That would be nice since that would mean not having to install the 2010 DirectX SDK.

**Comment by joncampbell123** [comment]
I have been compiling Direct3D9 support so far using the DirectX SDK from mid 2010 that is still available on Microsoft's site.

**Comment by aybe** [comment]
Here's the link to the kit:

https://www.microsoft.com/en-us/download/details.aspx?id=6812

And the fix to the potential error you might encounter while installing it:

https://support.microsoft.com/en-us/help/2728613/s1023-error-when-you-install-the-directx-sdk-june-2010

Note that you must restart VS for it to pick DXSDK_DIR environment variable.

**Comment by aybe** [comment]
[It's in the docs now](https://github.com/joncampbell123/dosbox-x/blob/master/README.Windows)
