### ISSUE TITLE
Build in macOS?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#640]
Is it possible to build DOSBox-X under macOS without using brew, mac ports, etc., but using only the command-line tools from Xcode? I can run autogen.sh, then configure, then make, but the build fails with:

In file included from sdl_gui.cpp:41:
/usr/local/include/SDL/SDL_syswm.h:58:10: fatal error: 'X11/Xlib.h' file not
      found
#include <X11/Xlib.h>

I'm able to build SVN in macOS without X11 by using (among a lot of other things) ./configure --without-x but that option is unrecognized in DOSBox-X.

**Comment by joncampbell123** [comment]
I use the ./build-debug script in the root of the source tree to compile a reasonable default.

**Comment by emendelson** [comment]
I should have figured out that those scripts were the way to go. Yes, the ./build-debug and ./build script do exactly what I was trying to do. Thank you!
