### ISSUE TITLE
Patch to add multiple custom video modes for text (50 lines, etc.)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#643]
This is in response to https://github.com/joncampbell123/dosbox-x/issues/633 , but it seemed to be best presented as a separate issue.

I am NOT asking that this be added to DOSBox-X, because it has nothing to do with accurate emulation. But for anyone who is interested, it adds these custom video modes, all using the standard VGA text font:

43-lines
50-lines
60-lines
66-lines
132x25
132x43
132x50
132x60

It also adds shell commands that switch between these modes and back to standard 25-line mode.  I hope it's useful to someone.

https://github.com/emendelson/dosbox-x/commit/29f8d55e319d27627adc5e3686310d3da6bef17b

**Comment by emendelson** [comment]
It may be useful to add to dos_programs.cpp this line in the block: void MODE::Run(void), after the line that begins mem_writeb:

`WriteOut("[2J"):`

This assures that the screen will be cleared when entering any mode command.

**Comment by emendelson** [comment]
I realize that this is entirely my problem, but I wonder if anyone has any insight that might help. The patch listed above worked perfectly in all my builds up to December 1st. I built again today (December 19th), and now the 60-line, 66-line, and 132x43, 132x50, and 132x60 modes have stopped working correctly. The bottom lines on the screen (8 through about 18 lines at the bottom, depending on the mode) repeat the top lines on the screen, but indented about a dozen characters. The 43-line and 50-line modes continue to work perfectly.

I can't see what change in the past 19 days might have caused this problem. Does anyone have a clue as to what change might have caused this? Is there some change affecting how much video memory is available or something like that? 

Again, I know this is my own problem, but I'm hoping to be able to use builds later than December 1st for my project, and the only way I can do this is by sorting out these custom modes.

**Comment by emendelson** [comment]
That does indeed fix it. Thank you!

**Comment by rderooy** [comment]
setting this in the dosbox-x config works fine here:

```ini
[sdl]
output = ttf

[ttf]
lins=50
cols=80
```
