### ISSUE TITLE
Tags have very long names

### ISSUE THREAD

**Issue by popey** [joncampbell123/dosbox-x#644]
The tags of dosbox-x have rather long names and some redundancy in there. Why have the "windows" name in there at all. The reason I ask is because the system I'm using to build it barfs when the version is longer than 32 characters, and yours is 42. I will of course file a bug against that other tool to get their limit lifted, but it does look a bit messy having -windows- in the tag name - especially when I'm not even building on or for Windows personally :)

**Comment by joncampbell123** [comment]
Those were very specific development branches. There is one experimental branch for compiling with cmake as well. Please use the master or develop branches.
