### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by empsmoke** [joncampbell123/dosbox-x#647]
Dear Jon,
Here are the upcoming things for version 0.9 :
1. Dial-up emulation (emulates dial-up, and also enables the use of AOL and Prodigy, but the user must use the parameter "fauxdialup 1" and "redirect-to-userfiles 1" to be set in the conf file.)
2. DX/SX/DX2 emulation (which also includes a switcher to switch from DX to SX and DX2)
3. i287, i387, and i487 emulation (which is going to be somewhat buggy)

If so, you could add them in 0.9 and create the DOSBox-X 1.0 milestone and project,
and also include a text document of all the community-suggested features.

**Comment by joncampbell123** [comment]
DOSBox-X already emulates the FPU. One can emulate the 386DX/SX or 486DX/SX in a basic manner using the "memory aliasing" feature (lesser address lines). Dial-up emulation is already a plan of mine, however I only plan on adding basic PPP/SLIP emulation for Windows 95 and earlier.

How's Project86 coming along?

**Comment by empsmoke** [comment]
Not updated, must scrap that.

**Comment by joncampbell123** [comment]
Well that's fine. I can't work on every possible feature, but if you have the programming skills to do it, feel free to clone DOSBox-X as DOSBox-X and code it yourself the way you think it should be done. Try it out, maybe it will work.

**Comment by empsmoke** [comment]
I got rid of VS which means I will use MinGW  to compile it.

**Comment by empsmoke** [comment]
because it could be incompatible with older versions of Windows before XP.

**Comment by empsmoke** [comment]
Fun fact, I read BleepingComputer all the time.

**Comment by joncampbell123** [comment]
That's your choice, but again I can't code everything and I have my own focus on the project as well. As I've stated on Twitter and elsewhere, my focus of late is on debugging facilities that can be used to figure out why a game or program is crashing.

MinGW does have a working port of GDB (the GNU debugger) by the way.

**Comment by empsmoke** [comment]
How to edit the Icons and BIOS image in MinGW, because I can't do that.

**Comment by joncampbell123** [comment]
The application icon is a standard .ico file.

The BIOS image is a BMP file compiled into the code as an unsigned char array using a tool in Linux (and possibly MinGW) called 'xxd'. The BMP must be in the paletted 16-color packed format. The unsigned char array is in one of the header files. There's another one for 2-color monochrome CGA as well. Have fun.
