### ISSUE TITLE
SDL2: no redraw, no fullscreen, no window resize with Windows 95

### ISSUE THREAD

**Issue by legluondunet** [joncampbell123/dosbox-x#648]
Hello,

I just downloaded the last Dosbox-x from git and I compiled it with SDL2.
I launched Windows 95 and i can not:
- go fullscreen: when I push on "alt+enter" keys, the cursor is inside dosbox-x but the window does not go fullscreen, it stays the OS original resolution.
- resize the dosbox-x window with the window corner
- the window does not redraw correctly and let black screen or squares (try alt+enter several times)

I joined you the log file.

Thanks.

[win95osr2.5-dosbox-x.log](https://github.com/joncampbell123/dosbox-x/files/1881996/win95osr2.5-dosbox-x.log)

Config:
Ubuntu + NVidia

**Comment by joncampbell123** [comment]
What output are you using?

Windows builds should default to Direct3D, Mac OS X to OpenGL, Linux to surface.

**Comment by emendelson** [comment]
Aren't these problems the result of building with SDL2? I asked a similar question in https://github.com/joncampbell123/dosbox-x/issues/479

**Comment by legluondunet** [comment]
I just recompiled dosbox-x with sdl1 and now I can resize window with stretch on or go fullscreen with alt+enter. I close this issue since it's a duplicate of #479
