### ISSUE TITLE
PC-98 mode SASI/SCSI BIOS (INT 1Bh) emulation

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#656]
According to NP2 code:

SASI BIOS functions are AH=0x00/0x80 and SCSI BIOS functions are AH=0x20/0xA0.

There are provisions it seems to specify read/write by CHS as well as LBA.

The goal is to be able to boot PC-98 MS-DOS from an HDI image, since most PC-98 games are distributed as HDI hard disk images (that may be bootable).

**Comment by joncampbell123** [comment]
Done.

It turns out prior attempts were blocked by a bug in the IMGMOUNT command where it would guess the geometry and then overwrite whatever the HDI image already specified. Since the PC-98 bootloader is sensitive to C/H/S geometry the incorrect guess caused it to load the wrong thing and crash. Also PC-98 bootable floppies need the correct C/H/S geometry to see the hard disk as well.

**Comment by yksoft1** [comment]
For many HDI images, there is still PROGRAM_BOOT_UNABLE errors coming out but imgmount -fs none/boot -l trick worked.
PC-98's partition table and IPL is much more complex than IBM's, NEC has a built-in menu to choose booting from which partition. And you cannot simply decide a disk is bootable by looking for 55 AA signature.
When I tried to boot a HDI with the boot menu, the booting just fails. This is the log:
```
Image file has .HDI extension, assuming HDI image and will take on parameters in header.
HDI header: sectorsize is 512 bytes/sector, header is 4096 bytes, hdd size (plus header) is 85647360 bytes
HDI: Geometry is C/H/S 1230/8/17
Booting guest OS stack_seg=0x0030 load_seg=0x1fe0
Removing UMB block 0xd000-0xcfff
Alright: DOS kernel shutdown, booting a guest OS
  CS:IP=1fe0:0000 SS:SP=0030:00d4 AX=0030 BX=0200 CX=0200 DX=0001
PC-98 INT 1Bh unknown SCSI BIOS call AX=00A0 BX=0200 CX=0200 DX=0001 SI=1FE0 DI=FFFE DS=0000 ES=1FE0
PC-98 INT 1Bh unknown SCSI BIOS call AX=00A0 BX=1C00 CX=1C20 DX=0002 SI=1D20 DI=FFFE DS=0000 ES=1C20
PC-98 INT 1Bh unknown SCSI BIOS call AX=00A0 BX=0400 CX=0000 DX=0002 SI=1D20 DI=FFFE DS=0000 ES=1C20
PC-98 INT 1Bh unknown SCSI BIOS call AX=00A0 BX=0400 CX=0267 DX=0000 SI=1D20 DI=FFFE DS=0000 ES=1C20
PC-98 INT 1Bh unknown SCSI BIOS call AX=00A0 BX=0200 CX=0100 DX=0001 SI=0800 DI=FFFE DS=0000 ES=1C20
PC-98 INT 1Bh unknown SCSI BIOS call AX=00A0 BX=0400 CX=0001 DX=0000 SI=0200 DI=FFFE DS=0000 ES=1FA0
PC-98 INT 1Bh unknown SCSI BIOS call AX=00A0 BX=0400 CX=0001 DX=0000 SI=0200 DI=FFFE DS=0000 ES=1FA0
rotate mode not supported
rotate mode not supported
PIC: 4 byte interval not handled
PIC: level triggered mode not handled
PIC: 8080/8085 mode not handled
PIC: 4 byte interval not handled
PIC: level triggered mode not handled
PIC: 8080/8085 mode not handled
PIC: 4 byte interval not handled
PIC: level triggered mode not handled
PIC: 8080/8085 mode not handled
PIC: 4 byte interval not handled
PIC: level triggered mode not handled
```
I suggest to reopen this issue until such problems are fixed.

**Comment by joncampbell123** [comment]
Will test.
Please pull the latest commit and check the HDI image.

**Comment by joncampbell123** [comment]
Works on my end. Please pull the latest commit.

![testx works pc98](https://user-images.githubusercontent.com/6245486/38794746-f229c296-410a-11e8-841a-02a5c4357679.png)

**Comment by joncampbell123** [comment]
Ah, spoke to soon. Selecting MS-DOS crashes.

**Comment by joncampbell123** [comment]
The DOSBox-X log reports that the geometry is C/H/S 1640/8/17.

Is that the correct geometry?

Knowing the IPL1 partition table it is unfortunately based on C/H/S sector addresses instead of LBA sector numbers, so getting the geometry correct is very important for PC-98 hard disk booting to work.

**Comment by yksoft1** [comment]
I created the HDI image in Anex86 with this geometry so I can 100% assume the CHS is right.

**Comment by joncampbell123** [comment]
The FAT driver appears to work fine with each partition of the image. The IPL1 parsing code uses the disk geometry from the HDI image to locate partitions, so that part is correct.

**Comment by joncampbell123** [comment]
Okay, if you imgmount without a filesystem attached, it crashes.

If you imgmount to drive c: and boot drive c:, it works.

I'll look into this now.

**Comment by yksoft1** [comment]
CHS 512/4/17 -> works
CHS 1024/8/17 -> works
CHS 1332/8/17 -> crashes
CHS 1178/8/17 -> crashes
CHS 1101/8/17 -> crashes
CHS 1063/8/17 -> crashes
CHS 1044/8/17 -> crashes
CHS 1025/8/17 -> crashes

**Comment by joncampbell123** [comment]
Now that I think of it, IMGMOUNT might still have some IBM PC specific code to try to adjust the C/H/S values if the cylinder count is > 1024 cylinders.

**Comment by yksoft1** [comment]
This?
```
			/* INT 13h mapping, deal with 1024-cyl limit */
			while (sizes[3] > 1024) {
				if (sizes[2] >= 255) break; /* nothing more we can do */

											/* try to generate head count 16, 32, 64, 128, 255 */
				sizes[2]/*heads*/ *= 2;
				if (sizes[2] >= 256) sizes[2] = 255;

				/* and recompute cylinders */
				sizes[3]/*cylinders*/ = (Bitu)((Bit64u)sectors / (Bit64u)sizes[2]/*heads*/ / (Bit64u)sizes[1]/*sectors/track*/);
			}
```

**Comment by joncampbell123** [comment]
That's exactly the code. It needs to not do it's work if PC-98 mode because PC-98 does not have the IBM PC legacy of a 510MB limit and having to remap cylinders into heads to bypass the limit.

**Comment by joncampbell123** [comment]
Fixing that code now...

**Comment by joncampbell123** [comment]
I have a fix I'm testing now.

The geometry translation was also in the disk image code itself.

**Comment by joncampbell123** [comment]
Pull the latest commit and try again.

**Comment by joncampbell123** [comment]
The latest commit allows your 3-partition 114MB HDI image to work.

**Comment by yksoft1** [comment]
Found the code in bios_disk.cpp by own and disabled that for PC-98 mode, then my 300MB+ HDI also worked...
Now how about the PROGRAM_BOOT_UNABLE error using BOOT xxx.hdi directly without imgmount first?

**Comment by joncampbell123** [comment]
I don't think BOOT ever supported booting a hard drive directly, even in the original DOSBox project. It only supports directly booting floppy disk images as drive A at this time.

**Comment by joncampbell123** [comment]
Git pull the latest changes and booting with the following will work:

IMGMOUNT 2 something.hdi -fs none
BOOT -l C

**Comment by HyabusaBadge** [comment]
The PC-98 has an identification code called DA/UA (Device Address/Unit Address), which identifies FDD mode, IDE (SASI), and SCSI.
For the time being, I will omit it on the FDD, but in the actual notation, it includes 0x8n in IDE or SASI, and 0xAn in SCSI. (n is a drive number)
In the implementation of DOSBOX-X, it contains 0xan because it is processed by SCSI BIOS even though it is an IDE emulation.
So DOS can be booted, but Windows NT and OS/2 cannot be booted as it is. (Also, Windows 9x protect mode driver will not work.)
PC-98 has SASI / IDE BIOS and SCSI BIOS separately.

Strictly
0x2n: SCSI HARD DISK BIOS (LBA)
0xAn: SCSI HARD DISK BIOS (CHS)
0x0n: SASI / IDE HARD DISK BIOS (LBA)
0x8n: SASI / IDE HARD DISK BIOS (CHS)
However, I usually use CHS.

The fact that IDE CD-ROM does not work is also related to this.
 PC-98 IDE EMULATION #1085
https://github.com/joncampbell123/dosbox-x/issues/1085

[](url)
