### ISSUE TITLE
Some games require the A20 gate to be disabled or use of LOADFIX

### ISSUE THREAD

**Issue by rubin55** [joncampbell123/dosbox-x#663]
Hi,

Happy DOSBox-X user here. While configuring DOSBox-X for various games I have, I noticed I could not get Lemmings 2: The Tribes to work. I've attached a screenshot of the screen corruption I see after startup. I also verified that the game starts up normally on vanilla DOSBox 0.74 (it does).

![l2_000](https://user-images.githubusercontent.com/6214491/38914077-5ba0f6d4-42de-11e8-8f11-a3ef2f92ae2f.png)

Tested on DOSBox-X 0.82.4 x64, Windows.

I tried full core emulation, setting the type of cpu to 386, but all to no avail.

**Comment by rubin55** [comment]
And LOADFIX.EXE to the rescue...

I should have checked this before creating an issue.. Running LOADFIX before L2-FIX.EXE makes the game work.

**Comment by joncampbell123** [comment]
The idea is to see if the issue can be resolved by turning off the A20 gate.

**Comment by rubin55** [comment]
Yes: the game works without loadfix when setting memsize = 1 and xms = false!

**Comment by joncampbell123** [comment]
A recent commit changed the system so that XMS and EMS by default leave A20 off to help resolve this issue (enabling when needed).
