### ISSUE TITLE
PC-98: Quarth hangs in menu with "8251 warning: RX overrun" in log

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#667]
I don't know if there is anything related with wrong interrupt vectors or with the keyboard controller itself.
@joncampbell123 I'll send you the game's floppy image elsewhere if you need.

Edit: the stub interrupt vector change has no effect on this game.

**Comment by yksoft1** [comment]
Uploaded Quarth.hdm.
https://mega.nz/#!bU0A1K5Z!LrOiykkhM4ZKoiM6TbPmzyWdNx5eT7Z_KfuJBn9FkB4
@joncampbell123 I will remove the link after you download this.

**Comment by joncampbell123** [comment]
@yksoft1 That looks like the same HDI image as your Dragon Slayer HDI.

**Comment by yksoft1** [comment]
I'm sorry. Edited the link.
