### ISSUE TITLE
Re-define "host key" to F11 for Windows to avoid F12 debugger trigger

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#676]
https://github.com/joncampbell123/dosbox-x/commit/e43e64f583925e31ecbf47f07ead368c94c24105

It turns out Windows reserves F12 for a debugging trigger of some kind, so Windows builds will need to use F11 instead.

**Comment by yksoft1** [comment]
It's better to make the host key configurable in dosbox.conf I think.

**Comment by Shane32** [comment]
See: https://msdn.microsoft.com/ko-kr/library/ms646309.aspx
_The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident._

**Comment by joncampbell123** [comment]
I've already made the change for F11 in Windows builds. The host key is always configurable.

Either Windows key is not a good idea because Windows generally likes to use it.
