### ISSUE TITLE
PC-98: About "Epson Protect" in NEC's DOS and some other software

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#682]
Back when Epson made their PC-9801 compatibles, NEC decided to add a copy protection in their MS-DOS and some applications to prevent them from running in non-NEC PC-98 systems. This was called "Epson Protect" or "Epson Check" by PC-98 users as Epson was the only manufacturer of PC-98 compatibles.
Non-modified NEC MS-DOS 3.3 and 5.0 series all had this, but removed in MS-DOS 6.2.
According to https://hayabusa8.5ch.net/test/read.cgi/news/1488133362/ , NEC edition of Windows 2.11 and 3.0 also had such check built in.

Many HDIs distributed contain modified IO.SYS to be compatible with Anex86 (Anex86 emulates those Epson compatibles instead of a genuine NEC PC-98), but original MS-DOS 3.3 and MS-DOS 5.0 disks won't boot in Anex86 and Dosbox-X for this reason. 

Neko Project II had a solution of this in xnp2/bios.c. It's about some certain values in certain memory locations.

**Comment by joncampbell123** [comment]
I have a question then about another bizarre action taken by PC-98 MS-DOS.

I found while developing support for BOOTing MS-DOS that PC-98 MS-DOS will hook BIOS interrupt vector 1Ah, but then call down to 0x19 bytes past the original interrupt vector, right into the middle of the interrupt handler. It will push some segment registers onto the stack as part of it.

I check on real PC-98 hardware, and sure enough, the BIOS handler for INT 1Ah is laid out with the first half in 8 bytes, then a long string of NOPs, then at 0x19 bytes, the rest of the routine.

I had to add it to prevent MS-DOS from crashing in DOSBox-X. It seemed like a really bizarre thing to do to a BIOS software interrupt.

Would that be another anti-Epson trick by NEC?

**Comment by yksoft1** [comment]
Neko Project II has such code:
```
if ((!biosrom) && (!(pccore.model & PCMODEL_EPSON))) {
CopyMemory(mem + 0xe8dd8, neccheck, 0x25);
pos = LOADINTELWORD(itfrom + 2);
CopyMemory(mem + 0xf538e, itfrom + pos, 0x27);
}
```
The second CopyMemory copies a piece of code in Neko Project II's ITF ROM blob to somewhere in memory. I don't know if this one had any relation with the mysterious hook in IO.SYS.

**Comment by joncampbell123** [comment]
The latest commit offers an option to turn on the copyright string at E800:0DD8 in PC-98 mode.

**Comment by yksoft1** [comment]
In recent commits, there is a new "

> The latest commit offers an option to turn on the copyright string at E800:0DD8 in PC-98 mode.

In recent commits, such option could satisfy NEC's Windows 2.1, Windows 3.0 and unpatched MS-DOS 5.00A.
This issue could be closed.
