### ISSUE TITLE
PC-98: Text layer anomalies in Dragon Slayer: Legend of Heroes II

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#683]
Dragon Slayer: Legend of Heroes II is Falcom's RPG released in 1992. It won't start in Dosbox-X's DOS, and if you boot it from HDI, you would see some wrong graphics in text layer.
Vertical lines in overall graphics.
![guest os_000](https://user-images.githubusercontent.com/37106774/39393021-965bdb6c-4aaf-11e8-8e7b-4d7926d6de61.png)
![guest os_001](https://user-images.githubusercontent.com/37106774/39393064-06748598-4ab0-11e8-9bcf-4778cd8b6ae0.png)
![guest os_003](https://user-images.githubusercontent.com/37106774/39393083-4d73aff0-4ab0-11e8-8921-6df614130c66.png)

Masks drawn in text layer displays incorrectly.
![guest os_002](https://user-images.githubusercontent.com/37106774/39393073-32a9fada-4ab0-11e8-9104-6b5923910650.png)
![guest os_005](https://user-images.githubusercontent.com/37106774/39393113-b2ccdd54-4ab0-11e8-9608-e260386c0e8c.png)

The anomalies look very similar to Carat's bug (#345) recently fixed. A fact is that if you first start and exit Carat in Dosbox-X's DOS and imgmount/boot Legend of Heroes II, everything looks correct.

**Comment by joncampbell123** [comment]
The game is probably using bit 4 to signal "Simple Graphics", but unlike Carat, may be using a BIOS call to do it (where Carat just writes to the I/O port directly to trigger it).

**Comment by joncampbell123** [comment]
It's calling INT 18h AH=0A to set text layer parameters, which is not yet implemented in DOSBox-X.

Right away in the log, it's calling INT 18h AX=0A00 to set up a normal text mode, then AX=0A04 to switch on the "simple graphics" interpretation of attribute bit 4.

Carat doesn't use the BIOS, it just writes 0x01 to port 68h to accomplish the same effect.

"Angelus" has the same problem with vertical lines, it seems.

**Comment by yksoft1** [comment]
Resolved this myself in pull request #684.

**Comment by yksoft1** [comment]
I think this issue could be closed at least for now.

**Comment by joncampbell123** [comment]
Looks good, thanks!
