### ISSUE TITLE
Run update-build-timestamp.pl during build?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#686]
I suppose there's a good reason why update-build-timestamp.pl is not run during every build, but for those of us who want to do so, it's easy enough to add a line to the unix-based build scripts.

EDIT: In Visual Studio, this syntax seems to work as a pre-build event:

cd $(SolutionDir)..
perl update-build-timestamp.pl
cd $(SolutionDir)

Probably the third line isn't needed, but I haven't experimented without it.

Is something like this worth adding to the code? Or, as I said, is there a good reason to omit it?

**Comment by joncampbell123** [comment]
The update script rewrites a header file that many parts of the code rely on.

If you did that, any recompile or minor change would require many CPP files to be recompiled for no gain.

**Comment by emendelson** [comment]
OK - I understand. I'll close this.
