### ISSUE TITLE
Enhancement: An option to force PC-98 mode to use IBM US-English key layout as default

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#695]
Some people would prefer to use PC-98 mode with their familiar key layout printed on keyboard. Among other PC-98 emulators, Anex86 defaults to use Windows keyboard layout instead of converting the key codes using PC-98's own keyboard layout.

Use of the mapper is a solution, but at least 18 keys must be remapped if you want US-English layout.

**Comment by joncampbell123** [comment]
That should be an option, yes.

By default, I'm trying to match actual PC-98 hardware, including keyboard layout and handling.

**Comment by joncampbell123** [comment]
Since it is the PC-98 BIOS that produces the ASCII scan codes from the keyboard, that can be added easily.

But do understand that when a game or Windows handles the keyboard by itself, there is nothing I can do to apply a US layout.

**Comment by joncampbell123** [comment]
@yksoft1 your patch has been applied, so this is finished as far as I know.
