### ISSUE TITLE
Compressed audio tracks in DOSBox-X

### ISSUE THREAD

**Issue by Maxim-1982** [joncampbell123/dosbox-x#698]
Please add support for CD images cue + bin along with ogg / flac tracks.

**Comment by joncampbell123** [comment]
That is a good idea.

That will require some work to add libogg, libvorbis, and libflac library dependencies, and to make them optional. I have written code against those libraries before so there is some familiarity.

I understand there is also an extension to cue + bin for MP3 as well, correct?

**Comment by Maxim-1982** [comment]
> "I understand there is also an extension to cue + bin for MP3 as well, correct?"

Yes, but MP3 has poor quality. OGG is better. Flac is excellent.

**Comment by sikthehedgehog** [comment]
Eh, from empirical testing, MP3 requires about twice as much data as Vorbis to get more or less the same quality. So Vorbis is preferable but using MP3 is not entirely catastrophic if you're willing to take the space usage hit.

The biggest issue with MP3 has been historically the patents. The MP3 patents expired last year though\*, so that's not much of an issue anymore.

*\* Kind of, I think a couple of encoding patents in non-US countries still remain. But not anywhere as big a deal as before and shouldn't be a problem for this case anyway.*

**Comment by joncampbell123** [comment]
I'll hold off on the MP3 version then until someone has a CUE+BIN setup that uses it.

Are there any CUE+BIN setups using the Opus codec? I've heard it's a great improvement over Vorbis and I've been meaning to play with the official Xiph library for it.

**Comment by yksoft1** [comment]
Why not start from porting Dosbox SVN's AudioFile class (the original one use SDL_sound)?

**Comment by joncampbell123** [comment]
Eh... my professional work involves multimedia files. I can probably do a better implementation than that. I've written code to handle WAV files and libogg/libvorbis before.

**Comment by Maxim-1982** [comment]
Offtopic:
Why does DOSBox-X turn off "Num Lock" at startup?

**Comment by joncampbell123** [comment]
@Maxim-1982 This is Windows, right?

There is code to synchronize num/caps/scroll lock LEDs to the guest, though it is disabled by default. It can be enabled in dosbox.conf.

**Comment by Maxim-1982** [comment]
> @Maxim-1982 This is Windows, right?

Yes.

> There is code to synchronize num/caps/scroll lock LEDs to the guest, though it is disabled by default. It can be enabled in dosbox.conf.

"keyboard hook=true" does not work for me. :(

**Comment by Maxim-1982** [comment]
What am I doing wrong?
Where is it better to ask such questions?

**Comment by joncampbell123** [comment]
When the keyboard hook is enabled, and you capture the mouse, DOSBox-X will change the num/caps/scroll lock LEDs to match the guest.

**Comment by Maxim-1982** [comment]
"keyboard hook=true" and capture the mouse, DOSBox-X turn off the num/caps/scroll lock LEDs at startup.
"keyboard hook=false" and capture the mouse, DOSBox-X all the same turn off the num/caps/scroll lock LEDs at startup.
The original DOSBox-0.74 does not turn off num / caps / scroll lock LEDs.

How to enable "Num Lock" from the "guest"?

**Comment by heydojo** [comment]
> That will require some work to add libogg, libvorbis, and libflac library dependencies, and to make them optional. I have written code against those libraries before so there is some familiarity.

@joncampbell123 allowing the user to pipe the wave output out to ffmpeg or [sox](http://sox.sourceforge.net/) might be much simpler to implement and would remove the need to pull in the dependencies you mention.

**Comment by yksoft1** [comment]
@heydojo This would be impossible to implement for some supported systems (for example, HX DOS Extender is a single-tasking environment with no support for processes). Also, on Windows there might be situations when the OS doesn't provide Vorbis decoding support by default (Windows 7).

**Comment by joncampbell123** [comment]
@yksoft1 @heydojo Correct. I actually find it easier to play within the DOSBox-X project and link in the correct libraries. I've written code to deal with WAV, MP3, and OGG Vorbis before so it's not difficult for me to do. I can implement it first on Linux and then figure out how to compile the right libraries in the Windows builds.

**Comment by yksoft1** [comment]
By the way, a few days ago I've hacked DosBox SVN SDL_sound support back into my DosBox-X fork for playing a particular game in ISO+OGG format and it seemed to work with some tinkering under MinGW.

**Comment by yksoft1** [comment]
@heydojo I mean that HX DOS Extender does not support piping and any forms of Win32 interprocess communication at all.
And I don't think anybody will install system-wide FFmpeg binaries on Windows at all. Windows had its own media frameworks that always available. Only implement ISO+MP3/OGG/etc emulation using a pipe to FFmpeg or sox will make Windows users disappointed.

**Comment by joncampbell123** [comment]
The easiest way to do this is to compile the libraries into the DOSBox executable so that everything is there ready to work.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Is here any update about the compressed audio feature?

**Comment by joncampbell123** [comment]
My focus right now is on test programs to ensure accuracy against real hardware.

If anyone else wants to add compressed audio track support, patches are welcome.

**Comment by Wengier** [comment]
I have already added it to DOSBox-X in my pull request #1639.
