### ISSUE TITLE
Installing WIN95 in MAC High Sierra 10.13.4, the cursor disappeared when set screen depth

### ISSUE THREAD

**Issue by kryxus** [joncampbell123/dosbox-x#706]
When I set the screen bit depth to anything over 8-bit (256 colors). 16-bit and 32-bit are broken and cause visual glitches. And cannot see the cursor.

**Comment by joncampbell123** [comment]
The alternate renderer for 16/24/32bpp needed for Mac OS X omits the cursor overlay at this time.

**Comment by kryxus** [comment]
is there any workaround to solve this issue? Thanks for your good work on dosbox.
