### ISSUE TITLE
Mac OS X: "Always on top" should be re-added to the menu, and follow VLC player's example

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#709]
Either find the API function to enable "always on top", or remove the menu item on Mac OS X.

**Comment by joncampbell123** [comment]
Removed the menu item

**Comment by john-at-charpa** [comment]
Jon,

I noticed this commit this morning and I thought I might mention that VLC on macOS 
can do 'always on top'. That project uses SDL too I think. I'm not sure this is of much
help, but they've had it implemented for some time.

http://git.videolan.org/?p=vlc.git;a=commitdiff;h=92b23685102224ea82635459905d261a0ba0e00c

**Comment by joncampbell123** [comment]
Thanks, I'll see if I can get it to work when I get back on the Mac Mini at the office.

**Comment by joncampbell123** [comment]
On a related note, here's how "Always on Top" can be implemented in Linux/X11:

https://stackoverflow.com/questions/4345224/x11-xlib-window-always-on-top#16235920

**Comment by joncampbell123** [comment]
Done
