### ISSUE TITLE
E_Exit: Unsupported key press

### ISSUE THREAD

**Issue by skerit** [joncampbell123/dosbox-x#710]
When pressing a key that is not supported, the default behaviour in Dosbox-x is to exit the application. This is quite frustrating as I tend to press them from time to time, forgetting they don't work :/

**Comment by heydojo** [comment]
https://github.com/joncampbell123/dosbox-x/blob/master/src/hardware/keyboard.cpp#L952

**Comment by joncampbell123** [comment]
@heydojo DOSBox's source code used to be full of that kind of thing. A long time ago DOSBox used to E_Exit() if the DOS game happened to put the PIC into one of the special modes or any mode it didn't support.

**Comment by joncampbell123** [comment]
Please try the latest commit
