### ISSUE TITLE
Win32 build not excutable / 32bit windows

### ISSUE THREAD

**Issue by nemo838** [joncampbell123/dosbox-x#714]
win32 빌드가 32비트 윈도우즈에서 실행이 안됩니다.
mingw 와 mingw-lowend는 문제없이 실행되지만
output 이 direct3d를 지원하지 않는 것 같습니다.
이 문제를 해결할 방법이 있습니까?
-------------------------------------------------------------
The win32 build can not run on 32-bit Windows.
mingw and mingw-lowend will run fine
It seems that output does not support direct3d.
Is there a way to solve this problem?
-------------------------------------------------------------
Translated by Google Translator

**Comment by joncampbell123** [comment]
It seems the Direct3D output has issues on anything lower than about Windows 7. I'm not sure why, since that code was brought in a long time ago from Daum's branch. However because it was compiled with VS2017 it will not run on anything lower than Windows Vista.

The MinGW builds work fine because they do not support Direct3D and they can run on XP and lower.

**Comment by nemo838** [comment]
output=opengl일때 aspect=false 옵션이 제대로 작동하지 않는데,
이게 제대로 작동하면 굳이 output=Direct3D 옵션이 필요하지 않을 것 같기도 합니다.

When output = opengl the aspect = false option is not working properly,
If this works properly, you probably do not need the output = Direct3D option.

**Comment by nemo838** [comment]
제가 이때까지 사용해왔던 그 기능은
aspect=true  일때 창의 비율이 4:3으로 고정되었었고,
aspect=false 일땐 게임의 원래 화면비로 자동으로 고정이 되었었는데
dosbox-x는 조금 다르게 작동을 하나보군요.
그렇다면 output=opengl로 설정했을 경우에 무조건 4:3으로 고정이 되는데,
오리지널 dosbox처럼 원래 화면비로 고정시키려면 어떻게 해야 하나요?

**Comment by joncampbell123** [comment]
Check that the display fills the window entirely when you resize with aspect=false.

You can switch back to the original aspect ratio by selecting "Reset window size"

**Comment by nemo838** [comment]
output=direct3d → original ratio
output=opengl → 4:3 ratio
both aspect=false

what's wrong?
give me solution please.
i can't understand why dosbox-x working like that.

see this video.
https://youtu.be/tREA1QRYHgM

**Comment by joncampbell123** [comment]
Can you compile DOSBox-X from source? I've made a lot of fixes and adjustments since 0.8.25 and in the latest commit, I'm not seeing the issue at all. output=opengl and aspect=false on the latest 0.8.27 code is working fine.

**Comment by nemo838** [comment]
i don't know how to complie it.

**Comment by joncampbell123** [comment]
@nemo838 Please try the latest 0.8.26 release and let me know if that happens on your system.

**Comment by nemo838** [comment]
0.8.26 , WIP BETA 2018-05-06 17:54
nothing different with 0.8.25

**Comment by joncampbell123** [comment]
Based on the YouTube video, this is Windows 7, correct?

**Comment by nemo838** [comment]
Windows 7 Professional
build 7601: Service pack 1
VGA: redeon hd5830
cpu: i3 sandybridge

**Comment by joncampbell123** [comment]
I just tried the latest commit against Windows 7.

output=opengl and aspect=false seems to work fine.

**Comment by heydojo** [comment]
Here; try:

```
[sdl]
pixelshader=AdvancedAA.fx
fulldouble=false
fullresolution=desktop
windowresolution=original
output=direct3d
autolock=false
overscan=0

[dosbox]
dpi aware=false

[render]
frameskip=0
aspect=false
char9=true
doublescan=false
scaler=hardware3x
autofit=true
```

Hope this helps.

**Comment by nemo838** [comment]
thank you guys.
finally i find the solution in your answers.
i said dosbox-x working different with other dosbox when set output=opengl
and i hoped change dosbox-x to work same as other dosbox.
But I was stupid.
It is valuable because it working different.
If it works differently, I can use it.

**Comment by nemo838** [comment]
Finally i found the way to use that option.

see this video.
https://youtu.be/_eDpOxWbnL0

first run = dosbox 0.74 daum SVN lastest build (output=direct3d/aspect=true)
second run = dosbox-x 82.5 (output=opengl/aspect=true)
third run = dosbox-x 82.5 (output-opengl/aspect=false)

The front end that I use in the video is made by me. (DGLauncher)

**Comment by joncampbell123** [comment]
@heydojo Regarding the Windows DPI awareness, the compiled EXE is not marked as being DPI aware, but a Win32 call is made at startup to disable the high DPI "upscaling" to improve the DOSBox-X output quality.

@nemo838 Happy to see a solution to the issue!

I will close this issue in 24 hours unless there is anything else that needs to be addressed.
