### ISSUE TITLE
Incorporate XBRZ scaler into DOSBox-X

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#716]
There has been an xBRZ scaler option in the menu since importing changes from Daum awhile back, but it does nothing at the moment and selecting does nothing.

xBRZ is apparently a popular scaler library: https://sourceforge.net/projects/xbrz/

So, incorporate that library into DOSBox-X to make the menu option valid.

**Comment by Maxim-1982** [comment]
I think this will be a useful option.

**Comment by GhoulUnlimited** [comment]
Hopefully it will be done

**Comment by joncampbell123** [comment]
Thought so.

The option has been sitting there doing nothing since it appeared from Daum's branch, it's time for it to do something.

**Comment by alexat** [comment]
Well, first of all just for people wanting better image. "5xBR-v3.8c.fx forced" is a good scaler mode to use for 1920x1080/1920x1200 screens.

**Comment by alexat** [comment]
Next, I've prepared a patch (sorry, not against GIT itself but just separate one against latest rev) to incorporate xBRZ scaler into DOSBox-X. Portions from Daum, most of the code directly taken from https://sourceforge.net/projects/xbrz , some code written to extend it with tunables. 

This one basically adds few scaler types: xbrz and xbrz_bilinear. The former is using nearest neighbor scaling after xbrz, and the latter is using bilinear scaling. The former looks coarse, and the latter is slower but looks... well, text modes are totally gorgeous with it, gfx in games is comparable.

xBRZ patch requires DirectX SDK.

The scaler is *VERY* CPU-intensive. There is one tunable I added ('xbrz slice'), but seems like changing it from default mostly does nothing good. On my Ryzen 1800X, 32-bit builds are totally bad and 64-bit builds with SSE2 or AVX/AVX2 run fine except for heavy games that update all the screen at once too often (like Tyrian, and with frameskip or lowering 'quality' in the game it's still ok). But it indeed looks better than any D3D shader available.

[dosbox-x-xbrz.zip](https://github.com/joncampbell123/dosbox-x/files/2051186/dosbox-x-xbrz.zip)

**Comment by alexat** [comment]
While I may eventually find some time to convert it to pull request, this is better applied by hand and then checked for dependencies. VC2015 project files are a mess and I don't want to make pull for these :)

**Comment by aybe** [comment]
I tried to merge this patch with SourceTree but it fails on modified files, saying that it can't find one of the other (b file) for modified files:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false apply -v --reject -p 0 "D:\Downloads\dosbox-x-xbrz (1)\dosbox-x-xbrz.patch"
D:/Downloads/dosbox-x-xbrz (1)/dosbox-x-xbrz.patch:105: trailing whitespace.
            if (sdl.desktop.full.fixed || sdl.xBRZ) 
D:/Downloads/dosbox-x-xbrz (1)/dosbox-x-xbrz.patch:184: trailing whitespace.
                    const int outputWidth = sdl.surface->w; 
D:/Downloads/dosbox-x-xbrz (1)/dosbox-x-xbrz.patch:301: trailing whitespace.
                        } 
D:/Downloads/dosbox-x-xbrz (1)/dosbox-x-xbrz.patch:329: trailing whitespace.
            else 
D:/Downloads/dosbox-x-xbrz (1)/dosbox-x-xbrz.patch:432: trailing whitespace.
===========
Checking patch b/src/dosbox.cpp...
error: b/src/dosbox.cpp: No such file or directory
Checking patch b/src/gui/render.cpp...
error: b/src/gui/render.cpp: No such file or directory
Checking patch b/src/gui/sdlmain.cpp...
error: b/src/gui/sdlmain.cpp: No such file or directory
Checking patch b/src/xBRZ/Changelog.txt...
Checking patch b/src/xBRZ/License.txt...
Checking patch b/src/xBRZ/xbrz.cpp...
Checking patch b/src/xBRZ/xbrz.h...
Checking patch b/src/xBRZ/xbrz_config.h...
Checking patch b/src/xBRZ/xbrz_tools.h...
Applied patch b/src/xBRZ/Changelog.txt cleanly.
Applied patch b/src/xBRZ/License.txt cleanly.
Applied patch b/src/xBRZ/xbrz.cpp cleanly.
Applied patch b/src/xBRZ/xbrz.h cleanly.
Applied patch b/src/xBRZ/xbrz_config.h cleanly.
Applied patch b/src/xBRZ/xbrz_tools.h cleanly.
```

I really would like not to have to manually copy/paste and un-plus each of the lines, any ideas are welcome, if it ain't possible then i'll do it that way !

**Comment by joncampbell123** [comment]
I suggest locating the specific commit the patch was written against, applying it, then looking at the differences from then to now. That could help.

**Comment by alexat** [comment]
Hello :)
Please try the patch uploaded in this post (removed a/ and b/ from file names).
[dosbox-x-xbrz.zip](https://github.com/joncampbell123/dosbox-x/files/2063483/dosbox-x-xbrz.zip)

**Comment by alexat** [comment]
Patch was done against commit 69d1d250

**Comment by alexat** [comment]
Pull request #746 created

**Comment by aybe** [comment]
You have been faster than me, was just finished it actually 🥇 

Thanks !

**Comment by aybe** [comment]
The discussion continues at https://github.com/joncampbell123/dosbox-x/pull/793.
