### ISSUE TITLE
Enhancement: Add a new build target to use SDL drawn menus in Windows

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#717]
I think in long term Dosbox-X should use a unified UI for all supported platforms, like QEMU or ZSNES did.
Currently I can confirm that except under OpenGL output (glGenTextures for SDLDrawGenFontTexture is not working), almost everything in SDL drawn menus worked well.

**Comment by joncampbell123** [comment]
It already has a unified UI... mostly.

The whole point of the new C++ menu system is to allow the creation of menu items, lay them out, and then either draw them directly or place them into the menu framework provided by the host operating system.

On Windows that means creating a menu resource and attaching it to the window.

On Mac OS X that means constructing an NSMenu and directing the NSApplication to use it.

On anything else, that means drawing and taking mouse input for menus directly without using the host OS's resources.

The GUI dialog boxes are already platform independent, and drawn by the C++ classes in gui_tk.cpp. They work on all platforms, even if they don't have very good performance.

I'll have to examine what's wrong with OpenGL on Windows/MinGW. It's possible the Windows OpenGL implementation doesn't like the texture parameters I'm asking of it.

**Comment by joncampbell123** [comment]
Actually, you said glGenTextures() is not working, which means it's a failure before the texture format is even defined.

My code initializes the value to ~0UL so I wonder if it's something silly in Windows's implementation that requires the value to be zero before it will generate the texture ID.

**Comment by joncampbell123** [comment]
I just fixed it. Some code farther up triggers an error code that is retained by OpenGL and mistaken as a glGenTextures() error code further down. Try the latest commit.

There is a new build script and configure.ac flag to force the SDL drawn menus in Windows and MinGW.

**Comment by joncampbell123** [comment]
Now there is a ./build-mingw-sdldraw script.

The OpenGL font texture bug is fixed.

Enjoy.
