### ISSUE TITLE
Documented setMainMenu method

### ISSUE THREAD

**Issue by mdeletrain** [joncampbell123/dosbox-x#718]
https://github.com/joncampbell123/dosbox-x/blob/22355a4ddd47a90f559f16eda77240b9b2cd1f9c/src/gui/menu_osx.mm#L63

Hi, just throwing my two cents, this is by convention : ObjC properties, unless otherwise specified, are accessed by their name and set by a method named setCapitalizedPropertyName

In SDLMain.m you use `[NSApp mainMenu]` to get the menu, you need to use `[NSApp setMainMenu:yourOtherMenu]` to set it.

Related documentation : https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/EncapsulatingData/EncapsulatingData.html

**Comment by joncampbell123** [comment]
I get that *now* thanks :)

That's a consequence of never having written Objective C++ before.

I'll go clean up my unnecessary profanity now.

**Comment by mdeletrain** [comment]
By the way, I'm looking at how to make dosbox-x compile on MacOS-X with SDL2, do you have any related information to give me ?

**Comment by joncampbell123** [comment]
I would try the ./build-debug-sdl2 script.

However I've never compiled DOSBox-X like that before on Mac OS X so I cannot guarantee that it will work.
