### ISSUE TITLE
PC-98: double-byte characters don't appear in some games

### ISSUE THREAD

**Issue by hihihirokane** [joncampbell123/dosbox-x#720]
Thank you for great works.
I have tested some games. Double-wide characters in text don't appear in some games such as EVE: burst error while single-wide characters do. The following screen shows what characters lack. I think It should be "[E]ve [B]urst [E]rror [N]o.1 [M]ain(Noon) for [W]oman" (brackets are for emphasis).
<img border="0" height="268" src="https://2.bp.blogspot.com/-QnCx_m4p6Qc/Wv2uXHPn4UI/AAAAAAAAJus/m2Mu4JSXqAYofVHT-D9ADd3weGU426WQgCPcBGAYYCw/s1600/Screen%2BShot%2B2018-05-18%2Bat%2B1.08.05.png" width="377" />
Neko Project II works like that:
<img border="0" src="https://3.bp.blogspot.com/-uHpPrvkoXIM/Wv2yEbPrIjI/AAAAAAAAJu0/oSbbwQopKR89OfBh8vjicsS7EdTeVLwMgCLcBGAs/s1600/Screen%2BShot%2B2018-05-18%2Bat%2B1.09.19.png" width="336" height="237" />

I think log is around here, because this screen is for playing music and opend eve_01.M in the log is a music file. I hope it help.
> LOG: PC-98 INT DCh unknown call AX=0000 BX=0000 CX=0012 DX=0000 SI=0000 DI=0000 DS=0000 ES=0000
> LOG:   76881919       FILES:file open command 0 file m.cc
> LOG:   76882473 DEBUG MISC:DOS_ResizeMemory(seg=0x100a) blocks=0x3240
> LOG:   76882740 DEBUG MISC:DOS_ResizeMemory(seg=0x100a) blocks=0x3200
> LOG:   76883134 DEBUG MISC:DOS_ResizeMemory(seg=0x100a) blocks=0x3480
> LOG:   76884556 DEBUG MISC:DOS_ResizeMemory(seg=0x100a) blocks=0x3500
> LOG:   76884949 DEBUG MISC:DOS_ResizeMemory(seg=0x100a) blocks=0x3540
> LOG:   76967219 DEBUG MISC:DOS_ResizeMemory(seg=0x100a) blocks=0x3500
> LOG: PC-98 INT DCh unknown call AX=0000 BX=09A6 CX=0012 DX=3301 SI=0F14 DI=2187 DS=0E54 ES=2187
> LOG:   77034340       FILES:file open command 0 file eve_01.M
> LOG:   77319538 WARN  IOCTL:ANSI SEQUENCES USED
> LOG: PC-98 INT DCh unknown call AX=0000 BX=09A6 CX=0012 DX=3301 SI=0F14 DI=2187 DS=0E54 ES=2187

**Comment by joncampbell123** [comment]
It depends on what byte characters are in video RAM prior to each letter.

Awhile back, there was a similar bug where the 2nd level of TH02 was displaying the level name with the first letter missing.

Based on tinking with real PC-98 hardware, there seem to be inconsistent rules on how to handle double-wide characters and whether the adjacent 16-bit value in text RAM is ignored or not.

**Comment by joncampbell123** [comment]
If the debugger is available, bring it up at that point in the game, and point the memory window at A000:0000 to see exactly what 16-bit WORDs are written to text RAM. You should be able to scroll down and see where the text is.

**Comment by joncampbell123** [comment]
Perhaps to better understand these rules, I should sit down and write another DOSLIB toy under hw/necpc98 to allow poking 16-bit wide kanji into text RAM to determine exactly what these overlap rules are on actual PC-98 hardware.

**Comment by joncampbell123** [comment]
I just noticed as well the game didn't turn off the function key row. Either the unknown ANSI code is supposed to do that, or the unknown INT DCh call.

**Comment by joncampbell123** [comment]
DOSLIB toy (text painting program) in progress now:

https://github.com/joncampbell123/doslib/blob/master/hw/necpc98/tpaint.c

**Comment by hihihirokane** [comment]
How do I use the debugger? alt-F12 key (or any other possible configuration with the mapper) gets dosbox-x freezed after it left the following messages:
> LOG:   82291310 DEBUG MISC:DEBUG_SetupConsole initializing GUI
> LOG:   82291310 DEBUG MISC:DEBUG GUI startup

**Comment by joncampbell123** [comment]
The debugger is accessible through Alt+Pause.

I'm not sure if that works on Mac OS X, but there the menu bar should also have a Debugger command if you compiled it as SDL 1.x.

**Comment by joncampbell123** [comment]
Notes:

- Eve burst error fails to remove function key row at startup
- Several unknown calls to INT DCh. Perhaps one of those calls is responsible for turning off the function key row.
- The text display at the start is using ANSI codes to display text (which is apparently none right now) as well as the down arrow.
- It's using ANSI attribute 5 (blink) which DOSBox does not yet support. The blink attribute is for the arrow.
- My copy doesn't display any text at all. It only prints the arrow.

**Comment by joncampbell123** [comment]
More notes:
- Stepping through INT DCh of an MS-DOS bootdisk, CL selects the major function, and then AH selects a minor function.
- INT DCh CL=0x10 AH=0x00 appears to take the contents of DL and print it on the screen
- The sequence of DL spells out **\<ESC\>** [>5h which is the proprietary ANSI code on PC-98 DOS to turn off the function key row.

**Comment by joncampbell123** [comment]
I found the music room. The text in question is drawn on the graphics layer, so it has nothing to do with double-wide characters on the text layer. So for some reason, the game can't get font bitmaps for anything beyond plain ASCII.

**Comment by joncampbell123** [comment]
Hey, it just occurred to me what might be wrong.

I was checking through the PC-98 section of Hackipedia and an article mentioned the character generator ROM I/O and memory-mapped I/O.

I know of the I/O ports A1h-A9h odd to read character generator ROM, but I also remember single-stepping through the ROM BIOS of an actual PC-9821 laptop and discovering that it uses REP MOVSW to write to A4000-A400xx instead.

I checked the EVE game mentioned in this issue, and it indeed seems that EVE is reading from A4000-A401F instead of from the I/O ports.

I may be able to get the text to display after all.

**Comment by joncampbell123** [comment]
Yup!

![ags_000](https://user-images.githubusercontent.com/6245486/47231341-77dcc880-d381-11e8-85f7-6c90f79351e4.png)

**Comment by joncampbell123** [comment]
I will close this issue in one day.

Feel free to list any other games where the latest commit allows the text to appear.

**Comment by hihihirokane** [comment]
Outstanding work!
As of ver 0.82.6, at least 5 games by C's Ware had the same situation as Eve burst error.

**Comment by joncampbell123** [comment]
Excellent.

The only concern left is to test how the A4000-A5FFF range is handled on real hardware.

I doubt that only A4000-A401F would decode to the CG.

I vaguely recall once using DEBUG to print out the A4000-A5FFF range and seeing a repeating pattern, so it's possible that the entire range maps to the CG.

I will pull out some PC-98 hardware tonight to see if I'm right and commit a change based on the results.

**Comment by joncampbell123** [comment]
Just for reference, on the original IBM PC (the one from the early 1980s), the PIC, DMA, and other I/O ports defined cover a lot more than the official range.

The PIC at 20h-21h on original IBM PC hardware has alias ports all the way from 22h to 3Fh for example.

It makes sense that PC-98 might have the same thing with A4000-A5FFF and only the low 5 bits are actually used.

**Comment by hihihirokane** [comment]
[The latest commit](https://github.com/joncampbell123/dosbox-x/tree/a16dff8f1c02ac564cb037387e895b08cc87a296) allows the text of the following games to appear while v0.82.6 didn't:
Kindan no Ketsuzoku (1993),
Etsuraku no Gakuen (1994),
Desire (1994),
Xenon (1994), and
EVE Burst Error (1995).

**Comment by hihihirokane** [comment]
Besides 5 games above, ver 0.82.10 solved missing text in Amy to Yobanaide (エイミーと呼ばないでっ) (1995) by C's Ware as well.

**Comment by joncampbell123** [comment]
Good!

I just pulled out the PC-9821 laptop I use for testing, and it turns out the character generator responds to memory region A4000-A4FFF instead of just A4000-A401F.

![img_20181108_222717770](https://user-images.githubusercontent.com/6245486/48246983-68f89d00-e3a6-11e8-9e4b-7c400f0c7f5c.jpg)
