### ISSUE TITLE
get_item() No such item 'mapper_capmouse' when going fullscreen.

### ISSUE THREAD

**Issue by bckpkol** [joncampbell123/dosbox-x#721]
X11 surface backend, fullscreen.
`LOG: Early LOG Init complete
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 0.82.7
LOG: Current X11 keyboard layout (full name) is: 'English (US)'
LOG: Current X11 keyboard layout (token) is: 'us'
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: E_Exit: DOSBoxMenu::get_item() No such item 'mapper_capmouse'
E_Exit: DOSBoxMenu::get_item() No such item 'mapper_capmouse'`

Also, because of SDL2, fbcon is not working, but it's off topic.
Compiler is clang 6.0, OS is Armbian Stretch. At default settings it works okay.

**Comment by joncampbell123** [comment]
Is this going fullscreen at startup or triggering the fullscreen shortcut during emulation?

The "capmouse" mapper shortcut is registered fairly early, so if the menu item was never registered that's a bug that needs to be fixed.

This is compilg on Linux/X11 with SDL2, correct?

**Comment by joncampbell123** [comment]
Try the latest commit, compile it, and see if it still happens.

**Comment by joncampbell123** [comment]
My latest changes move the creation of that menu/mapper item up to the point that it should not happen anymore. Can you confirm?

I will close this in 24 hours if no response.
