### ISSUE TITLE
Disabling BIOS startup screen

### ISSUE THREAD

**Issue by Arcnor** [joncampbell123/dosbox-x#722]
This is more a question than a real bug/feature request (unless what I want is not supported, obviously 😃) but I haven't found any forum or community for this project, so apologies in advance.

I'm trying to use DosBox-X to run a compiler farm for old MS-DOS compilers, but currently, the startup banner takes much of the time to start the compilation, so I was wondering if there is some flag to disable said startup banner somewhere.

Thanks in advance.

**Comment by joncampbell123** [comment]
How about a command line switch to skip the 1-second pause instead?

**Comment by joncampbell123** [comment]
I just added the --fastbioslogo command line option. See if that helps.

**Comment by Arcnor** [comment]
Oh wow, you're fast! Thanks, will try and let you know, although it probably just works as you described :)

**Comment by Arcnor** [comment]
Cool, so the switch works.

Unrelated, but to compile on OSX I had to change the scripts to add the `CoreFoundation` and `CoreServices` frameworks (I'm on Sierra, maybe that's needed there?).

I'm also getting a new menu (with `Main`, `Cpu`, etc) inside the DosBox window which doesn't work as expected, it flickers a lot and I cannot select anything, and even sometimes things get selected by themselves, so I cannot really type anything. I'm guessing that menu should be on the OSX menubar?

In any case, thanks, I think this can be closed now 😄
