### ISSUE TITLE
PC-98: NEC Windows 2.1 and 3.0 use many unimplemented EGC ROPs

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#723]
I managed to boot Microsoft Windows 2.11 and 3.0 from NEC after booting from an MS-DOS 3.3 HDI with their "Epson protect" removed. However, their graphics look erroneous.
![winx-1](https://user-images.githubusercontent.com/37106774/40243702-75430f70-5ab0-11e8-8165-d01b7d58845f.png)
![winx-2](https://user-images.githubusercontent.com/37106774/40243711-77ff507a-5ab0-11e8-89e9-d7a804bd3cbd.png)
I found a lot of EGC unimplemented ROPs warnings in log.
The most frequent unimplemented ROPs are 0xAA, 0x0, 0x3C, 0xF and 0x66.

**Comment by joncampbell123** [comment]
Nice! Does the mouse work?

**Comment by yksoft1** [comment]
The mouse did work, but I almost have to always triple-click to achieve double-click in spite of DosBox-X is not using 100% of its host cpu core.

**Comment by joncampbell123** [comment]
These ROPs have been implemented, Windows 2.x and 3.x appear correctly now.
