### ISSUE TITLE
PC-98: Some SystemSoft games complain "Not enough memory"

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#724]
![ssys1](https://user-images.githubusercontent.com/37106774/40265675-39d03cfc-5b2c-11e8-8308-767ac6fae61e.png)
![ssys2](https://user-images.githubusercontent.com/37106774/40265676-3a28982a-5b2c-11e8-8b70-75c9c95aaaaf.png)
![ssys3](https://user-images.githubusercontent.com/37106774/40265677-3ac9dc62-5b2c-11e8-860c-7383122ba642.png)
Those games seems not detecting conventional memory size in Dosbox-X at all.

**Comment by joncampbell123** [comment]
So then it's using a memory detection routine that isn't yet emulated by DOSBox.

Obviously it's not using MS-DOS to do it, so it must be yet another byte in the BIOS data area.

**Comment by joncampbell123** [comment]
It acts the same way whether you boot from the disk image, or copy it to a folder and run it.

**Comment by joncampbell123** [comment]
Ah, it's reading the NVRAM for memory size:

    0306:00000100 8CC8                mov  ax,cs
    0306:00000102 B304                mov  bl,04
    0306:00000104 1E                  push ds
    0306:00000105 B800A3              mov  ax,A300
    0306:00000108 8ED8                mov  ds,ax
    0306:0000010A BEEA0F              mov  si,0FEA
    0306:0000010D 8A04                mov  al,[si]                ds:[0100]=C88C
    0306:0000010F 1F                  pop  ds
    0306:00000110 3AC3                cmp  al,bl
    0306:00000112 731B                jnc  0000012F ($+1b)        (down)
    0306:00000114 BABF01              mov  dx,01BF

**Comment by joncampbell123** [comment]
Try the latest commit.

![dosbox_000 avi](https://user-images.githubusercontent.com/6245486/40266331-37b5e36e-5afe-11e8-9ea6-b0fc47050fbf.gif)

**Comment by yksoft1** [comment]
Seems this had been fixed. You may close this.
