### ISSUE TITLE
showmenu=false causes E_exit error on startup

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#725]
With current code, showmenu=false in dosbox.conf causes an E_exit error message:

DOSBoxMenu::get _item() No such item 'mapper_togmenu'

**Comment by joncampbell123** [comment]
Pull the latest commit, compile, and see if it happens again.

**Comment by emendelson** [comment]
Excellent. Thank you. I'll close this, but will point out this (I don't know if it's relevant):

If I start with showmenu=false and then enter at the command prompt

config -set "showmenu=true"

then showmenu is set to true, but the menu isn't shown. But maybe that's working by design?
