### ISSUE TITLE
SDL drawn menus had problems with Direct3D 9 output

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#726]
After fiddling with D3D shader support, Direct3D 9 output is finally working in my MinGW environment. However, though not crashing Dosbox-X, the SDL drawn menus had problems under it.
1. The guest screen overlaps with the root menu.
2. The guest screen is not shown correctly when using the menu.

![dxsm1](https://user-images.githubusercontent.com/37106774/40275822-1243c4c4-5bea-11e8-8626-4389adbde1c7.png)
![dxsm2](https://user-images.githubusercontent.com/37106774/40275823-166143e2-5bea-11e8-9a67-944e8abd22df.png)

**Comment by joncampbell123** [comment]
So the proper fix is to make the menus unavailable if output=direct3d.

**Comment by joncampbell123** [comment]
output=direct3d crashing with MinGW was caused by looking up the "pixelshader" property, which did not exist without enabling Direct3D pixel shaders. My latest commits fix that.

**Comment by yksoft1** [comment]
However the menu itself works well.

**Comment by yksoft1** [comment]
Seems the behavior of SDL menu is now identical on D3D9 and OpenGL. You may close this now.
