### ISSUE TITLE
dos_files.obj : error LNK2001: unresolved external symbol __nhandle

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#735]
When using the original line,

https://github.com/joncampbell123/dosbox-x/blob/1ec50211a2ba4a8b1b7dac46e812d0760b018f96/src/dos/dos_network2.h#L109

the CMake build fails:

```
1>dos_files.obj : error LNK2001: unresolved external symbol __nhandle
```

If I fix it in this way, as can be seen on other parts of the code:

```
#ifdef __cplusplus
extern "C" {
#endif
	int _nhandle;
#ifdef __cplusplus
}
#endif
```

the CMake build now builds, but the ```vs2015``` solution now fails to build:

```
4>libucrtd.lib(ioinit.obj) : error LNK2005: __nhandle already defined in dos_files.obj
4>C:\Dev\dosbox-x\vs2015\..\bin\Win32\Debug SDL2\/dosbox-x.exe : fatal error LNK1169: one or more multiply defined symbols found
```

For sure this must be a trivial thing to fix but I couldn't figure it out...

Anyone, help ?

Thanks !

**Comment by joncampbell123** [comment]
Ew... well, see if wrapping it with an #ifdef defined(_MSC_VER) works to enable/disable that line of code when compiled with Visual Studio.

**Comment by aybe** [comment]
Fixed https://github.com/joncampbell123/dosbox-x/blob/develop/src/dos/dos_network2.h#L109

**Comment by ChrisNonyminus** [comment]
The issue is back for me.
