### ISSUE TITLE
Neither the vs2017 or the CMake build do run properly

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#736]
Both equally fails in the same way, needs to investigate that, the error is triggered only when specific menu items are hovered by the mouse.

![2018-05-24 05_19_02-dosbox-x 0 82 1 3000 cyc_ms dosbox](https://user-images.githubusercontent.com/1537591/40463182-fbb815ac-5f13-11e8-8515-c8b6cbd2bb47.png)

![2018-05-24 05_19_15-dosbox-x 0 82 7 3000 cyc_ms dosbox](https://user-images.githubusercontent.com/1537591/40463185-fd297e58-5f13-11e8-81bf-e4d27fc75040.png)

**Comment by aybe** [comment]
The error appears at https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/sdlmain.cpp#L4550, IIRC modifying a vector while iterating it invalidates it ?

It does happens only on SDL2, obviously since that part is disabled on SDL1.

However it does work with dosbox-x-windows-20180518-170549-windows, wondering if there's been any change since then or it's never been tested, couldn't find anything on history as well, anyone ?

**Comment by joncampbell123** [comment]
Ah, yhat's right.

Just as realloc() can change the location of memory, popping from the back of a vector can invalidate the iterator. Didn't think of that.

**Comment by joncampbell123** [comment]
I refactored that code to iterate with a copy of the iterator, THEN erase the items from that point on. That change should fix the crash. Please try the latest commit.

**Comment by aybe** [comment]
Works perfectly, thanks !!!
