### ISSUE TITLE
Only one warning in VS2015 build (using VS2017)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#737]
The current code is so clean that I wondered about the one (only one) warning that I got when building in VS2017:

9>c:\users\edward\desktop\dosbox-x-master\src\gui\sdlmain.cpp(8280): warning C4297: 'SDL_main': function assumed not to throw an exception but does
9>c:\users\edward\desktop\dosbox-x-master\src\gui\sdlmain.cpp(8280): note: __declspec(nothrow), throw(), noexcept(true), or noexcept was specified on the function

Is this deliberate? It's not really an issue - just a curious question!

**Comment by emendelson** [comment]
It's clearly not worth taking time over it. It's the cleanest build I've ever seen on even a moderately complex project. 

But here's a page with a suggestion for an answer, one that I don't pretend to understand:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/4060ab94-bbd4-4f5e-9622-98e11b0a90ee/compiling-problem-function-throws-exception-please-help?forum=vclanguage

If that's not relevant, might as well close this as a time-wasting point...

**Comment by joncampbell123** [comment]
Fixed it, I think.

**Comment by emendelson** [comment]
Fixed indeed!
