### ISSUE TITLE
showmenu=false needs to do something useful in Mac OS X

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#739]
Under macOS, is there any way to prevent the DOSBox-X menu items from showing? showmenu=false in ~/dosbox.conf seems to have no effect. Thanks for any help with this.

**Comment by joncampbell123** [comment]
Mac OS X is the only target where hiding the menu bar is not implemented because it's position on the screen is global to all applications on the system.

The showmenu=false option only makes sense when the menu bar is in the DOSBox-X window itself.

**Comment by emendelson** [comment]
I understood that the menu has to appear in Mac OS X - but is there any way to prevent the DOSBox-X specific menu items from appearing (I mean Main, CPU, Video, Sound, DOS, Capture)?

**Comment by emendelson** [comment]
Wait - I see how to do this. The brute force method is to comment out lines 620-625 in menu.cpp. But the intelligent way would be to make those lines active or not depending on showmenu=true|false. I'll see if I'm capable of that...

**Comment by joncampbell123** [comment]
Try looking at sdlmain.cpp line 8206

**Comment by emendelson** [comment]
Before I saw your post about sdlmain.cpp, I figured out how to add a configure switch, like this:

In menu.cpp, add an if/else/endif around line 620 like this:

/* top level menu ("") */
static const char *def_menu__toplevel[] = {
#if NOMACMENU
#else
    "MainMenu",
    "CpuMenu",
    "VideoMenu",
    "SoundMenu",
    "DOSMenu",
    "CaptureMenu",
#endif
    NULL
};

Then add this block to configure.ac after around line 75:

AH_TEMPLATE(NOMACMENU,[Define to 1 to disable menu items in Mac OSX])
AC_ARG_ENABLE(nomacmenu,AC_HELP_STRING([--enable-nomacmenu],[Hide custom menu in Mac OSX]),[
  if test x$enable_nomacmenu = xyes ; then 
    AC_MSG_RESULT([hiding custom Mac OSX menu])
    AC_DEFINE(NOMACMENU,1) 
  fi
],)

And then use --enable-nomacmenu in the build script. I know there's a double negative in "enable-nomacmenu" but I couldn't get the logic right for a --disable... switch.

I'm now staring at sdlmain.cpp line 8206, but I'm afraid I'm not competent enough to figure out what to do with it to make it respond to showmenu=false...

**Comment by emendelson** [comment]
Oh, I see - you were referring to the TODO note in the latest sdlmenu.cpp... Thank you!

**Comment by joncampbell123** [comment]
DONE

**Comment by emendelson** [comment]
That was quick! Thank you!!
