### ISSUE TITLE
How to set cursor blink rate?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#753]
Is there a way to set the text cursor blink rate in the non-PC98 parts of DOSBox-X? In DOSBox SVN, the cursor rate depends on the frame rate, as described in this thread:

https://www.vogons.org/viewtopic.php?t=27374

In DOSBox-X, the rate seems to be adjustable in PC98 mode. Could there be a way to adjust the rate in normal VGA mode also?

**Comment by joncampbell123** [comment]
The cursor rate is adjustable in PC-98 mode because the hardware allows the cursor blink rate to be adjustable. VGA hardware as far as I know fixes the blink rate and does not permit changing it.

**Comment by emendelson** [comment]
OK - that settles that! (If you ever decided to build in a blink-rate adjustment, I don't think anyone would complain, but of course that's just a luxury to think about...)
