### ISSUE TITLE
Black bar shown at top of screen in fullscreen if menu is open

### ISSUE THREAD

**Issue by mgiuca** [joncampbell123/dosbox-x#755]
Version: e4c23bc (latest head)
OS: Linux Unity

Steps to reproduce:

1. Set config: `sdl.output=opengl` and `render.aspect=true` (former is necessary for fullscreen applications to actually take up the full screen, latter is optional)
2. Open dosbox-x with the above config (or just use the menu to change renderer to opengl).
3. F12+F to go full screen, and observe the result.
4. F12+F to exit full screen, F12+Esc to hide the menu bar, F12+F to go full screen again. Observe the result.

Results:

Full screen with menu bar:
![dosbox-x-fs-with-menu](https://user-images.githubusercontent.com/228433/41343543-478fd12a-6f42-11e8-8ef9-1dc46cb86f9c.png)

Full screen without menu bar:
![dosbox-x-fs-no-menu](https://user-images.githubusercontent.com/228433/41343548-49a5b86c-6f42-11e8-970c-96d4fefcd83e.png)

When the menu bar is enabled but in fullscreen mode, it's invisible but still takes up space. As a result, all fullscreen games have a small black bar along the top of the screen, and are shrunk down to fit the rest of the display.

Took me quite a while to realise that it was being caused by the menu bar.

**Comment by joncampbell123** [comment]
Can you git pull the latest code and try again?

There is code in place to draw the menu bar with OpenGL output.

**Comment by mgiuca** [comment]
Hi Jon,

I just pulled and tried d955cf92. Same as yesterday.

Is the expected output that a menu bar is drawn, or that it's automatically hidden?

**Comment by joncampbell123** [comment]
There is the expectation that, if the code makes room for a menu bar, that it should draw a menu bar.

So I'm not certain why it's not drawing a menu bar on your system.

**Comment by joncampbell123** [comment]
@mgiuca Answering this issue properly, the menu bar is supposed to disappear in fullscreen mode. If it is not, then that is a bug.

**Comment by mgiuca** [comment]
Wait, I just realised I never tested this on Windows; sorry I wrote that in the first place. I can test it on Windows later.

**Comment by aybe** [comment]
I cannot reproduce it on Windows.
