### ISSUE TITLE
About shipping XInput builds for SDL1

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#757]
Following my previous XInput driver for SDL1 builds, I was wondering if XInput builds could be shipped as part of the package ?

Because basically, DOSBox-X is simply ununsable with an XInput joystick due to the weird M$ decision to share the 3rd axis by triggers.

The simplest way I thought of is a batch file:

https://github.com/joncampbell123/dosbox-x/commit/7fbc42069588990d625ca8d14cebcdf7afe3aeed

Somehow it could be baked in the process that packages the whole thing.

...

The other way would be to simply switch to XInput by default in SDL1 but this would be a breaking change !

**Comment by aybe** [comment]
PS I've temporarily manually packaged it on https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-v0.82.7

**Comment by joncampbell123** [comment]
I would be OK with a separate XInput build until it's eventually merged into SDL1 as an optional code path if enabled on the system.

Can XInput support be done as something that SDL1 can LoadLibrary/GetProcAddress() for to check for it?

**Comment by joncampbell123** [comment]
My focus this month is on writing source code and user documentation for DOSBox-X so that users can use it better and others can hack on the source code better.

**Comment by aybe** [comment]
~~~I thought about that but there's a catch, I believe all non-Microsoft joysticks do also ship the same broken DirectInput driver layout that follows the original one. And they also don't provide support for legacy games (makes sense but leaves retro gamers in the dust).~~~

If I understand you well, you mean add an ```xinput=true``` to a conf section and conditionally swap the input method if it's available ? Sounds good to me, I will take a look.

---

Ok

**Comment by joncampbell123** [comment]
Not only would I like to help with xinput=true, but I also think it might be useful to add it to the menu as well to switch it on/off at runtime.

**Comment by aybe** [comment]
Alright, if I can get past step 1 then step 2 should be a breeze !

**Comment by aybe** [comment]
How would you do to implement the switching to XInput ?

I am talking about the part between DOSBox and SDL, from when the user sets the config param to the point of SDL needing to re-init accordingly.

Thanks

**Comment by joncampbell123** [comment]
The quickest way would be:
- SDL_QuitSubsystem input/joystick
- setenv() to direct input from XInput or some other way
- SDL_InitSubsystem input/joystick

**Comment by aybe** [comment]
Okay, thanks !

**Comment by aybe** [comment]
I have added a menu item that gets saved and loaded, but Configuration GUI and main menu item are never synchronized on startup; apparently it does that for other ones too.

So setenv would allow to set a flag that SDL1 would act upon, and the two others selectively manages SDL parts, right ?

I couldn't find setenv() and the docs are really unhelpful : https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html.

When and how I'm supposed to use these, in this place I guess ?
https://github.com/joncampbell123/dosbox-x/commit/1ba3656b7897750c4b5b6d2db34eb75dde48fdc5#diff-8a3f7446253ee20f230453b249d54541R54

And to my knowledge, only https://github.com/joncampbell123/dosbox-x/blob/master/vs2015/sdl/src/joystick/win32/SDL_mmjoystick.c should be changed in SDL1, correct ?

Would be great if you could sketch out some of this !

---

And for SDL2 the error is simply here https://github.com/joncampbell123/dosbox-x/blob/e443964d20f55f6b34cf64f06a9ce97fee9b780c/vs2015/sdl2/src/joystick/windows/SDL_xinputjoystick.c#L388 and it is really tempting to simply swap these axes but now we'll have a patched SDL2 ... 

Another idea would be an SDL2 #if and swap them here https://github.com/joncampbell123/dosbox-x/blob/04f0a23b37d63a6738e1203acf947e3230f3cc94/src/gui/sdl_mapper.cpp#L1311, cheap, better but still poor.

Comes in my old, unmergeable branch were there was custom remapping per the user, no SDL changes were needed at all.

Let's see if we can come up with the best idea involving the least changes.

**Comment by joncampbell123** [comment]
You'll need to add a call in main() under src/gui/sdlmain.cpp to set the menu item initially.

You only need to add it to SDL1 builds, and the SDL1 library.

setenv() is considered part of the C standard library.

https://linux.die.net/man/3/setenv

Then SDL1 could call getenv() to read it and act on it.

Or, the SDL1 library could offer a function for the main program to call to switch between XInput and normal, either before SDL_InitSubsystem() or after.

**Comment by aybe** [comment]
Thank you, I'll take another look tomorrow !

**Comment by aybe** [comment]
see #758
