### ISSUE TITLE
Future rewrite: Emulator Construction Set design

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#760]
This is a long way off, but it would probably help a future rewrite of DOSBox-X if it were made of more independent components than the intertwined code in this project.

As a "construction set" it would allow the same set of components to be re-used for different platforms and system configurations instead of jamming all emulation into one big executable.

Possible components:
- 8255 (PPI) chip emulation
- 8250 (PIT) emulation
- Serial port
- Parallel port
- PS/2 keyboard
- XT keyboard
- Common video raster emulation framework
- Intel x86 CPU emulation via "opcode compiler"
- Floppy drive model base class (including motor speed)
- Hard drive model base class
- CD-ROM drive model base class
- Audio mixer framework
- Time and event scheduling framework
- Common DOS kernel emulation framework
- "Standard VGA" common emulation framework. SVGA emulation can defer to it when standard VGA modes are active.
- Mapper framework (hopefully, much cleaner and better written than the one in DOSBox-X). It would include keyboard, mouse, joystick, and mapper shortcut events.

Each component would work as an independent object (as independent as possible) that can also compile against a test framework to make sure it behaves as it should.

DOSLIB (a sister project) would provide additional test programs that could run on either real hardware or DOSBox-X and test for specific behavior.

As a "construction set", the components could easily be reused as needed for other platforms. Considering the discussion here, the framework could provide components for each type of emulation, separate from one another:
- One for IBM PC/XT/AT and Tandy/PCjr emulation
- One for NEC PC-9801 and NEC PC-9821 emulation
- One for FM towns emulation

Other ideas:
- One for NES emulation (6502 core)
- One for Amiga emulation (68000 core)
- One for Macintosh 68k emulation (68000 core)
- One for Macintosh PowerPC emulation (PowerPC core)

Again all this is a long way off, but if the individual parts are written and well tested such that they can be assembled together into an emulator easily and maintained as independent emulators.

The first generation of this code will work as reference code. Performance will not be a consideration, only accuracy.

The hard part is defining the components, how they will work, and properly.

Discussion?

**Comment by joncampbell123** [comment]
Also as a common core, it would permit the same menu system and audio/video recording system to exist in all emulators so that people can record their gameplay and operate the emulator with menus and shortcuts.

**Comment by joncampbell123** [comment]
To explain the "opcode compiler"...

anyone who's looked at the dosbox-rewrite repository might know what I mean by "opcode compiler".

Modern x86 processors have a lot of instruction encodings and variations. The idea is that instead of manually maintaining the opcode decoder for each core, a program could take a file that describes the encoding of each opcode, and generate the code to do it instead. All opcodes that are common from the 8088 up will have the same code without mistakes. The file would have conditional expressions to enable opcodes if, for example, generating a core for a 286 vs a 486 vs a Pentium III.

**Comment by sikthehedgehog** [comment]
> One for NES emulation (Z80 core)

But NES uses a 6502 without decimal mode ( ﾟ-ﾟ) (SG-1000 / SC-3000 / Master System are the ones using Z80... and also ZX Spectrum and a lot of Japanese 8-bit computers)

**Comment by joncampbell123** [comment]
@sikthehedgehog Corrected, sorry about that. It would be a 6502 core with consideration for whatever minor changes Nintendo made.

**Comment by sikthehedgehog** [comment]
OK (・・　)

The NES CPU core is a 6502 with the decimal flag ignored as if it didn't exist (Ricoh literally cut out a few lines to prevent it from working), exclusively to avoid paying for a patent regarding how the 6502 implements BCD. I forgot what was the exact situation with undocumented opcodes (which differ between NMOS and CMOS on stock 6502) but Nintendo explicitly forbade their use (in fact they may have changed across revisions).

**Comment by joncampbell123** [comment]
https://retrocomputing.stackexchange.com/questions/2592/what-is-the-relationship-between-the-ricoh-2a03-and-the-mos-6502#2593

**Comment by joncampbell123** [comment]
@Jarvik7 DOSBox-X already uses some code from MAME, true. I was only using classic game consoles as examples here.

**Comment by joncampbell123** [comment]
@Jarvik7 Obviously if there's no need for a new emulator, I'm much more likely to use and possibly modify existing emulator code instead.

**Comment by joncampbell123** [comment]
I've thought this over, and this enhancement as described is waaaaaaay too ambitious.
It might be better to clean up DOSBox-X and carefully modularize the code so it can become components to enable different emulation, instead of rewriting the world.
