### ISSUE TITLE
XBRZ branch deleted accidentally

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#763]
Sorry, I thought it was merged but I was wrong and I don't have the branch on my hard drive ... can someone push it again ?

Thanks

**Comment by aybe** [comment]
Fixed it by forking, I'll be more careful in the future !

**Comment by alexat** [comment]
Hello aybe,
You can always take it from my xbrz branch. I think it's viable to merge it, I tested it on multiple different machines and found no issues. Of course lack of color order recoding may backfire somewhere, but it's something to tend to later on.

**Comment by aybe** [comment]
That's what I did in fact, I deleted 4 of branches and mistakenly thought XBRZ was merged but it was not.

Things are back to normal and hope to merge this ASAP.

Thanks !
