### ISSUE TITLE
What is the mechanism that updates dosbox-reference.conf, if any ?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#766]
I thought that it got generated with ```config -all -wc``` but no, apparently it's a manual (and tedious) task.

Currently the ones missing would be the new joystick settings and xbrz once it gets merged.

**Comment by joncampbell123** [comment]
Compile DOSBox-X then run the shell script update-dosbox-reference-conf

**Comment by aybe** [comment]
Thanks!
