### ISSUE TITLE
MOUNT command doesn't accept single quotes around path (original DosBox does)

### ISSUE THREAD

**Issue by Tenebrous** [joncampbell123/dosbox-x#770]
MOUNT C 'C:\Temp' doesn't work and gives a "Can't create drive" error, although this works on baseline DosBox.

**Comment by aybe** [comment]
Fixed

**Comment by yksoft1** [comment]
Single quote is a legal character in Windows file names.
Assume there is a directory 

> D:\a\b\c\'d
If you try mounting it as

> mount c 'D:\a\b\c\'d'
Then the mounted C: would be D:\a\b\c instead of D:\a\b\c\'d as of current master head.

**Comment by Tenebrous** [comment]
While I understand the difficulty, unfortunately this means that in some cases dosbox-x can't be used as a drop-in replacement to original dosbox (e.g. with LaunchBox for example).

May I suggest removing single quotes that appear at the start and end in a pair?

**Comment by joncampbell123** [comment]
Another possibility might be to simply require double quotes and pass single quotes through without translation.

**Comment by Tenebrous** [comment]
That doesn't get around the backwards compatibility issue with (for example) LaunchBox. However I'll raise an issue with them too to allow customisation of the MOUNT command they use.

**Comment by aybe** [comment]
I asked for a review because I was reluctant of this change. 

I think we should just revert the change.

As far as I know, there is DOS in DOSBox and this is the commonly seen syntax for command line arguments.

It just makes sense to me to use delimiters that are forbidden in file names, it keeps things simple and at the same time avoids introducing subtle bugs unless significant rework of the parser is done, e.g. https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/.

**Comment by joncampbell123** [comment]
I thought it was OK, but it doesn't seem to sit well with others here.

**Comment by Tenebrous** [comment]
I'd hold off on this too tbh. I don't think my initial assessment of the problem was correct.

I was seeing the single quotes being passed as a -c arg to dosbox, e.g. -c "MOUNT C 'folder'"

Will get screenies and test some more when I'm at my desktop.

**Comment by sikthehedgehog** [comment]
Quoting myself from the PR:

> And on Linux (and other POSIX systems), everything that isn't the nul character can show up in a path (the only two reserved characters are nul and /, with the latter being the path separator so it can show up in a full path). Given that DOSBox-X supports Linux, this needs to be taken into account.

So any solution that's taken needs to account for the case that just about any character is allowed.

Again from there, probably the best solution is to offer to escape the quotes:

> If that's an issue then I think it'd be time to start thinking on ways to deal with it (repeating the quote is a popular solution when you don't need to escape any other character)

And of course, only do the escaping for the quotes that get used to begin the string (either single quote or double quote). That's how most programming languages handle it.

**Comment by Tenebrous** [comment]
Right, not entirely sure what's happening here.

LaunchBox is giving DosBox an argument of `-c "MOUNT C 'C:\Content\Games\MS-DOS\Galactix'"`:
![image](https://user-images.githubusercontent.com/593662/41644865-4902626e-7467-11e8-84ba-2d64fdf2c73e.png)

This can be seen in the actual DosBox window as `MOUNT C "C:\Content\Games\MS-DOS\Galactix"`:
![image](https://user-images.githubusercontent.com/593662/41644919-684b44b0-7467-11e8-9c14-3a490b2ba753.png)

But the same command line doesn't appear to work in DosBox-x 0.82.7:
![image](https://user-images.githubusercontent.com/593662/41644955-81fa47d0-7467-11e8-96ce-feb2a2f3137f.png)

But it works if I type it manually:
![image](https://user-images.githubusercontent.com/593662/41645017-a5ef739a-7467-11e8-9ea8-97d63b2dd534.png)

**Comment by aybe** [comment]
@all

Right, I am reverting this change to put things back to **normal**:

![command_000](https://user-images.githubusercontent.com/1537591/41694410-81a32100-750a-11e8-9429-4fe13a1590c8.png)

This is simple (no change at all) and handles all scenarios at least on Windows.

---

@Tenebrous 

The right syntax for mounting from a command-line in your 2nd screenshot is:

```dosbox-x -c "MOUNT C \"C:\Content\Games\MS-DOS\Galactix\""```

![command_000](https://user-images.githubusercontent.com/1537591/41694489-d5fa2ea6-750a-11e8-8f41-cf54c3316fba.png)

---

@sikthehedgehog 

You are definitely right, this is how it should be done in fact, thing is, I don't use Linux at all (a good excuse for not fixing it !).

I'll try to get a VM up and see if I can setup a development environment using the instructions in the README.

**Comment by Tenebrous** [comment]
@aybe That's it, perfect. Thanks! I'll let the LaunchBox guys know they are doing it wrong ;)

**Comment by aybe** [comment]
Okay,

Closing for now, reopen if needed.
