### ISSUE TITLE
VESA 320x200/240 modes doublescanning method causes some demos to stretch image vertically

### ISSUE THREAD

**Issue by wbcbz7** [joncampbell123/dosbox-x#771]
As far as I discovered (at least if machine=svga_s3), VESA lowres modes (such as 320x240 15/16/32bpp or so on) use bit 7 of CRTC index 9 (Maximum Scan Line Register) for double scanning, and bits 0-4 are set to zero, resulting in repeating each line twice, as expected.
Some demos (like [Licht deluxe: Osram 2000/Haujobb](http://www.pouet.net/prod.php?which=2197) or [ venus/fudge](http://www.pouet.net/prod.php?which=913) seem to force double scanning in these modes by ORing current CRTC index 9 value with 0b00001, assuming that bit 7 is clear. However, as bit 7 is set, each line as result is repeated 4 times, so image gets vertically stretched and only top half is displayed. Some real hardware (i.e. NVidia cards) also experience this issue.
On real S3 cards, CRTC index 9 after VESA lowres mode set had bit 7 clear and bit 0-4 set to 0b00001, so this issue does not appear on them.

So, the easiest fix would be using bits 0-5 for doublescan and set bit 7 to 0 :)

![](https://i.imgur.com/i6imKkE.png)

**Comment by joncampbell123** [comment]
I have found at least one demo that runs as if only the top half is visible, so I can confirm that.

As far as I know bit 7 is for double-scanning in a way that's backwards compatible with old DOS games, so it seems silly to me for SVGA emulation to set it for VESA modes. That is something that should be adjusted.

**Comment by joncampbell123** [comment]
I'm testing a fix now with this demo, which also showed the same problem in the middle part of the demo.

http://files.scene.org/get/mirrors/hornet/demos/1996/f/fdg_ucla.zip

Prior to the fix, you'd only see the top half of the 3D scene rendered in M_LIN15 mode.

So far the fix seems to make the whole scene visible.

**Comment by joncampbell123** [comment]
Try the latest commit

**Comment by joncampbell123** [comment]
The latest commit has a fix for these demos. Does it work for you?

**Comment by yksoft1** [comment]
Worked here for Osram 2000.

**Comment by joncampbell123** [comment]
Works here as well, for two demos known to have this issue.

**Comment by wbcbz7** [comment]
yep, now it works fine. Thanks :)
