### ISSUE TITLE
SHELL if command spans to many lines, unable to move to previous line

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#781]
![dosbox_000](https://user-images.githubusercontent.com/1537591/41752084-7078200e-75c5-11e8-8b6a-155329aa2bd1.png)

Type a command that is longer than available columns, try to go to the beginning with <kbd>Left</kbd>, you'll be stuck on the last row you're in.

**Comment by aybe** [comment]
This doesn't seem trivial, there are a couple of interrupts this could be retrieved from, and how and where should this be done in the end ?

http://www2.ift.ulaval.ca/~marchand/ift17583/dosints.pdf

**Comment by joncampbell123** [comment]
At least in IBM PC mode, you might consider getting/setting cursor position with INT 10h. The rest can be done with ANSI escape codes since DOSBox and DOSBox-X default to ANSI emulation.

If you write the calls to the BIOS as function calls, I can then provide the conditional changes in that function call to allow it to work in PC-98 mode as well.

**Comment by sikthehedgehog** [comment]
Random possibly irrelevant story: I remember running into an this issue like this on an actual DOS computer many years ago (almost two decades ago, probably?), where the command line would refuse to go back beyond the line split. I started being careful about how much I wrote after that.

No idea exactly what combination of software was involved but there's definitely precedent on real systems. I suppose it's not desirable behaviour however.

**Comment by aybe** [comment]
On DOS 6.22 it also prevents you from going back:

![s](https://user-images.githubusercontent.com/1537591/41755892-ca74e204-75d9-11e8-87f0-f243ea28d7ab.PNG)

But with ```doskey``` it is possible:

![capture](https://user-images.githubusercontent.com/1537591/41755893-cc56022e-75d9-11e8-9de7-0aa8a5558282.PNG)

**Comment by aybe** [comment]
So how is this supposed to be implemented ?

Within the scan code handling, checking if ```str_index > 0``` and then calling ```INT10_SetCursorPos``` ?


But I'll need to get cursor row first, from which of these ?

INT 10 - AH = 0Fh VIDEO - GET CURRENT VIDEO MODE
INT 10 - AH = 1Bh VIDEO - FUNCTIONALITY/STATE INFORMATION (PS,VGA/MCGA)

And what's a good web link for DOS interrupts ?

**Comment by aybe** [comment]
I meant rather ```INT 10 - AH = 03h VIDEO - READ CURSOR POSITION``` ?

**Comment by aybe** [comment]
Moving to #783
