### ISSUE TITLE
Why IMGMAKE fails for +4GB images ?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#784]

**Comment by joncampbell123** [comment]
What platform?

32-bit builds might have a problem only because lseek and open() use "long" for file offsets and sizes.

**Comment by aybe** [comment]
Win32 SDL1, it tells there's not enough drive space to create image.

**Comment by aybe** [comment]
This is wrong, in fact it is IMGMAKE that fails.

**Comment by aybe** [comment]
I was so happy to have it fixed in no time, tried again then got that no text, _gasp_, how the hell could such change screw the program ... until I've seen https://github.com/joncampbell123/dosbox-x/commit/45388a5b24bc8a0d9ec7416b1865bfea3222b395

Pushing this to master instead,
