### ISSUE TITLE
Repository for NEC PC-98 stuff

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#787]
### General

[Intro to NEC PC-9800 World](http://euc.jp/articles/pc9800.en.html)

[NEC PC-9800 Quick Guide](http://newsonya.narod.ru/pc9821/quick-guide/quick-guide-intro.html)

### Documents

[Index of /docs/content/computing/NEC](http://chiclassiccomp.org/docs/content/computing/NEC/) <- BIOS docs, Japanese X)

To translate with Chrome:

https://archive.org/stream/PC9800TechnicalDataBookBIOS1992/PC-9800TechnicalDataBook_BIOS_1992_djvu.txt

### Emulators

[PC-98 emulators](http://emulation.gametechwiki.com/index.php/PC-98_emulators)

[Neko Project II](https://www.yui.ne.jp/np2/)

[Neko Project 21/WでWindowsを動かす](https://sites.google.com/site/np21win/)

**Comment by aybe** [comment]
I really need some sleep ! #787

**Comment by joncampbell123** [comment]
I've been collecting PC-98 documentation too:

http://hackipedia.org/browse/Computer/Platform/PC%2c%20NEC%20PC%2d98
