### ISSUE TITLE
Windows 95 OSR2: Bringing up a DOS box causes system to freeze (including cursor)

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#79]
It's not a fatal freeze. Despite the locked up appearance, you can break the freeze by hitting CTRL+ALD+DEL twice, then hitting enter to return to Windows. Dismiss the task manager, and then the DOS VM will be active and running.

This lockup will happen every time you bring up a DOS VM.

Once the lockup is bypassed, the DOS VM works normally.

If this happens at least once, then the shutdown process for that session will not see INT 10h run off into the weeds a bit.

The lockup appears to happen in Win16 land, in a tight loop that loops until a memory location (WORD size) resets bit 3 to zero:

0317:1621  A1E89A              mov  ax,[9AE8]              [illegal]
0317:1624  83E008              and  ax,0008
0317:1627  75F8                jne  00001621 ($-8)         (up)

Not sure why using CTRL+ALT+DEL breaks this loop.
I'm curious what DOSBox means by "illegal" as well since that is the encoding for MOV AX,[memaddr]

**Comment by joncampbell123** [comment]
Okay. I think I know what DOSBox means by that MOV instruction that it marks "illegal".

DS=2087

Segment base/limit according to LDT:
 826763394 ERROR MISC:2084: b:C127B000 type: 12 parbg
 826763394 ERROR MISC:      l:00000000 dpl : 3  10000

Notice it's a code segment that's execute only, limit = 0. So then, this code is obviously trying to cause a general protection fault or some kind of fault that loads the segment into memory?

**Comment by joncampbell123** [comment]
Ah-ha. So the problem was exactly what I thought it was. Adding code to GP# fault on segment limit violation (for MOV AL,[mem]) makes Windows 95 OSR2 start the DOS VM properly.

**Comment by 8bitKittyKat** [comment]
I'm having this exact issue with Windows 95 OSR2 on the current release

**Comment by ThisIsNotRTS** [comment]
Hi I'm having a similar issue with Win95 OSR2, in which the system freezes only on shutdown, most of the time. Probably I should open a new issue and refer to this one as a reference. The CTRL+ALT+DEL trick does not work in this case.

**Comment by Wengier** [comment]
@ThisIsNotRTS The issue you experienced is likely associated with the CD image change function. There is a new thread #3062 for this which is hopefully already fixed.
