### ISSUE TITLE
Pointer integration for DOS ?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#794]
I'm trying to understand how this works,

Is it worth the effort for DOS ?

**Comment by joncampbell123** [comment]
Do you mean within the DOSBox-X DOS kernel, or when you boot MS-DOS as a guest OS?

I suppose INT 33h emulation could be modified to support "pointer integration". It would be a lot easier than writing a mouse driver to use the DOSBox integration device.

**Comment by joncampbell123** [comment]
If either of us implement this, I recommend making it a dosbox.conf option only because most people are used to capturing the mouse cursor to use the mouse with DOS games.

**Comment by aybe** [comment]
Not when booting M$-DOS,

I'll take a look at INT33 and see if I can get something up.

**Comment by aybe** [comment]
Discussion continues at https://github.com/joncampbell123/dosbox-x/pull/796.
