### ISSUE TITLE
Possible emulation problem: INT 10h in machine=pcjr does not control text "blinking" attribute

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#800]
Using INT 10h to toggle the blink attribute does not work in machine=pcjr.

If there is evidence the PCjr is too cheap to implement the blinking attribute, then I'll close this without fixing, with the understanding then that INT 10h AH=0x10 AL=0x03 emulation should not do anything in PCjr mode then.

**Comment by joncampbell123** [comment]
DOSBox SVN appears to have the same problem.

**Comment by joncampbell123** [comment]
Unrelated question: Do the tandy/PCjr palette registers take effect in text mode? DOSBox emulation seems to imply they don't. (noted in DOSLIB)

**Comment by sikthehedgehog** [comment]
Looked up this issue and first thing I found was a BLINKJR program that exists to fix blinking text in programs. The readme file that comes with it says this:

```
         Documentation for PCjr
         BLINKOFF and BLINKON
 
Have you every run a program on your PCjr and found some of the text
blinking in strange places? This may be because the program sets the
video gate array mode control 2 register to disable blinking on a
regular PC. This causes the high order bit of the attribute byte to
be interpreted as the high intensity version of the background color
instead of whether the character should blink or not.
 
Unfortunately, the port address for the video gate array is different
on the PCjr, hence the continued blinking. A popular public domain
version of Monopoly is one program that runs on the PCjr with blinking
text in strange places.
 
If your using the ANSI.SYS device driver to set screen colors you can
now have 16 background color choices instead of the normal 8.
 
BLINKOFF.EXE sets the blinking off, and BLINKON.EXE sets the BLINKING
back on.
 
 
WARNING!!!! These programs write directly to port hex 3DA. Their use
on any PC that's not a PCjr can cause unexpected ( and perhaps
unpleasant) results.
```

Found the program here, the readme says nothing about the program's procedence though (not even who wrote it) :/
https://www.brutman.com/PCjr/pcjr_downloads.html

**Comment by joncampbell123** [comment]
My code is using INT 10h to (try to) control blinking.

Does this mean INT 10h on the PCjr lacks blink control?

**Comment by joncampbell123** [comment]
According to RBIL, the Jr should support it too.

http://www.ctyme.com/intr/rb-0117.htm

Unless RBIL is wrong, this means DOSBox-X and DOSBox fail to implement the INT 10h function in PCjr mode.

**Comment by joncampbell123** [comment]
I appreciate it.

If you have DEBUG on the system and you're in 80x25 text mode, you might try entering with the 'a' command:

    mov ax,1003
    mov bx,1
    int 10

To turn on blinking.

Then use 'e B800:0000' to write character and attribute bytes where the high bit of the attribute (bit 7) is set. See if they blink.

I also release DOSLIB binaries with some code that might help to test this.

https://github.com/joncampbell123/doslib/releases/tag/doslib-20180627

Use TEST-FW\VIDEO\PC\DOS86l\TEST.EXE and HW\VGA\DOS86l\TEST.EXE

**Comment by MobyGamer** [comment]
Looking at the PCjr tech ref page A-61, I don't think that's going to be necessary -- the BIOS listing stops at subfunction 2.  So I'm wrong, and the PCjr's BIOS (there was only ever one revision) does not support Int 10h, AH=10h, AL=03 -- and it also means the RBIL is wrong :-(

**Comment by joncampbell123** [comment]
It's possible the reference was written before the BIOS was fully completed. Does the asm listed above enable blinking when entered with debug?

**Comment by joncampbell123** [comment]
Make sure to single-step with debug until just after the INT 10h.

**Comment by MobyGamer** [comment]
Not only was the reference written after the BIOS was finalized, but there was never a newer revision of the PCjr BIOS.  Even if they wanted to revise it, it would have been very difficult because the SET_PALETTE section of the source is immediately followed by other code and data that cannot be shifted: IBM rigorously maintained parameter tables, font tables, and even subfunction entry points at the same locations in memory for the benefit of very early programs (as well as ROM BASIC and, in the case of the PCjr, Cartridge BASIC) that directly referenced them, most notable being the font table at FA6Eh.

If you _really really_ want this verified, I can set up a PCjr and test, but there are more fruitful uses of time :-)

**Comment by joncampbell123** [comment]
I see. I'll revise DOSBox-X to ignore AL=2 and AL=3 for PCjr mode then until further information is available.

**Comment by joncampbell123** [comment]
I fixed DOSBox-X to ignore INT 10h AL=2/3 when machine=pcjr, and the DOSLIB test program to write 0x3DA directly to control blinking.

If PCjr actually does have the INT 10h call, reopen this issue and say so.

**Comment by MobyGamer** [comment]
AL=2 is valid.  PCjr handles AL=0/1/2.  Only 3 and later are rejected.

**Comment by joncampbell123** [comment]
Fixed. I thought you meant that AL=2 or higher was ignored.

**Comment by MobyGamer** [comment]
As a data point, someone is trying to create ASCII text bios listings of several BIOSes: https://gitlab.com/ricardoquesada/bios-8088
Their rationale: The published BIOS listings are complete, but sometimes hard to read and not searchable.
