### ISSUE TITLE
Current code stretches text vertically

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#808]
This was built under Windows 10, 29 June 2018, 6:44 AM EST:
![capture](https://user-images.githubusercontent.com/5208505/42088578-f2078d1a-7b67-11e8-94a1-9c95c9509b88.PNG)

**Comment by alexat** [comment]
This may be related to latest aspect ratio correction changes introduced by me in xBRZ patch series.
Can someone please check against real DOS on 4x3 monitor for if the proportions are proper?
If stretching is undesired, aspect=false should solve it.

**Comment by alexat** [comment]
Please share the following settings:
aspect
output
scaler

**Comment by emendelson** [comment]
My mistake! I forgot that DOSBox-X, without a conf file in the same folder, uses whatever conf file is in the user data folder. This was pure user-stupidity. When I renamed dosbox.reference.conf to dosbox.conf, everything was OK.

The stretching occcurred with:

aspect =false
output=direct3d
scaler=normal2x

I don't remember how direct3d got in there, but it's clearly the problem. Apologies for a mistaken post!

**Comment by alexat** [comment]
No problem. Good to hear because I never touched the original stretching part. As for D3D stretching, I will doublecheck the new code, thanks!

**Comment by alexat** [comment]
Yes, a little bug with exactly output=direct3d/aspect=false/windowed mode found and I'll ask developers to include amendment to my mistake soon.

**Comment by emendelson** [comment]
Glad to help out, and thanks for the quick response!

**Comment by alexat** [comment]
Hm, for the reference config, alas I can't tell, totally don't know how it's generated. D3D mode looks good as default for windows systems though. The small mistake is amended with a small patch I submitted above, with it aspect=false initial window selection is fixed under D3D.
