### ISSUE TITLE
Mouse integration minor fixups

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#811]
Host cursor is visible while Windows 3.1 is using the DOSBox Integration Device (should be hidden as long as Windows within is reading the host mouse position).

I also noticed a problem with DOS games that read relative mouse motion instead of absolute. I found one demoscene "invite" that uses the mouse but reads only relative motion, which caused the cursor to not match the host. I also noticed that relative motion with DOOM works, but it's a pain to have to move the cursor back and forth manually to try and turn.

Perhaps it would be better if the INT 33h mouse integration were to only report absolute mouse position, and not report relative motion, if your synced=true code is working. Code that requires reading relative motion should require the user to capture the mouse.

This is why, when I wrote the mouse pointer integration support for Windows 3.1, I wrote the PS/2 mouse emulation to send mouse events with NO motion (dx=0 and dy=0, only the button state) unless mouse capture is active.

**Comment by joncampbell123** [comment]
I'm referring to an INT 33h call (don't remember the function right now) that DOOM calls to read relative motion. The INT 33h call returns accumulated relative motion and then resets it to zero.

**Comment by joncampbell123** [comment]
Are the positions consistent between client and host? Does capturing the mouse, moving it, then un-capturing the mouse result in different positions?

This may be the relative movement behavior I just described here.

**Comment by joncampbell123** [comment]
I like to make an INST\WIN311 directory, then copy disk #1 to DISK1, disk2 #2 to DISK2, etc.

Then I just run SETUP from DISK1.

Whenever it stops and asks for another disk, just edit the path to where you copied it on drive C:

When it's all set up, you should have Windows 3.1 with plain 640x480 16-color VGA graphics.

**Comment by joncampbell123** [comment]
If you want the Windows 3.1 integration drivers, download the latest DOSLIB release, and look in the WINDRV/DOSBOXPI/BIN/WIN31 directory.

When you're ready to install, run Windows setup, select "Other..." in the dropdown menu for the mouse, and direct Windows to WINDRV/DOSBOXPI/BIN/WIN31 so that Windows can find the INF file and install the DOSBox-X integration mouse driver.

**Comment by aybe** [comment]
Ok I've got it, 

I see what the problem is, thing is my code has nothing to do with that (pointer in different places) but for visible cursor it has to do.

As you I think mouse should be synced but I can't figure it out:

https://github.com/joncampbell123/dosbox-x/blob/develop/src/gui/sdlmain.cpp#L4804

```mouse_notify_mode``` is always 0

No matter what setting I use for

```
[cpu]
integration device=
```

**Comment by aybe** [comment]
Once I know that I should be able to fix that double pointer issue.

Then try DOOM !

**Comment by aybe** [comment]
Okay it works now ... I should have read better !

Added to the list of not so obvious things #813

**Comment by joncampbell123** [comment]
Can this be completed on July 1st? I'd like to make another official release before continuing. Make sure the CHANGELOG lists your accomplishments.

**Comment by emendelson** [comment]
For installing Windows 3.1, I made this system:

http://www.columbia.edu/~em36/win31dosbox.html

I did some behind-the-scenes work on replacing DOSBox with DOSBox-X, but a friend who experimented with it a few months ago experienced lockups and other problems, so I've delayed that. I'll look forward to trying it again. (And figuring out some way to add the mouse driver...)

**Comment by joncampbell123** [comment]
@aybe I got the xBRZ code to compile without ppl.h on Linux.

I noted two minor issues with the code as it stands.
- Toggling "fit to aspect ratio" seems to disable xBRZ's interpolation effects. De-selecting then re-selecting xBRZ fixes it.
- The code to place xBRZ's output on the screen disregards the SDL drawn menus on Linux. It needs to fill only the part of the screen as directed by sdl.clip.x, sdl.clip.y, sdl.clip.w, and sdl.clip.h.

**Comment by joncampbell123** [comment]
I realize that if you implement that literally at this time, it would just fill that part of the screen like output=surface would, so I'll fix the surface output code to set sdl.clip the way it does for OpenGL and Direct3D if the xBRZ scaler is selected.

**Comment by joncampbell123** [comment]
The synched mouse behavior is supposed to set the absolute position in the client according to where you moved the mouse in the emulator. That can't be done properly if the DOS program is ignoring absolute position and reading only relative position, thus my recommendation that the relative movement INT 33h function return zero unless the mouse was captured (or autolock).

**Comment by joncampbell123** [comment]
@emendelson That happens if the program is reading relative motion only from INT 33h, instead of absolute position from INT 33h. Emulation can synchronize the cursor only if the program reads absolute position.

**Comment by emendelson** [comment]
@joncampbell123 For what it's worth, WordPerfect for DOS has a couple of dozen mouse drivers, including two called "Absolute/Pen" and "Absolute/Pen 2." I didn't see any difference in the two-mouse-cursor problem when I chose either of them. But I'm not at all sure that's relevant here...

**Comment by joncampbell123** [comment]
@aybe I just fixed the xBRZ code to render to sdl.clip, it's fine now.

**Comment by aybe** [comment]
@joncampbell123 

Fixed

https://github.com/joncampbell123/dosbox-x/commit/76ab920a8e3f28beca41126b30cfa40d3a8cdce7

---

I noticed that ```autolock=true``` does not work inside Win31 but works after you exit it.

But if you lock with <kbd>Ctrl</kbd>+<kbd>F10</kbd> the pointer does not move anymore !!!

---

When you <kbd>Ctrl</kbd>+<kbd>F10</kbd> in WP:

![2018-06-30 01_47_47-dosbox-x 0 82 7 30000 cyc_ms wp](https://user-images.githubusercontent.com/1537591/42118968-af2c5c50-7c07-11e8-9e37-743eff7ea077.png)

💯 

---

WP

It hides the mouse but uses it ... if you lock the mouse then problem vanishes.

There could be something either _force_hide_ or _do not hide if enabled and then moving_ but honestly it feels weird to me.

---
@joncampbell123 

_thus my recommendation that the relative movement INT 33h function return zero unless the mouse was captured (or autolock)._

Where is that ?

**Comment by aybe** [comment]
@joncampbell123 

ok

**Comment by aybe** [comment]
@emendelson 

Your guide is great, I need to read it details !

**Comment by joncampbell123** [comment]
It's INT 33h AH=0Bh.

Line 1026, src/ints/mouse.cpp

**Comment by aybe** [comment]
With that change only the SDL cursor is now visible ... but when you lock, the right cursor is visible.

Is this what you intended ? If yes then it works fine.

**Comment by aybe** [comment]
Forgot to add, basically the cursor still exists but when WP is started it is at a non-visible position (when unlocking you see it).

I think this change is pretty good because it just forces the user to autolock and that's it.

**Comment by joncampbell123** [comment]
That's the idea. The program has to ask for absolute position in order to synchronize to cursor movement in the window, otherwise withheld relative motion until autolock or mouse capture.

**Comment by aybe** [comment]
Here it is: fc92ff13811f27f555ffa470441649df26dddbc2

**Comment by emendelson** [comment]
@joncampbell123 and @aybe The latest code seems to work perfectly with WPDOS 6.x. In both text mode and graphic mode (you switch with Ctrl-F3), only the WPDOS cursor is visible by default.

Without a conf file, I see that I need to press Ctrl-F10 in order make the WPDOS mouse pointer visible. But with these settings in the conf, it seems that I can start using the mouse pointer as soon as I click in the window:

autolock=true
mouse_emulation=locked

I'm probably asking for the impossible, but is there a setting that would let me start using the WPDOS mouse cursor without clicking in the window? Meanwhile, many thanks for all this progress!

**Comment by aybe** [comment]
@emendelson 

https://github.com/joncampbell123/dosbox-x/pull/796#issuecomment-400895638

Why would DOSBox steal user mouse without permission ?

This is likely to bring more problems than it solves.

Just click the mouse at startup 😃 


**EDIT**

Just had a brilliant idea !

8b8641a73163fff8f2b47c9c4cfa7297341b5ac2

I guess that calling this before WP does the trick and can be useful for others too.

**Comment by emendelson** [comment]
@aybe That is a brilliant idea - and I'm slapping my forehead because I had exactly the same brilliant idea two years ago for DOSBox SVN! --

https://www.vogons.org/viewtopic.php?f=41&t=45688

**Comment by aybe** [comment]
+1 for the help but unfortunately it's not a shell command so I can't add help in the same way you did, I'll let people discover its use.

How does it work, did you test it in your AUTOEXEC ?

**Comment by emendelson** [comment]
@aybe Works perfectly when run before starting WP. Thank you!

**Comment by joncampbell123** [comment]
@aybe I'd like to put out a release tomorrow. I will be going over my commits to make sure what I've done is listed in the CHANGELOG. Anything you'd like to add?

**Comment by aybe** [comment]
@emendelson 

🥇 

@joncampbell123 

Yes, I am finishing up in getting <kbd>CapsLock</kbd> and <kbd>ScrollLock</kbd> to behave as <kbd>NumLock</kbd>.

**Comment by aybe** [comment]
@joncampbell123 

Almost finished

**Comment by joncampbell123** [comment]
@aybe Is that an option? Remapping like that can be done in the mapper or as an option, it doesn't need special treatment.

**Comment by joncampbell123** [comment]
If you're going to do that can you make sure the *default* is to map them to the actual keys on the keyboard? Caps lock to caps lock, num lock to num lock, etc?

**Comment by joncampbell123** [comment]
@aybe I'm OK with that as an option, just don't make that remapping default.

**Comment by aybe** [comment]
No just that if the key was on before starting, it will be on in DOSBOX and restore when window is activated again but was changed externally.

Remember the long plaguing non synchronized num lock at startup ? Been using CAPS and found it lacking this, and while we're at it, why not SCRLCK 😃 

(no remapping at all)

If you have to pack something up you can, changes added,
https://github.com/joncampbell123/dosbox-x/commit/298ce2d4b3c60113a55588f2ed25c2b6a9055710
https://github.com/joncampbell123/dosbox-x/commit/ba8e3dfcaa99e1786d1c8c9546178f4771e97eae
https://github.com/joncampbell123/dosbox-x/commit/243c473e7a9c0e487fc89d30b0f47a0dfba75e2b

Right now I'm just implementing remaining leds defines and making the code to use these instead of hex.

**Comment by aybe** [comment]
All is working fine for me @ 6bd3908ef90efba765a039e413255acc798a7749

I made flags replacements in my code but not everywhere, because it really needs to double check before massive update ... so next time.

No more changes for me at this point.

**Comment by matt-curtis** [comment]
The problem I'm experiencing seems to be related to this issue... I'm using Windows 3.1 in DOSBox to run an old app, and wanted to find out if there was a way to move the cursor in host and client while keeping the exact same position in both. Currently the client cursor is always some distance from the host, depending on where I enter the window. Is there anything I can try? I'm using the latest release (0.82.8).

**Comment by aybe** [comment]
This is because the mouse is emulated (it's always been behaving like that),

If you `autolock `obviously it's less noticeable, if you don't it is definitely.

So if you don't `autolock `, set `mouse_emulation `to `locked `or `never`.

and

```
To install Windows 3.1 mouse integration driver:

 - in config, section [cpu], set 'integration device' to 'true'
 - download DOSLIB from https://github.com/joncampbell123/doslib/releases
 - extract it to the virtual hard drive
 - run 'Windows setup'
 - select 'Other ...' in the dropdown menu for the mouse
 - install \doslib\windrv\dosboxpi\bin\win31\oemsetup.inf
 - restart Windows
```

**Comment by matt-curtis** [comment]
Fantastic. I'll give this a try. Thanks!

**Comment by joncampbell123** [comment]
@matt-curtis If you can compile from source, try the latest commit.

**Comment by joncampbell123** [comment]
DOSLIB mentions lack of running on Windows 10. Running the driver in Windows 3.1 in DOSBox-X should work regardless of the host system.

**Comment by joncampbell123** [comment]
I know some fixes were applied recently to make int33 pointer integration work that I later found broke the integration device support. I had to patch those up.

It sounds like I should compile up a binary from the latest source as a beta, see if that helps.

**Comment by aybe** [comment]
@matt-curtis 
works fine on win10

https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-20180701-1000/dosbox-x-windows-20180701-103732-windows.zip

```
[cpu]
integration device=true

[autoexec]
mount c .
c:\windows\win
```

@joncampbell123 
I thought int33 doesn't affect at all Win31 ? Anyway, setting it doesn't have any effect.
