### ISSUE TITLE
Pruning stale branches ?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#818]
@joncampbell123 
https://github.com/joncampbell123/dosbox-x/branches

**Comment by joncampbell123** [comment]
Agreed.

Anyone here want to keep their branch?

Any branch not claimed will be deleted one by one, starting with the oldest.

**Comment by aybe** [comment]
I have removed two branches that were merged already:

- caret_fix
- xbrz

Renamed my two branches related to vmware-like input to:

- aybe_feature_kbd
- aybe_input_integration

Just keeping them so whenever I look at the problem again I don't have to figure bunch of code.

---

I propose that we nuke all these since they're stalled:

alexat-sdlmain_refactor Updated 2 months ago by joncampbell123   
380
0
 revert-795-mouseintegrationdos Updated 2 months ago by joncampbell123   
492
1
 Shane32-ramdrive_bugfix Updated 6 months ago by Shane32   
2070
0
 develop-win-sdl1-async-hack-201802 Updated 6 months ago by joncampbell123   
2261
0
alexat-nuked-opl Updated 10 months ago by joncampbell123   
3753
0
 heftig-master Updated 11 months ago by heftig   
3768
0
 fxcoudert-master Updated 11 months ago by fxcoudert   
3770
0
 mingw-testme-20170415-2332-hail-to-the-ryzen Updated a year ago by joncampbell123   
3939
1
 martinlindhe-fullscreen-scale-fix Updated a year ago by joncampbell123   
3962
0
 martinlindhe-fix-osx-build Updated a year ago by martinlindhe   
3968
0
 martinlindhe-compile-fixes Updated 2 years ago by martinlindhe   
4027
0

---

And I see that you don't use develop much, rather directly commit to master :)

I guess that's enough for now .

**Comment by aybe** [comment]
see #1918 instead
