### ISSUE TITLE
Remove "self-exec" hack and implement proper emulator reset logic

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#82]
I think it's time for DOSBox to handle reboot by resetting emulator state and restarting the shell rather than forking and exec'ing itself. That hack is just dumb.

**Comment by Jarvik7** [comment]
Hard reset vs soft reset?
Soft reset seems to be a lot more complicated to handle correctly than I would have expected:
ex: https://en.wikipedia.org/wiki/Reset_vector

**Comment by joncampbell123** [comment]
I have the soft reset part implemented. I have the code in place to detect CMOS shutdown byte reset vector tricks. It works well enough that you can use Windows 3.0 & 3.1 with cputype=286 in protected ("standard") mode without problems.

I'm talking about a hard reset of the emulator, at least at the level that actual PC hardware resets state on hard reset. So that would mean CPU register + mode reset, clearing the callback list, re-initializing the BIOS and VGA BIOS, etc.

**Comment by joncampbell123** [comment]
Coming back to this issue: I haven't used the self-exec hack in a long time. Off the top of my head, it's now used only if you're using the dynamic core because the dynamic core uses it's own stack in a way that's incompatible with how most C++ runtimes throw/catch exceptions.

**Comment by joncampbell123** [comment]
There is an emulator reset now.

The self-exec stuff is still there if the user wants to manually trigger it from the menu.
