### ISSUE TITLE
Minor warnings from VS 2017 in 1 July code

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#822]
Probably you know this, but these are the warnings generated by current code from VS2017 running under Windows 10 64:

9>..\src\dos\dos_programs.cpp(756): warning C4018: '>': signed/unsigned mismatch

9>..\src\gui\sdlmain.cpp(5223): warning C4244: '=': conversion from 'const long' to 'Sint16', possible loss of data
9>..\src\gui\sdlmain.cpp(5224): warning C4244: '=': conversion from 'const long' to 'Sint16', possible loss of data

Only three, and they clearly don't really matter, and if this is a needless post, my apologies for wasting bandwidth!

**Comment by joncampbell123** [comment]
Eh, they're not all that important, but worth taking care of at some point.

**Comment by Allofich** [comment]
All warnings for DOSBox-X code are currently taken care of in MSVC builds (VS 2019, not VS 2017, but they raise the same kind of warnings).

Various warnings are still raised for library code used in the compilation. But these and any new warnings are visible at any time, and the warnings above were probably taken care of long ago. This issue can be closed IMO.
