### ISSUE TITLE
machine=pcjr requires minimum 256kb of RAM, when the original PCjr had a minimum of 64kb and typically 128kb

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#823]
Several things to make this occur:
- The video memory segment needs to be movable, instead of hard-coded at segment 1800
- Then when the video memory segment is movable, it needs to be chosen automatically according to user preference (dosbox.conf) and available memory.
- Need to make sure DOSBox-X implements whatever means MS-DOS 3.3 uses to detect PCjr and arrange video memory. machine=pcjr with an MS-DOS 3.3 bootdisk is a bit crashy.

**Comment by Allofich** [comment]
With the recent PCjr memory emulation improvements, is this issue still relevant? Maybe the MS-DOS 3.3 bootdisk part still is.

**Comment by joncampbell123** [comment]
Yes, the code does not yet support PCjr emulation with only 64KB of RAM (which is incompatible with the hardcoded video memory segment 1800:0000)

**Comment by joncampbell123** [comment]
Recent commits allow PCjr emulation with as little as 64KB of RAM and Tandy emulation with as little as 256KB of RAM.

PCjr emulation will omit the "reserved MCB block" around video memory if emulating 128KB or less.
