### ISSUE TITLE
Why aren't the different CPU core included in the solution ?

### ISSUE THREAD

**Issue by aybe** [joncampbell123/dosbox-x#835]
@joncampbell123 

When going through the VS2015 solution, neither of the following folders are included, why ?

```
	C:\Dev\dosbox-x\src\cpu\core_dyn_x86
	C:\Dev\dosbox-x\src\cpu\core_dynrec
	C:\Dev\dosbox-x\src\cpu\core_full
	C:\Dev\dosbox-x\src\cpu\core_normal
```

**Comment by Allofich** [comment]
These are all included now. (I think I may have added them in a pull request a few years ago)
