### ISSUE TITLE
Stating graphics corrupted

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [joncampbell123/dosbox-x#841]
**Describe the bug**
A starting graphics are corrupted.

**To Reproduce**
Simply run dosbox-x

**Screenshots**
![image](https://user-images.githubusercontent.com/17617005/42571872-369b55e8-8553-11e8-8fb3-a073e0987b9d.png)

![image](https://user-images.githubusercontent.com/17617005/42571894-464e7d62-8553-11e8-9766-a745a3c0e8f9.png)

**Environment (please complete the following information):**
 - OS: Linux
 - DOSBox-X release version or commit SHA1 this issue occurred on a50c3beaec1bcc00413717954b9f55dda32d81bb

**Comment by joncampbell123** [comment]
This is a known issue with screen refresh and SDL2.

**Comment by joncampbell123** [comment]
I just fixed this issue in the latest commit. Can you compile from source?

**Comment by tokumeiwokiboushimasu** [comment]
> Can you compile from source?
Yes! The problem is fixed. Thank you.
