### ISSUE TITLE
Slow MinGW Builts

### ISSUE THREAD

**Issue by landloafer** [joncampbell123/dosbox-x#846]
**Describe the bug**
Slow MinGW Builts

**To Reproduce**
1. a cleaning installation of WFG311
2. ren dosbox.reference.conf to dosbox.conf
3. dosbox-x-windows-20180503-100034-windows-mingw.zip\dosbox-x.exe > 64633 cyc/ms
4. dosbox-x-windows-20180701-103732-windows.zip\bin\x64\Release SDL2.zip\dosbox-x.exe > 51238 cyc/ms
5. dosbox-x-windows-20180701-103732-mingw.zip\dosbox-x-windows-20180701-103732-windows-mingw-sdldraw.exe > 14833 cyc/ms

**Screenshots**
![1](https://user-images.githubusercontent.com/39210397/42681424-386a5b54-86ba-11e8-84e7-e68bbb9c9a05.png)
dosbox-x-windows-20180503-100034-windows-mingw.zip\dosbox-x.exe > 64633 cyc/ms

![2](https://user-images.githubusercontent.com/39210397/42681432-3bbd33da-86ba-11e8-829b-5db308d7010a.png)
dosbox-x-windows-20180701-103732-windows.zip\bin\x64\Release SDL2.zip\dosbox-x.exe > 51238 cyc/ms

![3](https://user-images.githubusercontent.com/39210397/42681438-3f084b4c-86ba-11e8-98a2-fdcf6df65226.png)
dosbox-x-windows-20180701-103732-mingw.zip\dosbox-x-windows-20180701-103732-windows-mingw-sdldraw.exe > 14833 cyc/ms

**Environment (please complete the following information):**
 - Operating system
Windows 7 Professional SP1 64-bit
Intel Core i5-4570 @3.2GHz
10 GB RAM

**Comment by yksoft1** [comment]
build-mingw scripts seemed not to use any optimize options for gcc and configure.ac also specified none.
There is no doubt that the generated executables will be slow.
