### ISSUE TITLE
Broken filepaths on Windows XP - mount-imgmount don't work 

### ISSUE THREAD

**Issue by Corak667** [joncampbell123/dosbox-x#852]
tried Mount and Imgmount - but it simply don't work now on Windows XP. Results always:
"Directory don't exist"
"The image must be on a host or local drive"
Tried
http://imagizer.imageshack.com/img921/1773/3kss1H.png

On Win7 - normally mounts.

**Comment by joncampbell123** [comment]
Are you running the normal (non-MinGW) builds on Windows XP?

There's a known issue where Microsoft VS2017 compiled binaries "can" run on Windows XP but vital C runtime functions like stat() don't work on anything below Windows Vista.

**Comment by Corak667** [comment]
Yes, right tried latest non-mingw builds. On Mingw - paths work normally.
Is there any fix for VS2017 or way to use VS2010?

**Comment by joncampbell123** [comment]
Nope. _stat() in the C runtime has been broken on Windows XP since VS2015. Microsoft doesn't appear to be interested in fixing it, if it's been broken for now 3 years.

**Comment by joncampbell123** [comment]
Since my primary development platform is Linux and since MinGW builds work despite that, I don't care enough to work around it.
