### ISSUE TITLE
DOSBox-X becomes unresponsive when running MSD (Microsoft Diagnostics) if machine=pcjr

### ISSUE THREAD

**Issue by Allofich** [joncampbell123/dosbox-x#855]
**Describe the bug**
MSD (Version 2.10, included with Microsoft Windows for Workgroups 3.11) freezes at the initial "MSD is examining your system ..." screen and DOSBox-X becomes unresponsive if using `machine=pcjr`. This happens in builds since mid-February.

**To Reproduce**
1. Set `machine=pcjr`.
2. Run `MCD.EXE` in the installation folder of Microsoft Windows for Workgroups 3.11.

**Expected behavior**
Program starts normally.

**Environment (please complete the following information):**
 - Windows 7 64-bit.
 - Commit fea9554 (latest as of now), as well as all the releases I tried back until
"DOSBox-X release 0.82.3 2018-02-13 23:12", in which the problem does not appear. It doesn't happen in the releases I tested before that. In all cases I used the x64 SDL release.
 - Default settings except for
`machine=pcjr`

**Additional context**
I wanted to test if the new keyboard code for PCjr might have fixed https://github.com/joncampbell123/dosbox-x/issues/11, but then I encountered this problem.

From the log file:
  23278691       EXEC:Execute msd.EXE 0
  23278691       FILES:file open command 0 file msd.EXE
  26209502 ERROR DOSMISC:DOS:65:Extended country information call 6506
  26210377 ERROR DOSMISC:DOS:65:Extended country information call 6501
  26216518 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=160A
  26216524 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1600
  26216530 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1700
  26216536 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4680
  26216661       DOSMISC:Call is made for list of lists - let's hope for the best
  26216749 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1100
  26216762 ERROR MISC:DOS:Setting country code not supported
  26244557 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=160A
  26244563 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1600
  26244569 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=1700
  26244575 ERROR DOSMISC:DOS:INT 2F Unhandled call AX=4680
  27911766 ERROR BIOS:INT15:Unknown call ax=D804
  27911906 ERROR FPU:8087 only fpu code used esc 3: group 4: subfuntion :1
  27949262       BIOS:INT15:Function 0x88 Remaining 0000 kb
MCB chain no longer goes to end of memory (corruption?), not linking in UMB!

**Comment by Allofich** [comment]
By the way in that last version I found that works (commit 15895b3), issue https://github.com/joncampbell123/dosbox-x/issues/11 is still happening.

**Comment by joncampbell123** [comment]
I'm not sure what the issue is, even 3 years later. I'll dig out MSD.EXE again.

**Comment by Allofich** [comment]
Just to be clear (perhaps you already know), when I wrote "unresponsive" I meant that that DOSBox-X freezes and the process has to be terminated, not that the keyboard is unresponsive. The program doesn't even start up properly since that release from mid-February this year.

**Comment by joncampbell123** [comment]
Bring up DOSBox-X, then the console, and see what the console says when it's hung

**Comment by joncampbell123** [comment]
Ah, it's a problem with MSD calling into XMS and causing memory corruption, and DOSBox-X's XMS emulation to hang.

It works with machine=pcjr if you also add under the [dos] section xms=false

**Comment by joncampbell123** [comment]
The first and obvious fix is that machine=pcjr should disable XMS emulation because, well, the PCjr doesn't have extended memory... or expanded memory... or UMB and HMA for that matter. It is an 8088 after all.

**Comment by joncampbell123** [comment]
Funny, MSD.EXE won't even run with less than about 400KB of RAM. I don't think MSD is even written to recognize the PCjr. It thinks it's an "unknown CGA".

**Comment by joncampbell123** [comment]
When cputype=8086, MSD thinks DOSBox-X is a NEC V20 :)

**Comment by joncampbell123** [comment]
Okay... machine=pcjr and xms=true works with MSD only when cputype=8086

**Comment by joncampbell123** [comment]
The problem seems to be related to umb=true and machine=pcjr. Adding code to force disable UMB emulation in PCjr mode seems to fix it.

**Comment by joncampbell123** [comment]
It seems MSD.EXE does recognize the PCjr.

![msd_000](https://user-images.githubusercontent.com/6245486/42904346-982139e6-8a89-11e8-8d19-5cd93bc01326.png)

**Comment by Allofich** [comment]
Thanks, the issue no longer happens.

**Comment by joncampbell123** [comment]
Then it is fixed.

The alternate MCB behavior with machine=pcjr is incompatible with UMB emulation.

Going forward, umb=true no longer has any effect if machine=pcjr.
