### ISSUE TITLE
What are the different functions in them?(dosbox,dosbox-x release,dosbox-x release SDL2)

### ISSUE THREAD

**Issue by leoxxx** [joncampbell123/dosbox-x#857]
As the title. Especially release and release SDL2.

**Comment by joncampbell123** [comment]
Release and Debug refer to the build modes offered by VS2017.

SDL2 means it was compiled against SDL 2.x instead of SDL 1.x

Mingw means it was compiled for Windows using GCC+MinGW instead of VS2017.

**Comment by leoxxx** [comment]
THX.

**Comment by landloafer** [comment]
hx-dos, mingw, lowend, sdl2, sdldraw & x64, how to choose?

**Comment by leoxxx** [comment]
> How to compile in general
-------------------------

General Linux compile (FFMPEG/libav support required)
./build-debug


General Linux compile if FFMPEG/libav not desired
./build-debug-no-avcodec


MinGW compile (on Windows, using MinGW64) for 32-bit Windows XP
./build-mingw


MinGW compile (on Windows, using MinGW64) for 32-bit Windows XP, lower-end systems that lack MMX/SSE
./build-mingw-lowend


MinGW compile (on Windows, using MinGW, not MinGW64) to target MS-DOS and the HX DOS extender
./build-mingw-hx-dos

NOTICE: Use the 32-bit toolchain from the main MinGW project, not the MinGW64 project.
        Binaries compiled with MinGW64 have extra dependencies not provided by the HX DOS extender.


Visual Studio 2017 compile for 32/64-bit Windows Vista or higher
Use the ./vs2015/dosbox-x.sln "solution" file and compile.
You will need the DirectX 2010 SDK for Direct3D9 support.

As of 2018/06/06, VS2017 builds (32-bit and 64-bit) explicitly require
a processor that supports the SSE instruction set.

Visual Studio Code is supported, too.

Check the README.Windows file for more information about this platform.


XCode (on Mac OS X, from the Terminal) to target Mac OS X
./build-debug
