### ISSUE TITLE
VS2017 build errors in bitop.cpp fatal error C1001

### ISSUE THREAD

**Issue by yxmline** [joncampbell123/dosbox-x#867]
dosbox\build\dosbox-x\src\gui\bitop.cpp(10): fatal error C1001: An internal error has occurred in the compiler

CTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASHCTIPlugin::InvokeCallback=APPCRASH

**Comment by joncampbell123** [comment]
Which compiler is this, and what system?

**Comment by yxmline** [comment]
win10 vs2017 15.8.1
Switch PlatformToolset v141 to V140
To compile and pass.

**Comment by joncampbell123** [comment]
V140 is the toolset for targeting Windows XP if I recall?

I guess by the internal error it doesn't like the compile-time static asserts to ensure the bitop constexpr functions work correctly. You can #if 0 out the code in that function if it helps to compile.

**Comment by yxmline** [comment]
V140 not support XP

**Comment by joncampbell123** [comment]
All I can say at this point is compile with v141.

Can you provide the _MSC_VER value v140 uses to compile with?

It may be possible to use a #if block around it to allow all but v140 to compile that self-test code.

**Comment by joncampbell123** [comment]
_MSC_VER is a compiler-provided #define that can be used to identify what version of Microsoft C++ the code is being compiled against. It's a numeric value.

**Comment by yxmline** [comment]
_MSC_VER = 1900

**Comment by joncampbell123** [comment]
Does v141 provide a different value?

**Comment by joncampbell123** [comment]
Good.

When I have free time today I'll add an #if block around that self-test code to exclude _MSC_VER = 1900

**Comment by joncampbell123** [comment]
Please try commit b5a91272ce7a3ef1b0da7c1e6ffd4969254ee54b

**Comment by yxmline** [comment]
Not solved - -

**Comment by yxmline** [comment]
solved https://github.com/joncampbell123/dosbox-x/commit/2e4c6f463b926bd0e3850a9a306b749767726bd5

**Comment by yksoft1** [comment]
By the way, how do I benchmark the performance of Dosbox-X? I want to know if there are any difference on performance of Dosbox-X builds between MinGW.org GCC 4.x,  6.3, mingw-w64 7.3, and Microsoft compilers, and GCC option -O2 and -O3.

**Comment by yxmline** [comment]
hard to say
