### ISSUE TITLE
Enabling memory aliasing (config option memalias) crashed DOSBox-X on startup

### ISSUE THREAD

**Issue by Sethur** [joncampbell123/dosbox-x#869]
Hi,

while trying to get a an old DOS PCB design application to run, I stumbled across a bug when enabling memory aliasing.

The application I am trying to run came before DOS extenders (around or shortly before the 386 release) and I think it plays dirty tricks with memory. There is an option to use EMS or alternatively INT 15, AH=87 to get memory above 1 MB. In the later case, XMS needs to be turned of, because there is currently no options of emulating the required `HIMEM.SYS /INT15=<reserved space in kB>` switch. 

Unfortunately, there are random crashes and weird behavior with both options. For example, when activating `zero memory on ems memory allocation`, the program does not work at all and there are tons of consecutive `ERROR CPU:Write 0 to rom at 1c0170` messages. If memory is not zeroed, it works partially but with some actions it will stop responding and run into a EMS allocate memory loop (calling INT 67, AH=44 over and over again.

So while playing around with this I tired to turn on memory aliasing, and when setting `memalias=24` and `cputype=386` or `cputype=486`, DOSBox-X will crash very early on startup with the message:
`Unable to map ROM region as ROM alias`, although most other options are on their defaults. Strangely enough `memalias=26` does not produce the crash for both `cputype=386` and `cputype=486`

Any ideas how to fix that?

**Comment by joncampbell123** [comment]
You may try turning off EMS and XMS and running "A20GATE ON" before running the program.

**Comment by joncampbell123** [comment]
It may also help to disable HMA and UMB as well.

The program may also have faults related to base memory address if loaded too low, try LOADFIX before running the program.

**Comment by Sethur** [comment]
Thanks for the helpful hints! In INT 15h, AH 67h mode with EMS,XMS,HMA and UMB turned of, it seems to run a little bit longer before crashing, but this may be coincidental. Loadfix also seemed to have an influence on when the crashes are occurring.

It definitely seems to be a memory issue, since I can clearly see that upon crashing, the debugger runs into a "reserve memory" loop, both for EMS mode and INT15h mode.

Is there any way of getting more console info on EMS page mappings and INT15h mem allocations?

Also, the `memalias=24` crash is still there. Not sure how many programs need this, but if it's not working the option should be removed or fixed.

**Comment by joncampbell123** [comment]
Bring up the debugger.

Type "DOS EMS", it will show you the EMS allocation and page frame mapping.

**Comment by Sethur** [comment]
That's what I was looking for, thank you. When I run into a crash I get something like this, so it really seems to be memory related:

```
         0 ERROR MISC:EMS memory (type EMM386) handles:
         0 ERROR MISC:Handle Address  Size (bytes)    Name
         0 ERROR MISC:     0 00110000 00060000
         0 ERROR MISC:     1 00170000 00100000
         0 ERROR MISC:EMS page frame 0x000e0000-0x000effff
         0 ERROR MISC:Handle Page(p/l) Address
         0 ERROR MISC:     1    0/  19 000e0000-000e3fff virt -> 001bc000-001...
         0 ERROR MISC:--        1/     000e4000-000e7fff
         0 ERROR MISC:--        2/     000e8000-000ebfff
         0 ERROR MISC:--        3/     000ec000-000effff
```

**Comment by joncampbell123** [comment]
memalias has been fixed not to cause a crash on startup, the BIOS now makes room for itself.
