### ISSUE TITLE
sdlmain.cpp fails to compile

### ISSUE THREAD

**Issue by k5jat** [joncampbell123/dosbox-x#874]
**Describe the bug**
On a fresh pull, sdlmain.cpp fails to compile

**To Reproduce**
1. Run "git pull"
2. Run ./cleanup
3. Run ./config.guess
4. Run ./configure
5. Run make

**Expected behavior**
Error free compile.

**Environment (please complete the following information):**
 - Linux Mint 18.2
 - DOSBox-X fresh git pull
 - gcc 5.4.0

**Additional context**
Here is a copy from the error down...
depbase=`echo sdlmain.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -I../../src/aviwriter "-DRESDIR=\"\"" -I../../src -I../../src/mt32 -Wno-extended-offsetof   -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wconversion-null   -pedantic   -Wextra   -Wall   -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -g -std=gnu++0x  -O2 -msse  -Wall   -Wextra   -pedantic   -Wconversion-null   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast   -Wno-extended-offsetof  -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -mmmx -msse -msse2 -MT sdlmain.o -MD -MP -MF $depbase.Tpo -c -o sdlmain.o sdlmain.cpp &&\
mv -f $depbase.Tpo $depbase.Po
sdlmain.cpp:112:4: error: #error This code must be compiled using the SDL 1.x library provided in this source repository
 #  error This code must be compiled using the SDL 1.x library provided in this 
    ^
sdlmain.cpp: In function ‘Bitu GFX_SetSize(Bitu, Bitu, Bitu, double, double, GFX_CallBack_t)’:
sdlmain.cpp:1460:10: warning: unused variable ‘bpp’ [-Wunused-variable]
     Bitu bpp = 0;
          ^
sdlmain.cpp: At global scope:
sdlmain.cpp:1894:30: warning: unused parameter ‘capture’ [-Wunused-parameter]
 void CaptureMouseNotify(bool capture)
                              ^
sdlmain.cpp: In function ‘void GFX_EndUpdate(const Bit16u*)’:
sdlmain.cpp:2364:47: error: ‘SDL_HAX_NOREFRESH’ was not declared in this scope
         sdl.surface->flags &= ~((unsigned int)SDL_HAX_NOREFRESH);
                                               ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-extended-offsetof’
cc1plus: warning: unrecognized command line option ‘-Wno-int-to-void-pointer-cast’
cc1plus: warning: unrecognized command line option ‘-Wno-address-of-packed-member’
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-fallthrough’
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-fallthrough’
cc1plus: warning: unrecognized command line option ‘-Wno-address-of-packed-member’
cc1plus: warning: unrecognized command line option ‘-Wno-int-to-void-pointer-cast’
cc1plus: warning: unrecognized command line option ‘-Wno-extended-offsetof’
Makefile:420: recipe for target 'sdlmain.o' failed
make[3]: *** [sdlmain.o] Error 1
make[3]: Leaving directory '/home/fireball/dosbox-x/src/gui'
Makefile:515: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/fireball/dosbox-x/src'
Makefile:389: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/fireball/dosbox-x'
Makefile:326: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yxmline** [comment]
update gcc 7.3.0

**Comment by yksoft1** [comment]
Build and install joncampbell123's modified SDL in vs2015/sdl.
Or just use build-debug.

**Comment by joncampbell123** [comment]
DOSBox-X has it's own version of SDL1 in-tree that it needs to compile against.

This version has numerous bug fixes, enhancements, and functional additions needed by DOSBox-X.
