### ISSUE TITLE
(Win10) set sdl_videodriver=directx startup error / Windows builds cannot handle both shift keys at once

### ISSUE THREAD

**Issue by Pantalaim0n** [joncampbell123/dosbox-x#876]
**Describe the bug**
For some reason, I have to set SDL_VIDEODRIVER=DIRECTX to be able to use both SHIFT keys simultaneously ([source](https://www.vogons.org/viewtopic.php?t=33088)). This has worked in the past (last version I used was 2018-01-07 14:09) but is broken in version 0.82.9. Upon starting Dosbox-X It crashes with an alert box 'Can't init SDL No available video device'.

**To Reproduce**
1. Open a command prompt
2. Type 'SET SDL_VIDEODRIVER=DIRECTX'
3. Run dosbox-x

**Expected behavior**
Dosbox-X starts as usual and I can use both SHIFT keys simultaneous.

**Screenshots**
![image](https://user-images.githubusercontent.com/25281933/44998541-bdeaf200-afb6-11e8-9ab3-e51e820d283b.png)

**Environment (please complete the following information):**
 - Windows 10 (x64)
 - dosbox-x-windows-20180901-124401-windows.zip
 - Default ```dosbox.conf```

**Additional context**
Problem exists in both SDL1 and SDL2

**Comment by joncampbell123** [comment]
The question is why DirectX is even needed to read either shift key state, when the standard messages WM_KEYUP/WM_KEYDOWN should convey those anyway in a way that DOSBox-X can tell left from right shift.

I don't see a similar problem in Linux though.

Can you try bringing up the mapper, and tapping left/right to confirm they light up correctly?

**Comment by joncampbell123** [comment]
It might also help to know if you have the standard US keyboard layout or are using a different one.

**Comment by Pantalaim0n** [comment]
The mapper lights up the SHIFT keys correctly for left and right, but it doesn't light up the second while holding the first. I'm using a standard US keyboard.

**Comment by Pantalaim0n** [comment]
To clarify:
SDL1: Both SHIFT keys simultaneous doesn't work. The usual SET SDL_VIDEODRIVER=DIRECTX fix crashes Dosbox-x with said error message.
SDL2: Both SHIFT keys do work simultaneous. However, if SDL_VIDEODRIVER=DIRECTX is set anyways, Dosbox-x silently fails.

**Comment by Pantalaim0n** [comment]
I've compiled from source just now and I can confirm both SHIFT keys work simultaneously in SDL1. I've tested it in Win10 and Win7, without issues.

Having set sdl_videodriver=directx still causes the error, but the main issue is now fixed.
