### ISSUE TITLE
Save/load state system added, currently very minimal and experimental.

### ISSUE THREAD

**Issue by ghost** [joncampbell123/dosbox-x#886]
But why the user cannot see that these functions exist in the menus?

Why the user doesn't know what keys needs to be pressed to invoke these functions?

**Comment by joncampbell123** [comment]
They can be seen in the mapper interface.

It works, but it's not yet good enough to appear in the menus.

Some games, like Xargon, don't work with it at all.

**Comment by buruto** [comment]
I understand you, but you could at least say that [here](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-windows-v0.82.9)

**Comment by frank-deng** [comment]
Is it possible to save the state into a file, then close the emulator today and load the state the next day?

**Comment by joncampbell123** [comment]
I don't think the save/load state system saves enough information to do that yet.

**Comment by Allofich** [comment]
Save/load state are in the menu now, and "save the state into a file, then close the emulator today and load the state the next day" is in line with the general "saved state doesn't load correctly later" issue that is in other issue reports.
