### ISSUE TITLE
Dunnos & Feature Request

### ISSUE THREAD

**Issue by inukaze** [joncampbell123/dosbox-x#892]
1 - Why here i just have "Surface" output. 
i have an "Nvidia GT 620" max "OpenGL 3". but i don't see the options "OpenGL" or "OpenGL v2" or "OpenGL v3" or something similar. why ?

Feature Request -> you can add OpenGL ? to the menu Output

2 - When i try to run "Bugs Bunny & Taz : Time Busters". the Game Hang-up here:
[![dosbox-x-0.82.9-sdl2-bblit2.png](https://i.postimg.cc/vZ0LF7qc/dosbox-x-0.82.9-sdl2-bblit2.png)](https://postimg.cc/NKrrRXwc)
[Output](http://pasted.co/8a689ff5)

Note : this game can be played using : VirtualBox + Addons + Windows XP + Bugs Bunny & Taz : Time Busters. and disabling "Mouse Integration".

Try to run with Wine, are really hard, because evers needs 16 Bits, and if i ran another Xorg in 16 Bits, and modify the Wine registry to 16 Bpp, says it not set to 16 bpp yet, when you try to run. the same with MotoRacer. and anothers games, runs exclusive in 16 Bpp under Windows9X.

3 - I am Playing MotoRacer Interactive Demo (Because i download de GOG Version just for Test, and not able to access to Audio CD, because Windows 95 don't have CDROM Drive, and i delete it, and download the demo from -> [Here](http://www.bestoldgames.net/moto-racer)) 

During the Game i change on menu:

CPU -> Core -> [Auto Cyles] (i set off), Normal Core, or Simple Core (Works a little better), in Full Core (works a little worse than normal]

CPU -> Type -> Pentium / Pentium Pro or / Pentium MMX (for me pc is the same result)
Set the cycles in "18360" or "18432" for play decent, the sound is laggy and choppy. and the window borders says FPS : 7. but i feel i more like 15 or 20. max 23 FPS.

Here a screenshot : 
[![dosboxxmotoracerdemo.png](https://i.postimg.cc/XN5ZcK99/dosboxxmotoracerdemo.png)](https://postimg.cc/bdzNqtCv)

Feature Request -> In a next vesion, in main the menu, you can add a menu called "Images" to set in "0" (For Floppy), "1" & "2" for HDD, and "3" for cdrom ?

Feature Request -> you can add an "Override" Section and when the user launch an specific app, read the override, to set the cpu : type, core, and cycles for a specific app? and the users of the comunnity determine the better values.

Similar to VisualBoyAdvance or VisualBoyAdvance-M, override.ini file for specific titles.

like when i add this lines to autoexec section: 
```
imgmount 0 "~/dos622.ima" -t floppy -fs none
imgmount 2 /media/Audiovisual/msdos/c/so/win9x.img -size 512,63,64,1023 -t hdd -fs none
imgmount 3 "~/My ISO Files/Inukaze.iso" -t iso -fs iso
```

or something like that. and a method to Windows 9X, access to a virtual cdrom, an access directly to the mounted image in "3" ?

4 - Why i can't compile SDL1 version ?
```
./autogen.sh
make clean ; ./configure --disable-avcodec --enable-sdl1 --prefix=/media/Compartido/Videojuegos/Msdos/dosbox-x/0.82.9/sdl1 ; make all ; make install
```
[Output Here](http://pasted.co/91df50b8)

Note : i ever put the binaries of dosbox-x in diferrent prefixes. and after i add to system with simbolic link, like : 

su -c "ln -s $PWD/dosbox-x /usr/bin/dosbox-x0829-sdl2" root
why the configuration file, in this case "$HOME/.dosbox/dosbox-0.82.9.conf", never is autogenerated ?
where is the default template of configuration file ?

Thanks for readme.

**Comment by joncampbell123** [comment]
You need to use the SDL builds for OpenGL, SDL2 builds do not yet support OpenGL.

3Dfx emulation with SDL2 builds is not well tested.

**Comment by joncampbell123** [comment]
DOSBox-X should read dosbox.conf from the current working directory first, and it will also try to read it from your home directory second.

**Comment by inukaze** [comment]
> You need to use the SDL builds for OpenGL, SDL2 builds do not yet support OpenGL.
> 
> 3Dfx emulation with SDL2 builds is not well tested.

Here my test with 3DFX Running from Windows 95 : 
Voodoo 1 Drivers [![DOSBOXX3_DFX_001.png](https://i.postimg.cc/fbHT7Czj/DOSBOXX3_DFX_001.png)](https://postimg.cc/2qZDr4BV)

Tomb Raider 3DFX Demo -> Slow
[![dosbox-x-3dfx.png](https://i.postimg.cc/KcMstYQR/dosbox-x-3dfx.png)](https://postimg.cc/JtRqLMfL)

Turok 2 : Seeds Of Evil Demo -> Slow
[![DOSBOXX3_DFX_002.png](https://i.postimg.cc/G2H3XD90/DOSBOXX3_DFX_002.png)](https://postimg.cc/cgGNHrQT)
[![DOSBOXX3_DFX_003.png](https://i.postimg.cc/Kc3vLtdB/DOSBOXX3_DFX_003.png)](https://postimg.cc/LhRpFg48)
[![DOSBOXX3_DFX_004.png](https://i.postimg.cc/909mhjGJ/DOSBOXX3_DFX_004.png)](https://postimg.cc/p52bf4cF)

GLQuake -> Very Slow!
[![Q23dfx.png](https://i.postimg.cc/430B9C96/Q23dfx.png)](https://postimg.cc/2q44sKTy)

Deathkartz Demo -> Very slow!
[![dosbox-x-3dfx-deathkartz.png](https://i.postimg.cc/CK5c5MzM/dosbox-x-3dfx-deathkartz.png)](https://postimg.cc/KKXPs2PC)

Final Fantasy 7 Demo-> Very Slow!, some glitches during the fight.
[![dosbox-x-sdl2-ff7_001.png](https://i.postimg.cc/BbHY3htx/dosbox-x-sdl2-ff7_001.png)](https://postimg.cc/QKNkkJQt)
[![dosbox-x_Q23dfx.png_https_i.postimg.cc_430_B9_C96_Q23dfx.png.png](https://i.postimg.cc/kgn1rvCb/dosbox-x_Q23dfx.png_https_i.postimg.cc_430_B9_C96_Q23dfx.png.png)](https://postimg.cc/dLxmrdLs)

Half-Life Demo -> Very Slow!
Outlaws Demo -> Slow!
Quake 2 Demo -> Very Slow!
[![Q23dfx.png](https://i.postimg.cc/430B9C96/Q23dfx.png)](https://postimg.cc/2q44sKTy)

Rogue Squadron 3D -> Hang up dosbox.
Rollcage -> Very Slow!
Shogo: Mobile Armor Division - PC GAMER DEMO -> Very Slow!
Wipeout XL -> The launcher become dosbox extremly slowly!

Quake 3 Arena Demo -> Can't start don't found C:\Windows\System\3dfxvgl.dll, C:\Windows\System\opengl32.dll

From DOSBOX 0.82.9 the games like Tomb Raider 3DFX Demo, i can play perfectly, and better rendered than DOSBOX-ECE. 

Another titles like : Turok 1 & 2, Deathkartz, a lot with 3DFX Support, can be playable perfectly from Wine 1.2 (32 Bits) + nGlide , except by titles need exclusive a 16 Bpp Wine.
