### ISSUE TITLE
Build on macOS Mojave - lavcodec missing?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#895]
I have no trouble building DOSBox-X (and my custom build) under macOS High Sierra, but I can't build on a clean Mojave system (with autoconf, automake, and libtool installed). I get this error:

`g++  -I/Users/Edward/Development/dosbox-x-master/vs2015/libpng/linux-host/include -I/Users/Edward/Development/dosbox-x-master/vs2015/zlib/linux-host/include -std=gnu++0x  -O2 -msse  -Wall   -Wextra   -pedantic   -Wconversion-null   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast   -Wno-extended-offsetof   -mmmx -msse -msse2  -L/Users/Edward/Development/dosbox-x-master/vs2015/libpng/linux-host/lib -L/Users/Edward/Development/dosbox-x-master/vs2015/zlib/linux-host/lib  -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a output/liboutput.a aviwriter/libaviwriter.a xBRZ/libxbrz.a mt32/libmt32.a -framework CoreMIDI -framework AudioUnit -framework AudioToolbox -L/Users/Edward/Development/dosbox-x-master/vs2015/sdl/linux-host/lib /Users/Edward/Development/dosbox-x-master/vs2015/sdl/linux-host/lib/libSDLmain.a /Users/Edward/Development/dosbox-x-master/vs2015/sdl/linux-host/lib/libSDL.a -Wl,-framework,OpenGL -Wl,-framework,Cocoa -Wl,-framework,ApplicationServices -Wl,-framework,Carbon -Wl,-framework,AudioToolbox -Wl,-framework,AudioUnit -Wl,-framework,IOKit -lcurses -lz -lpng -lz -lpcap -lavcodec -lavformat -lavutil -lswscale  -framework OpenGL
ld: library not found for -lavcodec
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

This is very puzzling. Is there an easy solution?

**Comment by joncampbell123** [comment]
It means you don't have FFMPEG libraries installed on your system.

That's OK, use ./build-debug-no-avcodec to disable FFMPEG support.

**Comment by emendelson** [comment]
OK - thank you! I'll try to install the FFMPEG libraries later, as I suppose it can't hurt to have them, and I'd like to have a non-debug build...
