### ISSUE TITLE
Build on macOS Mojave - blank screen 

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#896]
As instructed in another message, I built a debug version of current code in macOS Mojave. The resulting executable displays a blank window. It accepts keyboard input; I can shut it down by entering EXIT, but nothing is visible in the window.

The console reports this:

--------------

LOG: Early LOG Init complete
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 0.82.10
LOG: Mac OS X EXE path: /Users/edward/Development/dosbox-x-master/src/dosbox-x
LOG: Mac OS X Resource path: 
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
LOG: USING AVI+ZMBV
LOG: Pentium CMPXCHG8B emulation is enabled
LOG: VOODOO LFB now at d0000000
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
LOG: Allocated APM BIOS pm entry point at f000:e8ac
LOG: Writing code to fe8ac
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: surface consider=640x480 final=640x480
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
LOG:    2969642 ERROR BIOS:Keyboard layout file auto not found
LOG:    2969642 ERROR BIOS:Keyboard layout file auto not found
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x01e9 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x0217 sz=0x009a
LOG: COMMAND.COM stack:                0x0231
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: surface consider=720x400 final=720x400
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)

---------------

I haven't the faintest idea of how to interpret this, except that "Screen report" looks a bit worrisome.

**Comment by joncampbell123** [comment]
Does output=surface or output=opengl work?

The screen report is just debug output of new code written to determine your screen's DPI and size so that future code can size elements (such as the SDL2 menus) properly for your display.

I only have the code working with Linux/X11 at the moment with plans to add Windows detection later.

**Comment by emendelson** [comment]
Neither of those output= options work, I'm sorry to say. I created a two-line dosbox.conf in the same folder with the lines [sdl] and output= and launched the executable from the command line.

**Comment by cimarronm** [comment]
I'm seeing the same issue in macOS Mojave

**Comment by joncampbell123** [comment]
I'm going to need some external help with this issue then, the only hardware I have for Mac OS X development is a Mac Mini from 2016 with OS X Sierra on it.

**Comment by Midar** [comment]
This seems to be a bug in SDL. While SDL2 has a fix, there is none for SDL1 yet.

**Comment by emendelson** [comment]
I don't pretend to know anything about this, but does this possibly help (or does it help only with SDL2):

http://people.bath.ac.uk/abscjkw/ComputerPrograms/C++programs/OpenGL/MojaveOpenGL.cpp

**Comment by emendelson** [comment]
And I don't know if you want to mess with your Mac Mini, but a 2016 Mac Mini can certainly upgrade to Mojave if you want. Mojave supports Mac Mini models as far back as late 2012.

**Comment by joncampbell123** [comment]
It looks like the option to upgrade to Mojave just appeared on the mac mini.

**Comment by joncampbell123** [comment]
I'm just going to upgrade to Mojave and hope the future builds work OK under prior versions of Mac OS X. I don't care enough about Mac OS X to worry about older versions too much.

**Comment by joncampbell123** [comment]
No.... not seeing that here, even under Mojave.
![mojaveok1](https://user-images.githubusercontent.com/6245486/50100091-75a5b780-01d4-11e9-8ea6-3762ca261d82.png)

**Comment by joncampbell123** [comment]
SDL2 builds are OK as well, as is the OpenGL mode.

**Comment by joncampbell123** [comment]
Is there any kind of high DPI or high bit depth / HDR setup on your display?

**Comment by emendelson** [comment]
Did you build it under Mojave? The bug doesn't show up with builds made under earlier versions - only with builds made in Mojave itself. (Although I haven't tried building it since the initial release - will try again if you don't see the problem when building under the latest Mojave version.)

**Comment by joncampbell123** [comment]
So this is a SDK issue then.
Recompiling the binary on Mojave does indeed make a blank screen.

**Comment by joncampbell123** [comment]
The strange thing is that the code I wrote in dosbox-rewrite (cocoa1.cpp and cocoa2.cpp work just fine still in Mojave) and those were based on what SDL1 was doing with the Cocoa API.

**Comment by joncampbell123** [comment]
Uh, the other possibility is this context check that also seems to prevent drawing on the window (where it says "uhoh you might be rendering from another thread").

**Comment by joncampbell123** [comment]
Please compile the latest commit, check that it still works on older Mac OS X. I got it to work on Mojave. Some things changed that broke SDL1, and applications can't update the contents of their windows anymore unless responding to NSView drawRect.

**Comment by joncampbell123** [comment]
What I mean by that is that the Cocoa API in Mojave seems rebuilt to restrict screen updates only in response to drawRect(). Attempting to update the window any other way doesn't work.

Perhaps this is the magic hack that Apple engineers did to make Mojave more "snappy and responsive" :)

**Comment by emendelson** [comment]
Well, that's impressive! It certainly works. A lot of other projects have been struggling with this. Well done! I built the SDL1 version, and that worked. Am building SDL2 as we speak.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/5208505/50127898-00240080-0241-11e9-9e54-a47ece392363.png">

**Comment by emendelson** [comment]
Yes, it's a MacBook Pro with a Retina display. I copied the the executable to a 2015 MacBook Air (non-Retina), and there it works correctly, with a menu at the top of the SDL2 surface. I can't actually use any of the menu items - the dropdown disappears if I move the mouse into it - but I suppose that will be fixed before long. 

Is there any way to make dosbox-x compensate for the high DPI setting?

**Comment by joncampbell123** [comment]
Not sure, I'll need to develop against a high DPI setup. I might be able to trigger the same if I connect the mac mini to a 4K UHD TV set or anything else with high enough DPI to trigger the same.

**Comment by emendelson** [comment]
Is this relevant to the high DPI issue:

https://wiki.libsdl.org/SDL_CreateWindow

There's a setting there for "SDL_WINDOW_ALLOW_HIGHDPI". I'm not at my Mojave machine so I haven't checked...

**Comment by joncampbell123** [comment]
If I specify the HIGHDPI flag to SDL CreateWindow I still get a pixel doubled window (though not blurry anymore) but I'm not familiar with SDL2 enough to get a 1:1 pixel mapping (in case you want a tiny DOSBox-X window). If I can figure out how to do that then the same "high DPI awareness" option made for Windows can be added to OS X builds.

**Comment by sikthehedgehog** [comment]
https://wiki.libsdl.org/SDL_CreateWindow

> On Apple's OS X you must set the NSHighResolutionCapable Info.plist property to YES, otherwise you will not receive a High DPI OpenGL canvas.

**Comment by joncampbell123** [comment]
I understand that... but DOSBox-X is not using OpenGL in SDL2 builds.

**Comment by sikthehedgehog** [comment]
But the underlying renderer may be. Also actually I think it affects *any* window, not just OpenGL (so the sentence may be misleading).

Anyway, worth a shot to make sure it's indeed set to rule that out.

**Comment by joncampbell123** [comment]
OK. I would prefer to make it a dosbox.conf option like I did on Windows, so if it turns out there's some under-documented API in OS X to flip that switch at startup, I'm all for it. Otherwise, dosbox-x.app is going to have to set that option.

That makes things a little more complicated to develop without running "make dosbox-x.app" all the time.

**Comment by emendelson** [comment]
Just making sure: there's no fix in the code yet, right?

**Comment by joncampbell123** [comment]
Seems like it.

In Windows I was able to get away with calling an API function that says "yes, I am DPI aware" and that's enough to stop Windows from upconverting the DOSBox-X window.

Mac OS X looks like it's serious about the plist setting, so I might as well add it.

**Comment by joncampbell123** [comment]
Adding the key to Info.plist doesn't seem to change anything.

**Comment by joncampbell123** [comment]
I added the plist entries, and while it looks a bit sharper (no interpolation), it's is still scaling the window surface up by 2x.

I think SDL2 is upscaling by 2x now. If anyone can figure out how to tell SDL2 not to do that, that would be nice.

**Comment by joncampbell123** [comment]
However, if I have the entry in the plist and manually modify the SDL1 build to set up the window and views at 1/2 the resolution requested while in HighDPI mode, it does even out the way I want to.

**Comment by joncampbell123** [comment]
I don't know how to handle this in SDL2 but I updated the in-tree version of SDL1 to handle HighDPI displays. "dpi aware" is off by default so that DOSBox-X is usable on a Retina display, but there is also a menu item you can play with to switch it on/off at runtime to your liking.

**Comment by joncampbell123** [comment]
The original problem this issue was filed for was fixed, so I'm going to go ahead and close it. Further discussion on High DPI scaling should continue in another issue.
