### ISSUE TITLE
Compile crash on Arch Linux

### ISSUE THREAD

**Issue by parkerlreed** [joncampbell123/dosbox-x#901]
**Describe the bug**
Latest git no longer compiles on Arch Linux, seemingly due to ffmpeg calls and gcc command line options

**To Reproduce**
1. Build dosbox-x from source
2. Run into compile failure

**Expected behavior**
For the program to compile

**Environment:**
 - Arch Linux
 - a16dff8f1c02ac564cb037387e895b08cc87a296
 - Software versions

gcc 8.2.1+20180831-1
ffmpeg 1:4.0.2-7

**Additional context**
[out.log](https://github.com/joncampbell123/dosbox-x/files/2502270/out.log)

**Comment by joncampbell123** [comment]
hardware.cpp:423:27: error: ‘AV_AV_CODEC_FLAG2_FAST’ was not declared in this scope
      ffmpeg_vid_ctx->flags2 = AV_AV_CODEC_FLAG2_FAST;
                               ^~~~~~~~~~~~~~~~~~~~~~

How did *that* happen?

Replace AV_AV_ with AV_

**Comment by parkerlreed** [comment]
I found the culprit. The AUR package ran a sed but didn't actually check whether it worked

````
  sed -i 's/CODEC_FLAG2_FAST/AV_CODEC_FLAG2_FAST/g' src/hardware/hardware.cpp
````

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dosbox-x-git#n24

Sorry for the bother

**Comment by joncampbell123** [comment]
This is a sed run on your machine at compile time, correct?

**Comment by parkerlreed** [comment]
@joncampbell123 Yeah. It pulls the sources, runs that sed, and then builds. I think they were fixing an older reference but was never updated once your upstream reflected the change.
