### ISSUE TITLE
PC-98: INT DCh with AH=01h and CL=10h not implemented

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#904]
INT DCh with AH=01h and CL=10h seems to be a write string DOS call. The game 蟹味噌 (Kanimiso) cannot clear text screen because the call is not implemented.

![kani_000](https://user-images.githubusercontent.com/1381939/47716228-6222a980-dc85-11e8-9ba0-15939a2242f0.png)

I wrote the following simple terminate and stay resident program that makes the game work properly.

![command_000](https://user-images.githubusercontent.com/1381939/47715608-95643900-dc83-11e8-975f-a961f2c78de4.png)

I could not find documents describing the INT DCh, so this program may be incorrect. I found a text that has a short example code using the INT DCh with AH=01h and CL=10h:
gt10.pdf at http://tepe.tec.fukuoka-u.ac.jp/HP98/studfile/grth/grth.htm

**Comment by joncampbell123** [comment]
I appreciate your help, I cannot find any INT DCh documentation whatsoever except the "extensions" to the interface.

When I have a stretch of time to focus on it, I will boot a PC-98 MS-DOS disk in DOSBox-X, poke at INT DCh through the debugger, and note the memory addresses of each branch point to aid in further reverse engineering INT DCh. My initial attempt months ago revealed the use of lookup tables within the driver to determine what to execute.

**Comment by joncampbell123** [comment]
Most lookup tables are just an array of 16-bit offsets into a segment, though one lookup table was an array of 3 bytes (1 the CL function, 2 the 16-bit offset).

**Comment by joncampbell123** [comment]
To be honest, poking at INT DCh in the debugger was one of the main reasons for getting PC-98 MS-DOS to boot into DOSBox-X, where the debugger can see it.

**Comment by joncampbell123** [comment]
Looking back over the INT DCh stub, AH=1 CL=0x10 as "write a string" makes sense, since AH=0 CL=0x10 was successfully determined to be a "write character" function.

**Comment by hdk1983** [comment]
I found that the INT DCh was different from the AH=9 INT 21h system call about redirection. The output of INT DCh with AH=1 and CL=10h is not redirected by using ">" symbol in a command line.

**Comment by joncampbell123** [comment]
Neither is INT 29h output, I understand.

**Comment by hdk1983** [comment]
It looks OK now. This also fixes blinking text cursor during running NyaHax'93 that might use the same way to hide the cursor.
