### ISSUE TITLE
PC-98: bit7 of 0000:053Ch should be 1

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#905]
bit7 of 0000:053Ch shows a CRT type. 0 for 15kHz, 1 for 24kHz, so should be 1. 大貧民 (Daihimmin) game checks this field to manage game and music speed based on horizontal blank signal but the bit is 0 so the game runs too fast. The game can be downloaded at https://www.vector.co.jp/soft/dos/game/se001269.html

**Comment by joncampbell123** [comment]
The documentation I have says bit 7 of 0000:053Ch is set for a high resolution display, clear for non-hires.

**Comment by joncampbell123** [comment]
Done.
