### ISSUE TITLE
PC-98: bit 6 and bit 3 of 0000:054Ch should be 1

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#906]
bit 6 of 0000:054Ch is same as #905 

bit 3 shows number of user-defined, modifiable fonts. The bit was 0 for old models that only had small RAM for 63 characters. Gajet, a pattern editor can be downloaded at https://www.vector.co.jp/soft/dos/writing/se001839.html, checks the bit and shows an error that the application does not run on PC-9801/E/F/M:

![command_000](https://user-images.githubusercontent.com/1381939/47720708-debb8500-dc91-11e8-918c-d0cdc52f71dd.png)

According to the DOSBox-X source file vga_pc98_cg.cpp, modifiable code range is 0x56xx and 0x57xx, so the bit 3 should be 1.

**Comment by joncampbell123** [comment]
At the time the modifiable range was implemented, I confirmed that on real hardware attempts to write anything other than 56xx and 57xx are silently ignored.

Same as #905, that bit is documented (in what I have) to mean a high resolution CRT, not a 15khz rate.

**Comment by joncampbell123** [comment]
Also according to documentation I have, "high resolution" is said to be much higher than the standard 640x400 video mode used by PC-98, so as far as I know, none of the video modes emulated in DOSBox-X are "high resolution".

**Comment by joncampbell123** [comment]
I just pushed a change that enables the "188+ CG cells" bit.

It's also controllable by a dosbox.conf option.

**Comment by hdk1983** [comment]
> Also according to documentation I have, "high resolution" is said to be much higher than the standard 640x400 video mode used by PC-98, so as far as I know, none of the video modes emulated in DOSBox-X are "high resolution".

No, it is not correct. It is mistakable.

https://www.webtech.co.jp/company/doc/undocumented_mem/memsys.txt
bit6=0, 標準ディスプレイ can be translated as a standard display.
bit6=1, 専用高解像度ディスプレイ, can be translated as a dedicated high-resolution display.
高解像度 means high-resolution, and ハイレゾ also means high-resolution. But ハイレゾ is only used for the mode higher than 640x400. The 400 line mode is called as 高解像度 because of a historically reason: a display used for PC-8001, the ancestor of PC-98, is called as 標準ディスプレイ which only has 200 lines. SW1-1 selects which type of display is used. PC-8800 series models also support both type of displays. When 高解像度 display was released, ハイレゾ mode was not released.

https://ja.wikipedia.org/wiki/PC-9800%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA#cite_note-75
This note also describes the mistakable terms. It says that the ハイレゾ mode resolution is 超高解像度, super high resolution.

**Comment by joncampbell123** [comment]
Done.

Setting that bit also fixes this game.

Prior to the latest commit, the mouse cursor was stuck on the top half of the screen, making it impossible to start the game.

![guest os_000](https://user-images.githubusercontent.com/6245486/47765911-79639600-dc89-11e8-9304-1535c601250f.png)

**Comment by hdk1983** [comment]
Thanks. It looks good now.
