### ISSUE TITLE
PC-98: Corrupted background tiles in Ys II introductory sequence / Divide by zero after loading disk 2

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#908]
**Describe the bug**
As the cutscene pans upward into the sky, past the clouds, the edges of the clouds have garbage 8x8 tiles on them.

**To Reproduce**
1. Boot YS II disk image
2. Observe opening sequence, which is flawless except for garbage tiles on the edges of the clouds when panning upward into the sky.

**Environment (please complete the following information):**
 - machine=pc98
 - NFD disk images of Ys II

![guest os_000](https://user-images.githubusercontent.com/6245486/47817790-d2780c00-dd13-11e8-820b-6eb59c18d9d7.png)

**Comment by joncampbell123** [comment]
At first I thought it was the D88 images provided by @yksoft1, who mentioned NFD to D88 conversion.

Adding NFD disk image support to DOSBox-X did not resolve the issue.

**Comment by yksoft1** [comment]
There are two sets of Ys 2 disk images floating around on Internet. One is bad dump in NFD format, another one is a better dump in FDD format.

**Comment by joncampbell123** [comment]
You're right. I found a VFD image of the game that does not have the corrupted tile data in the intro.

The NFD and D88 images I found appear to be a bad dump.

**Comment by joncampbell123** [comment]
Still crashes with divide by zero after asking for disk swap though.

**Comment by joncampbell123** [comment]
Oh, that is weird...

Debugging Ys II, when loading the second disk after prompting for it, it calls INT 1Bh and reads the timer after the call.

There's some interaction between the timer readback and later code where if the high byte of the timer is certain values, a later divide by 3 causes divide overflow exception.

It seems like sometimes merely debugging the code allows Ys II to start the game without crashing with divide by zero.

**Comment by joncampbell123** [comment]
Got it.

Ys II sets the timer countdown from 0x10000 then calls INT 1Bh, then reads the timer afterward.

Somehow the high byte ends up as part of a later divide by 3, which is usually a large value and causes a divide by zero/overflow exception.

Since the BIOS timer interval call on PC-98 seems based on a fixed interval, and floppy drives need timeouts and delays, it seems logical that INT 1Bh would use that timer interval system.

Having INT 1Bh FDC emulation reset the interval does indeed allow Ys II to start the game without crashing, every time now.

Interesting. It's either a bug or a deliberate anti-debugger trick.

**Comment by yksoft1** [comment]
Nihon Falcom is known to use many copy protection tricks back in 80s. The disk images floating on the Internet did have master check cracked, but some remnants of copy protection might still be there.

**Comment by joncampbell123** [comment]
I've noticed that, yes. Haven't figured it out yet.

**Comment by joncampbell123** [comment]
Just curious, are there disk images of the original uncracked disk out there? Might be fun to put up against DOSBox-X to see what tricks are involved.

**Comment by joncampbell123** [comment]
Ys I seems to get stuck in an endless REP CMPSB for 6 bytes searching through memory. I'm not sure what it's looking for, but it might be a case of mis-reading the disk somehow rather than copy-protection.

**Comment by joncampbell123** [comment]
@yksoft1 The way that part of the code is written in Ys I makes me wonder if the read call in INT 1Bh might be the kind that modifies the C/H/S/sz values in CX and DX on return to reflect the last sector read. Perhaps Ys was written against BIOSes that does that, and it expects the sector value to come back as 3 after starting at 1.

**Comment by joncampbell123** [comment]
Hey, wait...

The directory structure is split across two duplicate sectors 1-5 on track 0, head 1.

D88: trackindex=1 C/H/S/sz=0/0/1/1024 data-at=0x13c0
D88: trackindex=1 C/H/S/sz=0/0/2/1024 data-at=0x17d0
D88: trackindex=1 C/H/S/sz=0/0/3/1024 data-at=0x1be0
D88: trackindex=1 C/H/S/sz=0/0/4/1024 data-at=0x1ff0
D88: trackindex=1 C/H/S/sz=0/0/5/1024 data-at=0x2400
D88: trackindex=2 C/H/S/sz=0/1/1/1024 data-at=0x2810
D88: trackindex=2 C/H/S/sz=0/1/2/1024 data-at=0x2c20
D88: trackindex=2 C/H/S/sz=0/1/3/1024 data-at=0x3030
D88: trackindex=2 C/H/S/sz=0/1/4/1024 data-at=0x3440
D88: trackindex=2 C/H/S/sz=0/1/5/1024 data-at=0x3850
D88: trackindex=3 C/H/S/sz=0/1/1/1024 data-at=0x3c60
D88: trackindex=3 C/H/S/sz=0/1/2/1024 data-at=0x4070
D88: trackindex=3 C/H/S/sz=0/1/3/1024 data-at=0x4480
D88: trackindex=3 C/H/S/sz=0/1/4/1024 data-at=0x4890
D88: trackindex=3 C/H/S/sz=0/1/5/1024 data-at=0x4ca0

**Comment by joncampbell123** [comment]
So INT 1Bh immediately followed by INT 1Bh of the same C/H/S/sz specification means it reads one after the other, in whichever order they go by the head.

**Comment by joncampbell123** [comment]
This is going to require some re-work of the floppy emulation to get Ys I to run, it's not trivial at this time.

**Comment by joncampbell123** [comment]
Further discussion here:
https://github.com/joncampbell123/dosbox-x/issues/912
