### ISSUE TITLE
dosbox-x key rate

### ISSUE THREAD

**Issue by gabrielxfx** [joncampbell123/dosbox-x#909]
Hello, it seems dosbox-x gets a high key press rate, for me, it is too sensible, is there a way to adjust it so I just barely press A for a half a sec and not get AAAAAAAAAAAAAAAAAAAA , I've got problems trying to type commands or programming.

Thanks

**Comment by joncampbell123** [comment]
Are you sure Turbo mode / speed lock isn't enabled?

That can happen if you attempt to type while turbo mode / speed lock is enabled.

The typematic rate is set by default to the normal delay and repeat of a DOS machine.

**Comment by gabrielxfx** [comment]
No, Turbo mode is not enabled, if I enable it it is thousands of times worst

ok, let me explain better, in windows while I am trying this question, if I leave pressed A , it takes a sec before repeating it many times to do AAAAAAAAAA , in Dosbox-x as soon as I leave pressed A it starts right away AAAAAAAAAAAAA, I consider it too fast for my taste, I had a program called quickeys (in DOS era) where you could set in milisecs the delay, can't this be done in dosbox-x ? thanks

**Comment by joncampbell123** [comment]
I see what you mean.

The latest commit just pushed now fixes the initial keyboard pause/repeat values.

**Comment by gabrielxfx** [comment]
Thank you for your time to fix this, I do really appreciate your effort.

**Comment by joncampbell123** [comment]
Before you go, do you mean you acknowledge that the commit was made, or do you mean that you were able to pull the latest commit, compile, and verify the keyboard pause / repeat intervals are satisfactory?

**Comment by gabrielxfx** [comment]
I don't know how to pull latest commit, I just downloaded the .exe file 0.82.8 I am running now,

**Comment by joncampbell123** [comment]
I'll just leave this open until the latest binary is released soon.

**Comment by gabrielxfx** [comment]
alrightie thanks, I'll be waiting for it, sorry

**Comment by joncampbell123** [comment]
Latest release is out, is it satisfactory?

**Comment by gabrielxfx** [comment]
Perfect !!!!!!!!!!!!!!!!!!!!!!!!! keyboard has been fixed !!!!! thank you Jonathan!

Sent from Mail for Windows 10
