### ISSUE TITLE
VGA BIOS size too small

### ISSUE THREAD

**Issue by landloafer** [joncampbell123/dosbox-x#916]
**Describe the bug**
The subject E_Exit dialog is shown and dosbox-x quits when setting any vmemsize>4

**To Reproduce**
1. set vmemsize=6 or 8 or 16
2. execute dosbox-x-20181103-mingw\mingw-sdldraw\dosbox.exe

**Expected behavior**
It was ok in dosbox-x-windows-20180901-140000-windows-mingw

**Screenshots**
![vmz](https://user-images.githubusercontent.com/39210397/47979452-3b89c600-e0fe-11e8-9084-437c663d737d.PNG)

**Environment (please complete the following information):**
 - Windows 7
 - dosbox-x-20181103-mingw
 - vmemsize=6 or 8 or 16

**Comment by joncampbell123** [comment]
The VESA modelist has grown so large that when video memory permits it, it overflows the 12KB allotted to the VGA BIOS area.

**Comment by joncampbell123** [comment]
Try playing with the vesa modelist cap= option.

**Comment by joncampbell123** [comment]
If you can, git pull the latest commit and try again.

**Comment by joncampbell123** [comment]
It's fixed, I can no longer get it to crash with machine=svga_s3 and vmemsize=8
