### ISSUE TITLE
MIDIPORT error 

### ISSUE THREAD

**Issue by leoxxx** [joncampbell123/dosbox-x#917]
I install windows 3.2 in dosbox. It work fine. But I load windows 3.2 with DOSBox-X, it has a error.
As shown in the picture.
![TIM截图20191002112229](https://user-images.githubusercontent.com/5364709/66015972-54b21700-e507-11e9-89c9-410105734137.png)
I change MIDIPORT from 330 to 300 in SB configuration. Then reboot. It can't be loaded with DOSBox-X. Dosbox can load it, but MIDIPORT error. I  have to change MIDIPORT from 300 to 330. 
Dosbox's version is 0.74.
DOSBox-X's version is last version. 
This issue also in previous version.
system: windows 7 x64

Another issue: sometimes DOSBox-X hang when toggle window to another progarm.

**Comment by gr33k** [comment]
Try these drivers - I had issues with some SB16 drivers in Win 3.11 and read SBBASIC.exe is the version that works better: https://www.philscomputerlab.com/uploads/3/7/2/3/37231621/sbbasic.exe

**Comment by leoxxx** [comment]
@joncampbell123 
So great!
It is fixed in 0.82.19.
I've tested x64 (release&SDL2) & mingw-SDL2. It's O.K.

**Comment by leoxxx** [comment]
@joncampbell123
It happend in 0.82.20.

**Comment by joncampbell123** [comment]
Strange, nothing other than typecast fixes were made to sblaster.cpp and mpu401.cpp.

**Comment by leoxxx** [comment]
> 
> 
> Strange, nothing other than typecast fixes were made to sblaster.cpp and mpu401.cpp.

It is fixed in 0.82.21.

**Comment by leoxxx** [comment]
> 
> 
> Strange, nothing other than typecast fixes were made to sblaster.cpp and mpu401.cpp.

It is fixed in 0.82.21.

**Comment by leoxxx** [comment]
It still happend in 0.82.22.

**Comment by Allofich** [comment]
I can't reproduce the problem. I tried using the sbbasic.exe program above, using both MIDI port 300 and 330 with Windows 3.11. I then tried Windows 3.12 (Chinese) with the sbbasic.exe program above and MIDI port 300, and still no problem. Also no problem when using a default dosbox.conf.

I was using code from a couple days ago, basically the latest version.

@leoxxx, does the problem happen with a default dosbox.conf? Also, I don't completely understand your description of the problem. Where does the error message happen? When starting Windows? Does it only happen with port 330, or with both port 300 and 330?

Maybe also check your autoexec.bat and config.sys. After just installing Windows 3.12 and the Sound Blaster program, my files are as follows:

autoexec.bat

SET SOUND=C:\SB16
SET BLASTER=A220 I5 D1 H5 P300 T6
SET MIDI=SYNTH:1 MAP:E
C:\SB16\DIAGNOSE /S
C:\SB16\MIXERSET /P /Q
C:\WINDOWS\SMARTDRV.EXE
PATH C:\WINDOWS;
SET TEMP=C:\WINDOWS\TEMP

config.sys

REM ** FILES=30
BUFFERS=30
DEVICE=C:\WINDOWS\HIMEM.SYS
DEVICE=C:\WINDOWS\SMARTDRV.EXE /DOUBLE_BUFFER
STACKS=9,256
FILES=40

**Comment by leoxxx** [comment]
> SET SOUND=C:\SB16
> SET BLASTER=A220 I7 D1 H5 P330 T6
> SET MIDI=SYNTH:1 MAP:E
> C:\SB16\DIAGNOSE /S
> C:\SB16\SB16SET /P /Q
> C:\WINDOWS\SMARTDRV.EXE
> PATH C:\WINDOWS;
> SET TEMP=C:\WINDOWS\TEMP

> DEVICE=C:\SB16\DRV\CSP.SYS /UNIT=0 /BLASTER=A:220
> DEVICE=C:\SB16\DRV\CTSB16.SYS /UNIT=0 /BLASTER=A:220 I:7 D:1 H:5
> DEVICE=C:\SB16\DRV\CTMMSYS.SYS
> FILES=40
> REM ** FILES=30
> BUFFERS=30
> DEVICE=C:\WINDOWS\HIMEM.SYS
> DEVICE=C:\WINDOWS\SMARTDRV.EXE /DOUBLE_BUFFER
> STACKS=9,256

@Allofich 
These is mine.
"dosbox.conf" is default, form the dosxbox. I just add three auto mount commands.
The dialog popup when starting windows. It will play a login midi.
330 is O.K. in dosbox. But it's error in DOSBox-X. It can't be loaded if you change it from 330 to 300 in DOSBox-X. 300 can be loaded in dosbox, but it's error.

**Comment by Allofich** [comment]
When I ran install.exe from sbbasic.exe, there was a parameter to specify the Windows installation directory. It was blank by default, so I changed it to the Windows directory. Did you also do so?

Also, did you install a different sound driver before installing the "sbbasic.exe" that gr33k mentioned? If so, maybe there is still some leftover part of the earlier driver.

I don't have any other ideas right now, it works without a problem for me.

**Comment by Allofich** [comment]
My Windows 3.2 `SYSTEM.INI` file looks like this:

```
[boot]
shell=progman.exe
mouse.drv=mouse.drv
network.drv=
language.dll=
sound.drv=mmsound.drv
comm.drv=comm.drv
keyboard.drv=keyboard.drv
system.drv=system.drv
386grabber=vga.3gr
oemfonts.fon=vgaoem.fon
286grabber=vgacolor.2gr
fixedfon.fon=vgafix.fon
fonts.fon=vgasys.fon
display.drv=vga.drv
drivers=mmsystem.dll msmixmgr.dll

[keyboard]
subtype=
type=4
keyboard.dll=
oemansi.bin=

[boot.description]
keyboard.typ=Enhanced 101 or 102 key US and Non US keyboards
mouse.drv=Microsoft, or IBM PS/2
network.drv=No Network Installed
language.dll=Simplified Chinese
system.drv=MS-DOS System
codepage=437
woafont.fon=English (437)
aspect=100,96,96
display.drv=VGA

[386Enh]
mouse=*vmd
network=*dosnet,*vnetbios
ebios=*ebios
woafont=dosapp.fon
display=*vddvga
EGA80WOA.FON=EGA80WOA.FON
EGA40WOA.FON=EGA40WOA.FON
CGA80WOA.FON=CGA80WOA.FON
CGA40WOA.FON=CGA40WOA.FON
keyboard=*vkd
device=vtdapi.386
device=*vpicd
device=*vtd
device=*reboot
device=*vdmad
device=*vsd
device=*v86mmgr
device=*pageswap
device=*dosmgr
device=*vmpoll
device=*wshell
device=*BLOCKDEV
device=*PAGEFILE
device=*vfd
device=*parity
device=*biosxlat
device=*vcd
device=*vmcpd
device=*combuff
device=*cdpscsi
local=CON
FileSysChange=off
PagingFile=C:\WINDOWS\WIN386.SWP
MaxPagingFileSize=57344
device=vsbpd.386

[standard]

[NonWindowsApp]
localtsrs=dosedit,ced

[mci]
WaveAudio=mciwave.drv
Sequencer=mciseq.drv
CDAudio=mcicda.drv

[drivers]
timer=timer.drv
midimapper=midimap.drv
Midi=sb16fm.drv
Midi1=sb16snd.drv
Wave=sb16snd.drv
Aux=sb16snd.drv
Mixer=sb16snd.drv
[sndblst.drv]
Port=220
Int=5
DmaChannel=1
MidiPort=300
HDmaChannel=5
FDMAPlayBack=0
FDMARecording=0
VoiceVolume=16, 16
FMVolume=16, 16
CDVolume=16, 16
LineVolume=16, 16
MicVolume=16
MasterVolume=16, 16
SpeakerVolume=16
MuteVirtual=10
OutputMixerSwitch=6
BassTone=16, 16
TrebleTone=16, 16
RecordGain=1, 1
OutputGain=1, 1
AGC=0
Mux_WaveIn=1e
```

@leoxxx,
is yours different? (Other than the Sound Blaster IRQ, I see you are using the default DOSBox-X IRQ of 7. I am using IRQ 5 above, the default of the Sound Blaster 16 INSTALL.EXE program.)

**Comment by leoxxx** [comment]
@Allofich 
It's mine.

> [boot]
> shell=progman.exe
> mouse.drv=mouse.drv
> network.drv=
> language.dll=
> sound.drv=mmsound.drv
> comm.drv=comm.drv
> keyboard.drv=keyboard.drv
> system.drv=system.drv
> 386grabber=S3911GRB.3GR
> oemfonts.fon=vgaoem.fon
> 286grabber=VGACOLOR.2GR
> fixedfon.fon=vgafix.fon
> fonts.fon=vgasys.fon
> display.drv=S3VSND.DRV
> drivers=mmsystem.dll
> SCRNSAVE.EXE=(无)
> 
> [keyboard]
> subtype=
> type=4
> keyboard.dll=
> oemansi.bin=
> 
> [boot.description]
> keyboard.typ=Enhanced 101 or 102 key US and Non US keyboards
> mouse.drv=Microsoft, or IBM PS/2
> network.drv=No Network Installed
> language.dll=Simplified Chinese
> system.drv=MS-DOS System
> codepage=437
> woafont.fon=English (437)
> aspect=100,96,96
> display.drv=S3 864 1.41B5  800x600   256 colors SF
> 
> [386Enh]
> mouse=*vmd
> network=*dosnet,*vnetbios
> ebios=*ebios
> woafont=dosapp.fon
> display=VDDS3VSN.386
> EGA80WOA.FON=EGA80WOA.FON
> EGA40WOA.FON=EGA40WOA.FON
> CGA80WOA.FON=CGA80WOA.FON
> CGA40WOA.FON=CGA40WOA.FON
> keyboard=*vkd
> device=vtdapi.386
> device=*vpicd
> device=*vtd
> device=*reboot
> device=*vdmad
> device=*vsd
> device=*v86mmgr
> device=*pageswap
> device=*dosmgr
> device=*vmpoll
> device=*wshell
> device=*BLOCKDEV
> device=*PAGEFILE
> device=*vfd
> device=*parity
> device=*biosxlat
> device=*vcd
> device=*vmcpd
> device=*combuff
> device=*cdpscsi
> local=CON
> FileSysChange=off
> device=vsbpd.386
> Paging=0
> 
> [standard]
> 
> [NonWindowsApp]
> localtsrs=dosedit,ced
> 
> [mci]
> WaveAudio=mciwave.drv
> Sequencer=mciseq.drv
> CDAudio=mcicda.drv
> 
> [drivers]
> timer=timer.drv
> midimapper=midimap.drv
> Midi=sb16fm.drv
> Midi1=sb16snd.drv
> Wave=sb16snd.drv
> Aux=sb16aux.drv
> [sndblst.drv]
> Port=220
> Int=7
> DmaChannel=1
> MidiPort=330
> HDmaChannel=5
> 
> [DISPLAY]
> dac-type=nbt
> polygon-support=on
> ellipse-support=on
> scache=on
> textrmw=0
> fastmmio=on
> screen-size=800
> color-format=8
> dpi=96
>

**Comment by Allofich** [comment]
Differences in the sound section:

Mine:
Aux=sb16snd.drv
Yours:
Aux=sb16aux.drv

Mine:
Mixer=sb16snd.drv
Yours:
(Don't have)

Mine:
FDMAPlayBack=0
FDMARecording=0
VoiceVolume=16, 16
FMVolume=16, 16
CDVolume=16, 16
LineVolume=16, 16
MicVolume=16
MasterVolume=16, 16
SpeakerVolume=16
MuteVirtual=10
OutputMixerSwitch=6
BassTone=16, 16
TrebleTone=16, 16
RecordGain=1, 1
OutputGain=1, 1
AGC=0
Mux_WaveIn=1e

Yours:
(Don't have)

You could try using my settings.
Also you have a Chinese character: SCRNSAVE.EXE=(无)

Maybe it causes some problem?

**Comment by Allofich** [comment]
I tried changing the differences I noted above to the values of your SYSTEM.INI, but it still works for me. Sorry, I can't think of anything else right now.

**Comment by Allofich** [comment]
> It is fixed in 0.82.19.

@leoxxx, does 0.82.19 still work for you? If it doesn't, it seems to me you probably have a problem in your Windows 3.2 configuration.

If it does work, maybe we can find the commit between 0.82.19 and 0.82.20 where it stopped working.

**Comment by leoxxx** [comment]
> 
> 
> > It is fixed in 0.82.19.
> 
> @leoxxx, does 0.82.19 still work for you? If it doesn't, it seems to me you probably have a problem in your Windows 3.2 configuration.
> 
> If it does work, maybe we can find the commit between 0.82.19 and 0.82.20 where it stopped working.
19 is O.K.



> 
> 
> Strange, nothing other than typecast fixes were made to sblaster.cpp and mpu401.cpp.

The owner think it is strange.

**Comment by joncampbell123** [comment]
Typecast changes have broken things before. Can you see which one broke MPU-401 emulation for you?

**Comment by leoxxx** [comment]
> 
> 
> Typecast changes have broken things before. Can you see which one broke MPU-401 emulation for you?

I don't understand the code, just a user, sorry.
BTW, will the DOSBox-X create some logs when some errors happen?

**Comment by Allofich** [comment]
@leoxxx, can you please try these two versions of DOSBox-X and tell me if each of them has the error or does not? This is to find exactly when the problem starts between .19 and .20.
[dosbox-x-windows-44a39c7.zip](https://github.com/joncampbell123/dosbox-x/files/3692980/dosbox-x-windows-44a39c7.zip)
[dosbox-x-windows-fffdb0a.zip](https://github.com/joncampbell123/dosbox-x/files/3692981/dosbox-x-windows-fffdb0a.zip)

**Comment by leoxxx** [comment]
Both are 20 and they are errors.

**Comment by Allofich** [comment]
I found the commit that causes the error to start appearing.

https://github.com/joncampbell123/dosbox-x/commit/eb90fb4d94aa3a39d5001526ffab173ce5ec302f

@leoxxx, here is the latest DOSBox-X with the above commit reverted. The error doesn't appear with it. You can use it for now if you want.

[dosbox-x-windows-8d27faf.zip](https://github.com/joncampbell123/dosbox-x/files/3693510/dosbox-x-windows-8d27faf.zip)

@joncampbell123, what do you think we should do? Revert the above commit?

**Comment by Allofich** [comment]
As the commit description suggests, reverting the commit causes F29 Retaliator to no longer detect MPU MIDI and instead it plays OPL MIDI.

**Comment by Allofich** [comment]
@leoxxx, there are many differences between your Windows 3.2 installation and mine, and between the Sound Blaster drivers. Also, yours has an English title screen and says Windows 3.1, while mine says Windows 3.2 and is in Chinese. I think it may be best for you to make sure you have a good installation of Windows 3.2 and a good Sound Blaster 16 driver, rather than trying to adjust DOSBox-X to match the installation you have now.

**Comment by joncampbell123** [comment]
@Allofich Let's leave the commit, but find out which typecast caused the error.

**Comment by leoxxx** [comment]
@Allofich 
THX.
8d27faf is O.K.
The login cover display 3.1 after I install S3 VGA driver.
ed2k://|file|SC_Windows32_12.exe|12832984|A76EB68E35CD62F8B40ECD3E6F5E213F|/
ed2k://|file|SC_Windows32_144.exe|12835440|782F5AF8A1405D518C181F057FCC4287|/
I install 3.2 from one of two links(for a long time, I don't remeber which one).

**Comment by Allofich** [comment]
@joncampbell123, reverting eb90fb4 allows current code to not have the error with leoxxx's setup, so everything else in master branch, including all typefixes, seems to not cause it. But, I'm suspicious that leoxxx's installation of Windows 3.2 and/or the SoundBlaster driver might be messed up, because when comparing leoxxx's files to those from a clean installation of Windows 3.2 and SoundBlaster drivers, there were lots of files with different contents, different files, etc. , so I prefer to keep eb90fb4 since we at least know it helps with F29 Retaliator.

@leoxxx, you may want to try a different Windows 3.2 installation, such as from image disks (even though it's a bit of trouble). My installation shows the Windows 3.2 Chinese title screen when starting. And try the Sound Blaster 16 setup program suggested above.

![win386_000](https://user-images.githubusercontent.com/19624336/66265449-8aca0080-e851-11e9-8560-cad5c6133963.png)

**Comment by leoxxx** [comment]
I reinstall win3.2 in DOSBox-X 0.83.15 mingw-sdl2 win64. Then intall video and audio driver, it's fine in both DOSBox & DOSBox-X.
But the title still display 3.1 after install the video driver.
