### ISSUE TITLE
Voodoo1 MAME code updates port to DOSBox-X

### ISSUE THREAD

**Issue by ghoul8765** [joncampbell123/dosbox-x#92]
Some of the MAME project updates port to the Voodoo1 emulation in DOSBox-X, and these changes appear to improve image quality. Below is a diff file of the changes to 6/9 source code, please confirm whether this is of interest to you.  :)

I chose and tested all code bits line by line, and these seem to pass my limited testing (* updated on 6/9).

The vast majority of the code additions and modifications are by Ted Green.  We should all be grateful that he joined their project and is making so many improvements to MAME!

DIFF FILE:
<pre lang="diff"><code>
diff -rupN dosbox-x-OLD//src/hardware/voodoo_data.h dosbox-x-UPDATED//src/hardware/voodoo_data.h
--- dosbox-x-OLD//src/hardware/voodoo_data.h	2015-06-08 03:01:33 -0400
+++ dosbox-x-UPDATED//src/hardware/voodoo_data.h	2015-06-09 04:41:36 -0400
@@ -195,7 +195,7 @@ static const UINT8 dither_matrix_2x2[16]
 #define EXTRACT_332_TO_888(val, a, b, c)					\
 	(a) = (((val) >> 0) & 0xe0) | (((val) >> 3) & 0x1c) | (((val) >> 6) & 0x03); \
 	(b) = (((val) << 3) & 0xe0) | (((val) >> 0) & 0x1c) | (((val) >> 3) & 0x03); \
-	(c) = (((val) << 6) & 0xc0) | (((val) << 4) & 0x30) | (((val) << 2) & 0xc0) | (((val) << 0) & 0x03); \
+	(c) = (((val) << 6) & 0xc0) | (((val) << 4) & 0x30) | (((val) << 2) & 0x0c) | (((val) << 0) & 0x03); \
 
 
 
@@ -1093,6 +1093,9 @@ INLINE UINT32 compute_raster_hash(const
 	const UINT8 *dither4 = NULL;												\
 	const UINT8 *dither = NULL													\
 
+#define DECLARE_DITHER_POINTERS_NO_DITHER_VAR												\
+	const UINT8 *dither_lookup = NULL;											\
+
 #define COMPUTE_DITHER_POINTERS(FBZMODE, YY)									\
 do																				\
 {																				\
@@ -1114,6 +1117,24 @@ do																				\
 }																				\
 while (0)
 
+#define COMPUTE_DITHER_POINTERS_NO_DITHER_VAR(FBZMODE, YY)									\
+do																				\
+{																				\
+	/* compute the dithering pointers */										\
+	if (FBZMODE_ENABLE_DITHERING(FBZMODE))										\
+	{																			\
+		if (FBZMODE_DITHER_TYPE(FBZMODE) == 0)									\
+		{																		\
+			dither_lookup = &dither4_lookup[(YY & 3) << 11];					\
+		}																		\
+		else																	\
+		{																		\
+			dither_lookup = &dither2_lookup[(YY & 3) << 11];					\
+		}																		\
+	}																			\
+}																				\
+while (0)
+
 #define APPLY_DITHER(FBZMODE, XX, DITHER_LOOKUP, RR, GG, BB)					\
 do																				\
 {																				\
@@ -1148,10 +1169,10 @@ while (0)
 #define CLAMPED_ARGB(ITERR, ITERG, ITERB, ITERA, FBZCP, RESULT)					\
 do																				\
 {																				\
-	INT32 r = (INT32)(ITERR) >> 12;												\
-	INT32 g = (INT32)(ITERG) >> 12;												\
-	INT32 b = (INT32)(ITERB) >> 12;												\
-	INT32 a = (INT32)(ITERA) >> 12;												\
+	r = (INT32)(ITERR) >> 12;												\
+	g = (INT32)(ITERG) >> 12;												\
+	b = (INT32)(ITERB) >> 12;												\
+	a = (INT32)(ITERA) >> 12;												\
 																				\
 	if (FBZCP_RGBZW_CLAMP(FBZCP) == 0)											\
 	{																			\
@@ -1421,9 +1442,8 @@ do																				\
 	if (ALPHAMODE_ALPHABLEND(ALPHAMODE))										\
 	{																			\
 		int dpix = dest[XX];													\
-		int dr = (dpix >> 8) & 0xf8;											\
-		int dg = (dpix >> 3) & 0xfc;											\
-		int db = (dpix << 3) & 0xf8;											\
+		int dr, dg, db;                                                         \
+		EXTRACT_565_TO_888(dpix, dr, dg, db);                                   \
 		int da = (FBZMODE_ENABLE_ALPHA_PLANES(FBZMODE) && depth) ? depth[XX] : 0xff;		\
 		int sr = (RR);															\
 		int sg = (GG);															\
@@ -1624,12 +1644,12 @@ do																				\
 			{																	\
 				case 0:		/* fog table */										\
 				{																\
-					INT32 delta = (VV)->fbi.fogdelta[wfloat >> 10];				\
+					INT32 delta = (VV)->fbi.fogdelta[fogdepth >> 10];				\
 					INT32 deltaval;												\
 																				\
 					/* perform the multiply against lower 8 bits of wfloat */	\
 					deltaval = (delta & (VV)->fbi.fogdelta_mask) *				\
-								((wfloat >> 2) & 0xff);							\
+								((fogdepth >> 2) & 0xff);							\
 																				\
 					/* fog zones allow for negating this value */				\
 					if (FOGMODE_FOG_ZONES(FOGMODE) && (delta & 2))				\
@@ -1643,7 +1663,7 @@ do																				\
 					deltaval >>= 4;												\
 																				\
 					/* add to the blending factor */							\
-					fogblend = (VV)->fbi.fogblend[wfloat >> 10] + deltaval;		\
+					fogblend = (VV)->fbi.fogblend[fogdepth >> 10] + deltaval;		\
 					break;														\
 				}																\
 																				\
@@ -2044,7 +2064,7 @@ while (0)
 #define PIXEL_PIPELINE_BEGIN(VV, XX, YY, FBZCOLORPATH, FBZMODE, ITERZ, ITERW)	\
 do																				\
 {																				\
-	INT32 depthval, wfloat;														\
+	INT32 depthval, wfloat, fogdepth, biasdepth;														\
 	INT32 prefogr, prefogg, prefogb;											\
 	INT32 r, g, b, a;															\
 																				\
@@ -2086,111 +2106,125 @@ do																				\
 		else																	\
 		{																		\
 			int exp = count_leading_zeros(temp);								\
-			wfloat = ((exp << 12) | ((~temp >> (19 - exp)) & 0xfff));			\
-			if (wfloat < 0xffff) wfloat++;										\
-		}																		\
-	}																			\
-																				\
-	/* compute depth value (W or Z) for this pixel */							\
-	if (FBZMODE_WBUFFER_SELECT(FBZMODE) == 0)									\
-		CLAMPED_Z(ITERZ, FBZCOLORPATH, depthval);								\
-	else if (FBZMODE_DEPTH_FLOAT_SELECT(FBZMODE) == 0)							\
-		depthval = wfloat;														\
-	else																		\
-	{																			\
-		if ((ITERZ) & 0xf0000000)												\
-			depthval = 0x0000;													\
-		else																	\
-		{																		\
-			UINT32 temp = (ITERZ) << 4;											\
-			if ((temp & 0xffff0000) == 0)										\
-				depthval = 0xffff;												\
-			else																\
-			{																	\
-				int exp = count_leading_zeros(temp);							\
-				depthval = ((exp << 12) | ((~temp >> (19 - exp)) & 0xfff));		\
-				if (depthval < 0xffff) depthval++;								\
-			}																	\
+			wfloat = ((exp << 12) | ((~temp >> (19 - exp)) & 0xfff)) + 1;			\
 		}																		\
 	}																			\
-																				\
-	/* add the bias */															\
-	if (FBZMODE_ENABLE_DEPTH_BIAS(FBZMODE))										\
-	{																			\
-		depthval += (INT16)(VV)->reg[zaColor].u;								\
-		CLAMP(depthval, 0, 0xffff);												\
-	}																			\
-																				\
-	/* handle depth buffer testing */											\
-	if (FBZMODE_ENABLE_DEPTHBUF(FBZMODE))										\
-	{																			\
-		INT32 depthsource;														\
-																				\
-		/* the source depth is either the iterated W/Z+bias or a */				\
-		/* constant value */													\
-		if (FBZMODE_DEPTH_SOURCE_COMPARE(FBZMODE) == 0)							\
-			depthsource = depthval;												\
-		else																	\
-			depthsource = (UINT16)(VV)->reg[zaColor].u;							\
-																				\
-		/* test against the depth buffer */										\
-		switch (FBZMODE_DEPTH_FUNCTION(FBZMODE))								\
-		{																		\
-			case 0:		/* depthOP = never */									\
-				goto skipdrawdepth;												\
-																				\
-			case 1:		/* depthOP = less than */								\
-				if (depth)														\
-					if (depthsource >= depth[XX])								\
-					{															\
-						goto skipdrawdepth;										\
-					}															\
-				break;															\
-																				\
-			case 2:		/* depthOP = equal */									\
-				if (depth)														\
-					if (depthsource != depth[XX])								\
-					{															\
-						goto skipdrawdepth;										\
-					}															\
-				break;															\
-																				\
-			case 3:		/* depthOP = less than or equal */						\
-				if (depth)														\
-					if (depthsource > depth[XX])								\
-					{															\
-						goto skipdrawdepth;										\
-					}															\
-				break;															\
-																				\
-			case 4:		/* depthOP = greater than */							\
-				if (depth)														\
-					if (depthsource <= depth[XX])								\
-					{															\
-						goto skipdrawdepth;										\
-					}															\
-				break;															\
-																				\
-			case 5:		/* depthOP = not equal */								\
-				if (depth)														\
-					if (depthsource == depth[XX])								\
-					{															\
-						goto skipdrawdepth;										\
-					}															\
-				break;															\
-																				\
-			case 6:		/* depthOP = greater than or equal */					\
-				if (depth)														\
-					if (depthsource < depth[XX])								\
-					{															\
-						goto skipdrawdepth;										\
-					}															\
-				break;															\
-																				\
-			case 7:		/* depthOP = always */									\
-				break;															\
-		}																		\
-	}
+	fogdepth = wfloat;                                                         \
+ 	/* add the bias for fog selection*/                                         \
+ 	if (FBZMODE_ENABLE_DEPTH_BIAS(FBZMODE))                                     \
+ 	{                                                                           \
+		fogdepth += (INT16)(VV)->reg[zaColor].u;                                \
+		CLAMP(fogdepth, 0, 0xffff);                                             \
+ 	}                                                                           \
+																				\
+	/* compute depth value (W or Z) for this pixel */                           \
+	if (FBZMODE_WBUFFER_SELECT(FBZMODE) == 0)                                   \
+	{                                                                           \
+		CLAMPED_Z(ITERZ, FBZCOLORPATH, depthval);                               \
+	}                                                                           \
+	else if (FBZMODE_DEPTH_FLOAT_SELECT(FBZMODE) == 0)                          \
+		depthval = wfloat;                                                      \
+	else                                                                        \
+	{                                                                           \
+		if ((ITERZ) & 0xf0000000)                                               \
+			depthval = 0x0000;                                                  \
+		else                                                                    \
+		{                                                                       \
+			UINT32 temp = (ITERZ << 4);                             \
+			if (!(temp & 0xffff0000))                                                           \
+				depthval = 0xffff;                                              \
+			else                                                                \
+			{                                                                   \
+				int exp = count_leading_zeros(temp);                            \
+				depthval = ((exp << 12) | ((~temp >> (19 - exp)) & 0xfff)) + 1; \
+			}                                                                   \
+		}                                                                       \
+	}                                                                            \
+	/* add the bias */                                                          \
+	biasdepth = depthval;                                                     \
+	if (FBZMODE_ENABLE_DEPTH_BIAS(FBZMODE))                                     \
+	{                                                                           \
+		biasdepth += (INT16)(VV)->reg[zaColor].u;                                \
+		CLAMP(biasdepth, 0, 0xffff);                                             \
+	}															\
+
+
+#define DEPTH_TEST(VV, STATS, XX, FBZMODE)    \
+do                                                                              \
+{                                                                               \
+	/* handle depth buffer testing */                                           \
+	if (FBZMODE_ENABLE_DEPTHBUF(FBZMODE))                                       \
+	{                                                                           \
+		INT32 depthsource;                                                      \
+																				\
+		/* the source depth is either the iterated W/Z+bias or a */             \
+		/* constant value */                                                    \
+		if (FBZMODE_DEPTH_SOURCE_COMPARE(FBZMODE) == 0)                         \
+			depthsource = biasdepth;                                             \
+		else                                                                    \
+			depthsource = (UINT16)(VV)->reg[zaColor].u;                         \
+																				\
+		/* test against the depth buffer */                                     \
+		switch (FBZMODE_DEPTH_FUNCTION(FBZMODE))                                \
+		{                                                                       \
+			case 0:     /* depthOP = never */                                   \
+				(STATS)->zfunc_fail++;                                          \
+				goto skipdrawdepth;                                             \
+																				\
+			case 1:     /* depthOP = less than */                               \
+				if (depthsource >= depth[XX])                                   \
+				{                                                               \
+					(STATS)->zfunc_fail++;                                      \
+					goto skipdrawdepth;                                         \
+				}                                                               \
+				break;                                                          \
+																				\
+			case 2:     /* depthOP = equal */                                   \
+				if (depthsource != depth[XX])                                   \
+				{                                                               \
+					(STATS)->zfunc_fail++;                                      \
+					goto skipdrawdepth;                                         \
+				}                                                               \
+				break;                                                          \
+																				\
+			case 3:     /* depthOP = less than or equal */                      \
+				if (depthsource > depth[XX])                                    \
+				{                                                               \
+					(STATS)->zfunc_fail++;                                      \
+					goto skipdrawdepth;                                         \
+				}                                                               \
+				break;                                                          \
+																				\
+			case 4:     /* depthOP = greater than */                            \
+				if (depthsource <= depth[XX])                                   \
+				{                                                               \
+					(STATS)->zfunc_fail++;                                      \
+					goto skipdrawdepth;                                         \
+				}                                                               \
+				break;                                                          \
+																				\
+			case 5:     /* depthOP = not equal */                               \
+				if (depthsource == depth[XX])                                   \
+				{                                                               \
+					(STATS)->zfunc_fail++;                                      \
+					goto skipdrawdepth;                                         \
+				}                                                               \
+				break;                                                          \
+																				\
+			case 6:     /* depthOP = greater than or equal */                   \
+				if (depthsource < depth[XX])                                    \
+				{                                                               \
+					(STATS)->zfunc_fail++;                                      \
+					goto skipdrawdepth;                                         \
+				}                                                               \
+				break;                                                          \
+																				\
+			case 7:     /* depthOP = always */                                  \
+				break;                                                          \
+		}                                                                       \
+	}                                                                       \
+}                                                                               \
+while (0)
 
 
 #define PIXEL_PIPELINE_MODIFY(VV, DITHER, DITHER4, XX, FBZMODE, FBZCOLORPATH, ALPHAMODE, FOGMODE, ITERZ, ITERW, ITERAXXX) \
@@ -2220,7 +2254,7 @@ do																				\
 	if (depth && FBZMODE_AUX_BUFFER_MASK(FBZMODE))								\
 	{																			\
 		if (FBZMODE_ENABLE_ALPHA_PLANES(FBZMODE) == 0)							\
-			depth[XX] = (UINT16)depthval;										\
+			depth[XX] = (UINT16)biasdepth;										\
 		else																	\
 			depth[XX] = (UINT16)a;												\
 	}
diff -rupN dosbox-x-OLD//src/hardware/voodoo_emu.cpp dosbox-x-UPDATED//src/hardware/voodoo_emu.cpp
--- dosbox-x-OLD//src/hardware/voodoo_emu.cpp	2015-06-08 03:01:33 -0400
+++ dosbox-x-UPDATED//src/hardware/voodoo_emu.cpp	2015-06-09 04:44:13 -0400
@@ -230,12 +230,16 @@ void raster_generic(UINT32 TMUS, UINT32
 	/* loop in X */
 	for (x = startx; x < stopx; x++)
 	{
-		rgb_union iterargb = { 0 };
+		rgb_union iterargb;
 		rgb_union texel = { 0 };
+		rgb_union color;
 
 		/* pixel pipeline part 1 handles depth testing and stippling */
 		PIXEL_PIPELINE_BEGIN(v, x, y, v->reg[fbzColorPath].u, v->reg[fbzMode].u, iterz, iterw);
 
+		/* depth testing */
+		DEPTH_TEST(v, stats, x, v->reg[fbzMode].u);
+
 		/* run the texture pipeline on TMU1 to produce a value in texel */
 		/* note that they set LOD min to 8 to "disable" a TMU */
 
@@ -305,25 +309,6 @@ void raster_generic(UINT32 TMUS, UINT32
 		/* handle alpha mask */
 		APPLY_ALPHAMASK(v, stats, v->reg[fbzMode].u, c_other.rgb.a);
 
-		/* handle alpha test */
-		APPLY_ALPHATEST(v, stats, v->reg[alphaMode].u, c_other.rgb.a);
-
-		/* compute c_local */
-		if (FBZCP_CC_LOCALSELECT_OVERRIDE(v->reg[fbzColorPath].u) == 0)
-		{
-			if (FBZCP_CC_LOCALSELECT(v->reg[fbzColorPath].u) == 0)	/* iterated RGB */
-				c_local.u = iterargb.u;
-			else											/* color0 RGB */
-				c_local.u = v->reg[color0].u;
-		}
-		else
-		{
-			if (!(texel.rgb.a & 0x80))					/* iterated RGB */
-				c_local.u = iterargb.u;
-			else											/* color0 RGB */
-				c_local.u = v->reg[color0].u;
-		}
-
 		/* compute a_local */
 		switch (FBZCP_CCA_LOCALSELECT(v->reg[fbzColorPath].u))
 		{
@@ -350,6 +335,78 @@ void raster_generic(UINT32 TMUS, UINT32
 			}
 		}
 
+		/* select zero or a_other */
+		if (FBZCP_CCA_ZERO_OTHER(v->reg[fbzColorPath].u) == 0)
+			a = c_other.rgb.a;
+		else
+			a = 0;
+
+		/* subtract a_local */ 
+		if (FBZCP_CCA_SUB_CLOCAL(v->reg[fbzColorPath].u)) 
+			a -= c_local.rgb.a; 
+		
+		/* blend alpha */ 
+		switch (FBZCP_CCA_MSELECT(v->reg[fbzColorPath].u)) 
+		{ 
+			default: /* reserved */ 
+			case 0: /* 0 */ 
+				blenda = 0; 
+				break; 
+		
+			case 1: /* a_local */ 
+				blenda = c_local.rgb.a; 
+				break; 
+		
+			case 2: /* a_other */ 
+				blenda = c_other.rgb.a; 
+				break; 
+		
+			case 3: /* a_local */ 
+				blenda = c_local.rgb.a; 
+				break; 
+		
+			case 4: /* texture alpha */ 
+				blenda = texel.rgb.a; 
+				break; 
+		} 
+		
+		/* reverse the alpha blend */ 
+		if (!FBZCP_CCA_REVERSE_BLEND(v->reg[fbzColorPath].u)) 
+			blenda ^= 0xff; 
+		
+		/* do the blend */ 
+		a = (a * (blenda + 1)) >> 8; 
+		
+		/* add clocal or alocal to alpha */ 
+		if (FBZCP_CCA_ADD_ACLOCAL(v->reg[fbzColorPath].u)) 
+			a += c_local.rgb.a; 
+		
+		/* clamp */ 
+		CLAMP(a, 0x00, 0xff); 
+		
+		/* invert */ 
+		if (FBZCP_CCA_INVERT_OUTPUT(v->reg[fbzColorPath].u)) 
+			a ^= 0xff; 
+
+		/* handle alpha test */
+		APPLY_ALPHATEST(v, stats, v->reg[alphaMode].u, a);
+		
+		/* compute c_local */
+		if (FBZCP_CC_LOCALSELECT_OVERRIDE(v->reg[fbzColorPath].u) == 0)
+		{
+			if (FBZCP_CC_LOCALSELECT(v->reg[fbzColorPath].u) == 0) /* iterated RGB */
+				c_local.u = iterargb.u;
+			else /* color0 RGB */
+				c_local.u = v->reg[color0].u;
+		}
+		else
+		{
+			if (!(texel.rgb.a & 0x80)) /* iterated RGB */
+				c_local.u = iterargb.u;
+			else /* color0 RGB */
+				c_local.u = v->reg[color0].u;
+		} 
+		
 		/* select zero or c_other */
 		if (FBZCP_CC_ZERO_OTHER(v->reg[fbzColorPath].u) == 0)
 		{
@@ -360,12 +417,6 @@ void raster_generic(UINT32 TMUS, UINT32
 		else
 			r = g = b = 0;
 
-		/* select zero or a_other */
-		if (FBZCP_CCA_ZERO_OTHER(v->reg[fbzColorPath].u) == 0)
-			a = c_other.rgb.a;
-		else
-			a = 0;
-
 		/* subtract c_local */
 		if (FBZCP_CC_SUB_CLOCAL(v->reg[fbzColorPath].u))
 		{
@@ -374,10 +425,6 @@ void raster_generic(UINT32 TMUS, UINT32
 			b -= c_local.rgb.b;
 		}
 
-		/* subtract a_local */
-		if (FBZCP_CCA_SUB_CLOCAL(v->reg[fbzColorPath].u))
-			a -= c_local.rgb.a;
-
 		/* blend RGB */
 		switch (FBZCP_CC_MSELECT(v->reg[fbzColorPath].u))
 		{
@@ -406,27 +453,6 @@ void raster_generic(UINT32 TMUS, UINT32
 				break;
 		}
 
-		/* blend alpha */
-		switch (FBZCP_CCA_MSELECT(v->reg[fbzColorPath].u))
-		{
-			default:	/* reserved */
-			case 0:		/* 0 */
-				blenda = 0;
-				break;
-			case 1:		/* a_local */
-				blenda = c_local.rgb.a;
-				break;
-			case 2:		/* a_other */
-				blenda = c_other.rgb.a;
-				break;
-			case 3:		/* a_local */
-				blenda = c_local.rgb.a;
-				break;
-			case 4:		/* texture alpha */
-				blenda = texel.rgb.a;
-				break;
-		}
-
 		/* reverse the RGB blend */
 		if (!FBZCP_CC_REVERSE_BLEND(v->reg[fbzColorPath].u))
 		{
@@ -435,15 +461,10 @@ void raster_generic(UINT32 TMUS, UINT32
 			blendb ^= 0xff;
 		}
 
-		/* reverse the alpha blend */
-		if (!FBZCP_CCA_REVERSE_BLEND(v->reg[fbzColorPath].u))
-			blenda ^= 0xff;
-
 		/* do the blend */
 		r = (r * (blendr + 1)) >> 8;
 		g = (g * (blendg + 1)) >> 8;
 		b = (b * (blendb + 1)) >> 8;
-		a = (a * (blenda + 1)) >> 8;
 
 		/* add clocal or alocal to RGB */
 		switch (FBZCP_CC_ADD_ACLOCAL(v->reg[fbzColorPath].u))
@@ -463,15 +484,10 @@ void raster_generic(UINT32 TMUS, UINT32
 				break;
 		}
 
-		/* add clocal or alocal to alpha */
-		if (FBZCP_CCA_ADD_ACLOCAL(v->reg[fbzColorPath].u))
-			a += c_local.rgb.a;
-
 		/* clamp */
 		CLAMP(r, 0x00, 0xff);
 		CLAMP(g, 0x00, 0xff);
 		CLAMP(b, 0x00, 0xff);
-		CLAMP(a, 0x00, 0xff);
 
 		/* invert */
 		if (FBZCP_CC_INVERT_OUTPUT(v->reg[fbzColorPath].u))
@@ -480,9 +496,6 @@ void raster_generic(UINT32 TMUS, UINT32
 			g ^= 0xff;
 			b ^= 0xff;
 		}
-		if (FBZCP_CCA_INVERT_OUTPUT(v->reg[fbzColorPath].u))
-			a ^= 0xff;
-
 
 		/* pixel pipeline part 2 handles fog, alpha, and final output */
 		PIXEL_PIPELINE_MODIFY(v, dither, dither4, x,
@@ -2177,7 +2190,7 @@ void lfb_w(UINT32 offset, UINT32 data, U
 	/* simple case: no pipeline */
 	if (!LFBMODE_ENABLE_PIXEL_PIPELINE(v->reg[lfbMode].u))
 	{
-		DECLARE_DITHER_POINTERS;
+		DECLARE_DITHER_POINTERS_NO_DITHER_VAR;
 		UINT32 bufoffs;
 
 		if (LOG_LFB) LOG(LOG_VOODOO,LOG_WARN)("VOODOO.LFB:write raw mode %X (%d,%d) = %08X & %08X\n", LFBMODE_WRITE_FORMAT(v->reg[lfbMode].u), x, y, data, mem_mask);
@@ -2191,7 +2204,7 @@ void lfb_w(UINT32 offset, UINT32 data, U
 		bufoffs = scry * v->fbi.rowpixels + x;
 
 		/* compute dithering */
-		COMPUTE_DITHER_POINTERS(v->reg[fbzMode].u, y);
+		COMPUTE_DITHER_POINTERS_NO_DITHER_VAR(v->reg[fbzMode].u, y);
 
 		/* loop over up to two pixels */
 		for (pix = 0; mask; pix++)
@@ -2271,9 +2284,15 @@ void lfb_w(UINT32 offset, UINT32 data, U
 			if (mask & 0x0f)
 			{
 				stats_block *stats = &v->fbi.lfb_stats;
-				INT64 iterw = sw[pix] << (30-16);
+				INT64 iterw;
+				if (LFBMODE_WRITE_W_SELECT(v->reg[lfbMode].u)) {
+					iterw = (UINT32) v->reg[zaColor].u << 16;
+				} else {
+					iterw = (UINT32) sw[pix] << 16;
+				}
 				INT32 iterz = sw[pix] << 12;
 				rgb_union color;
+				rgb_union iterargb = { 0 };
 
 				/* apply clipping */
 				if (FBZMODE_ENABLE_CLIPPING(v->reg[fbzMode].u))
@@ -2291,13 +2310,55 @@ void lfb_w(UINT32 offset, UINT32 data, U
 
 				/* pixel pipeline part 1 handles depth testing and stippling */
 				// TODO: in the v->ogl case this macro doesn't really work with depth testing
-				PIXEL_PIPELINE_BEGIN(v, x, y, v->reg[fbzColorPath].u, v->reg[fbzMode].u, iterz, iterw);
+				// PIXEL_PIPELINE_BEGIN(v, x, y, v->reg[fbzColorPath].u, v->reg[fbzMode].u, iterz, iterw);
+// Start PIXEL_PIPE_BEGIN copy
+			do
+				{
+					INT32 fogdepth, biasdepth;
+					INT32 prefogr, prefogg, prefogb;
+					INT32 r, g, b, a;
+
+					(stats)->pixels_in++;
+
+					/* apply clipping */
+					/* note that for perf reasons, we assume the caller has done clipping */
+
+					/* handle stippling */
+					if (FBZMODE_ENABLE_STIPPLE(v->reg[fbzMode].u))
+					{
+						/* rotate mode */
+						if (FBZMODE_STIPPLE_PATTERN(v->reg[fbzMode].u) == 0)
+						{
+							v->reg[stipple].u = (v->reg[stipple].u << 1) | (v->reg[stipple].u >> 31);
+							if ((v->reg[stipple].u & 0x80000000) == 0)
+							{
+								goto skipdrawdepth;
+							}
+						}
+
+						/* pattern mode */
+						else
+						{
+							int stipple_index = ((y & 3) << 3) | (~x & 7);
+							if (((v->reg[stipple].u >> stipple_index) & 1) == 0)
+							{
+								goto nextpixel;
+							}
+						}
+					}
+// End PIXEL_PIPELINE_BEGIN COPY
+
+				// Depth testing value for lfb pipeline writes is directly from write data, no biasing is used
+				fogdepth = biasdepth = (UINT32) sw[pix];
 
 				color.rgb.r = sr[pix];
 				color.rgb.g = sg[pix];
 				color.rgb.b = sb[pix];
 				color.rgb.a = sa[pix];
 
+				/* Perform depth testing */
+				DEPTH_TEST(v, stats, x, v->reg[fbzMode].u);	
+
 				/* apply chroma key */
 				APPLY_CHROMAKEY(v, stats, v->reg[fbzMode].u, color);
 
@@ -2529,7 +2590,7 @@ void lfb_w(UINT32 offset, UINT32 data, U
 					} */
 				} else {
 					/* pixel pipeline part 2 handles color combine, fog, alpha, and final output */
-					PIXEL_PIPELINE_MODIFY(v, dither, dither4, x, v->reg[fbzMode].u, v->reg[fbzColorPath].u, v->reg[alphaMode].u, v->reg[fogMode].u, iterz, iterw, v->reg[zaColor]);
+					PIXEL_PIPELINE_MODIFY(v, dither, dither4, x, v->reg[fbzMode].u, v->reg[fbzColorPath].u, v->reg[alphaMode].u, v->reg[fogMode].u, iterz, iterw, iterargb);
 
 					PIXEL_PIPELINE_FINISH(v, dither_lookup, x, dest, depth, v->reg[fbzMode].u);
 				}
@@ -2639,7 +2700,7 @@ INT32 texture_w(UINT32 offset, UINT32 da
 		UINT16 *dest;
 
 		/* extract info */
-		tmunum = (offset >> 19) & 0x03;
+		// tmunum = (offset >> 19) & 0x03;
 		lod = (offset >> 15) & 0x0f;
 		tt = (offset >> 7) & 0xff;
 		ts = (offset << 1) & 0xfe;
@@ -2852,8 +2913,10 @@ UINT32 lfb_r(UINT32 offset)
 	} else {
 		/* advance pointers to the proper row */
 		bufoffs = scry * v->fbi.rowpixels + x;
-		if (bufoffs >= bufmax)
+		if (bufoffs >= bufmax){
+			LOG_MSG("LFB_R: Buffer offset out of bounds x=%i y=%i offset=%08X bufoffs=%08X\n", x, y, offset, (UINT32) bufoffs);
 			return 0xffffffff;
+		}
 
 		/* compute the data */
 		data = buffer[bufoffs + 0] | (buffer[bufoffs + 1] << 16);
@@ -3136,8 +3199,8 @@ void fastfill(voodoo_state *v)
 		/* determine the dither pattern */
 		for (y = 0; y < 4; y++)
 		{
-			DECLARE_DITHER_POINTERS;
-			COMPUTE_DITHER_POINTERS(v->reg[fbzMode].u, y);
+			DECLARE_DITHER_POINTERS_NO_DITHER_VAR;
+			COMPUTE_DITHER_POINTERS_NO_DITHER_VAR(v->reg[fbzMode].u, y);
 			for (x = 0; x < 4; x++)
 			{
 				int r = v->reg[color1].rgb.r;
</code></pre>

**Comment by joncampbell123** [comment]
Do you have a link to download the full patch? I believe github cut the patch off in the middle.

**Comment by ghoul8765** [comment]
The experimental patch is only posted here at your site. The last function in the patch is "void fastfill", at least at it appears on my web browser. It seems complete. Also, I've been running this patch for a while and haven't noticed any glaring problems.

**Comment by joncampbell123** [comment]
I'm asking because "patch" on my end complains about a truncated patch file. Could you post the patch on a download link or on pastebin?

**Comment by ghoul8765** [comment]
It's now posted at pastebin: http://pastebin.com/H8xUya3B. The problem was that the copied text from github was not preserving the correct number of spaces.

As a side note, PCem has a modified 3dfx algorithm from the one in dosbox 3dfx. However, Tom has direct3d6 working with the voodoo driver -- where text is printed to screen correctly, unlike the dosbox 3dfx emulation. I couldn't find the obvious difference between the code bases, so I thought it must be in the PCI emulation, the cpu timings, or some other inaccuracy in the cpu/fpu emulation which is not obvious; I don't think it is in the pixel pipeline (the function which prints the text to screen in d3d mode). My mere guess is that the text prints correctly in a particular frame and then the next frame distorts the text because of a shift in pixels; slowing down the emulation should show this effect.

**Comment by joncampbell123** [comment]
Hm, "patch" says the patch is incomplete when I apply it:

    bash-4.3$ patch -u -p1 <patch1.patch 
    (Stripping trailing CRs from patch; use --binary to disable.)
    patching file src/hardware/voodoo_data.h
    (Stripping trailing CRs from patch; use --binary to disable.)
    patching file src/hardware/voodoo_emu.cpp
    patch unexpectedly ends in middle of line
    Hunk #17 succeeded at 3196 with fuzz 1.

**Comment by ghoul8765** [comment]
Sorry, just append a blank line at the end of the patch file. I deleted the last line before uploading, but apparently it is necessary to the patch working.

**Comment by joncampbell123** [comment]
Got it. It works. Thanks!

**Comment by ghoul8765** [comment]
:-)

**Comment by leilei-** [comment]
Quick unrelated Q, does Mame voodoo do dac filter yet?

can't be bothered to commit downloads of arcade games i don't own to check for the existence ATM...
