### ISSUE TITLE
PC-98 and drive_fat: Unable to IMGMOUNT hard disk image with 2048 bytes per sector FAT partition

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#921]
**Describe the bug**
PC-98 DOS could format hard disk partitions with 2048 bytes/sector. Such hard disk images would not mount with IMGMOUNT at all.

**To Reproduce**
Just IMGMOUNT this HDI file.
[d2.zip](https://github.com/joncampbell123/dosbox-x/files/2564444/d2.zip)
The log would say:

> IDE: index -1 slave=0
Image file has .HDI extension, assuming HDI image and will take on parameters in header.
HDI header: sectorsize is 512 bytes/sector, header is 4096 bytes, hdd size (plus header) is 85647360 bytes
HDI: Geometry is C/H/S 1230/8/17
PC-98 IPL1 signature detected
Using IPL1 entry 0 name 'MS-DOS 6.20     ' which starts at sector 136
FAT: BPB says 17 sectors/track 8 heads 2048 bytes/sector
FAT bytes/sector value 2048 not supported
--END OF LOG--

**Expected behavior**
The first partition should be mounted in DOSBox DOS.

**Screenshots**

**Environment (please complete the following information):**
- DOSBox-X 0.82.10
- PC-98 emulation mode

**Additional context**

**Comment by joncampbell123** [comment]
I honestly didn't think anyone would use a FAT filesystem with 2048 bytes per sector, interesting.

Normally the only device to use 2048 bytes per sector is CD-ROM.

**Comment by joncampbell123** [comment]
The latest commit can now mount the HDI image provided.
