### ISSUE TITLE
PC-98: INT18h with AH=42h does not set display plane (bank)

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#926]
**Describe the bug**
INT18h with AH=42h does not set display plane (bank). Because of this bug, a title screen of Markadia, a freeware game, is not properly shown. 

**To Reproduce**
1. Run Markadia

**Screenshots**
![mkdopn_000](https://user-images.githubusercontent.com/1381939/48313839-33052400-e605-11e8-9b80-e4302336e7ff.png)

To verify the issue, I created the following simple terminate and stay resident program that set the display plane for the INT 18h with AH=42h:
![debug_000](https://user-images.githubusercontent.com/1381939/48313863-59c35a80-e605-11e8-866a-c882d1f008e1.png)
![mkdopn_001](https://user-images.githubusercontent.com/1381939/48313889-80819100-e605-11e8-8201-1a4959366a58.png)

**Comment by joncampbell123** [comment]
Try the latest commit.

**Comment by yksoft1** [comment]
This game could be downloaded from: https://www.vector.co.jp/soft/dos/game/se001354.html.

**Comment by joncampbell123** [comment]
Looks like it's working now, from the latest commit.
