### ISSUE TITLE
PC-98: BIOS interrupt vectors should use segment FD80h

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#927]
**Describe the bug**
Balloon Punch!, a freeware game, does not detect machine type properly. It supports PC-98 and Fujitsu FMR machines. It works when a machine type is specified via a command line parameter "-c4". Only the automatic machine type detection does not work.

I used a debugger and found that the program sets the machine type to PC-98 when the segment 
of INT 1Dh is FD80h. It seems that other PC-98 emulators like Neko Project use the segment FD80h for BIOS interrupts.

**To Reproduce**
1. Run Balloon Punch! without parameter "-c4"
2. It hangs up

**Expected behavior**
The game starts

**Comment by joncampbell123** [comment]
Interesting. INT 1Dh on real hardware is confirmed to point to segment FD80h. It also appears to be a single IRET instruction, so it's an interrupt that does nothing.

**Comment by joncampbell123** [comment]
The latest commit points INT 1Dh at a stub in segment FD80, does that satisfy the game?

**Comment by joncampbell123** [comment]
Are there any other interrupt vectors that games expect to point to segment FD80?

**Comment by hdk1983** [comment]
Balloon Punch! only checks the INT 1Dh. Now it works.
Detecting machine type based on interrupt vector may fail if the interrupt vector has been modified by other programs, like TSRs, so I guess that the game checks INT 1Dh which is normally not used i.e normally TSRs do not modify the vector of INT 1Dh. I have no idea about other games or applications that check such vectors.
