### ISSUE TITLE
PC-98: GDC command 0xe0 is needed by MS-BASIC programs

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#928]
**Describe the bug**
Applications generated by Microsoft Basic compiler apparently issues GDC command 0xe0 to get cursor position. Currently it is not implemented, so message "LOG: GDC: master: Unknown command 0xe0" is printed repeatedly and such applications do not start.

**To Reproduce**
1. Run an application generated by Microsoft Basic compiler
2. The application does not start
3. See error "LOG: GDC: master: Unknown command 0xe0"

**Expected behavior**
The application starts

**Additional context**
I created a hello world application that prints a message and cursor position for debugging. It is a standalone binary generated by Visual Basic compiler:
[HELLO.zip](https://github.com/joncampbell123/dosbox-x/files/2571975/HELLO.zip)

I created a dirty patch to verify that implementing the GDC command 0xe0 fixes the issue:
[cmde0patch.txt](https://github.com/joncampbell123/dosbox-x/files/2571981/cmde0patch.txt)
My patch is dirty. I think it should add a method instead of modifying fifo buffer directly. I am not sure that my patch is correct about GDC behavior.

**Comment by joncampbell123** [comment]
http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20NEC%20PC%2d98/Video/NEC%20High%2dPerformance%20Graphics%20Display%20Controller%207220/%c2%b5PD7220%2c%20%c2%b5PD7220%2d1%2c%20%c2%b5PD7220%2d2%20Graphics%20Display%20Controller%2epdf

According to this datasheet, 5 bytes are returned. The last 2 are related to graphics.

**Comment by joncampbell123** [comment]
The latest commit adds a method to write the return FIFO and adds command 0xE0

**Comment by hdk1983** [comment]
It is fixed now. Thanks.
