### ISSUE TITLE
Documentation needed: Pulse/Reve 1995 demo can exit early if minimum mcb segment too low

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#93]
I find it strange that the demo crashes to DOS midway through when memsize=8, and very near the end when memsize=16, when the demo was written late 1995 at a time when the average PC was a 486 or Pentium with 8MB to 16MB of RAM. Is the demo intended to use paging of some kind, that DOSBox isn't running correctly? Meaning that it doesn't matter to me that you can fix the issue by setting memsize=32, if the demo required that much RAM to run it probably would've failed on the democompo computer that way.

**Comment by ghoul8765** [comment]
Tested with core=dynamic/memsize=8 (xms=ems=umb=true) and this demo played to end (no crash).  Did you run "REVE.EXE DPMI"?

**Comment by joncampbell123** [comment]
I will try that. I ran it with ems=false and xms=true.

**Comment by joncampbell123** [comment]
What is the core= setting in your dosbox.conf?

**Comment by joncampbell123** [comment]
A-ha: Setting "minimum mcb segment" to a higher value resolves the crashiness and I am able to run it in 8MB of RAM.

**Comment by ghoul8765** [comment]
Sorry for the delay. I'm glad that you easily determined the cause. I am running core=dynamic and would have suggested to revert to the vanilla dosbox memory setup, although I would not have known that was the only possibility!
