### ISSUE TITLE
PC-98: Graphic LIO not implemented

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#930]
**Describe the bug**
Graphic LIO is a set of routines in BIOS ROM.  I found it was used by the following games/applications:

- KATALITH
- MAZE_999 https://www.vector.co.jp/soft/dos/game/se023680.html
- Microsoft Basic programs that use graphics (probably MAZE_999 is built on Microsoft Basic)

Graphic LIO is in segment F990h.  If you see some errors around in segment F990h, probably it is related to this issue.  For example:

- KATALITH: ERROR CPU:Write 0 to rom at f9900
- MAZE_999: ERROR CPU:Write 20 to rom at f9900

**To Reproduce**
1. Run a program that uses graphic LIO
2. The program does not start

**Expected behavior**
The program works

**Additional context**
To verify the graphic LIO is used, I added a dummy implementation to DOSBox-X as follows:

[dummyliopatch.txt](https://github.com/joncampbell123/dosbox-x/files/2576252/dummyliopatch.txt)

With this patch, KATALITH shows the following copyright screen:

![katalith_000](https://user-images.githubusercontent.com/1381939/48414108-1ac01100-e78d-11e8-949f-f04b5e411b2e.png)

And, MAZE_999 shows the following error (maybe because of the dummy implementation), looks like an error of Microsoft Basic:

![game_999_000](https://user-images.githubusercontent.com/1381939/48414129-26133c80-e78d-11e8-8169-279670ea7cec.png)

I made a hello world program using MSGBOX statement of Visual Basic for DOS:

[HELLO2.zip](https://github.com/joncampbell123/dosbox-x/files/2576255/HELLO2.zip)

With the above patch, this program starts with broken graphic screen (maybe because of the dummy implementation):

![hello2_000](https://user-images.githubusercontent.com/1381939/48414149-388d7600-e78d-11e8-8e2b-82f021da9f0c.png)

The hello world works on Neko Project:

![hello2_np21w](https://user-images.githubusercontent.com/1381939/48414320-b81b4500-e78d-11e8-9adc-086fefcf3bb9.png)

**Comment by joncampbell123** [comment]
Actually, yes, I noticed "Sword of Legend" is quite consistent at jumping to segment F990, evidently without checking properly.

**Comment by joncampbell123** [comment]
If anyone has a PDF or link to documentation on the LIO interface that would be helpful.

The source code of Neko Project II appears to explicitly implement the LIO interface in bios_lio()

**Comment by joncampbell123** [comment]
Hm, "Sword of Legend" doesn't seem to really be looking for LIO.

**Comment by hdk1983** [comment]
I found Japanese documentation describing the graphic LIO on the web:

- http://chiclassiccomp.org/docs/index.php?dir=%2Fbooks%2FComputing%2FProgramming&highlight=PC-9801Bible_%E6%9D%B1%E4%BA%AC%E7%90%86%E7%A7%91%E5%A4%A7%E5%AD%A6.pdf (Page 184-)
- https://archive.org/details/PC9800TechnicalDataBookBIOS1992/page/n151
- https://archive.org/details/98HardBookBecomingStrongII1988 (Page 181-)

**Comment by yksoft1** [comment]
> Hm, "Sword of Legend" doesn't seem to really be looking for LIO.
> 
> EDIT: It does, it crashed because my initial implementation had a mistake.
> 
> EDIT: This is apparently why WINGS also crashed at startup. Now it just sits with a blank screen with debug output indicating that LIO was called.
> 
> EDIT: This is also why Balance of Power was crashing. Now it runs, minus many graphics of course.

Hell Ogre also require it to work.

**Comment by hdk1983** [comment]
Fixed by #3508. Thanks.
