### ISSUE TITLE
PC-98 Hell Ogre MUSIC driver points INT D2h at segment CEE0 and jumps there (FM SOUND ROM BIOS)

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#931]
**Describe the bug**
PC-98 Hell Ogre MUSIC driver points INT D2h at segment CEE0 and jumps there

**To Reproduce**
1. Run Hell Ogre !GAME.BAT
2. Observe a crash, nothing at CEE0:xxxx
3. Try again, just running MUSIC, and observe the same crash

**Expected behavior**
??? I'm not sure what is supposed to exist there.

    0316:00000147 BBE0CE              mov  bx,CEE0
    0316:0000014A 8EDB                mov  ds,bx
    0316:0000014C 8B160600            mov  dx,[0006]              ds:[0006]=0000
    0316:00000150 B8D225              mov  ax,25D2
    0316:00000153 CD21                int  21
    0316:00000155 0E                  push cs

...

    0316:00000185 32E4                xor  ah,ah
    0316:00000187 CDD2                int  D2

**Comment by yksoft1** [comment]
INT D2h is the sound BIOS of FM boards.

http://www.webtech.co.jp/company/doc/undocumented_mem/memsys.txt

> メモリ	0000:05E0～05E3h
型	DWORD
名前	MUSIC_WORK
分類	SOUND
対象	PC-9801-14, PC-9801-26初代･K, PC-9801-73･86
	(上記ボード相当の内蔵型含む)搭載ROM BIOS
内容	ミュージックBIOS／サウンドBIOS用ワークエリアの開始アドレス
解説  o ミュージックBIOS(PC-9801-14 ミュージックジェネレータボード搭載
	ROM BIOS)、サウンドBIOS(PC-9801-26初代･K, PC-9801-73･86 サウンド
	ボード搭載ROM BIOS)のワークエリアの開始アドレスを格納する。
      u PC-98XAが搭載するBIOS ROM内のミュージックBIOSでは、0000:05E0h(WORD)に
	ワークエリアのセグメントが格納される。そのほかのハイレゾ機では、
	ミュージックBIOSはサポートしていない(サウンドBIOSはどのハイレゾ機も
	サポートしていない)。
関連	INT D2h
	I/O 008Eh
	I/O 0188h

**Comment by yksoft1** [comment]
You could see if soundrom.name[0] is 0 to determine if sound ROM is loaded.
src/hardware/snd_pc98/sound/soundrom.c
`void soundrom_load(UINT32 address, const OEMCHAR *primary) {

	if (primary != NULL) {
		if (loadsoundrom(address, primary) == SUCCESS) {
			return;
		}
	}
	if (loadsoundrom(address, NULL) == SUCCESS) {
		return;
	}
	CopyMemory(mem + address + 0x2e00, defsoundrom, sizeof(defsoundrom));
	soundrom.name[0] = '\0';
	soundrom.address = address;
}`

**Comment by yksoft1** [comment]
By the way,  this game requires not only sound BIOS, but Graphics LIO.

**Comment by joncampbell123** [comment]
This is good information to have here, thank you.

I'm not certain where to find the sound ROM image.

Until then, it might help to put a stub interrupt routine and table in segment CEE0. The game appears to copy and load the interrupt vector the same way the LIO library is called. Notice the code posted reads the offset from CEE0:0006 as the interrupt vector offset.

**Comment by joncampbell123** [comment]
Perhaps it would be more realistic not to put a dummy INT D2h handler if the PC-98 sound BIOS is not enabled.

**Comment by joncampbell123** [comment]
I have a stub for INT D2h implemented at CEE0:0000.

Hopefully it (and the LIO stub) should serve as a starting point for implementing these BIOS calls.

**Comment by joncampbell123** [comment]
I forgot to update this issue when some commits back I did add loading SOUND.ROM.
