### ISSUE TITLE
HDI images with 256 bytes/sector claimed in header not BOOTing

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#933]
**Describe the bug**
I found an HDI image with 256 bytes/sector claimed in HDI header but with 1024 bytes/sector claimed in FAT BPB. I verified that it contains normal NEC IPL and boots in other PC-98 emulators, but can't boot in DOSBox-X.

**To Reproduce**
Just IMGMOUNT and BOOT this HDI file.
[ed4.zip](https://github.com/joncampbell123/dosbox-x/files/2588208/ed4.zip)
The log said:

> IDE: index -1 slave=0
Image file has .HDI extension, assuming HDI image and will take on parameters in header.
HDI header: sectorsize is 256 bytes/sector, header is 4096 bytes, hdd size (plus header) is 10475520 bytes
HDI: Geometry is C/H/S 310/4/33
Possibly invalid partition table in disk image.
PC-98 IPL1 signature detected
Using IPL1 entry 0 name 'MS-DOS 6.20     ' which starts at sector 132
FAT: BPB says 33 sectors/track 4 heads 1024 bytes/sector
Disk indicates 256 bytes/sector, FAT filesystem indicates 1024 bytes/sector. Ratio=4:1 shift=2
Using logical sector size 1024
Mounted FAT volume is FAT12 with 2466 clusters
First sector is 256 byte/sector. Booting from first two sectors.
Booting guest OS stack_seg=0x0030 load_seg=0x1fc0
PC-98 INT 18 AH=42h CH=0x80
Removing UMB block 0xd000-0xdfff
Alright: DOS kernel shutdown, booting a guest OS

**Expected behavior**
DOS should boot correctly from it.

**Environment (please complete the following information):**
 - DOSBox-X latest commit
 - PC-98 mode

**Additional context**

**Comment by joncampbell123** [comment]
I'll look at the image. Please verify the system files needed to boot are there (IO.SYS, etc.)

**Comment by joncampbell123** [comment]
By the way, you're mounting the image in a way that triggers the FAT filesystem driver before booting.

Use -fs none to avoid that.

**Comment by joncampbell123** [comment]
I see the problem. Drive 'C' check needs to come first in src/dos/dos_programs.cpp before the 256-byte/sector PC-98 check for odd boot disks.

**Comment by joncampbell123** [comment]
Notice the wrong drive identifier is written to memory location 0x584, which is used by DOS to identify the boot device.

**Comment by joncampbell123** [comment]
I noticed this same issue with another game, "Sorcerer's Kingdom", which the latest commit makes possible to boot. Pull the latest commit. I will be testing your image and one more game that also hit this bug.

**Comment by yksoft1** [comment]
It's now booting at my side. I think the wrong boot type  should be the only problem for this issue.
