### ISSUE TITLE
PC-98: Mouse interrupt must be generated periodically

### ISSUE THREAD

**Issue by hdk1983** [joncampbell123/dosbox-x#934]
**Describe the bug**
The PC-98 mouse interrupt is a simple periodic interrupt, not an event notification. However currently it seems to be generated on mouse events only.

Maybe related to #932 discussion.  FMDSP https://www.vector.co.jp/soft/dos/art/se022227.html is the one that required moving the mouse constantly to advance on DOSBox-X. I found a "OUT 64H,AL" instruction that makes the next vsync interrupt at head of mouse interrupt handler of the program, so periodic mouse interrupt may resolve the problem.

**To Reproduce**
I created a simple terminate and stay resident program that counts 120Hz mouse interrupts and print it in hexadecimal to the text VRAM.
[mouseint.zip](https://github.com/joncampbell123/dosbox-x/files/2589327/mouseint.zip)

1. Run my mouseint.com program
2. Move mouse
3. See the first line of the screen
4. The count changes only when mouse is moved

**Expected behavior**
The count is displayed as:
11.22
The 11 part is the number of mouse interrupts divided by 120.
The 22 part is the remainder.
The 11 part must be incremented per second.
I tested this behavior on Neko Project and T98-Next.

**Comment by joncampbell123** [comment]
Perfect! This makes it clear how mouse interrupts should work. Thanks, I will implement.

**Comment by yksoft1** [comment]
So joncampbell123's find on Metal Force and Amaranth is right?
However, not every PC-98 had bus mouse support on board and we need to also emulate what will happen with mouse support disabled.

**Comment by joncampbell123** [comment]
When I first added mouse emulation, I assumed it worked like the mouse interrupt on IBM PC/AT systems where no interrupt occurs unless the mouse has data to send, which only happens if the mouse is moved or buttons are clicked.

If I understand this correctly, enabling the interrupt on PC-98 means an interrupt every 120Hz whether or not any mouse events happened, correct?

**Comment by hdk1983** [comment]
> If I understand this correctly, enabling the interrupt on PC-98 means an interrupt every 120Hz whether or not any mouse events happened, correct? I will implement this now.

Right. The interrupt frequency is set via port BFDBh.

**Comment by joncampbell123** [comment]
Just finished the periodic interrupt generation, latest commit.

**Comment by joncampbell123** [comment]
Port BFDB implemented, latest commit.

**Comment by joncampbell123** [comment]
Mouse input works in all test cases I'm aware of. Interrupt is periodic now when enabled.

Please confirm the same on your end. Please use the latest commit to master.

**Comment by hdk1983** [comment]
![fmdsp_000](https://user-images.githubusercontent.com/1381939/48651819-f0e24500-ea3f-11e8-854a-4528bab7b537.png)

Now FMDSP works properly. Thanks.
