### ISSUE TITLE
PC-98: Numeric keypad not working in Tetris menu screen

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#941]
**Describe the bug**
On the menu screen of Tetris,
![tetris_000](https://user-images.githubusercontent.com/37106774/48760105-04134000-ece0-11e8-9d18-2284c51c3ae1.png)

The menu won't respond to numeric keypad at all, but will respond to 8, 2, 4, 6 keys on the main keyboard.
In other emulators, the menu would respond to numeric keypad.
After entering game screen, numeric keypad worked.

**Comment by joncampbell123** [comment]
I was curious about that too. Some games seem to require using the top numeric row as if the numeric keypad but won't respond to the numeric keypad.

I'll check mem_sys.txt right now. Is there some DOS/BIOS flag that if set, remaps numeric keypad for older DOS games?

**Comment by joncampbell123** [comment]
Try the latest commit. It was the BIOS keyboard handler's fault for not returning ASCII characters for numeric keypad input.

**Comment by joncampbell123** [comment]
Reopen this issue if it does not solve the issue, which is unlikely as far as I know.
