### ISSUE TITLE
Problem with upercase diacritical letters with CAPS LOCK

### ISSUE THREAD

**Issue by Codythejack** [joncampbell123/dosbox-x#942]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Operating system
 - DOSBox-X release version or commit SHA1 this issue occurred on
 - Used configuration, e.g. ```dosbox.conf```

**Additional context**

**Comment by joncampbell123** [comment]
I'm going to close this because this issue looks like it was entered by mistake, the second one #943 is better to keep open for the issue.
