### ISSUE TITLE
config file is incomplete.

### ISSUE THREAD

**Issue by startmenu** [joncampbell123/dosbox-x#95]
Config file created by config command isn't complete.  What's more, there is no config file sample available in the tarball.

**Comment by startmenu** [comment]
![snapshot9](https://cloud.githubusercontent.com/assets/3387747/8087018/23422b4e-0fcb-11e5-8347-e40af68a9bf6.png)

config file created by "config -writeconf".

**Comment by joncampbell123** [comment]
You need to use config -all -writeconf.

And I need to add text to the default mode of dosbox.conf that mentions it.

**Comment by joncampbell123** [comment]
The config command mentions -all and the dosbox.conf file written mentions how to get all options.
