### ISSUE TITLE
C_DEBUG 0 in config.h causes build failure in VS2017

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#950]
**Describe the bug**
In current code (as of Nov 29, anyway), building fails in VS2017 if C_DEBUG is set to 0 in config.h. The error message is:

bios.obj : error LNK2001: unresolved external symbol "void __cdecl DEBUG_StopLog(void)" (?DEBUG_StopLog@@YAXXZ)
10>F:\Users\Edward\Desktop\dosbox-x-29Nov\vs2015\..\bin\Win32\Release\/dosbox-x.exe : fatal error LNK1120: 1 unresolved externals
10>Done building project "dosbox-x.vcxproj" -- FAILED.

In order to build, I also had to add paths for three files (one in SDL_NET, two in DOSBox-X) to the Properties panels; I don't know if there's any way to automate this, or whether it's special to my setup.

**To Reproduce**
1. Edit config.h to change C_DEBUG from 1 to 0
2. Build
3. Get error message shown above

**Expected behavior**
Successful build.

**Environment (please complete the following information):**
 - Operating system: Win10 32-bit
 - DOSBox-X download code as of 29 Nov 2018

**NOTE: An easy fix (but probably not the best one) is to edit bios.cpp and add #if C_DEBUG below line 5609 and then add an #endif immediately above the the existing #endif five lines afterward.

**Comment by joncampbell123** [comment]
Better yet, it would help to have a core header file (like dosbox.h) throw an error if C_HEAVY_DEBUG is defined without C_DEBUG.

**Comment by emendelson** [comment]
Sounds good. Will close this.
