### ISSUE TITLE
Build SDL2 version under Visual Studio 2017 (how-to)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#962]
I was able to build the SDL2 version of current code under Visual Studio but needed to take some additional steps first. Here they are. If I've got something wrong, please tell me - and I hope that the build procedure under VS2017 can be changed to avoid all this, though it's only a mild annoyance.

1. Change the properties of the two SDL2 Libraries (SDL2 and SDL2main) so that the Platform Toolset is Visual Studio 2017 (v. 141)

2. Don't try to build dosbox-x yet. First build the two SDL2 libraries.

3. Create this folder:

**dosbox-x-master\obj\SDL2\Win32\Release SDL2**

and copy into that new folder the file **SDL2.lib** from the **vs2015\Win32\Release** folder

4. Create this folder:

**dosbox-x-master\obj\SDL2main\Win32\Release SDL2**

and copy into that new folder the file **SDL2main.lib** from the **vs2015\Win32\Release** folder

5. Build dosbox-x using the Release SDL2 configuration.

6. Find **dosbox-x.exe** in the **dosbox-x-master\bin\Win32\Release SDL2** folder but don't run it yet.

7. Find the **SDL2.dll** file in **dosbox-x-master\vs2015\Win32\Release**, and copy it into the same folder named in step 6, so that it is in the same folder with dosbox-x.exe

8. Now launch dosbox-x.exe.

**Comment by joncampbell123** [comment]
I just fixed the SDL2 library in-tree to compile properly again with VS2017.
