### ISSUE TITLE
Close configuration menu shuts down dosbox-x (macOS)

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#973]
**Describe the bug**
In current SDL1 code, compiled in macOS High Sierra, closing the configuration menu shuts down dosbox-x.

**To Reproduce**
Run dosbox-x.
On the top-line menu, click Main, Configuration GUI
In the Configuration GUI, click Close

**Expected behavior**
The Configuration GUI menu should close, but dosbox-x should remain open.

**Environment (please complete the following information):**
macOS High Sierra
DOSBox-X built from code at commit  a7853f4

**Comment by joncampbell123** [comment]
I'm not able to reproduce this on Mojave.

Could you run DOSBox-X from the Terminal app and report what appears on the terminal?

**Comment by joncampbell123** [comment]
In fact... does DOSBox-X unexpectedly shut down in other transitions, such as going to/from the mapper interface?

**Comment by emendelson** [comment]
Yes, it unexpectedly when I'm in the mapper interface and click Exit. The end of the report in the terminal is this:

LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x01e9 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x0217 sz=0x009a
LOG: COMMAND.COM stack:                0x0231
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
LOG: Screen report: Method 'None' (-1.000 x -1.000 pixels) (-1.000 x -1.000 mm) (-0.039 x -0.039 in) (-1.000 x -1.000 DPI)
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
Segmentation fault: 11

**Comment by joncampbell123** [comment]
I'm not able to reproduce that issue. Perhaps it was fixed since the time this bug was filed?

**Comment by emendelson** [comment]
Seems to be fixed!
