### ISSUE TITLE
SDL2 builds: fullresolution=original causes endless loop

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#982]
**Save your work before testing this!! You may need to power down your machine by holding down the power button!! You will not be able to close any open programs or save files!!**

**Describe the bug**
Current SDL2 code built in Windows 10 and macOS High Sierra, with [sdl] fullresolution=original causes an endless loop when host+f is pressed for full-screen toggle. The dosbox-x window goes to full-screen, then back to windowed mode, then back to full-screen, then back to windowed mode - and the only way I can get out is by holding down the Power button until the machine switches off.

**To Reproduce**
In High Sierra (maybe in other OS versions) build-macosx-sdl2; or in Windows 10 with VS2017, build Release SDL2
Launch dosbox-x with a conf file containing the lines [sdl] and fullresolution=original
Be prepared to shut down your machine by holding down the power button

**Again: save your work before testing this, because you will probably need to power down your machine without getting a chance to save anything.**

**Comment by emendelson** [comment]
In Windows 10, you can avoid powering down by doing this:

Press Ctrl-Alt-Del; then press Tab twice (?) to get to the Sign Out button. Press Enter.

I don't know an equivalent in macOS...

**Comment by joncampbell123** [comment]
I am developing from an SSH connection to the Macbook. I can CTRL+Z to stop it and then killall -KILL dosbox-x to terminate it.

**Comment by emendelson** [comment]
With a lot of trial and error, I was able to use Cmd-Opt-Esc to bring up the Force Quit dialog, and, after a few tries, I got DOSBox-X to quit. It left the dock invisible (probably because I killed DOSBox-X when it was in full-screen mode), but the terminal command "killall Dock" got it back....

**Comment by joncampbell123** [comment]
Found it.

One of the contributers to DOSBox-X awhile back cleaned up the output code into the src/output directory. It seems the SDL2 surface code had two mistakes that happened in the fullresolution=original case. One was that it had a retry label, and it would "goto retry" after setting the mode. The other was calling the GFX code to set fullscreen mode but then immediately call SDL to set the window fullscreen state back to windowed.

**Comment by joncampbell123** [comment]
On top of that, whenever SDL2 "restores" the window from fullscreen, it sends a "restored" and "resize" event which in DOSBox-X triggers a call to GFX to re-initialize the screen, which goes to set the mode back to fullscreen... etc. etc.

**Comment by joncampbell123** [comment]
Seems fixed on my end.
