### ISSUE TITLE
Detect SDL2 build from DOSBox-X command line or other test?

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#985]
Is there a way to run a "config -get" or similar command to detect whether SDL1 or SDL2 is being used? Or am I missing something obvious?

And could there (someday) be a command that could be run at the bash or Windows command line to detect the SDL version in use?

**Comment by joncampbell123** [comment]
There's no such feature. Nor for that matter does anything differ in what it shows of the text at startup.

**Comment by emendelson** [comment]
This trivial patch (trivial to anyone who knows how to do it; not trivial to me) adds the SDL major version to the Welcome to DOSBox-X message and to the output of the VER command:

https://github.com/emendelson/dosbox-x/commit/91648cc12e53db09a28112b4b130a2d5b18dba59

**Comment by emendelson** [comment]
And this second patch adds the SDL version to the dosbox-x --version output so it can be tested before launching DOSBox-X:

https://github.com/emendelson/dosbox-x/commit/6d01d6ec66d0d0f4cfbbc485cfb108678c2883f3

**Comment by emendelson** [comment]
And you made a further addition to the help... Thank you.
