### ISSUE TITLE
VS2017 SDL1 build doesn't remember window position after full-screen

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#987]
Building current code in VS2017, all default settings.

Launch DOSBox-X, press host+F to toggle full-screen, press host+F to return to windowed mode.

After the second host+F, the window snaps to the upper left corner of the desktop, not its current position.

This works correctly when building in macOS, but not in VS2017, oddly enough.

**Comment by joncampbell123** [comment]
I had not yet modified the Windows SDL1 code to do it. Now it does. Fixed.

**Comment by emendelson** [comment]
Could this be reopened? It still isn't fixed when I build current code in VS2017 in 32-bit Windows 10. Is it possible that my two-monitor setup is affecting this? It doesn't matter which monitor I start DOSBox-X in, or which monitor it's in when I switch to full-screen - it always switches back to the upper left corner of the left-hand monitor.

BEFORE:
![before](https://user-images.githubusercontent.com/5208505/50604440-f5967780-0e8c-11e9-9280-03f6e69b43db.PNG)
AFTER:
![after](https://user-images.githubusercontent.com/5208505/50604444-fa5b2b80-0e8c-11e9-8623-03fe9209ab51.PNG)

**Comment by joncampbell123** [comment]
Are you sure you pulled the latest commit and did the build recompile SDL?

The code so far has only been tested on single-monitor setups.

**Comment by joncampbell123** [comment]
However multi-monitor shouldn't matter since Windows presents the classic API with effectively a giant virtual desktop made up of all screens.

**Comment by emendelson** [comment]
You're right - it's fixed. User-incompetence on my part. When I downloaded a fresh ZIP of the current code, and built everything, It works correctly. Apologies for wasting bandwidth!
