### ISSUE TITLE
Add possibility to change current time

### ISSUE THREAD

**Issue by mariobrx** [joncampbell123/dosbox-x#989]
The clock in DOSBox-x is not automatically synchronised with the host system. After 24 hours I get about 6 minutes behind normal time.

Ideal situation would be that the clock in Dosbox-x is synchronised with the host system, but I guess this would be almost impossible to implement. 

As an alternative solution, I propose to add a feature that allows to change TIME, the same way you can change the DATE.

PS: the reason I use DosBox-x instead of Dosbox is just the fact that IRQ21 is better implemented.

**Comment by joncampbell123** [comment]
It depends on the API used to get time. DOSBox-X inherits DOSBox SVN's code to read the local clock through the RTC and DOS APIs.

Which IRQ did you mean? There's no IRQ21 in the classic DOS system architecture (though there probably is on later APIC-based systems).

**Comment by mariobrx** [comment]
In the original implementation of Dosbox, the time started running and continued after midnight, without changing the date. Result: the next morning  at 8:10 it showed 32:10 and the date indicates yesterday. The Dosbox-x implementation corrected this situation and allowed even to change the date in the console. So when you type DATE, it shows:
_

> current date: Mon 01/07/2019
> Type 'date MM-DD-YYYY' to change

_
It would be interesting to have similar possibility with TIME. Now it just displays current time but you cannot change it:
_

> Current time: 20:28:00,07

_

About the API: I'm using a "VisualBasic for DOS" program, it uses the same API as what the TIME command in DOS is using. The instructions used in VisualBasic are TIMER and TIME$ and they give exactly the same result as the TIME command in DOS. 
Currently, my program tries to adapt the clock at midnight, but it fails because the feature doesn't exist.

I've added all possible logging and found this in the logfile:
_

> ERROR DOSMISC:DOS:Set System Time not supported

_
It seems to be part of the DOS_21Handler (DOS.CPP) in line 981.

**Comment by joncampbell123** [comment]
Ah, I see. It could be added in the future.

You mean INT21, not IRQ21.

**Comment by mariobrx** [comment]
Yes, sorry: mixed abbreviation from previous experiences...

**Comment by Wengier** [comment]
I have made a patch that allows you to change DOSBox-X's internal time either by the built-in TIME command or the INT21 function. More information about the patch is available from Issue #1474.
