### ISSUE TITLE
Massive flickering/redraw problems with Corncob 3D game

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/dosbox-x#992]
**Describe the bug**
Corncob 3D is redrawing the screen while displaying, causing a lot of flickering.

**To Reproduce**
1. Run Corncob 3D
2. Create pilot, open mission, etc.
3. Start mission
4. Notice the EGA graphics flicker a lot

**Expected behavior**
Graphics to move and render without flickering.

I remember finding Corncob 3D on a shareware compilation CD back in the day, and running it on my 33MHz 386 (with a Tseng ET4000 card). I don't recall flickering problems on that setup.

This bug also affects DOSBox SVN.

**Comment by joncampbell123** [comment]
Adding a video memory delay solves the flickering problem, except for the instruments.

A video memory delay of at least 500ns (recommended 800ns) solves the flicker problem.

**Comment by joncampbell123** [comment]
This comment is a reminder to myself to run Corncob 3D on a a 386, 486, and Pentium class system to determine what happens on real hardware.

**Comment by steelstring94** [comment]
The vmemdelay fix doesn't work for me. No matter what value I set it to, there is no discernible effect.
