### ISSUE TITLE
Textmode 132x43 double height bug

### ISSUE THREAD

**Issue by Pantalaim0n** [joncampbell123/dosbox-x#996]
**Describe the bug**
When changing the textmode to 132x43, it actually becomes 132x86, with only the top half on-screen. Other extended text modes like 132x25, 132x50 and 132x60 are unaffected.

**To Reproduce**
1. Invoke 132x43 textmode
**AX = 4F02h**
**BX = 10Ah**
**Int 10h**

2. Generate output past the 43rd line, scrolling *should* occur, but output continues off-screen.

3. Scrolling does occur when output runs past the 86th line

Also, checking memory address 0040h:0084h (rows on screen minus one) returns 85 instead of expected 42.

**Expected behavior**
Textmode 132x43 should in fact have 43 lines.

**Environment (please complete the following information):**
 - Windows 10 64-bit
 - DOSBox-X release 0.82.14
 - Default configuration

**Comment by joncampbell123** [comment]
It looks like a mistake in the modelist for mode 0x10A.

Funny enough DOSBox SVN seems to have the same mistake.

**Comment by joncampbell123** [comment]
The latest commit tweaks mode 0x10A to have vertical timing parameters similar to 1024x768 mode, and changes the character cell to 8x16 to match. Can you compile from source?

**Comment by Pantalaim0n** [comment]
That did the trick. Thanks!
