### ISSUE TITLE
Input underscore key on PC98

### ISSUE THREAD

**Issue by tomyun** [joncampbell123/dosbox-x#997]
While playing with PC98 machine on Doxbox-X 0.82.14, I can't find a way to input underscore (`_`) key with my English layout keyboard on macOS. I fiddled with key mapper, for example, mapping `ro` key to something and pressing it with `shift` in hope to get `_`, but no luck yet. Does anyone know a good way to accomplish this?

**Comment by joncampbell123** [comment]
I'll pull out the PC-98 system and confirm what the RO key actually does.

There's no case statement for code 0x33 (_ / RO) in src/ints/bios_keyboard.cpp right now which is obviously part of the issue.

**Comment by joncampbell123** [comment]
Re-testing the PC-98 BIOS handling of the keyboard, it seems Ro by itself does not emit any keystroke. Shift+Ro however types an underscore. It seems Ctrl+Ro also emits a BIOS scancode.

I will update DOSBox-X to match this behavior.

**Comment by joncampbell123** [comment]
You should be able to bind Ro to a key and type an underscore with Shift+Ro now in the latest commit (if you can compile from source)
